DECLARE
BEGIN
  FOR rec IN (
    SELECT 
      BASE.CODUSUR,
      BASE.CODSUPERVISOR,
      BASE.NUMTRANSITEM,
      BASE.NUMTRANS,
      BASE.TIPO_NUMTRANS
    FROM (
      SELECT 
        PED.CODUSUR,
        PED.CODSUPERVISOR,
        MOV.NUMTRANSITEM,
        CASE
          WHEN MOV.NUMTRANSVENDA IS NOT NULL THEN MOV.NUMTRANSVENDA
          WHEN MOV.NUMTRANSENT IS NOT NULL THEN MOV.NUMTRANSENT
        END NUMTRANS,
        CASE
          WHEN MOV.NUMTRANSVENDA IS NOT NULL THEN 'V'
          WHEN MOV.NUMTRANSENT IS NOT NULL THEN 'E'
        END TIPO_NUMTRANS    
      FROM PCMOV MOV
      LEFT JOIN PCPEDC PED ON PED.NUMPED = MOV.NUMPED  
      WHERE MOV.NUMPED > 0
        AND MOV.ROTINALANC LIKE '%PCSIS328%'
        AND (MOV.NUMTRANSVENDA IS NOT NULL OR MOV.NUMTRANSENT IS NOT NULL)
    ) BASE
  ) LOOP

    IF rec.TIPO_NUMTRANS = 'V' THEN

      UPDATE PCNFSAID SET 
        CODUSUR = rec.CODUSUR,
        CODSUPERVISOR = rec.CODSUPERVISOR
      WHERE NUMTRANSVENDA = rec.NUMTRANS
        AND (
             (NVL(CODUSUR, -1) <> NVL(rec.CODUSUR, -1)) OR 
             (NVL(CODSUPERVISOR, -1) <> NVL(rec.CODSUPERVISOR, -1))
        );
        
      UPDATE PCESTCOM SET
        CODUSUR = rec.CODUSUR
      WHERE NUMTRANSVENDA = rec.NUMTRANS
        AND (NVL(CODUSUR, -1) <> NVL(rec.CODUSUR, -1));
        
      UPDATE PCMOV SET
        CODUSUR = rec.CODUSUR
      WHERE NUMTRANSITEM = rec.NUMTRANSITEM
        AND (NVL(CODUSUR, -1) <> NVL(rec.CODUSUR, -1));
        
      UPDATE PCMOVCOMPLE SET
        CODSUPERVISOR = rec.CODSUPERVISOR
      WHERE NUMTRANSITEM = rec.NUMTRANSITEM
        AND (NVL(CODSUPERVISOR, -1) <> NVL(rec.CODSUPERVISOR, -1));

    ELSIF rec.TIPO_NUMTRANS = 'E' THEN
    
      UPDATE PCNFENT SET
        PCNFENT.CODUSURDEVOL = rec.CODUSUR
      WHERE NUMTRANSENT = rec.NUMTRANS
        AND (NVL(CODUSURDEVOL, -1) <> NVL(rec.CODUSUR, -1));
        
      UPDATE PCESTCOM SET
        CODUSUR = rec.CODUSUR
      WHERE NUMTRANSENT = rec.NUMTRANS
        AND (NVL(CODUSUR, -1) <> NVL(rec.CODUSUR, -1));

    END IF;

  END LOOP;

  COMMIT;
END;