CREATE OR REPLACE VIEW VW_INT_C5_DIVISAO AS
(
SELECT TO_CHAR(R.NUMREGIAO) NUMREGIAO,
       TO_CHAR(D.NRODIVISAO) NRODIVISAO,
       SUBSTR(R.REGIAO, 1, 20) DIVISAO,
       'V' TIPO,
       (CASE
           WHEN NVL(R.STATUS, 'A') = 'A' THEN
                'S'
           ELSE 'N'
        END) ATIVO,
        R.NUMREGIAO||R.UF IDREF
FROM PCREGIAO R,
     PCDEPARAREGIAOC5 D,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO') DTPADRAO
 WHERE R.NUMREGIAO = D.NUMREGIAO(+)
 AND   NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
 AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'

UNION ALL

SELECT  F.CODIGO  NUMREGIAO,
        F.CODIGO  NRODIVISAO,
        'DIVISAO TRIBUTACAO POR UF' DIVISAO,
        'V' TIPO,
        (CASE
            WHEN F.dtexclusao IS NULL
                THEN 'S'
            ELSE
          'N'
        END) ATIVO,
        F.UF IDREF
FROM PCFILIAL F,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO'
     ) DTPADRAO,
     VW_INT_C5_OBTER_FILIAIS_C5 c5
WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
AND F.codigo <>'99'
AND F.codigo = c5.codfilial
AND NVL(F.Dtalterc5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
 
)
