CREATE OR REPLACE VIEW VW_INT_C5_DIVISAO AS
(
SELECT R.NUMREGIAO,
       D.NRODIVISAO,
       SUBSTR(R.REGIAO, 1, 20) DIVISAO,
       'V' TIPO,
       (CASE
           WHEN NVL(R.STATUS, 'A') = 'A' THEN
                'S'
           ELSE 'N'
        END) ATIVO,
        R.NUMREGIAO||R.UF IDREF
FROM PCREGIAO R,
     PCDEPARAREGIAOC5 D,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO') DTPADRAO
 WHERE R.NUMREGIAO = D.NUMREGIAO(+)
 AND   NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
)
