CREATE OR REPLACE PACKAGE PKG_MONITOR_DADOS_FAKE AS
  PROCEDURE GERAR_DADOS(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCDEVAVULSO(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCDEVFORNEC(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCESTCOM(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCNFBASESAID(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCNFBASEENT(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCLANCINTERMEDIARI(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCNFSAID(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCNFENT(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
  PROCEDURE GERAR_DADOS_PCMOV_E_PCMOVCOMPL(P_QUANTIDADE_REGISTROS_A_GERAR NUMBER);
END PKG_MONITOR_DADOS_FAKE;
/