CREATE OR REPLACE TRIGGER TRG_PCTABTRIB_OMNI_PRODUT
    AFTER INSERT OR UPDATE OR DELETE
    ON PCTABTRIB
    FOR EACH ROW
DECLARE
    v_codprod NUMBER;
BEGIN
    IF INSERTING THEN
        v_codprod := :NEW.CODPROD;
    ELSIF UPDATING THEN
        v_codprod := :NEW.CODPROD;
    ELSIF DELETING THEN
        v_codprod := :OLD.CODPROD;
    end if;
    UPDATE PCPRODUT
    SET DESCRICAO = DESCRICAO
    WHERE CODPROD = v_codprod;
end;