CREATE OR REPLACE VIEW VIEW_GET_RESPONSAVEL_TECNICO AS
WITH TAMBIENTE AS (SELECT 'H,P' AMB FROM PCCONSUM WHERE ROWNUM = 1)
SELECT FILIAL.CODIGO
     , FILIAL.RAZAOSOCIALRESPTEC
     , FILIAL.CNPJRESPTEC
     , FILIAL.TELEFONERESPTEC
     , FILIAL.EMAILRESPTEC
     , FILIAL.AMBIENTE
     , CSRT.IDCSRT
     , CSRT.CSRT
  FROM (SELECT PCFILIAL.CODIGO
             , PCFILIAL.RAZAOSOCIALRESPTEC
             , PCFILIAL.CNPJRESPTEC
             , PCFILIAL.TELEFONERESPTEC
             , PCFILIAL.EMAILRESPTEC
             , PCFILIAL.UF
             , AMBI.AMBIENTE
          FROM PCFILIAL
             , (SELECT REGEXP_SUBSTR(AMB, '[^,]+', 1, LEVEL) AMBIENTE FROM TAMBIENTE CONNECT BY INSTR(AMB, ',', 1, LEVEL - 1) > 0) AMBI
         WHERE ((NVL(PCFILIAL.UTILIZANFE, 'N') = 'S') 
             OR (NVL(PCFILIAL.UTILIZACTE, 'N') = 'S')
             OR (NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZAMDFE', PCFILIAL.CODIGO) , 'N') = 'S')
             OR (NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZASRVTERCEIROS', PCFILIAL.CODIGO) , 'N') = 'S'))) FILIAL
     , (SELECT W.* FROM PCCSRTWINTHOR W WHERE TRUNC(W.DATAINICIO) <= TRUNC(SYSDATE)) CSRT
 WHERE FILIAL.CNPJRESPTEC = CSRT.CNPJ(+)
   AND FILIAL.AMBIENTE = CSRT.AMBIENTE(+)
   AND FILIAL.UF = CSRT.UF(+)
