CREATE OR REPLACE VIEW VIEW_GET_RESPONSAVEL_TECNICO AS
SELECT PCFILIAL.CODIGO
     , PCFILIAL.RAZAOSOCIALRESPTEC
     , PCFILIAL.CNPJRESPTEC
     , PCFILIAL.TELEFONERESPTEC
     , PCFILIAL.EMAILRESPTEC
     , CSRT.AMBIENTE
     , CSRT.IDCSRT
     , CSRT.CSRT
  FROM PCFILIAL
     , (SELECT W.* FROM PCCSRTWINTHOR W WHERE TRUNC(W.DATAINICIO) <= TRUNC(SYSDATE)) CSRT
 WHERE ((NVL(PCFILIAL.UTILIZANFE, 'N') = 'S') 
     OR (NVL(PCFILIAL.UTILIZACTE, 'N') = 'S')
     OR (NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZAMDFE', PCFILIAL.CODIGO) , 'N') = 'S')
     OR (NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZASRVTERCEIROS', PCFILIAL.CODIGO) , 'N') = 'S'))
   AND PCFILIAL.CNPJRESPTEC = CSRT.CNPJ(+)
   AND PCFILIAL.UF = CSRT.UF(+)
