DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_CTE_INFO_SUBSTITUTO'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_CTE_INFO_SUBSTITUTO';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_CTE_INFO_SUBSTITUTO AS OBJECT
  (
     CHAVE_CTE_ORIGINAL                    VARCHAR2(45),
     CNPJ_CPF_EMITENTE                     VARCHAR2(18),
     MODELO_DOC                            VARCHAR2(2),
     SERIE_DOC                             VARCHAR2(3),
     SUBSERIE_DOC                          VARCHAR2(3),
     NUMERO_DOC                            NUMBER(10),
     VALOR_DOC                             NUMBER(13,2),                          
     DT_EMISSAO_DOC                        DATE, 
     CHAVE_NFE_TOMADOR                     VARCHAR2(45),
     CHAVE_CTE_ANULACAO                    VARCHAR2(45)    
  );
\
CREATE OR REPLACE TYPE TABELA_CTE_INFO_SUBSTITUTO IS TABLE OF TIPO_CTE_INFO_SUBSTITUTO;