DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_CTE_IDENTIFICACAO'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_CTE_IDENTIFICACAO';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_CTE_IDENTIFICACAO AS OBJECT
(
   NUM_TRANSACAO               NUMBER,
   CHAVECTE                    VARCHAR2(44),
   CFOP                        NUMBER,
   NATUREZA_OP                 VARCHAR2(60),
   FORMA_PAGAMENTO             NUMBER,
   SERIE                       VARCHAR2(3),
   NUMERO_NOTA                 NUMBER,
   DATA_HORA_EMISSAO           DATE,
   TIPO_DACTE                  NUMBER,
   TIPO_EMISSAO                NUMBER,
   TIPO_AMBIENTE               NUMBER,
   TIPO_CTE                    NUMBER,
   CHAVECTE_REFERENCIADA       VARCHAR2(44),
   CODIGO_MUN_EMISSAO          NUMBER,
   MUNICIPIO_EMISSAO           VARCHAR2(80),
   SIGLA_UF_EMISSAO            VARCHAR2(2),
   MODAL                       NUMBER,
   TIPO_SERVICO                NUMBER,
   TIPOSERVICOCTE              VARCHAR2(1),
   CODIGO_MUN_INICIO_PRESTACAO NUMBER,
   MUNICIPIO_INICIO_PRESTACAO  VARCHAR2(80),
   SIGLA_UF_INICIO_PRESTACAO   VARCHAR2(2),
   CODIGO_MUN_FIM_PRESTACAO    NUMBER,
   MUNICIPIO_FIM_PRESTACAO     VARCHAR2(80),
   SIGLA_UF_FIM_PRESTACAO      VARCHAR2(2),
   RETIRA                      NUMBER,
   DETALHE_RETIRA              VARCHAR2(160),
   TOMADOR_SERVICO             NUMBER,
   VALOR_TOTAL                 NUMBER,
   PROTOCOLO_AUTORIZACAO       VARCHAR2(16),
   DATA_HORA_AUTORIZACAO       DATE,
   DTHORA_CONTINGENCIA         DATE,
   JUSTIFICATIVA_CONTINGENCIA  VARCHAR2(256),
   TOTAL_PESO_BRUTO            NUMBER(18,6),
   TOTAL_CUBAGEM               NUMBER(12,6),
   QTDE_VOLUMES                NUMBER(12,6),
   LACRES                      VARCHAR2(200),
   VALOR_TOTAL_SERVICO         NUMBER,
   IE_TOMADOR                  VARCHAR2(20),
   CTE_GLOBALIZADO             VARCHAR2(1),
   INF_GLOBALIZADO             VARCHAR2(256),
   QRCODE                      VARCHAR2(1000),
   CODIGO_NUMERICO_CHAVE       VARCHAR2(8)
)