DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_CONFIG_EMAIL'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_CONFIG_EMAIL';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_CONFIG_EMAIL AS OBJECT
(
   USUARIO        VARCHAR2(100),
   SENHA          VARCHAR2(100),
   DOMINIO        VARCHAR2(100),
   NOME_REMENTE   VARCHAR2(100),
   EMAIL_REMENTE   VARCHAR2(100),
   SERVIDOR_SMTP  VARCHAR2(100),
   PORTA          NUMBER,
   ATIVAR_SSL     VARCHAR2(1),
   EMAIL_RESPOSTA VARCHAR2(100),
   EMAIL_COPIA    VARCHAR2(100),
   ATIVAR_TLS     VARCHAR2(1)
) 