DECLARE
  VEXISTE NUMBER;
BEGIN    
  -- PRECONFE
  SELECT COUNT(*)
    INTO VEXISTE
    FROM PCROTULOITEM
   WHERE ID = 'PRECONFE'
     AND VALOR = 'LR';

  IF VEXISTE = 0 THEN
    INSERT INTO PCROTULOITEM
	(ID
	,DESCRICAO
	,VALOR
	,DTCADASTRO
	,CRIADOPELOCLIENTE)
    VALUES
	('PRECONFE'
	,'LR - Preço Líquido + Repasse (LR)'
	,'LR'
	,SYSDATE
	,'N');
  END IF;  

  -- Corrige cadastro antigo do REIDI
  UPDATE PCROTULOITEM
     SET VALOR     = 'REID',
         DESCRICAO = 'Beneficiário REIDI'
   WHERE ID = 'TIPOEMPRESA'
     AND VALOR = 'REIDI';

  -- Corrige cadastro antigo da SUFRAMA
  UPDATE PCROTULOITEM
     SET VALOR     = 'SUFR',
         DESCRICAO = 'Suframa'
   WHERE ID = 'TIPOEMPRESA'
     AND VALOR = 'SUFRAMA';
  
  -- REIDI
  SELECT COUNT(*)
    INTO VEXISTE
    FROM PCROTULOITEM
   WHERE ID = 'TIPOEMPRESA'
     AND VALOR = 'REID';

  IF VEXISTE = 0 THEN
    INSERT INTO PCROTULOITEM
	(ID
	,DESCRICAO
	,VALOR)
    VALUES
	('TIPOEMPRESA'
	,'Beneficiário REIDI'
	,'REID');
  END IF;

  -- SUFRAMA
  SELECT COUNT(*)
    INTO VEXISTE
    FROM PCROTULOITEM
   WHERE ID = 'TIPOEMPRESA'
     AND VALOR = 'SUFR';

  IF VEXISTE = 0 THEN
    INSERT INTO PCROTULOITEM
	(ID
	,DESCRICAO
	,VALOR)
    VALUES
	('TIPOEMPRESA'
	,'Suframa'
	,'SUFR');
  END IF;

  COMMIT;

END;