 DECLARE
 vCOUNT NUMBER;
 BEGIN
 SELECT COUNT(1) 
 INTO vCOUNT
 FROM PCSUBMODULO WHERE CODSUBMODULO = 1 AND CODMODULO = 11;
 
 IF vCOUNT = 0 THEN
 INSERT INTO PCSUBMODULO (codmodulo, codsubmodulo,submodulo,exibirmenu) values (11,1,'ESTOQUE','S');
 END IF;
 
 UPDATE PCROTINA SET CODSUBMODULO = 1, NOMEROTINA = 'Movimentações de estoque WMS Saas' WHERE CODIGO = 1149;
COMMIT;
 END;