CREATE OR REPLACE VIEW VW_GRUPOSCAMPANHA_RCA AS
  SELECT PCGRUPOSCAMPANHAC.CODGRUPO
       , PCGRUPOSCAMPANHAC.TIPO
       , PCGRUPOSCAMPANHAC.CODFILIAL
       , PCGRUPOSCAMPANHAC.DESCRICAO
       , PCGRUPOSCAMPANHAI.CODITEM AS CODUSUR
       , PCGRUPOSCAMPANHAC.DTEXCLUSAO
       , PCGRUPOSCAMPANHAC.DTINCLUSAO
       , PCGRUPOSCAMPANHAC.CODFUNC
    FROM PCGRUPOSCAMPANHAC
       , PCGRUPOSCAMPANHAI
   WHERE PCGRUPOSCAMPANHAC.CODGRUPO = PCGRUPOSCAMPANHAI.CODGRUPO
     AND PCGRUPOSCAMPANHAC.TIPO = 'GR'
