CREATE OR REPLACE PROCEDURE PRC_INT_C5_CONTROLEATIVO IS
BEGIN
  UPDATE MONITORPDVMIDDLE.tb_regraincentivo SET ATIVO = ''N''
  WHERE SEQREGRA IN (SELECT L.CODFILIAL||561||L.CODDESCONTO  
                       FROM PCDESCONTOLOG L 
                       WHERE TRUNC(SYSDATE) BETWEEN L.DTINICIO AND L.DTFIM);

  UPDATE MONITORPDVMIDDLE.tb_regraincentivoperiodo SET ATIVO = ''N''
  WHERE SEQREGRA IN (SELECT L.CODFILIAL||561||L.CODDESCONTO  
                       FROM PCDESCONTOLOG L 
                       WHERE TRUNC(SYSDATE) BETWEEN L.DTINICIO AND L.DTFIM);

  UPDATE MONITORPDVMIDDLE.tb_regrafamilia SET ATIVO = ''N''
  WHERE SEQREGRA IN (SELECT L.CODFILIAL||561||L.CODDESCONTO  
                       FROM PCDESCONTOLOG L 
                       WHERE TRUNC(SYSDATE) BETWEEN L.DTINICIO AND L.DTFIM);                       

  UPDATE MONITORPDVMIDDLE.tb_regracliente SET ATIVO = ''N''
  WHERE SEQREGRA IN (SELECT L.CODFILIAL||561||L.CODDESCONTO  
                       FROM PCDESCONTOLOG L 
                       WHERE TRUNC(SYSDATE) BETWEEN L.DTINICIO AND L.DTFIM);                       

  UPDATE MONITORPDVMIDDLE.tb_regracategoria SET ATIVO = ''N''
  WHERE SEQREGRA IN (SELECT L.CODFILIAL||561||L.CODDESCONTO  
                       FROM PCDESCONTOLOG L 
                       WHERE TRUNC(SYSDATE) BETWEEN L.DTINICIO AND L.DTFIM);                       
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END PRC_INT_C5_CONTROLEATIVO;
