DECLARE
vSQL VARCHAR2(200);
BEGIN
  -- Incluindo as colunas de bkp
  vSQL := 'ALTER TABLE PCDESPESAIMPCE ADD VALOR_BKP NUMBER(12,6)';
  EXECUTE IMMEDIATE vSQL;
  
  -- Incluindo as colunas de bkp
  vSQL := 'ALTER TABLE PCDESPESAIMPCE ADD VLREALIZADO_BKP NUMBER(12,6)';
  EXECUTE IMMEDIATE vSQL;
  
  -- Clonando os dados das colunas VALOR e VLREALIZADO para as colunas de bkp
  vSQL := 'UPDATE PCDESPESAIMPCE SET VALOR_BKP = VALOR, VLREALIZADO_BKP = VLREALIZADO';
  EXECUTE IMMEDIATE vSQL;
  
  -- Limpado os dados das colunas VALOR e VLREALIZADO
  vSQL := 'UPDATE PCDESPESAIMPCE SET VALOR = NULL, VLREALIZADO = NULL';
  EXECUTE IMMEDIATE vSQL;
  
  -- Alterando a precisão dos campos VALOR e VLREALIZADO
  vSQL := 'ALTER TABLE PCDESPESAIMPCE MODIFY VALOR NUMBER(22,6)';
  EXECUTE IMMEDIATE vSQL;
  
  -- Alterando a precisão dos campos VALOR e VLREALIZADO
  vSQL := 'ALTER TABLE PCDESPESAIMPCE MODIFY VLREALIZADO NUMBER(22,6)';
  EXECUTE IMMEDIATE vSQL;
  
  -- Clonando os dados das colunas BKP para colunas VALOR e VLREALIZADO
  vSQL := 'UPDATE PCDESPESAIMPCE SET VALOR = VALOR_BKP, VLREALIZADO = VLREALIZADO_BKP';
  EXECUTE IMMEDIATE vSQL;
  
  commit;
END;