CREATE OR REPLACE FUNCTION GET_NOTAS_CODIGO_FISCAL RETURN VARCHAR2 IS
    v_sql VARCHAR2(4000);
BEGIN
    v_sql := 'SELECT ''1'' TIPO,
DECODE(SUBSTR(A.CODFISCAL, 1, 1),
       1,
       ''ENTRADAS E OU PRESTAÇÃO DE SERVIÇOS PARA O ESTADO'',
       2,
       ''ENTRADAS E OU PRESTAÇÃO DE SERVIÇOS PARA OUTRO ESTADO'',
       3,
       ''ENTRADAS E OU PRESTAÇÃO DE SERVIÇOS PARA O EXTERIOR'') SUBTIPO,
A.CODFISCAL FISC,
B.DESCCFO DESCRICAO,
SUM(NVL(A.VLDESDOBRADO,0)) VLCONTAB,
SUM(NVL(A.VLBASE,0)) VLBASE,
SUM( NVL(A.VLICMS,0)) VLICMS,
SUM(NVL(A.VLISENTAS,0)) VLISENTO,                   
SUM( NVL(A.VLOUTRAS,0)) VLOUTRAS,
SUM(NVL(A.VLST,0)) VLST,
SUM(NVL(A.VLOUTRAS,0) - NVL(A.VLIPI,0) - NVL(A.VLST,0)) VLPRODUTOS,
SUM(NVL(A.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP,
SUM(NVL(A.VLFECP, 0)) AS VLFECP
FROM   PCCFO       B,
       PCNFBASEENT A
WHERE  A.CODFISCAL = B.CODFISCAL(+)
AND    A.DTENTRADA BETWEEN TRUNC(SYSDATE-90) AND TRUNC(SYSDATE-1)
AND    A.CODFISCAL BETWEEN 1000 AND 3999
AND    A.CODFISCAL > 0
AND not exists(select DISTINCT NUMTRANSENT from pcnfent where not dtcancel is null and numtransent = A.NUMTRANSENT AND ESPECIE = A.ESPECIE)
GROUP BY A.CODFILIALNF, A.CODFISCAL, B.DESCCFO
UNION ALL
SELECT ''2.1'' TIPO,
DECODE(SUBSTR(A.CODFISCAL, 1, 1),
       5,
       ''SAIDAS E OU PRESTAÇÃO DE SERVIÇOS PARA O ESTADO'',
       6,
       ''SAIDAS E OU PRESTAÇÃO DE SERVIÇOS PARA OUTRO ESTADO'',
       7,
       ''SAIDAS E OU PRESTAÇÃO DE SERVIÇOS PARA O EXTERIOR'') SUBTIPO,
A.CODFISCAL FISC,
B.DESCCFO DESCRICAO,
SUM(NVL(A.VLDESDOBRADO,0)) VLCONTAB,
SUM(NVL(A.VLBASE,0)) VLBASE,                   
SUM(NVL(A.VLICMS,0)) VLICMS,
SUM(NVL(A.VLISENTAS,0)) VLISENTO,
SUM( NVL(A.VLOUTRAS,0)) VLOUTRAS,
SUM(NVL(A.VLST,0)) VLST,
SUM(NVL(A.VLOUTRAS,0) - NVL(A.VLIPI,0) - NVL(A.VLST,0)) VLPRODUTOS,
SUM(NVL(A.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP,
SUM(NVL(A.VLFECP, 0)) AS VLFECP                 
FROM   PCCFO        B,
       PCNFBASESAID A,
       PCCONSUM     C,
       PCNFSAID     S
WHERE  A.CODFISCAL = B.CODFISCAL(+)
AND    A.NUMTRANSVENDA = S.NUMTRANSVENDA(+)
AND  NVL(S.DTENTREGA, NVL(S.DTSAIDANF, A.DTSAIDA)) BETWEEN TRUNC(SYSDATE-90) AND TRUNC(SYSDATE-1)
AND    A.CODFISCAL BETWEEN 5000 AND 7999
AND    A.CODFISCAL > 0
AND    S.DTCANCEL IS NULL
AND    A.ESPECIE <> ''MR''
AND    (NVL(A.SERIE, ''X'') NOT IN (''CF'', ''CP'') OR S.CHAVENFE IS NOT NULL)
AND    (NVL(A.SERIE, ''X'') NOT IN (''CF'', ''CP'') OR S.SITUACAONFE <> ''102'')
GROUP BY A.CODFILIALNF, A.CODFISCAL, B.DESCCFO
UNION ALL
SELECT ''2.2'' TIPO,
   DECODE(SUBSTR(A.CODFISCAL, 1, 1),
          5,
          ''SAIDAS E OU PRESTAÇÃO DE SERVIÇOS PARA O ESTADO'',
          6,
          ''SAIDAS E OU PRESTAÇÃO DE SERVIÇOS PARA OUTRO ESTADO'',
          7,
          ''SAIDAS E OU PRESTAÇÃO DE SERVIÇOS PARA O EXTERIOR'') SUBTIPO,
   A.CODFISCAL FISC,
   B.DESCCFO DESCRICAO,
   SUM(NVL(A.VLDESDOBRADO,0)) VLCONTAB,
   SUM(NVL(A.VLBASE,0)) VLBASE,                   
   SUM(NVL(A.VLICMS,0)) VLICMS,
   SUM(NVL(A.VLISENTAS,0)) VLISENTO,
   SUM( NVL(A.VLOUTRAS,0)) VLOUTRAS,
   SUM(NVL(A.VLST,0)) VLST,
   SUM(NVL(A.VLOUTRAS,0) - NVL(A.VLIPI,0) - NVL(A.VLST,0)) VLPRODUTOS,
   SUM(NVL(A.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP,
   SUM(NVL(A.VLFECP, 0)) AS VLFECP                 
FROM   PCCFO        B,
       PCNFBASESAID A,
       PCCONSUM     C,
       PCNFSAID     S
WHERE  A.CODFISCAL = B.CODFISCAL(+)
AND    A.NUMTRANSVENDA = S.NUMTRANSVENDA(+)
AND  A.DTSAIDA BETWEEN TRUNC(SYSDATE-90) AND TRUNC(SYSDATE-1) 
    AND    A.CODFISCAL BETWEEN 5000 AND 7999
    AND    A.CODFISCAL > 0
    AND    S.DTCANCEL IS NULL
    AND    A.ESPECIE <> ''MR''
    AND    (NVL(A.SERIE, ''X'') NOT IN (''CF'', ''CP'') OR S.CHAVENFE IS NOT NULL)
    AND    (NVL(A.SERIE, ''X'') NOT IN (''CF'', ''CP'') OR S.SITUACAONFE <> ''102'')
    GROUP BY A.CODFILIALNF, A.CODFISCAL, B.DESCCFO';

    RETURN v_sql;
END;
