CREATE OR REPLACE VIEW VW_GRUPOSCAMPANHA_FORNECEDOR AS
  SELECT PCGRUPOSCAMPANHAC.CODGRUPO
       , PCGRUPOSCAMPANHAC.TIPO
       , PCGRUPOSCAMPANHAC.CODFILIAL
       , PCGRUPOSCAMPANHAC.DESCRICAO
       , PCGRUPOSCAMPANHAI.CODITEM AS CODFORNEC
       , PCGRUPOSCAMPANHAC.DTEXCLUSAO
       , PCGRUPOSCAMPANHAC.DTINCLUSAO
       , PCGRUPOSCAMPANHAC.CODFUNC
    FROM PCGRUPOSCAMPANHAC
       , PCGRUPOSCAMPANHAI
   WHERE PCGRUPOSCAMPANHAC.CODGRUPO = PCGRUPOSCAMPANHAI.CODGRUPO
     AND PCGRUPOSCAMPANHAC.TIPO = 'GF'
