CREATE OR REPLACE VIEW VW_GRUPOSCAMPANHA_FORNECEDOR AS
SELECT PCGRUPOSCAMPANHAC.CODGRUPO
     , PCGRUPOSCAMPANHAC.TIPO
     , PCGRUPOSCAMPANHAC.CODFILIAL
     , PCGRUPOSCAMPANHAC.DESCRICAO
     , PCPRODUT.CODPROD AS CODPROD
     , PCGRUPOSCAMPANHAC.DTEXCLUSAO
     , PCGRUPOSCAMPANHAC.DTINCLUSAO
     , PCGRUPOSCAMPANHAC.CODFUNC
  FROM PCGRUPOSCAMPANHAC
     , PCGRUPOSCAMPANHAI
     , PCPRODUT
 WHERE PCGRUPOSCAMPANHAC.CODGRUPO = PCGRUPOSCAMPANHAI.CODGRUPO
   AND PCGRUPOSCAMPANHAC.TIPO = 'GF'
   AND PCGRUPOSCAMPANHAI.CODITEM = PCPRODUT.CODFORNEC
