DECLARE 
BEGIN
  INSERT INTO PCROTINATABELA (
      CODROTINA, NOMEOBJETO, USARCADGENERICO, WHEREADICIONALPESQ,
      PERMITEINCLUIR, PERMITEALTERAR, PERMITEEXCLUIR, TITULOROTINA,
      DTCADASTRO, ATUALIZARPERMISSAO
  ) VALUES (
     4000, 'PCTRIBUTACAO', 'N', '...',
      'S', 'S', 'S', 'Cadastro de reforma tributária',
      TO_DATE('24/01/2023 18:00:30', 'DD/MM/YYYY HH24:MI:SS'), 'S'
  );
  
  UPDATE PCDICIONARIOITEM D
    SET D.FORMULAAUTOGERACAO = UPPER(D.FORMULAAUTOGERACAO)
  WHERE D.NOMEOBJETO = 'PCTRIBUTACAO';
  
  UPDATE PCDICIONARIOITEMROT R
    SET R.EXIBIRRESPESQ = 'S', R.USARNAPESQUISA = 'S'
  WHERE R.CODROTINA = 4000;
  
  COMMIT;
END;