DECLARE 
BEGIN
  INSERT INTO PCROTINATABELA (
      CODROTINA, NOMEOBJETO, USARCADGENERICO, WHEREADICIONALPESQ,
      PERMITEINCLUIR, PERMITEALTERAR, PERMITEEXCLUIR, TITULOROTINA,
      DTCADASTRO, ATUALIZARPERMISSAO
  ) VALUES (
     4000, 'PCTRIBUTACAO', 'N', '...',
      'S', 'S', 'S', 'Cadastro de reforma tributária',
      TO_DATE('24/01/2023 18:00:30', 'DD/MM/YYYY HH24:MI:SS'), 'S'
  );
  
  UPDATE PCDICIONARIOITEM D
    SET D.FORMULAAUTOGERACAO = UPPER(D.FORMULAAUTOGERACAO)
  WHERE D.NOMEOBJETO = 'PCTRIBUTACAO';
  
  UPDATE PCDICIONARIOITEMROT R
    SET R.EXIBIRRESPESQ = 'S', R.USARNAPESQUISA = 'S'
  WHERE R.CODROTINA = 4000;
  
  COMMIT;
  

  --Exclusão e insersão dos tipos de fórmula.
  DELETE FROM PCFORMULA WHERE CODTIPOFORMULA IN (28, 29, 30, 31, 32, 33);
  
  DELETE FROM PCFORMULATIPO WHERE CODTIPOFORMULA IN (28, 29, 30, 31, 32, 33);

  --Insersão dos tipos de fórmula.   
  INSERT INTO PCFORMULATIPO
    (CODTIPOFORMULA, DESCRICAO, DTCADASTRO)
  VALUES
    (28, 'BASE_CBS', SYSDATE);
    
  INSERT INTO PCFORMULATIPO
    (CODTIPOFORMULA, DESCRICAO, DTCADASTRO)
  VALUES
    (29, 'BASE_IBS', SYSDATE);
    
  INSERT INTO PCFORMULATIPO
    (CODTIPOFORMULA, DESCRICAO, DTCADASTRO)
  VALUES
    (30, 'ALIQUOTA_CBS', SYSDATE);
    
  INSERT INTO PCFORMULATIPO
    (CODTIPOFORMULA, DESCRICAO, DTCADASTRO)
  VALUES
    (31, 'ALIQUOTA_IBS', SYSDATE);
    
  INSERT INTO PCFORMULATIPO
    (CODTIPOFORMULA, DESCRICAO, DTCADASTRO)
  VALUES
    (32, 'BASE_IS', SYSDATE);
    
  INSERT INTO PCFORMULATIPO
    (CODTIPOFORMULA, DESCRICAO, DTCADASTRO)
  VALUES
    (33, 'ALIQUOTA_IS', SYSDATE);

  --Insersão das formulas. 
  INSERT INTO PCFORMULA
    (CODFORMULA, DESCRICAO, FORMULA, CODTIPOFORMULA, DTCADASTRO)
  VALUES
    ('BASE_CBS_1',
     'Base sobre Valor do Produto',
     'GREATEST(' || '&' || 'PUNITCONT' || '&' || ',0)',
     28,
     SYSDATE);
  INSERT INTO PCFORMULA
    (CODFORMULA, DESCRICAO, FORMULA, CODTIPOFORMULA, DTCADASTRO)
  VALUES
    ('BASE_IBS_1',
     'Base sobre Valor do Produto',
     'GREATEST(' || '&' || 'PUNITCONT' || '&' || ',0)',
     29,
     SYSDATE);
  INSERT INTO PCFORMULA
    (CODFORMULA, DESCRICAO, FORMULA, CODTIPOFORMULA, DTCADASTRO)
  VALUES
    ('BASE_IS_1',
     'Base sobre Valor do Produto',
     'GREATEST(' || '&' || 'PUNITCONT' || '&' || ',0)',
     32,
     SYSDATE);

  COMMIT;     
  
END;