CREATE OR REPLACE FUNCTION FILIAL_EM_FECHAMENTO_DIARIO(P_COD_FILIAL IN VARCHAR2) RETURN VARCHAR2 IS
  V_RESULTADO VARCHAR2(1);
  
  FUNCTION ROTINA504DESCONTINUADA RETURN VARCHAR2 IS
    V_ROTINA_DESCONTINUADA NUMBER(1);
  BEGIN
    SELECT COUNT(1) INTO V_ROTINA_DESCONTINUADA FROM PCROTDESCONTINUADAS WHERE CODIGO = '504';
    
    IF (V_ROTINA_DESCONTINUADA > 0) THEN
      RETURN 'S';
    ELSE
      RETURN 'N';
    END IF;  
  END;
  
  FUNCTION ESTA_NO_HORARIO_DE_FECHAMENTO(P_COD_FILIAL IN VARCHAR2) RETURN VARCHAR2 IS
    V_UF_FILIAL VARCHAR2(2);
    V_DATA_HORA DATE;
    V_HORA_MIN  NUMBER;
  BEGIN
    SELECT UF INTO V_UF_FILIAL FROM PCFILIAL WHERE CODIGO = P_COD_FILIAL;

    -- Data e hora correta da filial
    V_DATA_HORA := FISCAL.GET_HORACERTA_TIMEZONE(V_UF_FILIAL);

    -- Hora no formato HHMM (ex: 2357, 0003)
    V_HORA_MIN := TO_NUMBER(TO_CHAR(V_DATA_HORA, 'HH24MI'));

    IF (V_HORA_MIN >= 2355 OR V_HORA_MIN <= 5) THEN
      RETURN 'S';
    ELSE
      RETURN 'N';
    END IF;
  END;
  
BEGIN
  BEGIN  
    IF (ROTINA504DESCONTINUADA() = 'S') AND (ESTA_NO_HORARIO_DE_FECHAMENTO(P_COD_FILIAL) = 'S') THEN
      RETURN 'S';
    ELSE
      RETURN 'N';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, ('Erro original: ' || SQLERRM));
  END;  
END;
