DECLARE
   e_idx_exist EXCEPTION; PRAGMA EXCEPTION_INIT(e_idx_exist, -955);
BEGIN
   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCGMMETAGLOBALTEMP_14_IDX_NTV ON PCGMMETAGLOBALTEMP_14 (NUMTRANSVENDA, TIPOMOV, DATA)'; EXCEPTION WHEN e_idx_exist THEN NULL; END;
   
   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCFORNEC_IDX_FORNECPRINC ON PCFORNEC (CODFORNEC, CODFORNECPRINC)'; EXCEPTION WHEN e_idx_exist THEN NULL; END;   

   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCCOMISSAOUSUR_IDX_R ON PCCOMISSAOUSUR (CODUSUR, TIPO, PERCDESCINI, PERCDESCFIM)'; EXCEPTION WHEN e_idx_exist
   THEN NULL; END;

   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCCOMISSAOUSUR_IDX_RP ON PCCOMISSAOUSUR (CODUSUR, CODPROD, TIPO, PERCDESCINI, PERCDESCFIM)'; EXCEPTION WHEN e_idx_exist THEN NULL; END;
   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCCOMISSAOUSUR_IDX_RD ON PCCOMISSAOUSUR (CODUSUR, CODEPTO, TIPO, PERCDESCINI, PERCDESCFIM)'; EXCEPTION WHEN e_idx_exist THEN NULL; END;
   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCCOMISSAOUSUR_IDX_RS ON PCCOMISSAOUSUR (CODUSUR, CODSEC, TIPO, PERCDESCINI, PERCDESCFIM)'; EXCEPTION WHEN e_idx_exist THEN NULL; END;
   
   BEGIN EXECUTE IMMEDIATE 'CREATE INDEX PCCOMISSAOUSUR_FBI_TIPO ON PCCOMISSAOUSUR (CODUSUR, NVL(TIPO, ''R''), PERCDESCINI, PERCDESCFIM)'; EXCEPTION WHEN e_idx_exist THEN NULL; END;
END;
/