BEGIN
    DELETE FROM PCPARAMINTEGRACAOWMSSAAS
    WHERE PARAMETRO IN ('BUSCAR_PEDIDOS_MONTADOS', 'BUSCAR_PEDIDOS_LIBERADOS', 'BUSCAR_PEDIDOS_FATURADOS');

    DELETE FROM PCPARAMINTEGRACAOWMSSAASROTULO
    WHERE PARAMETRO IN ('BUSCAR_PEDIDOS_MONTADOS', 'BUSCAR_PEDIDOS_LIBERADOS', 'BUSCAR_PEDIDOS_FATURADOS');
    COMMIT;
END;