CREATE OR REPLACE FUNCTION CTE_IMPOSTO(P_TRANSACAO NUMBER, P_MOV VARCHAR2 DEFAULT 'S')
   RETURN TABELA_CTE_IMPOSTO IS

   CURSOR CR_IMPOSTO IS
      SELECT NVL(PCNFBASE.SITTRIBUT,-1) AS SITUACAO_TRIBUTARIA
            ,PCNFBASE.VLBASE AS VALOR_BC_ICMS
            ,PCNFBASE.VLICMS AS VALOR_ICMS
            ,PCNFBASE.ALIQUOTA AS ALIQUOTA
            ,NVL(PCNFBASE.VLCREDICMSPRESUMIDO, 0) AS VALOR_CREDITO
            ,DECODE(PCNFSAID.VLFRETE, 0, 0,
                    DECODE(PCNFBASE.VLBASE,0,0,
                    DECODE(NVL(PCNFSAID.VLTOTAL,0), 0, 0, 
                    NVL(NVL(PCNFBASE.PERCREDCIMS,0), ROUND(((PCNFSAID.VLTOTAL - SUM(PCNFBASE.VLBASE)) / PCNFSAID.VLTOTAL) * 100, 2))))) AS PERCENTUAL_REDUCAO             
            ,NVL(PCNFSAID.VLTRIBUTOS,0) AS VALOR_TRIBUTOS
            ,NVL(PCNFBASE.VLBASEPARTDEST,0) AS VALOR_BC_UF_FIM --vBCUFFim 
            ,NVL(PCNFBASE.ALIQFCP,0) AS ALIQUOTA_FCP --pFCPUFFim 
            ,NVL(PCNFBASE.ALIQINTERNADEST,0) AS ALIQUOTA_INTERNA_DEST --pICMSUFFim 
            ,NVL(PCNFBASE.PERCPROVPART,0) AS ALIQUOTA_PROVISORIA_PARTILHA --pICMSInterPart 
            ,NVL(PCNFBASE.VLFCPPART,0) AS VALOR_FC_POBREZA --vFCPUFFim 
            ,NVL(PCNFBASE.VLICMSPARTDEST,0) AS VALOR_ICMS_PART_DEST --vICMSUFFim 
            ,NVL(PCNFBASE.VLICMSPARTREM,0) AS VALOR_ICMS_PART_REM --vICMSUFIni
            ,DECODE(NVL(PCNFSAID.REDUZICMSDOCTE, 'N'), 'N', NVL(PCNFSAID.VLTOTAL,0), NVL(PCNFSAID.VLTOTAL,0) + NVL(PCNFSAID.VLICMS,0)) AS VALOR_PRESTACAO_SERVICO
            ,NVL(PCNFSAID.VLTOTAL,0) AS VALOR_A_RECEBER
			,NVL(PCNFBASE.CODBENEFICIOFISCAL,0) AS CODBENEFICIOFISCAL
        FROM PCNFBASE, PCNFSAID
       WHERE PCNFSAID.NUMTRANSVENDA = P_TRANSACAO
       AND   PCNFBASE.NUMTRANSVENDA(+) = PCNFSAID.NUMTRANSVENDA
       AND P_MOV = 'S'
       GROUP BY PCNFBASE.SITTRIBUT,
                PCNFBASE.VLBASE,
                PCNFBASE.VLICMS,
                PCNFBASE.ALIQUOTA,
                PCNFSAID.VLFRETE,
                PCNFSAID.VLTOTAL,
                PCNFSAID.VLTRIBUTOS
                ,NVL(PCNFBASE.VLBASEPARTDEST,0) 
                ,NVL(PCNFBASE.ALIQFCP,0) 
                ,NVL(PCNFBASE.ALIQINTERNADEST,0) 
                ,NVL(PCNFBASE.PERCPROVPART,0) 
                ,NVL(PCNFBASE.VLFCPPART,0) 
                ,NVL(PCNFBASE.VLICMSPARTDEST,0) 
                ,NVL(PCNFBASE.VLICMSPARTREM,0)
                ,NVL(PCNFBASE.PERCREDCIMS,0)
                ,NVL(PCNFBASE.VLCREDICMSPRESUMIDO,0)
                ,NVL(PCNFSAID.REDUZICMSDOCTE, 'N')
                ,NVL(PCNFSAID.VLICMS,0)
				,NVL(PCNFBASE.CODBENEFICIOFISCAL,0)
                
       UNION ALL
       
       SELECT NVL(PCNFBASE.SITTRIBUT,-1) AS SITUACAO_TRIBUTARIA
            ,PCNFBASE.VLBASE AS VALOR_BC_ICMS
            ,PCNFBASE.VLICMS AS VALOR_ICMS
            ,PCNFBASE.ALIQUOTA AS ALIQUOTA
            ,0 AS VALOR_CREDITO
            ,0 AS PERCENTUAL_REDUCAO            
            ,0 AS VALOR_TRIBUTOS
            ,NVL(PCNFBASE.VLBASEPARTDEST,0) AS VALOR_BC_UF_FIM --vBCUFFim 
            ,NVL(PCNFBASE.ALIQFCP,0) AS ALIQUOTA_FCP --pFCPUFFim 
            ,NVL(PCNFBASE.ALIQINTERNADEST,0) AS ALIQUOTA_INTERNA_DEST --pICMSUFFim 
            ,NVL(PCNFBASE.PERCPROVPART,0) AS ALIQUOTA_PROVISORIA_PARTILHA --pICMSInterPart 
            ,NVL(PCNFBASE.VLFCPPART,0) AS VALOR_FC_POBREZA --vFCPUFFim 
            ,NVL(PCNFBASE.VLICMSPARTDEST,0) AS VALOR_ICMS_PART_DEST --vICMSUFFim 
            ,NVL(PCNFBASE.VLICMSPARTREM,0) AS VALOR_ICMS_PART_REM --vICMSUFIni
            ,NVL(PCNFENT.VLTOTAL,0) AS VALOR_PRESTACAO_SERVICO
            ,NVL(PCNFENT.VLTOTAL,0) AS VALOR_A_RECEBER
			,NVL(PCNFBASE.CODBENEFICIOFISCAL,0) AS CODBENEFICIOFISCAL
        FROM PCNFBASE, PCNFENT
       WHERE PCNFENT.NUMTRANSENT = P_TRANSACAO
       AND   PCNFBASE.NUMTRANSENT(+) = PCNFENT.NUMTRANSENT
       AND   PCNFBASE.CODCONT(+) = PCNFENT.CODCONT
       AND P_MOV = 'E';       
       
   RETORNO TABELA_CTE_IMPOSTO;

BEGIN
   RETORNO := TABELA_CTE_IMPOSTO();

   FOR IMPOSTO IN CR_IMPOSTO LOOP
      RETORNO.EXTEND;
      
      RETORNO(RETORNO.COUNT) := TIPO_CTE_IMPOSTO(SITUACAO_TRIBUTARIA => NULL
                                                ,VALOR_BC_ICMS       => NULL
                                                ,VALOR_ICMS          => NULL
                                                ,ALIQUOTA            => NULL
                                                ,VALOR_CREDITO       => NULL
                                                ,PERCENTUAL_REDUCAO  => NULL
                                                ,VALOR_TRIBUTOS      => NULL
                                                ,VALOR_BC_UF_FIM      => NULL           
                                                ,ALIQUOTA_FCP         => NULL          
                                                ,ALIQUOTA_INTERNA_DEST  => NULL        
                                                ,ALIQUOTA_PROVISORIA_PARTILHA  => NULL 
                                                ,VALOR_FC_POBREZA  => NULL             
                                                ,VALOR_ICMS_PART_DEST  => NULL         
                                                ,VALOR_ICMS_PART_REM => NULL 
                                                ,VALOR_PRESTACAO_SERVICO => NULL
                                                ,VALOR_A_RECEBER => NULL
												,CODBENEFICIOFISCAL => NULL);      
      
      RETORNO(RETORNO.COUNT).SITUACAO_TRIBUTARIA := IMPOSTO.SITUACAO_TRIBUTARIA;
      RETORNO(RETORNO.COUNT).VALOR_BC_ICMS       := IMPOSTO.VALOR_BC_ICMS;
      RETORNO(RETORNO.COUNT).VALOR_ICMS          := IMPOSTO.VALOR_ICMS;
      RETORNO(RETORNO.COUNT).ALIQUOTA            := IMPOSTO.ALIQUOTA;
      RETORNO(RETORNO.COUNT).VALOR_CREDITO       := IMPOSTO.VALOR_CREDITO;
      RETORNO(RETORNO.COUNT).PERCENTUAL_REDUCAO  := IMPOSTO.PERCENTUAL_REDUCAO;
      RETORNO(RETORNO.COUNT).VALOR_TRIBUTOS      := IMPOSTO.VALOR_TRIBUTOS;
      RETORNO(RETORNO.COUNT).VALOR_BC_UF_FIM     := IMPOSTO.VALOR_BC_UF_FIM;          
      RETORNO(RETORNO.COUNT).ALIQUOTA_FCP        := IMPOSTO.ALIQUOTA_FCP;          
      RETORNO(RETORNO.COUNT).ALIQUOTA_INTERNA_DEST := IMPOSTO.ALIQUOTA_INTERNA_DEST;        
      RETORNO(RETORNO.COUNT).ALIQUOTA_PROVISORIA_PARTILHA := IMPOSTO.ALIQUOTA_PROVISORIA_PARTILHA;
      RETORNO(RETORNO.COUNT).VALOR_FC_POBREZA := IMPOSTO.VALOR_FC_POBREZA;
      RETORNO(RETORNO.COUNT).VALOR_ICMS_PART_DEST := IMPOSTO.VALOR_ICMS_PART_DEST;
      RETORNO(RETORNO.COUNT).VALOR_ICMS_PART_REM := IMPOSTO.VALOR_ICMS_PART_REM; 
      RETORNO(RETORNO.COUNT).VALOR_PRESTACAO_SERVICO := IMPOSTO.VALOR_PRESTACAO_SERVICO;
      RETORNO(RETORNO.COUNT).VALOR_A_RECEBER := IMPOSTO.VALOR_A_RECEBER;         
	  RETORNO(RETORNO.COUNT).CODBENEFICIOFISCAL := IMPOSTO.CODBENEFICIOFISCAL;   
      
   END LOOP;
   RETURN RETORNO;

EXCEPTION
  WHEN OTHERS THEN  
    raise_application_error(-20001, 'Erro motivo: ' || SQLERRM || '. Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END; 