CREATE OR REPLACE VIEW SQL_NFE_CABECALHO_ENTRADA_DEV AS 
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO
      ,PCNFENT.CHAVENFE
      ,NVL(PCNFENT.NUMVIAS,
           0) + 1 AS NUM_IMPRESSAO
      ,PCNFENT.CODCONT
      ,0 AS MOVIMENTO
      ,NVL(PCNFENT.TIPOEMISSAO,
           '0') AS TIPO_EMISSAO
      ,PCFILIAL.CODIGO AS CODIGO_FILIAL
      ,NVL(PCNFENT.RECIBODPEC,
           PCNFENT.PROTOCOLONFE) AS PROTOCOLONFE
      ,NVL(PCNFENT.DTHORARECIBODPEC,
           NVL(PCNFENT.DTHORAAUTORIZACAOSEFAZ,
               PCNFENT.DTHORANFE)) AS DTHORA_AUTORIZACAO
      ,DECODE(NVL(PCNFENT.TIPOIMPRESSAO, NVL(PCFILIAL.TIPODANFE, 'R')),
              'R',
              '1',
              '2') AS TIPO_DANFE
      ,(SELECT PCESTCOM.NUMTRANSVENDA
        FROM   PCESTCOM
        WHERE  PCESTCOM.NUMTRANSENT = PCNFENT.NUMTRANSENT) NUM_TRANSACAO_DEV
      ,'2' AS TIPO_PGTO
      ,NVL(REPLACE(TRANSLATE(PCNFENT.SERIE,
                             TRIM(TRANSLATE(PCNFENT.SERIE,
                                            '1234567890',
                                            ' ')) || ' ',
                             ' '),
                   ' ',
                   ''),
           '') SERIE
      ,NVL(REPLACE(TRANSLATE(PCFILIAL.SERIENFESCAN,
                             TRANSLATE(PCFILIAL.SERIENFESCAN,
                                       '1234567890',
                                       ' '),
                             ' '),
                   ' ',
                   ''),
           '0') SERIE_SCAN
      ,PCNFENT.DTEMISSAO AS DATA_EMISSAO
      ,PCNFENT.DTSAIDA AS DATA_SAIDA
      ,NULL AS DATA_SAIDA_DANFE
      ,CASE WHEN NVL(PCNFENT.FINALIDADENFE, 'N') = 'A' THEN
             NULL --Nota de ajuste não pode ter data de saída de entrega preenchida
         ELSE
             DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ENVIARDATAENTREGAXML', PCFILIAL.CODIGO), 'S'),
                    'S',
                    PCNFENT.DTENT,
                    NULL)
       END AS DATA_ENTREGA        
      ,PCNFENT.NUMNOTA AS NUMERO_NOTA
      ,DECODE (PCNFENT.FINALIDADENFE, 'A', PCNFENT.NATOPERNFE,(SELECT NVL(MAX(PCCFO.DESCCFO),
                   '') DESCCFO
        FROM   PCCFO
              ,PCMOV
        WHERE  PCMOV.CODFISCAL = PCCFO.CODFISCAL
        AND    PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT)) AS NATUREZA_OP
       -----------------------EMITENTE-----------------------
      ,EMITENTE.CGC AS CNPJ_E
      ,EMITENTE.FORNECEDOR AS RAZAO_SOCIAL_E
      ,EMITENTE.FANTASIA AS NOME_FANTASIA_E
      ,EMITENTE.ENDER AS LOGRADOURO_E
      ,NVL(EMITENTE.NUMEROEND,
           'S\N') AS NUMERO_E
      ,EMITENTE.COMPLEMENTOEND AS COMPLEMENTO_E
      ,EMITENTE.BAIRRO AS BAIRRO_E
      ,NVL(CIDADE_E.CODIBGE,
           0) AS CODIGO_MUNICIPIO_E
      ,CIDADE_E.NOMECIDADE AS NOME_MUNICIPIO_E
      ,UF_E.UF AS SIGLA_UF_E
      ,NVL(PAIS_E.CODPAIS,
           0) AS CODIGO_PAIS_E
      ,PAIS_E.DESCRICAO AS PAIS_E
      ,EMITENTE.CEP AS CEP_E
      ,EMITENTE.TELFAB AS TELEFONE_E
      ,EMITENTE.IE AS INSCRICAO_ESTADUAL_E
      ,NVL((SELECT PCINSCRICAOST.IESUBSTTRIBUT
           FROM   PCINSCRICAOST
           WHERE  PCINSCRICAOST.CODFILIAL = PCFILIAL.CODIGO
           AND    PCINSCRICAOST.UF = UF_D.UF
           AND    ROWNUM = 1),
           UF_D.IESUBSTTRIBUT) AS INSCRICAO_SUBSTITUTO_E
      ,EMITENTE.INSCMUNICIP AS INSCRICAO_MUNICIPAL_E
      ,EMITENTE.CAE AS CNAE_E
      ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('FIL_OPTANTESIMPLESNAC',
                                                PCFILIAL.CODIGO),
                  'N'),
              'N',
              3,
              'S',
              1,
              'E',
              2,
              3) CRT
       -----------------------DESTINATARIO---------------------
       --Removida validação conforme solicitação HIS.01620.2016
      /*,CASE WHEN (NVL(PCNFENT.AMBIENTENFE,
                      PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE', 
                                                    PCFILIAL.CODIGO)) = 'P') THEN PCNFENT.CGC
       ELSE CASE WHEN (NVL(PCNFENT.AMBIENTENFE,
                           PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE', 
                                                    PCFILIAL.CODIGO)) = 'H' AND PCNFENT.DTSAIDA >= TO_DATE('01-05-2011', 'DD-MM-YYYY')) THEN '99.999.999/0001-91'
          ELSE PCNFENT.CGC
          END
       END*/ 
      ,PCNFENT.CGC AS CNPJ_CPF_D
      ,CASE WHEN (NVL(PCNFENT.AMBIENTENFE,
                      PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE', 
                                                    PCFILIAL.CODIGO)) = 'P') THEN PCNFENT.FORNECEDOR
       ELSE CASE WHEN (NVL(PCNFENT.AMBIENTENFE,
                           PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE', 
                                                    PCFILIAL.CODIGO)) = 'H' AND PCNFENT.DTSAIDA >= TO_DATE('01-05-2011', 'DD-MM-YYYY')) 
                                                    THEN 'NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL' 
       ELSE PCNFENT.FORNECEDOR
       END
       END AS RAZAO_SOCIAL_D
      ,NVL(PCNFENT.FORNECEDOR,
           DESTINATARIO.FANTASIA) AS NOME_FANTASIA_D
      ,PCNFENT.ENDERECO AS LOGRADOURO_D
      ,NVL(PCNFENT.NUMEROEND,
           'S\N') AS NUMERO_D
      ,DESTINATARIO.COMPLEMENTOENT AS COMPLEMENTO_D
      ,PCNFENT.BAIRRO AS BAIRRO_D
      ,NVL(PCNFENT.CODIBGE,0) AS CODIGO_MUNICIPIO_D
      ,CIDADE_D.NOMECIDADE AS NOME_MUNICIPIO_D
      ,PCNFENT.UF AS SIGLA_UF_D
      ,PCNFENT.CEP AS CEP_D
      ,PCNFENT.CODPAIS AS CODIGO_PAIS_D
      ,PCNFENT.DESCPAIS AS PAIS_D
      ,PCNFENT.TELEFONE AS TELEFONE_D
      ----------------------------------------------------------
      -------------------------ENTREGA--------------------------
      ,NULL AS CNPJ_CPF_ENT
      ,NULL AS LOGRADOURO_ENT
      ,NULL AS NUMERO_ENT
      ,NULL AS COMPLEMENTO_ENT
      ,NULL AS BAIRRO_ENT
      ,NULL AS CODIGO_MUNICIPIO_ENT
      ,NULL AS NOME_MUNICIPIO_ENT
      ,NULL AS SIGLA_UF_ENT
      ----------------------------------------------------------
      ------------------------RETIRADA--------------------------
      ,PCNFENT.CGC AS CNPJ_CPF_RET           
      ,ENT.ENDERENT AS LOGRADOURO_RET           
      ,ENT.NUMEROENT AS NUMERO_RET                 
      ,ENT.COMPLEMENTOENT AS COMPLEMENTO_RET       
      ,ENT.BAIRROENT AS BAIRRO_RET                        
      ,CID_ENT.CODIBGE AS CODIGO_MUNICIPIO_RET             
      ,SUBSTR(ENT.MUNICENT,1,60) AS NOME_MUNICIPIO_RET     
      ,ENT.ESTENT AS SIGLA_UF_RET                 
      ,ENT.CEPRECEBEDOR AS CEP_RET                      
      ,ENT.IERECEBEDOR AS INSCRICAO_ESTADUAL_RET         
      ,ENT.FONERECEBEDOR AS TELEFONE_RET            
      ,ENT.CODPAISRECEBEDOR AS CODIGO_PAIS_RET
      ,ENT.RAZAORECEBEDOR AS RAZAO_SOCIAL_RET
      ,ENT.EMAILRECEBEDOR AS EMAIL_RET         
      ,PAIS_ENT.DESCRICAO AS PAIS_RET
      ---------------------------------------------------------
      ,CASE WHEN (PCNFENT.UF = 'EX') THEN 
                 '' 
       ELSE
            CASE WHEN (NVL(DESTINATARIO.CONTRIBUINTE, '') = 'N' AND ((UPPER(PCNFENT.IE) LIKE '%ISENT%'))) THEN
                 ''        
            ELSE 
                 PCNFENT.IE
            END
       END AS INSCRICAO_ESTADUAL_D
      ,PCNFENT.EMAILDEST AS EMAIL_D
      ,PCNFENT.SULFRAMA INSCRICAO_SUFRAMA_D
      ,PCNFENT.TIPODESCARGA
      ,NULL AS CONDVENDA
      ,PCNFENT.CODEXPORTADOR AS CODIGO_EXPORTADOR
      ,PCNFENT.CODEXPORTADOR AS CODIGO_FABRICANTE_EX
      ,(SELECT NVL(MAX(PCCFO.CODFISCAL),
                   '')
        FROM   PCCFO
              ,PCMOV
        WHERE  PCMOV.CODFISCAL = PCCFO.CODFISCAL
        AND    PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT) AS CODIGO_FISCAL
      ,PCNFENT.DATADIIMPORTACAO AS DATA_DESEMBARACO
      ,EMITENTE.EMAIL AS EMAIL_E
      ,(EMITENTE.ENDER || ' - ' || NVL(EMITENTE.NUMEROEND,
                                       'S/N') || ' - ' || EMITENTE.BAIRRO ||
       ' - ' || CIDADE_E.NOMECIDADE || ' - ' || UF_E.UF || ' - ' ||
       EMITENTE.CEP) AS ENDERECO
      ,PCNFENT.ESPECIE
      ,EMITENTE.FAXFAB AS FAX_E
      ,(NVL(PCNFENT.HORALANC,'00') || ':' || NVL(PCNFENT.MINUTOLANC,'00')) HORA
      ,PCNFENT.LOCALDESEMBARACO AS LOCAL_DESEMBARACO
      ,PCNFENT.UFDESEMBARACO AS SIGLA_UF_DESEMBARACO
      ,PCNFENT.NUMDIIMPORTACAO AS NUM_DOC_IMPORTACAO
      ,0 AS NUM_PEDIDO
      ,0 AS RCA
      ,'' AS NUM_PEDIDO_CLI
      ,'' AS TIPO_COBRANCA
      ,0 AS NUMERO_CAR
      ,DESTINATARIO.CODCLI AS CODIGO_CLI
      ,'N' AS ORGAO_PUBLICO
      ,PCFILIAL.CODDOCNF AS CODDOC
      ,'' AS TIPO_EMPRESA
      ,'J' AS TIPO_PESSOA
      ,NULL AS NUM_TRANSACAO_ORIG
      ,DECODE(NVL(PCNFENT.AMBIENTENFE,
                  'X'),
              'H',
              2,
              'P',
              1,
              -1) AS AMBIENTE
      ,NVL(PCNFENT.SITUACAONFE,
           0) AS SITUACAONFE
      ,NVL(DESTINATARIO.CONSUMIDORFINAL,
           'N') AS CONSUMIDOR_FINAL
      ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('SERIALCERTIFICADO',
                                         PCFILIAL.CODIGO),
           '') AS SERIALCERTIFICADO
      ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PINCERTIFICADO',
                                         PCFILIAL.CODIGO),
           '') AS PINCERTIFICADO
      ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PROVIDERCERTIFICADOA3',
                                         PCFILIAL.CODIGO),
           'SafeSign Standard Cryptographic Service Provider') AS PROVIDERCERTIFICADOA3
      ,NVL(PARAMFILIAL.OBTERCOMONUMBER('TIPOPROVIDERA3',
                                       PCFILIAL.CODIGO),
           1) AS TIPOPROVIDERA3
      ,
       CASE
         WHEN ((((SELECT CODPROD
                FROM   PCMOV
                WHERE  PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
                AND    ROWNUM = 1) IS NULL)
              AND (PCNFENT.NUMTRANSORIGEM > 0) OR PCNFENT.FINALIDADENFE = 'C') and (PCNFENT.FINALIDADENFE <> 'A')) THEN
          2
         ELSE
         CASE WHEN (FINALIDADENFE = 'A') THEN
         3
         ELSE
          1
          END
       END AS FINALIDADE
      ,PCNFENT.DTAHORAENTRADACONTIGENCIA AS DTHORA_CONTINGENCIA
      ,PCNFENT.JUSTIFICATIVACONTIGENCIA AS JUSTIFICATIVA
      ,'' AS DESTINOCARGA
      ,'' AS NUMPEDRCA
      ,PCNFENT.MOTESTORNONFE AS MOT_ESTORNONFE
      ,PCNFENT.SITUACAONFEEPEC AS SITUACAO_NFE_EPEC
      ,NVL(DESTINATARIO.CONTRIBUINTE, '') CONTRIBUINTE
      ,NVL(PCNFENT.QTDEREPROCNFE, 0) AS QTD_REPROCESSAMENTO_NFE
      ,NULL AS CODCOBSEFAZ
      ,PCNFENT.NUMEMPENHO
      ,NULL AS UTILIZASRVTERCEIROS
      ,'N' AS ENVIADASEMRESPOSTA
      ,DESTINATARIO.IDENTIFICESTRANG AS IDESTRANGEIRO
      ,PCNFENT.CODIGONUMERICOCHAVE AS CODIGO_NUMERICO_CHAVE
      ,NVL(PCNFENT.TIPOPRESENCAADQUIRINTE, '1') AS INDICADOR_PRESENCA      
      ,PCNFENT.DESCINTERMEDIADOR
      ,PCNFENT.CNPJINTERMEDIADOR      
FROM   PCNFENT
      ,PCFILIAL
       --EMITENTE
      ,PCFORNEC EMITENTE
      ,PCPAIS   PAIS_E
      ,PCCIDADE CIDADE_E
      ,PCESTADO UF_E
       --DESTINATARIO
      ,PCCLIENT DESTINATARIO
      ,PCPAIS PAIS_D
      ,PCCIDADE CIDADE_D
      ,PCESTADO UF_D
      --RETIRA
      ,PCCLIENTENDENT ENT
      ,PCCIDADE CID_ENT
      ,PCPAIS PAIS_ENT
WHERE  EMITENTE.CODFORNEC = PCFILIAL.CODFORNEC
      --EMITENTE
AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE(+)
AND    CIDADE_E.UF = UF_E.UF(+)
AND    UF_E.CODPAIS = PAIS_E.CODPAIS(+)
      --DESTINATARIO
AND    DESTINATARIO.CODCLI = NVL(PCNFENT.CODFORNECNF,
                                 PCNFENT.CODFORNEC)
AND    PCNFENT.CODMUNICIPIO = CIDADE_D.CODCIDADE(+)
AND    CIDADE_D.UF = UF_D.UF(+)
AND    UF_D.CODPAIS = PAIS_D.CODPAIS(+)
AND    NVL(PCNFENT.CODFILIALNF,
           PCNFENT.CODFILIAL) = PCFILIAL.CODIGO
      --RETIRA
AND    PCNFENT.CODENDENTCLI = ENT.CODENDENTCLI(+)
AND    PCNFENT.CODFORNEC = ENT.CODCLI(+)       
AND    ENT.CODCIDADE = CID_ENT.CODCIDADE(+)
AND    ENT.CODPAISRECEBEDOR = PAIS_ENT.CODPAIS(+)
  
AND    ((NVL(PCFILIAL.UTILIZANFE, 'N') = 'S') OR
        (NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZASRVTERCEIROS', PCFILIAL.CODIGO), 'N') = 'S'))  
AND    NVL(PCNFENT.OBS, ' ') <> 'NF CANCELADA'
AND    NVL(PCNFENT.GERANFDEVCLI, 'N') = 'S'
AND    PCNFENT.ESPECIE IN ('NF', 'NE', 'EI')
--Linhas abaixo sevem para obedecer a ordem de numeração das notas fiscais no processo de Adjudicação
AND    ( (NVL(PCNFENT.NUMTRANSENTDEPENDENTE,-1) = -1) OR EXISTS (SELECT 1 FROM PCNFENT E WHERE E.NUMTRANSENT = PCNFENT.NUMTRANSENTDEPENDENTE AND E.SITUACAONFE = 100))
AND    (( NVL(PCNFENT.NUMTRANSVENDADEPENDENTE,-1) = -1 ) OR (EXISTS (SELECT 1 FROM PCNFSAID S WHERE S.NUMTRANSVENDA = PCNFENT.NUMTRANSVENDADEPENDENTE AND S.SITUACAONFE = 100)))
ORDER  BY NUMERO_NOTA