CREATE OR REPLACE VIEW SQL_NFE_PARCELA_ENTRADA AS
SELECT PCLANC.NUMTRANSENT AS NUM_TRANSACAO,
       PCLANC.DTVENC,
       (TO_CHAR(PCLANC.NUMNOTA) || ' - ' || TO_CHAR(PCLANC.DUPLIC)) AS PRESTACAO,
       PCLANC.VALOR,
       '' AS CODCOB,
       0 AS VALORDESC,
       PCLANC.NUMNOTA,
       PCLANC.DUPLIC,
       PCLANC.CODCOBSEFAZ,
       PCLANC.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       PCLANC.NSUTEF AS NUMAUTOR_CARTAO,
       PCLANC.BANDEIRACARTAO AS BANDEIRA_CARTAO,
       0 INDPAG       
FROM   PCLANC
WHERE  NVL(PCLANC.VALOR, 0) > 0
   AND NVL(PCLANC.NUMNOTA, 0) > 0
   AND (SELECT SUBSTR(VERSAO,1,3) FROM PCVERSAOBD WHERE UPPER(ROTINA) = 'SERVIDORNFE310') <> '1.3'

UNION

--notas de entrada de produtor rural
SELECT PCLANC.NUMTRANSENT AS NUM_TRANSACAO,
       PCLANC.DTVENC,
       (TO_CHAR(PCLANC.NUMNOTA) || ' - ' || TO_CHAR(PCLANC.DUPLIC)) AS PRESTACAO,
       PCLANC.VALOR,
       '' AS CODCOB,
       0 AS VALORDESC,
       PCLANC.NUMNOTA,
       PCLANC.DUPLIC,
       PCLANC.CODCOBSEFAZ,
       PCLANC.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       PCLANC.NSUTEF AS NUMAUTOR_CARTAO,
       PCLANC.BANDEIRACARTAO AS BANDEIRA_CARTAO,
       0 AS INDPAG
FROM   PCLANC,
       PCNFENT
WHERE  NVL(PCLANC.VALOR, 0) > 0
   AND NVL(PCLANC.NUMNOTA, 0) > 0
   AND PCNFENT.CODCONT = PCLANC.CODCONTA
   AND PCNFENT.NUMTRANSENT = PCLANC.NUMTRANSENT
   AND PCNFENT.ESPECIE IN ('NE', 'NF')
   AND (SELECT SUBSTR(VERSAO,1,3) FROM PCVERSAOBD WHERE UPPER(ROTINA) = 'SERVIDORNFE310') = '1.3'
ORDER  BY PRESTACAO 