
/* Popular tabela PCTIPOCONTROLECONSINCO */
CREATE OR REPLACE VIEW VW_INT_TIPOPROCESSOPDVSUP AS (
SELECT 1 ID, 'tb_pessoa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 2 ID, 'tb_cliente' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 3 ID, 'tb_grupopessoa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 4 ID, 'tb_pessoagrupo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 5 ID, 'tb_segmento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 6 ID, 'tb_empresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 7 ID, 'tb_empresasegmento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 8 ID, 'tb_famgrupo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 9 ID, 'tb_marca' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 10 ID, 'tb_familia' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 11 ID, 'tb_produto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 12 ID, 'tb_formapagtoespecie' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 13 ID, 'tb_clientesegmento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 14 ID, 'tb_formapagto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 15 ID, 'tb_formapagtoempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 16 ID, 'tb_famsegmento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 17 ID, 'tb_divisao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 18 ID, 'tb_categoria' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 19 ID, 'tb_famdivisaocategoria' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 20 ID, 'tb_prodempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 21 ID, 'tb_famembalagem' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 22 ID, 'tb_prodcodigo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 23 ID, 'tb_prodpreco' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 24 ID, 'tb_tributacao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 25 ID, 'tb_tributacaouf' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 26 ID, 'tb_enderecoalternativo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 27 ID, 'tb_famdivisao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 28 ID, 'tb_cargatributaria' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 29 ID, 'tb_condicaopagto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 30 ID, 'tb_codgeraloper' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 31 ID, 'tb_codgeralopercfop' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 32 ID, 'tb_regraincentivo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 33 ID, 'tb_regraincentperiodo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 34 ID, 'tb_regraempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 35 ID, 'tb_regrasegmento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 36 ID, 'tb_regraproduto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 37 ID, 'tb_regracliente' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 38 ID, 'tb_regracategoria' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 39 ID, 'tb_regrapessoagrupo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 40 ID, 'tb_combo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 41 ID, 'tb_comboempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 42 ID, 'tb_comboitem' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 43 ID, 'tb_combogrupo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 44 ID, 'tb_parcelamento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 45 ID, 'tb_parcempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 46 ID, 'tb_parcperiodo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 47 ID, 'tb_parcfamformapagto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 48 ID, 'tb_usuario' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 49 ID, 'tb_grupo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 50 ID, 'tb_grupousuario' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 51 ID, 'tb_prodprecoapartir' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 52 ID, 'tb_promsurpresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 53 ID, 'tb_promsurpresaempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 54 ID, 'tb_promsurpresaperiodo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 55 ID, 'tb_promsurpresaitem' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 56 ID, 'tb_promsurpresagrupo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 57 ID, 'tb_cadobs' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 58 ID, 'tb_cadobssped' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 59 ID, 'tb_cadobsspedfamilia' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 60 ID, 'tb_especiefinanceira' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 61 ID, 'tb_prodcomposto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 62 ID, 'tb_precoapartir' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 63 ID, 'tb_precoapartirpessoa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 64 ID, 'tb_precoapartirempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 65 ID, 'tb_precoapartirperiodo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 66 ID, 'tb_precoapartirsegmento' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 67 ID, 'tb_precoapartirproduto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 68 ID, 'tb_limitevenda' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 69 ID, 'tb_limitevendaperiodo' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 70 ID, 'tb_limitevendaempresa' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 71 ID, 'tb_limitevendafamilia' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 72 ID, 'tb_clientecredito' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 73 ID, 'tb_clientecartao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 74 ID, 'tb_bincartao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 75 ID, 'tb_regraformapagto' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 76 ID, 'tb_convenioperiodo' DESCRICAO FROM PCCONSUM
UNION ALL 
SELECT 77 ID, 'tb_formapagtobincartao' DESCRICAO FROM PCCONSUM
UNION ALL 
SELECT 78 ID, 'tb_cartaopresente' DESCRICAO FROM PCCONSUM
UNION ALL 
SELECT 79 ID, 'tb_local' DESCRICAO FROM PCCONSUM
UNION ALL 
SELECT 80 ID, 'tb_loteestoque' DESCRICAO FROM PCCONSUM
UNION ALL 
SELECT 81 ID, 'tb_cctcenario' DESCRICAO FROM PCCONSUM
UNION ALL 
SELECT 82 ID, 'tb_cctcondicao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 83 ID, 'tb_cctcenariocondicao' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 84 ID, 'tb_cctcenariocondicaoitem' DESCRICAO FROM PCCONSUM
UNION ALL
SELECT 85 ID, 'tb_cctimposto' DESCRICAO FROM PCCONSUM
)

\

BEGIN
  MERGE INTO PCTIPOPROCESSOCONSINCO C
    USING (SELECT ID,
 				  DESCRICAO
		     FROM VW_INT_TIPOPROCESSOPDVSUP) T
    ON (T.ID = C.ID )
  WHEN MATCHED THEN
    UPDATE SET 
      C.DESCRICAO = T.DESCRICAO
  WHEN NOT MATCHED THEN
    INSERT(
     C.ID,
	 C.DESCRICAO
    )
    VALUES(
     T.ID,
	 T.DESCRICAO
    );
	
	COMMIT;
	
END;

\

/* Popular tabela PCCONTROLECONSINCO */
CREATE OR REPLACE VIEW VW_INT_CONTROLEPDVSUP AS (

SELECT 1 ID, 1 CODPROCESSO, 'Sincronização de tabela TB_PESSOA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_pessoa' OBJETOREFERENCIA, 1 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 2 ID, 2 CODPROCESSO, 'Sincronização de tabela TB_CLIENTE' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cliente' OBJETOREFERENCIA, 2 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 3 ID, 3 CODPROCESSO, 'Sincronização de tabela TB_GRUPOPESSOA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_GRUPOPESSOA' OBJETOREFERENCIA, 3 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 4 ID, 4 CODPROCESSO, 'Sincronização de tabela TB_PESSOAGRUPO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_PESSOAGRUPO' OBJETOREFERENCIA, 4 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 5 ID, 5 CODPROCESSO, 'Sincronização de tabela TB_SEGMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_segmento' OBJETOREFERENCIA, 3 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 6 ID, 6 CODPROCESSO, 'Sincronização de tabela TB_EMPRESA' DESCRICAO,  TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_empresa' OBJETOREFERENCIA, 6 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 7 ID, 7 CODPROCESSO, 'Sincronização de tabela TB_EMPRESASEGMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_empresasegmento' OBJETOREFERENCIA, 7 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 8 ID, 8 CODPROCESSO, 'Sincronização de tabela TB_FAMGRUPO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_famgrupo' OBJETOREFERENCIA, 8 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 9 ID, 9 CODPROCESSO, 'Sincronização de tabela TB_MARCA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_marca' OBJETOREFERENCIA, 9 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 10 ID, 10 CODPROCESSO, 'Sincronização de tabela TB_FAMILIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_familia' OBJETOREFERENCIA, 10 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 11 ID, 11 CODPROCESSO, 'Sincronização de tabela TB_PRODUTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_produto' OBJETOREFERENCIA, 12 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 12 ID, 12 CODPROCESSO, 'Sincronização de tabela TB_FORMAPAGTOESPECIE' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_formapagtoespecie' OBJETOREFERENCIA, 17 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 13 ID, 13 CODPROCESSO, 'Sincronização de tabela TB_CLIENTESEGMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_clientesegmento' OBJETOREFERENCIA, 4 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 14 ID, 14 CODPROCESSO, 'Sincronização de tabela TB_FORMAPAGTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_formapagto' OBJETOREFERENCIA, 18 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 15 ID, 15 CODPROCESSO, 'Sincronização de tabela TB_FORMAPAGTOEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_formapagtoempresa' OBJETOREFERENCIA, 19 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 16 ID, 16 CODPROCESSO, 'Sincronização de tabela TB_FAMSEGMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_famsegmento' OBJETOREFERENCIA, 16 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 17 ID, 17 CODPROCESSO, 'Sincronização de tabela TB_DIVISAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_divisao' OBJETOREFERENCIA, 5 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 18 ID, 18 CODPROCESSO, 'Sincronização de tabela TB_CATEGORIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_categoria' OBJETOREFERENCIA, 20 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 19 ID, 19 CODPROCESSO, 'Sincronização de tabela TB_FAMDIVISAOCATEGORIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_famdivisaocategoria' OBJETOREFERENCIA, 21 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 20 ID, 20 CODPROCESSO, 'Sincronização de tabela TB_PRODEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_prodempresa' OBJETOREFERENCIA, 13 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 21 ID, 21 CODPROCESSO, 'Sincronização de tabela TB_FAMEMBALAGEM' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_famembalagem' OBJETOREFERENCIA, 11 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 22 ID, 22 CODPROCESSO, 'Sincronização de tabela TB_PRODCODIGO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_prodcodigo' OBJETOREFERENCIA, 14 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 23 ID, 23 CODPROCESSO, 'Sincronização de tabela TB_PRODPRECO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_prodpreco' OBJETOREFERENCIA, 15 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 24 ID, 24 CODPROCESSO, 'Sincronização de tabela TB_TRIBUTACAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_tributacao' OBJETOREFERENCIA, 24 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 25 ID, 25 CODPROCESSO, 'Sincronização de tabela TB_TRIBUTACAOUF' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_tributacaouf' OBJETOREFERENCIA, 25 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 26 ID, 26 CODPROCESSO, 'Sincronização de tabela TB_ENDERECOALTERNATIVO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_enderecoalternativo' OBJETOREFERENCIA, 26 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 27 ID, 27 CODPROCESSO, 'Sincronização de tabela TB_FAMDIVISAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_famdivisao' OBJETOREFERENCIA, 27 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 28 ID, 28 CODPROCESSO, 'Sincronização de tabela TB_CARGATRIBUTARIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cargatributaria' OBJETOREFERENCIA,  28 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM 
UNION ALL
SELECT 29 ID, 29 CODPROCESSO, 'Sincronização de tabela TB_CONDICAOPAGTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_condicaopagto' OBJETOREFERENCIA,  29 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 30 ID, 30 CODPROCESSO, 'Sincronização de tabela TB_CODGERALOPER' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_codgeraloper' OBJETOREFERENCIA,  30 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 31 ID, 31 CODPROCESSO, 'Sincronização de tabela TB_CODGERALOPERCFOP' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_codgeralopercfop' OBJETOREFERENCIA,  31 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 32 ID, 32 CODPROCESSO, 'Sincronização de tabela TB_REGRAINCENTIVO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regraincentivo' OBJETOREFERENCIA,  32 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 33 ID, 33 CODPROCESSO, 'Sincronização de tabela TB_INCENTIVOPERIODO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regraincentperiodo' OBJETOREFERENCIA,  33 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 34 ID, 34 CODPROCESSO, 'Sincronização de tabela TB_REGRAEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regraempresa' OBJETOREFERENCIA,  34 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 35 ID, 35 CODPROCESSO, 'Sincronização de tabela TB_REGRASEGMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regrasegmento' OBJETOREFERENCIA,  35 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 36 ID, 36 CODPROCESSO, 'Sincronização de tabela TB_REGRAPRODUTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regraproduto' OBJETOREFERENCIA,  36 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 37 ID, 37 CODPROCESSO, 'Sincronização de tabela TB_REGRACLIENTE' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regracliente' OBJETOREFERENCIA,  37 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 38 ID, 38 CODPROCESSO, 'Sincronização de tabela TB_REGRACATEGORIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regracategoria' OBJETOREFERENCIA,  38 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 39 ID, 39 CODPROCESSO, 'Sincronização de tabela TB_REGRAPESSOAGRUPO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regrapessoagrupo' OBJETOREFERENCIA,  39 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 40 ID, 40 CODPROCESSO, 'Sincronização de tabela TB_COMBO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_combo' OBJETOREFERENCIA,  40 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 41 ID, 41 CODPROCESSO, 'Sincronização de tabela TB_COMBOEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_comboempresa' OBJETOREFERENCIA,  41 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 42 ID, 42 CODPROCESSO, 'Sincronização de tabela TB_COMBOITEM' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_comboitem' OBJETOREFERENCIA,  42 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 43 ID, 43 CODPROCESSO, 'Sincronização de tabela TB_COMBOGRUPO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_combogrupo' OBJETOREFERENCIA,  43 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 44 ID, 44 CODPROCESSO, 'Sincronização de tabela TB_PARCELAMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_parcelamento' OBJETOREFERENCIA,  44 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 45 ID, 45 CODPROCESSO, 'Sincronização de tabela TB_PARCEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_parcempresa' OBJETOREFERENCIA,  45 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 46 ID, 46 CODPROCESSO, 'Sincronização de tabela TB_PARCPERIODO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_parcperiodo' OBJETOREFERENCIA,  46 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 47 ID, 47 CODPROCESSO, 'Sincronização de tabela TB_PARCFAMFORMAPAGTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_parcfamformapagto' OBJETOREFERENCIA,  47 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) FROM PCCONSUM
UNION ALL
SELECT 48 ID, 48 CODPROCESSO, 'Sincronização de tabela TB_USUARIO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_usuario' OBJETOREFERENCIA,  48 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 49 ID, 49 CODPROCESSO, 'Sincronização de tabela TB_GRUPO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_grupo' OBJETOREFERENCIA,  49 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 50 ID, 50 CODPROCESSO, 'Sincronização de tabela TB_GRUPOUSUARIO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_grupousuario' OBJETOREFERENCIA,  50 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 51 ID, 51 CODPROCESSO, 'Sincronização de tabela TB_PRODPRECOAPARTIR' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_prodprecoapartir' OBJETOREFERENCIA,  51 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 52 ID, 52 CODPROCESSO, 'Sincronização de tabela TB_PROMSURPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_promsurpresa' OBJETOREFERENCIA,  52 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 53 ID, 53 CODPROCESSO, 'Sincronização de tabela TB_PROMSURPRESAEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_promsurpresaempresa' OBJETOREFERENCIA,  53 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 54 ID, 54 CODPROCESSO, 'Sincronização de tabela TB_PROMSURPRESAPERIODO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_promsurpresaperiodo' OBJETOREFERENCIA,  54 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 55 ID, 55 CODPROCESSO, 'Sincronização de tabela TB_PROMSURPRESAITEM' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_promsurpresaitem' OBJETOREFERENCIA,  55 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 56 ID, 56 CODPROCESSO, 'Sincronização de tabela TB_PROMSURPRESAGRUPO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_promsurpresagrupo' OBJETOREFERENCIA,  56 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 57 ID, 57 CODPROCESSO, 'Sincronização de tabela TB_CADOBS' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cadobs' OBJETOREFERENCIA,  57 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 58 ID, 58 CODPROCESSO, 'Sincronização de tabela TB_CADOBSSPED' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cadobssped' OBJETOREFERENCIA,  58 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 59 ID, 59 CODPROCESSO, 'Sincronização de tabela TB_CADOBSSPEDFAMILIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cadobsspedfamilia' OBJETOREFERENCIA,  59 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 60 ID, 60 CODPROCESSO, 'Sincronização de tabela TB_ESPECIEFINANCEIRA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_especiefinanceira' OBJETOREFERENCIA,  60 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 61 ID, 61 CODPROCESSO, 'Sincronização de tabela TB_PRODCOMPOSTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_prodcomposto' OBJETOREFERENCIA,  61 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 62 ID, 62 CODPROCESSO, 'Sincronização de tabela TB_PRECOAPARTIR' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_precoapartir' OBJETOREFERENCIA,  62 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 63 ID, 63 CODPROCESSO, 'Sincronização de tabela TB_PRECOAPARTIRPESSOA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_precoapartirpessoa' OBJETOREFERENCIA, 63 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 64 ID, 64 CODPROCESSO, 'Sincronização de tabela TB_PRECOAPARTIREMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_precoapartirempresa' OBJETOREFERENCIA, 64 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 65 ID, 65 CODPROCESSO, 'Sincronização de tabela TB_PRECOAPARTIRPERIODO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_precoapartirperiodo' OBJETOREFERENCIA, 65 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 66 ID, 66 CODPROCESSO, 'Sincronização de tabela TB_PRECOAPARTIRSEGMENTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_precoapartirsegment' OBJETOREFERENCIA, 66 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 67 ID, 67 CODPROCESSO, 'Sincronização de tabela TB_PRECOAPARTIRPRODUTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_precoapartirproduto' OBJETOREFERENCIA, 67 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 68 ID, 68 CODPROCESSO, 'Sincronização de tabela TB_LIMITEVENDA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_LIMITEVENDA' OBJETOREFERENCIA, 68 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 69 ID, 69 CODPROCESSO, 'Sincronização de tabela TB_LIMITEVENDAPERIODO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_LIMITEVENDAPERIODO' OBJETOREFERENCIA, 69 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 70 ID, 70 CODPROCESSO, 'Sincronização de tabela TB_LIMITEVENDAEMPRESA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_LIMITEVENDAEMPRESA' OBJETOREFERENCIA, 70 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 71 ID, 71 CODPROCESSO, 'Sincronização de tabela TB_LIMITEVENDAFAMILIA' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_LIMITEVENDAFAMILIA' OBJETOREFERENCIA, 71 PRECEDENCIA, 'A' ATIVO, TRUNC(SYSDATE) DTCRIACAO, TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 72 ID, 72 CODPROCESSO, 'Sincronização de tabela TB_CLIENTECREDITO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_TB_CLIENTECREDITO' OBJETOREFERENCIA,  72 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 73 ID, 73 CODPROCESSO, 'Sincronização de tabela TB_CLIENTECARTAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_clientecartao' OBJETOREFERENCIA,  73 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 74 ID, 74 CODPROCESSO, 'Sincronização de tabela TB_BINCARTAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_bincartao' OBJETOREFERENCIA,  74 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 75 ID, 75 CODPROCESSO, 'Sincronização de tabela TB_REGRAFORMAPAGTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_regraformapagto' OBJETOREFERENCIA,  75 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 76 ID, 76 CODPROCESSO, 'Sincronização de tabela TB_CONVENIOPERIODO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_convenioperiodo' OBJETOREFERENCIA,  76 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 77 ID, 77 CODPROCESSO, 'Sincronização de tabela TB_FORMAPAGTOBINCARTAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_formapagtobincartao' OBJETOREFERENCIA,  77 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 78 ID, 78 CODPROCESSO, 'Sincronização de tabela TB_CARTAOPRESENTE' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cartaopresente' OBJETOREFERENCIA,  78 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 79 ID, 79 CODPROCESSO, 'Sincronização de tabela TB_LOCAL' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_local' OBJETOREFERENCIA,  79 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 80 ID, 80 CODPROCESSO, 'Sincronização de tabela TB_LOTEESTOQUE' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_loteestoque' OBJETOREFERENCIA,  80 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL
SELECT 81 ID, 81 CODPROCESSO, 'Sincronização de tabela TB_CCTCENARIO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cctcenario' OBJETOREFERENCIA,  81 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL 
SELECT 82 ID, 82 CODPROCESSO, 'Sincronização de tabela TB_CCTCONDICAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cctcondicao' OBJETOREFERENCIA,  82 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL 
SELECT 83 ID, 83 CODPROCESSO, 'Sincronização de tabela TB_CCTCENARIOCONDICAO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cctcenariocondicao' OBJETOREFERENCIA,  83 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL 
SELECT 84 ID, 84 CODPROCESSO, 'Sincronização de tabela TB_CCTCENARIOCONDICAOITEM' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cctcenconditem' OBJETOREFERENCIA,  84 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
UNION ALL 
SELECT 85 ID, 85 CODPROCESSO, 'Sincronização de tabela TB_CCTIMPOSTO' DESCRICAO, TRUNC(SYSDATE) ULTIMAEXECUCAO, 'D' TIPO, 'pkg_sinc_PDV_Consinco.carrega_tb_cctimposto' OBJETOREFERENCIA,  85 PRECEDENCIA,  'A' ATIVO,  TRUNC(SYSDATE) DTCRIACAO,  TRUNC(SYSDATE) DTALTERACAO FROM PCCONSUM
)

\

BEGIN
  MERGE INTO PCCONTROLECONSINCO C
    USING (SELECT ID,
    	    CODPROCESSO,
 				  DESCRICAO,
				  ULTIMAEXECUCAO,
				  TIPO,
				  OBJETOREFERENCIA,
				  PRECEDENCIA,
				  ATIVO,
				  DTCRIACAO,
				  DTALTERACAO 
		     FROM VW_INT_CONTROLEPDVSUP) T
    ON (T.ID = C.ID )
  WHEN MATCHED THEN
    UPDATE SET
	       C.DESCRICAO = T.DESCRICAO,
           C.OBJETOREFERENCIA = T.OBJETOREFERENCIA,
           C.PRECEDENCIA = T.PRECEDENCIA,
           C.ULTIMAEXECUCAO = SYSDATE - 10000
    WHERE NVL(UPPER(C.DESCRICAO), 'X') <> NVL(UPPER(T.DESCRICAO), 'X') 	
  WHEN NOT MATCHED THEN
    INSERT(
     C.ID,
	 C.CODPROCESSO,
	 C.DESCRICAO, 
	 C.ULTIMAEXECUCAO,
	 C.TIPO,
	 C.OBJETOREFERENCIA,
	 C.PRECEDENCIA,
	 C.ATIVO, 
	 C.DTCRIACAO, 
	 C.DTALTERACAO
    )
    VALUES(
     T.ID,
	 T.CODPROCESSO,
	 T.DESCRICAO, 
	 T.ULTIMAEXECUCAO,
	 T.TIPO,
	 T.OBJETOREFERENCIA,
	 T.PRECEDENCIA,
	 T.ATIVO, 
	 T.DTCRIACAO, 
	 T.DTALTERACAO
    );
	
	COMMIT;
	
END;
