DECLARE
  CURSOR C_INDEXES IS
    SELECT A.INDEX_NAME
      FROM USER_INDEXES A
     WHERE A.TABLE_NAME = 'PCDOCFISCALNODES'
       AND A.INDEX_TYPE LIKE 'FUNCTION%';
       
  CURSOR C_CONSTRAINT IS
    SELECT C.CONSTRAINT_NAME
         , C.TABLE_NAME
         , C.SEARCH_CONDITION
      FROM USER_CONSTRAINTS C
         , USER_CONS_COLUMNS CC
     WHERE C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
       AND C.TABLE_NAME = 'PCDOCFISCALNODES'
       AND CC.COLUMN_NAME IN ('STATUS', 'PERFIL')
       AND C.CONSTRAINT_TYPE = 'C';    
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE PCDOCFISCALNODES';
   
  FOR C IN C_INDEXES LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP INDEX ' || C.INDEX_NAME;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;   
  END LOOP;
  
  FOR C IN C_CONSTRAINT LOOP
    BEGIN
      IF C.SEARCH_CONDITION LIKE '%STATUS IN%' OR C.SEARCH_CONDITION LIKE '%PERFIL IN%' THEN
         EXECUTE IMMEDIATE 'ALTER TABLE ' || C.TABLE_NAME || ' DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;   
  END LOOP;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCDOCFISCALNODES ADD CONSTRAINT PCDOCFISCALNODES_CK_STATUS CHECK (STATUS IN (''ATIVO'', ''INATIVO''))';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
  
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCDOCFISCALNODES ADD CONSTRAINT PCDOCFISCALNODES_CK_PERFIL CHECK (PERFIL IN (''MASTER'', ''SLAVE''))';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
          
  BEGIN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PCDOCFISCALNODES_UK_UM_MASTER ON PCDOCFISCALNODES (CASE WHEN PERFIL = ''MASTER'' AND STATUS = ''ATIVO'' THEN 1 END)';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END; 
END;
