DECLARE
  VCOUNT INTEGER;
BEGIN
  SELECT COUNT(COLUMN_NAME)
    INTO VCOUNT
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
     AND TABLE_NAME = 'PCDICIONARIOITEMROT'
     AND COLUMN_NAME = 'UTILIZACADASTRODINAMICO';

  IF VCOUNT > 0 THEN
  
  
    UPDATE PCDICIONARIOITEMROT
       SET UTILIZACADASTRODINAMICO = 'N'
     WHERE NOMEOBJETO = 'PCFORNEC'
       AND CODROTINA = 202
       AND NOMECAMPO IN
           ('CODCONTACONTABADIANTFOR', 'CODCONTAINSSTOMADOR',
            'CODCONTASESTSENAT', 'CODCONTAB', 'CODCONTACOFINS',
            'CODCONTACSRF', 'CODCONTAINSS', 'CODCONTAIRRF', 'CODCENTROCUSTO',
            'CODCIDADE', 'CODCONTAISS', 'CODCONTAPIS', 'CODPAIS', 'ADM_UF',
            'COM_UF', 'REP_UF', 'CODDISTRIB', 'ESTADO', 'FORMAPGTO',
            'CODPARCELAFRETEFOB', 'CODPARCELAOUTDESP', 'CODPARCICMSANTECIP',
            'CODPARCELADIFALIQ', 'CODPARCELAFUNRURAL', 'CODPARCELA',
            'CODPARCELASTGUIA');  
  
    UPDATE PCDICIONARIOITEMROT
       SET UTILIZACADASTRODINAMICO = 'S'
     WHERE NOMEOBJETO = 'PCFORNEC'
       AND CODROTINA = 202
       AND NOMECAMPO IN
           ('CODDEPTO');
  
    COMMIT;
  END IF;
END;
