CREATE OR REPLACE VIEW VW_INT_C5_MARCA AS
(
  SELECT DISTINCT
         MARCA.*
  FROM(
        SELECT  DISTINCT 
              m.codmarca     AS seqmarca,
              SUBSTR(m.marca,1,20)    AS marca,
              
              (case 
                when NVL(m.ativo, 'S') = 'N' then
                     'N'
                else 'S'
               end) ativo    
        FROM pcprodut p
        INNER JOIN pcmarca m
        ON m.codmarca = p.codmarca
        AND m.codmarca > 0
  UNION ALL
        SELECT  CODMARCA seqmarca,
                SUBSTR(MARCA,1,20) marca,
                (case 
                 when NVL(ativo, 'S') = 'N' then
                     'N'
                 else 'S'
                 end) ativo
        FROM PCMARCA 
        WHERE CODMARCA > 0
        AND CODMARCA = ferramentas.f_buscarparametro_num('MARCAINTEGRACAOCONSINCO', '99', '1')) MARCA
)

 \

CREATE OR REPLACE VIEW VW_INT_C5_FAMILIA AS
(
SELECT
    DEPARA.SEQFAMILIA,
    TBFAM."CODPROD", TBFAM."CODAUXILIAR",TBFAM."ORIGEM",TBFAM."FAMILIA",TBFAM."CODNCMSH",TBFAM."PERMITEDECIMAL",TBFAM."PERMITEMULTIPLICACAO",TBFAM."CODCEST",TBFAM."ATIVO",TBFAM."SEQMARCA",TBFAM."SEQFAMGRUPO",TBFAM."PESAVEL",TBFAM."INDESCALA",TBFAM."CNPJFABRICANTE",TBFAM."EANTRIB",TBFAM."SEQFAMILIAPRINC",TBFAM."ESTOQUEPORLOTE",
	TBFAM."CHECAPESOETIQUETA"
FROM (
      SELECT
           /*NECESSÁRIO ATRIBUIR ZERO QUANDO O CODAUXILIAR ESTIVER NULO, POIS NA TABELA DEPARACODPRODC5 O CAMPO É PK(NÃO ACEITA NULO)*/
           MIN(PROD.CODPROD) CODPROD,
           (CASE
             WHEN MIN(PROD.CODAUXILIAR) IS NULL THEN
                  0
             ELSE MIN(PROD.CODAUXILIAR)
           END) CODAUXILIAR,
           MIN(PROD.ORIGEM) ORIGEM,
           MIN(PROD.familia) FAMILIA,
           MIN(PROD.codncmsh) codncmsh,
           MIN(PROD.permitedecimal) permitedecimal,
           MIN(PROD.permitemultiplicacao) permitemultiplicacao,
           MIN(PROD.codcest) codcest,
           MIN(PROD.ativo) ativo,
           MIN(PROD.seqmarca) seqmarca,
           MIN(PROD.seqfamgrupo) seqfamgrupo,
           MIN(PROD.PESAVEL) PESAVEL,
           MIN(PROD.indescala) indescala,
           MIN(PROD.cnpjfabricante) cnpjfabricante,
           MIN(PROD.eantrib) eantrib,
           MIN(PROD.Seqfamiliaprinc) Seqfamiliaprinc,
           MIN(PROD.estoqueporlote) estoqueporlote,
		   MIN(PROD.checapesoetiqueta) checapesoetiqueta		   
      FROM (
            /* SELECT ORIGINAL VIEW EMBPROD */
            SELECT DISTINCT
                   p.codprod CODPROD,
                   NULL CODAUXILIAR,
                   MIN(P.CODAUXILIAR) IDREF, /*NECESSÁRIO TRAZER O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'E' ORIGEM,
				   CASE
				     WHEN (SELECT valor FROM pcparametros2651 WHERE nome = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
					   NVL(fnc_remove_char_esp_v2(SUBSTR(p.descricao, 0, 39)), '-')
					 ELSE
					   NVL(fnc_remove_char_esp(SUBSTR(p.descricao, 0, 39)), '-')
				   END as familia,
                   MAX(p.codncmsh) codncmsh,
                   MAX(p.aceitavendafracao) permitedecimal,
                   --MAX(p.permitemultiplicacao) permitemultiplicacao,
                   
                   CASE WHEN (SELECT COUNT(DISTINCT TIPOEMBALAGEM)
                              FROM PCEMBALAGEM
                              WHERE codprod = p.codprod
                              AND tipoembalagem IN ('U', 'P')) > 1 THEN
                          'S'
                        ELSE
                          'N'
                   END PERMITEMULTIPLICACAO,

                   (SELECT nvl(CODCEST, 0) codcest
                    FROM PCCEST INNER JOIN PCCESTPRODUTO ON PCCEST.CODIGO = PCCESTPRODUTO.CODSEQCEST
                    WHERE PCCESTPRODUTO.CODPROD = p.codprod
                    AND ROWNUM = 1
                   ) codcest,
                   'S' ativo,
                   MAX(p.codmarca) seqmarca,
                   1 seqfamgrupo,
                   
                   /*(CASE
                      WHEN  MIN(p.tipoembalagem) = 'P' THEN
                            'S'
                      ELSE  'N'
                   END)PESAVEL,*/

                   CASE
                       WHEN (SELECT COUNT(DISTINCT TIPOEMBALAGEM)
                             FROM PCEMBALAGEM
                             WHERE codprod = p.codprod
                             AND tipoembalagem IN ('U', 'P')) > 1 THEN
                              'N'
                       WHEN  (SELECT COUNT(DISTINCT TIPOEMBALAGEM)
                              FROM PCEMBALAGEM
                              WHERE codprod = p.codprod
                              AND tipoembalagem IN ('P')) = 1 THEN
                                      
                               'S'
                       ELSE
                               'N'
                  END PESAVEL,

                   
                   MIN(NVL(p.indescalarelevante, 'S')) indescala,
                   
				   MAX(
				     CASE
					   WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
					     fnc_remove_char_esp_v2(p.cnpjfabricante) 
					   ELSE
					     fnc_remove_char_esp(p.cnpjfabricante)    
					 END
				   ) as cnpjfabricante,
                   MAX(p.codauxiliartrib) eantrib,
                   MAX(P.codprodprinc) seqfamiliaprinc,
                   MAX(P.estoqueporlote) estoqueporlote,
				   MAX(NVL(p.checapesoetiqueta, 'N')) checapesoetiqueta
            FROM VW_INT_C5_EMBPROD_MAT p
            GROUP BY p.codprod, p.descricao

            UNION ALL

            /* SELECT CUSTOMIZADO PARA TRAZER EMBALAGENS COM O MESMO QTUNIT DESMEMBRADAS */
            SELECT
                   p.codprod CODPROD,
                   p.codauxiliar CODAUXILIAR,
                   p.codauxiliar IDREF, /*NECESSÁRIO REPETIR O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'D' ORIGEM,
                   NVL(
				     CASE
					   WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
					     fnc_remove_char_esp_v2(SUBSTR(p.descricao, 1, 39))
					   ELSE
						 fnc_remove_char_esp(SUBSTR(p.descricao, 1, 39))
					  END,
					  '-'
				   ) AS familia,
                   p.codncmsh,
                   p.aceitavendafracao permitedecimal,
                   'N' permitemultiplicacao,
                   (SELECT nvl(CODCEST, 0) codcest
                    FROM PCCEST INNER JOIN PCCESTPRODUTO ON PCCEST.CODIGO = PCCESTPRODUTO.CODSEQCEST
                    WHERE PCCESTPRODUTO.CODPROD = p.codprod
                    AND ROWNUM = 1
                   ) codcest,
                   'S' ativo,
                   p.codmarca seqmarca,
                   1 seqfamgrupo,
                   (CASE
                      WHEN  p.tipoembalagem = 'P' THEN
                            'S'
                      ELSE  'N'
                   END)PESAVEL,
                   NVL(p.indescalarelevante, 'S') indescala,
				   CASE 
					   WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
                         fnc_remove_char_esp_v2(p.cnpjfabricante) 
					   ELSE
					     fnc_remove_char_esp(p.cnpjfabricante)    
					   END as cnpjfabricante,
                   p.codauxiliartrib eantrib,
                   P.codprodprinc seqfamiliaprinc,
                   P.estoqueporlote,
				   NVL(p.checapesoetiqueta, 'N') checapesoetiqueta
            FROM VW_INT_C5_EMB_DESMEMBRADAS p
           ) PROD /*TABELA VIRTUAL CRIADA PARA LISTAR REGISTROS DA VIEW EMBPROD E VW_INT_C5_EMB_DESMEMBRADAS*/
      GROUP BY PROD.IDREF /*ORDERNAÇÃO DEVE SER PELO IDREF PARA AGRUPAR O RESULTADO O UNION ALL DA TABELA VIRTUAL "PROD"*/
      ) TBFAM, /*TABELA VIRTUAL COM O RESULTADO FINAL DO AGRUPAMENTO, SEM CODAUXILIAR DUPLICADO*/
      PCDEPARAPRODC5 DEPARA
WHERE TBFAM.CODPROD = DEPARA.CODPROD(+)
AND   TBFAM.CODAUXILIAR = DEPARA.CODAUXILIAR(+)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMEMBALAGEM AS
WITH CTE_EMBALAGEM AS (
  SELECT
    DEPARA.SEQFAMILIA,
    NVL(e.qtunit, 1) AS QTDEMBALAGEM,
    NVL(MAX(e.unidade), '1') AS EMBALAGEM,
    NVL(MAX(e.pesobruto), 0) AS PESOBRUTO,
    NVL(MAX(e.pesoliq), 0) AS PESOLIQ,
    'N' AS PESOAFERIDO,
    'S' AS ATIVO
  FROM VW_INT_C5_EMBPROD_MAT e
  JOIN PCDEPARAPRODC5 DEPARA 
    ON DEPARA.CODPROD = E.CODPROD 
   AND DEPARA.ATIVO = 'S'
   AND (DEPARA.CODAUXILIAR = E.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0)
  /* DPDVSUPER-3308 : retirado tratamento para descer todas as embalagens independente do gatilho de atacado
    WHERE 
    (E.qtunit <> E.qtminimaatacado)*/
  GROUP BY 
    DEPARA.SEQFAMILIA,
    NVL(e.qtunit, 1)
  UNION ALL
  SELECT
    DEPARA.SEQFAMILIA,
    NVL(e.qtminimaatacado, 1) QTDEMBALAGEM,
    NVL(MAX(e.unidade), '1') AS EMBALAGEM,
    NVL(MAX(e.pesobruto), 0) AS PESOBRUTO,
    NVL(MAX(e.pesoliq), 0) AS PESOLIQ,
    'N' AS PESOAFERIDO,
    'S' AS ATIVO
  FROM VW_INT_C5_EMBPROD_MAT e
  JOIN PCDEPARAPRODC5 DEPARA 
    ON DEPARA.CODPROD = E.CODPROD 
   AND DEPARA.ATIVO = 'S'
   AND (DEPARA.CODAUXILIAR = E.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0)
  WHERE 
    (E.qtminimaatacado > 1)
  GROUP BY 
    DEPARA.SEQFAMILIA,
    NVL(e.qtminimaatacado, 1)  
)
SELECT
  SEQFAMILIA,
  QTDEMBALAGEM,
  MAX(EMBALAGEM) AS EMBALAGEM,
  LEAST(MAX(PESOBRUTO), 9999.999) AS PESOBRUTO,
  LEAST(MAX(PESOLIQ), 9999.999) AS pesoliquido,
  MAX(PESOAFERIDO) AS PESOAFERIDO,
  MAX(ATIVO) AS ATIVO
FROM CTE_EMBALAGEM
GROUP BY SEQFAMILIA, QTDEMBALAGEM

/*(
  SELECT
    SEQFAMILIA,
    QTDEMBALAGEM QTDEMBALAGEM,
    max(EMBALAGEM) EMBALAGEM,
    --max(PESOBRUTO) PESOBRUTO,
    --max(PESOLIQ) PESOLIQ,
    LEAST(max(PESOBRUTO), 9999.999) PESOBRUTO,
    LEAST(max(PESOLIQ), 9999.999) PESOLIQ,
    max(PESOAFERIDO) PESOAFERIDO,
    max(ATIVO) ATIVO
 FROM
  (
  --Embalagem preço varejo
  select distinct DEPARA.SEQFAMILIA seqfamilia,
                NVL(e.qtunit, 1) qtdembalagem,
                NVL(max(e.unidade), '1') embalagem,
                NVL(max(e.pesobruto), 0) pesobruto,
                NVL(max(e.pesoliq), 0) pesoliq,
                'N' pesoaferido,
                'S' ativo
  from VW_INT_C5_EMBPROD e, PCDEPARAPRODC5 DEPARA
 where E.qtunit <> E.qtminimaatacado
   and (((DEPARA.CODPROD = E.CODPROD)
   and (DEPARA.CODAUXILIAR = E.CODAUXILIAR)
   and (DEPARA.ATIVO = 'S'))
    or ((DEPARA.CODPROD = E.CODPROD) 
   and (DEPARA.CODAUXILIAR = 0) 
   and (DEPARA.ATIVO = 'S')))
 group by DEPARA.SEQFAMILIA,
          NVL(e.qtunit, 1)
UNION ALL
--Embalagem preço Atacado
select distinct DEPARA.SEQFAMILIA seqfamilia,
                NVL(e.qtminimaatacado, 1) qtdembalagem,
                NVL(max(e.unidade), '1') embalagem,
                NVL(max(e.pesobruto), 0) pesobruto,
                NVL(max(e.pesoliq), 0) pesoliq,
                'N' pesoaferido,
                'S' ativo
  from VW_INT_C5_EMBPROD e, PCDEPARAPRODC5 DEPARA
 where e.qtminimaatacado > 1
   and (((DEPARA.CODPROD = E.CODPROD)
   and (DEPARA.CODAUXILIAR = E.CODAUXILIAR)
   and (DEPARA.ATIVO = 'S'))
    or ((DEPARA.CODPROD = E.CODPROD) 
	and (DEPARA.CODAUXILIAR = 0)
	and (DEPARA.ATIVO = 'S')))
 group by DEPARA.SEQFAMILIA,
          NVL(e.qtminimaatacado, 1))DADOSEMB
  group by SEQFAMILIA, QTDEMBALAGEM
)*/

\

CREATE OR REPLACE VIEW VW_INT_C5_EMBFAMILIA AS
WITH CTE_EMBFAMILIA AS (
SELECT DISTINCT DEPARA.SEQFAMILIA,
       E.CODPRODPRINC, 
       NVL(E.QTUNIT, 1) QTDEMBALAGEM, 
       NVL(MAX(E.UNIDADE), '1') EMBALAGEM, 
       LEAST(NVL(MAX(E.pesobruto), 0), 9999.999) AS PESOBRUTO,
       LEAST(NVL(MAX(E.pesoliq), 0), 9999.999) AS PESOLIQUIDO,
       'N' AS PESOAFERIDO,
       'S' AS ATIVO,
       E.CODPROD IDREF
FROM VW_INT_C5_EMBPROD_MAT E,
     PCDEPARAPRODC5 DEPARA,
     VW_INT_C5_OBTER_FILIAIS_C5 C5
WHERE E.CODFILIAL = C5.CODFILIAL
AND   E.CODPRODPRINC = DEPARA.CODPROD
AND   DEPARA.ATIVO = 'S'
AND   (DEPARA.CODAUXILIAR = E.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0)
AND   E.CODPROD <> E.CODPRODPRINC
AND   NOT EXISTS(SELECT 1
                 FROM MONITORPDVMIDDLE.TB_FAMEMBALAGEM EMB
                 WHERE EMB.SEQFAMILIA = DEPARA.SEQFAMILIA
                 AND    NVL(E.QTUNIT, 1) = EMB.QTDEMBALAGEM)
GROUP BY DEPARA.SEQFAMILIA, E.QTUNIT, E.CODPRODPRINC, E.CODPROD
)
SELECT DISTINCT
  SEQFAMILIA,
  QTDEMBALAGEM,
  EMBALAGEM,
  PESOBRUTO,
  PESOLIQUIDO,
  PESOAFERIDO,
  ATIVO
FROM CTE_EMBFAMILIA
WHERE NOT EXISTS (SELECT 1
                  FROM MONITORPDVMIDDLE.TB_FAMEMBALAGEM EMB
                  WHERE EMB.SEQFAMILIA = SEQFAMILIA
                  AND   EMB.QTDEMBALAGEM = QTDEMBALAGEM)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODUTO AS
(
SELECT
    DEPARA.SEQPRODUTO,
    
    NVL((CASE
         /*DEFINICAO DO SEQFAMILIA DOS PRODUTOS DESMEMBRADOS*/
         WHEN ORIGEM = 'D' THEN
              DEPARA.SEQFAMILIA
         /*DEFINICAO DO SEQFAMILIA DE PRODUTO PAI*/
         WHEN TBPROD.CODPROD = TBPROD.CODPRODPRINC THEN
              DEPARA.SEQFAMILIA
         /*Se o produto principal não existir nas filiais de integração, então seta o seqfamilia do filho*/
         WHEN (SELECT COUNT(*)
               FROM PCPRODFILIAL PF
               WHERE PF.CODFILIAL IN (SELECT C5.CODFILIAL FROM VW_INT_C5_OBTER_FILIAIS_C5 C5)
               AND  TBPROD.CODPRODPRINC = PF.CODPROD
              ) = 0 THEN
              DEPARA.SEQFAMILIA
         /*DEFINICAO DO SEQFAMILIA DE PRODUTO FILHO, DE ACORDO COM A TRIBUTACAO DO PRODUTO PAI*/     
         WHEN /*SE O PRODUTO É FILHO...*/
              (TBPROD.CODPROD <> TBPROD.CODPRODPRINC) AND 
              
              /*E SE A TRIBUTACAO DO PRODUTO FILHO É DIFERENTE DA TRIBUTACAO DO PRODUTO PAI, ENTÃO SETA O SEQFAMILIA DO FILHO*/
              (
                (SELECT F.NROTRIBUTACAO 
                 FROM VW_INT_C5_FAMDIV_MAT F 
                 WHERE F.CODPROD = TBPROD.CODPROD 
                 AND ROWNUM = 1
                ) 
                
                <>
              
                NVL((SELECT F.NROTRIBUTACAO 
                     FROM VW_INT_C5_FAMDIV_MAT F
                     WHERE F.CODPROD = TBPROD.CODPRODPRINC
                     AND ROWNUM = 1), (SELECT F.NROTRIBUTACAO
                                       FROM MONITORPDVMIDDLE.TB_FAMDIVISAO F,
                                            PCDEPARAPRODC5 D
                                       WHERE F.SEQFAMILIA = D.SEQFAMILIA
                                       AND   D.ATIVO = 'S'
                                       AND   D.CODPROD = TBPROD.CODPRODPRINC
                                       AND   D.CODAUXILIAR = 0
                                       AND ROWNUM = 1)
                    )
              ) 
              THEN 
                DEPARA.SEQFAMILIA
         ELSE /*SE A TRIBUTACAO PRODUTO FILHO É IGUAL A TRIBUTACAO DO PRODUTO PAI, SETA O SEQFAMILIA DO PRODUTO PAI*/ 
             NVL((SELECT PP.SEQFAMILIA
             FROM PCPRODUT P, PCDEPARAPRODC5 PP, MONITORPDVMIDDLE.TB_FAMILIA F
             WHERE P.CODPROD = PP.CODPROD
             AND F.SEQFAMILIA = PP.SEQFAMILIA
             AND  F.ATIVO = 'S'
             AND F.IDREF = P.CODPROD
             AND PP.CODAUXILIAR = 0
             AND TBPROD.CODPRODPRINC = PP.CODPROD
             AND PP.ATIVO = 'S'), DEPARA.SEQFAMILIA)
        END
        ), DEPARA.SEQPRODUTO) SEQFAMILIA,
           
    TBPROD.*
FROM (
      SELECT 
           MIN(PROD.CODPROD) CODPROD,
           (CASE
             WHEN MIN(PROD.CODAUXILIAR) IS NULL THEN
                  0
             ELSE MIN(PROD.CODAUXILIAR)
           END) CODAUXILIAR,
           MIN(PROD.ORIGEM) ORIGEM,
           MIN(PROD.CODPRODUTO) CODPRODUTO,
           MIN(PROD.desccompleta) desccompleta,
           MIN(PROD.descreduzida) descreduzida,
           MIN(PROD.produtocomposto) produtocomposto,
           MIN(PROD.QTDDIAVALIDADE) QTDDIAVALIDADE,
           MIN(PROD.codanp) codanp,
           MIN(PROD.descanp_prod) descanp_prod,
           MIN(PROD.percglp) percglp,
           MIN(PROD.percgnn) percgnn,
           MIN(PROD.percgni) percgni,
           MIN(PROD.CODPRODPRINC)CODPRODPRINC,
           MIN(PROD.ATIVO) ATIVO
      FROM( 
            SELECT DISTINCT
                   p.codprod CODPROD,
                   NULL CODAUXILIAR,
                   MIN(P.CODAUXILIAR) IDREF, /*NECESSÁRIO TRAZER O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'E' ORIGEM,
                   p.codprod codproduto,
                   CASE
				     WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
					   fnc_remove_char_esp_v2(p.descricao)
					 ELSE
					   fnc_remove_char_esp(p.descricao)
				   END as desccompleta,
                   SUBSTR(
				     CASE
					   WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
						 fnc_remove_char_esp_v2(p.descricao)
					   ELSE
						 fnc_remove_char_esp(p.descricao)
					  END,
					  1,
					  24
				   ) as descreduzida,
                   --'N' produtocomposto,
                   (CASE
                      WHEN MAX(P.TIPOMERC) IN ('CB', 'KT') THEN
                           'S'
                      ELSE 'N'     
                   END) PRODUTOCOMPOSTO,
                   0 QTDDIAVALIDADE,
                   MAX(nvl(P.anp, 0)) codanp,
                   MAX(P.descanp) descanp_prod,
                   MAX(nvl(P.pglp, 0)) percglp,
                   MAX(nvl(P.pgnn, 0)) percgnn,
                   MAX(nvl(P.pgni, 0)) percgni,
                   MIN(P.CODPRODPRINC) CODPRODPRINC,
                   'S' ATIVO
            FROM VW_INT_C5_EMBPROD_MAT p
            GROUP BY p.codprod, p.descricao

            UNION ALL

            /* SELECT CUSTOMIZADO PARA TRAZER EMBALAGENS COM O MESMO QTUNIT DESMEMBRADAS */
            SELECT
                   p.codprod CODPROD,
                   p.codauxiliar CODAUXILIAR,
                   p.codauxiliar IDREF, /*NECESSÁRIO TRAZER O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'D' ORIGEM,
                   p.codprod codproduto,
                   CASE
					 WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
					   fnc_remove_char_esp_v2(NVL(p.descricaoreduzida, p.descricao))
					 ELSE
					   fnc_remove_char_esp(NVL(p.descricaoreduzida, p.descricao))
				   END as desccompleta,
                   SUBSTR(
				     CASE
					   WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
						 fnc_remove_char_esp_v2(NVL(p.descricaoreduzida, p.descricao))
					   ELSE
						 fnc_remove_char_esp(NVL(p.descricaoreduzida, p.descricao))
					 END,
					 1,
					 24
				   ) as descreduzida,
                   'N' produtocomposto,
                   0 QTDDIAVALIDADE,
                   nvl(p.anp, 0) codanp,
                   p.descanp descanp_prod,
                   nvl(P.pglp, 0) percglp,
                   nvl(P.pgnn, 0) percgnn,
                   nvl(P.pgni, 0) percgni,                   
                   NULL CODPRODPRINC,
                   'S' ATIVO

            FROM VW_INT_C5_EMB_DESMEMBRADAS p
          ) PROD /*TABELA VIRTUAL CRIADA PARA LISTAR REGISTROS DA VIEW EMBPROD E VW_INT_C5_EMB_DESMEMBRADAS*/
      GROUP BY PROD.IDREF /*ORDERNAÇÃO DEVE SER PELO IDREF PARA AGRUPAR O RESULTADO O UNION ALL DA TABELA VIRTUAL "PROD"*/
      ) TBPROD, /*TABELA VIRTUAL COM O RESULTADO FINAL DO AGRUPAMENTO, SEM CODAUXILIAR DUPLICADO*/
      PCDEPARAPRODC5 DEPARA
WHERE TBPROD.CODPROD = DEPARA.CODPROD
AND   TBPROD.CODAUXILIAR = DEPARA.CODAUXILIAR
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODEMPRESA AS
(
  SELECT DISTINCT E.codfilialintegracao nroempresa,
         E.CODPROD idref,
         P.SEQPRODUTO SEQPRODUTO,
         0000000 estqloja,
         'S' ativo
  FROM VW_INT_C5_EMBPROD_MAT E,
       PCDEPARAPRODC5 P
  WHERE (((E.CODPROD = P.CODPROD) AND (E.CODAUXILIAR = P.CODAUXILIAR) AND (P.ATIVO = 'S'))
     OR ((E.CODPROD = P.CODPROD) AND (P.CODAUXILIAR = 0) AND (P.ATIVO = 'S')))

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODCODIGO AS
WITH CTE_PRODCODIGO AS (
SELECT  distinct
        e.codfilialintegracao nroempresa,
        e.codauxiliar codacesso,
        P.SEQPRODUTO SEQPRODUTO,
        COALESCE(e.qtunit, 1) qtdembalagem,
        (CASE
            WHEN length(e.codauxiliar) = 13 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'E'
            WHEN length(e.codauxiliar) = 14 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'D'
            WHEN NVL(E.PRODSEMCODBARRAS, 'N') = 'S' THEN
             'B'
         ELSE
           'B'
         END) tipo,
        'S' ativo
 FROM  VW_INT_C5_EMBPROD_MAT e
    JOIN PCDEPARAPRODC5 P ON P.ATIVO = 'S' AND E.CODPROD = P.CODPROD
 WHERE (E.CODAUXILIAR = P.CODAUXILIAR OR P.CODAUXILIAR = 0)
)
SELECT "NROEMPRESA","CODACESSO","SEQPRODUTO","QTDEMBALAGEM","TIPO","ATIVO" 
FROM CTE_PRODCODIGO

/*(
  SELECT
        e.codfilialintegracao nroempresa,
        e.codauxiliar codacesso,
        P.SEQPRODUTO SEQPRODUTO,
        COALESCE(e.qtunit, 1) qtdembalagem,
        (CASE
            WHEN length(e.codauxiliar) = 13 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'E'
            WHEN length(e.codauxiliar) = 14 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'D'
            WHEN NVL(E.PRODSEMCODBARRAS, 'N') = 'S' THEN
             'B'
         ELSE
           'B'
         END) tipo,
        'S' ativo
 FROM  VW_INT_C5_EMBPROD e,
       PCDEPARAPRODC5 P
 WHERE (((E.CODPROD = P.CODPROD) AND (E.CODAUXILIAR = P.CODAUXILIAR) AND (P.ATIVO = 'S'))
     OR ((E.CODPROD = P.CODPROD) AND (P.CODAUXILIAR = 0) AND P.ATIVO = 'S'))
)*/

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMSEGMENTO AS
(SELECT DISTINCT
       --e.codprod seqfamilia,
       T.SEQFAMILIA,
       1 nrosegmento,
       'S' ativo
  FROM  VW_INT_C5_EMBPROD_MAT e,
    MONITORPDVMIDDLE.TB_FAMILIA T
  WHERE
    E.CODPROD = T.IDREF

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODPRECO AS
WITH CTE_PRECO AS (
    --Linha de preço varejo
    SELECT
    TO_CHAR(E.CODAUXILIAR) IDREF,
    DEPARA.SEQPRODUTO SEQPRODUTO,
    --E.CODFILIAL NROEMPRESA,
    C5.CODFILIALINTEGRACAO NROEMPRESA,
    NVL(E.QTUNIT, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,

    (CASE
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.00
      ELSE LEAST(E.PVENDA, 9999999.999)
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_OBTER_FILIAIS_C5 C5,
       VW_INT_C5_EMBPROD_MAT e
  JOIN PCDEPARAPRODC5 DEPARA
    ON DEPARA.CODPROD = E.CODPROD
       AND DEPARA.ATIVO = 'S'
       AND (DEPARA.CODAUXILIAR = E.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0)
       AND E.QTUNIT <> E.QTMINIMAATACADO
   WHERE C5.CODFILIAL = E.CODFILIAL

  UNION ALL

  --LINHA DE PREÇO ATACADO
  SELECT
    CASE 
      WHEN (NVL(E.QTMINIMAATACADO, 0) >= 1) AND (NVL(E.PVENDAATAC, 0) <= 0) THEN
           TO_CHAR(E.CODAUXILIAR) || 'V' /*SETAR QUE A LINHA DE ATACADO RECEBEU "V" INDICANDO QUE PREÇO DE ATACADO RECEBEU O PRECO DE VAREJO*/
      ELSE     
           TO_CHAR(E.CODAUXILIAR) || 'A' 
    END  IDREF,
    p.SEQPRODUTO SEQPRODUTO,
    --E.CODFILIAL NROEMPRESA,
    C5.CODFILIALINTEGRACAO NROEMPRESA,
    NVL(E.QTMINIMAATACADO, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,

    /*(CASE
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999)
    END)  PRECO,*/
    (CASE
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.00
      WHEN (NVL(E.QTMINIMAATACADO, 0) >= 1) AND (NVL(E.PVENDAATAC, 0) <= 0) THEN /*CASO EXISTA GATILHO MAS NAO TENHA PRECO DE ATACADO, SETAR O PREÇO DE VAREJO*/
           LEAST(ROUNDABNT((E.PVENDA / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999)
      ELSE LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999)
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_OBTER_FILIAIS_C5 C5,
       VW_INT_C5_EMBPROD_MAT E
    JOIN PCDEPARAPRODC5 P ON E.CODPROD = P.CODPROD-- AND P.ATIVO = 'S'
    WHERE
        (
            (E.CODAUXILIAR = P.CODAUXILIAR AND P.ATIVO = 'S')
            OR (P.CODAUXILIAR = 0 AND P.ATIVO = 'S' AND E.QTUNIT = (SELECT MIN(QTUNIT) FROM VW_INT_C5_EMBPROD_MAT EMB
                                                                    WHERE E.CODFILIAL = EMB.CODFILIAL
                                                                    AND E.CODPROD = EMB.CODPROD)
                                                                    )
        )
    AND E.QTMINIMAATACADO >= 1
    AND C5.CODFILIAL = E.CODFILIAL
)
SELECT "IDREF","SEQPRODUTO","NROEMPRESA","QTDEMBALAGEM","NROSEGMENTO","PROMOCAO","PRECO","PRECONORMAL","ATIVO" 
FROM CTE_PRECO

/*(
   --Linha de preço varejo
    SELECT
    TO_CHAR(E.CODAUXILIAR) IDREF,
    P.SEQPRODUTO SEQPRODUTO,
    E.codfilialintegracao NROEMPRESA,
    NVL(E.QTUNIT, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,
    --E.PVENDA PRECO,
    --LEAST(E.PVENDA, 9999999.999) PRECO,

    (CASE 
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(E.PVENDA, 9999999.999) 
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_EMBPROD E,
       PCDEPARAPRODC5 P
  WHERE ((E.CODAUXILIAR = P.CODAUXILIAR
    AND E.CODPROD = P.CODPROD AND P.ATIVO = 'S') 
	 OR (E.CODPROD = P.CODPROD
    AND P.CODAUXILIAR = 0 AND P.ATIVO = 'S'))
    AND E.QTUNIT <> E.QTMINIMAATACADO

  UNION ALL

  --LINHA DE PREÇO ATACADO
  SELECT
    TO_CHAR(E.CODAUXILIAR) || 'A' IDREF,
    P.SEQPRODUTO SEQPRODUTO,
    E.codfilialintegracao NROEMPRESA,
    NVL(E.QTMINIMAATACADO, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,
    --ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3) PRECO,
    --LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999) PRECO,
    
    (CASE 
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999) 
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_EMBPROD E,
       PCDEPARAPRODC5 P 
  WHERE 
    (
      (E.CODAUXILIAR = P.CODAUXILIAR AND E.CODPROD = P.CODPROD AND P.ATIVO = 'S') 
	    OR (E.CODPROD = P.CODPROD AND P.CODAUXILIAR = 0 AND P.ATIVO = 'S' AND E.QTUNIT = (SELECT MIN(QTUNIT) FROM VW_INT_C5_EMBPROD WHERE E.CODFILIAL = CODFILIAL AND E.CODPROD = CODPROD ))
    )
    AND E.QTMINIMAATACADO >= 1
)*/

\

CREATE OR REPLACE VIEW VW_INT_C5_PROMOCOES_VIGENTES AS
(
  --POLITICA 357
   SELECT
     'P357' IDREF,
     DEPARA.SEQPRODUTO,
     C5.CODFILIALINTEGRACAO NROEMPRESA,
     LEAST(NVL(round(E.QTUNIT, 3), 1), 999999.999) QTDEMBALAGEM,
     1 NROSEGMENTO,
     (R.PRECOFIXO * E.QTUNIT) PRECO,
     'S' PROMOCAO,
     'S' ATIVO,
     0 PRIORIDADE,
     E.PVENDA PRECONORMAL

   FROM PCPRECOPROM R,
        PCEMBALAGEM E,
        PCDEPARAPRODC5 DEPARA,
        VW_INT_C5_OBTER_FILIAIS_C5 c5,
        (select min(s.ultimaexecucao) ultimaexecucao
        from pccontroleconsinco s
        where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAINCENTIVO')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAINCENTPERIODO')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAPRODUTO')
        ) DTPADRAO
   WHERE DEPARA.CODPROD = R.CODPROD
   AND DEPARA.ATIVO = 'S'
   AND R.FRENTECX = 'S'
   AND E.CODPROD = R.CODPROD
   AND E.CODFILIAL = R.CODFILIAL
   AND E.CODFILIAL = C5.CODFILIAL
   AND E.CODPROD = DEPARA.CODPROD
   AND R.DTINICIOVIGENCIA IS NOT NULL
   AND R.DTFIMVIGENCIA IS NOT NULL
   AND R.CODFILIAL = c5.CODFILIAL
   AND TRUNC(SYSDATE) BETWEEN R.DTINICIOVIGENCIA AND R.DTFIMVIGENCIA
   AND NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO

UNION ALL

  
  --OFERTA 2011 VAREJO
   SELECT
    PCOFERTAPROGRAMADAC.CODOFERTA || ' - 2011' IDREF, 
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    --PCEMBALAGEM.QTUNIT QTDEMBALAGEM,
    LEAST(NVL(round(PCEMBALAGEM.QTUNIT, 3), 1), 999999.999) QTDEMBALAGEM,
    1 NROSEGMENTO,  
    PCOFERTAPROGRAMADAI.VLOFERTA PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    decode(PCOFERTAPROGRAMADAC.HORAINICIAL, null, 2, 1) PRIORIDADE,
    PCEMBALAGEM.PVENDA PRECONORMAL    
  FROM 
    PCOFERTAPROGRAMADAI
  INNER JOIN PCOFERTAPROGRAMADAC
  ON (PCOFERTAPROGRAMADAC.CODOFERTA = PCOFERTAPROGRAMADAI.CODOFERTA)  

  INNER JOIN PCEMBALAGEM
  ON (PCEMBALAGEM.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR AND PCOFERTAPROGRAMADAI.CODFILIAL = PCEMBALAGEM.CODFILIAL)

  INNER JOIN PCDEPARAPRODC5 
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S')  
      OR (PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD  AND PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCDEPARAPRODC5.ATIVO = 'S'))

  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCOFERTAPROGRAMADAI.CODFILIAL AND C5.CODFILIAL = PCOFERTAPROGRAMADAC.CODFILIAL)
  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD AND PROD.CODPROD = PCOFERTAPROGRAMADAI.CODPROD)
  WHERE 
  	PCOFERTAPROGRAMADAC.DTINICIAL IS NOT NULL
	AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCOFERTAPROGRAMADAC.DTFINAL IS NOT NULL
    AND PCOFERTAPROGRAMADAC.DTCANCEL IS NULL
    AND PCOFERTAPROGRAMADAI.DATAEXCLUSAO IS NULL
	AND SYSDATE BETWEEN COALESCE(PCOFERTAPROGRAMADAC.HORAINICIAL, PCOFERTAPROGRAMADAC.DTINICIAL)
					AND COALESCE(PCOFERTAPROGRAMADAC.HORAFINAL, PCOFERTAPROGRAMADAC.DTFINAL + 0.99999)
    AND PCOFERTAPROGRAMADAI.VLOFERTA > 0
    AND PCOFERTAPROGRAMADAC.PRIORIDADEOFERTA = (
      SELECT MIN(P.PRIORIDADEOFERTA)
      FROM PCOFERTAPROGRAMADAC P
      INNER JOIN PCOFERTAPROGRAMADAI I
      ON (P.CODOFERTA = I.CODOFERTA)
      WHERE 
        P.DTINICIAL IS NOT NULL
        AND P.DTFINAL IS NOT NULL
        AND P.DTCANCEL IS NULL
        AND I.DATAEXCLUSAO IS NULL
        AND I.CODPROD = PCOFERTAPROGRAMADAI.CODPROD 
        AND I.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR 
        AND I.CODFILIAL = PCOFERTAPROGRAMADAI.CODFILIAL 
        AND SYSDATE BETWEEN COALESCE(P.HORAINICIAL, P.DTINICIAL)
						AND COALESCE(P.HORAFINAL, P.DTFINAL + 0.99999) 
        AND I.VLOFERTA > 0
    )
 AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    
 UNION ALL 
--OFERTA 2011 ATACADO
 SELECT
    PCOFERTAPROGRAMADAC.CODOFERTA || ' - 2011A' IDREF, 
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    --PCEMBALAGEM.QTMINIMAATACADO QTDEMBALAGEM,
    LEAST(NVL(round(PCEMBALAGEM.QTMINIMAATACADO, 3), 1), 999999.999) QTDEMBALAGEM,
    1 NROSEGMENTO,  
    LEAST(ROUNDABNT((PCOFERTAPROGRAMADAI.VLOFERTAATAC / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    decode(PCOFERTAPROGRAMADAC.HORAINICIAL, null, 2, 1) PRIORIDADE,
    LEAST(ROUNDABNT((DECODE(NVL(PCEMBALAGEM.PVENDAATAC,0), 0 , PCEMBALAGEM.PVENDA, PCEMBALAGEM.PVENDAATAC) / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECONORMAL
  FROM 
    PCOFERTAPROGRAMADAI
  INNER JOIN PCOFERTAPROGRAMADAC
  ON (PCOFERTAPROGRAMADAC.CODOFERTA = PCOFERTAPROGRAMADAI.CODOFERTA)  

  INNER JOIN PCEMBALAGEM
  ON (PCEMBALAGEM.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR AND PCOFERTAPROGRAMADAI.CODFILIAL = PCEMBALAGEM.CODFILIAL)

  INNER JOIN PCDEPARAPRODC5 
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S') OR
   (PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S') )
   
  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCOFERTAPROGRAMADAI.CODFILIAL AND C5.CODFILIAL = PCOFERTAPROGRAMADAC.CODFILIAL)

  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD AND PROD.CODPROD = PCOFERTAPROGRAMADAI.CODPROD)
  WHERE 
  	PCOFERTAPROGRAMADAC.DTINICIAL IS NOT NULL
	AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCOFERTAPROGRAMADAC.DTFINAL IS NOT NULL
    AND PCOFERTAPROGRAMADAC.DTCANCEL IS NULL
    AND PCOFERTAPROGRAMADAI.DATAEXCLUSAO IS NULL    
    AND SYSDATE BETWEEN COALESCE(PCOFERTAPROGRAMADAC.HORAINICIAL, PCOFERTAPROGRAMADAC.DTINICIAL)
					AND COALESCE(PCOFERTAPROGRAMADAC.HORAFINAL, PCOFERTAPROGRAMADAC.DTFINAL + 0.99999)
    AND PCOFERTAPROGRAMADAI.VLOFERTAATAC > 0
    AND PCOFERTAPROGRAMADAC.PRIORIDADEOFERTA = (
      SELECT MIN(P.PRIORIDADEOFERTA)
      FROM PCOFERTAPROGRAMADAC P
      INNER JOIN PCOFERTAPROGRAMADAI I
      ON (P.CODOFERTA = I.CODOFERTA)
      WHERE 
        P.DTINICIAL IS NOT NULL
        AND P.DTFINAL IS NOT NULL
        AND P.DTCANCEL IS NULL
        AND I.DATAEXCLUSAO IS NULL
        AND I.CODPROD = PCOFERTAPROGRAMADAI.CODPROD 
        AND I.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR 
        AND I.CODFILIAL = PCOFERTAPROGRAMADAI.CODFILIAL 
        AND SYSDATE BETWEEN COALESCE(P.HORAINICIAL, P.DTINICIAL)
						AND COALESCE(P.HORAFINAL, P.DTFINAL + 0.99999) 
        AND I.VLOFERTAATAC > 0
    )
    AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    AND NVL(PCEMBALAGEM.QTMINIMAATACADO, 0) >= 1

  UNION ALL

  SELECT
    PCEMBALAGEM.CODAUXILIAR || ' - 2017' IDREF,
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    --PCEMBALAGEM.QTUNIT QTDEMBALAGEM,  
    LEAST(NVL(round(PCEMBALAGEM.QTUNIT, 3), 1), 999999.999) QTDEMBALAGEM,
    1 NROSEGMENTO,  
    PCEMBALAGEM.POFERTA PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    3 PRIORIDADE,
    PCEMBALAGEM.PVENDA PRECONORMAL
  FROM 
    PCEMBALAGEM

  INNER JOIN PCDEPARAPRODC5
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S')
  OR (PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.CODAUXILIAR =0 AND PCDEPARAPRODC5.ATIVO = 'S'))
  
  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCEMBALAGEM.CODFILIAL)
  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD)
  WHERE  
  	PCEMBALAGEM.DTOFERTAINI IS NOT NULL
    AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCEMBALAGEM.DTOFERTAFIM IS NOT NULL 
    AND TRUNC(SYSDATE) BETWEEN PCEMBALAGEM.DTOFERTAINI AND PCEMBALAGEM.DTOFERTAFIM
     --TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAINI, 'DD-MM-YY') || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') 
      --AND TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAFIM, 'DD-MM-YY')  || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
    AND PCEMBALAGEM.POFERTA > 0
    AND PCEMBALAGEM.QTUNIT  > 0
    AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    
  UNION ALL 

  SELECT
    PCEMBALAGEM.CODAUXILIAR ||' - 2017A' IDREF,
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    --PCEMBALAGEM.QTMINIMAATACADO QTDEMBALAGEM,
    LEAST(NVL(round(PCEMBALAGEM.QTMINIMAATACADO, 3), 1), 999999.999) QTDEMBALAGEM,
    1 NROSEGMENTO,  
    LEAST(ROUNDABNT((PCEMBALAGEM.POFERTAATAC / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    3 PRIORIDADE,
    LEAST(ROUNDABNT((DECODE(NVL(PCEMBALAGEM.PVENDAATAC,0), 0 , PCEMBALAGEM.PVENDA, PCEMBALAGEM.PVENDAATAC) / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECONORMAL
  FROM 
    PCEMBALAGEM

  INNER JOIN PCDEPARAPRODC5
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S') 
  OR (PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCDEPARAPRODC5.ATIVO = 'S'))
  
  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCEMBALAGEM.CODFILIAL)
  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD)
  WHERE
  	PCEMBALAGEM.DTOFERTAATACINI IS NOt NULL
	AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCEMBALAGEM.DTOFERTAATACFIM IS NOT null
    AND TRUNC(SYSDATE) BETWEEN PCEMBALAGEM.DTOFERTAATACINI AND PCEMBALAGEM.DTOFERTAATACFIM
      --TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAATACINI, 'DD-MM-YY')|| ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
      -- AND TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAATACFIM, 'DD-MM-YY')  || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')    
    AND PCEMBALAGEM.POFERTAATAC > 0
    AND PCEMBALAGEM.QTMINIMAATACADO > 0
    AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODCOMPOSTO AS
(
SELECT DISTINCT
       (SELECT X.SEQPRODUTO FROM PCDEPARAPRODC5 X WHERE X.CODPROD = F.CODPRODACAB AND X.ATIVO = 'S' AND ROWNUM = 1)SEQPRODCOMPOSTO,
       P.SEQPRODUTO,
       
       NVL((SELECT QTUNIT 
        FROM PCEMBALAGEM E 
        WHERE E.CODPROD = F.CODPRODMP
        AND E.CODAUXILIAR = F.CODAUXILIARMP 
        AND E.CODFILIAL = F.CODFILIAL
       ), 1) QTDEMBALAGEM,
       
       F.QTPRODMP QUANTIDADE,
       0 PRECO,
       'S'ATIVO,
       F.CODPRODACAB IDREF
FROM MONITORPDVMIDDLE.TB_PRODUTO TP,
     PCFORMPROD F,
     PCPRODUT PROD,
     PCDEPARAPRODC5 P,
     VW_INT_C5_OBTER_FILIAIS_C5 C5
WHERE F.CODFILIAL IS NOT NULL
AND   (TP.CODPRODUTO = F.CODPRODACAB or TP.CODPRODUTO = F.CODPRODMP)
AND   TP.CODPRODUTO = PROD.CODPROD
AND   TP.PRODUTOCOMPOSTO = 'S'
AND   PROD.CODPROD = F.CODPRODACAB
AND   PROD.TIPOMERC IN ('CB', 'KT')
AND   C5.CODFILIAL = F.CODFILIAL           
AND   P.ATIVO = 'S'
AND   EXISTS(SELECT SEQPRODUTO FROM MONITORPDVMIDDLE.TB_PRODUTO WHERE SEQPRODUTO = P.SEQPRODUTO)
AND   ((P.CODPROD = F.codprodMP) AND (P.CODAUXILIAR = 0) OR
       (P.CODPROD = F.codprodMP) AND (P.CODAUXILIAR = F.codauxiliarMP)
      )
           
/*TRATATIVA PARA NÃO DESCER CESSTA QUE NÃO POSSUI VINCULO NA PCDEPARAPRODC5*/
AND EXISTS(SELECT 1
           FROM PCDEPARAPRODC5 PROD
           WHERE F.CODPRODACAB = PROD.CODPROD
           AND PROD.ATIVO = 'S'
          )    

/*TRATATIVA PARA NÃO DEIXAR DESCER A CESTA CASO UM DOS ITENS ESTEJA COM PREÇO ZERADO*/
AND   NOT EXISTS (SELECT EMB_PRECO.CODAUXILIAR
                  FROM VW_INT_C5_EMBPROD_MAT EMB_PRECO,
                       PCFORMPROD FP
                  WHERE EMB_PRECO.pvenda <= 0
                  AND EMB_PRECO.codprod = FP.CODPRODMP
                  AND EMB_PRECO.codauxiliar = FP.CODAUXILIARMP
                  AND EMB_PRECO.codfilial = FP.CODFILIAL
                  AND FP.CODFILIAL = F.CODFILIAL
                  AND FP.CODPRODACAB = F.CODPRODACAB
                  AND NVL(FP.CODFILIAL, EMB_PRECO.CODFILIAL) = EMB_PRECO.CODFILIAL
                 )
     
/*TRATATIVA PARA NÃO DEIXAR DESCER A CESTA CASO UM DOS ITENS ESTEJA INATIVO*/
AND   NOT EXISTS(SELECT EMB.CODAUXILIAR
                 FROM PCEMBALAGEM EMB, -- ANALISAR PELA PCEMBALAGEM PQ A VIEW EMBPROD NAO TRAZ REGISTROS INATIVADOS
                      PCFORMPROD FP,
                      PCPRODUT PR,
                      PCPRODFILIAL PRODFILIAL
                 WHERE EMB.CODPROD = FP.CODPRODMP
                 AND   EMB.CODAUXILIAR = FP.CODAUXILIARMP
                 AND   EMB.CODPROD = PR.CODPROD
                 AND   NVL(FP.CODFILIAL, EMB.CODFILIAL) = EMB.CODFILIAL
                 AND   FP.CODPRODACAB = F.CODPRODACAB
                 AND   EMB.CODPROD = PRODFILIAL.CODPROD
                 AND   EMB.CODFILIAL = PRODFILIAL.CODFILIAL
                 AND   FP.CODPRODMP = PRODFILIAL.CODPROD
                 AND   FP.CODFILIAL = PRODFILIAL.CODFILIAL
                 AND   FP.CODPRODACAB = PRODFILIAL.CODPROD
                 AND   PR.CODPROD = PRODFILIAL.CODPROD
                 AND   ((DTINATIVO IS NOT NULL) OR (PR.DTEXCLUSAO IS NOT NULL) OR (NVL(PRODFILIAL.PROIBIDAVENDA, 'N') = 'N'))
                )
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CAB_CESTA AS
(
SELECT
  MAX(C.SEQPRODUTO) SEQPRODUTO,
  CESTA.CODPRODACAB,
  CESTA.NROEMPRESA,
  (CASE
       WHEN NVL(SUM(CESTA.PRECOFIXO),0) > 0 THEN
            SUM(ROUND(CESTA.PRECOFIXO * CESTA.QTPRODMP, 2))
       WHEN NVL(SUM(CESTA.PERCDESC), 0) > 0 THEN
            SUM(ROUND((CESTA.PRECO - (ABS(CESTA.PRECO * CESTA.PERCDESC / 100))) , 2))
       ELSE SUM(ROUND(CESTA.PRECO,2))
   END)PRECO

FROM (  
      SELECT 
         F.CODPRODACAB,
         P.SEQPRODUTO,
         PP.NROEMPRESA,
         F.codprodmp,
         F.QTPRODMP,
         F.codauxiliarmp,
         I.PRECOFIXO,
         I.PERCDESC,
    
         (CASE
            WHEN FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('FIL_PRECOPOREMBALAGEM', F.CODFILIAL, 'N') = 'S' THEN
                 COLUNA_PRECO(BUSCAPRECOS(F.CODFILIAL, 0, F.CODAUXILIARMP, TRUNC(SYSDATE)),'PVENDA')
            ELSE COLUNA_PRECO(BUSCAPRECOS(F.CODFILIAL, FERRAMENTAS.F_BUSCARPARAMETRO_NUM('NUMREGIAOPADRAOVAREJO', F.CODFILIAL, 1), F.CODAUXILIARMP, TRUNC(SYSDATE)),'PVENDA1')
         END) * F.QTPRODMP PRECO

      FROM  MONITORPDVMIDDLE.TB_PRODPRECO PP,
            MONITORPDVMIDDLE.TB_PRODUTO TB_PROD,
            PCEMBALAGEM E,
            PCFORMPROD F,
            PCDEPARAPRODC5 P,
            (SELECT * FROM PCPRECOCESTAC WHERE TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM) C,
            PCPRECOCESTAI I,
            VW_INT_C5_OBTER_FILIAIS_C5 C5
      WHERE PP.SEQPRODUTO = P.SEQPRODUTO
      AND   P.ATIVO = 'S'

      AND   ((P.CODPROD = E.codprod) AND (P.CODAUXILIAR = 0) OR
             (P.CODPROD = E.codprod) AND (P.CODAUXILIAR = E.codauxiliar)
            )  
           
      AND   ((P.CODPROD = F.CODPRODMP) AND (P.CODAUXILIAR = 0) OR
             (P.CODPROD = F.CODPRODMP) AND (P.CODAUXILIAR = F.CODAUXILIARMP)
            )
      
      AND  TB_PROD.SEQPRODUTO = PP.SEQPRODUTO
      AND  TB_PROD.CODPRODUTO = E.CODPROD
      AND  TB_PROD.SEQPRODUTO = P.SEQPRODUTO
      AND  ((TB_PROD.CODPRODUTO = F.CODPRODACAB) or (TB_PROD.CODPRODUTO = F.CODPRODMP))

      AND   F.CODFILIAL = C5.CODFILIAL
      AND   E.CODFILIAL = C5.CODFILIAL
      AND   C5.CODFILIALINTEGRACAO = PP.NROEMPRESA
      AND   E.CODAUXILIAR = F.CODAUXILIARMP
      AND   E.CODFILIAL   = F.CODFILIAL
      AND   E.CODPROD     = F.CODPRODMP
      AND   E.CODPROD     = P.CODPROD
      AND   E.QTUNIT      = PP.QTDEMBALAGEM
      AND   F.CODPRODACAB = I.CODPRODACAB(+)
      AND   F.CODFILIAL = I.CODFILIAL(+)   
      AND   F.CODPRODMP = I.CODPRODMP(+)
      AND   E.CODFILIAL = NVL(I.CODFILIAL, E.CODFILIAL)
      AND   E.CODPROD   = NVL(I.CODPRODMP, E.CODPROD)
      AND   C5.CODFILIAL = NVL(I.CODFILIAL, C5.CODFILIAL)
      AND   I.CODPRECOCESTA = C.CODPRECOCESTA(+)
      AND   P.CODPROD = NVL(I.CODPRODMP, P.CODPROD)
	  AND   F.CODPRODACAB IN (SELECT CODPROD FROM PCPRODUT WHERE TIPOMERC IN ('KT','CB'))
      )CESTA,
      PCDEPARAPRODC5 C,
      PCPRODUT P
WHERE CESTA.PRECO > 0 
AND   P.CODPROD = CESTA.CODPRODACAB
AND   P.CODPROD = C.CODPROD  
AND   P.TIPOMERC IN ('CB', 'KT') 
AND   (CESTA.CODPRODACAB = C.CODPROD AND C.ATIVO = 'S')    
GROUP BY CESTA.CODPRODACAB, CESTA.NROEMPRESA
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODLOTE AS
(
SELECT
  C5.CODFILIALINTEGRACAO NROEMPRESA,
  C5.CODFILIALINTEGRACAO SEQLOCAL,
  --F.RAZAOSOCIAL LOCAL_RAZAO,
  SUBSTR(
    CASE
	  WHEN (SELECT VALOR FROM PCPARAMETROS2651 WHERE NOME = 'UTILIZAR_FNC_REMOVE_CHAR_ESP_V2') = 'S' THEN
	    fnc_remove_char_esp_v2(F.RAZAOSOCIAL)
	  ELSE
	    fnc_remove_char_esp(F.RAZAOSOCIAL)
	END,
	  1,
	  20
  ) as LOCAL_RAZAO,
  'L' TIPO,
  (CASE
    WHEN f.dtexclusao IS NULL THEN 
         'S'
    ELSE 'N'
  END) ATIVO_FILIAL,
  NVL((SELECT M.SEQLOTEESTOQUE
       FROM MONITORPDVMIDDLE.TB_LOTEESTOQUE M
       WHERE P.SEQPRODUTO = M.SEQPRODUTO
       AND   C5.CODFILIALINTEGRACAO =  M.NROEMPRESA
       AND   LT.NUMLOTE = M.NROLOTEESTOQUE
       AND   ROWNUM = 1), 0
     ) SEQLOTEESTOQUE,
  P.SEQPRODUTO SEQPRODUTO,
  LT.QT ESTQLOTE,
  LT.NUMLOTE NROLOTEESTOQUE,
  LT.DATAFABRICACAO DTAFABRICACAO,
  LT.DTVALIDADE DTAVALIDADE,
  NVL(LT.DATAFABRICACAO, TRUNC(SYSDATE))  DTAENTRADA,
  (CASE
    WHEN (LT.DTVALIDADE >= TRUNC(SYSDATE)) AND 
         (LT.QT > 0) AND 
         (PROD.ESTOQUEPORLOTE = 'S') AND
         (FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_UTILIZACONTROLELOTE', '99', 'N') = 'S') THEN 
         'S'
    ELSE 'N'
  END) ATIVO_LOTE,
  PROD.CODPROD IDREF
FROM VW_INT_C5_OBTER_FILIAIS_C5 C5,
     PCFILIAL F,
     PCDEPARAPRODC5 P,
     PCLOTE LT,
     PCPRODUT PROD,
     (SELECT min(s.ultimaexecucao) ultimaexecucao
      FROM PCCONTROLECONSINCO S
      WHERE (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_LOCAL')
      OR    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_LOTEESTOQUE')
     )DTPADRAO
WHERE C5.CODFILIAL = F.CODIGO     
AND   P.ATIVO = 'S'
AND   LT.CODPROD = P.CODPROD
AND   LT.CODFILIAL = F.CODIGO
AND   PROD.CODPROD = P.CODPROD
AND   PROD.CODPROD = LT.CODPROD
AND   LT.DTVALIDADE IS NOT NULL
AND   NVL(LT.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_LIMITEVENDA AS
(
SELECT 1 SEQLIMITEVENDA,
       SYSDATE DTAHORINICIO,
       SYSDATE + 100000 DTAHORFIM,
	   C5.CODFILIALINTEGRACAO NROEMPRESA,
       'COTA DE VENDA - 2017' DESCRICAO,
	   'S' ATIVO
	   FROM VW_INT_C5_OBTER_FILIAIS_C5 C5
)

\

CREATE OR REPLACE VIEW VW_INT_C5_LIMITEVENDAFAMILIA AS
(
SELECT DISTINCT PROD.SEQFAMILIA,
                NVL(I.QTMAXVENDA, NVL(EMB.QTMAXVENDA, 0)) QTMAXVENDA,
                NVL(EMB.QTUNIT, 1) QTUNIT,
                '2011' ORIGEM,
                DECODE(C.HORAINICIAL, NULL, C.PRIORIDADEOFERTA, 0) PRIORIDADE,
                1 SEQLIMITEVENDA
  FROM PCEMBALAGEM               EMB,
       PCOFERTAPROGRAMADAC         C,
       PCOFERTAPROGRAMADAI         I,
       PCDEPARAPRODC5              DEPARA,
       MONITORPDVMIDDLE.TB_PRODUTO PROD,
       VW_INT_C5_OBTER_FILIAIS_C5 C5
 WHERE C.CODOFERTA = I.CODOFERTA
   AND I.CODPROD = EMB.CODPROD
   AND I.CODAUXILIAR = EMB.CODAUXILIAR
   AND NVL(I.QTMAXVENDA, NVL(EMB.QTMAXVENDA, 0)) > 0
   AND TRUNC(SYSDATE) BETWEEN C.DTINICIAL AND C.DTFINAL
   AND C.DTCANCEL IS NULL
   AND PROD.SEQPRODUTO = DEPARA.SEQPRODUTO
   AND DEPARA.CODPROD = EMB.CODPROD
   AND C5.CODFILIAL = EMB.CODFILIAL
   AND C5.CODFILIAL = C.CODFILIAL
   AND C.CODFILIAL = EMB.CODFILIAL
   AND DEPARA.ATIVO = 'S'
   AND (DEPARA.CODAUXILIAR = 0 OR DEPARA.CODAUXILIAR = EMB.CODAUXILIAR)
 UNION ALL
 SELECT DISTINCT PROD.SEQFAMILIA,
                NVL(EMB.QTMAXVENDA, 0) QTMAXVENDA,
                EMB.QTUNIT QTUNIT,
                '2017' ORIGEM,
                11 PRIORIDADEOFERTA,
                1 SEQLIMITEVENDA
  FROM PCEMBALAGEM           EMB,
       PCDEPARAPRODC5              DEPARA,
       MONITORPDVMIDDLE.TB_PRODUTO PROD,
       VW_INT_C5_OBTER_FILIAIS_C5 C5
 WHERE PROD.SEQPRODUTO = DEPARA.SEQPRODUTO
   AND DEPARA.CODPROD = EMB.CODPROD
   AND C5.CODFILIAL = EMB.CODFILIAL
   AND NVL(EMB.QTMAXVENDA, 0) > 0
   AND DEPARA.ATIVO = 'S'
   AND (DEPARA.CODAUXILIAR = 0 OR DEPARA.CODAUXILIAR = EMB.CODAUXILIAR)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BAIRRODELIVERY AS
(
  SELECT 
    B.CODFILIAL AS NROEMPRESA,
    B.CODIGO AS SEQREGIAO,
    B.BAIRRO AS REGIAO,
    B.VLTXENTREGA AS PRECOFRETE,
    CASE WHEN B.DTINATIVO IS NULL
      THEN 'S'
      ELSE 'N'
    END ATIVO
  FROM PCBAIRRODELIV B,
    (SELECT CODFILIAL FROM VW_INT_C5_OBTER_FILIAIS_C5) FILIAL,
    (select min(s.ultimaexecucao) ultimaexecucao
              from pccontroleconsinco s
              where s.ativo = 'A'
              and  (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGIAO')
              ) DTPADRAO
  WHERE B.CODFILIAL = FILIAL.CODFILIAL 
    AND NVL(B.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
)