CREATE OR REPLACE VIEW VW_INT_C5_MARCA AS
(
  SELECT DISTINCT
         MARCA.*
  FROM(
        SELECT  DISTINCT 
              m.codmarca     AS seqmarca,
              SUBSTR(m.marca,1,20)    AS marca,
              
              (case 
                when NVL(m.ativo, 'S') = 'N' then
                     'N'
                else 'S'
               end) ativo    
        FROM pcprodut p
        INNER JOIN pcmarca m
        ON m.codmarca = p.codmarca
        AND m.codmarca > 0
  UNION ALL
        SELECT  CODMARCA seqmarca,
                SUBSTR(MARCA,1,20) marca,
                (case 
                 when NVL(ativo, 'S') = 'N' then
                     'N'
                 else 'S'
                 end) ativo
        FROM PCMARCA 
        WHERE CODMARCA > 0
        AND CODMARCA = ferramentas.f_buscarparametro_num('MARCAINTEGRACAOCONSINCO', '99', '1')) MARCA
)

 \

CREATE OR REPLACE VIEW VW_INT_C5_FAMILIA AS
(
SELECT
    DEPARA.SEQFAMILIA,
    TBFAM."CODPROD", TBFAM."CODAUXILIAR",TBFAM."ORIGEM",TBFAM."FAMILIA",TBFAM."CODNCMSH",TBFAM."PERMITEDECIMAL",TBFAM."PERMITEMULTIPLICACAO",TBFAM."CODCEST",TBFAM."ATIVO",TBFAM."SEQMARCA",TBFAM."SEQFAMGRUPO",TBFAM."PESAVEL",TBFAM."INDESCALA",TBFAM."CNPJFABRICANTE",TBFAM."EANTRIB",TBFAM."SEQFAMILIAPRINC"
FROM (
      SELECT
           /*NECESSÁRIO ATRIBUIR ZERO QUANDO O CODAUXILIAR ESTIVER NULO, POIS NA TABELA DEPARACODPRODC5 O CAMPO É PK(NÃO ACEITA NULO)*/
           MIN(PROD.CODPROD) CODPROD,
           (CASE
             WHEN MIN(PROD.CODAUXILIAR) IS NULL THEN
                  0
             ELSE MIN(PROD.CODAUXILIAR)
           END) CODAUXILIAR,
           MIN(PROD.ORIGEM) ORIGEM,
           MIN(PROD.familia) FAMILIA,
           MIN(PROD.codncmsh) codncmsh,
           MIN(PROD.permitedecimal) permitedecimal,
           MIN(PROD.permitemultiplicacao) permitemultiplicacao,
           MIN(PROD.codcest) codcest,
           MIN(PROD.ativo) ativo,
           MIN(PROD.seqmarca) seqmarca,
           MIN(PROD.seqfamgrupo) seqfamgrupo,
           MIN(PROD.PESAVEL) PESAVEL,
           MIN(PROD.indescala) indescala,
           MIN(PROD.cnpjfabricante) cnpjfabricante,
           MIN(PROD.eantrib) eantrib,
           MIN(PROD.Seqfamiliaprinc) Seqfamiliaprinc

      FROM (
            /* SELECT ORIGINAL VIEW EMBPROD */
            SELECT DISTINCT
                   p.codprod CODPROD,
                   NULL CODAUXILIAR,
                   MIN(P.CODAUXILIAR) IDREF, /*NECESSÁRIO TRAZER O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'E' ORIGEM,
                   NVL(fnc_remove_char_esp(substr(p.descricao,0,39)), '-') familia,
                   MAX(p.codncmsh) codncmsh,
                   MAX(p.aceitavendafracao) permitedecimal,
                   --MAX(p.permitemultiplicacao) permitemultiplicacao,
                   
                   CASE WHEN (SELECT COUNT(DISTINCT TIPOEMBALAGEM)
                              FROM PCEMBALAGEM
                              WHERE codprod = p.codprod
                              AND tipoembalagem IN ('U', 'P')) > 1 THEN
                          'S'
                        ELSE
                          'N'
                   END PERMITEMULTIPLICACAO,

                   (SELECT nvl(CODCEST, 0) codcest
                    FROM PCCEST INNER JOIN PCCESTPRODUTO ON PCCEST.CODIGO = PCCESTPRODUTO.CODSEQCEST
                    WHERE PCCESTPRODUTO.CODPROD = p.codprod
                    AND ROWNUM = 1
                   ) codcest,
                   'S' ativo,
                   MAX(p.codmarca) seqmarca,
                   1 seqfamgrupo,
                   
                   /*(CASE
                      WHEN  MIN(p.tipoembalagem) = 'P' THEN
                            'S'
                      ELSE  'N'
                   END)PESAVEL,*/

                   CASE
                       WHEN (SELECT COUNT(DISTINCT TIPOEMBALAGEM)
                             FROM PCEMBALAGEM
                             WHERE codprod = p.codprod
                             AND tipoembalagem IN ('U', 'P')) > 1 THEN
                              'N'
                       WHEN  (SELECT COUNT(DISTINCT TIPOEMBALAGEM)
                              FROM PCEMBALAGEM
                              WHERE codprod = p.codprod
                              AND tipoembalagem IN ('P')) = 1 THEN
                                      
                               'S'
                       ELSE
                               'N'
                  END PESAVEL,

                   
                   MIN(NVL(p.indescalarelevante, 'S')) indescala,
                   MAX(fnc_remove_char_esp(p.cnpjfabricante)) cnpjfabricante,
                   MAX(p.codauxiliartrib) eantrib,
                   MAX(P.codprodprinc) seqfamiliaprinc
            FROM VW_INT_C5_EMBPROD p
            GROUP BY p.codprod, p.descricao

            UNION ALL

            /* SELECT CUSTOMIZADO PARA TRAZER EMBALAGENS COM O MESMO QTUNIT DESMEMBRADAS */
            SELECT
                   p.codprod CODPROD,
                   p.codauxiliar CODAUXILIAR,
                   p.codauxiliar IDREF, /*NECESSÁRIO REPETIR O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'D' ORIGEM,
                   NVL(fnc_remove_char_esp(substr(p.descricao,0,39)), '-') familia,
                   p.codncmsh,
                   p.aceitavendafracao permitedecimal,
                   'N' permitemultiplicacao,
                   (SELECT nvl(CODCEST, 0) codcest
                    FROM PCCEST INNER JOIN PCCESTPRODUTO ON PCCEST.CODIGO = PCCESTPRODUTO.CODSEQCEST
                    WHERE PCCESTPRODUTO.CODPROD = p.codprod
                    AND ROWNUM = 1
                   ) codcest,
                   'S' ativo,
                   p.codmarca seqmarca,
                   1 seqfamgrupo,
                   (CASE
                      WHEN  p.tipoembalagem = 'P' THEN
                            'S'
                      ELSE  'N'
                   END)PESAVEL,
                   NVL(p.indescalarelevante, 'S') indescala,
                   fnc_remove_char_esp(p.cnpjfabricante) cnpjfabricante,
                   p.codauxiliartrib eantrib,
                   P.codprodprinc seqfamiliaprinc

            FROM VW_INT_C5_EMB_DESMEMBRADAS p
           ) PROD /*TABELA VIRTUAL CRIADA PARA LISTAR REGISTROS DA VIEW EMBPROD E VW_INT_C5_EMB_DESMEMBRADAS*/
      GROUP BY PROD.IDREF /*ORDERNAÇÃO DEVE SER PELO IDREF PARA AGRUPAR O RESULTADO O UNION ALL DA TABELA VIRTUAL "PROD"*/
      ) TBFAM, /*TABELA VIRTUAL COM O RESULTADO FINAL DO AGRUPAMENTO, SEM CODAUXILIAR DUPLICADO*/
      PCDEPARAPRODC5 DEPARA
WHERE TBFAM.CODPROD = DEPARA.CODPROD(+)
AND   TBFAM.CODAUXILIAR = DEPARA.CODAUXILIAR(+)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMEMBALAGEM AS
WITH CTE_EMBALAGEM AS (
  SELECT
    DEPARA.SEQFAMILIA,
    CASE 
      WHEN E.qtunit <> E.qtminimaatacado THEN NVL(e.qtunit, 1)
      WHEN E.qtminimaatacado > 1 THEN NVL(e.qtminimaatacado, 1)
    END AS QTDEMBALAGEM,
    NVL(MAX(e.unidade), '1') AS EMBALAGEM,
    NVL(MAX(e.pesobruto), 0) AS PESOBRUTO,
    NVL(MAX(e.pesoliq), 0) AS PESOLIQ,
    'N' AS PESOAFERIDO,
    'S' AS ATIVO
  FROM VW_INT_C5_EMBPROD e
  JOIN PCDEPARAPRODC5 DEPARA 
    ON DEPARA.CODPROD = E.CODPROD 
   AND DEPARA.ATIVO = 'S'
   AND (DEPARA.CODAUXILIAR = E.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0)
  WHERE 
    (E.qtunit <> E.qtminimaatacado OR E.qtminimaatacado > 1)
  GROUP BY 
    DEPARA.SEQFAMILIA,
    CASE 
      WHEN E.qtunit <> E.qtminimaatacado THEN NVL(e.qtunit, 1)
      WHEN E.qtminimaatacado > 1 THEN NVL(e.qtminimaatacado, 1)
    END
)
SELECT
  SEQFAMILIA,
  QTDEMBALAGEM,
  MAX(EMBALAGEM) AS EMBALAGEM,
  LEAST(MAX(PESOBRUTO), 9999.999) AS PESOBRUTO,
  LEAST(MAX(PESOLIQ), 9999.999) AS pesoliquido,
  MAX(PESOAFERIDO) AS PESOAFERIDO,
  MAX(ATIVO) AS ATIVO
FROM CTE_EMBALAGEM
GROUP BY SEQFAMILIA, QTDEMBALAGEM

/*(
  SELECT
    SEQFAMILIA,
    QTDEMBALAGEM QTDEMBALAGEM,
    max(EMBALAGEM) EMBALAGEM,
    --max(PESOBRUTO) PESOBRUTO,
    --max(PESOLIQ) PESOLIQ,
    LEAST(max(PESOBRUTO), 9999.999) PESOBRUTO,
    LEAST(max(PESOLIQ), 9999.999) PESOLIQ,
    max(PESOAFERIDO) PESOAFERIDO,
    max(ATIVO) ATIVO
 FROM
  (
  --Embalagem preço varejo
  select distinct DEPARA.SEQFAMILIA seqfamilia,
                NVL(e.qtunit, 1) qtdembalagem,
                NVL(max(e.unidade), '1') embalagem,
                NVL(max(e.pesobruto), 0) pesobruto,
                NVL(max(e.pesoliq), 0) pesoliq,
                'N' pesoaferido,
                'S' ativo
  from VW_INT_C5_EMBPROD e, PCDEPARAPRODC5 DEPARA
 where E.qtunit <> E.qtminimaatacado
   and (((DEPARA.CODPROD = E.CODPROD)
   and (DEPARA.CODAUXILIAR = E.CODAUXILIAR)
   and (DEPARA.ATIVO = 'S'))
    or ((DEPARA.CODPROD = E.CODPROD) 
   and (DEPARA.CODAUXILIAR = 0) 
   and (DEPARA.ATIVO = 'S')))
 group by DEPARA.SEQFAMILIA,
          NVL(e.qtunit, 1)
UNION ALL
--Embalagem preço Atacado
select distinct DEPARA.SEQFAMILIA seqfamilia,
                NVL(e.qtminimaatacado, 1) qtdembalagem,
                NVL(max(e.unidade), '1') embalagem,
                NVL(max(e.pesobruto), 0) pesobruto,
                NVL(max(e.pesoliq), 0) pesoliq,
                'N' pesoaferido,
                'S' ativo
  from VW_INT_C5_EMBPROD e, PCDEPARAPRODC5 DEPARA
 where e.qtminimaatacado > 1
   and (((DEPARA.CODPROD = E.CODPROD)
   and (DEPARA.CODAUXILIAR = E.CODAUXILIAR)
   and (DEPARA.ATIVO = 'S'))
    or ((DEPARA.CODPROD = E.CODPROD) 
	and (DEPARA.CODAUXILIAR = 0)
	and (DEPARA.ATIVO = 'S')))
 group by DEPARA.SEQFAMILIA,
          NVL(e.qtminimaatacado, 1))DADOSEMB
  group by SEQFAMILIA, QTDEMBALAGEM
)*/

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODUTO AS
(
SELECT
    DEPARA.SEQPRODUTO,
    
    NVL((CASE
         /*DEFINICAO DO SEQFAMILIA DOS PRODUTOS DESMEMBRADOS*/
         WHEN ORIGEM = 'D' THEN
              DEPARA.SEQFAMILIA
         /*DEFINICAO DO SEQFAMILIA DE PRODUTO PAI*/
         WHEN TBPROD.CODPROD = TBPROD.CODPRODPRINC THEN
              DEPARA.SEQFAMILIA
         /*DEFINICAO DO SEQFAMILIA DE PRODUTO FILHO, DE ACORDO COM A TRIBUTACAO DO PRODUTO PAI*/     
         WHEN /*SE O PRODUTO É FILHO...*/
              (TBPROD.CODPROD <> TBPROD.CODPRODPRINC) AND 
              
              /*E SE A TRIBUTACAO DO PRODUTO FILHO É DIFERENTE DA TRIBUTACAO DO PRODUTO PAI, ENTÃO SETA O SEQFAMILIA DO FILHO*/
              (
                (SELECT F.NROTRIBUTACAO 
                 FROM VW_INT_C5_FAMDIVISAO F 
                 WHERE F.CODPROD = TBPROD.CODPROD 
                 AND ROWNUM = 1
                ) 
                
                <>
              
                NVL((SELECT F.NROTRIBUTACAO 
                     FROM VW_INT_C5_FAMDIVISAO F
                     WHERE F.CODPROD = TBPROD.CODPRODPRINC
                     AND ROWNUM = 1), (SELECT F.NROTRIBUTACAO
                                       FROM MONITORPDVMIDDLE.TB_FAMDIVISAO F,
                                            PCDEPARAPRODC5 D
                                       WHERE F.SEQFAMILIA = D.SEQFAMILIA
                                       AND   D.ATIVO = 'S'
                                       AND   D.CODPROD = TBPROD.CODPRODPRINC
                                       AND   D.CODAUXILIAR = 0
                                       AND ROWNUM = 1)
                    )
              ) 
              THEN 
                DEPARA.SEQFAMILIA
         ELSE /*SE A TRIBUTACAO PRODUTO FILHO É IGUAL A TRIBUTACAO DO PRODUTO PAI, SETA O SEQFAMILIA DO PRODUTO PAI*/ 
             (SELECT PP.SEQFAMILIA 
             FROM PCPRODUT P, PCDEPARAPRODC5 PP 
             WHERE P.CODPROD = PP.CODPROD  
             AND PP.CODAUXILIAR = 0 
             AND TBPROD.CODPRODPRINC = PP.CODPROD
             AND PP.ATIVO = 'S')                   
        END
        ), DEPARA.SEQPRODUTO) SEQFAMILIA,
           
    TBPROD.*
FROM (
      SELECT 
           MIN(PROD.CODPROD) CODPROD,
           (CASE
             WHEN MIN(PROD.CODAUXILIAR) IS NULL THEN
                  0
             ELSE MIN(PROD.CODAUXILIAR)
           END) CODAUXILIAR,
           MIN(PROD.ORIGEM) ORIGEM,
           MIN(PROD.CODPRODUTO) CODPRODUTO,
           MIN(PROD.desccompleta) desccompleta,
           MIN(PROD.descreduzida) descreduzida,
           MIN(PROD.produtocomposto) produtocomposto,
           MIN(PROD.QTDDIAVALIDADE) QTDDIAVALIDADE,
           MIN(PROD.codanp) codanp,
           MIN(PROD.descanp_prod) descanp_prod,
           MIN(PROD.CODPRODPRINC)CODPRODPRINC,
           MIN(PROD.ATIVO) ATIVO
      FROM( 
            SELECT DISTINCT
                   p.codprod CODPROD,
                   NULL CODAUXILIAR,
                   MIN(P.CODAUXILIAR) IDREF, /*NECESSÁRIO TRAZER O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'E' ORIGEM,
                   p.codprod codproduto,
                   fnc_remove_char_esp(p.descricao) desccompleta,
                   SUBSTR((fnc_remove_char_esp(P.descricao)),1,24) descreduzida,
                   --'N' produtocomposto,
                   (CASE
                      WHEN MAX(P.TIPOMERC) IN ('CB', 'KT') THEN
                           'S'
                      ELSE 'N'     
                   END) PRODUTOCOMPOSTO,
                   0 QTDDIAVALIDADE,
                   MAX(nvl(P.anp, 0)) codanp,
                   MAX(P.descanp) descanp_prod,
                   MIN(P.CODPRODPRINC) CODPRODPRINC,
                   'S' ATIVO
            FROM VW_INT_C5_EMBPROD p
            GROUP BY p.codprod, p.descricao

            UNION ALL

            /* SELECT CUSTOMIZADO PARA TRAZER EMBALAGENS COM O MESMO QTUNIT DESMEMBRADAS */
            SELECT
                   p.codprod CODPROD,
                   p.codauxiliar CODAUXILIAR,
                   p.codauxiliar IDREF, /*NECESSÁRIO TRAZER O CODAUXILIAR PARA SER UTILIZADO NO GROUP BY*/
                   'D' ORIGEM,
                   p.codprod codproduto,
                   fnc_remove_char_esp(p.descricao) desccompleta,
                   SUBSTR((fnc_remove_char_esp(p.descricao)),1,24) descreduzida,
                   'N' produtocomposto,
                   0 QTDDIAVALIDADE,
                   nvl(p.anp, 0) codanp,
                   p.descanp descanp_prod,
                   NULL CODPRODPRINC,
                   'S' ATIVO

            FROM VW_INT_C5_EMB_DESMEMBRADAS p
          ) PROD /*TABELA VIRTUAL CRIADA PARA LISTAR REGISTROS DA VIEW EMBPROD E VW_INT_C5_EMB_DESMEMBRADAS*/
      GROUP BY PROD.IDREF /*ORDERNAÇÃO DEVE SER PELO IDREF PARA AGRUPAR O RESULTADO O UNION ALL DA TABELA VIRTUAL "PROD"*/
      ) TBPROD, /*TABELA VIRTUAL COM O RESULTADO FINAL DO AGRUPAMENTO, SEM CODAUXILIAR DUPLICADO*/
      PCDEPARAPRODC5 DEPARA
WHERE TBPROD.CODPROD = DEPARA.CODPROD
AND   TBPROD.CODAUXILIAR = DEPARA.CODAUXILIAR
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODEMPRESA AS
(
  SELECT DISTINCT E.codfilialintegracao nroempresa,
         E.CODPROD idref,
         P.SEQPRODUTO SEQPRODUTO,
         0000000 estqloja,
         'S' ativo
  FROM VW_INT_C5_EMBPROD E,
       PCDEPARAPRODC5 P
  WHERE (((E.CODPROD = P.CODPROD) AND (E.CODAUXILIAR = P.CODAUXILIAR) AND (P.ATIVO = 'S'))
     OR ((E.CODPROD = P.CODPROD) AND (P.CODAUXILIAR = 0) AND (P.ATIVO = 'S')))

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODCODIGO AS
WITH CTE_PRODCODIGO AS (
SELECT  distinct
        e.codfilialintegracao nroempresa,
        e.codauxiliar codacesso,
        P.SEQPRODUTO SEQPRODUTO,
        COALESCE(e.qtunit, 1) qtdembalagem,
        (CASE
            WHEN length(e.codauxiliar) = 13 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'E'
            WHEN length(e.codauxiliar) = 14 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'D'
            WHEN NVL(E.PRODSEMCODBARRAS, 'N') = 'S' THEN
             'B'
         ELSE
           'B'
         END) tipo,
        'S' ativo
 FROM  VW_INT_C5_EMBPROD e
    JOIN PCDEPARAPRODC5 P ON P.ATIVO = 'S' AND E.CODPROD = P.CODPROD
 WHERE (E.CODAUXILIAR = P.CODAUXILIAR OR P.CODAUXILIAR = 0)
)
SELECT "NROEMPRESA","CODACESSO","SEQPRODUTO","QTDEMBALAGEM","TIPO","ATIVO" 
FROM CTE_PRODCODIGO

/*(
  SELECT
        e.codfilialintegracao nroempresa,
        e.codauxiliar codacesso,
        P.SEQPRODUTO SEQPRODUTO,
        COALESCE(e.qtunit, 1) qtdembalagem,
        (CASE
            WHEN length(e.codauxiliar) = 13 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'E'
            WHEN length(e.codauxiliar) = 14 AND NVL(E.PRODSEMCODBARRAS, 'N') = 'N'
                 THEN 'D'
            WHEN NVL(E.PRODSEMCODBARRAS, 'N') = 'S' THEN
             'B'
         ELSE
           'B'
         END) tipo,
        'S' ativo
 FROM  VW_INT_C5_EMBPROD e,
       PCDEPARAPRODC5 P
 WHERE (((E.CODPROD = P.CODPROD) AND (E.CODAUXILIAR = P.CODAUXILIAR) AND (P.ATIVO = 'S'))
     OR ((E.CODPROD = P.CODPROD) AND (P.CODAUXILIAR = 0) AND P.ATIVO = 'S'))
)*/

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMSEGMENTO AS
(SELECT DISTINCT
       --e.codprod seqfamilia,
       T.SEQFAMILIA,
       1 nrosegmento,
       'S' ativo
  FROM  VW_INT_C5_EMBPROD e,
    MONITORPDVMIDDLE.TB_FAMILIA T
  WHERE
    E.CODPROD = T.IDREF

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODPRECO AS
WITH CTE_PRECO AS (
    --Linha de preço varejo
    SELECT
    E.CODAUXILIAR IDREF,
    DEPARA.SEQPRODUTO SEQPRODUTO,
    E.CODFILIAL NROEMPRESA,
    NVL(E.QTUNIT, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,

    (CASE
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(E.PVENDA, 9999999.999)
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_EMBPROD e
  JOIN PCDEPARAPRODC5 DEPARA
    ON DEPARA.CODPROD = E.CODPROD
   AND DEPARA.ATIVO = 'S'
   AND (DEPARA.CODAUXILIAR = E.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0)
   AND E.QTUNIT <> E.QTMINIMAATACADO

  UNION ALL

  --LINHA DE PREÇO ATACADO
  SELECT
    E.CODAUXILIAR IDREF,
    p.SEQPRODUTO SEQPRODUTO,
    E.CODFILIAL NROEMPRESA,
    NVL(E.QTMINIMAATACADO, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,

    (CASE
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999)
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_EMBPROD E
    JOIN PCDEPARAPRODC5 P ON E.CODPROD = P.CODPROD-- AND P.ATIVO = 'S'
    WHERE
        (
            (E.CODAUXILIAR = P.CODAUXILIAR AND P.ATIVO = 'S')
            OR (P.CODAUXILIAR = 0 AND P.ATIVO = 'S' AND E.QTUNIT = (SELECT MIN(QTUNIT) FROM VW_INT_C5_EMBPROD EMB
                                                                    WHERE E.CODFILIAL = EMB.CODFILIAL
                                                                    AND E.CODPROD = EMB.CODPROD)
                                                                    )
        )
        AND E.QTMINIMAATACADO >= 1
)
SELECT "IDREF","SEQPRODUTO","NROEMPRESA","QTDEMBALAGEM","NROSEGMENTO","PROMOCAO","PRECO","PRECONORMAL","ATIVO" 
FROM CTE_PRECO

/*(
   --Linha de preço varejo
    SELECT
    TO_CHAR(E.CODAUXILIAR) IDREF,
    P.SEQPRODUTO SEQPRODUTO,
    E.codfilialintegracao NROEMPRESA,
    NVL(E.QTUNIT, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,
    --E.PVENDA PRECO,
    --LEAST(E.PVENDA, 9999999.999) PRECO,

    (CASE 
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(E.PVENDA, 9999999.999) 
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_EMBPROD E,
       PCDEPARAPRODC5 P
  WHERE ((E.CODAUXILIAR = P.CODAUXILIAR
    AND E.CODPROD = P.CODPROD AND P.ATIVO = 'S') 
	 OR (E.CODPROD = P.CODPROD
    AND P.CODAUXILIAR = 0 AND P.ATIVO = 'S'))
    AND E.QTUNIT <> E.QTMINIMAATACADO

  UNION ALL

  --LINHA DE PREÇO ATACADO
  SELECT
    TO_CHAR(E.CODAUXILIAR) || 'A' IDREF,
    P.SEQPRODUTO SEQPRODUTO,
    E.codfilialintegracao NROEMPRESA,
    NVL(E.QTMINIMAATACADO, 1) QTDEMBALAGEM,
    1 NROSEGMENTO,
    'N' PROMOCAO,
    --ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3) PRECO,
    --LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999) PRECO,
    
    (CASE 
      WHEN E.TIPOMERC IN ('CB', 'KT') THEN
           0.01
      ELSE LEAST(ROUNDABNT((E.PVENDAATAC / E.QTUNIT) * E.QTMINIMAATACADO, 3), 9999999.999) 
    END)  PRECO,

    0 PRECONORMAL,
    'S' ATIVO
  FROM VW_INT_C5_EMBPROD E,
       PCDEPARAPRODC5 P 
  WHERE 
    (
      (E.CODAUXILIAR = P.CODAUXILIAR AND E.CODPROD = P.CODPROD AND P.ATIVO = 'S') 
	    OR (E.CODPROD = P.CODPROD AND P.CODAUXILIAR = 0 AND P.ATIVO = 'S' AND E.QTUNIT = (SELECT MIN(QTUNIT) FROM VW_INT_C5_EMBPROD WHERE E.CODFILIAL = CODFILIAL AND E.CODPROD = CODPROD ))
    )
    AND E.QTMINIMAATACADO >= 1
)*/

\

CREATE OR REPLACE VIEW VW_INT_C5_PROMOCOES_VIGENTES AS
(
  --OFERTA 2011 VAREJO
   SELECT
    PCOFERTAPROGRAMADAC.CODOFERTA || ' - 2011' IDREF, 
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    PCEMBALAGEM.QTUNIT QTDEMBALAGEM,
    1 NROSEGMENTO,  
    PCOFERTAPROGRAMADAI.VLOFERTA PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    decode(PCOFERTAPROGRAMADAC.HORAINICIAL, null, 1, 0) PRIORIDADE,
    PCEMBALAGEM.PVENDA PRECONORMAL    
  FROM 
    PCOFERTAPROGRAMADAI
  INNER JOIN PCOFERTAPROGRAMADAC
  ON (PCOFERTAPROGRAMADAC.CODOFERTA = PCOFERTAPROGRAMADAI.CODOFERTA)  

  INNER JOIN PCEMBALAGEM
  ON (PCEMBALAGEM.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR AND PCOFERTAPROGRAMADAI.CODFILIAL = PCEMBALAGEM.CODFILIAL)

  INNER JOIN PCDEPARAPRODC5 
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S')  
      OR (PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD  AND PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCDEPARAPRODC5.ATIVO = 'S'))

  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCOFERTAPROGRAMADAI.CODFILIAL AND C5.CODFILIAL = PCOFERTAPROGRAMADAC.CODFILIAL)
  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD AND PROD.CODPROD = PCOFERTAPROGRAMADAI.CODPROD)
  WHERE 
  	PCOFERTAPROGRAMADAC.DTINICIAL IS NOT NULL
	AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCOFERTAPROGRAMADAC.DTFINAL IS NOT NULL
    AND PCOFERTAPROGRAMADAC.DTCANCEL IS NULL
    AND PCOFERTAPROGRAMADAI.DATAEXCLUSAO IS NULL
    AND TRUNC(SYSDATE) BETWEEN PCOFERTAPROGRAMADAC.DTINICIAL AND PCOFERTAPROGRAMADAC.DTFINAL
	  --   TO_DATE(TO_CHAR(PCOFERTAPROGRAMADAC.DTINICIAL, 'DD-MM-YY')   || ' ' || NVL(TO_CHAR(PCOFERTAPROGRAMADAC.HORAINICIAL, 'HH24:MI:SS'), '00:00:01' ),'DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
	  --	  AND TO_DATE(TO_CHAR(PCOFERTAPROGRAMADAC.DTFINAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(PCOFERTAPROGRAMADAC.HORAFINAL  , 'HH24:MI:SS'), '23:59:59' ),'DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
    AND PCOFERTAPROGRAMADAI.VLOFERTA > 0
    AND PCOFERTAPROGRAMADAC.PRIORIDADEOFERTA = (
      SELECT MIN(P.PRIORIDADEOFERTA)
      FROM PCOFERTAPROGRAMADAC P
      INNER JOIN PCOFERTAPROGRAMADAI I
      ON (P.CODOFERTA = I.CODOFERTA)
      WHERE 
        P.DTINICIAL IS NOT NULL
        AND P.DTFINAL IS NOT NULL
        AND P.DTCANCEL IS NULL
        AND I.DATAEXCLUSAO IS NULL
        AND I.CODPROD = PCOFERTAPROGRAMADAI.CODPROD 
        AND I.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR 
        AND I.CODFILIAL = PCOFERTAPROGRAMADAI.CODFILIAL 
        AND TRUNC(SYSDATE) BETWEEN P.DTINICIAL AND P.DTFINAL
          --TO_DATE(TO_CHAR(P.DTINICIAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(P.HORAINICIAL, 'HH24:MI:SS'), '00:00:01' ), 'DD-MM-YY HH24:MI:SS', 'NLS_DATE_LANGUAGE = AMERICAN')
          --AND TO_DATE(TO_CHAR(P.DTFINAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(P.HORAFINAL, 'HH24:MI:SS'), '23:59:59' ), 'DD-MM-YY HH24:MI:SS', 'NLS_DATE_LANGUAGE = AMERICAN')
        AND I.VLOFERTA > 0
    )
 AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    
 UNION ALL 
--OFERTA 2011 ATACADO
 SELECT
    PCOFERTAPROGRAMADAC.CODOFERTA || ' - 2011' IDREF, 
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    PCEMBALAGEM.QTMINIMAATACADO QTDEMBALAGEM,
    1 NROSEGMENTO,  
    LEAST(ROUNDABNT((PCOFERTAPROGRAMADAI.VLOFERTAATAC / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    decode(PCOFERTAPROGRAMADAC.HORAINICIAL, null, 1, 0) PRIORIDADE,
    LEAST(ROUNDABNT((PCEMBALAGEM.PVENDAATAC / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECONORMAL
  FROM 
    PCOFERTAPROGRAMADAI
  INNER JOIN PCOFERTAPROGRAMADAC
  ON (PCOFERTAPROGRAMADAC.CODOFERTA = PCOFERTAPROGRAMADAI.CODOFERTA)  

  INNER JOIN PCEMBALAGEM
  ON (PCEMBALAGEM.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR AND PCOFERTAPROGRAMADAI.CODFILIAL = PCEMBALAGEM.CODFILIAL)

  INNER JOIN PCDEPARAPRODC5 
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S') OR
   (PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S') )
   
  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCOFERTAPROGRAMADAI.CODFILIAL AND C5.CODFILIAL = PCOFERTAPROGRAMADAC.CODFILIAL)

  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD AND PROD.CODPROD = PCOFERTAPROGRAMADAI.CODPROD)
  WHERE 
  	PCOFERTAPROGRAMADAC.DTINICIAL IS NOT NULL
	AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCOFERTAPROGRAMADAC.DTFINAL IS NOT NULL
    AND PCOFERTAPROGRAMADAC.DTCANCEL IS NULL
    AND PCOFERTAPROGRAMADAI.DATAEXCLUSAO IS NULL    
    AND TRUNC(SYSDATE) BETWEEN PCOFERTAPROGRAMADAC.DTINICIAL AND PCOFERTAPROGRAMADAC.DTFINAL
	    --TO_DATE(TO_CHAR(PCOFERTAPROGRAMADAC.DTINICIAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(PCOFERTAPROGRAMADAC.HORAINICIAL, 'HH24:MI:SS'), '00:00:01' ),'DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
		  --AND TO_DATE(TO_CHAR(PCOFERTAPROGRAMADAC.DTFINAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(PCOFERTAPROGRAMADAC.HORAFINAL  , 'HH24:MI:SS'), '23:59:59' ),'DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
    AND PCOFERTAPROGRAMADAI.VLOFERTAATAC > 0
    AND PCOFERTAPROGRAMADAC.PRIORIDADEOFERTA = (
      SELECT MIN(P.PRIORIDADEOFERTA)
      FROM PCOFERTAPROGRAMADAC P
      INNER JOIN PCOFERTAPROGRAMADAI I
      ON (P.CODOFERTA = I.CODOFERTA)
      WHERE 
        P.DTINICIAL IS NOT NULL
        AND P.DTFINAL IS NOT NULL
        AND P.DTCANCEL IS NULL
        AND I.DATAEXCLUSAO IS NULL
        AND I.CODPROD = PCOFERTAPROGRAMADAI.CODPROD 
        AND I.CODAUXILIAR = PCOFERTAPROGRAMADAI.CODAUXILIAR 
        AND I.CODFILIAL = PCOFERTAPROGRAMADAI.CODFILIAL 
        AND TRUNC(SYSDATE) BETWEEN P.DTINICIAL AND P.DTFINAL
          --TO_DATE(TO_CHAR(P.DTINICIAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(P.HORAINICIAL, 'HH24:MI:SS'), '00:00:01' ), 'DD-MM-YY HH24:MI:SS', 'NLS_DATE_LANGUAGE = AMERICAN')
          --AND TO_DATE(TO_CHAR(P.DTFINAL, 'DD-MM-YY') || ' ' || NVL(TO_CHAR(P.HORAFINAL, 'HH24:MI:SS'), '23:59:59' ), 'DD-MM-YY HH24:MI:SS', 'NLS_DATE_LANGUAGE = AMERICAN')
        AND I.VLOFERTAATAC > 0
    )
    AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'

  UNION ALL

  SELECT
    PCEMBALAGEM.CODAUXILIAR || ' - 2017' IDREF,
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    PCEMBALAGEM.QTUNIT QTDEMBALAGEM,  
    1 NROSEGMENTO,  
    PCEMBALAGEM.POFERTA PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    2 PRIORIDADE,
    PCEMBALAGEM.PVENDA PRECONORMAL
  FROM 
    PCEMBALAGEM

  INNER JOIN PCDEPARAPRODC5
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S')
  OR (PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.CODAUXILIAR =0 AND PCDEPARAPRODC5.ATIVO = 'S'))
  
  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCEMBALAGEM.CODFILIAL)
  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD)
  WHERE  
  	PCEMBALAGEM.DTOFERTAINI IS NOT NULL
    AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCEMBALAGEM.DTOFERTAFIM IS NOT NULL 
    AND TRUNC(SYSDATE) BETWEEN PCEMBALAGEM.DTOFERTAINI AND PCEMBALAGEM.DTOFERTAFIM
     --TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAINI, 'DD-MM-YY') || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') 
      --AND TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAFIM, 'DD-MM-YY')  || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
    AND PCEMBALAGEM.POFERTA > 0
    AND PCEMBALAGEM.QTUNIT  > 0
    AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    
  UNION ALL 

  SELECT
    PCEMBALAGEM.CODAUXILIAR ||' - 2017' IDREF,
    PCDEPARAPRODC5.SEQPRODUTO,
    c5.codfilialintegracao NROEMPRESA,
    PCEMBALAGEM.QTMINIMAATACADO QTDEMBALAGEM,
    1 NROSEGMENTO,  
    LEAST(ROUNDABNT((PCEMBALAGEM.POFERTAATAC / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECO,
    'S' PROMOCAO,
    'S' ATIVO,
    2 PRIORIDADE,
    LEAST(ROUNDABNT((PCEMBALAGEM.PVENDAATAC / PCEMBALAGEM.QTUNIT) * PCEMBALAGEM.QTMINIMAATACADO, 3), 9999999.999) PRECONORMAL
  FROM 
    PCEMBALAGEM

  INNER JOIN PCDEPARAPRODC5
  ON ((PCDEPARAPRODC5.CODAUXILIAR = PCEMBALAGEM.CODAUXILIAR AND PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.ATIVO = 'S') 
  OR (PCEMBALAGEM.CODPROD = PCDEPARAPRODC5.CODPROD AND PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCDEPARAPRODC5.ATIVO = 'S'))
  
  INNER JOIN VW_INT_C5_OBTER_FILIAIS_C5 C5
  ON (C5.CODFILIAL =  PCEMBALAGEM.CODFILIAL)
  INNER JOIN PCPRODUT PROD
  ON (PROD.CODPROD = PCEMBALAGEM.CODPROD)
  WHERE
  	PCEMBALAGEM.DTOFERTAATACINI IS NOt NULL
	AND LENGTH(PCEMBALAGEM.CODAUXILIAR) <= 14
	AND PCEMBALAGEM.DTINATIVO IS NULL
	AND PROD.DTEXCLUSAO IS NULL
    AND LENGTH(PROD.NBM) >= 2
    AND PCEMBALAGEM.CODPROD >= 0
  	AND PCEMBALAGEM.DTOFERTAATACFIM IS NOT null
    AND TRUNC(SYSDATE) BETWEEN PCEMBALAGEM.DTOFERTAATACINI AND PCEMBALAGEM.DTOFERTAATACFIM
      --TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAATACINI, 'DD-MM-YY')|| ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')
      -- AND TO_DATE(TO_CHAR(PCEMBALAGEM.DTOFERTAATACFIM, 'DD-MM-YY')  || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN')    
    AND PCEMBALAGEM.POFERTAATAC > 0
    AND PCEMBALAGEM.QTMINIMAATACADO > 0
    AND PCEMBALAGEM.ENVIAFRENTECAIXA = 'S'
    
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODCOMPOSTO AS
(

SELECT
  (SELECT X.SEQPRODUTO FROM PCDEPARAPRODC5 X WHERE X.CODPROD = CESTA.CODPRODACAB AND X.ATIVO = 'S' AND ROWNUM = 1)SEQPRODCOMPOSTO,
  CESTA.SEQPRODUTO,
  CESTA.QTDEMBALAGEM,
  CESTA.QUANTIDADE,
  
  (CASE
       WHEN (TRUNC(SYSDATE) BETWEEN C.DTINICIO AND C.DTFIM) AND (NVL(I.PRECOFIXO,0) > 0) THEN
            I.PRECOFIXO
       WHEN (TRUNC(SYSDATE) BETWEEN C.DTINICIO AND C.DTFIM) AND (NVL(I.PERCDESC,0) > 0) THEN
            CESTA.PRECO - (ABS(CESTA.PRECO * I.PERCDESC / 100))
       ELSE CESTA.PRECO
  END)PRECO,
  
  CESTA.ATIVO,
  CESTA.CODPRODACAB IDREF
FROM(/*SELECT BASE, SEM A VALIDAÇÃO COM A PRECOCESTAC E PRECOCESTA I QUE NEM SEMPRE ESTARÃO POPULADAS*/
     SELECT DISTINCT
       F.CODPRODACAB CODPRODACAB,
       (SELECT X.CODAUXILIAR FROM PCEMBALAGEM X WHERE X.CODPROD = F.CODPRODACAB AND X.CODFILIAL = F.CODFILIAL AND ROWNUM = 1) CODAUXILIAR_PRODACAB,
       E.CODFILIALINTEGRACAO NROEMPRESA,
	   F.CODFILIAL CODFILIAL,
       P.SEQPRODUTO,
       F.CODAUXILIARMP CODAUXILIAR,
       F.CODPRODMP,
       (CASE
         WHEN FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('FIL_PRECOPOREMBALAGEM', F.CODFILIAL, 'N') = 'S' THEN
              COLUNA_PRECO(BUSCAPRECOS(F.CODFILIAL, 0, F.CODAUXILIARMP, TRUNC(SYSDATE)),'PVENDA')
         ELSE COLUNA_PRECO(BUSCAPRECOS(F.CODFILIAL, FERRAMENTAS.F_BUSCARPARAMETRO_NUM('NUMREGIAOPADRAOVAREJO', F.CODFILIAL, 1), F.CODAUXILIARMP, TRUNC(SYSDATE)),'PVENDA1')
       END) PRECO,
       E.qtunit QTDEMBALAGEM,
       F.QTPRODMP QUANTIDADE,
       E.ATIVO
     FROM VW_INT_C5_EMBPROD E,
          PCFORMPROD F,
          PCDEPARAPRODC5 P
     WHERE E.codprod = F.CODPRODMP
     AND   E.codauxiliar = F.CODAUXILIARMP
     AND   ((P.CODPROD = E.codprod) AND (P.CODAUXILIAR = 0) OR
            (P.CODPROD = E.codprod) AND (P.CODAUXILIAR = E.codauxiliar)
           )  
           
     AND   ((P.CODPROD = F.codprodMP) AND (P.CODAUXILIAR = 0) OR
            (P.CODPROD = F.codprodMP) AND (P.CODAUXILIAR = F.codauxiliarMP)
           )
           
     
     AND   P.ATIVO = 'S'
     AND   F.CODFILIAL IS NOT NULL
     AND   NVL(F.CODFILIAL, E.CODFILIAL) = E.CODFILIAL
     
     /*TRATATIVA PARA NÃO DEIXAR DESCER A CESTA CASO UM DOS ITENS ESTEJA COM PREÇO ZERADO*/
     AND   NOT EXISTS (SELECT EMB_PRECO.CODAUXILIAR
                       FROM VW_INT_C5_EMBPROD EMB_PRECO,
                            PCFORMPROD FP
                       WHERE EMB_PRECO.pvenda <= 0
                       AND EMB_PRECO.codprod = FP.CODPRODMP
                       AND EMB_PRECO.codauxiliar = FP.CODAUXILIARMP
                       AND EMB_PRECO.codfilial = FP.CODFILIAL
                       AND FP.CODFILIAL = F.CODFILIAL
                       AND FP.CODPRODACAB = F.CODPRODACAB
                       AND NVL(FP.CODFILIAL, EMB_PRECO.CODFILIAL) = EMB_PRECO.CODFILIAL
                      )
     
     /*TRATATIVA PARA NÃO DEIXAR DESCER A CESTA CASO UM DOS ITENS ESTEJA INATIVO*/
     AND   NOT EXISTS(SELECT EMB.CODAUXILIAR
                      FROM PCEMBALAGEM EMB, -- ANALISAR PELA PCEMBALAGEM PQ A VIEW EMBPROD NAO TRAZ REGISTROS INATIVADOS
                           PCFORMPROD FP,
                           PCPRODUT PR,
                           PCPRODFILIAL PRODFILIAL
                      WHERE EMB.CODPROD = FP.CODPRODMP
                      AND   EMB.CODAUXILIAR = FP.CODAUXILIARMP
                      AND   EMB.CODPROD = PR.CODPROD
                      AND   NVL(FP.CODFILIAL, EMB.CODFILIAL) = EMB.CODFILIAL
                      AND   FP.CODPRODACAB = F.CODPRODACAB
                      AND   EMB.CODPROD = PRODFILIAL.CODPROD
                      AND   EMB.CODFILIAL = PRODFILIAL.CODFILIAL
                      AND   FP.CODPRODMP = PRODFILIAL.CODPROD
                      AND   FP.CODFILIAL = PRODFILIAL.CODFILIAL
                      AND   FP.CODPRODACAB = PRODFILIAL.CODPROD
                      AND   PR.CODPROD = PRODFILIAL.CODPROD
                      AND   ((DTINATIVO IS NOT NULL) OR (PR.DTEXCLUSAO IS NOT NULL) OR (NVL(PRODFILIAL.PROIBIDAVENDA, 'N') = 'N'))
                     )
    ) CESTA,
    --PCPRECOCESTAC C,
    (SELECT * FROM PCPRECOCESTAC WHERE TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM) C,
    PCPRECOCESTAI I,
    PCDEPARAPRODC5 EMBC5
WHERE CESTA.CODPRODACAB = I.CODPRODACAB(+) 
--AND   NVL(C.CODPRECOCESTA, 1) = NVL(I.CODPRECOCESTA, 1)
AND   I.CODPRECOCESTA = C.CODPRECOCESTA(+)
AND   CESTA.CODPRODMP = NVL(I.CODPRODMP, CESTA.CODPRODMP)
AND   CESTA.CODFILIAL = NVL(I.CODFILIAL, CESTA.CODFILIAL)
--AND  EMBC5.CODAUXILIAR = CESTA.CODAUXILIAR_PRODACAB/*Clausula para eliminar cestas que estao com cadastro inconsistentes*/
AND  ((EMBC5.CODPROD = CESTA.CODPRODACAB) AND (EMBC5.CODAUXILIAR = 0) OR
      (EMBC5.CODPROD = CESTA.CODPRODACAB) AND (EMBC5.CODAUXILIAR = CESTA.CODAUXILIAR_PRODACAB)
     )
AND   EMBC5.ATIVO = 'S'     
)
