CREATE OR REPLACE VIEW VW_INT_C5_RECARGACEL AS
(
SELECT  
        D.SEQDOCTO,
        D.NROEMPRESA,
        D.NROCHECKOUT,
        
        CASE
          WHEN D.ESPECIE = 'RP' THEN
               'R' 
          ELSE 'V' 
        END TIPOOPERACAO,

        CASE
          WHEN D.ESPECIE = 'RP' THEN
               'Recarga Celular '|| P.OPERADORA 
          ELSE 'Vale Gas '|| P.OPERADORA 
        END INFPRODUTO,
        
        PG.NSUTEF,
        P.VALOR,
        TO_CHAR(P.DTAHOREMISSAO, 'YYYY-MM-DD') DTAHOREMISSAO,
        P.CODIGO,
        D.SEQUSUARIO,
        D.COO,
        P.OPERADORA
  FROM  MONITORPDVMIDDLE.TB_DOCTO D,
        MONITORPDVMIDDLE.TB_DOCTOPREPAGO P,
        MONITORPDVMIDDLE.TB_DOCTOPAGTO PG
 WHERE  D.SEQDOCTO = P.SEQDOCTO
 AND    D.NROEMPRESA = P.NROEMPRESA
 AND    D.NROCHECKOUT = P.NROCHECKOUT
 AND    D.SEQDOCTO = PG.SEQDOCTO
 AND    D.NROEMPRESA = PG.NROEMPRESA
 AND    D.NROCHECKOUT = PG.NROCHECKOUT
 AND    PG.SEQDOCTO = P.SEQDOCTO
 AND    PG.NROEMPRESA = P.NROEMPRESA
 AND    PG.NROCHECKOUT = P.NROCHECKOUT
 AND    D.REPLICACAO = 'P'
 AND    D.ESPECIE IN ('RP', 'VG')
)