CREATE OR REPLACE VIEW VW_INT_C5_RECARGACEL AS
(
SELECT  D.SEQDOCTO,
        D.NROEMPRESA,
        D.NROCHECKOUT,
        
        CASE
          WHEN D.ESPECIE = 'RP' THEN
               'R' 
          ELSE 'V' 
        END TIPOOPERACAO,

        CASE
          WHEN D.ESPECIE = 'RP' THEN
               'Recarga Celular '|| P.OPERADORA 
          ELSE 'Vale Gas '|| P.OPERADORA 
        END INFPRODUTO,

        CASE
          WHEN D.ESPECIE = 'RP' THEN
               P.CODIGOFILIAL
          ELSE '137'
        END CodOperRecargaCel,
        
        CASE
          WHEN  D.ESPECIE = 'RP' THEN
                PG.NSUTEF
          ELSE (SELECT NSUTEF FROM MONITORPDVMIDDLE.TB_DOCTOTEF WHERE SEQDOCTO = D.SEQDOCTO AND NROEMPRESA = D.NROEMPRESA AND NROCHECKOUT = D.NROCHECKOUT)
        END VALOR,
        
        CASE
          WHEN  D.ESPECIE = 'RP' THEN
                P.VALOR
          ELSE (SELECT VLRTOTAL FROM MONITORPDVMIDDLE.TB_DOCTOTEF WHERE SEQDOCTO = D.SEQDOCTO AND NROEMPRESA = D.NROEMPRESA AND NROCHECKOUT = D.NROCHECKOUT)
        END VALOR, 

        TO_CHAR(D.DTAHOREMISSAO, 'YYYY-MM-DD') DTAHOREMISSAO,
        TO_CHAR(D.DTAMOVIMENTO, 'YYYY-MM-DD') DTAMOVIMENTO,
        
        CASE
          WHEN  D.ESPECIE = 'RP' THEN
                P.CODIGO
          ELSE  ''
        END CODIGO,

        D.SEQUSUARIO,
        D.COO,
 
        CASE
          WHEN  D.ESPECIE = 'RP' THEN
                P.OPERADORA
          ELSE  ''
        END OPERADORA
        
  FROM  MONITORPDVMIDDLE.TB_DOCTO D,
        MONITORPDVMIDDLE.TB_DOCTOPREPAGO P,
        MONITORPDVMIDDLE.TB_DOCTOPAGTO PG
 WHERE  D.SEQDOCTO = P.SEQDOCTO(+)
 AND    D.NROEMPRESA = P.NROEMPRESA(+)
 AND    D.NROCHECKOUT = P.NROCHECKOUT(+)
 AND    D.SEQDOCTO    = PG.SEQDOCTO
 AND    D.NROEMPRESA  = PG.NROEMPRESA
 AND    D.NROCHECKOUT = PG.NROCHECKOUT
 AND    D.REPLICACAO = 'P'
 AND    D.ESPECIE IN ('RP', 'VG')
)