CREATE OR REPLACE TRIGGER TRG_INATIVACAOPCEMBALAGEM_C5 BEFORE
  INSERT OR UPDATE ON PCEMBALAGEM REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
  VSEQPRODUTO PCDEPARAPRODC5.SEQPRODUTO%TYPE;
BEGIN
  IF FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('USAINTEGRACAOCONSINCO', :OLD.CODFILIAL, 'N') = 'S' THEN
    BEGIN
      SELECT
        SEQPRODUTO INTO VSEQPRODUTO
      FROM
        PCDEPARAPRODC5 DEPARA
      WHERE 1 =1 
	    AND (
        (DEPARA.CODAUXILIAR = :OLD.CODAUXILIAR
	    AND DEPARA.CODPROD = :OLD.CODPROD
		AND DEPARA.ATIVO = 'S') 
		OR 
		(DEPARA.CODAUXILIAR = 0
	    AND DEPARA.CODPROD = :OLD.CODPROD
		AND DEPARA.ATIVO = 'N'));
    EXCEPTION 
      WHEN NO_DATA_FOUND THEN 
        VSEQPRODUTO := NULL;
    END;

    IF VSEQPRODUTO IS NOT NULL THEN
      IF (NVL(:NEW.QTUNIT, 0) <> NVL(:OLD.QTUNIT, 0)) THEN
        MERGE INTO PCINATIVACAOEMBALAGEMC5 P USING (
            SELECT
              :OLD.CODFILIAL                         NROEMPRESA,
              1                                      NROSEGMENTO,
              VSEQPRODUTO                            SEQPRODUTO,
              LEAST(NVL(:OLD.QTUNIT, 1), 999999.999) QTDEMBALAGEM
            FROM
              DUAL
          ) T 
        ON ( P.NROEMPRESA = T.NROEMPRESA
          AND P.NROSEGMENTO = T.NROSEGMENTO
          AND P.SEQPRODUTO = T.SEQPRODUTO
          AND P.QTDEMBALAGEM = T.QTDEMBALAGEM 
        )
        WHEN NOT MATCHED THEN
          INSERT (
            P.NROEMPRESA,
            P.NROSEGMENTO,
            P.SEQPRODUTO,
            P.QTDEMBALAGEM
          ) VALUES (
            T.NROEMPRESA,
            T.NROSEGMENTO,
            T.SEQPRODUTO,
            T.QTDEMBALAGEM
          );
        END IF;

        IF (NVL(:NEW.QTMINIMAATACADO, 0) <> NVL(:OLD.QTMINIMAATACADO, 0)) 
		AND (FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('FIL_PRECOPOREMBALAGEM',
                                               :OLD.CODFILIAL,
                                               'N') = 'S') THEN
          MERGE INTO PCINATIVACAOEMBALAGEMC5 P 
          USING (
              SELECT
                :OLD.CODFILIAL                                  NROEMPRESA,
                1                                               NROSEGMENTO,
                VSEQPRODUTO                                     SEQPRODUTO,
                LEAST(NVL(:OLD.QTMINIMAATACADO, 1), 999999.999) QTDEMBALAGEM
              FROM
                DUAL
          ) T 
          ON ( P.NROEMPRESA = T.NROEMPRESA
            AND P.NROSEGMENTO = T.NROSEGMENTO
            AND P.SEQPRODUTO = T.SEQPRODUTO
            AND P.QTDEMBALAGEM = T.QTDEMBALAGEM 
          ) 
          WHEN NOT MATCHED THEN
            INSERT (
              P.NROEMPRESA,
              P.NROSEGMENTO,
              P.SEQPRODUTO,
              P.QTDEMBALAGEM
            ) VALUES (
              T.NROEMPRESA,
              T.NROSEGMENTO,
              T.SEQPRODUTO,
              T.QTDEMBALAGEM
            );
          END IF;
        END IF;
      END IF;
    END;


\


CREATE OR REPLACE TRIGGER TRG_INATIVACAOPCPRODFILIAL_C5
  BEFORE INSERT OR UPDATE ON PCPRODFILIAL
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
DECLARE
  VSEQPRODUTO PCDEPARAPRODC5.SEQPRODUTO%TYPE;
BEGIN
  IF FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('USAINTEGRACAOCONSINCO',
                                        :OLD.CODFILIAL,
                                        'N') = 'S' THEN

    FOR EMBALAGENS IN (SELECT DEPARAEMB.SEQPRODUTO
                         FROM PCDEPARAPRODC5 DEPARAEMB, PCEMBALAGEM E
                        WHERE ((DEPARAEMB.CODAUXILIAR = E.CODAUXILIAR
						  AND DEPARAEMB.CODPROD = E.CODPROD
						  AND DEPARAEMB.ATIVO = 'S') 
						   OR (DEPARAEMB.CODAUXILIAR = 0
						  AND DEPARAEMB.CODPROD = E.CODPROD 
						  AND DEPARAEMB.ATIVO = 'S'))
                          AND E.CODPROD = :OLD.CODPROD 
                          AND E.CODFILIAL = :OLD.CODFILIAL) LOOP

      VSEQPRODUTO := EMBALAGENS.SEQPRODUTO;

      IF VSEQPRODUTO IS NOT NULL THEN

        IF (NVL(:NEW.QTMINIMAATACADO, 0) <> NVL(:OLD.QTMINIMAATACADO, 0)) AND
           (FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('FIL_PRECOPOREMBALAGEM',
                                               :OLD.CODFILIAL,
                                               'N') = 'N') THEN
          MERGE INTO PCINATIVACAOEMBALAGEMC5 P
          USING (SELECT :OLD.CODFILIAL NROEMPRESA,
                        1 NROSEGMENTO,
                        VSEQPRODUTO SEQPRODUTO,
                        LEAST(NVL(:OLD.QTMINIMAATACADO, 1), 999999.999) QTDEMBALAGEM
                   FROM DUAL) T
          ON (P.NROEMPRESA = T.NROEMPRESA AND P.NROSEGMENTO = T.NROSEGMENTO AND P.SEQPRODUTO = T.SEQPRODUTO AND P.QTDEMBALAGEM = T.QTDEMBALAGEM)
          WHEN NOT MATCHED THEN
            INSERT
              (P.NROEMPRESA, P.NROSEGMENTO, P.SEQPRODUTO, P.QTDEMBALAGEM)
            VALUES
              (T.NROEMPRESA, T.NROSEGMENTO, T.SEQPRODUTO, T.QTDEMBALAGEM);
        END IF;
      END IF;
    END LOOP;
  END IF;
END;