CREATE OR REPLACE TRIGGER TRG_INATIVACAOPCEMBALAGEM_C5
 BEFORE INSERT OR UPDATE
        ON PCEMBALAGEM
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN   
  IF FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('USAINTEGRACAOCONSINCO', :old.CODFILIAL, 'N') = 'S' THEN
    IF (:new.QTUNIT <> :old.QTUNIT) THEN

      MERGE INTO PCINATIVACAOEMBALAGEMC5 P
      USING (SELECT :old.CODFILIAL NROEMPRESA, 1 NROSEGMENTO, (SELECT SEQPRODUTO FROM PCDEPARAEMBALAGENSC5 WHERE CODAUXILIAR = :old.CODAUXILIAR) SEQPRODUTO, LEAST(NVL(:old.QTUNIT, 1), 999999.999) QTDEMBALAGEM FROM DUAL) T
      ON (
        P.NROEMPRESA = T.NROEMPRESA
        AND P.NROSEGMENTO = T.NROSEGMENTO
        AND P.SEQPRODUTO = T.SEQPRODUTO
        AND P.QTDEMBALAGEM = T.QTDEMBALAGEM
      )
      WHEN NOT MATCHED THEN
        INSERT (
          P.NROEMPRESA,
          P.NROSEGMENTO,
          P.SEQPRODUTO,
          P.QTDEMBALAGEM        
        ) VALUES (
          T.NROEMPRESA,
          T.NROSEGMENTO,
          T.SEQPRODUTO,
          T.QTDEMBALAGEM
        );
          
    END IF;

    IF (:new.QTMINIMAATACADO <> :old.QTMINIMAATACADO) THEN
    MERGE INTO PCINATIVACAOEMBALAGEMC5 P
      USING (SELECT :OLD.CODFILIAL NROEMPRESA, 1 NROSEGMENTO, (SELECT SEQPRODUTO FROM PCDEPARAEMBALAGENSC5 WHERE CODAUXILIAR = :OLD.CODAUXILIAR) SEQPRODUTO, LEAST(NVL(:OLD.QTMINIMAATACADO, 1), 999999.999) QTDEMBALAGEM FROM DUAL) T
      ON (
        P.NROEMPRESA = T.NROEMPRESA
        AND P.NROSEGMENTO = T.NROSEGMENTO
        AND P.SEQPRODUTO = T.SEQPRODUTO
        AND P.QTDEMBALAGEM = T.QTDEMBALAGEM
      )
      WHEN NOT MATCHED THEN
      INSERT (
        P.NROEMPRESA,
        P.NROSEGMENTO,
        P.SEQPRODUTO,
        P.QTDEMBALAGEM
      ) VALUES (
        T.NROEMPRESA,
        T.NROSEGMENTO,
        T.SEQPRODUTO,
        T.QTDEMBALAGEM
      );
    END IF;
  END IF;
END;
