DECLARE
  EXISTE_UNIQUE NUMBER;
  nomeCampo     VARCHAR2(60) := 'PCINTEGRACAOFLUXOEXECUCAO_UK1';
  nometabela    VARCHAR2(60) := 'PCINTEGRACAOFLUXOEXECUCAO';
  vScript       VARCHAR2(4000);
BEGIN
  BEGIN
    SELECT COUNT(1)
      INTO EXISTE_UNIQUE
      FROM All_Constraints A
     WHERE A.TABLE_NAME = nometabela
       AND A.INDEX_NAME IS NOT NULL
       AND A.CONSTRAINT_NAME = nomeCampo;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      EXISTE_UNIQUE := 0;
  END;
  IF EXISTE_UNIQUE <> 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PCINTEGRACAOFLUXOEXECUCAO DROP CONSTRAINT PCINTEGRACAOFLUXOEXECUCAO_UK1 CASCADE';
  END IF;

  vScript := 'ALTER TABLE PCINTEGRACAOFLUXOEXECUCAO ADD CONSTRAINT PCINTEGRACAOFLUXOEXECUCAO_UK1 UNIQUE (DESCRICAO, ORDEMEXECUCAO)';
  execute immediate vscript;

END;