DECLARE
  V_CONTADOR NUMBER;
BEGIN
  -- Verifica se a chave estrangeira PCAUXCAMPANHACUMULATIVAP_FK1 existe
  SELECT COUNT(*)
    INTO V_CONTADOR 
    FROM USER_CONSTRAINTS 
   WHERE CONSTRAINT_NAME = 'PCAUXCAMPANHACUMULATIVAP_FK1' AND CONSTRAINT_TYPE = 'R';
  
  IF V_CONTADOR > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PCAUXCAMPANHACUMULATIVAPROD DROP CONSTRAINT PCAUXCAMPANHACUMULATIVAP_FK1';
  END IF;
  
  -- Verifica se a chave estrangeira PCAUXCAMPANHACUMULATIVAP_FK2 existe
  SELECT COUNT(*)
    INTO V_CONTADOR 
    FROM USER_CONSTRAINTS 
   WHERE CONSTRAINT_NAME = 'PCAUXCAMPANHACUMULATIVAP_FK2' AND CONSTRAINT_TYPE = 'R';
  
  IF V_CONTADOR > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PCAUXCAMPANHACUMULATIVAPROD DROP CONSTRAINT PCAUXCAMPANHACUMULATIVAP_FK2';
  END IF;
END;
