DECLARE
  vCOUNT NUMBER;
  vSQL   VARCHAR2(400);
  
BEGIN
  SELECT COUNT(1)
    INTO vCOUNT    
    FROM USER_TAB_COLUMNS A
   WHERE A.COLUMN_NAME LIKE 'SOMAICMSTV10%'
     AND DATA_TYPE = 'NUMBER'
     AND TABLE_NAME = 'PCNFENTPREENT';
     
  IF vCOUNT > 0 THEN
    vSQL := 'ALTER TABLE PCNFENTPREENT DROP COLUMN SOMAICMSTV10'; 
    EXECUTE IMMEDIATE vSQL;
    vSQL := 'ALTER TABLE PCNFENTPREENT ADD SOMAICMSTV10 VARCHAR2(1)';
    EXECUTE IMMEDIATE vSQL; 
  END IF;
  
END;