CREATE OR REPLACE VIEW SQL_NFE_RODAPE_ENTRADA AS
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO
      ,NVL(SUM(PRODUTO.BASE_ICMS),
           0) AS BASE_ICMS
      ,NVL(SUM(PRODUTO.VALOR_ICMS),
           0) AS VALOR_ICMS
      ,NVL(SUM(PRODUTO.BASE_ST),
           0) AS BASE_ICMS_ST
      ,NVL(SUM(PRODUTO.VALOR_ST),
           0) AS VALOR_ICMS_ST --VST
      ,NVL(SUM(PRODUTO.VALOR_PRODUTOS),
           0) AS VALOR_TOTAL_PRODUTOS --VPROD
      ,NVL(SUM(PRODUTO.VALOR_FRETE),
           0) AS VALOR_FRETE --VFRETE
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),
           0) AS VALOR_DESCONTO --VDESC
      ,NVL(SUM(PRODUTO.VALOR_IPI),
           0) AS VALOR_IPI --VLIPI
      ,NVL(SUM(PRODUTO.VALOR_OUTROS),
           0) AS VALOR_OUTRO --VOUTRO
      ,PCNFENT.VLTOTAL AS VALOR_TOTAL --VNF
      ,NVL(SUM(PRODUTO.VALOR_II),
           0) AS VALOR_II
      ,SUM(PRODUTO.VALOR_COFINS) AS VALOR_COFINS
      ,SUM(PRODUTO.VALOR_PIS) AS VALOR_PIS
      ,0 AS BASE_ISS
      ,0 AS VALOR_ISS
       ------------------- FRETE AS ENTRADAS TIPO 4 E R E DEVOLUÇÃO 6 E 8 NÃO TEM FRETE---------------------
      ,DECODE(NVL(PCNFENT.TIPOFRETECIFFOB,
                  'N'),
              'C',
              0,
              'F',
              1,
              'T',
              2,              
              'R',
              3,
              'D',
              4,
              'G',
              9,
              'N',
              9,
              'S',
              9) AS MODALIDADE_FRETE
       --MODFRETE
      ,FRETEIRO.CGC AS CNPJ_TRANSPORTADOR
      ,FRETEIRO.FORNECEDOR AS TRANSPORTADOR
      ,FRETEIRO.IE AS IE_TRANSPORTADOR
      ,FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO AS END_TRANSPORTADOR
      ,FRETEIRO.CIDADE AS CIDADE_TRANSPORTADOR
      ,FRETEIRO.ESTADO AS ESTADO_TRANSPORTADOR
      ,DECODE(FINALIDADENFE, 'A', PCNFENT.MOTESTORNONFE, NULL) AS INFORMACAOADICIONALFISCO
       ------------------ VEICULO --------------------
      ,NVL(PCNFENT.PLACAVEICULO, PCVEICUL.PLACA) AS PLACA
       --PLACA
      ,PCVEICUL.ANTT,
       NVL(PCNFENT.UFVEICULO, PCVEICUL.UFPLACAVEICULO) AS PLACA_UF
       ------------------ GRUPO DE VOLUMES -----------
      ,SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL) QT
      ,SUM(NVL(PRODUTO.QUANTIDADE_TRIBUTAVEL,
                   0) * DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PESOLIQIGUALAPESOBRUTONFE',
                                                                 NVL(PCNFENT.CODFILIALNF,
                                                                     PCNFENT.CODFILIAL)),
                                   'N'),
                               'N',
                               NVL(PCPRODUT.PESOLIQ,
                                   0),
                               NVL(PCPRODUT.PESOBRUTO,
                                   0))) AS PESO_LIQUIDO
      ,NVL(MAX(PCNFENT.TOTPESO),
           SUM(NVL(PRODUTO.QUANTIDADE_TRIBUTAVEL,
                   0) * NVL(PCPRODUT.PESOBRUTO,
                            0))) AS PESO_BRUTO
      ,NVL(PCNFENT.NUMVOL, 0) AS NUM_VOLUME
      ,CASE WHEN (PCNFENT.TIPODESCARGA IN ('N','F')) THEN
              PCNFENT.MARCAVOLUME
          ELSE
              NULL
       END AS MARCAVOLUME
      ,PCNFENT.ESPECIEVOLUME
      ,TO_CHAR(NVL(PCNFENT.NUMVOL,DECODE(ROUND(SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL)), 0, 1, ROUND(SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL))))) NUMVOL
      ,0 VOLUME_PEDIDO
      ,CASE WHEN (PCNFENT.TIPODESCARGA IN ('N','F')) THEN
              PCNFENT.NUMVOLUME
          ELSE
              NULL
       END AS NVOL --CONTAINER,
      ,SUM(PRODUTO.NUMVOLUMESCONFERENCIA) AS NUMVOLUMESCONFERENCIA
      ,PCNFENT.DTENT DTENTREGA
      ,0 AS NUMCAR
      ,PCNFENT.CODMOTORISTADEVOL AS CODMOTORISTA
      ,PCEMPR.NOME AS NOME_MOTORISTA
      ,0 AS VLDESCRODAPE
      ,0 AS NUM_VOLUME_EMB
      ,NULL AS DESC_PL_PGTO
      ,PCNFENT.FINALIDADENFE
      ,0 AS VLFCPPART
      ,0 AS VLICMSPARTDEST
      ,0 AS VLICMSPARTREM
      ,0 AS VLBASEFCPICMS
      ,0 AS VLBASEFCPST
      ,0 AS VLBCFCPSTRET
      ,0 AS VLFCPSTRET
      ,0 AS VLCREDFCPICMSSN
      ,SUM(NVL(PRODUTO.VLFECP, 0)) AS VLFECP
      ,SUM(NVL(PRODUTO.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP
      ,0 AS VALOR_IPI_DEVOLVIDO   
      ,SUM(NVL(PRODUTO.QBCMONO, 0)) AS QBCMONO
      ,SUM(NVL(PRODUTO.VICMSMONO, 0)) AS VICMSMONO
      ,SUM(NVL(PRODUTO.QBCMONORETEN, 0)) AS QBCMONORETEN
      ,SUM(NVL(PRODUTO.VICMSMONORETEN, 0)) AS VICMSMONORETEN
      ,SUM(NVL(PRODUTO.QBCMONODIF, 0)) AS QBCMONODIF
      ,SUM(NVL(PRODUTO.VICMSMONODIF, 0)) AS VICMSMONODIF
      ,SUM(NVL(PRODUTO.QBCMONORET, 0)) AS QBCMONORET
      ,SUM(NVL(PRODUTO.VICMSMONORET, 0)) AS VICMSMONORET      
      ,PRODUTO.GERAGRPRETTRIB
      ,SUM(NVL(PRODUTO.VLPISRETORGPUB, 0)) AS VLPISRETORGPUB
      ,SUM(NVL(PRODUTO.VLCOFINSRETORGPUB, 0)) AS VLCOFINSRETORGPUB
      ,SUM(NVL(PRODUTO.VLCSLLRETORGPUB, 0)) AS VLCSLLRETORGPUB
      ,SUM(NVL(PRODUTO.VLIRPJRETORGPUB, 0)) AS VLIRPJRETORGPUB
      ,SUM(NVL(PRODUTO.VLBCIRRFRETORGPUB, 0)) AS VLBCIRRFRETORGPUB      
      ,SUM(PRODUTO.VLICMSDESONERACAO) AS VALOR_TOTAL_DESONERADO        
FROM   PCNFENT,
       PCPRODUT,
       PCVEICUL,
       PCFORNEC FRETEIRO,
       PCCONSUM,
       PCEMPR,
       TABLE(NFE_PRODUTO_ENTRADA(PCNFENT.NUMTRANSENT)) PRODUTO
WHERE  PCNFENT.NUMTRANSENT = PCNFENT.NUMTRANSENT
AND    PCNFENT.CODCONT <> NVL(PCCONSUM.CODCONTFRE,0)
AND    PCNFENT.CODCONT <> NVL(PCCONSUM.CODCONTOUT,0)
AND    PRODUTO.CODPROD = PCPRODUT.CODPROD
AND    PCNFENT.CODFORNECFRETE = FRETEIRO.CODFORNEC(+)
AND    PCNFENT.CODMOTORISTADEVOL = PCEMPR.MATRICULA(+)
AND    PCNFENT.CODENTVEICULO = PCVEICUL.CODVEICULO(+)
AND    NVL(PCNFENT.FINALIDADENFE, 'X') <> 'P'
--AND    NOT EXISTS (SELECT COUNT(*)FROM PCPRODCIAP WHERE CODPROD =PRODUTO.CODPROD)
AND    PCNFENT.ESPECIE IN('NF','NE','EI')
AND    PCNFENT.TIPODESCARGA NOT IN ('6', '8', 'C', 'N', 'F', 'T')
GROUP  BY PCNFENT.NUMTRANSENT,
          PCNFENT.VLST,
          PCNFENT.VLTOTAL,
          PCNFENT.BASEICST,
          PCNFENT.VLFRETE,
          PCNFENT.VLOUTRAS,
          PCNFENT.VLST,
          PCNFENT.VLIPI,
          PRODUTO.GERAGRPRETTRIB,
          PCNFENT.TOTPESO,
          PCNFENT.TOTPESOLIQ,
          PCNFENT.ESPECIEVOLUME,
          NVL(PCNFENT.PLACAVEICULO, PCVEICUL.PLACA),
          PCVEICUL.ANTT,
          NVL(PCNFENT.UFVEICULO, PCVEICUL.UFPLACAVEICULO),
          FRETEIRO.CGC,
          FRETEIRO.FORNECEDOR,
          FRETEIRO.IE,
          (FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO),
          FRETEIRO.CIDADE,
          FRETEIRO.ESTADO,
          PCNFENT.DTENT,
          PCNFENT.CODMOTORISTADEVOL,
          PCNFENT.TIPOFRETECIFFOB,
          PCEMPR.NOME,
          PCNFENT.NUMVOL,
          PCNFENT.NUMVOLUME,
          PCNFENT.MARCAVOLUME,
          PCNFENT.TIPODESCARGA,
          PCNFENT.MOTESTORNONFE,
          PCNFENT.FINALIDADENFE
-----------------------------------------
UNION ALL
-----------------------------------------
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO
      ,NVL(SUM(PRODUTO.BASE_ICMS),
           0) AS BASE_ICMS
      ,NVL(SUM(PRODUTO.VALOR_ICMS),
           0) AS VALOR_ICMS
      ,NVL(SUM(PRODUTO.BASE_ST),
           0) AS BASE_ICMS_ST
      ,NVL(SUM(PRODUTO.VALOR_ST),
           0) AS VALOR_ICMS_ST --VST
      ,NVL(SUM(PRODUTO.VALOR_PRODUTOS),
           0) AS VALOR_TOTAL_PRODUTOS --VPROD
      ,NVL(SUM(PRODUTO.VALOR_FRETE),
           0) AS VALOR_FRETE --VFRETE
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),
           0) AS VALOR_DESCONTO --VDESC
      ,NVL(SUM(PRODUTO.VALOR_IPI),
           0) AS VALOR_IPI --VLIPI
      ,NVL(SUM(PRODUTO.VALOR_OUTROS),
           0) AS VALOR_OUTRO --VOUTRO
      ,PCNFENT.VLTOTAL AS VALOR_TOTAL --VNF
      ,NVL(SUM(PRODUTO.VALOR_II),
           0) AS VALOR_II
      ,SUM(PRODUTO.VALOR_COFINS) AS VALOR_COFINS
      ,SUM(PRODUTO.VALOR_PIS) AS VALOR_PIS
      ,0 AS BASE_ISS
      ,0 AS VALOR_ISS
       ------------------- FRETE AS ENTRADAS TIPO 4 E R E DEVOLUÇÃO 6 E 8 NÃO TEM FRETE---------------------
      ,DECODE(NVL(PCNFENT.TIPOFRETECIFFOB,
                  'N'),
              'C',
              0,
              'F',
              1,
              'T',
              2,              
              'R',
              3,
              'D',
              4,
              'G',
              9,
              'N',
              9,
              'S',
              9) AS MODALIDADE_FRETE--MODFRETE
      ,FRETEIRO.CGC AS CNPJ_TRANSPORTADOR
      ,FRETEIRO.FORNECEDOR AS TRANSPORTADOR
      ,FRETEIRO.IE AS IE_TRANSPORTADOR
      ,FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO AS END_TRANSPORTADOR
      ,FRETEIRO.CIDADE AS CIDADE_TRANSPORTADOR
      ,FRETEIRO.ESTADO AS ESTADO_TRANSPORTADOR
      ,DECODE(FINALIDADENFE, 'A', PCNFENT.MOTESTORNONFE, NULL) AS INFORMACAOADICIONALFISCO
       ------------------ VEICULO --------------------
      ,NVL(PCNFENT.PLACAVEICULO, PCVEICUL.PLACA) AS PLACA
       --PLACA
      ,PCVEICUL.ANTT
      ,NVL(PCNFENT.UFVEICULO, PCVEICUL.UFPLACAVEICULO) AS PLACA_UF
       ------------------ GRUPO DE VOLUMES -----------
      ,SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL) QT
      ,SUM(NVL(PRODUTO.QUANTIDADE_TRIBUTAVEL,
                   0) * DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PESOLIQIGUALAPESOBRUTONFE',
                                                                 NVL(PCNFENT.CODFILIALNF,
                                                                     PCNFENT.CODFILIAL)),
                                   'N'),
                               'N',
                               NVL(0,
                                   0),
                               NVL(0,
                                   0))) AS PESO_LIQUIDO
      ,NVL(MAX(PCNFENT.TOTPESO),
           SUM(NVL(PRODUTO.QUANTIDADE_TRIBUTAVEL,
                   0) * NVL(0,
                            0))) AS PESO_BRUTO
      ,NVL(PCNFENT.NUMVOL, 0) AS NUM_VOLUME
      ,CASE WHEN (PCNFENT.TIPODESCARGA IN ('N','F')) THEN
              PCNFENT.MARCAVOLUME
          ELSE
              NULL
          END AS MARCAVOLUME
      ,PCNFENT.ESPECIEVOLUME
      ,TO_CHAR(NVL(PCNFENT.NUMVOL,DECODE(ROUND(SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL)), 0, 1, ROUND(SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL))))) NUMVOL
      ,0 VOLUME_PEDIDO
      ,CASE WHEN (PCNFENT.TIPODESCARGA IN ('N','F')) THEN
              PCNFENT.NUMVOLUME
          ELSE
              NULL
       END AS NVOL --CONTAINER,
      ,SUM(PRODUTO.NUMVOLUMESCONFERENCIA) AS NUMVOLUMESCONFERENCIA
      ,PCNFENT.DTENT DTENTREGA
      ,0 AS NUMCAR
      ,PCNFENT.CODMOTORISTADEVOL AS CODMOTORISTA
      ,PCEMPR.NOME AS NOME_MOTORISTA
      ,0 AS VLDESCRODAPE
      ,0 AS NUM_VOLUME_EMB
      ,NULL AS DESC_PL_PGTO
      ,PCNFENT.FINALIDADENFE
      ,SUM(NVL(PRODUTO.VLFCPPART, 0)) AS VLFCPPART
      ,SUM(NVL(PRODUTO.VLICMSPARTDEST, 0)) AS VLICMSPARTDEST
      ,SUM(NVL(PRODUTO.VLICMSPARTREM, 0)) AS VLICMSPARTREM
      ,SUM(NVL(PRODUTO.VLBASEFCPICMS, 0)) AS VLBASEFCPICMS
      ,SUM(NVL(PRODUTO.VLBASEFCPST, 0)) AS VLBASEFCPST
      ,SUM(NVL(PRODUTO.VLBCFCPSTRET, 0)) AS VLBCFCPSTRET
      ,SUM(NVL(PRODUTO.VLFCPSTRET, 0)) AS VLFCPSTRET
      ,SUM(NVL(PRODUTO.VLCREDFCPICMSSN, 0)) AS VLCREDFCPICMSSN
      ,SUM(NVL(PRODUTO.VLFECP, 0)) AS VLFECP
      ,SUM(NVL(PRODUTO.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP  
      ,0 AS VALOR_IPI_DEVOLVIDO  
      ,SUM(NVL(PRODUTO.QBCMONO, 0)) AS QBCMONO
      ,SUM(NVL(PRODUTO.VICMSMONO, 0)) AS VICMSMONO
      ,SUM(NVL(PRODUTO.QBCMONORETEN, 0)) AS QBCMONORETEN
      ,SUM(NVL(PRODUTO.VICMSMONORETEN, 0)) AS VICMSMONORETEN
      ,SUM(NVL(PRODUTO.QBCMONODIF, 0)) AS QBCMONODIF
      ,SUM(NVL(PRODUTO.VICMSMONODIF, 0)) AS VICMSMONODIF
      ,SUM(NVL(PRODUTO.QBCMONORET, 0)) AS QBCMONORET
      ,SUM(NVL(PRODUTO.VICMSMONORET, 0)) AS VICMSMONORET      
      ,PRODUTO.GERAGRPRETTRIB
      ,SUM(NVL(PRODUTO.VLPISRETORGPUB, 0)) AS VLPISRETORGPUB
      ,SUM(NVL(PRODUTO.VLCOFINSRETORGPUB, 0)) AS VLCOFINSRETORGPUB
      ,SUM(NVL(PRODUTO.VLCSLLRETORGPUB, 0)) AS VLCSLLRETORGPUB
      ,SUM(NVL(PRODUTO.VLIRPJRETORGPUB, 0)) AS VLIRPJRETORGPUB
      ,SUM(NVL(PRODUTO.VLBCIRRFRETORGPUB, 0)) AS VLBCIRRFRETORGPUB         
      ,SUM(PRODUTO.VLICMSDESONERACAO) AS VALOR_TOTAL_DESONERADO
FROM   PCNFENT,
       PCPRODCIAP,
       PCVEICUL,
       PCFORNEC FRETEIRO,
       PCCONSUM,
       PCEMPR,
       TABLE(NFE_PRODUTO_ENTRADA(PCNFENT.NUMTRANSENT)) PRODUTO
WHERE  PCNFENT.NUMTRANSENT = PCNFENT.NUMTRANSENT
AND    PCNFENT.CODCONT <> NVL(PCCONSUM.CODCONTFRE,0)
AND    PCNFENT.CODCONT <> NVL(PCCONSUM.CODCONTOUT,0)
AND    PCPRODCIAP.CODPROD = PRODUTO.CODPROD
AND    PCNFENT.CODFORNECFRETE = FRETEIRO.CODFORNEC(+)
AND    PCNFENT.CODMOTORISTADEVOL = PCEMPR.MATRICULA(+)
AND    PCNFENT.CODENTVEICULO = PCVEICUL.CODVEICULO(+)
AND    PCNFENT.ESPECIE IN('NF','NE','EI')
AND    PCNFENT.TIPODESCARGA NOT IN ('6', '8', 'C', 'N', 'F')
AND    NVL(PCNFENT.FINALIDADENFE, 'X') =  'P'
GROUP  BY PCNFENT.NUMTRANSENT,
          PCNFENT.VLST,
          PCNFENT.VLTOTAL,
          PCNFENT.BASEICST,
          PCNFENT.VLFRETE,
          PCNFENT.VLOUTRAS,
          PCNFENT.VLST,
          PCNFENT.VLIPI,
          PRODUTO.GERAGRPRETTRIB,
          PCNFENT.TOTPESO,
          PCNFENT.TOTPESOLIQ,
          PCNFENT.ESPECIEVOLUME,
          NVL(PCNFENT.PLACAVEICULO, PCVEICUL.PLACA),
          PCVEICUL.ANTT,
          NVL(PCNFENT.UFVEICULO, PCVEICUL.UFPLACAVEICULO),
          FRETEIRO.CGC,
          FRETEIRO.FORNECEDOR,
          FRETEIRO.IE,
          (FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO),
          FRETEIRO.CIDADE,
          FRETEIRO.ESTADO,
          PCNFENT.DTENT,
          PCNFENT.CODMOTORISTADEVOL,
          PCNFENT.TIPOFRETECIFFOB,
          PCEMPR.NOME,
          PCNFENT.NUMVOL,
          PCNFENT.NUMVOLUME,
          PCNFENT.MARCAVOLUME,
          PCNFENT.TIPODESCARGA,
          PCNFENT.MOTESTORNONFE,
          PCNFENT.FINALIDADENFE
-----------------------------------------
UNION ALL
-----------------------------------------
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO
      ,NVL(SUM(PRODUTO.BASE_ICMS),
           0) AS BASE_ICMS
      ,NVL(SUM(PRODUTO.VALOR_ICMS),
           0) AS VALOR_ICMS
      ,NVL(SUM(PRODUTO.BASE_ST),
           0) AS BASE_ICMS_ST
      ,NVL(SUM(PRODUTO.VALOR_ST),
           0) AS VALOR_ICMS_ST --VST
      ,NVL(SUM(PRODUTO.VALOR_PRODUTOS),
           0) AS VALOR_TOTAL_PRODUTOS --VPROD
      ,NVL(SUM(PRODUTO.VALOR_FRETE),
           0) AS VALOR_FRETE --VFRETE
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),
           0) AS VALOR_DESCONTO --VDESC
      ,NVL(SUM(PRODUTO.VALOR_IPI),
           0) AS VALOR_IPI --VLIPI
      ,NVL(SUM(PRODUTO.VALOR_OUTROS),
           0) AS VALOR_OUTRO --VOUTRO
      ,PCNFENT.VLTOTAL AS VALOR_TOTAL --VNF
      ,NVL(SUM(PRODUTO.VALOR_II),
           0) AS VALOR_II
      ,SUM(PRODUTO.VALOR_COFINS) AS VALOR_COFINS
      ,SUM(PRODUTO.VALOR_PIS) AS VALOR_PIS
      ,0 AS BASE_ISS --VBC
      ,0 VALOR_ISS
       ------------------- FRETE AS ENTRADAS TIPO 4 E R E DEVOLUÇÃO 6 E 8 NÃO TEM FRETE---------------------
      ,DECODE(NVL(PCNFENT.FINALIDADENFE, 'X'),'A',
                                              9,
                                              'C',
                                              9,
                                              '2',
                                              9,
                                              '3',
                                              9,
                DECODE(NVL(PCNFENT.TIPOFRETECIFFOB,
                                      'N'),
                                  'C',
                                  0,
                                  'F',
                                  1,
                                  'T',
                                  2,              
                                  'R',
                                  3,
                                  'D',
                                  4,
                                  'G',
                                  9,
                                  'N',
                                  9,
                                  'S',
                                  9))
       AS MODALIDADE_FRETE
      ,FRETEIRO.CGC AS CNPJ_TRANSPORTADOR
      ,FRETEIRO.FORNECEDOR AS TRANSPORTADOR
      ,FRETEIRO.IE AS IE_TRANSPORTADOR
      ,FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO AS END_TRANSPORTADOR
      ,FRETEIRO.CIDADE AS CIDADE_TRANSPORTADOR
      ,FRETEIRO.ESTADO AS ESTADO_TRANSPORTADOR
      ,DECODE(PCNFENT.FINALIDADENFE, 'A', PCNFENT.MOTESTORNONFE, NULL) AS INFORMACAOADICIONALFISCO
       ------------------ VEICULO --------------------
      ,NVL(PCNFENT.PLACAVEICULO, PCVEICUL.PLACA) AS PLACA
      ,PCVEICUL.ANTT
      ,NVL(PCNFENT.UFVEICULO, PCVEICUL.UFPLACAVEICULO) AS PLACA_UF
       ------------------ GRUPO DE VOLUMES -----------
      ,SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL) QT
      ,NVL(PCNFENT.TOTPESOLIQ,
           SUM(NVL(PRODUTO.QUANTIDADE_TRIBUTAVEL,
                   0) * DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PESOLIQIGUALAPESOBRUTONFE',
                                                                 NVL(PCNFENT.CODFILIALNF,
                                                                     PCNFENT.CODFILIAL)),
                                   'N'),
                               'N',
                               NVL(PCPRODUT.PESOLIQ,
                                   0),
                               NVL(PCPRODUT.PESOBRUTO,
                                   0)))) AS PESO_LIQUIDO
      ,NVL(MAX(PCNFENT.TOTPESO),
           SUM(NVL(PRODUTO.QUANTIDADE_TRIBUTAVEL,
                   0) * NVL(PCPRODUT.PESOBRUTO,
                            0))) AS PESO_BRUTO
      ,NVL(PCNFENT.NUMVOL, 0) AS NUM_VOLUME
      ,CASE WHEN (PCNFENT.TIPODESCARGA IN ('N','F')) THEN
              PCNFENT.MARCAVOLUME
          ELSE
              NULL
          END AS MARCAVOLUME
      ,PCNFENT.ESPECIEVOLUME
      ,TO_CHAR(NVL(NVL(TO_CHAR(PCNFENT.NUMVOL), TRIM(REPLACE(REPLACE(REPLACE(REPLACE(PCNFENT.NUMVOLUME, '.', ''), ',', ''), '/', ''), '-', ''))),DECODE(SUM(PRODUTO.QUANTIDADE_TRIBUTAVEL), 0, 1))) NUMVOL
      ,0 VOLUME_PEDIDO
      ,CASE WHEN (PCNFENT.TIPODESCARGA IN ('N','F')) THEN
         PCNFENT.NUMVOLUME
       ELSE
         NULL
       END AS NVOL --CONTAINER,
      ,SUM(PRODUTO.NUMVOLUMESCONFERENCIA) AS NUMVOLUMESCONFERENCIA
      ,PCNFENT.DTENT DTENTREGA
      ,0 AS NUMCAR
      ,PCNFENT.CODMOTORISTADEVOL AS CODMOTORISTA
      ,PCEMPR.NOME AS NOME_MOTORISTA
      ,0 AS VLDESCRODAPE
      ,0 AS NUM_VOLUME_EMB
      ,NULL AS DESC_PL_PGTO
      ,PCNFENT.FINALIDADENFE
      ,SUM(NVL(PRODUTO.VLFCPPART, 0)) AS VLFCPPART
      ,SUM(NVL(PRODUTO.VLICMSPARTDEST, 0)) AS VLICMSPARTDEST
      ,SUM(NVL(PRODUTO.VLICMSPARTREM, 0)) AS VLICMSPARTREM
      ,SUM(NVL(PRODUTO.VLBASEFCPICMS, 0)) AS VLBASEFCPICMS
      ,SUM(NVL(PRODUTO.VLBASEFCPST, 0)) AS VLBASEFCPST
      ,SUM(NVL(PRODUTO.VLBCFCPSTRET, 0)) AS VLBCFCPSTRET
      ,SUM(NVL(PRODUTO.VLFCPSTRET, 0)) AS VLFCPSTRET
      ,SUM(NVL(PRODUTO.VLCREDFCPICMSSN, 0)) AS VLCREDFCPICMSSN
      ,SUM(NVL(PRODUTO.VLFECP, 0)) AS VLFECP
      ,SUM(NVL(PRODUTO.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP  
      ,0 AS VALOR_IPI_DEVOLVIDO  
      ,SUM(NVL(PRODUTO.QBCMONO, 0)) AS QBCMONO
      ,SUM(NVL(PRODUTO.VICMSMONO, 0)) AS VICMSMONO
      ,SUM(NVL(PRODUTO.QBCMONORETEN, 0)) AS QBCMONORETEN
      ,SUM(NVL(PRODUTO.VICMSMONORETEN, 0)) AS VICMSMONORETEN
      ,SUM(NVL(PRODUTO.QBCMONODIF, 0)) AS QBCMONODIF
      ,SUM(NVL(PRODUTO.VICMSMONODIF, 0)) AS VICMSMONODIF
      ,SUM(NVL(PRODUTO.QBCMONORET, 0)) AS QBCMONORET
      ,SUM(NVL(PRODUTO.VICMSMONORET, 0)) AS VICMSMONORET      
      ,PRODUTO.GERAGRPRETTRIB
      ,SUM(NVL(PRODUTO.VLPISRETORGPUB, 0)) AS VLPISRETORGPUB
      ,SUM(NVL(PRODUTO.VLCOFINSRETORGPUB, 0)) AS VLCOFINSRETORGPUB
      ,SUM(NVL(PRODUTO.VLCSLLRETORGPUB, 0)) AS VLCSLLRETORGPUB
      ,SUM(NVL(PRODUTO.VLIRPJRETORGPUB, 0)) AS VLIRPJRETORGPUB
      ,SUM(NVL(PRODUTO.VLBCIRRFRETORGPUB, 0)) AS VLBCIRRFRETORGPUB        
      ,SUM(PRODUTO.VLICMSDESONERACAO) AS VALOR_TOTAL_DESONERADO
FROM   PCNFENT,
       PCPRODUT,
       PCVEICUL,
       PCFORNEC FRETEIRO,
       PCCONSUM,
       PCEMPR,
       TABLE(NFE_PRODUTO_ENTRADA(PCNFENT.NUMTRANSENT)) PRODUTO
WHERE  PCNFENT.ESPECIE IN ('NE', 'NF', 'EI')
AND    PRODUTO.CODPROD = PCPRODUT.CODPROD
AND    PCNFENT.CODFORNECFRETE = FRETEIRO.CODFORNEC(+)
AND    PCNFENT.CODMOTORISTADEVOL = PCEMPR.MATRICULA(+)
AND    PCNFENT.CODENTVEICULO = PCVEICUL.CODVEICULO(+)
AND    PCNFENT.TIPODESCARGA IN ('6', '8', 'C', 'N', 'F', 'T')
AND    NVL(PCNFENT.FINALIDADENFE, 'X') <> 'P'
GROUP  BY PCNFENT.NUMTRANSENT,
          PCNFENT.VLST,
          PCNFENT.VLTOTAL,
          PCNFENT.BASEICST,
          PCNFENT.VLFRETE,
          PCNFENT.VLOUTRAS,
          PCNFENT.VLST,
          PCNFENT.VLIPI,
          PRODUTO.GERAGRPRETTRIB,
          PCNFENT.TOTPESO,
          PCNFENT.TOTPESOLIQ,
          PCNFENT.ESPECIEVOLUME,
          NVL(PCNFENT.PLACAVEICULO, PCVEICUL.PLACA),
          PCVEICUL.ANTT,
          NVL(PCNFENT.UFVEICULO, PCVEICUL.UFPLACAVEICULO),
          PCNFENT.CODFILIALNF,
          PCNFENT.CODFILIAL,
          FRETEIRO.CGC,
          FRETEIRO.FORNECEDOR,
          FRETEIRO.IE,
          (FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO),
          FRETEIRO.CIDADE,
          FRETEIRO.ESTADO,
          PCNFENT.DTENT,
          PCNFENT.CODMOTORISTADEVOL,
          PCNFENT.TIPOFRETECIFFOB,
          PCEMPR.NOME,
          PCNFENT.NUMVOL,
          PCNFENT.NUMVOLUME,
          PCNFENT.MARCAVOLUME,
          PCNFENT.TIPODESCARGA,
          PCNFENT.MOTESTORNONFE,
          PCNFENT.FINALIDADENFE