CREATE OR REPLACE PACKAGE PKG_SINC_PDV_CONSINCO_INUT IS
  PROCEDURE PROCESSAR_INUTILIZACAO_NOTA(P_SEQDOCTO NUMBER DEFAULT 0,
                                        P_NROCHECKOUT NUMBER DEFAULT 0,
                                        P_NROEMPRESA NUMBER DEFAULT 0) ;

END PKG_SINC_PDV_CONSINCO_INUT;