CREATE OR REPLACE FUNCTION CONFIGURACOES_EMAIL(P_CODIGO_FILIAL VARCHAR2)
  RETURN TABELA_CONFIG_EMAIL IS

  RETORNO TABELA_CONFIG_EMAIL;

  CONFIG_USUARIO        VARCHAR2(100);
  CONFIG_SENHA          VARCHAR2(100);
  CONFIG_DOMINIO        VARCHAR2(100);
  CONFIG_NOME_REMENTE   VARCHAR2(100);
  CONFIG_EMAIL_REMENTE  VARCHAR2(100);
  CONFIG_SERVIDOR_SMTP  VARCHAR2(100);
  CONFIG_PORTA          VARCHAR2(5);
  CONFIG_ATIVAR_SSL     VARCHAR2(1);
  CONFIG_ATIVAR_TLS     VARCHAR2(1);
  CONFIG_EMAIL_RESPOSTA VARCHAR2(100);
  CONFIG_EMAIL_COPIA    VARCHAR2(100);
  RESULTADO             NUMBER;
BEGIN
  RESULTADO := 0;
  BEGIN
    SELECT PARAMFILIAL.OBTERCOMOVARCHAR2('USUARIOEMAIL', P_CODIGO_FILIAL),
           PARAMFILIAL.OBTERCOMOVARCHAR2('SENHAEMAIL', P_CODIGO_FILIAL),
           PARAMFILIAL.OBTERCOMOVARCHAR2('DOMINIOEMAIL', P_CODIGO_FILIAL),
           PARAMFILIAL.OBTERCOMOVARCHAR2('NOMEREMETENTE', P_CODIGO_FILIAL),
           PARAMFILIAL.OBTERCOMOVARCHAR2('EMAILREMETENTE', P_CODIGO_FILIAL),
           PARAMFILIAL.OBTERCOMOVARCHAR2('ENDERECOSMTP', P_CODIGO_FILIAL),
           NVL(PARAMFILIAL.OBTERCOMONUMBER('PORTASMTP', P_CODIGO_FILIAL), 0),
           NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ATIVARSSL', P_CODIGO_FILIAL),'N'),
           DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ATIVARTLS', P_CODIGO_FILIAL),'N'),
           'N',
           'N',
           'S'
           ),
           PARAMFILIAL.OBTERCOMOVARCHAR2('EMAILRESPOSTA', P_CODIGO_FILIAL),
           PARAMFILIAL.OBTERCOMOVARCHAR2('EMAILCOPIA', P_CODIGO_FILIAL)
      INTO CONFIG_USUARIO,
           CONFIG_SENHA,
           CONFIG_DOMINIO,
           CONFIG_NOME_REMENTE,
           CONFIG_EMAIL_REMENTE,
           CONFIG_SERVIDOR_SMTP,
           CONFIG_PORTA,
           CONFIG_ATIVAR_SSL,
           CONFIG_ATIVAR_TLS,
           CONFIG_EMAIL_RESPOSTA,
           CONFIG_EMAIL_COPIA           
      FROM DUAL;
  EXCEPTION
    WHEN OTHERS THEN
      RESULTADO := 1;
  END;

  RETORNO := TABELA_CONFIG_EMAIL();
  IF RESULTADO = 0 THEN
    RETORNO.EXTEND;

    RETORNO(RETORNO.COUNT) := TIPO_CONFIG_EMAIL(USUARIO        => NULL,
                                                SENHA          => NULL,
                                                DOMINIO        => NULL,
                                                NOME_REMENTE   => NULL,
                                                EMAIL_REMENTE  => NULL,
                                                SERVIDOR_SMTP  => NULL,
                                                PORTA          => NULL,
                                                ATIVAR_SSL     => NULL,
                                                EMAIL_RESPOSTA => NULL,
                                                EMAIL_COPIA    => NULL,
                                                ATIVAR_TLS     => NULL
                                                );

    RETORNO(RETORNO.COUNT).USUARIO := CONFIG_USUARIO;
    RETORNO(RETORNO.COUNT).SENHA := CONFIG_SENHA;
    RETORNO(RETORNO.COUNT).DOMINIO := CONFIG_DOMINIO;
    RETORNO(RETORNO.COUNT).NOME_REMENTE := CONFIG_NOME_REMENTE;
    RETORNO(RETORNO.COUNT).EMAIL_REMENTE := CONFIG_EMAIL_REMENTE;
    RETORNO(RETORNO.COUNT).SERVIDOR_SMTP := CONFIG_SERVIDOR_SMTP;
    RETORNO(RETORNO.COUNT).PORTA := TO_NUMBER(CONFIG_PORTA);
    RETORNO(RETORNO.COUNT).ATIVAR_SSL := CONFIG_ATIVAR_SSL;
    RETORNO(RETORNO.COUNT).EMAIL_RESPOSTA := CONFIG_EMAIL_RESPOSTA;
    RETORNO(RETORNO.COUNT).EMAIL_COPIA := CONFIG_EMAIL_COPIA;
    RETORNO(RETORNO.COUNT).ATIVAR_TLS := CONFIG_ATIVAR_TLS;

  END IF;

  RETURN RETORNO;
EXCEPTION
  WHEN OTHERS THEN
    raise_application_error(-20001, 'Erro motivo: ' || SQLERRM || '. Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END; 