CREATE OR REPLACE VIEW VW_INT_C5_REGRAINCENTIVO AS
(
/*Rotina 357 - PRECO FIXO*/
SELECT
  SEQREGRA,
  NROEMPRESA,
  REGRA,
  SEQTIPOCREDITO,
  ATIVO,
  TIPOREGRA,
  CUMULATIVO,
  TO_DATE(DTAHORINICIO || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORINICIO,
  TO_DATE(DTAHORFIM || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORFIM,
  --'357' AS IDREF
  IDREF
FROM VW_INT_C5_PRECOFIXO_R357

UNION ALL

 /*Rotina 561 - PRODUTO*/
SELECT
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO,
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     TO_DATE(DTAHORINICIO || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORINICIO,
     TO_DATE(DTAHORFIM || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORFIM,
     --'561' AS IDREF
     IDREF
FROM VW_INT_C5_DESC561FAMILIA

UNION ALL

/*Rotina 561 - CLIENTE*/
SELECT
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO,
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     TO_DATE(DTAHORINICIO || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORINICIO,
     TO_DATE(DTAHORFIM || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORFIM,
     --'561' AS IDREF
     IDREF
FROM VW_INT_C5_DESC561CLIENTE
UNION ALL

/*Rotina 561 - CATEGORIA*/

SELECT
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO,
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     TO_DATE(DTAHORINICIO || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORINICIO,
     TO_DATE(DTAHORFIM || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORFIM,
     --'561' AS IDREF
     IDREF
FROM VW_INT_C5_DESC561CATEGORIA
)