CREATE OR REPLACE VIEW VW_INT_C5_INCENTIVO AS 
( /*Rotina 357*/
SELECT 
  SEQREGRA,
  REGRA, 
  SEQTIPOCREDITO, 
  ATIVO, 
  TIPOREGRA,
  CUMULATIVO,
  DTAHORINICIO, 
  DTAHORFIM 
FROM VW_INT_C5_PRECOFIXO_R357 
UNION ALL
 /*Rotina 561 - produto*/
SELECT 
     SEQREGRA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM
FROM VW_INT_C5_DESC561FAMILIA
UNION ALL
/*Rotina 561 - cliente*/
SELECT 
     SEQREGRA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM
FROM VW_INT_C5_DESC561CLIENTE
UNION ALL
/*Rotina 561 - categoria*/
SELECT 
     SEQREGRA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM
FROM VW_INT_C5_DESC561CATEGORIA
)