CREATE OR REPLACE VIEW VW_INT_C5_REGRAINCENTIVO AS
( 
/*Rotina 357 - PRECO FIXO*/
SELECT 
  SEQREGRA,
  NROEMPRESA,
  REGRA, 
  SEQTIPOCREDITO, 
  ATIVO, 
  TIPOREGRA,
  CUMULATIVO,
  DTAHORINICIO, 
  DTAHORFIM,
  '357' AS IDREF
FROM VW_INT_C5_PRECOFIXO_R357 

UNION ALL

 /*Rotina 561 - PRODUTO*/
SELECT 
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM,
     '561' AS IDREF
FROM VW_INT_C5_DESC561FAMILIA

UNION ALL

/*Rotina 561 - CLIENTE*/
SELECT 
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM,
     '561' AS IDREF
FROM VW_INT_C5_DESC561CLIENTE
UNION ALL

/*Rotina 561 - CATEGORIA*/

SELECT 
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM,
     '561' AS IDREF
FROM VW_INT_C5_DESC561CATEGORIA

UNION ALL

/*Rotina 2011 - OFERTA PROGRAMADA*/
SELECT
     SEQREGRA,
     NROEMPRESA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTAHORINICIO,
     DTAHORFIM,
     '2011' AS IDREF
FROM VW_INT_C5_OFERTA_R2011
)