CREATE OR REPLACE VIEW SQL_NFE_REF_ENTRADA_DEV AS
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO,
       UF_E.UF AS SIGLA_UF,
       REPLACE(REPLACE(REPLACE(EMITENTE.CGC,'.',''),'/',''),'-','') AS CNPJ_E,
       PCNFENT.DTEMISSAONFVENDA AS DATA_EMISSAO,
       '01' AS MODELO,
       DECODE(NVL(PCNFENT.SERIENFVENDA,
                  'U'),
              'U',
              '0',
              PCNFENT.SERIENFVENDA) AS SERIE,
       NVL(PCNFENT.NUMNOTAVENDA,
           0) AS NUMERO_NOTA
FROM   PCNFENT,
       PCFORNEC EMITENTE,
       PCESTADO UF_E,
       PCCIDADE CIDADE_E,
       PCFILIAL
WHERE  NVL(PCNFENT.CODFILIALNF,
           PCNFENT.CODFILIAL) = PCFILIAL.CODIGO
AND    PCFILIAL.CODFORNEC = EMITENTE.CODFORNEC
AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE
AND    PCNFENT.SERIE <> 'CF'
AND    PCNFENT.ESPECIE IN ('NE','NF')
AND    CIDADE_E.UF = UF_E.UF 