CREATE OR REPLACE FUNCTION CTE_INFO_SUBSTITUTO(P_TRANSACAO NUMBER)
  RETURN TABELA_CTE_INFO_SUBSTITUTO IS

  CURSOR CR_INFO_SUBSTITUTO IS
   
    SELECT (SELECT ORIG.CHAVECTE FROM PCNFSAID ORIG WHERE ORIG.NUMTRANSCTESUBS = N.NUMTRANSVENDA) AS CHAVE_CTE_ORIGINAL,
           N.CNPJCPFEMITENTESUB AS CNPJ_CPF_EMITENTE,
           N.MODELODOCSUB AS MODELO_DOC,
           N.SERIEDOCSUB  AS SERIE_DOC,
           N.SUBSERIEDOCSUB AS SUBSERIE_DOC,
           N.NUMERODOCSUB AS NUMERO_DOC,
           N.VALORDOCSUB AS VALOR_DOC,                          
           N.DTEMISSAODOCSUB AS DT_EMISSAO_DOC,
           NVL(N.CHAVENFETOMADORSUB,
               NVL((SELECT CHAVENFE FROM PCNFSAID WHERE NUMTRANSVENDA = N.NUMTRANSCTEANUL) ,
                   (SELECT CHAVENFE FROM PCNFENT WHERE NUMTRANSENT = N.NUMTRANSCTEANUL))) AS CHAVE_NFE_TOMADOR,
           (SELECT ANU.CHAVECTE FROM PCNFSAID ORIG, PCNFENT ANU  WHERE ORIG.NUMTRANSCTESUBS = N.NUMTRANSVENDA  AND ANU.NUMTRANSENT = ORIG.NUMTRANSCTEANUL) AS CHAVE_CTE_ANULACAO
      FROM PCNFSAID N, 
           PCFORNEC,
           PCFILIAL
     WHERE NVL(N.CODFILIALNF, N.CODFILIAL) = PCFILIAL.CODIGO
       AND PCFILIAL.CODFORNEC = PCFORNEC.CODFORNEC
       AND N.NUMTRANSVENDA = P_TRANSACAO;

  RETORNO TABELA_CTE_INFO_SUBSTITUTO; 
BEGIN
  RETORNO := TABELA_CTE_INFO_SUBSTITUTO();

  FOR ITEM IN CR_INFO_SUBSTITUTO LOOP
    RETORNO.EXTEND;
    RETORNO(RETORNO.COUNT) := TIPO_CTE_INFO_SUBSTITUTO(CHAVE_CTE_ORIGINAL         => NULL,
                                                       CNPJ_CPF_EMITENTE          => NULL,
                                                       MODELO_DOC                 => NULL,
                                                       SERIE_DOC                  => NULL,
                                                       SUBSERIE_DOC               => NULL,
                                                       NUMERO_DOC                 => NULL,
                                                       VALOR_DOC                  => NULL,
                                                       DT_EMISSAO_DOC             => NULL,
                                                       CHAVE_NFE_TOMADOR          => NULL,
                                                       CHAVE_CTE_ANULACAO         => NULL);

     RETORNO(RETORNO.COUNT).CHAVE_CTE_ORIGINAL          := ITEM.CHAVE_CTE_ORIGINAL;
     RETORNO(RETORNO.COUNT).CNPJ_CPF_EMITENTE           := ITEM.CNPJ_CPF_EMITENTE;
     RETORNO(RETORNO.COUNT).MODELO_DOC                  := ITEM.MODELO_DOC;
     RETORNO(RETORNO.COUNT).SERIE_DOC                   := ITEM.SERIE_DOC;
     RETORNO(RETORNO.COUNT).SUBSERIE_DOC                := ITEM.SUBSERIE_DOC;
     RETORNO(RETORNO.COUNT).NUMERO_DOC                  := ITEM.NUMERO_DOC;
     RETORNO(RETORNO.COUNT).VALOR_DOC                   := ITEM.VALOR_DOC;
     RETORNO(RETORNO.COUNT).DT_EMISSAO_DOC              := ITEM.DT_EMISSAO_DOC;
     RETORNO(RETORNO.COUNT).CHAVE_NFE_TOMADOR           := ITEM.CHAVE_NFE_TOMADOR;
     RETORNO(RETORNO.COUNT).CHAVE_CTE_ANULACAO          := ITEM.CHAVE_CTE_ANULACAO;
  
  END LOOP;

  RETURN RETORNO;

EXCEPTION
  WHEN OTHERS THEN  
    raise_application_error(-20001, 'Erro motivo: ' || SQLERRM || '. Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;