CREATE OR REPLACE PACKAGE BODY PKG_MONITOR_TRIBUTARIO_CONSULT AS

  FUNCTION GET_CREATE_TABELA_TELEMETRIA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCTELEMETRIAMONITOR (
              DATAPROCESSAMENTO DATE,
              OBJETO VARCHAR(30),
              DATAHORAINICIO DATE,
              DATAHORATERMINO DATE,
              DADOS VARCHAR2(4000)
            )';
  END GET_CREATE_TABELA_TELEMETRIA;

  
  FUNCTION GET_INDICES_TELEMETRIA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DATAPROCESSAMENTO';
  END GET_INDICES_TELEMETRIA;
  
  
  FUNCTION GET_CREATE_TABELA_CONTROLEPROC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCCONTROLEPROCESSAMENTO (  
              DTCADASTRO DATE DEFAULT TRUNC(SYSDATE), 
              OBJETO VARCHAR2(30) NOT NULL ENABLE, 
              ATIVO VARCHAR2(1) DEFAULT ''N'', 
              MULTIPLASEXECUCOES VARCHAR(1) DEFAULT ''S'',
              DTULTPROCESSAMENTO DATE,
              DTPREPARACAOAMBIENTE DATE
            )';
  END GET_CREATE_TABELA_CONTROLEPROC;

  
  FUNCTION GET_INDICES_CONTROLEPROC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'OBJETO';
  END GET_INDICES_CONTROLEPROC;


  FUNCTION GET_DATA_INICIAL(P_DATA IN DATE) RETURN DATE IS
  BEGIN
    RETURN NVL(P_DATA, SYSDATE - 90);
  END GET_DATA_INICIAL;


  FUNCTION GET_DATA_FINAL(PDATA IN DATE) RETURN DATE IS
  BEGIN
    RETURN NVL(PDATA, SYSDATE);
  END GET_DATA_FINAL;


  FUNCTION GET_FILTRO_DATA_FORMATADA(PCAMPO IN VARCHAR2, PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
    v_filtro VARCHAR(200);
  BEGIN
    v_filtro := PCAMPO || ' BETWEEN TO_DATE(''@DTINICIAL'', ''DD/MM/YYYY HH24:MI:SS'')'
                       || ' AND TO_DATE(''@DTFINAL'', ''DD/MM/YYYY HH24:MI:SS'') ';

    v_filtro := REPLACE(v_filtro, '@DTINICIAL', TO_CHAR(GET_DATA_INICIAL(PDATA_INICIAL), 'DD/MM/YYYY') || ' 00:00:00');
    v_filtro := REPLACE(v_filtro, '@DTFINAL', TO_CHAR(GET_DATA_FINAL(PDATA_FINAL), 'DD/MM/YYYY') || ' 23:59:59');

    RETURN v_filtro;
  END GET_FILTRO_DATA_FORMATADA;
  
  
  FUNCTION GET_VALORES_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.* FROM ' || PTABELA || ' T';
  END GET_VALORES_TABELA_MONITOR;


  FUNCTION GET_VALORES_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.DTSAIDA,
              T.CODFISCAL,
              T.NUMTRANSVENDA,
              D.NUMTRANSVENDA PCDEVFORNEC_NUMTRANSVENDA,
              T.SERIE,
              T.CONDVENDA,
              T.VLTOTGER,
              T.VLCUSTOFIN,
              T.CODFILIAL,
              T.TIPOVENDA,
              T.DTCANCEL,
              T.CODFILIALNF,
              T.CONTRIBUINTE,
              T.CONSUMIDORFINAL,
              T.ESPECIE
            FROM PCNFSAID T, PCDEVFORNEC D
            WHERE T.NUMTRANSVENDA = D.NUMTRANSVENDA(+)
              AND ' || GET_FILTRO_DATA_FORMATADA('DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFSAID;

  FUNCTION GET_INDICES_PCNFSAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIAL';
  END GET_INDICES_PCNFSAID;


  FUNCTION GET_VALORES_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.NUMTRANSVENDA,
              T.NUMNOTA,
              T.CODFILIALNF,
              T.CODFILIAL,
              T.NUMTRANSITEM,
              T.CODPROD,
              T.STATUS,
              T.DTMOV,
              T.CODOPER,
              T.CODFISCAL,
              T.PERCICM,
              T.GERAICMSLIVROFISCAL,
              T.SITTRIBUT,
              T.IMPORTADO,
              T.ST,
              T.QTCONT,
              T.BASEICMS,
              T.PUNITCONT,
              T.VLIPI,
              T.VLOUTROS,
              T.VLACRESCIMOPF,
              T.VLFRETE,
              T.BASEICST,
              T.VLBASEIPI,
              T.PERCIPI,
              T.VLSUFRAMA,
              T.VLPIS,
              T.VLCOFINS,
              T.BASEACRESCIMOPF,
              T.VLREPASSE,
              T.BASEBCR,
              T.STBCR,
              T.VLICMSBCR,
              T.VLDESCREDUCAOPIS,
              T.VLDESCONTO,
              T.VLDESCICMISENCAO
            FROM PCMOV T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTMOV', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCMOV;

  FUNCTION GET_INDICES_PCMOV RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSITEM;DTMOV;CODFILIAL';
  END GET_INDICES_PCMOV;


  FUNCTION GET_VALORES_MOV_UNIFICADA(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.NUMTRANSITEM,
              T.DTREGISTRO,
              T.PERDIFEREIMENTOICMS,
              T.ORIGMERCTRIB,
              T.VLBASEFRETE,
              T.VLBASEOUTROS,
              T.VLFECP,
              T.CODSITTRIBIPI,
              T.QTLITRAGEM,
              T.USAPISCOFINSLIT,
              T.VLICMSPARTDEST,
              T.VLICMSPARTREM,
              T.VLFCPPART,
              T.VLICMSDIFALIQPART,
              T.VLBASEPARTDEST,
              T.VLIPIDEVFORNEC,
              T.VLBASEFCPICMS,
              T.VLACRESCIMOFUNCEP,
              T.VLBASEFCPST,
              T.PERACRESCIMOFUNCEP,
              T.ALIQICMSFECP,
              T.PRECOUTILIZADONFE,
              T.VLICMSDESONERACAO,
              M.NUMTRANSVENDA,
              M.NUMNOTA,
              M.CODFILIALNF,
              M.CODFILIAL,
              M.CODPROD,
              M.STATUS,
              M.DTMOV,
              M.CODOPER,
              M.CODFISCAL,
              M.PERCICM,
              M.GERAICMSLIVROFISCAL,
              M.SITTRIBUT,
              M.IMPORTADO,
              M.ST,
              M.QTCONT,
              M.BASEICMS,
              M.PUNITCONT,
              M.VLIPI,
              M.VLOUTROS,
              M.VLACRESCIMOPF,
              M.VLFRETE,
              M.BASEICST,
              M.VLBASEIPI,
              M.PERCIPI,
              M.VLSUFRAMA,
              M.VLPIS,
              M.VLCOFINS,
              M.BASEACRESCIMOPF,
              M.VLREPASSE,
              M.BASEBCR,
              M.STBCR,
              M.VLICMSBCR,
              M.VLDESCREDUCAOPIS,
              M.VLDESCONTO,
              M.VLDESCICMISENCAO
            FROM PCMOVCOMPLE T, PCTMPMONMOV M
            WHERE T.NUMTRANSITEM = M.NUMTRANSITEM
            AND ' || GET_FILTRO_DATA_FORMATADA('M.DTMOV', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_MOV_UNIFICADA;

  FUNCTION GET_INDICES_MOV_UNIFICADA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTMOV;NUMTRANSITEM';
  END GET_INDICES_MOV_UNIFICADA;


  FUNCTION GET_VALORES_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFISCAL,
              T.NUMTRANSVENDA,
              T.DTSAIDA,
              T.VLDESDOBRADO,
              T.VLBASE,
              T.VLICMS,
              T.VLISENTAS,
              T.VLOUTRAS,
              T.VLST,
              T.VLIPI,
              T.VLACRESCIMOFUNCEP,
              T.VLFECP,
              T.ESPECIE,
              T.SERIE,
              T.CODFILIALNF,
              T.UF,
			  T.VLCOFINS,
              T.VLPIS,
			  T.VLTOTAL
            FROM PCNFBASESAID T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFBASESAID;

  FUNCTION GET_INDICES_PCNFBASESAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIALNF;NUMTRANSVENDA';
  END GET_INDICES_PCNFBASESAID;


  FUNCTION GET_VALORES_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFISCAL,
              T.NUMTRANSENT,
              T.DTENTRADA,
              T.VLDESDOBRADO,
              T.VLBASE,
              T.VLICMS,
              T.VLISENTAS,
              T.VLOUTRAS,
              T.VLST,
              T.VLIPI,
              T.VLACRESCIMOFUNCEP,
              T.VLFECP,
              T.ESPECIE,
              T.SERIE,
              T.CODFILIALNF,
              T.UF,
              T.TIPODESCARGA,
			  T.VLCOFINS,
              T.VLPIS,
			  T.VLTOTAL
            FROM PCNFBASEENT T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTENTRADA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFBASEENT;

  FUNCTION GET_INDICES_PCNFBASEENT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENTRADA;CODFILIALNF;NUMTRANSENT';
  END GET_INDICES_PCNFBASEENT;


  FUNCTION GET_VALORES_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFILIALNF,
              T.CODFILIAL,
              T.DTENT,
              T.NUMNOTA,
              T.NUMTRANSENT,
              D.NUMTRANSENT PCDEVFORNEC_NUMTRANSENT,
              T.CODEXPORTADOR,
              T.CODFORNECNF,
              T.CODFORNEC,
              T.TIPODESCARGA,
              T.NOTADUPLIQUESVC,
              T.SITUACAONFE,
              T.CHAVENFE,
              T.GERANFVENDA,
              T.ESPECIE,
              T.DTEMISSAO,
              T.SERIE,
              T.FORNECEDOR,
              T.CGC,
              T.IE,
              T.UF,
              T.VLTOTAL,
              T.VLFRETE,
              T.VLOUTRAS,
              T.PERBASEREDOUTRASDESP,
              T.OBSLIVROFISCAL,
              T.OBS,
              T.NFENTREGAFUTURA,
              T.EMISSAOPROPRIA,
              T.IMPORTADOXML,
              T.DTCANCEL
            FROM PCNFENT T, PCDEVFORNEC D
            WHERE T.NUMTRANSENT = D.NUMTRANSENT (+)
              AND ' || GET_FILTRO_DATA_FORMATADA('DTENT', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFENT;

  FUNCTION GET_INDICES_PCNFENT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENT;CODFILIAL';
  END GET_INDICES_PCNFENT;


  FUNCTION GET_VALORES_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCESTCOM T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTESTORNO', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCESTCOM;

  FUNCTION GET_INDICES_PCESTCOM RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENT;CODFILIAL';
  END GET_INDICES_PCESTCOM;


  FUNCTION GET_VALORES_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCDEVFORNEC T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTDEVOL', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCDEVFORNEC;


  FUNCTION GET_VALORES_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCDEVAVULSO T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTEMISSAO', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCDEVAVULSO;

  FUNCTION GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT L.NUMTRANSOPERACAO
                  ,R.CODFATOGERADOR
                  ,R.CODFILIAL
                  ,L.DATAINTEGRACAO
              FROM PCLANCINTERMEDIARIA L
                  ,PCREGRACONTABIL     R
                  ,PCREGRAFILIAL       F
             WHERE ' || GET_FILTRO_DATA_FORMATADA('L.DATAINTEGRACAO', PDATA_INICIAL, PDATA_FINAL) ||'
               AND L.STATUS = ''I''
               AND R.CODFATOGERADOR in (1,2)
               AND R.CODREGRA = F.CODREGRA
               AND F.CODREGRA = L.CODREGRA
               AND F.CODFILIAL = L.CODFILIAL
               AND R.CODREGRA = L.CODREGRA
               AND R.CODPLANOCONTA = L.CODPLANOCONTA';
  END GET_VALORES_NOTAS_CONTABIL;


END PKG_MONITOR_TRIBUTARIO_CONSULT;
