CREATE OR REPLACE PACKAGE PKG_MONITOR_TRIBUTARIO_CONSULT AUTHID CURRENT_USER AS
  
  FUNCTION GET_CREATE_LISTA_TABELA_MONIT RETURN VARCHAR2;
  FUNCTION GET_CREATE_TABELA_TELEMETRIA RETURN VARCHAR2;
  FUNCTION GET_INDICES_TELEMETRIA RETURN VARCHAR2;
  
  FUNCTION GET_CREATE_TABELA_CONTROLEPROC RETURN VARCHAR2;
  FUNCTION GET_INDICES_CONTROLEPROC RETURN VARCHAR2;
  FUNCTION GET_CREATE_TABELA_LOG RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION GET_VALORES_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFSAID RETURN VARCHAR2;

  FUNCTION GET_VALORES_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCMOV RETURN VARCHAR2;

  FUNCTION GET_VALORES_NFENTSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_NFENTSAID RETURN VARCHAR2;

  FUNCTION GET_VALORES_MOV_UNIFICADA(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_MOV_UNIFICADA RETURN VARCHAR2;

  FUNCTION GET_VALORES_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFBASESAID RETURN VARCHAR2;

  FUNCTION GET_VALORES_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFBASEENT RETURN VARCHAR2;

  FUNCTION GET_VALORES_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFENT RETURN VARCHAR2;

  FUNCTION GET_VALORES_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCESTCOM RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCDEVFORNEC RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCDEVAVULSO RETURN VARCHAR2;

  FUNCTION GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_NOTAS_CONTABIL RETURN VARCHAR2;  
  
  FUNCTION GET_VALORES_PROD_TRIB_VINC RETURN VARCHAR2;
  FUNCTION GET_INDICES_PROD_TRIB_VINC RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_MOV_ROTINA_111(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN CLOB;
  FUNCTION GET_INDICES_MOV_ROTINA_111 RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_DEVOLUCAO_ROT_111(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN CLOB;
  FUNCTION GET_INDICES_DEVOLUCAO_ROT_111 RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_DEVAVULSA_ROT_111(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN CLOB;
  FUNCTION GET_INDICES_DEVAVULSA_ROT_111 RETURN VARCHAR2;
  
END PKG_MONITOR_TRIBUTARIO_CONSULT;
