CREATE OR REPLACE PACKAGE BODY PKG_MONITOR_TRIBUTARIO_CONSULT AS

  FUNCTION GET_CREATE_LISTA_TABELA_MONIT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCMONITORTRIBUTARIOLISTATABELA (
              TABELAORIGEM VARCHAR2(30) NOT NULL,
              TABELATEMPORARIA VARCHAR2(30) NOT NULL,
              TABELAMONITOR VARCHAR2(30) NOT NULL,
              TABELADEPENDENCIA VARCHAR2(30),
              INDICE VARCHAR2(4000)
            )';
  END GET_CREATE_LISTA_TABELA_MONIT;

  FUNCTION GET_CREATE_TABELA_TELEMETRIA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCTELEMETRIAMONITOR (
              DATAPROCESSAMENTO DATE,
              OBJETO VARCHAR(30),
              DATAHORAINICIO DATE,
              DATAHORATERMINO DATE,
              DADOS VARCHAR2(4000)
            )';
  END GET_CREATE_TABELA_TELEMETRIA;

  
  FUNCTION GET_INDICES_TELEMETRIA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DATAPROCESSAMENTO';
  END GET_INDICES_TELEMETRIA;
  
  
  FUNCTION GET_CREATE_TABELA_CONTROLEPROC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCCONTROLEPROCESSAMENTO (  
              DTCADASTRO DATE DEFAULT TRUNC(SYSDATE), 
              OBJETO VARCHAR2(30) NOT NULL ENABLE, 
              ATIVO VARCHAR2(1) DEFAULT ''N'', 
              MULTIPLASEXECUCOES VARCHAR(1) DEFAULT ''S'',
              DTULTPROCESSAMENTO DATE,
              DTPREPARACAOAMBIENTE DATE
            )';
  END GET_CREATE_TABELA_CONTROLEPROC;

  FUNCTION GET_CREATE_TABELA_LOG RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCMONITORTRIBLOG (
              DATALOG DATE,
              CODUSUR NUMBER(4),
              TEMPOPERMANENCIA NUMBER(6),
              ACAO VARCHAR2(500),
              STATUSTELA VARCHAR2(1)
            )';
  END GET_CREATE_TABELA_LOG;


  FUNCTION GET_INDICES_CONTROLEPROC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'OBJETO';
  END GET_INDICES_CONTROLEPROC;


  FUNCTION GET_DATA_INICIAL(P_DATA IN DATE) RETURN DATE IS
  BEGIN
    RETURN NVL(P_DATA, SYSDATE - 90);
  END GET_DATA_INICIAL;


  FUNCTION GET_DATA_FINAL(PDATA IN DATE) RETURN DATE IS
  BEGIN
    RETURN NVL(PDATA, SYSDATE);
  END GET_DATA_FINAL;


  FUNCTION GET_FILTRO_DATA_FORMATADA(PCAMPO IN VARCHAR2, PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
    v_filtro VARCHAR(200);
  BEGIN
    v_filtro := PCAMPO || ' BETWEEN TO_DATE(''@DTINICIAL'', ''DD/MM/YYYY HH24:MI:SS'')'
                       || ' AND TO_DATE(''@DTFINAL'', ''DD/MM/YYYY HH24:MI:SS'') ';

    v_filtro := REPLACE(v_filtro, '@DTINICIAL', TO_CHAR(GET_DATA_INICIAL(PDATA_INICIAL), 'DD/MM/YYYY') || ' 00:00:00');
    v_filtro := REPLACE(v_filtro, '@DTFINAL', TO_CHAR(GET_DATA_FINAL(PDATA_FINAL), 'DD/MM/YYYY') || ' 23:59:59');

    RETURN v_filtro;
  END GET_FILTRO_DATA_FORMATADA;
  
  
  FUNCTION GET_VALORES_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.* FROM ' || PTABELA || ' T';
  END GET_VALORES_TABELA_MONITOR;


  FUNCTION GET_VALORES_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.DTSAIDA,
              T.CODFISCAL,
              T.NUMTRANSVENDA,
              D.NUMTRANSVENDA PCDEVFORNEC_NUMTRANSVENDA,
              T.SERIE,
              T.CONDVENDA,
              T.VLTOTGER,
              T.VLCUSTOFIN,
              T.CODFILIAL,
              T.TIPOVENDA,
              T.DTCANCEL,
              T.CODFILIALNF,
              T.CONTRIBUINTE,
              T.CONSUMIDORFINAL,
              T.ESPECIE,
              T.DTSAIDANF,
              T.VLTOTAL,
              T.NUMNOTA
            FROM PCNFSAID T, PCDEVFORNEC D
            WHERE T.NUMTRANSVENDA = D.NUMTRANSVENDA(+)
              AND ' || GET_FILTRO_DATA_FORMATADA('DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFSAID;

  FUNCTION GET_INDICES_PCNFSAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIAL;NUMTRANSVENDA';
  END GET_INDICES_PCNFSAID;


  FUNCTION GET_VALORES_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.NUMTRANSVENDA,
              T.NUMTRANSENT,
              T.NUMNOTA,
              T.CODFILIALNF,
              T.CODFILIAL,
              T.NUMTRANSITEM,
              T.CODPROD,
              T.STATUS,
              T.DTMOV,
              T.CODOPER,
              T.CODFISCAL,
              T.PERCICM,
              T.GERAICMSLIVROFISCAL,
              T.SITTRIBUT,
              T.IMPORTADO,
              T.ST,
              T.QTCONT,
              T.BASEICMS,
              T.PUNITCONT,
              T.VLIPI,
              T.VLOUTROS,
              T.VLACRESCIMOPF,
              T.VLFRETE,
              T.BASEICST,
              T.VLBASEIPI,
              T.PERCIPI,
              T.VLSUFRAMA,
              T.VLPIS,
              T.VLCOFINS,
              T.BASEACRESCIMOPF,
              T.VLREPASSE,
              T.BASEBCR,
              T.STBCR,
              T.VLICMSBCR,
              T.VLDESCREDUCAOPIS,
              T.VLDESCONTO,
              T.VLDESCICMISENCAO,
              T.ALIQICMS1,
              T.PERICM,
              T.CODSITTRIBPISCOFINS
			  ,T.PERPIS
			  ,T.PERCOFINS

			  ,T.VLBASEPISCOFINS
            FROM PCMOV T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTMOV', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCMOV;

  FUNCTION GET_INDICES_PCMOV RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTMOV;NUMTRANSITEM;CODFILIAL;CODFILIALNF;NUMTRANSVENDA;NUMTRANSENT';
  END GET_INDICES_PCMOV;

  FUNCTION GET_VALORES_NFENTSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              ''E'' CODOPER, 
              NUMTRANSENT NUMTRANSACAO, 
              CODFILIAL, 
              CODFILIALNF, 
              ESPECIE 
            FROM PCTMPMONNFENT
            UNION
              SELECT ''S'' CODOPER, 
              NUMTRANSVENDA NUMTRANSACAO, 
              CODFILIAL, 
              CODFILIALNF, 
              ESPECIE 
            FROM PCTMPMONNFSAID ';
  END GET_VALORES_NFENTSAID;

  FUNCTION GET_INDICES_NFENTSAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSACAO,CODFILIAL,CODOPER';
  END GET_INDICES_NFENTSAID;


  FUNCTION GET_VALORES_MOV_UNIFICADA(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.NUMTRANSITEM,
              T.DTREGISTRO,
              T.PERDIFEREIMENTOICMS,
              T.ORIGMERCTRIB,
              T.VLBASEFRETE,
              T.VLBASEOUTROS,
              T.VLFECP,
              T.CODSITTRIBIPI,
              T.QTLITRAGEM,
              T.USAPISCOFINSLIT,
              T.VLICMSPARTDEST,
              T.VLICMSPARTREM,
              T.VLFCPPART,
              T.VLICMSDIFALIQPART,
              T.VLBASEPARTDEST,
              T.VLIPIDEVFORNEC,
              T.VLBASEFCPICMS,
              T.VLACRESCIMOFUNCEP,
              T.VLBASEFCPST,
              T.PERACRESCIMOFUNCEP,
              T.ALIQICMSFECP,
              T.PRECOUTILIZADONFE,
              T.VLICMSDESONERACAO,
            
              M.NUMTRANSVENDA,
              M.NUMTRANSENT,
              M.NUMNOTA,
              M.CODFILIALNF,
              M.CODFILIAL,
              M.CODPROD,
              M.STATUS,
              M.DTMOV,
              M.CODOPER,
              M.CODFISCAL,
              M.PERCICM,
              M.GERAICMSLIVROFISCAL,
              M.SITTRIBUT,
              M.IMPORTADO,
              M.ST,
              M.QTCONT,
              M.BASEICMS,
              M.PUNITCONT,
              M.VLIPI,
              M.VLOUTROS,
              M.VLACRESCIMOPF,
              M.VLFRETE,
              M.BASEICST,
              M.VLBASEIPI,
              M.PERCIPI,
              M.VLSUFRAMA,
              M.VLPIS,
              M.VLCOFINS,
              M.BASEACRESCIMOPF,
              M.VLREPASSE,
              M.BASEBCR,
              M.STBCR,
              M.VLICMSBCR,
              M.VLDESCREDUCAOPIS,
              M.VLDESCONTO,
              M.VLDESCICMISENCAO,
              M.ALIQICMS1,
              M.PERICM,
              M.CODSITTRIBPISCOFINS,
            
              DX.VPROD,
              DX.VUNTRIB,
              DX.VDESC,
              DX.VBC,
              DX.VICMS,
              DX.VBCST,
              DX.VICMSST,
              DX.VICMSDIF,
              DX.VOUTRO,
              DX.VICMSDESON,
              DX.VII,
              DX.VFRETE,
              DX.VSEG,
              
              (
                SELECT ES.ESPECIE 
                FROM PCTMPMONNFENTSAID ES
                WHERE 
                  ES.NUMTRANSACAO = M.NUMTRANSVENDA
                  AND ES.CODFILIAL = M.CODFILIAL
                  AND ES.CODOPER = SUBSTR(M.CODOPER, 1, 1)
              ) ESPECIE
			  ,M.PERPIS
			  ,M.PERCOFINS
		
			  ,M.VLBASEPISCOFINS
            FROM 
              PCMOVCOMPLE T
              ,PCMOV M
              , PCDADOSXML DX
            WHERE 
              EXISTS ( SELECT *
                             FROM PCMOV X
                             WHERE ' || GET_FILTRO_DATA_FORMATADA('X.DTMOV', PDATA_INICIAL, PDATA_FINAL) || '
                               AND X.NUMTRANSITEM = T.NUMTRANSITEM )
              AND M.NUMTRANSITEM = T.NUMTRANSITEM 
              AND DX.NUMTRANSITEM (+) = M.NUMTRANSITEM ';
  END GET_VALORES_MOV_UNIFICADA;

  FUNCTION GET_INDICES_MOV_UNIFICADA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTMOV;NUMTRANSITEM;CODFILIAL;CODFILIALNF;NUMTRANSVENDA;NUMTRANSENT';
  END GET_INDICES_MOV_UNIFICADA;


  FUNCTION GET_VALORES_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFISCAL,
              T.NUMTRANSVENDA,
              T.DTSAIDA,
              T.VLDESDOBRADO,
              T.VLBASE,
              T.VLICMS,
              T.VLISENTAS,
              T.VLOUTRAS,
              T.VLST,
              T.VLIPI,
              T.VLACRESCIMOFUNCEP,
              T.VLFECP,
              T.ESPECIE,
              T.SERIE,
              T.CODFILIALNF,
              T.UF,
              T.VLCOFINS,
              T.VLPIS,
              T.VLTOTAL,
              T.NUMNOTA,
              T.SITTRIBUT
			  ,T.PERCICM
            FROM PCNFBASESAID T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFBASESAID;

  FUNCTION GET_INDICES_PCNFBASESAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIALNF;NUMTRANSVENDA;NUMNOTA';
  END GET_INDICES_PCNFBASESAID;


  FUNCTION GET_VALORES_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFISCAL,
              T.NUMTRANSENT,
              T.DTENTRADA,
              T.VLDESDOBRADO,
              T.VLBASE,
              T.VLICMS,
              T.VLISENTAS,
              T.VLOUTRAS,
              T.VLST,
              T.VLIPI,
              T.VLACRESCIMOFUNCEP,
              T.VLFECP,
              T.ESPECIE,
              T.SERIE,
              T.CODFILIALNF,
              T.UF,
              T.TIPODESCARGA,
              T.VLCOFINS,
              T.VLPIS,
              T.VLTOTAL,
              T.NUMNOTA,
              T.SITTRIBUT
            FROM PCNFBASEENT T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTENTRADA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFBASEENT;

  FUNCTION GET_INDICES_PCNFBASEENT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENTRADA;CODFILIALNF;NUMTRANSENT;NUMNOTA';
  END GET_INDICES_PCNFBASEENT;


  FUNCTION GET_VALORES_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFILIALNF,
              T.CODFILIAL,
              T.DTENT,
              T.NUMNOTA,
              T.NUMTRANSENT,
              D.NUMTRANSENT PCDEVFORNEC_NUMTRANSENT,
              T.CODEXPORTADOR,
              T.CODFORNECNF,
              T.CODFORNEC,
              T.TIPODESCARGA,
              T.NOTADUPLIQUESVC,
              T.SITUACAONFE,
              T.CHAVENFE,
              T.GERANFVENDA,
              T.ESPECIE,
              T.DTEMISSAO,
              T.SERIE,
              T.FORNECEDOR,
              T.CGC,
              T.IE,
              T.UF,
              T.VLTOTAL,
              T.VLFRETE,
              T.VLOUTRAS,
              T.PERBASEREDOUTRASDESP,
              T.OBSLIVROFISCAL,
              T.OBS,
              T.NFENTREGAFUTURA,
              T.EMISSAOPROPRIA,
              T.IMPORTADOXML,
              T.DTCANCEL
            FROM PCNFENT T, PCDEVFORNEC D
            WHERE T.NUMTRANSENT = D.NUMTRANSENT (+)
              AND ' || GET_FILTRO_DATA_FORMATADA('DTENT', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFENT;

  FUNCTION GET_INDICES_PCNFENT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENT;CODFILIAL;NUMTRANSENT';
  END GET_INDICES_PCNFENT;


  FUNCTION GET_VALORES_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCESTCOM T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTESTORNO', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCESTCOM;

  FUNCTION GET_INDICES_PCESTCOM RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSVENDA;NUMTRANSENT;DTESTORNO';
  END GET_INDICES_PCESTCOM;


  FUNCTION GET_VALORES_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCDEVFORNEC T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTDEVOL', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCDEVFORNEC;

  FUNCTION GET_INDICES_PCDEVFORNEC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSVENDA;NUMTRANSENT;DTDEVOL';
  END GET_INDICES_PCDEVFORNEC;

  FUNCTION GET_VALORES_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCDEVAVULSO T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTEMISSAO', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCDEVAVULSO;
  
  FUNCTION GET_INDICES_PCDEVAVULSO RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSVENDA;NUMTRANSENT';
  END GET_INDICES_PCDEVAVULSO;
  

  FUNCTION GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT L.NUMTRANSOPERACAO
                  ,R.CODFATOGERADOR
                  ,R.CODFILIAL
                  ,L.DATAINTEGRACAO
              FROM PCLANCINTERMEDIARIA L
                  ,PCREGRACONTABIL     R
                  ,PCREGRAFILIAL       F
             WHERE ' || GET_FILTRO_DATA_FORMATADA('L.DATAINTEGRACAO', PDATA_INICIAL, PDATA_FINAL) ||'
               AND L.STATUS = ''I''
               AND R.CODFATOGERADOR in (1,2)
               AND R.CODREGRA = F.CODREGRA
               AND F.CODREGRA = L.CODREGRA
               AND F.CODFILIAL = L.CODFILIAL
               AND R.CODREGRA = L.CODREGRA
               AND R.CODPLANOCONTA = L.CODPLANOCONTA
             GROUP BY
               L.NUMTRANSOPERACAO
               ,R.CODFATOGERADOR
               ,R.CODFILIAL
               ,L.DATAINTEGRACAO';
  END GET_VALORES_NOTAS_CONTABIL;
  
  FUNCTION GET_INDICES_NOTAS_CONTABIL RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DATAINTEGRACAO;CODFATOGERADOR';
  END GET_INDICES_NOTAS_CONTABIL;


  FUNCTION GET_VALORES_PROD_TRIB_VINC RETURN VARCHAR2 IS
    V_SQL VARCHAR2(32000);
    V_TIPOTRIBUTACAOENTRADA VARCHAR2(1);
    V_LISTAFILIAIS VARCHAR(2);
    
    C_UNION_ALL CONSTANT VARCHAR2(100) := 
        '
        
        UNION ALL
          
        ';
    
    C_SQL_NCM_FIGURA CONSTANT VARCHAR2(2000) := 
        'SELECT DISTINCT 
          ''F'' TIPOTRIBUTACAOENTRADA,
          ''NCM/Figura tributária'' DESCRICAOTIPOTRIBUTACAOENTRADA, 
          PCTRIBENTRADA.CODFILIAL CODFILIAL, 
          PCPRODUT.CODPROD CODPROD, 
          PCPRODUT.DESCRICAO,
          DECODE(PCPRODUT.DTEXCLUSAO, NULL, ''Ativo'', ''Inativo'') STATUS,
          PCPRODUT.CODTRIBPISCOFINS,
          PCTRIBENTRADA.NCM NCM,
          PCTRIBFIGURA.PERCICM,
          PCTRIBFIGURA.PERIPI,
          PCTRIBPISCOFINS.PERCPIS,
          PCTRIBPISCOFINS.PERCCOFINS,
          ''XX'' UFORIGEM,
          ''XX'' UFDESTINO
        FROM PCTRIBENTRADA
           , PCTRIBFIGURA
           , PCFILIAL
           , PCTRIBPISCOFINS
           , PCEXPISCOFINS
           , PCPRODUT
        WHERE PCTRIBENTRADA.CODFIGURA   = PCTRIBFIGURA.CODFIGURA
         AND PCTRIBENTRADA.CODFILIAL   = PCFILIAL.CODIGO 
         AND PCTRIBENTRADA.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+) 
         AND PCTRIBENTRADA.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+)
         AND PCTRIBENTRADA.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
         AND PCTRIBENTRADA.NCM = PCPRODUT.CODNCMEX(+)';

    C_SQL_PRODUTO_FIGURA CONSTANT VARCHAR2(2000) := 
        'SELECT DISTINCT 
          ''P'' TIPOTRIBUTACAOENTRADA,
          ''Produto/Figura Tributária'' DESCRICAOTIPOTRIBUTACAOENTRADA, 
          PCTRIBENTPROD.CODFILIAL CODFILIAL,
          PCTRIBENTPROD.CODPROD CODPROD, 
          PCPRODUT.DESCRICAO,
          DECODE(PCPRODUT.DTEXCLUSAO, NULL, ''Ativo'', ''Inativo'') STATUS,
          PCPRODUT.CODTRIBPISCOFINS,
          PCPRODUT.CODNCMEX NCM,
          PCTRIBFIGURA.PERCICM,
          PCTRIBFIGURA.PERIPI,
          PCTRIBPISCOFINS.PERCPIS,
          PCTRIBPISCOFINS.PERCCOFINS,
          ''XX'' UFORIGEM,
          ''XX'' UFDESTINO
        FROM PCTRIBENTPROD
           , PCTRIBFIGURA
           , PCFILIAL
           , PCPRODUT
           , PCTRIBPISCOFINS
           , PCEXPISCOFINS
           , PCFORNEC     
        WHERE PCTRIBENTPROD.CODFIGURA   = PCTRIBFIGURA.CODFIGURA
         AND PCTRIBENTPROD.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+) 
         AND PCTRIBENTPROD.CODFILIAL   = PCFILIAL.CODIGO
         AND PCTRIBENTPROD.CODPROD     = PCPRODUT.CODPROD(+)
         AND PCTRIBENTPROD.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
         AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC';
         
    C_SQL_PRODUTO_UF CONSTANT VARCHAR2(2000) :=
        'SELECT 
          ''S'' TIPOTRIBUTACAOENTRADA,
          ''Produto/Estado(UF)'' DESCRICAOTIPOTRIBUTACAOENTRADA,
          PCPRODUT.CODFILIAL,
          PCTABTRIBENT.CODPROD,
          PCPRODUT.DESCRICAO PRODUTO,
          DECODE(PCPRODUT.DTEXCLUSAO, NULL, ''Ativo'', ''Inativo'') STATUS,
          PCTABTRIBENT.CODTRIBPISCOFINS,
          PCPRODUT.NBM NCM,
          NVL(PCTABTRIBENT.PERCICM,0) PERCICM,
          NVL(PCTABTRIBENT.PERIPI,0) PERIPI,
          NVL(PCTABTRIBENT.PERPIS,0) PERPIS,
          NVL(PCTABTRIBENT.PERCOFINS,0) PERCOFINS,
          NVL(PCTABTRIBENT.UFORIGEM, ''XX'') UFORIGEM,
          NVL(PCTABTRIBENT.UFDESTINO, ''XX'') UFDESTINO
        FROM PCTABTRIBENT
           , PCPRODUT
           , PCFORNEC
           , PCTRIBPISCOFINS
           , PCEXPISCOFINS
        WHERE PCTABTRIBENT.CODPROD   = PCPRODUT.CODPROD
          AND PCPRODUT.CODFORNEC     = PCFORNEC.CODFORNEC
          AND PCTABTRIBENT.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
          AND PCTABTRIBENT.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+) 
          AND PCTABTRIBENT.UFORIGEM <> ''EX''
          AND PCTABTRIBENT.UFDESTINO <> ''EX'' ';

    C_SQL_PRODUTO CONSTANT VARCHAR2(2000) :=
        'SELECT 
          ''N'' TIPOTRIBUTACAOENTRADA, 
          ''Produto'' DESCRICAOTIPOTRIBUTACAOENTRADA, 
          ''99'' CODFILIAL, 
          PCPRODUT.CODPROD CODPROD, 
          PCPRODUT.DESCRICAO,
          DECODE(PCPRODUT.DTEXCLUSAO, NULL, ''Ativo'', ''Inativo'') STATUS,
          PCPRODUT.CODTRIBPISCOFINS,
          PCPRODUT.CODNCMEX NCM,
          NVL(PCPRODUT.PERICM, 0) PERICMS,
          NVL(PCPRODUT.PERCIPI, 0) PERCIPI, 
          NVL(PCPRODUT.PERPIS, 0) PERCPIS,
          NVL(PCPRODUT.PERCOFINS, 0) PERCCOFINS,
          ''XX'' UFORIGEM,
          ''XX'' UFDESTINO
        FROM PCPRODUT
           , PCFORNEC
           , PCTRIBPISCOFINS
           , PCEXPISCOFINS
        WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
         AND PCPRODUT.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
         AND PCPRODUT.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+)';
    
  BEGIN
    V_SQL := '';
  
    FOR REGISTRO IN (SELECT 
                        VALOR VALOR_PARAMETRO, 
                        CODFILIAL FILIAL
                      FROM PCPARAMFILIAL F
                      WHERE F.NOME = 'CON_USATRIBENTPORUF') 
    LOOP

      IF NVL(TRIM(V_SQL), 'XX') <> 'XX' THEN
        V_SQL := V_SQL || C_UNION_ALL;
      END IF;

      -- NCM/Figura tributária (F)
      IF REGISTRO.VALOR_PARAMETRO = 'F' THEN
        V_SQL := V_SQL || C_SQL_NCM_FIGURA;
                 
        IF NVL(REGISTRO.FILIAL, '99') <> '99' THEN
          V_SQL := V_SQL || '  AND PCTRIBENTRADA.CODFILIAL = ' || CHR(39) || REGISTRO.FILIAL || CHR(39);
        END IF;
      END IF;
      
      -- Produto/Figura Tributária (P)
      IF REGISTRO.VALOR_PARAMETRO = 'P' THEN
        V_SQL := V_SQL || C_SQL_PRODUTO_FIGURA;
                 
        IF NVL(REGISTRO.FILIAL, '99') <> '99' THEN
          V_SQL := V_SQL || '  AND PCTRIBENTPROD.CODFILIAL = ' || CHR(39) || REGISTRO.FILIAL || CHR(39);
        END IF;
      END IF;
      
      -- Produto / Estado(UF) (S)  
      IF REGISTRO.VALOR_PARAMETRO = 'S' THEN
        V_SQL :=  V_SQL || C_SQL_PRODUTO_UF;
                 
        IF NVL(REGISTRO.FILIAL, '99') <> '99' THEN
          V_SQL := V_SQL || '  AND PCPRODUT.CODFILIAL = ' || CHR(39) || REGISTRO.FILIAL || CHR(39);
        END IF;
      END IF;
    
      -- Produto (N)  
      IF REGISTRO.VALOR_PARAMETRO = 'N' THEN
        V_SQL :=  V_SQL || C_SQL_PRODUTO;
      END IF;
    
    END LOOP;

    RETURN NVL(V_SQL, C_SQL_PRODUTO || ' AND PCPRODUT.CODPROD = -1 ');
  END GET_VALORES_PROD_TRIB_VINC;

  FUNCTION GET_INDICES_PROD_TRIB_VINC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CODFILIAL,NCM,CODPROD';
  END GET_INDICES_PROD_TRIB_VINC;


END PKG_MONITOR_TRIBUTARIO_CONSULT;