CREATE OR REPLACE PACKAGE "PKG_MONITOR_TRIBUTARIO_CONSULT" AS
  FUNCTION GET_VALORES_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFSAID RETURN VARCHAR2;
    
  FUNCTION GET_VALORES_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCMOV RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_PCMOVCOMPLE(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCMOVCOMPLE RETURN VARCHAR2;
    
  FUNCTION GET_VALORES_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFBASESAID RETURN VARCHAR2;
    
  FUNCTION GET_VALORES_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFBASEENT RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_INDICES_PCNFENT RETURN VARCHAR2;
    
  FUNCTION GET_VALORES_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_VALORES_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  FUNCTION GET_VALORES_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
  
  FUNCTION GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2;
END PKG_MONITOR_TRIBUTARIO_CONSULT;