CREATE OR REPLACE PACKAGE BODY PKG_MONITOR_TRIBUTARIO_CONSULT AS

  FUNCTION GET_CREATE_LISTA_TABELA_MONIT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCMONITORTRIBUTARIOLISTATABELA (
              TABELAORIGEM VARCHAR2(30) NOT NULL,
              TABELATEMPORARIA VARCHAR2(30) NOT NULL,
              TABELAMONITOR VARCHAR2(30) NOT NULL,
              TABELADEPENDENCIA VARCHAR2(30),
              INDICE VARCHAR2(4000)
            )';
  END GET_CREATE_LISTA_TABELA_MONIT;

  FUNCTION GET_CREATE_TABELA_TELEMETRIA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCTELEMETRIAMONITOR (
              DATAPROCESSAMENTO DATE,
              OBJETO VARCHAR(30),
              DATAHORAINICIO DATE,
              DATAHORATERMINO DATE,
              DADOS VARCHAR2(4000)
            )';
  END GET_CREATE_TABELA_TELEMETRIA;

  
  FUNCTION GET_INDICES_TELEMETRIA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DATAPROCESSAMENTO';
  END GET_INDICES_TELEMETRIA;
  
  
  FUNCTION GET_CREATE_TABELA_CONTROLEPROC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCCONTROLEPROCESSAMENTO (  
              DTCADASTRO DATE DEFAULT TRUNC(SYSDATE), 
              OBJETO VARCHAR2(30) NOT NULL ENABLE, 
              ATIVO VARCHAR2(1) DEFAULT ''N'', 
              MULTIPLASEXECUCOES VARCHAR(1) DEFAULT ''S'',
              DTULTPROCESSAMENTO DATE,
              DTPREPARACAOAMBIENTE DATE
            )';
  END GET_CREATE_TABELA_CONTROLEPROC;

  FUNCTION GET_CREATE_TABELA_LOG RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CREATE TABLE PCMONITORTRIBLOG (
              DATALOG DATE,
              CODUSUR NUMBER(4),
              TEMPOPERMANENCIA NUMBER(6),
              ACAO VARCHAR2(500),
              STATUSTELA VARCHAR2(1)
            )';
  END GET_CREATE_TABELA_LOG;


  FUNCTION GET_INDICES_CONTROLEPROC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'OBJETO';
  END GET_INDICES_CONTROLEPROC;


  FUNCTION GET_DATA_INICIAL(P_DATA IN DATE) RETURN DATE IS
  BEGIN
    RETURN NVL(P_DATA, SYSDATE - 90);
  END GET_DATA_INICIAL;


  FUNCTION GET_DATA_FINAL(PDATA IN DATE) RETURN DATE IS
  BEGIN
    RETURN NVL(PDATA, SYSDATE);
  END GET_DATA_FINAL;


  FUNCTION GET_FILTRO_DATA_FORMATADA(PCAMPO IN VARCHAR2, PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
    v_filtro VARCHAR(200);
  BEGIN
    v_filtro := PCAMPO || ' BETWEEN TO_DATE(''@DTINICIAL'', ''DD/MM/YYYY HH24:MI:SS'')'
                       || ' AND TO_DATE(''@DTFINAL'', ''DD/MM/YYYY HH24:MI:SS'') ';

    v_filtro := REPLACE(v_filtro, '@DTINICIAL', TO_CHAR(GET_DATA_INICIAL(PDATA_INICIAL), 'DD/MM/YYYY') || ' 00:00:00');
    v_filtro := REPLACE(v_filtro, '@DTFINAL', TO_CHAR(GET_DATA_FINAL(PDATA_FINAL), 'DD/MM/YYYY') || ' 23:59:59');

    RETURN v_filtro;
  END GET_FILTRO_DATA_FORMATADA;
  
  
  FUNCTION GET_VALORES_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.* FROM ' || PTABELA || ' T';
  END GET_VALORES_TABELA_MONITOR;


  FUNCTION GET_VALORES_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.DTSAIDA,
              T.CODFISCAL,
              T.NUMTRANSVENDA,
              D.NUMTRANSVENDA PCDEVFORNEC_NUMTRANSVENDA,
              T.SERIE,
              T.CONDVENDA,
              T.VLTOTGER,
              T.VLCUSTOFIN,
              T.CODFILIAL,
              T.TIPOVENDA,
              T.DTCANCEL,
              T.CODFILIALNF,
              T.CONTRIBUINTE,
              T.CONSUMIDORFINAL,
              T.ESPECIE,
              T.DTSAIDANF,
              T.VLTOTAL,
              T.NUMNOTA,
              T.CHAVENFE
            FROM PCNFSAID T, PCDEVFORNEC D
            WHERE T.NUMTRANSVENDA = D.NUMTRANSVENDA(+)
              AND ' || GET_FILTRO_DATA_FORMATADA('DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFSAID;

  FUNCTION GET_INDICES_PCNFSAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIAL;NUMTRANSVENDA;ESPECIE';
  END GET_INDICES_PCNFSAID;
  
  FUNCTION GET_VALORES_MOV_ROTINA_111(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN CLOB IS
    V_SQL_VLFECP       VARCHAR2(4000);
    V_SQL_ICMSRETIDO   VARCHAR2(4000);
    V_SQL_VLIPI        VARCHAR2(4000);
    V_SQL_VLREPASSE    VARCHAR2(4000);
    V_SQL_VLCUSTOFIN   VARCHAR2(4000);
    V_SQL_VLCUSTOFINB  VARCHAR2(4000);
    V_SQL_VLVENDA      VARCHAR2(10000);
    v_sql VARCHAR2(32000);
    V_VIEW_NAME VARCHAR2(100);
  BEGIN
    V_VIEW_NAME := 'VIEW_VENDAS_RESUMO_FATURAMENTO';  
  
    V_SQL_VLFECP      := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLFECP');
    V_SQL_ICMSRETIDO  := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'ICMSRETIDO');
    V_SQL_VLIPI       := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLIPI');
    V_SQL_VLREPASSE   := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLREPASSE');
    V_SQL_VLCUSTOFIN  := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLCUSTOFIN');
    V_SQL_VLCUSTOFINB := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLCUSTOFINB');
    V_SQL_VLVENDA     := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLVENDA');

    v_sql :=  ' SELECT 
              PCMOV.NUMTRANSVENDA,
              PCMOV.NUMNOTA,
              PCMOV.CODFILIALNF,
              PCNFSAID.CONDVENDA,
              NVL(PCMOV.CODFILIALNF, PCMOV.CODFILIAL) CODFILIAL,'
               || V_SQL_VLFECP || CHR(10) 
               || V_SQL_ICMSRETIDO || CHR(10) 
               || V_SQL_VLIPI || CHR(10) 
               || V_SQL_VLREPASSE ||  CHR(10) 
               || V_SQL_VLCUSTOFIN || CHR(10) 
               || V_SQL_VLCUSTOFINB || CHR(10)  
               || V_SQL_VLVENDA || CHR(10) ||
            ' PCNFSAID.DTSAIDA 
             FROM PCNFSAID, PCMOV, PCMOVCOMPLE 
             WHERE PCNFSAID.NUMTRANSVENDA = PCMOV.NUMTRANSVENDA
               AND PCNFSAID.NUMNOTA = PCMOV.NUMNOTA
               AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM
               AND NVL(PCMOV.TIPOITEM, ''C'') IN (''C'', ''N'')
               AND PCNFSAID.CODFISCAL <> 0
               AND PCNFSAID.DTCANCEL IS NULL
               AND NVL(PCNFSAID.CONDVENDA, -1) IN (1, 5, -1, 7, 9, 11, 14) 
               AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
               AND NVL(PCNFSAID.TIPOVENDA, ''X'') NOT IN (''SR'', ''DF'') 
               AND '|| GET_FILTRO_DATA_FORMATADA('PCNFSAID.DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  RETURN v_sql;
      
  END GET_VALORES_MOV_ROTINA_111;  
  
  FUNCTION GET_VALORES_DEVOLUCAO_ROT_111(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN CLOB IS
    V_SQL_VLDEVOLUCAO       VARCHAR2(4000);
    V_SQL_VLCMVDEVOL   VARCHAR2(4000);
    V_SQL_VLCUSTOFIN        VARCHAR2(4000);
    V_SQL_VLST    VARCHAR2(4000);
    V_SQL_VLIPI   VARCHAR2(4000);
    V_SQL_VLFECP  VARCHAR2(4000);
    V_SQL_VLREPASSE      VARCHAR2(10000);
    v_sql VARCHAR2(32000);
    V_VIEW_NAME VARCHAR2(100);
  BEGIN
    V_VIEW_NAME := 'VIEW_DEVOL_RESUMO_FATURAMENTO';  
  
    V_SQL_VLDEVOLUCAO := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLDEVOLUCAO');
    V_SQL_VLCMVDEVOL := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLCMVDEVOL');
    V_SQL_VLCUSTOFIN := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLCMVDEVOLBONIF');
    V_SQL_VLST := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLST');
    V_SQL_VLIPI := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLIPI');
    V_SQL_VLFECP := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLFECP');
    V_SQL_VLREPASSE := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLREPASSE');
    
    v_sql :=  ' SELECT 
              PCMOV.NUMTRANSVENDA,
              PCMOV.NUMNOTA,
              PCMOV.NUMTRANSENT,
              PCMOV.CODFILIALNF,
              NVL(PCNFENT.CODFILIALNF, PCNFENT.CODFILIAL) CODFILIAL,'
               || V_SQL_VLDEVOLUCAO || CHR(10) 
               || V_SQL_VLCMVDEVOL || CHR(10) 
               || V_SQL_VLCUSTOFIN || CHR(10) 
               || V_SQL_VLST ||  CHR(10) 
               || V_SQL_VLIPI || CHR(10) 
               || V_SQL_VLFECP || CHR(10)  
               || V_SQL_VLREPASSE || CHR(10) ||
            ' PCNFENT.DTENT 
             FROM PCNFSAID, PCMOV, PCMOVCOMPLE, PCNFENT, PCESTCOM 
             WHERE PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT
               AND PCESTCOM.NUMTRANSENT = PCMOV.NUMTRANSENT 
               AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+)
               AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM
               AND NVL(PCESTCOM.NUMTRANSVENDA, 0) <> 0
               AND PCNFENT.TIPODESCARGA IN (''6'', ''7'', ''T'')
               AND NVL(PCNFENT.CODFISCAL, 0) IN (131, 132, 231, 232, 199, 299)
               AND PCMOV.DTCANCEL IS NULL
               AND PCMOV.CODOPER = ''ED''
               AND (NVL(PCNFENT.ESPECIE, ''X'') <> ''OE'' OR
                   (NVL(PCNFENT.ESPECIE, ''X'') = ''OE'' AND
                   NVL(PCNFSAID.VENDAASSISTIDA, ''N'') = ''S'' AND PCNFSAID.CONDVENDA = 7))
               AND NVL(PCNFENT.OBS, ''X'') <> ''NF CANCELADA''
               AND NVL(PCNFENT.TIPOMOVGARANTIA, -1) = -1
               AND NOT (PCNFENT.ROTINACAD like ''%1303%'' and PCNFSAID.CONDVENDA = 8)
               AND NOT (PCNFSAID.CONDVENDA = 8 AND PCMOV.CUSTOFIN = 0)
               AND PCMOV.STATUS IN (''A'', ''AB'')
               AND '|| GET_FILTRO_DATA_FORMATADA('PCNFENT.DTENT', PDATA_INICIAL, PDATA_FINAL);
  RETURN v_sql;
      
  END GET_VALORES_DEVOLUCAO_ROT_111;
  
  FUNCTION GET_VALORES_DEVAVULSA_ROT_111(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN CLOB IS
    V_SQL_VLDEVOLUCAO       VARCHAR2(4000);
    V_SQL_VLCMVDEVOL   VARCHAR2(4000);
    V_SQL_VLCUSTOFIN        VARCHAR2(4000);
    V_SQL_VLST    VARCHAR2(4000);
    V_SQL_VLIPI   VARCHAR2(4000);
    V_SQL_VLFECP  VARCHAR2(4000);
    V_SQL_VLREPASSE      VARCHAR2(10000);
    v_sql VARCHAR2(32000);
    V_VIEW_NAME VARCHAR2(100);
  BEGIN
    V_VIEW_NAME := 'VIEW_DEVOL_RESUMO_FATURAVULSA';  
  
    V_SQL_VLDEVOLUCAO := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLDEVOLUCAO');
    V_SQL_VLCMVDEVOL := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLDEVCMVAVULSAI');
    V_SQL_VLST := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLST');
    V_SQL_VLIPI := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLIPI');
    V_SQL_VLFECP := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLFECP');
    V_SQL_VLREPASSE := F_EXTRAIR_SQL_VIEW(V_VIEW_NAME, 'VLREPASSE');
    
    v_sql :=  ' SELECT 
              PCMOV.NUMTRANSVENDA,
              PCMOV.NUMNOTA,
              PCMOV.NUMTRANSENT,
              PCMOV.CODFILIALNF,
              NVL(PCNFENT.CODFILIALNF, PCNFENT.CODFILIAL) CODFILIAL,'
               || V_SQL_VLDEVOLUCAO || CHR(10) 
               || V_SQL_VLCMVDEVOL || CHR(10) 
               || V_SQL_VLCUSTOFIN || CHR(10) 
               || V_SQL_VLST ||  CHR(10) 
               || V_SQL_VLIPI || CHR(10) 
               || V_SQL_VLFECP || CHR(10)  
               || V_SQL_VLREPASSE || CHR(10) ||
            ' PCNFENT.DTENT 
             FROM PCMOV, PCMOVCOMPLE, PCNFENT, PCESTCOM 
             WHERE PCESTCOM.NUMTRANSENT = PCNFENT.NUMTRANSENT
               AND PCESTCOM.NUMTRANSENT = PCMOV.NUMTRANSENT
               AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
               AND PCNFENT.TIPODESCARGA NOT IN (''C'', ''D'', ''8'')
               AND NVL(PCNFENT.OBS, ''X'') <> ''NF CANCELADA''
               AND NVL(PCESTCOM.NUMTRANSVENDA, 0) = 0
               AND PCMOV.CODOPER = ''ED''
               AND NVL(PCNFENT.ESPECIE, ''X'') <> ''OE''
               AND NVL(PCNFENT.TIPOMOVGARANTIA, -1) = -1
               AND '|| GET_FILTRO_DATA_FORMATADA('PCNFENT.DTENT', PDATA_INICIAL, PDATA_FINAL);
  RETURN v_sql;
      
  END GET_VALORES_DEVAVULSA_ROT_111;

  FUNCTION GET_VALORES_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.NUMTRANSVENDA,
              T.NUMTRANSENT,
              T.NUMNOTA,
              T.CODFILIALNF,
              T.CODFILIAL,
              T.NUMTRANSITEM,
              T.CODPROD,
              T.STATUS,
              T.DTMOV,
              T.CODOPER,
              T.CODFISCAL,
              T.PERCICM,
              T.GERAICMSLIVROFISCAL,
              T.SITTRIBUT,
              T.IMPORTADO,
              T.ST,
              T.QTCONT,
              T.BASEICMS,
              T.PUNITCONT,
              T.VLIPI,
              T.VLOUTROS,
              T.VLACRESCIMOPF,
              T.VLFRETE,
              T.BASEICST,
              T.VLBASEIPI,
              T.PERCIPI,
              T.VLSUFRAMA,
              T.VLPIS,
              T.VLCOFINS,
              T.BASEACRESCIMOPF,
              T.VLREPASSE,
              T.BASEBCR,
              T.STBCR,
              T.VLICMSBCR,
              T.VLDESCREDUCAOPIS,
              T.VLDESCONTO,
              T.VLDESCICMISENCAO,
              T.ALIQICMS1,
              T.PERICM,
              T.CODSITTRIBPISCOFINS,
      			  T.PERPIS,
     	  		  T.PERCOFINS,
       		 	  T.VLBASEPISCOFINS,
   	    		  T.DTCANCEL
         FROM PCMOV T
        WHERE ' || GET_FILTRO_DATA_FORMATADA('DTMOV', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCMOV;

  FUNCTION GET_INDICES_PCMOV RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTMOV;NUMTRANSITEM;CODFILIAL;CODFILIALNF;NUMTRANSVENDA;NUMTRANSENT';
  END GET_INDICES_PCMOV;

  FUNCTION GET_VALORES_NFENTSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              ''E'' CODOPER, 
              NUMTRANSENT NUMTRANSACAO, 
              CODFILIAL, 
              CODFILIALNF, 
              ESPECIE,
              CHAVENFE    
            FROM PCTMPMONNFENT
            UNION
              SELECT ''S'' CODOPER, 
              NUMTRANSVENDA NUMTRANSACAO, 
              CODFILIAL, 
              CODFILIALNF, 
              ESPECIE,
              CHAVENFE 
            FROM PCTMPMONNFSAID ';
  END GET_VALORES_NFENTSAID;

  FUNCTION GET_INDICES_NFENTSAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSACAO,CODFILIAL,CODOPER';
  END GET_INDICES_NFENTSAID;


  FUNCTION GET_VALORES_MOV_UNIFICADA(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'WITH 
            MOV AS (
                SELECT /*+ INDEX(PCMOV PCMOV_INDEX1) */  ROWID
                FROM PCMOV M 
                WHERE '|| GET_FILTRO_DATA_FORMATADA('M.DTMOV', PDATA_INICIAL, PDATA_FINAL) || '
            )
            SELECT
              MC.NUMTRANSITEM,
              MC.DTREGISTRO,
              MC.PERDIFEREIMENTOICMS,
              MC.ORIGMERCTRIB,
              ROUND(MC.VLBASEFRETE*NVL(M.QTCONT,0),2) AS VLBASEFRETE,
              ROUND(MC.VLBASEOUTROS*NVL(M.QTCONT,0),2) AS VLBASEOUTROS,
              ROUND(MC.VLFECP*NVL(M.QTCONT,0),2) AS VLFECP,
              MC.CODSITTRIBIPI,
              MC.QTLITRAGEM,
              MC.USAPISCOFINSLIT,
              ROUND(MC.VLICMSPARTDEST*NVL(M.QTCONT,0),2) AS VLICMSPARTDEST,
              ROUND(MC.VLICMSPARTREM*NVL(M.QTCONT,0),2) AS VLICMSPARTREM,
              ROUND(MC.VLFCPPART*NVL(M.QTCONT,0),2) AS VLFCPPART,
              ROUND(MC.VLICMSDIFALIQPART*NVL(M.QTCONT,0),2) AS VLICMSDIFALIQPART,
              ROUND(MC.VLBASEPARTDEST*NVL(M.QTCONT,0),2) AS VLBASEPARTDEST,
              ROUND(MC.VLIPIDEVFORNEC*NVL(M.QTCONT,0),2) AS VLIPIDEVFORNEC,
              ROUND(MC.VLBASEFCPICMS*NVL(M.QTCONT,0),2) AS VLBASEFCPICMS,
              ROUND(MC.VLACRESCIMOFUNCEP*NVL(M.QTCONT,0),2) AS VLACRESCIMOFUNCEP,
              ROUND(MC.VLBASEFCPST*NVL(M.QTCONT,0),2) AS VLBASEFCPST,
              MC.PERACRESCIMOFUNCEP,
              MC.ALIQICMSFECP,
              MC.PRECOUTILIZADONFE,
              ROUND(MC.VLICMSDESONERACAO*NVL(M.QTCONT,0),2) AS VLICMSDESONERACAO,
              M.NUMTRANSVENDA,
              M.NUMTRANSENT,
              M.NUMNOTA,
              M.CODFILIALNF,
              M.CODFILIAL,
              M.CODPROD,
              M.STATUS,
              M.DTMOV,
              M.CODOPER,
              M.CODFISCAL,
              M.PERCICM,
              M.GERAICMSLIVROFISCAL,
              M.SITTRIBUT,
              M.IMPORTADO,
              M.ST*NVL(M.QTCONT,0) AS ST,
              M.QTCONT,
              ROUND(M.BASEICMS*NVL(M.QTCONT,0),2) AS BASEICMS,
              ROUND(M.PUNITCONT*NVL(M.QTCONT,0),2) AS PUNITCONT,
              ROUND(M.VLIPI*NVL(M.QTCONT,0),2) AS VLIPI,
              ROUND(M.VLOUTROS*NVL(M.QTCONT,0),2) AS VLOUTROS,
              ROUND(M.VLACRESCIMOPF*NVL(M.QTCONT,0),2) AS VLACRESCIMOPF,
              ROUND(M.VLFRETE*NVL(M.QTCONT,0),2) AS VLFRETE,
              ROUND(M.BASEICST*NVL(M.QTCONT,0),2) AS BASEICST,
              ROUND(M.VLBASEIPI*NVL(M.QTCONT,0),2) AS VLBASEIPI,
              M.PERCIPI,
              ROUND(M.VLSUFRAMA*NVL(M.QTCONT,0),2) AS VLSUFRAMA,
              ROUND(M.VLPIS*NVL(M.QTCONT,0),2) AS VLPIS,
              ROUND(M.VLCOFINS*NVL(M.QTCONT,0),2) AS VLCOFINS,
              ROUND(M.BASEACRESCIMOPF*NVL(M.QTCONT,0),2) AS BASEACRESCIMOPF,
              M.VLREPASSE,
              ROUND(M.BASEBCR*NVL(M.QTCONT,0),2) AS BASEBCR,
              ROUND(M.STBCR*NVL(M.QTCONT,0),2) AS STBCR,
              ROUND(M.VLICMSBCR*NVL(M.QTCONT,0),2) AS VLICMSBCR,
              ROUND(M.VLDESCREDUCAOPIS*NVL(M.QTCONT,0),2) AS VLDESCREDUCAOPIS,
              ROUND(M.VLDESCONTO*NVL(M.QTCONT,0),2) AS VLDESCONTO,
              ROUND(M.VLDESCICMISENCAO*NVL(M.QTCONT,0),2) AS VLDESCICMISENCAO,
              M.ALIQICMS1,
              M.PERICM,
              M.CODSITTRIBPISCOFINS,
              DX.VPROD,
              DX.VUNTRIB,
              DX.VDESC,
              DX.VBC,
              DX.VICMS,
              DX.VBCST,
              DX.VICMSST,
              DX.VICMSDIF,
              DX.VOUTRO,
              DX.VICMSDESON,
              DX.VII,
              DX.VFRETE,
              DX.VSEG,
              (SELECT ES.ESPECIE
                 FROM PCTMPMONNFENTSAID ES
                WHERE ES.NUMTRANSACAO = M.NUMTRANSVENDA
                  AND NVL(ES.CODFILIALNF, ES.CODFILIAL) = NVL(M.CODFILIALNF, M.CODFILIAL)
                  AND ES.CODOPER = SUBSTR(M.CODOPER, 1, 1)) ESPECIE
              ,(SELECT ES.CHAVENFE
                  FROM PCTMPMONNFENTSAID ES
                 WHERE ES.NUMTRANSACAO = M.NUMTRANSVENDA
                   AND NVL(ES.CODFILIALNF, ES.CODFILIAL) = NVL(M.CODFILIALNF, M.CODFILIAL)
                   AND ES.CODOPER = SUBSTR(M.CODOPER, 1, 1)) CHAVENFE
              ,M.PERPIS
              ,M.PERCOFINS
              ,ROUND(M.VLBASEPISCOFINS*NVL(M.QTCONT,0),2) AS VLBASEPISCOFINS
              ,M.DTCANCEL
            FROM MOV, 
                 PCMOV M,
                 PCMOVCOMPLE MC,
                 PCDADOSXML DX
           WHERE MOV.ROWID = M.ROWID
             AND MC.NUMTRANSITEM = M.NUMTRANSITEM
             AND DX.NUMTRANSITEM(+) = M.NUMTRANSITEM
             AND M.DTCANCEL IS NULL 
             AND M.QTCONT > 0
             AND '|| GET_FILTRO_DATA_FORMATADA('M.DTMOV', PDATA_INICIAL, PDATA_FINAL) || '
             ';
  END GET_VALORES_MOV_UNIFICADA;

  FUNCTION GET_INDICES_MOV_UNIFICADA RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTMOV;NUMTRANSITEM;CODFILIAL;CODFILIALNF;NUMTRANSVENDA;NUMTRANSENT';
  END GET_INDICES_MOV_UNIFICADA;

  FUNCTION GET_INDICES_DEVOLUCAO_ROT_111 RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENT;CODFILIAL';
  END GET_INDICES_DEVOLUCAO_ROT_111;
  
  FUNCTION GET_INDICES_DEVAVULSA_ROT_111 RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENT;CODFILIAL';
  END GET_INDICES_DEVAVULSA_ROT_111;
  
  FUNCTION GET_INDICES_MOV_ROTINA_111 RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIAL';
  END GET_INDICES_MOV_ROTINA_111;

  FUNCTION GET_VALORES_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFISCAL,
              T.NUMTRANSVENDA,
              T.DTSAIDA,
              T.VLDESDOBRADO,
              T.VLBASE,
              T.VLICMS,
              T.VLISENTAS,
              T.VLOUTRAS,
              T.VLST,
              T.VLIPI,
              T.VLACRESCIMOFUNCEP,
              T.VLFECP,
              T.ESPECIE,
              T.SERIE,
              T.CODFILIALNF,
              T.UF,
              T.VLCOFINS,
              T.VLPIS,
              T.VLTOTAL,
              T.NUMNOTA,
              T.SITTRIBUT,
   			      T.PERCICM,
			        T.DTCANCEL
         FROM PCNFBASESAID T
        WHERE ' || GET_FILTRO_DATA_FORMATADA('DTSAIDA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFBASESAID;

  FUNCTION GET_INDICES_PCNFBASESAID RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTSAIDA;CODFILIALNF;NUMTRANSVENDA;NUMNOTA;ESPECIE';
  END GET_INDICES_PCNFBASESAID;


  FUNCTION GET_VALORES_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFISCAL,
              T.NUMTRANSENT,
              T.DTENTRADA,
              T.VLDESDOBRADO,
              T.VLBASE,
              T.VLICMS,
              T.VLISENTAS,
              T.VLOUTRAS,
              T.VLST,
              T.VLIPI,
              T.VLACRESCIMOFUNCEP,
              T.VLFECP,
              T.ESPECIE,
              T.SERIE,
              T.CODFILIALNF,
              T.UF,
              T.TIPODESCARGA,
              T.VLCOFINS,
              T.VLPIS,
              T.VLTOTAL,
              T.NUMNOTA,
              T.SITTRIBUT
         FROM PCNFBASEENT T
        WHERE ' || GET_FILTRO_DATA_FORMATADA('DTENTRADA', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFBASEENT;

  FUNCTION GET_INDICES_PCNFBASEENT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENTRADA;CODFILIALNF;NUMTRANSENT;NUMNOTA;ESPECIE';
  END GET_INDICES_PCNFBASEENT;


  FUNCTION GET_VALORES_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT
              T.CODFILIALNF,
              T.CODFILIAL,
              T.DTENT,
              T.NUMNOTA,
              T.NUMTRANSENT,
              D.NUMTRANSENT PCDEVFORNEC_NUMTRANSENT,
              T.CODEXPORTADOR,
              T.CODFORNECNF,
              T.CODFORNEC,
              T.TIPODESCARGA,
              T.NOTADUPLIQUESVC,
              T.SITUACAONFE,
              T.CHAVENFE,
              T.GERANFVENDA,
              T.ESPECIE,
              T.DTEMISSAO,
              T.SERIE,
              T.FORNECEDOR,
              T.CGC,
              T.IE,
              T.UF,
              T.VLTOTAL,
              T.VLFRETE,
              T.VLOUTRAS,
              T.PERBASEREDOUTRASDESP,
              T.OBSLIVROFISCAL,
              T.OBS,
              T.NFENTREGAFUTURA,
              T.EMISSAOPROPRIA,
              T.IMPORTADOXML,
              T.DTCANCEL
         FROM PCNFENT T, PCDEVFORNEC D
        WHERE T.NUMTRANSENT = D.NUMTRANSENT(+)
          AND T.ESPECIE <> ''OE'' 
          AND T.DTCANCEL IS NULL
          AND ' || GET_FILTRO_DATA_FORMATADA('DTENT', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCNFENT;

  FUNCTION GET_INDICES_PCNFENT RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DTENT;CODFILIAL;NUMTRANSENT;ESPECIE';
  END GET_INDICES_PCNFENT;


  FUNCTION GET_VALORES_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCESTCOM T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTESTORNO', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCESTCOM;

  FUNCTION GET_INDICES_PCESTCOM RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSVENDA;NUMTRANSENT;DTESTORNO';
  END GET_INDICES_PCESTCOM;


  FUNCTION GET_VALORES_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCDEVFORNEC T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTDEVOL', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCDEVFORNEC;

  FUNCTION GET_INDICES_PCDEVFORNEC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSVENDA;NUMTRANSENT;DTDEVOL';
  END GET_INDICES_PCDEVFORNEC;

  FUNCTION GET_VALORES_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT T.*
            FROM PCDEVAVULSO T
            WHERE ' || GET_FILTRO_DATA_FORMATADA('DTEMISSAO', PDATA_INICIAL, PDATA_FINAL);
  END GET_VALORES_PCDEVAVULSO;
  
  FUNCTION GET_INDICES_PCDEVAVULSO RETURN VARCHAR2 IS
  BEGIN
    RETURN 'NUMTRANSVENDA;NUMTRANSENT';
  END GET_INDICES_PCDEVAVULSO;
  

  FUNCTION GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'SELECT L.NUMTRANSOPERACAO
                  ,R.CODFATOGERADOR
                  ,R.CODFILIAL
                  ,L.DATAINTEGRACAO
              FROM PCLANCINTERMEDIARIA L
                  ,PCREGRACONTABIL     R
                  ,PCREGRAFILIAL       F
             WHERE ' || GET_FILTRO_DATA_FORMATADA('L.DATAINTEGRACAO', PDATA_INICIAL, PDATA_FINAL) ||'
               AND L.STATUS = ''I''
               AND R.CODREGRA = F.CODREGRA
               AND F.CODREGRA = L.CODREGRA
               AND F.CODFILIAL = L.CODFILIAL
               AND R.CODREGRA = L.CODREGRA
               AND R.CODPLANOCONTA = L.CODPLANOCONTA
             GROUP BY
                L.NUMTRANSOPERACAO
               ,R.CODFATOGERADOR
               ,R.CODFILIAL
               ,L.DATAINTEGRACAO';
  END GET_VALORES_NOTAS_CONTABIL;
  
  FUNCTION GET_INDICES_NOTAS_CONTABIL RETURN VARCHAR2 IS
  BEGIN
    RETURN 'DATAINTEGRACAO;CODFATOGERADOR';
  END GET_INDICES_NOTAS_CONTABIL;


  FUNCTION GET_VALORES_PROD_TRIB_VINC RETURN VARCHAR2 IS
    V_SQL VARCHAR2(32000);
    V_TIPOTRIBUTACAOENTRADA VARCHAR2(1000);
    V_LISTAFILIAIS VARCHAR(2);
    
    -- NCM/Figura tributária (F)
    C_SQL_NCM_FIGURA CONSTANT VARCHAR2(2000) := 
        'SELECT 
           ''F'' TIPOTRIBUTACAOENTRADA
           ,TRIB.CODFILIAL CODFILIAL
           ,PCPRODUT.CODPROD CODPROD
           ,PCPRODUT.CODFORNEC
           ,PCPRODUT.CODTRIBPISCOFINS
           ,PCPRODUT.NBM NCM
           ,TRIB.NCM CODNCMEX          
           ,TRIB.UFORIGEM
           ,PCFILIAL.UF UFDESTINO
         FROM PCTRIBFIGURA
              ,PCFILIAL
              ,PCTRIBPISCOFINS
              ,PCEXPISCOFINS
              ,PCPRODUT
              ,
              (SELECT CODFIGURA
                 ,CODFILIAL
                 ,UFORIGEM
                 ,CODEXCECAOPISCOFINS
                 ,CODTRIBPISCOFINS
                 ,NCM
               FROM PCTRIBENTRADA
               GROUP BY 
                 CODFIGURA
                 ,CODFILIAL
                 ,UFORIGEM
                 ,CODEXCECAOPISCOFINS
                 ,CODTRIBPISCOFINS
                 ,NCM) TRIB
         WHERE TRIB.CODFIGURA = PCTRIBFIGURA.CODFIGURA
           AND TRIB.NCM = PCPRODUT.CODNCMEX(+)
           AND TRIB.CODFILIAL = PCFILIAL.CODIGO
           AND TRIB.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+)
           AND TRIB.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
           AND PCPRODUT.DTEXCLUSAO IS NULL
         GROUP BY 
           TRIB.CODFILIAL
           ,PCPRODUT.CODPROD
           ,PCPRODUT.CODFORNEC
           ,PCPRODUT.CODTRIBPISCOFINS
           ,PCPRODUT.NBM
           ,TRIB.NCM          
           ,TRIB.UFORIGEM
           ,PCFILIAL.UF';

    -- Produto/Figura Tributária (P)
    C_SQL_PRODUTO_FIGURA CONSTANT VARCHAR2(2000) := 
        'SELECT 
           ''P'' TIPOTRIBUTACAOENTRADA
           ,TRIB.CODFILIAL CODFILIAL
           ,TRIB.CODPROD CODPROD
           ,PCPRODUT.CODFORNEC
           ,PCPRODUT.CODTRIBPISCOFINS
           ,PCPRODUT.NBM NCM
           ,PCPRODUT.CODNCMEX
           ,TRIB.UFORIGEM
           ,PCFILIAL.UF UFDESTINO
         FROM 
           PCTRIBFIGURA      
           ,PCFILIAL
           ,PCPRODUT
           ,PCTRIBPISCOFINS
           ,PCEXPISCOFINS
           ,PCFORNEC
           , 
            (
              SELECT 
                CODFILIAL
                ,UFORIGEM
                ,CODPROD
                ,CODFIGURA
                ,CODEXCECAOPISCOFINS
                ,CODTRIBPISCOFINS
              FROM PCTRIBENTPROD
              GROUP BY 
                CODFILIAL
                ,UFORIGEM
                ,CODPROD
                ,CODFIGURA
                ,CODEXCECAOPISCOFINS
                ,CODTRIBPISCOFINS
           ) TRIB
          WHERE TRIB.CODFIGURA = PCTRIBFIGURA.CODFIGURA
            AND TRIB.CODFILIAL   = PCFILIAL.CODIGO
            AND TRIB.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+)
            AND TRIB.CODPROD = PCPRODUT.CODPROD(+)
            AND TRIB.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
            AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
            AND PCPRODUT.DTEXCLUSAO IS NULL
          GROUP BY 
            TRIB.CODFILIAL
            ,TRIB.CODPROD
            ,PCPRODUT.CODFORNEC
            ,PCPRODUT.CODTRIBPISCOFINS
            ,PCPRODUT.NBM
            ,PCPRODUT.CODNCMEX
            ,TRIB.UFORIGEM
            ,PCFILIAL.UF';
    
    -- Produto / Estado(UF) (S)     
    C_SQL_PRODUTO_UF CONSTANT VARCHAR2(2000) :=
        'SELECT 
          ''S'' TIPOTRIBUTACAOENTRADA,
          PCPRODUT.CODFILIAL,
          PCTABTRIBENT.CODPROD,
          PCPRODUT.CODFORNEC,
          PCTABTRIBENT.CODTRIBPISCOFINS,
          PCPRODUT.NBM NCM,
          PCPRODUT.CODNCMEX,
          NVL(PCTABTRIBENT.UFORIGEM, ''XX'') UFORIGEM,
          NVL(PCTABTRIBENT.UFDESTINO, ''XX'') UFDESTINO
        FROM PCTABTRIBENT
           , PCPRODUT
           , PCFORNEC
           , PCTRIBPISCOFINS
           , PCEXPISCOFINS
        WHERE PCTABTRIBENT.CODPROD   = PCPRODUT.CODPROD
          AND PCPRODUT.CODFORNEC     = PCFORNEC.CODFORNEC
          AND PCTABTRIBENT.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
          AND PCTABTRIBENT.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+) 
          AND PCTABTRIBENT.UFORIGEM <> ''EX''
          AND PCTABTRIBENT.UFDESTINO <> ''EX''
          AND PCPRODUT.DTEXCLUSAO IS NULL
        GROUP BY
          PCPRODUT.CODFILIAL
          ,PCTABTRIBENT.CODPROD
          ,PCPRODUT.CODFORNEC
          ,PCTABTRIBENT.CODTRIBPISCOFINS
          ,PCPRODUT.NBM
          ,PCPRODUT.CODNCMEX
          ,NVL(PCTABTRIBENT.UFORIGEM, ''XX'')
          ,NVL(PCTABTRIBENT.UFDESTINO, ''XX'')';

    -- Produto (N)
    C_SQL_PRODUTO CONSTANT VARCHAR2(2000) :=
        'SELECT
          ''N'' TIPOTRIBUTACAOENTRADA
          ,''99'' CODFILIAL
          ,PCPRODUT.CODPROD
          ,PCPRODUT.CODFORNEC
          ,PCPRODUT.CODTRIBPISCOFINS
          ,PCPRODUT.NBM NCM
          ,PCPRODUT.CODNCMEX
          ,''XX'' UFORIGEM
          ,''XX'' UFDESTINO
        FROM PCPRODUT
           , PCFORNEC
           , PCTRIBPISCOFINS
           , PCEXPISCOFINS
        WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
          AND PCPRODUT.CODTRIBPISCOFINS = PCTRIBPISCOFINS.CODTRIBPISCOFINS(+)
          AND PCPRODUT.CODEXCECAOPISCOFINS = PCEXPISCOFINS.CODEXCECAO(+)
          AND PCPRODUT.DTEXCLUSAO IS NULL
        GROUP BY
          PCPRODUT.CODPROD
          ,PCPRODUT.CODFORNEC
          ,PCPRODUT.CODTRIBPISCOFINS
          ,PCPRODUT.NBM
          ,PCPRODUT.CODNCMEX';
    
  BEGIN
    V_SQL := '';
  
    SELECT VALOR
    INTO V_TIPOTRIBUTACAOENTRADA
    FROM PCPARAMFILIAL F
    WHERE F.NOME = 'CON_USATRIBENTPORUF'
      AND CODFILIAL = '99';

    -- NCM/Figura tributária (F)
    IF TRIM(V_TIPOTRIBUTACAOENTRADA) = 'F' THEN
      V_SQL := V_SQL || C_SQL_NCM_FIGURA;
    END IF;
      
    -- Produto/Figura Tributária (P)
    IF TRIM(V_TIPOTRIBUTACAOENTRADA) = 'P' THEN
      V_SQL := V_SQL || C_SQL_PRODUTO_FIGURA;
    END IF;
      
    -- Produto / Estado(UF) (S)  
    IF TRIM(V_TIPOTRIBUTACAOENTRADA) = 'S' THEN
      V_SQL :=  V_SQL || C_SQL_PRODUTO_UF;
    END IF;
    
    -- Produto (N)  
    IF TRIM(V_TIPOTRIBUTACAOENTRADA) = 'N' THEN
      V_SQL :=  V_SQL || C_SQL_PRODUTO;
    END IF;

    RETURN NVL(V_SQL, C_SQL_PRODUTO || ' AND PCPRODUT.CODPROD = -1 ');
  END GET_VALORES_PROD_TRIB_VINC;

  FUNCTION GET_INDICES_PROD_TRIB_VINC RETURN VARCHAR2 IS
  BEGIN
    RETURN 'CODNCMEX,CODFILIAL;CODPROD,CODFILIAL';
  END GET_INDICES_PROD_TRIB_VINC;

END PKG_MONITOR_TRIBUTARIO_CONSULT;
-- 25/09/2025 - v001 --