CREATE OR REPLACE FUNCTION CTE_INFO_CARGA(P_TRANSACAO NUMBER)
  RETURN TABELA_CTE_INFO_CARGA IS

  CURSOR CR_INF_CARGA IS
     SELECT NVL(PCUNIDADE.UNIDADECTE,
           DECODE(PCMOV.UNIDADE,
                  'M3',
                  '00',
                  'KG',
                  '01',
                  'T0',
                  '02',
                  'UN',
                  '03',
                  'LT',
                  '04',
                  '03')) AS CODIGO_UNIDADE,
       NVL(PCUNIDADE.DESCRICAO, 'UNIDADE') AS TIPO_MEDIDA,
       DECODE(NVL(PCUNIDADE.UNIDADECTE,
                  DECODE(PCMOV.UNIDADE,
                         'M3',
                         '00',
                         'KG',
                         '01',
                         'T0',
                         '02',
                         'UN',
                         '03',
                         'LT',
                         '04',
                         '03')),
              '00',
              SUM(PCMOV.QTCONT * NVL(PCPRODUT.VOLUME, 1)),
              '01',
              SUM(PCMOV.QTCONT * NVL(PCMOV.PESOBRUTO, PCMOV.PESOLIQ)),
              '02',
              SUM(PCMOV.QTCONT * NVL(PCMOV.PESOBRUTO, PCMOV.PESOLIQ) / 1000),
              '03',
              SUM(PCMOV.QTCONT),
              '04',
              SUM(PCMOV.QTCONT *
                  DECODE(NVL(PCMOVCOMPLE.QTLITRAGEM, 0),
                         0,
                         1,
                         PCMOVCOMPLE.QTLITRAGEM))) QUANTIDADE_CARGA,
       DECODE(NVL(PCUNIDADE.UNIDADECTE,
                  DECODE(PCMOV.UNIDADE,
                         'M3',
                         '00',
                         'KG',
                         '01',
                         'T0',
                         '02',
                         'UN',
                         '03',
                         'LT',
                         '04',
                         '03')),
              '00',
              SUM(PCMOV.QTCONT * NVL(PCPRODUT.VOLUME, 1))) CUBAGEM,
       SUM(PCMOV.QTCONT * NVL(PCMOV.PESOBRUTO, PCMOV.PESOLIQ)) AS VALOR_PESO_BRUTO,
       (SELECT SUM(PCNFSAID.VLTOTAL)
          FROM PCNFSAID
         WHERE PCNFSAID.NUMTRANSVENDACONHEC = P_TRANSACAO
           AND NOT ESPECIE IN ('CE', 'CO')) AS VALOR_TOTAL_CARGA,
       PRODPREDOMINANTE.DESCRICAO PRODUTO_PREDOMINANTE,
       PCVEICUL.CODIGORNTRC RNTRC,
       NVL(PCNFSAID.DTENTREGA, PCCARREG.DTFAT) DATA_PREVISTA,
       PCCARREG.NUMONUCARGA,
       PCCARREG.NOMEAPROPRIADOCARGA,
       PCCARREG.DIVISAOCARGA,
       PCCARREG.GRUPOEMBCARGA,
       PCCARREG.QTDTOTALPRODCARGA,
       PCCARREG.PONTOFUGORCARGA,
       PCNFSAID.CNPJFORNEC,
       PCNFSAID.NUMCOMPROVANTE,
       PCNFSAID.CNPJRESPONSAVEL,
       NVL(PCNFSAID.RESPSEGURO, NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('RESPSEGUROPADRAO',NVL(CONHECIMENTOFRETE.CODFILIALNF, CONHECIMENTOFRETE.CODFILIAL)), CONHECIMENTOFRETE.RESPSEGURO)) AS RESPSEGURO,
       NVL(PCNFSAID.NOMESEGURADORA, CONHECIMENTOFRETE.NOMESEGURADORA) AS NOMESEGURADORA,
       NVL(PCNFSAID.NUMEROAPOLICE, CONHECIMENTOFRETE.NUMEROAPOLICE) AS NUMEROAPOLICE,
       NVL(PCNFSAID.NUMEROAVERBACAO,CONHECIMENTOFRETE.NUMEROAVERBACAO) AS NUMEROAVERBACAO,
       NVL(PCNFSAID.VLPEDAGIO,CONHECIMENTOFRETE.VLPEDAGIO) AS VLPEDAGIO
  FROM PCMOV,
       PCMOVCOMPLE,
       PCUNIDADE,
       PCNFSAID,
       PCPRODUT PRODPREDOMINANTE,
       PCPRODUT,
       PCNFSAID CONHECIMENTOFRETE,
       PCCARREG,
       PCVEICUL
 WHERE PCUNIDADE.UNIDADE(+) = PCMOV.UNIDADE
   AND PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCNFSAID.NUMTRANSVENDACONHEC = P_TRANSACAO
   AND PCNFSAID.ESPECIE NOT IN ('CE', 'CO')
   AND CONHECIMENTOFRETE.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDACONHEC
   AND CONHECIMENTOFRETE.CODPRODPREDOMINANTE = PRODPREDOMINANTE.CODPROD
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND CONHECIMENTOFRETE.NUMCAR = PCCARREG.NUMCAR
   AND NVL(PCCARREG.CODVEICULO, CONHECIMENTOFRETE.CODVEICULO) = PCVEICUL.CODVEICULO
   AND NVL(PCNFSAID.TIPOEMISSAOCTE, 0) = 0
   AND CONHECIMENTOFRETE.ESPECIE IN ('CE', 'CO')
   AND PCMOV.STATUS in ('A','AB')
 GROUP BY PCUNIDADE.UNIDADECTE,
          PCMOV.UNIDADE,
          PCUNIDADE.DESCRICAO,
          PRODPREDOMINANTE.DESCRICAO,
          PCVEICUL.CODIGORNTRC,
          NVL(PCNFSAID.DTENTREGA, PCCARREG.DTFAT),
          PCCARREG.NUMONUCARGA,
          PCCARREG.NOMEAPROPRIADOCARGA,
          PCCARREG.DIVISAOCARGA,
          PCCARREG.GRUPOEMBCARGA,
          PCCARREG.QTDTOTALPRODCARGA,
          PCCARREG.PONTOFUGORCARGA,
          PCNFSAID.CNPJFORNEC,
          PCNFSAID.NUMCOMPROVANTE,
          PCNFSAID.CNPJRESPONSAVEL,
          PCNFSAID.RESPSEGURO,
          CONHECIMENTOFRETE.RESPSEGURO,
          NVL(PCNFSAID.NOMESEGURADORA, CONHECIMENTOFRETE.NOMESEGURADORA),
          NVL(PCNFSAID.NUMEROAPOLICE, CONHECIMENTOFRETE.NUMEROAPOLICE),
          NVL(PCNFSAID.NUMEROAVERBACAO,CONHECIMENTOFRETE.NUMEROAVERBACAO),
          CONHECIMENTOFRETE.CODFILIALNF,
          CONHECIMENTOFRETE.CODFILIAL,
          NVL(PCNFSAID.VLPEDAGIO,CONHECIMENTOFRETE.VLPEDAGIO)
    UNION ALL

    SELECT NVL(PCCONHECIMENTOFRETEI.UNIDADECTE, '03') CODIGO_UNIDADE,
           NVL(PCCONHECIMENTOFRETEI.TIPOMEDIDACTE, 'UNIDADE') TIPO_MEDIDA,
           DECODE(NVL(PCCONHECIMENTOFRETEI.UNIDADECTE, '03'),
              '00',
              SUM(NVL(PCCONHECIMENTOFRETEI.QTLITRAGEM, 1)),
              '01',
              SUM(NVL(PCCONHECIMENTOFRETEI.PESO, 1)),
              '02',
              (SUM(NVL(PCCONHECIMENTOFRETEI.PESO, 1)) / 1000),
              '03',
              SUM(PCCONHECIMENTOFRETEI.QTITENS),
              '04',
              SUM(NVL(PCCONHECIMENTOFRETEI.QTLITRAGEM, 1))) QUANTIDADE_CARGA,
           DECODE(NVL(PCCONHECIMENTOFRETEI.UNIDADECTE, '03'),
              '00',
              SUM(NVL(PCCONHECIMENTOFRETEI.VOLUME, 1))) CUBAGEM,
           SUM(PCCONHECIMENTOFRETEI.PESO) VALOR_PESO_BRUTO,
           (SELECT SUM(FRETE.VLTOTAL)
                 FROM PCCONHECIMENTOFRETEI FRETE
             WHERE FRETE.NUMTRANSCONHEC = P_TRANSACAO) AS VALOR_TOTAL_CARGA,
           PCPRODUT.DESCRICAO PRODUTO_PREDOMINANTE,
           PCVEICUL.CODIGORNTRC RNTRC,
           NVL(PCNFSAID.DTENTREGA, PCNFSAID.DTSAIDA) DATA_PREVISTA,
           '' NUMONUCARGA,
           '' NOMEAPROPRIADOCARGA,
           '' DIVISAOCARGA,
           '' GRUPOEMBCARGA,
           '' QTDTOTALPRODCARGA,
           '' PONTOFUGORCARGA,
           PCNFSAID.CNPJFORNEC,
           PCNFSAID.NUMCOMPROVANTE,
           PCNFSAID.CNPJRESPONSAVEL,
           NVL(PCNFSAID.RESPSEGURO,PARAMFILIAL.OBTERCOMOVARCHAR2('RESPSEGUROPADRAO',NVL(PCNFSAID.CODFILIALNF, PCNFSAID.CODFILIAL)))AS RESPSEGURO,
           PCNFSAID.NOMESEGURADORA,
           PCNFSAID.NUMEROAPOLICE,
           PCNFSAID.NUMEROAVERBACAO,
           PCNFSAID.VLPEDAGIO
      FROM PCCONHECIMENTOFRETEI, PCNFSAID, PCPRODUT, PCVEICUL
     WHERE PCCONHECIMENTOFRETEI.NUMTRANSCONHEC = P_TRANSACAO
       AND PCNFSAID.NUMTRANSVENDA = PCCONHECIMENTOFRETEI.NUMTRANSCONHEC
       AND NVL(PCNFSAID.TIPOEMISSAOCTE, 0) = 0
       AND PCPRODUT.CODPROD(+) = PCNFSAID.CODPRODPREDOMINANTE
       AND PCVEICUL.CODVEICULO(+) = PCNFSAID.CODVEICULO
     GROUP BY PCCONHECIMENTOFRETEI.UNIDADECTE,
              PCCONHECIMENTOFRETEI.TIPOMEDIDACTE,
              PCPRODUT.DESCRICAO,
              PCVEICUL.CODIGORNTRC,
              NVL(PCNFSAID.DTENTREGA, PCNFSAID.DTSAIDA),
              PCNFSAID.CNPJFORNEC,
              PCNFSAID.NUMCOMPROVANTE,
              PCNFSAID.CNPJRESPONSAVEL,
              PCNFSAID.RESPSEGURO,
              PCNFSAID.NOMESEGURADORA,
              PCNFSAID.NUMEROAPOLICE,
              PCNFSAID.NUMEROAVERBACAO,
              PCNFSAID.CODFILIALNF,
              PCNFSAID.CODFILIAL,
              PCNFSAID.VLPEDAGIO;

  RETORNO TABELA_CTE_INFO_CARGA;
BEGIN
  RETORNO := TABELA_CTE_INFO_CARGA();

  FOR ITEM IN CR_INF_CARGA LOOP
        RETORNO.EXTEND;

        RETORNO(RETORNO.COUNT) := TIPO_CTE_INFO_CARGA(VALOR_TOTAL_MERCADORIA       => NULL,
                                                  PRODUTO_PREDOMINANTE         => NULL,
                                                  OUTRAS_CARACTERISTICAS_CARGA => NULL,
                                                  CODIGO_UNIDADE               => NULL,
                                                  TIPO_MEDIDA                  => NULL,
                                                  QUANTIDADE_CARGA             => NULL,
                                                  CUBAGEM                      => NULL,
                                                  VALOR_PESO_BRUTO             => NULL,
                                                  RNTRC                        => NULL,
                                                  DATA_PREVISTA_ENTREGA        => NULL,
                                                  LOTACAO                      => NULL,
                                                  NUMONUCARGA                  => NULL,
                                                  NOMEAPROPRIADOCARGA          => NULL,
                                                  DIVISAOCARGA                 => NULL,
                                                  GRUPOEMBCARGA                => NULL,
                                                  QTDTOTALPRODCARGA            => NULL,
                                                  PONTOFUGORCARGA              => NULL,
                                                  CNPJFORNEC                   => NULL,
                                                  NUMCOMPROVANTE               => NULL,
                                                  CNPJRESPONSAVEL              => NULL,
                                                  RESPSEGURO                   => NULL,
                                                  NOMESEGURADORA               => NULL,
                                                  NUMEROAPOLICE                => NULL,
                                                  NUMEROAVERBACAO              => NULL,
                                                  VLVALEPEDAGIO                => NULL);


      RETORNO(RETORNO.COUNT).VALOR_TOTAL_MERCADORIA       := ITEM.VALOR_TOTAL_CARGA;
      RETORNO(RETORNO.COUNT).PRODUTO_PREDOMINANTE         := ITEM.PRODUTO_PREDOMINANTE;
      RETORNO(RETORNO.COUNT).OUTRAS_CARACTERISTICAS_CARGA := '';
      RETORNO(RETORNO.COUNT).CODIGO_UNIDADE               := ITEM.CODIGO_UNIDADE;
      RETORNO(RETORNO.COUNT).TIPO_MEDIDA                  := ITEM.TIPO_MEDIDA;
      RETORNO(RETORNO.COUNT).QUANTIDADE_CARGA             := ITEM.QUANTIDADE_CARGA;
      RETORNO(RETORNO.COUNT).CUBAGEM                      := ITEM.CUBAGEM;
      RETORNO(RETORNO.COUNT).VALOR_PESO_BRUTO             := ITEM.VALOR_PESO_BRUTO;
      RETORNO(RETORNO.COUNT).RNTRC                        := ITEM.RNTRC;
      RETORNO(RETORNO.COUNT).DATA_PREVISTA_ENTREGA        := ITEM.DATA_PREVISTA;
      RETORNO(RETORNO.COUNT).LOTACAO                      := 1;
      RETORNO(RETORNO.COUNT).NUMONUCARGA                  := ITEM.NUMONUCARGA;
      RETORNO(RETORNO.COUNT).NOMEAPROPRIADOCARGA          := ITEM.NOMEAPROPRIADOCARGA;
      RETORNO(RETORNO.COUNT).DIVISAOCARGA                 := ITEM.DIVISAOCARGA;
      RETORNO(RETORNO.COUNT).GRUPOEMBCARGA                := ITEM.GRUPOEMBCARGA;
      RETORNO(RETORNO.COUNT).QTDTOTALPRODCARGA            := ITEM.QTDTOTALPRODCARGA;
      RETORNO(RETORNO.COUNT).PONTOFUGORCARGA              := ITEM.PONTOFUGORCARGA;
      RETORNO(RETORNO.COUNT).CNPJFORNEC                   := ITEM.CNPJFORNEC;
      RETORNO(RETORNO.COUNT).NUMCOMPROVANTE               := ITEM.NUMCOMPROVANTE;
      RETORNO(RETORNO.COUNT).CNPJRESPONSAVEL              := ITEM.CNPJRESPONSAVEL;
      RETORNO(RETORNO.COUNT).RESPSEGURO                   := ITEM.RESPSEGURO;
      RETORNO(RETORNO.COUNT).NOMESEGURADORA               := ITEM.NOMESEGURADORA;
      RETORNO(RETORNO.COUNT).NUMEROAPOLICE                := ITEM.NUMEROAPOLICE;
      RETORNO(RETORNO.COUNT).NUMEROAVERBACAO              := ITEM.NUMEROAVERBACAO;
      RETORNO(RETORNO.COUNT).VLVALEPEDAGIO                := ITEM.VLPEDAGIO;

  END LOOP;

  RETURN RETORNO;

EXCEPTION
  WHEN OTHERS THEN
    raise_application_error(-20001, 'Erro motivo: ' || SQLERRM || '. Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;