CREATE OR REPLACE VIEW SQL_NFE_PARCELA_SAIDA_DIN AS
SELECT DH.NUMTRANSVENDA AS NUM_TRANSACAO,
       MAX((TO_CHAR(DH.DUPLIC) || ' - ' || TO_CHAR(DH.PREST))) AS PRESTACAO,
       MAX(DH.DUPLIC) AS DUPLIC,
       MAX(DH.PREST) AS PREST,
       MAX(DECODE(DH.CODCOB,
                  'VPP',
                  DH.DTEMISSAO,
                  DH.DTVENC)) AS DTVENC,
       MAX(NVL(DH.VALORENTFUT, DH.VALOR)) AS VALOR,
       MAX(DH.CODCOB) AS CODCOB,
       MAX(NVL(DH.VALORDESC, 0)) AS VALORDESC,
       MAX(DH.CODCOBSEFAZ) AS CODCOBSEFAZ,
       MAX(DH.RAZAOCREDENCCARTAO) AS RAZAO_CRED_CARTAO,
       MAX(DH.CNPJCREDENCCARTAO) AS CNPJ_CRED_CARTAO,
       MAX(DH.NSUTEF) AS NUMAUTOR_CARTAO,
       MAX(DH.BANDEIRACARTAO) AS BANDEIRA_CARTAO,
       MAX(NVL(DH.CORRESPONDENTE, '2')) AS TP_INTEGRA,
       MAX(DH.DATACONSOLIDACAOPREFAT) DATACONSOLIDACAOPREFAT,
       'N' PREFATURAMENTO,
       MAX(PCCOB.INDPAG) INDPAG
FROM  PCPREST DH, PCNFSAID, PCCOB
WHERE DH.STATUS = 'A'
AND   DH.DTDESD IS NULL
AND   DH.DTESTORNO IS NULL
AND   NVL(DH.VALOR, 0) > 0
AND   DH.CODCOB IN ('DH', 'D')
AND   PCNFSAID.NUMTRANSVENDA = DH.NUMTRANSVENDA
AND   DH.CODCLI = PCNFSAID.CODCLI
AND   PCCOB.CODCOB = DH.CODCOB
AND   ((NVL(PCNFSAID.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAID.CODFILIAL) = 'S'))
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(DH.PERMITEESTORNO, 'S') = 'S'
GROUP BY DH.NUMTRANSVENDA, DH.PREST
--Modifiquei pois no cliente tinha plano especial de pgto e deveria trazer as 03 parcelas Bruno 4255.040287.2016
UNION ALL
SELECT DH.NUMTRANSVENDA AS NUM_TRANSACAO,
       MAX((TO_CHAR(DH.DUPLIC) || ' - ' || TO_CHAR(DH.PREST))) AS PRESTACAO,
       MAX(DH.DUPLIC) AS DUPLIC,
       MAX(DH.PREST) AS PREST,
       MAX(DECODE(DH.CODCOB,
                  'VPP',
                  DH.DTEMISSAO,
                  DH.DTVENC)) AS DTVENC,
       MAX(NVL(DH.VALORENTFUT, DH.VALOR)) AS VALOR,
       MAX(DH.CODCOB) AS CODCOB,
       MAX(NVL(DH.VALORDESC, 0)) AS VALORDESC,
       MAX(DH.CODCOBSEFAZ) AS CODCOBSEFAZ,
       MAX(DH.RAZAOCREDENCCARTAO) AS RAZAO_CRED_CARTAO,
       MAX(DH.CNPJCREDENCCARTAO) AS CNPJ_CRED_CARTAO,
       MAX(DH.NSUTEF) AS NUMAUTOR_CARTAO,
       MAX(DH.BANDEIRACARTAO) AS BANDEIRA_CARTAO,
       MAX(NVL(DH.CORRESPONDENTE, '2')) AS TP_INTEGRA,
       MAX(DH.DATACONSOLIDACAOPREFAT) DATACONSOLIDACAOPREFAT,
       'S' PREFATURAMENTO,
       MAX(PCCOB.INDPAG) INDPAG
FROM  PCPRESTPREFAT DH, PCNFSAIDPREFAT, PCCOB
WHERE DH.STATUS = 'A'
AND   DH.DTDESD IS NULL
AND   DH.DTESTORNO IS NULL
AND   NVL(DH.VALOR, 0) > 0
AND   DH.CODCOB IN ('DH', 'D')
AND   PCNFSAIDPREFAT.NUMTRANSVENDA = DH.NUMTRANSVENDA
AND   DH.CODCLI = PCNFSAIDPREFAT.CODCLI
AND   PCCOB.CODCOB = DH.CODCOB
AND   ((NVL(PCNFSAIDPREFAT.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAIDPREFAT.CODFILIAL) = 'S'))
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(DH.PERMITEESTORNO, 'S') = 'S'
AND   DH.DATACONSOLIDACAOPREFAT IS NULL
GROUP BY DH.NUMTRANSVENDA, DH.PREST 