CREATE OR REPLACE FUNCTION GET_VALORES_FATURAMENTO(PDIAANTERIOR IN BOOLEAN)
  RETURN VARCHAR2 IS
  V_SQL VARCHAR2(4000);
BEGIN
  V_SQL := 'SELECT
                N.NUMTRANSVENDA,
                N.SERIE,
                N.VLTOTGER,
                N.VLCUSTOFIN,
                N.VLTOTGER -
                N.VLCUSTOFIN AS VLLUCRO,
                N.CODFILIAL,
                N.CODFILIALNF
            FROM PCNFSAID N
            WHERE N.DTSAIDA >= TRUNC(SYSDATE-90) ';
  IF PDIAANTERIOR THEN
    V_SQL := V_SQL || ' AND N.DTSAIDA < TRUNC(SYSDATE-1) ';
  ELSE
    V_SQL := V_SQL || '  AND N.DTSAIDA < TRUNC(SYSDATE) ';
  END IF;

  V_SQL := V_SQL || ' AND N.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
            AND N.CONDVENDA IN (1, 5, 7, 9, 11, 14)';

  RETURN V_SQL;
END;
