CREATE OR REPLACE VIEW VW_INT_C5_EMB_DESMEMBRADAS AS
(
SELECT E.*
FROM VW_INT_C5_EMBPROD E,
(SELECT DISTINCT
             EMB.CODPROD,
             EMB.CODFILIAL
      FROM VW_INT_C5_EMBPROD EMB,
           (SELECT *
            FROM VW_INT_C5_OBTER_FILIAIS_C5) F
      WHERE F.CODFILIAL = EMB.CODFILIAL
      GROUP BY EMB.CODPROD, EMB.QTUNIT, EMB.CODFILIAL
      HAVING COUNT(EMB.CODAUXILIAR) > 1
     ) PROD
WHERE PROD.CODPROD = E.CODPROD
AND   PROD.CODFILIAL = E.CODFILIAL

/*SELECT E."CODFILIAL",E."DTULALTERINTEGRA",E."DTCADASTRO",E."DTINATIVO",E."CODPROD",E."CODAUXILIAR",E."TAMANHO_EAN",E."DESCRICAO",E."DESCRICAOREDUZIDA",E."PVENDA",E."DTULTALTPVENDA",E."POFERTA",E."POFERTAATAC",E."DTOFERTAINI",E."DTOFERTAFIM",E."DTOFERTAATACINI",E."DTOFERTAATACFIM",E."QTUNIT",E."PRAZOVAL",E."QTMINIMAATACADO",E."PVENDAATAC",E."ENVIABALANCA",E."UNIDADE",E."PESOBRUTO",E."PESOLIQ",E."PESOVARIAVEL",E."ACEITAVENDAFRACAO",E."PERMITEMULTIPLICACAO",E."COMISSAO",E."TIPOEMBALAGEM",E."PRODSEMCODBARRAS",E."CODFORNEC_PROD",E."VOLUME_PROD",E."CODMARCA",E."TIPOMERC",E."CODNCMSH",E."TAMANHO_CODNCMSH",E."DTULTALTER_PROD",E."DTCADASTRO_PROD",E."DTEXCLUSAO_PROD",E."DTULTALTPVENDAATAC",E."ANP",E."DESCANP",E."CODPRODPRINC",E."ATIVO",E."REVENDA",E."CODSEC",E."CODEPTO",E."CODCATEGORIA",E."CODSUBCATEGORIA",E."FORALINHA",E."INDESCALARELEVANTE",E."CNPJFABRICANTE",E."DTALTERC5",E."CODAUXILIARTRIB",E."CODCEST"
FROM VW_INT_C5_EMBPROD E,
     (SELECT DISTINCT
             EMB.CODPROD,
             EMB.CODFILIAL
      FROM VW_INT_C5_EMBPROD EMB,
           (SELECT *
            FROM VW_INT_C5_OBTER_FILIAIS_C5
            WHERE ROWNUM = 1) F
      WHERE F.CODFILIAL = EMB.CODFILIAL
      GROUP BY EMB.CODPROD, EMB.QTUNIT, EMB.CODFILIAL
      HAVING COUNT(EMB.CODAUXILIAR) > 1
     ) PROD
WHERE PROD.CODPROD = E.CODPROD
AND   PROD.CODFILIAL = E.CODFILIAL*/
)
