CREATE OR REPLACE VIEW VW_INT_C5_EMB_DESMEMBRADAS AS
(
SELECT E.*
FROM VW_INT_C5_EMBPROD_MAT E,
(SELECT DISTINCT
             EMB.CODPROD,
             EMB.CODFILIAL
      FROM VW_INT_C5_EMBPROD_MAT EMB,
           (SELECT *
            FROM VW_INT_C5_OBTER_FILIAIS_C5) F
      WHERE F.CODFILIAL = EMB.CODFILIAL
      GROUP BY EMB.CODPROD, EMB.QTUNIT, EMB.CODFILIAL
      HAVING COUNT(EMB.CODAUXILIAR) > 1
	  UNION ALL
  SELECT   DISTINCT EMB_TE.CODPROD,
	                EMB_TE.CODFILIAL
    FROM VW_INT_C5_EMBPROD_MAT EMB_TE,
         (  SELECT   * FROM VW_INT_C5_OBTER_FILIAIS_C5) F
   WHERE F.CODFILIAL = EMB_TE.CODFILIAL
         AND EXISTS (SELECT 1
                       FROM VW_INT_C5_EMBPROD_MAT EMB1
                       WHERE EMB1.CODPROD = EMB_TE.CODPROD
                         AND EMB1.CODFILIAL = EMB_TE.CODFILIAL
                         AND EMB1.CODAUXILIAR <> EMB_TE.CODAUXILIAR
                         AND EMB1.TIPOEMBALAGEM <> EMB_TE.TIPOEMBALAGEM)
   GROUP BY   EMB_TE.CODPROD, EMB_TE.TIPOEMBALAGEM, EMB_TE.CODFILIAL
   HAVING   COUNT (1) = 1
   UNION ALL
 SELECT DISTINCT EQ.CODPROD, EQ.CODFILIAL
   FROM VW_INT_C5_EMBPROD_MAT EQ,
        (SELECT * FROM VW_INT_C5_OBTER_FILIAIS_C5) F,
        (SELECT NVL(VALOR, 'N') VALOR, CODFILIAL
           FROM PCPARAMFILIAL
          WHERE NOME = 'FIL_PRECOPOREMBALAGEM') PRECOEMB
  WHERE F.CODFILIAL = EQ.CODFILIAL
    AND F.CODFILIAL = PRECOEMB.CODFILIAL
    AND PRECOEMB.VALOR = 'S'
    AND NVL(EQ.QTMINIMAATACADO, 1) > 1
    AND EXISTS
  (SELECT 1
           FROM VW_INT_C5_EMBPROD_MAT E1
          WHERE E1.CODPROD = EQ.CODPROD
            AND E1.CODFILIAL = EQ.CODFILIAL
            AND E1.CODAUXILIAR <> EQ.CODAUXILIAR
            AND NVL(E1.QTMINIMAATACADO, 1) <> NVL(EQ.QTMINIMAATACADO, 1))
  GROUP BY EQ.CODPROD, EQ.QTMINIMAATACADO, EQ.CODFILIAL
 HAVING COUNT(1) = 1
     ) PROD
WHERE PROD.CODPROD = E.CODPROD
AND PROD.CODFILIAL IN (SELECT CODFILIAL FROM VW_INT_C5_OBTER_FILIAIS_C5)
--AND PROD.CODFILIAL = E.CODFILIAL
)
