CREATE OR REPLACE TRIGGER TRG_PCPEDIDOTEMPORARIO_GERARID
BEFORE INSERT ON PCPEDIDOTEMPORARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DFSEQ_PCPEDIDOTEMPORARIO.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
