DECLARE
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_INT_C5_ESPECIE_FORMAPGTO';

  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
END;

\

DECLARE
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_INT_C5_FORMAPAGTOEMPRESA';
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
END;

\

CREATE VIEW VW_INT_C5_ESPECIE_FORMAPGTO AS
select especie,
       descricao,
       winthor
from    (SELECT 'D' especie, 'DINHEIRO' descricao, 'D' winthor FROM PCCONSUM
     UNION
     SELECT 'B' especie, 'BOLETO' descricao, 'BK' winthor FROM PCCONSUM
     UNION
     SELECT 'C' especie, 'CHEQUE' descricao, 'CHP' winthor FROM PCCONSUM
     UNION
     SELECT 'C' especie, 'CHEQUE' descricao, 'CHV' winthor FROM PCCONSUM
     UNION
     SELECT 'E' especie, 'CARTAO DE DEBITO' descricao, 'CTD' winthor
       FROM PCCONSUM
     UNION
     SELECT 'N' especie, 'NOTA PROMISSORIA' descricao, 'NP' winthor
       FROM PCCONSUM
     UNION
     SELECT 'R' especie, 'CARTAO DE CREDITO' descricao, 'CTC' winthor
       FROM PCCONSUM
     UNION
     SELECT 'S' especie, 'POS' descricao, 'POS' winthor FROM PCCONSUM
     UNION
     SELECT 'T' especie, 'TICKET PAPEL' descricao, 'TKT' winthor FROM PCCONSUM
     UNION
     SELECT 'U' especie, 'VALE CREDITO' descricao, 'U' winthor FROM PCCONSUM
     UNION
     SELECT 'V' especie, 'CONVENIO' descricao, 'CONV' winthor FROM PCCONSUM
     UNION
     SELECT 'X' especie, 'VALE CREDITO' descricao, 'X' winthor FROM PCCONSUM
     UNION
     SELECT 'I' especie, 'CREDITO FINANCEIRO' descricao, 'CRED' winthor
       FROM PCCONSUM
     UNION
     SELECT 'G' especie, 'CARTEIRA DIGITAL' descricao, 'PIX' winthor FROM PCCONSUM)

\

CREATE VIEW VW_INT_C5_FORMAPAGTOEMPRESA AS
(
  SELECT DISTINCT
    C5.CODFILIALINTEGRACAO NROEMPRESA,
    1 NROSEGMENTO,
    F.CODFINALIZADORA NROFORMAPAGTO,
    (CASE 
		WHEN F.PERTXFIN < 0 THEN F.PERTXFIN * -1
        ELSE 0 
    END) AS PERCJUROMENSAL,
    0 as PERCTAXAADM,
    LEAST(P.NUMDIAS, 999) NRODIASVENCTO,
    'N' SOLICITAVENCTO,
    COALESCE(F.PERMITETROCO, 'N') PERMITETROCO,
    LEAST(NVL(F.VLMINIMO, 0), 999999) VLRMINIMO,
    LEAST(NVL(F.VLMAXIMO, 0), 999999) VLRMAXIMO,
    (CASE
      WHEN f.especie IN ('D',  'CHV', 'CHP' ) THEN
      'S'
      ELSE
      'N'
     END) gerasangria,
    LEAST(O.PRAZOMAXIMOVENDA, 999) PRAZOMAXIMO,
    (CASE
      WHEN COALESCE(O.CARTAO, 'N') = 'S' THEN
      'S'
      ELSE
      'N'
    END) USATEF,
    NVL(F.TIPOJUROS, 'S') AS TIPOCALCULOJUROS,
    NVL(O.PERMITECONTRAVALE, 'N') EMITEVALETROCO,
    NVL(F.IMPRIMEVINCULADO, 'N') EMITECOMPROVANTE,
    'S' ABREGAVETA,
    'N' ALTERNATIVA,
    'T' FATURAMENTO,
    NVL(F.CODCOBINTEGRACAO,F.CODCOB) CODCOB,
    (CASE
      WHEN F.DTINATIVACAO IS NULL THEN
      'S'
      ELSE
      'N'
    END) ATIVO,
    NVL(F.PARCELAINICIOJUROS, 0) NROPARCELAJURO,
    F.VALORMINIMOPARCELA VLRMINIMOPARCELA,
    NVL(F.QTMAXPARCELAS,1) QTMAXPARCELAS,
    CASE WHEN F.VERIFICALIMITE = 'S' THEN 'C' ELSE 'N' END CONTROLELIMITE
  FROM
    VW_INT_C5_ESPECIE_FORMAPGTO VEF,
    MONITORPDVMIDDLE.TB_EMPRESA TBEMP,
    PCFILIAL E,
    PCFINALIZADORA   F,
    PCCOB            O,
    PCPLPAG          P,
    VW_INT_C5_OBTER_FILIAIS_C5 C5,
    (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO  
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA')
             OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTO')
			 OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOBINCARTAO')
    ) D
  WHERE F.ESPECIE = VEF.WINTHOR(+)
    AND   F.CODFILIAL = E.CODIGO
    AND   F.CODCOB = O.CODCOB(+)
    AND   F.CODPLPAG = P.CODPLPAG(+)
    AND   F.CODFILIAL IS NOT NULL
    AND   F.CODFINALIZADORA IS NOT NULL
    AND   E.CODIGO <> '99'
    AND   C5.CODFILIALINTEGRACAO = TBEMP.NROEMPRESA
    AND   F.CODFILIAL = C5.CODFILIAL
    AND   E.CODIGO = C5.CODFILIAL
    AND  (NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(O.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(E.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(P.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)

  UNION ALL

  SELECT DISTINCT
    E.CODFILIALINTEGRACAO NROEMPRESA,
    1 NROSEGMENTO,
    F.CODFINALIZADORA NROFORMAPAGTO,
    (CASE
		WHEN F.PERTXFIN < 0 THEN F.PERTXFIN * -1
		ELSE 0
    END) AS PERCJUROMENSAL,
    0 as PERCTAXAADM,
    LEAST(P.NUMDIAS, 999) NRODIASVENCTO,
    'N' SOLICITAVENCTO,
    COALESCE(F.PERMITETROCO, 'N') PERMITETROCO,
    LEAST(NVL(F.VLMINIMO, 0), 999999) VLRMINIMO,
    LEAST(NVL(F.VLMAXIMO, 0), 999999) VLRMAXIMO,
    (CASE
      WHEN F.ESPECIE IN ('D', 'CHV', 'CHP') THEN
      'S'
      ELSE
      'N'
    END) GERASANGRIA,
    LEAST(O.PRAZOMAXIMOVENDA, 999) PRAZOMAXIMO,
    (CASE
      WHEN COALESCE(O.CARTAO, 'N') = 'S' THEN
      'S'
      ELSE
      'N'
    END) USATEF,
    NVL(F.TIPOJUROS, 'S') AS TIPOCALCULOJUROS,
    NVL(O.PERMITECONTRAVALE, 'N') EMITEVALETROCO,
    NVL(F.IMPRIMEVINCULADO, 'N') EMITECOMPROVANTE,
    'S' ABREGAVETA,
    'N' ALTERNATIVA,
    'T' FATURAMENTO,
    NVL(F.CODCOBINTEGRACAO,F.CODCOB) CODCOB,
    (CASE
      WHEN F.DTINATIVACAO IS NULL THEN
      'S'
      ELSE
      'N'
    END) ATIVO,
    NVL(F.PARCELAINICIOJUROS, 0) NROPARCELAJURO,
    F.VALORMINIMOPARCELA VLRMINIMOPARCELA,
    NVL(F.QTMAXPARCELAS,1) QTMAXPARCELAS,
    CASE WHEN F.VERIFICALIMITE = 'S' THEN 'C' ELSE 'N' END CONTROLELIMITE
  FROM PCFINALIZADORA F,
    --PCFILIAL E,
    (SELECT FIL.*
      FROM PCFILIAL FIL,
      VW_INT_C5_OBTER_FILIAIS_C5 C5
      WHERE FIL.CODIGO = C5.CODFILIAL
    ) E,
    VW_INT_C5_ESPECIE_FORMAPGTO VEF,
    MONITORPDVMIDDLE.TB_EMPRESA TBEMP,
    PCCOB            O,
    PCPLPAG          P,
    (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA')
            OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTO')
			OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOBINCARTAO')
    ) D

  WHERE F.CODFILIAL = '99'
    AND   E.CODIGO <> '99'
    AND   F.CODCOB = O.CODCOB(+)
    AND   F.CODPLPAG = P.CODPLPAG(+)
    AND   F.CODFILIAL IS NOT NULL
    AND   F.CODFINALIZADORA IS NOT NULL
    AND   E.CODFILIALINTEGRACAO = TBEMP.NROEMPRESA
    AND  (NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(O.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(E.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(P.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)


  /*SELECT
  F.CODFILIAL NROEMPRESA,
  1 NROSEGMENTO,
  F.CODFINALIZADORA NROFORMAPAGTO,
  0 PERCJUROMENSAL,
  NVL(F.PERTXFIN, 0) PERCTAXAADM,
  LEAST(P.NUMDIAS, 999) NRODIASVENCTO,
  'N' SOLICITAVENCTO,
  COALESCE(F.PERMITETROCO, 'N') PERMITETROCO,
  LEAST(NVL(F.VLMINIMO, 0), 999999) VLRMINIMO,
  LEAST(NVL(F.VLMAXIMO, 0), 999999) VLRMAXIMO,
  (CASE
  WHEN F.ESPECIE IN ('D', 'BK', 'CHV', 'CHP', 'CTD', 'CTC', 'CRE') THEN
  'S'
  WHEN F.ESPECIE LIKE 'POS%' THEN
  'S'
  ELSE
  'N'
  END) GERASANGRIA,
  LEAST(O.PRAZOMAXIMOVENDA, 999) PRAZOMAXIMO,
  (CASE
  WHEN COALESCE(O.CARTAO, 'N') = 'S' THEN
  'S'
  ELSE
  'N'
  END) USATEF,
  NVL(F.TIPOJUROS, 'S')  TIPOCALCULOJUROS,
  NVL(O.PERMITECONTRAVALE, 'N') EMITEVALETROCO,
  NVL(F.IMPRIMEVINCULADO, 'N') EMITECOMPROVANTE,
  'S' ABREGAVETA,
  'N' ALTERNATIVA,
  'T' FATURAMENTO,
  NVL(F.CODCOBINTEGRACAO,F.CODCOB) CODCOB,
  (CASE
  WHEN F.DTINATIVACAO IS NULL THEN
  'S'
  ELSE
  'N'
  END) ATIVO,
  NVL(F.PARCELAINICIOJUROS, 0) NROPARCELAJURO
  FROM VW_INT_C5_ESPECIE_FORMAPGTO VEF,
  PCFILIAL E,
  PCFINALIZADORA   F,
  PCCOB            O,
  PCPLPAG          P,
  (
  SELECT S.ULTIMAEXECUCAO
  FROM PCCONTROLECONSINCO S
  WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA'
  ) D,
  VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE F.ESPECIE = VEF.WINTHOR(+)
  AND   F.CODFILIAL = E.CODIGO
  AND   F.CODCOB = O.CODCOB(+)
  AND   F.CODPLPAG = P.CODPLPAG(+)
  AND   F.CODFILIAL IS NOT NULL
  AND   F.CODFINALIZADORA IS NOT NULL
  AND   E.CODIGO >= '0'
  AND   E.CODIGO < '99'
  AND   E.CODIGO = C5.CODFILIAL
  AND   LENGTH(TRIM(TRANSLATE(E.CODIGO, '0123456789',' '))) IS NULL
  AND  (NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
  NVL(O.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
  NVL(E.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
  NVL(P.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)*/
)

\

CREATE OR REPLACE VIEW VW_INT_C5_FORMAPAGTOBINCARTAO AS
(
  SELECT F.CODFINALIZADORA NROFORMAPAGTO, 
         F.NUMBINCARTAO NROBINCARTAOTEF,
         'S' ATIVO
  FROM   PCFINALIZADORA F,
         (select min(s.ultimaexecucao) ultimaexecucao
          from pccontroleconsinco s
		  where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA')
		  or    (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTO')
		  or    (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOBINCARTAO')
         ) D
  WHERE F.NUMBINCARTAO IS NOT NULL 
  AND NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
  AND F.DTINATIVACAO IS NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PLPAG AS
(
SELECT D.NROCONDICAOPAGTO,
       P.CODPLPAG IDREF,
       SUBSTR(P.DESCRICAO,1,40) CONDICAOPAGTO,       
       NVL((CASE WHEN ABS(P.PERTXFIM) > 99.99 
            THEN 99.99 * SIGN(P.PERTXFIM)
              ELSE P.PERTXFIM
       END),0) PERCACRESCIMO,
       (CASE
            WHEN P.FORMAPARCELAMENTO = 'T' 
              THEN P.NUMEROPARCELASDIAFIXO
            WHEN P.FORMAPARCELAMENTO = 'V' 
              THEN P.NUMPARCELAS
            ELSE
              0
        END) NROMAXIMOPARCELA,
       P.NUMDIAS NRODIASVENCTO,
       (CASE
            WHEN (NVL(P.STATUS,'A') = 'A' AND NVL(P.USAPLPAGAUTOSERVICO,'N') = 'S')
              THEN 'S'
            ELSE
             'N'
        END) ATIVO
FROM PCPLPAG P,
     PCDEPARAPLPAGC5 D,
     (select min(s.ultimaexecucao) ultimaexecucao
      from pccontroleconsinco s
      where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CONDICAOPAGTO')
      ) DTPADRAO
 WHERE P.CODPLPAG = D.CODPLPAG(+) 
 AND   NVL(P.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PARCELDEPTO AS
(
SELECT
     D.CODPARCEL SEQPARCELA,
     'PARCELA CLASSIFICACAO MERCADOLOGICA' DESCRICAO,
     C5.CODFILIALINTEGRACAO NROEMPRESA,
     'C' TIPO,
     TRUNC(SYSDATE) DTAHORINICIAL,
     TRUNC(SYSDATE) + 2000 DTAHORFINAL,
     DF.CODFINALIZADORA NROFORMAPAGTO,
     --PROD.CODPROD SEQFAMILIA,
     P.SEQFAMILIA,
     D.CODDEPTO,
     D.CODSEC,
     D.CODCATEGORIA,
     D.CODSUBCATEGORIA,
     NVL(F.QTMAXPARCELAS, D.QTMAXPARCELA) NROMAXIMOPARCELA,
     (CASE
        WHEN D.STATUS = 'A' THEN
             'S'
        ELSE 'N'
     END) ATIVO

  FROM PCPARCELDEPTO D,
       PCFINALIZADORA F,
       MONITORPDVMIDDLE.TB_FAMILIA P,
       PCPRODUT PROD,
       PCPARCELDEPTOFINALIZADORA DF,
       VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE DF.CODPARCEL = D.CODPARCEL
  AND D.CODFILIAL = C5.CODFILIAL
  AND P.IDREF = PROD.CODPROD
  AND P.ATIVO = 'S'
  AND ((D.CODDEPTO IS NOT NULL AND D.CODSEC IS NULL AND D.CODDEPTO = PROD.CODEPTO) OR
       (D.CODSEC IS NOT NULL AND D.CODCATEGORIA IS NULL AND D.CODSEC = PROD.CODSEC) OR
       (D.CODCATEGORIA IS NOT NULL AND D.CODSUBCATEGORIA IS NULL AND D.CODCATEGORIA = PROD.CODCATEGORIA) OR
       (D.CODSUBCATEGORIA IS NOT NULL AND D.CODSUBCATEGORIA = PROD.CODSUBCATEGORIA) OR
       (D.CODPROD IS NOT NULL AND D.CODPROD = PROD.CODPROD)
      )   
  AND DF.CODFINALIZADORA = F.CODFINALIZADORA
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BINCARTAO AS
(
SELECT B.CODBINCARTAO SEQBINCARTAO,
       B.NROBININICIAL,
       B.NROBINFINAL,
       B.CODREDE,
       B.CODBANDEIRA,
       B.TIPO,       
       DECODE(B.DTEXCLUSAO, NULL, 'S', 'N') ATIVO
  FROM PCBINCARTAO B
)
