CREATE OR REPLACE VIEW VW_INT_C5_ESPECIE_FORMAPGTO AS
select especie,
       descricao,
       winthor
from    (SELECT 'D' especie, 'DINHEIRO' descricao, 'D' winthor FROM DUAL
     UNION
     SELECT 'B' especie, 'BOLETO' descricao, 'BK' winthor FROM DUAL
     UNION
     SELECT 'C' especie, 'CHEQUE' descricao, 'CHP' winthor FROM DUAL
     UNION
     SELECT 'C' especie, 'CHEQUE' descricao, 'CHV' winthor FROM DUAL
     UNION
     SELECT 'E' especie, 'CARTAO DE DEBITO' descricao, 'CTD' winthor
       FROM DUAL
     UNION
     SELECT 'N' especie, 'NOTA PROMISSORIA' descricao, 'NP' winthor
       FROM dual
     UNION
     SELECT 'R' especie, 'CARTAO DE CREDITO' descricao, 'CTC' winthor
       FROM DUAL
     UNION
     SELECT 'S' especie, 'POS' descricao, 'POS' winthor FROM DUAL
     UNION
     SELECT 'T' especie, 'TICKET PAPEL' descricao, 'TKT' winthor FROM DUAL
     UNION
     SELECT 'U' especie, 'VALE CREDITO' descricao, 'U' winthor FROM DUAL
     UNION
     SELECT 'V' especie, 'CONVENIO' descricao, 'CONV' winthor FROM DUAL
     UNION
     SELECT 'X' especie, 'VALE CREDITO' descricao, 'X' winthor FROM DUAL
     UNION
     SELECT 'I' especie, 'CREDITO FINANCEIRO' descricao, 'CRED' winthor
       FROM DUAL
     UNION
     SELECT 'G' especie, 'CARTEIRA DIGITAL' descricao, 'PIX' winthor FROM DUAL)

\

CREATE OR REPLACE VIEW VW_INT_C5_FORMAPAGTOEMPRESA AS
(
  SELECT DISTINCT
    C5.CODFILIALINTEGRACAO NROEMPRESA,
    1 NROSEGMENTO,
    F.CODFINALIZADORA NROFORMAPAGTO,
    0 PERCJUROMENSAL,
    NVL(F.PERTXFIN, 0) PERCTAXAADM,
    LEAST(P.NUMDIAS, 999) NRODIASVENCTO,
    'N' SOLICITAVENCTO,
    COALESCE(F.PERMITETROCO, 'N') PERMITETROCO,
    LEAST(NVL(F.VLMINIMO, 0), 999999) VLRMINIMO,
    LEAST(NVL(F.VLMAXIMO, 0), 999999) VLRMAXIMO,
    (CASE
      WHEN F.ESPECIE IN ('D', 'BK', 'CHV', 'CHP', 'CTD', 'CTC', 'CRE') THEN
      'S'
      WHEN F.ESPECIE LIKE 'POS%' THEN
      'S'
      ELSE
      'N'
    END) GERASANGRIA,
    LEAST(O.PRAZOMAXIMOVENDA, 999) PRAZOMAXIMO,
    (CASE
      WHEN COALESCE(O.CARTAO, 'N') = 'S' THEN
      'S'
      ELSE
      'N'
    END) USATEF,
    NVL(F.TIPOJUROS, 'S')  TIPOCALCULOJUROS,
    NVL(O.PERMITECONTRAVALE, 'N') EMITEVALETROCO,
    NVL(F.IMPRIMEVINCULADO, 'N') EMITECOMPROVANTE,
    'S' ABREGAVETA,
    'N' ALTERNATIVA,
    'T' FATURAMENTO,
    NVL(F.CODCOBINTEGRACAO,F.CODCOB) CODCOB,
    (CASE
      WHEN F.DTINATIVACAO IS NULL THEN
      'S'
      ELSE
      'N'
    END) ATIVO,
    NVL(F.PARCELAINICIOJUROS, 0) NROPARCELAJURO,
    F.VALORMINIMOPARCELA VLRMINIMOPARCELA,
    NVL(F.QTMAXPARCELAS,1) QTMAXPARCELAS,
    F.VERIFICALIMITE CONTROLELIMITE
  FROM
    VW_INT_C5_ESPECIE_FORMAPGTO VEF,
    MONITORPDVMIDDLE.TB_EMPRESA TBEMP,
    PCFILIAL E,
    PCFINALIZADORA   F,
    PCCOB            O,
    PCPLPAG          P,
    VW_INT_C5_OBTER_FILIAIS_C5 C5,
    (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO  
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA')
             OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTO')
    ) D
  WHERE F.ESPECIE = VEF.WINTHOR(+)
    AND   F.CODFILIAL = E.CODIGO
    AND   F.CODCOB = O.CODCOB(+)
    AND   F.CODPLPAG = P.CODPLPAG(+)
    AND   F.CODFILIAL IS NOT NULL
    AND   F.CODFINALIZADORA IS NOT NULL
    AND   E.CODIGO <> '99'
    AND   C5.CODFILIALINTEGRACAO = TBEMP.NROEMPRESA
    AND   F.CODFILIAL = C5.CODFILIAL
    AND   E.CODIGO = C5.CODFILIAL
    AND   LENGTH(TRIM(TRANSLATE(E.CODIGO, '0123456789',' '))) IS NULL
    AND  (NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(O.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(E.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(P.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)

  UNION ALL

  SELECT DISTINCT
    E.CODFILIALINTEGRACAO NROEMPRESA,
    1 NROSEGMENTO,
    F.CODFINALIZADORA NROFORMAPAGTO,
    0 PERCJUROMENSAL,
    NVL(F.PERTXFIN, 0) PERCTAXAADM,
    LEAST(P.NUMDIAS, 999) NRODIASVENCTO,
    'N' SOLICITAVENCTO,
    COALESCE(F.PERMITETROCO, 'N') PERMITETROCO,
    LEAST(NVL(F.VLMINIMO, 0), 999999) VLRMINIMO,
    LEAST(NVL(F.VLMAXIMO, 0), 999999) VLRMAXIMO,
    (CASE
      WHEN F.ESPECIE IN ('D', 'CHV', 'CHP') THEN
      'S'
      ELSE
      'N'
    END) GERASANGRIA,
    LEAST(O.PRAZOMAXIMOVENDA, 999) PRAZOMAXIMO,
    (CASE
      WHEN COALESCE(O.CARTAO, 'N') = 'S' THEN
      'S'
      ELSE
      'N'
    END) USATEF,
    NVL(F.TIPOJUROS, 'S')  TIPOCALCULOJUROS,
    NVL(O.PERMITECONTRAVALE, 'N') EMITEVALETROCO,
    NVL(F.IMPRIMEVINCULADO, 'N') EMITECOMPROVANTE,
    'S' ABREGAVETA,
    'N' ALTERNATIVA,
    'T' FATURAMENTO,
    NVL(F.CODCOBINTEGRACAO,F.CODCOB) CODCOB,
    (CASE
      WHEN F.DTINATIVACAO IS NULL THEN
      'S'
      ELSE
      'N'
    END) ATIVO,
    NVL(F.PARCELAINICIOJUROS, 0) NROPARCELAJURO,
    F.VALORMINIMOPARCELA VLRMINIMOPARCELA,
    NVL(F.QTMAXPARCELAS,1) QTMAXPARCELAS,
    F.VERIFICALIMITE CONTROLELIMITE
  FROM PCFINALIZADORA F,
    --PCFILIAL E,
    (SELECT FIL.*
      FROM PCFILIAL FIL,
      VW_INT_C5_OBTER_FILIAIS_C5 C5
      WHERE FIL.CODIGO = C5.CODFILIAL
    ) E,
    VW_INT_C5_ESPECIE_FORMAPGTO VEF,
    MONITORPDVMIDDLE.TB_EMPRESA TBEMP,
    PCCOB            O,
    PCPLPAG          P,
    (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA')
            OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTO')
    ) D

  WHERE F.CODFILIAL = '99'
    AND   E.CODIGO <> '99'
    AND   F.CODCOB = O.CODCOB(+)
    AND   F.CODPLPAG = P.CODPLPAG(+)
    AND   F.CODFILIAL IS NOT NULL
    AND   F.CODFINALIZADORA IS NOT NULL
    AND   E.CODFILIALINTEGRACAO = TBEMP.NROEMPRESA
    AND  (NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(O.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(E.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(P.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)


  /*SELECT
  F.CODFILIAL NROEMPRESA,
  1 NROSEGMENTO,
  F.CODFINALIZADORA NROFORMAPAGTO,
  0 PERCJUROMENSAL,
  NVL(F.PERTXFIN, 0) PERCTAXAADM,
  LEAST(P.NUMDIAS, 999) NRODIASVENCTO,
  'N' SOLICITAVENCTO,
  COALESCE(F.PERMITETROCO, 'N') PERMITETROCO,
  LEAST(NVL(F.VLMINIMO, 0), 999999) VLRMINIMO,
  LEAST(NVL(F.VLMAXIMO, 0), 999999) VLRMAXIMO,
  (CASE
  WHEN F.ESPECIE IN ('D', 'BK', 'CHV', 'CHP', 'CTD', 'CTC', 'CRE') THEN
  'S'
  WHEN F.ESPECIE LIKE 'POS%' THEN
  'S'
  ELSE
  'N'
  END) GERASANGRIA,
  LEAST(O.PRAZOMAXIMOVENDA, 999) PRAZOMAXIMO,
  (CASE
  WHEN COALESCE(O.CARTAO, 'N') = 'S' THEN
  'S'
  ELSE
  'N'
  END) USATEF,
  NVL(F.TIPOJUROS, 'S')  TIPOCALCULOJUROS,
  NVL(O.PERMITECONTRAVALE, 'N') EMITEVALETROCO,
  NVL(F.IMPRIMEVINCULADO, 'N') EMITECOMPROVANTE,
  'S' ABREGAVETA,
  'N' ALTERNATIVA,
  'T' FATURAMENTO,
  NVL(F.CODCOBINTEGRACAO,F.CODCOB) CODCOB,
  (CASE
  WHEN F.DTINATIVACAO IS NULL THEN
  'S'
  ELSE
  'N'
  END) ATIVO,
  NVL(F.PARCELAINICIOJUROS, 0) NROPARCELAJURO
  FROM VW_INT_C5_ESPECIE_FORMAPGTO VEF,
  PCFILIAL E,
  PCFINALIZADORA   F,
  PCCOB            O,
  PCPLPAG          P,
  (
  SELECT S.ULTIMAEXECUCAO
  FROM PCCONTROLECONSINCO S
  WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FORMAPAGTOEMPRESA'
  ) D,
  VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE F.ESPECIE = VEF.WINTHOR(+)
  AND   F.CODFILIAL = E.CODIGO
  AND   F.CODCOB = O.CODCOB(+)
  AND   F.CODPLPAG = P.CODPLPAG(+)
  AND   F.CODFILIAL IS NOT NULL
  AND   F.CODFINALIZADORA IS NOT NULL
  AND   E.CODIGO >= '0'
  AND   E.CODIGO < '99'
  AND   E.CODIGO = C5.CODFILIAL
  AND   LENGTH(TRIM(TRANSLATE(E.CODIGO, '0123456789',' '))) IS NULL
  AND  (NVL(F.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
  NVL(O.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
  NVL(E.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
  NVL(P.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)*/
)

