CREATE OR REPLACE VIEW SQL_NFE_RODAPE_ENTRADA_COMP AS 
SELECT E.NUMTRANSENT AS NUM_TRANSACAO,
       DECODE(NVL(E.FINALIDADENFE, 'X'), 'A', SUM(NVL(B.VLTOTPRODAJUSTE, E.VLTOTBRUTOPRODAJUSTE)), MAX(E.VLTOTAL)) AS VALOR_TOTAL_PRODUTOS,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '1',
                  NVL(B.VLBASE,
                      0),
                  0)) BASE_ICMS,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '2',
                  NVL(B.VLBASE,
                      0),
                  0)) BASE_IPI,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '2',0,
                  DECODE(NVL(B.VLICMS,
                             0),
                         0,
                         NVL(B.VLBASE,
                             0) * NVL(B.ALIQUOTA,
                                      0) / 100,
                         NVL(B.VLICMS,
                             0)))) VALOR_ICMS,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '2',
                  DECODE(NVL(B.VLICMS,
                             0),
                         0,
                         NVL(B.VLBASE,
                             0) * NVL(B.ALIQUOTA,
                                      0) / 100,
                         NVL(B.VLICMS,
                             0)),
                  0)) VALOR_IPI,
       MAX(E.VLTOTAL) VALOR_TOTAL,
       MAX(E.BASEICST) BASE_ST,
       MAX(E.VLST) VALOR_ST,
       MAX(NVL(E.VLOUTRAS,
               0)) AS VALOR_OUTRO,
       E.FINALIDADENFE,
       MAX(NVL(E.VLFRETE,0)) AS VALOR_FRETE,
       MAX(NVL(E.VLDESCONTO,0)) AS VALOR_DESCONTO
FROM   PCNFBASE B,
       PCNFENT  E
WHERE  B.NUMTRANSENT = E.NUMTRANSENT
AND    E.ESPECIE IN('NF','NE','EI')
GROUP BY E.NUMTRANSENT,E.FINALIDADENFE,E.VLTOTAL