BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO ADD (CODBANCO_TEMP VARCHAR2(5))';

  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CODBANCO_TEMP = TO_CHAR(CODBANCO)';
  
  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CODBANCO = NULL';
  
  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO MODIFY ( CODBANCO VARCHAR2(5))';
  
  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CODBANCO = CODBANCO_TEMP';

  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO DROP COLUMN CODBANCO_TEMP';
  
  
  
  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO ADD (CODAGENCIA_TEMP VARCHAR2(10))';

  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CODAGENCIA_TEMP = TO_CHAR(CODAGENCIA)';
  
  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CODAGENCIA = NULL';
  
  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO MODIFY ( CODAGENCIA VARCHAR2(10))';
  
  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CODAGENCIA = CODAGENCIA_TEMP';

  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO DROP COLUMN CODAGENCIA_TEMP';
  
  
  
  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO ADD (CNPJIPEF_TEMP VARCHAR2(14))';

  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CNPJIPEF_TEMP = TO_CHAR(CNPJIPEF)';
  
  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CNPJIPEF = NULL';
  
  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO MODIFY ( CNPJIPEF VARCHAR2(14))';
  
  EXECUTE IMMEDIATE 'UPDATE PCMANIFESTOELETRONICOPGTO SET CNPJIPEF = CNPJIPEF_TEMP';

  EXECUTE IMMEDIATE 'ALTER TABLE PCMANIFESTOELETRONICOPGTO DROP COLUMN CNPJIPEF_TEMP';
END;