CREATE OR REPLACE FUNCTION LISTA_DE_NUMEROS(LISTA IN VARCHAR2)
   RETURN TABELA_INTEIRO IS
   TABELA_NUMEROS TABELA_INTEIRO;
   NOVO_NUMERO    NUMBER;
   L_CURSOR       SYS_REFCURSOR;
BEGIN
   TABELA_NUMEROS := TABELA_INTEIRO();

   OPEN L_CURSOR FOR 'SELECT ' || REPLACE(LISTA,
                                          ',',
                                          ' FROM DUAL UNION SELECT ') || ' FROM DUAL';
   LOOP
      FETCH L_CURSOR
         INTO NOVO_NUMERO;

      EXIT WHEN L_CURSOR%NOTFOUND;
      TABELA_NUMEROS.EXTEND;
      TABELA_NUMEROS(TABELA_NUMEROS.COUNT) := ARRAY_INTEIRO(NUMEROS => NOVO_NUMERO);
   END LOOP;

   CLOSE L_CURSOR;

   RETURN TABELA_NUMEROS;
END; 