CREATE OR REPLACE VIEW VW_INT_C5_GIFTCARD AS
(
SELECT  A.SEQDOCTO,
        A.NROEMPRESA,
        A.NROCHECKOUT,
        B.NROCARTAO NUMGIFTCARD,
        'NOTAFISCAL' NUMSERIEEQUIP,
        TRUNC(SYSDATE) DATA,
        TO_CHAR(A.DTAMOVIMENTO, 'YYYY-MM-DD') DTABERTURA,
        A.SEQUSUARIO CODFUNCCX,
        1 CODCLI,
        B.VALOR VALOR,
        A.COO,
        FNC_INT_C5_CODUSUR(A.SEQUSUARIO) CODUSUR
  FROM  MONITORPDVMIDDLE.TB_DOCTO A, MONITORPDVMIDDLE.TB_DOCTOPAGTO B, MONITORPDVMIDDLE.TB_CREDITOCUPOM C 
 WHERE  0 = 0
   AND  A.REPLICACAO = 'P'
   AND  A.SEQDOCTO = B.SEQDOCTO
   AND  A.NROEMPRESA = B.NROEMPRESA
   AND  A.NROCHECKOUT = B.NROCHECKOUT
   AND  B.NROCREDITOCUPOM = C.NROCREDITOCUPOM
   AND  C.ATIVO = 'S'
   AND  A.ESPECIE IN ('VC')
)