CREATE OR REPLACE VIEW VW_INT_C5_GIFTCARD AS
(
SELECT  A.SEQDOCTO,
        A.NROEMPRESA,
        A.NROCHECKOUT,
        B.NROCREDITOCUPOM NUMGIFTCARD,
        'NOTAFISCAL' NUMSERIEEQUIP,
        TRUNC(SYSDATE) DATA,
        A.SEQUSUARIO CODFUNCCX,
        1 CODCLI,
        B.VALOR VALOR,
        FNC_INT_C5_CODUSUR(A.SEQUSUARIO) CODUSUR
  FROM  MONITORPDVMIDDLE.TB_DOCTO A, MONITORPDVMIDDLE.TB_DOCTOPAGTO B
 WHERE  A.REPLICACAO = 'P'
   AND  A.SEQDOCTO = B.SEQDOCTO
   AND  A.NROEMPRESA = B.NROEMPRESA
   AND  A.NROCHECKOUT = B.NROCHECKOUT
   AND  A.ESPECIE IN ('GC')
)
