CREATE OR REPLACE TYPE TIPO_CONFIG_EMAIL AS OBJECT
(
   USUARIO        VARCHAR2(100),
   SENHA          VARCHAR2(100),
   DOMINIO        VARCHAR2(100),
   NOME_REMENTE   VARCHAR2(100),
   EMAIL_REMENTE   VARCHAR2(100),
   SERVIDOR_SMTP  VARCHAR2(100),
   PORTA          NUMBER,
   ATIVAR_SSL     VARCHAR2(1),
   EMAIL_RESPOSTA VARCHAR2(100),
   EMAIL_COPIA    VARCHAR2(100),
   ATIVAR_TLS     VARCHAR2(1),  
  CONSTRUCTOR FUNCTION TIPO_CONFIG_EMAIL(SELF IN OUT NOCOPY TIPO_CONFIG_EMAIL)
    RETURN SELF AS RESULT
)
