DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_CTE_DOC_ANTERIOR'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_CTE_DOC_ANTERIOR';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_CTE_DOC_ANTERIOR AS OBJECT
(
    CHAVE_CTE_REF          varchar2(45),
    CNPJCPF_CTE_REF    varchar2(18),
    IE_CTE_REF            varchar2(20),
    UF_CTE_REF            varchar2(2),
    RAZAOSOCIAL_CTE_REF         varchar2(60),
    TIPODOC_CTE_REF             varchar2(2),
    SERIEDOC_CTE_REF    varchar2(3),
    SUBSERIE_CTE_REF          varchar2(2),
    NUMDOC_CTE_REF    varchar2(20),
    DTEMISSAO_CTE_REF          DATE
);
\
CREATE OR REPLACE TYPE TABELA_CTE_DOC_ANTERIOR IS TABLE OF TIPO_CTE_DOC_ANTERIOR;