DECLARE
  vSQL VARCHAR2(4000);
  vNOMETABELATEMP VARCHAR2(50);
  vNOMETABELATEMP_FILIAL VARCHAR2(50);
  
  PROCEDURE ADICIONAR_COLUNA_VLFECPBONIFIC(pNOMETABELATEMP IN VARCHAR2) IS
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE '|| pNOMETABELATEMP ||' ADD VLFECPBONIFIC NUMBER(18,6)';
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;    
  END;
  
  PROCEDURE ADICIONAR_COLUNAS_COMISSAO(pNOMETABELATEMP IN VARCHAR2) IS
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE '|| pNOMETABELATEMP ||' ADD (VLSTCOMISSAO NUMBER(18, 6), VLIPICOMISSAO NUMBER(18, 6), VLFECPCOMISSAO NUMBER(18, 6))';
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;    
  END;
  
BEGIN
  /* Migração da rotina 300 - PKG_GESTAOMETA Componente osTbTemp_GESTAOMETA */
  vNOMETABELATEMP := 'PCGMMETAGLOBALTEMP';
  
  FOR LINHA IN (SELECT CODIGO FROM PCFILIAL WHERE CODIGO <> '99' ORDER BY 1) LOOP
    vNOMETABELATEMP_FILIAL := vNOMETABELATEMP||'_'|| LINHA.CODIGO;
    
    BEGIN
      vSQL := 'CREATE GLOBAL TEMPORARY TABLE '|| vNOMETABELATEMP_FILIAL ||' ON COMMIT PRESERVE ROWS AS SELECT * FROM PCGMMETAGLOBALTEMP WHERE 1 = 2';
      EXECUTE IMMEDIATE vSQL;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
    
    BEGIN
      vSQL := 'CREATE INDEX '|| vNOMETABELATEMP_FILIAL ||'_IDX1 ON '|| vNOMETABELATEMP_FILIAL ||'(DATA)';
      EXECUTE IMMEDIATE vSQL;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;      
    
    ADICIONAR_COLUNA_VLFECPBONIFIC(vNOMETABELATEMP_FILIAL);
    ADICIONAR_COLUNAS_COMISSAO(vNOMETABELATEMP_FILIAL);
  END LOOP;
  
  ADICIONAR_COLUNA_VLFECPBONIFIC(vNOMETABELATEMP);
  ADICIONAR_COLUNAS_COMISSAO(vNOMETABELATEMP);
END;