DECLARE
  vSQL VARCHAR2(4000);
  vNOMETABELATEMP VARCHAR2(50);
BEGIN
  /* Migração da rotina 300 - PKG_GESTAOMETA Componente osTbTemp_GESTAOMETA */
  FOR LINHA IN (SELECT CODIGO FROM PCFILIAL WHERE CODIGO <> '99' ORDER BY 1) LOOP
    vNOMETABELATEMP := 'PCGMMETAGLOBALTEMP_'|| LINHA.CODIGO;
    
    BEGIN
      vSQL := 'CREATE GLOBAL TEMPORARY TABLE '|| vNOMETABELATEMP ||' ON COMMIT PRESERVE ROWS AS SELECT * FROM PCGMMETAGLOBALTEMP WHERE 1 = 2';
      EXECUTE IMMEDIATE vSQL;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
    
    BEGIN
      vSQL := 'CREATE INDEX '|| vNOMETABELATEMP ||'_IDX1 ON '|| vNOMETABELATEMP ||'(DATA)';
      EXECUTE IMMEDIATE vSQL;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;      
    
    BEGIN
      vSQL := 'ALTER TABLE '|| vNOMETABELATEMP ||' ADD VLFECPBONIFIC NUMBER(18,6)';
      EXECUTE IMMEDIATE vSQL;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
 
  END LOOP;
END;