CREATE OR REPLACE TRIGGER trg_c5_dt_tribut
 BEFORE INSERT OR UPDATE
        ON pctribut
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tribpiscofins
 BEFORE INSERT OR UPDATE
        ON pctribpiscofins
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
   :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

   IF (UPDATING) THEN
      UPDATE PCPRODUT SET
             DTALTERC5 = CURRENT_TIMESTAMP
      WHERE CODPROD IN (SELECT DISTINCT CODPROD 
                        FROM PCTABPR 
                        WHERE CODTRIBPISCOFINS = :OLD.CODTRIBPISCOFINS);
   END IF;
END;
     
\

CREATE OR REPLACE TRIGGER trg_c5_dt_tabpr
 BEFORE INSERT OR UPDATE
        ON pctabpr
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
    
  IF (UPDATING) AND (:NEW.CODTRIBPISCOFINS <> :OLD.CODTRIBPISCOFINS) THEN

      UPDATE PCPRODUT SET
             DTALTERC5 = CURRENT_TIMESTAMP
      WHERE CODPROD = :OLD.CODPROD;

  END IF;                
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tabtrib
 BEFORE INSERT OR UPDATE
        ON pctabtrib
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_produt
 BEFORE INSERT OR UPDATE
        ON pcprodut
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;        

\

CREATE OR REPLACE TRIGGER trg_c5_dt_prodfilial
 BEFORE INSERT OR UPDATE
        ON pcprodfilial
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;       

\

CREATE OR REPLACE TRIGGER trg_c5_dt_finalizadora
 BEFORE INSERT OR UPDATE
        ON pcfinalizadora
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;  

\

CREATE OR REPLACE TRIGGER trg_c5_dt_cob
 BEFORE INSERT OR UPDATE
        ON pccob
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;  

\

CREATE OR REPLACE TRIGGER trg_c5_dt_plpag
 BEFORE INSERT OR UPDATE
        ON pcplpag
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;   

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcembalagem
 BEFORE INSERT OR UPDATE
        ON pcembalagem
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 
  
\

CREATE OR REPLACE TRIGGER trg_c5_dt_empr
 BEFORE INSERT OR UPDATE
        ON pcempr
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_filial
 BEFORE INSERT OR UPDATE
        ON pcfilial
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;   

\

CREATE OR REPLACE TRIGGER trg_c5_dt_client
 BEFORE INSERT OR UPDATE
        ON pcclient
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;    

\

CREATE OR REPLACE TRIGGER trg_c5_dt_marca
 BEFORE INSERT OR UPDATE
        ON pcmarca
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;              

\

CREATE OR REPLACE TRIGGER trg_c5_dt_depto
 BEFORE INSERT OR UPDATE
        ON pcdepto
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_secao
 BEFORE INSERT OR UPDATE
        ON pcsecao
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_categoria
 BEFORE INSERT OR UPDATE
        ON pccategoria
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;   

\

CREATE OR REPLACE TRIGGER trg_c5_dt_subcategoria
 BEFORE INSERT OR UPDATE
        ON pcsubcategoria
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;     

\

CREATE OR REPLACE TRIGGER trg_c5_dt_cfo
 BEFORE INSERT OR UPDATE
        ON pccfo
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_ncm
 BEFORE INSERT OR UPDATE
        ON pcncm
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tribncmfilial
 BEFORE INSERT OR UPDATE
        ON pctribncmfilial
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_regiao
 BEFORE INSERT OR UPDATE
        ON pcregiao
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_desconto561
 BEFORE INSERT OR UPDATE
        ON pcdesconto
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcprecoprom
 BEFORE INSERT OR UPDATE
        ON pcprecoprom
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\
                                    
CREATE OR REPLACE TRIGGER trg_c5_dt_pcofertaprogramadac
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadac
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\
                                    
CREATE OR REPLACE TRIGGER trg_c5_dt_pcofertaprogramadai
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadai
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcpromc
 BEFORE INSERT OR UPDATE
        ON pcpromc
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcpromi
 BEFORE INSERT OR UPDATE
        ON pcpromi
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_programadac_hist
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadac_hist
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_programadai_hist
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadai_hist
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;

