DECLARE
  vnContSeq NUMBER;
  vScript VARCHAR2(4000);
BEGIN
  BEGIN
    SELECT COUNT(1)
    INTO vnContSeq
    FROM all_triggers A
    WHERE trigger_name = 'TRG_C5_DT_DESC561LOG';
  END;
     
  IF vnContSeq > 0  THEN
     vScript := ' DROP TRIGGER TRG_C5_DT_DESC561LOG';
     execute immediate vscript;  
  END IF;
  BEGIN
    SELECT COUNT(1)
    INTO vnContSeq
    FROM all_triggers A
    WHERE trigger_name = 'TRG_C5_DT_PRECOPROMLOG';
  END;
     
  IF vnContSeq > 0  THEN
     vScript := ' DROP TRIGGER TRG_C5_DT_PRECOPROMLOG';
     execute immediate vscript;  
  END IF;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tribut
 BEFORE INSERT OR UPDATE
        ON pctribut
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tribpiscofins
 BEFORE INSERT OR UPDATE
        ON pctribpiscofins
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
   :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

   IF (UPDATING) THEN
      UPDATE PCPRODUT SET
             DTALTERC5 = CURRENT_TIMESTAMP
      WHERE CODPROD IN (SELECT DISTINCT CODPROD 
                        FROM PCTABPR 
                        WHERE CODTRIBPISCOFINS = :OLD.CODTRIBPISCOFINS);
   END IF;
END;
     
\

CREATE OR REPLACE TRIGGER trg_c5_dt_tabpr
 BEFORE INSERT OR UPDATE
        ON pctabpr
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE vCont  NUMBER;
BEGIN
  
  vCont := 0;
  SELECT COUNT(1)
  INTO vCont
  FROM PCPARAMFILIAL
  WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
  AND CODFILIAL IN (SELECT CODFILIAL FROM VW_INT_C5_OBTER_FILIAIS_C5)
  AND VALOR = :OLD.NUMREGIAO;
  IF (vCont > 0) THEN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
	
	UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
    WHERE CODPROD = :OLD.CODPROD;
  END IF;

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD));*/
    
  /*IF (UPDATING) AND (:NEW.CODTRIBPISCOFINS <> :OLD.CODTRIBPISCOFINS) THEN

      UPDATE PCPRODUT SET
             DTALTERC5 = CURRENT_TIMESTAMP
      WHERE CODPROD = :OLD.CODPROD;

  END IF;                */
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tabtrib
 BEFORE INSERT OR UPDATE
        ON pctabtrib
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

    UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
    WHERE CODPROD = :OLD.CODPROD;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_produt
 BEFORE INSERT OR UPDATE
        ON pcprodut
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;        

\

CREATE OR REPLACE TRIGGER trg_c5_dt_prodfilial
 BEFORE INSERT OR UPDATE
        ON pcprodfilial
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;       

\

CREATE OR REPLACE TRIGGER trg_c5_dt_finalizadora
 BEFORE INSERT OR UPDATE
        ON pcfinalizadora
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;  

\

CREATE OR REPLACE TRIGGER trg_c5_dt_cob
 BEFORE INSERT OR UPDATE
        ON pccob
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;  

\

CREATE OR REPLACE TRIGGER trg_c5_dt_plpag
 BEFORE INSERT OR UPDATE
        ON pcplpag
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;   

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcembalagem
 BEFORE INSERT OR UPDATE
        ON pcembalagem
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

    UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
    WHERE CODPROD = :OLD.CODPROD;

    /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
    WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                            FROM PCFORMPROD 
                                                                            WHERE CODPRODMP = :OLD.CODPROD));
    UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
    WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                            FROM PCFORMPROD 
                                                                            WHERE CODPRODMP = :OLD.CODPROD));  */                                                                          
END; 
  
\

CREATE OR REPLACE TRIGGER trg_c5_dt_empr
 BEFORE INSERT OR UPDATE
        ON pcempr
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_filial
 BEFORE INSERT OR UPDATE
        ON pcfilial
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;   

\

CREATE OR REPLACE TRIGGER trg_c5_dt_client
 BEFORE INSERT OR UPDATE
        ON pcclient
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;    

\

CREATE OR REPLACE TRIGGER trg_c5_dt_marca
 BEFORE INSERT OR UPDATE
        ON pcmarca
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;              

\

CREATE OR REPLACE TRIGGER trg_c5_dt_depto
 BEFORE INSERT OR UPDATE
        ON pcdepto
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_secao
 BEFORE INSERT OR UPDATE
        ON pcsecao
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_categoria
 BEFORE INSERT OR UPDATE
        ON pccategoria
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;   

\

CREATE OR REPLACE TRIGGER trg_c5_dt_subcategoria
 BEFORE INSERT OR UPDATE
        ON pcsubcategoria
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;     

\

CREATE OR REPLACE TRIGGER trg_c5_dt_cfo
 BEFORE INSERT OR UPDATE
        ON pccfo
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_ncm
 BEFORE INSERT OR UPDATE
        ON pcncm
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_tribncmfilial
 BEFORE INSERT OR UPDATE
        ON pctribncmfilial
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_regiao
 BEFORE INSERT OR UPDATE
        ON pcregiao
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
 
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_desconto561
 BEFORE INSERT OR UPDATE
        ON pcdesconto
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*Trazer todos os registros de cesta porque na 561 a politica pode ser criado sem ser informado um produto*/
  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);*/
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcprecoprom
 BEFORE INSERT OR UPDATE
        ON pcprecoprom
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);*/

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD));
  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD));*/                                                                          
END; 

\
                                    
CREATE OR REPLACE TRIGGER trg_c5_dt_pcofertaprogramadac
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadac
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);*/

  /*Trazer todos os registros de cesta porque nao existe referencia de produto nessa tabela*/
  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);*/
END; 

\
                                    
CREATE OR REPLACE TRIGGER trg_c5_dt_pcofertaprogramadai
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadai
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
   :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*UPDATE PCEMBALAGEM SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODAUXILIAR = :OLD.CODAUXILIAR;*/

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD));
  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD)); */                                                                         
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcpromc
 BEFORE INSERT OR UPDATE
        ON pcpromc
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_pcpromi
 BEFORE INSERT OR UPDATE
        ON pcpromi
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_programadac_hist
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadac_hist
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*Trazer todos os registros de cesta porque nao existe referencia de produto nessa tabela*/
  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);*/
END; 

\

CREATE OR REPLACE TRIGGER trg_c5_dt_programadai_hist
 BEFORE INSERT OR UPDATE
        ON pcofertaprogramadai_hist
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

 /* UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD));

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB IN(SELECT CODPRODACAB 
                                                                          FROM PCFORMPROD 
                                                                          WHERE CODPRODMP = :OLD.CODPROD));*/                                                                          
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_excecaocafiscais
 BEFORE INSERT OR UPDATE
        ON pcexcecaocadastrosfiscais
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
  
  UPDATE PCCONSOLIDATRIBUTACAO SET DTALTERC5 = CURRENT_TIMESTAMP;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_cest
 BEFORE INSERT OR UPDATE
        ON PCCESTPRODUTO
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD = :OLD.CODPROD;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_formprod
 BEFORE INSERT OR UPDATE
        ON PCFORMPROD
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD = :OLD.CODPRODMP;*/

  UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB = :OLD.CODPRODACAB);

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB = :OLD.CODPRODACAB);
  
  UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD = :OLD.CODPRODACAB;

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD = :OLD.CODPRODACAB;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
  BEGIN
    ROLLBACK;
  END;
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_precocestac
 BEFORE INSERT OR UPDATE
        ON PCPRECOCESTAC
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  /*UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD);*/

  UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB = :OLD.CODPRODACAB);

  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB = :OLD.CODPRODACAB);
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_precocestai
 BEFORE INSERT OR UPDATE
        ON PCPRECOCESTAI
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;

  UPDATE PCPRODUT SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB = :OLD.CODPRODACAB);
  
  UPDATE PCTABPR SET DTALTERC5 = CURRENT_TIMESTAMP
  WHERE CODPROD IN (SELECT CODPRODMP FROM PCFORMPROD WHERE CODPRODACAB = :OLD.CODPRODACAB);
END;

\

CREATE OR REPLACE TRIGGER trg_c5_dt_descontofidelidade
 BEFORE INSERT OR UPDATE
        ON PCDESCONTOFIDELIDADE
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  :NEW.DTALTERC5 := CURRENT_TIMESTAMP;
END;
