CREATE OR REPLACE VIEW SQL_NFE_PARCELA_SAIDA_DESD AS
SELECT DISTINCT PCPREST.NUMTRANSVENDA AS NUM_TRANSACAO,
                (TO_CHAR(PCPREST.DUPLIC) || ' - ' || TO_CHAR(PCPREST.PREST)) AS PRESTACAO,
                DECODE(NVL(PCPREST.CODCOBORIG,
                           PCPREST.CODCOB),
                       'VPP',
                       PCPREST.DTEMISSAO,
                       PCPREST.DTVENCORIG) AS DTVENC,
                NVL(PCPREST.VALORENTFUT, NVL(PCPREST.VALOR,0)) - nvl((SELECT SUM(ABS(NVL(PCPREST.VALORENTFUT, NVL(P.VALOR,0)))) FROM PCPREST P WHERE P.NUMTRANSVENDA = PCPREST.NUMTRANSVENDA AND (CODCOB = 'TR' OR CODCOBORIG = 'TR') GROUP BY VALOR),0) AS VALOR,
                NVL(PCPREST.CODCOBORIG,
                    PCPREST.CODCOB) AS CODCOB,
                NVL(PCPREST.VALORDESC,
                    0) AS VALORDESC,
                    PCDESD.PRESTORIG AS PREST,
       PCPREST.CODCOBSEFAZ,
       PCPREST.RAZAOCREDENCCARTAO AS RAZAO_CRED_CARTAO,
       PCPREST.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       PCPREST.NSUTEF AS NUMAUTOR_CARTAO,
       PCPREST.BANDEIRACARTAO AS BANDEIRA_CARTAO,
       0 INDPAG                    
FROM   PCPREST,
       PCDESD,
       PCNFSAID
WHERE  PCPREST.CODCOB = 'DESD'
AND    PCDESD.NUMTRANSVENDAORIG = PCPREST.NUMTRANSVENDA
AND    PCDESD.PRESTORIG = PCPREST.PREST
AND    PCPREST.CODCOBORIG NOT IN ('JUR')
AND    PCNFSAID.NUMTRANSVENDA = PCPREST.NUMTRANSVENDA
AND    ((NVL(PCNFSAID.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAID.CODFILIAL) = 'S'))
AND    NVL(PCPREST.PERMITEESTORNO, 'S') = 'S'
AND    (PCPREST.CODCOB <> 'TR' AND PCPREST.CODCOBORIG <> 'TR') 