CREATE OR REPLACE VIEW V_CALCULO_UEPS_CC AS
SELECT NVL(E.CODFILIALNF, E.CODFILIAL) CODFILIAL, 
       NVL(ME.NBM, PE.NBM) NCM, 
       ME.CODPROD, 
       NVL(ME.DESCRICAO, PE.DESCRICAO) DSCPRODUTO, 
       NVL(PE.CESTABASICALEGIS,'N') CESTABASICALEGIS, 
       PE.CODLINHAPROD, 
       PE.UNIDADE UNIDADECAD, 
       NVL(PPF.PERCALIQVIGINT,0) PERCALIQVIGINTCAD, 
       NVL(PPF.PERCALIQVIGEXT,0) PERCALIQVIGEXTCAD, 
       ------------------------------------------------------
       -- Informações de Entradas 
       ------------------------------------------------------
       E.NUMTRANSENT, 
       E.NUMNOTA NUMNOTAENT, 
       ------------------------------------------------------
       CASE 
         WHEN ((E.UF = 'EX') AND (NVL(E.EMISSAOPROPRIA, 'N') = 'S')) THEN 
           (SELECT CODFORNEC 
            FROM (SELECT F.CODFORNEC, 
                         F.CGC 
                    FROM PCFORNEC F 
                   ORDER BY F.CODFORNEC) A 
           WHERE CGC = PF.CGC 
             AND ROWNUM = 1) 
       ELSE 
         NVL(E.CODFORNECNF, E.CODFORNEC) 
       END CODFORNECENT, 
       ------------------------------------------------------
       E.FORNECEDOR FORNECEDORENT, 
       E.CGC CNPJENT, 
       E.IE IEENT, 
       E.CONSUMIDORFINAL CONSUMIDORFINALENT, 
       E.CHAVENFE CHAVENFEENT, 
       E.MODELO MODELOENT, 
       E.UF UFENT, 
       E.UFFILIAL UFFILIALENT, 
       E.DTENT DATAENT, 
       E.DTEMISSAO DATAEMIENT, 
       E.ESPECIE ESPECIEENT, 
       E.SERIE SERIEENT, 
       E.TIPODESCARGA TIPOCOMPRAENT, 
       NVL(E.CONTRIBUINTE,'N') CONTRIBUINTEENT, 
       E.VLTOTAL VLTOTALENT, 
       ME.SITTRIBUT SITTRIBUTENT, 
       MCE.ORIGMERCTRIB ORIGMERCTRIBENT, 
       ME.NUMSEQ NUMSEQENT, 
       MCE.NUMSEQENT NUMSEQENT_ENT, 
       ME.IMPORTADO IMPORTADOENT, 
       ME.CODFISCAL CODFISCALENT, 
       ME.CODOPER CODOPERENT, 
       ME.QTCONT QTCONTENT, 
       ME.PUNITCONT PUNITCONTENT, 
       ROUND(ME.QTCONT * NVL(ME.BASEBCR,0), 2) VLBASEBCRENT, 
       NVL(ME.BASEBCR,0) VLBASEBCRENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.VLDESCONTO,0), 2) VLDESCONTOENT, 
       NVL(ME.VLDESCONTO,0) VLDESCONTOENT_UNIT, 
       ------------------------------------------------------
       CASE WHEN E.TIPODESCARGA IN ('6','8','C','T') THEN 
               ROUND(ME.QTCONT * (NVL(ME.BASEICMS,0) + NVL(MCE.VLBASEFRETE,0) + NVL(MCE.VLBASEOUTROS,0)), 2) 
            ELSE 
               ROUND(ME.QTCONT * NVL(ME.BASEICMS, 0),2) 
       END VLBASECALCICMSENT, 
       ------------------------------------------------------
       CASE WHEN E.TIPODESCARGA IN ('6','8','C','T') THEN 
               ROUND((NVL(ME.BASEICMS,0) + NVL(MCE.VLBASEFRETE,0) + NVL(MCE.VLBASEOUTROS,0)), 2) 
            ELSE 
               ROUND(NVL(ME.BASEICMS, 0),2) 
       END VLBASECALCICMSENT_UNIT, 
       ------------------------------------------------------
       ME.PERCICM ALIQICMSENT, 
       ------------------------------------------------------
       CASE WHEN E.TIPODESCARGA IN ('6','8','C','T') THEN 
               ROUND(ME.QTCONT * (NVL(ME.BASEICMS,0) + NVL(MCE.VLBASEFRETE,0) + NVL(MCE.VLBASEOUTROS,0)) * NVL(ME.PERCICM, 0) / 100, 2) 
            ELSE 
               ME.QTCONT * (NVL(ME.BASEICMS, 0) * NVL(ME.PERCICM, 0) / 100) 
       END VLICMSENT, 
       --------------------------- 
       CASE WHEN E.TIPODESCARGA IN ('6','8','C','T') THEN 
               ROUND((NVL(ME.BASEICMS,0) + NVL(MCE.VLBASEFRETE,0) + NVL(MCE.VLBASEOUTROS,0)) * NVL(ME.PERCICM, 0) / 100, 2) 
            ELSE 
               (NVL(ME.BASEICMS, 0) * NVL(ME.PERCICM, 0) / 100) 
       END VLICMSENT_UNIT, 
       ------------------------------------------------------
       CASE WHEN E.TIPODESCARGA IN ('N','F') THEN 
               ME.QTCONT * NVL(ME.VLIMPORTACAO,0) 
            ELSE 
               0 
       END VLIIENT, 
       ------------------------------------------------------       
       CASE WHEN E.TIPODESCARGA IN ('N','F') THEN 
               NVL(ME.VLIMPORTACAO,0) 
            ELSE 
               0 
       END VLIIENT_UNIT, 
       ------------------------------------------------------
       CASE 
         WHEN (SUBSTR(LPAD(ME.SITTRIBUT, 3, '0'), 2, 2) = '60') THEN 
           ROUND(ME.QTCONT * NVL(ME.BASEICMSBCR, 0), 2) 
         ELSE
           0
       END VLBASECALCICMSBCRENT,
       ------------------------------------------------------
       CASE 
         WHEN (SUBSTR(LPAD(ME.SITTRIBUT, 3, '0'), 2, 2) = '60') THEN 
           NVL(ME.BASEICMSBCR, 0) 
         ELSE
           0
       END VLBASECALCICMSBCRENT_UNIT,
       ------------------------------------------------------
       CASE 
         WHEN (SUBSTR(LPAD(ME.SITTRIBUT, 3, '0'), 2, 2) = '60') THEN 
           ROUND(ME.QTCONT * NVL(ME.VLICMSBCR, 0), 2) 
         ELSE
           0
       END VLICMSBCRENT,
       ------------------------------------------------------
       CASE 
         WHEN (SUBSTR(LPAD(ME.SITTRIBUT, 3, '0'), 2, 2) = '60') THEN 
           NVL(ME.VLICMSBCR, 0) 
         ELSE
           0
       END VLICMSBCRENT_UNIT,
       ------------------------------------------------------
       NVL(ME.ALIQICMS1, 0) ALIQICMSINTENT, 
       NVL(ME.ALIQICMS2, 0) ALIQICMSEXTENT, 
       NVL(ME.PERCALIQEXTGUIA, 0) PERCALIQEXTGUIAENT, 
       NVL(ME.PERCIVA, 0) PERCMVAAJUSTADOENT, 
       ME.QTCONT * NVL(ME.BASEICST, 0) VLBASEICMSSTENT, 
       NVL(ME.BASEICST, 0) VLBASEICMSSTENT_UNIT, 
       ME.QTCONT * NVL(ME.ST, 0) VLSTENT, 
       NVL(ME.ST, 0) VLSTENT_UNIT, 
       ME.QTCONT * NVL(ME.VLBASESTFORANF, 0) VLBASEICMSSTENTGUIA, 
       NVL(ME.VLBASESTFORANF, 0) VLBASEICMSSTENTGUIA_UNIT, 
       ME.QTCONT * NVL(ME.VLDESPADICIONAL, 0) VLSTGUIAENT, 
       ME.QTCONT * NVL(ME.STBCR,0) VLSTBCRENT, 
       NVL(ME.STBCR,0) VLSTBCRENT_UNIT, 
       NVL(ME.VLDESPADICIONAL, 0) VLSTGUIAENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.VLBASEIPI, 0), 2) VLBASEIPIENT, 
       NVL(ME.PERCIPI, 0) PERCIPIENT, 
       ROUND(ME.QTCONT * NVL(ME.VLIPI, 0), 2) VLIPIENT, 
       NVL(ME.VLIPI, 0) VLIPIENT_UNIT, 
       (ME.QTCONT * (NVL(ME.VLFRETE, 0) + NVL(ME.VLOUTRASDESP, 0))) VLENCARGOSENT, --Frete, Seguro, Impostos e outros encargos transf. ou cobr. do destin. 
       NVL(MCE.PERCMVAORIG, 0) VLAGREGADOMVA_ENT, --Margem de Valor Agregado - MVA 
       ------------------------------------------------------
       CASE WHEN (E.TIPODESCARGA IN ('6','8','C','T')) THEN 
               ROUND(ME.QTCONT * (ME.PUNITCONT + NVL(ME.VLFRETE,0) + NVL(ME.VLOUTROS,0)), 2) 
            WHEN E.TIPODESCARGA IN ('N','F','I') THEN 
               (ME.QTCONT * ME.PUNITCONT) 
            ELSE 
               ME.QTCONT * (ME.PUNITCONT + NVL(ME.VLIPI,0) + NVL(ME.ST,0) + NVL(ME.VLFRETE,0) + NVL(ME.VLOUTRASDESP,0) - NVL(ME.VLDESCONTO,0) - NVL(ME.VLSUFRAMA,0)) 
       END VLCONTABILENT, 
       ------------------------------------------------------
       CASE WHEN (E.TIPODESCARGA IN ('6','8','C','T')) THEN 
               (ME.PUNITCONT + NVL(ME.VLFRETE,0) + NVL(ME.VLOUTROS,0)) 
            WHEN E.TIPODESCARGA IN ('N','F','I') THEN 
               ME.PUNITCONT 
            ELSE 
               (ME.PUNITCONT + NVL(ME.VLIPI,0) + NVL(ME.ST,0) + NVL(ME.VLFRETE,0) + NVL(ME.VLOUTRASDESP,0) - NVL(ME.VLDESCONTO,0) - NVL(ME.VLSUFRAMA,0)) 
       END VLCONTABILENT_UNIT, 
       ------------------------------------------------------
       ROUND(ME.QTCONT * NVL(ME.VLFRETE, 0), 2) VLFRETEENT, 
       NVL(ME.VLFRETE, 0) VLFRETEENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.VLOUTRASDESP, 0), 2) VLOUTRASDESPENT, 
       NVL(ME.VLOUTRASDESP, 0) VLOUTRASDESPENT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLREDPVENDASIMPLESNA, 0), 2) VLREDPVENDASIMPLESNAENT, 
       E.NUMTRANSORIGEM NUMTRANSORIGEMENT, 
       ME.UNIDADE UNIDADEMOVENT, 
       MCE.TIPOCALCST, 
       UE.CHAVENFEULTENT, 
       UE.NUMTRANSENTULTENT, 
       UE.NUMNFULTENT, 
       UE.CODFORNECULTENT, 
       UE.SERIEULTENT, 
       UE.NUMSEQENTULTENT, 
       UE.CODFILIALULTENT, 
       NVL(MCE.VLBASEFCPST,0) VLBASEFCPSTENT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLBASEFCPST,0), 2) VLBASEFCPSTENT, 
       NVL(MCE.ALIQICMSFECP,0) ALIQICMSFECPENT, 
       NVL(MCE.VLFECP,0) VLFECPENT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLFECP,0), 2) VLFECPENT, 
       NVL(MCE.VLFCPSTRET,0) VLFCPSTRETENT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLFCPSTRET,0), 2) VLFCPSTRETENT, 
       NVL(MCE.PERFCPSTRET,0) PERFCPSTRETENT, 
       NVL(ME.PAUTA,0) PAUTAENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.PAUTA,0), 2) PAUTAENT, 
       NVL(ME.VLPAUTA2,0) VLPAUTA2ENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.VLPAUTA2,0), 2) VLPAUTA2ENT, 
       NVL(ME.VLPAUTAICMS,0) VLPAUTAICMSENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.VLPAUTAICMS,0), 2) VLPAUTAICMSENT, 
       NVL(ME.VLPAUTAICMSANTEC,0) VLPAUTAICMSANTECENT_UNIT, 
       ROUND(ME.QTCONT * NVL(ME.VLPAUTAICMSANTEC,0), 2) VLPAUTAICMSANTECENT, 
       NVL(MCE.VLPAUTABCR,0) VLPAUTABCRENT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLPAUTABCR,0), 2) VLPAUTABCRENT, 
       NVL(MCE.USAPMCBASEST,'N') USAPMCBASESTENT, 
       NVL(MCE.PRECOMAXCONSUM,0) PRECOMAXCONSUMENT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.PRECOMAXCONSUM,0), 2) PRECOMAXCONSUMENT, 
       MCE.UNIDADECOMERCIAL UNIDADECOMERCIALENT, 
       MCE.CODFABRICA CODFABRICAENT, 
       ME.QTUNITCX QTUNITCXENT, 
       NVL(MCE.VLFECPSTGUIA,0) VLFECPSTGUIAT_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLFECPSTGUIA,0), 2) VLFECPSTGUIAENT, 
       NVL(MCE.VLACRESCIMOFUNCEP,0) VLACRESCIMOFUNCEP_UNIT, 
       ROUND(ME.QTCONT * NVL(MCE.VLACRESCIMOFUNCEP,0), 2) VLACRESCIMOFUNCEPENT, 
       ------------------------------------------------------
       -- Informações de Saídas 
       ------------------------------------------------------
       SAI.CODFILIALSAI, 
       SAI.NUMTRANSVENDA, 
       SAI.NUMNOTASAI, 
       SAI.CODCLISAI, 
       SAI.CLIENTESAI, 
       SAI.CNPJSAI, 
       SAI.IESAI, 
       SAI.CONSUMIDORFINALSAI, 
       SAI.CHAVENFESAI, 
       SAI.MODELOSAI, 
       SAI.SIMPLESNACIONALSAI, 
       SAI.UFSAI, 
       SAI.UFFILIALSAI, 
       SAI.DATASAI, 
       SAI.DATAEMISAI, 
       SAI.ESPECIESAI, 
       SAI.SERIESAI, 
       SAI.TIPOVENDASAI, 
       SAI.VLTOTALSAI, 
       SAI.SITTRIBUTSAI, 
       SAI.ORIGMERCTRIBSAI, 
       SAI.NUMSEQSAI, 
       SAI.NUMSEQENTSAI, 
       SAI.IMPORTADOSAI, 
       SAI.CONTRIBUINTESAI, 
       SAI.ORGAOPUBSAI, 
       SAI.ORGAOPUBFEDERALSAI, 
       SAI.ORGAOPUBMUNICIPALSAI, 
       SAI.CODFISCALSAI, 
       SAI.CODOPERSAI, 
       SAI.QTCONTSAI, 
       SAI.QTCONTMOVSAI, 
       SAI.VLBASEBCRSAI, 
       SAI.VLBASEBCRSAI_UNIT, 
       SAI.VLSTBCRSAI, 
       SAI.VLSTBCRSAI_UNIT, 
       SAI.VLDESCONTOSAI, 
       SAI.VLDESCONTOSAI_UNIT, 
       SAI.PUNITCONTSAI, 
       SAI.VLBASECALCICMSSAI, 
       SAI.VLBASECALCICMSSAI_UNIT, 
       SAI.ALIQICMSSAI, 
       SAI.VLICMSSAI, 
       SAI.VLICMSSAI_UNIT, 
       SAI.VLBASEICMSSTSAI, 
       SAI.VLBASEICMSSTSAI_UNIT, 
       SAI.ALIQICMSINTSAI, 
       SAI.ALIQICMSEXTSAI, 
       SAI.VLSTSAI, 
       SAI.VLSTSAI_UNIT, 
       SAI.VLSTGUIASAI, 
       SAI.VLSTGUIASAI_UNIT, 
       SAI.CODIPISAI, 
       SAI.VLBASEIPISAI, 
       SAI.PERCIPISAI, 
       SAI.VLIPISAI, 
       SAI.VLIPISAI_UNIT, 
       SAI.VLENCARGOSSAI, 
       SAI.VLCONTABILSAI, 
       SAI.VLFRETESAI, 
       SAI.VLFRETESAI_UNIT, 
       SAI.VLOUTRASDESPSAI, 
       SAI.VLOUTRASDESPSAI_UNIT, 
       SAI.VLCONTABILSAI_UNIT, 
       SAI.VLREDPVENDASIMPLESNASAI, 
       SAI.NUMTRANSENTORIGEMSAI, 
       SAI.UNIDADEMOVSAI, 
       SAI.NUMSERIEEQUIP NUMSERIEEQUIPSAI, 
       SAI.NUMSERIESAT NUMSERIESATSAI, 
       SAI.USAPMCBASESTSAI, 
       SAI.PAUTASAI_UNIT, 
       SAI.VLPAUTA2SAI_UNIT, 
       SAI.VLPAUTAICMSANTECSAI_UNIT, 
       SAI.VLPAUTABCRSAI_UNIT, 
       SAI.PRECOMAXCONSUMSAI_UNIT, 
       SAI.PAUTASAI, 
       SAI.VLPAUTA2SAI, 
       SAI.VLPAUTAICMSANTECSAI, 
       SAI.VLPAUTABCRSAI, 
       SAI.PRECOMAXCONSUMSAI, 
       SAI.PERFCPSTRETSAI, 
       SAI.VLFCPSTRETSAI, 
       SAI.VLFCPSTRETSAI_UNIT, 
       SAI.UNIDADECOMERCIALSAI, 
       SAI.CODFABRICASAI, 
       SAI.QTUNITCXSAI, 
       SAI.QTDEVOL 
FROM PCNFENT E, 
     PCFILIAL PF, 
     PCMOV ME, 
     PCMOVCOMPLE MCE, 
     PCUEPSSALDOENT UE, 
     PCPRODUT PE, 
     PCPRODFILIAL PPF, 
     (SELECT S.NUMTRANSVENDA, 
             NVL(S.CODFILIALNF, S.CODFILIAL) CODFILIALSAI, 
             S.NUMNOTA NUMNOTASAI, 
             MVS.NUMTRANSENT NUMTRANSENTSAI, 
             NVL(S.CODCLINF, S.CODCLI) CODCLISAI, 
             S.CLIENTE CLIENTESAI, 
             S.CGC CNPJSAI, 
             S.IE IESAI, 
             S.CONSUMIDORFINAL CONSUMIDORFINALSAI, 
             S.CHAVENFE CHAVENFESAI, 
             DECODE(S.CHAVENFE, NULL, NULL, SUBSTR(S.CHAVENFE, 21, 2)) MODELOSAI, 
             NVL(S.SIMPLESNACIONAL,'N') SIMPLESNACIONALSAI, 
             S.UF UFSAI, 
             S.UFFILIAL UFFILIALSAI, 
             S.DTSAIDA DATASAI, 
             S.DTENTREGA DATAEMISAI, 
             S.ESPECIE ESPECIESAI, 
             S.SERIE SERIESAI, 
             S.TIPOVENDA TIPOVENDASAI, 
             S.VLTOTAL VLTOTALSAI, 
             MS.SITTRIBUT SITTRIBUTSAI, 
             MCS.ORIGMERCTRIB ORIGMERCTRIBSAI, 
             MS.NUMSEQ NUMSEQSAI, 
             MCS.NUMSEQENT NUMSEQENTSAI, 
             MS.IMPORTADO IMPORTADOSAI, 
             NVL(S.CONTRIBUINTE,'N') CONTRIBUINTESAI, 
             NVL(S.ORGAOPUB,'N') ORGAOPUBSAI, 
             NVL(S.ORGAOPUBFEDERAL,'N') ORGAOPUBFEDERALSAI, 
             NVL(S.ORGAOPUBMUNICIPAL,'N') ORGAOPUBMUNICIPALSAI, 
             MS.CODFISCAL CODFISCALSAI, 
             MS.CODPROD CODPRODSAI, 
             MS.CODOPER CODOPERSAI, 
             MAX(MS.QTCONT) QTCONTSAI, 
             SUM(MVS.QTCONT) QTCONTMOVSAI, 
             MAX(MS.PUNITCONT) PUNITCONTSAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.BASEBCR,0), 2)) VLBASEBCRSAI, 
             NVL(MS.BASEBCR,0) VLBASEBCRSAI_UNIT, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLDESCONTO,0), 2)) VLDESCONTOSAI, 
             NVL(MS.VLDESCONTO,0) VLDESCONTOSAI_UNIT, 
             SUM(ROUND(MS.QTCONT * MS.BASEICMS, 2)) VLBASECALCICMSSAI, 
             MAX(MS.BASEICMS) VLBASECALCICMSSAI_UNIT, 
             NVL(MS.PERCICM, 0) ALIQICMSSAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.BASEICMS, 0) * NVL(MS.PERCICM, 0) / 100, 2)) VLICMSSAI, 
             MAX(NVL(MS.BASEICMS, 0) * NVL(MS.PERCICM, 0) / 100) VLICMSSAI_UNIT, 
             SUM(ROUND(MS.QTCONT * NVL(MS.BASEICST, 0), 2)) VLBASEICMSSTSAI, 
             MAX(NVL(MS.BASEICST, 0)) VLBASEICMSSTSAI_UNIT, 
             NVL(MS.ALIQICMS1,0) ALIQICMSINTSAI, 
             NVL(MS.ALIQICMS2,0) ALIQICMSEXTSAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.ST, 0), 2)) VLSTSAI, 
             MAX(NVL(MS.ST, 0)) VLSTSAI_UNIT, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLDESPADICIONAL, 0), 2)) VLSTGUIASAI, 
             MAX(NVL(MS.VLDESPADICIONAL, 0)) VLSTGUIASAI_UNIT, 
             SUM(ROUND(MS.QTCONT * NVL(MS.STBCR,0), 2)) VLSTBCRSAI, 
             NVL(MS.STBCR,0) VLSTBCRSAI_UNIT, 
             MCS.CODSITTRIBIPI CODIPISAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLBASEIPI, 0), 2)) VLBASEIPISAI, 
             NVL(MS.PERCIPI, 0) PERCIPISAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLIPI, 0), 2)) VLIPISAI, 
             MAX(NVL(MS.VLIPI, 0)) VLIPISAI_UNIT, 
             SUM((MS.QTCONT * (NVL(MS.VLFRETE, 0) + NVL(MS.VLOUTRASDESP, 0)))) VLENCARGOSSAI, --Frete, Seguro, Impostos e outros encargos transf. ou cobr. do destin. 
             MAX(NVL(MCS.PERCMVAORIG, 0)) VLAGREGADOMVASAI, --Margem de Valor Agregado - MVA 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLFRETE, 0), 2)) VLFRETESAI, 
             MAX(NVL(MS.VLFRETE, 0)) VLFRETESAI_UNIT, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLOUTRASDESP, 0), 2)) VLOUTRASDESPSAI, 
             MAX(NVL(MS.VLOUTRASDESP, 0)) VLOUTRASDESPSAI_UNIT, 
             ------------------------------------------------
             SUM(CASE WHEN (NVL(MS.CODOPER,'X') <> 'SD') THEN 
                       ROUND(MS.QTCONT * (MS.PUNITCONT + NVL(MS.VLFRETE,0) + NVL(MS.VLOUTROS,0)), 2) 
                    ELSE 
                       ROUND(MS.QTCONT * (MS.PUNITCONT + NVL(MS.VLOUTRASDESP,0)), 2) 
                 END) VLCONTABILSAI, 
             ------------------------------------------------
             MAX(CASE WHEN (NVL(MS.CODOPER,'X') <> 'SD') THEN 
                       (MS.PUNITCONT + NVL(MS.VLFRETE,0) + NVL(MS.VLOUTROS,0)) 
                    ELSE 
                       (MS.PUNITCONT + NVL(MS.VLOUTRASDESP,0)) 
                 END) VLCONTABILSAI_UNIT, 
             ------------------------------------------------
             SUM(ROUND(MS.QTCONT * NVL(MCS.VLREDPVENDASIMPLESNA, 0),2)) VLREDPVENDASIMPLESNASAI, 
             S.NUMTRANSENTORIGEM NUMTRANSENTORIGEMSAI, 
             MS.UNIDADE UNIDADEMOVSAI, 
             MVS.NUMSEQENTULTENT, 
             S.NUMSERIEEQUIP, 
             S.NUMSERIESAT, 
             NVL(MCS.USAPMCBASEST,'N') USAPMCBASESTSAI, 
             MAX(NVL(MS.PAUTA,0)) PAUTASAI_UNIT, 
             MAX(NVL(MS.VLPAUTA2,0)) VLPAUTA2SAI_UNIT, 
             MAX(NVL(MS.VLPAUTAICMSANTEC,0)) VLPAUTAICMSANTECSAI_UNIT, 
             MAX(NVL(MCS.VLPAUTABCR,0)) VLPAUTABCRSAI_UNIT, 
             MAX(NVL(MCS.PRECOMAXCONSUM,0)) PRECOMAXCONSUMSAI_UNIT, 
             SUM(ROUND(MS.QTCONT * NVL(MS.PAUTA, 0), 2)) PAUTASAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLPAUTA2,0), 2)) VLPAUTA2SAI, 
             SUM(ROUND(MS.QTCONT * NVL(MS.VLPAUTAICMSANTEC,0), 2)) VLPAUTAICMSANTECSAI, 
             SUM(ROUND(MS.QTCONT * NVL(MCS.VLPAUTABCR,0), 2)) VLPAUTABCRSAI, 
             SUM(ROUND(MS.QTCONT * NVL(MCS.PRECOMAXCONSUM,0), 2)) PRECOMAXCONSUMSAI, 
             NVL(MCS.PERFCPSTRET,0) PERFCPSTRETSAI, 
             SUM(ROUND(MS.QTCONT * NVL(MCS.VLFCPSTRET,0), 2)) VLFCPSTRETSAI, 
             MAX(NVL(MCS.VLFCPSTRET,0)) VLFCPSTRETSAI_UNIT, 
             MAX(MCS.UNIDADECOMERCIAL) UNIDADECOMERCIALSAI, 
             MAX(MCS.CODFABRICA) CODFABRICASAI, 
             MAX(MS.QTUNITCX) QTUNITCXSAI, 
             MAX(MS.QTDEVOL) QTDEVOL 
      FROM PCNFSAID S, 
           PCMOV MS, 
           PCMOVCOMPLE MCS, 
           PCUEPSSALDOSAID MVS 
      WHERE S.NUMTRANSVENDA = MS.NUMTRANSVENDA 
        AND S.NUMNOTA = MS.NUMNOTA 
        AND MS.NUMTRANSITEM = MCS.NUMTRANSITEM(+) 
        AND MVS.NUMTRANSVENDA(+) = MS.NUMTRANSVENDA 
        AND MVS.CODPROD(+) = MS.CODPROD 
        -- Filtros Utilizando a PKG_PARAMETRO_FISCAL
        AND S.DTSAIDA   BETWEEN PKG_PARAMETRO_FISCAL.GET_DATA1 AND PKG_PARAMETRO_FISCAL.GET_DATA2
        AND MVS.DTSAIDA BETWEEN PKG_PARAMETRO_FISCAL.GET_DATA1 AND PKG_PARAMETRO_FISCAL.GET_DATA2
        AND MS.DTMOV    BETWEEN PKG_PARAMETRO_FISCAL.GET_DATA1 AND PKG_PARAMETRO_FISCAL.GET_DATA2
        AND ((NVL(S.CODFILIALNF, S.CODFILIAL)   = PKG_PARAMETRO_FISCAL.GET_CODFILIAL) OR (PKG_PARAMETRO_FISCAL.GET_CODFILIAL IS NULL))
        AND ((NVL(MS.CODFILIALNF, MS.CODFILIAL) = PKG_PARAMETRO_FISCAL.GET_CODFILIAL) OR (PKG_PARAMETRO_FISCAL.GET_CODFILIAL IS NULL))
        AND ((MVS.CODFILIAL = PKG_PARAMETRO_FISCAL.GET_CODFILIAL)                     OR (PKG_PARAMETRO_FISCAL.GET_CODFILIAL IS NULL))
        ---         
        AND (SUBSTR(S.ESPECIE, 1,2) = 'NF' OR SUBSTR(S.ESPECIE, 1,2) = 'CP')
        AND MS.STATUS IN ('A','AB') 
        AND MS.DTCANCEL IS NULL 
       GROUP BY S.NUMTRANSVENDA, S.NUMNOTA, MVS.NUMTRANSENT, S.CGC, S.IE, S.CONSUMIDORFINAL, S.CHAVENFE, S.NUMSERIEEQUIP, 
                NVL(S.SIMPLESNACIONAL,'N'), S.DTSAIDA, S.DTENTREGA, NVL(S.CODCLINF, S.CODCLI), S.NUMTRANSENTORIGEM, 
                S.CLIENTE, S.UF, S.UFFILIAL, S.ESPECIE, S.SERIE, S.TIPOVENDA, NVL(S.CONTRIBUINTE,'N'), S.NUMSERIESAT, 
                NVL(S.ORGAOPUB,'N'), NVL(S.ORGAOPUBFEDERAL,'N'), NVL(S.ORGAOPUBMUNICIPAL,'N'), NVL(MCS.USAPMCBASEST,'N'), 
                S.VLTOTAL, MS.CODPROD, MS.UNIDADE, MS.SITTRIBUT, MCS.ORIGMERCTRIB, MS.NUMSEQ, MCS.NUMSEQENT, MS.IMPORTADO, 
                MS.CODFISCAL, MS.CODOPER, MS.PERCICM, MS.ALIQICMS1, MS.ALIQICMS2, NVL(MCS.PERFCPSTRET,0), 
                NVL(MS.BASEBCR,0), NVL(MS.STBCR,0), NVL(MS.VLDESCONTO,0), MCS.CODSITTRIBIPI, 
                MS.PERCIPI,NVL(S.CODFILIALNF,S.CODFILIAL), MVS.NUMSEQENTULTENT 
     ) SAI 
WHERE E.NUMTRANSENT = ME.NUMTRANSENT 
  AND E.NUMNOTA = ME.NUMNOTA 
  AND PF.CODIGO = NVL(E.CODFILIALNF, E.CODFILIAL) 
  AND E.NUMTRANSENT = UE.NUMTRANSENT 
  AND ME.CODPROD = UE.CODPROD 
  AND ME.CODPROD = PE.CODPROD 
  AND ME.NUMTRANSITEM = MCE.NUMTRANSITEM(+) 
  AND ME.CODPROD(+) = SAI.CODPRODSAI 
  AND ME.NUMTRANSENT(+) = SAI.NUMTRANSENTSAI 
  AND NVL(MCE.NUMSEQENT, 1) = DECODE(NVL(UE.NUMTRANSENTULTENT, -1), -1, NVL(UE.NUMSEQENTULTENT, 1), NVL(MCE.NUMSEQENT, 1)) -- SOMENTE QUANDO VINCULO É NA MESMA FILIAL  
  AND ME.CODPROD = PPF.CODPROD 
  AND NVL(ME.CODFILIALNF,ME.CODFILIAL) = PPF.CODFILIAL 
  AND E.ESPECIE = 'NF' 
  AND ME.DTCANCEL IS NULL 
  AND ME.STATUS IN ('A','AB') 
-- 13/12/2024 - Gleibe - Implementado a utilização do objeto fiscal de filtros data e filial;
-- 12/02/2026 - Messias - Migração da view V_CALCULO_UEPS_CC do portal ADM DB para o repositório do Azure