DECLARE
  VREC_QTDE PKG_ANALISAR_ESTOQUE.TP_ENTRADA;
  IPREST INTEGER;
  VNCONTADOR NUMBER;
  PVC2MENSSAGEM VARCHAR2(1000);
  VSCREATE VARCHAR2(1000);
   
  PTRANSACAO NUMBER;
  VSMSGEST   VARCHAR2(100);
  PRETORNO   NUMBER(10);
  VNSITUACAONFE NUMBER(4);
  VSESPECIE     VARCHAR2(4);
  VNTIPOEMISSAO VARCHAR2(4);
  VNCHAVENFE    VARCHAR2(45);
  VNSERIE       VARCHAR2(4);
  VSENVIADA     VARCHAR2(4);
  VSAMBIENTENFE VARCHAR2(2);
  VNNUMVIAS     NUMBER(4);
  VSOWNER       VARCHAR2(40);
   
  PROCEDURE FASTCONSOLIDATE(VSTABLE IN VARCHAR2, VNNUMTRANSVENDA IN NUMBER) IS
    VSSCRIPT VARCHAR2(32767);
  BEGIN
    --VNNUMTRANSVENDA := &TRANSV;
    --VSTABLE         := &TB;
    VSSCRIPT := 'INSERT INTO ' || UPPER(VSTABLE) || ' (';

    FOR COLUNAS IN (SELECT A.COLUMN_NAME, ROWNUM IDR
                      FROM ALL_TAB_COLUMNS A
                     WHERE A.TABLE_NAME = UPPER(VSTABLE)
                       AND EXISTS
                     (SELECT 1
                              FROM ALL_TAB_COLUMNS C
                             WHERE C.COLUMN_NAME = A.COLUMN_NAME
                               AND C.TABLE_NAME = UPPER(VSTABLE) || 'PREFAT'
                               AND C.OWNER = VSOWNER)
                       AND A.OWNER = VSOWNER
                     ORDER BY ROWNUM) LOOP

      IF COLUNAS.IDR = 1 THEN
        VSSCRIPT := VSSCRIPT || --'SELECT ''PREFAT'' TABELA,' ||
                    COLUNAS.COLUMN_NAME || CHR(13);
      ELSE
        VSSCRIPT := VSSCRIPT || ',' || COLUNAS.COLUMN_NAME || CHR(13);
      END IF;
    END LOOP;
    --   VSSCRIPT := VSSCRIPT ||
    --                'FROM PCMOVPREFAT WHERE NUMTRANSVENDA = :NUMTRANSVENDAPREFAT';
    VSSCRIPT := VSSCRIPT || ' ) SELECT   ';

    FOR COLUNAS IN (SELECT A.COLUMN_NAME, A.TABLE_NAME, ROWNUM IDR
                      FROM ALL_TAB_COLUMNS A
                     WHERE A.TABLE_NAME = UPPER(VSTABLE)
                       AND EXISTS
                     (SELECT 1
                              FROM ALL_TAB_COLUMNS C
                             WHERE C.COLUMN_NAME = A.COLUMN_NAME
                               AND C.TABLE_NAME = UPPER(VSTABLE) || 'PREFAT'
                               AND C.OWNER = VSOWNER)
                       AND A.OWNER = VSOWNER
                     ORDER BY ROWNUM) LOOP

      IF COLUNAS.IDR = 1 THEN
        VSSCRIPT := VSSCRIPT || --'SELECT ''PCMOV'' TABELA,' ||
                    UPPER(VSTABLE) || 'PREFAT' || '.' ||
                    COLUNAS.COLUMN_NAME || CHR(13);
      ELSE
        VSSCRIPT := VSSCRIPT || ',' || UPPER(VSTABLE) || 'PREFAT' || '.' ||
                    COLUNAS.COLUMN_NAME || CHR(13);
      END IF;

    END LOOP;

    IF INSTR(UPPER(VSTABLE), 'PCMOVCOMPLE') > 0 THEN
      VSSCRIPT := VSSCRIPT ||
                  'FROM PCMOVPREFAT, PCMOVCOMPLEPREFAT WHERE PCMOVPREFAT.NUMTRANSITEM = PCMOVCOMPLEPREFAT.NUMTRANSITEM' ||
                  ' AND PCMOVPREFAT.NUMTRANSVENDA = ' || VNNUMTRANSVENDA;
    ELSE
      VSSCRIPT := VSSCRIPT || 'FROM ' || UPPER(VSTABLE) ||
                  'PREFAT WHERE NUMTRANSVENDA = ' || VNNUMTRANSVENDA;
    END IF;

    EXECUTE IMMEDIATE VSSCRIPT;
    --DBMS_OUTPUT.PUT_LINE(VSSCRIPT);
  END;
BEGIN
  
  
  BEGIN
    SELECT COUNT(*)
      INTO VNCONTADOR
      FROM USER_TABLES
     WHERE TABLE_NAME = 'PCLOGCANCELAMEMTO_1409';
  EXCEPTION
    WHEN OTHERS THEN
      VNCONTADOR := 0;
  END;
  -- CRIANDO A TABELA PARA ARMAZENAR OS DIAS
  IF VNCONTADOR = 0 THEN
    VSCREATE := 'CREATE TABLE PCLOGCANCELAMEMTO_1409 (NUMTRANSVENDA NUMBER(20), MSG_RETORNO VARCHAR2(2000)) NOLOGGING';
    EXECUTE IMMEDIATE VSCREATE;
    COMMIT;
  END IF;
  -- SEMPE DELETA A TABELA PCLISTADIAS
  BEGIN
    VSCREATE := 'TRUNCATE TABLE PCLOGCANCELAMEMTO_1409';
    EXECUTE IMMEDIATE VSCREATE;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      VSCREATE := 'N';
  END;
  
  SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') FROM DUAL;
    INTO VSOWNER
    FROM DUAL;
  
  FOR TRANSACOES IN (SELECT  DISTINCT 'CONSOLIDADAS' TABELAS, M.NUMTRANSVENDA
                       FROM PCMOV M, PCNFSAID S
                     WHERE M.DTCANCEL IS NOT NULL
                     AND S.NUMTRANSVENDA = M.NUMTRANSVENDA
                     AND S.DTCANCEL IS NOT NULL
                     AND S.SITUACAONFE = 1006
                     AND S.DTCANCEL >= TO_DATE('28/08/2025','DD/MM/YYYY')
                     AND CODOPER LIKE 'S%'                     
                     AND ((QT > 0 AND (SELECT COUNT(1)
                                         FROM PCMOV
                                        WHERE PCMOV.NUMTRANSVENDA = M.NUMTRANSVENDA
                                          AND PCMOV.QT < 0) = 0) OR
                         (QTCONT > 0 AND (SELECT COUNT(1)
                                             FROM PCMOV
                                            WHERE PCMOV.NUMTRANSVENDA = M.NUMTRANSVENDA
                                              AND PCMOV.QTCONT < 0) = 0))
                     UNION
                     SELECT 'NAO CONSOLIDADAS' TABELA
                     , NF.NUMTRANSVENDA
                     FROM PCNFSAIDPREFAT NF, PCMOVPREFAT M
                   WHERE NF.NUMTRANSVENDA = M.NUMTRANSVENDA
                     AND NF.DTCANCEL IS NOT NULL
                     AND NF.DTCANCEL >= TO_DATE('28/08/2025','DD/MM/YYYY')                     
                     AND NOT EXISTS (SELECT NUMNOTA
                                     FROM PCNFSAID
                                     WHERE PCNFSAID.NUMTRANSVENDA = NF.NUMTRANSVENDA)
    
                   ) LOOP

    PTRANSACAO := TRANSACOES.NUMTRANSVENDA;
    IF TRANSACOES.TABELAS = 'NAO CONSOLIDADAS' THEN
     
      FASTCONSOLIDATE('PCMOV', PTRANSACAO);
      FASTCONSOLIDATE('PCMOVCOMPLE', PTRANSACAO);
      FASTCONSOLIDATE('PCNFSAID', PTRANSACAO);
      FASTCONSOLIDATE('PCNFBASE', PTRANSACAO);
      FASTCONSOLIDATE('PCPREST', PTRANSACAO);
      FASTCONSOLIDATE('PCLANC', PTRANSACAO);

      SELECT SITUACAONFE,
             ESPECIE,
             TIPOEMISSAO,
             CHAVENFE,
             SERIE,
             ENVIADA,
             AMBIENTENFE,
             NUMVIAS
        INTO VNSITUACAONFE,
             VSESPECIE,
             VNTIPOEMISSAO,
             VNCHAVENFE,
             VNSERIE,
             VSENVIADA,
             VSAMBIENTENFE,
             VNNUMVIAS
        FROM PCNFSAIDPREFAT
       WHERE NUMTRANSVENDA = PTRANSACAO;

      UPDATE PCNFSAID
         SET SITUACAONFE = VNSITUACAONFE,
             ESPECIE     = VSESPECIE,
             TIPOEMISSAO = VNTIPOEMISSAO,
             CHAVENFE    = VNCHAVENFE,
             SERIE       = VNSERIE,
             ENVIADA     = VSENVIADA,
             AMBIENTENFE = VSAMBIENTENFE,
             NUMVIAS     = VNNUMVIAS
       WHERE 1 = 1
         AND NUMTRANSVENDA = PTRANSACAO;

      PRETORNO := PKG_ESTOQUE.VENDAS_SAIDA(PTRANSACAO, 'N', PVC2MENSSAGEM);

      DELETE FROM PCNFSAIDPREFAT WHERE NUMTRANSVENDA = PTRANSACAO;
      DELETE FROM PCMOVCOMPLEPREFAT
       WHERE NUMTRANSITEM IN
             (SELECT NUMTRANSITEM
                FROM PCMOVPREFAT
               WHERE NUMTRANSVENDA = PTRANSACAO);
      DELETE FROM PCMOVPREFAT WHERE NUMTRANSVENDA = PTRANSACAO;
      DELETE FROM PCPRESTPREFAT WHERE NUMTRANSVENDA = PTRANSACAO;
    END IF;
    
    FOR DADOS IN ( SELECT 
                       NUMTRANSVENDA
                      ,DTSAIDA
                      ,SITUACAONFE
                      ,CHAVENFE
                      ,PROTOCOLONFE
                      ,ROWID
                    FROM PCNFSAID
                    WHERE 1=1
                    AND NUMTRANSVENDA IN (PTRANSACAO)
    ) LOOP
      
      SELECT COUNT(*) INTO IPREST 
      FROM PCPREST 
      WHERE 1=1
      AND NUMTRANSVENDA = DADOS.NUMTRANSVENDA;
      
      IF IPREST > 0 THEN
        UPDATE PCPREST SET
            DTCANCEL = NULL
           ,DTPAG = NULL
           ,VPAGO = NULL
        WHERE NUMTRANSVENDA = DADOS.NUMTRANSVENDA;  
      END IF;
      
      UPDATE PCNFSAID SET
           DTCANCEL = NULL
           ,ESPECIE = 'NF'
          ,SITUACAONFE = 100
      WHERE NUMTRANSVENDA = DADOS.NUMTRANSVENDA;

      UPDATE PCMOV SET 
          DTCANCEL = NULL
      WHERE NUMTRANSVENDA = DADOS.NUMTRANSVENDA;    
      
      BEGIN 
        P_PC_CACELA_NF('PCADMIN', DADOS.NUMTRANSVENDA, 'NF INUTILIZADA NA SEFAZ', PVC2MENSSAGEM);
        IF PVC2MENSSAGEM <> 'OK' THEN 
          VSCREATE := 'INSERT INTO PCLOGCANCELAMEMTO_1409(NUMTRANSVENDA, MSG_RETORNO) VALUES (DADOS.NUMTRANSVENDA, PVC2MENSSAGEM || SQLERRM)';
          EXECUTE IMMEDIATE VSCREATE;
          COMMIT;
		ELSE
		  VSCREATE := 'INSERT INTO PCLOGCANCELAMEMTO_1409(NUMTRANSVENDA, MSG_RETORNO) VALUES (DADOS.NUMTRANSVENDA, PVC2MENSSAGEM || SQLERRM)';
          EXECUTE IMMEDIATE VSCREATE;
          COMMIT;
        END IF; 
      EXCEPTION
        WHEN OTHERS THEN
          VSCREATE := 'INSERT INTO PCLOGCANCELAMEMTO_1409(NUMTRANSVENDA, MSG_RETORNO) VALUES (DADOS.NUMTRANSVENDA, PVC2MENSSAGEM || SQLERRM)';
          EXECUTE IMMEDIATE VSCREATE;
          COMMIT;
      END;    
     
      UPDATE PCNFSAID SET
           DTCANCEL = DADOS.DTSAIDA
      ,ESPECIE = 'NF'
          ,SITUACAONFE = 102
      WHERE NUMTRANSVENDA = DADOS.NUMTRANSVENDA;

      UPDATE PCMOV SET
           DTMOV = DADOS.DTSAIDA
      ,DTCANCEL = DADOS.DTSAIDA
      WHERE NUMTRANSVENDA = DADOS.NUMTRANSVENDA;
    
      FOR ITENS IN (SELECT 
                    DISTINCT
                    CODPROD
                    ,NVL(CODFILIALNF,CODFILIAL) CODFILIALNF
                    ,NVL(CODFILIALRETIRA,CODFILIAL) CODFILIALRETIRA
                    FROM PCMOV
                  WHERE NUMTRANSVENDA = DADOS.NUMTRANSVENDA
                    AND QT < 0
      ) LOOP
        VREC_QTDE.CODPROD         := ITENS.CODPROD;       
        VREC_QTDE.CODFILIAL       := ITENS.CODFILIALRETIRA;     
        VREC_QTDE.DTINICIAL       := DADOS.DTSAIDA;          
        VREC_QTDE.TIPOCHAMADA     := '';   
        VREC_QTDE.GERAR_LOG       := 'N';            
        VREC_QTDE.USA_FUNCAO_1070 := 'S'; 
        PKG_ANALISAR_ESTOQUE.PRC_CORRIGIR_PCHISTEST(VREC_QTDE);
        IF ITENS.CODFILIALNF <> ITENS.CODFILIALRETIRA THEN
          VREC_QTDE.CODFILIAL := ITENS.CODFILIALNF;
        
          PKG_ANALISAR_ESTOQUE.PRC_CORRIGIR_PCHISTEST(VREC_QTDE);
        END IF;
      END LOOP;
    END LOOP;
  END LOOP;
END;