CREATE OR REPLACE VIEW VW_INT_C5_DEPARATRIBUTACAO AS (
  SELECT 
    DEPARA.SEQCENARIO,
    TRIBUTACAO.CODIGO_TRIBUTACAO,
    TRIBUTACAO.TIPO_IMPOSTO_EXIBIR AS TIPO_IMPOSTO,
    CASE 
      WHEN TRIBUTACAO.DTINATIVACAO IS NULL THEN 'S' 
      ELSE 'N' 
    END AS ATIVO
  FROM (
    SELECT 
      CODIGO_TRIBUTACAO,
      'CBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IS' AS TIPO_IMPOSTO_EXIBIR,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'IS') TRIBUTACAO,
    PCDEPARATRIBUTACAOC5 DEPARA
  WHERE TRIBUTACAO.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO(+)
    AND TRIBUTACAO.TIPO_IMPOSTO_EXIBIR = DEPARA.TIPO_IMPOSTO(+)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIO AS (
  SELECT 
    DEPARA.SEQCENARIO,
    DEPARA.TIPO_IMPOSTO DESCRICAO,
    T.DESCRICAO_TRIBUTACAO ORIENTACAO,
    NVL(T.DTINICIO_VIGENCIA, SYSDATE) DTAINICIALVALIDADE,
    NVL(T.DTFIM_VIGENCIA, SYSDATE + 1) DTAFINALVALIDADE,
    0 TOTALPONTOS,
    CASE WHEN T.DTINATIVACAO IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO,
    T.DTALTERC5
  FROM PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO T,
       (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
         WHERE ATIVO = 'A'
           AND ((UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIO') 
            OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAO')
            OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAOITEM'))
        ) D
  WHERE T.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO
    AND NVL(T.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCONDICAO AS
(
  SELECT 1 as SEQCONDICAO, 'PRODUTO' as IDENTIFICADOR, 80 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQCONDICAO, 'FAMILIA' as IDENTIFICADOR, 80 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQCONDICAO, 'NCM' as IDENTIFICADOR, 60 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 4 as SEQCONDICAO, 'CFOP' as IDENTIFICADOR, 50 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 5 as SEQCONDICAO, 'CGO' as IDENTIFICADOR, 40 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 6 as SEQCONDICAO, 'ORIGEM' as IDENTIFICADOR, 30 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 7 as SEQCONDICAO, 'DESTINO' as IDENTIFICADOR, 30 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 8 as SEQCONDICAO, 'UFORIGEM' as IDENTIFICADOR, 20 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 9 as SEQCONDICAO, 'UFDESTINO' as IDENTIFICADOR, 20 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOCONDICAO AS
(
  SELECT 
    MIN(NVL((SELECT SEQCENARIOCONDICAO
          FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
      WHERE SEQCENARIO = DEPARA.SEQCENARIO
      AND SEQCONDICAO = CN.SEQCONDICAO
      AND ROWNUM = 1), 0)) SEQCENARIOCONDICAO,
    DEPARA.SEQCENARIO,
    CN.SEQCONDICAO,
    MIN(CN.PESOBUSCA) PONTOSBUSCA,
    CASE WHEN MIN(TP.DTINATIVACAO) IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO
  FROM PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO_FILTRO_PRODUTO TP,
       VW_INT_C5_CCTCONDICAO CN
  WHERE DEPARA.CODIGO_TRIBUTACAO = TP.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 1
  GROUP BY DEPARA.SEQCENARIO, CN.SEQCONDICAO    
  
  UNION ALL
  
  SELECT
    MIN(NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = DEPARA.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0)) SEQCENARIOCONDICAO,
    DEPARA.SEQCENARIO,
    CN.SEQCONDICAO,
    MIN(CN.PESOBUSCA) PONTOSBUSCA,   
    CASE WHEN MIN(N.DTINATIVACAO) IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO
  FROM PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO_FILTRO_NCM N,
       VW_INT_C5_CCTCONDICAO CN
  WHERE DEPARA.CODIGO_TRIBUTACAO = N.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 3
  GROUP BY DEPARA.SEQCENARIO, CN.SEQCONDICAO  

  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = DEPARA.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    DEPARA.SEQCENARIO,
    CN.SEQCONDICAO,
    CN.PESOBUSCA PONTOSBUSCA,
    DEPARA.ATIVO
  FROM PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND DEPARA.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 8  
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENCONDITEM AS 
(
  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    TO_CHAR(DEPARA.SEQPRODUTO) VALOR,
    'P' INDTIPOIDENTIDADE,
    'PRODUTO' IDENTIFICADOR,
    CC.SEQCENARIO,
    CASE WHEN N.DTINATIVACAO IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO,
    N.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO_FILTRO_PRODUTO N,
       PCDEPARAPRODC5 DEPARA
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = N.CODIGO_TRIBUTACAO
    AND DEPARA.CODPROD = N.CODPROD
    AND DEPARA.ATIVO = 'S'
    AND CC.SEQCONDICAO = 1

  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    TO_CHAR(N.NCM) VALOR,
    'P' INDTIPOIDENTIDADE,
    'NCM' IDENTIFICADOR,
    CC.SEQCENARIO,
    CASE WHEN N.DTINATIVACAO IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO,
    N.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO_FILTRO_NCM N
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = N.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 3

  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    CASE WHEN T.TIPO_LOCAL_CONSUMO = 'G' 
      THEN TO_CHAR(NVL(T.LOCAL_CONSUMO_GERAL, 'BR'))
      ELSE TO_CHAR(T.LOCAL_CONSUMO_MUNICIPIO)
    END VALOR,
    'P' INDTIPOIDENTIDADE,
    'UFORIGEM' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 8
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTIMPOSTO AS
(
  SELECT 1 as SEQIMPOSTO, 'CBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQIMPOSTO, 'IBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQIMPOSTO, 'IS'  as DESCRICAO, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTFORMULA AS
(
  SELECT 1 as SEQFORMULA, 'PADRAO' as DESCRICAO, '[#PRECOPRODUTO] + [#ACRESCIMO] + [#MULTAJUROS] + [#DESCADICIONAL] + [#FRETE] + [#IPI] + [#ST]' as BASE, 'S' as ATIVO FROM PCCONSUM
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCODIGOTRIBUTARIO AS 
(
  SELECT
    MIN(NVL((SELECT SEQCODIGOTRIBUTARIO
            FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO
        WHERE CODIGO = CODTRIB.CODIGO
        AND ROWNUM = 1), 0)) SEQCODIGOTRIBUTARIO,
    CODTRIB.CODIGO,
    CODTRIB.DESCRICAO,
    CODTRIB.INDTIPOCODIGO,
    CODTRIB.DTAINICIALVALIDADE,
    CODTRIB.DTAFINALVALIDADE ,
    CODTRIB.ATIVO,
    CODTRIB.IDREF
  FROM (
    SELECT
      T.CST AS CODIGO,
      'CST ' || T.CST AS DESCRICAO,
      1 AS INDTIPOCODIGO,
      NVL(T.DTINICIO_VIGENCIA, SYSDATE) AS DTAINICIALVALIDADE,
      NVL(T.DTFIM_VIGENCIA, SYSDATE + 1) AS DTAFINALVALIDADE,
      CASE 
        WHEN T.DTINATIVACAO IS NULL THEN 'S' ELSE 'N'
      END AS ATIVO,
      T.CODIGO_TRIBUTACAO IDREF
    FROM PCTRIBUTACAO T
    
    UNION ALL
    
    SELECT
      T.CCLASSTRIB AS CODIGO,
      'CCLASSTRIB ' || T.CCLASSTRIB AS DESCRICAO,
      2 AS INDTIPOCODIGO,
      NVL(T.DTINICIO_VIGENCIA, SYSDATE) AS DTAINICIALVALIDADE,
      NVL(T.DTFIM_VIGENCIA, SYSDATE + 1) AS DTAFINALVALIDADE,
      CASE 
        WHEN T.DTINATIVACAO IS NULL THEN 'S' ELSE 'N'
      END AS ATIVO,
      T.CODIGO_TRIBUTACAO IDREF
    FROM PCTRIBUTACAO T
  ) CODTRIB
  GROUP BY CODTRIB.CODIGO, CODTRIB.DESCRICAO, CODTRIB.INDTIPOCODIGO, CODTRIB.DTAINICIALVALIDADE, CODTRIB.DTAFINALVALIDADE, CODTRIB.ATIVO, CODTRIB.IDREF
)

\
CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOIMPOSTO AS 
(
  SELECT
    NVL((SELECT SEQCENARIOIMPOSTO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOIMPOSTO
        WHERE SEQIMPOSTO = CCTI.SEQIMPOSTO
        AND ROWNUM = 1), 0) SEQCENARIOIMPOSTO,
    DPTRIB.SEQCENARIO,
    CCTI.SEQIMPOSTO,
    (SELECT CCTC.SEQCODIGOTRIBUTARIO FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO CCTC WHERE TO_CHAR(T.CODIGO_TRIBUTACAO) = CCTC.IDREF AND CCTC.INDTIPOCODIGO = 1) SEQCODTRIBCST,
    (SELECT CCTC.SEQCODIGOTRIBUTARIO FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO CCTC WHERE TO_CHAR(T.CODIGO_TRIBUTACAO) = CCTC.IDREF AND CCTC.INDTIPOCODIGO = 2) SEQCODTRIBCCLASTRIB,
    CASE
      WHEN DPTRIB.TIPO_IMPOSTO = 'IS' THEN
           T.PERC_IS
      WHEN DPTRIB.TIPO_IMPOSTO = 'CBS' THEN
           T.PERC_CBS
      WHEN T.PERC_IBS_MUN IS NOT NULL THEN
           T.PERC_IBS_MUN     
      WHEN  T.PERC_IBS_UF IS NOT NULL THEN
           T.PERC_IBS_UF     
      ELSE NULL
    END PERALIQ,
    
    CASE
      WHEN DPTRIB.TIPO_IMPOSTO = 'CBS' THEN
           T.PERC_RED_CBS
      WHEN T.PERC_IBS_MUN IS NOT NULL THEN
           T.PERC_RED_IBS_MUN     
      WHEN  T.PERC_IBS_UF IS NOT NULL THEN
           T.PERC_RED_IBS_UF     
      ELSE NULL
    END PERALIQRED,
    
    1 SEQFORMULA,
    DPTRIB.ATIVO,
    T.CODIGO_TRIBUTACAO||'-'||CCTI.DESCRICAO IDREF
  FROM PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTIMPOSTO CCTI       
  WHERE DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
  AND   DPTRIB.TIPO_IMPOSTO = CCTI.DESCRICAO
)

  \

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOIMPOSTOMUN AS
(
 SELECT 
    NVL((SELECT SEQCENARIOIMPOSTOMUNICIPIO
      FROM MONITORPDVMIDDLE.TB_CCTCENARIOIMPOSTOMUN
      WHERE SEQCENARIOIMPOSTO = DEPARA.SEQCENARIO
        AND CODIBGE = TRIB.CODIBGE
        AND ROWNUM = 1), 0) SEQCENARIOIMPOSTOMUNICIPIO,
    (SELECT CCTC.SEQCENARIOIMPOSTO FROM MONITORPDVMIDDLE.TB_CCTCENARIOIMPOSTO CCTC WHERE CCTC.SEQCENARIO = DEPARA.SEQCENARIO) SEQCENARIOIMPOSTO,
    TRIB.CODIBGE CODIBGE,
    TRIB.NOMECIDADE CIDADE,
    TRIB.UF UF,
    CASE 
      WHEN DEPARA.TIPO_IMPOSTO = 'CBS' THEN TRIB.PERC_CBS
      WHEN DEPARA.TIPO_IMPOSTO = 'IBS' 
      THEN
        CASE WHEN (TRIB.TIPO_LOCAL_CONSUMO = 'G')
          THEN TRIB.PERC_IBS_UF
          ELSE TRIB.PERC_IBS_MUN				
        END
      ELSE TRIB.PERC_IS
    END PERALIQ,
    CASE 
      WHEN DEPARA.TIPO_IMPOSTO = 'CBS' THEN TRIB.PERC_RED_CBS
      WHEN DEPARA.TIPO_IMPOSTO = 'IBS' 
      THEN
        CASE WHEN (TRIB.TIPO_LOCAL_CONSUMO = 'G')
          THEN TRIB.PERC_RED_IBS_UF
          ELSE TRIB.PERC_RED_IBS_MUN				
        END
      ELSE 0
    END PERALIQRED,	
    '1' AS SEQFORMULA,
    TRIB.ATIVO,
    TRIB.CODIGO_TRIBUTACAO IDREF
  FROM (
    SELECT
      T.CODIGO_TRIBUTACAO,
      C.CODIBGE,
      C.NOMECIDADE,
      C.UF,
      T.TIPO_LOCAL_CONSUMO,
      T.PERC_CBS,
      T.PERC_RED_CBS,
      T.PERC_IBS_UF,
      T.PERC_RED_IBS_UF,
      T.PERC_IBS_MUN,
      T.PERC_RED_IBS_MUN,
      T.PERC_IS,
      CASE WHEN T.DTINATIVACAO IS NULL
        THEN 'S'
        ELSE 'N'
      END AS ATIVO
    FROM PCTRIBUTACAO T
    JOIN PCCIDADE C
      ON 1 = 1
    WHERE
      T.TIPO_LOCAL_CONSUMO = 'G'
      AND T.LOCAL_CONSUMO_GERAL = 'BR'
    
    UNION ALL
    
    SELECT
      T.CODIGO_TRIBUTACAO,
      C.CODIBGE,
      C.NOMECIDADE,
      C.UF,
      T.TIPO_LOCAL_CONSUMO,
      T.PERC_CBS,
      T.PERC_RED_CBS,
      T.PERC_IBS_UF,
      T.PERC_RED_IBS_UF,
      T.PERC_IBS_MUN,
      T.PERC_RED_IBS_MUN,
      T.PERC_IS,
      CASE WHEN T.DTINATIVACAO IS NULL
        THEN 'S'
        ELSE 'N'
      END AS ATIVO
    FROM PCTRIBUTACAO T
    JOIN PCCIDADE C
      ON C.UF = T.LOCAL_CONSUMO_GERAL
    WHERE
      T.TIPO_LOCAL_CONSUMO = 'G'
      AND T.LOCAL_CONSUMO_GERAL <> 'BR'
    
    UNION ALL
    
    SELECT
      T.CODIGO_TRIBUTACAO,
      C.CODIBGE,
      C.NOMECIDADE,
      C.UF,
      T.TIPO_LOCAL_CONSUMO,
      T.PERC_CBS,
      T.PERC_RED_CBS,
      T.PERC_IBS_UF,
      T.PERC_RED_IBS_UF,
      T.PERC_IBS_MUN,
      T.PERC_RED_IBS_MUN,
      T.PERC_IS,
      CASE WHEN T.DTINATIVACAO IS NULL
        THEN 'S'
        ELSE 'N'
      END AS ATIVO
    FROM PCTRIBUTACAO T
    JOIN PCCIDADE C
      ON C.CODIBGE = T.LOCAL_CONSUMO_MUNICIPIO
    WHERE
      T.TIPO_LOCAL_CONSUMO = 'M'
  ) TRIB,
  PCDEPARATRIBUTACAOC5 DEPARA
  WHERE DEPARA.CODIGO_TRIBUTACAO  = TRIB.CODIGO_TRIBUTACAO
)