CREATE OR REPLACE VIEW VW_INT_C5_DEPARATRIBUTACAO AS (
  SELECT 
    DEPARA.SEQCENARIO,
    TRIBUTACAO.CODIGO_TRIBUTACAO,
    TRIBUTACAO.TIPO_IMPOSTO_EXIBIR AS TIPO_IMPOSTO,
    CASE 
      WHEN TRIBUTACAO.DTINATIVACAO IS NULL THEN 'S' 
      ELSE 'N' 
    END AS ATIVO
  FROM (
    SELECT 
      CODIGO_TRIBUTACAO,
      'CBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IS' AS TIPO_IMPOSTO_EXIBIR,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'IS') TRIBUTACAO,
    PCDEPARATRIBUTACAOC5 DEPARA
  WHERE TRIBUTACAO.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO(+)
    AND TRIBUTACAO.TIPO_IMPOSTO_EXIBIR = DEPARA.TIPO_IMPOSTO(+)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIO AS (
  SELECT 
    DEPARA.SEQCENARIO,
    DEPARA.TIPO_IMPOSTO DESCRICAO,
    T.DESCRICAO_TRIBUTACAO ORIENTACAO,
    NVL(T.DTINICIO_VIGENCIA, SYSDATE) DTAINICIALVALIDADE,
    NVL(T.DTFIM_VIGENCIA, SYSDATE + 1) DTAFINALVALIDADE,
    0 TOTALPONTOS,
    CASE WHEN T.DTINATIVACAO IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO,
    T.DTALTERC5
  FROM PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO T,
       (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
         WHERE ATIVO = 'A'
           AND ((UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIO') 
            OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAO'))
        ) D
  WHERE T.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO
    AND NVL(T.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCONDICAO AS
(
  SELECT 1 as SEQCONDICAO, 'PRODUTO' as IDENTIFICADOR, 80 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQCONDICAO, 'FAMILIA' as IDENTIFICADOR, 80 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQCONDICAO, 'NCM' as IDENTIFICADOR, 60 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 4 as SEQCONDICAO, 'CFOP' as IDENTIFICADOR, 50 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 5 as SEQCONDICAO, 'CGO' as IDENTIFICADOR, 40 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 6 as SEQCONDICAO, 'ORIGEM' as IDENTIFICADOR, 30 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 7 as SEQCONDICAO, 'DESTINO' as IDENTIFICADOR, 30 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 8 as SEQCONDICAO, 'UFORIGEM' as IDENTIFICADOR, 20 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 9 as SEQCONDICAO, 'UFDESTINO' as IDENTIFICADOR, 20 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOCONDICAO AS
(
  SELECT 
    MIN(NVL((SELECT SEQCENARIOCONDICAO
          FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
      WHERE SEQCENARIO = C.SEQCENARIO
      AND SEQCONDICAO = CN.SEQCONDICAO
      AND ROWNUM = 1), 0)) SEQCENARIOCONDICAO,
    C.SEQCENARIO,
    CN.SEQCONDICAO,
    MIN(CN.PESOBUSCA) PONTOSBUSCA,
    CASE WHEN MIN(TP.DTINATIVACAO) IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO
  FROM VW_INT_C5_CCTCENARIO C,
       PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO_FILTRO_PRODUTO TP,
       VW_INT_C5_CCTCONDICAO CN
  WHERE C.SEQCENARIO = DEPARA.SEQCENARIO
    AND DEPARA.CODIGO_TRIBUTACAO = TP.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 1
  GROUP BY C.SEQCENARIO, CN.SEQCONDICAO    
  
  UNION ALL
  
  SELECT
    MIN(NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = C.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0)) SEQCENARIOCONDICAO,
    C.SEQCENARIO,
    CN.SEQCONDICAO,
    MIN(CN.PESOBUSCA) PONTOSBUSCA,   
    CASE WHEN MIN(N.DTINATIVACAO) IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO
  FROM VW_INT_C5_CCTCENARIO C,
       PCDEPARATRIBUTACAOC5 DEPARA,
       PCTRIBUTACAO_FILTRO_NCM N,
       VW_INT_C5_CCTCONDICAO CN
  WHERE C.SEQCENARIO = DEPARA.SEQCENARIO
    AND DEPARA.CODIGO_TRIBUTACAO = N.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 3
  GROUP BY C.SEQCENARIO, CN.SEQCONDICAO  

  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = C.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    C.SEQCENARIO,
    CN.SEQCONDICAO,
    CN.PESOBUSCA PONTOSBUSCA,
    C.ATIVO
  FROM VW_INT_C5_CCTCENARIO C,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CN.SEQCONDICAO = 8  
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENCONDITEM AS 
(
  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    TO_CHAR(DEPARA.SEQPRODUTO) VALOR,
    'P' INDTIPOIDENTIDADE,
    'PRODUTO' IDENTIFICADOR,
    CC.SEQCENARIO,
    CASE WHEN N.DTINATIVACAO IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO_FILTRO_PRODUTO N,
       PCDEPARAPRODC5 DEPARA
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = N.CODIGO_TRIBUTACAO
    AND DEPARA.CODPROD = N.CODPROD
    AND DEPARA.ATIVO = 'S'
    AND CC.SEQCONDICAO = 1

  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    TO_CHAR(N.NCM) VALOR,
    'P' INDTIPOIDENTIDADE,
    'NCM' IDENTIFICADOR,
    CC.SEQCENARIO,
        CASE WHEN N.DTINATIVACAO IS NULL
    THEN
      'S'
    ELSE
      'N'
    END ATIVO
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO_FILTRO_NCM N
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = N.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 3

  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    TO_CHAR(NVL(T.LOCAL_CONSUMO_GERAL, 'BR')) VALOR,
    'P' INDTIPOIDENTIDADE,
    'UFORIGEM' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 8
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTIMPOSTO AS
(
  SELECT 1 as SEQIMPOSTO, 'CBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQIMPOSTO, 'IBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQIMPOSTO, 'IS'  as DESCRICAO, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTFORMULA AS
(
  SELECT 1 as SEQFORMULA, 'PADRAO' as DESCRICAO, '[#PRECOPRODUTO] + [#ACRESCIMO] + [#MULTAJUROS] + [#DESCADICIONAL] + [#FRETE] + [#IPI] + [#ST]' as BASE, 'S' as ATIVO FROM PCCONSUM
)