CREATE OR REPLACE VIEW SQL_NFE_PRODUTO_ENTRADA_COMP AS 
SELECT N.NUMTRANSENT AS NUM_TRANSACAO,
       NVL(NVL(N.CODPRODNFAJUSTE,B.CODPRODAJUSTE), LPAD((TO_CHAR(999999) || TO_CHAR((ROWNUM))),7,'0')) CODIGO_PRODUTO,
       DECODE(B.TIPO,'2', 0 ,NVL(N.BASEICST, 0)) AS BASE_ST,
       DECODE(B.TIPO,'2',0,NVL(N.VLST, 0)) AS VALOR_ST,
       B.CODFISCAL CFOP,
       DECODE(N.FINALIDADENFE, 'A', NVL(NVL(N.NCMNFAJUSTE,B.NCMPRODAJUSTE),'00'),

       (SELECT REPLACE(PCPRODUT.NBM,'.','')FROM PCPRODUT
        WHERE PCPRODUT.DTEXCLUSAO IS NULL AND NBM IS NOT NULL
        AND ROWNUM = 1)) AS NCM,

       DECODE((NVL(B.TIPO,'1')),'2',0 ,B.ALIQUOTA) ALIQUOTA_ICMS,
       DECODE((NVL(B.TIPO,'1')),'2',B.ALIQUOTA,0) ALIQUOTA_IPI,

       NVL(NVL(N.VLTOTBRUTOPRODAJUSTE,B.VLTOTPRODAJUSTE),
             GREATEST((NVL(N.VLTOTAL, 0) - NVL(N.VLST,0) - NVL(N.VLIPI,0)),0))
       AS VALOR_PRODUTOS,
       DECODE(NVL(B.TIPO,'1'),'1',NVL(B.VLBASE,0),0) BASE_ICMS,
       DECODE(NVL(B.TIPO,'1'),'1',NVL(B.VLICMS,0),0) VALOR_ICMS,
       DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLBASE,0),0) BASE_IPI,
       DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLICMS,0),0) VALOR_IPI,
       NVL(B.SITTRIBUT, 90) AS SITUACAO_TRIBUTARIA,
       NVL(B.SITTRIBUTIPI, 99) AS SITUACAO_TRIBUTARIA_IPI,
       NVL(NVL(N.UNIDADENFAJUSTE,B.UNIDADEPRODAJUSTE),'UN') AS UNIDADENFAJUSTE,
       NVL(NVL(NVL(N.DESCRICAOPRODNFAJUSTE,B.DESCRICAOPRODAJUSTE),
          (SELECT MIN(C.COMPLEMENTO1) FROM PCCOMPLEMENTO C WHERE C.NOMETABELA = 'PCNFENT'
           AND C.NUMTRANS = N.NUMTRANSENT)),
           'ITEM ' || DECODE(N.FINALIDADENFE, 'A', 'DE AJUSTE', 'COMPLEMENTAR')) AS DESCRICAO,
       0 AS VALOR_IPI_OUTROS,
       NVL(N.VLFRETE,0) AS VALOR_FRETE,
       NVL(N.VLOUTRAS,0) AS VALOR_OUTROS,
       NVL(N.VLDESCONTO,0) AS VALOR_DESCONTO,
       NULL AS TIPO_PRESENCA_ADQUIRINTE,
       N.CSTPISCOFINSNFAJUSTE AS SIT_PIS_CONFINS,
       CASE WHEN (N.FINALIDADENFE = 'C') OR (N.FINALIDADENFE = 'A') THEN
       (SELECT MAX(MC.CODCEST) FROM PCMOV M, PCMOVCOMPLE MC
       WHERE M.NUMTRANSITEM = MC.NUMTRANSITEM AND M.NUMTRANSVENDA = N.NUMTRANSVENDAORIG) 
       ELSE
       NULL
       END AS CODCEST
      ,B.CSTIBSCBS
      ,B.CCLASSTRIB
      ,NVL(B.VBC,0) AS VBC
      ,NVL(B.PIBSUF,0) AS PIBSUF
      ,NVL(B.VIBSUF,0) AS VIBSUF
      ,NVL(B.PIBSMUN,0) AS PIBSMUN
      ,NVL(B.VIBSMUN,0) AS VIBSMUN
      ,NVL(B.PCBS,0) AS PCBS
      ,NVL(B.VCBS,0) AS VCBS
      ,NVL(B.PREDALIQ_IBSUF,0) AS PREDALIQ_IBSUF
      ,NVL(B.PALIQEFET_IBSUF,0) AS PALIQEFET_IBSUF
      ,NVL(B.PREDALIQ_IBSMUN,0) AS PREDALIQ_IBSMUN
      ,NVL(B.PALIQEFET_IBSMUN,0) AS PALIQEFET_IBSMUN
      ,NVL(B.PREDALIQ_CBS,0) AS PREDALIQ_CBS
      ,NVL(B.PALIQEFET_CBS,0) AS PALIQEFET_CBS         
  FROM PCNFBASE B,
       PCNFENT  N
  WHERE N.NUMTRANSENT = B.NUMTRANSENT
  AND N.ESPECIE IN('NF','NE','EI')
