DECLARE
  vDELETOU BOOLEAN;
BEGIN
  vDELETOU := TRUE;
  
  BEGIN
    DELETE FROM PCFORMULATIPO WHERE CODTIPOFORMULA = 18;
  EXCEPTION
    WHEN OTHERS THEN vDELETOU := FALSE;
  END;
  
  IF vDELETOU THEN 
    INSERT INTO PCFORMULATIPO  (CODTIPOFORMULA, DESCRICAO, DTCADASTRO) VALUES (18,'ICMS_A_RECOLHER',SYSDATE);
  END IF;
  
  vDELETOU := TRUE;
  
  BEGIN
    DELETE FROM PCFORMULA WHERE CODFORMULA = 'ICMS_PADRAO';
  EXCEPTION
    WHEN OTHERS THEN vDELETOU := FALSE;  
  END;
  
  IF vDELETOU THEN   
    INSERT INTO PCFORMULA (CODFORMULA, DESCRICAO, FORMULA, CODTIPOFORMULA, DTCADASTRO)
       VALUES ('ICMS_PADRAO', 
               'Retorna a formula de calculo de Icms padrão para somar na base de CBS/IBS', 
               '(([PTABELASEMIMPOSTO1] + [VLFRETE] + [VLOUTRASDESP]) * ([PERC_REDUCAO_ICMS]/100)) * ([PERC_ICMS]/100)', 18, SYSDATE);
  END IF;

  UPDATE PCTRIBUT SET FORMULAICMS = 'ICMS_PADRAO' WHERE FORMULAICMS IS NULL;
  
  COMMIT WORK;
END;