DECLARE

BEGIN
  INSERT INTO PCFORMULA (CODFORMULA, DESCRICAO, FORMULA, CODTIPOFORMULA, DTCADASTRO)
     VALUES ('ICMS_PADRAO', 'Retorna a formula de calculo de Icms padrão para somar na base de CBS/IBS', '(([PTABELASEMIMPOSTO1] + [VLFRETE] + [VLOUTRASDESP]) * ([PERC_REDUCAO_ICMS]/100)) * ([PERC_ICMS]/100)', 18, SYSDATE);

  UPDATE PCTRIBUT SET FORMULAICMS = 'ICMS_PADRAO' WHERE FORMULAICMS IS NULL;
END;