DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_NFE_RODAPE'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_NFE_RODAPE';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_NFE_RODAPE AS OBJECT
 (
    ANTT                 VARCHAR2(20),
    BASE_ICMS            NUMBER,
    BASE_ICMS_ST         NUMBER,
    BASE_ISS             NUMBER,
    DTENTREGA            DATE,
    CIDADE_TRANSPORTADOR VARCHAR2(80),
    CODMOTORISTA         NUMBER,
    CNPJ_TRANSPORTADOR   VARCHAR2(20),
    END_TRANSPORTADOR    VARCHAR2(300),
    ESPECIEVOLUME        VARCHAR2(100),
    ESTADO_TRANSPORTADOR VARCHAR2(2),
    IE_TRANSPORTADOR     VARCHAR2(20),
    MARCAVOLUME          VARCHAR2(100),
    MODALIDADE_FRETE     NUMBER,
    NOME_MOTORISTA       VARCHAR2(40),
    NUMCAR               NUMBER,
    NUM_VOLUME           NUMBER,
    NUMVOL               NUMBER,
    NUMVOLUMESCONFERENCIA NUMBER,
    VOLUME_PEDIDO        NUMBER,
    PESO_BRUTO           NUMBER,
    PESO_LIQUIDO         NUMBER,
    PLACA                VARCHAR2(10),
    PLACA_UF             VARCHAR2(2),
    TRANSPORTADOR        VARCHAR2(60),
    VALOR_COFINS         NUMBER,
    VALOR_DESCONTO       NUMBER,
    VLDESCRODAPE         NUMBER,
    VALOR_FRETE          NUMBER,
    VALOR_ICMS           NUMBER,
    VALOR_ICMS_ST        NUMBER,
    VALOR_IPI            NUMBER,
    VALOR_II             NUMBER,
    VALOR_ISS            NUMBER,
    VALOR_OUTRO          NUMBER,
    VALOR_PIS            NUMBER,
    VALOR_TOTAL          NUMBER,
    VALOR_TOTAL_PRODUTOS NUMBER,
    NVOL                 VARCHAR2(20),
    INFOADICIONALFISCO   VARCHAR2(2000),
    NUM_VOLUME_EMB       NUMBER,
    DESC_PL_PAGTO        VARCHAR2(40),
    VLTOTALIMPOSTOS      NUMBER,
    VALOR_TOTAL_SEGURO   NUMBER,
    VALOR_TOTAL_DESONERADO  NUMBER(18,6),
    VLFCPPART            NUMBER(22,2),
    VLICMSPARTDEST       NUMBER(22,2),
    VLICMSPARTREM        NUMBER(22,2),
    VLBASEFCPICMS       NUMBER(18,6),
    VLBASEFCPST         NUMBER(18,6),
    VLBCFCPSTRET          NUMBER(18,6),
    VLFCPSTRET            NUMBER(18,6),
    VLCREDFCPICMSSN     NUMBER(18,6),
    VLFECP               NUMBER(18,6), 
    VLACRESCIMOFUNCEP    NUMBER(18,6), 
    VALOR_IPI_DEVOLVIDO  NUMBER(18,6), 
    DATACONSOLIDACAOPREFAT   DATE, 
    PREFATURAMENTO           VARCHAR2(1), 
    VALOR_SERVICO_TRANSP         NUMBER(10,2), 
    BASE_RETENCAO_ICMS_TRANSP  NUMBER(10,2), 
    PERC_RETENCAO_ICMS_TRANSP  NUMBER(10,2), 
    VALOR_RETENCAO_ICMS_TRANSP   NUMBER(10,2), 
    CFOP_TRANSP                NUMBER(8), 
    COD_MUN_FATO_GERADOR_TRANSP NUMBER(10),
    FINALIDADENFE VARCHAR2(2),
    GERAGRPRETTRIB           VARCHAR2(1),    
    VLPISRETORGPUB           NUMBER(18,6),
    VLCOFINSRETORGPUB        NUMBER(18,6),
    VLCSLLRETORGPUB          NUMBER(18,6),
    VLIRPJRETORGPUB          NUMBER(18,6),
    VLBCIRRFRETORGPUB        NUMBER(18,6),
    QBCMONO                  NUMBER(22,10),
    VICMSMONO                NUMBER(22,10),
    QBCMONORETEN             NUMBER(22,10),
    VICMSMONORETEN           NUMBER(22,10),
    QBCMONODIF               NUMBER(22,10), 
    VICMSMONODIF             NUMBER(22,10),
    QBCMONORET               NUMBER(22,10),   
    VICMSMONORET             NUMBER(22,10)
 )