DECLARE
  vEXEC VARCHAR(4000);
BEGIN
  -- Drop materialized view if exists
  BEGIN
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW VW_INT_C5_EMBPROD_MAT';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  -- Create materialized view
  vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_EMBPROD_MAT REFRESH FORCE ON DEMAND AS SELECT * FROM VW_INT_C5_EMBPROD';
  EXECUTE IMMEDIATE vEXEC;

  -- Drop and create index 1
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX1';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX1 ON VW_INT_C5_EMBPROD_MAT (CODFILIAL, CODAUXILIAR)';

  -- Drop and create index 2
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX2';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX2 ON VW_INT_C5_EMBPROD_MAT (CODFILIAL, codprod)';

  -- Drop and create index 3
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX3';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX3 ON VW_INT_C5_EMBPROD_MAT(CODFILIAL, codprod, codauxiliar)';

  -- Drop and create index 4
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX4';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX4 ON VW_INT_C5_EMBPROD_MAT(CODFILIAL, codprod, codauxiliar, qtunit)';

  -- Drop and create index 5
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX5';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX5 ON VW_INT_C5_EMBPROD_MAT(codprod, descricao)';

  -- Drop and create index 6
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX6';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX6 ON VW_INT_C5_EMBPROD_MAT(codprod, codauxiliar)';

  -- Drop and create index 7
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX VW_INT_C5_EMBPROD_MAT_IDX7';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
  EXECUTE IMMEDIATE 'CREATE INDEX VW_INT_C5_EMBPROD_MAT_IDX7 ON VW_INT_C5_EMBPROD_MAT(codprod, codauxiliar, qtunit)';

END;
