DECLARE
  vEXEC VARCHAR(4000);
  vCONT NUMBER;
  vContColunasOriginal number;
  vContColunasMaterializada number;
BEGIN
 
 BEGIN
   SELECT COUNT(1)
	INTO vCONT
   FROM USER_OBJECTS A
   WHERE A.OBJECT_NAME = 'VW_INT_C5_EMBPROD_MAT';
 END;
 
 IF vCont > 0 THEN
   SELECT COUNT(*) into vContColunasOriginal FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'VW_INT_C5_EMBPROD';
   SELECT COUNT(*) into vContColunasMaterializada FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'VW_INT_C5_EMBPROD_MAT';
   
   IF vContColunasOriginal <> vContColunasMaterializada THEN
      BEGIN
        EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW VW_INT_C5_EMBPROD_MAT';
        vCont := 0; 
      EXCEPTION
        WHEN OTHERS THEN
        BEGIN
          NULL;
        END;  
      END;
   END IF;
 END IF; 

 IF vCONT = 0 THEN
  
  --vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_EMBPROD_MAT REFRESH FORCE ON DEMAND AS SELECT * FROM VW_INT_C5_EMBPROD where rownum = 1';
  BEGIN
    vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_EMBPROD_MAT BUILD DEFERRED REFRESH FORCE ON DEMAND AS SELECT * from VW_INT_C5_EMBPROD';   
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;
  

  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX1 on VW_INT_C5_EMBPROD_MAT (CODFILIAL, CODAUXILIAR)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  
  
  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX2 on VW_INT_C5_EMBPROD_MAT (CODFILIAL, codprod)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX3 on VW_INT_C5_EMBPROD_MAT(CODFILIAL, codprod, codauxiliar)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX4 on VW_INT_C5_EMBPROD_MAT(CODFILIAL, codprod, codauxiliar, qtunit)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX5 on VW_INT_C5_EMBPROD_MAT(codprod, descricao)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX6 on VW_INT_C5_EMBPROD_MAT(codprod, codauxiliar)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_EMBPROD_MAT_IDX7 on VW_INT_C5_EMBPROD_MAT(codprod, codauxiliar, qtunit)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;
 END IF; 
END;