DECLARE

BEGIN
  DELETE FROM PCRESTRICAOAVANCADACONFIG;

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (1, 'PCPRODUT', 'CODPROD', 'NUMBER', 'Produto', 'N', 'PCPRODUT', 'CODPROD', 'DESCRICAO', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (2, 'PCPRODUT', 'CODFORNEC', 'NUMBER', ' Fornecedor', 'N', 'PCFORNEC', 'CODFORNEC', 'FORNECEDOR', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (3, 'PCPRODUT', 'CODEPTO', 'NUMBER', ' Departamento', 'N', 'PCDEPTO', 'CODEPTO', 'DESCRICAO', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (4, 'PCPRODUT', 'CODSEC', 'NUMBER', 'Seção', 'N', 'PCSECAO', 'CODSEC', 'DESCRICAO', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (5, 'PCPRODUT', 'CODCATEGORIA', 'NUMBER', 'Categoria', 'N', 'PCCATEGORIA', 'CODCATEGORIA', 'CATEGORIA', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (6, 'PCPRODUT', 'CODLINHAPROD', 'NUMBER', 'Linha de Produto', 'N', 'PCLINHAPROD', 'CODLINHA', 'DESCRICAO', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (7, 'PCPRODUT', 'TIPOMERC', 'VARCHAR2', 'Tipo de Mercadoria', 'N', NULL, NULL, NULL, 'TIPOMERCADORIA', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (8, 'PCPRODUT', 'NBM', 'VARCHAR2', 'NCM', 'N', 'PCNCM', 'CODNCM', 'DESCRICAO', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (9, 'PCPRODUT', 'CODPRODPRINC', 'NUMBER', 'Produto Principal', 'N', 'PCPRODUT', 'CODPROD', 'DESCRICAO', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (10, 'PCPRODUT', 'CLASSEVENDA', 'VARCHAR2', 'Classe de Venda (Produto)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (11, 'PCPRODUT', 'TIPOESTOQUE', 'VARCHAR2', 'Tipo de Estoque', 'N', NULL, NULL, NULL, 'TIPOESTOQUE', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (12, 'PCPRODUT', 'GRUPOFATURAMENTO', 'VARCHAR2', 'Grupo de Faturamento', 'N', NULL, NULL, NULL, 'GRUPOFATURAMENTO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (13, 'PCPRODUT', 'TIPOMEDICAMENTO', 'VARCHAR2', 'Tipo de Medicamento', 'N', NULL, NULL, NULL, 'TIPOMEDICAMENTO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (14, 'PCPRODUT', 'CODMARCA', 'NUMBER', 'Marca', 'N', 'PCMARCA', 'CODMARCA', 'MARCA', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (15, 'PCPRODUT', 'CODSUBMARCA', 'NUMBER', 'Sub-Marca', 'N', 'PCSUBMARCA', 'CODSUBMARCA', 'DESCSUBMARCA', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (16, 'PCPRODUT', 'OBS2', 'VARCHAR2', 'Fora de Linha', 'N', NULL, NULL, NULL, 'FORALINHA', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (17, 'PCPRODUT', 'CODSUBCATEGORIA', 'NUMBER', 'Sub-Categoria', 'N', 'PCSUBCATEGORIA', 'CODSUBCATEGORIA', 'SUBCATEGORIA', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (18, 'PCPRODUT', 'DTCADASTRO', 'DATE', 'Data de Cadastro (Produto)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (19, 'PCPRODUT', 'CLASSE', 'VARCHAR2', 'Classe do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (20, 'PCPRODUT', 'VOLUME', 'NUMBER', 'Volume do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (21, 'PCPRODUT', 'PESOBRUTO', 'NUMBER', 'Peso Bruto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (22, 'PCPRODUT', 'PESOLIQ', 'NUMBER', 'Peso Líquido', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (23, 'PCPRODUT', 'PSICOTROPICO', 'VARCHAR2', 'Psicotrópico?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (24, 'PCPRODUT', 'RETINOICO', 'VARCHAR2', 'Retinóico', 'N', NULL, NULL, NULL, 'RETINOICO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (25, 'PCPRODUT', 'FARMACIAPOPULAR', 'VARCHAR2', 'Produto Farmácia Popular?', 'N', NULL, NULL, NULL, 'FARMACIAPOPULAR', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (26, 'PCPRODUT', 'CODAUXILIAR', 'NUMBER', 'Código de Barras de Venda', 'N', 'PCEMBALAGEM', 'CODAUXILIAR', 'EMBALAGEM', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (27, 'PCPRODFILIAL', 'FABRICANTE', 'VARCHAR2', 'Fabricante', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', NULL, 96, 'I', 'CODPROD;CODFILIAL');

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (28, 'PCPRODFILIAL', 'SUBCLASSE', 'VARCHAR2', 'Sub-Classe do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', NULL, 96, 'I', 'CODPROD;CODFILIAL');

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (29, 'VW_GRUPOSCAMPANHA_PRODUTO', 'CODGRUPO', 'NUMBER', 'Grupo de Produto', 'N', 'VW_GRUPOSCAMPANHA_PRODUTO', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Produto', NULL, 96, 'I', 'CODPROD;CODFILIAL');

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (30, 'PCCLIENT', 'CODCLI', 'NUMBER', 'Cliente', 'N', 'PCCLIENT', 'CODCLI', 'CLIENTE', NULL, 'S', 'S', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (31, 'PCCLIENT', 'CODBAIRROENT', 'NUMBER', 'Bairro', 'N', 'PCBAIRRO', 'CODBAIRRO', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (32, 'PCCLIENT', 'CLASSEVENDA', 'VARCHAR2', 'Classe de Venda (Cliente)', 'N', NULL, NULL, NULL, 'CLASSEVENDA', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (33, 'PCCLIENT', 'CODATV1', 'NUMBER', 'Atividade', 'N', 'PCATIVI', 'CODATIV', 'RAMO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (34, 'PCCLIENT', 'CODCIDADE', 'NUMBER', 'Cidade', 'N', 'PCCIDADE', 'CODCIDADE', 'NOMECIDADE', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (35, 'PCCLIENT', 'CODCLIPRINC', 'NUMBER', 'Cliente Principal', 'N', 'PCCLIENT', 'CODCLI', 'CLIENTE', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (36, 'PCCLIENT', 'CODCNAE', 'VARCHAR2', 'CNAE', 'N', 'PCCNAE', 'CODCNAE', 'DESCCNAE', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (37, 'PCCLIENT', 'CODCONDCOMERCIAL', 'VARCHAR2', 'Condição Comercial (Indústria)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (38, 'PCCLIENT', 'CODPRACA', 'NUMBER', 'Praça', 'N', 'PCPRACA', 'CODPRACA', 'PRACA', NULL, 'S', 'S', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (39, 'PCCLIENT', 'CODREDE', 'NUMBER', 'Rede de Cliente', 'N', 'PCREDECLIENTE', 'CODREDE', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (40, 'PCCLIENT', 'CONSUMIDORFINAL', 'VARCHAR2', 'Consumidor Final?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (41, 'PCCLIENT', 'CONTRIBUINTE', 'VARCHAR2', 'Contribuinte?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (42, 'PCCLIENT', 'TIPOFJ', 'VARCHAR2', 'Tipo de Pessoa', 'N', NULL, NULL, NULL, 'TIPOPESSOA', 'S', 'S', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (43, 'PCCLIENT', 'DTCADASTRO', 'DATE', 'Data de Cadastro (Cliente)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (44, 'PCCLIENT', 'DTVALIDADECONV', 'DATE', 'Dt. Val. do Convênio', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (45, 'PCCLIENT', 'DTVALIDADEIBAMA', 'DATE', 'Dt. Val. do Registro no IBAMA', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (46, 'PCCLIENT', 'DTVENCALVARA', 'DATE', 'Dt. Venc. Alvará do Psicotrópicos', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (47, 'PCCLIENT', 'DTVENCALVARAANVISA', 'DATE', 'Dt. Venc. Alvará da ANVISA', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (48, 'PCCLIENT', 'DTVENCALVARAFUNC', 'DATE', 'Dt. Venc. Alvará de Funcionamento', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (49, 'PCCLIENT', 'DTVENCALVARARETINOICO', 'DATE', 'Dt Venc. Alvará do Retinóico', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (50, 'PCCLIENT', 'DTVENCALVARASUS', 'DATE', 'Dt. Venc. Alvará do SUS', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (51, 'PCCLIENT', 'DTVENCCRF', 'DATE', 'Dt. Venc. Alvará do CRF', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (52, 'PCCLIENT', 'DTVENCSUFRAMA', 'DATE', 'Dt. Venc. Suframa', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (53, 'PCCLIENT', 'ESTENT', 'VARCHAR2', 'UF do Estado', 'N', 'PCESTADO', 'UF', 'ESTADO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (54, 'PCCLIENT', 'ORGAOPUB', 'VARCHAR2', 'Orgão Público Estadual?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (55, 'PCCLIENT', 'ORGAOPUBFEDERAL', 'VARCHAR2', 'Orgão Público Federal?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (56, 'PCCLIENT', 'ORGAOPUBMUNICIPAL', 'VARCHAR2', 'Orgão Público Municipal?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (57, 'PCCLIENT', 'PARTICIPAFARMACIAPOPULAR', 'VARCHAR2', 'Participa da Farmácia Popular?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (58, 'PCCLIENT', 'TIPOEMPRESA', 'VARCHAR2', 'Tipo de Empresa', 'N', NULL, NULL, NULL, 'TIPOEMPRESA', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (59, 'PCCLIENT', 'TIPOCLIMED', 'VARCHAR2', 'Tipo do Ramo de Medicamentos', 'N', NULL, NULL, NULL, 'TIPOCLIMED', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (60, 'PCCLIENT', 'USADEBCREDRCA', 'VARCHAR2', 'Usa Débito e Crédito de RCA?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (61, 'PCCLIENT', 'LIMCRED', 'NUMBER', 'Limite de Crédito', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (62, 'PCCLIENT', 'CODPLPAG', 'NUMBER', 'Plano de Pagamento (Nível de Venda - Cliente)', 'N', 'PCPLPAG', 'CODPLPAG', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (63, 'PCCLIENT', 'CLIENTEMONITORADO', 'VARCHAR2', 'Cliente Monitorado?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (64, 'PCCLIENT', 'USACRECLIFAT', 'VARCHAR2', 'Cliente Utiliza Créd. Faturamento?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (65, 'PCCLIENT', 'CODUSUR1', 'NUMBER', 'RCA 1 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (66, 'PCCLIENT', 'CODUSUR2', 'NUMBER', 'RCA 2 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (67, 'PCCLIENT', 'CODUSUR3', 'NUMBER', 'RCA 3 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (68, 'VW_GRUPOSCAMPANHA_CLIENTE', 'CODGRUPO', 'NUMBER', 'Grupo de Cliente', 'N', 'VW_GRUPOSCAMPANHA_CLIENTE', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', NULL, 97, 'I', 'CODCLI;CODFILIAL');

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (69, 'PCPEDC', 'VLTOTAL', 'NUMBER', 'Valor Total do Pedido', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Pedido', 'VLTOTAL', NULL, 'C', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (70, 'PCPEDC', 'ORIGEMPED', 'VARCHAR2', 'Origem do Pedido', 'N', NULL, NULL, NULL, 'ORIGEMPEDIDO', 'N', 'N', 'Pedido', 'ORIGEMPED', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (71, 'PCPEDC', 'FRETEDESPACHO', 'VARCHAR2', 'Tipo de Frete', 'N', NULL, NULL, NULL, 'TIPOFRETE', 'N', 'N', 'Pedido', 'FRETEDESPACHO', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (72, 'PCPEDC', 'CONDVENDA', 'VARCHAR2', 'Condição de Venda', 'N', NULL, NULL, NULL, 'CONDVENDA', 'S', 'S', 'Pedido', 'CONDVENDA', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (73, 'PCPEDC', 'CODPLPAG', 'NUMBER', 'Plano de Pagamento (Pedido)', 'N', 'PCPLPAG', 'CODPLPAG', 'DESCRICAO', NULL, 'S', 'S', 'Pedido', 'CODPLPAG', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (74, 'PCPEDC', 'CODCOB', 'VARCHAR2', 'Cobrança', 'N', 'PCCOB', 'CODCOB', 'COBRANCA', NULL, 'S', 'S', 'Pedido', 'CODCOB', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (75, 'PCPEDC', 'CODFILIALNF', 'VARCHAR2', 'Filial (Pedido)', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'N', 'N', 'Pedido', 'CODFILIALNF', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (76, 'PCPEDC', 'CODUSUR', 'NUMBER', 'RCA (Pedido)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'S', 'S', 'Pedido', 'CODUSUR', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (77, 'VW_GRUPOSCAMPANHA_RCA', 'CODGRUPO', 'NUMBER', 'Grupo de RCA', 'N', 'VW_GRUPOSCAMPANHA_RCA', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Pedido', NULL, 98, 'I', 'CODUSUR;CODFILIAL');

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (78, 'PCPEDI', 'PVENDA', 'NUMBER', 'Preço de Venda', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Item do Pedido', 'PVENDA', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (79, 'PCPEDI', 'QT', 'NUMBER', 'Quantidade do item', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Item do Pedido', 'QT', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (80, 'PCPEDI', 'SUBTOTAL', 'NUMBER', 'Subtotal do Item', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Item do Pedido', 'SUBTOTAL', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (81, 'PCPEDI', 'CODFILIALRETIRA', 'VARCHAR2', 'Filial Retira', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'S', 'S', 'Item do Pedido', 'CODFILIALRETIRA', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (82, 'PCPEDI', 'CODST', 'NUMBER', 'Figura Tributária', 'N', 'PCTRIBUT', 'CODST', 'MENSAGEM', NULL, 'N', 'N', 'Item do Pedido', 'CODST', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (83, 'PCPEDI', 'CODLINHAPRAZO', 'NUMBER', 'Linha de Prazo', 'N', 'PCLINHAPRAZO', 'CODLINHAPRAZO', 'DESCRICAO', NULL, 'N', 'N', 'Item do Pedido', 'CODLINHAPRAZO', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (84, 'PCPEDC', 'CODFILIAL', 'VARCHAR2', 'Filial', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'S', 'S', 'Pedido', 'CODFILIAL', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (85, 'PCPEDC', 'NUMREGIAO', 'NUMBER', 'Região', 'N', 'PCREGIAO', 'NUMREGIAO', 'REGIAO', NULL, 'S', 'S', 'Pedido', 'NUMREGIAO', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (86, 'PCUSUARI', 'CODSUPERVISOR', 'NUMBER', 'Supervisor', 'N', 'PCSUPERV', 'CODSUPERVISOR', 'NOME', NULL, 'N', 'N', 'Pedido', 'CODUSUR', 76, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (87, 'PCSUPERV', 'CODGERENTE', 'NUMBER', 'Gerente', 'N', 'PCGERENTE', 'CODGERENTE', 'NOMEGERENTE', NULL, 'N', 'N', 'Pedido', 'CODUSUR', 86, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (88, 'CALCULADO', 'MARGEMMINIMA', 'NUMBER', 'Margem Mínima', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'MARGEMMINIMA', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (89, 'CALCULADO', 'MOVCONTACORRENTEITEM', 'NUMBER', 'Mov. Conta Corrente por Item (Valor / Percentual)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'MOVCONTACORRENTEITEM', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (90, 'CALCULADO', 'MOVCONTACORRENTEPED', 'NUMBER', 'Mov. Conta Corrente por Pedido (Valor / Percentual)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'MOVCONTACORRENTEPED', NULL, 'C', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (91, 'CALCULADO', 'PERCVALORBONIFICADO', 'NUMBER', '% Valor Bonificado', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCVALORBONIFICADO', NULL, 'C', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (92, 'CALCULADO', 'PERCDESCONTOMEDIO', 'NUMBER', '% Desconto Médio', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCDESCONTOMEDIO', NULL, 'C', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (93, 'CALCULADO', 'PERCDESCONTOITEM', 'NUMBER', '% Desconto Item', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCDESCONTOITEM', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (94, 'CALCULADO', 'ESTOQUEMINIMO', 'NUMBER', 'Estoque Mínimo', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'ESTOQUEMINIMO', NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (95, 'CALCULADO', 'PERCCOMPOSICAO', 'NUMBER', '% Composição', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCCOMPOSICAO', NULL, 'C', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (96, 'NIVEL', 'CODPROD, CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (97, 'NIVEL', 'CODCLI,CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL);

  INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
  VALUES (98, 'NIVEL', 'CODUSUR,CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL);      
END;