DECLARE

BEGIN
  DELETE FROM PCRESTRICAOAVANCADACONFIG WHERE CODCONFIG IN(69, 88, 89, 90, 91, 92, 93, 94, 95);

  MERGE INTO PCRESTRICAOAVANCADACONFIG tgt
  USING (
    SELECT 1 AS CODCONFIG
         , 'PCPRODUT' AS TABELA
         , 'CODPROD' AS CAMPO
         , 'NUMBER' AS TIPOCAMPO
         , 'Produto' AS NOMELIVRE
         , 'N' AS VISIVELFILTRO
         , 'PCPRODUT' AS TABELAPESQUISA
         , 'CODPROD' AS CAMPOPESQUISA
         , 'DESCRICAO' AS DESCRICAOPESQUISA
         , NULL AS CODROTULO
         , 'S' AS CONDICAO
         , 'S' AS REGRAEXCECAO
         , 'Produto' AS GRUPO
         , 'CODPROD' AS NOMEPARAMETRO
         , 1 AS CODIGONIVEL
         , 'I' AS TIPOVALIDACAO
         , NULL AS CHAVEMULTIPLA
      FROM DUAL UNION ALL
    SELECT 2, 'PCPRODUT', 'CODFORNEC', 'NUMBER', 'Fornecedor', 'N', 'PCFORNEC', 'CODFORNEC', 'FORNECEDOR', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 3, 'PCPRODUT', 'CODEPTO', 'NUMBER', 'Departamento', 'N', 'PCDEPTO', 'CODEPTO', 'DESCRICAO', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 4, 'PCPRODUT', 'CODSEC', 'NUMBER', 'Seção', 'N', 'PCSECAO', 'CODSEC', 'DESCRICAO', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 5, 'PCPRODUT', 'CODCATEGORIA', 'NUMBER', 'Categoria', 'N', 'PCCATEGORIA', 'CODCATEGORIA', 'CATEGORIA', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 6, 'PCPRODUT', 'CODLINHAPROD', 'NUMBER', 'Linha de Produto', 'N', 'PCLINHAPROD', 'CODLINHA', 'DESCRICAO', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 7, 'PCPRODUT', 'TIPOMERC', 'VARCHAR2', 'Tipo de Mercadoria', 'N', NULL, NULL, NULL, 'TIPOMERCADORIA', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 8, 'PCPRODUT', 'NBM', 'VARCHAR2', 'NCM', 'N', 'PCNCM', 'CODNCM', 'DESCRICAO', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 9, 'PCPRODUT', 'CODPRODPRINC', 'NUMBER', 'Produto Principal', 'N', 'PCPRODUT', 'CODPROD', 'DESCRICAO', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 10, 'PCPRODUT', 'CLASSEVENDA', 'VARCHAR2', 'Classe de Venda (Produto)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 11, 'PCPRODUT', 'TIPOESTOQUE', 'VARCHAR2', 'Tipo de Estoque', 'N', NULL, NULL, NULL, 'TIPOESTOQUE', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 12, 'PCPRODUT', 'GRUPOFATURAMENTO', 'VARCHAR2', 'Grupo de Faturamento', 'N', NULL, NULL, NULL, 'GRUPOFATURAMENTO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 13, 'PCPRODUT', 'TIPOMEDICAMENTO', 'VARCHAR2', 'Tipo de Medicamento', 'N', NULL, NULL, NULL, 'TIPOMEDICAMENTO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 14, 'PCPRODUT', 'CODMARCA', 'NUMBER', 'Marca', 'N', 'PCMARCA', 'CODMARCA', 'MARCA', NULL, 'S', 'S', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 15, 'PCPRODUT', 'CODSUBMARCA', 'NUMBER', 'Sub-Marca', 'N', 'PCSUBMARCA', 'CODSUBMARCA', 'DESCSUBMARCA', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 16, 'PCPRODUT', 'OBS2', 'VARCHAR2', 'Fora de Linha', 'N', NULL, NULL, NULL, 'FORALINHA', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 17, 'PCPRODUT', 'CODSUBCATEGORIA', 'NUMBER', 'Sub-Categoria', 'N', 'PCSUBCATEGORIA', 'CODSUBCATEGORIA', 'SUBCATEGORIA', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 18, 'PCPRODUT', 'DTCADASTRO', 'DATE', 'Data de Cadastro (Produto)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 19, 'PCPRODUT', 'CLASSE', 'VARCHAR2', 'Classe do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 20, 'PCPRODUT', 'VOLUME', 'NUMBER', 'Volume do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 21, 'PCPRODUT', 'PESOBRUTO', 'NUMBER', 'Peso Bruto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 22, 'PCPRODUT', 'PESOLIQ', 'NUMBER', 'Peso Líquido', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 23, 'PCPRODUT', 'PSICOTROPICO', 'VARCHAR2', 'Psicotrópico?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 24, 'PCPRODUT', 'RETINOICO', 'VARCHAR2', 'Retinóico', 'N', NULL, NULL, NULL, 'RETINOICO', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 25, 'PCPRODUT', 'FARMACIAPOPULAR', 'VARCHAR2', 'Produto Farmácia Popular?', 'N', NULL, NULL, NULL, 'FARMACIAPOPULAR', 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 26, 'PCPRODUT', 'CODAUXILIAR', 'NUMBER', 'Código de Barras de Venda', 'N', 'PCEMBALAGEM', 'CODAUXILIAR', 'EMBALAGEM', NULL, 'N', 'N', 'Produto', 'CODPROD', 1, 'I', NULL FROM DUAL UNION ALL
    SELECT 27, 'PCPRODFILIAL', 'FABRICANTE', 'VARCHAR2', 'Fabricante', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', NULL, 96, 'I', 'CODPROD;CODFILIAL' FROM DUAL UNION ALL
    SELECT 28, 'PCPRODFILIAL', 'SUBCLASSE', 'VARCHAR2', 'Sub-Classe do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Produto', NULL, 96, 'I', 'CODPROD;CODFILIAL' FROM DUAL UNION ALL
    SELECT 29, 'VW_GRUPOSCAMPANHA_PRODUTO', 'CODGRUPO', 'NUMBER', 'Grupo de Produto', 'N', 'VW_GRUPOSCAMPANHA_PRODUTO', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Produto', NULL, 96, 'I', 'CODPROD;CODFILIAL' FROM DUAL UNION ALL
    SELECT 30, 'PCCLIENT', 'CODCLI', 'NUMBER', 'Cliente', 'N', 'PCCLIENT', 'CODCLI', 'CLIENTE', NULL, 'S', 'S', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 31, 'PCCLIENT', 'CODBAIRROENT', 'NUMBER', 'Bairro', 'N', 'PCBAIRRO', 'CODBAIRRO', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 32, 'PCCLIENT', 'CLASSEVENDA', 'VARCHAR2', 'Classe de Venda (Cliente)', 'N', NULL, NULL, NULL, 'CLASSEVENDA', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 33, 'PCCLIENT', 'CODATV1', 'NUMBER', 'Atividade', 'N', 'PCATIVI', 'CODATIV', 'RAMO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 34, 'PCCLIENT', 'CODCIDADE', 'NUMBER', 'Cidade', 'N', 'PCCIDADE', 'CODCIDADE', 'NOMECIDADE', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 35, 'PCCLIENT', 'CODCLIPRINC', 'NUMBER', 'Cliente Principal', 'N', 'PCCLIENT', 'CODCLI', 'CLIENTE', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 36, 'PCCLIENT', 'CODCNAE', 'VARCHAR2', 'CNAE', 'N', 'PCCNAE', 'CODCNAE', 'DESCCNAE', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 37, 'PCCLIENT', 'CODCONDCOMERCIAL', 'VARCHAR2', 'Condição Comercial (Indústria)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 38, 'PCCLIENT', 'CODPRACA', 'NUMBER', 'Praça', 'N', 'PCPRACA', 'CODPRACA', 'PRACA', NULL, 'S', 'S', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 39, 'PCCLIENT', 'CODREDE', 'NUMBER', 'Rede de Cliente', 'N', 'PCREDECLIENTE', 'CODREDE', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 40, 'PCCLIENT', 'CONSUMIDORFINAL', 'VARCHAR2', 'Consumidor Final?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 41, 'PCCLIENT', 'CONTRIBUINTE', 'VARCHAR2', 'Contribuinte?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 42, 'PCCLIENT', 'TIPOFJ', 'VARCHAR2', 'Tipo de Pessoa', 'N', NULL, NULL, NULL, 'TIPOPESSOA', 'S', 'S', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 43, 'PCCLIENT', 'DTCADASTRO', 'DATE', 'Data de Cadastro (Cliente)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 44, 'PCCLIENT', 'DTVALIDADECONV', 'DATE', 'Dt. Val. do Convênio', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 45, 'PCCLIENT', 'DTVALIDADEIBAMA', 'DATE', 'Dt. Val. do Registro no IBAMA', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 46, 'PCCLIENT', 'DTVENCALVARA', 'DATE', 'Dt. Venc. Alvará do Psicotrópicos', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 47, 'PCCLIENT', 'DTVENCALVARAANVISA', 'DATE', 'Dt. Venc. Alvará da ANVISA', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 48, 'PCCLIENT', 'DTVENCALVARAFUNC', 'DATE', 'Dt. Venc. Alvará de Funcionamento', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 49, 'PCCLIENT', 'DTVENCALVARARETINOICO', 'DATE', 'Dt Venc. Alvará do Retinóico', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 50, 'PCCLIENT', 'DTVENCALVARASUS', 'DATE', 'Dt. Venc. Alvará do SUS', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 51, 'PCCLIENT', 'DTVENCCRF', 'DATE', 'Dt. Venc. Alvará do CRF', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 52, 'PCCLIENT', 'DTVENCSUFRAMA', 'DATE', 'Dt. Venc. Suframa', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 53, 'PCCLIENT', 'ESTENT', 'VARCHAR2', 'UF do Estado', 'N', 'PCESTADO', 'UF', 'ESTADO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 54, 'PCCLIENT', 'ORGAOPUB', 'VARCHAR2', 'Orgão Público Estadual?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 55, 'PCCLIENT', 'ORGAOPUBFEDERAL', 'VARCHAR2', 'Orgão Público Federal?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 56, 'PCCLIENT', 'ORGAOPUBMUNICIPAL', 'VARCHAR2', 'Orgão Público Municipal?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 57, 'PCCLIENT', 'PARTICIPAFARMACIAPOPULAR', 'VARCHAR2', 'Participa da Farmácia Popular?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 58, 'PCCLIENT', 'TIPOEMPRESA', 'VARCHAR2', 'Tipo de Empresa', 'N', NULL, NULL, NULL, 'TIPOEMPRESA', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 59, 'PCCLIENT', 'TIPOCLIMED', 'VARCHAR2', 'Tipo do Ramo de Medicamentos', 'N', NULL, NULL, NULL, 'TIPOCLIMED', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 60, 'PCCLIENT', 'USADEBCREDRCA', 'VARCHAR2', 'Usa Débito e Crédito de RCA?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 61, 'PCCLIENT', 'LIMCRED', 'NUMBER', 'Limite de Crédito', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 62, 'PCCLIENT', 'CODPLPAG', 'NUMBER', 'Plano de Pagamento (Nível de Venda - Cliente)', 'N', 'PCPLPAG', 'CODPLPAG', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 63, 'PCCLIENT', 'CLIENTEMONITORADO', 'VARCHAR2', 'Cliente Monitorado?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 64, 'PCCLIENT', 'USACRECLIFAT', 'VARCHAR2', 'Cliente Utiliza Créd. Faturamento?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 65, 'PCCLIENT', 'CODUSUR1', 'NUMBER', 'RCA 1 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 66, 'PCCLIENT', 'CODUSUR2', 'NUMBER', 'RCA 2 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 67, 'PCCLIENT', 'CODUSUR3', 'NUMBER', 'RCA 3 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N', 'Cliente', 'CODCLI', 30, 'I', NULL FROM DUAL UNION ALL
    SELECT 68, 'VW_GRUPOSCAMPANHA_CLIENTE', 'CODGRUPO', 'NUMBER', 'Grupo de Cliente', 'N', 'VW_GRUPOSCAMPANHA_CLIENTE', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Cliente', NULL, 97, 'I', 'CODCLI;CODFILIAL' FROM DUAL UNION ALL
    --SELECT 69, 'PCPEDC', 'VLTOTAL', 'NUMBER', 'Valor Total do Pedido', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Pedido', 'VLTOTAL', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 70, 'PCPEDC', 'ORIGEMPED', 'VARCHAR2', 'Origem do Pedido', 'N', NULL, NULL, NULL, 'ORIGEMPEDIDO', 'N', 'N', 'Pedido', 'ORIGEMPED', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 71, 'PCPEDC', 'FRETEDESPACHO', 'VARCHAR2', 'Tipo de Frete', 'N', NULL, NULL, NULL, 'TIPOFRETE', 'N', 'N', 'Pedido', 'FRETEDESPACHO', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 72, 'PCPEDC', 'CONDVENDA', 'VARCHAR2', 'Condição de Venda', 'N', NULL, NULL, NULL, 'CONDVENDA', 'S', 'S', 'Pedido', 'CONDVENDA', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 73, 'PCPEDC', 'CODPLPAG', 'NUMBER', 'Plano de Pagamento (Pedido)', 'N', 'PCPLPAG', 'CODPLPAG', 'DESCRICAO', NULL, 'S', 'S', 'Pedido', 'CODPLPAG', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 74, 'PCPEDC', 'CODCOB', 'VARCHAR2', 'Cobrança', 'N', 'PCCOB', 'CODCOB', 'COBRANCA', NULL, 'S', 'S', 'Pedido', 'CODCOB', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 75, 'PCPEDC', 'CODFILIALNF', 'VARCHAR2', 'Filial (Pedido)', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'N', 'N', 'Pedido', 'CODFILIALNF', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 76, 'PCPEDC', 'CODUSUR', 'NUMBER', 'RCA (Pedido)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'S', 'S', 'Pedido', 'CODUSUR', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 77, 'VW_GRUPOSCAMPANHA_RCA', 'CODGRUPO', 'NUMBER', 'Grupo de RCA', 'N', 'VW_GRUPOSCAMPANHA_RCA', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Pedido', NULL, 98, 'I', 'CODUSUR;CODFILIAL' FROM DUAL UNION ALL
    SELECT 78, 'PCPEDI', 'PVENDA', 'NUMBER', 'Preço de Venda', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Item do Pedido', 'PVENDA', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 79, 'PCPEDI', 'QT', 'NUMBER', 'Quantidade do item', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Item do Pedido', 'QT', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 80, 'PCPEDI', 'SUBTOTAL', 'NUMBER', 'Subtotal do Item', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Item do Pedido', 'SUBTOTAL', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 81, 'PCPEDI', 'CODFILIALRETIRA', 'VARCHAR2', 'Filial Retira', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'S', 'S', 'Item do Pedido', 'CODFILIALRETIRA', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 82, 'PCPEDI', 'CODST', 'NUMBER', 'Figura Tributária', 'N', 'PCTRIBUT', 'CODST', 'MENSAGEM', NULL, 'N', 'N', 'Item do Pedido', 'CODST', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 83, 'PCPEDI', 'CODLINHAPRAZO', 'NUMBER', 'Linha de Prazo', 'N', 'PCLINHAPRAZO', 'CODLINHAPRAZO', 'DESCRICAO', NULL, 'N', 'N', 'Item do Pedido', 'CODLINHAPRAZO', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 84, 'PCPEDC', 'CODFILIAL', 'VARCHAR2', 'Filial', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'S', 'S', 'Pedido', 'CODFILIAL', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 85, 'PCPEDC', 'NUMREGIAO', 'NUMBER', 'Região', 'N', 'PCREGIAO', 'NUMREGIAO', 'REGIAO', NULL, 'S', 'S', 'Pedido', 'NUMREGIAO', NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 86, 'PCUSUARI', 'CODSUPERVISOR', 'NUMBER', 'Supervisor', 'N', 'PCSUPERV', 'CODSUPERVISOR', 'NOME', NULL, 'N', 'N', 'Pedido', 'CODUSUR', 76, 'I', NULL FROM DUAL UNION ALL
    SELECT 87, 'PCSUPERV', 'CODGERENTE', 'NUMBER', 'Gerente', 'N', 'PCGERENTE', 'CODGERENTE', 'NOMEGERENTE', NULL, 'N', 'N', 'Pedido', 'CODUSUR', 86, 'I', NULL FROM DUAL UNION ALL
    --SELECT 88, 'CALCULADO', 'MARGEMMINIMA', 'NUMBER', 'Margem Mínima', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'MARGEMMINIMA', NULL, 'I', NULL FROM DUAL UNION ALL
    --SELECT 89, 'CALCULADO', 'MOVCONTACORRENTEITEM', 'NUMBER', 'Mov. Conta Corrente por Item (Valor / Percentual)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'MOVCONTACORRENTEITEM', NULL, 'I', NULL FROM DUAL UNION ALL
    --SELECT 90, 'CALCULADO', 'MOVCONTACORRENTEPED', 'NUMBER', 'Mov. Conta Corrente por Pedido (Valor / Percentual)', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'MOVCONTACORRENTEPED', NULL, 'C', NULL FROM DUAL UNION ALL
    --SELECT 91, 'CALCULADO', 'PERCVALORBONIFICADO', 'NUMBER', '% Valor Bonificado', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCVALORBONIFICADO', NULL, 'C', NULL FROM DUAL UNION ALL
    --SELECT 92, 'CALCULADO', 'PERCDESCONTOMEDIO', 'NUMBER', '% Desconto Médio', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCDESCONTOMEDIO', NULL, 'C', NULL FROM DUAL UNION ALL
    --SELECT 93, 'CALCULADO', 'PERCDESCONTOITEM', 'NUMBER', '% Desconto Item', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCDESCONTOITEM', NULL, 'I', NULL FROM DUAL UNION ALL
    --SELECT 94, 'CALCULADO', 'ESTOQUEMINIMO', 'NUMBER', 'Estoque Mínimo', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'ESTOQUEMINIMO', NULL, 'I', NULL FROM DUAL UNION ALL
    --SELECT 95, 'CALCULADO', 'PERCCOMPOSICAO', 'NUMBER', '% Composição', 'N', NULL, NULL, NULL, NULL, 'N', 'N', 'Calculado', 'PERCCOMPOSICAO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 96, 'NIVEL', 'CODPROD, CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 97, 'NIVEL', 'CODCLI,CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 98, 'NIVEL', 'CODUSUR,CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL FROM DUAL UNION ALL
    SELECT 99, 'NIVEL', 'CODFORNEC,CODFILIAL', 'NIVEL', 'NIVEL', 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL, NULL, 'I', NULL FROM DUAL UNION ALL	
    SELECT 100, 'VW_GRUPOSCAMPANHA_FORNECEDOR', 'CODGRUPO', 'NUMBER', 'Grupo de Fornecedores', 'N', 'VW_GRUPOSCAMPANHA_FORNECEDOR', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N', 'Produto', NULL, 99, 'I', 'CODFORNEC;CODFILIAL' FROM DUAL	
  ) src
  ON (tgt.CODCONFIG = src.CODCONFIG)
WHEN MATCHED THEN UPDATE SET
    tgt.TABELA = src.TABELA
   ,tgt.CAMPO = src.CAMPO
   ,tgt.TIPOCAMPO = src.TIPOCAMPO
   ,tgt.TABELAPESQUISA = src.TABELAPESQUISA
   ,tgt.CAMPOPESQUISA = src.CAMPOPESQUISA
   ,tgt.DESCRICAOPESQUISA = src.DESCRICAOPESQUISA
   ,tgt.CODROTULO = src.CODROTULO
   ,tgt.GRUPO = src.GRUPO
   ,tgt.NOMEPARAMETRO = src.NOMEPARAMETRO
   ,tgt.CODIGONIVEL = src.CODIGONIVEL
   ,tgt.TIPOVALIDACAO = src.TIPOVALIDACAO
   ,tgt.CHAVEMULTIPLA = src.CHAVEMULTIPLA
WHEN NOT MATCHED THEN
   INSERT (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
   VALUES (src.CODCONFIG, src.TABELA, src.CAMPO, src.TIPOCAMPO, src.NOMELIVRE, src.VISIVELFILTRO, src.TABELAPESQUISA, src.CAMPOPESQUISA, src.DESCRICAOPESQUISA, src.CODROTULO, src.CONDICAO, src.REGRAEXCECAO, src.GRUPO, src.NOMEPARAMETRO, src.CODIGONIVEL, src.TIPOVALIDACAO, src.CHAVEMULTIPLA);
END;