DECLARE

  V_EXISTE_CONFIGURACAO NUMBER := 0;
  
BEGIN
  
  BEGIN
    SELECT COUNT(1)
      INTO V_EXISTE_CONFIGURACAO
      FROM PCRESTRICAOAVANCADACONFIG
     WHERE CODCONFIG BETWEEN 1 AND 95; 
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      V_EXISTE_CONFIGURACAO := 0;
  END;
  
  IF V_EXISTE_CONFIGURACAO = 0 THEN

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (1, 'PCPRODUT', 'CODPROD', 'NUMBER', 'Produto', 'N', 'PCPRODUT', 'CODPROD', 'DESCRICAO', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (2, 'PCPRODUT', 'CODFORNEC', 'NUMBER', ' Fornecedor', 'N', 'PCFORNEC', 'CODFORNEC', 'FORNECEDOR', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (3, 'PCPRODUT', 'CODEPTO', 'NUMBER', ' Departamento', 'N', 'PCDEPTO', 'CODEPTO', 'DESCRICAO', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (4, 'PCPRODUT', 'CODSEC', 'NUMBER', 'Seção', 'N', 'PCSECAO', 'CODSEC', 'DESCRICAO', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (5, 'PCPRODUT', 'CODCATEGORIA', 'NUMBER', 'Categoria', 'N', 'PCCATEGORIA', 'CODCATEGORIA', 'CATEGORIA', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (6, 'PCPRODUT', 'CODLINHAPROD', 'NUMBER', 'Linha de Produto', 'N', 'PCLINHAPROD', 'CODLINHA', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (7, 'PCPRODUT', 'TIPOMERC', 'VARCHAR2', 'Tipo de Mercadoria', 'N', NULL, NULL, NULL, 'TIPOMERCADORIA', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (8, 'PCPRODUT', 'NBM', 'VARCHAR2', 'NCM', 'N', 'PCNCM', 'CODNCM', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (9, 'PCPRODUT', 'CODPRODPRINC', 'NUMBER', 'Produto Principal', 'N', 'PCPRODUT', 'CODPROD', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (10, 'PCPRODUT', 'CLASSEVENDA', 'VARCHAR2', 'Classe de Venda (Produto)', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (11, 'PCPRODUT', 'TIPOESTOQUE', 'VARCHAR2', 'Tipo de Estoque', 'N', NULL, NULL, NULL, 'TIPOESTOQUE', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (12, 'PCPRODUT', 'GRUPOFATURAMENTO', 'VARCHAR2', 'Grupo de Faturamento', 'N', NULL, NULL, NULL, 'GRUPOFATURAMENTO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (13, 'PCPRODUT', 'TIPOMEDICAMENTO', 'VARCHAR2', 'Tipo de Medicamento', 'N', NULL, NULL, NULL, 'TIPOMEDICAMENTO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (14, 'PCPRODUT', 'CODMARCA', 'NUMBER', 'Marca', 'N', 'PCMARCA', 'CODMARCA', 'MARCA', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (15, 'PCPRODUT', 'CODSUBMARCA', 'NUMBER', 'Sub-Marca', 'N', 'PCSUBMARCA', 'CODSUBMARCA', 'DESCSUBMARCA', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (16, 'PCPRODUT', 'OBS2', 'VARCHAR2', 'Fora de Linha', 'N', NULL, NULL, NULL, 'FORALINHA', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (17, 'PCPRODUT', 'CODSUBCATEGORIA', 'NUMBER', 'Sub-Categoria', 'N', 'PCSUBCATEGORIA', 'CODSUBCATEGORIA', 'SUBCATEGORIA', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (18, 'PCPRODUT', 'DTCADASTRO', 'DATE', 'Data de Cadastro (Produto)', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (19, 'PCPRODUT', 'CLASSE', 'VARCHAR2', 'Classe do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (20, 'PCPRODUT', 'VOLUME', 'NUMBER', 'Volume do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (21, 'PCPRODUT', 'PESOBRUTO', 'NUMBER', 'Peso Bruto', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (22, 'PCPRODUT', 'PESOLIQ', 'NUMBER', 'Peso Líquido', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (23, 'PCPRODUT', 'PSICOTROPICO', 'VARCHAR2', 'Psicotrópico?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (24, 'PCPRODUT', 'RETINOICO', 'VARCHAR2', 'Retinóico', 'N', NULL, NULL, NULL, 'RETINOICO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (25, 'PCPRODUT', 'FARMACIAPOPULAR', 'VARCHAR2', 'Produto Farmácia Popular?', 'N', NULL, NULL, NULL, 'FARMACIAPOPULAR', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (26, 'PCPRODUT', 'CODAUXILIAR', 'NUMBER', 'Código de Barras de Venda', 'N', 'PCEMBALAGEM', 'CODAUXILIAR', 'EMBALAGEM', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (27, 'PCPRODFILIAL', 'FABRICANTE', 'VARCHAR2', 'Fabricante', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (28, 'PCPRODFILIAL', 'SUBCLASSE', 'VARCHAR2', 'Sub-Classe do Produto', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (29, 'VW_GRUPOSCAMPANHA_PRODUTO', 'CODGRUPO', 'NUMBER', 'Grupo de Produto', 'N', 'VW_GRUPOSCAMPANHA_PRODUTO', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (30, 'PCCLIENT', 'CODCLI', 'NUMBER', 'Cliente', 'N', 'PCCLIENT', 'CODCLI', 'CLIENTE', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (31, 'PCCLIENT', 'CODBAIRROENT', 'NUMBER', 'Bairro', 'N', 'PCBAIRRO', 'CODBAIRRO', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (32, 'PCCLIENT', 'CLASSEVENDA', 'VARCHAR2', 'Classe de Venda (Cliente)', 'N', NULL, NULL, NULL, 'CLASSEVENDA', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (33, 'PCCLIENT', 'CODATV1', 'NUMBER', 'Atividade', 'N', 'PCATIVI', 'CODATIV', 'RAMO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (34, 'PCCLIENT', 'CODCIDADE', 'NUMBER', 'Cidade', 'N', 'PCCIDADE', 'CODCIDADE', 'NOMECIDADE', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (35, 'PCCLIENT', 'CODCLIPRINC', 'NUMBER', 'Cliente Principal', 'N', 'PCCLIENT', 'CODCLI', 'CLIENTE', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (36, 'PCCLIENT', 'CODCNAE', 'NUMBER', 'CNAE', 'N', 'PCCNAE', 'CODCNAE', 'DESCCNAE', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (37, 'PCCLIENT', 'CODCONDCOMERCIAL', 'VARCHAR2', 'Condição Comercial (Indústria)', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (38, 'PCCLIENT', 'CODPRACA', 'NUMBER', 'Praça', 'N', 'PCPRACA', 'CODPRACA', 'PRACA', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (39, 'PCCLIENT', 'CODREDE', 'NUMBER', 'Rede de Cliente', 'N', 'PCREDECLIENTE', 'CODREDE', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (40, 'PCCLIENT', 'CONSUMIDORFINAL', 'VARCHAR2', 'Consumidor Final?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (41, 'PCCLIENT', 'CONTRIBUINTE', 'VARCHAR2', 'Contribuinte?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (42, 'PCCLIENT', 'TIPOFJ', 'VARCHAR2', 'Tipo de Pessoa', 'N', NULL, NULL, NULL, 'TIPOPESSOA', 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (43, 'PCCLIENT', 'DTCADASTRO', 'DATE', 'Data de Cadastro (Cliente)', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (44, 'PCCLIENT', 'DTVALIDADECONV', 'DATE', 'Dt. Val. do Convênio', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (45, 'PCCLIENT', 'DTVALIDADEIBAMA', 'DATE', 'Dt. Val. do Registro no IBAMA', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (46, 'PCCLIENT', 'DTVENCALVARA', 'DATE', 'Dt. Venc. Alvará do Psicotrópicos', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (47, 'PCCLIENT', 'DTVENCALVARAANVISA', 'DATE', 'Dt. Venc. Alvará da ANVISA', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (48, 'PCCLIENT', 'DTVENCALVARAFUNC', 'DATE', 'Dt. Venc. Alvará de Funcionamento', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (49, 'PCCLIENT', 'DTVENCALVARARETINOICO', 'DATE', 'Dt Venc. Alvará do Retinóico', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (50, 'PCCLIENT', 'DTVENCALVARASUS', 'DATE', 'Dt. Venc. Alvará do SUS', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (51, 'PCCLIENT', 'DTVENCCRF', 'DATE', 'Dt. Venc. Alvará do CRF', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (52, 'PCCLIENT', 'DTVENCSUFRAMA', 'DATE', 'Dt. Venc. Suframa', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (53, 'PCCLIENT', 'ESTENT', 'VARCHAR2', 'UF do Estado', 'N', 'PCESTADO', 'UF', 'ESTADO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (54, 'PCCLIENT', 'ORGAOPUB', 'VARCHAR2', 'Orgão Público Estadual?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (55, 'PCCLIENT', 'ORGAOPUBFEDERAL', 'VARCHAR2', 'Orgão Público Federal?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (56, 'PCCLIENT', 'ORGAOPUBMUNICIPAL', 'VARCHAR2', 'Orgão Público Municipal?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (57, 'PCCLIENT', 'PARTICIPAFARMACIAPOPULAR', 'VARCHAR2', 'Participa da Farmácia Popular?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (58, 'PCCLIENT', 'TIPOEMPRESA', 'VARCHAR2', 'Tipo de Empresa', 'N', NULL, NULL, NULL, 'TIPOEMPRESA', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (59, 'PCCLIENT', 'TIPOCLIMED', 'VARCHAR2', 'Tipo do Ramo de Medicamentos', 'N', NULL, NULL, NULL, 'TIPOCLIMED', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (60, 'PCCLIENT', 'USADEBCREDRCA', 'VARCHAR2', 'Usa Débito e Crédito de RCA?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (61, 'PCCLIENT', 'LIMCRED', 'NUMBER', 'Limite de Crédito', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (62, 'PCCLIENT', 'CODPLPAG', 'NUMBER', 'Plano de Pagamento (Nível de Venda - Cliente)', 'N', 'PCPLPAG', 'CODPLPAG', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (63, 'PCCLIENT', 'CLIENTEMONITORADO', 'VARCHAR2', 'Cliente Monitorado?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (64, 'PCCLIENT', 'USACRECLIFAT', 'VARCHAR2', 'Cliente Utiliza Créd. Faturamento?', 'N', NULL, NULL, NULL, 'SIMNAO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (65, 'PCCLIENT', 'CODUSUR1', 'NUMBER', 'RCA 1 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (66, 'PCCLIENT', 'CODUSUR2', 'NUMBER', 'RCA 2 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (67, 'PCCLIENT', 'CODUSUR3', 'NUMBER', 'RCA 3 (Cliente)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (68, 'VW_GRUPOSCAMPANHA_CLIENTE', 'CODGRUPO', 'NUMBER', 'Grupo de Cliente', 'N', 'VW_GRUPOSCAMPANHA_CLIENTE', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (69, 'PCPEDC', 'VLTOTAL', 'NUMBER', 'Valor Total do Pedido', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (70, 'PCPEDC', 'ORIGEMPED', 'VARCHAR2', 'Origem do Pedido', 'N', NULL, NULL, NULL, 'ORIGEMPEDIDO', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (71, 'PCPEDC', 'FRETEDESPACHO', 'VARCHAR2', 'Tipo de Frete', 'N', NULL, NULL, NULL, 'TIPOFRETE', 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (72, 'PCPEDC', 'CONDVENDA', 'VARCHAR2', 'Condição de Venda', 'N', NULL, NULL, NULL, 'CONDVENDA', 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (73, 'PCPEDC', 'CODPLPAG', 'NUMBER', 'Plano de Pagamento (Pedido)', 'N', 'PCPLPAG', 'CODPLPAG', 'DESCRICAO', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (74, 'PCPEDC', 'CODCOB', 'VARCHAR2', 'Cobrança', 'N', 'PCCOB', 'CODCOB', 'COBRANCA', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (75, 'PCPEDC', 'CODFILIALNF', 'VARCHAR2', 'Filial (Pedido)', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (76, 'PCPEDC', 'CODUSUR', 'NUMBER', 'RCA (Pedido)', 'N', 'PCUSUARI', 'CODUSUR', 'NOME', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (77, 'VW_GRUPOSCAMPANHA_RCA', 'CODGRUPO', 'NUMBER', 'Grupo de RCA', 'N', 'VW_GRUPOSCAMPANHA_RCA', 'CODGRUPO', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (78, 'PCPEDI', 'PVENDA', 'NUMBER', 'Preço de Venda', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (79, 'PCPEDI', 'QT', 'NUMBER', 'Quantidade do item', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (80, 'PCPEDI', 'SUBTOTAL', 'NUMBER', 'Subtotal do Item', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (81, 'PCPEDI', 'CODFILIALRETIRA', 'VARCHAR2', 'Filial Retira', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (82, 'PCPEDI', 'CODST', 'NUMBER', 'Figura Tributária', 'N', 'PCTRIBUT', 'CODST', 'MENSAGEM', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (83, 'PCPEDI', 'CODLINHAPRAZO', 'NUMBER', 'Linha de Prazo', 'N', 'PCLINHAPRAZO', 'CODLINHAPRAZO', 'DESCRICAO', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (84, 'PCFILIAL', 'CODIGO', 'VARCHAR2', 'Filial', 'N', 'PCFILIAL', 'CODIGO', 'RAZAOSOCIAL', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (85, 'PCREGIAO', 'NUMREGIAO', 'NUMBER', 'Região', 'N', 'PCREGIAO', 'NUMREGIAO', 'REGIAO', NULL, 'S', 'S');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (86, 'PCSUPERV', 'CODSUPERVISOR', 'NUMBER', 'Supervisor', 'N', 'PCSUPERV', 'CODSUPERVISOR', 'NOME', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (87, 'PCGERENTE', 'CODGERENTE', 'NUMBER', 'Gerente', 'N', 'PCGERENTE', 'CODGERENTE', 'NOMEGERENTE', NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (88, 'CALCULADO', 'MARGEMMINIMA', 'NUMBER', 'Margem Mínima', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (89, 'CALCULADO', 'MOVCONTACORRENTEITEM', 'NUMBER', 'Mov. Conta Corrente por Item (Valor / Percentual)', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (90, 'CALCULADO', 'MOVCONTACORRENTEPED', 'NUMBER', 'Mov. Conta Corrente por Pedido (Valor / Percentual)', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (91, 'CALCULADO', 'PERCVALORBONIFICADO', 'NUMBER', '% Valor Bonificado', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (92, 'CALCULADO', 'PERCDESCONTOMEDIO', 'NUMBER', '% Desconto Médio', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (93, 'CALCULADO', 'PERCDESCONTOITEM', 'NUMBER', '% Desconto Item', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (94, 'CALCULADO', 'ESTOQUEMINIMO', 'NUMBER', 'Estoque Mínimo', 'N', NULL, NULL, NULL, NULL, 'N', 'N');

    INSERT INTO PCRESTRICAOAVANCADACONFIG (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CODROTULO, CONDICAO, REGRAEXCECAO)
    VALUES (95, 'CALCULADO', 'PERCCOMPOSICAO', 'NUMBER', '% Composição', 'N', NULL, NULL, NULL, NULL, 'N', 'N');
    
  END IF;
  
END;