DECLARE
  vEXEC VARCHAR(4000);
  vCONT NUMBER;
BEGIN
 BEGIN
	SELECT COUNT(1)
	 INTO vCONT
	FROM USER_OBJECTS A
	WHERE A.OBJECT_NAME = 'VW_INT_C5_FAMDIV_MAT';
 END;

 IF vCONT = 0 THEN

  --vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_FAMDIV_MAT REFRESH FORCE ON DEMAND AS SELECT 1 SEQFAMILIA, 1 CODPROD, 1 NROTRIBUTACAO, 1 NRODIVISAO, ''1'' IDREF, ''S'' ATIVO, 1 CODORIGEMTRIB FROM PCCONSUM';
  BEGIN
    --vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_FAMDIV_MAT BUILD DEFERRED REFRESH FORCE ON DEMAND AS SELECT * from VW_INT_C5_FAMDIVISAO';   
      vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_FAMDIV_MAT REFRESH FORCE ON DEMAND AS SELECT 1 SEQFAMILIA, 1 CODPROD, 1 NROTRIBUTACAO, 1 NRODIVISAO, ''1'' IDREF, ''S'' ATIVO, 1 CODORIGEMTRIB FROM PCCONSUM';    
	EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;

  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX1 on VW_INT_C5_FAMDIV_MAT (CODPROD)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  
  
  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX2 on VW_INT_C5_FAMDIV_MAT (CODPROD , NROTRIBUTACAO)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX3 on VW_INT_C5_FAMDIV_MAT(CODPROD , NROTRIBUTACAO , NRODIVISAO)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX4 on VW_INT_C5_FAMDIV_MAT(CODPROD , NROTRIBUTACAO , SEQFAMILIA ,NRODIVISAO)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        RAISE;
      END;  
  END;
 END IF;  
END;
