DECLARE
  vEXEC VARCHAR(4000);
BEGIN

	BEGIN
	 SELECT COUNT(1)
	 INTO vCONT
	 FROM ALL_OBJECTS A
	 WHERE A.OBJECT_NAME = 'VW_INT_C5_EMBPROD_MAT';
	END;

 IF vCONT > 0 THEN
 
  BEGIN
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW VW_INT_C5_FAMDIV_MAT';
 
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
  END;

  vEXEC := 'CREATE MATERIALIZED VIEW VW_INT_C5_FAMDIV_MAT REFRESH FORCE ON DEMAND AS SELECT * FROM VW_INT_C5_FAMDIVISAO';
  EXECUTE IMMEDIATE vEXEC;

  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX1 on VW_INT_C5_FAMDIV_MAT (CODPROD)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
  END;  
  
  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX2 on VW_INT_C5_FAMDIV_MAT (CODPROD , NROTRIBUTACAO)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX3 on VW_INT_C5_FAMDIV_MAT(CODPROD , NROTRIBUTACAO , NRODIVISAO)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
  END;  

  BEGIN
    vEXEC := 'create index VW_INT_C5_FAMDIV_MAT_IDX4 on VW_INT_C5_FAMDIV_MAT(CODPROD , NROTRIBUTACAO , SEQFAMILIA ,NRODIVISAO)';
    EXECUTE IMMEDIATE vEXEC;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        NULL;
      END;  
  END; 

 END IF;
  
END;
