CREATE OR REPLACE FUNCTION REPROCESSAR_PCFINANC2(VDATA      IN DATE,
                                                 VCODFILIAL IN VARCHAR2)
  RETURN VARCHAR2 IS
  VTOTALPCFINANC2 NUMBER;
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  BEGIN
  
    SELECT COUNT(1) TOTAL
      INTO VTOTALPCFINANC2
      FROM PCFINANC2
     WHERE DATA = VDATA
       AND CODFILIAL = VCODFILIAL;
  
    IF VTOTALPCFINANC2 = 0 THEN
    
      --CAIXA
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CAIXA' TIPODADO,
               PCMOVCR.CODBANCO CODIGON,
               PCMOVCR.CODCOB,
               SUM(DECODE(TIPO, 'D', VALOR, 0)) -
               SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCMOVCR, PCBANCO
         WHERE DATA <= VDATA
           AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
           AND PCBANCO.CODBANCO IN
               (SELECT PCFINANC2.CODIGON
                  FROM PCFINANC2
                 WHERE DATA = VDATA - 1
                   AND CODFILIAL = VCODFILIAL
                   AND TIPODADO = 'CAIXA'
                   AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N')
           AND PCBANCO.TIPOCXBCO = 'C'
           AND PCMOVCR.CODCOB IN ('D', 'APLI')
         GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
    
      --BANCO
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'BANCO' TIPODADO,
               PCMOVCR.CODBANCO CODIGON,
               PCMOVCR.CODCOB,
               SUM(DECODE(TIPO, 'D', VALOR, 0)) -
               SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCMOVCR, PCBANCO
         WHERE DATA <= VDATA
           AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
           AND PCBANCO.CODBANCO IN
               (SELECT PCFINANC2.CODIGON
                  FROM PCFINANC2
                 WHERE DATA = VDATA - 1
                   AND CODFILIAL = VCODFILIAL
                   AND TIPODADO = 'BANCO'
                   AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N')
           AND PCBANCO.TIPOCXBCO = 'B'
           AND PCMOVCR.CODCOB IN ('D', 'APLI')
         GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
    
      --VALE
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'VALE' TIPODADO,
               PCMOVCR.CODBANCO CODIGON,
               PCMOVCR.CODCOB,
               SUM(DECODE(TIPO, 'D', VALOR, 0)) -
               SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCMOVCR, PCBANCO
         WHERE DATA <= VDATA
           AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
           AND PCBANCO.CODBANCO IN
               (SELECT PCFINANC2.CODIGON
                  FROM PCFINANC2
                 WHERE DATA = VDATA - 1
                   AND CODFILIAL = VCODFILIAL
                   AND TIPODADO = 'VALE'
                   AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N')
           AND PCMOVCR.CODCOB IN ('VALE')
         GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
    
      --EMPRESTIMO ATIVO
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'EMPRESTA' TIPODADO,
               PCMOVCR.CODBANCO CODIGON,
               PCMOVCR.CODCOB,
               SUM(DECODE(TIPO, 'D', VALOR, 0)) -
               SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCMOVCR, PCBANCO
         WHERE DATA <= VDATA
           AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
           AND PCBANCO.CODBANCO IN
               (SELECT PCFINANC2.CODIGON
                  FROM PCFINANC2
                 WHERE DATA = VDATA - 1
                   AND CODFILIAL = VCODFILIAL
                   AND TIPODADO = 'EMPRESTA'
                   AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N')
           AND PCBANCO.TIPOCXBCO = 'E'
         GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
    
      --EMPRESTIMO PASSIVO     
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'EMPRESTP' TIPODADO,
               CODIGON,
               CODIGOA,
               VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCFINANC2
         WHERE TIPODADO = 'EMPRESTP'
           AND CODFILIAL = VCODFILIAL
           AND DATA = VDATA - 1
           AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N'
        UNION ALL
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'FINIMP' TIPODADO,
               CODIGON,
               CODIGOA,
               VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCFINANC2
         WHERE TIPODADO = 'FINIMP'
           AND CODFILIAL = VCODFILIAL
           AND DATA = VDATA - 1
           AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N';
    
      --INVESTIMENTO ATIVO
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'INVEST' TIPODADO,
               CODIGON,
               CODIGOA,
               VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCFINANC2
         WHERE TIPODADO = 'INVEST'
           AND CODFILIAL = VCODFILIAL
           AND DATA = VDATA - 1
           AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N';
    
      --INVESTIMENTO PASSIVO
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'INVESTP' TIPODADO,
               CODIGON,
               CODIGOA,
               VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCFINANC2
         WHERE TIPODADO = 'INVESTP'
           AND CODFILIAL = VCODFILIAL
           AND DATA = VDATA - 1
           AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N';
    
      --VENDOR
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'VENDOR' TIPODADO,
               CODIGON,
               CODIGOA,
               VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCFINANC2
         WHERE TIPODADO = 'VENDOR'
           AND CODFILIAL = VCODFILIAL
           AND DATA = VDATA - 1
           AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N';
    
      --ESTOQUE CONSIGNADO
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'ESTOQUECI' TIPODADO,
               CODIGON,
               CODIGOA,
               VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCFINANC2
         WHERE TIPODADO = 'ESTOQUECI'
           AND CODFILIAL = VCODFILIAL
           AND DATA = VDATA - 1
           AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N';
    
      --CONTAS TRANSITÓRIAS
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CTRANS' TIPODADO,
               PCMOVCR.CODBANCO CODIGON,
               PCMOVCR.CODCOB,
               SUM(DECODE(TIPO, 'D', VALOR, 0)) -
               SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCMOVCR, PCBANCO
         WHERE DATA <= VDATA
           AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
           AND PCBANCO.CODBANCO IN
               (SELECT PCFINANC2.CODIGON
                  FROM PCFINANC2
                 WHERE DATA = VDATA - 1
                   AND CODFILIAL = VCODFILIAL
                   AND TIPODADO = 'CTRANS'
                   AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'N')
           AND PCMOVCR.CODCOB NOT IN ('D', 'APLI', 'VALE')
         GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
    
      --CONTAS A RECEBER CRECEBER
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CRECEBER' TIPODADO,
               0 CODIGON,
               PCPREST.CODCOB CODIGOA,
               SUM(VALOR) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCPREST
         WHERE (DTBAIXA IS NULL OR DTBAIXA > VDATA)
           AND DTEMISSAO <= VDATA
           AND NVL(PERMITEESTORNO, 'S') = 'S'
           AND CODFILIAL = VCODFILIAL
           AND CODCOB NOT IN ('DESD', 'DEVT', 'DEVP')
           AND CODCOB NOT LIKE 'BNF%'
         GROUP BY PCPREST.CODCOB;
    
      --VERBAS - CONTAS A RECEBER DE FORNECEDOR
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CRFORNEC' TIPODADO,
               PCMOVCRFOR.CODFORNEC CODIGON,
               0 CODIGOA,
               SUM(DECODE(TIPO, 'D', VALOR, 0)) -
               SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCMOVCRFOR
         WHERE DATA <= VDATA
           AND PCMOVCRFOR.CODFILIAL = VCODFILIAL
		   AND PCMOVCRFOR.CODFORNEC IS NOT NULL
         GROUP BY PCMOVCRFOR.CODFORNEC;
    
      --ESTOQUE
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT PCHISTEST.DATA,
               VCODFILIAL,
               'ESTOQUE' TIPODADO,
               PCPRODUT.CODEPTO CODIGON,
               0 CODIGOA,
               SUM(PCHISTEST.QTESTGER * PCHISTEST.CUSTOREP) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCHISTEST, PCPRODUT
         WHERE PCHISTEST.CODPROD = PCPRODUT.CODPROD
           AND PCHISTEST.DATA = VDATA
           AND PCHISTEST.CODFILIAL = VCODFILIAL
		   AND PCPRODUT.CODEPTO IS NOT NULL
           AND PCHISTEST.TIPOMERCDEPTO NOT IN ('CI', 'IM')
         GROUP BY PCPRODUT.CODEPTO, PCHISTEST.DATA;
    
      --ADIANTAMENTO A FORNECEDOR
      --ADIANTAMENTO DEVE TER SIDO LANÇADO E BAIXADO TAMBEM ANTERIOR A DATA DE CONSOLIDAÇÃO,
      --VISTO QUE A 117 SÓ MOSTRA ADIANTAMENTOS BAIXADOS E LANÇADOS ANTERIORES À ESSA DATA.
      --E O ADIANTAMENTO DEVE TER SALDO NÃO UTILIZADO OU DEVE TER SIDO BAIXADO POSTERIORMENTE À DATA DA CONSOLIDAÇÃO
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'ADFORNEC' TIPODADO,
               PCLANC.CODFORNEC CODIGON,
               0 CODIGOA,
               SUM(PCLANC.VALOR) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCLANC, PCCONSUM
         WHERE (PCLANC.CODCONTA = PCCONSUM.CODCONTAADIANTFOR OR
               PCLANC.CODCONTA = PCCONSUM.CODCONTAADIANTFOROUTROS)
           AND DTESTORNOBAIXA IS NULL
           AND DTCANCEL IS NULL
           AND DTLANC <= VDATA
           AND DTPAGTO <= VDATA
           AND (PCLANC.DTPAGADIANTFOR >= VDATA OR
               NVL(PCLANC.VLRUTILIZADOADIANTFORNEC, 0) < PCLANC.VALOR)
           AND PCLANC.CODFILIAL = VCODFILIAL
         GROUP BY PCLANC.CODFORNEC;
    
      --CONTAS A PAGAR - REVENDA
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CPAGAR' TIPODADO,
               PCLANC.CODFORNEC CODIGON,
               0 CODIGOA,
               SUM(PCLANC.VALOR) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCLANC, PCCONSUM
         WHERE (PCLANC.CODCONTA = PCCONSUM.CODCONTFOR OR
               PCLANC.CODCONTA = PCCONSUM.CODCONTFRE OR
               PCLANC.CODCONTA = PCCONSUM.CODCONTOUT)
           AND DTLANC <= VDATA
           AND (DTPAGTO IS NULL OR DTPAGTO > VDATA)
           AND PCLANC.CODFILIAL = VCODFILIAL
         GROUP BY PCLANC.CODFORNEC;
    
      --CONTAS A PAGAR - OUTROS FORNECEDORES
      --VALIDANDO PARAMETRO INCCPOUTROFORNECSBOLETFIN DA 132 QUE DEVE ESTAR COM SIM.
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CPOUTROS' TIPODADO,
               PCLANC.CODFORNEC CODIGON,
               0 CODIGOA,
               SUM(PCLANC.VALOR) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCLANC, PCCONSUM
         WHERE PCLANC.CODCONTA NOT IN
               (PCCONSUM.CODCONTFOR,
                PCCONSUM.CODCONTFRE,
                PCCONSUM.CODCONTOUT,
                PCCONSUM.CODCONTAADIANTFOR,
                PCCONSUM.CODCONTAADIANTFOROUTROS)
           AND (SELECT VALOR
                  FROM PCPARAMFILIAL
                 WHERE NOME = 'INCCPOUTROFORNECSBOLETFIN') = 'S'
           AND DTLANC <= VDATA
           AND (DTPAGTO IS NULL OR DTPAGTO > VDATA)
           AND PCLANC.TIPOPARCEIRO = 'F'
           AND PCLANC.TIPOLANC = 'C'
           AND PCLANC.DTCANCEL IS NULL
           AND PCLANC.CODFILIAL = VCODFILIAL
           AND PCLANC.CODFORNEC IN
               (SELECT CODIGON
                  FROM PCFINANC2
                 WHERE TIPODADO = 'CPOUTROS'
                   AND CODFILIAL = VCODFILIAL
                   AND DATA = VDATA - 1)
           AND PCLANC.CODCONTA NOT IN
               (SELECT NVL(P.VALOR, 0)
                  FROM PCPARAMFILIAL P
                 WHERE P.NOME IN ('CON_CODCONTFOR',
                                  'CON_CODCONTFRE',
                                  'CON_CODCONTOUT',
                                  'CON_CODCONTAADIANTFOR',
                                  'CON_CODCONTAADIANTFOROUTROS',
                                  'CON_CODCONTAVERBAFORNEC',
                                  'CON_CODCONTAVERBACMV',
                                  'CON_CODCONTEMPREST',
                                  'CODCONTAEMPRESTIMONACIONAL',
                                  'CODCONTAEMPRESTIMOESTRANGEIRO'))
         GROUP BY PCLANC.CODFORNEC;
    
      --CREDITO DE CLIENTES
      INSERT INTO PCFINANC2
        (DATA,
         CODFILIAL,
         TIPODADO,
         CODIGON,
         CODIGOA,
         VALOR,
         DTGERACAO,
         CODROTINA,
         CODFUNC,
         PARMULTIFILIALCAIXABANCO3882)
        SELECT VDATA DATA,
               VCODFILIAL CODFILIAL,
               'CREDCLI' TIPODADO,
               PCCRECLI.CODCLI CODIGON,
               0 CODIGOA,
               SUM(PCCRECLI.VALOR) VALOR,
               SYSDATE DTGERACAO,
               504 CODROTINA,
               1 CODFUNC,
               'N' PARMULTIFILIALCAIXABANCO3882
          FROM PCCRECLI
         WHERE PCCRECLI.DTLANC <= VDATA
           AND (PCCRECLI.DTDESCONTO IS NULL OR PCCRECLI.DTDESCONTO > VDATA)
		   AND PCCRECLI.CODCLI IS NOT NULL
           AND PCCRECLI.CODFILIAL = VCODFILIAL
         GROUP BY PCCRECLI.CODCLI;
    
      COMMIT;
    END IF;
  
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, ('Erro na execução: ' || SQLCODE || ' - ' || SQLERRM));
  END;

  RETURN 'OK';

END;
