CREATE OR REPLACE TRIGGER TRG_LOG_PCCONTASCONTABEISSPED
  BEFORE INSERT OR UPDATE OR DELETE ON PCCONTASCONTABEISSPED
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE

  VSEQUIPAMENTO VARCHAR2(64);
  VSUSUARIO     VARCHAR2(30);
  VSPROGRAMA    VARCHAR2(48);
  VSTIPO        VARCHAR2(20);

  PROCEDURE GERARLOG(pNOMECOLUNA VARCHAR2, pOLDValue VARCHAR2, pNEWValue VARCHAR2) IS
  BEGIN
    IF NVL(pOLDValue, 'X') <> NVL(pNEWValue, 'X') THEN
      INSERT INTO PCLOGALTERACAODADOS(
        DATA,
        TABELA,
        COLUNA,
        OBSERVACOES,
        PROGRAMA,
        TERMINAL,
        OSUSER,
        VALORALFAANT,
        VALORALFA,
        OPERACAO,
    OBSERVACOES2
      )
      VALUES(
        SYSDATE,
        'PCCONTASCONTABEISSPED',
        pNOMECOLUNA,
        '',
        VSPROGRAMA,
        VSEQUIPAMENTO,
        VSUSUARIO,
        pOLDValue,
        pNEWValue,
        VSTIPO,
        ''
      );

    END IF;
  END;
BEGIN

  VSEQUIPAMENTO := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 64);
  VSUSUARIO     := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 30);
  VSPROGRAMA    := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 48);

  IF UPDATING THEN
    VSTIPO := 'U';
  ELSIF INSERTING THEN
    VSTIPO := 'I';
  ELSE
    VSTIPO := 'D';
  END IF;

  GERARLOG('COD_CTA_REF', TO_CHAR(:OLD.COD_CTA_REF), TO_CHAR(:NEW.COD_CTA_REF));
  GERARLOG('CNPJ_EST', TO_CHAR(:OLD.CNPJ_EST), TO_CHAR(:NEW.CNPJ_EST));
  GERARLOG('GERARSPED', TO_CHAR(:OLD.GERARSPED), TO_CHAR(:NEW.GERARSPED));
  GERARLOG('SEQCONTCONTSPED', TO_CHAR(:OLD.SEQCONTCONTSPED), TO_CHAR(:NEW.SEQCONTCONTSPED));
  GERARLOG('TIPOCONTA', TO_CHAR(:OLD.TIPOCONTA), TO_CHAR(:NEW.TIPOCONTA));
  GERARLOG('CODFILIAL', TO_CHAR(:OLD.CODFILIAL), TO_CHAR(:NEW.CODFILIAL));
  GERARLOG('REGISTROSPED', TO_CHAR(:OLD.REGISTROSPED), TO_CHAR(:NEW.REGISTROSPED));
  GERARLOG('CODFISCAL', TO_CHAR(:OLD.CODFISCAL), TO_CHAR(:NEW.CODFISCAL));
  GERARLOG('NATUREZAFISCAL', TO_CHAR(:OLD.NATUREZAFISCAL), TO_CHAR(:NEW.NATUREZAFISCAL));
  GERARLOG('DT_ALT', TO_CHAR(:OLD.DT_ALT), TO_CHAR(:NEW.DT_ALT));
  GERARLOG('COD_NAT_CC', TO_CHAR(:OLD.COD_NAT_CC), TO_CHAR(:NEW.COD_NAT_CC));
  GERARLOG('IND_CTA', TO_CHAR(:OLD.IND_CTA), TO_CHAR(:NEW.IND_CTA));
  GERARLOG('NIVEL', TO_CHAR(:OLD.NIVEL), TO_CHAR(:NEW.NIVEL));
  GERARLOG('COD_CTA', TO_CHAR(:OLD.COD_CTA), TO_CHAR(:NEW.COD_CTA));
  GERARLOG('NOME_CTA', TO_CHAR(:OLD.NOME_CTA), TO_CHAR(:NEW.NOME_CTA));
  GERARLOG('CSTPISCOFINS', TO_CHAR(:OLD.CSTPISCOFINS), TO_CHAR(:NEW.CSTPISCOFINS));

END;