CREATE OR REPLACE VIEW VW_INT_C5_BINCARTAO AS
(
SELECT B.CODBINCARTAO SEQBINCARTAO,
       B.NROBININICIAL,
       B.NROBINFINAL,
       B.CODREDE,
       B.CODBANDEIRA,
       B.TIPO,       
       DECODE(B.DTEXCLUSAO, NULL, 'S', 'N') ATIVO
  FROM PCBINCARTAO B
);