CREATE OR REPLACE VIEW VW_INT_C5_TRIB_UF AS
(SELECT distinct
            t.codst nrotributacao,
            c.UFORIGEM uforigem,
            c.UFDESTINO ufdestino,
            'SN' tipotributacao,
            0 nroregtributacao,
            c.percaliquota,
            (case
              when (Length(NVL(t.sittributecf, t.sittributpf))) = 2 then
                   '0' || NVL(t.sittributecf, t.sittributpf) 
              else NVL(t.sittributecf, t.sittributpf)
            end)  situacaotributacao,
		    (case
              when Length(t.sittributsimplesnac) = 2 then
                   '0' || t.sittributsimplesnac 
              else t.sittributsimplesnac
            end) SITUACAOSIMPLES,
            c.percisento,
            c.perctributado,
            c.percoutro,
            0 percacrescst,
            NVL(t.aliqstsaida,0) percisentost,
            'B' tipocalcfcp,
            NVL(C.percaliqfcpicms, t.peracrescimofuncep) percaliqfcpicms,

            (case
               when NVL(C.percaliqfcpicms, t.peracrescimofuncep) > 0 THEN
                    100
               else  0
            end) percbasefcpicms,

            c.reducaobasest,
            'T' tiporeducaoicmscalcst,
            0 perctributst,
            'S' ativo,
            0 situacaopis,
            0 situacaocofins,
            0 percpis,
            0 perccofins,
            0 percbasefcpst,
            0 percaliqfcpst,
            CASE WHEN NVL(t.PERDESCICMISENCAO, 0) > 0 
            	THEN c.percdesoneracao
            	ELSE NULL
            END percaliqicmsdeson,
            CASE WHEN NVL(t.PERDESCICMISENCAO, 0) > 0 
            	THEN c.calcicmsdeson
            	ELSE 'N'
            END calcicmsdeson,
            c.codmotivodesoneracao motivodesonicms,
            c.codbeneficiofiscal codbeneficiodesonicms,
            --t.codst||(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = C.UFORIGEM) codobservacao,

            (CASE WHEN c.codbeneficiofiscal is null THEN 
                      null
                 ELSE t.codst||(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = C.UFORIGEM) 
            END)  codobservacao,

            t.codst,
            t.mensagem || ' - TRIBUTACAO' tributacao,
            t.mensagem || ' - TRIBUTACAO' descaplicacao,
            COALESCE(t.codecf, '0000') codecf,
            /*GREATEST(
                     NVL(t.DTALTERC5, d.datapadrao),
                     NVL(c.DTALTERC5, d.datapadrao)) data,*/

            GREATEST(NVL(t.DTALTERC5, d.datapadrao),
                         d.datapadrao
                    ) data,

            COALESCE(c.aliqicms1,0) aliqicms1,
            COALESCE(c.aliqicms2,0) aliqicms2
FROM pctribut t,
     PCCONSOLIDATRIBUTACAO c,
     /*(SELECT MIN(s.ultimaexecucao) datapadrao FROM pccontroleconsinco s) d*/
     (SELECT MIN(S.ULTIMAEXECUCAO)  datapadrao
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAOUF')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBS')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPED')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPEDFAMILIA')
      )d

WHERE t.codst = c.codst
AND t.codecf IS NOT NULL
AND t.codst is not null
AND NVL(NVL(T.CODICMPF, T.CODICM), 0) = c.PERCALIQUOTA
)

\

CREATE OR REPLACE VIEW VW_INT_C5_TRIB_UF_CONSOLIDADA AS
(
SELECT  distinct
        NROTRIBUTACAO,
        UFORIGEM,
        UFDESTINO,
        'SN' TIPOTRIBUTACAO,
        NROREGTRIBUTACAO,
        PERCALIQUOTA,
        SITUACAOTRIBUTACAO,
		SITUACAOSIMPLES,
        PERCISENTO,
        PERCTRIBUTADO,
        PERCOUTRO,
        PERCACRESCST,
        PERCISENTOST,
        TIPOCALCFCP,
        PERCBASEFCPICMS,
        PERCALIQFCPICMS,
        REDUCAOBASEST,
        TIPOREDUCAOICMSCALCST,
        PERCTRIBUTST,
        ATIVO,
        PERCBASEFCPST,
        PERCALIQFCPST,
        CALCICMSDESON,
        PERCALIQICMSDESON,
        MOTIVODESONICMS,
        NULL CODBENEFICIODESONICMS,
        CODOBSERVACAO,
        CODBENEFICIODESONICMS IDREF--(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = UFORIGEM) IDREF
  FROM VW_INT_C5_TRIB_UF
 WHERE DATA >= (SELECT MIN(S.ULTIMAEXECUCAO)  ULTIMAEXECUCAO
                FROM PCCONTROLECONSINCO S 
                WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAOUF')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBS')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPED')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPEDFAMILIA')
               )
 AND LENGTH(SITUACAOTRIBUTACAO) <= 3 --Não considerar CST de Simples Nacional que pode estar com 4 digitos  
 UNION ALL
 SELECT  distinct
        NROTRIBUTACAO,
        UFORIGEM,
        UFDESTINO,
        'SC' TIPOTRIBUTACAO,
        NROREGTRIBUTACAO,
        PERCALIQUOTA,
        SITUACAOTRIBUTACAO,
		SITUACAOSIMPLES,
        PERCISENTO,
        PERCTRIBUTADO,
        PERCOUTRO,
        PERCACRESCST,
        PERCISENTOST,
        TIPOCALCFCP,
        PERCBASEFCPICMS,
        PERCALIQFCPICMS,
        REDUCAOBASEST,
        TIPOREDUCAOICMSCALCST,
        PERCTRIBUTST,
        ATIVO,
        PERCBASEFCPST,
        PERCALIQFCPST,
        CALCICMSDESON,
        PERCALIQICMSDESON,
        MOTIVODESONICMS,
        NULL CODBENEFICIODESONICMS,
        CODOBSERVACAO,
        CODBENEFICIODESONICMS IDREF--(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = UFORIGEM) IDREF
  FROM VW_INT_C5_TRIB_UF
 WHERE DATA >= (SELECT MIN(S.ULTIMAEXECUCAO)  ULTIMAEXECUCAO
                FROM PCCONTROLECONSINCO S 
                WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAOUF')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBS')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPED')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPEDFAMILIA')
               )
 AND LENGTH(SITUACAOTRIBUTACAO) <= 3 
)

\

CREATE OR REPLACE VIEW VW_TB_TRIBUTACAO_CONSOLIDADA AS
(
SELECT NROTRIBUTACAO,
       CODST,
       TRIBUTACAO,
       DESCAPLICACAO,
       CODECF,
       ATIVO,
       DATA,
       ALIQICMS1,
       ALIQICMS2
  FROM VW_INT_C5_TRIB_UF 
 WHERE DATA >= (SELECT MIN(S.ULTIMAEXECUCAO) FROM PCCONTROLECONSINCO S WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAO'))

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMDIVISAO AS
(
 SELECT
    PRODTRIB."SEQFAMILIA", PRODTRIB."CODPROD", PRODTRIB."NROTRIBUTACAO",PRODTRIB."NRODIVISAO",PRODTRIB."IDREF",PRODTRIB."ATIVO", PRODTRIB."CODORIGEMTRIB"
 FROM
     (SELECT DISTINCT
        R.CODPROD,
        T.SEQFAMILIA,
        R.CODST nrotributacao,
        0 codorigemtrib,
        D.NRODIVISAO,
        D.NUMREGIAO IDREF,
        'S' ativo

      FROM MONITORPDVMIDDLE.TB_FAMILIA TF,
           PCDEPARAPRODC5 T,
           MONITORPDVMIDDLE.TB_TRIBUTACAOUF F,
           (SELECT PR.CODPROD, PR.CODST, PR.NUMREGIAO
            FROM PCTABPR PR,
                 (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FAMDIVISAO') DTPADRAO
            WHERE NVL(PR.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO 
            AND  PR.NUMREGIAO IN (SELECT VALOR
                                   FROM PCPARAMFILIAL
                                   WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                                   AND CODFILIAL IN (SELECT CODFILIAL FROM VW_INT_C5_OBTER_FILIAIS_C5)
                                   AND VALOR <> '99'
                                   AND VALOR IS NOT NULL)
            UNION
            SELECT PR2.CODPROD, PR2.CODST, PR2.NUMREGIAO
            FROM PCTABPR PR2,
                 MONITORPDVMIDDLE.TB_FAMILIA FAM,
                 PCDEPARAREGIAOC5 REG
            WHERE TO_CHAR(PR2.CODPROD) = FAM.IDREF
            AND   FAM.ATIVO = 'S'
            AND   REG.NUMREGIAO = PR2.NUMREGIAO
            AND   PR2.NUMREGIAO IN (SELECT VALOR
                                   FROM PCPARAMFILIAL
                                   WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                                   AND CODFILIAL IN (SELECT CODFILIAL FROM VW_INT_C5_OBTER_FILIAIS_C5)
                                   AND VALOR <> '99'
                                   AND VALOR IS NOT NULL)
            AND NOT EXISTS (SELECT 1
                            FROM MONITORPDVMIDDLE.TB_FAMDIVISAO DIV
                            WHERE DIV.NROTRIBUTACAO = PR2.CODST
                            AND   DIV.SEQFAMILIA = FAM.SEQFAMILIA
                            AND   DIV.NRODIVISAO = REG.NRODIVISAO
                           )

           )R,
          PCCONSOLIDATRIBUTACAO C,
          PCDEPARAREGIAOC5 D
      WHERE T.CODPROD = R.CODPROD
      AND   TF.IDREF = TO_CHAR(R.CODPROD)
      AND   TF.IDREF = TO_CHAR(T.CODPROD)
      AND   T.ATIVO = 'S'
	  AND   T.SEQFAMILIA = TF.SEQFAMILIA
	  AND   TF.ATIVO = 'S'
      AND   R.CODST = C.CODST
      AND   R.CODST = F.NROTRIBUTACAO
      AND   C.CODST = F.NROTRIBUTACAO
      AND   R.NUMREGIAO = C.NUMREGIAO
      AND   R.NUMREGIAO = D.NUMREGIAO
      AND   C.NUMREGIAO = D.NUMREGIAO
      AND   R.CODST IS NOT NULL
      AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
      GROUP BY T.SEQFAMILIA, R.CODPROD, R.CODST, D.NRODIVISAO, D.NUMREGIAO

      UNION ALL
      
      SELECT DISTINCT
        TB.CODPROD,
        T.SEQFAMILIA,
        TB.CODST nrotributacao,
        0 codorigemtrib,
        C5.CODFILIALINTEGRACAO NRODIVISAO,
         C5.CODFILIALINTEGRACAO IDREF,
        'S' ativo
      FROM MONITORPDVMIDDLE.TB_FAMILIA TF,
           PCDEPARAPRODC5 T,
           MONITORPDVMIDDLE.TB_TRIBUTACAOUF F,
           MONITORPDVMIDDLE.TB_EMPRESA E,
           PCFILIAL FIL,
           (SELECT TABTRIB.CODPROD, TABTRIB.CODST, TABTRIB.UFDESTINO, TABTRIB.CODFILIALNF
            FROM PCTABTRIB TABTRIB,
                 (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FAMDIVISAO') DTPADRAO
            WHERE NVL(TABTRIB.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
            UNION
            SELECT TABTRIB2.CODPROD, TABTRIB2.CODST, TABTRIB2.UFDESTINO, TABTRIB2.CODFILIALNF
            FROM PCTABTRIB TABTRIB2,
                 MONITORPDVMIDDLE.TB_FAMILIA FAM
            WHERE TO_CHAR(TABTRIB2.CODPROD) = FAM.IDREF
            AND   FAM.ATIVO = 'S'
            AND NOT EXISTS (SELECT 1
                            FROM MONITORPDVMIDDLE.TB_FAMDIVISAO DIV
                            WHERE DIV.NROTRIBUTACAO = TABTRIB2.CODST
                            AND   DIV.SEQFAMILIA = FAM.SEQFAMILIA
                           )

           )TB,
           PCCONSOLIDATRIBUTACAO C,
           VW_INT_C5_OBTER_FILIAIS_C5 c5,
           (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FAMDIVISAO') DTPADRAO
      
      WHERE T.CODPROD = TB.CODPROD
      AND   TF.IDREF = TO_CHAR(TB.CODPROD)
      AND   TF.IDREF = TO_CHAR(T.CODPROD)
      AND   T.ATIVO = 'S'
	  AND   T.SEQFAMILIA = TF.SEQFAMILIA
	  AND   TF.ATIVO = 'S'
      AND   F.NROTRIBUTACAO = TB.CODST
      AND   F.UFORIGEM = TB.UFDESTINO
      AND   C5.CODFILIAL = TB.CODFILIALNF
      AND   C.CODST = TB.CODST
      AND   C.NUMREGIAO = C5.CODFILIALINTEGRACAO
      AND   C.UFORIGEM = TB.UFDESTINO
      AND   C5.CODFILIAL = TB.CODFILIALNF
      AND   FIL.UF = TB.UFDESTINO
      AND   FIL.CODIGO = TB.CODFILIALNF
      AND   F.NROTRIBUTACAO = C.CODST
      AND   F.UFORIGEM = C.UFORIGEM
      AND   E.NROEMPRESA = C.NUMREGIAO
      AND   E.NROEMPRESA = C5.CODFILIALINTEGRACAO
      AND   FIL.CODIGO  = C5.CODFILIAL
      AND   TB.CODST IS NOT NULL
      AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
      GROUP BY T.SEQFAMILIA, TB.CODPROD, TB.CODST, C5.CODFILIALINTEGRACAO
      )PRODTRIB    
  )

 \

CREATE OR REPLACE VIEW VW_INT_C5_CODGERALOPER AS
(SELECT 65  codgeraloper,
        SUBSTR(UPPER(O.desccfo),1,40)    descricao,
        SUBSTR(UPPER(O.desccfo),1,80)    aplicacao,
        5102                             cfopestado,
        6102                             cfopforaestado,
        'N'                              calculaicmsst,
        'N'                              gerareducaobasest,
        'N'                              calculaipi,
        'N'                              tipocalculoipi,
        'N'                              calculafecp,
        'T'                              tipofaturamento,
        'S'                              ativo,
         O.dtalterc5                     dtalterc5,
        'N'                              consumidorfinal,
        'N'                              vendapresencial,
        'P'                              tipotributacao,
        'S'                              gerareducaobasepiscofins
 FROM  PCCFO O,
       
       (select min(s.ultimaexecucao) ultimaexecucao
        from pccontroleconsinco s
        where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CODGERALOPER')
       )DTPADRAO

 WHERE O.codfiscal = 5102
 --AND   NVL(O.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
 UNION ALL
 SELECT 55 codgeraloper,
       SUBSTR(UPPER(O.desccfo), 1, 40) descricao,
       SUBSTR(UPPER(O.desccfo), 1, 80) aplicacao,
       5102 cfopestado,
       6102 cfopforaestado,
       'N' calculaicmsst,
       'N' gerareducaobasest,
       'N' calculaipi,
       'N' tipocalculoipi,
       'N' calculafecp,
       'T' tipofaturamento,
       'S' ativo,
       O.dtalterc5 dtalterc5,
       'N' consumidorfinal,
       'N' vendapresencial,
       'P' tipotributacao,
       'S' gerareducaobasepiscofins
  FROM PCCFO O,
       
       (select min(s.ultimaexecucao) ultimaexecucao
          from pccontroleconsinco s
         where (upper(s.objetoreferencia) =
               'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CODGERALOPER')) DTPADRAO WHERE O.codfiscal = 5102
  -- AND NVL(O.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
 
)

 \

CREATE OR REPLACE VIEW VW_INT_C5_CODGERALOPERCFOP AS
(SELECT   65      codgeraloper,
          T.CODST nrotributacao,
          'N'     contribicms,
          T.CODFISCAL  cfopestado,
          T.CODFISCALINTER cfopforaestado,
          'S' ativo,
          T.DTALTERC5 dtalterc5
FROM  PCTRIBUT T,
      
     (select s.ultimaexecucao
      from pccontroleconsinco s
      where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CODGERALOPERCFOP')
     )DTPADRAO
--WHERE  NVL(T.SITTRIBUTECF, T.SITTRIBUTPF) IN ('00','20','40','41','60','61','90')
WHERE NVL(T.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
AND   T.CODFISCAL IS NOT NULL

)

\

CREATE OR REPLACE VIEW VW_INT_C5_CADOBS AS
(
 SELECT DISTINCT
     T.CODOBSERVACAO,
     'N' INFORMADOTRIBUF,
     'S' GERACBENEFFAMTRIB,
     'S' ATIVO
 FROM Vw_Int_C5_Trib_Uf_Consolidada T
 WHERE T.IDREF IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CADOBSSPED AS
(
SELECT DISTINCT
  T.CODOBSERVACAO||(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = T.UFORIGEM) SEQOBSSPED,
  T.CODOBSERVACAO,
  T.IDREF CODAJUSTEEFD,
  'S' USACODAJUSTENFE,
  'A' REGISTRO,
  'S' ATIVO
FROM Vw_Int_C5_Trib_Uf_Consolidada T
WHERE T.IDREF IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CADOBSSPEDFAMILIA AS
(

SELECT
  *
FROM (  
     SELECT 
        ROW_NUMBER() OVER(partition by FAM.SEQFAMILIA,  S.SEQOBSSPED  order BY  E.CODEXCECAO) sequencia,
        FAM.SEQFAMILIA,
        E.CODEXCECAO,
        S.SEQOBSSPED,
        E.CODCADASTROPRINC,
        E.CODCADASTROEXCECAO CODAJUSTEEFD,
        T.UFORIGEM UF,
        E.TIPO1,
        E.VALOR1,
        'S' ATIVO,
        E.TIPO1||E.VALOR1 IDREF
     FROM MONITORPDVMIDDLE.TB_CADOBSSPED S,
          MONITORPDVMIDDLE.TB_FAMILIA FAM,
          MONITORPDVMIDDLE.tb_famdivisao D,
          MONITORPDVMIDDLE.TB_TRIBUTACAOUF T,
          PCEXCECAOCADASTROSFISCAIS E,
          pcdepararegiaoc5 R
     WHERE S.CODAJUSTEEFD = E.CODCADASTROPRINC
     AND   D.seqfamilia = FAM.SEQFAMILIA
     AND   FAM.ATIVO = 'S'
     AND   T.NROTRIBUTACAO = D.nrotributacao
     AND   T.IDREF = E.CODCADASTROPRINC
     AND   T.CODOBSERVACAO = S.CODOBSERVACAO
     --AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.SEQFAMILIA), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.IDREF), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
     AND   R.nrodivisao = D.nrodivisao
     AND   R.NUMREGIAO = (SELECT MIN(TO_CHAR(VALOR)) VALOR
                          FROM PCPARAMFILIAL
                          WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                          AND VALOR <> '99'
                          AND VALOR IS NOT NULL
                          --AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
                          HAVING MIN(VALOR) IS NOT NULL
                          
                          /*UNION ALL
                          
                          SELECT TO_CHAR(NROEMPRESA) VALOR 
                          FROM MONITORPDVMIDDLE.TB_EMPRESA 
                          WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S' 
                          AND ROWNUM = 1*/)
                          
     UNION ALL
     
     SELECT 
        ROW_NUMBER() OVER(partition by FAM.SEQFAMILIA,  S.SEQOBSSPED  order BY  E.CODEXCECAO) sequencia,
        FAM.SEQFAMILIA,
        E.CODEXCECAO,
        S.SEQOBSSPED,
        E.CODCADASTROPRINC,
        E.CODCADASTROEXCECAO CODAJUSTEEFD,
        T.UFORIGEM UF,
        E.TIPO1,
        E.VALOR1,
        'S' ATIVO,
        E.TIPO1||E.VALOR1 IDREF
     FROM MONITORPDVMIDDLE.TB_CADOBSSPED S,
          MONITORPDVMIDDLE.TB_FAMILIA FAM,
          MONITORPDVMIDDLE.tb_famdivisao D,
          MONITORPDVMIDDLE.TB_TRIBUTACAOUF T,
          PCEXCECAOCADASTROSFISCAIS E
          --pcdepararegiaoc5 R
          --VW_INT_C5_TRIB_UF_CONSOLIDADA T
     WHERE S.CODAJUSTEEFD = E.CODCADASTROPRINC
     AND   D.seqfamilia = FAM.SEQFAMILIA
     AND   FAM.ATIVO = 'S'
     AND   T.NROTRIBUTACAO = D.nrotributacao
     AND   T.IDREF = E.CODCADASTROPRINC
     AND   T.CODOBSERVACAO = S.CODOBSERVACAO
     --AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.SEQFAMILIA), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.IDREF), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
     AND   D.nrodivisao = (SELECT TO_CHAR(NROEMPRESA) VALOR 
                          FROM MONITORPDVMIDDLE.TB_EMPRESA 
                          WHERE ROWNUM = 1)
    )EXCECAO
WHERE EXCECAO.SEQUENCIA = 1
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DIVISAO AS
(
SELECT TO_CHAR(R.NUMREGIAO) NUMREGIAO,
       TO_CHAR(D.NRODIVISAO) NRODIVISAO,
       SUBSTR(R.REGIAO, 1, 20) DIVISAO,
       'V' TIPO,
       (CASE
           WHEN NVL(R.STATUS, 'A') = 'A' THEN
                'S'
           ELSE 'N'
        END) ATIVO,
        R.NUMREGIAO||R.UF IDREF
FROM PCREGIAO R,
     PCDEPARAREGIAOC5 D,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO') DTPADRAO
 WHERE R.NUMREGIAO = D.NUMREGIAO(+)
 AND   NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
 AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
UNION ALL
SELECT  TO_CHAR(F.CODFILIALINTEGRACAO)  NUMREGIAO,
        TO_CHAR(F.CODFILIALINTEGRACAO)  NRODIVISAO,
        'DIVISAO TRIBUTACAO POR UF' DIVISAO,
        'V' TIPO,
        (CASE
            WHEN F.dtexclusao IS NULL
                THEN 'S'
            ELSE
          'N'
        END) ATIVO,
        F.UF IDREF
FROM PCFILIAL F,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO'
     ) DTPADRAO,
     VW_INT_C5_OBTER_FILIAIS_C5 c5
WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
AND F.codigo <>'99'
AND F.codigo = c5.codfilial
AND NVL(F.Dtalterc5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CFOP AS(
SELECT *FROM
  (SELECT DISTINCT
          CONCAT(a.codst,o.codfiscal)     AS codgeraloper,
          SUBSTR(UPPER(o.desccfo),1,40)   AS descricao,
          SUBSTR(UPPER(o.desccfo),1,80)   AS aplicacao,
          a.codst                         AS nrotributacao,
          a.cfop                          AS cfopestado,
          a.cfopexterno                   AS cfopforaestado,
          a.uforigem                      AS uforigem,
          a.ufdestino                     AS ufdestino,
          'N'                             AS contribicms,
           0                              AS nroregtributacao,
          'S'                             AS ativo,
          a.dtalterc5                     AS dtalterc5,
          'N'                             AS calculaicmsst,
          'N'                             AS gerareducaobasest,
          'N'                             AS calculaipi,
          'N'                             AS tipocalculoipi,
          'N'                             AS calculafecp,
          'T'                             AS tipofaturamento,
          'N'                             AS consumidorfinal,
          'N'                             AS vendapresencial,
          'P'                             AS tipotributacao
    FROM  pcconsolidatributacao a,
          pccfo o
   WHERE  o.codfiscal = a.cfop)
   WHERE UFDESTINO IS NOT NULL
         AND UFORIGEM IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_LEITRANSP AS
(
SELECT
  CARGATRIB."CODNCMSH",
  CARGATRIB."EX",
  CARGATRIB."UFDESTINO",
  MAX(CARGATRIB."PERCTRIBUTOS") PERCTRIBUTOS,
  (CASE
    WHEN (MAX(CARGATRIB.PERCTRIBUTONACFEDERAL) = 0) AND
         (MAX(CARGATRIB.PERCTRIBUTOESTADUAL) = 0) AND
         (MAX(CARGATRIB.PERCTRIBUTOMUNICIPAL) = 0) 
    THEN
         MAX(CARGATRIB.PERCTRIBUTOS)
    ELSE MAX(CARGATRIB.PERCTRIBUTONACFEDERAL) 
  END) PERCTRIBUTONACFEDERAL,
  MAX(CARGATRIB."PERCTRIBUTOIMPORTADO") PERCTRIBUTOIMPORTADO,
  MAX(CARGATRIB."PERCTRIBUTOIMPFEDERAL") PERCTRIBUTOIMPFEDERAL,
  MAX(CARGATRIB."PERCTRIBUTOESTADUAL") PERCTRIBUTOESTADUAL,
  MAX(CARGATRIB."PERCTRIBUTOMUNICIPAL")PERCTRIBUTOMUNICIPAL ,
  MAX(CARGATRIB."ATIVO") ATIVO
FROM
  (SELECT DISTINCT
       NCMFILIAL.CODNCM codncmsh,
       NVL(NCMFILIAL.CODEX, 0) ex,
       NCMFILIAL.UF ufdestino,
       NVL(PRODTRIB.PERCTRIBUTOS, 0) PERCTRIBUTOS,
       NVL(TRIBNCMFILIAL.percentfisica, 0) perctributonacfederal,
       NVL(TRIBNCMFILIAL.percfisicaestimp, 0) perctributoimportado,
       NVL(TRIBNCMFILIAL.percentfisicaimportado, 0) perctributoimpfederal,
       NVL(TRIBNCMFILIAL.percfisicaestnac, 0) perctributoestadual,
       NVL(TRIBNCMFILIAL.percfisicamunicnac, 0) perctributomunicipal,

       (CASE
           WHEN NCMFILIAL.DTEXCLUSAO IS NULL THEN
                'S'
           ELSE
                'N'
       END) ativo
   FROM
     (SELECT DISTINCT
             PCNCM.CODNCM, /*CODNCM É CADASTRADO SEM O "." */
             PCNCM.CODNCMEX, /*CODNCM DA PCNCM É CADASTRADO COM "." E JÁ POSSUI A EXCEÇÃO CASO EXISTA*/
             PCNCM.CODEX,
             PCNCM.DTEXCLUSAO,
             PCREGIAO.UF,
             PCREGIAO.CODFILIAL
           FROM PCNCM,
                PCREGIAO/*,
                (select min(s.ultimaexecucao) ultimaexecucao
                 from pccontroleconsinco s
                 where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARGATRIBUTARIA')
                )DTPADRAO*/
           WHERE PCNCM.CODNCMEX IS NOT NULL
           AND   PCNCM.CODEX IS NULL
           AND   PCREGIAO.NUMREGIAO IN (SELECT DISTINCT(VALOR)
                                        FROM PCPARAMFILIAL
                                        WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                                        AND VALOR <> '99'
                                        AND VALOR IS NOT NULL)
           --AND   NVL(PCNCM.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
     )NCMFILIAL,

    (SELECT
       PCTRIBNCMFILIAL.CODNCM||PCTRIBNCMFILIAL.CODFILIAL ID,
       PCTRIBNCMFILIAL.percentfisica,
       PCTRIBNCMFILIAL.percfisicaestimp,
       PCTRIBNCMFILIAL.percentfisicaimportado,
       PCTRIBNCMFILIAL.percfisicaestnac,
       PCTRIBNCMFILIAL.percfisicamunicnac
     FROM PCTRIBNCMFILIAL, PCFILIAL/*,
          (select min(s.ultimaexecucao) ultimaexecucao
           from pccontroleconsinco s
           where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARGATRIBUTARIA')
           )DTPADRAO*/
     WHERE PCTRIBNCMFILIAL.CODFILIAL = PCFILIAL.CODIGO
     AND   PCTRIBNCMFILIAL.CODFILIAL <> '99'
     --AND   NVL(PCTRIBNCMFILIAL.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
     )TRIBNCMFILIAL,

     (SELECT DISTINCT
         P.codncmex,
         G.UF,
         MAX(T.PERCTRIBUTOS) PERCTRIBUTOS
      FROM PCTRIBUT T,
           PCTABPR R,
           PCNCM N,
           PCPRODUT P,
           PCREGIAO G/*,
          (select min(s.ultimaexecucao) ultimaexecucao
           from pccontroleconsinco s
           where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARGATRIBUTARIA')
          )DTPADRAO*/
      WHERE 
      R.CODST = T.CODST
      AND   P.CODPROD = R.CODPROD
      AND   G.NUMREGIAO = R.NUMREGIAO
      AND   G.NUMREGIAO IN (SELECT DISTINCT(VALOR)
                            FROM PCPARAMFILIAL
                            WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                            AND VALOR <> '99'
                            AND VALOR IS NOT NULL)

      AND   N.CODNCMEX IS NOT NULL
      AND   P.CODNCMEX IS NOT NULL
      AND   N.CODEX IS NULL
      AND   T.CODST IS NOT NULL
      AND   P.codncmex = N.CODNCM||'.'||N.CODEX
      --AND   NVL(T.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
      GROUP BY P.codncmex, G.UF
     ) PRODTRIB

   WHERE NCMFILIAL.CODNCMEX||NCMFILIAL.CODFILIAL = TRIBNCMFILIAL.ID(+)
   AND   PRODTRIB.codncmex = NCMFILIAL.CODNCM||'.'||NCMFILIAL.CODEX
   AND   PRODTRIB.UF = NCMFILIAL.UF
  )CARGATRIB
GROUP BY CARGATRIB.CODNCMSH,
         CARGATRIB.EX,
         CARGATRIB.UFDESTINO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DEPARATRIBUTACAO AS (
  SELECT 
    DEPARA.SEQCENARIO,
    TRIBUTACAO.CODIGO_TRIBUTACAO,
    TRIBUTACAO.TIPO_IMPOSTO_EXIBIR AS TIPO_IMPOSTO,
    CASE 
      WHEN TRIBUTACAO.DTINATIVACAO IS NULL THEN 'S' 
      ELSE 'N' 
    END AS ATIVO
  FROM (
    SELECT 
      CODIGO_TRIBUTACAO,
      'CBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINICIO_VIGENCIA,
      DTFIM_VIGENCIA,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINICIO_VIGENCIA,
      DTFIM_VIGENCIA,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IS' AS TIPO_IMPOSTO_EXIBIR,
      DTINICIO_VIGENCIA,
      DTFIM_VIGENCIA,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'IS') TRIBUTACAO,
    PCDEPARATRIBUTACAOC5 DEPARA
  WHERE TRIBUTACAO.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO(+)
    AND TRIBUTACAO.TIPO_IMPOSTO_EXIBIR = DEPARA.TIPO_IMPOSTO(+)
    AND (TRIBUTACAO.DTINICIO_VIGENCIA IS NOT NULL AND TRIBUTACAO.DTFIM_VIGENCIA IS NOT NULL)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTIMPOSTO AS
(
  SELECT 1 as SEQIMPOSTO, 'CBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQIMPOSTO, 'IBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQIMPOSTO, 'IS'  as DESCRICAO, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIO AS (
    SELECT 
      DEPARA.SEQCENARIO,
      DEPARA.TIPO_IMPOSTO DESCRICAO,
      T.DESCRICAO_TRIBUTACAO ORIENTACAO,
      T.DTINICIO_VIGENCIA DTAINICIALVALIDADE,
      T.DTFIM_VIGENCIA DTAFINALVALIDADE,
      0 TOTALPONTOS,
      DEPARA.ATIVO,
      T.DTALTERC5,
      IMP.SEQIMPOSTO,
      DEPARA.CODIGO_TRIBUTACAO IDREF
    FROM PCDEPARATRIBUTACAOC5 DEPARA,
        VW_INT_C5_CCTIMPOSTO IMP,
        PCTRIBUTACAO T,
        (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
            FROM PCCONTROLECONSINCO S
          WHERE ATIVO = 'A'
            AND ((UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIO') 
              OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAO')
              OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAOITEM'))
          ) D
  WHERE T.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO
    AND (SYSDATE >= T.DTINICIO_VIGENCIA AND SYSDATE <= T.DTFIM_VIGENCIA)
    AND NVL(T.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
    AND DEPARA.TIPO_IMPOSTO = IMP.DESCRICAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCONDICAO AS
(
  SELECT 1 as SEQCONDICAO, 'PRODUTO' as IDENTIFICADOR, 700 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQCONDICAO, 'FAMILIA' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQCONDICAO, 'NCM' as IDENTIFICADOR, 500 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 4 as SEQCONDICAO, 'CFOP' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 5 as SEQCONDICAO, 'CGO' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 6 as SEQCONDICAO, 'ORIGEM' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 7 as SEQCONDICAO, 'DESTINO' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 8 as SEQCONDICAO, 'UFORIGEM' as IDENTIFICADOR, 101 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 9 as SEQCONDICAO, 'UFDESTINO' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL 
  SELECT 10 as SEQCONDICAO, 'NBS' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOCONDICAO AS
(
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
          FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
      WHERE SEQCENARIO = CEN.SEQCENARIO
      AND SEQCONDICAO = CN.SEQCONDICAO
      AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    CASE WHEN EXISTS (SELECT 1 FROM PCTRIBUTACAO_FILTRO_PRODUTO TP WHERE CEN.IDREF = TP.CODIGO_TRIBUTACAO AND TP.DTEXCLUSAO IS NULL)
    	THEN CN.PESOBUSCA 
    	ELSE 1
    END PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       VW_INT_C5_CCTCONDICAO CN,
       PCTRIBUTACAO T
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 1   
  
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 2
  
  UNION ALL
  
  SELECT
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    CASE WHEN EXISTS (SELECT 1 FROM PCTRIBUTACAO_FILTRO_NCM TP WHERE CEN.IDREF = TP.CODIGO_TRIBUTACAO AND TP.DTEXCLUSAO IS NULL)
    	THEN CN.PESOBUSCA 
    	ELSE 1
    END PONTOSBUSCA,   
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       VW_INT_C5_CCTCONDICAO CN,
       PCTRIBUTACAO T
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 3 

  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 4
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 5
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 6
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 7    
  
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    CASE 
      WHEN T.TIPO_LOCAL_CONSUMO = 'G' AND T.LOCAL_CONSUMO_GERAL = 'BR' THEN 100
      WHEN T.TIPO_LOCAL_CONSUMO = 'G' AND T.LOCAL_CONSUMO_GERAL <> 'BR' THEN CN.PESOBUSCA
      WHEN T.TIPO_LOCAL_CONSUMO = 'M' THEN 102
      ELSE 1
    END PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 8
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 9 
	
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 10   

)	

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENCONDITEM AS 
(
  SELECT
    NVL((
        SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
          AND VALOR = NVL(TO_CHAR(DEPARA.SEQPRODUTO), '0')
          AND IDENTIFICADOR = 'PRODUTO'
          AND ROWNUM = 1
      ), 0) AS SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    NVL(TO_CHAR(DEPARA.SEQPRODUTO), '0') AS VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'PRODUTO' AS IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    DPTRIB.CODIGO_TRIBUTACAO AS IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC
  JOIN PCDEPARATRIBUTACAOC5 DPTRIB
    ON DPTRIB.SEQCENARIO = CC.SEQCENARIO
  LEFT JOIN PCTRIBUTACAO_FILTRO_PRODUTO N
    ON N.CODIGO_TRIBUTACAO = DPTRIB.CODIGO_TRIBUTACAO
   AND N.DTEXCLUSAO IS NULL
  LEFT JOIN PCDEPARAPRODC5 DEPARA
    ON DEPARA.CODPROD = N.CODPROD
   AND DEPARA.ATIVO = 'S'
  WHERE CC.SEQCONDICAO = 1

  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'FAMILIA' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 2    
    
  UNION ALL

  SELECT
    NVL((
        SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
          AND VALOR = NVL(TO_CHAR(N.NCM), '0')
          AND IDENTIFICADOR = 'NCM'
          AND ROWNUM = 1
      ), 0) AS SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    NVL(TO_CHAR(N.NCM), '0') AS VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'NCM' AS IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    DPTRIB.CODIGO_TRIBUTACAO AS IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC
  JOIN PCDEPARATRIBUTACAOC5 DPTRIB
    ON DPTRIB.SEQCENARIO = CC.SEQCENARIO
  LEFT JOIN PCTRIBUTACAO_FILTRO_NCM N
    ON N.CODIGO_TRIBUTACAO = DPTRIB.CODIGO_TRIBUTACAO
   AND N.DTEXCLUSAO IS NULL
  WHERE CC.SEQCONDICAO = 3

  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'CFOP' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 4
    
  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'CGO' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 5
    
  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'ORIGEM' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 6
    
  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'DESTINO' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 7    
    
  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
          AND VALOR = CASE WHEN T.TIPO_LOCAL_CONSUMO = 'G' 
                        THEN TO_CHAR(NVL(T.LOCAL_CONSUMO_GERAL, 'BR'))
                        ELSE TO_CHAR(T.LOCAL_CONSUMO_MUNICIPIO)
                      END
          AND IDENTIFICADOR = 'UFORIGEM'
          AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    CASE WHEN T.TIPO_LOCAL_CONSUMO = 'G' 
      THEN TO_CHAR(NVL(T.LOCAL_CONSUMO_GERAL, 'BR'))
      ELSE TO_CHAR(T.LOCAL_CONSUMO_MUNICIPIO)
    END VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'UFORIGEM' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 8
    
  UNION ALL

  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'UFDESTINO' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 9
	
  UNION ALL 
  
  SELECT
    NVL((SELECT SEQCENARIOCONDICAOITEM
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
        WHERE SEQCENARIOCONDICAO = CC.SEQCENARIOCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAOITEM,
    CC.SEQCENARIOCONDICAO,
    '0' VALOR,
    'N' AS INDTIPOIDENTIDADE,
    'NBS' IDENTIFICADOR,
    CC.SEQCENARIO,
    CC.ATIVO,
    T.CODIGO_TRIBUTACAO IDREF
  FROM VW_INT_C5_CCTCENARIOCONDICAO CC,
       PCDEPARATRIBUTACAOC5 DPTRIB,
       PCTRIBUTACAO T
  WHERE CC.SEQCENARIO = DPTRIB.SEQCENARIO
    AND DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    AND CC.SEQCONDICAO = 10
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTFORMULA AS
(
  SELECT 1 as SEQFORMULA, 'PADRAO' as DESCRICAO, '(PRECOPRODUTO + ACRESCIMO + MULTASJUROS + DESCCONDICIONAL + SEGUROTAXA + FRETE)' as BASE, '* (ALIQUOTA - (ALIQUOTA * REDUCAO))' as ALIQUOTA, 'F' as INDTIPOFORMULA, 'S' as ATIVO FROM PCCONSUM
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCODIGOTRIBUTARIO AS 
(
  SELECT 
    *
  FROM (
    SELECT
      MIN(NVL((SELECT SEQCODIGOTRIBUTARIO
              FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO
          WHERE CODIGO = CODTRIB.CODIGO
          AND ROWNUM = 1), 0)) SEQCODIGOTRIBUTARIO,
      CODTRIB.CODIGO,
      CODTRIB.DESCRICAO,
      CODTRIB.CODIGOPAI,
      CODTRIB.INDTIPOCODIGO,
      CODTRIB.DTAINICIALVALIDADE,
      CODTRIB.DTAFINALVALIDADE,
      CODTRIB.PERALIQREDCBS,
      CODTRIB.PERALIQREDIBS,
      CODTRIB.ATIVO,
      CODTRIB.IDREF,
      ROW_NUMBER() OVER (
        PARTITION BY CODTRIB.CODIGO
        ORDER BY CODTRIB.DTAFINALVALIDADE ASC
      ) AS RN
    FROM (
      SELECT
        T.CST AS CODIGO,
        'CST ' || T.CST AS DESCRICAO,
        1 AS INDTIPOCODIGO,
        T.CCLASSTRIB AS CODIGOPAI,
        CEN.DTAINICIALVALIDADE,
        CEN.DTAFINALVALIDADE,
        NVL(T.PERC_RED_CBS, 0) AS PERALIQREDCBS,
        CASE
          WHEN T.TIPO_LOCAL_CONSUMO = 'G' THEN NVL(T.PERC_RED_IBS_UF, 0)
          WHEN T.TIPO_LOCAL_CONSUMO = 'M' THEN NVL(T.PERC_RED_IBS_MUN, 0)
          ELSE 0
        END AS PERALIQREDIBS,
        CEN.ATIVO,
        CEN.IDREF IDREF
      FROM PCTRIBUTACAO T
      INNER JOIN MONITORPDVMIDDLE.TB_CCTCENARIO CEN ON (CEN.IDREF = T.CODIGO_TRIBUTACAO)
      WHERE (SYSDATE >= CEN.DTAINICIALVALIDADE AND SYSDATE <= CEN.DTAFINALVALIDADE)
      
      UNION ALL
      
      SELECT
        T.CCLASSTRIB AS CODIGO,
        'CCLASSTRIB ' || T.CCLASSTRIB AS DESCRICAO,
        2 AS INDTIPOCODIGO,
        T.CCLASSTRIB AS CODIGOPAI,
        CEN.DTAINICIALVALIDADE,
        CEN.DTAFINALVALIDADE,
        NVL(T.PERC_RED_CBS, 0) AS PERALIQREDCBS,
        CASE
          WHEN T.TIPO_LOCAL_CONSUMO = 'G' THEN NVL(T.PERC_RED_IBS_UF, 0)
          WHEN T.TIPO_LOCAL_CONSUMO = 'M' THEN NVL(T.PERC_RED_IBS_MUN, 0)
          ELSE 0
        END AS PERALIQREDIBS,
        CEN.ATIVO,
        CEN.IDREF IDREF
      FROM PCTRIBUTACAO T
      INNER JOIN MONITORPDVMIDDLE.TB_CCTCENARIO CEN ON (CEN.IDREF = T.CODIGO_TRIBUTACAO)
      WHERE (SYSDATE >= CEN.DTAINICIALVALIDADE AND SYSDATE <= CEN.DTAFINALVALIDADE)
    ) CODTRIB
    GROUP BY CODTRIB.CODIGO, CODTRIB.DESCRICAO, CODTRIB.CODIGOPAI, CODTRIB.INDTIPOCODIGO, 
            CODTRIB.DTAINICIALVALIDADE, CODTRIB.DTAFINALVALIDADE, CODTRIB.PERALIQREDCBS, 
            CODTRIB.PERALIQREDIBS, CODTRIB.ATIVO, CODTRIB.IDREF
  )
  WHERE RN = 1
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOIMPOSTO AS 
(
  SELECT
    NVL((SELECT SEQCENARIOIMPOSTO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOIMPOSTO
        WHERE SEQIMPOSTO = CEN.SEQIMPOSTO
          AND SEQCENARIO = CEN.SEQCENARIO        
        AND ROWNUM = 1), 0) SEQCENARIOIMPOSTO,
    CEN.SEQCENARIO,
    CEN.SEQIMPOSTO,
    (SELECT CCTC.SEQCODIGOTRIBUTARIO FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO CCTC WHERE TO_CHAR(CEN.IDREF) = CCTC.IDREF AND CCTC.INDTIPOCODIGO = 1 AND CCTC.CODIGO = T.CST) SEQCODTRIBCST,
    (SELECT CCTC.SEQCODIGOTRIBUTARIO FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO CCTC WHERE TO_CHAR(CEN.IDREF) = CCTC.IDREF AND CCTC.INDTIPOCODIGO = 2 AND CCTC.CODIGO = T.CCLASSTRIB) SEQCODTRIBCCLASTRIB,
    CASE
      WHEN CEN.DESCRICAO = 'IS' THEN
           NVL(T.PERC_IS, 0)
      WHEN CEN.DESCRICAO = 'CBS' THEN
           NVL(T.PERC_CBS, 0)
      WHEN CEN.DESCRICAO = 'IBS' AND T.TIPO_LOCAL_CONSUMO = 'G' THEN
           NVL(T.PERC_IBS_UF, 0)
      WHEN CEN.DESCRICAO = 'IBS' AND T.TIPO_LOCAL_CONSUMO = 'M' THEN
           NVL(T.PERC_IBS_MUN, 0)     
      ELSE 0
    END PERALIQ,
    
    CASE
      WHEN CEN.DESCRICAO = 'CBS' THEN
           NVL(T.PERC_RED_CBS, 0)
      WHEN CEN.DESCRICAO = 'IBS' AND T.TIPO_LOCAL_CONSUMO = 'G' THEN
           NVL(T.PERC_RED_IBS_UF, 0)
      WHEN CEN.DESCRICAO = 'IBS' AND T.TIPO_LOCAL_CONSUMO = 'M' THEN
           NVL(T.PERC_RED_IBS_MUN, 0)     
      ELSE 0
    END PERALIQRED,
    
    CASE
      WHEN CEN.DESCRICAO = 'IBS' AND T.TIPO_LOCAL_CONSUMO = 'M' THEN
           NVL(T.PERC_IBS_MUN, 0)     
      ELSE 0
    END PERALIQMUN,

    1 SEQFORMULA,
    CEN.ATIVO,
    CEN.IDREF || '-' || CEN.DESCRICAO IDREF
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T   
  WHERE CEN.IDREF = T.CODIGO_TRIBUTACAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCONFIGURACAO AS
(
  SELECT 
    1 AS SEQCONFIGURACAO, 
    NVL((SELECT 
            CASE 
              WHEN VALOR = 'S' THEN 'P'
              ELSE 'H'
            END
         FROM PCPARAMFILIAL WHERE NOME = 'USAREFORMAPDVSUPERMERCADO'), 'H') AS INDTIPOAMBIENTE, 
    'S' AS ATIVO 
  FROM PCCONSUM
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTALIQUOTA AS 
(
  SELECT 
    (SELECT IMP.SEQIMPOSTO FROM MONITORPDVMIDDLE.TB_CCTIMPOSTO IMP WHERE IMP.DESCRICAO = CEN.DESCRICAO) AS SEQIMPOSTO,
    TRIB.DTINICIO_VIGENCIA AS DTAINICIALVALIDADE,
    TRIB.DTFIM_VIGENCIA AS DTAFINALVALIDADE,
    NVL(CASE
      WHEN CEN.DESCRICAO = 'CBS' THEN TRIB.PERC_CBS
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'M' THEN TRIB.PERC_IBS_MUN
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'G' THEN TRIB.PERC_IBS_UF
      WHEN CEN.DESCRICAO = 'IS' THEN TRIB.PERC_IS
      ELSE 0
    END, 0) AS PERALIQ,
    CASE
      WHEN CEN.DESCRICAO IN ('CBS', 'IS') THEN ''
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'M' THEN (SELECT C.UF FROM PCCIDADE C WHERE C.CODIBGE = TRIB.LOCAL_CONSUMO_MUNICIPIO) 
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'G' THEN TRIB.LOCAL_CONSUMO_GERAL
      ELSE NULL
    END AS UF,
    CASE
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'M' THEN TRIB.LOCAL_CONSUMO_MUNICIPIO 
      ELSE NULL
    END AS CODIBGE,
    CEN.ATIVO,
    CEN.IDREF AS IDREF
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
      PCTRIBUTACAO TRIB,
      (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
        WHERE ATIVO = 'A'
          AND (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTALIQUOTA')
      ) D
  WHERE CEN.IDREF = TRIB.CODIGO_TRIBUTACAO
    AND (SYSDATE >= TRIB.DTINICIO_VIGENCIA AND SYSDATE <= TRIB.DTFIM_VIGENCIA)
    AND NVL(TRIB.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOITEM AS 
WITH BASE_UNICA AS (
    SELECT
        SEQCENARIO,
        MAX(CASE WHEN IDENTIFICADOR = 'FAMILIA' THEN VALOR END) AS FAMILIA,
        MAX(CASE WHEN IDENTIFICADOR = 'CGO'     THEN VALOR END) AS CGO,
        MAX(CASE WHEN IDENTIFICADOR = 'ORIGEM'  THEN VALOR END) AS ORIGEM,
        MAX(CASE WHEN IDENTIFICADOR = 'DESTINO' THEN VALOR END) AS DESTINO,
        MAX(CASE WHEN IDENTIFICADOR = 'NBS'     THEN VALOR END) AS NBS,
        MIN(INDTIPOENTIDADE) AS INDTIPOENTIDADEORIGEM, 
        MIN(INDTIPOENTIDADE) AS INDTIPOENTIDADEDESTINO,
        MIN(ATIVO) AS ATIVO,
		MIN(SEQCENARIOCONDICAOITEM) AS IDREF
    FROM 
		MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
    GROUP BY 
		SEQCENARIO
),

PRODUTOS_E_NCMS AS (
    SELECT DISTINCT 
        SEQCENARIO, 
        VALOR AS PRODUTO, 
        '0'   AS NCM
    FROM 
		MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
    WHERE IDENTIFICADOR = 'PRODUTO'
      AND VALOR <> '0' 

    UNION ALL

    SELECT DISTINCT 
        SEQCENARIO, 
        '0'   AS PRODUTO, 
        VALOR AS NCM
    FROM 
		MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
    WHERE IDENTIFICADOR = 'NCM'
      AND VALOR <> '0'
)

SELECT
    B.SEQCENARIO,
    NVL(I.PRODUTO, '0') AS PRODUTO, 
    NVL(I.NCM, '0') AS NCM,
    B.FAMILIA,
    B.CGO,
    B.ORIGEM,
    B.DESTINO,
    B.INDTIPOENTIDADEORIGEM,
    B.INDTIPOENTIDADEDESTINO,
    B.ATIVO,
    B.NBS,
    B.IDREF
FROM 
	BASE_UNICA B
LEFT JOIN PRODUTOS_E_NCMS I 
    ON B.SEQCENARIO = I.SEQCENARIO
ORDER BY
	I.SEQCENARIO,
	PRODUTO,
	NCM



