CREATE OR REPLACE VIEW VW_INT_C5_TRIB_UF AS
(SELECT distinct
            t.codst nrotributacao,
            c.UFORIGEM uforigem,
            c.UFDESTINO ufdestino,
            'SN' tipotributacao,
            0 nroregtributacao,
            c.percaliquota,
            (case
              when (Length(NVL(t.sittributecf, t.sittributpf))) = 2 then
                   '0' || NVL(t.sittributecf, t.sittributpf) 
              else NVL(t.sittributecf, t.sittributpf)
            end)  situacaotributacao,
		    (case
              when Length(t.sittributsimplesnac) = 2 then
                   '0' || t.sittributsimplesnac 
              else t.sittributsimplesnac
            end) SITUACAOSIMPLES,
            c.percisento,
            c.perctributado,
            c.percoutro,
            0 percacrescst,
            NVL(t.aliqstsaida,0) percisentost,
            'B' tipocalcfcp,
            NVL(C.percaliqfcpicms, t.peracrescimofuncep) percaliqfcpicms,

            (case
               when NVL(C.percaliqfcpicms, t.peracrescimofuncep) > 0 THEN
                    100
               else  0
            end) percbasefcpicms,

            c.reducaobasest,
            'T' tiporeducaoicmscalcst,
            0 perctributst,
            'S' ativo,
            0 situacaopis,
            0 situacaocofins,
            0 percpis,
            0 perccofins,
            0 percbasefcpst,
            0 percaliqfcpst,
            CASE WHEN NVL(t.PERDESCICMISENCAO, 0) > 0 
            	THEN c.percdesoneracao
            	ELSE NULL
            END percaliqicmsdeson,
            CASE WHEN NVL(t.PERDESCICMISENCAO, 0) > 0 
            	THEN c.calcicmsdeson
            	ELSE 'N'
            END calcicmsdeson,
            c.codmotivodesoneracao motivodesonicms,
            c.codbeneficiofiscal codbeneficiodesonicms,
            --t.codst||(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = C.UFORIGEM) codobservacao,

            (CASE WHEN c.codbeneficiofiscal is null THEN 
                      null
                 ELSE t.codst||(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = C.UFORIGEM) 
            END)  codobservacao,

            t.codst,
            t.mensagem || ' - TRIBUTACAO' tributacao,
            t.mensagem || ' - TRIBUTACAO' descaplicacao,
            COALESCE(t.codecf, '0000') codecf,
            /*GREATEST(
                     NVL(t.DTALTERC5, d.datapadrao),
                     NVL(c.DTALTERC5, d.datapadrao)) data,*/

            GREATEST(NVL(t.DTALTERC5, d.datapadrao),
                         d.datapadrao
                    ) data,

            COALESCE(c.aliqicms1,0) aliqicms1,
            COALESCE(c.aliqicms2,0) aliqicms2
FROM pctribut t,
     PCCONSOLIDATRIBUTACAO c,
     /*(SELECT MIN(s.ultimaexecucao) datapadrao FROM pccontroleconsinco s) d*/
     (SELECT MIN(S.ULTIMAEXECUCAO)  datapadrao
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAOUF')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBS')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPED')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPEDFAMILIA')
      )d

WHERE t.codst = c.codst
AND t.codecf IS NOT NULL
AND t.codst is not null
AND NVL(NVL(T.CODICMPF, T.CODICM), 0) = c.PERCALIQUOTA
)

\

CREATE OR REPLACE VIEW VW_INT_C5_TRIB_UF_CONSOLIDADA AS
(
SELECT  distinct
        NROTRIBUTACAO,
        UFORIGEM,
        UFDESTINO,
        'SN' TIPOTRIBUTACAO,
        NROREGTRIBUTACAO,
        PERCALIQUOTA,
        SITUACAOTRIBUTACAO,
		SITUACAOSIMPLES,
        PERCISENTO,
        PERCTRIBUTADO,
        PERCOUTRO,
        PERCACRESCST,
        PERCISENTOST,
        TIPOCALCFCP,
        PERCBASEFCPICMS,
        PERCALIQFCPICMS,
        REDUCAOBASEST,
        TIPOREDUCAOICMSCALCST,
        PERCTRIBUTST,
        ATIVO,
        PERCBASEFCPST,
        PERCALIQFCPST,
        CALCICMSDESON,
        PERCALIQICMSDESON,
        MOTIVODESONICMS,
        NULL CODBENEFICIODESONICMS,
        CODOBSERVACAO,
        CODBENEFICIODESONICMS IDREF--(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = UFORIGEM) IDREF
  FROM VW_INT_C5_TRIB_UF
 WHERE DATA >= (SELECT MIN(S.ULTIMAEXECUCAO)  ULTIMAEXECUCAO
                FROM PCCONTROLECONSINCO S 
                WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAOUF')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBS')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPED')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPEDFAMILIA')
               )
 AND LENGTH(SITUACAOTRIBUTACAO) <= 3 --Não considerar CST de Simples Nacional que pode estar com 4 digitos  
 UNION ALL
 SELECT  distinct
        NROTRIBUTACAO,
        UFORIGEM,
        UFDESTINO,
        'SC' TIPOTRIBUTACAO,
        NROREGTRIBUTACAO,
        PERCALIQUOTA,
        SITUACAOTRIBUTACAO,
		SITUACAOSIMPLES,
        PERCISENTO,
        PERCTRIBUTADO,
        PERCOUTRO,
        PERCACRESCST,
        PERCISENTOST,
        TIPOCALCFCP,
        PERCBASEFCPICMS,
        PERCALIQFCPICMS,
        REDUCAOBASEST,
        TIPOREDUCAOICMSCALCST,
        PERCTRIBUTST,
        ATIVO,
        PERCBASEFCPST,
        PERCALIQFCPST,
        CALCICMSDESON,
        PERCALIQICMSDESON,
        MOTIVODESONICMS,
        NULL CODBENEFICIODESONICMS,
        CODOBSERVACAO,
        CODBENEFICIODESONICMS IDREF--(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = UFORIGEM) IDREF
  FROM VW_INT_C5_TRIB_UF
 WHERE DATA >= (SELECT MIN(S.ULTIMAEXECUCAO)  ULTIMAEXECUCAO
                FROM PCCONTROLECONSINCO S 
                WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAOUF')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBS')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPED')
                or    (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CADOBSSPEDFAMILIA')
               )
 AND LENGTH(SITUACAOTRIBUTACAO) <= 3 
)

\

CREATE OR REPLACE VIEW VW_TB_TRIBUTACAO_CONSOLIDADA AS
(
SELECT NROTRIBUTACAO,
       CODST,
       TRIBUTACAO,
       DESCAPLICACAO,
       CODECF,
       ATIVO,
       DATA,
       ALIQICMS1,
       ALIQICMS2
  FROM VW_INT_C5_TRIB_UF 
 WHERE DATA >= (SELECT MIN(S.ULTIMAEXECUCAO) FROM PCCONTROLECONSINCO S WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_TRIBUTACAO'))

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMDIVISAO AS
WITH 
  cte_param_data AS (
    SELECT /*+ MATERIALIZE */ s.ultimaexecucao 
    FROM pccontroleconsinco s 
    WHERE upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_FAMDIVISAO'
  ),
  cte_filiais_validas AS (
    SELECT /*+ MATERIALIZE */ CODFILIAL, CODFILIALINTEGRACAO FROM VW_INT_C5_OBTER_FILIAIS_C5
  ),
  cte_regioes_validas AS (
    SELECT /*+ MATERIALIZE */ VALOR 
    FROM PCPARAMFILIAL
    WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
      AND CODFILIAL IN (SELECT CODFILIAL FROM cte_filiais_validas)
      AND VALOR <> '99'
      AND VALOR IS NOT NULL
  ),
  cte_pcdeparaprodc5 AS (
    SELECT SEQFAMILIA, SEQPRODUTO, CODPROD, CODAUXILIAR, ATIVO FROM PCDEPARAPRODC5
  ),
  cte_base_tabpr AS (
    SELECT DISTINCT 
           PR.CODPROD, 
           PR.CODST, 
           PR.NUMREGIAO,
           REG.NRODIVISAO
    FROM PCTABPR PR
    JOIN cte_regioes_validas REG_VAL ON PR.NUMREGIAO = REG_VAL.VALOR
    JOIN MONITORPDVMIDDLE.TB_FAMILIA FAM ON PR.CODPROD = FAM.IDREF AND FAM.ATIVO = 'S'
    JOIN PCDEPARAREGIAOC5 REG ON REG.NUMREGIAO = PR.NUMREGIAO
    CROSS JOIN cte_param_data DTPADRAO
    LEFT JOIN MONITORPDVMIDDLE.TB_FAMDIVISAO DIV 
           ON DIV.NROTRIBUTACAO = PR.CODST
          AND DIV.SEQFAMILIA = FAM.SEQFAMILIA
          AND DIV.NRODIVISAO = REG.NRODIVISAO
    WHERE (
       NVL(PR.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
       OR
       DIV.SEQFAMILIA IS NULL
    )
  ),
  cte_base_tabtrib AS (
    SELECT DISTINCT 
           TAB.CODPROD, 
           TAB.CODST, 
           TAB.UFDESTINO, 
           TAB.CODFILIALNF
    FROM PCTABTRIB TAB
    JOIN MONITORPDVMIDDLE.TB_FAMILIA FAM ON TAB.CODPROD = FAM.IDREF AND FAM.ATIVO = 'S'
    CROSS JOIN cte_param_data DTPADRAO
    LEFT JOIN MONITORPDVMIDDLE.TB_FAMDIVISAO DIV 
           ON DIV.NROTRIBUTACAO = TAB.CODST
          AND DIV.SEQFAMILIA = FAM.SEQFAMILIA
    WHERE (
       NVL(TAB.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
       OR
       DIV.SEQFAMILIA IS NULL
    )
  )
  
SELECT
    PRODTRIB."SEQFAMILIA", 
    PRODTRIB."CODPROD", 
    PRODTRIB."NROTRIBUTACAO",
    PRODTRIB."NRODIVISAO",
    PRODTRIB."IDREF",
    PRODTRIB."ATIVO", 
    PRODTRIB."CODORIGEMTRIB"
FROM ( 
  SELECT 
      T.SEQFAMILIA,
      R.CODPROD,
      R.CODST AS nrotributacao,
      0 AS codorigemtrib,
      D.NRODIVISAO,
      D.NUMREGIAO AS IDREF,
      'S' AS ativo
  FROM cte_base_tabpr R
  JOIN cte_pcdeparaprodc5 T ON T.CODPROD = R.CODPROD
  JOIN MONITORPDVMIDDLE.TB_TRIBUTACAOUF F ON F.NROTRIBUTACAO = R.CODST
  JOIN PCCONSOLIDATRIBUTACAO C ON C.CODST = R.CODST AND C.NUMREGIAO = R.NUMREGIAO
  JOIN PCDEPARAREGIAOC5 D ON D.NUMREGIAO = R.NUMREGIAO
  WHERE T.ATIVO = 'S'
    AND R.CODST IS NOT NULL
    AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
  GROUP BY T.SEQFAMILIA, R.CODPROD, R.CODST, D.NRODIVISAO, D.NUMREGIAO

  UNION ALL
  
  SELECT 
      T.SEQFAMILIA,
      TB.CODPROD,
      TB.CODST AS NROTRIBUTACAO,
      0 AS CODORIGEMTRIB,
      C5.CODFILIALINTEGRACAO AS NRODIVISAO,
      C5.CODFILIALINTEGRACAO AS IDREF,
      'S' AS ATIVO
  FROM cte_base_tabtrib TB
  JOIN cte_pcdeparaprodc5 T ON T.CODPROD = TB.CODPROD
  JOIN MONITORPDVMIDDLE.TB_TRIBUTACAOUF F ON F.NROTRIBUTACAO = TB.CODST 
                                          AND F.UFORIGEM = TB.UFDESTINO
  JOIN cte_filiais_validas C5 ON C5.CODFILIAL = TB.CODFILIALNF
  JOIN PCCONSOLIDATRIBUTACAO C ON C.CODST = TB.CODST 
                              AND C.NUMREGIAO = C5.CODFILIALINTEGRACAO 
                              AND C.UFORIGEM = TB.UFDESTINO
                              AND C.CODST = F.NROTRIBUTACAO 
                              AND C.UFORIGEM = F.UFORIGEM
  INNER JOIN PCFILIAL FIL ON FIL.CODIGO = TB.CODFILIALNF 
                          AND FIL.UF = TB.UFDESTINO 
                          AND FIL.CODIGO = C5.CODFILIAL
  INNER JOIN MONITORPDVMIDDLE.TB_EMPRESA E ON E.NROEMPRESA = C.NUMREGIAO 
                                          AND E.NROEMPRESA = C5.CODFILIALINTEGRACAO
  WHERE T.ATIVO = 'S'
    AND TB.CODST IS NOT NULL
    AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
  GROUP BY T.SEQFAMILIA, TB.CODPROD, TB.CODST, C5.CODFILIALINTEGRACAO
) PRODTRIB

 \

CREATE OR REPLACE VIEW VW_INT_C5_CODGERALOPER AS
(SELECT 65  codgeraloper,
        SUBSTR(UPPER(O.desccfo),1,40)    descricao,
        SUBSTR(UPPER(O.desccfo),1,80)    aplicacao,
        5102                             cfopestado,
        6102                             cfopforaestado,
        'N'                              calculaicmsst,
        'N'                              gerareducaobasest,
        'N'                              calculaipi,
        'N'                              tipocalculoipi,
        'N'                              calculafecp,
        'T'                              tipofaturamento,
        'S'                              ativo,
         O.dtalterc5                     dtalterc5,
        'N'                              consumidorfinal,
        'N'                              vendapresencial,
        'P'                              tipotributacao,
        'S'                              gerareducaobasepiscofins
 FROM  PCCFO O,
       
       (select min(s.ultimaexecucao) ultimaexecucao
        from pccontroleconsinco s
        where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CODGERALOPER')
       )DTPADRAO

 WHERE O.codfiscal = 5102
 --AND   NVL(O.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
 UNION ALL
 SELECT 55 codgeraloper,
       SUBSTR(UPPER(O.desccfo), 1, 40) descricao,
       SUBSTR(UPPER(O.desccfo), 1, 80) aplicacao,
       5102 cfopestado,
       6102 cfopforaestado,
       'N' calculaicmsst,
       'N' gerareducaobasest,
       'N' calculaipi,
       'N' tipocalculoipi,
       'N' calculafecp,
       'T' tipofaturamento,
       'S' ativo,
       O.dtalterc5 dtalterc5,
       'N' consumidorfinal,
       'N' vendapresencial,
       'P' tipotributacao,
       'S' gerareducaobasepiscofins
  FROM PCCFO O,
       
       (select min(s.ultimaexecucao) ultimaexecucao
          from pccontroleconsinco s
         where (upper(s.objetoreferencia) =
               'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CODGERALOPER')) DTPADRAO WHERE O.codfiscal = 5102
  -- AND NVL(O.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
 
)

 \

CREATE OR REPLACE VIEW VW_INT_C5_CODGERALOPERCFOP AS
(SELECT   65      codgeraloper,
          T.CODST nrotributacao,
          'N'     contribicms,
          T.CODFISCAL  cfopestado,
          T.CODFISCALINTER cfopforaestado,
          'S' ativo,
          T.DTALTERC5 dtalterc5
FROM  PCTRIBUT T,
      
     (select s.ultimaexecucao
      from pccontroleconsinco s
      where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CODGERALOPERCFOP')
     )DTPADRAO
--WHERE  NVL(T.SITTRIBUTECF, T.SITTRIBUTPF) IN ('00','20','40','41','60','61','90')
WHERE NVL(T.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
AND   T.CODFISCAL IS NOT NULL

)

\

CREATE OR REPLACE VIEW VW_INT_C5_CADOBS AS
(
 SELECT DISTINCT
     T.CODOBSERVACAO,
     'N' INFORMADOTRIBUF,
     'S' GERACBENEFFAMTRIB,
     'S' ATIVO
 FROM Vw_Int_C5_Trib_Uf_Consolidada T
 WHERE T.IDREF IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CADOBSSPED AS
(
SELECT DISTINCT
  T.CODOBSERVACAO||(SELECT TO_NUMBER(CODIBGE) FROM PCESTADO WHERE UF = T.UFORIGEM) SEQOBSSPED,
  T.CODOBSERVACAO,
  T.IDREF CODAJUSTEEFD,
  'S' USACODAJUSTENFE,
  'A' REGISTRO,
  'S' ATIVO
FROM Vw_Int_C5_Trib_Uf_Consolidada T
WHERE T.IDREF IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CADOBSSPEDFAMILIA AS
(

SELECT
  *
FROM (  
     SELECT 
        ROW_NUMBER() OVER(partition by FAM.SEQFAMILIA,  S.SEQOBSSPED  order BY  E.CODEXCECAO) sequencia,
        FAM.SEQFAMILIA,
        E.CODEXCECAO,
        S.SEQOBSSPED,
        E.CODCADASTROPRINC,
        E.CODCADASTROEXCECAO CODAJUSTEEFD,
        T.UFORIGEM UF,
        E.TIPO1,
        E.VALOR1,
        'S' ATIVO,
        E.TIPO1||E.VALOR1 IDREF
     FROM MONITORPDVMIDDLE.TB_CADOBSSPED S,
          MONITORPDVMIDDLE.TB_FAMILIA FAM,
          MONITORPDVMIDDLE.tb_famdivisao D,
          MONITORPDVMIDDLE.TB_TRIBUTACAOUF T,
          PCEXCECAOCADASTROSFISCAIS E,
          pcdepararegiaoc5 R
     WHERE S.CODAJUSTEEFD = E.CODCADASTROPRINC
     AND   D.seqfamilia = FAM.SEQFAMILIA
     AND   FAM.ATIVO = 'S'
     AND   T.NROTRIBUTACAO = D.nrotributacao
     AND   T.IDREF = E.CODCADASTROPRINC
     AND   T.CODOBSERVACAO = S.CODOBSERVACAO
     --AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.SEQFAMILIA), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.IDREF), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
     AND   R.nrodivisao = D.nrodivisao
     AND   R.NUMREGIAO = (SELECT MIN(TO_CHAR(VALOR)) VALOR
                          FROM PCPARAMFILIAL
                          WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                          AND VALOR <> '99'
                          AND VALOR IS NOT NULL
                          --AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
                          HAVING MIN(VALOR) IS NOT NULL
                          
                          /*UNION ALL
                          
                          SELECT TO_CHAR(NROEMPRESA) VALOR 
                          FROM MONITORPDVMIDDLE.TB_EMPRESA 
                          WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S' 
                          AND ROWNUM = 1*/)
                          
     UNION ALL
     
     SELECT 
        ROW_NUMBER() OVER(partition by FAM.SEQFAMILIA,  S.SEQOBSSPED  order BY  E.CODEXCECAO) sequencia,
        FAM.SEQFAMILIA,
        E.CODEXCECAO,
        S.SEQOBSSPED,
        E.CODCADASTROPRINC,
        E.CODCADASTROEXCECAO CODAJUSTEEFD,
        T.UFORIGEM UF,
        E.TIPO1,
        E.VALOR1,
        'S' ATIVO,
        E.TIPO1||E.VALOR1 IDREF
     FROM MONITORPDVMIDDLE.TB_CADOBSSPED S,
          MONITORPDVMIDDLE.TB_FAMILIA FAM,
          MONITORPDVMIDDLE.tb_famdivisao D,
          MONITORPDVMIDDLE.TB_TRIBUTACAOUF T,
          PCEXCECAOCADASTROSFISCAIS E
          --pcdepararegiaoc5 R
          --VW_INT_C5_TRIB_UF_CONSOLIDADA T
     WHERE S.CODAJUSTEEFD = E.CODCADASTROPRINC
     AND   D.seqfamilia = FAM.SEQFAMILIA
     AND   FAM.ATIVO = 'S'
     AND   T.NROTRIBUTACAO = D.nrotributacao
     AND   T.IDREF = E.CODCADASTROPRINC
     AND   T.CODOBSERVACAO = S.CODOBSERVACAO
     --AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.SEQFAMILIA), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   NVL(E.VALOR1, '0') = (DECODE(NVL(E.TIPO1,'XX'), 'PR', TO_CHAR(FAM.IDREF), 'FT', TO_CHAR(D.nrotributacao), 'CM', TO_CHAR(FAM.codnbmsh)))
     AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
     AND   D.nrodivisao = (SELECT TO_CHAR(NROEMPRESA) VALOR 
                          FROM MONITORPDVMIDDLE.TB_EMPRESA 
                          WHERE ROWNUM = 1)
    )EXCECAO
WHERE EXCECAO.SEQUENCIA = 1
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DIVISAO AS
(
SELECT TO_CHAR(R.NUMREGIAO) NUMREGIAO,
       TO_CHAR(D.NRODIVISAO) NRODIVISAO,
       SUBSTR(R.REGIAO, 1, 20) DIVISAO,
       'V' TIPO,
       (CASE
           WHEN NVL(R.STATUS, 'A') = 'A' THEN
                'S'
           ELSE 'N'
        END) ATIVO,
        R.NUMREGIAO||R.UF IDREF
FROM PCREGIAO R,
     PCDEPARAREGIAOC5 D,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO') DTPADRAO
 WHERE R.NUMREGIAO = D.NUMREGIAO(+)
 AND   NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
 AND   FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
UNION ALL
SELECT  TO_CHAR(F.CODFILIALINTEGRACAO)  NUMREGIAO,
        TO_CHAR(F.CODFILIALINTEGRACAO)  NRODIVISAO,
        'DIVISAO TRIBUTACAO POR UF' DIVISAO,
        'V' TIPO,
        (CASE
            WHEN F.dtexclusao IS NULL
                THEN 'S'
            ELSE
          'N'
        END) ATIVO,
        F.UF IDREF
FROM PCFILIAL F,
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_DIVISAO'
     ) DTPADRAO,
     VW_INT_C5_OBTER_FILIAIS_C5 c5
WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
AND F.codigo <>'99'
AND F.codigo = c5.codfilial
AND NVL(F.Dtalterc5, DTPADRAO.ULTIMAEXECUCAO)  >= DTPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CFOP AS(
SELECT *FROM
  (SELECT DISTINCT
          CONCAT(a.codst,o.codfiscal)     AS codgeraloper,
          SUBSTR(UPPER(o.desccfo),1,40)   AS descricao,
          SUBSTR(UPPER(o.desccfo),1,80)   AS aplicacao,
          a.codst                         AS nrotributacao,
          a.cfop                          AS cfopestado,
          a.cfopexterno                   AS cfopforaestado,
          a.uforigem                      AS uforigem,
          a.ufdestino                     AS ufdestino,
          'N'                             AS contribicms,
           0                              AS nroregtributacao,
          'S'                             AS ativo,
          a.dtalterc5                     AS dtalterc5,
          'N'                             AS calculaicmsst,
          'N'                             AS gerareducaobasest,
          'N'                             AS calculaipi,
          'N'                             AS tipocalculoipi,
          'N'                             AS calculafecp,
          'T'                             AS tipofaturamento,
          'N'                             AS consumidorfinal,
          'N'                             AS vendapresencial,
          'P'                             AS tipotributacao
    FROM  pcconsolidatributacao a,
          pccfo o
   WHERE  o.codfiscal = a.cfop)
   WHERE UFDESTINO IS NOT NULL
         AND UFORIGEM IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_LEITRANSP AS
(
SELECT
  CARGATRIB."CODNCMSH",
  CARGATRIB."EX",
  CARGATRIB."UFDESTINO",
  MAX(CARGATRIB."PERCTRIBUTOS") PERCTRIBUTOS,
  (CASE
    WHEN (MAX(CARGATRIB.PERCTRIBUTONACFEDERAL) = 0) AND
         (MAX(CARGATRIB.PERCTRIBUTOESTADUAL) = 0) AND
         (MAX(CARGATRIB.PERCTRIBUTOMUNICIPAL) = 0) 
    THEN
         MAX(CARGATRIB.PERCTRIBUTOS)
    ELSE MAX(CARGATRIB.PERCTRIBUTONACFEDERAL) 
  END) PERCTRIBUTONACFEDERAL,
  MAX(CARGATRIB."PERCTRIBUTOIMPORTADO") PERCTRIBUTOIMPORTADO,
  MAX(CARGATRIB."PERCTRIBUTOIMPFEDERAL") PERCTRIBUTOIMPFEDERAL,
  MAX(CARGATRIB."PERCTRIBUTOESTADUAL") PERCTRIBUTOESTADUAL,
  MAX(CARGATRIB."PERCTRIBUTOMUNICIPAL")PERCTRIBUTOMUNICIPAL ,
  MAX(CARGATRIB."ATIVO") ATIVO
FROM
  (SELECT DISTINCT
       NCMFILIAL.CODNCM codncmsh,
       NVL(NCMFILIAL.CODEX, 0) ex,
       NCMFILIAL.UF ufdestino,
       NVL(PRODTRIB.PERCTRIBUTOS, 0) PERCTRIBUTOS,
       NVL(TRIBNCMFILIAL.percentfisica, 0) perctributonacfederal,
       NVL(TRIBNCMFILIAL.percfisicaestimp, 0) perctributoimportado,
       NVL(TRIBNCMFILIAL.percentfisicaimportado, 0) perctributoimpfederal,
       NVL(TRIBNCMFILIAL.percfisicaestnac, 0) perctributoestadual,
       NVL(TRIBNCMFILIAL.percfisicamunicnac, 0) perctributomunicipal,

       (CASE
           WHEN NCMFILIAL.DTEXCLUSAO IS NULL THEN
                'S'
           ELSE
                'N'
       END) ativo
   FROM
     (SELECT DISTINCT
             PCNCM.CODNCM, /*CODNCM É CADASTRADO SEM O "." */
             PCNCM.CODNCMEX, /*CODNCM DA PCNCM É CADASTRADO COM "." E JÁ POSSUI A EXCEÇÃO CASO EXISTA*/
             PCNCM.CODEX,
             PCNCM.DTEXCLUSAO,
             PCREGIAO.UF,
             PCREGIAO.CODFILIAL
           FROM PCNCM,
                PCREGIAO/*,
                (select min(s.ultimaexecucao) ultimaexecucao
                 from pccontroleconsinco s
                 where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARGATRIBUTARIA')
                )DTPADRAO*/
           WHERE PCNCM.CODNCMEX IS NOT NULL
           AND   PCNCM.CODEX IS NULL
           AND   PCREGIAO.NUMREGIAO IN (SELECT DISTINCT(VALOR)
                                        FROM PCPARAMFILIAL
                                        WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                                        AND VALOR <> '99'
                                        AND VALOR IS NOT NULL)
           --AND   NVL(PCNCM.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
     )NCMFILIAL,

    (SELECT
       PCTRIBNCMFILIAL.CODNCM||PCTRIBNCMFILIAL.CODFILIAL ID,
       PCTRIBNCMFILIAL.percentfisica,
       PCTRIBNCMFILIAL.percfisicaestimp,
       PCTRIBNCMFILIAL.percentfisicaimportado,
       PCTRIBNCMFILIAL.percfisicaestnac,
       PCTRIBNCMFILIAL.percfisicamunicnac
     FROM PCTRIBNCMFILIAL, PCFILIAL/*,
          (select min(s.ultimaexecucao) ultimaexecucao
           from pccontroleconsinco s
           where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARGATRIBUTARIA')
           )DTPADRAO*/
     WHERE PCTRIBNCMFILIAL.CODFILIAL = PCFILIAL.CODIGO
     AND   PCTRIBNCMFILIAL.CODFILIAL <> '99'
     --AND   NVL(PCTRIBNCMFILIAL.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
     )TRIBNCMFILIAL,

     (SELECT DISTINCT
         P.codncmex,
         G.UF,
         MAX(T.PERCTRIBUTOS) PERCTRIBUTOS
      FROM PCTRIBUT T,
           PCTABPR R,
           PCNCM N,
           PCPRODUT P,
           PCREGIAO G/*,
          (select min(s.ultimaexecucao) ultimaexecucao
           from pccontroleconsinco s
           where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARGATRIBUTARIA')
          )DTPADRAO*/
      WHERE 
      R.CODST = T.CODST
      AND   P.CODPROD = R.CODPROD
      AND   G.NUMREGIAO = R.NUMREGIAO
      AND   G.NUMREGIAO IN (SELECT DISTINCT(VALOR)
                            FROM PCPARAMFILIAL
                            WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
                            AND VALOR <> '99'
                            AND VALOR IS NOT NULL)

      AND   N.CODNCMEX IS NOT NULL
      AND   P.CODNCMEX IS NOT NULL
      AND   N.CODEX IS NULL
      AND   T.CODST IS NOT NULL
      AND   P.codncmex = N.CODNCM||'.'||N.CODEX
      --AND   NVL(T.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
      GROUP BY P.codncmex, G.UF
     ) PRODTRIB

   WHERE NCMFILIAL.CODNCMEX||NCMFILIAL.CODFILIAL = TRIBNCMFILIAL.ID(+)
   AND   PRODTRIB.codncmex = NCMFILIAL.CODNCM||'.'||NCMFILIAL.CODEX
   AND   PRODTRIB.UF = NCMFILIAL.UF
  )CARGATRIB
GROUP BY CARGATRIB.CODNCMSH,
         CARGATRIB.EX,
         CARGATRIB.UFDESTINO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DEPARATRIBUTACAO AS (
  SELECT 
    DEPARA.SEQCENARIO,
    TRIBUTACAO.CODIGO_TRIBUTACAO,
    TRIBUTACAO.TIPO_IMPOSTO_EXIBIR AS TIPO_IMPOSTO,
    CASE 
      WHEN TRIBUTACAO.DTINATIVACAO IS NULL THEN 'S' 
      ELSE 'N' 
    END AS ATIVO
  FROM (
    SELECT 
      CODIGO_TRIBUTACAO,
      'CBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINICIO_VIGENCIA,
      DTFIM_VIGENCIA,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IBS' AS TIPO_IMPOSTO_EXIBIR,
      DTINICIO_VIGENCIA,
      DTFIM_VIGENCIA,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'CBSIBS'

    UNION ALL

    SELECT 
      CODIGO_TRIBUTACAO,
      'IS' AS TIPO_IMPOSTO_EXIBIR,
      DTINICIO_VIGENCIA,
      DTFIM_VIGENCIA,
      DTINATIVACAO
    FROM PCTRIBUTACAO
    WHERE TIPO_IMPOSTO = 'IS') TRIBUTACAO,
    PCDEPARATRIBUTACAOC5 DEPARA
  WHERE TRIBUTACAO.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO(+)
    AND TRIBUTACAO.TIPO_IMPOSTO_EXIBIR = DEPARA.TIPO_IMPOSTO(+)
    AND (TRIBUTACAO.DTINICIO_VIGENCIA IS NOT NULL AND TRIBUTACAO.DTFIM_VIGENCIA IS NOT NULL)
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTIMPOSTO AS
(
  SELECT 1 as SEQIMPOSTO, 'CBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQIMPOSTO, 'IBS' as DESCRICAO, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQIMPOSTO, 'IS'  as DESCRICAO, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIO AS (
    SELECT 
      DEPARA.SEQCENARIO,
      DEPARA.TIPO_IMPOSTO DESCRICAO,
      T.DESCRICAO_TRIBUTACAO ORIENTACAO,
      T.DTINICIO_VIGENCIA DTAINICIALVALIDADE,
      T.DTFIM_VIGENCIA DTAFINALVALIDADE,
      0 TOTALPONTOS,
      DEPARA.ATIVO,
      T.DTALTERC5,
      IMP.SEQIMPOSTO,
      DEPARA.CODIGO_TRIBUTACAO IDREF
    FROM PCDEPARATRIBUTACAOC5 DEPARA,
        VW_INT_C5_CCTIMPOSTO IMP,
        PCTRIBUTACAO T,
        (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
            FROM PCCONTROLECONSINCO S
          WHERE ATIVO = 'A'
            AND ((UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIO') 
              OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAO')
              OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIOCONDICAOITEM'))
          ) D
  WHERE T.CODIGO_TRIBUTACAO = DEPARA.CODIGO_TRIBUTACAO
    AND (SYSDATE >= T.DTINICIO_VIGENCIA AND SYSDATE <= T.DTFIM_VIGENCIA)
    AND NVL(T.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
    AND DEPARA.TIPO_IMPOSTO = IMP.DESCRICAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCONDICAO AS
(
  SELECT 1 as SEQCONDICAO, 'PRODUTO' as IDENTIFICADOR, 700 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 2 as SEQCONDICAO, 'FAMILIA' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 3 as SEQCONDICAO, 'NCM' as IDENTIFICADOR, 500 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 4 as SEQCONDICAO, 'CFOP' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 5 as SEQCONDICAO, 'CGO' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM
  UNION ALL
  SELECT 6 as SEQCONDICAO, 'ORIGEM' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 7 as SEQCONDICAO, 'DESTINO' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 8 as SEQCONDICAO, 'UFORIGEM' as IDENTIFICADOR, 101 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL
  SELECT 9 as SEQCONDICAO, 'UFDESTINO' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
  UNION ALL 
  SELECT 10 as SEQCONDICAO, 'NBS' as IDENTIFICADOR, 0 as PESOBUSCA, 'S' as ATIVO FROM PCCONSUM 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOCONDICAO AS
(
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
          FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
      WHERE SEQCENARIO = CEN.SEQCENARIO
      AND SEQCONDICAO = CN.SEQCONDICAO
      AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    CASE WHEN EXISTS (SELECT 1 FROM PCTRIBUTACAO_FILTRO_PRODUTO TP WHERE CEN.IDREF = TP.CODIGO_TRIBUTACAO AND TP.DTEXCLUSAO IS NULL)
    	THEN CN.PESOBUSCA 
    	ELSE 1
    END PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       VW_INT_C5_CCTCONDICAO CN,
       PCTRIBUTACAO T
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 1   
  
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 2
  
  UNION ALL
  
  SELECT
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    CASE WHEN EXISTS (SELECT 1 FROM PCTRIBUTACAO_FILTRO_NCM TP WHERE CEN.IDREF = TP.CODIGO_TRIBUTACAO AND TP.DTEXCLUSAO IS NULL)
    	THEN CN.PESOBUSCA 
    	ELSE 1
    END PONTOSBUSCA,   
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       VW_INT_C5_CCTCONDICAO CN,
       PCTRIBUTACAO T
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 3 

  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 4
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 5
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 6
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 7    
  
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    CASE 
      WHEN T.TIPO_LOCAL_CONSUMO = 'G' AND T.LOCAL_CONSUMO_GERAL = 'BR' THEN 100
      WHEN T.TIPO_LOCAL_CONSUMO = 'G' AND T.LOCAL_CONSUMO_GERAL <> 'BR' THEN CN.PESOBUSCA
      WHEN T.TIPO_LOCAL_CONSUMO = 'M' THEN 102
      ELSE 1
    END PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 8
    
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 9 
	
  UNION ALL
  
  SELECT 
    NVL((SELECT SEQCENARIOCONDICAO
        FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAO
        WHERE SEQCENARIO = CEN.SEQCENARIO
        AND SEQCONDICAO = CN.SEQCONDICAO
        AND ROWNUM = 1), 0) SEQCENARIOCONDICAO,
    CEN.SEQCENARIO,
    CN.SEQCONDICAO,
    1 PONTOSBUSCA,
    CEN.ATIVO
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
       PCTRIBUTACAO T,
       VW_INT_C5_CCTCONDICAO CN
  WHERE 1 = 1
    AND CEN.IDREF = T.CODIGO_TRIBUTACAO
    AND CN.SEQCONDICAO = 10   

)	

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENCONDITEM AS 
WITH BASE_DADOS AS (
    SELECT 
        CC.SEQCENARIOCONDICAO,
        CC.SEQCENARIO,
        CC.SEQCONDICAO,
        CC.ATIVO AS CC_ATIVO,
        DPTRIB.CODIGO_TRIBUTACAO AS IDREF,
        CASE CC.SEQCONDICAO
            WHEN 1 THEN TO_CHAR(DEPARA.SEQPRODUTO)
            WHEN 3 THEN TO_CHAR(NCM_F.NCM)
            WHEN 8 THEN 
                CASE WHEN T.TIPO_LOCAL_CONSUMO = 'G' 
                     THEN TO_CHAR(NVL(T.LOCAL_CONSUMO_GERAL, 'BR'))
                     ELSE TO_CHAR(T.LOCAL_CONSUMO_MUNICIPIO)
                END
            ELSE '0'
        END AS VALOR_ESPECIFICO,
        DECODE(CC.SEQCONDICAO, 1,'PRODUTO', 2,'FAMILIA', 3,'NCM', 4,'CFOP', 5,'CGO', 6,'ORIGEM', 7,'DESTINO', 8,'UFORIGEM', 9,'UFDESTINO', 10,'NBS') AS IDENTIFICADOR,
        CASE 
            WHEN CC.SEQCONDICAO = 1 THEN CASE WHEN CC.ATIVO = 'S' AND DEPARA.ATIVO = 'S' AND P_FILTRO.DTEXCLUSAO IS NULL THEN 'S' ELSE 'N' END
            WHEN CC.SEQCONDICAO = 3 THEN CASE WHEN CC.ATIVO = 'S' AND NCM_F.DTEXCLUSAO IS NULL THEN 'S' ELSE 'N' END
            
            ELSE CC.ATIVO
        END AS ATIVO_ESPECIFICO
    FROM VW_INT_C5_CCTCENARIOCONDICAO CC
    JOIN PCDEPARATRIBUTACAOC5 DPTRIB ON DPTRIB.SEQCENARIO = CC.SEQCENARIO
    JOIN PCTRIBUTACAO T ON DPTRIB.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
    LEFT JOIN PCTRIBUTACAO_FILTRO_PRODUTO P_FILTRO ON P_FILTRO.CODIGO_TRIBUTACAO = DPTRIB.CODIGO_TRIBUTACAO AND CC.SEQCONDICAO = 1
    LEFT JOIN PCDEPARAPRODC5 DEPARA ON DEPARA.CODPROD = P_FILTRO.CODPROD AND CC.SEQCONDICAO = 1
    LEFT JOIN PCTRIBUTACAO_FILTRO_NCM NCM_F ON NCM_F.CODIGO_TRIBUTACAO = DPTRIB.CODIGO_TRIBUTACAO AND CC.SEQCONDICAO = 3
    WHERE CC.SEQCONDICAO BETWEEN 1 AND 10
),
UNIFICACAO_LINHAS AS (
    SELECT SEQCENARIOCONDICAO, SEQCENARIO, SEQCONDICAO, IDREF, VALOR_ESPECIFICO AS VALOR, IDENTIFICADOR, ATIVO_ESPECIFICO AS ATIVO
    FROM BASE_DADOS
    WHERE VALOR_ESPECIFICO IS NOT NULL 

    UNION ALL

    SELECT DISTINCT 
        SEQCENARIOCONDICAO, SEQCENARIO, SEQCONDICAO, IDREF, '0' AS VALOR, IDENTIFICADOR,
        CASE 
            WHEN MAX(ATIVO_ESPECIFICO) OVER (PARTITION BY SEQCENARIOCONDICAO, IDENTIFICADOR) = 'S' THEN 'N'
            ELSE 'S' 
        END AS ATIVO
    FROM BASE_DADOS
    WHERE SEQCONDICAO IN (1, 3) 
      AND VALOR_ESPECIFICO <> '0'  
)
SELECT 
    NVL((SELECT MIN(I.SEQCENARIOCONDICAOITEM)
         FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM I
         WHERE I.SEQCENARIOCONDICAO = U.SEQCENARIOCONDICAO
           AND I.VALOR = U.VALOR
           AND I.IDENTIFICADOR = U.IDENTIFICADOR
           AND ROWNUM = 1
        ), 0) AS SEQCENARIOCONDICAOITEM,
    U.SEQCENARIOCONDICAO,
    U.VALOR,
    'N' AS INDTIPOIDENTIDADE,
    U.IDENTIFICADOR,
    U.SEQCENARIO,
    U.ATIVO,
    U.IDREF
FROM UNIFICACAO_LINHAS U
ORDER BY U.SEQCENARIO, U.SEQCENARIOCONDICAO

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTFORMULA AS
(
  SELECT 1 as SEQFORMULA, 'PADRAO' as DESCRICAO, '(PRECOPRODUTO + ACRESCIMO + MULTASJUROS + DESCCONDICIONAL + SEGUROTAXA + FRETE)' as BASE, '* (ALIQUOTA - (ALIQUOTA * REDUCAO))' as ALIQUOTA, 'F' as INDTIPOFORMULA, 'S' as ATIVO FROM PCCONSUM
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCODIGOTRIBUTARIO AS 
WITH CTEPCTRIBUTACAO AS (
    SELECT 
        T.CST,
        T.CCLASSTRIB,
        T.PERC_RED_CBS,
        T.TIPO_LOCAL_CONSUMO,
        T.PERC_RED_IBS_UF,
        T.PERC_RED_IBS_MUN,
        CEN.DTAINICIALVALIDADE,
        CEN.DTAFINALVALIDADE,
        CEN.ATIVO,
        CEN.IDREF,
        (SELECT DECODE(MAX(PC.TRIBUTACAOGIBSCBS), 'Sim', 'N', 'Não', 'S') 
          FROM PCCSTTRIBUTACAOIBSCBS PC 
          WHERE PC.CODSITUACAOTRIBUTARIA = T.CST) AS INDISENTO
    FROM PCTRIBUTACAO T
    INNER JOIN MONITORPDVMIDDLE.TB_CCTCENARIO CEN ON (CEN.IDREF = T.CODIGO_TRIBUTACAO)
    WHERE SYSDATE BETWEEN CEN.DTAINICIALVALIDADE AND CEN.DTAFINALVALIDADE
),
CTECSTCCLASSTRIB AS (
    SELECT 
        CST AS CODIGO, 'CST ' || CST AS DESCRICAO, 1 AS INDTIPOCODIGO, 
        CCLASSTRIB AS CODIGOPAI, INDISENTO, DTAINICIALVALIDADE, DTAFINALVALIDADE,
        PERC_RED_CBS, TIPO_LOCAL_CONSUMO, PERC_RED_IBS_UF, PERC_RED_IBS_MUN, ATIVO, IDREF
    FROM CTEPCTRIBUTACAO
    UNION ALL
    SELECT 
        CCLASSTRIB AS CODIGO, 'CCLASSTRIB ' || CCLASSTRIB AS DESCRICAO, 2 AS INDTIPOCODIGO, 
        CCLASSTRIB AS CODIGOPAI, INDISENTO, DTAINICIALVALIDADE, DTAFINALVALIDADE,
        PERC_RED_CBS, TIPO_LOCAL_CONSUMO, PERC_RED_IBS_UF, PERC_RED_IBS_MUN, ATIVO, IDREF
    FROM CTEPCTRIBUTACAO
),
CTEROWNUMBER AS (
    SELECT
        MIN(NVL((SELECT SEQCODIGOTRIBUTARIO 
                  FROM MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO 
                  WHERE CODIGO = U.CODIGO AND ROWNUM = 1), 0)) AS SEQCODIGOTRIBUTARIO,
        U.CODIGO,
        U.DESCRICAO,
        U.CODIGOPAI,
        U.INDTIPOCODIGO,
        U.INDISENTO,
        U.DTAINICIALVALIDADE,
        U.DTAFINALVALIDADE,
        NVL(U.PERC_RED_CBS, 0) AS PERALIQREDCBS,
        CASE
            WHEN U.TIPO_LOCAL_CONSUMO = 'G' THEN NVL(U.PERC_RED_IBS_UF, 0)
            WHEN U.TIPO_LOCAL_CONSUMO = 'M' THEN NVL(U.PERC_RED_IBS_MUN, 0)
            ELSE 0
        END AS PERALIQREDIBS,
        U.ATIVO,
        U.IDREF,
        ROW_NUMBER() OVER (PARTITION BY U.CODIGO ORDER BY U.DTAFINALVALIDADE ASC) AS RN
    FROM CTECSTCCLASSTRIB U
    GROUP BY 
        U.CODIGO, U.DESCRICAO, U.CODIGOPAI, U.INDTIPOCODIGO, U.INDISENTO,
        U.DTAINICIALVALIDADE, U.DTAFINALVALIDADE, U.PERC_RED_CBS, 
        U.TIPO_LOCAL_CONSUMO, U.PERC_RED_IBS_UF, U.PERC_RED_IBS_MUN, U.ATIVO, U.IDREF
)
SELECT * FROM CTEROWNUMBER 
WHERE RN = 1

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOIMPOSTO AS 
WITH BASECALCULO AS (
  SELECT
    CEN.SEQCENARIO,
    CEN.SEQIMPOSTO,
    CEN.DESCRICAO AS TIPO_IMPOSTO,
    CEN.ATIVO,
    CEN.IDREF,
    T.CST,
    T.CCLASSTRIB,
    CASE 
      WHEN CEN.DESCRICAO = 'IS'  THEN NVL(T.PERC_IS, 0)
      WHEN CEN.DESCRICAO = 'CBS' THEN NVL(T.PERC_CBS, 0)
      WHEN CEN.DESCRICAO = 'IBS' THEN 
          CASE T.TIPO_LOCAL_CONSUMO 
            WHEN 'G' THEN NVL(T.PERC_IBS_UF, 0)
            WHEN 'M' THEN NVL(T.PERC_IBS_MUN, 0)
            ELSE 0 
          END
      ELSE 0 
    END AS VALOR_PERALIQ,
    CASE 
      WHEN CEN.DESCRICAO = 'IS'  THEN NVL(T.PERC_IS, 0)
      WHEN CEN.DESCRICAO = 'CBS' THEN NVL(T.PERC_CBS, 0)
      WHEN CEN.DESCRICAO = 'IBS' THEN 
        CASE T.TIPO_LOCAL_CONSUMO 
          WHEN 'G' THEN NVL(T.PERC_IBS_UF, 0)
          WHEN 'M' THEN NVL(T.PERC_IBS_MUN, 0)
          WHEN 'M' THEN NVL(T.PERC_RED_IBS_MUN, 0)
          ELSE 0 
        END
      ELSE 0 
    END AS VALOR_PERALIQRED,
    CASE 
        WHEN CEN.DESCRICAO = 'IBS' AND T.TIPO_LOCAL_CONSUMO = 'M' THEN NVL(T.PERC_IBS_MUN, 0)
        ELSE 0 
    END AS VALOR_PERALIQMUN
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN
  JOIN PCTRIBUTACAO T ON CEN.IDREF = T.CODIGO_TRIBUTACAO
)
SELECT
  NVL(CI.SEQCENARIOIMPOSTO, 0) AS SEQCENARIOIMPOSTO,
  BASE.SEQCENARIO,
  BASE.SEQIMPOSTO,
  CCTC_CST.SEQCODIGOTRIBUTARIO AS SEQCODTRIBCST,
  CCTC_CC.SEQCODIGOTRIBUTARIO AS SEQCODTRIBCCLASTRIB,
  BASE.VALOR_PERALIQ AS PERALIQ,
  BASE.VALOR_PERALIQRED AS PERALIQRED,
  BASE.VALOR_PERALIQMUN AS PERALIQMUN,
  1 AS SEQFORMULA,
  BASE.ATIVO,
  BASE.IDREF || '-' || BASE.TIPO_IMPOSTO AS IDREF,
  CCTC_CST.CODIGO AS CODIGOCST,
  CCTC_CC.CODIGO AS CODIGOCCLASSTRIB,
  CCTC_CST.INDISENTO AS INDISENTO
FROM BASECALCULO BASE
LEFT JOIN MONITORPDVMIDDLE.TB_CCTCENARIOIMPOSTO CI 
       ON (CI.SEQIMPOSTO = BASE.SEQIMPOSTO AND CI.SEQCENARIO = BASE.SEQCENARIO)
LEFT JOIN MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO CCTC_CST 
       ON (CCTC_CST.INDTIPOCODIGO = 1 AND CCTC_CST.CODIGO = BASE.CST)
LEFT JOIN MONITORPDVMIDDLE.TB_CCTCODIGOTRIBUTARIO CCTC_CC 
       ON (CCTC_CC.INDTIPOCODIGO = 2 AND CCTC_CC.CODIGO = BASE.CCLASSTRIB)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCONFIGURACAO AS
(
  SELECT 
    1 AS SEQCONFIGURACAO, 
    NVL((SELECT 
            CASE 
              WHEN VALOR = 'S' THEN 'P'
              ELSE 'H'
            END
         FROM PCPARAMFILIAL WHERE NOME = 'USAREFORMAPDVSUPERMERCADO'), 'H') AS INDTIPOAMBIENTE, 
    'S' AS ATIVO 
  FROM PCCONSUM
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTALIQUOTA AS 
(
  SELECT 
    (SELECT IMP.SEQIMPOSTO FROM MONITORPDVMIDDLE.TB_CCTIMPOSTO IMP WHERE IMP.DESCRICAO = CEN.DESCRICAO) AS SEQIMPOSTO,
    TRIB.DTINICIO_VIGENCIA AS DTAINICIALVALIDADE,
    TRIB.DTFIM_VIGENCIA AS DTAFINALVALIDADE,
    NVL(CASE
      WHEN CEN.DESCRICAO = 'CBS' THEN TRIB.PERC_CBS
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'M' THEN TRIB.PERC_IBS_MUN
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'G' THEN TRIB.PERC_IBS_UF
      WHEN CEN.DESCRICAO = 'IS' THEN TRIB.PERC_IS
      ELSE 0
    END, 0) AS PERALIQ,
    CASE
      WHEN CEN.DESCRICAO IN ('CBS', 'IS') THEN ''
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'M' THEN (SELECT C.UF FROM PCCIDADE C WHERE C.CODIBGE = TRIB.LOCAL_CONSUMO_MUNICIPIO) 
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'G' THEN TRIB.LOCAL_CONSUMO_GERAL
      ELSE NULL
    END AS UF,
    CASE
      WHEN CEN.DESCRICAO = 'IBS' AND TRIB.TIPO_LOCAL_CONSUMO = 'M' THEN TRIB.LOCAL_CONSUMO_MUNICIPIO 
      ELSE NULL
    END AS CODIBGE,
    CEN.ATIVO,
    CEN.IDREF AS IDREF
  FROM MONITORPDVMIDDLE.TB_CCTCENARIO CEN,
      PCTRIBUTACAO TRIB,
      (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
        WHERE ATIVO = 'A'
          AND (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTALIQUOTA')
      ) D
  WHERE CEN.IDREF = TRIB.CODIGO_TRIBUTACAO
    AND (SYSDATE >= TRIB.DTINICIO_VIGENCIA AND SYSDATE <= TRIB.DTFIM_VIGENCIA)
    AND NVL(TRIB.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIOITEM AS 
WITH BASE_DADOS AS (
    SELECT 
        SEQCENARIO,
        IDENTIFICADOR,
        VALOR,
        ATIVO,
        INDTIPOENTIDADE,
        MAX(CASE WHEN IDENTIFICADOR = 'FAMILIA' THEN VALOR END) OVER (PARTITION BY SEQCENARIO) AS FAMILIA,
        MAX(CASE WHEN IDENTIFICADOR = 'CGO'     THEN VALOR END) OVER (PARTITION BY SEQCENARIO) AS CGO,
        MAX(CASE WHEN IDENTIFICADOR = 'ORIGEM'  THEN VALOR END) OVER (PARTITION BY SEQCENARIO) AS ORIGEM,
        MAX(CASE WHEN IDENTIFICADOR = 'DESTINO' THEN VALOR END) OVER (PARTITION BY SEQCENARIO) AS DESTINO,
        MAX(CASE WHEN IDENTIFICADOR = 'NBS'     THEN VALOR END) OVER (PARTITION BY SEQCENARIO) AS NBS,
        MAX(CASE 
                WHEN IDENTIFICADOR IN ('PRODUTO', 'NCM') 
                AND VALOR != '0' 
                AND ATIVO = 'S' THEN 1 
                ELSE 0 
            END) OVER (PARTITION BY SEQCENARIO) AS TEM_ATIVO_NUM
    FROM MONITORPDVMIDDLE.TB_CCTCENARIOCONDICAOITEM
),
NORMALIZACAO_DADOS AS (
    SELECT 
        SEQCENARIO,
        CASE WHEN IDENTIFICADOR = 'PRODUTO' THEN VALOR ELSE '0' END AS PRODUTO,
        CASE WHEN IDENTIFICADOR = 'NCM'     THEN VALOR ELSE '0' END AS NCM,
        FAMILIA, CGO, ORIGEM, DESTINO, NBS, INDTIPOENTIDADE, ATIVO, TEM_ATIVO_NUM
    FROM BASE_DADOS
    WHERE IDENTIFICADOR IN ('PRODUTO', 'NCM')
)
SELECT 
    SEQCENARIO,
    PRODUTO,
    NCM,
    FAMILIA,
    CGO,
    ORIGEM,
    DESTINO,
    MIN(INDTIPOENTIDADE) AS INDTIPOENTIDADEORIGEM,
    MIN(INDTIPOENTIDADE) AS INDTIPOENTIDADEDESTINO,
    CASE 
        WHEN PRODUTO = '0' AND NCM = '0' THEN 
            CASE WHEN MAX(TEM_ATIVO_NUM) = 1 THEN 'N' ELSE 'S' END
        ELSE MIN(ATIVO) 
    END AS ATIVO,
    NBS
FROM NORMALIZACAO_DADOS
GROUP BY 
    SEQCENARIO, PRODUTO, NCM, FAMILIA, CGO, ORIGEM, DESTINO, NBS
ORDER BY 
    SEQCENARIO, PRODUTO DESC, NCM DESC