CREATE OR REPLACE PROCEDURE P_CTBINTEGRACAOCONTABIL(PCODFILIAL        IN VARCHAR2,
                                                    PCODREGRA         IN NUMERIC,
                                                    PDTINICIO         IN DATE,
                                                    PDTFINAL          IN DATE,
                                                    PCODPLANOCONTA    IN NUMERIC,
                                                    PCODFATOGERADOR   IN NUMERIC,
                                                    PEXCLUIREGISTROS  IN VARCHAR2,
                                                    PCONSOLIDAR       IN VARCHAR2,
                                                    PNUMTRANSOPERACAO IN NUMBER DEFAULT 0,
                                                    RESULTADO         OUT VARCHAR2) IS

  TYPE CURSOR_TYPE IS REF CURSOR;

  CURSOR_DADOS CURSOR_TYPE;



  TYPE TIPO_PAGAMENTO IS RECORD(
   CONSIDERARPROVISAO VARCHAR2(1)
  );

  TYPE TIPO_ESTOQUE IS RECORD(
   CODFILIAL PCFILIAL.CODIGO%TYPE,
   TIPOCUSTO_MOVESTOQUE NUMBER(2),
   CONDVENDA14_MOVESTOQUE VARCHAR2(1),
   USAPRC_CONTROLEPRODUCAO VARCHAR2(1),
   VALOR_DEST_NF VARCHAR2(1),   
   CONSIDERARCUSTOBONIF VARCHAR2(1),
   DESCONS_CUSTO_DEVCLI VARCHAR2(1),
   CONS_ENT_SAIDA_CANC VARCHAR2(1),
   EXCLUI_OPER_ER VARCHAR2(1),
   DESC_CUSTO_NF_ENT VARCHAR2(1),
   DESC_TIPOMERC_BD VARCHAR2(1),
   DESC_DEP_ATI_IMO VARCHAR2(1),
   DESC_DEP_MAT_CON VARCHAR2(1),
   DESC_NF_DENEGADA VARCHAR2(1)
  );

  PAGAMENTO TIPO_PAGAMENTO;

  ESTOQUE TIPO_ESTOQUE;

  CURSOR_PAGAMENTO SYS_REFCURSOR;
  CURSOR_ESTOQUE   SYS_REFCURSOR;


  V_SQLFATOGERADOR     CLOB;
  V_RETORNO            VARCHAR2(8096);

  VCODFILIAL VARCHAR2(4000);
  
  V_DATAINIAUX DATE;
  V_DATAFIMAUX DATE;
  V_BUSCARDATA VARCHAR2(10);
  
  V_UTILIZACENTRODERECEITA VARCHAR2(2);
BEGIN
  IF INSTR(PCODFILIAL,'''') <= 0 AND PCONSOLIDAR = 'N' THEN
    VCODFILIAL := '''' || PCODFILIAL || '''';
  ELSE
    VCODFILIAL := PCODFILIAL;
  END IF;
  
  SELECT NVL(F.VALOR, 'N') 
    INTO V_UTILIZACENTRODERECEITA
  FROM PCPARAMFILIAL F 
 WHERE F.NOME = 'UTILIZACENTRODERECEITA';

  IF PEXCLUIREGISTROS = 'S' THEN
     PKG_INTEGRACAOCONTABIL.P_EXCLUI_LANCINTERMEDIARIA_GER(PCODREGRA, VCODFILIAL, PDTINICIO, PDTFINAL,PCONSOLIDAR);
  END IF;

  V_SQLFATOGERADOR := PKG_INTEGRACAOCONTABIL.F_PREPARA_SQL_FATO_GERADOR(PCODREGRA,
                                                                        PNUMTRANSOPERACAO,
                                                                        VCODFILIAL);

  --1 - ENTRADAS
  IF PCODFATOGERADOR = 1 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 1 - ENTRADA ';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
     USING PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCODPLANOCONTA, PCODREGRA, PCONSOLIDAR, PDTFINAL,
           PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL;
    PKG_INTEGRACAOCONTABIL.P_DADOS_ENTRADAS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --2 - SAÍDAS
  IF PCODFATOGERADOR = 2 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 2 - SAÍDAS';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODREGRA, PCONSOLIDAR, PDTFINAL,
            PCODPLANOCONTA, PCODPLANOCONTA,
             PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA,
			PDTINICIO, PDTFINAL;
    PKG_INTEGRACAOCONTABIL.P_DADOS_SAIDAS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --3 - PAGAMENTOS
  IF PCODFATOGERADOR = 3 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 3 - PAGAMENTOS';
     ---------------------------------------------------------------------------------
    OPEN CURSOR_PAGAMENTO FOR 'SELECT DISTINCT NVL(RC.CONSIDERARPROVISAO, ''N'') CONSIDERARPROVISAO
                            FROM PCCONFFILIAL F1,
                                 PCREGRAFILIAL R1,
                                 PCREGRACONTABIL RC
                            WHERE R1.CODFILIAL = F1.CODFILIAL
                            AND   R1.CODREGRA = RC.CODREGRA
                            AND   R1.CODREGRA = :PCODREGRA
                            AND   DECODE(:PCONSOLIDAR, ''S'', TO_CHAR(F1.CODGRUPOFILIAL), F1.CODFILIAL) IN ( ' || VCODFILIAL || ')
                            AND   F1.ANO = EXTRACT(YEAR FROM TO_DATE(:PDTFINAL)) '
    USING PCODREGRA, PCONSOLIDAR, PDTFINAL;
    LOOP
     FETCH CURSOR_PAGAMENTO INTO PAGAMENTO;
      EXIT WHEN CURSOR_PAGAMENTO%NOTFOUND;

              OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
                 USING PCODREGRA, PCONSOLIDAR, PDTFINAL,
				       PAGAMENTO.CONSIDERARPROVISAO, PAGAMENTO.CONSIDERARPROVISAO, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA,
					   PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, 
                       PCONSOLIDAR, 
					   PCODPLANOCONTA, 
					   PDTINICIO, PDTFINAL,
					   PCODPLANOCONTA, PCODPLANOCONTA,
					   PDTINICIO, PDTFINAL;
              PKG_INTEGRACAOCONTABIL.P_DADOS_PAGAMENTOS(CURSOR_DADOS,
                                                        PCODREGRA,
                                                        PCODPLANOCONTA,
                                                        V_RETORNO);
    END LOOP;
     CLOSE CURSOR_PAGAMENTO;
  END IF;

  --4 - RECEBIMENTOS
  IF PCODFATOGERADOR = 4 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 4 - RECEBIMENTOS';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      --USING PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL, PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCODREGRA;
        using pcodregra,pconsolidar,pdtfinal,pcodplanoconta,pcodplanoconta,pcodregra, pcodplanoconta, pdtinicio,pdtfinal,PCONSOLIDAR, pdtinicio,pdtfinal,pcodregra,pconsolidar,pdtfinal,pdtinicio,pdtfinal,pcodplanoconta;
    PKG_INTEGRACAOCONTABIL.P_DADOS_RECEBIMENTOS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --5 - DEVOLUÇÃO PARA FORNECEDOR
  IF PCODFATOGERADOR = 5 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 5 - DEVOLUÇÃO PARA FORNECEDOR';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PCODPLANOCONTA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA;
    PKG_INTEGRACAOCONTABIL.P_DADOS_DEVFORNECEDORES(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --6 - DEVOLUÇÃO DE CLIENTES
  IF PCODFATOGERADOR = 6 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 6 - DEVOLUÇÃO DE CLIENTES';
    ---------------------------------------------------------------------------------
	IF V_UTILIZACENTRODERECEITA = 'S' THEN
	    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
		  USING
			PCODREGRA, PCONSOLIDAR, PDTFINAL,
			PCODPLANOCONTA,
			PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, 	
			PDTINICIO, PDTFINAL, PDTINICIO, PDTFINAL;
		PKG_INTEGRACAOCONTABIL.P_DADOS_DEVCLIENTES(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
	ELSE
		OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
		  USING
			PCODREGRA, PCONSOLIDAR, PDTFINAL,
			PCODPLANOCONTA,
			PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, 	
			PDTINICIO, PDTFINAL;
		PKG_INTEGRACAOCONTABIL.P_DADOS_DEVCLIENTES(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
	END IF;
  END IF;

  --7 - TRANSFERÊNCIA DE NUMERÁRIOS
  IF PCODFATOGERADOR = 7 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 7 - TRANSFERÊNCIA DE NUMERÁRIOS';
    ---------------------------------------------------------------------------------
    
    SELECT R.BUSCARDADOSPELADATA
    INTO V_BUSCARDATA
    FROM PCREGRACONTABIL R
    WHERE R.CODREGRA = PCODREGRA;
    
    IF V_BUSCARDATA = 'C' THEN
    
    BEGIN  
      SELECT MIN(M.DATA), MAX(M.DATA)
       INTO V_DATAINIAUX, V_DATAFIMAUX
      FROM PCMOVCR M
      WHERE EXISTS(SELECT 1 FROM PCMOVCR A
      WHERE A.NUMTRANS = M.NUMTRANS
       AND A.DATA = M.DATA
       AND A.DTCOMPENSACAO BETWEEN PDTINICIO AND PDTFINAL);
       
       IF V_DATAINIAUX IS NULL THEN 
           V_DATAINIAUX := PDTINICIO;
       END IF;
	   
	   IF V_DATAFIMAUX IS NULL THEN 
           V_DATAFIMAUX := PDTFINAL;
       END IF;
       
    EXCEPTION 
      WHEN OTHERS THEN
          V_DATAINIAUX := PDTINICIO;
		  V_DATAFIMAUX := PDTFINAL;
    END;   
    
      
      OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
        USING PCODREGRA, PCONSOLIDAR, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA,
              PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, V_DATAINIAUX, V_DATAFIMAUX, PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL;--
      PKG_INTEGRACAOCONTABIL.P_DADOS_TRANSFNUMERARIOS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
    ELSE
      OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
        USING PCODREGRA, PCONSOLIDAR, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA,
              PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL;--
      PKG_INTEGRACAOCONTABIL.P_DADOS_TRANSFNUMERARIOS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);   
    END IF;
    
  END IF;

  --8 - MOVIMENTAÇÃO DE ESTOQUE
  IF PCODFATOGERADOR = 8 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 8 - MOVIMENTAÇÃO DE ESTOQUE';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_ESTOQUE FOR 'SELECT DISTINCT F1.CODFILIAL,
                                               NVL(RC.TIPOCUSTO_MOVESTOQUE, 0) TIPOCUSTO_MOVESTOQUE,
                                               NVL(RC.CONDVENDA14_MOVESTOQUE, ''N'') CONDVENDA14_MOVESTOQUE,
                                               NVL(RC.USAPRC_CONTROLEPRODUCAO,''N'') USAPRC_CONTROLEPRODUCAO,
                                               NVL(RC.VALOR_DEST_NF , ''N'') VALOR_DEST_NF ,                                             
                                               NVL(RC.CONSIDERARCUSTOBONIF,''N'') CONSIDERARCUSTOBONIF,
                                               NVL(RC.DESCONS_CUSTO_DEVCLI,''N'') DESCONS_CUSTO_DEVCLI,
											   NVL(RC.CONS_ENT_SAIDA_CANC,''N'') CONS_ENT_SAIDA_CANC,
											   NVL(RC.EXCLUI_OPER_ER,''N'') EXCLUI_OPER_ER,
                                               NVL(RC.DESC_CUSTO_NF_ENT,''N'') DESC_CUSTO_NF_ENT,
                                               NVL(RC.DESC_TIPOMERC_BD,''N'')  DESC_TIPOMERC_BD,
                                               NVL(RC.DESC_DEP_ATI_IMO,''N'')  DESC_DEP_ATI_IMO,
											   NVL(RC.DESC_DEP_MAT_CON,''N'')  DESC_DEP_MAT_CON,
											   NVL(RC.DESC_NF_DENEGADA,''N'')  DESC_NF_DENEGADA 
                                        FROM PCCONFFILIAL F1,
                                             PCREGRAFILIAL R1,
                                             PCREGRACONTABIL RC
                                        WHERE R1.CODFILIAL = F1.CODFILIAL
                                        AND   R1.CODREGRA = RC.CODREGRA
                                        AND   R1.CODREGRA = :PCODREGRA
                                        AND   DECODE(:PCONSOLIDAR, ''S'', TO_CHAR(F1.CODGRUPOFILIAL), F1.CODFILIAL) IN (' || VCODFILIAL || ')
                                        AND   F1.ANO = EXTRACT(YEAR FROM TO_DATE(:PDTFINAL)) '
    USING PCODREGRA, PCONSOLIDAR, PDTFINAL;
    LOOP
     FETCH CURSOR_ESTOQUE INTO ESTOQUE;
      EXIT WHEN CURSOR_ESTOQUE%NOTFOUND;
      OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
        USING PCODREGRA, PCONSOLIDAR, PDTFINAL,
		      ESTOQUE.TIPOCUSTO_MOVESTOQUE, ESTOQUE.TIPOCUSTO_MOVESTOQUE,
			  PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, 	
              ESTOQUE.CODFILIAL,
              PDTINICIO,
              PDTFINAL,
              ESTOQUE.TIPOCUSTO_MOVESTOQUE,
              ESTOQUE.VALOR_DEST_NF,
			  ESTOQUE.DESC_DEP_MAT_CON,
              ESTOQUE.DESC_DEP_ATI_IMO,			   			  
			  ESTOQUE.CONS_ENT_SAIDA_CANC,
              ESTOQUE.CONDVENDA14_MOVESTOQUE,
              ESTOQUE.USAPRC_CONTROLEPRODUCAO, 
			  ESTOQUE.DESC_NF_DENEGADA,		  
              ESTOQUE.CONSIDERARCUSTOBONIF,
              ESTOQUE.DESCONS_CUSTO_DEVCLI,
			  ESTOQUE.EXCLUI_OPER_ER,
			  ESTOQUE.DESC_CUSTO_NF_ENT,
			  ESTOQUE.DESC_TIPOMERC_BD;
      PKG_INTEGRACAOCONTABIL.P_DADOS_MOVESTOQUES(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
    END LOOP;
    CLOSE CURSOR_ESTOQUE;
  END IF;

  --9 - LANÇAMENTO DE PROVISÕES
  IF PCODFATOGERADOR = 9 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 9 - LANÇAMENTO DE PROVISÕES';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL,
            --PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCODPLANOCONTA;
			PCODPLANOCONTA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO , PDTFINAL , PCODPLANOCONTA , 
			PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA;
    PKG_INTEGRACAOCONTABIL.P_DADOS_LANCPROVISOES(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --10 - ACERTO DE CARGAS
  IF PCODFATOGERADOR = 10 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 10 - ACERTO DE CARGAS';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODREGRA, PCODPLANOCONTA, PCONSOLIDAR, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA, PCODREGRA, PCODPLANOCONTA, PDTINICIO, PDTFINAL,
            PCODPLANOCONTA, PCONSOLIDAR, PDTINICIO, PDTFINAL, PDTINICIO, PDTFINAL;
    PKG_INTEGRACAOCONTABIL.P_DADOS_ACERTOCARGAS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --11 - CUPONS FISCAIS
  IF PCODFATOGERADOR = 11 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 11 - CUPONS FISCAIS';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PCODPLANOCONTA,  PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL,
            PCODREGRA, PDTINICIO, PDTFINAL;
    PKG_INTEGRACAOCONTABIL.P_DADOS_CUPONS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

    --12 - NOTAS FISCAIS DE SERVICO
  IF PCODFATOGERADOR = 12 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 12 - NOTAS FISCAIS SERVICO';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCODREGRA,PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL;
    PKG_INTEGRACAOCONTABIL.P_DADOS_NFSERVICO(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --13 - PAGAMENTOS COM ADIANTAMENTO DE FORNECEDOR
  IF PCODFATOGERADOR = 13 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 13 - PAGAMENTOS COM ADIANTAMENTO DE FORNECEDOR';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL;
    PKG_INTEGRACAOCONTABIL.P_DADOS_ADIANTAMENTOFORNECEDOR(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --14 - INCLUSÃO MANUAL RECEBER
  IF PCODFATOGERADOR = 14 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 14 - INCLUSÃO MANUAL RECEBER';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL,  PCODPLANOCONTA,
      PCODPLANOCONTA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PCODPLANOCONTA, PDTINICIO, PDTFINAL,
      PDTINICIO, PDTFINAL, PCODREGRA, PCODPLANOCONTA;

    PKG_INTEGRACAOCONTABIL.P_DADOS_INCLUSAOMANUALRECEBER(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --15 -BAIXA DE ATIVO IMOBILIZADO
  IF PCODFATOGERADOR = 15 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 15 - BAIXA DE ATIVO IMOBILIZADO';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PDTINICIO, PDTFINAL, PCODREGRA, PCODREGRA, PCONSOLIDAR, PDTFINAL, PDTINICIO, PDTFINAL,
      PCODPLANOCONTA;

    PKG_INTEGRACAOCONTABIL.P_DADOS_BAIXAATIVOIMOBILIZADO(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

  --16 -BAIXA TÍTULOS COM CRÉDITO DE CLIENTE
  IF PCODFATOGERADOR = 16 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 16 - BAIXA TÍTULOS COM CRÉDITO DE CLIENTE';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODREGRA,
            PCONSOLIDAR,
            PDTFINAL,
            PDTINICIO,
            PDTFINAL,
            PCODPLANOCONTA,
            PDTINICIO,
            PDTFINAL,
            PCODREGRA,
            PCODPLANOCONTA,
            PDTINICIO,
            PDTFINAL,
            PCODPLANOCONTA,
            PDTINICIO,
            PDTFINAL,
            PCODREGRA,
            PCODPLANOCONTA;

    PKG_INTEGRACAOCONTABIL.P_DADOS_BAIXAATITULOSCRED(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;

    --17 -BAIXA TÍTULOS COM CRÉDITO DE CLIENTE
  IF PCODFATOGERADOR = 17 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 17 - INCLUSÃO CRÉDITO DE CLIENTE';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL,
            PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL,
            PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCONSOLIDAR,
            PDTFINAL, PDTINICIO, PDTFINAL, PCODREGRA;

    PKG_INTEGRACAOCONTABIL.P_DADOS_INCLUSAOCREDITOCLIENTE(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;
  
  --18 -CONTRATOS FINIMP E FINAME
  IF PCODFATOGERADOR = 18 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 18 - CONTRATOS FINIMP E FINAME';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
	  -- os parâmetros abaixo correspondem aos parâmetros (na mesma ordem) utilizados no SQL "criador do fato gerador" na Rotina 2100)
      USING PCODREGRA, PCONSOLIDAR, PDTFINAL,
	        PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, 	
	        PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PCODPLANOCONTA;

    PKG_INTEGRACAOCONTABIL.P_DADOS_CONTRATOSFINIMPFINAME(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;  

   --19 - PIS/COFINS SERVIÇOS TOMADOS
  IF PCODFATOGERADOR = 19 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 19 - PIS/COFINS SERVIÇOS TOMADOS';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODREGRA, PCONSOLIDAR, PDTFINAL, PCODPLANOCONTA, PCODPLANOCONTA, PDTINICIO, PDTFINAL, PCODREGRA, PCODPLANOCONTA, 
	        PCODPLANOCONTA, PDTINICIO, PDTFINAL, PDTINICIO, PDTFINAL;

    PKG_INTEGRACAOCONTABIL.P_DADOS_PISCOFINSSERVTOMADOS(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;
  
    --20 - SAÍDAS CANCELADAS TECHFIN
  IF PCODFATOGERADOR = 20 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 20 - SAÍDAS CANCELADAS TECHFIN';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODREGRA, PCONSOLIDAR, PDTFINAL,
            PCODPLANOCONTA, PCODPLANOCONTA,
            
			PDTINICIO, PDTFINAL, PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA;
    PKG_INTEGRACAOCONTABIL.P_DADOS_SAIDAS_CANC_TECHFIN(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;
  
    --21 - PROVISÕES TECHFIN
  IF PCODFATOGERADOR = 21 THEN
    ---------------------------------------------------------------------------------
    V_RETORNO := 'ABRINDO FATO GERADOR 21 - PROVISÕES TECHFIN';
    ---------------------------------------------------------------------------------
    OPEN CURSOR_DADOS FOR DBMS_LOB.SUBSTR(V_SQLFATOGERADOR)
      USING PCODREGRA, PCONSOLIDAR, PDTFINAL, PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PDTINICIO, PDTFINAL;
      
    PKG_INTEGRACAOCONTABIL.P_DADOS_PROV_TECHFIN(CURSOR_DADOS, PCODREGRA, PCODPLANOCONTA, V_RETORNO);
  END IF;  
  -- =============================================================================================================
  -- Testa contas compõe DMPL/DLPA com históricos não marcados como DMPL/DLPA
  -- PS_TIPOINCONSISTENCIA = 10
  -- Os outros tipos de inconsistências são tratados na proceduree PKG_INTEGRACAOCONTABIL.P_VERIFICA_INCONSISTENCIAS
  -- =============================================================================================================
  IF V_RETORNO IS NULL OR V_RETORNO = 'OK' THEN
    PKG_INTEGRACAOCONTABIL.P_VERIFICAR_CONTA_DMPLDLPA(PCODFILIAL, PCODREGRA, PDTINICIO, PDTFINAL, PCODPLANOCONTA, PCONSOLIDAR);
    RESULTADO := 'OK';
  ELSE
    RESULTADO := V_RETORNO;
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    BEGIN
      ROLLBACK;
      RESULTADO := 'Ocorreu um erro quando: ' || V_RETORNO || CHR(13) ||
                   'Erro Original: ' || SQLERRM;
    END;
END P_CTBINTEGRACAOCONTABIL;
