CREATE OR REPLACE PACKAGE PKG_MEMORIA_CALCULO AS

PROCEDURE INICIAR(P_CLOB OUT CLOB);

  FUNCTION FORMATAR_VALOR(P_VALOR IN NUMBER) RETURN VARCHAR2;
  FUNCTION FORMATAR_PERCENTUAL (p_valor IN NUMBER) RETURN VARCHAR2;

  PROCEDURE ADD_LINHA_DETALHE(P_CLOB  IN OUT NOCOPY CLOB,
                              P_TEXTO IN VARCHAR2);

  PROCEDURE ADD_TITULO_MEMORIA(
    P_CLOB  IN OUT NOCOPY CLOB,
    P_TEXTO IN VARCHAR2
  );

  PROCEDURE ADD_DETALHE_MEMORIA(
    P_CLOB      IN OUT NOCOPY CLOB,
    P_DESCRICAO IN VARCHAR2,
    P_VALOR     IN VARCHAR2
  );

  PROCEDURE GRAVAR_MEMORIA_CENTRAL(
    P_NUMTRANSITEM IN NUMBER,
    P_DETALHAMENTO IN CLOB, 
    P_DETALHAMENTO_JSON IN CLOB DEFAULT NULL);

  PROCEDURE GRAVAR_MEMORIA_IMP_ICMS(P_NUMTRANSITEM IN NUMBER,P_DETALHAMENTO IN CLOB);
  PROCEDURE GRAVAR_MEMORIA_IMP_ST(P_NUMTRANSITEM IN NUMBER, P_DETALHAMENTO IN CLOB);
  PROCEDURE GRAVAR_MEMORIA_IMP_FCP(P_NUMTRANSITEM IN NUMBER, P_DETALHAMENTO IN CLOB);
  PROCEDURE GRAVAR_MEMORIA_IMP_DIFAL(P_NUMTRANSITEM IN NUMBER, P_DETALHAMENTO IN CLOB);
  PROCEDURE GRAVAR_MEMORIA_IMP_PIS(P_NUMTRANSITEM IN NUMBER, P_DETALHAMENTO IN CLOB);
  PROCEDURE GRAVAR_MEMORIA_IMP_COFINS(P_NUMTRANSITEM IN NUMBER, P_DETALHAMENTO IN CLOB);

  PROCEDURE FINALIZAR(P_CLOB IN OUT NOCOPY CLOB);
END PKG_MEMORIA_CALCULO;
