CREATE OR REPLACE VIEW VW_INT_C5_OFERTA_R2017 AS
(
SELECT  -- E.CODFILIAL||P.SEQPRODUTO  SEQREGRA,
         NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = E.CODFILIAL||P.SEQPRODUTO||2017
              AND   ROWNUM = 1), 0) SEQREGRA,
         'OFERTA 2017' regra,
         E.CODFILIAL NROEMPRESA,
         3 SEQTIPOCREDITO,
         (CASE
          WHEN DTOFERTAFIM < TRUNC(SYSDATE)  THEN
               'N'
          ELSE 'S'
         END)  ATIVO,
         'G' tiporegra,
         'S' cumulativo,
         DTOFERTAFIM dtahorfim,
         DTOFERTAINI  dtahorinicio,
         E.CODAUXILIAR,
         P.SEQPRODUTO SEQPRODUTO,
         E.QTUNIT QTDEMBALAGEM,
         0 PERCDESCONTO,
         E.POFERTA PRECO,
         --'2017' IDREF
         E.CODFILIAL||P.SEQPRODUTO||2017 IDREF
FROM PCEMBALAGEM E,
     PCDEPARAEMBALAGENSC5 P,
     monitorpdvmiddle.tb_produto C,
     VW_INT_C5_OBTER_FILIAIS_C5 C5
     /*(select min(s.ultimaexecucao) ultimaexecucao
        from pccontroleconsinco s
        where (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAINCENTIVO')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAPRODUTO')
           or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAINCENTPERIODO')
     ) DATAPADRAO*/
WHERE E.CODAUXILIAR = P.CODAUXILIAR
--NVL(E.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
AND C.SEQPRODUTO = P.SEQPRODUTO
AND E.CODFILIAL = C5.CODFILIAL
AND E.CODPROD = C.SEQFAMILIA
AND E.DTOFERTAFIM >= TRUNC(SYSDATE)
AND NVL(E.POFERTA, 0) > 0
AND E.DTOFERTAINI IS NOT NULL
AND E.DTOFERTAFIM IS NOT NULL
)