DECLARE
  V_EXISTE VARCHAR2(100);
BEGIN
  BEGIN
    SELECT T.OBJECT_NAME 
      INTO V_EXISTE
      FROM ALL_OBJECTS T
     WHERE T.OBJECT_NAME = 'FUNC_RESUMOFATURAMENTO'
       AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
  EXCEPTION
    WHEN OTHERS THEN
      V_EXISTE := NULL;
  END;
  
  IF V_EXISTE IS NOT NULL THEN
    EXECUTE IMMEDIATE 'DROP FUNCTION FUNC_RESUMOFATURAMENTO';
  END IF;


END;