CREATE OR REPLACE PACKAGE PKG_SINC_PDV_CONSINCO_SANG_SUP IS

  PROCEDURE PROCESSAR_SANGRIA_SUPRIMENTO(P_SEQDOCTO NUMBER DEFAULT 0,
                                         P_NROCHECKOUT NUMBER DEFAULT 0,
										 P_NROEMPRESA NUMBER DEFAULT 0);

END PKG_SINC_PDV_CONSINCO_SANG_SUP;
