DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_NFE_PARCELA'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_NFE_PARCELA';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_NFE_PARCELA AS OBJECT
  (
     DTVENC DATE,
     PREST VARCHAR2(60),
     VALOR NUMBER,
     CODCOB VARCHAR2(4),
     VALORDESC NUMBER,
     DUPLICATA NUMBER(10),
     NUMPREST VARCHAR2(2),
     CODCOBSEFAZ VARCHAR2(4),
     CNPJ_CRED_CARTAO VARCHAR2(18),
     NUMAUTOR_CARTAO VARCHAR2(15),
     BANDEIRA_CARTAO VARCHAR2(3),
     TP_INTEGRA VARCHAR2(2), 
     DATACONSOLIDACAOPREFAT DATE, 
     PREFATURAMENTO VARCHAR2(1), 
     INDPAG NUMBER(1),
	 CNPJPAG VARCHAR2(14),
     UFPAG VARCHAR2(2),
     CNPJRECEB VARCHAR2(14),
     IDTERMPAG VARCHAR2(40)
  ) 