BEGIN
  --UPDATE 1:
  UPDATE PCDICIONARIOITEMROT
     SET SECAO = REPLACE(SUBSTR(SECAO, 1, 5), ' ', '') ||
                 SUBSTR(SECAO, 6, 200)
   WHERE CODROTINA = 202
     AND NOMEOBJETO = 'PCFORNEC'
     AND SUBSTR(SECAO, 1, 5) LIKE '% - %';

  --UPDATE 2:
  UPDATE PCDICIONARIOITEMROT
     SET SECAO = '08-' || SUBSTR(SECAO, 6, 200)
   WHERE CODROTINA = 202
     AND NOMEOBJETO = 'PCFORNEC'
     AND SUBSTR(SECAO, 1, 5) LIKE '%08 %';
END;