DECLARE

  V_STEP_5 CONSTANT VARCHAR2(50) := '05-Customizados';

  V_CODIGOROTINA CONSTANT PCDICIONARIOITEMROT.CODROTINA%TYPE := 203;
  V_OBJETO       CONSTANT PCDICIONARIOITEMROT.NOMEOBJETO%TYPE := 'PCPRODUT';
  V_CONTADOR NUMBER(10) := 1;

  TYPE ARRAY_CAMPOS IS VARRAY(100) OF VARCHAR2(100);
  V_LISTA_CAMPOS ARRAY_CAMPOS;

BEGIN

  FOR CUSTOMIZADOS IN (SELECT PCDICIONARIOITEMROTCUST.*
                             ,PCDICIONARIOITEMROTCUST.ROWID AS R_ID
                         FROM PCDICIONARIOITEMROTCUST
                        WHERE PCDICIONARIOITEMROTCUST.CODROTINA =
                              V_CODIGOROTINA
                          AND PCDICIONARIOITEMROTCUST.NOMEOBJETO = V_OBJETO
                          AND NOT EXISTS
                        (SELECT 1
                                 FROM PCDICIONARIOITEMROT R
                                WHERE R.CODROTINA =
                                      PCDICIONARIOITEMROTCUST.CODROTINA
                                  AND R.NOMEOBJETO =
                                      PCDICIONARIOITEMROTCUST.NOMEOBJETO
                                  AND R.NOMECAMPO =
                                      PCDICIONARIOITEMROTCUST.NOMECAMPO)
                        ORDER BY PCDICIONARIOITEMROTCUST.SECAO
                                ,PCDICIONARIOITEMROTCUST.ORDEMCAD)
  LOOP
  
    UPDATE PCDICIONARIOITEMROTCUST
       SET PCDICIONARIOITEMROTCUST.SECAO    = V_STEP_5
          ,PCDICIONARIOITEMROTCUST.ORDEMCAD = V_CONTADOR
     WHERE PCDICIONARIOITEMROTCUST.ROWID = CUSTOMIZADOS.R_ID;
  
    V_CONTADOR := V_CONTADOR + 1;
  END LOOP;

  FOR CUSTO IN (SELECT PCDICIONARIOITEMROT.*
                      ,PCDICIONARIOITEMROT.ROWID AS R_ID
                  FROM PCDICIONARIOITEMROT
                 WHERE PCDICIONARIOITEMROT.CODROTINA = V_CODIGOROTINA
                   AND PCDICIONARIOITEMROT.NOMEOBJETO = V_OBJETO
                 ORDER BY PCDICIONARIOITEMROT.SECAO
                         ,PCDICIONARIOITEMROT.ORDEMCAD)
  LOOP
  
    UPDATE PCDICIONARIOITEMROTCUST
       SET PCDICIONARIOITEMROTCUST.SECAO    = CUSTO.SECAO
          ,PCDICIONARIOITEMROTCUST.ORDEMCAD = CUSTO.ORDEMCAD
     WHERE PCDICIONARIOITEMROTCUST.CODROTINA = CUSTO.CODROTINA
       AND PCDICIONARIOITEMROTCUST.NOMECAMPO = CUSTO.NOMECAMPO
       AND PCDICIONARIOITEMROTCUST.NOMEOBJETO = CUSTO.NOMEOBJETO;
  
  END LOOP;

  UPDATE PCDICIONARIO
     SET DESCRICAO = 'Produto'
   WHERE NOMEOBJETO = 'PCPRODUT';
   
  UPDATE PCDICIONARIOITEMROTCUST
    SET MASCARA = NULL
  WHERE 
	NOMEOBJETO = 'PCPRODUT' AND 
	CODROTINA  = 203 AND 
	NOMECAMPO  = 'UNIDADETRIB';
	
  UPDATE PCDICIONARIOITEMROT
    SET OBRIGATORIO = 'N'
  WHERE 
	NOMEOBJETO = 'PCPRODUT' AND 
	CODROTINA  = 203 AND 
	NOMECAMPO  = 'USAECOMMERCEUNILEVER' AND
	VISIVEL    = 'N';	
	
  UPDATE PCDICIONARIOITEMROTCUST
    SET OBRIGATORIO = 'N'
  WHERE 
	NOMEOBJETO = 'PCPRODUT' AND 
	CODROTINA  = 203 AND 
	NOMECAMPO  = 'USAECOMMERCEUNILEVER' AND
	VISIVEL    = 'N';  	

  COMMIT;

END;
