DECLARE

  V_STEP_5 CONSTANT VARCHAR2(50) := '05-Customizados';

  V_CODIGOROTINA CONSTANT PCDICIONARIOITEMROT.CODROTINA%TYPE := 203;
  V_OBJETO       CONSTANT PCDICIONARIOITEMROT.NOMEOBJETO%TYPE := 'PCPRODUT';
  V_CONTADOR NUMBER(10) := 1;

  TYPE ARRAY_CAMPOS IS VARRAY(100) OF VARCHAR2(100);
  V_LISTA_CAMPOS ARRAY_CAMPOS;

BEGIN
 

  FOR CUSTOMIZADOS IN (SELECT PCDICIONARIOITEMROTCUST.*
                             ,PCDICIONARIOITEMROTCUST.ROWID AS R_ID
                         FROM PCDICIONARIOITEMROTCUST
                        WHERE PCDICIONARIOITEMROTCUST.CODROTINA =
                              V_CODIGOROTINA
                          AND PCDICIONARIOITEMROTCUST.NOMEOBJETO = V_OBJETO
                        ORDER BY PCDICIONARIOITEMROTCUST.SECAO
                                ,PCDICIONARIOITEMROTCUST.ORDEMCAD)
  LOOP
  
    UPDATE PCDICIONARIOITEMROTCUST
       SET PCDICIONARIOITEMROTCUST.SECAO    = V_STEP_5
          ,PCDICIONARIOITEMROTCUST.ORDEMCAD = V_CONTADOR
     WHERE PCDICIONARIOITEMROTCUST.ROWID = CUSTOMIZADOS.R_ID
       AND PCDICIONARIOITEMROTCUST.NOMECAMPO NOT IN
           ('CODPROD', 'DESCRICAO', 'CODFORNEC', 'CODEPTO', 'CODSEC',
            'CODMARCA', 'CODCATEGORIA', 'CODLINHAPROD', 'TIPOMERC',
            'NATUREZAPRODUTO', 'EMBALAGEM', 'UNIDADE', 'QTUNIT',
            'EMBALAGEMMASTER', 'UNIDADEMASTER', 'QTUNITCX', 'PESOLIQ',
            'PESOBRUTO', 'CODNCMEX', 'NBM', 'EXTIPI', 'CODAUXILIARTRIB',
            'GTINCODAUXILIARTRIB', 'GTINCODAUXILIAR', 'CODAUXILIAR',
            'GTINCODAUXILIAR2', 'CODAUXILIAR2', 'CODFAB', 'CODPRODMASTER',
            'CODPRODPRINC', 'ENVIAINFTECNICANFE', 'INFORMACOESTECNICAS',
            'DADOSTECNICOS', 'CHECARMULTIPLOVENDABNF', 'ENVIARFORCAVENDAS',
            'ACEITAVENDAFRACAO', 'PERCBONIFICVENDA', 'CLASSEVENDA', 'CLASSE',
            'MARGEMMIN', 'PRECOFIXO', 'PRECOMAXCONSUMTAB', 'PRECOMAXCONSUM',
            'MULTIPLO', 'PCOMEXT1', 'PCOMINT1', 'PCOMREP1', 'TIPOCOMISSAO',
            'VLBONIFIC', 'CODPRAZOENT', 'CUSTOREP', 'CUSTOREPTAB',
            'MULTIPLOCOMPRAS', 'PERCBONOUTRAS', 'TEMREPOS', 'QTMINSUGCOMPRA',
            'DESTAQUEFICHATECNICA', 'SUGVENDA', 'CODFILIAL',
            'CONCILIAIMPORTACAO', 'IMPORTADO', 'USALICENCAIMPORTACAO',
            'MOEDA', 'PERCDESC1', 'PERCDESC2', 'PERCDESC3', 'PERCDESC4',
            'PERCDESC5', 'PERCDESC6', 'PERCDESC7', 'PERCDESC8', 'PERCDESC9',
            'PERCDESC10', 'TIPOEMBARQUEIMP', 'PERCFRETE', 'PERCFRETEFOB',
            'UNIDADETRIB', 'CESTABASICALEGIS', 'UNIDADETRIBEX',
            'FATORCONVTRIB', 'FATORCONVTRIBEX', 'ISENTOTCIF',
            'LICITUSARDESONERAICM', 'LICITPERCDESONERAICM', 'PAISORIGEM',
            'CODDISTRIB', 'USAWMS', 'CONFERENOCHECKOUT', 'RESTRICAOTRANSP',
            'EXPORTABALANCA', 'PRAZOVAL', 'TIPOESTOQUE', 'APTO', 'MODULO',
            'LASTROPAL', 'TIPOPROD', 'TIPOVOLUMEDESCARGA', 'VOLUME', 'ALTURA',
            'PESOBRUTOMASTER', 'PESOEMBALAGEM', 'PESOPECA', 'PESOVARIAVEL',
            'PERCPERDAKG', 'PERCDIFERENCAKGFRIO', 'FATORCONVERSAOKG');
  
    V_CONTADOR := V_CONTADOR + 1;
  END LOOP;

  FOR CUSTO IN (SELECT PCDICIONARIOITEMROT.*
                      ,PCDICIONARIOITEMROT.ROWID AS R_ID
                  FROM PCDICIONARIOITEMROT
                 WHERE PCDICIONARIOITEMROT.CODROTINA = V_CODIGOROTINA
                   AND PCDICIONARIOITEMROT.NOMEOBJETO = V_OBJETO
                   AND PCDICIONARIOITEMROT.NOMECAMPO IN
                       ('CODPROD', 'DESCRICAO', 'CODFORNEC', 'CODEPTO',
                        'CODSEC', 'CODMARCA', 'CODCATEGORIA', 'CODLINHAPROD',
                        'TIPOMERC', 'NATUREZAPRODUTO', 'EMBALAGEM', 'UNIDADE',
                        'QTUNIT', 'EMBALAGEMMASTER', 'UNIDADEMASTER',
                        'QTUNITCX', 'PESOLIQ', 'PESOBRUTO', 'CODNCMEX', 'NBM',
                        'EXTIPI', 'CODAUXILIARTRIB', 'GTINCODAUXILIARTRIB',
                        'GTINCODAUXILIAR', 'CODAUXILIAR', 'GTINCODAUXILIAR2',
                        'CODAUXILIAR2', 'CODFAB', 'CODPRODMASTER',
                        'CODPRODPRINC', 'ENVIAINFTECNICANFE',
                        'INFORMACOESTECNICAS', 'DADOSTECNICOS',
                        'CHECARMULTIPLOVENDABNF', 'ENVIARFORCAVENDAS',
                        'ACEITAVENDAFRACAO', 'PERCBONIFICVENDA', 'CLASSEVENDA',
                        'CLASSE', 'MARGEMMIN', 'PRECOFIXO',
                        'PRECOMAXCONSUMTAB', 'PRECOMAXCONSUM', 'MULTIPLO',
                        'PCOMEXT1', 'PCOMINT1', 'PCOMREP1', 'TIPOCOMISSAO',
                        'VLBONIFIC', 'CODPRAZOENT', 'CUSTOREP', 'CUSTOREPTAB',
                        'MULTIPLOCOMPRAS', 'PERCBONOUTRAS', 'TEMREPOS',
                        'QTMINSUGCOMPRA', 'DESTAQUEFICHATECNICA', 'SUGVENDA',
                        'CODFILIAL', 'CONCILIAIMPORTACAO', 'IMPORTADO',
                        'USALICENCAIMPORTACAO', 'MOEDA', 'PERCDESC1',
                        'PERCDESC2', 'PERCDESC3', 'PERCDESC4', 'PERCDESC5',
                        'PERCDESC6', 'PERCDESC7', 'PERCDESC8', 'PERCDESC9',
                        'PERCDESC10', 'TIPOEMBARQUEIMP', 'PERCFRETE',
                        'PERCFRETEFOB', 'UNIDADETRIB', 'CESTABASICALEGIS',
                        'UNIDADETRIBEX', 'FATORCONVTRIB', 'FATORCONVTRIBEX',
                        'ISENTOTCIF', 'LICITUSARDESONERAICM',
                        'LICITPERCDESONERAICM', 'PAISORIGEM', 'CODDISTRIB',
                        'USAWMS', 'CONFERENOCHECKOUT', 'RESTRICAOTRANSP',
                        'EXPORTABALANCA', 'PRAZOVAL', 'TIPOESTOQUE', 'APTO',
                        'MODULO', 'LASTROPAL', 'TIPOPROD',
                        'TIPOVOLUMEDESCARGA', 'VOLUME', 'ALTURA',
                        'PESOBRUTOMASTER', 'PESOEMBALAGEM', 'PESOPECA',
                        'PESOVARIAVEL', 'PERCPERDAKG', 'PERCDIFERENCAKGFRIO',
                        'FATORCONVERSAOKG')
                 ORDER BY PCDICIONARIOITEMROT.SECAO
                         ,PCDICIONARIOITEMROT.ORDEMCAD)
  LOOP
  
    UPDATE PCDICIONARIOITEMROTCUST
       SET PCDICIONARIOITEMROTCUST.SECAO    = CUSTO.SECAO
          ,PCDICIONARIOITEMROTCUST.ORDEMCAD = CUSTO.ORDEMCAD
     WHERE PCDICIONARIOITEMROTCUST.CODROTINA = CUSTO.CODROTINA
       AND PCDICIONARIOITEMROTCUST.NOMECAMPO = CUSTO.NOMECAMPO
       AND PCDICIONARIOITEMROTCUST.NOMEOBJETO = CUSTO.NOMEOBJETO;
  
    V_CONTADOR := V_CONTADOR + 1;
  END LOOP;

  UPDATE PCDICIONARIO
     SET DESCRICAO = 'Produto'
   WHERE NOMEOBJETO = 'PCPRODUT';

  COMMIT;

END;
