CREATE OR REPLACE VIEW VW_INT_C5_REGRABINCARTAO AS
(
SELECT B.CODFIDELIDADE SEQREGRA, 
       B.CODBINCARTAO SEQBINCARTAO,
       0 PERCDESCONTO,
       DECODE(C.DTEXCLUSAO, NULL, 'S', 'N') ATIVO 
  FROM PCBINCARTAO C,
       PCBINCARTAOFIDELIDADE B,
       PCDESCONTOFIDELIDADE D       
 WHERE C.CODBINCARTAO  = B.CODBINCARTAO 
   AND B.CODFIDELIDADE = D.CODFIDELIDADE       
);