CREATE OR REPLACE VIEW VW_INT_C5_REGRABINCARTAO AS
(
SELECT NVL((SELECT M.SEQREGRA
	          FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
             WHERE M.IDREF = P.CODFILIAL||2048||P.CODFIDELIDADE
               AND ROWNUM = 1), 0) SEQREGRA,
       B.CODBINCARTAO SEQBINCARTAO,
       0 PERCDESCONTO,       
	   CASE 
         WHEN ((C.DTEXCLUSAO IS NOT NULL) OR (P.DTEXCLUSAO IS NOT NULL)) THEN 'N'
         ELSE 'S'
       END ATIVO
  FROM PCBINCARTAO C,
       PCBINCARTAOFIDELIDADE B,
       PCDESCONTOFIDELIDADE P       
 WHERE C.CODBINCARTAO  = B.CODBINCARTAO 
   AND B.CODFIDELIDADE = P.CODFIDELIDADE   
)
