CREATE OR REPLACE VIEW SQL_NFE_PARCELA_SAIDA_TROCO AS 
SELECT DH.NUMTRANSVENDA AS NUM_TRANSACAO,
       MAX((TO_CHAR(DH.DUPLIC) || ' - ' || TO_CHAR(DH.PREST))) AS PRESTACAO,
       MAX(DH.DUPLIC) AS DUPLIC,
       MAX(DH.PREST) AS PREST,
       TO_DATE('01/01/1899',
               'DD/MM/YYYY') AS DTVENC,
       ABS(SUM(NVL(DH.VALORENTFUT, DH.VALOR))) AS VALOR,
       MAX(DH.CODCOB) AS CODCOB,
       0 AS VALORDESC,
       NULL CODCOBSEFAZ,
       NULL AS CNPJ_CRED_CARTAO,
       NULL AS NUMAUTOR_CARTAO,
       0 AS BANDEIRA_CARTAO,
       NULL AS TP_INTEGRA,
       MAX(DH.DATACONSOLIDACAOPREFAT) DATACONSOLIDACAOPREFAT,
       'N' PREFATURAMENTO, 
       0 INDPAG
FROM  PCPREST DH, PCNFSAID, PCCOB
WHERE DH.STATUS = 'A'
AND   DH.CODCLI = PCNFSAID.CODCLI
AND   DH.DTDESD IS NULL
AND   DH.DTESTORNO IS NULL
AND   DH.CODCOB IN ('TR', 'DOAC')
AND   PCNFSAID.NUMTRANSVENDA = DH.NUMTRANSVENDA
AND   PCCOB.CODCOB = DH.CODCOB
AND   ((NVL(PCNFSAID.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAID.CODFILIAL) = 'S'))
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(DH.PERMITEESTORNO, 'S') = 'S'
GROUP BY DH.NUMTRANSVENDA
UNION ALL
SELECT DH.NUMTRANSVENDA AS NUM_TRANSACAO,
       MAX((TO_CHAR(DH.DUPLIC) || ' - ' || TO_CHAR(DH.PREST))) AS PRESTACAO,
       MAX(DH.DUPLIC) AS DUPLIC,
       MAX(DH.PREST) AS PREST,
       TO_DATE('01/01/1899',
               'DD/MM/YYYY') AS DTVENC,
       ABS(SUM(NVL(DH.VALORENTFUT, DH.VALOR))) AS VALOR,
       MAX(DH.CODCOB) AS CODCOB,
       0 AS VALORDESC,
       NULL CODCOBSEFAZ,
       NULL AS CNPJ_CRED_CARTAO,
       NULL AS NUMAUTOR_CARTAO,
       0 AS BANDEIRA_CARTAO,
       NULL AS TP_INTEGRA,
       MAX(DH.DATACONSOLIDACAOPREFAT) DATACONSOLIDACAOPREFAT,
       'S' PREFATURAMENTO,
       0 INDPAG
FROM  PCPRESTPREFAT DH, PCNFSAIDPREFAT, PCCOB
WHERE DH.STATUS = 'A'
AND   DH.DTDESD IS NULL
AND   DH.DTESTORNO IS NULL
AND   DH.CODCOB IN ('TR', 'DOAC')
AND   PCNFSAIDPREFAT.NUMTRANSVENDA = DH.NUMTRANSVENDA
AND   PCCOB.CODCOB = DH.CODCOB
AND   ((NVL(PCNFSAIDPREFAT.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAIDPREFAT.CODFILIAL) = 'S'))
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(DH.PERMITEESTORNO, 'S') = 'S'
AND   DH.DATACONSOLIDACAOPREFAT IS NULL
GROUP BY DH.NUMTRANSVENDA