DECLARE
  V_VALIDADOR NUMBER(3);
BEGIN
  V_VALIDADOR := 0;

  SELECT COUNT(1) INTO V_VALIDADOR FROM PCMODULO WHERE CODMODULO = -70;

  IF V_VALIDADOR = 0 THEN
  
    INSERT INTO PCMODULO
      (CODMODULO, MODULO, NUMVERSAO, DTULTVERSAO, EXIBIRMENU, AUTMENU)
    VALUES
      (-70, 'Inteligência Tributária', NULL, NULL, 'S', 0);
  
    INSERT INTO PCSUBMODULO
      (CODMODULO, CODSUBMODULO, SUBMODULO, EXIBIRMENU, AUTMENU)
    VALUES
      (-70, 1, 'Inteligência Tributária', 'S', 0);
  
    DELETE FROM PCROTINA WHERE CODIGO = 7000;
  
    INSERT INTO PCROTINA
      (CODIGO
      ,NOMEROTINA
      ,CODMODULO
      ,CODSUBMODULO
      ,LOG
      ,AJUDA
      ,NUMSEQ
      ,NUMULTVERSAO
      ,DTULTVERSAO
      ,NIVEL
      ,STATUS
      ,EXIBIRMENU
      ,AUTMENU
      ,VERSAOCOMPLETA)
    VALUES
      (7000
      ,'Inteligência Tributária'
      ,-70
      ,1
      ,NULL
      ,NULL
      ,NULL
      ,2
      ,SYSDATE
      ,NULL
      ,NULL
      ,'S'
      ,0
      ,NULL);
  END IF;

  INSERT INTO PCCONTRO
    (CODUSUARIO, CODROTINA, ACESSO)
    SELECT M.MATRICULA
          ,7000
          ,'S'
      FROM PCEMPR M
     WHERE NOT EXISTS
     (SELECT 1 FROM PCCONTRO WHERE PCCONTRO.CODUSUARIO = M.MATRICULA);

  COMMIT;

END;
