BEGIN
  
  DELETE FROM PCMODULO WHERE CODMODULO = -70;
  
  DELETE FROM PCSUBMODULO WHERE CODMODULO = -70;
  
  DELETE FROM PCMODULO WHERE CODMODULO = 70;
  
  DELETE FROM PCSUBMODULO WHERE CODMODULO = 70;
  
    INSERT INTO PCMODULO
      (CODMODULO, MODULO, NUMVERSAO, DTULTVERSAO, EXIBIRMENU, AUTMENU)
    VALUES
      (70, 'Inteligência Tributária', NULL, NULL, 'S', 0);
  
    INSERT INTO PCSUBMODULO
      (CODMODULO, CODSUBMODULO, SUBMODULO, EXIBIRMENU, AUTMENU)
    VALUES
      (70, 1, 'Inteligência Tributária', 'S', 0);
  
    UPDATE PCROTINA SET CODMODULO = ABS(CODMODULO) WHERE CODIGO = 7000;  

  INSERT INTO PCCONTRO
    (CODUSUARIO, CODROTINA, ACESSO)
    SELECT M.MATRICULA
          ,7000
          ,'S'
      FROM PCEMPR M
     WHERE NOT EXISTS
     (SELECT 1 FROM PCCONTRO WHERE PCCONTRO.CODUSUARIO = M.MATRICULA AND CODROTINA = 7000);

  COMMIT;

END;
