DECLARE
  VCONTDET NUMBER;
  VEXEC    VARCHAR2(4000);
BEGIN
  FOR DADOS IN (SELECT C.OWNER       ESQUEMA,
                       C.TABLE_NAME  TABELA,
                       C.COLUMN_NAME COLNOME,
                       C.DATA_TYPE   COLTIPO,
                       C.DATA_LENGTH COLTAMANHO
                  FROM ALL_TAB_COLUMNS C
                 WHERE C.TABLE_NAME = 'PCFILAMENSAGEMERRO'
                   AND C.COLUMN_NAME = 'DETALHE'
                   AND C.DATA_TYPE = 'VARCHAR2'
                   AND C.DATA_LENGTH = '4000') LOOP
               
   VCONTDET := 0;
    BEGIN
      SELECT COUNT(1)
        INTO VCONTDET
        FROM ALL_TAB_COLUMNS C
       WHERE C.TABLE_NAME = DADOS.TABELA
         AND C.COLUMN_NAME = DADOS.COLNOME
         AND C.DATA_TYPE = DADOS.COLTIPO
         AND C.DATA_LENGTH = DADOS.COLTAMANHO
         AND C.OWNER = DADOS.ESQUEMA;
    END;
  
    IF VCONTDET > 0 THEN
      vExec := 'ALTER TABLE '|| DADOS.ESQUEMA ||'.PCFILAMENSAGEMERRO DROP COLUMN DETALHE';
      EXECUTE IMMEDIATE VEXEC;
    
      VCONTDET := -1;
      BEGIN
        SELECT COUNT(1)
          INTO VCONTDET
          FROM ALL_TAB_COLUMNS C
         WHERE C.TABLE_NAME = DADOS.TABELA
           AND C.COLUMN_NAME = DADOS.COLNOME
           AND C.DATA_TYPE = DADOS.COLTIPO
           AND C.DATA_LENGTH = DADOS.COLTAMANHO
           AND C.OWNER = DADOS.ESQUEMA;
      END;
    
      IF VCONTDET = 0 THEN
        vExec := 'ALTER TABLE '|| DADOS.ESQUEMA||'.PCFILAMENSAGEMERRO ADD DETALHE CLOB';
        EXECUTE IMMEDIATE VEXEC;
      END IF;
    END IF;
  END LOOP;
END;