CREATE OR REPLACE VIEW VW_INT_C5_DESC561PRODUTO AS
(
SELECT DISTINCT
     NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
              AND   ROWNUM = 1), 0) SEQREGRA,

     C5.CODFILIALINTEGRACAO NROEMPRESA,
     'DESCONTO POR PRODUTO' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,

     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     --DEPARA.SEQFAMILIA,
     DEPARA.SEQPRODUTO,
     --'1' QTDEMBALAGEM,
     E.QTUNIT QTDEMBALAGEM,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     P.CODFILIAL||561||P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     PCEMBALAGEM E,
     PCDEPARAPRODC5 DEPARA,
     (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAPRODUTO')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
     ) DATAPADRAO, VW_INT_C5_OBTER_FILIAIS_C5 C5
WHERE DEPARA.CODPROD = P.CODPROD
AND DEPARA.ATIVO = 'S'
AND   P.CODFILIAL = C5.CODFILIAL
AND   P.CODDESCONTO = L.CODDESCONTO(+)
AND   P.CODPROD = E.CODPROD
AND   DEPARA.CODPROD = E.CODPROD
AND   P.CODFILIAL = E.CODFILIAL
AND   P.DTINICIO IS NOT NULL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A')
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   ((/*POLITICA DE DESCONTO POR PRODUTO*/
        ((P.CODPROD IS NOT NULL) OR 
         (P.CODPROD IS NOT NULL AND P.CODCLI IS NOT NULL)
        ) AND (P.CODAUXILIAR IS NULL)

        OR
        /*POLITICA DE DESCONTO POR EMBALAGEM*/
        ((P.CODPROD IS NULL) AND (P.CODAUXILIAR IS NOT NULL))

       ) 
      )

AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
--AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO)
AND   GREATEST(NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO),
                     NVL(E.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO)) >= DATAPADRAO.ULTIMAEXECUCAO)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561CLIENTE AS
(
SELECT
     --P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
              AND   ROWNUM = 1), 0) SEQREGRA,
     C5.CODFILIALINTEGRACAO NROEMPRESA,
     'DESCONTO POR CLIENTE' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,

     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODCLI SEQPESSOA,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     --P.CODDESCONTO IDREF
     P.CODFILIAL||561||P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     MONITORPDVMIDDLE.TB_CLIENTE CLI,
     (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRACLIENTE')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
      ) DATAPADRAO, VW_INT_C5_OBTER_FILIAIS_C5 C5
WHERE CLI.SEQPESSOA = P.CODCLI
AND   P.CODDESCONTO = L.CODDESCONTO(+)
AND   P.DTINICIO IS NOT NULL
AND   P.CODFILIAL = C5.CODFILIAL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A')
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   P.CODCLI IS NOT NULL
AND   P.CODPROD IS NULL
AND   P.CODAUXILIAR IS NULL
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\
CREATE OR REPLACE VIEW VW_INT_C5_DESC561CATEGORIA AS
(
  SELECT DISTINCT
    C.SEQCATEGORIA,
    DADOSCAT.SEQCATEGORIAWINTHOR, 
    DADOSCAT.NUMREGIAO,
    C.NRODIVISAO,
    DADOSCAT."SEQREGRA",DADOSCAT."REGRA",DADOSCAT."NROEMPRESA",DADOSCAT."SEQTIPOCREDITO",DADOSCAT."ATIVO",DADOSCAT."TIPOREGRA",DADOSCAT."CUMULATIVO",DADOSCAT."DTAHORINICIO",DADOSCAT."DTAHORFIM",DADOSCAT."CODEPTO",DADOSCAT."CODSEC",DADOSCAT."CODCATEGORIA",DADOSCAT."CODSUBCATEGORIA",DADOSCAT."NIVEL",DADOSCAT."PERCDESCONTO",DADOSCAT."PRECO",DADOSCAT."IDREF"
  FROM
    (SELECT 
      NVL((SELECT M.SEQREGRA
                FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
                WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
                AND   ROWNUM = 1), 0) SEQREGRA,
      'DESCONTO POR CATEGORIA' REGRA,
      C5.CODFILIALINTEGRACAO NROEMPRESA,
      regpadraovarejo.NUMREGIAO,
      regpadraovarejo.NRODIVISAO,
      3 AS SEQTIPOCREDITO,
      (CASE
          WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
              'N'
          ELSE 'S'
      END) ATIVO,

      'G' TIPOREGRA,
      'S' CUMULATIVO,
      P.DTINICIO DTAHORINICIO,
      P.DTFIM DTAHORFIM,
      PROD.CODPROD,
      PROD.CODEPTO,
      PROD.CODSEC,
      PROD.CODCATEGORIA,
      PROD.CODSUBCATEGORIA CODSUBCATEGORIA,
      regpadraovarejo.NUMREGIAO || 
      (CASE
              WHEN PROD.CODSUBCATEGORIA IS NOT NULL THEN
                  PROD.CODSEC||'0'||PROD.CODCATEGORIA||'0'||PROD.CODSUBCATEGORIA||'0'||4
              WHEN PROD.CODCATEGORIA IS NOT NULL THEN
                  PROD.CODSEC||'0'||PROD.CODCATEGORIA||'0'||3
              WHEN PROD.CODSEC IS NOT NULL THEN
                  PROD.CODSEC||'0'||2
              ELSE PROD.CODEPTO||1
      END) SEQCATEGORIAWINTHOR,
      (CASE
          WHEN PROD.CODSUBCATEGORIA IS NOT NULL THEN
                4
          WHEN PROD.CODCATEGORIA IS NOT NULL THEN
                3
          WHEN PROD.CODSEC IS NOT NULL THEN
                2
          WHEN PROD.CODEPTO IS NOT NULL THEN
                1
      END) NIVEL,
      P.PERCDESC PERCDESCONTO,
      0  PRECO,
      P.CODFILIAL||561||P.CODDESCONTO IDREF
    FROM PCDESCONTO P,
      PCPRODUT PROD,
      PCDESCONTOLOG L,
      (SELECT DISTINCT
              TO_CHAR(pcparamfilial.valor) NUMREGIAO,
              TO_CHAR(D.NRODIVISAO) NRODIVISAO,
              to_char(pcparamfilial.CODFILIAL) vinculofilial
          FROM pcparamfilial, PCDEPARAREGIAOC5 D
        WHERE D.NUMREGIAO = pcparamfilial.valor
          AND nome = 'NUMREGIAOPADRAOVAREJO'
          AND valor <> '99'
          AND FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'

          UNION ALL

          SELECT
              TO_CHAR(NROEMPRESA) NUMREGIAO,
              TO_CHAR(NROEMPRESA) NRODIVISAO,
              to_char(NROEMPRESA) vinculofilial
          from MONITORPDVMIDDLE.TB_EMPRESA tb
          WHERE
         	FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S'
      ) regpadraovarejo,
      
      (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRACATEGORIA')
          or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
          or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
      ) DATAPADRAO, VW_INT_C5_OBTER_FILIAIS_C5 C5
    WHERE P.CODDESCONTO = L.CODDESCONTO(+)
    AND   P.DTINICIO IS NOT NULL
    AND   P.DTFIM IS NOT NULL
    AND   P.CODFILIAL = C5.CODFILIAL
    AND   regpadraovarejo.vinculofilial = CASE WHEN FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S' THEN TO_CHAR(C5.codfilialintegracao) ELSE c5.codfilial end
    AND   P.ORIGEMPED IN('O', 'A')
    AND   P.TIPO = 'C'
    AND   NVL(P.APLICADESCONTO, 'N') = 'S'
    AND   NVL(P.CODFILIAL, '99') <> '99'
    AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
    AND   P.CODAUXILIAR IS NULL
    AND   ((P.CODEPTO IS NOT NULL) OR (P.CODSEC IS NOT NULL) OR (P.CODCATEGORIA IS NOT NULL) OR (P.SUBCATEGORIA IS NOT NULL))
    AND   P.CODCLI IS NULL
    AND   P.CODMARCA IS NULL
    AND   P.CODFORNEC IS NULL
    AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
    AND   ((P.SUBCATEGORIA IS NOT NULL) AND (PROD.CODSUBCATEGORIA = P.SUBCATEGORIA) OR
            (P.SUBCATEGORIA IS NULL) AND (P.CODCATEGORIA IS NOT NULL) AND (PROD.CODCATEGORIA = P.CODCATEGORIA) OR
            (P.SUBCATEGORIA IS NULL) AND (P.CODCATEGORIA IS NULL) AND (P.CODSEC IS NOT NULL) AND(PROD.CODSEC = P.CODSEC) OR
            (P.SUBCATEGORIA IS NULL) AND (P.CODCATEGORIA IS NULL) AND (P.CODSEC IS NULL) AND (P.CODEPTO IS NOT NULL) AND (PROD.CODEPTO = P.CODEPTO)
          )
    )DADOSCAT,

    MONITORPDVMIDDLE.TB_CATEGORIA C,
    PCDEPARACATEGORIAC5 D
  WHERE D.SEQCATEGORIAWINTHOR = DADOSCAT.SEQCATEGORIAWINTHOR
    AND   D.SEQCATEGORIAC5 = C.SEQCATEGORIA
    AND   DADOSCAT.NIVEL = C.NIVELHIERARQUIA
    AND   C.NRODIVISAO = DADOSCAT.NRODIVISAO
)