CREATE OR REPLACE VIEW VW_INT_C5_DESC561FAMILIA AS
(SELECT 
     P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     'DESCONTO POR PRODUTO' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,
     
     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODPROD SEQFAMILIA,
     '1' QTDEMBALAGEM,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     monitorpdvmiddle.tb_familia f,
     (SELECT S.ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAFAMILIA') DATAPADRAO
WHERE P.CODPROD = f.SEQFAMILIA
AND   P.CODDESCONTO = L.CODDESCONTO(+) 
AND   P.DTINICIO IS NOT NULL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A') 
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   ((P.CODPROD IS NOT NULL) OR (P.CODPROD IS NOT NULL AND P.CODCLI IS NOT NULL))  
AND   P.CODAUXILIAR IS NULL
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561PRODUTO AS
(
 SELECT 
     P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     'DESCONTO POR EMBALAGEM' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,
     
     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     PROD.SEQPRODUTO,
     PROD.QTDEMBALAGEM,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     MONITORPDVMIDDLE.TB_PRODCODIGO PROD,
     (SELECT S.ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAPRODUTO') DATAPADRAO
WHERE P.CODAUXILIAR = PROD.CODACESSO
AND   P.CODFILIAL = PROD.NROEMPRESA
AND   P.CODDESCONTO = L.CODDESCONTO(+) 
AND   P.DTINICIO IS NOT NULL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A') 
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   P.CODAUXILIAR IS NOT NULL
AND   P.CODPROD IS NULL  
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODCLI IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561CATEGORIA AS
(
SELECT 
  C.SEQCATEGORIA,
  C.NRODIVISAO,
  DADOSCAT.*
FROM  
   (SELECT 
     P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     'DESCONTO POR CATEGORIA' REGRA,
     P.CODFILIAL,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,
     
     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODEPTO,
     P.CODSEC,
     P.CODCATEGORIA,
     P.SUBCATEGORIA CODSUBCATEGORIA,
     (CASE
         WHEN P.SUBCATEGORIA IS NOT NULL THEN
              4
         WHEN P.CODCATEGORIA IS NOT NULL THEN
              3
         WHEN P.CODSEC IS NOT NULL THEN
              2
         WHEN P.CODEPTO IS NOT NULL THEN
              1
     END) NIVEL,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,    
     P.CODDESCONTO IDREF 
   FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     (SELECT S.ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRACATEGORIA') DATAPADRAO
   WHERE P.CODDESCONTO = L.CODDESCONTO(+) 
   AND   P.DTINICIO IS NOT NULL
   AND   P.DTFIM IS NOT NULL
   AND   P.ORIGEMPED IN('O', 'A') 
   AND   P.TIPO = 'C'
   AND   NVL(P.APLICADESCONTO, 'N') = 'S'
   AND   NVL(P.CODFILIAL, '99') <> '99'
   AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
   AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
   AND   P.CODPROD IS NULL  
   AND   P.CODAUXILIAR IS NULL
   AND   ((P.CODEPTO IS NOT NULL) OR (P.CODSEC IS NOT NULL) OR (P.CODCATEGORIA IS NOT NULL) OR (P.SUBCATEGORIA IS NOT NULL))
   AND   P.CODCLI IS NULL
   AND   P.CODMARCA IS NULL
   AND   P.CODFORNEC IS NULL
   AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
   )DADOSCAT,
   
   MONITORPDVMIDDLE.TB_CATEGORIA C
WHERE DADOSCAT.NIVEL = C.NIVELHIERARQUIA
AND  ((DADOSCAT.CODEPTO = C.IDREF) OR (DADOSCAT.CODSEC = C.IDREF) OR (DADOSCAT.CODCATEGORIA = C.IDREF) OR (DADOSCAT.CODSUBCATEGORIA = C.IDREF))
AND   C.NRODIVISAO = ferramentas.f_buscarparametro_num('NUMREGIAOPADRAOVAREJO', DADOSCAT.CODFILIAL, '99')
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561CLIENTE AS
(
SELECT 
     P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     'DESCONTO POR CLIENTE' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,
     
     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODCLI SEQPESSOA,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,    
     P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     MONITORPDVMIDDLE.TB_CLIENTE CLI,
     (SELECT S.ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRACLIENTE') DATAPADRAO
WHERE CLI.SEQPESSOA = P.CODCLI
AND   P.CODDESCONTO = L.CODDESCONTO(+) 
AND   P.DTINICIO IS NOT NULL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A') 
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   P.CODCLI IS NOT NULL
AND   P.CODPROD IS NULL  
AND   P.CODAUXILIAR IS NULL
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)