CREATE OR REPLACE VIEW VW_INT_C5_DESC561PRODUTO AS
(
 SELECT
     --P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
              AND   ROWNUM = 1), 0) SEQREGRA,
     P.CODFILIAL NROEMPRESA,
     'DESCONTO POR EMBALAGEM' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,

     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     PROD.SEQPRODUTO,
     PROD.QTDEMBALAGEM,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
--     P.CODDESCONTO IDREF
     P.CODFILIAL||561||P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     MONITORPDVMIDDLE.TB_PRODCODIGO PROD,
     (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAPRODUTO')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
      ) DATAPADRAO
WHERE P.CODAUXILIAR = PROD.CODACESSO
AND   P.CODFILIAL = PROD.NROEMPRESA
AND   P.CODDESCONTO = L.CODDESCONTO(+)
AND   P.DTINICIO IS NOT NULL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A')
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   P.CODAUXILIAR IS NOT NULL
AND   P.CODPROD IS NULL
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODCLI IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561FAMILIA AS
(SELECT
     --P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
              AND   ROWNUM = 1), 0) SEQREGRA,

     P.CODFILIAL NROEMPRESA,
     'DESCONTO POR PRODUTO' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,

     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODPROD SEQFAMILIA,
     '1' QTDEMBALAGEM,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     --P.CODDESCONTO IDREF
     P.CODFILIAL||561||P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     monitorpdvmiddle.tb_familia f,
     (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAFAMILIA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
     ) DATAPADRAO
WHERE P.CODPROD = f.SEQFAMILIA
AND   P.CODDESCONTO = L.CODDESCONTO(+)
AND   P.DTINICIO IS NOT NULL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A')
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   ((P.CODPROD IS NOT NULL) OR (P.CODPROD IS NOT NULL AND P.CODCLI IS NOT NULL))
AND   P.CODAUXILIAR IS NULL
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561CLIENTE AS
(
SELECT
     --P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
              AND   ROWNUM = 1), 0) SEQREGRA,
     P.CODFILIAL NROEMPRESA,
     'DESCONTO POR CLIENTE' REGRA,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,

     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODCLI SEQPESSOA,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     --P.CODDESCONTO IDREF
     P.CODFILIAL||561||P.CODDESCONTO IDREF
FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     MONITORPDVMIDDLE.TB_CLIENTE CLI,
     (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRACLIENTE')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
      ) DATAPADRAO, VW_INT_C5_OBTER_FILIAIS_C5 C5
WHERE CLI.SEQPESSOA = P.CODCLI
AND   P.CODDESCONTO = L.CODDESCONTO(+)
AND   P.DTINICIO IS NOT NULL
AND   P.CODFILIAL = C5.CODFILIAL
AND   P.DTFIM IS NOT NULL
AND   P.ORIGEMPED IN('O', 'A')
AND   P.TIPO = 'C'
AND   NVL(P.APLICADESCONTO, 'N') = 'S'
AND   NVL(P.CODFILIAL, '99') <> '99'
AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
AND   P.CODCLI IS NOT NULL
AND   P.CODPROD IS NULL
AND   P.CODAUXILIAR IS NULL
AND   P.CODEPTO IS NULL
AND   P.CODSEC IS NULL
AND   P.CODCATEGORIA IS NULL
AND   P.SUBCATEGORIA IS NULL
AND   P.CODMARCA IS NULL
AND   P.CODFORNEC IS NULL
AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_DESC561CATEGORIA AS
(
SELECT
  C.SEQCATEGORIA,
  C.NRODIVISAO,
  DADOSCAT."SEQREGRA",DADOSCAT."REGRA",DADOSCAT."NROEMPRESA",DADOSCAT."SEQTIPOCREDITO",DADOSCAT."ATIVO",DADOSCAT."TIPOREGRA",DADOSCAT."CUMULATIVO",DADOSCAT."DTAHORINICIO",DADOSCAT."DTAHORFIM",DADOSCAT."CODEPTO",DADOSCAT."CODSEC",DADOSCAT."CODCATEGORIA",DADOSCAT."CODSUBCATEGORIA",DADOSCAT."NIVEL",DADOSCAT."PERCDESCONTO",DADOSCAT."PRECO",DADOSCAT."IDREF"
FROM
   (SELECT
     --P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     NVL((SELECT M.SEQREGRA
              FROM MONITORPDVMIDDLE.TB_REGRAINCENTIVO M
              WHERE M.IDREF = P.CODFILIAL||561||P.CODDESCONTO
              AND   ROWNUM = 1), 0) SEQREGRA,
     'DESCONTO POR CATEGORIA' REGRA,
     P.CODFILIAL NROEMPRESA,
     ferramentas.f_buscarparametro_num('NUMREGIAOPADRAOVAREJO', P.CODFILIAL, '1') NUMREGIAO,
     3 AS SEQTIPOCREDITO,
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,

     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM,
     P.CODEPTO,
     P.CODSEC,
     P.CODCATEGORIA,
     P.SUBCATEGORIA CODSUBCATEGORIA,
     (CASE
            WHEN P.SUBCATEGORIA IS NOT NULL THEN
                 P.CODSEC||'0'||P.CODCATEGORIA||'0'||P.SUBCATEGORIA||'0'||4
            WHEN P.CODCATEGORIA IS NOT NULL THEN
                 P.CODCATEGORIA||'0'||P.CODCATEGORIA||'0'||3
            WHEN P.CODSEC IS NOT NULL THEN
                 P.CODSEC||'0'||2
            ELSE P.CODEPTO||1
     END) SEQCATEGORIAWINTHOR,
     (CASE
         WHEN P.SUBCATEGORIA IS NOT NULL THEN
              4
         WHEN P.CODCATEGORIA IS NOT NULL THEN
              3
         WHEN P.CODSEC IS NOT NULL THEN
              2
         WHEN P.CODEPTO IS NOT NULL THEN
              1
     END) NIVEL,
     P.PERCDESC PERCDESCONTO,
     0  PRECO,
     --P.CODDESCONTO IDREF
     P.CODFILIAL||561||P.CODDESCONTO IDREF
   FROM PCDESCONTO P,
     PCDESCONTOLOG L,
     (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRACATEGORIA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRAEMPRESA')
         or (upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_REGRASEGMENTO')
     ) DATAPADRAO, VW_INT_C5_OBTER_FILIAIS_C5 C5
   WHERE P.CODDESCONTO = L.CODDESCONTO(+)
   AND   P.DTINICIO IS NOT NULL
   AND   P.DTFIM IS NOT NULL
   AND   P.CODFILIAL = C5.CODFILIAL
   AND   P.ORIGEMPED IN('O', 'A')
   AND   P.TIPO = 'C'
   AND   NVL(P.APLICADESCONTO, 'N') = 'S'
   AND   NVL(P.CODFILIAL, '99') <> '99'
   AND   REGEXP_LIKE(P.CODFILIAL, '^[[:digit:]]+$')
   AND   TRUNC(SYSDATE) BETWEEN P.DTINICIO AND P.DTFIM
   AND   P.CODPROD IS NULL
   AND   P.CODAUXILIAR IS NULL
   AND   ((P.CODEPTO IS NOT NULL) OR (P.CODSEC IS NOT NULL) OR (P.CODCATEGORIA IS NOT NULL) OR (P.SUBCATEGORIA IS NOT NULL))
   AND   P.CODCLI IS NULL
   AND   P.CODMARCA IS NULL
   AND   P.CODFORNEC IS NULL
   AND   NVL(P.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
   )DADOSCAT,

   MONITORPDVMIDDLE.TB_CATEGORIA C,
   PCDEPARACATEGORIAC5 D
WHERE D.SEQCATEGORIAWINTHOR = DADOSCAT.NUMREGIAO||DADOSCAT.SEQCATEGORIAWINTHOR
AND   D.SEQCATEGORIAC5 = C.SEQCATEGORIA
AND   DADOSCAT.NIVEL = C.NIVELHIERARQUIA
AND   C.NRODIVISAO = (SELECT R.NRODIVISAO
                      FROM   PCDEPARAREGIAOC5 R
                      WHERE  R.NUMREGIAO = ferramentas.f_buscarparametro_num('NUMREGIAOPADRAOVAREJO', DADOSCAT.NROEMPRESA, '1')
                      AND    FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') <> 'S'
                      
                      UNION ALL
                          
                      SELECT NROEMPRESA DIVISAO
                      FROM MONITORPDVMIDDLE.TB_EMPRESA E
                      WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('CON_USATRIBUTACAOPORUF', '99', 'N') = 'S' 
                      AND   E.NROEMPRESA = DADOSCAT.NROEMPRESA
                     )
)