CREATE OR REPLACE PACKAGE PKG_PARAMETRO_CONTABIL IS
 VCODFILIAL  VARCHAR2(2);
 vDATA1      DATE;
 vDATA2      DATE;

 PROCEDURE SET_CODFILIAL(P_CODFILIAL IN VARCHAR2);
 PROCEDURE SET_DATA1    (P_DATA IN DATE);
 PROCEDURE SET_DATA2    (P_DATA IN DATE);

 FUNCTION GET_CODFILIAL RETURN VARCHAR2;
 FUNCTION GET_DATA1     RETURN DATE;
 FUNCTION GET_DATA2     RETURN DATE;
END;