CREATE OR REPLACE PACKAGE BODY PKG_PARAMETRO_CONTABIL is
 PROCEDURE SET_DATA1     (P_DATA IN DATE) IS BEGIN vDATA1 := P_DATA;  END;
 PROCEDURE SET_DATA2     (P_DATA IN DATE) IS BEGIN vDATA2 := P_DATA;  END;
 PROCEDURE SET_CODFILIAL (P_CODFILIAL    IN VARCHAR2) IS BEGIN vCODFILIAL    := P_CODFILIAL;    END;


 FUNCTION GET_DATA1     RETURN DATE IS BEGIN  RETURN NVL(vDATA1, TO_DATE('01/01/1900','DD/MM/YYYY')); END;
 FUNCTION GET_DATA2     RETURN DATE IS BEGIN  RETURN NVL(vDATA2, TO_DATE('01/01/2200','DD/MM/YYYY')); END;
 FUNCTION GET_CODFILIAL RETURN VARCHAR2 IS BEGIN RETURN vCODFILIAL; END;
END;