DECLARE
vSQL VARCHAR2(2000);
COL_CONT INTEGER;

BEGIN
	SELECT COUNT(*) 
	 INTO COL_CONT 
	FROM PCROTDESCONTINUADAS WHERE CODROTINA = 289;
	
	IF COL_CONT > 0 THEN		
		vSQL := 'DELETE FROM PCROTDESCONTINUADAS WHERE CODROTINA = 289';
		EXECUTE IMMEDIATE vSQL;
	END;
	commit;
END;