DECLARE
  vREGRACALCREALIZADO PCGMINDICADOR.REGRACALCREALIZADO%type;
  vREGRACALCPREVISTO PCGMINDICADOR.REGRACALCPREVISTO%type;
BEGIN
  /* Migração da rotina 300 - PKG_GESTAOMETA*/
  FOR LINHA IN (SELECT * FROM PCGMINDICADOR WHERE CODIGO IN(5, 8, 11, 16)) LOOP
    vREGRACALCREALIZADO := '';
    vREGRACALCPREVISTO  := '';
        
    CASE LINHA.CODIGO
      WHEN 1 THEN -- LITRAGEM TOTAL
      BEGIN
        vREGRACALCREALIZADO := 'SUM(NVL(LITRAGEMLIQUIDO, 0))';
        vREGRACALCPREVISTO  := 'SUM(PREVISTO.VALOR)';
      END;
      WHEN 5 THEN -- NÚMERO DE CLIENTES POSITIVADOS
      BEGIN
        vREGRACALCREALIZADO := 'COUNT(DISTINCT MOV.CODCLI)';
        vREGRACALCPREVISTO  := '';
      END;
      WHEN 8 THEN -- PERCENTUAL LUCRO
      BEGIN
        vREGRACALCREALIZADO := 'CASE WHEN SUM(VLVENDA - (CASE WHEN VLST > 0 THEN  VLST ELSE 0 END) - (CASE WHEN VLIPI > 0 THEN VLIPI ELSE 0 END)) = 0  THEN 0 ';
        vREGRACALCREALIZADO :=  vREGRACALCREALIZADO || ' ELSE  ROUND(SUM(VLLUCRO) / SUM(VLVENDA - (CASE WHEN VLST > 0 THEN VLST ELSE 0 END) - (CASE WHEN VLIPI > 0 THEN VLIPI ELSE 0 END)) * 100, 2) END';
        vREGRACALCPREVISTO  := '';
      END;
      WHEN 11 THEN -- PRAZO MÉDIO
      BEGIN
        vREGRACALCREALIZADO := 'ROUND(SUM(NVL(PRAZOMEDIO, 0) * (NVL(VLVENDA, 0))) / SUM(NVL(VLVENDA, 0) - (CASE WHEN VLST > 0 THEN VLST ELSE 0 END) - (CASE WHEN VLIPI > 0 THEN VLIPI ELSE 0 END) - NVL(VLFECP, 0)))';
        vREGRACALCPREVISTO  := '';
      END;
      WHEN 16 THEN -- VALOR FATURADO LÍQUIDO
      BEGIN
        vREGRACALCREALIZADO := 'ROUND(SUM(NVL(VLLIQUIDO, 0) - NVL(VLST, 0) - NVL(VLIPI, 0) - NVL(VLFECP, 0)), 2)';
        vREGRACALCPREVISTO  := 'SUM(PREVISTO.VALOR)';
      END;
      WHEN 18 THEN -- VALOR MÉDIO DE VENDA
      BEGIN
        vREGRACALCREALIZADO := 'SUM(NVL(VOLUMELIQUIDO, 0))';
        vREGRACALCPREVISTO  := 'SUM(PREVISTO.VALOR)';
      END;
    END CASE;
    
    UPDATE PCGMINDICADOR SET
      REGRACALCREALIZADO = vREGRACALCREALIZADO,
      REGRACALCPREVISTO  = DECODE(vREGRACALCPREVISTO,'',NULL,vREGRACALCPREVISTO)
    WHERE CODIGO = LINHA.CODIGO;
    
    COMMIT;
  END LOOP;
END;