CREATE OR REPLACE FUNCTION F_EXTRAIR_SQL_VIEW(P_VIEW_NAME IN VARCHAR2,
                                              P_PARAMETRO IN VARCHAR2)
  RETURN VARCHAR2 IS
  V_SQL_TEXT     CLOB;
  V_START_MARKER VARCHAR2(100) := '--INICIO_' || UPPER(P_PARAMETRO);
  V_END_MARKER   VARCHAR2(100) := '--FIM_' || UPPER(P_PARAMETRO);
  V_START_POS    PLS_INTEGER;
  V_END_POS      PLS_INTEGER;
  V_RESULT       CLOB;
BEGIN

  SELECT V.TEXT
    INTO V_SQL_TEXT
    FROM TABLE(F_USER_VIEWS_PTF('V%')) V
   WHERE V.VIEW_NAME = P_VIEW_NAME;


  V_START_POS := INSTR(V_SQL_TEXT, V_START_MARKER);
  V_END_POS   := INSTR(V_SQL_TEXT, V_END_MARKER);

  IF V_START_POS = 0 OR
     V_END_POS = 0 THEN
    RETURN NULL; 
  END IF;

  V_START_POS := V_START_POS + LENGTH(V_START_MARKER);

  V_RESULT := TRIM(SUBSTR(V_SQL_TEXT, V_START_POS, V_END_POS - V_START_POS));

  WHILE INSTR(V_RESULT, '  ') > 0
  LOOP
    V_RESULT := REPLACE(V_RESULT, '  ', ' ');
  END LOOP;

  V_RESULT := REPLACE(V_RESULT, ' (', '(');
  V_RESULT := REPLACE(V_RESULT, '( ', '(');
  V_RESULT := REPLACE(V_RESULT, ' )', ')');
  V_RESULT := REPLACE(V_RESULT, ') ', ')');

  V_RESULT := REPLACE(V_RESULT, ' ,', ',');
  V_RESULT := REPLACE(V_RESULT, ', ', ',');

  RETURN V_RESULT;
END;
