DECLARE
  vTIPOCAMPO VARCHAR2(100);
  vSQL       VARCHAR2(4000);
BEGIN

  SELECT DATA_TYPE
    INTO vTIPOCAMPO
    FROM user_tab_columns
   WHERE table_name = 'PCMOVCOMPLEPREENT'
     AND COLUMN_NAME = 'SITTRIBUTORIG';

  IF (vTIPOCAMPO = 'NUMBER') THEN
  
    vSQL := 'ALTER TABLE PCMOVCOMPLEPREENT ADD SITTRIBUTORIG_BKP VARCHAR2(3)';
    EXECUTE IMMEDIATE vSQL;
  
    vSQL := 'UPDATE PCMOVCOMPLEPREENT SET SITTRIBUTORIG_BKP = TO_CHAR(SITTRIBUTORIG) WHERE SITTRIBUTORIG IS NOT NULL';
    EXECUTE IMMEDIATE vSQL;
    
    COMMIT;
    
    vSQL := 'ALTER TABLE PCMOVCOMPLEPREENT DROP COLUMN SITTRIBUTORIG';
    EXECUTE IMMEDIATE vSQL;
  
    vSQL := 'ALTER TABLE PCMOVCOMPLEPREENT ADD SITTRIBUTORIG VARCHAR2(3)';
    EXECUTE IMMEDIATE vSQL;
    
    vSQL := 'UPDATE PCMOVCOMPLEPREENT SET SITTRIBUTORIG = TO_CHAR(SITTRIBUTORIG_BKP) WHERE SITTRIBUTORIG_BKP IS NOT NULL';
    EXECUTE IMMEDIATE vSQL;
    
    COMMIT;
    
    vSQL := 'ALTER TABLE PCMOVCOMPLEPREENT DROP COLUMN SITTRIBUTORIG_BKP';
    EXECUTE IMMEDIATE vSQL;
    
  END IF;
END;
