CREATE OR REPLACE VIEW VW_INT_C5_RECFATURA AS
(
SELECT  
        D.SEQDOCTO,
        D.NROEMPRESA,
        D.NROCHECKOUT,
        MAX(PG.NSUTEF) NSUTEF,
        SUM(PG.VLRTOTAL) VLRTOTAL,
        TO_CHAR(D.DTAHOREMISSAO, 'YYYY-MM-DD') DTAHOREMISSAO,
        TO_CHAR(D.DTAMOVIMENTO, 'YYYY-MM-DD') DTAMOVIMENTO,
        D.SEQUSUARIO,
        D.COO,
        'C' ORIGEMFATURA,
        'E' STATUS,
        MAX(NVL(PG.CODREDETEF,'0')) CODOPERRECARGACEL,
        
        CASE
          WHEN TO_NUMBER(MAX(NVL(PG.CODREDETEF,'0'))) = 266 THEN
               'D'
          WHEN TO_NUMBER(MAX(NVL(PG.CODREDETEF,'0'))) = 269 THEN 
               'B'    
          WHEN TO_NUMBER(MAX(NVL(PG.CODREDETEF,'0'))) = 52 THEN      
               'T'
          ELSE ''
       END TIPOFATURA

 FROM  MONITORPDVMIDDLE.TB_DOCTO D,
       MONITORPDVMIDDLE.TB_DOCTOPAGTO PG
 WHERE  D.SEQDOCTO = PG.SEQDOCTO
 AND    D.NROEMPRESA = PG.NROEMPRESA
 AND    D.NROCHECKOUT = PG.NROCHECKOUT
 AND    D.REPLICACAO = 'P'
 AND    D.ESPECIE IN ('PL')
 GROUP BY 
        D.SEQDOCTO,
        D.NROEMPRESA,
        D.NROCHECKOUT,
        D.SEQUSUARIO,
        D.DTAHOREMISSAO,
        D.DTAMOVIMENTO,
        D.COO
)