CREATE OR REPLACE VIEW VW_INT_C5_RECFATURA AS
(
SELECT  
        D.SEQDOCTO,
        D.NROEMPRESA,
        D.NROCHECKOUT,
        PG.NSUTEF,
        SUM(PG.VLRTOTAL) VLRTOTAL,
        TO_CHAR(D.DTAHOREMISSAO, 'YYYY-MM-DD') DTAHOREMISSAO,
        D.SEQUSUARIO,
        D.COO,
        'C' ORIGEMFATURA,
        'E' STATUS,
        PG.CODREDETEF CODOPERRECARGACEL,
        
        CASE
          WHEN PG.CODREDETEF = 52 THEN
               'T'
          WHEN PG.CODREDETEF = 269 THEN
               'B'     
          WHEN PG.CODREDETEF = 266 THEN
               'D'
          ELSE NULL
        END TIPOFATURA

 FROM  MONITORPDVMIDDLE.TB_DOCTO D,
       MONITORPDVMIDDLE.TB_DOCTOPAGTO PG
 WHERE  D.SEQDOCTO = PG.SEQDOCTO
 AND    D.NROEMPRESA = PG.NROEMPRESA
 AND    D.NROCHECKOUT = PG.NROCHECKOUT
 AND    D.REPLICACAO = 'P'
 AND    D.ESPECIE IN ('PL')
 GROUP BY 
        D.SEQDOCTO,
        D.NROEMPRESA,
        D.NROCHECKOUT,
        PG.NSUTEF,
        D.SEQUSUARIO,
        D.DTAHOREMISSAO,
        D.COO,
        PG.CODREDETEF 
)