CREATE OR REPLACE FUNCTION OBTERPRECOUTILIZADONFE( 
                                       P_CODIGO_FILIAL  VARCHAR2, 
                                       P_CODIGO_CLIENTE NUMBER, 
                                       P_CODIGO_PRODUTO NUMBER) 
 
  RETURN VARCHAR2 IS 
  V_PRODUTO_PRECOUTILIZADONFE PCPRODFILIAL.PRECOUTILIZADONFE%TYPE; 
  V_CLIENTE_PRECOUTILIZADONFE PCCLIENT.PRECOUTILIZADONFE%TYPE; 
 
BEGIN 
  BEGIN 
    SELECT PCPRODFILIAL.PRECOUTILIZADONFE 
      INTO V_PRODUTO_PRECOUTILIZADONFE 
      FROM PCPRODFILIAL 
     WHERE PCPRODFILIAL.CODPROD = P_CODIGO_PRODUTO 
       AND PCPRODFILIAL.CODFILIAL = P_CODIGO_FILIAL; 
  EXCEPTION 
     WHEN OTHERS THEN 
        V_PRODUTO_PRECOUTILIZADONFE := 'N'; 
  END; 
 
  IF ( NVL(V_PRODUTO_PRECOUTILIZADONFE,'N') = 'N' ) THEN 
 
    SELECT PCCLIENT.PRECOUTILIZADONFE 
    INTO V_CLIENTE_PRECOUTILIZADONFE 
    FROM PCCLIENT 
    WHERE PCCLIENT.CODCLI = P_CODIGO_CLIENTE; 
 
    IF ( NVL(V_CLIENTE_PRECOUTILIZADONFE,'N') = 'N' ) THEN 
       RETURN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PRECOUTILIZADONFE',P_CODIGO_FILIAL), 'L'); 
    ELSE 
       RETURN V_CLIENTE_PRECOUTILIZADONFE; 
    END IF; 
  ELSE 
     RETURN V_PRODUTO_PRECOUTILIZADONFE; 
  END IF; 
END; 