CREATE OR REPLACE TRIGGER TRG_LOG_PCTRIBPISCOFINSVIG
   BEFORE INSERT OR UPDATE OR DELETE
   ON PCTRIBPISCOFINSVIGENCIA
   REFERENCING OLD AS OLD NEW AS NEW
   FOR EACH ROW
DECLARE
   VSEQUIPAMENTO   VARCHAR2(64);
   VSUSUARIO       VARCHAR2(30);
   VSPROGRAMA      VARCHAR2(48);
   VSTIPO          VARCHAR2(20);

   PROCEDURE GERARLOG(PNOMECOLUNA VARCHAR2, POLDVALUE VARCHAR2, PNEWVALUE VARCHAR2)
   IS
   BEGIN
      IF NVL(POLDVALUE, 'X') <> NVL(PNEWVALUE, 'X')
      THEN
         INSERT INTO PCLOGALTERACAODADOS
                     (DATA
                    , TABELA
                    , COLUNA
                    , CODIGO
                    , OBSERVACOES
                    , PROGRAMA
                    , TERMINAL
                    , OSUSER
                    , VALORALFAANT
                    , VALORALFA
                    , OPERACAO
                    , OBSERVACOES2)
              VALUES (SYSDATE
                    , 'PCTRIBPISCOFINSVIGENCIA'
                    , PNOMECOLUNA
                    , DECODE(VSTIPO,'D',:OLD.CODTRIBPISCOFINS,:NEW.CODTRIBPISCOFINS)
                    , 'CODTRIBPISCOFINS-DTINICIO-DTFINAL: ' || :NEW.CODTRIBPISCOFINS || '-' || :NEW.DTINICIO|| '-' || :NEW.DTFINAL
                    , VSPROGRAMA
                    , VSEQUIPAMENTO
                    , VSUSUARIO
                    , POLDVALUE
                    , PNEWVALUE
                    , VSTIPO
                    , 'CODTRIBPISCOFINS-DTINICIO-DTFINAL: ' || :OLD.CODTRIBPISCOFINS || '-' || :OLD.DTINICIO|| '-' || :OLD.DTFINAL);
      END IF;
   END;
BEGIN
   VSEQUIPAMENTO              := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 64);
   VSUSUARIO                  := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 30);
   VSPROGRAMA                 := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 48);

   IF UPDATING
   THEN
      VSTIPO                     := 'U';
   ELSIF INSERTING
   THEN
      VSTIPO                     := 'I';
   ELSE
      VSTIPO                     := 'D';
   END IF;

   /*Gerar Log*/
    GERARLOG('CODTRIBPISCOFINS', TO_CHAR(:OLD.CODTRIBPISCOFINS), TO_CHAR(:NEW.CODTRIBPISCOFINS));
    GERARLOG('DESCRICAOTRIBPISCOFINS', TO_CHAR(:OLD.DESCRICAOTRIBPISCOFINS), TO_CHAR(:NEW.DESCRICAOTRIBPISCOFINS));
    GERARLOG('CONSIDERAVLFIXOLIT', TO_CHAR(:OLD.CONSIDERAVLFIXOLIT), TO_CHAR(:NEW.CONSIDERAVLFIXOLIT));
    GERARLOG('UTILIZAPERCPISCOFINSDIFCONS', TO_CHAR(:OLD.UTILIZAPERCPISCOFINSDIFCONS), TO_CHAR(:NEW.UTILIZAPERCPISCOFINSDIFCONS));
    GERARLOG('CONSIDERAPRECOMERC', TO_CHAR(:OLD.CONSIDERAPRECOMERC), TO_CHAR(:NEW.CONSIDERAPRECOMERC));
    GERARLOG('CONSIDERAPAUTA', TO_CHAR(:OLD.CONSIDERAPAUTA), TO_CHAR(:NEW.CONSIDERAPAUTA));
    GERARLOG('VLPAUTAPIS', TO_CHAR(:OLD.VLPAUTAPIS), TO_CHAR(:NEW.VLPAUTAPIS));
    GERARLOG('VLPAUTACOFINS', TO_CHAR(:OLD.VLPAUTACOFINS), TO_CHAR(:NEW.VLPAUTACOFINS));
    GERARLOG('CONSIDERAIPI', TO_CHAR(:OLD.CONSIDERAIPI), TO_CHAR(:NEW.CONSIDERAIPI));
    GERARLOG('CONSIDERAST', TO_CHAR(:OLD.CONSIDERAST), TO_CHAR(:NEW.CONSIDERAST));
    GERARLOG('CONSIDERAOUTRASDESP', TO_CHAR(:OLD.CONSIDERAOUTRASDESP), TO_CHAR(:NEW.CONSIDERAOUTRASDESP));
    GERARLOG('CONSIDERAFRETE', TO_CHAR(:OLD.CONSIDERAFRETE), TO_CHAR(:NEW.CONSIDERAFRETE));
    GERARLOG('CONSIDERASUFRAMA', TO_CHAR(:OLD.CONSIDERASUFRAMA), TO_CHAR(:NEW.CONSIDERASUFRAMA));
    GERARLOG('RETERPISCOFINS', TO_CHAR(:OLD.RETERPISCOFINS), TO_CHAR(:NEW.RETERPISCOFINS));
    GERARLOG('PERCPIS', TO_CHAR(:OLD.PERCPIS), TO_CHAR(:NEW.PERCPIS));
    GERARLOG('PERCCOFINS', TO_CHAR(:OLD.PERCCOFINS), TO_CHAR(:NEW.PERCCOFINS));
    GERARLOG('SITTRIBUT', TO_CHAR(:OLD.SITTRIBUT), TO_CHAR(:NEW.SITTRIBUT));
    GERARLOG('PERCPISCALCDI', TO_CHAR(:OLD.PERCPISCALCDI), TO_CHAR(:NEW.PERCPISCALCDI));
    GERARLOG('PERCCOFINSCALCDI', TO_CHAR(:OLD.PERCCOFINSCALCDI), TO_CHAR(:NEW.PERCCOFINSCALCDI));
    GERARLOG('BASEPISCOFINSLIT', TO_CHAR(:OLD.BASEPISCOFINSLIT), TO_CHAR(:NEW.BASEPISCOFINSLIT));
    GERARLOG('VLPISLIT', TO_CHAR(:OLD.VLPISLIT), TO_CHAR(:NEW.VLPISLIT));
    GERARLOG('VLCOFINSLIT', TO_CHAR(:OLD.VLCOFINSLIT), TO_CHAR(:NEW.VLCOFINSLIT));
    GERARLOG('MENSAGEMGERAL', TO_CHAR(:OLD.MENSAGEMGERAL), TO_CHAR(:NEW.MENSAGEMGERAL));
    GERARLOG('PERCPISCONSUMO', TO_CHAR(:OLD.PERCPISCONSUMO), TO_CHAR(:NEW.PERCPISCONSUMO));
    GERARLOG('PERCCOFINSCONSUMO', TO_CHAR(:OLD.PERCCOFINSCONSUMO), TO_CHAR(:NEW.PERCCOFINSCONSUMO));
    GERARLOG('SITTRIBUTCONSUMO', TO_CHAR(:OLD.SITTRIBUTCONSUMO), TO_CHAR(:NEW.SITTRIBUTCONSUMO));
    GERARLOG('MENSAGEMCONSUMO', TO_CHAR(:OLD.MENSAGEMCONSUMO), TO_CHAR(:NEW.MENSAGEMCONSUMO));
    GERARLOG('CONSIDERADIFALIQ', TO_CHAR(:OLD.CONSIDERADIFALIQ), TO_CHAR(:NEW.CONSIDERADIFALIQ));
    GERARLOG('DTINICIO', TO_CHAR(:OLD.DTINICIO), TO_CHAR(:NEW.DTINICIO));
    GERARLOG('DTFINAL', TO_CHAR(:OLD.DTFINAL), TO_CHAR(:NEW.DTFINAL));
    GERARLOG('ZERARBCCSTST', TO_CHAR(:OLD.ZERARBCCSTST), TO_CHAR(:NEW.ZERARBCCSTST));
END;