CREATE OR REPLACE VIEW VIEW_CONTAS_A_PAGAR AS
SELECT RECNUM, 
       CODCONTA,
       HISTORICO, 
       DUPLIC,
       DTVENC, 
       DTPAGTO, 
       NUMTRANS,
       NUMTRANSENT,
       VALOR, 
       VPAGO, 
       NUMBANCO, 
       NUMCHEQUE2, 
       NOMEFUNC, 
       DESCONTOFIN 
  FROM PCLANC
 WHERE VALOR > 0 
   AND (DTPAGTO IS NULL OR
       (DTPAGTO IS NOT NULL AND
       (PCLANC.NUMTRANS IS NOT NULL or
       NVL(PCLANC.HISTORICO2, 'X0XOXX0XXLXX') in
       ('PAGTO COM ADIANT. FORNEC', 'DESD. REF. ADIANT. FORNEC.'))))
   AND (PCLANC.CODCONTA NOT IN (SELECT NVL(CODCONTPAGJUR, 0) FROM PCCONSUM))
   AND (PCLANC.CODCONTA NOT IN (SELECT NVL(CODCONTANTPAG, 0) FROM PCCONSUM))
   AND (PCLANC.CODCONTA NOT IN
       (SELECT NVL(CODCONTACAMBIAL, 0) FROM PCCONSUM))
   AND PCLANC.DTESTORNOBAIXA IS NULL
   AND PCLANC.HISTORICO <> 'REF.CANCEL.BORDERO JA BAIXADO'
   AND PCLANC.HISTORICO <> 'REF.CANCEL.CHEQUE JA BAIXADO'
   AND NVL(PCLANC.CODROTINABAIXA, 0) NOT IN (737)