CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIO AS (
  SELECT 
    T.CODIGO_TRIBUTACAO SEQCENARIO,
    T.TIPO_IMPOSTO DESCRICAO,
    T.DESCRICAO_TRIBUTACAO ORIENTACAO,
    NVL(T.DTINICIO_VIGENCIA, SYSDATE) DTINICIALVALIDADE,
    NVL(T.DTFIM_VIGENCIA, SYSDATE + 1) DTFINALVALIDADE,
    0 TOTALPONTOS,
    T.STATUS
  FROM PCTRIBUTACAO T
  WHERE GREATES(NVL(T.DTULTALTER, DATAPADRAO.ULTIMAEXECUCAO),DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)