CREATE OR REPLACE VIEW VW_INT_C5_CCTCENARIO AS (
  SELECT 
    T.CODIGO_TRIBUTACAO SEQCENARIO,
    T.TIPO_IMPOSTO DESCRICAO,
    T.DESCRICAO_TRIBUTACAO ORIENTACAO,
    NVL(T.DTINICIO_VIGENCIA, SYSDATE) DTINICIALVALIDADE,
    NVL(T.DTFIM_VIGENCIA, SYSDATE + 1) DTFINALVALIDADE,
    0 TOTALPONTOS,
    T.STATUS
  FROM PCTRIBUTACAO T,
       (SELECT S.ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
         WHERE UPPER(S.OBJETOREFERENCIA) =
               'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CCTCENARIO') D
  WHERE NVL(T.DTULTALTER, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
)