CREATE OR REPLACE VIEW VW_INT_C5_CATEGORIA AS
(
 SELECT DISTINCT
       (SELECT R.NRODIVISAO
        FROM   PCDEPARAREGIAOC5 R
        WHERE  R.NUMREGIAO = REGPARAOVAREJO.VALOR
       )NRODIVISAO,
       
       --REGPARAOVAREJO.VALOR  NRODIVISAO,
       to_number(DADOSCLASSIFIC.SEQCATEGORIA) SEQCATEGORIA,
       DADOSCLASSIFIC.SEQCATEGORIAPAI,
       'M' TIPO,
       DADOSCLASSIFIC.NIVELHIERARQUIA,
       DADOSCLASSIFIC.CATEGORIA,
       DADOSCLASSIFIC.ATIVO,
       'N' LERPESO,
       IDREF

FROM
 (SELECT ora_hash(0||CODEPTO||1, 2147483647) SEQCATEGORIA,
         NULL SEQCATEGORIAPAI,
         1 NIVELHIERARQUIA,
         SUBSTR(UPPER(DESCRICAO), 0, 25) CATEGORIA,
         'S' ATIVO,
         CODEPTO IDREF,
         DTALTERC5

  FROM PCDEPTO,
       (SELECT S.ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CATEGORIA') DATAPADRAO

  WHERE NVL(DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
------------------
UNION ALL
  SELECT 
       --A.CODEPTO||1||B.CODSEC||2 SEQCATEGORIA,
       ora_hash(B.CODSEC||2, 2147483647) SEQCATEGORIA,
       A.CODEPTO||1 SEQCATEGORIAPAI,
       2 NIVELHIERARQUIA,
       SUBSTR(UPPER(B.DESCRICAO), 0, 25) CATEGORIA,
       'S' ATIVO,
       B.CODSEC IDREF,
       B.DTALTERC5
  FROM PCSECAO B,
       PCDEPTO A,
       (SELECT S.ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CATEGORIA') DATAPADRAO
  WHERE A.CODEPTO = B.CODEPTO
  AND   NVL(B.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
------------------
UNION ALL
  SELECT 
       --A.CODEPTO||1||B.CODSEC||2||C.CODCATEGORIA||3 SEQCATEGORIA,
       --A.CODEPTO||1||B.CODSEC||2 SEQCATEGORIAPAI,
       ora_hash(B.CODSEC||C.CODCATEGORIA||3, 2147483647) SEQCATEGORIA,
       B.CODSEC||2 SEQCATEGORIAPAI,
       3 NIVELHIERARQUIA,
       SUBSTR(UPPER(C.CATEGORIA),0,25) CATEGORIA,
       'S' ATIVO,
       C.CODCATEGORIA IDREF,
       C.DTALTERC5
  FROM PCCATEGORIA C,
       PCSECAO B,
       PCDEPTO A,
       (SELECT S.ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
         WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CATEGORIA') DATAPADRAO
  WHERE A.CODEPTO = B.CODEPTO
  AND B.CODSEC = C.CODSEC
  AND NVL(C.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
-----------------------
UNION ALL
  SELECT 
       --A.CODEPTO||1||B.CODSEC||2||C.CODCATEGORIA||3||D.CODSUBCATEGORIA||4 SEQCATEGORIA,
       --A.CODEPTO||1||B.CODSEC||2||C.CODCATEGORIA||3 SEQCATEGORIAPAI,
       ora_hash(B.CODSEC||C.CODCATEGORIA||D.CODSUBCATEGORIA||4, 2147483647) SEQCATEGORIA,
       C.CODCATEGORIA||3 SEQCATEGORIAPAI,
       4 NIVELHIERARQUIA,
       SUBSTR(UPPER(D.SUBCATEGORIA), 0, 25) CATEGORIA,
       'S' ATIVO,
       D.CODSUBCATEGORIA IDREF,
       D.DTALTERC5
  FROM PCSUBCATEGORIA D,
       PCCATEGORIA C,
       PCSECAO B,
       PCDEPTO A,
       (SELECT S.ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
         WHERE UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CATEGORIA') DATAPADRAO
  WHERE A.CODEPTO = B.CODEPTO
  AND B.CODSEC = C.CODSEC
  AND C.CODCATEGORIA = D.CODCATEGORIA
  AND D.CODSEC = B.CODSEC
  AND NVL(D.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
  ) DADOSCLASSIFIC,

  (SELECT DISTINCT PCPARAMFILIAL.VALOR
   FROM PCPARAMFILIAL
   WHERE NOME = 'NUMREGIAOPADRAOVAREJO'
   AND VALOR <> '99'
   AND REGEXP_LIKE(CODFILIAL, '^[[:digit:]]+$')
  ) REGPARAOVAREJO

WHERE REGPARAOVAREJO.VALOR IS NOT NULL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_FAMDIVISAOCATEGORIA AS
(SELECT
    VW_INT_C5_CATEGORIA.NRODIVISAO,
    VW_INT_C5_FAMILIA.SEQFAMILIA,
    VW_INT_C5_CATEGORIA.SEQCATEGORIA,
    'S' ATIVO,
    
    /*Caseo seja necessário identificar no winthor a categoria atribuida
      no produto(CODPROD) do lado da Consinco, o IDREF receberá a hierarquia
      concatenado com a categoria(departamento /seção/categoria/subcategoria
    )*/
    (CASE
      WHEN VW_INT_C5_CATEGORIA.NIVELHIERARQUIA = 4 THEN
           VW_INT_C5_CATEGORIA.NIVELHIERARQUIA||PRODCATEGORIA.CODSUBCATEGORIA
      WHEN VW_INT_C5_CATEGORIA.NIVELHIERARQUIA = 3 THEN
           VW_INT_C5_CATEGORIA.NIVELHIERARQUIA||PRODCATEGORIA.CODCATEGORIA
      WHEN VW_INT_C5_CATEGORIA.NIVELHIERARQUIA = 2 THEN
           VW_INT_C5_CATEGORIA.NIVELHIERARQUIA||PRODCATEGORIA.CODSEC
      ELSE VW_INT_C5_CATEGORIA.NIVELHIERARQUIA||PRODCATEGORIA.CODEPTO
    END) IDREF 

 FROM VW_INT_C5_CATEGORIA,
      VW_INT_C5_FAMILIA,
      (SELECT
         CODPROD,
         CODEPTO,
         CODSEC,
         CODCATEGORIA,
         CODSUBCATEGORIA,
         (CASE
            WHEN CODSUBCATEGORIA IS NOT NULL THEN
                 ora_hash(CODSEC||CODCATEGORIA||CODSUBCATEGORIA||4, 2147483647)
            WHEN CODCATEGORIA IS NOT NULL THEN
                 ora_hash(CODSEC||CODCATEGORIA||3, 2147483647)
            WHEN CODSEC IS NOT NULL THEN
                 ora_hash(CODSEC||2, 2147483647)
            ELSE 
                 ora_hash(CODEPTO||1, 2147483647)
         END) SEQCATEGORIA

       FROM PCPRODUT
       WHERE ((CODEPTO IS NOT NULL) AND (CODSEC IS NOT NULL) AND (CODCATEGORIA IS NOT NULL) AND (CODSUBCATEGORIA IS NOT NULL)) --SUBCATEGORIA
          OR ((CODEPTO IS NOT NULL) AND (CODSEC IS NOT NULL) AND (CODCATEGORIA IS NOT NULL) AND (CODSUBCATEGORIA IS NULL)) -- CATEGORIA
          OR ((CODEPTO IS NOT NULL) AND (CODSEC IS NOT NULL) AND (CODCATEGORIA IS NULL) AND (CODSUBCATEGORIA IS NULL)) --SECAO
          OR (CODEPTO IS NOT NULL) --DEPARTAMENTO
        )PRODCATEGORIA
 WHERE PRODCATEGORIA.CODPROD = VW_INT_C5_FAMILIA.SEQFAMILIA
 AND   PRODCATEGORIA.SEQCATEGORIA =  VW_INT_C5_CATEGORIA.SEQCATEGORIA
)