CREATE OR REPLACE FUNCTION LISTA_DE_STRINGS(LISTA IN VARCHAR2)
   RETURN TABELA_STRING IS
   TABELA_STRINGS TABELA_STRING;
   TEXTO          VARCHAR2(50);
   L_CURSOR       SYS_REFCURSOR;
BEGIN
   TABELA_STRINGS := TABELA_STRING();

   OPEN L_CURSOR FOR 'SELECT ''' || REPLACE(LISTA,
                                          ',',
                                          ''' FROM DUAL UNION SELECT ''') || ''' FROM DUAL';

   LOOP
      FETCH L_CURSOR
         INTO TEXTO;

      EXIT WHEN L_CURSOR%NOTFOUND;
      TABELA_STRINGS.EXTEND;
      TABELA_STRINGS(TABELA_STRINGS.COUNT) := ARRAY_STRING(VALOR => TEXTO);
   END LOOP;

   CLOSE L_CURSOR;

   RETURN TABELA_STRINGS;
END; 