declare 
  V_EXISTE_TABELA NUMBER DEFAULT 0;
  V_EXISTE_SEQUENCE NUMBER DEFAULT 0;
begin
   SELECT COUNT(*)
     INTO V_EXISTE_TABELA
     FROM USER_TABLES
   WHERE table_name = 'PCTABPR_PROGRAMADA';
   
  SELECT COUNT(*) 
    INTO V_EXISTE_SEQUENCE
    FROM USER_SEQUENCES 
   WHERE SEQUENCE_NAME = 'DFSEQ_PCTABPR_PROGRAMADA';
   
  IF V_EXISTE_TABELA > 0 AND V_EXISTE_SEQUENCE = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE DFSEQ_PCTABPR_PROGRAMADA START WITH 1 INCREMENT BY 1';    
  END IF;   

  V_EXISTE_TABELA := 0;
  V_EXISTE_SEQUENCE := 0;

   SELECT COUNT(*)
     INTO V_EXISTE_TABELA
     FROM USER_TABLES
   WHERE table_name = 'PCPRODUT_PROGRAMADA';
   
  SELECT COUNT(*) 
    INTO V_EXISTE_SEQUENCE
    FROM USER_SEQUENCES 
   WHERE SEQUENCE_NAME = 'DFSEQ_PCPRODUT_PROGRAMADA';
   
  IF V_EXISTE_TABELA > 0 AND V_EXISTE_SEQUENCE = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE DFSEQ_PCPRODUT_PROGRAMADA START WITH 1 INCREMENT BY 1';    
  END IF;
   
end;
