BEGIN
	UPDATE PCDICIONARIO
	   SET PCDICIONARIO.DESCRICAO = 'Marca'
	 WHERE PCDICIONARIO.NOMEOBJETO = 'PCMARCA';

	UPDATE PCDICIONARIOITEM
	   SET PCDICIONARIOITEM.AUTOGERAR          = 'S',
		   PCDICIONARIOITEM.FORMULAAUTOGERACAO = 'MAIOR(PCMARCA.CODMARCA)'
	 WHERE PCDICIONARIOITEM.NOMEOBJETO = 'PCMARCA'
	   AND PCDICIONARIOITEM.NOMECAMPO = 'CODMARCA';
END;