BEGIN

DELETE FROM PCINTEGRAECOMMERCE_LAYOUTI WHERE CODLAYOUT IN (1, 2);

DELETE FROM PCINTEGRAECOMMERCE_LAYOUTC WHERE CODLAYOUT IN (1, 2);

  
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTC (CODLAYOUT, DESCRICAO) VALUES (1, 'Ifood Tabela de preço');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTC (CODLAYOUT, DESCRICAO) VALUES (2, 'Ifood Preço por embalagem');

INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CREDENCIAIS', 'CODIGO_AUTENTICACAO', 'Código de autenticação', 'VARCHAR2', 'S', 3, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CREDENCIAIS', 'ID_LOJA', 'Id da Loja no IFood', 'VARCHAR2', NULL, 4, 'N');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'NUMREGIAOENVIO', 'Região padrão de preços', 'NUMBER', NULL, 1, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'COLUNAPRECOENVIO', 'Coluna padrão de preços', 'NUMBER', NULL, 2, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'ACRESCIMO_PRECO', 'Acréscimo no preço', 'NUMBER', NULL, 3, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CREDENCIAIS', 'CODIGO_AUTENTICACAO', 'Código de autenticação', 'VARCHAR2', 'S', 3, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CREDENCIAIS', 'ID_LOJA', 'Id da Loja no IFood', 'VARCHAR2', NULL, 4, 'N');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CONFIGURACOES', 'ACRESCIMO_PRECO', 'Acréscimo no preço', 'NUMBER', NULL, 1, NULL);

COMMIT;

END;
