BEGIN

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTC T
USING (SELECT 1 AS CODLAYOUT, 'iFood - Tabela de Preço' AS DESCRICAO FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, DESCRICAO) VALUES (S.CODLAYOUT, S.DESCRICAO);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTC T
USING (SELECT 2 AS CODLAYOUT, 'iFood - Preço por Embalagem' AS DESCRICAO FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, DESCRICAO) VALUES (S.CODLAYOUT, S.DESCRICAO);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CREDENCIAIS' AS TIPO, 'AUTHORIZATION_CODE' AS CAMPO, 'Código de autenticação' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 1 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CREDENCIAIS' AS TIPO, 'AUTHORIZATION_CODE_VERIFIER' AS CAMPO, 'Verificador do código de autenticação' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 2 AS ORDEMEXIBICAO, 'N' AS EDITAVEL, 'N' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'NUMREGIAOENVIO' AS CAMPO, 'Região padrão de preços' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 3 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'COLUNAPRECOENVIO' AS CAMPO, 'Coluna padrão de preços' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 4 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODCLI_PADRAO' AS CAMPO, 'Código de cliente padrão' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 5 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODCOB_PADRAO' AS CAMPO, 'Cobrança padrão' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 6 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODPLPAG_PADRAO' AS CAMPO, 'Plano de pagamento padrão' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 7 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODUSUR_PADRAO' AS CAMPO, 'RCA padrão' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 8 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'ACRESCIMO_PRECO' AS CAMPO, 'Acréscimo no preço' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'N' AS OBRIGATORIO, 9 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'MINDIASESTOQUE' AS CAMPO, 'Quantidade mínima de dias de estoque' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 10 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'RESET_CATALOGO' AS CAMPO, 'Parâmetro que permite o reset de catálogo no envio de itens' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'N' AS OBRIGATORIO, 11 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'N' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 1 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CONSIDERAESTOQUEPRODMASTER' AS CAMPO, 'Considerar o estoque do produto master no produto filho' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'N' AS OBRIGATORIO, 12 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CREDENCIAIS' AS TIPO, 'AUTHORIZATION_CODE' AS CAMPO, 'Código de autenticação' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 1 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CREDENCIAIS' AS TIPO, 'AUTHORIZATION_CODE_VERIFIER' AS CAMPO, 'Verificador do código de autenticação' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 2 AS ORDEMEXIBICAO, 'N' AS EDITAVEL, 'N' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'ACRESCIMO_PRECO' AS CAMPO, 'Acréscimo no preço' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'N' AS OBRIGATORIO, 3 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'MINDIASESTOQUE' AS CAMPO, 'Quantidade mínima de dias de estoque' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 4 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODCLI_PADRAO' AS CAMPO, 'Código de cliente padrão' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 5 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODCOB_PADRAO' AS CAMPO, 'Cobrança padrão' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 6 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODPLPAG_PADRAO' AS CAMPO, 'Plano de pagamento padrão' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 7 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CODUSUR_PADRAO' AS CAMPO, 'RCA padrão' AS DESCRICAO, 'NUMBER' AS TIPOCAMPO, 'S' AS OBRIGATORIO, 8 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'RESET_CATALOGO' AS CAMPO, 'Parâmetro que permite o reset de catálogo no envio de itens' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'N' AS OBRIGATORIO, 9 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'N' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

MERGE INTO PCINTEGRAECOMMERCE_LAYOUTI T
USING (SELECT 2 AS CODLAYOUT, 'CONFIGURACOES' AS TIPO, 'CONSIDERAESTOQUEPRODMASTER' AS CAMPO, 'Considerar o estoque do produto master no produto filho' AS DESCRICAO, 'VARCHAR2' AS TIPOCAMPO, 'N' AS OBRIGATORIO, 10 AS ORDEMEXIBICAO, 'S' AS EDITAVEL, 'S' AS VISIVEL FROM DUAL) S
ON (T.CODLAYOUT = S.CODLAYOUT AND T.TIPO = S.TIPO AND T.CAMPO = S.CAMPO)
WHEN MATCHED THEN UPDATE SET T.DESCRICAO = S.DESCRICAO, T.TIPOCAMPO = S.TIPOCAMPO, T.OBRIGATORIO = S.OBRIGATORIO, T.ORDEMEXIBICAO = S.ORDEMEXIBICAO, T.EDITAVEL = S.EDITAVEL, T.VISIVEL = S.VISIVEL
WHEN NOT MATCHED THEN INSERT (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL, VISIVEL) VALUES (S.CODLAYOUT, S.TIPO, S.CAMPO, S.DESCRICAO, S.TIPOCAMPO, S.OBRIGATORIO, S.ORDEMEXIBICAO, S.EDITAVEL, S.VISIVEL);

COMMIT;

END;