BEGIN

DELETE FROM PCINTEGRAECOMMERCE_LAYOUTI WHERE CODLAYOUT IN (1, 2);

DELETE FROM PCINTEGRAECOMMERCE_LAYOUTC WHERE CODLAYOUT IN (1, 2);

  
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTC (CODLAYOUT, DESCRICAO) VALUES (1, 'Ifood Tabela de preço');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTC (CODLAYOUT, DESCRICAO) VALUES (2, 'Ifood Preço por embalagem');

INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CREDENCIAIS', 'AUTHORIZATION_CODE', 'Código de autenticação', 'VARCHAR2', 'S', 1, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CREDENCIAIS', 'AUTHORIZATION_CODE_VERIFIER', 'Código de autenticação', 'VARCHAR2', 'S', 2, 'N');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'NUMREGIAOENVIO', 'Região padrão de preços', 'NUMBER', NULL, 3, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'COLUNAPRECOENVIO', 'Coluna padrão de preços', 'NUMBER', NULL, 4, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'ACRESCIMO_PRECO', 'Acréscimo no preço', 'NUMBER', NULL, 5, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'MINDIASESTOQUE', 'Minimo dias Estoque', 'NUMBER', NULL, 6, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (1, 'CONFIGURACOES', 'RESET_CATALOGO', 'Parâmetro que permite o reset de cataogo o envio de itens', 'VARCHAR2', NULL, 7, 'S');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CREDENCIAIS', 'AUTHORIZATION_CODE', 'Código de autenticação', 'VARCHAR2', 'S', 1, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CREDENCIAIS', 'AUTHORIZATION_CODE_VERIFIER', 'Código de autenticação', 'VARCHAR2', 'S', 2, 'N');
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CONFIGURACOES', 'ACRESCIMO_PRECO', 'Acréscimo no preço', 'NUMBER', NULL, 3, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CONFIGURACOES', 'MINDIASESTOQUE', 'Minimo dias Estoque', 'NUMBER', NULL, 4, NULL);
INSERT INTO PCINTEGRAECOMMERCE_LAYOUTI (CODLAYOUT, TIPO, CAMPO, DESCRICAO, TIPOCAMPO, OBRIGATORIO, ORDEMEXIBICAO, EDITAVEL) VALUES (2, 'CONFIGURACOES', 'RESET_CATALOGO', 'Parâmetro que permite o reset de cataogo o envio de itens', 'VARCHAR2', NULL, 5, 'S');

COMMIT;

END;
