CREATE OR REPLACE VIEW VW_INT_C5_PLPAG AS
(
SELECT P.CODPLPAG NROCONDICAOPAGTO,
       SUBSTR(P.DESCRICAO,1,40) CONDICAOPAGTO,
       NVL(P.PERTXFIM,0) PERCACRESCIMO,
       (CASE
            WHEN P.FORMAPARCELAMENTO = 'T' 
              THEN P.NUMEROPARCELASDIAFIXO
            WHEN P.FORMAPARCELAMENTO = 'V' 
              THEN P.NUMPARCELAS
            ELSE
              0
        END) NROMAXIMOPARCELA,
       P.NUMDIAS NRODIASVENCTO,
       (CASE
            WHEN NVL(P.STATUS,'A') = 'A'
              THEN 'S'
            WHEN NVL(P.USAPLPAGAUTOSERVICO,'N') = 'S'
              THEN 'S'
            ELSE
             'N'
        END) ATIVO
  FROM PCPLPAG P
  WHERE (NVL(P.STATUS,'A') = 'A' 
         AND NVL(P.USAPLPAGAUTOSERVICO,'N') = 'S')
);
