DECLARE
  EXISTE_COLUNA NUMBER;
  nomeCampo VARCHAR2(50) := 'CONFIGURACAOERP';
BEGIN

    BEGIN
      SELECT count(1)
        INTO EXISTE_COLUNA
        FROM user_tab_cols
       WHERE table_name = 'PCINTEGRACAODADOSEMPRESA'
         and column_name = nomeCampo;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        EXISTE_COLUNA := 0;
    END;
  
    IF nomeCampo = 'CONFIGURACAOERP' AND EXISTE_COLUNA = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PCINTEGRACAODADOSEMPRESA ADD CONFIGURACAOERP CLOB';
    END IF;
  
END;