CREATE OR REPLACE FUNCTION VALIDAR_NOSSO_NUMERO (P_NUMTRANSVENDA        NUMBER,   -- NUMTRANSVENDA DO TÍTULO
                                                 P_DUPLIC               NUMBER,   -- NUMERO DA NOTA DO TÍTULO
                                                 P_PREST                VARCHAR2, -- PRESTAÇÃO/PARCELA DO TÍTULO
                                                 P_CODBANCOCM           VARCHAR2, -- BANCO QUE GEROU OS DADOS BANCÁRIOS
                                                 P_NOSSONUMEROBCOATUAL  VARCHAR2  -- NOSSO NÚMERO ATUAL  
) RETURN VARCHAR2 IS
    -- VARIÁVEIS PARA DE VALIDAÇÃO
    V_NUMERO_AGENCIA                VARCHAR2(4);   -- CÓDIGO DA COOPERATIVA/AGÊNCIA BENEFICIÁRIA
    V_POSTO_CARTEIRA3               VARCHAR2(2);   -- POSTO DO BENEFICIÁRIO
    V_POSTO_CARTEIRA                VARCHAR2(2);   -- POSTO DO BENEFICIÁRIO
    V_CODIGO_CODIGOCEDENTE          VARCHAR2(5);   -- CÓDIGO DO BENEFICIÁRIO
    V_ANO_ATUAL                     VARCHAR2(2);   -- ANO ATUAL EM DOIS DÍGITOS
    V_INDICADOR_NUMCARTEIRA         VARCHAR2(1);   -- INDICADOR DE GERAÇÃO DO NOSSO NÚMERO
    V_SEQUENCIAL                    VARCHAR2(5);   -- NÚMERO SEQUENCIAL DO BENEFICIÁRIO
    V_DV_INFORMADO                  VARCHAR(1);    -- DÍGITO VERIFICADOR INFORMADO PARA VALIDAÇÃO
    V_NUMBANCO                      NUMBER;        -- NUMERO DO BANCO (BACEN)
    -- VARIÁVEIS PARA O PROCESSAMENTO
    V_SEQUENCIA                     VARCHAR2(20);
    V_SOMA_PRODUTOS                 NUMBER := 0;
    V_DV_CALCULADO                  VARCHAR(1);
    V_RESTO                         NUMBER;
    V_PESO                          NUMBER := 2;
    
BEGIN
   -- CONSULTA PARA OBTER DADOS DA TABELA PCBANCO
   SELECT LPAD(B.AGENCIA,4,'0')            AGENCIA,
          LPAD(B.NUMCARTEIRA3,2,'0')       CARTEIRA3,
          LPAD(B.NUMCARTEIRA,2,'0')        CARTEIRA,
          LPAD(B.CODCLIENTENOBANCO,5,'0')  CODIGO_CEDENTE,
          TO_CHAR(SYSDATE, 'YY'),
          LPAD(B.NUMCARTEIRA,1,'0')        NUMCARTEIRA,
          B.NUMBANCO
     INTO V_NUMERO_AGENCIA,
          V_POSTO_CARTEIRA3,
          V_POSTO_CARTEIRA,
          V_CODIGO_CODIGOCEDENTE,
          V_ANO_ATUAL,
          V_INDICADOR_NUMCARTEIRA,
          V_NUMBANCO
     FROM PCBANCO B
    WHERE B.CODBANCO = P_CODBANCOCM;
     
    
   IF P_NOSSONUMEROBCOATUAL IS NOT NULL THEN      
      -- BANCO SAFRA 422
      IF V_NUMBANCO = 422 THEN
         V_DV_INFORMADO := (SUBSTR(P_NOSSONUMEROBCOATUAL, LENGTH(P_NOSSONUMEROBCOATUAL), 1));
         V_SEQUENCIAL   := SUBSTR(P_NOSSONUMEROBCOATUAL,4,5);          
        
         V_SEQUENCIA    := LPAD(P_NOSSONUMEROBCOATUAL,8,'0');

         FOR I IN REVERSE 1 .. LENGTH(V_SEQUENCIA) LOOP
            V_SOMA_PRODUTOS := V_SOMA_PRODUTOS + (SUBSTR(V_SEQUENCIA, I, 1)) * V_PESO;

            -- AJUSTA O PESO PARA O PRÓXIMO DÍGITO (CICLO DE 2 A 7)
            V_PESO := CASE WHEN V_PESO < 10 THEN V_PESO + 1 ELSE 2 END;
         END LOOP;                         

         V_RESTO := MOD(V_SOMA_PRODUTOS, 11);  
        
         IF V_RESTO = 0 THEN
            V_DV_CALCULADO := '1';
         ELSIF V_RESTO = 1 THEN
            V_DV_CALCULADO := '0';
         ELSE
            V_DV_CALCULADO := 11 - V_RESTO;
         END IF;      
      END IF;-- FIM BANCO 422
      
        -- BANCO BRADESCO 237
      IF V_NUMBANCO = 237 THEN
         V_DV_INFORMADO := (SUBSTR(P_NOSSONUMEROBCOATUAL, LENGTH(P_NOSSONUMEROBCOATUAL), 1));
         V_SEQUENCIAL   := SUBSTR(P_NOSSONUMEROBCOATUAL,4,5);
          
         V_SEQUENCIA    := V_POSTO_CARTEIRA ||LPAD(P_NOSSONUMEROBCOATUAL,11,'0');
                         
         DBMS_OUTPUT.PUT_LINE(V_SEQUENCIA);
          
         FOR I IN REVERSE 1 .. LENGTH(V_SEQUENCIA) LOOP
            V_SOMA_PRODUTOS := V_SOMA_PRODUTOS + (SUBSTR(V_SEQUENCIA, I, 1)) * V_PESO;

            -- AJUSTA O PESO PARA O PRÓXIMO DÍGITO (CICLO DE 2 A 7)
            V_PESO := CASE WHEN V_PESO < 7 THEN V_PESO + 1 ELSE 2 END;
         END LOOP;
          
         V_RESTO := MOD(V_SOMA_PRODUTOS, 11);

         -- PASSO 4: CALCULAR O DV ESPERADO    
         IF V_RESTO = 1 THEN
            V_DV_CALCULADO := 'P';
         ELSIF V_RESTO = 0 THEN
            V_DV_CALCULADO := '0';
         ELSE          
            V_DV_CALCULADO := 11 - V_RESTO;
         END IF;
      END IF;
    
      -- BANCO SICREDI 748
      IF V_NUMBANCO = 748 THEN
         -- OBTER O DV INFORMADO DIRETAMENTE DO NOSSO NÚMERO ATUAL (OU DA TABELA PCPREST)
         V_DV_INFORMADO := (SUBSTR(P_NOSSONUMEROBCOATUAL, LENGTH(P_NOSSONUMEROBCOATUAL), 1));
         V_SEQUENCIAL := SUBSTR(P_NOSSONUMEROBCOATUAL,4,5);

         DBMS_OUTPUT.PUT_LINE(V_DV_INFORMADO); --4

         -- PASSO 1: CONCATENAR A SEQUÊNCIA COMPLETA COM OS VALORES FORNECIDOS
         V_SEQUENCIA := LPAD(V_NUMERO_AGENCIA, 4, '0')      || 
                        LPAD(V_POSTO_CARTEIRA3, 2, '0')     || 
                        LPAD(V_CODIGO_CODIGOCEDENTE, 5, '0')|| 
                        LPAD(V_ANO_ATUAL, 2, '0')           || 
                        V_INDICADOR_NUMCARTEIRA             || 
                        LPAD(V_SEQUENCIAL, 5, '0');
            
            DBMS_OUTPUT.PUT_LINE(V_SEQUENCIA);
            -- PASSO 2: MULTIPLICAR CADA DÍGITO DA SEQUÊNCIA PELO PESO CORRESPONDENTE, DA DIREITA PARA A ESQUERDA
         FOR I IN REVERSE 1 .. LENGTH(V_SEQUENCIA) LOOP
            V_SOMA_PRODUTOS := V_SOMA_PRODUTOS + (SUBSTR(V_SEQUENCIA, I, 1)) * V_PESO;

            -- AJUSTA O PESO PARA O PRÓXIMO DÍGITO (CICLO DE 2 A 9)
            V_PESO := CASE WHEN V_PESO < 9 THEN V_PESO + 1 ELSE 2 END;
         END LOOP;

         -- PASSO 3: CALCULAR O RESTO DA DIVISÃO DA SOMA PELO MÓDULO 11
         V_RESTO := MOD(V_SOMA_PRODUTOS, 11);

         -- PASSO 4: CALCULAR O DV ESPERADO
         IF V_RESTO IN (0, 1) THEN
            V_DV_CALCULADO := 0;
         ELSE
            V_DV_CALCULADO := 11 - V_RESTO;
         END IF;
      END IF;      
   END IF;

   DBMS_OUTPUT.PUT_LINE(V_DV_CALCULADO);
   -- PASSO 5: COMPARAR O DV CALCULADO COM O DV INFORMADO E RETORNAR A MENSAGEM APROPRIADA       
   IF V_NUMBANCO IN (237,748,422) THEN 
      IF V_DV_CALCULADO = V_DV_INFORMADO THEN
         RETURN NULL;
      ELSE
         RETURN V_DV_CALCULADO;
      END IF;
   ELSE
      RETURN NULL; 
   END IF;
   
END VALIDAR_NOSSO_NUMERO;