CREATE OR REPLACE VIEW SQL_NFE_CABECALHO_SAIDA AS
SELECT PCNFSAID.NUMTRANSVENDA AS NUM_TRANSACAO
        ,PCNFSAID.CHAVENFE
        ,NVL(PCNFSAID.NUMVIAS,
             0) + 1 AS NUM_IMPRESSAO
        ,1 AS MOVIMENTO
        ,NVL(PCNFSAID.TIPOEMISSAO,
             '0') AS TIPO_EMISSAO
        ,PCFILIAL.CODIGO AS CODIGO_FILIAL
        ,NVL(PCNFSAID.RECIBODPEC,
             PCNFSAID.PROTOCOLONFE) AS PROTOCOLONFE
        ,NVL(PCNFSAID.DTHORARECIBODPEC,
             NVL(PCNFSAID.DTHORAAUTORIZACAOSEFAZ,
                 PCNFSAID.DTHORANFE)) AS DTHORA_AUTORIZACAO
        ,DECODE(NVL(PCNFSAID.TIPOIMPRESSAO, NVL(PCFILIAL.TIPODANFE,'R')),
                'R',
                '1',
                '2') AS TIPO_DANFE
        ,DECODE(PCNFSAID.TIPOVENDA,
                'VV',
                0,
                'VP',
                1,
                2) TIPO_PGTO
        ,REPLACE(TRANSLATE(PCNFSAID.SERIE,
                           TRIM(TRANSLATE(PCNFSAID.SERIE,
                                          '1234567890',
                                          ' ')) || ' ',
                           ' '),
                 ' ',
                 '') SERIE
        ,NVL(PCFILIAL.SERIENFESCAN,
             '0') AS SERIE_SCAN
        ,PCNFSAID.DTSAIDA AS DATA_EMISSAO
        ,PCNFSAID.DTSAIDANF AS DATA_SAIDA_DANFE
        ,PCNFSAID.NUMNOTA AS NUMERO_NOTA
        ,(SELECT PCDEVFORNEC.NUMTRANSENT
          FROM   PCDEVFORNEC
          WHERE  PCDEVFORNEC.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
          AND    ROWNUM = 1) NUM_TRANSACAO_DEV
        ,PCNFSAID.NUMTRANSVENDAORIGEM AS NUM_TRANSACAO_ORIG
        --Alteração solicitada pelo Ricardinho
        ,CASE
           WHEN (PCNFSAID.FINALIDADENFE = 'A') THEN
            DECODE(NVL(PCNFSAID.NATOPERNFE, ''),
                   '',
                   NVL(NVL((SELECT PCCFO.DESCCFO
                             FROM PCCFO
                            WHERE PCCFO.CODFISCAL =
                                  (SELECT MIN(CODFISCAL)
                                     FROM PCMOV
                                    WHERE PCMOV.NUMTRANSVENDA =
                                          PCNFSAID.NUMTRANSVENDA)),
                           (SELECT PCCFO.DESCCFO
                              FROM PCCFO
                             WHERE PCCFO.CODFISCAL =
                                   (SELECT MIN(CODFISCAL)
                                      FROM PCMOVCIAP
                                     WHERE PCMOVCIAP.NUMTRANSVENDA =
                                           PCNFSAID.NUMTRANSVENDA))),
                       (SELECT MIN(PCCFO.DESCCFO)
                          FROM PCCFO, PCNFBASE
                         WHERE PCNFBASE.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
                           AND PCNFBASE.CODFISCAL = PCCFO.CODFISCAL)),
                   NATOPERNFE)
           ELSE
            --Melhoria HIS.02791.2016 - Eddy
            DECODE(NVL(PCNFSAID.PAGCHEQUEMORADIA, 'N'),'S',
                   'VENDA COM CHEQUE MORADIA',
                   NVL(NVL((SELECT PCCFO.DESCCFO
                              FROM PCCFO
                             WHERE PCCFO.CODFISCAL =
                                   (SELECT MIN(CODFISCAL)
                                      FROM PCMOV
                                     WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA)),
                            (SELECT PCCFO.DESCCFO
                               FROM PCCFO
                              WHERE PCCFO.CODFISCAL =
                                    (SELECT MIN(CODFISCAL)
                                       FROM PCMOVCIAP
                                      WHERE PCMOVCIAP.NUMTRANSVENDA =
                                            PCNFSAID.NUMTRANSVENDA))),
                        (SELECT MIN(PCCFO.DESCCFO)
                           FROM PCCFO, PCNFBASE
                          WHERE PCNFBASE.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
                            AND PCNFBASE.CODFISCAL = PCCFO.CODFISCAL)))
         END AS NATUREZA_OP
        ,NVL((SELECT MIN(CODFISCAL)
              FROM PCMOV
              WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA),
             (SELECT MIN(CODFISCAL)
              FROM   PCNFBASE
              WHERE  PCNFBASE.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA)) AS CODIGO_FISCAL
         ------------------------------------------------------INCIO IDENTIFICAO DO EMITENTE-----------------------------------------------------------
         -----------------------EMITENTE-----------------------
        ,EMITENTE.CGC AS CNPJ_E
        ,EMITENTE.FORNECEDOR AS RAZAO_SOCIAL_E
        ,EMITENTE.FANTASIA AS NOME_FANTASIA_E
        ,EMITENTE.ENDER AS LOGRADOURO_E
        ,NVL(EMITENTE.NUMEROEND,
             'S\N') AS NUMERO_E
        ,EMITENTE.COMPLEMENTOEND AS COMPLEMENTO_E
        ,EMITENTE.BAIRRO AS BAIRRO_E
        ,NVL(CIDADE_E.CODIBGE,
             0) AS CODIGO_MUNICIPIO_E
        ,CIDADE_E.NOMECIDADE AS NOME_MUNICIPIO_E
        ,UF_E.UF AS SIGLA_UF_E
        ,NVL(PAIS_E.CODPAIS,
             0) AS CODIGO_PAIS_E
        ,PAIS_E.DESCRICAO AS PAIS_E
        ,EMITENTE.CEP AS CEP_E
        ,EMITENTE.TELFAB AS TELEFONE_E
        ,EMITENTE.IE AS INSCRICAO_ESTADUAL_E
        ,NVL((SELECT PCINSCRICAOST.IESUBSTTRIBUT
             FROM   PCINSCRICAOST
             WHERE  PCINSCRICAOST.CODFILIAL = PCFILIAL.CODIGO
             AND    PCINSCRICAOST.UF = DECODE(NVL(PCINSCRICAOST.VINCULOPORENDENT, 'N'), 'S', ENT.ESTENT, UF_D.UF)
             AND    ROWNUM = 1),
             UF_D.IESUBSTTRIBUT) AS INSCRICAO_SUBSTITUTO_E
        ,EMITENTE.INSCMUNICIP AS INSCRICAO_MUNICIPAL_E
        ,EMITENTE.CAE AS CNAE_E
        ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('FIL_OPTANTESIMPLESNAC',
                                                  PCFILIAL.CODIGO),
                    'N'),
                'N',
                3,
                'S',
                1,
                'E',
                2,
                3) CRT
         -----------------------DESTINATRIO-----------------------
        ,CASE WHEN (PCNFSAID.UF = 'EX') THEN '' ELSE PCNFSAID.CGC END AS CNPJ_CPF_D
        ,CASE WHEN (NVL(PCNFSAID.AMBIENTENFE,
                        PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE',
                                                      PCFILIAL.CODIGO)) = 'P') THEN PCNFSAID.CLIENTE
             ELSE CASE WHEN (NVL(PCNFSAID.AMBIENTENFE,
                                 PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE',
                                                      PCFILIAL.CODIGO)) = 'H' AND PCNFSAID.DTSAIDA >= TO_DATE('01-05-2011', 'DD-MM-YYYY'))
                                                      THEN 'NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL'
         ELSE PCNFSAID.CLIENTE
           END
         END AS RAZAO_SOCIAL_D
        ,CLIENTE.FANTASIA AS NOME_FANTASIA_D
        ,PCNFSAID.ENDERECO AS LOGRADOURO_D
        ,NVL(PCNFSAID.NUMENDERECO,
                    'S\N') AS NUMERO_D
        ,NVL(CLIENTE.COMPLEMENTOENT,
                '') AS COMPLEMENTO_D
        ,PCNFSAID.BAIRRO AS BAIRRO_D
        ,PCNFSAID.CODIBGE AS CODIGO_MUNICIPIO_D
        ,CASE WHEN (NVL(PCPEDC.VENDALOCESTRANG, 'N') = 'S') THEN
                  'EXTERIOR'
             ELSE
                  CIDADE_D.NOMECIDADE
         END AS NOME_MUNICIPIO_D
        ,CASE WHEN (NVL(PCPEDC.VENDALOCESTRANG, 'N') = 'S') THEN
                  'EX'
             ELSE
                  PCNFSAID.UF
         END AS SIGLA_UF_D
        ,PCNFSAID.CEP AS CEP_D
        ,PCNFSAID.CODPAIS AS CODIGO_PAIS_D
        ,PCNFSAID.DESCPAIS AS PAIS_D
        ,PCNFSAID.TELEFONE AS TELEFONE_D
        ,CASE WHEN (PCNFSAID.UF = 'EX') THEN '' ELSE
              CASE WHEN (PCNFSAID.CONTRIBUINTE = 'N' AND UPPER(PCNFSAID.IE) LIKE '%ISENT%')
                   THEN '' ELSE PCNFSAID.IE
               END
         END AS INSCRICAO_ESTADUAL_D
        ,PCNFSAID.EMAILDEST AS EMAIL_D
        ,CLIENTE.SULFRAMA AS INSCRICAO_SUFRAMA_D
        ----------------------------------------------------------
        -------------------------ENTREGA--------------------------
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN PCVENDACONSUM.CGCENT ELSE NVL(CLIENTE.CGCENTREGA, NVL(PCNFSAID.CGC, CLIENTE.CGCENT)) END) AS CNPJ_CPF_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.ENDERENT ELSE NVL(ENT.ENDERENT, CLIENTE.ENDERCOM) END) AS LOGRADOURO_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.NUMEROENT ELSE DECODE(NVL(ENT.NUMEROENT, ''), '', NVL(CLIENTE.NUMEROCOM,'S\N'), ENT.NUMEROENT) END) AS NUMERO_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.COMPLEMENTOENT ELSE DECODE(NVL(ENT.COMPLEMENTOENT, ''), '', NVL(CLIENTE.COMPLEMENTOCOM,''), ENT.COMPLEMENTOENT) END) AS COMPLEMENTO_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.BAIRROENT ELSE NVL(ENT.BAIRROENT, CLIENTE.BAIRROCOM) END) AS BAIRRO_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN CIDADE_ENT.CODIBGE ELSE NVL(CID_ENT.CODIBGE, CIDADE_ENT.CODIBGE) END) AS CODIGO_MUNICIPIO_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN SUBSTR(ENT.MUNICENT,1,60) ELSE SUBSTR(NVL(ENT.MUNICENT, CIDADE_ENT.NOMECIDADE),1,60) END) AS NOME_MUNICIPIO_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.ESTENT ELSE NVL(ENT.ESTENT, CIDADE_ENT.UF) END) AS SIGLA_UF_ENT
        ---novos campos
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN CAST(ENT.CEPRECEBEDOR as varchar2(9)) ELSE NVL(CAST(NVL(ENT.CEPRECEBEDOR, ENT.CEPENT) as varchar2(9)), REPLACE(CLIENTE.CEPCOM, '-','')) END) AS CEP_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.IERECEBEDOR ELSE NVL(ENT.IERECEBEDOR, CLIENTE.IERECEBEDORENDENT) END) AS INSCRICAO_ESTADUAL_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.FONERECEBEDOR ELSE NVL(ENT.FONERECEBEDOR, CLIENTE.FONERECEBEDORENDENT) END) AS TELEFONE_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.CODPAISRECEBEDOR ELSE NVL(ENT.CODPAISRECEBEDOR, CLIENTE.CODPAISRECEBEDORENDENT) END) AS CODIGO_PAIS_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.RAZAORECEBEDOR ELSE NVL(ENT.RAZAORECEBEDOR, CLIENTE.RAZAORECEBEDORENDENT) END) AS RAZAO_SOCIAL_REC_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN ENT.EMAILRECEBEDOR ELSE NVL(ENT.EMAILRECEBEDOR, CLIENTE.EMAILRECEBEDORENDENT) END) AS EMAIL_ENT
        ,(CASE WHEN NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI) IN ('1', '2', '3') THEN PAIS_ENT.DESCRICAO ELSE NVL(PAIS_ENT.DESCRICAO, CLIENTE.PAISENT) END) AS PAIS_ENT
        ----------------------------------------------------------
        ,NVL(CLIENTE.TIPOEMPRESA, FERRAMENTAS.VERIFICAR_FJ(CLIENTE.CODCLI)) AS TIPO_EMPRESA
        ,PCNFSAID.NUMNOTA AS NUM_DOC_IMPORTACAO
        ,PCNFSAID.LOCALDESEMBARACO AS LOCAL_DESEMBARACO
        ,PCNFSAID.UFDESEMBARACO AS SIGLA_UF_DESEMBARACO
        ,PCNFSAID.DTSAIDA AS DATA_DESEMBARACO
        ,PCNFSAID.CODEXPORTADOR AS CODIGO_EXPORTADOR
        ,PCNFSAID.CODFORNEC AS CODIGO_FABRICANTE_EX
        ,NVL(PCNFSAID.CONDVENDA,
             0) AS CONDVENDA
        ,CASE
           WHEN NVL(CLIENTE.TIPOCLIMED,
                    'X') IN ('D',
                             'E',
                             'M')
                AND (NVL(PCPEDC.ROTINA,
                         'X') = 'PCMED316') THEN
            'S'
           ELSE
            'N'
         END ORGAO_PUBLICO
        ,PCFILIAL.CODDOCNF AS CODDOC
        ,NVL(PCNFSAID.CODCLINF,
             PCNFSAID.CODCLI) AS CODIGO_CLI
        ,PCNFSAID.DTSAIDA AS DATA_SAIDA
        ,CASE WHEN NVL(PCNFSAID.FINALIDADENFE, 'N') = 'A' THEN
             NULL --Nota de ajuste não pode ter data de saída de entrega preenchida
         ELSE
             DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ENVIARDATAENTREGAXML',
                                                    PCFILIAL.CODIGO),
                      'S'),
                  'S',
                  NVL(PCNFSAID.DTENTREGA, PCNFSAID.DTSAIDANF), NULL)
         END AS DATA_ENTREGA
        ,EMITENTE.EMAIL AS EMAIL_E
        ,(EMITENTE.ENDER || ' - ' || NVL(EMITENTE.NUMEROEND,
                                         'S/N') || ' - ' || EMITENTE.BAIRRO ||
         ' - ' || CIDADE_E.NOMECIDADE || ' - ' || UF_E.UF || ' - ' ||
         EMITENTE.CEP) AS ENDERECO
        ,PCNFSAID.ESPECIE
        ,EMITENTE.FAXFAB AS FAX_E
          ,TO_CHAR(TO_DATE((NVL(TRIM(PCNFSAID.HORALANC),0) || ':' || NVL(TRIM(PCNFSAID.MINUTOLANC),0)), 'HH24:MI'), 'HH24:MI') AS HORA
            ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ENVIARDATAENTREGAXML',
                                                    PCFILIAL.CODIGO),
                      'S'),
                  'S',
                       TO_CHAR(TO_DATE((NVL(TO_CHAR(PCNFSAID.HORASAIDA), NVL(PCNFSAID.HORALANC,0)) || ':' || NVL(TO_CHAR(PCNFSAID.MINUTOSAIDA), NVL(PCNFSAID.MINUTOLANC,0))), 'HH24:MI'), 'HH24:MI')
             ) AS HORASAIDA
        ,PCNFSAID.NUMPED AS NUM_PEDIDO
        ,PCPEDC.NUMPEDCLI AS NUM_PEDIDO_CLI
        ,PCNFSAID.NUMCAR AS NUMERO_CAR
        ,PCNFSAID.CODUSUR AS RCA
        ,PCNFSAID.CODCOB AS TIPO_COBRANCA
        ,DECODE(CLIENTE.CODCLI,
                1,
                'F',
                2,
                'F',
                3,
                'F',
                CLIENTE.TIPOFJ) AS TIPO_PESSOA
        ,NULL AS TIPODESCARGA
        ,PCNFSAID.CODCONT
        ,DECODE(NVL(PCNFSAID.AMBIENTENFE,
                    'X'),
                'H',
                2,
                'P',
                1,
                -1) AS AMBIENTE
        ,NVL(PCNFSAID.SITUACAONFE,
             0) AS SITUACAONFE
        ,CASE WHEN (NVL(PCPEDC.VENDALOCESTRANG, 'N') = 'S') THEN
                   'S'
              ELSE
                   NVL(CLIENTE.CONSUMIDORFINAL, 'N')
         END AS CONSUMIDOR_FINAL
        ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('SERIALCERTIFICADO',
                                           PCFILIAL.CODIGO),
             '') AS SERIALCERTIFICADO
        ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PINCERTIFICADO',
                                           PCFILIAL.CODIGO),
             '') AS PINCERTIFICADO
        ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PROVIDERCERTIFICADOA3',
                                           PCFILIAL.CODIGO),
             'SafeSign Standard Cryptographic Service Provider') AS PROVIDERCERTIFICADOA3
        ,NVL(PARAMFILIAL.OBTERCOMONUMBER('TIPOPROVIDERA3',
                                         PCFILIAL.CODIGO),
             1) AS TIPOPROVIDERA3
        ,CASE
           WHEN ((SELECT CODPROD
                  FROM   PCMOV
                  WHERE  PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
                  AND    ROWNUM = 1
                  UNION
                  SELECT CODPROD
                  FROM   PCMOVCIAP
                  WHERE  PCMOVCIAP.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
                  AND    ROWNUM = 1) IS NULL)
                AND (PCNFSAID.NUMTRANSVENDAORIGEM > 0 AND PCNFSAID.FINALIDADENFE <> 'A')  OR PCNFSAID.FINALIDADENFE = 'C' THEN
            2
           ELSE CASE WHEN
                PCNFSAID.FINALIDADENFE = 'A'
           THEN
            3
            ELSE
            1
            END
         END AS FINALIDADE
        ,PCNFSAID.DTAHORAENTRADACONTIGENCIA AS DTHORA_CONTINGENCIA
        ,PCNFSAID.JUSTIFICATIVACONTIGENCIA AS JUSTIFICATIVA
        ,CARREG.DESTINO AS DESTINOCARGA
        ,TO_NUMBER(SUBSTR(TO_CHAR(NVL(PCPEDC.NUMPEDRCA,0)),1,10)) AS NUMPEDRCA
        ,'' AS MOT_ESTORNONFE
        ,PCNFSAID.NUMTRANSENTORIGEM
        ,PCNFSAID.SITUACAONFEEPEC AS SITUACAO_NFE_EPEC
        ,PCNFSAID.NUMTRANSENTORIGCONSIG
        ,NVL(PCNFSAID.TIPOPRESENCAADQUIRINTE,TO_CHAR(CASE WHEN PCNFSAID.CONDVENDA = 7 THEN 3
                                                     ELSE
                                                       CASE PCPEDC.ORIGEMPED
                                                       WHEN 'B' THEN 1
                                                       WHEN 'R' THEN 1
                                                       WHEN 'W' THEN 2
                                                       WHEN 'T' THEN 3
                                                       WHEN 'F' THEN 9
                                                       ELSE
                                                          (CASE WHEN PCNFSAID.FINALIDADENFE IN ('A', 'C') THEN 0 ELSE 1 END)
                                                       END
                                                   END)
         ) AS INDICADOR_PRESENCA
        ,PCNFSAID.TIPOVENDA
        ,PCPEDC.INTEGRADORA
        ,NVL(PCNFSAID.CONTRIBUINTE, CLIENTE.CONTRIBUINTE) CONTRIBUINTE
        ,NVL(PCNFSAID.QTDEREPROCNFE, 0) AS QTD_REPROCESSAMENTO_NFE
        ,PCNFSAID.UIDREGISTRO
        ,PCNFSAID.IDPARCEIRO
        ,PCNFSAID.ASSINATURA
        ,PCPEDC.DATA DATA_PEDIDO
        ,PCNFSAID.CODCOBSEFAZ
        ,PCNFSAID.DATACONSOLIDACAOPREFAT
        ,'N' PREFATURAMENTO
        ,PCPEDC.NUMEMPENHO AS NUMEMPENHO
        ,PCNFSAID.USASRVTERCEIROS AS UTILIZASRVTERCEIROS
        ,'N' AS ENVIADASEMRESPOSTA
        ,CLIENTE.IDENTIFICESTRANG AS IDESTRANGEIRO
        --VALIDAÇÃO PARA NOTAS EMITIDAS NO FORÇA DE VENDAS, EM CONTINGÊNCIA, NESTE CASO O SERVIDOR NFE NÃO PODE MUDAR A CHAVE DA NOTA
        ,CASE
           WHEN NVL(PCNFSAID.CONDVENDA,0) = 14 THEN
            CASE
              WHEN ((SELECT COUNT(*)
                       FROM PCPEDCFVMANIF
                      WHERE PCPEDC.NUMPEDRCA = PCPEDCFVMANIF.NUMPEDRCA
                        AND PCPEDC.CODUSUR = PCPEDCFVMANIF.CODUSUR
                        AND PCPEDCFVMANIF.IMPORTADO = 2) > 0) AND
                   (PCPEDC.TIPOEMISSAO <> 1) AND
                   (PCPEDC.CHAVENFE IS NOT NULL) THEN
               'S'
              ELSE
               'N'
            END
           ELSE
            'N'
         END AS CHAVEGERADATV14
        ,PCPEDC.CHAVENFE AS CHAVENFETV14
        ,PCNFSAID.CODIGONUMERICOCHAVE AS CODIGO_NUMERICO_CHAVE
        ,PCNFSAID.DESCINTERMEDIADOR
        ,PCNFSAID.CNPJINTERMEDIADOR
  FROM   PCNFSAID
        ,PCFORNEC EMITENTE
        ,PCESTADO UF_E
        ,PCPAIS PAIS_E
        ,PCCIDADE CIDADE_E
        ,PCFILIAL
        ,PCPEDC
        ,PCCLIENT CLIENTE
        ,PCESTADO UF_D
        ,PCPAIS PAIS_D
        ,PCCIDADE CIDADE_D
        ,PCCIDADE CIDADE_ENT
        ,PCCARREG CARREG
        ,PCPEDC PD
        ,PCCLIENTENDENT ENT
        ,PCCIDADE CID_ENT
        ,PCPAIS PAIS_ENT
        ,PCVENDACONSUM
  WHERE  NVL(PCNFSAID.CODFILIALNF, PCNFSAID.CODFILIAL) = PCFILIAL.CODIGO
  AND    PCFILIAL.CODFORNEC = EMITENTE.CODFORNEC(+)
  AND    CARREG.NUMCAR(+) = PCNFSAID.NUMCAR
  AND    PD.NUMTRANSVENDA(+) = PCNFSAID.NUMTRANSVENDA
  AND    ENT.CODENDENTCLI(+) =  NVL(PD.CODENDENTCLI, PD.CODENDENT)
  AND    ENT.CODCLI(+) =  PD.CODCLI
  AND    CID_ENT.CODCIDADE(+) = ENT.CODCIDADE
  AND    CIDADE_ENT.CODCIDADE(+) = CLIENTE.CODCIDADECOM
  AND    ((NVL(PCFILIAL.UTILIZANFE, 'N') = 'S') OR
          (NVL(PCNFSAID.USASRVTERCEIROS, NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZASRVTERCEIROS', PCFILIAL.CODIGO), 'N')) = 'S'))
  AND    PCNFSAID.DTCANCEL IS NULL
  AND    PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
  AND    PCNFSAID.NUMPED = PCVENDACONSUM.NUMPED(+)
  AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE(+)
  AND    CIDADE_E.UF = UF_E.UF(+)
  AND    UF_E.CODPAIS = PAIS_E.CODPAIS(+)
  AND    UF_D.CODPAIS = PAIS_D.CODPAIS(+)
  AND    CLIENTE.CODCLI(+) = NVL(PCNFSAID.CODCLINF, PCNFSAID.CODCLI)
  AND    PCNFSAID.CODMUNICIPIO = CIDADE_D.CODCIDADE(+)
  AND    CIDADE_D.UF = UF_D.UF(+)
  AND    ENT.CODPAISRECEBEDOR = PAIS_ENT.CODPAIS(+)
  --Linhas abaixo sevem para obedecer a ordem de numeração das notas fiscais no processo de Adjudicação
  AND    ( (nvl(PCNFSAID.NUMTRANSENTDEPENDENTE,-1) = -1)  OR EXISTS (SELECT 1 FROM PCNFENT E WHERE E.NUMTRANSENT = PCNFSAID.NUMTRANSENTDEPENDENTE AND E.SITUACAONFE IN (100,101)))
  AND    (( nvl(PCNFSAID.NUMTRANSVENDADEPENDENTE,-1) = -1) OR (EXISTS (SELECT 1 FROM PCNFSAID S WHERE S.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDADEPENDENTE AND S.SITUACAONFE IN (100,101))))
  AND    NVL(PCNFSAID.DOCEMISSAO, 'X') NOT IN ('CE','SF', 'MF', 'CF')
  --Add para melhorar a performance da impressão do Danfe
  AND PCNFSAID.DTSAIDA >= (SELECT MIN(DTSAIDA) FROM PCNFSAID)

  union all
  SELECT PCNFSAIDPREFAT.NUMTRANSVENDA AS NUM_TRANSACAO
        ,PCNFSAIDPREFAT.CHAVENFE
        ,NVL(PCNFSAIDPREFAT.NUMVIAS,
             0) + 1 AS NUM_IMPRESSAO
        ,1 AS MOVIMENTO
        ,NVL(PCNFSAIDPREFAT.TIPOEMISSAO,
             '0') AS TIPO_EMISSAO
        ,PCFILIAL.CODIGO AS CODIGO_FILIAL
        ,NVL(PCNFSAIDPREFAT.RECIBODPEC,
             PCNFSAIDPREFAT.PROTOCOLONFE) AS PROTOCOLONFE
        ,NVL(PCNFSAIDPREFAT.DTHORARECIBODPEC,
             NVL(PCNFSAIDPREFAT.DTHORAAUTORIZACAOSEFAZ,
                 PCNFSAIDPREFAT.DTHORANFE)) AS DTHORA_AUTORIZACAO
        ,DECODE(NVL(PCNFSAIDPREFAT.TIPOIMPRESSAO, NVL(PCFILIAL.TIPODANFE, 'R')),
                'R',
                '1',
                '2') AS TIPO_DANFE
        ,DECODE(PCNFSAIDPREFAT.TIPOVENDA,
                'VV',
                0,
                'VP',
                1,
                2) TIPO_PGTO
        ,REPLACE(TRANSLATE(PCNFSAIDPREFAT.SERIE,
                           TRIM(TRANSLATE(PCNFSAIDPREFAT.SERIE,
                                          '1234567890',
                                          ' ')) || ' ',
                           ' '),
                 ' ',
                 '') SERIE
        ,NVL(PCFILIAL.SERIENFESCAN,
             '0') AS SERIE_SCAN
        ,PCNFSAIDPREFAT.DTSAIDA AS DATA_EMISSAO
        ,PCNFSAIDPREFAT.DTSAIDANF AS DATA_SAIDA_DANFE
        ,PCNFSAIDPREFAT.NUMNOTA AS NUMERO_NOTA
        ,(SELECT PCDEVFORNEC.NUMTRANSENT
          FROM   PCDEVFORNEC
          WHERE  PCDEVFORNEC.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA
          AND    ROWNUM = 1) NUM_TRANSACAO_DEV
        ,PCNFSAIDPREFAT.NUMTRANSVENDAORIGEM AS NUM_TRANSACAO_ORIG
        --Alteração solicitada pelo Ricardinho
        ,CASE
           WHEN (PCNFSAIDPREFAT.FINALIDADENFE = 'A') THEN
            DECODE(NVL(PCNFSAIDPREFAT.NATOPERNFE, ''),
                   '',
                   NVL(NVL((SELECT PCCFO.DESCCFO
                             FROM PCCFO
                            WHERE PCCFO.CODFISCAL =
                                  (SELECT MIN(CODFISCAL)
                                     FROM PCMOVPREFAT
                                    WHERE PCMOVPREFAT.NUMTRANSVENDA =
                                          PCNFSAIDPREFAT.NUMTRANSVENDA)),
                           (SELECT PCCFO.DESCCFO
                              FROM PCCFO
                             WHERE PCCFO.CODFISCAL =
                                   (SELECT MIN(CODFISCAL)
                                      FROM PCMOVCIAP
                                     WHERE PCMOVCIAP.NUMTRANSVENDA =
                                           PCNFSAIDPREFAT.NUMTRANSVENDA))),
                       (SELECT MIN(PCCFO.DESCCFO)
                          FROM PCCFO, PCNFBASE
                         WHERE PCNFBASE.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA
                           AND PCNFBASE.CODFISCAL = PCCFO.CODFISCAL)),
                   NATOPERNFE)
           ELSE
            --Melhoria HIS.02791.2016 - Eddy
            DECODE(NVL(PCNFSAIDPREFAT.PAGCHEQUEMORADIA, 'N'),'S',
                   'VENDA COM CHEQUE MORADIA',
                   NVL(NVL((SELECT PCCFO.DESCCFO
                              FROM PCCFO
                             WHERE PCCFO.CODFISCAL =
                                   (SELECT MIN(CODFISCAL)
                                      FROM PCMOVPREFAT
                                     WHERE PCMOVPREFAT.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA)),
                            (SELECT PCCFO.DESCCFO
                               FROM PCCFO
                              WHERE PCCFO.CODFISCAL =
                                    (SELECT MIN(CODFISCAL)
                                       FROM PCMOVCIAP
                                      WHERE PCMOVCIAP.NUMTRANSVENDA =
                                            PCNFSAIDPREFAT.NUMTRANSVENDA))),
                        (SELECT MIN(PCCFO.DESCCFO)
                           FROM PCCFO, PCNFBASE
                          WHERE PCNFBASE.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA
                            AND PCNFBASE.CODFISCAL = PCCFO.CODFISCAL)))
         END AS NATUREZA_OP
        ,NVL((SELECT MIN(CODFISCAL)
              FROM PCMOVPREFAT
              WHERE PCMOVPREFAT.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA),
             (SELECT MIN(CODFISCAL)
              FROM   PCNFBASE
              WHERE  PCNFBASE.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA)) AS CODIGO_FISCAL
         ------------------------------------------------------INCIO IDENTIFICAO DO EMITENTE-----------------------------------------------------------
         -----------------------EMITENTE-----------------------
        ,EMITENTE.CGC AS CNPJ_E
        ,EMITENTE.FORNECEDOR AS RAZAO_SOCIAL_E
        ,EMITENTE.FANTASIA AS NOME_FANTASIA_E
        ,EMITENTE.ENDER AS LOGRADOURO_E
        ,NVL(EMITENTE.NUMEROEND,
             'S\N') AS NUMERO_E
        ,EMITENTE.COMPLEMENTOEND AS COMPLEMENTO_E
        ,EMITENTE.BAIRRO AS BAIRRO_E
        ,NVL(CIDADE_E.CODIBGE,
             0) AS CODIGO_MUNICIPIO_E
        ,CIDADE_E.NOMECIDADE AS NOME_MUNICIPIO_E
        ,UF_E.UF AS SIGLA_UF_E
        ,NVL(PAIS_E.CODPAIS,
             0) AS CODIGO_PAIS_E
        ,PAIS_E.DESCRICAO AS PAIS_E
        ,EMITENTE.CEP AS CEP_E
        ,EMITENTE.TELFAB AS TELEFONE_E
        ,EMITENTE.IE AS INSCRICAO_ESTADUAL_E
        ,NVL((SELECT PCINSCRICAOST.IESUBSTTRIBUT
             FROM   PCINSCRICAOST
             WHERE  PCINSCRICAOST.CODFILIAL = PCFILIAL.CODIGO
             AND    PCINSCRICAOST.UF = DECODE(NVL(PCINSCRICAOST.VINCULOPORENDENT, 'N'), 'S', ENT.ESTENT, UF_D.UF)
             AND    ROWNUM = 1),
             UF_D.IESUBSTTRIBUT) AS INSCRICAO_SUBSTITUTO_E
        ,EMITENTE.INSCMUNICIP AS INSCRICAO_MUNICIPAL_E
        ,EMITENTE.CAE AS CNAE_E
        ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('FIL_OPTANTESIMPLESNAC',
                                                  PCFILIAL.CODIGO),
                    'N'),
                'N',
                3,
                'S',
                1,
                'E',
                2,
                3) CRT
         -----------------------DESTINATRIO-----------------------
        ,CASE WHEN (PCNFSAIDPREFAT.UF = 'EX') THEN '' ELSE PCNFSAIDPREFAT.CGC END AS CNPJ_CPF_D
        ,CASE WHEN (NVL(PCNFSAIDPREFAT.AMBIENTENFE,
                        PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE',
                                                      PCFILIAL.CODIGO)) = 'P') THEN PCNFSAIDPREFAT.CLIENTE
             ELSE CASE WHEN (NVL(PCNFSAIDPREFAT.AMBIENTENFE,
                                 PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE',
                                                      PCFILIAL.CODIGO)) = 'H' AND PCNFSAIDPREFAT.DTSAIDA >= TO_DATE('01-05-2011', 'DD-MM-YYYY'))
                                                      THEN 'NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL'
         ELSE PCNFSAIDPREFAT.CLIENTE
           END
         END AS RAZAO_SOCIAL_D
        ,CLIENTE.FANTASIA AS NOME_FANTASIA_D
        ,PCNFSAIDPREFAT.ENDERECO AS LOGRADOURO_D
        ,NVL(PCNFSAIDPREFAT.NUMENDERECO,
                    'S\N') AS NUMERO_D
        ,NVL(CLIENTE.COMPLEMENTOENT,
                '') AS COMPLEMENTO_D
        ,PCNFSAIDPREFAT.BAIRRO AS BAIRRO_D
        ,PCNFSAIDPREFAT.CODIBGE AS CODIGO_MUNICIPIO_D
        ,CASE WHEN (NVL(PCPEDC.VENDALOCESTRANG, 'N') = 'S') THEN
                  'EXTERIOR'
             ELSE
                  CIDADE_D.NOMECIDADE
         END AS NOME_MUNICIPIO_D
        ,CASE WHEN (NVL(PCPEDC.VENDALOCESTRANG, 'N') = 'S') THEN
                  'EX'
             ELSE
                  PCNFSAIDPREFAT.UF
         END AS SIGLA_UF_D
        ,PCNFSAIDPREFAT.CEP AS CEP_D
        ,PCNFSAIDPREFAT.CODPAIS AS CODIGO_PAIS_D
        ,PCNFSAIDPREFAT.DESCPAIS AS PAIS_D
        ,PCNFSAIDPREFAT.TELEFONE AS TELEFONE_D
        ,CASE WHEN (PCNFSAIDPREFAT.UF = 'EX') THEN '' ELSE
              CASE WHEN (PCNFSAIDPREFAT.CONTRIBUINTE = 'N' AND UPPER(PCNFSAIDPREFAT.IE) LIKE '%ISENT%')
                   THEN '' ELSE PCNFSAIDPREFAT.IE
               END
         END AS INSCRICAO_ESTADUAL_D
        ,PCNFSAIDPREFAT.EMAILDEST AS EMAIL_D
        ,CLIENTE.SULFRAMA AS INSCRICAO_SUFRAMA_D
        ----------------------------------------------------------
        -------------------------ENTREGA--------------------------
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN PCVENDACONSUM.CGCENT ELSE NVL(CLIENTE.CGCENTREGA, NVL(PCNFSAIDPREFAT.CGC, CLIENTE.CGCENT)) END) AS CNPJ_CPF_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.ENDERENT ELSE NVL(ENT.ENDERENT, CLIENTE.ENDERCOM) END) AS LOGRADOURO_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.NUMEROENT ELSE DECODE(NVL(ENT.NUMEROENT, ''), '', NVL(CLIENTE.NUMEROCOM,'S\N'), ENT.NUMEROENT) END) AS NUMERO_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.COMPLEMENTOENT ELSE DECODE(NVL(ENT.COMPLEMENTOENT, ''), '', NVL(CLIENTE.COMPLEMENTOCOM,''), ENT.COMPLEMENTOENT) END) AS COMPLEMENTO_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.BAIRROENT ELSE NVL(ENT.BAIRROENT, CLIENTE.BAIRROCOM) END) AS BAIRRO_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN CIDADE_ENT.CODIBGE ELSE NVL(CID_ENT.CODIBGE, CIDADE_ENT.CODIBGE) END) AS CODIGO_MUNICIPIO_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN SUBSTR(ENT.MUNICENT,1,60) ELSE SUBSTR(NVL(ENT.MUNICENT, CIDADE_ENT.NOMECIDADE),1,60) END) AS NOME_MUNICIPIO_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.ESTENT ELSE NVL(ENT.ESTENT, CIDADE_ENT.UF) END) AS SIGLA_UF_ENT
        ---novos campos
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN CAST(ENT.CEPRECEBEDOR as varchar2(9)) ELSE NVL(CAST(ENT.CEPRECEBEDOR as varchar2(9)), REPLACE(CLIENTE.CEPCOM, '-','')) END)  AS CEP_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.IERECEBEDOR ELSE NVL(ENT.IERECEBEDOR, CLIENTE.IERECEBEDORENDENT) END) AS INSCRICAO_ESTADUAL_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.FONERECEBEDOR ELSE NVL(ENT.FONERECEBEDOR, CLIENTE.FONERECEBEDORENDENT) END) AS TELEFONE_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.CODPAISRECEBEDOR ELSE NVL(ENT.CODPAISRECEBEDOR, CLIENTE.CODPAISRECEBEDORENDENT) END) AS CODIGO_PAIS_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.RAZAORECEBEDOR ELSE NVL(ENT.RAZAORECEBEDOR, CLIENTE.RAZAORECEBEDORENDENT) END) AS RAZAO_SOCIAL_REC_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN ENT.EMAILRECEBEDOR ELSE NVL(ENT.EMAILRECEBEDOR, CLIENTE.EMAILRECEBEDORENDENT) END) AS EMAIL_ENT
        ,(CASE WHEN NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI) IN ('1', '2', '3') THEN PAIS_ENT.DESCRICAO ELSE NVL(PAIS_ENT.DESCRICAO, CLIENTE.PAISENT) END) AS PAIS_ENT
        ----------------------------------------------------------
        ,NVL(CLIENTE.TIPOEMPRESA, FERRAMENTAS.VERIFICAR_FJ(CLIENTE.CODCLI)) AS TIPO_EMPRESA
        ,PCNFSAIDPREFAT.NUMNOTA AS NUM_DOC_IMPORTACAO
        ,PCNFSAIDPREFAT.LOCALDESEMBARACO AS LOCAL_DESEMBARACO
        ,PCNFSAIDPREFAT.UFDESEMBARACO AS SIGLA_UF_DESEMBARACO
        ,PCNFSAIDPREFAT.DTSAIDA AS DATA_DESEMBARACO
        ,PCNFSAIDPREFAT.CODEXPORTADOR AS CODIGO_EXPORTADOR
        ,PCNFSAIDPREFAT.CODFORNEC AS CODIGO_FABRICANTE_EX
        ,NVL(PCNFSAIDPREFAT.CONDVENDA,
             0) AS CONDVENDA
        ,CASE
           WHEN NVL(CLIENTE.TIPOCLIMED,
                    'X') IN ('D',
                             'E',
                             'M')
                AND (NVL(PCPEDC.ROTINA,
                         'X') = 'PCMED316') THEN
            'S'
           ELSE
            'N'
         END ORGAO_PUBLICO
        ,PCFILIAL.CODDOCNF AS CODDOC
        ,NVL(PCNFSAIDPREFAT.CODCLINF,
             PCNFSAIDPREFAT.CODCLI) AS CODIGO_CLI
        ,PCNFSAIDPREFAT.DTSAIDA AS DATA_SAIDA
        ,CASE WHEN NVL(PCNFSAIDPREFAT.FINALIDADENFE, 'N') = 'A' THEN
             NULL --Nota de ajuste não pode ter data de saída de entrega preenchida
         ELSE
             DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ENVIARDATAENTREGAXML',
                                                PCFILIAL.CODIGO),
                  'S'),
              'S',
              NVL(PCNFSAIDPREFAT.DTENTREGA, PCNFSAIDPREFAT.DTSAIDANF), NULL)
         END AS DATA_ENTREGA
        ,EMITENTE.EMAIL AS EMAIL_E
        ,(EMITENTE.ENDER || ' - ' || NVL(EMITENTE.NUMEROEND,
                                         'S/N') || ' - ' || EMITENTE.BAIRRO ||
         ' - ' || CIDADE_E.NOMECIDADE || ' - ' || UF_E.UF || ' - ' ||
         EMITENTE.CEP) AS ENDERECO
        ,PCNFSAIDPREFAT.ESPECIE
        ,EMITENTE.FAXFAB AS FAX_E
          ,TO_CHAR(TO_DATE((NVL(PCNFSAIDPREFAT.HORALANC,0) || ':' || NVL(PCNFSAIDPREFAT.MINUTOLANC,0)), 'HH24:MI'), 'HH24:MI') AS HORA
            ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ENVIARDATAENTREGAXML',
                                                    PCFILIAL.CODIGO),
                      'S'),
                  'S',
                       TO_CHAR(TO_DATE((NVL(TO_CHAR(PCNFSAIDPREFAT.HORASAIDA), NVL(PCNFSAIDPREFAT.HORALANC,0)) || ':' || NVL(TO_CHAR(PCNFSAIDPREFAT.MINUTOSAIDA), NVL(PCNFSAIDPREFAT.MINUTOLANC,0))), 'HH24:MI'), 'HH24:MI')
             ) AS HORASAIDA
        ,PCNFSAIDPREFAT.NUMPED AS NUM_PEDIDO
        ,PCPEDC.NUMPEDCLI AS NUM_PEDIDO_CLI
        ,PCNFSAIDPREFAT.NUMCAR AS NUMERO_CAR
        ,PCNFSAIDPREFAT.CODUSUR AS RCA
        ,PCNFSAIDPREFAT.CODCOB AS TIPO_COBRANCA
        ,DECODE(CLIENTE.CODCLI,
                1,
                'F',
                2,
                'F',
                3,
                'F',
                CLIENTE.TIPOFJ) AS TIPO_PESSOA
        ,NULL AS TIPODESCARGA
        ,PCNFSAIDPREFAT.CODCONT
        ,DECODE(NVL(PCNFSAIDPREFAT.AMBIENTENFE,
                    'X'),
                'H',
                2,
                'P',
                1,
                -1) AS AMBIENTE
        ,NVL(PCNFSAIDPREFAT.SITUACAONFE,
             0) AS SITUACAONFE
        ,CASE WHEN (NVL(PCPEDC.VENDALOCESTRANG, 'N') = 'S') THEN
                   'S'
              ELSE
                   NVL(CLIENTE.CONSUMIDORFINAL, 'N')
         END AS CONSUMIDOR_FINAL
        ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('SERIALCERTIFICADO',
                                           PCFILIAL.CODIGO),
             '') AS SERIALCERTIFICADO
        ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PINCERTIFICADO',
                                           PCFILIAL.CODIGO),
             '') AS PINCERTIFICADO
        ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PROVIDERCERTIFICADOA3',
                                           PCFILIAL.CODIGO),
             'SafeSign Standard Cryptographic Service Provider') AS PROVIDERCERTIFICADOA3
        ,NVL(PARAMFILIAL.OBTERCOMONUMBER('TIPOPROVIDERA3',
                                         PCFILIAL.CODIGO),
             1) AS TIPOPROVIDERA3
        ,CASE
           WHEN ((SELECT CODPROD
                  FROM   PCMOVPREFAT
                  WHERE  PCMOVPREFAT.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA
                  AND    ROWNUM = 1
                  UNION
                  SELECT CODPROD
                  FROM   PCMOVCIAP
                  WHERE  PCMOVCIAP.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA
                  AND    ROWNUM = 1) IS NULL)
                AND (PCNFSAIDPREFAT.NUMTRANSVENDAORIGEM > 0 AND PCNFSAIDPREFAT.FINALIDADENFE <> 'A')  OR PCNFSAIDPREFAT.FINALIDADENFE = 'C' THEN
            2
           ELSE CASE WHEN
                PCNFSAIDPREFAT.FINALIDADENFE = 'A'
           THEN
            3
            ELSE
            1
            END
         END AS FINALIDADE
        ,PCNFSAIDPREFAT.DTAHORAENTRADACONTIGENCIA AS DTHORA_CONTINGENCIA
        ,PCNFSAIDPREFAT.JUSTIFICATIVACONTIGENCIA AS JUSTIFICATIVA
        ,CARREG.DESTINO AS DESTINOCARGA
        ,TO_NUMBER(SUBSTR(TO_CHAR(NVL(PCPEDC.NUMPEDRCA,0)),1,10)) AS NUMPEDRCA
        ,'' AS MOT_ESTORNONFE
        ,PCNFSAIDPREFAT.NUMTRANSENTORIGEM
        ,PCNFSAIDPREFAT.SITUACAONFEEPEC AS SITUACAO_NFE_EPEC
        ,PCNFSAIDPREFAT.NUMTRANSENTORIGCONSIG
        ,NVL(PCNFSAIDPREFAT.TIPOPRESENCAADQUIRINTE,TO_CHAR(CASE PCPEDC.ORIGEMPED
                                               WHEN 'B' THEN 1
                                               WHEN 'R' THEN 1
                                               WHEN 'W' THEN 2
                                               WHEN 'T' THEN 3
                                               WHEN 'F' THEN 9
                                               ELSE
                                                  (CASE WHEN PCNFSAIDPREFAT.FINALIDADENFE IN ('A', 'C') THEN 0 ELSE 1 END)
                                               END)
         ) AS INDICADOR_PRESENCA
        ,PCNFSAIDPREFAT.TIPOVENDA
        ,PCPEDC.INTEGRADORA
        ,NVL(PCNFSAIDPREFAT.CONTRIBUINTE, CLIENTE.CONTRIBUINTE) CONTRIBUINTE
        ,NVL(PCNFSAIDPREFAT.QTDEREPROCNFE, 0) AS QTD_REPROCESSAMENTO_NFE
        ,PCNFSAIDPREFAT.UIDREGISTRO
        ,PCNFSAIDPREFAT.IDPARCEIRO
        ,PCNFSAIDPREFAT.ASSINATURA
        ,PCPEDC.DATA DATA_PEDIDO
        ,PCNFSAIDPREFAT.CODCOBSEFAZ
        ,PCNFSAIDPREFAT.DATACONSOLIDACAOPREFAT
        ,'S' PREFATURAMENTO
        ,PCPEDC.NUMEMPENHO AS NUMEMPENHO
        ,PCNFSAIDPREFAT.USASRVTERCEIROS AS UTILIZASRVTERCEIROS
        ,PCNFSAIDPREFAT.ENVIADASEMRESPOSTA
        ,CLIENTE.IDENTIFICESTRANG AS IDESTRANGEIRO
        --VALIDAÇÃO PARA NOTAS EMITIDAS NO FORÇA DE VENDAS, EM CONTINGÊNCIA, NESTE CASO O SERVIDOR NFE NÃO PODE MUDAR A CHAVE DA NOTA
        ,CASE
           WHEN NVL(PCNFSAIDPREFAT.CONDVENDA,0) = 14 THEN
            CASE
              WHEN ((SELECT COUNT(*)
                       FROM PCPEDCFVMANIF
                      WHERE PCPEDC.NUMPEDRCA = PCPEDCFVMANIF.NUMPEDRCA
                        AND PCPEDC.CODUSUR = PCPEDCFVMANIF.CODUSUR
                        AND PCPEDCFVMANIF.IMPORTADO = 2) > 0) AND
                   (PCPEDC.TIPOEMISSAO <> 1) AND
                   (PCPEDC.CHAVENFE IS NOT NULL) THEN
               'S'
              ELSE
               'N'
            END
           ELSE
            'N'
         END AS CHAVEGERADATV14
        ,PCPEDC.CHAVENFE AS CHAVENFETV14
        ,PCNFSAIDPREFAT.CODIGONUMERICOCHAVE AS CODIGO_NUMERICO_CHAVE
        ,PCNFSAIDPREFAT.DESCINTERMEDIADOR
        ,PCNFSAIDPREFAT.CNPJINTERMEDIADOR
  FROM   PCNFSAIDPREFAT
        ,PCFORNEC EMITENTE
        ,PCESTADO UF_E
        ,PCPAIS PAIS_E
        ,PCCIDADE CIDADE_E
        ,PCFILIAL
        ,PCPEDC
        ,PCCLIENT CLIENTE
        ,PCESTADO UF_D
        ,PCPAIS PAIS_D
        ,PCCIDADE CIDADE_D
        ,PCCIDADE CIDADE_ENT
        ,PCCARREG CARREG
        ,PCPEDC PD
        ,PCCLIENTENDENT ENT
        ,PCCIDADE CID_ENT
        ,PCPAIS PAIS_ENT
        ,PCVENDACONSUM
  WHERE  NVL(PCNFSAIDPREFAT.CODFILIALNF, PCNFSAIDPREFAT.CODFILIAL) = PCFILIAL.CODIGO
  AND    PCFILIAL.CODFORNEC = EMITENTE.CODFORNEC(+)
  AND    CARREG.NUMCAR(+) = PCNFSAIDPREFAT.NUMCAR
  AND    PD.NUMTRANSVENDA(+) = PCNFSAIDPREFAT.NUMTRANSVENDA
  AND    ENT.CODENDENTCLI(+) =  NVL(PD.CODENDENTCLI, PD.CODENDENT)
  AND    ENT.CODCLI(+) =  PD.CODCLI
  AND    CID_ENT.CODCIDADE(+) = ENT.CODCIDADE
  AND    CIDADE_ENT.CODCIDADE(+) = CLIENTE.CODCIDADECOM
  AND    ((NVL(PCFILIAL.UTILIZANFE, 'N') = 'S') OR
          (NVL(PCNFSAIDPREFAT.USASRVTERCEIROS, NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZASRVTERCEIROS', PCFILIAL.CODIGO), 'N')) = 'S'))
  AND    PCNFSAIDPREFAT.DTCANCEL IS NULL
  AND    PCNFSAIDPREFAT.NUMPED = PCPEDC.NUMPED(+)
  AND    PCNFSAIDPREFAT.NUMPED = PCVENDACONSUM.NUMPED(+)
  AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE(+)
  AND    CIDADE_E.UF = UF_E.UF(+)
  AND    UF_E.CODPAIS = PAIS_E.CODPAIS(+)
  AND    UF_D.CODPAIS = PAIS_D.CODPAIS(+)
  AND    CLIENTE.CODCLI(+) = NVL(PCNFSAIDPREFAT.CODCLINF, PCNFSAIDPREFAT.CODCLI)
  AND    PCNFSAIDPREFAT.CODMUNICIPIO = CIDADE_D.CODCIDADE(+)
  AND    CIDADE_D.UF = UF_D.UF(+)
  AND    ENT.CODPAISRECEBEDOR = PAIS_ENT.CODPAIS(+)
  --Linhas abaixo sevem para obedecer a ordem de numeração das notas fiscais no processo de Adjudicação
  AND    ( (nvl(PCNFSAIDPREFAT.NUMTRANSENTDEPENDENTE,-1) = -1)  OR EXISTS (SELECT 1 FROM PCNFENT E WHERE E.NUMTRANSENT = PCNFSAIDPREFAT.NUMTRANSENTDEPENDENTE AND E.SITUACAONFE IN (100,101)))
  AND    (( nvl(PCNFSAIDPREFAT.NUMTRANSVENDADEPENDENTE,-1) = -1) OR (EXISTS (SELECT 1 FROM PCNFSAIDPREFAT S WHERE S.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDADEPENDENTE AND S.SITUACAONFE IN (100,101))))
  AND    NVL(PCNFSAIDPREFAT.DOCEMISSAO, 'X') NOT IN ('CE','SF', 'MF', 'CF')
  AND    PCNFSAIDPREFAT.DATACONSOLIDACAOPREFAT IS NULL
  AND    PCNFSAIDPREFAT.DTSAIDA >= (SELECT MIN(DTSAIDA) FROM PCNFSAIDPREFAT)                                    --PREDICADO ADICIONADO
  AND    PCNFSAIDPREFAT.NUMTRANSVENDA >= (SELECT MIN(NUMTRANSVENDA) FROM PCNFSAIDPREFAT)                        --PREDICADO ADICIONADO