BEGIN 
  UPDATE PCDICIONARIO SET DESCRICAO = 'Sazionalidade de Limite Crédito Cliente' WHERE NOMEOBJETO = 'PCLIMCRED';
  COMMIT; 

  UPDATE PCDICIONARIOITEMROT SET SECAO = '01-Geral', 
                                 EXIBIRRESPESQ = 'S' 
   WHERE CODROTINA = '3321' 
     AND NOMEOBJETO = 'PCLIMCRED' 
     AND NOMECAMPO IN ('CODDCLI','CODIGO','CODUSUR','DESCRICAO','DTFIM','DTINICIO','PERCAUMENTO','VALOR');   
  COMMIT; 
END;