CREATE OR REPLACE FUNCTION GET_DESCRICAO_FILTROAVANCADO(
  pTIPOCAMPO IN VARCHAR2,
  pROTULOPESQUISA IN VARCHAR2,  
  pTABELAPESQUISA IN VARCHAR2,  
  pDESCRICAOPESQUISA IN VARCHAR2,
  pCAMPOPESQUISA IN VARCHAR2,
  pVALORFILTRO IN VARCHAR2
) 
RETURN VARCHAR2 IS
  vSQL VARCHAR2(1000);
  vRESULT VARCHAR2(1000);
BEGIN
  IF (pTIPOCAMPO IN('NUMBER', 'VARCHAR2')) AND
     ((pROTULOPESQUISA IS NOT NULL) OR (pTABELAPESQUISA IS NOT NULL)) 
  THEN
    IF pROTULOPESQUISA IS NOT NULL THEN
      vSQL := 'SELECT DESCRICAO FROM PCROTULOITEM WHERE ID = :CODIGO';
    ELSE
      vSQL := 'SELECT '|| pDESCRICAOPESQUISA ||
              '  FROM '|| pTABELAPESQUISA ||
              ' WHERE '|| pCAMPOPESQUISA ||' = :CODIGO';
    END IF;
    
    EXECUTE IMMEDIATE vSQL INTO vRESULT USING pVALORFILTRO;
  END IF;

  RETURN vRESULT;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
