BEGIN 
  UPDATE PCDICIONARIO SET DESCRICAO = 'Contato de Clientes/Sócios' WHERE NOMEOBJETO = 'PCCONTATO';
  COMMIT; 
    
  UPDATE PCDICIONARIOITEMROT SET SECAO = '01-Geral', EXIBIRRESPESQ = 'S' 
   WHERE CODROTINA = '3312' 
     AND NOMEOBJETO = 'PCCONTATO' 
     AND NOMECAMPO IN ('AUTORCH','BAIRRO','CARGO','CELULAR','CEP','CGCCPF','CGCCPFAUX','CIDADE','CODCLI','CODCONTATO','DOC',
                       'DTNASCCONJUGE','DTNASCIMENTO','DTSOCIEDADE','EMAIL','ENDERECO','ESTADO','HOBBIE','NOMECONJUGE',
                       'NOMECONTATO','OBS','PARTICIPSOCIO','RG','TELEFONE','TIME','TIPOCONTATO'); 
  COMMIT;  

  UPDATE PCDICIONARIOITEM DIC 
   SET DIC.AJUDA = 'Código Cliente',  
       DIC.TITULO = 'Código Cliente'
 WHERE DIC.NOMEOBJETO = 'PCCONTATO'
   AND DIC.AJUDA = 'Código CLiente'; 
COMMIT;  

UPDATE PCDICIONARIOITEM DIC 
   SET DIC.AJUDA = 'Nome Cônjuge', 
       DIC.TITULO = 'Nome Cônjuge'
 WHERE DIC.NOMEOBJETO = 'PCCONTATO'
   AND DIC.AJUDA = 'Nome Conjuje'; 
COMMIT;  

UPDATE PCDICIONARIOITEM DIC 
   SET DIC.AJUDA = 'Data Nasc. Cônjuge', 
       DIC.TITULO = 'Data Nasc. Cônjuge'
 WHERE DIC.NOMEOBJETO = 'PCCONTATO'
   AND DIC.AJUDA = 'Data Nasc Conjuje'; 
COMMIT;  
  
END;