BEGIN 
  UPDATE PCDICIONARIO SET DESCRICAO = 'Contato de Clientes/Sócios' WHERE NOMEOBJETO = 'PCCONTATO';
  COMMIT; 
    
  UPDATE PCDICIONARIOITEMROT SET SECAO = '01-Geral', EXIBIRRESPESQ = 'S' 
   WHERE CODROTINA = '3312' 
     AND NOMEOBJETO = 'PCCONTATO' 
     AND NOMECAMPO IN ('AUTORCH','BAIRRO','CARGO','CELULAR','CEP','CGCCPF','CGCCPFAUX','CIDADE','CODCLI','CODCONTATO','DOC',
                       'DTNASCCONJUGE','DTNASCIMENTO','DTSOCIEDADE','EMAIL','ENDERECO','ESTADO','HOBBIE','NOMECONJUGE',
                       'NOMECONTATO','OBS','PARTICIPSOCIO','RG','TELEFONE','TIME','TIPOCONTATO'); 
  COMMIT;  
  
END;