CREATE OR REPLACE VIEW SQL_NFE_RODAPE_SAIDA_COMP AS 
SELECT S.NUMTRANSVENDA AS NUM_TRANSACAO,
       SUM(S.VLTOTAL) VALOR_TOTAL_PRODUTOS,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '1',
                  NVL(B.VLBASE,
                      0),
                  0)) BASE_ICMS,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '2',
                  NVL(B.VLBASE,
                      0),
                  0)) BASE_IPI,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '1',
                  DECODE(NVL(B.VLICMS,
                             0),
                         0,
                         NVL(B.VLBASE,
                             0) * NVL(B.ALIQUOTA,
                                      0) / 100,
                         NVL(B.VLICMS,
                             0)),
                  0)) VALOR_ICMS,
       SUM(DECODE(NVL(B.TIPO,
                      '1'),
                  '2',
                  DECODE(NVL(B.VLICMS,
                             0),
                         0,
                         NVL(B.VLBASE,
                             0) * NVL(B.ALIQUOTA,
                                      0) / 100,
                         NVL(B.VLICMS,
                             0)),
                  0)) VALOR_IPI,
       (SUM(S.VLTOTAL) - SUM(S.ICMSRETIDO) -
       SUM(DECODE(NVL(B.TIPO,
                       '1'),
                   '2',
                   DECODE(NVL(B.VLICMS,
                              0),
                          0,
                          NVL(B.VLBASE,
                              0) * NVL(B.ALIQUOTA,
                                       0) / 100,
                          NVL(B.VLICMS,
                              0)),
                   0))) VALOR_TOTAL,
       SUM(S.BCST) BASE_ST,
       SUM(S.ICMSRETIDO) VALOR_ST,
       S.TRANSPORTADORA AS TRANSPORTADOR,
       S.CGCFRETE AS CNPJ_TRANSPORTADOR,
       S.IEFRETE AS IE_TRANSPORTADOR,
       S.UFFRETE AS ESTADO_TRANSPORTADOR,
       S.PLACAVEIC AS PLACA,
       SUM(S.VLFRETE) AS VALOR_FRETE,
       SUM(NVL(S.VLOUTRASDESP,
               NVL(S.VLOUTRAS,
                   0))) AS VALOR_OUTRO,       
       CASE WHEN NVL(S.FINALIDADENFE, 'X') IN ('A', 'C', '2', '3') THEN
                 9 
          ELSE
                 DECODE(NVL(S.TIPOFRETE,
                            'C'),
                        'F',
                        1,
                        0)
       END AS MODALIDADE_FRETE,
       0 AS VALOR_TOTAL_SEGURO,
       MAX(NVL(S.VLOUTRAS,0)) AS VALOR_OUTROS,
       MAX(NVL(S.VLDESCONTO,0)) AS VALOR_DESCONTO,
       S.FINALIDADENFE       
FROM   PCNFBASE B,
       PCNFSAID S
WHERE  B.NUMTRANSVENDA = S.NUMTRANSVENDA
GROUP  BY S.NUMTRANSVENDA,
       S.TRANSPORTADORA,
       S.CGCFRETE,
       S.IEFRETE,
       S.UFFRETE,
       S.PLACAVEIC,
       S.FINALIDADENFE,
       S.TIPOFRETE