CREATE OR REPLACE VIEW VW_INT_C5_USUARIO_GRUPO AS
(
SELECT DISTINCT
      GRUPO.valor CODGRUPO,
      GRUPO.NOMEGRUPO NOMEGRUPO,
      FERRAMENTAS.F_BUSCARPARAMETRO_NUM('CON_PERMAXDESCITEMCF', '99', 0) PERCDESCMAX,
      'S' ATIVO
FROM
    (SELECT valor, 'OPERADOR DE CAIXA' NOMEGRUPO
      FROM pcparamfilial
      WHERE nome = 'CON_CODSETOROPERCX'
      AND codfilial = '99'
      UNION ALL
      SELECT valor, 'FISCAL DE CAIXA' NOMEGRUPO
      FROM pcparamfilial
      WHERE nome = 'CON_CODSETORFISCALCX'
      AND codfilial = '99'
    ) GRUPO
)
