DECLARE
  iCOUNT Integer;
BEGIN    
    FOR DADOS IN (
        SELECT '01' CODCOBSEFAZ,'Dinheiro' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '02' CODCOBSEFAZ,'Cheque' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '03' CODCOBSEFAZ,'Cartão de Crédito' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '04' CODCOBSEFAZ,'Cartão de Débito' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '05' CODCOBSEFAZ,'Cartão da Loja (Private Label), Crediário Digital, Outros Crediários' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '10' CODCOBSEFAZ,'Vale Alimentação' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '11' CODCOBSEFAZ,'Vale Refeição' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '12' CODCOBSEFAZ,'Vale Presente' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '13' CODCOBSEFAZ,'Vale Combustível' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '14' CODCOBSEFAZ,'Duplicata Mercantil' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '15' CODCOBSEFAZ,'Boleto Bancário' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '16' CODCOBSEFAZ,'Depósito Bancário' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '17' CODCOBSEFAZ,'Pagamento Instantâneo (PIX) - Dinâmico' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '18' CODCOBSEFAZ,'Transferência bancária, Carteira Digital' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '19' CODCOBSEFAZ,'Programa de fidelidade, Cashback, Crédito Virtual' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '20' CODCOBSEFAZ,'Pagamento Instantâneo (PIX) - Estático' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '21' CODCOBSEFAZ,'Crédito em Loja' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '22' CODCOBSEFAZ,'Pagamento Eletrônico não Informado - falha de hardware do sistema emissor' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '90' CODCOBSEFAZ,'Sem Pagamento' DESCRICAO, 'S' ATIVO FROM DUAL UNION
		SELECT '99' CODCOBSEFAZ,'Outros' DESCRICAO, 'S' ATIVO FROM DUAL
    ) LOOP
    
    SELECT COUNT(*) INTO iCOUNT FROM PCCOBSEFAZ WHERE CODCOBSEFAZ = DADOS.CODCOBSEFAZ;
    
    IF iCOUNT = 0 THEN
       INSERT INTO PCCOBSEFAZ(CODCOBSEFAZ, DESCRICAO, ATIVO) VALUES(DADOS.CODCOBSEFAZ, DADOS.DESCRICAO, DADOS.ATIVO);
    ELSE
       UPDATE PCCOBSEFAZ 
          SET DESCRICAO = DADOS.DESCRICAO
             ,ATIVO     = DADOS.ATIVO
       WHERE CODCOBSEFAZ = DADOS.CODCOBSEFAZ;
    END IF;
  END LOOP;
  COMMIT;
END;