DECLARE
  vQtde NUMBER(10);
BEGIN
  SELECT count(*)
  INTO vQtde
  FROM PCMOV S
  WHERE S.DFEREF_CHAVEACESSO IS NOT NULL
  OR S.NUMSEQ IS NOT NULL;

  
  IF vQtde < 1 THEN
    return;
  END IF;

  UPDATE PCMOV S SET 
    S.DFEREF_CHAVEACESSO = NULL,
    S.NUMSEQ = NULL
  WHERE S.DFEREF_CHAVEACESSO IS NOT NULL 
  OR S.NUMSEQ IS NOT NULL 
  AND ROTINACAD like '%PCSIS1360%'
  AND numtransvenda in (SELECT numtransvenda FROM pcnfent WHERE situacaonfe NOT IN (100, 150, 101, 151, 102, 152));
END;
