CREATE OR REPLACE TRIGGER TRG_PCTRIBUTACAO_F_NCM
BEFORE INSERT OR UPDATE ON PCTRIBUTACAO_FILTRO_NCM
FOR EACH ROW
DECLARE
  v_DTEXCLUSAO DATE;
BEGIN
  IF INSERTING THEN
    BEGIN
      SELECT DTEXCLUSAO
        INTO v_DTEXCLUSAO
        FROM PCTRIBUTACAO
       WHERE CODIGO_TRIBUTACAO = :NEW.CODIGO_TRIBUTACAO;
    EXCEPTION
      WHEN OTHERS THEN
        v_DTEXCLUSAO := NULL;
    END;

    IF v_DTEXCLUSAO IS NOT NULL THEN
      :NEW.DTINATIVACAO := SYSDATE;
    END IF;
  END IF;

  IF UPDATING THEN
    :NEW.DTULTALTER := SYSDATE;
  END IF;
END;