CREATE OR REPLACE VIEW SQL_NFE_REF_ENTRADA_COMP AS
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO,
       UF_E.UF AS SIGLA_UF,
       REPLACE(REPLACE(REPLACE(EMITENTE.CGC,'.',''),'/',''),'-','') AS CNPJ_E,
       PCNFENT.DTSAIDA AS DATA_EMISSAO,
       PCNFENT.CHAVENFE AS CHAVE_ACESSO,
       DECODE(NVL(PCNFENT.CHAVENFE,
                  '01'),
              '01',
              '01',
              '55') AS MODELO,
       DECODE(NVL(PCNFENT.SERIE,
                  'U'),
              'U',
              '0',
              PCNFENT.SERIE) AS SERIE,
       PCNFENT.NUMNOTA AS NUMERO_NOTA
FROM   PCNFENT,
       PCFORNEC EMITENTE,
       PCESTADO UF_E,
       PCCIDADE CIDADE_E,
       PCFILIAL
WHERE  NVL(PCNFENT.CODFILIALNF,
           PCNFENT.CODFILIAL) = PCFILIAL.CODIGO
AND    PCFILIAL.CODFORNEC = EMITENTE.CODFORNEC
AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE
AND    PCNFENT.SERIE <> 'CF'
AND    CIDADE_E.UF = UF_E.UF 