CREATE OR REPLACE FUNCTION REPROCESSAR_PCFINANC2_MULTI(VDATA      IN DATE,
                                                       VCODFILIAL IN VARCHAR2)
  RETURN VARCHAR2 IS
  VTOTALPCFINANC2 NUMBER;
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  BEGIN
    SELECT COUNT(1) TOTAL
      INTO VTOTALPCFINANC2
      FROM PCFINANC2
     WHERE DATA = VDATA
       AND CODFILIAL = VCODFILIAL
       AND PARMULTIFILIALCAIXABANCO3882 = 'S';
	   
	IF VTOTALPCFINANC2 = 0 THEN
    --CAIXA
    INSERT INTO PCFINANC2
      (DATA,
       CODFILIAL,
       TIPODADO,
       CODIGON,
       CODIGOA,
       VALOR,
       DTGERACAO,
       CODROTINA,
       CODFUNC,
       PARMULTIFILIALCAIXABANCO3882)
      SELECT VDATA DATA,
             VCODFILIAL CODFILIAL,
             'CAIXA' TIPODADO,
             PCMOVCR.CODBANCO CODIGON,
             PCMOVCR.CODCOB,
             SUM(DECODE(TIPO, 'D', VALOR, 0)) -
             SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
             SYSDATE DTGERACAO,
             504 CODROTINA,
             1 CODFUNC,
             'S' PARMULTIFILIALCAIXABANCO3882
        FROM PCMOVCR, PCBANCO
       WHERE DATA <= VDATA
         AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
         AND PCBANCO.CODBANCO IN
             (SELECT PCFINANC2.CODIGON
                FROM PCFINANC2
               WHERE DATA = VDATA - 1
                 AND CODFILIAL = VCODFILIAL
                 AND TIPODADO = 'CAIXA'
                 AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'S')
         AND PCBANCO.TIPOCXBCO = 'C'
         AND PCMOVCR.CODCOB IN ('D', 'APLI')
       GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
  
    --BANCO
    INSERT INTO PCFINANC2
      (DATA,
       CODFILIAL,
       TIPODADO,
       CODIGON,
       CODIGOA,
       VALOR,
       DTGERACAO,
       CODROTINA,
       CODFUNC,
       PARMULTIFILIALCAIXABANCO3882)
      SELECT VDATA DATA,
             VCODFILIAL CODFILIAL,
             'BANCO' TIPODADO,
             PCMOVCR.CODBANCO CODIGON,
             PCMOVCR.CODCOB,
             SUM(DECODE(TIPO, 'D', VALOR, 0)) -
             SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
             SYSDATE DTGERACAO,
             504 CODROTINA,
             1 CODFUNC,
             'S' PARMULTIFILIALCAIXABANCO3882
        FROM PCMOVCR, PCBANCO
       WHERE DATA <= VDATA
         AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
         AND PCBANCO.CODBANCO IN
             (SELECT PCFINANC2.CODIGON
                FROM PCFINANC2
               WHERE DATA = VDATA - 1
                 AND CODFILIAL = VCODFILIAL
                 AND TIPODADO = 'BANCO'
                 AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'S')
         AND PCBANCO.TIPOCXBCO = 'B'
         AND PCMOVCR.CODCOB IN ('D', 'APLI')
       GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
  
    --VALE
    INSERT INTO PCFINANC2
      (DATA,
       CODFILIAL,
       TIPODADO,
       CODIGON,
       CODIGOA,
       VALOR,
       DTGERACAO,
       CODROTINA,
       CODFUNC,
       PARMULTIFILIALCAIXABANCO3882)
      SELECT VDATA DATA,
             VCODFILIAL CODFILIAL,
             'VALE' TIPODADO,
             PCMOVCR.CODBANCO CODIGON,
             PCMOVCR.CODCOB,
             SUM(DECODE(TIPO, 'D', VALOR, 0)) -
             SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
             SYSDATE DTGERACAO,
             504 CODROTINA,
             1 CODFUNC,
             'S' PARMULTIFILIALCAIXABANCO3882
        FROM PCMOVCR, PCBANCO
       WHERE DATA <= VDATA
         AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
         AND PCBANCO.CODBANCO IN
             (SELECT PCFINANC2.CODIGON
                FROM PCFINANC2
               WHERE DATA = VDATA - 1
                 AND CODFILIAL = VCODFILIAL
                 AND TIPODADO = 'VALE'
                 AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'S')
         AND PCMOVCR.CODCOB IN ('VALE')
       GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
  
    --EMPRESTIMO ATIVO
    INSERT INTO PCFINANC2
      (DATA,
       CODFILIAL,
       TIPODADO,
       CODIGON,
       CODIGOA,
       VALOR,
       DTGERACAO,
       CODROTINA,
       CODFUNC,
       PARMULTIFILIALCAIXABANCO3882)
      SELECT VDATA DATA,
             VCODFILIAL CODFILIAL,
             'EMPRESTA' TIPODADO,
             PCMOVCR.CODBANCO CODIGON,
             PCMOVCR.CODCOB,
             SUM(DECODE(TIPO, 'D', VALOR, 0)) -
             SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
             SYSDATE DTGERACAO,
             504 CODROTINA,
             1 CODFUNC,
             'S' PARMULTIFILIALCAIXABANCO3882
        FROM PCMOVCR, PCBANCO
       WHERE DATA <= VDATA
         AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
         AND PCBANCO.CODBANCO IN
             (SELECT PCFINANC2.CODIGON
                FROM PCFINANC2
               WHERE DATA = VDATA - 1
                 AND CODFILIAL = VCODFILIAL
                 AND TIPODADO = 'EMPRESTA'
                 AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'S')
         AND PCBANCO.TIPOCXBCO = 'E'
       GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;
  
    --EMPRESTIMO PASSIVO
    INSERT INTO PCFINANC2
      (DATA,
       CODFILIAL,
       TIPODADO,
       CODIGON,
       CODIGOA,
       VALOR,
       DTGERACAO,
       CODROTINA,
       CODFUNC,
       PARMULTIFILIALCAIXABANCO3882)
      SELECT VDATA DATA,
             VCODFILIAL CODFILIAL,
             'EMPRESTP' TIPODADO,
             CODIGON,
             CODIGOA,
             VALOR,
             SYSDATE DTGERACAO,
             504 CODROTINA,
             1 CODFUNC,
             PCFINANC2.PARMULTIFILIALCAIXABANCO3882
        FROM PCFINANC2
       WHERE TIPODADO = 'EMPRESTP'
         AND CODFILIAL = VCODFILIAL
         AND DATA = VDATA - 1
         AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'S';
  
    --CONTAS TRANSITÓRIAS
    INSERT INTO PCFINANC2
      (DATA,
       CODFILIAL,
       TIPODADO,
       CODIGON,
       CODIGOA,
       VALOR,
       DTGERACAO,
       CODROTINA,
       CODFUNC,
       PARMULTIFILIALCAIXABANCO3882)
      SELECT VDATA DATA,
             VCODFILIAL CODFILIAL,
             'CTRANS' TIPODADO,
             PCMOVCR.CODBANCO CODIGON,
             PCMOVCR.CODCOB,
             SUM(DECODE(TIPO, 'D', VALOR, 0)) -
             SUM(DECODE(TIPO, 'C', VALOR, 0)) VALOR,
             SYSDATE DTGERACAO,
             504 CODROTINA,
             1 CODFUNC,
             'S' PARMULTIFILIALCAIXABANCO3882
        FROM PCMOVCR, PCBANCO
       WHERE DATA <= VDATA
         AND PCBANCO.CODBANCO = PCMOVCR.CODBANCO
         AND PCBANCO.CODBANCO IN
             (SELECT PCFINANC2.CODIGON
                FROM PCFINANC2
               WHERE DATA = VDATA - 1
                 AND CODFILIAL = VCODFILIAL
                 AND TIPODADO = 'CTRANS'
                 AND PCFINANC2.PARMULTIFILIALCAIXABANCO3882 = 'S')
         AND PCMOVCR.CODCOB NOT IN ('D', 'APLI', 'VALE')
       GROUP BY PCMOVCR.CODBANCO, PCMOVCR.CODCOB;  
    COMMIT;
  END IF;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, ('Erro na execução: ' || SQLCODE || ' - ' || SQLERRM));
  END;

  RETURN 'OK';

END;