DECLARE
   V_EXISTE ALL_TYPES.TYPE_NAME%TYPE;
BEGIN
   SELECT T.TYPE_NAME
     INTO V_EXISTE
     FROM ALL_TYPES T
    WHERE T.TYPE_NAME = 'TABELA_NFE_NFREFERENCIADA'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'DROP TYPE TABELA_NFE_NFREFERENCIADA';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
CREATE OR REPLACE TYPE TIPO_NFE_NFREFERENCIADA AS OBJECT
(
   CHAVE_ACESSO VARCHAR2(44),
   CNPJ_E       VARCHAR2(20),
   IE           VARCHAR2(15),
   SIGLA_UF     VARCHAR2(2),
   SERIE        VARCHAR2(3),
   MODELO       VARCHAR2(2),
   DATA_EMISSAO DATE,
   NUMERO_NOTA  NUMBER,
   TIPO         NUMBER,
   DOCREF       NUMBER,
   NUMSEQECF    VARCHAR2(4),
   DATACONSOLIDACAOPREFAT     DATE, 
   PREFATURAMENTO           VARCHAR2(1) 
) 