CREATE OR REPLACE TYPE BODY T_PC_CREDITOCLIENTE AS

  CONSTRUCTOR FUNCTION T_PC_CREDITOCLIENTE(
    PMATRICULA NUMBER,
    PCODROTINA NUMBER
  ) RETURN SELF AS
    RESULT IS
      BEGIN SELF.CODFUNC := PMATRICULA;
    SELF   .CODFUNCLANC := PMATRICULA;
    SELF   .CODROTINA := PCODROTINA;
    RETURN;
  END;
  MEMBER

  PROCEDURE LIMPAR IS
  BEGIN
    SELF.CODCLI := NULL;
    SELF.DTLANC := NULL;
    SELF.CODFILIAL := NULL;
    SELF.NUMNOTA := NULL;
    SELF.NUMTRANSVENDA := NULL;
    SELF.SERIE := NULL;
    SELF.VALOR := NULL;
    SELF.DTDESCONTO := NULL;
    SELF.CODFILIALDESC := NULL;
    SELF.NUMNOTADESC := NULL;
    SELF.SERIEDESC := NULL;
    SELF.HORA := NULL;
    SELF.MINUTO := NULL;
    SELF.ORIGEM := NULL;
    SELF.NUMTRANSVENDADESC := NULL;
    SELF.NUMTRANSENTDEVCLI := NULL;
    SELF.HISTORICO := NULL;
    SELF.CODFUNCLANC := NULL;
    SELF.NUMPED := NULL;
    SELF.NUMERARIO := NULL;
    SELF.CODMOVIMENTO := NULL;
    SELF.NUMLANCBAIXA := NULL;
    SELF.NUMTRANSBAIXA := NULL;
    SELF.NUMLANC := NULL;
    SELF.NUMTRANS := NULL;
    SELF.NUMPEDECF := NULL;
    SELF.NUMCAIXA := NULL;
    SELF.CODFUNCCX := NULL;
    SELF.NUMSERIEEQUIP := NULL;
    SELF.PRESTRESTCLI := NULL;
    SELF.SITUACAO := NULL;
    SELF.NUMINDENIZ := NULL;
    SELF.OBS := NULL;
    SELF.CODADMCARTAO := NULL;
    SELF.NUMCUPOM := NULL;
    SELF.NSUTEF := NULL;
    SELF.BIN := NULL;
    SELF.CODIGO := NULL;
    SELF.VALORESTORNOLIBERADO := NULL;
    SELF.CODCLIORIG := NULL;
    SELF.NUMGIFTCARD := NULL;
    SELF.DTEMISSAOTITULO := NULL;
    SELF.NUMCRED := NULL;
    SELF.DTESTORNO := NULL;
    SELF.CODPLPAG := NULL;
    SELF.DTVENC := NULL;
    SELF.DTCANCEL := NULL;
    SELF.CODCHECKOUTPDV := NULL;
    SELF.CODEMPRESAPDV := NULL;
    SELF.NUMDOCTOPDV := NULL;
  END LIMPAR;

  MEMBER

  PROCEDURE INSERIR IS
  BEGIN
    IF NVL(SELF.CODIGO, 0) <= 0 THEN
      SELECT
        DFSEQ_PCCRECLI.NEXTVAL INTO SELF.CODIGO
      FROM
        DUAL;
    END IF;

    INSERT INTO PCCRECLI (
      CODCLI,
      DTLANC,
      CODFILIAL,
      NUMNOTA,
      NUMTRANSVENDA,
      SERIE,
      VALOR,
      DTDESCONTO,
      CODFILIALDESC,
      NUMNOTADESC,
      SERIEDESC,
      CODFUNC,
      HORA,
      MINUTO,
      ORIGEM,
      NUMTRANSVENDADESC,
      NUMTRANSENTDEVCLI,
      HISTORICO,
      CODFUNCLANC,
      NUMPED,
      NUMERARIO,
      CODMOVIMENTO,
      NUMLANCBAIXA,
      NUMTRANSBAIXA,
      NUMLANC,
      NUMTRANS,
      NUMPEDECF,
      NUMCAIXA,
      CODFUNCCX,
      NUMSERIEEQUIP,
      CODROTINA,
      PRESTRESTCLI,
      SITUACAO,
      NUMINDENIZ,
      OBS,
      CODADMCARTAO,
      NUMCUPOM,
      NSUTEF,
      BIN,
      CODIGO,
      VALORESTORNOLIBERADO,
      CODCLIORIG,
      NUMGIFTCARD,
      DTEMISSAOTITULO,
      NUMCRED,
      DTESTORNO,
      CODPLPAG,
      DTVENC,
      DTCANCEL,
      CODCHECKOUTPDV,
      CODEMPRESAPDV,
      NUMDOCTOPDV
    ) VALUES (
      SELF.CODCLI,
      NVL(SELF.DTLANC, TRUNC(SYSDATE)),
      SELF.CODFILIAL,
      SELF.NUMNOTA,
      SELF.NUMTRANSVENDA,
      SELF.SERIE,
      SELF.VALOR,
      SELF.DTDESCONTO,
      SELF.CODFILIALDESC,
      SELF.NUMNOTADESC,
      SELF.SERIEDESC,
      SELF.CODFUNC,
      SELF.HORA,
      SELF.MINUTO,
      SELF.ORIGEM,
      SELF.NUMTRANSVENDADESC,
      SELF.NUMTRANSENTDEVCLI,
      SELF.HISTORICO,
      SELF.CODFUNCLANC,
      SELF.NUMPED,
      SELF.NUMERARIO,
      SELF.CODMOVIMENTO,
      SELF.NUMLANCBAIXA,
      SELF.NUMTRANSBAIXA,
      SELF.NUMLANC,
      SELF.NUMTRANS,
      SELF.NUMPEDECF,
      SELF.NUMCAIXA,
      SELF.CODFUNCCX,
      SELF.NUMSERIEEQUIP,
      SELF.CODROTINA,
      SELF.PRESTRESTCLI,
      SELF.SITUACAO,
      SELF.NUMINDENIZ,
      SELF.OBS,
      SELF.CODADMCARTAO,
      SELF.NUMCUPOM,
      SELF.NSUTEF,
      SELF.BIN,
      SELF.CODIGO,
      SELF.VALORESTORNOLIBERADO,
      SELF.CODCLIORIG,
      SELF.NUMGIFTCARD,
      SELF.DTEMISSAOTITULO,
      SELF.NUMCRED,
      SELF.DTESTORNO,
      SELF.CODPLPAG,
      SELF.DTVENC,
      SELF.DTCANCEL,
      SELF.CODCHECKOUTPDV,
      SELF.CODEMPRESAPDV,
      SELF.NUMDOCTOPDV
    );
  END INSERIR;

  MEMBER

  PROCEDURE BAIXAR IS
    VCODIGOAUX PCCRECLI.CODIGO%TYPE;
  BEGIN
    SELECT
      CODIGO INTO VCODIGOAUX
    FROM
      PCCRECLI
    WHERE
      CODIGO = SELF.CODIGO FOR UPDATE NOWAIT;
    UPDATE PCCRECLI
    SET
      DTDESCONTO = NVL(
        SELF.DTDESCONTO,
        TRUNC(SYSDATE)
      ),
      CODFILIALDESC = SELF.CODFILIALDESC,
      NUMNOTADESC = SELF.NUMNOTADESC,
      SERIEDESC = SELF.SERIEDESC,
      CODFUNC = SELF.CODFUNC,
      HORA = TO_CHAR(
        SYSDATE,
        'HH24'
      ),
      MINUTO = TO_CHAR(
        SYSDATE,
        'MI'
      ),
      NUMTRANSVENDADESC = SELF.NUMTRANSVENDADESC,
      NUMCRED = SELF.NUMCRED,
      DTESTORNO = DECODE(
        SELF.DTESTORNO,
        NULL,
        NULL,
        SELF.DTESTORNO
      ),
      CODFUNCCX = SELF.CODFUNCCX,
      NUMPEDECF = SELF.NUMPEDECF,
      NUMSERIEEQUIP = SELF.NUMSERIEEQUIP,
      NUMCAIXA = SELF.NUMCAIXA,
      NUMCUPOM = SELF.NUMCUPOM,
      HISTORICO = SELF.HISTORICO,
      PRESTRESTCLI = SELF.PRESTRESTCLI,
      DTCANCEL = DECODE(
        SELF.DTCANCEL,
        NULL,
        NULL,
        SELF.DTCANCEL
      ),
      NUMDOCTOPDV = SELF.NUMDOCTOPDV,
      CODEMPRESAPDV = SELF.CODEMPRESAPDV,
      CODCHECKOUTPDV = SELF.CODCHECKOUTPDV
    WHERE
      CODIGO = SELF.CODIGO;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20016, 'BAIXAR '
                                      || SELF.CODIGO
                                      ||' REGISTRO BLOQUEADO PARA EDICAO!');
  END BAIXAR;

  MEMBER PROCEDURE ESTORNARTOTAL IS
  BEGIN
 --AGORA BAIXANDO/ESTORNANDO
    SELF.DTDESCONTO := TRUNC(SYSDATE);
    SELF.HORA := TO_CHAR(SYSDATE, 'HH24');
    SELF.MINUTO := TO_CHAR(SYSDATE, 'MI');
    SELF.DTESTORNO := TRUNC(SYSDATE);
    SELF.BAIXAR;
 --FAZENDO UM CLONE PARA CONTRA PARTIDA
    SELF.VALOR := SELF.VALOR * (-1);
    SELF.CODIGO := NULL;
    SELF.INSERIR;
  END ESTORNARTOTAL;

  MEMBER FUNCTION PROXIMOCODIGOCREDITO RETURN NUMBER IS
    PFCODIGO PCCRECLI.CODIGO%TYPE;
  BEGIN
    SELECT
      DFSEQ_PCCRECLI.NEXTVAL INTO PFCODIGO
    FROM
      DUAL;
    RETURN PFCODIGO;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20016, 'PROXIMOCODIGOCREDITO: NAO FOI POSSIVEL GERAR CODIGO!');
  END PROXIMOCODIGOCREDITO;

  MEMBER PROCEDURE BUSCARCREDITO(
    PCODIGO NUMBER
  ) IS
  BEGIN
    SELECT
      CODCLI,
      DTLANC,
      CODFILIAL,
      NUMNOTA,
      NUMTRANSVENDA,
      SERIE,
      VALOR,
      DTDESCONTO,
      CODFILIALDESC,
      NUMNOTADESC,
      SERIEDESC,
      CODFUNC,
      HORA,
      MINUTO,
      ORIGEM,
      NUMTRANSVENDADESC,
      NUMTRANSENTDEVCLI,
      HISTORICO,
      CODFUNCLANC,
      NUMPED,
      NUMERARIO,
      CODMOVIMENTO,
      NUMLANCBAIXA,
      NUMTRANSBAIXA,
      NUMLANC,
      NUMTRANS,
      NUMPEDECF,
      NUMCAIXA,
      CODFUNCCX,
      NUMSERIEEQUIP,
      CODROTINA,
      PRESTRESTCLI,
      SITUACAO,
      NUMINDENIZ,
      OBS,
      CODADMCARTAO,
      NUMCUPOM,
      NSUTEF,
      BIN,
      CODIGO,
      VALORESTORNOLIBERADO,
      CODCLIORIG,
      NUMGIFTCARD,
      DTEMISSAOTITULO,
      NUMCRED,
      DTESTORNO,
      CODPLPAG,
      DTVENC,
      DTCANCEL,
      CODCHECKOUTPDV,
      CODEMPRESAPDV,
      NUMDOCTOPDV 
      INTO
      SELF.CODCLI,
      SELF.DTLANC,
      SELF.CODFILIAL,
      SELF.NUMNOTA,
      SELF.NUMTRANSVENDA,
      SELF.SERIE,
      SELF.VALOR,
      SELF.DTDESCONTO,
      SELF.CODFILIALDESC,
      SELF.NUMNOTADESC,
      SELF.SERIEDESC,
      SELF.CODFUNC,
      SELF.HORA,
      SELF.MINUTO,
      SELF.ORIGEM,
      SELF.NUMTRANSVENDADESC,
      SELF.NUMTRANSENTDEVCLI,
      SELF.HISTORICO,
      SELF.CODFUNCLANC,
      SELF.NUMPED,
      SELF.NUMERARIO,
      SELF.CODMOVIMENTO,
      SELF.NUMLANCBAIXA,
      SELF.NUMTRANSBAIXA,
      SELF.NUMLANC,
      SELF.NUMTRANS,
      SELF.NUMPEDECF,
      SELF.NUMCAIXA,
      SELF.CODFUNCCX,
      SELF.NUMSERIEEQUIP,
      SELF.CODROTINA,
      SELF.PRESTRESTCLI,
      SELF.SITUACAO,
      SELF.NUMINDENIZ,
      SELF.OBS,
      SELF.CODADMCARTAO,
      SELF.NUMCUPOM,
      SELF.NSUTEF,
      SELF.BIN,
      SELF.CODIGO,
      SELF.VALORESTORNOLIBERADO,
      SELF.CODCLIORIG,
      SELF.NUMGIFTCARD,
      SELF.DTEMISSAOTITULO,
      SELF.NUMCRED,
      SELF.DTESTORNO,
      SELF.CODPLPAG,
      SELF.DTVENC,
      SELF.DTCANCEL,
      SELF.CODCHECKOUTPDV,
      SELF.CODEMPRESAPDV,
      SELF.NUMDOCTOPDV
    FROM
      PCCRECLI
    WHERE
      CODIGO = PCODIGO;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20016, 'CREDITO CODIGO '
                                      || PCODIGO
                                      ||' NAO FOI LOCALIZADO!');
  END BUSCARCREDITO;
END;