CREATE or REPLACE VIEW VW_INT_C5_GRUPOPESSOA AS (
SELECT 
  CODGRUPOFIDELIDADE SEQGRUPOPESSOA,
  GRUPOFIDELIDADE DESCRICAO,
  'S' ATIVO
  FROM PCGRUPOFIDELIDADE
)

\

CREATE or REPLACE VIEW VW_INT_C5_PESSOAGRUPO AS (
SELECT 
  CODGRUPOFIDELIDADE SEQGRUPOPESSOA,
  CODCLI SEQPESSOA,
  'S' ATIVO
  FROM PCGRUPOFIDELIDADECLIENTE
)
