CREATE OR REPLACE FUNCTION CTE_DOC_ANTERIOR(P_TRANSACAO NUMBER)
  RETURN TABELA_CTE_DOC_ANTERIOR IS
  L_TIPOSUBCONTRATACAOCTE VARCHAR2(1);
  L_TIPOSERVICOCTE        VARCHAR2(1);

  CURSOR CR_CTE_DOC_ANTERIOR IS
   
   SELECT  PCNFSAID.CHAVECTEREF AS CHAVE_CTE_REF,     
           PCNFSAID.CNPJCPFCTEREF AS CNPJCPF_CTE_REF,
           PCNFSAID.IECTEREF AS IE_CTE_REF,
           PCNFSAID.UFCTEREF AS UF_CTE_REF,  
           PCNFSAID.RAZAOSOCIALCTEREF AS RAZAOSOCIAL_CTE_REF,  
           PCNFSAID.TIPODOCCTEREF AS TIPODOC_CTE_REF, 
           PCNFSAID.SERIEDOCCTEREF AS SERIEDOC_CTE_REF,  
           PCNFSAID.SUBSERIEDOCCTEREF AS SUBSERIE_CTE_REF,
           PCNFSAID.NUMDOCCTEREF AS NUMDOC_CTE_REF,   
           PCNFSAID.DTEMISSAOCTEREF AS DTEMISSAO_CTE_REF
      FROM PCNFSAID
     WHERE PCNFSAID.NUMTRANSVENDA = P_TRANSACAO;
  
  RETORNO TABELA_CTE_DOC_ANTERIOR; 
BEGIN
  SELECT TIPOSUBCONTRATACAOCTE, TIPOSERVICOCTE
    INTO L_TIPOSUBCONTRATACAOCTE, L_TIPOSERVICOCTE
    FROM PCNFSAID
   WHERE NUMTRANSVENDA = P_TRANSACAO; 
  IF ((L_TIPOSERVICOCTE = '1' AND NVL(L_TIPOSUBCONTRATACAOCTE,'') = '1') OR 
      (L_TIPOSERVICOCTE <> 1)) THEN
    RETORNO := TABELA_CTE_DOC_ANTERIOR();

    FOR ITEM IN CR_CTE_DOC_ANTERIOR LOOP
      RETORNO.EXTEND;
      
      RETORNO(RETORNO.COUNT) := TIPO_CTE_DOC_ANTERIOR( NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL,
                                                       NULL);
      
      RETORNO(RETORNO.COUNT).CHAVE_CTE_REF        := ITEM.CHAVE_CTE_REF;
      RETORNO(RETORNO.COUNT).CNPJCPF_CTE_REF      := ITEM.CNPJCPF_CTE_REF;
      RETORNO(RETORNO.COUNT).IE_CTE_REF           := ITEM.IE_CTE_REF;
      RETORNO(RETORNO.COUNT).UF_CTE_REF           := ITEM.UF_CTE_REF;
      RETORNO(RETORNO.COUNT).RAZAOSOCIAL_CTE_REF  := ITEM.RAZAOSOCIAL_CTE_REF;
      RETORNO(RETORNO.COUNT).TIPODOC_CTE_REF      := ITEM.TIPODOC_CTE_REF;
      RETORNO(RETORNO.COUNT).SERIEDOC_CTE_REF     := ITEM.SERIEDOC_CTE_REF;
      RETORNO(RETORNO.COUNT).SUBSERIE_CTE_REF     := ITEM.SUBSERIE_CTE_REF;
      RETORNO(RETORNO.COUNT).NUMDOC_CTE_REF       := ITEM.NUMDOC_CTE_REF;
      RETORNO(RETORNO.COUNT).DTEMISSAO_CTE_REF    := ITEM.DTEMISSAO_CTE_REF;
  
  
    END LOOP;
  END IF;
  RETURN RETORNO;
EXCEPTION
  WHEN OTHERS THEN  
    raise_application_error(-20001, 'Erro motivo: ' || SQLERRM || '. Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;