CREATE OR REPLACE VIEW VW_INT_C5_PARCELDEPTO AS
(
SELECT 
     D.CODPARCEL SEQPARCELA,
     'PARCELAMENTO POR CLASSIFICAÇÃO MERCADOLÓGICA' DESCRICAO, 
     'C' TIPO,
     TRUNC(SYSDATE) DTAHORAINICIAL,
     TO_DATE('31/DEC/2099') DTAHORAFINAL, 
     DF.CODFINALIZADORA NROFORMAPAGTO, 
     ferramentas.f_buscarparametro_num('NUMREGIAOPADRAOVAREJO', D.CODFILIAL, '1') NRODIVISAO,
     (CASE
            WHEN D.CODSUBCATEGORIA IS NOT NULL THEN
                 D.CODDEPTO||D.CODSEC||D.CODCATEGORIA||D.CODSUBCATEGORIA
            WHEN CODCATEGORIA IS NOT NULL THEN
                 D.CODDEPTO||D.CODSEC||D.CODCATEGORIA
            WHEN CODSEC IS NOT NULL THEN
                 D.CODDEPTO||D.CODSEC
            ELSE '0'||D.CODDEPTO
     END) SEQCATEGORIA,
     
     NVL(F.QTMAXPARCELAS, D.QTMAXPARCELA) NROMAXPARCELA,
     
     (CASE
        WHEN STATUS = 'A' THEN
             'S'
        ELSE 'N'
     END) ATIVO 
     
FROM PCPARCELDEPTO D,
     PCFINALIZADORA F,
     PCPARCELDEPTOFINALIZADORA DF
WHERE DF.CODPARCEL = D.CODPARCEL
AND   DF.CODFINALIZADORA = F.CODFINALIZADORA     
)
