CREATE OR REPLACE VIEW VW_INT_C5_PARCELDEPTO AS
(
SELECT 
     D.CODPARCEL SEQPARCELA,
     'PARCELA CLASSIFICACAO MERCADOLOGICA' DESCRICAO, 
     D.CODFILIAL NROEMPRESA,
     'C' TIPO,
     TRUNC(SYSDATE) DTAHORINICIAL,
     TO_DATE('31/DEC/2099') DTAHORFINAL, 
     DF.CODFINALIZADORA NROFORMAPAGTO, 
     
     (SELECT R.NRODIVISAO
      FROM   PCDEPARAREGIAOC5 R
      WHERE  R.NUMREGIAO = ferramentas.f_buscarparametro_num('NUMREGIAOPADRAOVAREJO', 
                                                             D.CODFILIAL, 
                                                             '1') 
     )NRODIVISAO,
     
     (CASE
            WHEN D.CODSUBCATEGORIA IS NOT NULL THEN
                 ora_hash(D.CODSEC||D.CODCATEGORIA||D.CODSUBCATEGORIA||4, 2147483647)
            WHEN CODCATEGORIA IS NOT NULL THEN
                 ora_hash(D.CODCATEGORIA||D.CODCATEGORIA||3, 2147483647)
            WHEN CODSEC IS NOT NULL THEN
                 ora_hash(D.CODSEC||2, 2147483647)
            ELSE ora_hash(D.CODDEPTO||1, 2147483647)
     END) SEQCATEGORIA,
     
     NVL(F.QTMAXPARCELAS, D.QTMAXPARCELA) NROMAXIMOPARCELA,
     
     (CASE
        WHEN STATUS = 'A' THEN
             'S'
        ELSE 'N'
     END) ATIVO 
     
FROM PCPARCELDEPTO D,
     PCFINALIZADORA F,
     PCPARCELDEPTOFINALIZADORA DF
WHERE DF.CODPARCEL = D.CODPARCEL
AND   DF.CODFINALIZADORA = F.CODFINALIZADORA     
)
