CREATE OR REPLACE VIEW VW_INT_C5_PARCELDEPTO AS
(
SELECT 
     D.CODPARCEL SEQPARCELA,
     'PARCELAMENTO POR CLASSIFICAÇÃO MERCADOLÓGICA' DESCRICAO, 
     D.CODFILIAL NROEMPRESA,
     'C' TIPO,
     TRUNC(SYSDATE) DTAHORINICIAL,
     TO_DATE('31/DEC/2099') DTAHORFINAL, 
     DF.CODFINALIZADORA NROFORMAPAGTO, 
     ferramentas.f_buscarparametro_num('NUMREGIAOPADRAOVAREJO', D.CODFILIAL, '1') NRODIVISAO,
     (CASE
            WHEN D.CODSUBCATEGORIA IS NOT NULL THEN
                 D.CODDEPTO||1||D.CODSEC||2||D.CODCATEGORIA||3||D.CODSUBCATEGORIA||4
            WHEN CODCATEGORIA IS NOT NULL THEN
                 D.CODDEPTO||1||D.CODSEC||2||D.CODCATEGORIA||3
            WHEN CODSEC IS NOT NULL THEN
                 D.CODDEPTO||1||D.CODSEC||2
            ELSE D.CODDEPTO||1
     END) SEQCATEGORIA,
     
     NVL(F.QTMAXPARCELAS, D.QTMAXPARCELA) NROMAXIMOPARCELA,
     
     (CASE
        WHEN STATUS = 'A' THEN
             'S'
        ELSE 'N'
     END) ATIVO 
     
FROM PCPARCELDEPTO D,
     PCFINALIZADORA F,
     PCPARCELDEPTOFINALIZADORA DF
WHERE DF.CODPARCEL = D.CODPARCEL
AND   DF.CODFINALIZADORA = F.CODFINALIZADORA     
)
