-- Create sequence 
DECLARE
  VNCONTSEQ NUMBER;
  VSCRIPT   VARCHAR2(4000);
BEGIN
    BEGIN
        SELECT COUNT(1)
          INTO VNCONTSEQ
          FROM ALL_SEQUENCES A
         WHERE A.SEQUENCE_NAME = 'SEQ_REMESSALEICADASTRPOSITIVO';         
    END;
    
    IF VNCONTSEQ = 0  THEN
        VSCRIPT := 'CREATE SEQUENCE SEQ_REMESSALEICADASTRPOSITIVO MINVALUE 1 MAXVALUE 99999 START WITH 1 INCREMENT BY 1 CACHE 20';
        EXECUTE IMMEDIATE VSCRIPT;  
    END IF;
    
END;