-- 06_PKG_SL_CDC_MANAGER.sql

CREATE OR REPLACE PACKAGE PKG_SL_CDC_MANAGER AS
    FUNCTION GET_ACTIVE_LOG_TABLE(p_entity_name IN VARCHAR2) RETURN VARCHAR2;
    PROCEDURE CREATE_FIRST_LOG_TABLE(p_entity_name IN VARCHAR2);
    PROCEDURE ROTATE_LOG_TABLE(p_entity_name IN VARCHAR2);
    PROCEDURE REQUEST_ROTATION(p_entity_name IN VARCHAR2);
    PROCEDURE DROP_ALL_LOG_OBJECTS(p_entity_name IN VARCHAR2);
    FUNCTION ESCAPE_JSON(p_text IN CLOB) RETURN CLOB DETERMINISTIC;
    
    PROCEDURE WRITE_TO_LOG(
        p_entity_name IN VARCHAR2,
        p_change_type IN CHAR,
        p_row_pk      IN VARCHAR2
    );  
END PKG_SL_CDC_MANAGER;
