-- 06_PKG_SL_CDC_MANAGER.sql
-- Correção V6.1: Tratamento para nomes de objetos > 30 caracteres (ORA-00972)
 
CREATE OR REPLACE PACKAGE PKG_SL_CDC_MANAGER AS
    PROCEDURE CREATE_FIRST_LOG_TABLE(p_entity_name IN VARCHAR2);
    PROCEDURE ROTATE_LOG_TABLE(p_entity_name IN VARCHAR2);
    PROCEDURE WRITE_TO_LOG(p_entity_name IN VARCHAR2, p_change_type IN CHAR, p_row_pk IN VARCHAR2);
    PROCEDURE DROP_ALL_LOG_OBJECTS(p_entity_name IN VARCHAR2);
END PKG_SL_CDC_MANAGER;