CREATE OR REPLACE TRIGGER TRG_PCINTEGRACAOCORE_BEFORE 
BEFORE INSERT OR UPDATE ON PCINTEGRACAOCORE
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
BEGIN
  IF UPDATING OR INSERTING THEN
    :NEW.DTULTALTER := SYSDATE;
  END IF;
END;