CREATE OR REPLACE TRIGGER TRG_PCLOGDADOSLOG_PCPRODUTPK
BEFORE
  INSERT OR UPDATE OR DELETE
  ON PCPRODUTPICKING
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW

DECLARE
  VSPROGRAMA VARCHAR2(80);
  VSUSUARIO  VARCHAR2(80);
  VSMAQUINA  VARCHAR2(80);
  VSOPERACAO VARCHAR2(100);
BEGIN

  VSMAQUINA  := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 80);
  VSUSUARIO  := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 80);
  VSPROGRAMA := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 80);

  IF VSPROGRAMA IS NULL THEN
    VSPROGRAMA := 'Client do oracle desatualizado';
  END IF;

  IF UPDATING THEN
    VSOPERACAO := 'UPDATE';
  ELSIF INSERTING THEN
    VSOPERACAO := 'INSERT';
  ELSE
    VSOPERACAO := 'DELETE';
  END IF;


  insert into pclogdadoslogisticos (
  codfilial,
  codfilial_ant,
  codendereco,
  codendereco_ant,
  deposito,
  deposito_ant,
  rua,
  rua_ant,
  predio,
  predio_ant,
  nivel,
  nivel_ant,
  apto,
  apto_ant,
  codprod,
  codprod_ant,
  descricao,
  descricao_ant,
  embalagem,
  embalagem_ant,
  embalagemmaster,
  embalagemmaster_ant,
  unidade,
  unidade_ant,
  unidademaster,
  unidademaster_ant,
  qtunit,
  qtunit_ant,
  qtunitcx,
  qtunitcx_ant,
  codfab,
  codfab_ant,
  dun_caixa,
  dun_caixa_ant,
  ean_unidade,
  ean_unidade_ant,
  lastropal,
  lastropal_ant,
  alturapal,
  alturapal_ant,
  qttotpal,
  qttotpal_ant,
  altura_un,
  altura_un_ant,
  largura_un,
  largura_un_ant,
  comprimento_un,
  comprimento_un_ant,
  volume_venda,
  volume_venda_ant,
  altura_cx,
  altura_cx_ant,
  largura_cx,
  largura_cx_ant,
  comprimento_cx,
  comprimento_cx_ant,
  volume_master,
  volume_master_ant,
  pesobruto_cx,
  pesobruto_cx_ant,
  pesoliq_cx,
  pesoliq_cx_ant,
  pesobruto_un,
  pesobruto_un_ant,
  pesoliq_un,
  pesoliq_un_ant,
  usawms,
  usawms_ant,
  estoquepordtvalidade,
  estoquepordtvalidade_ant,
  prazoval,
  prazoval_ant,
  perctoleranciaval,
  perctoleranciaval_ant,
  pesovariavel,
  pesovariavel_ant,
  tipoestoque,
  tipoestoque_ant,
  tipo,
  tipo_ant,
  capacidade,
  capacidade_ant,
  pontoreposicao,
  pontoreposicao_ant,
  abastepalete,
  abastepalete_ant,
  abastepaletecx,
  abastepaletecx_ant,
  normapalete,
  normapalete_ant,
  expedecaixafechada,
  expedecaixafechada_ant,
  nivelmaximoarm,
  nivelmaximoarm_ant,
  nivelminimoarm,
  nivelminimoarm_ant,
  restricaoblocado,
  restricaoblocado_ant,
  digitarqtmaster,
  digitarqtmaster_ant,
  validacapacidadepicking,
  validacapacidadepicking_ant,
  estoquepordtvalidadepk,
  estoquepordtvalidadepk_ant,
  tipovariacao,
  tipovariacao_ant,
  fracionado,
  fracionado_ant,
  tipocarga,
  tipocarga_ant,
  controlanumserie,
  controlanumserie_ant,
  novacaixaflowrack,
  novacaixaflowrack_ant,
  estoqueporlote,
  estoqueporlote_ant,
  induzlote,
  induzlote_ant,
  utilizaqtdesupmultipla,
  utilizaqtdesupmultipla_ant,
  utilizamultiplicador,
  utilizamultiplicador_ant,
  usaformulacao,
  usaformulacao_ant,
  perctoleranciacorte,
  perctoleranciacorte_ant,
  perctoleranciadepuratransf,
  perctoleranciadepuratransf_ant,
  emitiretqent,
  emitiretqent_ant,
  atualizafilialgestaowms,
  atualizafilialgestaowms_ant,
  filialgestaowms,
  filialgestaowms_ant,
  enderecamentocubagem,
  enderecamentocubagem_ant,
  estrupk,
  estrupk_ant,
  pk_end,
  pk_end_ant,
  caracteristica,
  caracteristica_ant,
  estrupul,
  estrupul_ant,
  pulmao,
  pulmao_ant,
  tipoprod,
  tipoprod_ant,
  PROGRAMA,
  MAQUINA,
  USUARIO,
  DATA,
  OPERACAO
  )
    (SELECT e.codfilial,
           e.codfilial,
           e.codendereco,
           e.codendereco,
           e.deposito,
           e.deposito,
           e.rua,
           e.rua,
           e.predio,
           e.predio,
           e.nivel,
           e.nivel,
           e.apto,
           e.apto,
           p.codprod,
           p.codprod,
           p.descricao,
           p.descricao,
           p.embalagem,
           p.embalagem,
           p.embalagemmaster,
           p.embalagemmaster,
           p.unidade,
           p.unidade,
           p.unidademaster,
           p.unidademaster,
           p.qtunit,
           p.qtunit,
           p.qtunitcx,
           p.qtunitcx,
           p.codfab,
           p.codfab,
           p.codauxiliar2,
           p.codauxiliar2,
           p.codauxiliar,
           p.codauxiliar,
           f.lastropal,
           f.lastropal,
           f.alturapal,
           f.alturapal,
           f.qttotpal,
           f.qttotpal,
           p.alturam3 altura_un,
           p.alturam3 altura_un,
           p.larguram3 largura_un,
           p.larguram3 largura_un,
           p.comprimentom3 comprimento_un,
           p.comprimentom3 comprimento_un,
           p.volume AS volume_venda,
           p.volume AS volume_venda,
           p.alturaarm altura_cx,
           p.alturaarm altura_cx,
           p.larguraarm largura_cx,
           p.larguraarm largura_cx,
           p.comprimentoarm comprimento_cx,
           p.comprimentoarm comprimento_cx,
           p.volumerec AS volume_master,
           p.volumerec AS volume_master,
           p.pesobrutomaster pesobruto_cx,
           p.pesobrutomaster pesobruto_cx,
           p.pesoliqmaster pesoliq_cx,
           p.pesoliqmaster pesoliq_cx,
           p.pesobruto pesobruto_un,
           p.pesobruto pesobruto_un,
           p.pesoliq pesoliq_un,
           p.pesoliq pesoliq_un,
           DECODE (p.usawms,
                   'S',
                   'SIM',
                   'N',
                   'N?O')
               usawms,
           DECODE (p.usawms,
                   'S',
                   'SIM',
                   'N',
                   'N?O')
               usawms,
           p.estoquepordtvalidade,
           p.estoquepordtvalidade,
           f.prazoval,
           f.prazoval,
           f.perctoleranciaval,
           f.perctoleranciaval,
           p.pesovariavel,
           p.pesovariavel,
           p.tipoestoque,
           p.tipoestoque,
           DECODE (:new.tipo,
                   'V',
                   'VENDA',
                   'M',
                   'M?STER',
                   'P',
                   'PR?-PICK')
               tipo,
           DECODE (:old.tipo,
                   'V',
                   'VENDA',
                   'M',
                   'M?STER',
                   'P',
                   'PR?-PICK')
               tipo,
           :new.capacidade,
           :old.capacidade,
           :new.pontoreposicao,
           :old.pontoreposicao,
           f.abastepalete,
           f.abastepalete,
           f.abastepaletecx,
           f.abastepaletecx,
           f.normapalete,
           f.normapalete,
           f.expedecaixafechada,
           f.expedecaixafechada,
           f.nivelmaximoarm,
           f.nivelmaximoarm,
           f.nivelminimoarm,
           f.nivelminimoarm,
           f.restricaoblocado,
           f.restricaoblocado,
           f.digitarqtmaster,
           f.digitarqtmaster,
           f.validacapacidadepicking,
           f.validacapacidadepicking,
           f.estoquepordtvalidadepk,
           f.estoquepordtvalidadepk,
           f.tipovariacao,
           f.tipovariacao,
           f.fracionado,
           f.fracionado,
           f.tipocarga,
           f.tipocarga,
           f.controlanumserie,
           f.controlanumserie,
           f.novacaixaflowrack,
           f.novacaixaflowrack,
           p.estoqueporlote,
           p.estoqueporlote,
           p.induzlote,
           p.induzlote,
           f.utilizaqtdesupmultipla,
           f.utilizaqtdesupmultipla,
           p.utilizamultiplicador,
           p.utilizamultiplicador,
           f.usaformulacao,
           f.usaformulacao,
           f.perctoleranciacorte,
           f.perctoleranciacorte,
           f.perctoleranciadepuratransf,
           f.perctoleranciadepuratransf,
           f.emitiretqent,
           f.emitiretqent,
           f.atualizafilialgestaowms,
           f.atualizafilialgestaowms,
           f.filialgestaowms,
           f.filialgestaowms,
           p.enderecamentocubagem,
           p.enderecamentocubagem,
           :new.tipoestrutura || '-' || (t.descricao) estrupk,
           :old.tipoestrutura || '-' || (t.descricao) estrupk,
           (:new.tipoendereco || '-' || (ll.descricao)) pk_end,
           (:old.tipoendereco || '-' || (ll.descricao)) pk_end,
           f.codcaracprod || ' - ' || (d.descricao) caracteristica,
           f.codcaracprod || ' - ' || (d.descricao) caracteristica,
           f.tipopalpul || '-' || (t.descricao) estrupul,
           f.tipopalpul || '-' || (t.descricao) estrupul,
           l.codigo || ' - ' || (l.descricao) pulmao,
           l.codigo || ' - ' || (l.descricao) pulmao,
           DECODE (f.tipoprod,
                   '1',
                   '1 - GRANDEZA',
                   '2',
                   '2 - MIUDEZA',
                   '3',
                   '3 - LEVEZA',
                   '4',
                   '4 - PERIGOSO',
                   '5',
                   '5 - EMBALADO')
               tipoprod,
           DECODE (f.tipoprod,
                   '1',
                   '1 - GRANDEZA',
                   '2',
                   '2 - MIUDEZA',
                   '3',
                   '3 - LEVEZA',
                   '4',
                   '4 - PERIGOSO',
                   '5',
                   '5 - EMBALADO')
               tipoprod,
         VSPROGRAMA,
         VSMAQUINA,
         VSUSUARIO,
         SYSDATE,
         VSOPERACAO
    FROM   pcprodut p,
           pcfornec c,
           pcprodfilial f,
           pcendereco e,
           pccaracprod d,
           pctipopal l,
           pctipoestrutura t,
           pctipopal ll
   WHERE       p.codprod = f.codprod
           AND :new.codprod = p.codprod
           AND :new.codendereco = e.codendereco
           AND f.codfilial = e.codfilial
           AND d.codigo = f.codcaracprod
           AND l.codigo = f.tipopalpul
           AND :new.tipoestrutura = t.codigo
           AND ll.codigo = :new.tipoendereco
           AND p.codfornec = c.codfornec);

END;
