DECLARE
  VCONSTRAINT USER_INDEXES.INDEX_NAME%TYPE;
  CURSOR C_CONSTRAINTS(PCONSTRAINT VARCHAR2) IS
    SELECT A.CONSTRAINT_NAME, A.TABLE_NAME
      FROM USER_CONSTRAINTS A
     WHERE A.TABLE_NAME = 'PCDOCFISCAL_WS'
       AND A.CONSTRAINT_NAME = PCONSTRAINT 
       AND A.INDEX_NAME IS NOT NULL;  
       
  CURSOR C_INDEXES IS
    SELECT A.INDEX_NAME, B.COLUMN_NAME
      FROM USER_INDEXES A
         , USER_IND_COLUMNS B
     WHERE A.TABLE_NAME = 'PCDOCFISCAL_WS'
       AND A.INDEX_NAME = B.INDEX_NAME
       AND A.TABLE_NAME = B.TABLE_NAME
       AND A.INDEX_TYPE = 'NORMAL';
BEGIN
  FOR C IN C_INDEXES LOOP
    IF (C.COLUMN_NAME = 'ID') THEN
      VCONSTRAINT := C.INDEX_NAME;
      FOR C IN C_CONSTRAINTS(VCONSTRAINT) LOOP
        BEGIN
          EXECUTE IMMEDIATE 'ALTER TABLE ' || C.TABLE_NAME || ' DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
        EXCEPTION
          WHEN OTHERS THEN
            NULL;
        END;    
      END LOOP;   
             
      BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX ' || C.INDEX_NAME;
      EXCEPTION
        WHEN OTHERS THEN
          NULL;
      END;
    END IF;    
  END LOOP;
        
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCDOCFISCAL_WS DROP COLUMN ID';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
      
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCDOCFISCAL_WS ADD CONSTRAINT PCDOCFISCAL_WS_PK PRIMARY KEY (ESTADO, AMBIENTE, SERVICO) USING INDEX TABLESPACE TS_INDICE';        
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
 END;
