CREATE OR REPLACE VIEW VW_INT_C5_INCENTIVO AS 
( /*Rotina 357*/
  SELECT 
  357||P.CODPRECOPROM AS SEQREGRA,
  'PRECO FIXO' AS REGRA, 
  3 AS SEQTIPOCREDITO, 
  (CASE
    WHEN (SELECT L.CODPRECOPROM FROM PCPRECOPROMLOG L 
            WHERE L.CODPRECOPROM = P.CODPRECOPROM) > 0 THEN 'N'
    WHEN (SELECT P.CODPRECOPROM FROM PCPRECOPROM P 
            WHERE P.DTFIMVIGENCIA = (SELECT SYSDATE FROM DUAL)) > 0 THEN 'N'  
    ELSE 'S'
  END) AS ATIVO, 
  'G' AS TIPOREGRA,
  'S' AS CUMULATIVO,
  P.DTINICIOVIGENCIA DTAHORINICIO, 
  P.DTFIMVIGENCIA  DTAHORFIM 
 
FROM VW_INT_C5_PRECOFIXO_R357
UNION ALL
/*Rotina 561*/
SELECT 
     P.CODFILIAL||561||P.CODDESCONTO SEQREGRA,
     NVL(P.DESCRICAO, 'DESCONTO 561') REGRA,
     3 AS SEQTIPOCREDITO, 
     (CASE
        WHEN (L.CODDESCONTO IS NOT NULL) OR (P.DTFIM < TRUNC(SYSDATE)) THEN
             'N'
        ELSE 'S'
     END) ATIVO,
     
     'G' TIPOREGRA,
     'S' CUMULATIVO,
     P.DTINICIO DTAHORINICIO,
     P.DTFIM DTAHORFIM
FROM VW_INT_C5_CAB_DESC561
)