CREATE OR REPLACE VIEW VW_INT_C5_INCENTIVO AS 
( /*Rotina 357*/
  SELECT 
  SEQREGRA,
  REGRA, 
  SEQTIPOCREDITO, 
  ATIVO, 
  TIPOREGRA,
  CUMULATIVO,
  DTINICIOVIGENCIA DTAHORINICIO, 
  DTFIMVIGENCIA  DTAHORFIM 
FROM VW_INT_C5_PRECOFIXO_R357 
UNION ALL
/*Rotina 561*/
SELECT 
     SEQREGRA,
     REGRA,
     SEQTIPOCREDITO, 
     ATIVO,
     TIPOREGRA,
     CUMULATIVO,
     DTINICIO DTAHORINICIO,
     DTFIM DTAHORFIM
FROM VW_INT_C5_CAB_DESC561
)