CREATE OR REPLACE FUNCTION GET_VALORES_ITENS RETURN VARCHAR2 IS
    v_sql VARCHAR2(4000);
BEGIN
    v_sql := 'SELECT PCMOV.CODFILIALNF
      ,PCMOV.DTMOV
      ,PCMOV.NUMTRANSITEM
      ,PCMOV.CODOPER
      ,PCMOV.CODFISCAL
      ,NVL(PCDADOSXML.VPROD, PCMOV.PUNITCONT) AS PUNITCONT
      ,NVL(PCMOVCOMPLE.XML_QCOM, PCMOV.QTCONT) AS QTCONT
      ,NVL(PCDADOSXML.VDESC, PCMOV.VLDESCONTO) AS VLDESCONTO
      ,PCMOV.NUMTRANSVENDA
      ,PCMOV.NUMTRANSENT
      ,PCMOV.CODST
      ,PCMOV.SITTRIBUT
      ,PCMOV.GERAICMSLIVROFISCAL
      ,NVL(PCDADOSXML.VBC, PCMOV.BASEICMS) AS BASEICMS
      ,PCMOV.PERCICM
      ,NVL(PCDADOSXML.VICMS, PCMOVCOMPLE.VLICMS) AS VLICMS
      ,PCMOV.PERCSUFRAMA
      ,PCMOV.VLDESCICMISENCAO
      ,PCMOVCOMPLE.VLICMSDESONERACAO
      ,NVL(PCDADOSXML.VBCST, PCMOV.BASEICST) AS BASEICST
      ,PCMOV.PERCST
      ,NVL(PCDADOSXML.VICMSST, PCMOV.ST) AS VICMSST
      ,PCMOVCOMPLE.CODTRIBPISCOFINS
      ,PCMOV.VLBASEPISCOFINS
      ,PCMOV.PERPIS
      ,PCMOV.PERCOFINS
      ,PCMOV.VLPIS
      ,PCMOV.VLCOFINS
      ,PCMOVCOMPLE.CODSITTRIBIPI
      ,PCMOV.VLBASEIPI
      ,PCMOV.VLIPI
  FROM PCMOV
 INNER JOIN PCMOVCOMPLE
    ON PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM
  LEFT JOIN PCDADOSXML
    ON PCMOV.NUMTRANSITEM = PCDADOSXML.NUMTRANSITEM
 WHERE PCMOV.DTMOV BETWEEN TRUNC(SYSDATE - 90) AND :DATAFINAL';

    RETURN v_sql;
END;
