CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_CABECALHO AS (
  SELECT
    PCPROMC.CODIGO SEQCOMBO,
    PCPROMC.CODFILIAL NROEMPRESA,
    PCPROMC.DESCRICAO,
    PCPROMC.DTINICIO DTAINICIO,
    PCPROMC.DTFIM DTAFIM,
    1 TIPO,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
          AND DTINATIVACAO IS NULL THEN 'S'
       ELSE 'N'
     END
    ) ATIVO
  FROM
    PCPROMC
  INNER JOIN PCPRODUT
  ON (PCPRODUT.CODPROD = PCPROMC.CODPROD)
  WHERE
    TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
    AND nvl(PCPROMC.DTALTERC5, PKG_SINC_PDV_CONSINCO.get_inicio_execucao) BETWEEN PKG_SINC_PDV_CONSINCO.get_inicio_execucao AND PKG_SINC_PDV_CONSINCO.get_final_execucao
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_ITENS AS (
--ITENS REFERENTES A CAMPANHA DE BRINDE     
  SELECT
    CODIGO SEQCOMBO,
    TO_NUMBER(PCPROMI.CODPROD || CODIGO || PCPROMI.QT || '1') SEQITEM, --Concatenação com 1 para evitar erro de PK, já que o produto brinde pode fazer parte da campanha também
    TO_NUMBER(PCPROMI.CODPROD || PCPROMC.CODFILIAL) SEQPRODUTO,
    PCPROMI.CODPROD,
    'N' TIPOITEM,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN PCPROMC.DTINICIO AND PCPROMC.DTFIM AND PCPROMC.DTINATIVACAO IS NULL 
       THEN 
          'S'  
       ELSE 
          'N'
     END
    ) ATIVO,
    PCPROMI.QT QTDE,
    0 PRECO,
    0 PERCDESCONTO
  FROM
    PCPROMI
  INNER JOIN PCPROMC 
  USING (CODIGO)
  
  INNER JOIN PCPRODUT PRODUTOCABECALHO 
  ON (PRODUTOCABECALHO.CODPROD = PCPROMC.CODPROD)
  
  INNER JOIN PCPRODUT PRODUTOITEM 
  ON (PRODUTOITEM.CODPROD = PCPROMI.CODPROD)
  
  WHERE
    TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
    AND NVL(PRODUTOCABECALHO.TIPOMERC, 'L') = 'L'
    AND NVL(PRODUTOITEM.TIPOMERC, 'L') = 'L'
    AND NVL(PCPROMI.DTALTERC5, PKG_SINC_PDV_CONSINCO.get_final_execucao) BETWEEN PKG_SINC_PDV_CONSINCO.get_inicio_execucao AND PKG_SINC_PDV_CONSINCO.get_final_execucao

  UNION ALL

-- ITEM REFERENTE AO BRINDE
  SELECT
    PCPROMC.CODIGO SEQCOMBO,
    TO_NUMBER(PCPROMC.CODPROD || PCPROMC.CODIGO || PCPROMC.QTBRINDE || '0') SEQITEM, --Concatenação com 0 para evitar erro de PK, já que o produto brinde pode fazer parte da campanha tambem
    TO_NUMBER(PCPROMC.CODPROD || PCPROMC.CODFILIAL) SEQPRODUTO,
    PCPROMC.CODPROD,
    'P' TIPOITEM,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM AND DTINATIVACAO IS NULL 
       THEN 
          'S'
       ELSE 
          'N'
     END
    ) ATIVO,
    PCPROMC.QTBRINDE QTDE,
    (
      CASE
        WHEN PCPROMC.TIPODESCONTOBRINDE = 'B' THEN 0.01
        ELSE 0
      END
    ) PRECO,
    (
      CASE
        WHEN PCPROMC.TIPODESCONTOBRINDE = 'B' THEN 99.99
        ELSE PCPROMC.DESCONTOPARCIAL
      END
    ) PERCDESCONTO
  FROM
    PCPROMC
  INNER JOIN PCPRODUT
  ON (PCPRODUT.CODPROD = PCPROMC.CODPROD)
  WHERE
    TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
    AND NVL(PCPROMC.DTALTERC5, PKG_SINC_PDV_CONSINCO.get_final_execucao) BETWEEN PKG_SINC_PDV_CONSINCO.get_inicio_execucao AND PKG_SINC_PDV_CONSINCO.get_final_execucao
)