/*
  BRINDE MANUAL
*/
CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_CABECALHO AS
(
  SELECT
    PCPROMC.CODIGO SEQCOMBO,
    PCPROMC.CODFILIAL NROEMPRESA,
    PCPROMC.DESCRICAO,
    PCPROMC.DTINICIO DTAINICIO,
    PCPROMC.DTFIM DTAFIM,
    1 TIPO,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
          AND DTINATIVACAO IS NULL THEN 'S'
       ELSE 'N'
     END
    ) ATIVO
  FROM
    PCPROMC

  INNER JOIN PCDEPARAEMBALAGENSC5
  ON (PCDEPARAEMBALAGENSC5.CODAUXILIAR = PCPROMC.CODAUXILIAR)

  INNER JOIN PCPRODUT
  ON (PCPRODUT.CODPROD = PCPROMC.CODPROD),
  (
    SELECT min(s.ultimaexecucao) ultimaexecucao
    FROM pccontroleconsinco s
    WHERE upper(s.objetoreferencia) IN (
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOEMPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOITEM',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOGRUPO'
    )
  ) D, VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE
    TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
    AND PCPROMC.CODFILIAL = C5.CODFILIAL
    AND NVL(PCPROMC.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
    AND PCPROMC.TIPODESCONTOBRINDE = 'D'
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_ITENS AS (
  SELECT 
    DENSE_RANK() OVER (PARTITION BY P.SEQCOMBO ORDER BY P.IDREF, P.TIPOITEM) SEQGRUPO,
    P.*
  FROM 
  (
    --ITENS GATILHO
    SELECT 
      PCPROMI.CODIGO SEQCOMBO,
      CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN PRODUTO_FAMILIA.CODPROD ELSE PCPROMI.CODPROD END SEQITEM,
      CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN PRODUTO_MIDDLE.SEQFAMILIA ELSE null END SEQFAMILIA, 
      CASE WHEN PCPROMC.PRODUTOPRINC = 'N' THEN DEPARA.SEQPRODUTO ELSE null END SEQPRODUTO,
      'N' TIPOITEM,
      (
        CASE
          WHEN TRUNC(SYSDATE) BETWEEN TRUNC(PCPROMC.DTINICIO) AND TRUNC(PCPROMC.DTFIM) AND PCPROMC.DTINATIVACAO IS NULL
          THEN
              'S'
          ELSE
              'N'
        END
      ) ATIVO,
      CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN 1 ELSE PCPROMI.QT END QTDE,
      CASE WHEN (PCPROMC.PRODUTOPRINC = 'S') AND (PRODUTO_FAMILIA.CODPROD = PCPROMI.CODPROD AND PCPROMI.CODAUXILIAR = EMBITEM.CODAUXILIAR) THEN PCPROMI.QT ELSE 0 END QTDEGRUPO,
      0 PRECO,
      0 PERCDESCONTO,
      PRODUTO_FAMILIA.CODPRODPRINC,
      PCPROMC.PRODUTOPRINC,
      EMBITEM.QTUNIT QTDEMBALAGEM,
      PCPROMI.CODAUXILIAR IDREF
    FROM 
      PCPROMI ,
      PCPROMC ,
      PCPRODUT PRODUTO_ITEM,
      PCPRODUT PRODUTO_FAMILIA,
      PCDEPARAPRODC5 DEPARA,
      PCEMBALAGEM EMBITEM,
      MONITORPDVMIDDLE.TB_PRODUTO PRODUTO_MIDDLE,
      (
          SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
          WHERE UPPER(S.OBJETOREFERENCIA) IN (
            'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBO',
            'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOEMPRESA',
            'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOITEM',
            'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOGRUPO'
          )
        ) D, 
      VW_INT_C5_OBTER_FILIAIS_C5 FILIAL
    WHERE 
      PCPROMI.CODPROD = PRODUTO_ITEM.CODPROD
      
      AND PCPROMC.CODIGO = PCPROMI.CODIGO
      AND PCPROMC.CODFILIAL = FILIAL.CODFILIAL
      AND PCPROMC.TIPODESCONTOBRINDE = 'D'

      AND (
        (PCPROMC.PRODUTOPRINC = 'S'
          AND PRODUTO_FAMILIA.CODPRODPRINC = PRODUTO_ITEM.CODPRODPRINC
          AND (EMBITEM.CODAUXILIAR = DEPARA.CODAUXILIAR OR DEPARA.CODAUXILIAR = 0))
        OR 
        (PCPROMC.PRODUTOPRINC = 'N'
          AND PRODUTO_FAMILIA.CODPROD = PRODUTO_ITEM.CODPROD
          AND EMBITEM.CODAUXILIAR = PCPROMI.CODAUXILIAR
        )
      )
      AND DEPARA.CODPROD = PRODUTO_FAMILIA.CODPROD
      AND DEPARA.ATIVO = 'S'
      
        
      AND EMBITEM.CODPROD = DEPARA.CODPROD
      AND EMBITEM.CODFILIAL = PCPROMC.CODFILIAL
      AND PRODUTO_MIDDLE.SEQPRODUTO = DEPARA.SEQPRODUTO 
      AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
      AND (NVL(PCPROMI.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR NVL(PCPROMC.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO)

     UNION ALL

    -- ITEM REFERENTE AO BRINDE
      SELECT
        PCPROMC.CODIGO SEQCOMBO,
        1 SEQITEM, --PALIATIVO
        --PCDEPARAEMBALAGENSC5.SEQPRODUTO,
        NULL SEQFAMILIA,
        PCDEPARAPRODC5.SEQPRODUTO,/*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
        'P' TIPOITEM,

        (
        CASE
          WHEN TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM) AND DTINATIVACAO IS NULL
          THEN
              'S'
          ELSE
              'N'
        END
        ) ATIVO,
        CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN 1 ELSE PCPROMC.QTBRINDE END QTDE,
        CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN PCPROMC.QTBRINDE ELSE NULL END QTDEGRUPO,
        (
          CASE
            WHEN PCPROMC.DESCONTOPARCIAL = 100 THEN 0.01
            ELSE 0
          END
        ) PRECO,
        (
          CASE
            WHEN PCPROMC.DESCONTOPARCIAL = 100 THEN 99.99
            ELSE PCPROMC.DESCONTOPARCIAL
          END
        ) PERCDESCONTO,
        NULL CODPRODPRINC,
        PCPROMC.PRODUTOPRINC,
      EMBITEM.QTUNIT QTDEMBALAGEM,
        PCPROMC.CODAUXILIAR IDREF
      FROM
        PCPROMC,
        PCPRODUT,
        PCEMBALAGEM EMBITEM,
        --PCDEPARAEMBALAGENSC5,
        PCDEPARAPRODC5,
      (
        SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE UPPER(S.OBJETOREFERENCIA) IN (
          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBO',
          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOEMPRESA',
          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOITEM',
          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOGRUPO'
        )
      ) D, VW_INT_C5_OBTER_FILIAIS_C5 C5

      WHERE
        PCPRODUT.CODPROD = PCPROMC.CODPROD
      AND EMBITEM.CODPROD = PCPRODUT.CODPROD
        AND EMBITEM.CODFILIAL = C5.CODFILIAL
        AND PCPROMC.CODAUXILIAR = EMBITEM.CODAUXILIAR
        --AND PCPROMC.CODAUXILIAR = PCDEPARAEMBALAGENSC5.CODAUXILIAR
        AND ((PCPROMC.CODAUXILIAR = PCDEPARAPRODC5.CODAUXILIAR/*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
        AND PCPROMC.CODPROD = PCDEPARAPRODC5.CODPROD /*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
      AND PCDEPARAPRODC5.ATIVO = 'S')
      OR (PCDEPARAPRODC5.CODAUXILIAR = 0
        AND PCPROMC.CODPROD = PCDEPARAPRODC5.CODPROD 
      AND PCDEPARAPRODC5.ATIVO = 'S'))
    
      AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
      AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
      AND NVL(PCPROMC.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
      AND PCPROMC.TIPODESCONTOBRINDE = 'D'
      AND PCPROMC.CODFILIAL = C5.CODFILIAL
  ) P 
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_ITEM_GRUPO AS 
(
  SELECT 
    SEQCOMBO,
    SEQGRUPO,
    SUM(QTDEGRUPO) QTDE,
    CASE WHEN MAX(SEQITEM) = 1
      THEN
        'ITEM PROMOCIONAL'
      ELSE
        'ITENS GATILHO FAMILIA ' || CODPRODPRINC
      END GRUPO,
      MAX(ATIVO) ATIVO,
      CODPRODPRINC IDREF
  FROM VW_INT_C5_BRINDE_ITENS 
  WHERE PRODUTOPRINC = 'S'
    AND SEQCOMBO = 105
  GROUP BY SEQCOMBO, SEQGRUPO, CODPRODPRINC
)

\

/*
  BRINDE AUTOMATICO
*/
CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_CABECALHO_AUT AS
(
  SELECT
    PCPROMC.CODIGO SEQPROMSURPRESA,
    PCPROMC.CODFILIAL NROEMPRESA,
    PCPROMC.DESCRICAO,
    TO_DATE(PCPROMC.DTINICIO || ' 00:00:01','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORINICIO,
    TO_DATE(PCPROMC.DTFIM || ' 23:59:59','DD-MM-YY HH24:MI:SS','NLS_DATE_LANGUAGE = AMERICAN') DTAHORFIM,
    'C' TIPOSURPRESA,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
          AND DTINATIVACAO IS NULL THEN 'S'
       ELSE 'N'
     END
    ) ATIVO
  FROM
    PCPROMC

  --INNER JOIN PCDEPARAEMBALAGENSC5
  INNER JOIN PCDEPARAPRODC5
  --ON (PCDEPARAEMBALAGENSC5.CODAUXILIAR = PCPROMC.CODAUXILIAR)
  ON((PCDEPARAPRODC5.CODPROD = PCPROMC.CODPROD AND PCDEPARAPRODC5.CODAUXILIAR = PCPROMC.CODAUXILIAR AND PCDEPARAPRODC5.ATIVO = 'S' ) 
  OR (PCDEPARAPRODC5.CODPROD = PCPROMC.CODPROD AND PCDEPARAPRODC5.CODAUXILIAR = 0 AND PCDEPARAPRODC5.ATIVO = 'S'))

  INNER JOIN PCPRODUT
  ON (PCPRODUT.CODPROD = PCPROMC.CODPROD),
  /*(
    SELECT min(s.ultimaexecucao) ultimaexecucao
    FROM pccontroleconsinco s
    WHERE upper(s.objetoreferencia) IN (
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAEMPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAPERIODO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAITEM'
    )
  ) D, */
  VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE
    TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
  --  AND NVL(PCPROMC.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao
    AND PCPROMC.TIPODESCONTOBRINDE = 'B'
    AND PCPROMC.CODFILIAL = C5.CODFILIAL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_ITENS_AUT AS(
--ITENS REFERENTES A CAMPANHA DE BRINDE

SELECT
  TAB_BRINDE.SEQPROMSURPRESA,
  
  CASE
    WHEN D.CODAUXILIAR > 0 THEN
         D.SEQPRODUTO||'1'
    ELSE P.CODPROD||'1'
  END SEQITEM,
 
  P.CODPROD IDREF,
  TAB_BRINDE.SEQGRUPO, /*SERÁ A CHAVE ESTRANGEIRA DA TABELA PROMSURPRESAGRUPO*/
  D.SEQFAMILIA, 
  NULL SEQPRODUTO,
  
  CASE
    WHEN (P.CODPROD = TAB_BRINDE.IDREF) AND (TAB_BRINDE.CODAUXILIAR = D.CODAUXILIAR) OR
         (P.CODPROD = TAB_BRINDE.IDREF) AND (D.CODAUXILIAR = 0) THEN
         'S'
    ELSE 'N'     
  END  EXISTEPCPROMI,  

  TAB_BRINDE.TIPOITEM,
  TAB_BRINDE.ATIVO,
  TAB_BRINDE.QTDE,
  TAB_BRINDE.QTDEGRUPO,
  TAB_BRINDE.CODPRODPRINC,
  TAB_BRINDE.PRODUTOPRINC,
  (SELECT E.QTUNIT FROM PCEMBALAGEM E WHERE DECODE(D.CODAUXILIAR, 0, TAB_BRINDE.CODAUXILIAR, D.CODAUXILIAR) = E.CODAUXILIAR AND E.CODFILIAL = TAB_BRINDE.CODFILIAL) QTDEMBALAGEM
FROM
  (
   SELECT
     PCPROMC.CODIGO SEQPROMSURPRESA,
     PRODUTOITEM.CODPROD || '1' SEQITEM, --Concatenação com 1 para evitar erro de PK, já que o produto brinde pode fazer parte da campanha também
     PRODUTOITEM.CODPROD IDREF,
     
     CASE
       WHEN PCPROMC.PRODUTOPRINC = 'S' THEN
            ROW_NUMBER() OVER(partition by PCPROMC.CODPROPRINC order BY PCPROMI.ROWID)
       ELSE NULL
     END  SEQGRUPO,
             
     C5.CODFILIAL,
     EMBALAGEMITEM.CODAUXILIAR,
   
     CASE 
      WHEN (PCPROMC.PRODUTOPRINC = 'S') AND (PRODUTOITEM.CODPROD = PCPROMI.CODPROD) THEN
           NVL(PRODUTOITEM.CODPRODPRINC, PRODUTOITEM.CODPROD)
      ELSE NULL 
     END SEQFAMILIA,
    
     CASE 
      WHEN (PCPROMC.PRODUTOPRINC <> 'S') OR (PRODUTOITEM.CODPROD <> PCPROMI.CODPROD) THEN 
           PRODUTOITEM.CODPROD
      ELSE NULL 
     END SEQPRODUTO,

     CASE 
       WHEN (PRODUTOITEM.CODPROD = PCPROMI.CODPROD) AND (EMBALAGEMITEM.CODAUXILIAR = PCPROMI.CODAUXILIAR) THEN 
            'S' 
       ELSE 'N' 
     END EXISTEPCPROMI,  
     
     'N' TIPOITEM,
     (
      CASE
       WHEN TRUNC(SYSDATE) BETWEEN TRUNC(PCPROMC.DTINICIO) AND TRUNC(PCPROMC.DTFIM) AND PCPROMC.DTINATIVACAO IS NULL
       THEN
          'S'
       ELSE
          'N'
      END
     ) ATIVO,

     CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN 1 ELSE  PCPROMI.QT END QTDE,
     CASE WHEN (PCPROMC.PRODUTOPRINC = 'S') AND (PRODUTOITEM.CODPROD = PCPROMI.CODPROD) THEN PCPROMI.QT ELSE 0 END QTDEGRUPO,
     PRODUTOITEM.CODPRODPRINC,
     PCPROMC.PRODUTOPRINC,
     EMBALAGEMITEM.QTUNIT QTDEMBALAGEM
   FROM
     PCPROMC,
     PCPROMI,
     PCPRODUT PRODUTOITEM,
     PCEMBALAGEM EMBALAGEMITEM,
    /* (SELECT min(s.ultimaexecucao) ultimaexecucao
      FROM pccontroleconsinco s
      WHERE upper(s.objetoreferencia) IN (
                                          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESA',
                                          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAEMPRESA',
                                          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAPERIODO',
                                          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAGRUPO',
                                          'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAITEM')
      ) D,*/
      VW_INT_C5_OBTER_FILIAIS_C5 C5
   WHERE PCPROMC.CODIGO = PCPROMI.CODIGO
     AND PCPROMC.TIPODESCONTOBRINDE = 'B'
     AND PCPROMC.CODFILIAL = C5.CODFILIAL
     AND EMBALAGEMITEM.CODFILIAL = C5.CODFILIAL
     AND PCPROMC.CODFILIAL = EMBALAGEMITEM.CODFILIAL
     AND PRODUTOITEM.CODPROD = PCPROMI.CODPROD
     /*AND ((PCPROMC.PRODUTOPRINC = 'S' AND PRODUTOITEM.CODPRODPRINC = PCPROMI.CODPROD) OR
          (PCPROMC.PRODUTOPRINC <> 'S' AND PRODUTOITEM.CODPROD = PCPROMI.CODPROD)
         )*/
     AND EMBALAGEMITEM.CODPROD = PRODUTOITEM.CODPROD    
     AND EMBALAGEMITEM.CODAUXILIAR = PCPROMI.CODAUXILIAR
     AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
     AND NVL(PRODUTOITEM.TIPOMERC, 'L') not in ('CB', 'KT')
    /* AND (NVL(PCPROMI.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(PCPROMC.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO OR
          NVL(EMBALAGEMITEM.DTALTERC5, D.ultimaexecucao) >= D.ultimaexecucao OR
          NVL(PRODUTOITEM.DTALTERC5, D.ultimaexecucao) >= D.ultimaexecucao)*/
     
  ) TAB_BRINDE,
    PCPRODUT P,
    PCDEPARAPRODC5 D
WHERE D.ATIVO = 'S'
AND   (
         (
           (TAB_BRINDE.PRODUTOPRINC = 'S') AND  
           ( (P.CODPRODPRINC = TAB_BRINDE.IDREF) OR (P.CODPROD = TAB_BRINDE.IDREF) OR (TAB_BRINDE.CODPRODPRINC = P.CODPRODPRINC ))
         )
         OR 
         (
           ((TAB_BRINDE.PRODUTOPRINC <> 'S') AND (P.CODPROD = TAB_BRINDE.IDREF))
         )
      )
  
AND   (/* LISTAR TODAS AS EMBALAGENS DESMEMBRADAS*/
       --(TAB_BRINDE.PRODUTOPRINC = 'S') AND (D.CODPROD = TAB_BRINDE.IDREF) OR 
       (TAB_BRINDE.PRODUTOPRINC = 'S') AND (D.CODPROD = P.CODPROD) OR
       /*LISTAR SOMENTE AS EMBALAGENS QUE CONSTAM NA PCPROMI*/
       (TAB_BRINDE.PRODUTOPRINC <> 'S') AND ((D.CODPROD = TAB_BRINDE.IDREF) AND (D.CODAUXILIAR = TAB_BRINDE.CODAUXILIAR) OR
                                             (D.CODPROD = TAB_BRINDE.IDREF) AND (D.CODAUXILIAR = 0)
                                            )
      )   

UNION ALL

-- ITEM REFERENTE AO BRINDE
SELECT
    PCPROMC.CODIGO SEQPROMSURPRESA,
    PCPROMC.CODPROD || '0' SEQITEM, --Concatenação com 0 para evitar erro de PK, já que o produto brinde pode fazer parte da campanha tambem
    PCPROMC.CODAUXILIAR IDREF,
    
    CASE
      WHEN PCPROMC.PRODUTOPRINC = 'S' THEN
           0 
      ELSE NULL
    END SEQGRUPO,
    
    NULL SEQFAMILIA,
    PCDEPARAPRODC5.SEQPRODUTO,/*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
    'S' EXISTEPCPROMI,
    'B' TIPOITEM,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM) AND DTINATIVACAO IS NULL
       THEN
          'S'
       ELSE
          'N'
     END
    ) ATIVO,
    PCPROMC.QTBRINDE QTDE,
    CASE WHEN PCPROMC.PRODUTOPRINC = 'S' THEN PCPROMC.QTBRINDE ELSE NULL END QTDEGRUPO,
    NULL CODPRODPRINC,
    PCPROMC.PRODUTOPRINC,
    EMBALAGEMCABECALHO.QTUNIT QTDEMBALAGEM
FROM
    PCPROMC,
    PCPRODUT,
    --PCDEPARAEMBALAGENSC5, 
    PCDEPARAPRODC5,/*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
    PCEMBALAGEM EMBALAGEMCABECALHO,
   /*(
    SELECT min(s.ultimaexecucao) ultimaexecucao
    FROM pccontroleconsinco s
    WHERE upper(s.objetoreferencia) IN (
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAEMPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAPERIODO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAGRUPO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PROMSURPRESAITEM')
   ) D, */
   VW_INT_C5_OBTER_FILIAIS_C5 C5
  
WHERE
    PCPRODUT.CODPROD = PCPROMC.CODPROD
    AND EMBALAGEMCABECALHO.CODAUXILIAR = PCPROMC.CODAUXILIAR AND EMBALAGEMCABECALHO.CODFILIAL = PCPROMC.CODFILIAL
    --AND PCPROMC.CODAUXILIAR = PCDEPARAEMBALAGENSC5.CODAUXILIAR
    AND ((PCPROMC.CODAUXILIAR = PCDEPARAPRODC5.CODAUXILIAR /*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
    AND PCPROMC.CODPROD = PCDEPARAPRODC5.CODPROD  /*REFATORACAO SEQFAMILIA/SEQPRODUTO*/
	  AND PCDEPARAPRODC5.ATIVO = 'S') 
	  OR (PCDEPARAPRODC5.CODAUXILIAR = 0 
    AND PCPROMC.CODPROD = PCDEPARAPRODC5.CODPROD  
	  AND PCDEPARAPRODC5.ATIVO = 'S'))
    AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
    /*AND (NVL(PCPROMC.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao
        OR NVL(EMBALAGEMCABECALHO.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao
		OR NVL(PCPRODUT.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao)*/
    AND PCPROMC.TIPODESCONTOBRINDE = 'B'
    AND PCPROMC.CODFILIAL = C5.CODFILIAL
)

\

CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_GRUPO_AUT AS 
(
  SELECT
    SEQPROMSURPRESA,
    SEQGRUPO,
    SUM(QTDEGRUPO) QTDE,
    
    CASE
      WHEN SEQGRUPO = 0 THEN
           'ITEM PROMOCIONAL' 
      ELSE 'ITENS GATILHO FAMILIA ' || CODPRODPRINC
    END GRUPO,

    MAX(ATIVO) ATIVO,
    CODPRODPRINC IDREF
  FROM VW_INT_C5_BRINDE_ITENS_AUT
  WHERE PRODUTOPRINC = 'S'
  AND  EXISTEPCPROMI = 'S'
  GROUP BY SEQPROMSURPRESA, CODPRODPRINC, SEQGRUPO
)