CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_CABECALHO AS (
  SELECT
    PCPROMC.CODIGO SEQCOMBO,
    PCPROMC.CODFILIAL NROEMPRESA,
    PCPROMC.DESCRICAO,
    PCPROMC.DTINICIO DTAINICIO,
    PCPROMC.DTFIM DTAFIM,
    1 TIPO,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
          AND DTINATIVACAO IS NULL THEN 'S'
       ELSE 'N'
     END
    ) ATIVO
  FROM
    PCPROMC
  INNER JOIN PCPRODUT
  ON (PCPRODUT.CODPROD = PCPROMC.CODPROD),
  (
    SELECT min(s.ultimaexecucao) ultimaexecucao
    FROM pccontroleconsinco s
    WHERE upper(s.objetoreferencia) IN (
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOEMPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOITEM'
    )
  ) D
  WHERE
    TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
    AND NVL(PCPROMC.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao 

)

\

CREATE OR REPLACE VIEW VW_INT_C5_BRINDE_ITENS AS(
--ITENS REFERENTES A CAMPANHA DE BRINDE
  SELECT
    CODIGO SEQCOMBO,
    TO_NUMBER(PCPROMI.CODPROD || CODIGO || PCPROMI.QT || '1') SEQITEM, --Concatenação com 1 para evitar erro de PK, já que o produto brinde pode fazer parte da campanha também
    --TO_NUMBER(PCPROMI.CODPROD || PCPROMC.CODFILIAL) SEQPRODUTO,
    PCPROMI.CODAUXILIAR idref,
    PCDEPARAEMBALAGENSC5.SEQPRODUTO,
--    ora_hash(PCPROMI.Codauxiliar, 2147483647) seqproduto,
    PCPROMI.CODPROD,
    'N' TIPOITEM,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN PCPROMC.DTINICIO AND PCPROMC.DTFIM AND PCPROMC.DTINATIVACAO IS NULL
       THEN
          'S'
       ELSE
          'N'
     END
    ) ATIVO,
    PCPROMI.QT QTDE,
    0 PRECO,
    0 PERCDESCONTO
  FROM
    PCPROMI
  INNER JOIN PCPROMC
  USING (CODIGO)
  
  INNER JOIN PCDEPARAEMBALAGENSC5
  ON (PCPROMI.CODAUXILIAR = PCDEPARAEMBALAGENSC5.CODAUXILIAR)
  
  INNER JOIN PCPRODUT PRODUTOCABECALHO
  ON (PRODUTOCABECALHO.CODPROD = PCPROMC.CODPROD)

  INNER JOIN PCPRODUT PRODUTOITEM
  ON (PRODUTOITEM.CODPROD = PCPROMI.CODPROD),
  (
    SELECT min(s.ultimaexecucao) ultimaexecucao
    FROM pccontroleconsinco s
    WHERE upper(s.objetoreferencia) IN (
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOEMPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOITEM'
    )
  ) D

  WHERE
    TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
    AND NVL(PRODUTOCABECALHO.TIPOMERC, 'L') = 'L'
    AND NVL(PRODUTOITEM.TIPOMERC, 'L') = 'L'
    AND (NVL(PCPROMI.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao or NVL(PCPROMC.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao)

  UNION ALL

-- ITEM REFERENTE AO BRINDE
  SELECT
    PCPROMC.CODIGO SEQCOMBO,
    TO_NUMBER(PCPROMC.CODPROD || PCPROMC.CODIGO || PCPROMC.QTBRINDE || '0') SEQITEM, --Concatenação com 0 para evitar erro de PK, já que o produto brinde pode fazer parte da campanha tambem
    --TO_NUMBER(PCPROMC.CODPROD || PCPROMC.CODFILIAL) SEQPRODUTO,
    PCPROMC.CODAUXILIAR idref,
    PCDEPARAEMBALAGENSC5.SEQPRODUTO,
--    ora_hash(PCPROMc.Codauxiliar, 2147483647) SEQPRODUTO,
    PCPROMC.CODPROD,
    'P' TIPOITEM,
    (
     CASE
       WHEN TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM AND DTINATIVACAO IS NULL
       THEN
          'S'
       ELSE
          'N'
     END
    ) ATIVO,
    PCPROMC.QTBRINDE QTDE,
    (
      CASE
        WHEN PCPROMC.TIPODESCONTOBRINDE = 'B' or PCPROMC.DESCONTOPARCIAL = 100 THEN 0.01
        ELSE 0
      END
    ) PRECO,
    (
      CASE
        WHEN PCPROMC.TIPODESCONTOBRINDE = 'B' or PCPROMC.DESCONTOPARCIAL = 100 THEN 99.99
        ELSE PCPROMC.DESCONTOPARCIAL
      END
    ) PERCDESCONTO
  FROM
    PCPROMC
  INNER JOIN PCPRODUT
  ON (PCPRODUT.CODPROD = PCPROMC.CODPROD)
  
  INNER JOIN PCDEPARAEMBALAGENSC5
  ON (PCPROMC.CODAUXILIAR = PCDEPARAEMBALAGENSC5.CODAUXILIAR),
  
  (
    SELECT min(s.ultimaexecucao) ultimaexecucao
    FROM pccontroleconsinco s
    WHERE upper(s.objetoreferencia) IN (
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBO',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOEMPRESA',
      'PKG_SINC_PDV_CONSINCO.CARREGA_TB_COMBOITEM'
    )
  ) D
  WHERE
    TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
    AND NVL(PCPRODUT.TIPOMERC, 'L') = 'L'
    AND NVL(PCPROMC.dtalterc5, D.ultimaexecucao) >= D.ultimaexecucao

)
