CREATE OR REPLACE VIEW SQL_NFE_CABECALHO_ENTRADA AS 
SELECT PCNFENT.NUMTRANSENT AS NUM_TRANSACAO
      ,PCNFENT.CHAVENFE
      ,NVL(PCNFENT.NUMVIAS,
           0) + 1 AS NUM_IMPRESSAO
      ,PCNFENT.CODCONT
      ,0 AS MOVIMENTO
      ,NVL(PCNFENT.TIPOEMISSAO,
           '0') AS TIPO_EMISSAO
      ,PCFILIAL.CODIGO AS CODIGO_FILIAL
      ,NVL(PCNFENT.RECIBODPEC,
           PCNFENT.PROTOCOLONFE) AS PROTOCOLONFE
      ,NVL(PCNFENT.DTHORARECIBODPEC,
           NVL(PCNFENT.DTHORAAUTORIZACAOSEFAZ,
               PCNFENT.DTHORANFE)) AS DTHORA_AUTORIZACAO
      ,DECODE(NVL(PCNFENT.TIPOIMPRESSAO, NVL(PCFILIAL.TIPODANFE, 'R')),
              'R',
              '1',
              '2') AS TIPO_DANFE
      ,NULL AS NUM_TRANSACAO_DEV
      ,'2' AS TIPO_PGTO
      ,REPLACE(TRANSLATE(PCNFENT.SERIE,
                         TRIM(TRANSLATE(PCNFENT.SERIE,
                                        '1234567890',
                                        ' ')) || ' ',
                         ' '),
               ' ',
               '') SERIE
      ,NVL(REPLACE(TRANSLATE(PCFILIAL.SERIENFESCAN,
                             TRANSLATE(PCFILIAL.SERIENFESCAN,
                                       '1234567890',
                                       ' '),
                             ' '),
                   ' ',
                   ''),
           '0') SERIE_SCAN
      ,PCNFENT.DTEMISSAO AS DATA_EMISSAO
      ,PCNFENT.DTSAIDA AS DATA_SAIDA
      ,NULL AS DATA_SAIDA_DANFE
      ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('ENVIARDATAENTREGAXML', PCFILIAL.CODIGO), 'S'),
                    'S',
                    PCNFENT.DTENT,
                    NULL)
       AS DATA_ENTREGA 
      ,PCNFENT.NUMNOTA AS NUMERO_NOTA
      ,CASE WHEN (PCNFENT.FINALIDADENFE = 'A') THEN
        DECODE(NVL(NATOPERNFE, ''), '', NVL((SELECT MIN(PCCFO.DESCCFO) DESCCFO
                                              FROM PCCFO
                                                   ,PCMOV
                                             WHERE  PCMOV.CODFISCAL = PCCFO.CODFISCAL
                                               AND  PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT),
                                           (SELECT MIN(PCCFO.DESCCFO) DESCCFO
                                            FROM   PCCFO, PCNFBASE
                                            WHERE  PCNFBASE.NUMTRANSENT = PCNFENT.NUMTRANSENT
                                            AND PCNFBASE.CODCONT  = PCNFENT.CODCONT
                                            AND PCNFBASE.CODFISCAL = PCCFO.CODFISCAL)) , NATOPERNFE)
       ELSE
         NVL( NVL((SELECT MIN(PCCFO.DESCCFO) DESCCFO
              FROM PCCFO
                   ,PCMOV
             WHERE  PCMOV.CODFISCAL = PCCFO.CODFISCAL
               AND  PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT),
        (SELECT MIN(PCCFO.DESCCFO) DESCCFO
              FROM PCCFO
                   ,PCMOVCIAP
             WHERE  PCMOVCIAP.CODFISCAL = PCCFO.CODFISCAL
               AND  PCMOVCIAP.NUMTRANSENT = PCNFENT.NUMTRANSENT)),
           (SELECT MIN(PCCFO.DESCCFO) DESCCFO
            FROM   PCCFO, PCNFBASE
            WHERE  PCNFBASE.NUMTRANSENT = PCNFENT.NUMTRANSENT
            AND PCNFBASE.CODCONT  = PCNFENT.CODCONT
            AND PCNFBASE.CODFISCAL = PCCFO.CODFISCAL))
       END AS NATUREZA_OP
      ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('FIL_OPTANTESIMPLESNAC',
                                                PCFILIAL.CODIGO),
                  'N'),
              'N',
              3,
              'S',
              1,
              'E',
              2,
              3) CRT
       -----------------------EMITENTE-----------------------
      ,EMITENTE.CGC AS CNPJ_E
      ,EMITENTE.FORNECEDOR AS RAZAO_SOCIAL_E
      ,EMITENTE.FANTASIA AS NOME_FANTASIA_E
      ,EMITENTE.ENDER AS LOGRADOURO_E
      ,NVL(EMITENTE.NUMEROEND,
           'S\N') AS NUMERO_E
      ,EMITENTE.COMPLEMENTOEND AS COMPLEMENTO_E
      ,EMITENTE.BAIRRO AS BAIRRO_E
      ,NVL(CIDADE_E.CODIBGE,
           0) AS CODIGO_MUNICIPIO_E
      ,CIDADE_E.NOMECIDADE AS NOME_MUNICIPIO_E
      ,UF_E.UF AS SIGLA_UF_E
      ,NVL(PAIS_E.CODPAIS,
           0) AS CODIGO_PAIS_E
      ,PAIS_E.DESCRICAO AS PAIS_E
      ,EMITENTE.CEP AS CEP_E
      ,EMITENTE.TELFAB AS TELEFONE_E
      ,EMITENTE.IE AS INSCRICAO_ESTADUAL_E
      ,NVL((SELECT PCINSCRICAOST.IESUBSTTRIBUT
           FROM   PCINSCRICAOST
           WHERE  PCINSCRICAOST.CODFILIAL = PCFILIAL.CODIGO
           AND    PCINSCRICAOST.UF = UF_D.UF
           AND    ROWNUM = 1),
           UF_E.IESUBSTTRIBUT) AS INSCRICAO_SUBSTITUTO_E
      ,EMITENTE.INSCMUNICIP AS INSCRICAO_MUNICIPAL_E
      ,EMITENTE.CAE AS CNAE_E
       -----------------------FIM------------------------------
       -----------------------DESTINATARIO---------------------
      ,PCNFENT.CGC AS CNPJ_CPF_D
      ,CASE WHEN (NVL(PCNFENT.AMBIENTENFE,
                      PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE', 
                                                    PCFILIAL.CODIGO)) = 'P') THEN PCNFENT.FORNECEDOR
      ELSE CASE WHEN (NVL(PCNFENT.AMBIENTENFE, 
                          PARAMFILIAL.OBTERCOMOVARCHAR2('AMBIENTENFE', 
                                                    PCFILIAL.CODIGO)) = 'H' AND PCNFENT.DTENT >= TO_DATE('01-05-2011', 'DD-MM-YYYY')) 
                                                    THEN 'NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL' 
     ELSE PCNFENT.FORNECEDOR
                                                    END
      END AS RAZAO_SOCIAL_D
      ,DESTINATARIO.FANTASIA AS NOME_FANTASIA_D
      ,PCNFENT.ENDERECO AS LOGRADOURO_D
      ,NVL(PCNFENT.NUMEROEND,
           'S\N') AS NUMERO_D
      ,'' AS COMPLEMENTO_D
      ,PCNFENT.BAIRRO AS BAIRRO_D
      ,NVL(PCNFENT.CODIBGE,
           0) AS CODIGO_MUNICIPIO_D
      ,CIDADE_D.NOMECIDADE AS NOME_MUNICIPIO_D
      ,PCNFENT.UF AS SIGLA_UF_D
      ,PCNFENT.CEP AS CEP_D
      ,NVL(PCNFENT.CODPAIS,
           0) AS CODIGO_PAIS_D
      ,PCNFENT.DESCPAIS AS PAIS_D --N
      ,PCNFENT.TELEFONE AS TELEFONE_D
      ,PCNFENT.IE AS INSCRICAO_ESTADUAL_D
      ,PCNFENT.EMAILDEST AS EMAIL_D
      ,PCNFENT.SULFRAMA AS INSCRICAO_SUFRAMA_D
      -----------------------------------------------------
      -------------------------ENTREGA--------------------------
      ,NULL AS CNPJ_CPF_ENT
      ,NULL AS LOGRADOURO_ENT
      ,NULL AS NUMERO_ENT
      ,NULL AS COMPLEMENTO_ENT
      ,NULL AS BAIRRO_ENT
      ,NULL AS CODIGO_MUNICIPIO_ENT
      ,NULL AS NOME_MUNICIPIO_ENT
      ,NULL AS SIGLA_UF_ENT
      ,NULL AS CEP_ENT
      ,NULL AS INSCRICAO_ESTADUAL_ENT
      ,NULL AS TELEFONE_ENT
      ,NULL AS CODIGO_PAIS_ENT
      ,NULL AS RAZAO_SOCIAL_REC_ENT
      ,NULL AS EMAIL_ENT
      ,NULL AS PAIS_ENT
      ----------------------------------------------------------
      ------------------------RETIRADA--------------------------
      ,PCPORTOS.CNPJ_CPF AS CNPJ_CPF_RET           
      ,PCPORTOS.ENDERECO AS LOGRADOURO_RET           
      ,PCPORTOS.NUMERO AS NUMERO_RET                 
      ,PCPORTOS.COMPLEMENTO AS COMPLEMENTO_RET       
      ,PCPORTOS.BAIRRO AS BAIRRO_RET                        
      ,CIDADE_RET.CODIBGE AS CODIGO_MUNICIPIO_RET             
      ,CIDADE_RET.NOMECIDADE AS NOME_MUNICIPIO_RET     
      ,PCPORTOS.UF AS SIGLA_UF_RET                 
      ,PCPORTOS.CEP AS CEP_RET                      
      ,PCPORTOS.IE AS INSCRICAO_ESTADUAL_RET         
      ,PCPORTOS.TELEFONE AS TELEFONE_RET            
      ,PCPORTOS.CODPAIS AS CODIGO_PAIS_RET
      ,PCPORTOS.RAZAOSOCIAL AS RAZAO_SOCIAL_RET
      ,PCPORTOS.EMAIL AS EMAIL_RET         
      ,PAIS_RET.DESCRICAO AS PAIS_RET
      ---------------------------------------------------------
      ,PCNFENT.TIPODESCARGA
      ,NULL AS CONDVENDA
      ,CASE
         WHEN PCNFENT.TIPODESCARGA IN ('N', 'F', 'P') THEN
          PCNFENT.CODEXPORTADOR
         ELSE
          (SELECT MAX(X.CODEXPORTADOR)
           FROM   PCNFENT X
           WHERE  X.NUMTRANSENT = PCNFENT.NUMTRANSORIGEM)
       END AS CODIGO_EXPORTADOR
      ,CASE
         WHEN PCNFENT.TIPODESCARGA IN ('N', 'F', 'P') THEN
          PCNFENT.CODEXPORTADOR
         ELSE
          (SELECT MAX(X.CODEXPORTADOR)
           FROM   PCNFENT X
           WHERE  X.NUMTRANSENT = PCNFENT.NUMTRANSORIGEM)
       END AS CODIGO_FABRICANTE_EX
      ,(SELECT NVL(MAX(PCCFO.CODFISCAL),
                   0)
        FROM   PCCFO
              ,PCMOV
        WHERE  PCMOV.CODFISCAL = PCCFO.CODFISCAL
        AND    PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT) AS CODIGO_FISCAL
      ,CASE
         WHEN PCNFENT.TIPODESCARGA IN ('N', 'F', 'P') THEN
          PCNFENT.DATADIIMPORTACAO
         ELSE
          (SELECT MAX(X.DATADIIMPORTACAO)
           FROM   PCNFENT X
           WHERE  X.NUMTRANSENT = PCNFENT.NUMTRANSORIGEM)
       END AS DATA_DESEMBARACO
      ,EMITENTE.EMAIL AS EMAIL_E
      ,(EMITENTE.ENDER || ' - ' || NVL(EMITENTE.NUMEROEND,
                                       'S/N') || ' - ' || EMITENTE.BAIRRO ||
       ' - ' || CIDADE_E.NOMECIDADE || ' - ' || UF_E.UF || ' - ' ||
       EMITENTE.CEP) AS ENDERECO
      ,PCNFENT.ESPECIE
      ,EMITENTE.FAXFAB AS FAX_E
      ,(NVL(TRIM(PCNFENT.HORALANC),'00') || ':' || NVL(TRIM(PCNFENT.MINUTOLANC),'00')) HORA
      ,CASE
         WHEN PCNFENT.TIPODESCARGA IN ('N', 'F', 'P') THEN
          PCNFENT.LOCALDESEMBARACO
         ELSE
          (SELECT MAX(X.LOCALDESEMBARACO)
           FROM   PCNFENT X
           WHERE  X.NUMTRANSENT = PCNFENT.NUMTRANSORIGEM)
       END AS LOCAL_DESEMBARACO
      ,CASE
         WHEN PCNFENT.TIPODESCARGA IN ('N', 'F', 'P') THEN
          PCNFENT.UFDESEMBARACO
         ELSE
          (SELECT MAX(X.UFDESEMBARACO)
           FROM   PCNFENT X
           WHERE  X.NUMTRANSENT = PCNFENT.NUMTRANSORIGEM)
       END AS SIGLA_UF_DESEMBARACO
      ,CASE
         WHEN PCNFENT.TIPODESCARGA IN ('N', 'F', 'P') THEN
          PCNFENT.NUMDIIMPORTACAO
         ELSE
          (SELECT MAX(X.NUMDIIMPORTACAO)
           FROM   PCNFENT X
           WHERE  X.NUMTRANSENT = PCNFENT.NUMTRANSORIGEM)
       END AS NUM_DOC_IMPORTACAO
      ,0 AS NUM_PEDIDO
      ,0 AS RCA
      ,'' AS NUM_PEDIDO_CLI
      ,'' AS TIPO_COBRANCA
      ,0 AS NUMERO_CAR
      ,DESTINATARIO.CODFORNEC AS CODIGO_CLI
      ,'N' AS ORGAO_PUBLICO
      ,PCFILIAL.CODDOCNF AS CODDOC
      ,'' AS TIPO_EMPRESA
      ,'J' AS TIPO_PESSOA
      ,NULL AS NUM_TRANSACAO_ORIG
      ,DECODE(NVL(PCNFENT.AMBIENTENFE,
                  'X'),
              'H',
              2,
              'P',
              1,
              -1) AS AMBIENTE
      ,NVL(PCNFENT.SITUACAONFE,
           0) AS SITUACAONFE
      ,CASE WHEN (NVL(NVL(PCNFENT.CONSUMIDORFINAL, DESTINATARIO.CONSUMIDORFINAL), 'N') = 'N') THEN     
                   DECODE(DESTINATARIO.TIPOPESSOA,
                          'F',    
                          DECODE(NVL(DESTINATARIO.PERCIMPPRODUTORURAL,0),0,'S','N'),
                          'N')
         ELSE
                   NVL(PCNFENT.CONSUMIDORFINAL, DESTINATARIO.CONSUMIDORFINAL)
         END AS CONSUMIDOR_FINAL
      ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('SERIALCERTIFICADO',
                                         PCFILIAL.CODIGO),
           '') AS SERIALCERTIFICADO
      ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PINCERTIFICADO',
                                         PCFILIAL.CODIGO),
           '') AS PINCERTIFICADO
      ,NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PROVIDERCERTIFICADOA3',
                                         PCFILIAL.CODIGO),
           'SafeSign Standard Cryptographic Service Provider') AS PROVIDERCERTIFICADOA3
      ,NVL(PARAMFILIAL.OBTERCOMONUMBER('TIPOPROVIDERA3',
                                       PCFILIAL.CODIGO),
           1) AS TIPOPROVIDERA3
      ,
       CASE
         WHEN ((((SELECT CODPROD
                FROM   PCMOV
                WHERE  PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
                AND    ROWNUM = 1) IS NULL)
              AND (PCNFENT.NUMTRANSORIGEM > 0) OR PCNFENT.FINALIDADENFE = 'C') and (PCNFENT.FINALIDADENFE <> 'A')) THEN
          2
         ELSE CASE WHEN
              PCNFENT.FINALIDADENFE = 'A'
         THEN
          3
          ELSE
          1
          END
       END AS FINALIDADE
      ,PCNFENT.DTAHORAENTRADACONTIGENCIA AS DTHORA_CONTINGENCIA
      ,PCNFENT.JUSTIFICATIVACONTIGENCIA AS JUSTIFICATIVA
      ,'' DESTINOCARGA
      ,'' NUMPEDRCA
      ,PCNFENT.MOTESTORNONFE AS MOT_ESTORNONFE
      ,PCNFENT.SITUACAONFEEPEC AS SITUACAO_NFE_EPEC
      ,NVL(PCNFENT.CONTRIBUINTE, EMITENTE.CONTRIBUINTEICMS) CONTRIBUINTE
      ,NVL(PCNFENT.QTDEREPROCNFE, 0) AS QTD_REPROCESSAMENTO_NFE
      ,NULL AS CODCOBSEFAZ
      ,PCNFENT.NUMEMPENHO
      ,NULL AS UTILIZASRVTERCEIROS
      ,'N' AS ENVIADASEMRESPOSTA
      ,NULL AS IDESTRANGEIRO
      ,NULL AS CHAVEGERADATV14
      ,NULL AS CHAVENFETV14
      ,PCNFENT.CODIGONUMERICOCHAVE AS CODIGO_NUMERICO_CHAVE
      ,NVL(PCNFENT.TIPOPRESENCAADQUIRINTE, '1') AS INDICADOR_PRESENCA
      ,PCNFENT.DESCINTERMEDIADOR
      ,PCNFENT.CNPJINTERMEDIADOR
FROM   PCNFENT
      ,PCFILIAL
       --EMITENTE
      ,PCFORNEC EMITENTE
      ,PCPAIS   PAIS_E
      ,PCCIDADE CIDADE_E
      ,PCESTADO UF_E
       --DESTINATARIO
      ,PCFORNEC DESTINATARIO
      ,PCPAIS PAIS_D
      ,PCCIDADE CIDADE_D
      ,PCESTADO UF_D
       --RETIRADA
      ,PCPORTOS
      ,PCPEDIDO
      ,PCPAIS PAIS_RET
      ,PCCIDADE CIDADE_RET
      ,PCESTADO UF_RET
      ,(SELECT MAX(PCPEDNF.NUMPEDIDO) NUMPEDIDO, PCPEDNF.NUMTRANSENT
         FROM PCPEDIDO, PCPEDNF
         WHERE PCPEDIDO.NUMPED = PCPEDNF.NUMPEDIDO GROUP BY PCPEDNF.NUMTRANSENT) PEDIDO
WHERE
--EMITENTE
 EMITENTE.CODFORNEC = PCFILIAL.CODFORNEC
 AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE(+)
 AND    CIDADE_E.UF = UF_E.UF(+)
 AND    UF_E.CODPAIS = PAIS_E.CODPAIS(+)
--DESTINATARIO
 AND    DESTINATARIO.CODFORNEC = NVL(PCNFENT.CODFORNECNF, PCNFENT.CODFORNEC)
 AND    PCNFENT.CODMUNICIPIO = CIDADE_D.CODCIDADE(+)
 AND    CIDADE_D.UF = UF_D.UF(+)
 AND    UF_D.CODPAIS = PAIS_D.CODPAIS(+)
 --RETIRADA
 AND    PCNFENT.NUMTRANSENT = PEDIDO.NUMTRANSENT(+)
 AND    PEDIDO.NUMPEDIDO = PCPEDIDO.NUMPED(+)
 AND    PCPEDIDO.CODPORTOCHEGADA = PCPORTOS.CODPORTO(+)
 AND    PCPORTOS.CODCIDADE = CIDADE_RET.CODCIDADE(+)
 AND    CIDADE_RET.UF = UF_RET.UF(+)
 AND    UF_RET.CODPAIS = PAIS_RET.CODPAIS(+)
 AND    NVL(PCNFENT.CODFILIALNF,
     PCNFENT.CODFILIAL) = PCFILIAL.CODIGO
 AND    ((NVL(PCFILIAL.UTILIZANFE, 'N') = 'S') OR
         (NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('UTILIZASRVTERCEIROS', PCFILIAL.CODIGO), 'N') = 'S'))  
 AND    NVL(PCNFENT.OBS,
     ' ') <> 'NF CANCELADA'
 AND    NVL(PCNFENT.GERANFVENDA,
     'N') = 'S'
 AND    NVL(PCNFENT.GERANFDEVCLI,
     'N') = 'N'
 AND    PCNFENT.ESPECIE IN ('NF', 'NE', 'EI')
--Linhas abaixo sevem para obedecer a ordem de numeração das notas fiscais no processo de Adjudicação
AND    ( (NVL(PCNFENT.NUMTRANSENTDEPENDENTE,-1)  = -1)  OR EXISTS (SELECT 1 FROM PCNFENT E WHERE E.NUMTRANSENT = PCNFENT.NUMTRANSENTDEPENDENTE AND E.SITUACAONFE = 100))
AND    (( NVL(PCNFENT.NUMTRANSVENDADEPENDENTE,-1) = -1 ) OR (EXISTS (SELECT 1 FROM PCNFSAID S WHERE S.NUMTRANSVENDA = PCNFENT.NUMTRANSVENDADEPENDENTE AND S.SITUACAONFE = 100)))
ORDER  BY NUMERO_NOTA