CREATE OR REPLACE PACKAGE BODY PKG_CENTRAL_TRIBUTOS AS

  TYPE T_LISTA_DADOS_NOTAS IS TABLE OF PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE;

  FUNCTION RETORNA_GRAVARLOG RETURN VARCHAR2 IS
  BEGIN
    RETURN V_GRAVAR_LOG;
  END RETORNA_GRAVARLOG;

  FUNCTION CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_LISTA_DADOS_NOTAS IS
    V_LISTA_DADOS_NOTAS T_LISTA_DADOS_NOTAS;
  BEGIN
    
  
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S')   THEN
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA
      );
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL;
    END IF;          
    
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'E') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.DEVOLUCAO = 'S')     THEN
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA
      );
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO;
    END IF;      
    
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'S')     THEN
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA
      );
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT;
    END IF;          
        
    
    
    RETURN V_LISTA_DADOS_NOTAS;
  END CONSULTAR_DADOS_MOVIMENTACAO;
  
  
  FUNCTION TRANSPORTAR_LISTA_PARA_TRIB(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE
  ) RETURN FISCAL.TIPO_TRIBUT_REFORMA  IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
  BEGIN
    V_DADOS_TRIBUTACAO              := P_DADOS_TRIBUTOS;
    
    V_DADOS_TRIBUTACAO.CODCLI        := P_LISTA_DADOS_NOTAS.CODCLI;
    V_DADOS_TRIBUTACAO.CODPROD       := P_LISTA_DADOS_NOTAS.CODPROD;
    V_DADOS_TRIBUTACAO.NCM           := P_LISTA_DADOS_NOTAS.NCM;
    V_DADOS_TRIBUTACAO.VALOR_PRODUTO := P_LISTA_DADOS_NOTAS.PUNITCONT;
    V_DADOS_TRIBUTACAO.VALOR_ICMS_ST := P_LISTA_DADOS_NOTAS.VLST;
    V_DADOS_TRIBUTACAO.VALOR_FCP_ST  := P_LISTA_DADOS_NOTAS.VLFECP;
    V_DADOS_TRIBUTACAO.VALOR_IPI     := P_LISTA_DADOS_NOTAS.VLIPI;
    V_DADOS_TRIBUTACAO.VALOR_FRETE   := P_LISTA_DADOS_NOTAS.VLOUTROS;
    V_DADOS_TRIBUTACAO.VALOR_OUTROS  := P_LISTA_DADOS_NOTAS.VLFRETE;
    
    RETURN (V_DADOS_TRIBUTACAO);
  END TRANSPORTAR_LISTA_PARA_TRIB;
  
  FUNCTION LIMPAR_VALOR_TRIBUTO(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA
  ) RETURN FISCAL.TIPO_TRIBUT_REFORMA  IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
  BEGIN
    V_DADOS_TRIBUTACAO              := P_DADOS_TRIBUTOS;
    
    V_DADOS_TRIBUTACAO.CODIGO_TRIBUTACAO        := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_BASE_CALCULO     := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_VALOR_TRIBUTO    := NULL;
    V_DADOS_TRIBUTACAO.BASE_CALCULO_COD_FORMULA := NULL;
    V_DADOS_TRIBUTACAO.SOMATOTALNF              := NULL;
    V_DADOS_TRIBUTACAO.ALIQUOTA_COD_FORMULA     := NULL;
    V_DADOS_TRIBUTACAO.CST                      := NULL;
    V_DADOS_TRIBUTACAO.CCLASSTRIB               := NULL;     
    V_DADOS_TRIBUTACAO.VALOR_BASE_TRIBUTO       := NULL;
    V_DADOS_TRIBUTACAO.VALOR_ALIQUOTA_TRIBUTO   := NULL;
    V_DADOS_TRIBUTACAO.VALOR_TRIBUTO            := NULL;          
         
    RETURN (V_DADOS_TRIBUTACAO);
  END LIMPAR_VALOR_TRIBUTO;    

  -- Procedimento genérico para gravar tributos, usa SQL dinâmico para atualizar campos variando por prefixo (CBS, IBS, IS)
  PROCEDURE GRAVAR_PCMOV_TRIBUTO(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE,
    P_PREFIXO IN VARCHAR2
  ) IS
  BEGIN
    EXECUTE IMMEDIATE
      'UPDATE PCMOV SET ' ||
      'CODIGOTRIBUTACAO' || P_PREFIXO || ' = :1, ' ||
      'CST' || P_PREFIXO || ' = :2, ' ||
      'CCLASSTRIB' || P_PREFIXO || ' = :3, ' ||
      'VLBASE' || P_PREFIXO || ' = :4, ' ||
      'ALIQ' || P_PREFIXO || ' = :5, ' ||
      'VL' || P_PREFIXO || ' = :6 ' ||
      'WHERE NUMTRANSVENDA = :7 AND NUMTRANSITEM = :8 AND CODPROD = :9'
    USING
      P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO,
      P_DADOS_TRIBUTOS.CST,
      P_DADOS_TRIBUTOS.CCLASSTRIB,
      P_DADOS_TRIBUTOS.VALOR_BASE_TRIBUTO,
      P_DADOS_TRIBUTOS.VALOR_ALIQUOTA_TRIBUTO,
      P_DADOS_TRIBUTOS.VALOR_TRIBUTO,
      P_LISTA_DADOS_NOTAS.NUMTRANSVENDA,
      P_LISTA_DADOS_NOTAS.NUMTRANSITEM,
      P_LISTA_DADOS_NOTAS.CODPROD;
  END GRAVAR_PCMOV_TRIBUTO;



  -- Função para calcular e gravar CBS e IBS
  FUNCTION CALCULAR_E_GRAVAR_CBSIBS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS

    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);

  BEGIN
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_CBS', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de CBS', 'S');

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP
      
      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO, 
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));
 
      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_CBS(V_DADOS_TRIBUTACAO, V_MSG);
      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, V_LISTA_DADOS_NOTA(POSICAO_ITEM), 'CBS');
            
      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_IBS(V_DADOS_TRIBUTACAO, V_MSG);      
      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, V_LISTA_DADOS_NOTA(POSICAO_ITEM), 'IBS');
    END LOOP;

    PKG_DEBUGGING_FWPC.DESATIVARDEBUG;

    RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;

  EXCEPTION
    WHEN OTHERS THEN
      PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_CBS: ' || SQLERRM, 'S');
      RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_CBSIBS;



  -- Função para calcular e gravar IS
  FUNCTION CALCULAR_E_GRAVAR_IS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS

    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);

  BEGIN
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_IS', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de IS', 'S');

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP
      
      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO, 
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));
 
      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_IS(V_DADOS_TRIBUTACAO, V_MSG);


      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, V_LISTA_DADOS_NOTA(POSICAO_ITEM), 'IS');
    END LOOP;

    PKG_DEBUGGING_FWPC.DESATIVARDEBUG;

    RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;

  EXCEPTION
    WHEN OTHERS THEN
      PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_IS: ' || SQLERRM, 'S');
      RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_IS;



  --Função para calcular e gravar todos os tributos
  FUNCTION CALCULAR_E_GRAVAR_TODOS_TRIB(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);    
  BEGIN

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP
      
      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO, 
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_CBS(V_DADOS_TRIBUTACAO, V_MSG);
      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, V_LISTA_DADOS_NOTA(POSICAO_ITEM), 'CBS');      

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_IBS(V_DADOS_TRIBUTACAO, V_MSG);
      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, V_LISTA_DADOS_NOTA(POSICAO_ITEM), 'IBS');

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_IS(V_DADOS_TRIBUTACAO, V_MSG);
      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, V_LISTA_DADOS_NOTA(POSICAO_ITEM), 'IS');
    END LOOP;


    RETURN V_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_TODOS_TRIB;
  
  

END PKG_CENTRAL_TRIBUTOS;
