CREATE OR REPLACE PACKAGE BODY PKG_CENTRAL_TRIBUTOS AS
  
  vAchouRegistro BOOLEAN := FALSE;
  
  cCodMensagem1 number := 1;
  cMensagem1    varchar2(70) := 'OK; Dados Atualizados com sucesso ';    
  cCodMensagem2 number      := 2;
  cMensagem2    varchar2(70) := 'ERRO; Erro ao atualizar os dados de todos os tributos ';      
  cCodMensagem3 number      := 3;
  cMensagem3    varchar2(70) := 'ERRO; Erro ao atualizar os dados do CBSIBS ';        
  cCodMensagem4 number      := 4;
  cMensagem4    varchar2(70) := 'ERRO; Erro ao atualizar os dados do IS ';  
  cCodMensagem5 number := 5;
  cMensagem5    varchar2(70) := 'OK; Registro não encontrado na consulta da movimentação ';  
  

  TYPE T_LISTA_DADOS_NOTAS IS TABLE OF PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE;

  FUNCTION RETORNA_GRAVARLOG RETURN VARCHAR2 IS
  BEGIN
    RETURN V_GRAVAR_LOG;
  END RETORNA_GRAVARLOG;

  FUNCTION CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_LISTA_DADOS_NOTAS IS
    V_LISTA_DADOS_NOTAS T_LISTA_DADOS_NOTAS;
  BEGIN
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'N') AND 
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) THEN

      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL;
    END IF;

    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'E') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.DEVOLUCAO = 'S') AND 
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) THEN

      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO;
    END IF;

    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'S') AND 
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) THEN
       
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT;
    END IF;
    
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S')  AND 
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE IN ('CT','CO')) AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) THEN
       
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_CTE_SAIDA(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_CTE_SAIDA BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_CTE_SAIDA;
    END IF;        
    
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'E') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.DEVOLUCAO = 'N') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE IN ('NF')) AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) THEN
       
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_NORMAL(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_NORMAL BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_NORMAL;
    END IF;     
        
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.DEVOLUCAO = 'N') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE IN ('NF')) AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO > 0) THEN
       
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_PEDIDO(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_PEDIDO BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_PEDIDO;
    END IF;    

    RETURN V_LISTA_DADOS_NOTAS;
  END CONSULTAR_DADOS_MOVIMENTACAO;


  FUNCTION TRANSPORTAR_LISTA_PARA_TRIB(P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
                                       P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS,
                                       P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) 
    RETURN FISCAL.TIPO_TRIBUT_REFORMA  IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
  BEGIN
    V_DADOS_TRIBUTACAO              := P_DADOS_TRIBUTOS;


    V_DADOS_TRIBUTACAO.TIPO_OPERACAO := P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO;
    V_DADOS_TRIBUTACAO.CODCLI        := P_LISTA_DADOS_NOTAS.CODCLI;
    V_DADOS_TRIBUTACAO.CODPROD       := P_LISTA_DADOS_NOTAS.CODPROD;
    V_DADOS_TRIBUTACAO.NCM           := P_LISTA_DADOS_NOTAS.NCM;
    V_DADOS_TRIBUTACAO.VALOR_PRODUTO := P_LISTA_DADOS_NOTAS.PUNITCONT;
    V_DADOS_TRIBUTACAO.VALOR_ICMS_ST := P_LISTA_DADOS_NOTAS.VLST;
    V_DADOS_TRIBUTACAO.VALOR_FCP_ST  := P_LISTA_DADOS_NOTAS.VLFECP;
    V_DADOS_TRIBUTACAO.VALOR_IPI     := P_LISTA_DADOS_NOTAS.VLIPI;
    V_DADOS_TRIBUTACAO.VALOR_FRETE   := P_LISTA_DADOS_NOTAS.VLOUTROS;
    V_DADOS_TRIBUTACAO.VALOR_OUTROS  := P_LISTA_DADOS_NOTAS.VLFRETE;

    RETURN (V_DADOS_TRIBUTACAO);
  END TRANSPORTAR_LISTA_PARA_TRIB;

  FUNCTION LIMPAR_VALOR_TRIBUTO(P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA) 
    RETURN FISCAL.TIPO_TRIBUT_REFORMA  IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
  BEGIN
    V_DADOS_TRIBUTACAO              := P_DADOS_TRIBUTOS;
 
    -- Dados CBSIBS
    V_DADOS_TRIBUTACAO.CODIGO_TRIBUTACAO_CBSIBS     := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_BASE_CALCULO_CBSIBS  := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_VALOR_TRIBUTO_CBSIBS := NULL;
    V_DADOS_TRIBUTACAO.COD_FORMULA_BASE_CBSIBS      := NULL;
    V_DADOS_TRIBUTACAO.SOMATOTALNF_CBSIBS           := NULL;
    V_DADOS_TRIBUTACAO.CST_CBSIBS                   := NULL;
    V_DADOS_TRIBUTACAO.CCLASSTRIB_CBSIBS            := NULL;
    V_DADOS_TRIBUTACAO.VALOR_BASE_CBSIBS            := NULL;      
    --Retorno valores CBS
    V_DADOS_TRIBUTACAO.PERC_CBS                     := NULL;
    V_DADOS_TRIBUTACAO.PERC_RED_CBS                 := NULL;
    V_DADOS_TRIBUTACAO.ALIQ_EFETIVA_CBS             := NULL;
    V_DADOS_TRIBUTACAO.VALOR_CBS                    := NULL;            
    --Retorno valores IBS UF
    V_DADOS_TRIBUTACAO.PERC_IBS_UF                  := NULL;
    V_DADOS_TRIBUTACAO.PERC_RED_ALIQ_IBS_UF         := NULL;
    V_DADOS_TRIBUTACAO.ALIQ_EFETIVA_IBS_UF          := NULL;
    V_DADOS_TRIBUTACAO.VALOR_IBS_UF                 := NULL;      
    --Retorno valores IBS    
    V_DADOS_TRIBUTACAO.PERC_IBS_MUN                 := NULL;
    V_DADOS_TRIBUTACAO.PERC_RED_ALIQ_IBS_MUN        := NULL;
    V_DADOS_TRIBUTACAO.ALIQ_EFETIVA_IBS_MUN         := NULL;
    V_DADOS_TRIBUTACAO.VALOR_IBS_MUN                := NULL;      
    --Retornos valores IS
    V_DADOS_TRIBUTACAO.CODIGO_TRIBUTACAO_IS         := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_BASE_CALCULO_IS      := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_VALOR_TRIBUTO_IS     := NULL;
    V_DADOS_TRIBUTACAO.COD_FORMULA_BASE_CALCULO_IS  := NULL;
    V_DADOS_TRIBUTACAO.SOMATOTALNF_IS               := NULL;
    V_DADOS_TRIBUTACAO.CST_IS                       := NULL;
    V_DADOS_TRIBUTACAO.CCLASSTRIB_IS                := NULL;
    V_DADOS_TRIBUTACAO.VALOR_BASE_IS                := NULL;
    V_DADOS_TRIBUTACAO.PERC_IS                      := NULL;
    V_DADOS_TRIBUTACAO.VALOR_IS                     := NULL;            

    RETURN (V_DADOS_TRIBUTACAO);
  END LIMPAR_VALOR_TRIBUTO;   
  
  PROCEDURE GRAVAR_PCPEDI_TRIBUTO(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE,
    P_TIPO_GRAVACAO IN VARCHAR2) IS 
          
    PROCEDURE GRAVAR_CBSIBS(
      P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
      P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS    
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE
          'UPDATE PCPEDI SET ' ||
          'CODIGOTRIBUTACAOCBSIBS  = :1, ' ||
          'CSTIBSCBS               = :2, ' ||
          'CCLASSTRIBIBSCBS        = :3, ' ||
          'VLBASEIBSCBS            = :4, ' ||
          'IBSUF                   = :5, ' ||
          'PREDALIQIBSUF           = :6, ' ||
          'PALIQEFETIBSUF          = :7, ' ||
          'VIBSUF                  = :8, ' ||
          'PIBSMUN                 = :9, ' ||
          'PREDALIQIBSMUN          = :10, ' ||
          'PALIQEFETIBSMUN         = :11, ' ||
          'VIBSMUN                 = :12, ' ||
          'ALIQCBS                 = :13, ' ||
          'PREDALIQCBS             = :14, ' ||
          'PALIQEFETCBS            = :15, ' ||
          'VLCBS                   = :16' ||
          'WHERE NUMPED = :17 AND NUMSEQ = :18 AND CODPROD = :19'
        USING
          P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO_CBSIBS, -- :1
          P_DADOS_TRIBUTOS.CST_CBSIBS,               -- :2
          P_DADOS_TRIBUTOS.CCLASSTRIB_CBSIBS,        -- :3
          P_DADOS_TRIBUTOS.VALOR_BASE_CBSIBS,        -- :4
          P_DADOS_TRIBUTOS.PERC_IBS_UF,              -- :5
          P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_UF,     -- :6
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_UF,      -- :7
          P_DADOS_TRIBUTOS.VALOR_IBS_UF,             -- :8
          P_DADOS_TRIBUTOS.PERC_IBS_MUN,             -- :9
          P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_MUN,    -- :10
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_MUN,     -- :11
          P_DADOS_TRIBUTOS.VALOR_IBS_MUN,            -- :12
          P_DADOS_TRIBUTOS.PERC_CBS,                 -- :13
          P_DADOS_TRIBUTOS.PERC_RED_CBS,             -- :14
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_CBS,         -- :15
          P_DADOS_TRIBUTOS.VALOR_CBS,                -- :16
          P_LISTA_DADOS_NOTAS.NUMPED,                -- :17
          P_LISTA_DADOS_NOTAS.NUMSEQ,                -- :18
          P_LISTA_DADOS_NOTAS.CODPROD                -- :19
          ;

      PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para CBSIBS: ' || SQL%ROWCOUNT, 'S');

      EXCEPTION
        WHEN OTHERS THEN
          PKG_DEBUGGING_FWPC.LOG(cMensagem3|| SQLERRM, 'S');        
      END;
    END GRAVAR_CBSIBS;
       
        
    PROCEDURE GRAVAR_IS(
        P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
        P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS
    BEGIN
      EXECUTE IMMEDIATE
        'UPDATE PCPEDI SET ' ||
        'CODIGOTRIBUTACAOIS = :1, CSTIS = :2, CCLASSTRIBIS = :3, ' ||
        'VLBASEIS = :4, ALIQIS = :5, VLIS = :6 ' ||
        'WHERE NUMPED = :7 AND NUMSEQ = :8 AND CODPROD = :9'
      USING
        P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO_IS,
        P_DADOS_TRIBUTOS.CST_IS,
        P_DADOS_TRIBUTOS.CCLASSTRIB_IS,
        P_DADOS_TRIBUTOS.VALOR_BASE_IS,
        P_DADOS_TRIBUTOS.PERC_IS,
        P_DADOS_TRIBUTOS.VALOR_IS,        
        P_LISTA_DADOS_NOTAS.NUMPED,
        P_LISTA_DADOS_NOTAS.NUMSEQ,
        P_LISTA_DADOS_NOTAS.CODPROD;

        PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para IS: ' || SQL%ROWCOUNT, 'S');      
      EXCEPTION
        WHEN OTHERS THEN
          PKG_DEBUGGING_FWPC.LOG(cMensagem4|| SQLERRM, 'S');        
    END GRAVAR_IS;          
  BEGIN    
    IF (P_TIPO_GRAVACAO =  'CBSIBS') THEN
      GRAVAR_CBSIBS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    END IF;
    
    IF (P_TIPO_GRAVACAO =  'IS') THEN
      GRAVAR_IS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    END IF;
    
    IF (P_TIPO_GRAVACAO =  'TODOS') THEN
      GRAVAR_CBSIBS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
      GRAVAR_IS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);      
    END IF;            
  END GRAVAR_PCPEDI_TRIBUTO;  
  

  -- Procedimento genérico para gravar tributos, usa SQL dinâmico para atualizar campos variando por prefixo (CBS, IBS, IS)
  PROCEDURE GRAVAR_PCMOV_TRIBUTO(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE,
    P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS,
    P_TIPO_GRAVACAO IN VARCHAR2) IS
 
    V_TABELA VARCHAR2(15);    
    V_TRANSENT_OU_TRANSVENDA VARCHAR2(15);    
      
    PROCEDURE GRAVAR_CBSIBS(
      P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
      P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS    
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE
          'UPDATE ' || V_TABELA || ' SET ' ||
          'CODIGOTRIBUTACAOCBSIBS  = :1, ' ||
          'CSTIBSCBS               = :2, ' ||
          'CCLASSTRIBIBSCBS        = :3, ' ||
          'VLBASEIBSCBS            = :4, ' ||
          'IBSUF                   = :5, ' ||
          'PREDALIQIBSUF           = :6, ' ||
          'PALIQEFETIBSUF          = :7, ' ||
          'VIBSUF                  = :8, ' ||
          'PIBSMUN                 = :9, ' ||
          'PREDALIQIBSMUN          = :10, ' ||
          'PALIQEFETIBSMUN         = :11, ' ||
          'VIBSMUN                 = :12, ' ||
          'ALIQCBS                 = :13, ' ||
          'PREDALIQCBS             = :14, ' ||
          'PALIQEFETCBS            = :15, ' ||
          'VLCBS                   = :16,' ||
          'SOMATOTALNF_CBS         = :17,' ||
          'SOMATOTALNF_IBS         = :18,' ||   
          'VLIBS                   = :19' ||                   
          'WHERE '||V_TRANSENT_OU_TRANSVENDA||' = :20 AND NUMTRANSITEM = :21 AND CODPROD = :22'
        USING
          P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO_CBSIBS, -- :1
          P_DADOS_TRIBUTOS.CST_CBSIBS,               -- :2
          P_DADOS_TRIBUTOS.CCLASSTRIB_CBSIBS,        -- :3
          P_DADOS_TRIBUTOS.VALOR_BASE_CBSIBS,        -- :4
          P_DADOS_TRIBUTOS.PERC_IBS_UF,              -- :5
          P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_UF,     -- :6
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_UF,      -- :7
          P_DADOS_TRIBUTOS.VALOR_IBS_UF,             -- :8
          P_DADOS_TRIBUTOS.PERC_IBS_MUN,             -- :9
          P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_MUN,    -- :10
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_MUN,     -- :11
          P_DADOS_TRIBUTOS.VALOR_IBS_MUN,            -- :12
          P_DADOS_TRIBUTOS.PERC_CBS,                 -- :13
          P_DADOS_TRIBUTOS.PERC_RED_CBS,             -- :14
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_CBS,         -- :15
          P_DADOS_TRIBUTOS.VALOR_CBS,                -- :16
          P_DADOS_TRIBUTOS.SOMATOTALNF_CBSIBS,       -- :17
          P_DADOS_TRIBUTOS.SOMATOTALNF_CBSIBS,       -- :18 
          P_DADOS_TRIBUTOS.VLTOTALIBS,               -- :19                    
          P_LISTA_DADOS_NOTAS.NUMTRANSACAO ,         -- :20
          P_LISTA_DADOS_NOTAS.NUMTRANSITEM,          -- :21
          P_LISTA_DADOS_NOTAS.CODPROD                -- :22
          ;

      PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para CBSIBS: ' || SQL%ROWCOUNT, 'S');

      EXCEPTION
        WHEN OTHERS THEN
          PKG_DEBUGGING_FWPC.LOG(cMensagem3|| SQLERRM, 'S');        
      END;
    END GRAVAR_CBSIBS;
       
        
    PROCEDURE GRAVAR_IS(
        P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
        P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS
    BEGIN
      EXECUTE IMMEDIATE
        'UPDATE ' || V_TABELA || ' SET ' ||
        'CODIGOTRIBUTACAOIS = :1, CSTIS = :2, CCLASSTRIBIS = :3, ' ||
        'VLBASEIS = :4, ALIQIS = :5, VLIS = :6, SOMATOTALNF_IS = :7 ' ||
        'WHERE '||V_TRANSENT_OU_TRANSVENDA||' = :8 AND NUMTRANSITEM = :9 AND CODPROD = :10'
      USING
        P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO_IS,
        P_DADOS_TRIBUTOS.CST_IS,
        P_DADOS_TRIBUTOS.CCLASSTRIB_IS,
        P_DADOS_TRIBUTOS.VALOR_BASE_IS,
        P_DADOS_TRIBUTOS.PERC_IS,
        P_DADOS_TRIBUTOS.VALOR_IS,
        P_DADOS_TRIBUTOS.SOMATOTALNF_IS,        
        P_LISTA_DADOS_NOTAS.NUMTRANSACAO,
        P_LISTA_DADOS_NOTAS.NUMTRANSITEM,
        P_LISTA_DADOS_NOTAS.CODPROD;

        PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para IS: ' || SQL%ROWCOUNT, 'S');      
      EXCEPTION
        WHEN OTHERS THEN
          PKG_DEBUGGING_FWPC.LOG(cMensagem4|| SQLERRM, 'S');        
    END GRAVAR_IS;          
  BEGIN    
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') THEN
      V_TABELA := 'PCMOVPREFAT';
    ELSE
      V_TABELA := 'PCMOV';
    END IF;      
      
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'E') AND  
       (P_PARAMETROS_CENTRAL_TRIBUTOS.DEVOLUCAO = 'N') AND       
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') THEN
      V_TRANSENT_OU_TRANSVENDA := 'NUMTRANSENT';
    ELSE
      V_TRANSENT_OU_TRANSVENDA := 'NUMTRANSVENDA';
    END IF; 

    
    IF (P_TIPO_GRAVACAO =  'CBSIBS') THEN
      GRAVAR_CBSIBS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    END IF;
    
    IF (P_TIPO_GRAVACAO =  'IS') THEN
      GRAVAR_IS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    END IF;
    
    IF (P_TIPO_GRAVACAO =  'TODOS') THEN
      GRAVAR_CBSIBS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
      GRAVAR_IS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);      
    END IF;            
  END GRAVAR_PCMOV_TRIBUTO;
  
  
  
  PROCEDURE GRAVAR_CTE_TRIBUTO(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS
      
    PROCEDURE GRAVAR_CBSIBS_CTE(
      P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
      P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS    
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE
          'UPDATE PCNFBASE SET ' ||
                  'CSTIBSCBS        = :1, ' ||
                  'CCLASSTRIB       = :2, ' ||
                  'VBC              = :3, ' ||

                  'PIBSUF           = :4, ' ||
                  'PREDALIQ_IBSUF   = :5, ' ||
                  'PALIQEFET_IBSUF  = :6, ' ||
                  'VIBSUF           = :7, ' ||
                  
                  'PIBSMUN          = :8, ' ||
                  'PREDALIQ_IBSMUN  = :9, ' ||
                  'PALIQEFET_IBSMUN = :10,' ||
                  'VIBSMUN          = :11,' ||                  

                  'PCBS             = :12,' ||
                  'PREDALIQ_CBS     = :13,' ||
                  'PALIQEFET_CBS    = :14,' ||
                  'VCBS             = :15,' ||                   
                  'SOMATOTALNF      = :16,' || 
                  'VLTOTALIBS       = :17 ' ||                 
          'WHERE NUMTRANSVENDA = :18 '
        USING
          P_DADOS_TRIBUTOS.CST_CBSIBS,               -- :1
          P_DADOS_TRIBUTOS.CCLASSTRIB_CBSIBS,        -- :2
          P_DADOS_TRIBUTOS.VALOR_BASE_CBSIBS,        -- :3

          P_DADOS_TRIBUTOS.PERC_IBS_UF,              -- :4          
          P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_UF,     -- :5
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_UF,      -- :6
          P_DADOS_TRIBUTOS.VALOR_IBS_UF,             -- :7          

          P_DADOS_TRIBUTOS.PERC_IBS_MUN,             -- :8
          P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_MUN,    -- :9
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_MUN,     -- :10
          P_DADOS_TRIBUTOS.VALOR_IBS_MUN,            -- :11          

          P_DADOS_TRIBUTOS.PERC_CBS,                 -- :12
          P_DADOS_TRIBUTOS.PERC_RED_CBS,             -- :13
          P_DADOS_TRIBUTOS.ALIQ_EFETIVA_CBS,         -- :14
          P_DADOS_TRIBUTOS.VALOR_CBS,                -- :15
          P_DADOS_TRIBUTOS.SOMATOTALNF_CBSIBS,       -- :16  
          P_DADOS_TRIBUTOS.VLTOTALIBS,               -- :17        
          P_LISTA_DADOS_NOTAS.NUMTRANSACAO           -- :18
          ;

      PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para CBSIBS: ' || SQL%ROWCOUNT, 'S');

      EXCEPTION
        WHEN OTHERS THEN
          PKG_DEBUGGING_FWPC.LOG(cMensagem3|| SQLERRM, 'S');        
      END;
    END GRAVAR_CBSIBS_CTE;                      
  BEGIN   
    
    GRAVAR_CBSIBS_CTE(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    
  END GRAVAR_CTE_TRIBUTO;  
  

  -- Função para calcular e gravar CBS e IBS
  FUNCTION CALCULAR_E_GRAVAR_CBSIBS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS

    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);
  BEGIN
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_CBSIBS', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de CBSIBS', 'S');
    
    V_PARAMETROS_CENTRAL_TRIBUTOS := P_PARAMETROS_CENTRAL_TRIBUTOS;    

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP

      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO,
                                                        P_PARAMETROS_CENTRAL_TRIBUTOS,
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_CBSIBS(V_DADOS_TRIBUTACAO, V_MSG);

      --Gravar itens de movimentação PCMOV, PCMOVPREFAT
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO = 0) THEN
        GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, 
                             V_LISTA_DADOS_NOTA(POSICAO_ITEM),                            
                             P_PARAMETROS_CENTRAL_TRIBUTOS,
                             'CBSIBS');
      END IF;
      
      --Gravar dados de cte, PCNFBASE
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE IN ('CT', 'CO')) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO = 0) THEN
        GRAVAR_CTE_TRIBUTO(V_DADOS_TRIBUTACAO, 
                           V_LISTA_DADOS_NOTA(POSICAO_ITEM));
      END IF;
      
      --Gravar dados de pedido, PCPEDI      
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO = 0) THEN
        GRAVAR_PCPEDI_TRIBUTO(V_DADOS_TRIBUTACAO, 
                              V_LISTA_DADOS_NOTA(POSICAO_ITEM),
                              'CBSIBS');
      END IF;

      vAchouRegistro := True;      
    END LOOP;

    PKG_DEBUGGING_FWPC.DESATIVARDEBUG;

    IF vAchouRegistro THEN      
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem1;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem1;
    ELSE   
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem5;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem5;
    END IF;

    RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;

  EXCEPTION
    WHEN OTHERS THEN
      PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_CBSIBS: ' || SQLERRM, 'S');
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem3;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO := cMensagem3||SQLERRM;      
      RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_CBSIBS;



  -- Função para calcular e gravar IS
  FUNCTION CALCULAR_E_GRAVAR_IS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS
    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);
  BEGIN
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_IS', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de IS', 'S');
    
    V_PARAMETROS_CENTRAL_TRIBUTOS := P_PARAMETROS_CENTRAL_TRIBUTOS;

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP

      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO,
                                                        P_PARAMETROS_CENTRAL_TRIBUTOS,
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_IS(V_DADOS_TRIBUTACAO, V_MSG);

      --Gravar itens de movimentação PCMOV, PCMOVPREFAT
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO = 0) THEN
        GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, 
                             V_LISTA_DADOS_NOTA(POSICAO_ITEM),                            
                             P_PARAMETROS_CENTRAL_TRIBUTOS,
                             'IS');
      END IF;
      
      --Gravar dados de pedido, PCPEDI      
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO = 0) THEN
        GRAVAR_PCPEDI_TRIBUTO(V_DADOS_TRIBUTACAO, 
                              V_LISTA_DADOS_NOTA(POSICAO_ITEM),
                              'IS');
      END IF;
            
      vAchouRegistro := True;
    END LOOP;

    PKG_DEBUGGING_FWPC.DESATIVARDEBUG;
    
    IF vAchouRegistro THEN      
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem1;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem1;
    ELSE   
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem5;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem5;
    END IF;
    
    RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;

  EXCEPTION
    WHEN OTHERS THEN
      PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_IS: ' || SQLERRM, 'S');
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem4;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO := cMensagem4||SQLERRM;
      RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_IS;



  --Função para calcular e gravar todos os tributos
  FUNCTION CALCULAR_E_GRAVAR_TODOS_TRIB(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);
  BEGIN    
    
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_TODOS_TRIB', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de todos os tributos', 'S');
    
    V_PARAMETROS_CENTRAL_TRIBUTOS := P_PARAMETROS_CENTRAL_TRIBUTOS;
  
    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP

      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO,
                                                        P_PARAMETROS_CENTRAL_TRIBUTOS,
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_TODOS_TRIBUTOS(V_DADOS_TRIBUTACAO, V_MSG);

      --Gravar itens de movimentação PCMOV, PCMOVPREFAT
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO = 0) THEN
        GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, 
                             V_LISTA_DADOS_NOTA(POSICAO_ITEM),                            
                             P_PARAMETROS_CENTRAL_TRIBUTOS,
                             'TODOS');
      END IF;
      
      --Gravar dados de cte, PCNFBASE
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE IN ('CT', 'CO')) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO = 0) THEN
        GRAVAR_CTE_TRIBUTO(V_DADOS_TRIBUTACAO, 
                           V_LISTA_DADOS_NOTA(POSICAO_ITEM));
      END IF;
      
      --Gravar dados de pedido, PCPEDI      
      IF (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_PEDIDO > 0) AND
         (P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO = 0) THEN
        GRAVAR_PCPEDI_TRIBUTO(V_DADOS_TRIBUTACAO, 
                              V_LISTA_DADOS_NOTA(POSICAO_ITEM),
                              'TODOS');
      END IF;
      
      vAchouRegistro := True;
    END LOOP;
   
    IF vAchouRegistro THEN      
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem1;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem1;
    ELSE   
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem5;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem5;
    END IF;

    RETURN V_PARAMETROS_CENTRAL_TRIBUTOS;    
  EXCEPTION
     WHEN OTHERS THEN
     BEGIN
        PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_IS: ' || SQLERRM, 'S');       
        
        V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem2;       
        V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO := cMensagem2||SQLERRM;        
        RETURN V_PARAMETROS_CENTRAL_TRIBUTOS;        
     END;                      
  END CALCULAR_E_GRAVAR_TODOS_TRIB;
  

PROCEDURE CALC_E_GRAVAR_TODOS_TRIB_TEST(P_CODIGO_FILIAL           IN  VARCHAR2,
                                        P_NUMERO_NOTA             IN  NUMBER,
                                        P_NUMERO_TRANSACAO        IN  NUMBER,
                                        P_NUMERO_PEDIDO           IN  NUMBER,
                                        P_TIPOMOVIMENTO           IN  VARCHAR2,
                                        P_DEVOLUCAO               IN  VARCHAR2,
                                        P_PRE_FATURAMENTO         IN  VARCHAR2,
                                        P_ESPECIE                 IN  VARCHAR2,
                                        P_CODIGO_MENSAGEM_RETORNO OUT NUMBER,
                                        P_MENSAGEM_RETORNO        OUT VARCHAR2) IS

  -- Declaração e inicialização do record
  V_PARAMETROS PKG_CENTRAL_TRIBUTOS.T_PARAMETROS_CENTRAL_TRIBUTOS;

BEGIN
  -- Inicialização manual dos campos (não pode deixar implícito)
  V_PARAMETROS.CODIGO_FILIAL        := P_CODIGO_FILIAL;
  V_PARAMETROS.NUMERO_NOTA          := NVL(P_NUMERO_NOTA, 0);
  V_PARAMETROS.NUMERO_TRANSACAO     := NVL(P_NUMERO_TRANSACAO, 0);
  V_PARAMETROS.NUMERO_PEDIDO        := NVL(P_NUMERO_PEDIDO, 0);
  V_PARAMETROS.TIPOMOVIMENTO        := P_TIPOMOVIMENTO;
  V_PARAMETROS.DEVOLUCAO            := NVL(P_DEVOLUCAO, 'N');
  V_PARAMETROS.PRE_FATURAMENTO      := NVL(P_PRE_FATURAMENTO, 'N');
  V_PARAMETROS.ESPECIE              := NVL(P_ESPECIE, 'NF');

  -- Chamada da função principal
  V_PARAMETROS := PKG_CENTRAL_TRIBUTOS.CALCULAR_E_GRAVAR_TODOS_TRIB(V_PARAMETROS);

  -- Retorno de saída
  P_CODIGO_MENSAGEM_RETORNO := V_PARAMETROS.CODIGO_MENSAGEM_RETORNO;
  P_MENSAGEM_RETORNO        := V_PARAMETROS.MENSAGEM_RETORNO;

EXCEPTION
  WHEN OTHERS THEN
    P_CODIGO_MENSAGEM_RETORNO := -1;
    P_MENSAGEM_RETORNO        := 'Erro: ' || SQLERRM;

END CALC_E_GRAVAR_TODOS_TRIB_TEST;

END PKG_CENTRAL_TRIBUTOS;
