CREATE OR REPLACE PACKAGE PKG_CENTRAL_TRIBUTOS AS

  V_GRAVAR_LOG VARCHAR2(1) := 'N';

  TYPE T_PARAMETROS_CENTRAL_TRIBUTOS IS RECORD(
     CODIGO_FILIAL             VARCHAR2(2),
     NUMERO_NOTA               NUMBER := 0,
     NUMERO_TRANSACAO          NUMBER := 0,
     NUMERO_PEDIDO             NUMBER := 0,

     TIPOMOVIMENTO             VARCHAR2(1),
     DEVOLUCAO                 VARCHAR2(1) := 'N',
     PRE_FATURAMENTO           VARCHAR2(1) := 'N',
     ESPECIE                   VARCHAR2(2) := 'NF',

     CODIGO_MENSAGEM_RETORNO   NUMBER,
     MENSAGEM_RETORNO          VARCHAR2(4000)
  );

  FUNCTION RETORNA_GRAVARLOG RETURN VARCHAR2;

  FUNCTION CALCULAR_E_GRAVAR_CBSIBS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS;

  FUNCTION CALCULAR_E_GRAVAR_IS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS;

  FUNCTION CALCULAR_E_GRAVAR_TODOS_TRIB(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS;

  PROCEDURE CALC_E_GRAVAR_TODOS_TRIB_TEST(P_CODIGO_FILIAL           IN  VARCHAR2,
                                         P_NUMERO_NOTA             IN  NUMBER,
                                         P_NUMERO_TRANSACAO        IN  NUMBER,
                                         P_NUMERO_PEDIDO           IN  NUMBER,
                                         P_TIPOMOVIMENTO           IN  VARCHAR2,
                                         P_DEVOLUCAO               IN  VARCHAR2,
                                         P_PRE_FATURAMENTO         IN  VARCHAR2,
                                         P_ESPECIE                 IN  VARCHAR2,
                                         P_CODIGO_MENSAGEM_RETORNO OUT NUMBER,
                                         P_MENSAGEM_RETORNO        OUT VARCHAR2
   );

END PKG_CENTRAL_TRIBUTOS;
