CREATE OR REPLACE PACKAGE BODY PKG_CENTRAL_TRIBUTOS AS

  cCodMensagem1 number := 1;
  cMensagem1    varchar2(70) := 'OK; Dados Atualizados com sucesso ';    
  cCodMensagem2 number      := 2;
  cMensagem2    varchar2(70) := 'ERRO; Erro ao atualizar os dados de todos os tributos ';      
  cCodMensagem3 number      := 3;
  cMensagem3    varchar2(70) := 'ERRO; Erro ao atualizar os dados do CBSIBS ';        
  cCodMensagem4 number      := 4;
  cMensagem4    varchar2(70) := 'ERRO; Erro ao atualizar os dados do IS ';  
  

  TYPE T_LISTA_DADOS_NOTAS IS TABLE OF PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE;

  FUNCTION RETORNA_GRAVARLOG RETURN VARCHAR2 IS
  BEGIN
    RETURN V_GRAVAR_LOG;
  END RETORNA_GRAVARLOG;

  FUNCTION CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_LISTA_DADOS_NOTAS IS
    V_LISTA_DADOS_NOTAS T_LISTA_DADOS_NOTAS;
  BEGIN
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'N') AND 
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF')  THEN

      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL;
    END IF;

    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'E') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.DEVOLUCAO = 'S') THEN

      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_ENTRADA_DEVOLUCAO;
    END IF;

    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.TIPOMOVIMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'S') AND 
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') THEN
       
      OPEN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT(
        P_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_FILIAL,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO,
        P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_NOTA);
        
      FETCH PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT BULK COLLECT INTO V_LISTA_DADOS_NOTAS;
      CLOSE PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_PREFAT;
    END IF;

    RETURN V_LISTA_DADOS_NOTAS;
  END CONSULTAR_DADOS_MOVIMENTACAO;


  FUNCTION TRANSPORTAR_LISTA_PARA_TRIB(P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
                                       P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) 
    RETURN FISCAL.TIPO_TRIBUT_REFORMA  IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
  BEGIN
    V_DADOS_TRIBUTACAO              := P_DADOS_TRIBUTOS;

    V_DADOS_TRIBUTACAO.CODCLI        := P_LISTA_DADOS_NOTAS.CODCLI;
    V_DADOS_TRIBUTACAO.CODPROD       := P_LISTA_DADOS_NOTAS.CODPROD;
    V_DADOS_TRIBUTACAO.NCM           := P_LISTA_DADOS_NOTAS.NCM;
    V_DADOS_TRIBUTACAO.VALOR_PRODUTO := P_LISTA_DADOS_NOTAS.PUNITCONT;
    V_DADOS_TRIBUTACAO.VALOR_ICMS_ST := P_LISTA_DADOS_NOTAS.VLST;
    V_DADOS_TRIBUTACAO.VALOR_FCP_ST  := P_LISTA_DADOS_NOTAS.VLFECP;
    V_DADOS_TRIBUTACAO.VALOR_IPI     := P_LISTA_DADOS_NOTAS.VLIPI;
    V_DADOS_TRIBUTACAO.VALOR_FRETE   := P_LISTA_DADOS_NOTAS.VLOUTROS;
    V_DADOS_TRIBUTACAO.VALOR_OUTROS  := P_LISTA_DADOS_NOTAS.VLFRETE;

    RETURN (V_DADOS_TRIBUTACAO);
  END TRANSPORTAR_LISTA_PARA_TRIB;

  FUNCTION LIMPAR_VALOR_TRIBUTO(P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA) 
    RETURN FISCAL.TIPO_TRIBUT_REFORMA  IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
  BEGIN
    V_DADOS_TRIBUTACAO              := P_DADOS_TRIBUTOS;
 
    -- Dados CBSIBS
    V_DADOS_TRIBUTACAO.CODIGO_TRIBUTACAO_CBSIBS     := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_BASE_CALCULO_CBSIBS  := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_VALOR_TRIBUTO_CBSIBS := NULL;
    V_DADOS_TRIBUTACAO.COD_FORMULA_BASE_CBSIBS      := NULL;
    V_DADOS_TRIBUTACAO.SOMATOTALNF_CBSIBS           := NULL;
    V_DADOS_TRIBUTACAO.CST_CBSIBS                   := NULL;
    V_DADOS_TRIBUTACAO.CCLASSTRIB_CBSIBS            := NULL;
    V_DADOS_TRIBUTACAO.VALOR_BASE_CBSIBS            := NULL;      
    --Retorno valores CBS
    V_DADOS_TRIBUTACAO.PERC_CBS                     := NULL;
    V_DADOS_TRIBUTACAO.PERC_RED_CBS                 := NULL;
    V_DADOS_TRIBUTACAO.ALIQ_EFETIVA_CBS             := NULL;
    V_DADOS_TRIBUTACAO.VALOR_CBS                    := NULL;            
    --Retorno valores IBS UF
    V_DADOS_TRIBUTACAO.PERC_IBS_UF                  := NULL;
    V_DADOS_TRIBUTACAO.PERC_RED_ALIQ_IBS_UF         := NULL;
    V_DADOS_TRIBUTACAO.ALIQ_EFETIVA_IBS_UF          := NULL;
    V_DADOS_TRIBUTACAO.VALOR_IBS_UF                 := NULL;      
    --Retorno valores IBS    
    V_DADOS_TRIBUTACAO.PERC_IBS_MUN                 := NULL;
    V_DADOS_TRIBUTACAO.PERC_RED_ALIQ_IBS_MUN        := NULL;
    V_DADOS_TRIBUTACAO.ALIQ_EFETIVA_IBS_MUN         := NULL;
    V_DADOS_TRIBUTACAO.VALOR_IBS_MUN                := NULL;      
    --Retornos valores IS
    V_DADOS_TRIBUTACAO.CODIGO_TRIBUTACAO_IS         := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_BASE_CALCULO_IS      := NULL;
    V_DADOS_TRIBUTACAO.FORMULA_VALOR_TRIBUTO_IS     := NULL;
    V_DADOS_TRIBUTACAO.COD_FORMULA_BASE_CALCULO_IS  := NULL;
    V_DADOS_TRIBUTACAO.SOMATOTALNF_IS               := NULL;
    V_DADOS_TRIBUTACAO.CST_IS                       := NULL;
    V_DADOS_TRIBUTACAO.CCLASSTRIB_IS                := NULL;
    V_DADOS_TRIBUTACAO.VALOR_BASE_IS                := NULL;
    V_DADOS_TRIBUTACAO.PERC_IS                      := NULL;
    V_DADOS_TRIBUTACAO.VALOR_IS                     := NULL;            

    RETURN (V_DADOS_TRIBUTACAO);
  END LIMPAR_VALOR_TRIBUTO;

  -- Procedimento genérico para gravar tributos, usa SQL dinâmico para atualizar campos variando por prefixo (CBS, IBS, IS)
  PROCEDURE GRAVAR_PCMOV_TRIBUTO(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE,
    P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS,
    P_TIPO_GRAVACAO IN VARCHAR2) IS
      
  PROCEDURE GRAVAR_CBSIBS(
    P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
    P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS    
    P_TABELA VARCHAR2(15);
  BEGIN
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') THEN
      P_TABELA := 'PCMOVPREFAT';
    ELSE
      P_TABELA := 'PCMOV';
    END IF;

    BEGIN
      EXECUTE IMMEDIATE
        'UPDATE ' || P_TABELA || ' SET ' ||
        'CODIGOTRIBUTACAOCBSIBS  = :1, ' ||
        'CSTIBSCBS               = :2, ' ||
        'CCLASSTRIBIBSCBS        = :3, ' ||
        'VLBASEIBSCBS            = :4, ' ||
        'IBSUF                   = :5, ' ||
        'PREDALIQIBSUF           = :6, ' ||
        'PALIQEFETIBSUF          = :7, ' ||
        'VIBSUF                  = :8, ' ||
        'PIBSMUN                 = :9, ' ||
        'PREDALIQIBSMUN          = :10, ' ||
        'PALIQEFETIBSMUN         = :11, ' ||
        'VIBSMUN                 = :12, ' ||
        'ALIQCBS                 = :13, ' ||
        'PREDALIQCBS             = :14, ' ||
        'PALIQEFETCBS            = :15, ' ||
        'VLCBS                   = :16 ' ||
        'WHERE NUMTRANSVENDA = :17 AND NUMTRANSITEM = :18 AND CODPROD = :19'
      USING
        P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO_CBSIBS, -- :1
        P_DADOS_TRIBUTOS.CST_CBSIBS,               -- :2
        P_DADOS_TRIBUTOS.CCLASSTRIB_CBSIBS,        -- :3
        P_DADOS_TRIBUTOS.VALOR_BASE_CBSIBS,        -- :4
        P_DADOS_TRIBUTOS.PERC_IBS_UF,              -- :5
        P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_UF,     -- :6
        P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_UF,      -- :7
        P_DADOS_TRIBUTOS.VALOR_IBS_UF,             -- :8
        P_DADOS_TRIBUTOS.PERC_IBS_MUN,             -- :9
        P_DADOS_TRIBUTOS.PERC_RED_ALIQ_IBS_MUN,    -- :10
        P_DADOS_TRIBUTOS.ALIQ_EFETIVA_IBS_MUN,     -- :11
        P_DADOS_TRIBUTOS.VALOR_IBS_MUN,            -- :12
        P_DADOS_TRIBUTOS.PERC_CBS,                 -- :13
        P_DADOS_TRIBUTOS.PERC_RED_CBS,             -- :14
        P_DADOS_TRIBUTOS.ALIQ_EFETIVA_CBS,         -- :15
        P_DADOS_TRIBUTOS.VALOR_CBS,                -- :16
        P_LISTA_DADOS_NOTAS.NUMTRANSVENDA,         -- :17
        P_LISTA_DADOS_NOTAS.NUMTRANSITEM,          -- :18
        P_LISTA_DADOS_NOTAS.CODPROD                -- :19
        ;

    PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para CBSIBS: ' || SQL%ROWCOUNT, 'S');

    EXCEPTION
      WHEN OTHERS THEN
        PKG_DEBUGGING_FWPC.LOG(cMensagem3|| SQLERRM, 'S');        
    END;
  END GRAVAR_CBSIBS;
       
        
  PROCEDURE GRAVAR_IS(
      P_DADOS_TRIBUTOS IN FISCAL.TIPO_TRIBUT_REFORMA,
      P_LISTA_DADOS_NOTAS IN PKG_CENTRAL_TRIBUTOS_CONSULTAS.C_DADOS_NF_SAIDA_NORMAL%ROWTYPE) IS
      v_tabela VARCHAR2(15);
  BEGIN
    IF (P_PARAMETROS_CENTRAL_TRIBUTOS.PRE_FATURAMENTO = 'S') AND
       (P_PARAMETROS_CENTRAL_TRIBUTOS.ESPECIE = 'NF') THEN
      v_tabela := 'PCMOVPREFAT';
    ELSE
      v_tabela := 'PCMOV';
    END IF;

    EXECUTE IMMEDIATE
      'UPDATE ' || v_tabela || ' SET ' ||
      'CODIGOTRIBUTACAOIS = :1, CSTIS = :2, CCLASSTRIBIS = :3, ' ||
      'VLBASEIS = :4, ALIQIS = :5, VLIS = :6 ' ||
      'WHERE NUMTRANSVENDA = :7 AND NUMTRANSITEM = :8 AND CODPROD = :9'
    USING
      P_DADOS_TRIBUTOS.CODIGO_TRIBUTACAO_IS,
      P_DADOS_TRIBUTOS.CST_IS,
      P_DADOS_TRIBUTOS.CCLASSTRIB_IS,
      P_DADOS_TRIBUTOS.VALOR_BASE_IS,
      P_DADOS_TRIBUTOS.PERC_IS,
      P_DADOS_TRIBUTOS.VALOR_IS,
      P_LISTA_DADOS_NOTAS.NUMTRANSVENDA,
      P_LISTA_DADOS_NOTAS.NUMTRANSITEM,
      P_LISTA_DADOS_NOTAS.CODPROD;

      PKG_DEBUGGING_FWPC.LOG('Linhas atualizadas para IS: ' || SQL%ROWCOUNT, 'S');
    
    EXCEPTION
      WHEN OTHERS THEN
        PKG_DEBUGGING_FWPC.LOG(cMensagem4|| SQLERRM, 'S');        
    END GRAVAR_IS;          
  BEGIN
    
    IF (P_TIPO_GRAVACAO =  'CBSIBS') THEN
      GRAVAR_CBSIBS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    END IF;
    
    IF (P_TIPO_GRAVACAO =  'IS') THEN
      GRAVAR_IS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
    END IF;
    
    IF (P_TIPO_GRAVACAO =  'TODOS') THEN
      GRAVAR_CBSIBS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);
      GRAVAR_IS(P_DADOS_TRIBUTOS, P_LISTA_DADOS_NOTAS);      
    END IF;        
  END GRAVAR_PCMOV_TRIBUTO;     

  -- Função para calcular e gravar CBS e IBS
  FUNCTION CALCULAR_E_GRAVAR_CBSIBS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS

    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);

  BEGIN
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_CBSIBS', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de CBSIBS', 'S');
    
    V_PARAMETROS_CENTRAL_TRIBUTOS := P_PARAMETROS_CENTRAL_TRIBUTOS;    

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP

      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO,
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_CBSIBS(V_DADOS_TRIBUTACAO, V_MSG);
      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, 
                           V_LISTA_DADOS_NOTA(POSICAO_ITEM),                            
                           P_PARAMETROS_CENTRAL_TRIBUTOS,
                           'CBSIBS');
    END LOOP;

    PKG_DEBUGGING_FWPC.DESATIVARDEBUG;

    V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem1;
    V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem1;
    RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;

  EXCEPTION
    WHEN OTHERS THEN
      PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_CBSIBS: ' || SQLERRM, 'S');
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem3;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO := cMensagem3||SQLERRM;      
      RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_CBSIBS;



  -- Função para calcular e gravar IS
  FUNCTION CALCULAR_E_GRAVAR_IS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS
    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);

  BEGIN
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_IS', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de IS', 'S');
    
    V_PARAMETROS_CENTRAL_TRIBUTOS := P_PARAMETROS_CENTRAL_TRIBUTOS;

    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP

      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO,
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_IS(V_DADOS_TRIBUTACAO, V_MSG);


      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, 
                           V_LISTA_DADOS_NOTA(POSICAO_ITEM),                            
                           P_PARAMETROS_CENTRAL_TRIBUTOS,
                           'IS');
    END LOOP;

    PKG_DEBUGGING_FWPC.DESATIVARDEBUG;
    
    V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem1;
    V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem1;
    
    RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;

  EXCEPTION
    WHEN OTHERS THEN
      PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_IS: ' || SQLERRM, 'S');
      V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem4;
      V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO := cMensagem4||SQLERRM;
      RETURN P_PARAMETROS_CENTRAL_TRIBUTOS;
  END CALCULAR_E_GRAVAR_IS;



  --Função para calcular e gravar todos os tributos
  FUNCTION CALCULAR_E_GRAVAR_TODOS_TRIB(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS IS
    V_DADOS_TRIBUTACAO FISCAL.TIPO_TRIBUT_REFORMA;
    V_PARAMETROS_CENTRAL_TRIBUTOS T_PARAMETROS_CENTRAL_TRIBUTOS;
    V_LISTA_DADOS_NOTA T_LISTA_DADOS_NOTAS;
    V_MSG VARCHAR2(4000);
  BEGIN    
    
    IF (RETORNA_GRAVARLOG = 'S') THEN
      PKG_DEBUGGING_FWPC.ATIVARDEBUG('CALCULAR_E_GRAVAR_TODOS_TRIB', '1.0', P_PARAMETROS_CENTRAL_TRIBUTOS.NUMERO_TRANSACAO);
    END IF;

    PKG_DEBUGGING_FWPC.LOG('Inicio do cálculo e gravação de todos os tributos', 'S');
    
    V_PARAMETROS_CENTRAL_TRIBUTOS := P_PARAMETROS_CENTRAL_TRIBUTOS;    
  
    V_LISTA_DADOS_NOTA := CONSULTAR_DADOS_MOVIMENTACAO(P_PARAMETROS_CENTRAL_TRIBUTOS);

    FOR POSICAO_ITEM IN 1 .. V_LISTA_DADOS_NOTA.COUNT LOOP

      V_DADOS_TRIBUTACAO := TRANSPORTAR_LISTA_PARA_TRIB(V_DADOS_TRIBUTACAO,
                                                        V_LISTA_DADOS_NOTA(POSICAO_ITEM));

      V_DADOS_TRIBUTACAO := LIMPAR_VALOR_TRIBUTO(V_DADOS_TRIBUTACAO);
      V_DADOS_TRIBUTACAO := FISCAL.CALCULAR_TODOS_TRIBUTOS(V_DADOS_TRIBUTACAO, V_MSG);

      GRAVAR_PCMOV_TRIBUTO(V_DADOS_TRIBUTACAO, 
                           V_LISTA_DADOS_NOTA(POSICAO_ITEM),                            
                           P_PARAMETROS_CENTRAL_TRIBUTOS,
                           'TODOS');

    END LOOP;
    
    V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem1;
    V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO        := cMensagem1;
    RETURN V_PARAMETROS_CENTRAL_TRIBUTOS;
    
  EXCEPTION
     WHEN OTHERS THEN
     BEGIN
        PKG_DEBUGGING_FWPC.LOG('Erro no CALCULAR_E_GRAVAR_IS: ' || SQLERRM, 'S');       
        
        V_PARAMETROS_CENTRAL_TRIBUTOS.CODIGO_MENSAGEM_RETORNO := cCodMensagem2;       
        V_PARAMETROS_CENTRAL_TRIBUTOS.MENSAGEM_RETORNO := cMensagem2||SQLERRM;        
        RETURN V_PARAMETROS_CENTRAL_TRIBUTOS;        
     END;                      
  END CALCULAR_E_GRAVAR_TODOS_TRIB;



END PKG_CENTRAL_TRIBUTOS;
