CREATE OR REPLACE PACKAGE PKG_CENTRAL_TRIBUTOS AS

  V_GRAVAR_LOG VARCHAR2(1) := 'N';
  
  TYPE T_PARAMETROS_CENTRAL_TRIBUTOS IS RECORD(
     CODIGO_FILIAL             VARCHAR2(2),
     NUMERO_NOTA               NUMBER,
     NUMERO_TRANSACAO          NUMBER,
     NUMERO_PEDIDO             NUMBER,

     TIPOMOVIMENTO             VARCHAR2(1),
     DEVOLUCAO                 VARCHAR2(1),     
     PRE_FATURAMENTO           VARCHAR2(1),
     
     CODIGO_MENSAGEM_RETORNO   NUMBER,
     MENSAGEM_RETORNO          VARCHAR2(4000)
  );  
  
  FUNCTION RETORNA_GRAVARLOG RETURN VARCHAR2;
  
  FUNCTION CALCULAR_E_GRAVAR_CBSIBS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS;

  FUNCTION CALCULAR_E_GRAVAR_IS(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS;

  FUNCTION CALCULAR_E_GRAVAR_TODOS_TRIB(P_PARAMETROS_CENTRAL_TRIBUTOS IN T_PARAMETROS_CENTRAL_TRIBUTOS)
    RETURN T_PARAMETROS_CENTRAL_TRIBUTOS;

END PKG_CENTRAL_TRIBUTOS;
