CREATE OR REPLACE TRIGGER TRG_PCTABPRCLI_DTALTERACAO
AFTER INSERT OR UPDATE ON PCTABPRCLI
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	UPDATE PCREGIAO SET DTALTERACAO = SYSDATE WHERE PCREGIAO.NUMREGIAO = :NEW.NUMREGIAO;
END;