DECLARE
    CURSOR C_CONSTRAINTS IS
    SELECT A.CONSTRAINT_NAME, A.TABLE_NAME
      FROM USER_CONSTRAINTS A
     WHERE A.TABLE_NAME = 'PCVIGENCIANTSEFAZ'
       AND A.INDEX_NAME IS NOT NULL
      AND  A.CONSTRAINT_TYPE <> 'P';
BEGIN
    FOR C IN C_CONSTRAINTS LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || C.TABLE_NAME || ' DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
    END LOOP;
    
    EXECUTE IMMEDIATE 'ALTER TABLE PCVIGENCIANTSEFAZ ADD CONSTRAINT PCVIGENCIANTSEFAZ_UK1 UNIQUE (IDENTIFICADOR_NT, UF, AMBIENTE)';
END;
