DECLARE
  VCONSTRAINT USER_INDEXES.INDEX_NAME%TYPE;
  CURSOR C_CONSTRAINTS(PCONSTRAINT VARCHAR2) IS
    SELECT A.CONSTRAINT_NAME, A.TABLE_NAME
      FROM USER_CONSTRAINTS A
     WHERE A.TABLE_NAME = 'PCVIGENCIANTSEFAZ'
       AND A.CONSTRAINT_NAME = PCONSTRAINT 
       AND A.INDEX_NAME IS NOT NULL
       AND A.CONSTRAINT_TYPE <> 'P';  
       
  CURSOR C_INDEXES IS
    SELECT A.INDEX_NAME, COUNT(B.COLUMN_NAME) QTDECOLUMN
      FROM USER_INDEXES A
         , USER_IND_COLUMNS B
         , USER_CONSTRAINTS C
     WHERE A.TABLE_NAME = 'PCVIGENCIANTSEFAZ'
       AND A.INDEX_NAME = C.INDEX_NAME
       AND C.CONSTRAINT_TYPE <> 'P'
       AND A.INDEX_NAME = B.INDEX_NAME
       AND A.TABLE_NAME = B.TABLE_NAME
       AND A.INDEX_TYPE = 'NORMAL'
  GROUP BY A.INDEX_NAME;
BEGIN
  FOR C IN C_INDEXES LOOP
    IF C.QTDECOLUMN <> 3 THEN
      VCONSTRAINT := C.INDEX_NAME;
      FOR C IN C_CONSTRAINTS(VCONSTRAINT) LOOP
        BEGIN
          EXECUTE IMMEDIATE 'ALTER TABLE ' || C.TABLE_NAME || ' DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
        EXCEPTION
          WHEN OTHERS THEN
            NULL;
        END;    
      END LOOP;   
             
      BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX ' || C.INDEX_NAME;
      EXCEPTION
        WHEN OTHERS THEN
          NULL;
      END;
    END IF;    
  END LOOP;
  
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCVIGENCIANTSEFAZ ADD CONSTRAINT PCVIGENCIANTSEFAZ_UK1 UNIQUE (IDENTIFICADOR_NT, UF, AMBIENTE)';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;    
END;
