BEGIN
  
  FOR C IN (SELECT CONSTRAINT_NAME, TABLE_NAME
              FROM USER_CONSTRAINTS
             WHERE TABLE_NAME = 'PCVIGENCIANTSEFAZ'
               AND INDEX_OWNER IS NOT NULL
               AND CONSTRAINT_TYPE <> 'P') LOOP
			   
	DELETE FROM PCVIGENCIANTSEFAZ; 
  
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || C.TABLE_NAME || ' DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
    EXCEPTION
      WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Erro ao remover chave única da tabela PCVIGENCIANTSEFAZ: ' || sqlerrm);
    END;
  END LOOP;
  
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCVIGENCIANTSEFAZ ADD CONSTRAINT PCVIGENCIANTSEFAZ_UK1 UNIQUE (IDENTIFICADOR_NT, UF, AMBIENTE)';
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, 'Erro ao criar chave composta na tabela PCVIGENCIANTSEFAZ: ' || sqlerrm);
  END;
END;
