CREATE OR REPLACE VIEW VW_INT_C5_OBTER_FILIAIS_C5 AS
SELECT P.CODFILIAL, F.CODFILIALINTEGRACAO
       FROM PCPARAMFILIAL P, PCFILIAL F
      WHERE P.NOME = 'USAINTEGRACAOCONSINCO'
       AND NVL(P.VALOR, 'N') = 'S'
	   AND P.CODFILIAL = F.CODIGO
       AND P.CODFILIAL <> '99'
