CREATE OR REPLACE VIEW VW_INT_C5_OBTER_FILIAIS_C5 AS
SELECT CODFILIAL
       FROM PCPARAMFILIAL
      WHERE NOME = 'USAINTEGRACAOCONSINCO'
       AND NVL(VALOR, 'N') = 'S'
       AND CODFILIAL <> '99'
