CREATE OR REPLACE VIEW VW_INT_C5_CLI_CONV_PERIODO AS
(
SELECT DISTINCT
       F.CODFINALIZADORA NROFORMAPAGTO,
       F.CODFINALIZADORA SEQPERIODO,
       TRUNC(SYSDATE)  DTAINICIO,
       CASE WHEN (NVL(P.PRAZO1, 0) > 0) AND (P.FORMAPARCELAMENTO = 'C') THEN TRUNC(SYSDATE) + NVL(P.PRAZO1, 0) ELSE TRUNC(SYSDATE) + 30 END DTAFIM,
       CASE WHEN (NVL(P.PRAZO1, 0) > 0) AND (P.FORMAPARCELAMENTO = 'C')THEN TRUNC(SYSDATE) + NVL(P.PRAZO1, 0) ELSE TRUNC(SYSDATE) + 30 END DTAVENCTO,
       'S' ATIVO
       
FROM (SELECT DISTINCT * FROM PCFINALIZADORA FIN, VW_INT_C5_OBTER_FILIAIS_C5 C5 WHERE FIN.CODFILIAL = C5.CODFILIAL) F, PCPLPAG P
WHERE ((F.ESPECIE = 'CNV') OR ((F.ESPECIE = 'O') AND (F.CODCOB = 'CONV'))) 
AND  F.DTINATIVACAO IS NULL   
AND F.CODPLPAG = P.CODPLPAG 
)
