CREATE OR REPLACE VIEW VW_INT_C5_CLI_CONV_PERIODO AS
(
SELECT DISTINCT
       F.CODFINALIZADORA NROFORMAPAGTO,
       F.CODFINALIZADORA SEQPERIODO,
       TRUNC(SYSDATE)  DTAINICIO,
       TRUNC(SYSDATE) + 100000 DTAFIM,
       TRUNC(SYSDATE) + 100000 DTAVENCTO,
       'S' ATIVO
       
FROM (SELECT DISTINCT * FROM PCFINALIZADORA FIN, VW_INT_C5_OBTER_FILIAIS_C5 C5 WHERE FIN.CODFILIAL = C5.CODFILIAL) F
WHERE ((F.ESPECIE = 'CNV') OR ((F.ESPECIE = 'O') AND (F.CODCOB = 'CONV'))) 
AND  F.DTINATIVACAO IS NULL   
)
