BEGIN
   FOR CC IN (SELECT C.NUMTRANSACAO
                   , C.NUMCARTACORRECAO
                   , E.ROWID LINHA
                FROM PCCARTACORRECAOC C
                   , PCDOCELETRONICO E
               WHERE C.SITUACAOCCE = 135
                 AND C.ESPECIE = 'CC'
                 AND TRUNC(C.DATACARTACORRECAO) >= TO_DATE('01-jan-2025')
                 AND C.NUMCARTACORRECAO = E.NUMTRANSACAO
                 AND E.MOVIMENTO = 'C'
                 AND E.XMLCCE IS NOT NULL)
   LOOP
      UPDATE PCDOCELETRONICO
         SET NUMTRANSACAO = CC.NUMTRANSACAO
       WHERE ROWID = CC.LINHA;
      COMMIT;
   END LOOP;
END;
