CREATE OR REPLACE VIEW VW_INT_C5_NFESAT AS
SELECT CFE.SEQDOCTO,
       CFE.NROEMPRESA,
       CFE.NROCHECKOUT,
       'SF' DOCEMISSAO,
       CFE.CHAVE CHAVESAT,
       CFE.CHAVECANC CHAVECANC,
       CFE.NROSERIESAT NUMSERIESAT,
       CFE.NROCFE NUMSESSAOSAT,
       CFE.NROCFECANC NUMSESSAOSATCANC,
       D.DTAHOREMISSAO DTAHORRECEBIMENTO,
       100 SITUACAOSAT,
       100 CODSEFAZSAT,
       100 CODSTATUSSAT,
       NULL chavenf,
       NULL protocoloenvio,
       CFE.AMBIENTE,
       NULL XMLNF,
       NULL XMLCANCNF,
       CFEXML.QRCODE QRCODESAT,
       NULL QRCODENF,
       CFEXML.XML XMLSAT,
       CFEXML.XMLCANC XMLCANCSAT,
       NULL PROTOCOLOCANCNF,
       NULL DATACANCNF
FROM MONITORPDVMIDDLE.TB_DOCTOCFE CFE,
     MONITORPDVMIDDLE.TB_DOCTOCFEXML CFEXML,
     MONITORPDVMIDDLE.TB_DOCTO D
WHERE CFE.SEQDOCTO = CFEXML.SEQDOCTO
AND CFE.NROEMPRESA = CFEXML.NROEMPRESA
AND CFE.NROCHECKOUT = CFEXML.NROCHECKOUT
AND D.NROEMPRESA = CFE.NROEMPRESA
AND D.NROCHECKOUT = CFE.NROCHECKOUT
AND D.SEQDOCTO = CFE.SEQDOCTO
AND D.NROEMPRESA = CFEXML.NROEMPRESA
AND D.NROCHECKOUT = CFEXML.NROCHECKOUT
AND D.SEQDOCTO = CFEXML.SEQDOCTO
UNION ALL         
SELECT NFE.SEQDOCTO,
       NFE.NROEMPRESA,
       NFE.NROCHECKOUT,
       'CE' DOCEMISSAO,
       NULL CHAVESAT,
       NULL CHAVECANC,
       NULL NUMSERIESAT,
       NULL NUMSESSAOSAT,
       NULL NUMSESSAOSATCANC,
       NFE.DTAHORRECEBIMENTO,
       NULL SITUACAOSAT,
       NULL CODSEFAZSAT,
       NULL CODSTATUSSAT,
       NFE.CHAVENF,
       NFE.protocoloenvio,
       NFE.AMBIENTE,
       NFEXML.XML XMLNF,
       NFEXML.XMLCANC XMLCANCNF,
       NULL QRCODESAT,
       NFEXML.QRCODE QRCODENF,
       NULL XMLSAT,
       NULL XMLCANCSAT,
       NFE.PROTOCOLOCANCELAMENTO PROTOCOLOCANCNF,
       NFE.DTAHORCANCELAMENTO DATACANCNF
FROM MONITORPDVMIDDLE.TB_DOCTONFE NFE,
     MONITORPDVMIDDLE.TB_DOCTONFEXML NFEXML
WHERE NFE.SEQDOCTO = NFEXML.SEQDOCTO
AND NFE.NROEMPRESA = NFEXML.NROEMPRESA
AND NFE.NROCHECKOUT = NFEXML.NROCHECKOUT
AND NFE.PROTOCOLOENVIO IS NOT NULL