CREATE OR REPLACE VIEW VW_INT_C5_NFESAT AS
SELECT NFE.SEQDOCTO,
       NFE.NROEMPRESA,
       NFE.NROCHECKOUT,
       'CE' DOCEMISSAO,
       NULL CHAVESAT,
       NULL CHAVECANC,
       NULL NUMSERIESAT,
       NULL NUMCUPOMSAT,
       NULL NUMCUPOMCANCSAT,
       NFE.DTAHORRECEBIMENTO,
       NULL SITUACAOSAT,
       NULL CODSEFAZSAT,
       NULL CODSTATUSSAT,
       NFE.CHAVENF,
       NFE.protocoloenvio,
       NFE.AMBIENTE,
       NFEXML.XML XMLNF,
       NFEXML.XMLCANC XMLCANCNF,
       NULL QRCODESAT,
       NFEXML.QRCODE QRCODENF,
       NULL XMLSAT,
       NULL XMLCANCSAT,
       NFE.PROTOCOLOCANCELAMENTO PROTOCOLOCANCNF,
       NFE.DTAHORCANCELAMENTO DATACANCNF,
       NFE.TIPOENVIO
FROM MONITORPDVMIDDLE.TB_DOCTONFE NFE,
     MONITORPDVMIDDLE.TB_DOCTONFEXML NFEXML
WHERE NFE.SEQDOCTO = NFEXML.SEQDOCTO (+)
AND NFE.NROEMPRESA = NFEXML.NROEMPRESA (+)
AND NFE.NROCHECKOUT = NFEXML.NROCHECKOUT (+)
AND NFE.PROTOCOLOENVIO IS NOT NULL