CREATE OR REPLACE PACKAGE BODY PKG_MONITOR_TRIBUTARIO AS

  PROCEDURE APAGARTABELATEMPORARIA(PTABELA IN VARCHAR2) IS
    V_SQL_DROP VARCHAR2(2000);
    V_SQL_TRUNCATE VARCHAR2(2000); 
  BEGIN
    V_SQL_TRUNCATE := 'TRUNCATE TABLE ' || PTABELA;   
    V_SQL_DROP := 'DROP TABLE ' || PTABELA;
    
    BEGIN
      EXECUTE IMMEDIATE V_SQL_TRUNCATE;
    EXCEPTION
     
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;    
    
    BEGIN
      EXECUTE IMMEDIATE V_SQL_DROP;
    EXCEPTION
     
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
  END APAGARTABELATEMPORARIA;

  PROCEDURE CRIARTABELA_PCNFSAID(PTABELA IN VARCHAR2, PDATAFINAL IN DATE) IS
    V_SQL_CREATE VARCHAR2(2000);
  BEGIN

    V_SQL_CREATE := 'CREATE TABLE ' || PTABELA || ' AS ' || GET_VALORES_FATURAMENTO;
    EXECUTE IMMEDIATE V_SQL_CREATE
     USING PDATAFINAL;
  END CRIARTABELA_PCNFSAID;
  
  PROCEDURE CRIARTABELA_CODFISCAL(PTABELA IN VARCHAR2, PDATAFINAL IN DATE) IS
    V_SQL_CREATE VARCHAR2(4000);
  BEGIN
    V_SQL_CREATE := 'CREATE TABLE ' || PTABELA || ' AS ' ||GET_NOTAS_CODIGO_FISCAL;  
    EXECUTE IMMEDIATE V_SQL_CREATE USING PDATAFINAL, PDATAFINAL;
  END CRIARTABELA_CODFISCAL;

  PROCEDURE CRIARTABELA_ITENS(PTABELA IN VARCHAR2, PDATAFINAL IN DATE) IS
    V_SQL_CREATE VARCHAR2(4000);
  BEGIN
    V_SQL_CREATE := 'CREATE TABLE ' || PTABELA || ' AS ' ||GET_VALORES_ITENS;  
    EXECUTE IMMEDIATE V_SQL_CREATE USING PDATAFINAL;
  END CRIARTABELA_ITENS;  
  

  PROCEDURE CRIARMONITORTRIBUTARIO IS
     C_TABELA_TEMPPCNFSAID CONSTANT VARCHAR2(30) := 'PCMONITORPCNFSAID'; 
     C_TABELA_TEMPCODFISCAL CONSTANT VARCHAR2(30) := 'PCMONITORCODFISCAL';
     C_TABELA_TEMPPCMOV CONSTANT VARCHAR2(30) := 'PCMONITORPCMOV';  
     V_DATA_FINAL DATE;
  BEGIN
    V_DATA_FINAL := SYSDATE;
    
    IF TO_CHAR(V_DATA_FINAL, 'HH24MI') < 8 THEN
      V_DATA_FINAL := SYSDATE-1;      
    ELSE
      V_DATA_FINAL := SYSDATE;  
    END IF;    
  
    APAGARTABELATEMPORARIA(C_TABELA_TEMPPCNFSAID);
    APAGARTABELATEMPORARIA(C_TABELA_TEMPCODFISCAL);
    APAGARTABELATEMPORARIA(C_TABELA_TEMPPCMOV);
  
    CRIARTABELA_PCNFSAID(C_TABELA_TEMPPCNFSAID, V_DATA_FINAL);
    CRIARTABELA_CODFISCAL(C_TABELA_TEMPCODFISCAL, V_DATA_FINAL);
    CRIARTABELA_CODFISCAL(C_TABELA_TEMPPCMOV, V_DATA_FINAL);
    
  END CRIARMONITORTRIBUTARIO;

END PKG_MONITOR_TRIBUTARIO;
