CREATE OR REPLACE PACKAGE BODY PKG_MONITOR_TRIBUTARIO AS

  FUNCTION QUOTED(PTEXTO VARCHAR2) RETURN VARCHAR2 IS 
  BEGIN
    RETURN CHR(39) || PTEXTO || CHR(39);
  END QUOTED;
  
  
  FUNCTION QUOTEDDUPLO(PTEXTO VARCHAR2) RETURN VARCHAR2 IS 
  BEGIN
    RETURN CHR(39) || CHR(39) || PTEXTO || CHR(39) || CHR(39);
  END QUOTEDDUPLO;


  FUNCTION MONITOR_TRIBUTARIO_HABILITADO RETURN BOOLEAN IS 
  BEGIN
    RETURN TRUE;
  END MONITOR_TRIBUTARIO_HABILITADO;
  
  PROCEDURE LOG(PTEXTO VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.put_line(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') || ' - ' || PTEXTO);
  END LOG ;

  FUNCTION GET_TABELAS_MONITOR RETURN SYS_REFCURSOR AS 
    v_tabelas SYS_REFCURSOR;
  BEGIN
    OPEN v_tabelas FOR 'SELECT 
                          TABELAORIGEM, 
                          TABELATEMPORARIA, 
                          TABELAMONITOR, 
                          TABELADEPENDENCIA, 
                          INDICE 
                        FROM PCMONITORTRIBUTARIOLISTATABELA';
    RETURN v_tabelas;
  END GET_TABELAS_MONITOR;

  FUNCTION AMBIENTE_ESTA_PREPARADO RETURN VARCHAR2 IS
    v_DataAmbiente DATE;
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE 'SELECT DTPREPARACAOAMBIENTE
                         FROM PCCONTROLEPROCESSAMENTO
                         WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''
      INTO v_DataAmbiente;
    EXCEPTION 
      WHEN OTHERS THEN
        v_DataAmbiente := SYSDATE - 1;
    END;
    
    IF TRUNC(NVL(v_DataAmbiente, SYSDATE - 1)) = TRUNC(SYSDATE) THEN
      RETURN 'S';
    ELSE
      RETURN 'N';
    END IF;
  END AMBIENTE_ESTA_PREPARADO;
  

  PROCEDURE ATUALIZAR_DATA_ULTIMA_EXECUCAO IS
  BEGIN
    EXECUTE IMMEDIATE 'UPDATE PCCONTROLEPROCESSAMENTO SET 
                         DTULTPROCESSAMENTO = SYSDATE
                       WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''; 
    COMMIT;
  END ATUALIZAR_DATA_ULTIMA_EXECUCAO;

  PROCEDURE LIMPAR_DATA_ULTIMA_EXECUCAO IS
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE 'UPDATE PCCONTROLEPROCESSAMENTO SET
                           DTULTPROCESSAMENTO = NULL
                         WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO''';
      COMMIT;
    EXCEPTION  
      WHEN OTHERS THEN
        NULL;
    END;
  END LIMPAR_DATA_ULTIMA_EXECUCAO;

  PROCEDURE ATUALIZAR_DATA_PREPAMBIENTE IS
  BEGIN
    EXECUTE IMMEDIATE 'UPDATE PCCONTROLEPROCESSAMENTO SET 
                         DTPREPARACAOAMBIENTE = SYSDATE
                       WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''; 
    COMMIT;
  END ATUALIZAR_DATA_PREPAMBIENTE;


  FUNCTION TEM_DATA_ULTIMA_EXECUCAO RETURN VARCHAR2 IS
    v_Data DATE;
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE 'SELECT DTULTPROCESSAMENTO
                         FROM PCCONTROLEPROCESSAMENTO
                         WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''
      INTO v_Data;
    EXCEPTION
      WHEN OTHERS THEN
        v_Data := NULL;
    END;

    IF v_Data IS NOT NULL THEN
      RETURN 'S';
    ELSE
      RETURN 'N';
    END IF;
  END;


  FUNCTION GET_NOME_TABELA_FORMATADA(PPREFIXO IN VARCHAR2, PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
    v_Tabela VARCHAR2(30);
  BEGIN
    v_Tabela := SUBSTR(PTABELA, 3, LENGTH(PTABELA)); -- remove o prefixo PC
    v_Tabela := PPREFIXO || v_Tabela;
    v_Tabela := 'PC' || v_Tabela; -- restaura o prefixo PC

    RETURN  SUBSTR(v_Tabela, 1, 30);
  END GET_NOME_TABELA_FORMATADA;


  FUNCTION GET_CONSULTA_PREPARAR_AMBIENTE(PCONSULTA VARCHAR2) RETURN VARCHAR2 IS 
    v_TemGroupBy BOOLEAN;
  BEGIN
    v_TemGroupBy := INSTR(UPPER(PCONSULTA), 'GROUP BY') > 0;
  
    IF INSTR(UPPER(PCONSULTA), ' WHERE ') = 0 THEN
        IF v_TemGroupBy THEN
          RETURN REPLACE(PCONSULTA, ' WHERE ', ' WHERE ROWNUM = 0 ');
        ELSE
           RETURN PCONSULTA || ' WHERE ROWNUM = 0';
        END IF;
    ELSE
      IF v_TemGroupBy THEN
        RETURN REPLACE(PCONSULTA, ' WHERE ' , ' WHERE ROWNUM = 0 AND ');
      ELSE
        RETURN PCONSULTA || ' AND ROWNUM = 0';
      END IF;
    END IF;
  END GET_CONSULTA_PREPARAR_AMBIENTE;


  FUNCTION EXISTE_TABELA_TMPMON(PTABELA IN VARCHAR2) RETURN BOOLEAN IS
    v_ExisteTabela NUMBER;
  BEGIN
    SELECT COUNT(TABLE_NAME)
    INTO v_ExisteTabela
    FROM USER_TABLES
    WHERE TABLE_NAME = PTABELA;

    RETURN NVL(v_ExisteTabela,0) > 0;
  END EXISTE_TABELA_TMPMON;
  

  FUNCTION GET_TAMANHO_TABELA_EM_MB(PTABELA IN VARCHAR2) RETURN NUMBER IS 
    v_Tamanho NUMBER;
  BEGIN
    SELECT SUM(BYTES)/POWER(1024,2) 
    INTO v_Tamanho
    FROM USER_SEGMENTS 
    WHERE SEGMENT_NAME = PTABELA;  
    
    RETURN v_Tamanho;
  END GET_TAMANHO_TABELA_EM_MB; 

  
  FUNCTION GET_QUANTIDADE_REGISTROS_TAB(PTABELA IN VARCHAR2) RETURN NUMBER IS 
    C_COUNT_TABELA CONSTANT VARCHAR(100) := 'SELECT COUNT(1) FROM @TABELA';
    v_Query VARCHAR(100);
    v_QuantidadeRegistros NUMBER;
  BEGIN
    v_Query := REPLACE(C_COUNT_TABELA, '@TABELA', PTABELA);
    EXECUTE IMMEDIATE v_Query INTO v_QuantidadeRegistros;
    
    RETURN v_QuantidadeRegistros;
  END GET_QUANTIDADE_REGISTROS_TAB;


  FUNCTION GET_ESPACO_LIVRE_TABLESPACE_MB(PTABLESPACE IN VARCHAR2 := 'TS_DADOS') RETURN NUMBER IS 
    v_Tamanho NUMBER;
  BEGIN
    SELECT SUM(BYTES)/POWER(1024,2)
    INTO v_Tamanho
    FROM USER_FREE_SPACE
    WHERE TABLESPACE_NAME = PTABLESPACE;
    
    RETURN v_Tamanho;
  END GET_ESPACO_LIVRE_TABLESPACE_MB;


  FUNCTION GET_ESPACO_USADO_TABLESPACE(PTABLESPACE IN VARCHAR2 := 'TS_DADOS') RETURN NUMBER IS 
    v_Tamanho NUMBER;
  BEGIN
    SELECT SUM(BYTES)/POWER(1024,2) 
    INTO v_Tamanho
    FROM USER_SEGMENTS 
    WHERE TABLESPACE_NAME = PTABLESPACE;
    
    RETURN v_Tamanho;
  END GET_ESPACO_USADO_TABLESPACE;


  FUNCTION GET_NOME_TABELA_TEMPORARIA(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN GET_NOME_TABELA_FORMATADA('TMPMON', PTABELA);
  END GET_NOME_TABELA_TEMPORARIA;


  FUNCTION GET_NOME_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN GET_NOME_TABELA_FORMATADA('MONITOR', PTABELA);
  END GET_NOME_TABELA_MONITOR;


  FUNCTION EXISTE_TABELA_MONITOR(PTABELA VARCHAR2, PDATA DATE) RETURN BOOLEAN IS 
    v_QuantidadeTabela NUMBER;
    v_NomeTabela VARCHAR2(30);
  BEGIN
    v_NomeTabela := GET_NOME_TABELA_MONITOR(PTABELA);
  
    SELECT COUNT(1)
    INTO v_QuantidadeTabela
    FROM USER_OBJECTS
    WHERE OBJECT_TYPE = 'TABLE'
          AND OBJECT_NAME = v_NomeTabela
          AND TRUNC(CREATED) >= TRUNC(PDATA);
  
    RETURN v_QuantidadeTabela > 0;
  END EXISTE_TABELA_MONITOR;
  

  FUNCTION GET_VERSAO_OBJETO(PNOMEOBJETO IN VARCHAR2) RETURN VARCHAR2 IS
    v_Versao VARCHAR2(15);
  BEGIN
    BEGIN
      SELECT VERSAO
      INTO v_Versao
      FROM PCVERSAOBD
      WHERE ROTINA = PNOMEOBJETO;
    EXCEPTION 
      WHEN OTHERS THEN
        v_Versao := '0.0.00.000';  
    END;
      
    RETURN v_Versao;
  END GET_VERSAO_OBJETO;


  FUNCTION MULTIPLAS_EXECUCOES_HABILITADA RETURN BOOLEAN IS
    v_MultiplasExecucoes VARCHAR(1);
  BEGIN
    BEGIN      
      EXECUTE IMMEDIATE 'SELECT MULTIPLASEXECUCOES
                         FROM PCCONTROLEPROCESSAMENTO
                         WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''
      INTO v_MultiplasExecucoes;
    EXCEPTION 
      WHEN OTHERS THEN
        v_MultiplasExecucoes := 'S';
    END;  
    
    RETURN v_MultiplasExecucoes = 'S';
  END MULTIPLAS_EXECUCOES_HABILITADA;


  FUNCTION TABELA_MONITOR_DESATUALIZADA(PTABELA VARCHAR2) RETURN BOOLEAN IS 
    v_DataUltimoProcessamento DATE;
    v_DataCriacaoTabela DATE;
  BEGIN
    BEGIN      
      EXECUTE IMMEDIATE 'SELECT DTULTPROCESSAMENTO
                         FROM PCCONTROLEPROCESSAMENTO
                         WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''
      INTO v_DataUltimoProcessamento;
    EXCEPTION 
      WHEN OTHERS THEN
        v_DataUltimoProcessamento := SYSDATE - 1;
    END;  
      
    BEGIN      
      EXECUTE IMMEDIATE 'SELECT CREATED
                         FROM USER_OBJECTS
                         WHERE OBJECT_TYPE = ''TABLE''
                           AND OBJECT_NAME = ' || QUOTED(PTABELA)
      INTO v_DataCriacaoTabela;
    EXCEPTION 
      WHEN OTHERS THEN
        v_DataCriacaoTabela := SYSDATE - 1;
    END;

    RETURN (TRUNC(v_DataCriacaoTabela) < TRUNC(v_DataUltimoProcessamento)) 
           OR (v_DataUltimoProcessamento IS NULL);
  END TABELA_MONITOR_DESATUALIZADA;


  FUNCTION DADOS_ESTAO_DESATUALIZADOS RETURN BOOLEAN IS 
    v_DataUltimoProcessamento DATE;
    v_DataPreparacaoAmbiente DATE;
    v_Ativo VARCHAR2(1);
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE 'SELECT
                           NVL(DTULTPROCESSAMENTO, SYSDATE - 1),
                           NVL(DTPREPARACAOAMBIENTE, SYSDATE),
                           ATIVO
                         FROM PCCONTROLEPROCESSAMENTO
                         WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''
      INTO v_DataUltimoProcessamento,
           v_DataPreparacaoAmbiente,
           v_Ativo;
    EXCEPTION 
      WHEN OTHERS THEN
        v_DataUltimoProcessamento := SYSDATE - 1;
        v_Ativo := 'N';
    END;

    RETURN TRUNC(v_DataUltimoProcessamento) < TRUNC(v_DataPreparacaoAmbiente)
           AND NVL(v_Ativo, 'N') = 'S';
  END DADOS_ESTAO_DESATUALIZADOS;

  PROCEDURE GRAVAR_TABELA_NA_LISTA_TABELAS(PTABELA IN VARCHAR2, PINDICE IN VARCHAR2, PTABELADEPENDENCIA IN VARCHAR2) IS 
    v_Query VARCHAR2(4000);
  BEGIN
    v_Query := 'INSERT INTO PCMONITORTRIBUTARIOLISTATABELA (
                  TABELAORIGEM,
                  TABELATEMPORARIA,
                  TABELAMONITOR,
                  TABELADEPENDENCIA,
                  INDICE
                ) VALUES (
                  @TABELAORIGEM,
                  @TABELATEMPORARIA,
                  @TABELAMONITOR,
                  @TABELADEPENDENCIA,
                  @INDICE
                )';
                
    v_Query := REPLACE(v_Query, '@TABELAORIGEM', QUOTED(PTABELA));
    v_Query := REPLACE(v_Query, '@TABELATEMPORARIA', QUOTED(GET_NOME_TABELA_TEMPORARIA(PTABELA)));
    v_Query := REPLACE(v_Query, '@TABELAMONITOR', QUOTED(GET_NOME_TABELA_MONITOR(PTABELA)));
    v_Query := REPLACE(v_Query, '@TABELADEPENDENCIA', QUOTED(PTABELADEPENDENCIA));
    v_Query := REPLACE(v_Query, '@INDICE', QUOTED(PINDICE));
    
    EXECUTE IMMEDIATE v_Query;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      LOG('  Gravando tabela ' || PTABELA || ' na lista de tabelas. ERRO: ' || SQLERRM);
      ROLLBACK;
  END GRAVAR_TABELA_NA_LISTA_TABELAS;

  PROCEDURE INICIAR_TELEMETRIA(PTELEMETRIA IN OUT T_TELEMETRIA, PNOME_OBJETO IN VARCHAR2, PINTERVALOEMDIAS NUMBER) IS 
  BEGIN
    PTELEMETRIA.Objeto := SUBSTR(PNOME_OBJETO, 1, 30);
    PTELEMETRIA.IntervaloDeDadosEmDias := PINTERVALOEMDIAS;
    PTELEMETRIA.DataHoraInicio := SYSDATE;
    --PTELEMETRIA.DadosTableSapceInicio.EspacoUsadoEmMB := GET_ESPACO_USADO_TABLESPACE();
    --PTELEMETRIA.DadosTableSapceInicio.EspacoLivreEmMB := GET_ESPACO_LIVRE_TABLESPACE_MB();
  END INICIAR_TELEMETRIA;

  
  PROCEDURE CAPTURA_DADOS_TELEMETRIA_WT(PTELEMETRIA IN OUT T_TELEMETRIA, PTABELA IN VARCHAR2) IS
  BEGIN
    PTELEMETRIA.DadosDaTabelaWinthor.NomeDaTabela := PTABELA;
    --PTELEMETRIA.DadosDaTabelaWinthor.QuantidadeRegistrosTabela := GET_QUANTIDADE_REGISTROS_TAB(PTABELA);
    --PTELEMETRIA.DadosDaTabelaWinthor.TamanhoTabelaEmMB := GET_TAMANHO_TABELA_EM_MB(PTABELA);
  END CAPTURA_DADOS_TELEMETRIA_WT;
  
  
  PROCEDURE CAPTURA_DADOS_TELEMETRIA_MON(PTELEMETRIA IN OUT T_TELEMETRIA, PTABELA IN VARCHAR2) IS
  BEGIN
    PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela := GET_NOME_TABELA_MONITOR(PTABELA);
    --PTELEMETRIA.DadosDaTabelaMonitor.QuantidadeRegistrosTabela := GET_QUANTIDADE_REGISTROS_TAB(PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela);
    --PTELEMETRIA.DadosDaTabelaMonitor.TamanhoTabelaEmMB := GET_TAMANHO_TABELA_EM_MB(PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela);
  END CAPTURA_DADOS_TELEMETRIA_MON;


  PROCEDURE FINALIZAR_TELEMETRIA(PTELEMETRIA IN OUT T_TELEMETRIA) IS 
    v_Dados       VARCHAR2(4000);
    v_Usuario     VARCHAR2(30);
    v_Rotina      VARCHAR2(50);
    v_Versao      VARCHAR(60);
    v_Equipamento VARCHAR2(65);
    v_TempoDecorrido NUMBER;
  BEGIN
    PTELEMETRIA.DadosTableSapceFinal.EspacoUsadoEmMB := GET_ESPACO_USADO_TABLESPACE();
    PTELEMETRIA.DadosTableSapceFinal.EspacoLivreEmMB := GET_ESPACO_LIVRE_TABLESPACE_MB();
    PTELEMETRIA.DataHoraTermino := SYSDATE;
    
    v_Versao         := GET_VERSAO_OBJETO('PKG_MONITOR_TRIBUTARIO');
    v_Usuario        := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 30);
    v_Rotina         := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 48);
    v_Equipamento    := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 64);
    v_TempoDecorrido := (PTELEMETRIA.DataHoraTermino -  PTELEMETRIA.DataHoraInicio) * 24*60*60;
    
    v_Dados := '{'
	             || 'Identificador: @Identificador, '
	             || 'TempoDecorridoEmSegundos: @TempoDecorridoEmSegundos, '
	             || 'IntervaloDeDadosEmDias: @IntervaloDeDadosEmDias, '
	             || 'VersaoDaPacakage: @VersaoDaPacakage, '
	             || 'Usuario: @Usuario, '
	             || 'Terminal: @Terminal, '
	             || 'RotinaDoWinthor: @RotinaDoWinthor, '
	             || 'NomeDaTabelaDoWinthor: @NomeDaTabelaDoWinthor, '
	             || 'QuantidadeDeRegistrosTabelaWinthor: @QuantidadeDeRegistrosTabelaWinthor, '
	             || 'TamanhoTabelaEmMBWinthor: @TamanhoTabelaEmMBWinthor, '
	             || 'NomeDaTabelaDoMonitor: @NomeDaTabelaDoMonitor, '
               || 'QuantidadeDeRegistrosTabelaMonitor: @QuantidadeDeRegistrosTabelaMonitor, '
               || 'TamanhoTabelaEmMBMonitor: @TamanhoTabelaEmMBMonitor, '
               || 'EspacoUtilizadoNaTableSpaceEmMBAntesDeExecutar: @EspacoUtilizadoNaTableSpaceEmMBAntesDeExecutar, '
               || 'EspacoLivreNaTableSpaceEmMBAntesExecutar: @EspacoLivreNaTableSpaceEmMBAntesExecutar, '
               || 'EspacoUtilizadoNaTableSpaceEmMBAposExecutar: @EspacoUtilizadoNaTableSpaceEmMBAposExecutar, '
               || 'EspacoLivreNaTableSpaceEmMBAposExecutar: @EspacoLivreNaTableSpaceEmMBAposExecutar' 
               || '}';

    v_Dados := REPLACE(v_Dados, '@Identificador', QUOTEDDUPLO(PTELEMETRIA.Objeto));
    v_Dados := REPLACE(v_Dados, '@TempoDecorridoEmSegundos', TO_CHAR(v_TempoDecorrido));
    v_Dados := REPLACE(v_Dados, '@IntervaloDeDadosEmDias', PTELEMETRIA.IntervaloDeDadosEmDias);
    v_Dados := REPLACE(v_Dados, '@VersaoDaPacakage', QUOTEDDUPLO(v_Versao));
    v_Dados := REPLACE(v_Dados, '@Usuario', QUOTEDDUPLO(v_Usuario));
    v_Dados := REPLACE(v_Dados, '@Terminal', QUOTEDDUPLO(v_Equipamento));
    v_Dados := REPLACE(v_Dados, '@RotinaDoWinthor', QUOTEDDUPLO(v_Rotina));
    v_Dados := REPLACE(v_Dados, '@NomeDaTabelaDoWinthor', QUOTEDDUPLO(PTELEMETRIA.DadosDaTabelaWinthor.NomeDaTabela));
    v_Dados := REPLACE(v_Dados, '@QuantidadeDeRegistrosTabelaWinthor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaWinthor.QuantidadeRegistrosTabela)));
    v_Dados := REPLACE(v_Dados, '@TamanhoTabelaEmMBWinthor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaWinthor.TamanhoTabelaEmMB)));
    v_Dados := REPLACE(v_Dados, '@NomeDaTabelaDoMonitor', QUOTEDDUPLO(PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela));    
    v_Dados := REPLACE(v_Dados, '@QuantidadeDeRegistrosTabelaMonitor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaMonitor.QuantidadeRegistrosTabela)));
    v_Dados := REPLACE(v_Dados, '@TamanhoTabelaEmMBMonitor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaMonitor.TamanhoTabelaEmMB)));
    v_Dados := REPLACE(v_Dados, '@EspacoUtilizadoNaTableSpaceEmMBAntesDeExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceInicio.EspacoUsadoEmMB)));
    v_Dados := REPLACE(v_Dados, '@EspacoLivreNaTableSpaceEmMBAntesExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceInicio.EspacoLivreEmMB)));
    v_Dados := REPLACE(v_Dados, '@EspacoUtilizadoNaTableSpaceEmMBAposExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceFinal.EspacoUsadoEmMB)));
    v_Dados := REPLACE(v_Dados, '@EspacoLivreNaTableSpaceEmMBAposExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceFinal.EspacoLivreEmMB)));
    
    PTELEMETRIA.Dados := v_Dados;
  END FINALIZAR_TELEMETRIA;
  
  
  PROCEDURE GRAVAR_TELEMETRIA(PTELEMETRIA IN T_TELEMETRIA) IS 
    v_Query VARCHAR2(4000);
  BEGIN
    v_Query := 'INSERT INTO PCTELEMETRIAMONITOR (
                  DATAPROCESSAMENTO,
                  OBJETO,
                  DATAHORAINICIO,
                  DATAHORATERMINO,
                  DADOS    
                ) VALUES (
                  TRUNC(SYSDATE),
                  ''@param1'',
                  TO_DATE(''@param2'', ''DD/MM/YYYY HH24:MI:SS''),
                  TO_DATE(''@param3'', ''DD/MM/YYYY HH24:MI:SS''),
                  ''@param4''
                )';
              
    v_Query := REPLACE(v_Query, '@param1', PTELEMETRIA.Objeto);
    v_Query := REPLACE(v_Query, '@param2', TO_CHAR(PTELEMETRIA.DataHoraInicio, 'DD/MM/YYYY HH24:MI:SS'));
    v_Query := REPLACE(v_Query, '@param3', TO_CHAR(PTELEMETRIA.DataHoraTermino, 'DD/MM/YYYY HH24:MI:SS'));
    v_Query := REPLACE(v_Query, '@param4', PTELEMETRIA.Dados);
  
    EXECUTE IMMEDIATE v_Query;
    COMMIT;
  EXCEPTION 
    WHEN OTHERS THEN
      ROLLBACK;
  END GRAVAR_TELEMETRIA;
  
  
  PROCEDURE FINALIZAR_E_GRAVAR_TELEMETRIA(PTELEMETRIA IN OUT T_TELEMETRIA) IS 
  BEGIN
    FINALIZAR_TELEMETRIA(PTELEMETRIA);
    GRAVAR_TELEMETRIA(PTELEMETRIA);
  END FINALIZAR_E_GRAVAR_TELEMETRIA;


  PROCEDURE INICIAR_TELEMETRIA_CABECALHO(PTELEMETRIA IN OUT T_TELEMETRIA, PNOME_OBJETO IN VARCHAR2) IS 
    v_Dados VARCHAR2(4000);
  BEGIN
    PTELEMETRIA.Objeto := PNOME_OBJETO;
    PTELEMETRIA.DataHoraInicio := SYSDATE;
    
    v_Dados := '{'
	             || 'Identificador: @Identificador, '
               || '}';
               
    v_Dados := REPLACE(v_Dados, '@Identificador', QUOTEDDUPLO('*INICIO*'));
    
    PTELEMETRIA.Dados := v_Dados;
    
    GRAVAR_TELEMETRIA(PTELEMETRIA);
  END INICIAR_TELEMETRIA_CABECALHO;


  PROCEDURE FINALIZAR_TELEMETRIA_CABECALHO(PTELEMETRIA IN OUT T_TELEMETRIA) IS 
    v_Dados VARCHAR2(4000);
    v_TempoDecorrido NUMBER;
  BEGIN
    PTELEMETRIA.DataHoraTermino := SYSDATE;
    v_TempoDecorrido := (PTELEMETRIA.DataHoraTermino -  PTELEMETRIA.DataHoraInicio) * 24*60*60;
    
    v_Dados := '{'
	             || 'Identificador: @Identificador, '
	             || 'TempoDecorridoEmSegundos: @TempoDecorridoEmSegundos'
               || '}';
               
    v_Dados := REPLACE(v_Dados, '@Identificador', QUOTEDDUPLO('*FIM*'));
    v_Dados := REPLACE(v_Dados, '@TempoDecorridoEmSegundos', TO_CHAR(v_TempoDecorrido));
    
    PTELEMETRIA.Dados := v_Dados;

    GRAVAR_TELEMETRIA(PTELEMETRIA);
  END FINALIZAR_TELEMETRIA_CABECALHO;


  PROCEDURE CRIAR_TABELA(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
    v_Create VARCHAR2(4000);
  BEGIN
    LOG('Criando tabela ' || PTABELA);
    v_Create := 'CREATE TABLE ' || PTABELA || ' NOLOGGING PARALLEL AS ' || PCONSULTA;

    EXECUTE IMMEDIATE v_Create;
    LOG('Tabela ' || PTABELA || ' criada.');
  END CRIAR_TABELA;
  

  PROCEDURE CARREGAR_TABELA(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
    v_Create VARCHAR2(4000);
  BEGIN
    LOG('Preenchendo tabela ' || PTABELA); 
    v_Create := 'INSERT /*+ APPEND */ INTO ' || PTABELA || ' ' || PCONSULTA;

    EXECUTE IMMEDIATE v_Create;
    COMMIT;
    LOG('Tabela ' || PTABELA || ' preenchida.');
  END CARREGAR_TABELA;
  

  PROCEDURE LIMPAR_TABELA(PTABELA IN VARCHAR2) IS
    v_Truncate VARCHAR2(100);
  BEGIN
    LOG('Limpando tabela ' || PTABELA); 
    v_Truncate := 'TRUNCATE TABLE ' || PTABELA;

    BEGIN
      EXECUTE IMMEDIATE v_Truncate;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
    LOG('Tabela ' || PTABELA || ' limpa.');
  END LIMPAR_TABELA;


  PROCEDURE APAGAR_TABELA(PTABELA IN VARCHAR2) IS
    v_Drop VARCHAR2(100);
  BEGIN
    LOG('Apagando tabela ' || PTABELA);
    v_Drop := 'DROP TABLE ' || PTABELA;

    BEGIN
      EXECUTE IMMEDIATE v_Drop;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
    LOG('Tabela ' || PTABELA || ' apagada.');
  END APAGAR_TABELA;


  FUNCTION EXISTE_TABELA_TELEMETRIA RETURN BOOLEAN IS 
    v_ExisteTabela NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO v_ExisteTabela
    FROM USER_TABLES
    WHERE TABLE_NAME = 'PCTELEMETRIAMONITOR';
    
    RETURN v_ExisteTabela > 0;
  END EXISTE_TABELA_TELEMETRIA;

  PROCEDURE CRIAR_LISTA_TABELAS_MONITOR_TR IS 
  BEGIN
      EXECUTE IMMEDIATE PKG_MONITOR_TRIBUTARIO_CONSULT.GET_CREATE_LISTA_TABELA_MONIT;
  EXCEPTION 
      WHEN OTHERS THEN
        LOG('  Não foi possível gerar a lista de tabelas do monitor');
  END CRIAR_LISTA_TABELAS_MONITOR_TR;

  PROCEDURE CRIAR_ESTRUTURA_TELEMETRIA IS 
  BEGIN
    IF NOT EXISTE_TABELA_TELEMETRIA THEN
      EXECUTE IMMEDIATE PKG_MONITOR_TRIBUTARIO_CONSULT.GET_CREATE_TABELA_TELEMETRIA;
      EXECUTE IMMEDIATE 'CREATE INDEX PCTELEMETRIAMONITOR_IDX01 ON PCTELEMETRIAMONITOR(DATAPROCESSAMENTO) NOLOGGING TABLESPACE TS_INDICE';
    END IF;
  END CRIAR_ESTRUTURA_TELEMETRIA;


  FUNCTION EXISTE_TABELA_CONTROLEPROCESS RETURN BOOLEAN IS 
    v_ExisteTabela NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO v_ExisteTabela
    FROM USER_TABLES
    WHERE TABLE_NAME = 'PCCONTROLEPROCESSAMENTO';
    
    RETURN v_ExisteTabela > 0;
  END EXISTE_TABELA_CONTROLEPROCESS;


  PROCEDURE CRIAR_ESTRUTURA_CONTROLEPROC IS 
  BEGIN
    IF NOT EXISTE_TABELA_CONTROLEPROCESS THEN
      EXECUTE IMMEDIATE PKG_MONITOR_TRIBUTARIO_CONSULT.GET_CREATE_TABELA_CONTROLEPROC;
      EXECUTE IMMEDIATE 'CREATE INDEX PCCONTROLEPROCESSAMENTO_IDX01 ON PCCONTROLEPROCESSAMENTO(OBJETO) NOLOGGING TABLESPACE TS_INDICE';
      EXECUTE IMMEDIATE 'INSERT INTO PCCONTROLEPROCESSAMENTO(OBJETO, ATIVO) VALUES (''PKG_MONITOR_TRIBUTARIO'', ''S'')';

      COMMIT;
    END IF;
  END CRIAR_ESTRUTURA_CONTROLEPROC;


  PROCEDURE CRIAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
  BEGIN
    CRIAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA), PCONSULTA);
  END CRIAR_TABELA_TEMPORARIA;


  PROCEDURE CARREGAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
  BEGIN
    CARREGAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA), PCONSULTA);
  END CARREGAR_TABELA_TEMPORARIA;


  PROCEDURE LIMPAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2) IS
  BEGIN
    LIMPAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA));
  END LIMPAR_TABELA_TEMPORARIA;


  PROCEDURE APAGAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2) IS
  BEGIN
    APAGAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA));
  END APAGAR_TABELA_TEMPORARIA;


  PROCEDURE CRIAR_TABELA_MONITOR(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
  BEGIN
    CRIAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA), PCONSULTA);
  END CRIAR_TABELA_MONITOR;


  PROCEDURE LIMPAR_TABELA_MONITOR(PTABELA IN VARCHAR2) IS
  BEGIN
    LIMPAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA));
  END LIMPAR_TABELA_MONITOR;


  PROCEDURE APAGAR_TABELA_MONITOR(PTABELA IN VARCHAR2) IS
  BEGIN
    APAGAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA));
  END APAGAR_TABELA_MONITOR;


  PROCEDURE CARREGAR_TABELA_MONITOR(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
  BEGIN
    CARREGAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA), PCONSULTA);
  END CARREGAR_TABELA_MONITOR;


  PROCEDURE CRIAR_INDICES_TABELA(PTABELA IN VARCHAR2, PSTRINGINDICE IN VARCHAR2, PTABELATEMP IN BOOLEAN := FALSE) IS
    C_PADRAO_CREATE CONSTANT VARCHAR2(100) := 'CREATE INDEX @INDICE ON @TABELA(@CAMPOS) NOLOGGING TABLESPACE TS_INDICE';
    v_ScriptIndice VARCHAR2(2000);
    v_NomeTabela VARCHAR(30);
  BEGIN
    v_NomeTabela := GET_NOME_TABELA_MONITOR(PTABELA);

    IF PTABELATEMP THEN
      v_NomeTabela := GET_NOME_TABELA_TEMPORARIA(PTABELA);
    END IF;

    FOR LISTA_INDICE IN (
      WITH INDICE AS (
        SELECT PSTRINGINDICE STRINGINDICE
        FROM DUAL
      )
      SELECT
        ROWNUM NUMERO,
        REGEXP_SUBSTR( STRINGINDICE, '[^;]+', 1, LEVEL ) NOME_CAMPO_INDICE
      FROM INDICE
      CONNECT BY LEVEL <= LENGTH(STRINGINDICE) - LENGTH(REPLACE(STRINGINDICE, ';')) + 1
    ) LOOP
      IF NVL(TRIM(LISTA_INDICE.NOME_CAMPO_INDICE), 'X') <> 'X' THEN
        v_ScriptIndice := C_PADRAO_CREATE;
        v_ScriptIndice := REPLACE(v_ScriptIndice, '@INDICE', v_NomeTabela || '_IDX' || LISTA_INDICE.NUMERO);
        v_ScriptIndice := REPLACE(v_ScriptIndice, '@TABELA', v_NomeTabela);
        v_ScriptIndice := REPLACE(v_ScriptIndice, '@CAMPOS', LISTA_INDICE.NOME_CAMPO_INDICE);

        EXECUTE IMMEDIATE v_ScriptIndice;
      END IF;
    END LOOP;
  END CRIAR_INDICES_TABELA;

  PROCEDURE PREPARA_TABELA_MONITOR(PTABELA VARCHAR2, PSCRIPTINDICE IN VARCHAR2) IS 
    v_NomeTabelaTemporaria VARCHAR2(30);
    v_NomeTabelaMonitor VARCHAR2(30);
    v_ContinuaPreparacao BOOLEAN;
  BEGIN
    v_NomeTabelaTemporaria := GET_NOME_TABELA_TEMPORARIA(PTABELA);
    v_NomeTabelaMonitor    := GET_NOME_TABELA_MONITOR(PTABELA);
    
    v_ContinuaPreparacao   := EXISTE_TABELA_TMPMON(v_NomeTabelaTemporaria)
                              AND TABELA_MONITOR_DESATUALIZADA(v_NomeTabelaMonitor);

    IF v_ContinuaPreparacao THEN
      APAGAR_TABELA_MONITOR(PTABELA);
      CRIAR_TABELA_MONITOR(PTABELA, GET_CONSULTA_PREPARAR_AMBIENTE(PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_TABELA_MONITOR(v_NomeTabelaTemporaria)));
      IF NVL(TRIM(PSCRIPTINDICE), 'X') <> 'X' THEN
        CRIAR_INDICES_TABELA(PTABELA, PSCRIPTINDICE);
      END IF;
    END IF;
  END PREPARA_TABELA_MONITOR;

  PROCEDURE CRIATABELA_BASE(PTABELA IN VARCHAR2, PQUERY IN VARCHAR2, PSCRIPTINDICE IN VARCHAR2, PTABELADEPENDENCIA IN VARCHAR2, PAMBIENTEPREPARADO IN BOOLEAN) IS
  BEGIN
    IF NOT PAMBIENTEPREPARADO THEN
      GRAVAR_TABELA_NA_LISTA_TABELAS(PTABELA, PSCRIPTINDICE, PTABELADEPENDENCIA);
      APAGAR_TABELA_TEMPORARIA(PTABELA);
      CRIAR_TABELA_TEMPORARIA(PTABELA, GET_CONSULTA_PREPARAR_AMBIENTE(PQUERY));
      
      IF NVL(TRIM(PTABELADEPENDENCIA), 'XX') <> 'XX' THEN
        CRIAR_INDICES_TABELA(PTABELADEPENDENCIA, PSCRIPTINDICE, PTABELATEMP => TRUE);
      END IF;
    ELSE
      CARREGAR_TABELA_TEMPORARIA(PTABELA, PQUERY);
    END IF;
  END CRIATABELA_BASE;


  PROCEDURE CRIARTABELA_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFSAID';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFSAID(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFSAID,
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCNFSAID;


  PROCEDURE CRIARTABELA_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCMOV';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCMOV(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCMOV,
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCMOV;


  PROCEDURE CRIARTABELA_MOV_UNIFICADA(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCMOVUNIF';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_MOV_UNIFICADA(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_MOV_UNIFICADA,
      PTABELADEPENDENCIA => 'PCMOV',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_MOV_UNIFICADA;


  PROCEDURE CRIARTABELA_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFBASESAID';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFBASESAID(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFBASESAID,
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCNFBASESAID;


  PROCEDURE CRIARTABELA_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFBASEENT';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFBASEENT(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFBASEENT,
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCNFBASEENT;


  PROCEDURE CRIARTABELA_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFENT';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFENT(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFENT,
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCNFENT;


  PROCEDURE CRIARTABELA_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCESTCOM';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCESTCOM(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => '',
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCESTCOM;


  PROCEDURE CRIARTABELA_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCDEVFORNEC';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCDEVFORNEC(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => '',
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCDEVFORNEC;


  PROCEDURE CRIARTABELA_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCDEVAVULSO';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCDEVAVULSO(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => '',
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCDEVAVULSO;

  PROCEDURE CRIARTABELA_PCLANCINTER(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCLANCINTERMEDIARIA';
  BEGIN
    CRIATABELA_BASE(
      PTABELA            => C_TABELA,
      PQUERY             => PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL, PDATA_FINAL),
      PSCRIPTINDICE      => '',
      PTABELADEPENDENCIA => '',
      PAMBIENTEPREPARADO => PAMBIENTEPREPARADO
    );
  END CRIARTABELA_PCLANCINTER;


  FUNCTION USA_CONTABIL RETURN BOOLEAN IS
    V_UsaContabil NUMBER(3);
  BEGIN
    SELECT COUNT(1)
      INTO V_UsaContabil
      FROM PCPARAMFILIAL F
     WHERE F.NOME = 'FIL_USACONTABIL'
       AND F.VALOR = 'S';
       
    RETURN V_UsaContabil > 0;
  END USA_CONTABIL;


  PROCEDURE GERAR_TABELAS(PDATAINICIAL IN DATE, PDATAFINAL IN DATE, PAMBIENTEPREPARADO IN BOOLEAN) IS
  BEGIN
    LOG('  Gerando tabelas');
    CRIARTABELA_PCNFSAID(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCNFBASESAID(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCNFENT(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCNFBASEENT(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCMOV(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_MOV_UNIFICADA(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCESTCOM(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCDEVFORNEC(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    CRIARTABELA_PCDEVAVULSO(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    
    IF USA_CONTABIL THEN
      CRIARTABELA_PCLANCINTER(PDATAINICIAL, PDATAFINAL, PAMBIENTEPREPARADO);
    END IF;
    
    LOG('  Tabelas geradas');
  END GERAR_TABELAS;


  PROCEDURE PREPARA_AMBIENTE_MONITOR_TRIB IS 
    v_Telemetria T_TELEMETRIA;
    v_AtualizaAmbiente BOOLEAN;
  BEGIN
    LOG('*Preparando o ambiente*');
    v_AtualizaAmbiente := (AMBIENTE_ESTA_PREPARADO = 'S');
    LOG('Ambiente atualizado: ' || CASE WHEN v_AtualizaAmbiente THEN 'S' ELSE 'N' END);

    IF NOT v_AtualizaAmbiente THEN
      CRIAR_ESTRUTURA_CONTROLEPROC;
      ATUALIZAR_DATA_PREPAMBIENTE;
      LIMPAR_DATA_ULTIMA_EXECUCAO;
      LOG('  Data de atualização do ambiente realizada!');
      
      INICIAR_TELEMETRIA_CABECALHO(g_Telemetria, '** MONITOR TRIBUTARIO **');
      INICIAR_TELEMETRIA(v_Telemetria, 'PREPARA_AMBIENTE_MONITOR_TRIB', 0);
      
      LIMPAR_TABELA('PCMONITORTRIBUTARIOLISTATABELA');
      
      LOG('  Gerando estruturas do monitor');
      CRIAR_LISTA_TABELAS_MONITOR_TR;
      CRIAR_ESTRUTURA_TELEMETRIA;
      LOG('  Estruturas do monitor geradas');
      
      GERAR_TABELAS(
        PDATAINICIAL       => SYSDATE,
        PDATAFINAL         => SYSDATE,
        PAMBIENTEPREPARADO => FALSE
      );
      
      FINALIZAR_E_GRAVAR_TELEMETRIA(v_Telemetria);
      FINALIZAR_TELEMETRIA_CABECALHO(g_telemetria);
    END IF;
    LOG('*Ambiente preparado*');
  END PREPARA_AMBIENTE_MONITOR_TRIB;


  PROCEDURE CRIAR_MONITOR_TRIBUTARIO(PDATAINICIAL IN DATE := SYSDATE - 30, PDATAFINAL IN DATE := SYSDATE) IS
    v_Telemetria T_TELEMETRIA;
    v_DataInicial DATE;
    v_DataFinal DATE;
    v_GeraDados BOOLEAN;
  BEGIN
    INICIAR_TELEMETRIA_CABECALHO(v_Telemetria, 'CRIAR_MONITOR_TRIBUTARIO');

    v_DataInicial := NVL(PDATAINICIAL, SYSDATE - 30);
    v_DataFinal   := NVL(PDATAFINAL, SYSDATE);
    v_GeraDados   := MONITOR_TRIBUTARIO_HABILITADO
                     AND DADOS_ESTAO_DESATUALIZADOS
                     AND (AMBIENTE_ESTA_PREPARADO = 'S');

    IF v_GeraDados THEN
        GERAR_TABELAS(
          PDATAINICIAL       => v_DataInicial, 
          PDATAFINAL         => v_DataFinal,
          PAMBIENTEPREPARADO => TRUE 
        );
    END IF;
    
    FINALIZAR_TELEMETRIA_CABECALHO(v_Telemetria);
    FINALIZAR_TELEMETRIA_CABECALHO(g_telemetria);
  END CRIAR_MONITOR_TRIBUTARIO;

  PROCEDURE FINALIZAR_CARGA_MONITOR_TRIBUT IS 
    CR_REFCUR_TABELAS_MONITOR T_REFCUR_TABELA_MONITOR;
    LISTA_TABELAS_MONITOR     T_TABLE_TABELA_MONITOR;
  BEGIN
    IF TEM_DATA_ULTIMA_EXECUCAO = 'S' THEN
       RETURN;
    END IF;  
  
    CR_REFCUR_TABELAS_MONITOR := GET_TABELAS_MONITOR;
    
    LOOP
      FETCH CR_REFCUR_TABELAS_MONITOR BULK COLLECT INTO LISTA_TABELAS_MONITOR;
   
      FOR ITEM IN LISTA_TABELAS_MONITOR.FIRST .. LISTA_TABELAS_MONITOR.LAST LOOP
         APAGAR_TABELA_MONITOR(LISTA_TABELAS_MONITOR(ITEM).TABELAORIGEM);
         
         CRIAR_TABELA_MONITOR(
           LISTA_TABELAS_MONITOR(ITEM).TABELAORIGEM,
           PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_TABELA_MONITOR(LISTA_TABELAS_MONITOR(ITEM).TABELATEMPORARIA)
         );
         
         CRIAR_INDICES_TABELA(
           LISTA_TABELAS_MONITOR(ITEM).TABELAORIGEM, 
           LISTA_TABELAS_MONITOR(ITEM).INDICE
         );
         
         IF NVL(TRIM(LISTA_TABELAS_MONITOR(ITEM).TABELADEPENDENCIA), 'XX') <> 'XX' THEN
           LIMPAR_TABELA_TEMPORARIA(LISTA_TABELAS_MONITOR(ITEM).TABELADEPENDENCIA);
         END IF;
      END LOOP;
       
      EXIT WHEN LISTA_TABELAS_MONITOR.EXISTS(1) = FALSE;
      EXIT WHEN CR_REFCUR_TABELAS_MONITOR%NOTFOUND;
      EXIT WHEN LISTA_TABELAS_MONITOR.COUNT = 0;
    END LOOP;

    ATUALIZAR_DATA_ULTIMA_EXECUCAO;
  END FINALIZAR_CARGA_MONITOR_TRIBUT;


END PKG_MONITOR_TRIBUTARIO;
