CREATE OR REPLACE PACKAGE BODY PKG_MONITOR_TRIBUTARIO AS

  FUNCTION QUOTED(PTEXTO VARCHAR2) RETURN VARCHAR2 IS 
  BEGIN
    RETURN CHR(39) || PTEXTO || CHR(39);
  END QUOTED;
  
  
  FUNCTION QUOTEDDUPLO(PTEXTO VARCHAR2) RETURN VARCHAR2 IS 
  BEGIN
    RETURN CHR(39) || CHR(39) || PTEXTO || CHR(39) || CHR(39);
  END QUOTEDDUPLO;


  FUNCTION USA_MONITOR_TRIBUTARIO RETURN BOOLEAN IS 
  BEGIN
    RETURN TRUE;
  END USA_MONITOR_TRIBUTARIO;


  FUNCTION EXECUTA_CARGA_DO_MONITOR RETURN BOOLEAN IS 
    v_data_ultima_execucao DATE;
    v_ativo VARCHAR2(1);
    v_existe_tabela_monitor NUMBER;
  BEGIN
    BEGIN
      
      EXECUTE IMMEDIATE 'SELECT DTULTPROCESSAMENTO, ATIVO
                FROM PCCONTROLEPROCESSAMENTO
                WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''
      INTO v_data_ultima_execucao, v_ativo;
    EXCEPTION 
      WHEN OTHERS THEN
        v_data_ultima_execucao := SYSDATE - 1;
        v_ativo := 'N';
    END;
    
    SELECT COUNT(1)
    INTO v_existe_tabela_monitor
    FROM USER_OBJECTS
    WHERE OBJECT_TYPE = 'TABLE'
          AND OBJECT_NAME LIKE 'PCMONITOR%'
          AND CREATED >= SYSDATE;
    
    RETURN nvl(v_ativo, 'N') = 'S';
    RETURN TRUNC(SYSDATE) > TRUNC(v_data_ultima_execucao)
           and nvl(v_ativo, 'N') = 'S'
           and v_existe_tabela_monitor <= 0;
  END EXECUTA_CARGA_DO_MONITOR;
  

  PROCEDURE ATUALIZAR_DATA_ULTIMA_EXECUCAO IS
  BEGIN
    EXECUTE IMMEDIATE 'UPDATE PCCONTROLEPROCESSAMENTO SET 
                DTULTPROCESSAMENTO = SYSDATE
              WHERE OBJETO = ''PKG_MONITOR_TRIBUTARIO'''; 
  END ATUALIZAR_DATA_ULTIMA_EXECUCAO;


  FUNCTION GET_NOME_TABELA_FORMATADA(PPREFIXO IN VARCHAR2, PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
    v_tabela VARCHAR2(30);
  BEGIN
    v_tabela := SUBSTR(PTABELA, 3, LENGTH(PTABELA)); -- remove o prefixo PC
    v_tabela := PPREFIXO || v_tabela;
    v_tabela := 'PC' || v_tabela; -- restaura o prefixo PC

    RETURN  SUBSTR(v_tabela, 1, 30);
  END GET_NOME_TABELA_FORMATADA;


  FUNCTION GET_NOME_TABELA_TEMPORARIA(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN GET_NOME_TABELA_FORMATADA('TMPMON', PTABELA);
  END GET_NOME_TABELA_TEMPORARIA;


  FUNCTION GET_NOME_TABELA_MONITOR(PTABELA IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN GET_NOME_TABELA_FORMATADA('MONITOR', PTABELA);
  END GET_NOME_TABELA_MONITOR;


  FUNCTION VERIFICAR_EXISTE_TABELA_TMPMON(PTABELA IN VARCHAR2) RETURN BOOLEAN IS
    v_existe_tabela NUMBER;
  BEGIN
    SELECT COUNT(TABLE_NAME)
    INTO v_existe_tabela
    FROM USER_TABLES
    WHERE TABLE_NAME = PTABELA;

    RETURN v_existe_tabela > 0;
  END VERIFICAR_EXISTE_TABELA_TMPMON;
  

  FUNCTION GET_TAMANHO_TABELA_EM_MB(PTABELA IN VARCHAR2) RETURN NUMBER IS 
    v_tamanho NUMBER;
  BEGIN
    SELECT SUM(BYTES)/POWER(1024,2) 
    INTO v_tamanho
    FROM USER_SEGMENTS 
    WHERE SEGMENT_NAME = PTABELA;  
    
    RETURN v_tamanho;
  END GET_TAMANHO_TABELA_EM_MB; 

  
  FUNCTION GET_QUANTIDADE_REGISTROS_TAB(PTABELA IN VARCHAR2) RETURN NUMBER IS 
    C_COUNT_TABELA CONSTANT VARCHAR(100) := 'SELECT COUNT(1) FROM @TABELA';
    v_sql VARCHAR(100);
    v_quantidade_registros NUMBER;
  BEGIN
    v_sql := REPLACE(C_COUNT_TABELA, '@TABELA', PTABELA);
    EXECUTE IMMEDIATE v_sql INTO v_quantidade_registros;
    
    RETURN v_quantidade_registros;
  END GET_QUANTIDADE_REGISTROS_TAB;


  FUNCTION GET_ESPACO_LIVRE_TABLESPACE_MB(PTABLESPACE IN VARCHAR2 := 'TS_DADOS') RETURN NUMBER IS 
    v_tamanho NUMBER;
  BEGIN
    SELECT SUM(BYTES)/POWER(1024,2)
    INTO v_tamanho
    FROM USER_FREE_SPACE
    WHERE TABLESPACE_NAME = PTABLESPACE;
    
    RETURN v_tamanho;
  END GET_ESPACO_LIVRE_TABLESPACE_MB;


  FUNCTION GET_ESPACO_USADO_TABLESPACE(PTABLESPACE IN VARCHAR2 := 'TS_DADOS') RETURN NUMBER IS 
    v_tamanho NUMBER;
  BEGIN
    SELECT SUM(BYTES)/POWER(1024,2) 
    INTO v_tamanho
    FROM USER_SEGMENTS 
    WHERE TABLESPACE_NAME = PTABLESPACE;
    
    RETURN v_tamanho;
  END GET_ESPACO_USADO_TABLESPACE;


  FUNCTION GET_VERSAO_OBJETO(PNOMEOBJETO IN VARCHAR2) RETURN VARCHAR2 IS
    v_versao VARCHAR2(15);
  BEGIN
    BEGIN
      SELECT VERSAO
      INTO v_versao
      FROM PCVERSAOBD
      WHERE ROTINA = PNOMEOBJETO;
    EXCEPTION 
      WHEN OTHERS THEN
        v_versao := '0.0.01.000';  
    END;
      
    RETURN v_versao;
  END;

  PROCEDURE INICIAR_TELEMETRIA(PTELEMETRIA IN OUT T_TELEMETRIA, PNOME_OBJETO IN VARCHAR2) IS 
  BEGIN
    PTELEMETRIA.Objeto := PNOME_OBJETO;
    PTELEMETRIA.DataHoraInicio := SYSDATE;
    PTELEMETRIA.DadosTableSapceInicio.EspacoUsadoEmMB := GET_ESPACO_USADO_TABLESPACE();
    PTELEMETRIA.DadosTableSapceInicio.EspacoLivreEmMB := GET_ESPACO_LIVRE_TABLESPACE_MB();
  END INICIAR_TELEMETRIA;

  
  PROCEDURE CAPTURA_DADOS_TELEMETRIA_WT(PTELEMETRIA IN OUT T_TELEMETRIA, PTABELA IN VARCHAR2) IS
  BEGIN
    PTELEMETRIA.DadosDaTabelaWinthor.NomeDaTabela := PTABELA;
    PTELEMETRIA.DadosDaTabelaWinthor.QuantidadeRegistrosTabela := GET_QUANTIDADE_REGISTROS_TAB(PTABELA);
    PTELEMETRIA.DadosDaTabelaWinthor.TamanhoTabelaEmMB := GET_TAMANHO_TABELA_EM_MB(PTABELA);
  END CAPTURA_DADOS_TELEMETRIA_WT;
  
  PROCEDURE CAPTURA_DADOS_TELEMETRIA_MON(PTELEMETRIA IN OUT T_TELEMETRIA, PTABELA IN VARCHAR2) IS
  BEGIN
    PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela := GET_NOME_TABELA_MONITOR(PTABELA);
    PTELEMETRIA.DadosDaTabelaMonitor.QuantidadeRegistrosTabela := GET_QUANTIDADE_REGISTROS_TAB(PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela);
    PTELEMETRIA.DadosDaTabelaMonitor.TamanhoTabelaEmMB := GET_TAMANHO_TABELA_EM_MB(PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela);
  END CAPTURA_DADOS_TELEMETRIA_MON;


  PROCEDURE FINALIZAR_TELEMETRIA(PTELEMETRIA IN OUT T_TELEMETRIA) IS 
    v_dados VARCHAR2(4000);
    v_equipamento VARCHAR2(65);
    v_usuario VARCHAR2(30);
    v_rotina VARCHAR2(50);
    v_versao VARCHAR(60);
    v_tempo_decorrido NUMBER;
  BEGIN
    PTELEMETRIA.DadosTableSapceFinal.EspacoUsadoEmMB := GET_ESPACO_USADO_TABLESPACE();
    PTELEMETRIA.DadosTableSapceFinal.EspacoLivreEmMB := GET_ESPACO_LIVRE_TABLESPACE_MB();
    PTELEMETRIA.DataHoraTermino := SYSDATE;
    
    v_versao := GET_VERSAO_OBJETO('PKG_MONITOR_TRIBUTARIO');
    v_equipamento := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 64);
    v_usuario     := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 30);
    v_rotina    := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 48);
    v_tempo_decorrido := (PTELEMETRIA.DataHoraTermino -  PTELEMETRIA.DataHoraInicio) * 24*60*60;
    
    v_dados := '{'
        || 'Identificador: @Identificador, '
        || 'TempoDecorridoEmSegundos: @TempoDecorridoEmSegundos, '
        || 'VersaoDaPacakage: @VersaoDaPacakage, '
        || 'Usuario: @Usuario, '
        || 'Terminal: @Terminal, '
        || 'RotinaDoWinthor: @RotinaDoWinthor, '
        || 'NomeDaTabelaDoWinthor: @NomeDaTabelaDoWinthor, '
        || 'QuantidadeDeRegistrosTabelaWinthor: @QuantidadeDeRegistrosTabelaWinthor, '
        || 'TamanhoTabelaEmMBWinthor: @TamanhoTabelaEmMBWinthor, '
        || 'NomeDaTabelaDoMonitor: @NomeDaTabelaDoMonitor, '
      || 'QuantidadeDeRegistrosTabelaMonitor: @QuantidadeDeRegistrosTabelaMonitor, '
      || 'TamanhoTabelaEmMBMonitor: @TamanhoTabelaEmMBMonitor, '
      || 'EspacoUtilizadoNaTableSpaceEmMBAntesDeExecutar: @EspacoUtilizadoNaTableSpaceEmMBAntesDeExecutar, '
      || 'EspacoLivreNaTableSpaceEmMBAntesExecutar: @EspacoLivreNaTableSpaceEmMBAntesExecutar, '
      || 'EspacoUtilizadoNaTableSpaceEmMBAposExecutar: @EspacoUtilizadoNaTableSpaceEmMBAposExecutar, '
      || 'EspacoLivreNaTableSpaceEmMBAposExecutar: @EspacoLivreNaTableSpaceEmMBAposExecutar' 
      || '}';


    v_dados := REPLACE(v_dados, '@Identificador', QUOTEDDUPLO(PTELEMETRIA.Objeto));
    v_dados := REPLACE(v_dados, '@TempoDecorridoEmSegundos', TO_CHAR(v_tempo_decorrido));
    v_dados := REPLACE(v_dados, '@VersaoDaPacakage', QUOTEDDUPLO(v_versao));
    v_dados := REPLACE(v_dados, '@Usuario', QUOTEDDUPLO(v_usuario));
    v_dados := REPLACE(v_dados, '@Terminal', QUOTEDDUPLO(v_equipamento));
    v_dados := REPLACE(v_dados, '@RotinaDoWinthor', QUOTEDDUPLO(v_rotina));
    v_dados := REPLACE(v_dados, '@NomeDaTabelaDoWinthor', QUOTEDDUPLO(PTELEMETRIA.DadosDaTabelaWinthor.NomeDaTabela));
    v_dados := REPLACE(v_dados, '@QuantidadeDeRegistrosTabelaWinthor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaWinthor.QuantidadeRegistrosTabela)));
    v_dados := REPLACE(v_dados, '@TamanhoTabelaEmMBWinthor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaWinthor.TamanhoTabelaEmMB)));
    v_dados := REPLACE(v_dados, '@NomeDaTabelaDoMonitor', QUOTEDDUPLO(PTELEMETRIA.DadosDaTabelaMonitor.NomeDaTabela));    
    v_dados := REPLACE(v_dados, '@QuantidadeDeRegistrosTabelaMonitor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaMonitor.QuantidadeRegistrosTabela)));
    v_dados := REPLACE(v_dados, '@TamanhoTabelaEmMBMonitor', TO_CHAR(TRUNC(PTELEMETRIA.DadosDaTabelaMonitor.TamanhoTabelaEmMB)));
    v_dados := REPLACE(v_dados, '@EspacoUtilizadoNaTableSpaceEmMBAntesDeExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceInicio.EspacoUsadoEmMB)));
    v_dados := REPLACE(v_dados, '@EspacoLivreNaTableSpaceEmMBAntesExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceInicio.EspacoLivreEmMB)));
    v_dados := REPLACE(v_dados, '@EspacoUtilizadoNaTableSpaceEmMBAposExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceFinal.EspacoUsadoEmMB)));
    v_dados := REPLACE(v_dados, '@EspacoLivreNaTableSpaceEmMBAposExecutar', TO_CHAR(TRUNC(PTELEMETRIA.DadosTableSapceFinal.EspacoLivreEmMB)));
    
    PTELEMETRIA.Dados := v_dados;
  END FINALIZAR_TELEMETRIA;
  
  PROCEDURE GRAVAR_TELEMETRIA(PTELEMETRIA IN T_TELEMETRIA) IS 
    v_sql VARCHAR2(4000);
  BEGIN
    v_sql := 'INSERT INTO PCTELEMETRIAMONITOR (
       DATAPROCESSAMENTO,
       OBJETO,
       DATAHORAINICIO,
       DATAHORATERMINO,
       DADOS    
     ) VALUES (
       TRUNC(SYSDATE),
       ''@param1'',
       TO_DATE(''@param2'', ''DD/MM/YYYY HH24:MI:SS''),
       TO_DATE(''@param3'', ''DD/MM/YYYY HH24:MI:SS''),
       ''@param4''
     )';
     
    v_sql := REPLACE(v_sql, '@param1', PTELEMETRIA.Objeto);
    v_sql := REPLACE(v_sql, '@param2', TO_CHAR(PTELEMETRIA.DataHoraInicio, 'DD/MM/YYYY HH24:MI:SS'));
    v_sql := REPLACE(v_sql, '@param3', TO_CHAR(PTELEMETRIA.DataHoraTermino, 'DD/MM/YYYY HH24:MI:SS'));
    v_sql := REPLACE(v_sql, '@param4', PTELEMETRIA.Dados);
  
    EXECUTE IMMEDIATE v_sql;
    COMMIT;
  END GRAVAR_TELEMETRIA;
  
  PROCEDURE FINALIZAR_E_GRAVAR_TELEMETRIA(PTELEMETRIA IN OUT T_TELEMETRIA) IS 
  BEGIN
    FINALIZAR_TELEMETRIA(PTELEMETRIA);
    GRAVAR_TELEMETRIA(PTELEMETRIA);
  END FINALIZAR_E_GRAVAR_TELEMETRIA;



  PROCEDURE INICIAR_TELEMETRIA_CABECALHO(PTELEMETRIA IN OUT T_TELEMETRIA, PNOME_OBJETO IN VARCHAR2) IS 
    v_dados VARCHAR2(4000);
  BEGIN
    PTELEMETRIA.Objeto := PNOME_OBJETO;
    PTELEMETRIA.DataHoraInicio := SYSDATE;
    
    v_dados := '{'
        || 'Identificador: @Identificador, '
      || '}';
    v_dados := REPLACE(v_dados, '@Identificador', QUOTEDDUPLO('*INICIO*'));
    
    PTELEMETRIA.Dados := v_dados;
    
    GRAVAR_TELEMETRIA(PTELEMETRIA);
  END INICIAR_TELEMETRIA_CABECALHO;


  PROCEDURE FINALIZAR_TELEMETRIA_CABECALHO(PTELEMETRIA IN OUT T_TELEMETRIA) IS 
    v_dados VARCHAR2(4000);
    v_tempo_decorrido NUMBER;
  BEGIN
    PTELEMETRIA.DataHoraTermino := SYSDATE;
    
    v_tempo_decorrido := (PTELEMETRIA.DataHoraTermino -  PTELEMETRIA.DataHoraInicio) * 24*60*60;
    v_dados := '{'
        || 'Identificador: @Identificador, '
        || 'TempoDecorridoEmSegundos: @TempoDecorridoEmSegundos'
      || '}';
    v_dados := REPLACE(v_dados, '@Identificador', QUOTEDDUPLO('*FIM*'));
    v_dados := REPLACE(v_dados, '@TempoDecorridoEmSegundos', TO_CHAR(v_tempo_decorrido));
    
    PTELEMETRIA.Dados := v_dados;

    GRAVAR_TELEMETRIA(PTELEMETRIA);
  END FINALIZAR_TELEMETRIA_CABECALHO;


  PROCEDURE CRIAR_TABELA(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
    v_sql_create VARCHAR2(4000);
  BEGIN
    v_sql_create := 'CREATE TABLE ' || PTABELA || ' NOLOGGING AS ' || PCONSULTA;
    EXECUTE IMMEDIATE v_sql_create;
  END CRIAR_TABELA;


  PROCEDURE LIMPAR_TABELA(PTABELA IN VARCHAR2) IS
    v_sql_truncate VARCHAR2(100);
  BEGIN
    v_sql_truncate := 'TRUNCATE TABLE ' || PTABELA;

    BEGIN
      EXECUTE IMMEDIATE v_sql_truncate;
    EXCEPTION

      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
  END LIMPAR_TABELA;


  PROCEDURE APAGAR_TABELA(PTABELA IN VARCHAR2) IS
    v_sql_drop VARCHAR2(100);
  BEGIN
    v_sql_drop := 'DROP TABLE ' || PTABELA;

    BEGIN
      EXECUTE IMMEDIATE v_sql_drop;
    EXCEPTION

      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
  END APAGAR_TABELA;


  PROCEDURE CRIAR_ESTRUTURA_TELEMETRIA IS 
    v_tabela_telemetria_existe NUMBER;
  BEGIN
      
    SELECT COUNT(1)
    INTO v_tabela_telemetria_existe
    FROM USER_TABLES
    WHERE TABLE_NAME = 'PCTELEMETRIAMONITOR';
    
    IF v_tabela_telemetria_existe = 0 THEN
      EXECUTE IMMEDIATE PKG_MONITOR_TRIBUTARIO_CONSULT.GET_CREATE_TABELA_TELEMETRIA;
      EXECUTE IMMEDIATE 'CREATE INDEX PCTELEMETRIAMONITOR_IDX01 ON PCTELEMETRIAMONITOR(DATAPROCESSAMENTO) NOLOGGING TABLESPACE TS_INDICE';
    END IF;
  END CRIAR_ESTRUTURA_TELEMETRIA;


  PROCEDURE CRIAR_ESTRUTURA_CONTROLEPROC IS 
    v_tabela_telemetria_existe NUMBER;
  BEGIN
      
    SELECT COUNT(1)
    INTO v_tabela_telemetria_existe
    FROM USER_TABLES
    WHERE TABLE_NAME = 'PCCONTROLEPROCESSAMENTO';
    
    IF v_tabela_telemetria_existe = 0 THEN
      EXECUTE IMMEDIATE PKG_MONITOR_TRIBUTARIO_CONSULT.GET_CREATE_TABELA_CONTROLEPROC;
      EXECUTE IMMEDIATE 'CREATE INDEX PCCONTROLEPROCESSAMENTO_IDX01 ON PCCONTROLEPROCESSAMENTO(OBJETO) NOLOGGING TABLESPACE TS_INDICE';
      EXECUTE IMMEDIATE 'INSERT INTO PCCONTROLEPROCESSAMENTO(OBJETO, ATIVO) VALUES (''PCCONTROLEPROCESSAMENTO'', ''S'')';

      COMMIT;
    END IF;
  END CRIAR_ESTRUTURA_CONTROLEPROC;


  PROCEDURE CRIA_ESTRUTURAS_MONITOR IS
  BEGIN
    CRIAR_ESTRUTURA_TELEMETRIA;
    CRIAR_ESTRUTURA_CONTROLEPROC;
  END; 

  PROCEDURE CRIAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
  BEGIN
    CRIAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA), PCONSULTA);
  END CRIAR_TABELA_TEMPORARIA;


  PROCEDURE LIMPAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2) IS
  BEGIN
    LIMPAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA));
  END LIMPAR_TABELA_TEMPORARIA;


  PROCEDURE APAGAR_TABELA_TEMPORARIA(PTABELA IN VARCHAR2) IS
  BEGIN
    APAGAR_TABELA(GET_NOME_TABELA_TEMPORARIA(PTABELA));
  END APAGAR_TABELA_TEMPORARIA;


  PROCEDURE CRIAR_TABELA_MONITOR(PTABELA IN VARCHAR2, PCONSULTA IN VARCHAR2) IS
  BEGIN
    CRIAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA), PCONSULTA);
  END CRIAR_TABELA_MONITOR;


  PROCEDURE LIMPAR_TABELA_MONITOR(PTABELA IN VARCHAR2) IS
  BEGIN
    LIMPAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA));
  END LIMPAR_TABELA_MONITOR;


  PROCEDURE APAGAR_TABELA_MONITOR(PTABELA IN VARCHAR2) IS
  BEGIN
    APAGAR_TABELA(GET_NOME_TABELA_MONITOR(PTABELA));
  END APAGAR_TABELA_MONITOR;


  PROCEDURE CARREGAR_TABELA_MONITOR(PTABELA IN VARCHAR2) IS
    v_tabela VARCHAR2(30);
  BEGIN
    v_tabela := GET_NOME_TABELA_TEMPORARIA(PTABELA);

    IF VERIFICAR_EXISTE_TABELA_TMPMON(v_tabela) THEN
      APAGAR_TABELA_MONITOR(PTABELA);
      CRIAR_TABELA_MONITOR(PTABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_TABELA_MONITOR(v_tabela));
    END IF;
  END CARREGAR_TABELA_MONITOR;


  PROCEDURE CRIAR_INDICES_TABELA(PTABELA IN VARCHAR2, PINDICE IN VARCHAR2, PTABELATEMP IN BOOLEAN := FALSE) IS
    C_PADRAO_CREATE CONSTANT VARCHAR2(100) := 'CREATE INDEX @INDICE ON @TABELA(@CAMPOS) NOLOGGING TABLESPACE TS_INDICE';
    v_indice VARCHAR2(2000);
    v_tabela VARCHAR(30);
  BEGIN
    v_tabela := GET_NOME_TABELA_MONITOR(PTABELA);

    IF PTABELATEMP THEN
      v_tabela := GET_NOME_TABELA_TEMPORARIA(PTABELA);
    END IF;

    FOR LISTA_INDICE IN (
      WITH INDICE AS (
        SELECT PINDICE IDX
        FROM DUAL
      )
      SELECT
        ROWNUM NUMERO,
        REGEXP_SUBSTR(
          IDX,
          '[^;]+',
          1,
          LEVEL
        ) NOME_INDICE
      FROM INDICE
      CONNECT BY LEVEL <= LENGTH(IDX) - LENGTH(REPLACE(IDX, ';')) + 1
    ) LOOP
      IF NVL(TRIM(LISTA_INDICE.NOME_INDICE), 'X') <> 'X' THEN
        v_indice := C_PADRAO_CREATE;
        v_indice := REPLACE(v_indice, '@INDICE', v_tabela || '_IDX' || LISTA_INDICE.NUMERO);
        v_indice := REPLACE(v_indice, '@TABELA', v_tabela);
        v_indice := REPLACE(v_indice, '@CAMPOS', LISTA_INDICE.NOME_INDICE);

        EXECUTE IMMEDIATE v_indice;
      END IF;
    END LOOP;

  END CRIAR_INDICES_TABELA;


  PROCEDURE CRIARTABELA_PCNFSAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFSAID';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCNFSAID');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
    
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFSAID(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    CRIAR_INDICES_TABELA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFSAID);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCNFSAID;


  PROCEDURE CRIARTABELA_PCMOV(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCMOV';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCMOV');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
    
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCMOV(PDATA_INICIAL, PDATA_FINAL));
    CRIAR_INDICES_TABELA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCMOV, TRUE);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCMOV;


  PROCEDURE CRIARTABELA_MOV_UNIFICADA(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCMOVUNIF';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_MOV_UNIFICADA');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, 'PCMOVCOMPLE');
    
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_MOV_UNIFICADA(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    CRIAR_INDICES_TABELA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_MOV_UNIFICADA);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_MOV_UNIFICADA;


  PROCEDURE CRIARTABELA_PCNFBASESAID(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFBASESAID';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCNFBASESAID');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);

    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFBASESAID(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    CRIAR_INDICES_TABELA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFBASESAID);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCNFBASESAID;


  PROCEDURE CRIARTABELA_PCNFBASEENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFBASEENT';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCNFBASEENT');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
        
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFBASEENT(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    CRIAR_INDICES_TABELA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFBASEENT);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCNFBASEENT;


  PROCEDURE CRIARTABELA_PCNFENT(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCNFENT';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCNFENT');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
    
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCNFENT(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    CRIAR_INDICES_TABELA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_INDICES_PCNFENT);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);    
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCNFENT;


  PROCEDURE CRIARTABELA_PCESTCOM(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCESTCOM';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCESTCOM');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
    
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCESTCOM(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);    
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCESTCOM;


  PROCEDURE CRIARTABELA_PCDEVFORNEC(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCDEVFORNEC';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCDEVFORNEC');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
        
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCDEVFORNEC(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);    
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCDEVFORNEC;


  PROCEDURE CRIARTABELA_PCDEVAVULSO(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCDEVAVULSO';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCDEVAVULSO');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);
        
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_PCDEVAVULSO(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);    
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCDEVAVULSO;

  PROCEDURE CRIARTABELA_PCLANCINTER(PDATA_INICIAL IN DATE, PDATA_FINAL IN DATE) IS
    C_TABELA CONSTANT VARCHAR2(30) := 'PCLANCINTERMEDIARIA';
    v_telemetria T_TELEMETRIA;
  BEGIN
    INICIAR_TELEMETRIA(v_telemetria, 'CRIARTABELA_PCLANCINTER');
    CAPTURA_DADOS_TELEMETRIA_WT(v_telemetria, C_TABELA);    
    
    APAGAR_TABELA_TEMPORARIA(C_TABELA);
    CRIAR_TABELA_TEMPORARIA(C_TABELA, PKG_MONITOR_TRIBUTARIO_CONSULT.GET_VALORES_NOTAS_CONTABIL(PDATA_INICIAL, PDATA_FINAL));
    CARREGAR_TABELA_MONITOR(C_TABELA);
    
    CAPTURA_DADOS_TELEMETRIA_MON(v_telemetria, C_TABELA);    
    FINALIZAR_E_GRAVAR_TELEMETRIA(v_telemetria);
  END CRIARTABELA_PCLANCINTER;


  FUNCTION USA_CONTABIL RETURN BOOLEAN IS 
    V_USACONTABIL NUMBER(3);
  BEGIN
    SELECT COUNT(1)
      INTO V_USACONTABIL
      FROM PCPARAMFILIAL F
     WHERE F.NOME = 'FIL_USACONTABIL'
       AND F.VALOR = 'S';
       
    RETURN V_USACONTABIL > 0;
  END USA_CONTABIL;


  PROCEDURE CRIAR_MONITOR_TRIBUTARIO(PDATAINICIAL IN DATE := SYSDATE - 30, PDATAFINAL IN DATE := SYSDATE) IS
    v_telemetria T_TELEMETRIA;
    v_datainicial DATE;
    v_datafinal DATE;
  BEGIN
    CRIA_ESTRUTURAS_MONITOR;
    INICIAR_TELEMETRIA_CABECALHO(v_telemetria, 'CRIAR_MONITOR_TRIBUTARIO');

    v_datainicial := NVL(PDATAINICIAL, SYSDATE - 30);
    v_datafinal := NVL(PDATAFINAL, SYSDATE);
    
    IF USA_MONITOR_TRIBUTARIO THEN
      IF EXECUTA_CARGA_DO_MONITOR THEN
        CRIARTABELA_PCNFSAID(v_datainicial, v_datafinal);
        CRIARTABELA_PCMOV(v_datainicial, v_datafinal);
        CRIARTABELA_MOV_UNIFICADA(v_datainicial, v_datafinal);
        CRIARTABELA_PCNFBASESAID(v_datainicial, v_datafinal);
        CRIARTABELA_PCNFBASEENT(v_datainicial, v_datafinal);
        CRIARTABELA_PCNFENT(v_datainicial, v_datafinal);
        CRIARTABELA_PCESTCOM(v_datainicial, v_datafinal);
        CRIARTABELA_PCDEVFORNEC(v_datainicial, v_datafinal);
        CRIARTABELA_PCDEVAVULSO(v_datainicial, v_datafinal);

        IF USA_CONTABIL THEN
          CRIARTABELA_PCLANCINTER(v_datainicial, v_datafinal);
        END IF;
        
        ATUALIZAR_DATA_ULTIMA_EXECUCAO;
      END IF;
    END IF;
    
    FINALIZAR_TELEMETRIA_CABECALHO(v_telemetria);
  END CRIAR_MONITOR_TRIBUTARIO;

END PKG_MONITOR_TRIBUTARIO;