CREATE OR REPLACE PACKAGE PKG_MONITOR_TRIBUTARIO AS

  TYPE T_DADOS_TABELA IS RECORD (
    NomeDaTabela VARCHAR2(30),
    QuantidadeRegistrosTabela NUMBER,
    TamanhoTabelaEmMB NUMBER
  );

  TYPE T_DADOS_TABLESPACE IS RECORD (
    EspacoUsadoEmMB NUMBER,
    EspacoLivreEmMB NUMBER
  );

  TYPE T_TELEMETRIA IS RECORD (
    Objeto VARCHAR2(30) DEFAULT '',
    DataHoraInicio DATE,
    DataHoraTermino DATE,
    IntervaloDeDadosEmDias NUMBER,
    DadosDaTabelaWinthor  T_DADOS_TABELA,
    DadosDaTabelaMonitor  T_DADOS_TABELA,
    DadosTableSapceInicio T_DADOS_TABLESPACE,
    DadosTableSapceFinal  T_DADOS_TABLESPACE,
    Dados VARCHAR2(4000) DEFAULT ''
  );
  
  g_Telemetria T_TELEMETRIA;

  TYPE T_REC_TABELA_MONITOR IS RECORD (
    TABELAORIGEM VARCHAR2(30),
    TABELATEMPORARIA VARCHAR2(30),
    TABELAMONITOR VARCHAR2(30),
    TABELADEPENDENCIA VARCHAR2(30),
    INDICE VARCHAR2(2000)
  );
  
  TYPE T_REFCUR_TABELA_MONITOR IS REF CURSOR RETURN T_REC_TABELA_MONITOR;
  TYPE T_TABLE_TABELA_MONITOR IS TABLE OF T_REC_TABELA_MONITOR INDEX BY PLS_INTEGER;

  FUNCTION AMBIENTE_ESTA_PREPARADO RETURN VARCHAR2;
  FUNCTION TEM_DATA_ULTIMA_EXECUCAO RETURN VARCHAR2;
  PROCEDURE PREPARA_AMBIENTE_MONITOR_TRIB;
  PROCEDURE CRIAR_MONITOR_TRIBUTARIO(PDATAINICIAL IN DATE := SYSDATE - 30, PDATAFINAL IN DATE := SYSDATE);
  PROCEDURE FINALIZAR_CARGA_MONITOR_TRIBUT;
END PKG_MONITOR_TRIBUTARIO;
