CREATE OR REPLACE PACKAGE PKG_MONITOR_TRIBUTARIO AS

  TYPE T_DADOS_TABELA IS RECORD (
    NomeDaTabela VARCHAR2(30),
    QuantidadeRegistrosTabela NUMBER,
    TamanhoTabelaEmMB NUMBER
  );

  TYPE T_DADOS_TABLESPACE IS RECORD (
    EspacoUsadoEmMB NUMBER,
    EspacoLivreEmMB NUMBER
  );

  TYPE T_TELEMETRIA IS RECORD (
    Objeto VARCHAR2(30) DEFAULT '',
    DataHoraInicio DATE,
    DataHoraTermino DATE,
    IntervaloDeDadosEmDias NUMBER,
    DadosDaTabelaWinthor  T_DADOS_TABELA,
    DadosDaTabelaMonitor  T_DADOS_TABELA,
    DadosTableSapceInicio T_DADOS_TABLESPACE,
    DadosTableSapceFinal  T_DADOS_TABLESPACE,
    Dados VARCHAR2(4000) DEFAULT ''
  );
  
  g_Telemetria T_TELEMETRIA;

  PROCEDURE PREPARA_AMBIENTE_MONITOR_TRIB;
  PROCEDURE CRIAR_MONITOR_TRIBUTARIO(PDATAINICIAL IN DATE := SYSDATE - 30, PDATAFINAL IN DATE := SYSDATE);
END PKG_MONITOR_TRIBUTARIO;
