CREATE OR REPLACE VIEW VW_INT_C5_USUARIO AS
(
  SELECT R.CODFILIAL,
        R.CODUSUR,
        R.MATRICULA SEQUSUARIO,
        1 SEQPESSOA,
        SUBSTR(R.NOME, 1, 40) NOME,
        SUBSTR(NVL(R.NOME_GUERRA, R.NOME), 1, 30) APELIDO,
        NULL SENHA,  --FNC_INT_C5_PWD(R.MATRICULA) SENHA,
        (CASE
            WHEN R.CODSETOR = G.CODGRUPO THEN 0
            ELSE 1
        END) NIVEL,
        R.DTEXPIRASENHA DTAEXPIRAR,
        (CASE
            WHEN NVL(R.PERDESCMAXITEM, 0) > 0 THEN R.PERDESCMAXITEM
            WHEN TO_NUMBER(G.PERCDESCMAX) > 0 THEN G.PERCDESCMAX
            ELSE 0
        END) PERCDESCMAXIMO,
        SUBSTR(R.EMAIL, 80) EMAIL,
        (CASE
            WHEN R.DT_EXCLUSAO IS NULL AND NVL(R.SITUACAO, 'A') = 'A' THEN 'S'
            ELSE 'N'
        END) ATIVO,
        R.CODSETOR CODGRUPO,
        R.FUNCAO NOMEGRUPO,
        G.PERCDESCMAX
  FROM PCEMPR R
  INNER JOIN VW_INT_C5_USUARIO_GRUPO G
  ON (R.CODSETOR = G.CODGRUPO),
    PCUSUARI I,
    (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
    FROM PCCONTROLECONSINCO S
    WHERE  (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_USUARIO')
        OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_GRUPOUSUARIO')
    ) DTPADRAO
    WHERE R.CODUSUR = I.CODUSUR
      AND I.CODSUPERVISOR IS NOT NULL
      AND R.CODUSUR > 0
      AND R.MATRICULA > 0
      AND (NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
        OR CODSETOR IN (SELECT
                          CODGRUPO
                        FROM VW_INT_C5_USUARIO_GRUPO V
                        LEFT JOIN TB_GRUPO G
                        ON (G.SEQGRUPO = V.CODGRUPO AND G.ATIVO = 'S')
                        LEFT JOIN TB_GRUPOUSUARIO GU
                        ON (GU.SEQGRUPO = V.CODGRUPO AND GU.ATIVO = 'S')
                        WHERE G.SEQGRUPO IS NULL OR GU.SEQGRUPO IS NULL)
      )
)