CREATE OR REPLACE VIEW VW_INT_C5_USUARIO AS
WITH 
  CTE_PARAMS AS (
    SELECT MIN(S.ULTIMAEXECUCAO) AS ULTIMAEXECUCAO
    FROM PCCONTROLECONSINCO S
    WHERE UPPER(S.OBJETOREFERENCIA) IN ('PKG_SINC_PDV_CONSINCO.CARREGA_TB_USUARIO', 
                                        'PKG_SINC_PDV_CONSINCO.CARREGA_TB_GRUPOUSUARIO')
  ),
  CTE_USUARI_UNICO AS (
    SELECT CODUSUR, MAX(CODSUPERVISOR) AS CODSUPERVISOR
    FROM PCUSUARI
    WHERE CODSUPERVISOR IS NOT NULL
    GROUP BY CODUSUR
  ),
  CTE_PESSOA AS (
    SELECT 
        REGEXP_REPLACE(CNPJCPF, '[^0-9]', '') AS CPF_LIMPO,
        MIN(SEQPESSOA) AS SEQPESSOA,
        MAX(DTAHORALTERACAO) AS DTAHORALTERACAO
    FROM MONITORPDVMIDDLE.TB_PESSOA 
    WHERE ATIVO = 'S' 
    GROUP BY REGEXP_REPLACE(CNPJCPF, '[^0-9]', '')
  )

SELECT DISTINCT
    R.CODFILIAL,
    R.CODUSUR,
    R.MATRICULA AS SEQUSUARIO,
    T.SEQPESSOA,
    SUBSTR(R.NOME, 1, 40) AS NOME,
    SUBSTR(NVL(R.NOME_GUERRA, R.NOME), 1, 30) AS APELIDO,
    CASE
      WHEN REGEXP_LIKE(DECRYPT(R.SENHABD, R.USUARIOBD),'\D+') THEN TO_CHAR(PKG_CRC32.CALCULATE('0'))
      ELSE TO_CHAR(PKG_CRC32.CALCULATE(DECRYPT(R.SENHABD, R.USUARIOBD))) 
    END AS SENHA,
    CASE WHEN R.CODSETOR = G.CODGRUPO THEN 0 ELSE 1 END AS NIVEL,
    R.DTEXPIRASENHA AS DTAEXPIRAR,
    CASE 
        WHEN NVL(R.PERDESCMAXITEM, 0) > 0 THEN R.PERDESCMAXITEM
        WHEN TO_NUMBER(G.PERCDESCMAX) > 0 THEN G.PERCDESCMAX
        ELSE 0
    END AS PERCDESCMAXIMO,
    SUBSTR(R.EMAIL, 1, 80) AS EMAIL,
    CASE WHEN R.DT_EXCLUSAO IS NULL AND NVL(R.SITUACAO, 'A') = 'A' THEN 'S' ELSE 'N' END AS ATIVO,
    R.CODSETOR AS CODGRUPO,
    R.FUNCAO AS NOMEGRUPO,
    G.PERCDESCMAX
FROM PCEMPR R
INNER JOIN VW_INT_C5_USUARIO_GRUPO G ON (R.CODSETOR = G.CODGRUPO)
INNER JOIN CTE_USUARI_UNICO I ON (R.CODUSUR = I.CODUSUR)
CROSS JOIN CTE_PARAMS DTPADRAO
LEFT JOIN CTE_PESSOA T ON (REGEXP_REPLACE(R.CPF, '[^0-9]', '') = T.CPF_LIMPO)
WHERE R.CODUSUR > 0
  AND R.MATRICULA > 0
  AND R.SENHABD IS NOT NULL
  AND R.USUARIOBD IS NOT NULL
  AND (
       NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
       OR T.DTAHORALTERACAO >= DTPADRAO.ULTIMAEXECUCAO
       OR EXISTS (
            SELECT 1 FROM VW_INT_C5_USUARIO_GRUPO V
            LEFT JOIN MONITORPDVMIDDLE.TB_GRUPO GR ON (GR.SEQGRUPO = V.CODGRUPO AND GR.ATIVO = 'S')
            LEFT JOIN MONITORPDVMIDDLE.TB_GRUPOUSUARIO GU ON (GU.SEQGRUPO = V.CODGRUPO AND GU.ATIVO = 'S')
            WHERE V.CODGRUPO = R.CODSETOR 
              AND (GR.SEQGRUPO IS NULL OR GU.SEQGRUPO IS NULL)
          )
  )