CREATE OR REPLACE VIEW VW_INT_C5_USUARIO AS
(
  SELECT R.CODFILIAL,
        R.CODUSUR,
        R.MATRICULA SEQUSUARIO,
        T.SEQPESSOA,
        SUBSTR(R.NOME, 1, 40) NOME,
        SUBSTR(NVL(R.NOME_GUERRA, R.NOME), 1, 30) APELIDO,
        (CASE
          WHEN REGEXP_LIKE(DECRYPT(SENHABD, USUARIOBD),'\D+') THEN
            TO_CHAR(PKG_CRC32.CALCULATE('0'))
          ELSE
            TO_CHAR(PKG_CRC32.CALCULATE(DECRYPT(R.SENHABD, R.USUARIOBD))) 
        END) SENHA,  
        (CASE
            WHEN R.CODSETOR = G.CODGRUPO THEN 0
            ELSE 1
        END) NIVEL,
        R.DTEXPIRASENHA DTAEXPIRAR,
        (CASE
            WHEN NVL(R.PERDESCMAXITEM, 0) > 0 THEN R.PERDESCMAXITEM
            WHEN TO_NUMBER(G.PERCDESCMAX) > 0 THEN G.PERCDESCMAX
            ELSE 0
        END) PERCDESCMAXIMO,
        SUBSTR(R.EMAIL, 80) EMAIL,
        (CASE
            WHEN R.DT_EXCLUSAO IS NULL AND NVL(R.SITUACAO, 'A') = 'A' THEN 'S'
            ELSE 'N'
        END) ATIVO,
        R.CODSETOR CODGRUPO,
        R.FUNCAO NOMEGRUPO,
        G.PERCDESCMAX
  FROM PCEMPR R
  
  INNER JOIN VW_INT_C5_USUARIO_GRUPO G
  ON (R.CODSETOR = G.CODGRUPO)
  
  LEFT JOIN (SELECT MIN(SEQPESSOA) SEQPESSOA , CNPJCPF, MAX(DTAHORALTERACAO) DTAHORALTERACAO FROM MONITORPDVMIDDLE.TB_PESSOA WHERE ATIVO = 'S' GROUP BY CNPJCPF) T 
  ON (FERRAMENTAS.SONUMEROS(R.CPF) = FERRAMENTAS.SONUMEROS(T.CNPJCPF)),

   PCUSUARI I,
    (SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
    FROM PCCONTROLECONSINCO S
    WHERE  (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_USUARIO')
        OR (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_GRUPOUSUARIO')
    ) DTPADRAO
    WHERE R.CODUSUR = I.CODUSUR
      AND I.CODSUPERVISOR IS NOT NULL
      AND R.CODUSUR > 0
      AND R.MATRICULA > 0
      AND (NVL(R.DTALTERC5, DTPADRAO.ULTIMAEXECUCAO) >= DTPADRAO.ULTIMAEXECUCAO
        OR CODSETOR IN (SELECT
                          CODGRUPO
                        FROM VW_INT_C5_USUARIO_GRUPO V
                        LEFT JOIN MONITORPDVMIDDLE.TB_GRUPO G
                        ON (G.SEQGRUPO = V.CODGRUPO AND G.ATIVO = 'S')
                        LEFT JOIN MONITORPDVMIDDLE.TB_GRUPOUSUARIO GU
                        ON (GU.SEQGRUPO = V.CODGRUPO AND GU.ATIVO = 'S')
                        WHERE G.SEQGRUPO IS NULL OR GU.SEQGRUPO IS NULL)
        OR T.DTAHORALTERACAO >= DTPADRAO.ULTIMAEXECUCAO
     )
)