CREATE OR REPLACE VIEW SQL_NFE_PRODUTO_SAIDA_COMP AS
SELECT N.NUMTRANSVENDA AS NUM_TRANSACAO,
       NVL(NVL(N.CODPRODNFAJUSTE,B.CODPRODAJUSTE), TO_CHAR(999999)) CODIGO_PRODUTO,
       (NVL(N.BCST,0)) AS BASE_ST,
       (NVL(N.ICMSRETIDO,0)) AS VALOR_ST,
       B.CODFISCAL CFOP,
       
       NVL(NVL(N.NCMNFAJUSTE,B.NCMPRODAJUSTE),
       (SELECT REPLACE(PCPRODUT.NBM,'.','')
         FROM PCPRODUT
         WHERE PCPRODUT.DTEXCLUSAO IS NULL AND NBM IS NOT NULL
         AND ROWNUM = 1)) AS NCM,
          
       DECODE((NVL(B.TIPO,'1')),'2',0 ,B.ALIQUOTA) ALIQUOTA_ICMS,
       DECODE((NVL(B.TIPO,'1')),'2',B.ALIQUOTA,0) ALIQUOTA_IPI,

       NVL(NVL(N.VLTOTBRUTOPRODAJUSTE,B.VLTOTPRODAJUSTE),
       GREATEST((NVL(N.VLTOTAL,0) -
                 NVL(N.ICMSRETIDO,0) -
                 (DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLICMS,0),0))),0)
           )AS VALOR_PRODUTOS,
       
       DECODE(NVL(B.TIPO,'1'),'1',NVL(B.VLBASE,0),0) BASE_ICMS,
       DECODE(NVL(B.TIPO,'1'),'1',NVL(B.VLICMS,0),0) VALOR_ICMS,
       DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLBASE,0),0) BASE_IPI,
       DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLICMS,0),0) VALOR_IPI,
       NVL(B.SITTRIBUT, 90) AS SITUACAO_TRIBUTARIA,
       NVL(B.SITTRIBUTIPI, 99) AS SITUACAO_TRIBUTARIA_IPI,
       NVL(NVL(N.UNIDADENFAJUSTE,B.UNIDADEPRODAJUSTE),'UN') AS UNIDADENFAJUSTE,
       
       NVL(NVL(NVL(N.DESCRICAOPRODNFAJUSTE,B.DESCRICAOPRODAJUSTE),
          (SELECT MIN(C.COMPLEMENTO1) FROM PCCOMPLEMENTO C WHERE C.NOMETABELA = 'PCNFSAID'
           AND C.NUMTRANS = N.NUMTRANSVENDA)),
           'ITEM ' || DECODE(N.FINALIDADENFE, 'A', 'DE AJUSTE', 'COMPLEMENTAR')) AS DESCRICAO,
       0 AS VALOR_IPI_OUTROS,
       
       NVL(N.VLFRETE,0) AS VALOR_FRETE,
       NVL(N.VLOUTRAS,0) AS VALOR_OUTROS,
       NVL(N.VLDESCONTO,0) AS VALOR_DESCONTO,
       NULL AS TIPO_PRESENCA_ADQUIRINTE,
       N.DATACONSOLIDACAOPREFAT,
       'N' AS PREFATURAMENTO,
       
       CASE WHEN (N.FINALIDADENFE = 'C') OR (N.FINALIDADENFE = 'A') THEN
         (SELECT MAX(MC.CODCEST) FROM PCMOV M, PCMOVCOMPLE MC
          WHERE M.NUMTRANSITEM = MC.NUMTRANSITEM AND M.NUMTRANSVENDA = N.NUMTRANSVENDAORIGEM)
       ELSE
         ''
       END AS CODCEST
FROM   PCNFBASE B,
       PCNFSAID N
WHERE  B.NUMTRANSVENDA = N.NUMTRANSVENDA

UNION ALL
SELECT N.NUMTRANSVENDA AS NUM_TRANSACAO,
       NVL(NVL(N.CODPRODNFAJUSTE,B.CODPRODAJUSTE), TO_CHAR(999999)) CODIGO_PRODUTO,
       (NVL(N.BCST,0)) AS BASE_ST,
       (NVL(N.ICMSRETIDO,0)) AS VALOR_ST,
       B.CODFISCAL CFOP,
       
       NVL(NVL(N.NCMNFAJUSTE,B.NCMPRODAJUSTE),
       (SELECT REPLACE(PCPRODUT.NBM,'.','')
        FROM PCPRODUT
        WHERE PCPRODUT.DTEXCLUSAO IS NULL AND NBM IS NOT NULL
        AND ROWNUM = 1)) AS NCM,

       DECODE((NVL(B.TIPO,'1')),'2',0 ,B.ALIQUOTA) ALIQUOTA_ICMS,
       DECODE((NVL(B.TIPO,'1')),'2',B.ALIQUOTA,0) ALIQUOTA_IPI,
       NVL(NVL(N.VLTOTBRUTOPRODAJUSTE,B.VLTOTPRODAJUSTE),
       
       GREATEST((NVL(N.VLTOTAL,0) -
                 NVL(N.ICMSRETIDO,0) -
                 (DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLICMS,0),0))),0)
           )AS VALOR_PRODUTOS,
       
       DECODE(NVL(B.TIPO,'1'),'1',NVL(B.VLBASE,0),0) BASE_ICMS,
       DECODE(NVL(B.TIPO,'1'),'1',NVL(B.VLICMS,0),0) VALOR_ICMS,
       DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLBASE,0),0) BASE_IPI,
       DECODE(NVL(B.TIPO,'1'),'2',NVL(B.VLICMS,0),0) VALOR_IPI,
       NVL(B.SITTRIBUT, 90) AS SITUACAO_TRIBUTARIA,
       NVL(B.SITTRIBUTIPI, 99) AS SITUACAO_TRIBUTARIA_IPI,
       NVL(N.UNIDADENFAJUSTE,B.UNIDADEPRODAJUSTE) AS UNIDADENFAJUSTE,
       
       NVL(NVL(NVL(N.DESCRICAOPRODNFAJUSTE,B.DESCRICAOPRODAJUSTE),
          (SELECT MIN(C.COMPLEMENTO1) FROM PCCOMPLEMENTO C WHERE C.NOMETABELA = 'PCNFSAID'
           AND C.NUMTRANS = N.NUMTRANSVENDA)),
           'ITEM ' || DECODE(N.FINALIDADENFE, 'A', 'DE AJUSTE', 'COMPLEMENTAR')) AS DESCRICAO,
       0 AS VALOR_IPI_OUTROS,
       
       NVL(N.VLFRETE,0) AS VALOR_FRETE,
       NVL(N.VLOUTRAS,0) AS VALOR_OUTROS,
       NVL(N.VLDESCONTO,0) AS VALOR_DESCONTO,
       NULL AS TIPO_PRESENCA_ADQUIRINTE,
       N.DATACONSOLIDACAOPREFAT,
       'N' PREFATURAMENTO,
       CASE WHEN (N.FINALIDADENFE = 'C') OR (N.FINALIDADENFE = 'A') THEN
         (SELECT MAX(MC.CODCEST) FROM PCMOV M, PCMOVCOMPLE MC
          WHERE M.NUMTRANSITEM = MC.NUMTRANSITEM AND M.NUMTRANSVENDA = N.NUMTRANSVENDAORIGEM)
       ELSE
         ''
       END AS CODCEST
FROM   PCNFBASEPREFAT B,
       PCNFSAIDPREFAT N
WHERE  N.NUMTRANSVENDA = B.NUMTRANSVENDA
  AND  N.DATACONSOLIDACAOPREFAT IS NULL