DECLARE

BEGIN 
  MERGE INTO PCFILTROAVANCADOCONFIG tgt
  USING (     
    SELECT 101 AS CODCONFIG
         , 'CALCULADO' AS TABELA
         , 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO' AS CAMPO
         , 'NUMBER' AS TIPOCAMPO
         , 'Percentual máximo permitido sobre o valor total do pedido' AS NOMELIVRE
         , 'I' AS VISIVELFILTRO
         , NULL AS TABELAPESQUISA
         , NULL AS CAMPOPESQUISA
         , NULL AS DESCRICAOPESQUISA
         , NULL AS CRITERIOPESQUISA
         , NULL AS ROTULOPESQUISA
         , 'S' AS VISIVELCONDICAO
         , 'S' AS VISIVELREGRAEXCECAO
         , 'Calculado' AS GRUPO
         , 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO' AS NOMEPARAMETRO
         , NULL AS CODIGONIVEL
         , 'C' AS TIPOVALIDACAO
         , NULL AS CHAVEMULTIPLA
      FROM DUAL UNION ALL     
    
    --SELECT 101, 'CALCULADO', 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO', 'NUMBER', 'Percentual máximo permitido sobre o valor total do pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 102, 'CALCULADO', 'PERCENTUALMINIMOITENSOBRIGATORIOPEDIDO', 'NUMBER', 'Percentual mínimo de itens obrigatórios que devem estar no pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'PERCENTUALMINIMOITENSOBRIGATORIOPEDIDO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 103, 'CALCULADO', 'QUANTIDADEMINIMAITENSDISTINTOSPEDIDO', 'NUMBER', 'Quantidade mínima de produtos distintos no pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'QUANTIDADEMINIMAITENSDISTINTOSPEDIDO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 104, 'CALCULADO', 'QUANTIDADEMINIMAITENSPROMOCAO', 'NUMBER', 'Quantidade mínima de itens participantes da promoção', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'QUANTIDADEMINIMAITENSPROMOCAO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 105, 'CALCULADO', 'PROMOCAOUNICAPEDIDO', 'VARCHAR2', 'Indica se o pedido deve conter apenas esta promoção', 'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', 'PROMOCAOUNICAPEDIDO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 106, 'CALCULADO', 'VALORMAXIMOPERMITIDOPEDIDO', 'NUMBER', 'Valor máximo permitido para o pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'VALORMAXIMOPERMITIDOPEDIDO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 107, 'CALCULADO', 'VALORMINIMOEXIGIDOATIVARPROMOCAO', 'NUMBER', 'Valor mínimo exigido para ativar a promoção', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'VALORMINIMOEXIGIDOATIVARPROMOCAO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 108, 'CALCULADO', 'VALORMINIMOTOTALEXIGIDOPEDIDO', 'NUMBER', 'Valor mínimo total exigido para o pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', 'VALORMINIMOTOTALEXIGIDOPEDIDO', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 109, 'CALCULADO', 'ATIVAVALIDACAOMIXSOMAITENSMESMOFABRICANTE', 'VARCHAR2', 'Ativa validação de mix somando produtos de um mesmo fabricante', 'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', 'ATIVAVALIDACAOMIXSOMAITENSMESMOFABRICANTE', NULL, 'C', NULL FROM DUAL UNION ALL
    SELECT 110, 'CALCULADO', 'ATIVAVALIDACAOMIXMAIORFABRICANTE', 'VARCHAR2', 'Ativa validação de mix considerando o maior mix entre fabricantes', 'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', 'ATIVAVALIDACAOMIXMAIORFABRICANTE', NULL, 'C', NULL FROM DUAL
  ) src
     ON (tgt.CODCONFIG = src.CODCONFIG)
   WHEN MATCHED THEN UPDATE SET
    tgt.TABELA = src.TABELA
   ,tgt.CAMPO = src.CAMPO
   ,tgt.TIPOCAMPO = src.TIPOCAMPO
   ,tgt.TABELAPESQUISA = src.TABELAPESQUISA
   ,tgt.CAMPOPESQUISA = src.CAMPOPESQUISA
   ,tgt.DESCRICAOPESQUISA = src.DESCRICAOPESQUISA
   ,tgt.CRITERIOPESQUISA = src.CRITERIOPESQUISA
   ,tgt.ROTULOPESQUISA = src.ROTULOPESQUISA
   ,tgt.GRUPO = src.GRUPO
   ,tgt.NOMEPARAMETRO = src.NOMEPARAMETRO
   ,tgt.CODIGONIVEL = src.CODIGONIVEL
   ,tgt.TIPOVALIDACAO = src.TIPOVALIDACAO
   ,tgt.CHAVEMULTIPLA = src.CHAVEMULTIPLA
   WHEN NOT MATCHED THEN
     INSERT (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CRITERIOPESQUISA, ROTULOPESQUISA, VISIVELCONDICAO, VISIVELREGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA)
     VALUES (src.CODCONFIG, src.TABELA, src.CAMPO, src.TIPOCAMPO, src.NOMELIVRE, src.VISIVELFILTRO, src.TABELAPESQUISA, src.CAMPOPESQUISA, src.DESCRICAOPESQUISA, src.CRITERIOPESQUISA, src.ROTULOPESQUISA, src.VISIVELCONDICAO, src.VISIVELREGRAEXCECAO, src.GRUPO, src.NOMEPARAMETRO, src.CODIGONIVEL, src.TIPOVALIDACAO, src.CHAVEMULTIPLA);

  MERGE INTO PCFILTROAVANCADOLAYOUTC tgt
  USING (
    SELECT 2 AS CODLAYOUT, 
	      'Requisitos de promoção de medicamentos' AS DESCRICAO 
      FROM DUAL
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT)
   WHEN MATCHED THEN UPDATE SET
     tgt.DESCRICAO = src.DESCRICAO
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, DESCRICAO) VALUES (src.CODLAYOUT, src.DESCRICAO);
    
  MERGE INTO PCFILTROAVANCADOLAYOUTI tgt
  USING (
    SELECT 2 AS CODLAYOUT, 
           CODCONFIG 
      FROM PCFILTROAVANCADOCONFIG 
     WHERE TIPOCAMPO <> 'NIVEL' 
       AND CODCONFIG BETWEEN 101 AND 110
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT AND tgt.CODCONFIG = src.CODCONFIG)
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, CODCONFIG) VALUES (src.CODLAYOUT, src.CODCONFIG);
END;