DECLARE

  V_SQL_FORMULA_CODCONFIG_101 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_102 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_103 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_104 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_105 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_106 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_107 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_108 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_109 VARCHAR2(10000);
  V_SQL_FORMULA_CODCONFIG_110 VARCHAR2(10000);

BEGIN

  V_SQL_FORMULA_CODCONFIG_101 := 'SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_CODCONFIG_102 := 'SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 VALOR_OBTIDO FROM PCPEDI I, (SELECT P.NUMPED, SUM(P.QT * P.PVENDA) TOTAL FROM PCPEDI P, PCDESCONTO D WHERE P.CODPROMOCAOMED = D.CODPROMOCAOMED AND P.CODPROD = D.CODPROD AND P.NUMPED = :NUMPED AND P.CODPROMOCAOMED = :CODPROMOCAOMED AND D.OBRIGATORIOPARCIALMED = ''S'' GROUP BY P.NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_CODCONFIG_103 := 'SELECT CASE WHEN COUNT(DISTINCT CODPROD) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, COUNT(DISTINCT CODPROD) VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED';
  V_SQL_FORMULA_CODCONFIG_104 := 'SELECT CASE WHEN COUNT(1) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, COUNT(1) VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_CODCONFIG_105 := 'SELECT CASE WHEN (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) = 1 THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, NULL PARAMETRO, (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) VALOR_OBTIDO FROM DUAL';
  V_SQL_FORMULA_CODCONFIG_106 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_CODCONFIG_107 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_CODCONFIG_108 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE NUMPED = :NUMPED';
  V_SQL_FORMULA_CODCONFIG_109 := 'SELECT CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN ''FALSE'' ELSE ''TRUE'' END PODE_SEGUIR, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.PARAMETRO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.PARAMETRO END) END) PARAMETRO, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.VALOR_OBTIDO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.VALOR_OBTIDO END) END) VALOR_OBTIDO FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= B.QTMINMIXFORNECEDORMED THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, B.QTMINMIXFORNECEDORMED PARAMETRO, COUNT(DISTINCT(I.CODPROD)) VALOR_OBTIDO FROM PCPEDI I, PCPRODUT P, (SELECT P.CODFORNEC, SUM(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCDESCONTO D, PCPRODUT P WHERE D.CODPROD = P.CODPROD AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) B WHERE P.CODFORNEC = B.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED GROUP BY B.QTMINMIXFORNECEDORMED) A';
  V_SQL_FORMULA_CODCONFIG_110 := 'SELECT CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN ''FALSE'' ELSE ''TRUE'' END PODE_SEGUIR, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.PARAMETRO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.PARAMETRO END) END) PARAMETRO, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.VALOR_OBTIDO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.VALOR_OBTIDO END) END) VALOR_OBTIDO FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= B.QTMINMIXFORNECEDORMED THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, B.QTMINMIXFORNECEDORMED PARAMETRO, COUNT(DISTINCT(I.CODPROD)) VALOR_OBTIDO FROM PCPEDI I, PCPRODUT P, (SELECT P.CODFORNEC, MAX(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCDESCONTO D, PCPRODUT P WHERE D.CODPROD = P.CODPROD AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) B WHERE P.CODFORNEC = B.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED GROUP BY B.QTMINMIXFORNECEDORMED) A';

  MERGE INTO PCFILTROAVANCADOCONFIG tgt
  USING (     
    SELECT 101 AS CODCONFIG
         , 'CALCULADO' AS TABELA
         , 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO' AS CAMPO
         , 'NUMBER' AS TIPOCAMPO
         , 'Percentual máximo permitido sobre o valor total do pedido' AS NOMELIVRE
         , 'I' AS VISIVELFILTRO
         , NULL AS TABELAPESQUISA
         , NULL AS CAMPOPESQUISA
         , NULL AS DESCRICAOPESQUISA
         , NULL AS CRITERIOPESQUISA
         , NULL AS ROTULOPESQUISA
         , 'S' AS VISIVELCONDICAO
         , 'S' AS VISIVELREGRAEXCECAO
         , 'Calculado' AS GRUPO
         , NULL AS NOMEPARAMETRO
         , NULL AS CODIGONIVEL
         , 'C' AS TIPOVALIDACAO
         , NULL AS CHAVEMULTIPLA
         , V_SQL_FORMULA_CODCONFIG_101 AS FORMULASQL
      FROM DUAL UNION ALL     
    
    --SELECT 101, 'CALCULADO', 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO', 'NUMBER', 'Percentual máximo permitido sobre o valor total do pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_101 FROM DUAL UNION ALL
    SELECT 102, 'CALCULADO', 'PERCENTUALMINIMOITENSOBRIGATORIOPEDIDO', 'NUMBER', 'Percentual mínimo de itens obrigatórios que devem estar no pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_102 FROM DUAL UNION ALL
    SELECT 103, 'CALCULADO', 'QUANTIDADEMINIMAITENSDISTINTOSPEDIDO', 'NUMBER', 'Quantidade mínima de produtos distintos no pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_103 FROM DUAL UNION ALL
    SELECT 104, 'CALCULADO', 'QUANTIDADEMINIMAITENSPROMOCAO', 'NUMBER', 'Quantidade mínima de itens participantes da promoção', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_104 FROM DUAL UNION ALL
    SELECT 105, 'CALCULADO', 'PROMOCAOUNICAPEDIDO', 'VARCHAR2', 'Indica se o pedido deve conter apenas esta promoção', 'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_105 FROM DUAL UNION ALL
    SELECT 106, 'CALCULADO', 'VALORMAXIMOPERMITIDOPEDIDO', 'NUMBER', 'Valor máximo permitido para o pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_106 FROM DUAL UNION ALL
    SELECT 107, 'CALCULADO', 'VALORMINIMOEXIGIDOATIVARPROMOCAO', 'NUMBER', 'Valor mínimo exigido para ativar a promoção', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_107 FROM DUAL UNION ALL
    SELECT 108, 'CALCULADO', 'VALORMINIMOTOTALEXIGIDOPEDIDO', 'NUMBER', 'Valor mínimo total exigido para o pedido', 'I', NULL, NULL, NULL, NULL, NULL, 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_108 FROM DUAL UNION ALL
    SELECT 109, 'CALCULADO', 'ATIVAVALIDACAOMIXSOMAITENSMESMOFABRICANTE', 'VARCHAR2', 'Ativa validação de mix somando produtos de um mesmo fabricante', 'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_109 FROM DUAL UNION ALL
    SELECT 110, 'CALCULADO', 'ATIVAVALIDACAOMIXMAIORFABRICANTE', 'VARCHAR2', 'Ativa validação de mix considerando o maior mix entre fabricantes', 'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', NULL, NULL, 'C', NULL, V_SQL_FORMULA_CODCONFIG_110 FROM DUAL
  ) src
     ON (tgt.CODCONFIG = src.CODCONFIG)
   WHEN MATCHED THEN UPDATE SET
    tgt.TABELA = src.TABELA
   ,tgt.CAMPO = src.CAMPO
   ,tgt.TIPOCAMPO = src.TIPOCAMPO
   ,tgt.TABELAPESQUISA = src.TABELAPESQUISA
   ,tgt.CAMPOPESQUISA = src.CAMPOPESQUISA
   ,tgt.DESCRICAOPESQUISA = src.DESCRICAOPESQUISA
   ,tgt.CRITERIOPESQUISA = src.CRITERIOPESQUISA
   ,tgt.ROTULOPESQUISA = src.ROTULOPESQUISA
   ,tgt.GRUPO = src.GRUPO
   ,tgt.NOMEPARAMETRO = src.NOMEPARAMETRO
   ,tgt.CODIGONIVEL = src.CODIGONIVEL
   ,tgt.TIPOVALIDACAO = src.TIPOVALIDACAO
   ,tgt.CHAVEMULTIPLA = src.CHAVEMULTIPLA
   ,tgt.FORMULASQL = src.FORMULASQL
   WHEN NOT MATCHED THEN
     INSERT (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CRITERIOPESQUISA, ROTULOPESQUISA, VISIVELCONDICAO, VISIVELREGRAEXCECAO, GRUPO, NOMEPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA, FORMULASQL)
     VALUES (src.CODCONFIG, src.TABELA, src.CAMPO, src.TIPOCAMPO, src.NOMELIVRE, src.VISIVELFILTRO, src.TABELAPESQUISA, src.CAMPOPESQUISA, src.DESCRICAOPESQUISA, src.CRITERIOPESQUISA, src.ROTULOPESQUISA, src.VISIVELCONDICAO, src.VISIVELREGRAEXCECAO, src.GRUPO, src.NOMEPARAMETRO, src.CODIGONIVEL, src.TIPOVALIDACAO, src.CHAVEMULTIPLA, src.FORMULASQL);

  MERGE INTO PCFILTROAVANCADOLAYOUTC tgt
  USING (
    SELECT 2 AS CODLAYOUT, 
	      'Requisitos de promoção de medicamentos' AS DESCRICAO 
      FROM DUAL
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT)
   WHEN MATCHED THEN UPDATE SET
     tgt.DESCRICAO = src.DESCRICAO
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, DESCRICAO) VALUES (src.CODLAYOUT, src.DESCRICAO);
    
  MERGE INTO PCFILTROAVANCADOLAYOUTI tgt
  USING (
    SELECT 2 AS CODLAYOUT, 
           CODCONFIG 
      FROM PCFILTROAVANCADOCONFIG 
     WHERE TIPOCAMPO <> 'NIVEL' 
       AND CODCONFIG BETWEEN 101 AND 110
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT AND tgt.CODCONFIG = src.CODCONFIG)
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, CODCONFIG) VALUES (src.CODLAYOUT, src.CODCONFIG);

END;