DECLARE
  iCOUNT Integer;
BEGIN     
  FOR DADOS IN (  
    SELECT 100 COD, 'AUTORIZADO O USO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 101 COD, 'CANCELAMENTO DE CT-E HOMOLOGADO' DESCRICAO FROM DUAL UNION  
    SELECT 102 COD, 'INUTILIZACAO DE NUMERO HOMOLOGADO' DESCRICAO FROM DUAL UNION  
    SELECT 103 COD, 'LOTE RECEBIDO COM SUCESSO' DESCRICAO FROM DUAL UNION  
    SELECT 104 COD, 'LOTE PROCESSADO' DESCRICAO FROM DUAL UNION  
    SELECT 105 COD, 'LOTE EM PROCESSAMENTO' DESCRICAO FROM DUAL UNION  
    SELECT 106 COD, 'LOTE NAO LOCALIZADO' DESCRICAO FROM DUAL UNION  
    SELECT 107 COD, 'SERVICO EM OPERACAO' DESCRICAO FROM DUAL UNION  
    SELECT 108 COD, 'SERVICO PARALISADO MOMENTANEAMENTE (CURTO PRAZO)' DESCRICAO FROM DUAL UNION  
    SELECT 109 COD, 'SERVICO PARALISADO SEM PREVISAO' DESCRICAO FROM DUAL UNION  
    SELECT 110 COD, 'USO DENEGADO' DESCRICAO FROM DUAL UNION  
    SELECT 111 COD, 'CONSULTA CADASTRO COM UMA OCORRENCIA' DESCRICAO FROM DUAL UNION  
    SELECT 112 COD, 'CONSULTA CADASTRO COM MAIS DE UMA OCORRENCIA' DESCRICAO FROM DUAL UNION  
    SELECT 113 COD, 'SERVICO SVC EM OPERACAO. DESATIVACAO PREVISTA PARA A UF EM DD/MM/AA, AS HH:MM HORAS' DESCRICAO FROM DUAL UNION  
    SELECT 114 COD, 'SVC-[SP/RS] DESABILITADA PELA SEFAZ DE ORIGEM' DESCRICAO FROM DUAL UNION  
    SELECT 134 COD, 'EVENTO REGISTRADO E VINCULADO AO CT-E COM ALERTA PARA SITUACAO DO DOCUMENTO. [ALERTA SITUACAO DO CT-E: XXXXXXXXXX]' DESCRICAO FROM DUAL UNION  
    SELECT 135 COD, 'EVENTO REGISTRADO E VINCULADO A CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 136 COD, 'EVENTO REGISTRADO, MAS NAO VINCULADO A CT-E' DESCRICAO FROM DUAL UNION   
    SELECT 201 COD, 'REJEICAO: O NUMERO MAXIMO DE NUMERACAO DE CT-E A INUTILIZAR ULTRAPASSOU O LIMITE' DESCRICAO FROM DUAL UNION  
    SELECT 202 COD, 'REJEICAO: FALHA NO RECONHECIMENTO DA AUTORIA OU INTEGRIDADE DO ARQUIVO DIGITAL' DESCRICAO FROM DUAL UNION  
    SELECT 203 COD, 'REJEICAO: EMISSOR NAO HABILITADO PARA EMISSAO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 204 COD, 'REJEICAO: DUPLICIDADE DE CT-E [NREC:999999999999999]' DESCRICAO FROM DUAL UNION  
    SELECT 205 COD, 'REJEICAO: CT-E ESTA DENEGADO NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 206 COD, 'REJEICAO: NUMERO DE CT-E JA ESTA INUTILIZADO NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 207 COD, 'REJEICAO: CNPJ DO EMITENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 208 COD, 'REJEICAO: CNPJ DO DESTINATARIO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 209 COD, 'REJEICAO: IE DO EMITENTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 210 COD, 'REJEICAO: IE DO DESTINATARIO INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 211 COD, 'REJEICAO: IE DO SUBSTITUTO INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 212 COD, 'REJEICAO: DATA DE EMISSAO CT-E POSTERIOR A DATA DE RECEBIMENTO' DESCRICAO FROM DUAL UNION  
    SELECT 213 COD, 'REJEICAO: CNPJ-BASE DO EMITENTE DIFERE DO CNPJ-BASE DO CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION  
    SELECT 214 COD, 'REJEICAO: TAMANHO DA MENSAGEM EXCEDEU O LIMITE ESTABELECIDO' DESCRICAO FROM DUAL UNION  
    SELECT 215 COD, 'REJEICAO: FALHA NO SCHEMA XML' DESCRICAO FROM DUAL UNION  
    SELECT 216 COD, 'REJEICAO: CHAVE DE ACESSO DIFERE DA CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 217 COD, 'REJEICAO: CT-E NAO CONSTA NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 218 COD, 'REJEICAO: CT-E JA ESTA CANCELADO NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 219 COD, 'REJEICAO: CIRCULACAO DO CT-E VERIFICADA' DESCRICAO FROM DUAL UNION  
    SELECT 220 COD, 'REJEICAO: CT-E AUTORIZADO HA MAIS DE 7 DIAS (168 HORAS)' DESCRICAO FROM DUAL UNION  
    SELECT 221 COD, 'REJEICAO: CONFIRMADO A PRESTACAO DO SERVICO DO CT-E PELO DESTINATARIO' DESCRICAO FROM DUAL UNION  
    SELECT 222 COD, 'REJEICAO: PROTOCOLO DE AUTORIZACAO DE USO DIFERE DO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 223 COD, 'REJEICAO: CNPJ DO TRANSMISSOR DO LOTE DIFERE DO CNPJ DO TRANSMISSOR DA CONSULTA' DESCRICAO FROM DUAL UNION  
    SELECT 224 COD, 'REJEICAO: A FAIXA INICIAL E MAIOR QUE A FAIXA FINAL' DESCRICAO FROM DUAL UNION  
    SELECT 225 COD, 'REJEICAO: FALHA NO SCHEMA XML DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 226 COD, 'REJEICAO: CODIGO DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION  
    SELECT 227 COD, 'REJEICAO: ERRO NA COMPOSICAO DO CAMPO ID' DESCRICAO FROM DUAL UNION  
    SELECT 228 COD, 'REJEICAO: DATA DE EMISSAO MUITO ATRASADA' DESCRICAO FROM DUAL UNION  
    SELECT 229 COD, 'REJEICAO: IE DO EMITENTE NAO INFORMADA' DESCRICAO FROM DUAL UNION  
    SELECT 230 COD, 'REJEICAO: IE DO EMITENTE NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 231 COD, 'REJEICAO: IE DO EMITENTE NAO VINCULADA AO CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 232 COD, 'REJEICAO: IE DO DESTINATARIO NAO INFORMADA' DESCRICAO FROM DUAL UNION  
    SELECT 233 COD, 'REJEICAO: IE DO DESTINATARIO NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 235 COD, 'REJEICAO: INSCRICAO SUFRAMA INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 236 COD, 'REJEICAO: CHAVE DE ACESSO COM DIGITO VERIFICADOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 237 COD, 'REJEICAO: CPF DO DESTINATARIO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 238 COD, 'REJEICAO: CABECALHO - VERSAO DO ARQUIVO XML SUPERIOR A VERSAO VIGENTE' DESCRICAO FROM DUAL UNION  
    SELECT 239 COD, 'REJEICAO: CABECALHO - VERSAO DO ARQUIVO XML NAO SUPORTADA' DESCRICAO FROM DUAL UNION  
    SELECT 240 COD, 'REJEICAO: CANCELAMENTO/INUTILIZACAO - IRREGULARIDADE FISCAL DO EMITENTE' DESCRICAO FROM DUAL UNION  
    SELECT 241 COD, 'REJEICAO: UM NUMERO DA FAIXA JA FOI UTILIZADO' DESCRICAO FROM DUAL UNION  
    SELECT 242 COD, 'REJEICAO: ELEMENTO CTECABECMSG INEXISTENTE NO SOAP HEADER' DESCRICAO FROM DUAL UNION  
    SELECT 243 COD, 'REJEICAO: XML MAL FORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 245 COD, 'REJEICAO: CNPJ EMITENTE NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 246 COD, 'REJEICAO: CNPJ DESTINATARIO NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 247 COD, 'REJEICAO: SIGLA DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION  
    SELECT 248 COD, 'REJEICAO: UF DO RECIBO DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION  
    SELECT 249 COD, 'REJEICAO: UF DA CHAVE DE ACESSO DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION  
    SELECT 250 COD, 'REJEICAO: UF DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION  
    SELECT 251 COD, 'REJEICAO: UF/MUNICIPIO DESTINATARIO NAO PERTENCE A SUFRAMA' DESCRICAO FROM DUAL UNION  
    SELECT 252 COD, 'REJEICAO: AMBIENTE INFORMADO DIVERGE DO AMBIENTE DE RECEBIMENTO' DESCRICAO FROM DUAL UNION  
    SELECT 253 COD, 'REJEICAO: DIGITO VERIFICADOR DA CHAVE DE ACESSO COMPOSTA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 254 COD, 'REJEICAO: CT-E A SER COMPLEMENTADO NAO INFORMADO PARA CT-E COMPLEMENTAR' DESCRICAO FROM DUAL UNION  
    SELECT 256 COD, 'REJEICAO: UM NUMERO DE CT-E DA FAIXA ESTA INUTILIZADO NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 257 COD, 'REJEICAO: SOLICITANTE NAO HABILITADO PARA EMISSAO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 258 COD, 'REJEICAO: CNPJ DA CONSULTA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 259 COD, 'REJEICAO: CNPJ DA CONSULTA NAO CADASTRADO COMO CONTRIBUINTE NA UF' DESCRICAO FROM DUAL UNION  
    SELECT 260 COD, 'REJEICAO: IE DA CONSULTA INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 261 COD, 'REJEICAO: IE DA CONSULTA NAO CADASTRADA COMO CONTRIBUINTE NA UF' DESCRICAO FROM DUAL UNION  
    SELECT 262 COD, 'REJEICAO: UF NAO FORNECE CONSULTA POR CPF' DESCRICAO FROM DUAL UNION  
    SELECT 263 COD, 'REJEICAO: CPF DA CONSULTA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 264 COD, 'REJEICAO: CPF DA CONSULTA NAO CADASTRADO COMO CONTRIBUINTE NA UF' DESCRICAO FROM DUAL UNION  
    SELECT 265 COD, 'REJEICAO: SIGLA DA UF DA CONSULTA DIFERE DA UF DO WEB SERVICE' DESCRICAO FROM DUAL UNION  
    SELECT 266 COD, 'REJEICAO: SERIE UTILIZADA NAO PERMITIDA NO WEB SERVICE' DESCRICAO FROM DUAL UNION  
    SELECT 267 COD, 'REJEICAO: CT-E COMPLEMENTAR REFERENCIA UM CT-E INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 268 COD, 'REJEICAO: CT-E COMPLEMENTAR REFERENCIA OUTRO CT-E COMPLEMENTAR' DESCRICAO FROM DUAL UNION  
    SELECT 269 COD, 'REJEICAO: CNPJ EMITENTE DO CT-E COMPLEMENTAR DIFERE DO CNPJ DO CT COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 270 COD, 'REJEICAO: CODIGO MUNICIPIO DO FATO GERADOR: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 271 COD, 'REJEICAO: CODIGO MUNICIPIO DO FATO GERADOR: DIFERE DA UF DO EMITENTE' DESCRICAO FROM DUAL UNION  
    SELECT 272 COD, 'REJEICAO: CODIGO MUNICIPIO DO EMITENTE: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 273 COD, 'REJEICAO: CODIGO MUNICIPIO DO EMITENTE: DIFERE DA UF DO EMITENTE' DESCRICAO FROM DUAL UNION  
    SELECT 274 COD, 'REJEICAO: CODIGO MUNICIPIO DO DESTINATARIO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 275 COD, 'REJEICAO: CODIGO MUNICIPIO DO DESTINATARIO: DIFERE DA UF DO DESTINATARIO' DESCRICAO FROM DUAL UNION  
    SELECT 276 COD, 'REJEICAO: CODIGO MUNICIPIO DO LOCAL DE RETIRADA: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 277 COD, 'REJEICAO: CODIGO MUNICIPIO DO LOCAL DE RETIRADA: DIFERE DA UF DO LOCAL DE RETIRADA' DESCRICAO FROM DUAL UNION  
    SELECT 278 COD, 'REJEICAO: CODIGO MUNICIPIO DO LOCAL DE ENTREGA: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 279 COD, 'REJEICAO: CODIGO MUNICIPIO DO LOCAL DE ENTREGA: DIFERE DA UF DO LOCAL DE ENTREGA' DESCRICAO FROM DUAL UNION  
    SELECT 280 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 281 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR DATA VALIDADE' DESCRICAO FROM DUAL UNION  
    SELECT 282 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR SEM CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 283 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR - ERRO CADEIA DE CERTIFICACAO' DESCRICAO FROM DUAL UNION  
    SELECT 284 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR REVOGADO' DESCRICAO FROM DUAL UNION  
    SELECT 285 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR DIFERE ICP-BRASIL' DESCRICAO FROM DUAL UNION  
    SELECT 286 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR ERRO NO ACESSO A LCR' DESCRICAO FROM DUAL UNION  
    SELECT 289 COD, 'REJEICAO: CODIGO DA UF INFORMADA DIVERGE DA UF SOLICITADA' DESCRICAO FROM DUAL UNION  
    SELECT 290 COD, 'REJEICAO: CERTIFICADO ASSINATURA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 291 COD, 'REJEICAO: CERTIFICADO ASSINATURA DATA VALIDADE' DESCRICAO FROM DUAL UNION  
    SELECT 292 COD, 'REJEICAO: CERTIFICADO ASSINATURA SEM CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 293 COD, 'REJEICAO: CERTIFICADO ASSINATURA - ERRO CADEIA DE CERTIFICACAO' DESCRICAO FROM DUAL UNION  
    SELECT 294 COD, 'REJEICAO: CERTIFICADO ASSINATURA REVOGADO' DESCRICAO FROM DUAL UNION  
    SELECT 295 COD, 'REJEICAO: CERTIFICADO ASSINATURA DIFERE ICP-BRASIL' DESCRICAO FROM DUAL UNION  
    SELECT 296 COD, 'REJEICAO: CERTIFICADO ASSINATURA ERRO NO ACESSO A LCR' DESCRICAO FROM DUAL UNION  
    SELECT 297 COD, 'REJEICAO: ASSINATURA DIFERE DO CALCULADO' DESCRICAO FROM DUAL UNION  
    SELECT 298 COD, 'REJEICAO: ASSINATURA DIFERE DO PADRAO DO PROJETO' DESCRICAO FROM DUAL UNION  
    SELECT 299 COD, 'REJEICAO: XML DA AREA DE CABECALHO COM CODIFICACAO DIFERENTE DE UTF-8' DESCRICAO FROM DUAL UNION  
    SELECT 301 COD, 'USO DENEGADO : IRREGULARIDADE FISCAL DO EMITENTE' DESCRICAO FROM DUAL UNION  
    SELECT 401 COD, 'REJEICAO: CPF DO REMETENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 402 COD, 'REJEICAO: XML DA AREA DE DADOS COM CODIFICACAO DIFERENTE DE UTF-8' DESCRICAO FROM DUAL UNION  
    SELECT 404 COD, 'REJEICAO: USO DE PREFIXO DE NAMESPACE NAO PERMITIDO' DESCRICAO FROM DUAL UNION  
    SELECT 405 COD, 'REJEICAO: CODIGO DO PAIS DO EMITENTE: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 406 COD, 'REJEICAO: CODIGO DO PAIS DO DESTINATARIO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 407 COD, 'REJEICAO: O CPF SO PODE SER INFORMADO NO CAMPO EMITENTE PARA O CT-E AVULSO' DESCRICAO FROM DUAL UNION  
    SELECT 408 COD, 'REJEICAO: LOTE COM CT-E DE DIFERENTES UF' DESCRICAO FROM DUAL UNION  
    SELECT 409 COD, 'REJEICAO: CAMPO CUF INEXISTENTE NO ELEMENTO CTECABECMSG DO SOAP HEADER' DESCRICAO FROM DUAL UNION  
    SELECT 410 COD, 'REJEICAO: UF INFORMADA NO CAMPO CUF NAO E ATENDIDA PELO WEBSERVICE' DESCRICAO FROM DUAL UNION  
    SELECT 411 COD, 'REJEICAO: CAMPO VERSAODADOS INEXISTENTE NO ELEMENTO CTECABECMSG DO SOAP HEADER' DESCRICAO FROM DUAL UNION  
    SELECT 413 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE TERMINO DA PRESTACAO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 414 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE TERMINO DA PRESTACAO' DESCRICAO FROM DUAL UNION  
    SELECT 415 COD, 'REJEICAO: CNPJ DO REMETENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 416 COD, 'REJEICAO: CPF DO REMETENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 417 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE LOCALIZACAO REMETENTE: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 418 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE LOCALIZACAO REMETENTE' DESCRICAO FROM DUAL UNION  
    SELECT 419 COD, 'REJEICAO: IE DO REMETENTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 420 COD, 'REJEICAO: CNPJ REMETENTE NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 421 COD, 'REJEICAO: IE DO REMETENTE NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 422 COD, 'REJEICAO: IE DO REMETENTE NAO VINCULADA AO CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 423 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE LOCALIZACAO DESTINATARIO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 424 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE LOCALIZACAO DESTINATARIO' DESCRICAO FROM DUAL UNION  
    SELECT 425 COD, 'REJEICAO: CNPJ DESTINATARIO NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 426 COD, 'REJEICAO: IE DO DESTINATARIO NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 427 COD, 'REJEICAO: IE DO DESTINATARIO NAO VINCULADA AO CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 428 COD, 'REJEICAO: CNPJ DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 429 COD, 'REJEICAO: CPF DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 430 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE LOCALIZACAO EXPEDIDOR: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 431 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE LOCALIZACAO EXPEDIDOR' DESCRICAO FROM DUAL UNION  
    SELECT 432 COD, 'REJEICAO: IE DO EXPEDIDOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 433 COD, 'REJEICAO: CNPJ EXPEDIDOR NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 434 COD, 'REJEICAO: IE DO EXPEDIDOR NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 435 COD, 'REJEICAO: IE DO EXPEDIDOR NAO VINCULADA AO CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 436 COD, 'REJEICAO: CNPJ DO RECEBEDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 437 COD, 'REJEICAO: CPF DO RECEBEDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 438 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE LOCALIZACAO DO RECEBEDOR: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 439 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE LOCALIZACAO RECEBEDOR' DESCRICAO FROM DUAL UNION  
    SELECT 440 COD, 'REJEICAO: IE DO RECEBEDOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 441 COD, 'REJEICAO: CNPJ RECEBEDOR NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 442 COD, 'REJEICAO: IE DO RECEBEDOR NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 443 COD, 'REJEICAO: IE DO RECEBEDOR NAO VINCULADA AO CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 444 COD, 'REJEICAO: CNPJ DO TOMADOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 445 COD, 'REJEICAO: CPF DO TOMADOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 446 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE LOCALIZACAO TOMADOR: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 447 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE LOCALIZACAO TOMADOR' DESCRICAO FROM DUAL UNION  
    SELECT 448 COD, 'REJEICAO: IE DO TOMADOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 449 COD, 'REJEICAO: CNPJ TOMADOR NAO CADASTRADO' DESCRICAO FROM DUAL UNION  
    SELECT 450 COD, 'REJEICAO: DÍGITO VERIFICADOR INVÁLIDO NA CHAVE DE ACESSO DE CT-E REFERENCIADO' DESCRICAO FROM DUAL UNION  
    SELECT 451 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (ANO < 2009 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION  
    SELECT 452 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (MÊS = 0 OU MÊS > 12)' DESCRICAO FROM DUAL UNION  
    SELECT 453 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (CNPJ ZERADO OU DIGITO INVÁLIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 454 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (MODELO DIFERENTE DE 57)' DESCRICAO FROM DUAL UNION  
    SELECT 455 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE INICIO DA PRESTACAO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 456 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE INICIO DA PRESTACAO' DESCRICAO FROM DUAL UNION  
    SELECT 457 COD, 'REJEICAO: O LOTE CONTEM CT-E DE MAIS DE UM ESTABELECIMENTO EMISSOR' DESCRICAO FROM DUAL UNION  
    SELECT 458 COD, 'REJEICAO: GRUPO DE CT-E NORMAL NAO INFORMADO PARA CT-E NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 459 COD, 'REJEICAO: GRUPO DE CT-E COMPLEMENTAR NAO INFORMADO PARA CT-E COMPLEMENTAR' DESCRICAO FROM DUAL UNION  
    SELECT 460 COD, 'REJEICAO: NAO INFORMADO OS DADOS DO REMETENTE INDICADO COMO TOMADOR DO SERVICO' DESCRICAO FROM DUAL UNION  
    SELECT 461 COD, 'REJEICAO: NAO INFORMADO OS DADOS DO EXPEDIDOR INDICADO COMO TOMADOR DO SERVICO' DESCRICAO FROM DUAL UNION  
    SELECT 462 COD, 'REJEICAO: NAO INFORMADO OS DADOS DO RECEBEDOR INDICADO COMO TOMADOR DO SERVICO' DESCRICAO FROM DUAL UNION  
    SELECT 463 COD, 'REJEICAO: NAO INFORMADO OS DADOS DO DESTINATARIO INDICADO COMO TOMADOR DO SERVICO' DESCRICAO FROM DUAL UNION  
    SELECT 469 COD, 'REJEICAO: REMETENTE DEVE SER INFORMADO PARA TIPO DE SERVICO DIFERENTE DE REDESPACHO INTERMEDIARIO OU SERVICO VINCULADO A MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 470 COD, 'REJEICAO: DESTINATARIO DEVE SER INFORMADO PARA TIPO DE SERVICO DIFERENTE DE REDESPACHO INTERMEDIARIO OU SERVICO VINCULADO A MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 471 COD, 'REJEICAO: ANO DE INUTILIZACAO NAO PODE SER SUPERIOR AO ANO ATUAL' DESCRICAO FROM DUAL UNION  
    SELECT 472 COD, 'REJEICAO: ANO DE INUTILIZACAO NAO PODE SER INFERIOR A 2008' DESCRICAO FROM DUAL UNION  
    SELECT 473 COD, 'REJEICAO: TIPO AUTORIZADOR DO RECIBO DIVERGE DO ORGAO AUTORIZADOR' DESCRICAO FROM DUAL UNION  
    SELECT 474 COD, 'REJEICAO: EXPEDIDOR DEVE SER INFORMADO PARA TIPO DE SERVICO DE REDESPACHO INTERMEDIARIO E SERVICO VINCULADO A MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 475 COD, 'REJEICAO: RECEBEDOR DEVE SER INFORMADO PARA TIPO DE SERVICO DE REDESPACHO INTERMEDIARIO E SERVICO VINCULADO A MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 478 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (NUMERO CT = 0)' DESCRICAO FROM DUAL UNION  
    SELECT 479 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 480 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 481 COD, 'REJEICAO: IE DEVE SER INFORMADA PARA TOMADOR CONTRIBUINTE' DESCRICAO FROM DUAL UNION  
    SELECT 482 COD, 'REJEICAO: IE DO TOMADOR ISENTO DEVE SER PREENCHIDA COM ISENTO ' DESCRICAO FROM DUAL UNION  
    SELECT 483 COD, 'REJEICAO: IE NÃO PODE SER INFORMADA PARA TOMADOR NÃO CONTRIBUINTE' DESCRICAO FROM DUAL UNION  
    SELECT 489 COD, 'REJEICAO: IE DO TOMADOR NAO CADASTRADA' DESCRICAO FROM DUAL UNION  
    SELECT 490 COD, 'REJEICAO: IE DO TOMADOR NAO VINCULADA AO CNPJ' DESCRICAO FROM DUAL UNION  
    SELECT 491 COD, 'REJEICAO: CT-E REFERENCIADO E CT-E COMPLEMENTAR' DESCRICAO FROM DUAL UNION  
    SELECT 492 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE ENVIO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 493 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE ENVIO' DESCRICAO FROM DUAL UNION  
    SELECT 494 COD, 'REJEICAO: PROCESSO DE EMISSAO INFORMADO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 495 COD, 'REJEICAO: SOLICITANTE NAO AUTORIZADO PARA CONSULTA' DESCRICAO FROM DUAL UNION  
    SELECT 496 COD, 'REJEICAO: GRUPO CT-E DE ANULACAO NAO INFORMADO PARA O CT-E DE ANULACAO' DESCRICAO FROM DUAL UNION  
    SELECT 497 COD, 'REJEICAO: CT-E OBJETO DA ANULACAO INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 498 COD, 'REJEICAO: CT-E OBJETO DA ANULACAO DEVE ESTAR COM A SITUACAO AUTORIZADA (NAO PODE ESTAR CANCELADO OU DENEGADO)' DESCRICAO FROM DUAL UNION  
    SELECT 499 COD, 'REJEICAO: CT-E DE ANULACAO DEVE TER TIPO DE EMISSAO = NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 500 COD, 'REJEICAO: CT-E OBJETO DA ANULACAO DEVE TER TIPO = 0 (NORMAL) OU 3 (SUBSTITUICAO)' DESCRICAO FROM DUAL UNION  
    SELECT 501 COD, 'REJEICAO: DATA DE EMISSAO DO CT-E DE ANULACAO DEVE OCORRER EM ATE 60 DIAS' DESCRICAO FROM DUAL UNION  
    SELECT 502 COD, 'REJEICAO: CT-E DE ANULACAO DEVE TER O VALOR DO ICMS E DE PRESTACAO IGUAIS AO CT-E ORIGINAL' DESCRICAO FROM DUAL UNION  
    SELECT 503 COD, 'REJEICAO: CT-E SUSBTITUTO DEVE TER TIPO DE EMISSAO = NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 504 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVÁLIDA (UF INVÁLIDA)' DESCRICAO FROM DUAL UNION  
    SELECT 505 COD, 'REJEICAO: GRUPO CT-E DE SUBSTITUICAO NAO INFORMADO PARA O CT-E DE SUBSTITUICAO' DESCRICAO FROM DUAL UNION  
    SELECT 507 COD, 'REJEICAO: CHAVE DE ACESSO INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO FROM DUAL UNION     
    SELECT 508 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 510 COD, 'REJEICAO: CNPJ DO EMITENTE DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 511 COD, 'REJEICAO: CNPJ/CPF DO REMETENTE DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 512 COD, 'REJEICAO: CNPJ/CPF DO DESTINATARIO DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 513 COD, 'REJEICAO: UF NAO ATENDIDA PELA SVC-[SP/RS]' DESCRICAO FROM DUAL UNION  
    SELECT 514 COD, 'REJEICAO: VERSAO DA MENSAGEM NAO SUPORTADA NA SVC' DESCRICAO FROM DUAL UNION  
    SELECT 515 COD, 'REJEICAO: O TPEMIS INFORMADO SO E VALIDO NA CONTINGENCIA SVC' DESCRICAO FROM DUAL UNION  
    SELECT 516 COD, 'REJEICAO: O TPEMIS INFORMADO E INCOMPATIVEL COM SVC-[SP/RS]' DESCRICAO FROM DUAL UNION  
    SELECT 517 COD, 'REJEICAO: CT-E INFORMADO EM SVC DEVE SER NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 518 COD, 'REJEICAO: SERVICO INDISPONIVEL NA SVC' DESCRICAO FROM DUAL UNION  
    SELECT 519 COD, 'REJEIÇÃO: CFOP INVÁLIDO PARA OPERAÇÃO' DESCRICAO FROM DUAL UNION  
    SELECT 520 COD, 'REJEIÇÃO: CT-E NÃO PODE RECEBER MAIS DO QUE 10 CT-E COMPLEMENTARES ' DESCRICAO FROM DUAL UNION  
    SELECT 521 COD, 'REJEIÇÃO: OS DOCUMENTOS DE TRANSPORTE ANTERIOR DEVEM SER INFORMADOS ' DESCRICAO FROM DUAL UNION  
    SELECT 522 COD, 'REJEIÇÃO: NRO ITEM ALTERADO INVÁLIDO. PREENCHER COM VALOR NUMÉRICO (01 – 99)' DESCRICAO FROM DUAL UNION  
    SELECT 523 COD, 'REJEICAO: VEDADO CANCELAMENTO QUANDO EXISTIR EVENTO CARTA DE CORREÇÃO ' DESCRICAO FROM DUAL UNION  
    SELECT 524 COD, 'REJEICAO: CFOP INVÁLIDO, INFORMAR 5932 OU 6932' DESCRICAO FROM DUAL UNION  
    SELECT 527 COD, 'REJEICAO: NF-E DUPLICADA NO CT-E [CHNFE: 99999999999999999999999999999999999999999999]' DESCRICAO FROM DUAL UNION  
    SELECT 528 COD, 'REJEICAO: VEDADO CANCELAMENTO SE EXITIR MDF-E AUTORIZADO PARA O CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 529 COD, 'REJEICAO: VEDADO CANCELAMENTO DO CT-E MULTIMODAL SE EXISTIR CT-E DE SERVIÇO VINCULADO AUTORIZADO REFERENCIANDO O MULTIMODAL.' DESCRICAO FROM DUAL UNION  
    SELECT 530 COD, 'REJEICAO: SE AMBIENTE SVC, REJEITAR EVENTOS DIFERENTES DE EPEC E CANCELAMENTO' DESCRICAO FROM DUAL UNION  
    SELECT 531 COD, 'REJEICAO: VALOR A RECEBER DEVE SER MENOR OU IGUAL VALOR DA PRESTAÇÃO' DESCRICAO FROM DUAL UNION  
    SELECT 532 COD, 'REJEICAO: MUNICÍPIO DO REMENTENTE INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 533 COD, 'REJEICAO: MUNICÍPIO DO DESTINATÁRIO INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 534 COD, 'REJEICAO: MUNICÍPIO DO EXPEDIDOR INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 535 COD, 'REJEICAO: MUNICÍPIO DO RECEBEDOR INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 536 COD, 'REJEICAO: MUNICÍPIO DO TOMADOR INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 537 COD, 'REJEICAO: MUNICÍPIO DE ENVIO INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 538 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (UF INVÁLIDA)' DESCRICAO FROM DUAL UNION  
    SELECT 539 COD, 'DUPLICIDADE DE CT-E, COM DIFERENÇA NA CHAVE DE ACESSO [ChCte: [9999999999999999999999999999999999999999999] [nProt:999999999999999][DhAut: AAAA-MM-DDTHH:MM:SS TZD]' DESCRICAO FROM DUAL UNION  
    SELECT 541 COD, 'REJEICAO: MUNICÍPIO DE INÍCIO DA PRESTAÇÃO INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 542 COD, 'REJEICAO: MUNICÍPIO DE TÉRMINO DA PRESTAÇÃO INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 543 COD, 'REJEICAO: CHAVE DE CT-E DUPLICADA EM DOCUMENTOS ANTERIORES' DESCRICAO FROM DUAL UNION  
    SELECT 544 COD, 'REJEICAO: DÍGITO VERIFICADOR INVÁLIDO NA CHAVE DE ACESSO DE CT-E ANTERIOR' DESCRICAO FROM DUAL UNION  
    SELECT 545 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (ANO < 2009 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION  
    SELECT 546 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (MÊS = 0 OU MÊS > 12)' DESCRICAO FROM DUAL UNION  
    SELECT 547 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (CNPJ ZERADO OU DIGITO INVÁLIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 548 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (MODELO DIFERENTE DE 57)' DESCRICAO FROM DUAL UNION  
    SELECT 549 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E ANTERIOR INVÁLIDA (NUMERO CT = 0)' DESCRICAO FROM DUAL UNION  
    SELECT 550 COD, 'REJEICAO: O CNPJ/CPF DO EXPEDIDOR DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 551 COD, 'REJEICAO: O CNPJ/CPF DO RECEBEDOR DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 552 COD, 'REJEICAO: O CNPJ/CPF DO TOMADOR DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 553 COD, 'REJEICAO: A IE DO EMITENTE DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 554 COD, 'REJEICAO: A IE DO REMETENTE DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 555 COD, 'REJEICAO: A IE DO DESTINATARIO DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 556 COD, 'REJEICAO: A IE DO EXPEDIDOR DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 557 COD, 'REJEICAO: A IE DO RECEBEDOR DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 558 COD, 'REJEICAO: A IE DO TOMADOR DO CT-E SUBSTITUTO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 559 COD, 'REJEICAO: A UF DE INICIO DA PRESTACAO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 560 COD, 'REJEICAO: A UF DE FIM DA PRESTACAO DEVE SER IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 561 COD, 'REJEICAO: O VALOR DA PRESTACAO DO SERVICO DEVE SER MENOR OU IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 562 COD, 'REJEICAO: O VALOR DO ICMS DO CT-E SUBSITUTO DEVE SER MENOR OU IGUAL AO INFORMADO NO CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 563 COD, 'REJEICAO: A SUBSTITUICAO DE UM CT-E DEVE OCORRER NO PRAZO MAXIMO DE 90 DIAS CONTADOS DA DATA DE EMISSAO DO CT-E OBJETO DE SUBSTITUICAO' DESCRICAO FROM DUAL UNION  
    SELECT 564 COD, 'REJEICAO: O CT-E DE ANULACAO NAO PODE SER CANCELADO' DESCRICAO FROM DUAL UNION  
    SELECT 565 COD, 'REJEICAO: O CT-E SO PODE SER ANULADO PELO EMITENTE' DESCRICAO FROM DUAL UNION  
    SELECT 566 COD, 'REJEICAO: CT-E OBJETO DA ANULACAO NAO PODE TER SIDO ANULADO ANTERIORMENTE' DESCRICAO FROM DUAL UNION  
    SELECT 567 COD, 'REJEICAO: CT-E OBJETO DA ANULACAO NAO PODE TER SIDO SUBSTITUIDO ANTERIORMENTE' DESCRICAO FROM DUAL UNION  
    SELECT 568 COD, 'REJEICAO: CT-E A SER SUBSTITUIDO INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 569 COD, 'REJEICAO: CT-E A SER SUBSTITUIDO DEVE ESTAR COM A SITUACAO AUTORIZADA (NAO PODE ESTAR CANCELADO OU DENEGADO)' DESCRICAO FROM DUAL UNION  
    SELECT 570 COD, 'REJEICAO: CT-E A SER SUBSTITUIDO NAO PODE TER SIDO SUBSTITUIDO ANTERIORMENTE' DESCRICAO FROM DUAL UNION  
    SELECT 571 COD, 'REJEICAO: CT-E A SER SUBSTITUIDO DEVE TER TIPO = 0 (NORMAL) OU 3 (SUBSTITUICAO)' DESCRICAO FROM DUAL UNION  
    SELECT 572 COD, 'REJEICAO: CT-E DE ANULACAO INFORMADO NO GRUPO “TOMADOR NAO E CONTRIBUINTE DO ICMS” INEXISTENTE' DESCRICAO FROM DUAL UNION  
    SELECT 573 COD, 'REJEICAO: CT-E DE ANULACAO INFORMADO NO GRUPO “TOMADOR NAO E CONTRIBUINTE DO ICMS” DEVE TER TIPO=2(ANULACAO)' DESCRICAO FROM DUAL UNION  
    SELECT 574 COD, 'REJEICAO: VEDADO O CANCELAMENTO DE CT-E DO TIPO SUBSTITUTO (TIPO=3)' DESCRICAO FROM DUAL UNION  
    SELECT 575 COD, 'REJEICAO: VEDADO O CANCELAMENTO SE POSSUIR CT-E DE ANULACAO ASSOCIADO' DESCRICAO FROM DUAL UNION  
    SELECT 576 COD, 'REJEICAO: VEDADO O CANCELAMENTO SE POSSUIR CT-E DE SUBSTITUICAO ASSOCIADO' DESCRICAO FROM DUAL UNION  
    SELECT 577 COD, 'REJEICAO: CT-E A SER SUBSTITUIDO NAO PODE TER SIDO ANULADO ANTERIORMENTE' DESCRICAO FROM DUAL UNION  
    SELECT 578 COD, 'REJEICAO: CHAVE DE ACESSO DO CT-E ANULADO DEVE SER IGUAL AO SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 579 COD, 'REJEICAO: VERSAO INFORMADA PARA O MODAL NAO SUPORTADA' DESCRICAO FROM DUAL UNION  
    SELECT 580 COD, 'REJEICAO: FALHA NO SCHEMA XML ESPECIFICO PARA O MODAL' DESCRICAO FROM DUAL UNION  
    SELECT 581 COD, 'REJEICAO: CAMPO VALOR DA CARGA DEVE SER INFORMADO PARA O MODAL' DESCRICAO FROM DUAL UNION  
    SELECT 582 COD, 'REJEICAO: GRUPO TRAFEGO MUTUO DEVE SER INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 583 COD, 'REJEICAO: FERROVIA EMITENTE DEVE SER A DE ORIGEM QUANDO RESPFAT=1' DESCRICAO FROM DUAL UNION  
    SELECT 584 COD, 'REJEICAO: REFERENCIAR O CT-E QUE FOI EMITIDO PELA FERROVIA DE ORIGEM' DESCRICAO FROM DUAL UNION  
    SELECT 585 COD, 'REJEICAO: IE EMITENTE NAO AUTORIZADA A EMITIR CT-E PARA O MODAL INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 586 COD, 'REJEICAO: DATA E JUSTIFICATIVA DE ENTRADA EM CONTINGENCIA NAO DEVEM SER INFORMADAS PARA TIPO DE EMISSAO NORMAL.' DESCRICAO FROM DUAL UNION  
    SELECT 587 COD, 'REJEICAO: DATA E JUSTIFICATIVA DE ENTRADA EM CONTINGENCIA DEVEM SER INFORMADAS' DESCRICAO FROM DUAL UNION  
    SELECT 588 COD, 'REJEICAO: DATA DE ENTRADA EM CONTINGENCIA POSTERIOR A DATA DE EMISSAO.' DESCRICAO FROM DUAL UNION  
    SELECT 589 COD, 'REJEICAO: O LOTE CONTEM CT-E DE MAIS DE UM MODAL' DESCRICAO FROM DUAL UNION  
    SELECT 590 COD, 'REJEICAO: O LOTE CONTEM CT-E DE MAIS DE UMA VERSAO DE MODAL' DESCRICAO FROM DUAL UNION  
    SELECT 591 COD, 'REJEICAO: DIGITO VERIFICADOR INVALIDO NA CHAVE DE ACESSO DE NF-E TRANSPORTADA' DESCRICAO FROM DUAL UNION  
    SELECT 592 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (ANO < 2009 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION  
    SELECT 593 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION  
    SELECT 594 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (CNPJ ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 595 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (MODELO DIFERENTE DE 57 ou 67)' DESCRICAO FROM DUAL UNION  
    SELECT 596 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (NUMERO CT = 0)' DESCRICAO FROM DUAL UNION  
    SELECT 598 COD, 'REJEICAO: USAR SOMENTE O NAMESPACE PADRAO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 599 COD, 'REJEICAO: NAO EH PERMITIDA A PRESENCA DE CARACTERES DE EDICAO NO INICIO/FIM DA MENSAGEM OU ENTRE AS TAGS DA MENSAGEM' DESCRICAO FROM DUAL UNION  
    SELECT 600 COD, 'REJEICAO: CHAVE DE ACESSO DIFERE DA EXISTENTE EM BD' DESCRICAO FROM DUAL UNION  
    SELECT 601 COD, 'REJEICAO: QUANTIDADE DE DOCUMENTOS INFORMADOS NO REMETENTE EXCEDE LIMITE DE 2000' DESCRICAO FROM DUAL UNION  
    SELECT 602 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (ANO < 2005 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION  
    SELECT 603 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION  
    SELECT 604 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (CNPJ ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 605 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (MODELO DIFERENTE DE 55)' DESCRICAO FROM DUAL UNION  
    SELECT 606 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (NUMERO NF = 0)' DESCRICAO FROM DUAL UNION  
    SELECT 608 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E REFERENCIADO INVÁLIDA (UF INVÁLIDA)' DESCRICAO FROM DUAL UNION  
    SELECT 610 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (UF INVÁLIDA)' DESCRICAO FROM DUAL UNION      
    SELECT 617 COD, 'REJEIÇÃO: UF DO TOMADOR NÃO ACEITA ISENTO COM INSCRIÇÃO ESTA' DESCRICAO FROM DUAL UNION  
    SELECT 627 COD, 'REJEICAO: CNPJ DO AUTOR DO EVENTO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 628 COD, 'REJEICAO: ERRO ATRIBUTO ID DO EVENTO NAO CORRESPONDE A CONCATENACAO DOS CAMPOS (“ID” + TPEVENTO + CHCTE + NSEQEVENTO)' DESCRICAO FROM DUAL UNION  
    SELECT 629 COD, 'REJEICAO: O TPEVENTO INFORMADO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 630 COD, 'REJEICAO: FALHA NO SCHEMA XML ESPECIFICO PARA O EVENTO' DESCRICAO FROM DUAL UNION  
    SELECT 631 COD, 'REJEICAO: DUPLICIDADE DE EVENTO' DESCRICAO FROM DUAL UNION  
    SELECT 632 COD, 'REJEICAO: O AUTOR DO EVENTO DIVERGE DO EMISSOR DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 633 COD, 'REJEICAO: O AUTOR DO EVENTO NAO E UM ORGAO AUTORIZADO A GERAR O EVENTO' DESCRICAO FROM DUAL UNION  
    SELECT 634 COD, 'REJEICAO: A DATA DO EVENTO NAO PODE SER MENOR QUE A DATA DE EMISSAO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 635 COD, 'REJEICAO: A DATA DO EVENTO NAO PODE SER MAIOR QUE A DATA DO PROCESSAMENTO' DESCRICAO FROM DUAL UNION  
    SELECT 636 COD, 'REJEICAO: O NUMERO SEQUENCIAL DO EVENTO E MAIOR QUE O PERMITIDO' DESCRICAO FROM DUAL UNION  
    SELECT 637 COD, 'REJEICAO: A DATA DO EVENTO NAO PODE SER MENOR QUE A DATA DE AUTORIZACAO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 638 COD, 'REJEICAO: JA EXISTE CT-E AUTORIZADO COM ESTA NUMERACAO' DESCRICAO FROM DUAL UNION  
    SELECT 639 COD, 'REJEICAO: EXISTE EPEC EMITIDO HA MAIS DE 7 DIAS (168H) SEM A EMISSAO DO CT-E NO AMBIENTE NORMAL DE AUTORIZACAO' DESCRICAO FROM DUAL UNION  
    SELECT 640 COD, 'REJEICAO: TIPO DE EMISSAO DO CT-E DIFERE DE EPEC COM EPEC AUTORIZADO NA SVC-XX PARA ESTE DOCUMENTO.' DESCRICAO FROM DUAL UNION  
    SELECT 641 COD, 'REJEICAO: O EVENTO PREVIO DESTE CT-E NAO FOI AUTORIZADO NA SVC.' DESCRICAO FROM DUAL UNION  
    SELECT 642 COD, 'REJEICAO: OS VALORES DE ICMS, PRESTACAO E TOTAL DA CARGA DO CT-E DEVEM SER IGUAIS AOS INFORMADOS NO EPEC.' DESCRICAO FROM DUAL UNION  
    SELECT 643 COD, 'REJEICAO: AS INFORMACOES DO TOMADOR DE SERVICO DO CT-E DEVEM SER IGUAIS AS INFORMADAS NO EPEC' DESCRICAO FROM DUAL UNION  
    SELECT 644 COD, 'REJEICAO: A INFORMACAO DO MODAL DO CT-E DEVE SER IGUAL A INFORMADA NO EPEC' DESCRICAO FROM DUAL UNION  
    SELECT 645 COD, 'REJEICAO: A UF DE INICIO E FIM DE PRESTACAO DO CT-E DEVEM SER IGUAIS AS INFORMADAS NO EPEC.' DESCRICAO FROM DUAL UNION  
    SELECT 646 COD, 'REJEICAO: CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO COM RAZAO SOCIAL DO REMETENTE DIFERENTE DE CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL' DESCRICAO FROM DUAL UNION  
    SELECT 647 COD, 'REJEICAO: CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO COM RAZAO SOCIAL DO EXPEDIDOR DIFERENTE DE CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL' DESCRICAO FROM DUAL UNION  
    SELECT 648 COD, 'REJEICAO: CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO COM RAZAO SOCIAL DO RECEBEDOR DIFERENTE DE CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL' DESCRICAO FROM DUAL UNION  
    SELECT 649 COD, 'REJEICAO: CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO COM RAZAO SOCIAL DO DESTINATARIO DIFERENTE DE CT-E EMITIDO EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL' DESCRICAO FROM DUAL UNION  
    SELECT 650 COD, 'REJEICAO: VALOR TOTAL DO SERVICO SUPERIOR AO LIMITE PERMITIDO (R$ 9.999.999,99)' DESCRICAO FROM DUAL UNION  
    SELECT 651 COD, 'REJEICAO: REFERENCIAR O CT-E MULTIMODAL QUE FOI EMITIDO PELO OTM' DESCRICAO FROM DUAL UNION  
    SELECT 652 COD, 'REJEICAO: NF-E NAO PODE ESTAR CANCELADA OU DENEGADA' DESCRICAO FROM DUAL UNION  
    SELECT 653 COD, 'REJEICAO: TIPO DE EVENTO NAO E PERMITIDO EM AMBIENTE DE AUTORIZACAO NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 654 COD, 'REJEICAO: TIPO DE EVENTO NAO E PERMITIDO EM AMBIENTE DE AUTORIZACAO SVC' DESCRICAO FROM DUAL UNION  
    SELECT 655 COD, 'REJEICAO: CT-E COMPLEMENTADO DEVE ESTAR COM A SITUACAO AUTORIZADA (NAO PODE ESTAR CANCELADO OU DENEGADO)' DESCRICAO FROM DUAL UNION  
    SELECT 656 COD, 'REJEICAO: CT-E COMPLEMENTADO NAO PODE TER SIDO ANULADO' DESCRICAO FROM DUAL UNION  
    SELECT 657 COD, 'REJEICAO: CT-E COMPLEMENTADO NAO PODE TER SIDO SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 658 COD, 'REJEICAO: CT-E OBJETO DA ANULACAO NAO PODE TER SIDO COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 659 COD, 'REJEICAO: CT-E SUBSTITUIDO NAO PODE TER SIDO COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 660 COD, 'REJEICAO: VEDADO O CANCELAMENTO SE POSSUIR CT-E COMPLEMENTAR ASSOCIADO' DESCRICAO FROM DUAL UNION  
    SELECT 661 COD, 'REJEICAO: NF-E INEXISTENTE NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 662 COD, 'REJEICAO: NF-E COM DIFERENCA DE CHAVE DE ACESSO' DESCRICAO FROM DUAL UNION  
    SELECT 663 COD, 'REJEICAO: CT-E AUTORIZADO HA MAIS DE 30 DIAS' DESCRICAO FROM DUAL UNION  
    SELECT 664 COD, 'REJEICAO: EVENTO NAO PERMITIDO PARA CT-E SUBSTITUIDO' DESCRICAO FROM DUAL UNION  
    SELECT 665 COD, 'REJEICAO: AS INFORMACOES DO SEGURO DA CARGA DEVEM SER PREENCHIDAS PARA O MODAL RODOVIARIO' DESCRICAO FROM DUAL UNION  
    SELECT 666 COD, 'REJEICAO: O RESPONSAVEL PELO SEGURO DA CARGA INDICADO NAO FOI RELACIONADO NO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 667 COD, 'REJEICAO: CNPJ DO TOMADOR DEVE SER IGUAL AO CNPJ DO EMITENTE DO CT-E MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 668 COD, 'REJEICAO: CPF DO FUNCIONARIO DO REGISTRO DE PASSAGEM INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 669 COD, 'REJEICAO: SEGUNDO CODIGO DE BARRAS DEVE SER INFORMADO PARA CT-E EMITIDO EM CONTINGENCIA FS-DA' DESCRICAO FROM DUAL UNION  
    SELECT 670 COD, 'REJEICAO: SERIE UTILIZADA NAO PERMITIDA NO WEBSERVICE' DESCRICAO FROM DUAL UNION  
    SELECT 671 COD, 'REJEICAO: CT-E REFERENCIADO NO CT-E COMPLEMENTAR COM DIFERENCA DE CHAVE DE ACESSO [chCte: 99999999999999999999999999999999999999999999][nRec:999999999999999].' DESCRICAO FROM DUAL UNION  
    SELECT 672 COD, 'REJEICAO: CT-E DE ANULACAO COM DIFERENCA DE CHAVE DE ACESSO [chCte: 99999999999999999999999999999999999999999999][nRec:999999999999999].' DESCRICAO FROM DUAL UNION  
    SELECT 673 COD, 'REJEICAO: CT-E SUBSTITUIDO COM DIFERENCA DE CHAVE DE ACESSO [chCte: 99999999999999999999999999999999999999999999][nRec]' DESCRICAO FROM DUAL UNION  
    SELECT 674 COD, 'REJEICAO: CT-E OBJETO DE ANULACAO COM DIFERENCA DE CHAVE DE ACESSO [CHCTE: 99999999999999999999999999999999999999999999][nRec]' DESCRICAO FROM DUAL UNION  
    SELECT 675 COD, 'REJEICAO: VALOR DO IMPOSTO NAO CORRESPONDE A BASE DE CALCULO X ALIQUOTA' DESCRICAO FROM DUAL UNION  
    SELECT 676 COD, 'REJEICAO: CFOP INFORMADO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 677 COD, 'REJEICAO: ORGAO DE RECEPCAO DO EVENTO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 678 COD, 'REJEICAO: CONSUMO INDEVIDO [DESCRICAO: XXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO FROM DUAL UNION  
    SELECT 679 COD, 'REJEICAO: O MODAL DO CT-E DEVE SER MULTIMODAL PARA EVENTO REGISTROS DO MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 680 COD, 'REJEICAO: TIPO DE EMISSAO DIFERENTE DE EPEC' DESCRICAO FROM DUAL UNION  
    SELECT 681 COD, 'REJEICAO: INFORMACAO NAO PODE SER ALTERADA POR CARTA DE CORRECAO' DESCRICAO FROM DUAL UNION  
    SELECT 682 COD, 'REJEICAO: JA EXISTE PEDIDO DE INUTILIZACAO COM A MESMA FAIXA DE INUTILIZACAO' DESCRICAO FROM DUAL UNION  
    SELECT 683 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (ANO < 2012 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION  
    SELECT 684 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION  
    SELECT 685 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (CNPJ ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION  
    SELECT 686 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (MODELO DIFERENTE DE 58)' DESCRICAO FROM DUAL UNION  
    SELECT 687 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (NUMERO MDF = 0)' DESCRICAO FROM DUAL UNION  
    SELECT 688 COD, 'REJEICAO: GRUPO DE INFORMACOES DO VEICULO DEVE SER INFORMADO PARA CARGA LOTACAO' DESCRICAO FROM DUAL UNION  
    SELECT 689 COD, 'REJEICAO: CT-E DE ANULACAO NAO E PERMITIDO PARA CT-E CUJO TOMADOR E CONTRIBUINTE DE ICMS.' DESCRICAO FROM DUAL UNION  
    SELECT 690 COD, 'REJEICAO: CT-E MULTIMODAL REFERENCIADO INEXISTENTE NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION  
    SELECT 691 COD, 'REJEICAO: CT-E MULTIMODAL REFERENCIADO EXISTE COM DIFERENCA DE CHAVE DE ACESSO' DESCRICAO FROM DUAL UNION  
    SELECT 692 COD, 'REJEICAO: CT-E MULTIMODAL REFERENCIADO NAO PODE ESTAR CANCELADO OU DENEGADO' DESCRICAO FROM DUAL UNION  
    SELECT 693 COD, 'REJEICAO: GRUPO DOCUMENTOS TRANSPORTADOS DEVE SER INFORMADO PARA TIPO DE SERVICO DIFERENTE DE REDESPACHO INTERMEDIARIO E SERVICO VINCULADO A MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 694 COD, 'REJEICAO: GRUPO DOCUMENTOS TRANSPORTADOS NAO PODE SER INFORMADO PARA TIPO DE SERVICO REDESPACHO INTERMEDIARIO E SERVICO VINCULADO A MULTIMODAL' DESCRICAO FROM DUAL UNION  
    SELECT 695 COD, 'REJEICAO: CT-E COM EMISSAO ANTERIOR AO EVENTO PREVIO (EPEC)' DESCRICAO FROM DUAL UNION  
    SELECT 716 COD, 'REJEIÇÃO: IE DO REMETENTE NÃO INFORMADA ' DESCRICAO FROM DUAL UNION  
    SELECT 717 COD, 'REJEIÇÃO: IE DO EXPEDIDOR NÃO INFORMADA ' DESCRICAO FROM DUAL UNION  
    SELECT 718 COD, 'REJEIÇÃO: IE DO RECEBEDOR NÃO INFORMADA ' DESCRICAO FROM DUAL UNION  
    SELECT 719 COD, 'REJEIÇÃO: IE DO TOMADOR NÃO INFORMADA ' DESCRICAO FROM DUAL UNION  
    SELECT 721 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (MODELO DIFERENTE DE 67) ' DESCRICAO FROM DUAL UNION  
    SELECT 722 COD, 'REJEIÇÃO: TOMADOR DO SERVIÇO DEVE SER REMETENTE OU DESTINATÁRIO PARA CT-E GLOBALIZADO ' DESCRICAO FROM DUAL UNION  
    SELECT 723 COD, 'REJEIÇÃO: CT-E GLOBALIZADO DEVE CONTER APENAS NF-E NOS DOCUMENTOS TRANSPORTADOS' DESCRICAO FROM DUAL UNION  
    SELECT 724 COD, 'REJEIÇÃO: CT-E GLOBALIZADO DEVE CONTER NF-E COM CNPJ DIFERENTES PARA MÚLTIPLOS REMETENTES ' DESCRICAO FROM DUAL UNION  
    SELECT 725 COD, 'REJEIÇÃO: RAZÃO SOCIAL DO REMETENTE DO CT-E GLOBALIZADO INVÁLIDO' DESCRICAO FROM DUAL UNION  
    SELECT 726 COD, 'REJEIÇÃO: RAZÃO SOCIAL DO DESTINATÁRIO DO CT-E GLOBALIZADO INVÁLIDO ' DESCRICAO FROM DUAL UNION  
    SELECT 727 COD, 'REJEIÇÃO: CNPJ DO REMETENTE DO CT-E GLOBALIZADO DEVE SER O MESMO DO EMITENTE DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 728 COD, 'REJEIÇÃO: CNPJ DO DESTINATÁRIO DO CT-E GLOBALIZADO DEVE SER O MESMO DO EMITENTE DO CT-E ' DESCRICAO FROM DUAL UNION  
    SELECT 729 COD, 'REJEIÇÃO: NF-E DE MÚLTIPLOS EMITENTES INFORMADAS NOS DOCUMENTOS TRANSPORTADOS SEM INDICADOR DE CT-E GLOBALIZADO ' DESCRICAO FROM DUAL UNION  
    SELECT 730 COD, 'REJEIÇÃO: RAZÃO SOCIAL INVÁLIDA PARA REMETENTE/DESTINATÁRIO SEM INDICADOR DE CT-E GLOBALIZADO ' DESCRICAO FROM DUAL UNION  
    SELECT 732 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (MODELO DIFERENTE DE 57) ' DESCRICAO FROM DUAL UNION  
    SELECT 733 COD, 'REJEIÇÃO: CNPJ DO DOCUMENTO ANTERIOR DEVE SER O MESMO INDICADO NO GRUPO EMIDOCANT ' DESCRICAO FROM DUAL UNION  
    SELECT 734 COD, 'REJEIÇÃO: AS NF-E TRANSPORTADAS DO CT-E SUBSTITUTO DEVEM SER IGUAIS ÀS INFORMADAS NO CT-E SUBSTITUÍDO' DESCRICAO FROM DUAL UNION  
    SELECT 735 COD, 'REJEIÇÃO: CT-E DE ANULAÇÃO PARA CT-E COM TOMADOR CONTRIBUINTE EXIGE EVENTO DE PRESTAÇÃO DE SERVIÇO EM DESACORDO ' DESCRICAO FROM DUAL UNION  
    SELECT 736 COD, 'REJEIÇÃO: EXISTE CT-E DE ANULAÇÃO AUTORIZADO HÁ MAIS DE 15 DIAS SEM A AUTORIZAÇÃO DO CT-E SUBSTITUTO  ' DESCRICAO FROM DUAL UNION  
    SELECT 737 COD, 'REJEIÇÃO: O CT-E GLOBALIZADO DEVE CONTER PELO MENOS 5 NF-E PARA O MESMO EMITENTE' DESCRICAO FROM DUAL UNION  
    SELECT 739 COD, 'REJEIÇÃO: O CT-E SUBSTITUÍDO DEVE POSSUIR EVENTO DE PRESTAÇÃO DO SERVIÇO EM DESACORDO' DESCRICAO FROM DUAL UNION  
    SELECT 740 COD, 'REJEIÇÃO: O CNPJ BASE DO TOMADOR DO CT-E SUBSTITUTO DEVE ESTAR RELACIONADO NOS PAPÉIS DO CT-E SUBSTITUÍDO PARA A ALTERAÇÃO DE TOMADOR' DESCRICAO FROM DUAL UNION  
    SELECT 741 COD, 'REJEIÇÃO: A UF DO CT-E SUBSTITUTO DEVE SER A MESMA DO TOMADOR DO CT-E SUBSTITUÍDO PARA ALTERAÇÃO DE TOMADOR' DESCRICAO FROM DUAL UNION  
    SELECT 742 COD, 'REJEIÇÃO: TOMADOR DO CT-E SUBSTITUTO IGUAL AO INFORMADO NO CT-E SUBSTITUÍDO PARA OPERAÇÃO DE ALTERAÇÃO DE TOMADOR' DESCRICAO FROM DUAL UNION  
    SELECT 743 COD, 'REJEIÇÃO: CT-E GLOBALIZADO NÃO PODE SER UTILIZADO PARA OPERAÇÃO INTERESTA ' DESCRICAO FROM DUAL UNION  
    SELECT 744 COD, 'REJEIÇÃO: CT-E GLOBALIZADO PARA TOMADOR REMETENTE COM NF-E DE EMITENTES DIFERENTES ' DESCRICAO FROM DUAL UNION  
    SELECT 745 COD, 'REJEIÇÃO: CNPJ BASE DO TOMADOR DEVE SER IGUAL AO CNPJ BASE INDICADO NO GRUPO EMIDOCANT ' DESCRICAO FROM DUAL UNION  
    SELECT 746 COD, 'REJEIÇÃO: TIPO DE SERVIÇO INVÁLIDO PARA O TOMADOR INFORMADO ' DESCRICAO FROM DUAL UNION  
    SELECT 747 COD, 'REJEIÇÃO: DOCUMENTOS ANTERIORES INFORMADOS PARA TIPO DE SERVIÇO NORMAL ' DESCRICAO FROM DUAL UNION  
    SELECT 748 COD, 'REJEIÇÃO: CT-E REFERENCIADO EM DOCUMENTOS ANTERIORES INEXISTENTE NA BASE DE DADOS DA SEFAZ ' DESCRICAO FROM DUAL UNION  
    SELECT 749 COD, 'REJEIÇÃO: CT-E REFERENCIADO EM DOCUMENTOS ANTERIORES EXISTE COM DIFERENÇA DE CHAVE DE ACESSO' DESCRICAO FROM DUAL UNION  
    SELECT 750 COD, 'REJEIÇÃO: CT-E REFERENCIADO EM DOCUMENTOS ANTERIORES NÃO PODE ESTAR CANCELADO OU DENEGADO' DESCRICAO FROM DUAL UNION  
    SELECT 755 COD, 'REJEIÇÃO: AUTOR DO EVENTO PRESTAÇÃO DO SERVIÇO EM DESACORDO DEVE SER O TOMADOR DO SERVIÇO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 756 COD, 'REJEIÇÃO: DATA DE EMISSÃO DO CT-E DEVE SER IGUAL À DATA DE EMISSÃO DA EPEC ' DESCRICAO FROM DUAL UNION  
    SELECT 786 COD, 'REJEIÇÃO: GRUPO DE INFORMAÇÕES DA PARTILHA COM A UF DE FIM DA PRESTAÇÃO DEVE ESTAR PREENCHIDO ' DESCRICAO FROM DUAL UNION  
    SELECT 799 COD, 'REJEIÇÃO: IDENTIFICAÇÃO DO TOMADOR UTILIZADA EM OUTRO PAPEL NO CT-E (CNPJ/CPF OU IE) ' DESCRICAO FROM DUAL UNION  
    SELECT 800 COD, 'REJEIÇÃO: CNPJ/CPF DO REMETENTE DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 801 COD, 'REJEIÇÃO: CNPJ/CPF DO DESTINATÁRIO DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 802 COD, 'REJEIÇÃO: O CNPJ/CPF DO EXPEDIDOR DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 803 COD, 'REJEIÇÃO: O CNPJ/CPF DO RECEBEDOR DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 804 COD, 'REJEIÇÃO: O CNPJ/CPF DO TOMADOR DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 805 COD, 'REJEIÇÃO: A IE DO EMITENTE DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 806 COD, 'REJEIÇÃO: A IE DO REMETENTE DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 807 COD, 'REJEIÇÃO: A IE DO DESTINATÁRIO DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 808 COD, 'REJEIÇÃO: A IE DO EXPEDIDOR DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 809 COD, 'REJEIÇÃO: A IE DO RECEBEDOR DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 810 COD, 'REJEIÇÃO: A IE DO TOMADOR DO CT-E COMPLEMENTAR DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 811 COD, 'REJEIÇÃO: A UF DE INÍCIO DA PRESTAÇÃO DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO ' DESCRICAO FROM DUAL UNION  
    SELECT 812 COD, 'REJEIÇÃO: A UF DE FIM DA PRESTAÇÃO DEVE SER IGUAL AO INFORMADO NO CT-E COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 813 COD, 'REJEIÇÃO: TIPO DE DOCUMENTO INVÁLIDO PARA OPERAÇÃO INTERESTA ' DESCRICAO FROM DUAL UNION  
    SELECT 832 COD, 'REJEIÇÃO: MUNICÍPIO DE INÍCIO E FIM DE PRESTAÇÃO DO CT-E DE SUBCONTRATAÇÃO DEVEM SER IGUAIS AO CT-E SUBCONTRATADO' DESCRICAO FROM DUAL UNION  
    SELECT 833 COD, 'REJEIÇÃO: O TIPO DE SERVIÇO DO CT-E DE ANULAÇÃO DEVE SER IGUAL AO CT-E ORIGINAL' DESCRICAO FROM DUAL UNION  
    SELECT 834 COD, 'REJEIÇÃO: O TIPO DE SERVIÇO DO CT-E DE SUBSTITUIÇÃO DEVE SER IGUAL AO CT-E SUBSTITUÍDO' DESCRICAO FROM DUAL UNION  
    SELECT 835 COD, 'REJEIÇÃO: O TIPO DE SERVIÇO DO CT-E COMPLEMENTAR DEVE SER IGUAL AO CT-E COMPLEMENTADO' DESCRICAO FROM DUAL UNION  
    SELECT 836 COD, 'REJEICAO: CNPJ DO DESENVOLVEDOR DO SISTEMA INVALIDO (ZERADO OU DIGITO INVALIDO) ' DESCRICAO FROM DUAL UNION  
    SELECT 837 COD, 'REJEICAO: DATA E HORA DA VIAGEM DEVE SER INFORMADA PARA TIPO DE FRETAMENTO EVENTUAL' DESCRICAO FROM DUAL UNION  
    SELECT 838 COD, 'REJEICAO: DATA E HORA DA VIAGEM DEVE SER SUPERIOR A DATA DE EMISSAO DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 839 COD, 'REJEICAO: NUMERO DO REGISTRO ESTA E OBRIGATORIO PARA TRANSPORTE DE PESSOAS RODIVIARIO NAS OPERACOES INTERNAS' DESCRICAO FROM DUAL UNION  
    SELECT 840 COD, 'REJEICAO: TERMO DE AUTORIZAÇAO DE FRETAMENTO E OBRIGATORIO PARA TRANSPORTE DE PESSOAS RODIVIARIO INTERESTA' DESCRICAO FROM DUAL UNION  
    SELECT 841 COD, 'REJEIÇÃO: INFORMAÇÃO DO FRETAMENTO É OBRIGATÓRIA PARA TRANSPORTE DE PESSOAS' DESCRICAO FROM DUAL UNION  
    SELECT 842 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E DA FERROVIA DE ORIGEM INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 843 COD, 'REJEIÇÃO: CHAVE DE ACESSO DA NF-E TRANSPORTADA INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 844 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E ANTERIOR INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 845 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E MULTIMODAL INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 846 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E OBJETO DA ANULAÇÃO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 847 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E SUBSTITUÍDO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 848 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E DE ANULAÇÃO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 849 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E COMPLEMENTADO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 850 COD, 'REJEIÇÃO: O QR CODE DO CT-E DEVE SER INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 851 COD, 'REJEIÇÃO: ENDEREÇO DO SITE DA UF DA CONSULTA VIA QR CODE DIVERGE DO PREVISTO' DESCRICAO FROM DUAL UNION  
    SELECT 852 COD, 'REJEIÇÃO: PARÂMETRO CHAVE DE ACESSO DO QR CODE DIVERGENTE DO CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 853 COD, 'REJEIÇÃO: PARÂMETRO SIGN NÃO INFORMADO NO QR CODE PARA EMISSÃO EM CONTINGÊNCIA' DESCRICAO FROM DUAL UNION  
    SELECT 854 COD, 'REJEIÇÃO: PARÂMETRO SIGN NÃO DEVE SER INFORMADO NO QR CODE PARA EMISSÃO NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 855 COD, 'REJEIÇÃO: ASSINATURA DO QR-CODE DIFERE DO CALCULADO' DESCRICAO FROM DUAL UNION  
    SELECT 856 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E REFERENCIADO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 857 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E OS OBJETO DA ANULAÇÃO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 858 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E OS SUBSTITUÍDO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 859 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E OS COMPLEMENTADO INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 860 COD, 'REJEIÇÃO: CHAVE DE ACESSO DA NF-E INDICADA NO COMPROVANTE DE ENTREGA INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 861 COD, 'REJEIÇÃO: NF-E EM DUPLICIDADE NO EVENTO COMPROVANTE DE ENTREGA' DESCRICAO FROM DUAL UNION  
    SELECT 862 COD, 'REJEIÇÃO: VEDADO O CANCELAMENTO QUANDO HOUVER EVENTO DE COMPROVANTE DE ENTREGA ASSOCIADO' DESCRICAO FROM DUAL UNION  
    SELECT 863 COD, 'REJEIÇÃO: NF-E JÁ POSSUI COMPROVANTE DE ENTREGA PARA ESTE CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 864 COD, 'REJEIÇÃO: NF-E NÃO POSSUI RELAÇÃO COM ESTE CT-E' DESCRICAO FROM DUAL UNION  
    SELECT 865 COD, 'REJEIÇÃO: COMPROVANTE DE ENTREGA DEVE RELACIONAR NF-E PARA CT-E DE TIPO DE SERVIÇO NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 866 COD, 'REJEIÇÃO: PROTOCOLO DO EVENTO A SER CANCELADO NÃO EXISTE, NÃO ESTÁ ASSOCIADO AO CT-E OU JÁ ESTÁ CANCELADO' DESCRICAO FROM DUAL UNION  
    SELECT 869 COD, 'REJEIÇÃO: EVENTO NÃO PERMITIDO PARA CT-E COMPLEMENTAR OU ANULAÇÃO' DESCRICAO FROM DUAL UNION  
    SELECT 870 COD, 'REJEIÇÃO: NÃO É PERMITIDO MAIS DE UM COMPROVANTE DE ENTREGA PARA CT-E (EXCETO CT-E GLOBALIZADO)' DESCRICAO FROM DUAL UNION  
    SELECT 871 COD, 'REJEIÇÃO: COMPROVANTE DE ENTREGA NÃO PODE INFORMAR NF-E PARA CT-E DE TIPO DE SERVIÇO DIFERENTE DE NORMAL' DESCRICAO FROM DUAL UNION  
    SELECT 872 COD, 'REJEIÇÃO: DATA E HORA DA ENTREGA INVÁLIDA' DESCRICAO FROM DUAL UNION  
    SELECT 873 COD, 'REJEIÇÃO: DATA E HORA DO HASH DO COMPROVANTE DE ENTREGA INVÁLIDA ' DESCRICAO FROM DUAL UNION  
    SELECT 906 COD, 'REJEIÇÃO: CFOP INVÁLIDO, NÃO INFORMAR 5932 OU 6932 PARA OPERAÇÕES INTERNAS' DESCRICAO FROM DUAL UNION  
    SELECT 908 COD, 'REJEIÇÃO: CFOP INVÁLIDO, NÃO INFORMAR 5932 OU 6932' DESCRICAO FROM DUAL UNION 
    SELECT 998 COD, 'REJEIÇÃO: SERVIÇO DESATIVADO' DESCRICAO FROM DUAL UNION
    SELECT 999 COD, 'REJEICAO: ERRO NAO CATALOGADO (INFORMAR A MENSAGEM DE ERRO CAPTURADO NO TRATAMENTO DA EXCECAO)' DESCRICAO FROM DUAL UNION      
    SELECT 1000 COD, 'CTE REPROVADO PELO VALIDADOR LOCAL' DESCRICAO FROM DUAL UNION  
    SELECT 1003 COD, 'CTE REPROVADA LOCAL AO MONTAR O LOTE' DESCRICAO FROM DUAL UNION  
    SELECT 1004 COD, 'CTE REPROVADA LOCAL - NÃO FOI ENCONTRADA A SÉRIE PARA UF DE INICIO DA PRESTAÇÃO DE SERVIÇO. VERIFICAR CADASTRO ROTINA 535' DESCRICAO FROM DUAL UNION  
    SELECT 1005 COD, 'REENVIO AUTOMATICO EXCEDIDO' DESCRICAO FROM DUAL UNION  
    SELECT 2000 COD, 'TIPO DO TOMADOR INFORMADO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 3000 COD, 'SIGLA UF DE ONDE O CTE ESTA SENDO EMITIDO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3001 COD, 'NATUREZA DA OPERACAO NAO INFORMADA OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 3002 COD, 'FORMA DE PAGAMENTO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3003 COD, 'CFOP E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3004 COD, 'FORMA DE PAGAMENTO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3005 COD, 'SERIE INFORMADA E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 3006 COD, 'DATA E HORA DE EMISSAO INFORMADA E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3007 COD, 'DACTE E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 3008 COD, 'TIPO DE EMISSAO NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3009 COD, 'TIPO DE AMBIENTE NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3010 COD, 'TIPO DA FINALIDADE DA EMISSAO NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3011 COD, 'CHAVE DO CTE REFERENCIADO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3012 COD, 'SIGLA DE UF DA CIDADE IBGE DE ONDE O CTE ESTA SENDO EMITIDO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3013 COD, 'CODIGO DA CIDADE IBGE DE ONDE O CTE ESTA SENDO EMITIDO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3014 COD, 'CIDADE IBGE DE ONDE O CTE ESTA SENDO EMITIDO NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 3015 COD, 'CODIGO IBGE DA CIDADE DE ONDE O CTE ESTA SENDO EMITIDO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3016 COD, 'NOME DO MUNICIPIO DE ONDE O CTE ESTA SENDO EMITIDO NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 3017 COD, 'TIPO DE MODAL NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3018 COD, 'TIPO DE SERVICO NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3019 COD, 'SIGLA UF DO INICIO DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3020 COD, 'SIGLA UF DO FIM DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3021 COD, 'SIGLA DE UF DA CIDADE IBGE DO INICIO DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3022 COD, 'CODIGO DA CIDADE IBGE DO INICIO DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3023 COD, 'CIDADE IBGE DO INICIO DA PRESTACAO NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 3024 COD, 'CODIGO IBGE DA CIDADE DO INICIO DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3025 COD, 'NOME DO MUNICIPIO DO INICIO DA PRESTACAO NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 3026 COD, 'SIGLA DE UF DA CIDADE IBGE DO FIM DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3027 COD, 'CODIGO DA CIDADE IBGE DO FIM DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3028 COD, 'CIDADE IBGE DO FIM DA PRESTACAO NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 3029 COD, 'CODIGO IBGE DA CIDADE DO FIM DA PRESTACAO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 3030 COD, 'NOME DO MUNICIPIO DO FIM DA PRESTACAO NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 3031 COD, 'NAO INFORMADO SE O RECEBEDOR RETIRA MERCADORIA' DESCRICAO FROM DUAL UNION  
    SELECT 3032 COD, 'DETALHES DA RETIRA MENOR QUE 2 CARACTERES OU MAIOR QUE 160 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 3033 COD, 'NUMERO DE CT IGUAL A ZERO' DESCRICAO FROM DUAL UNION  
    SELECT 3034 COD, 'DATA/HORA DE CONTINGENCIA INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 3035 COD, 'QUANTIDADE MAXIMA DE CARACTERES PERMITIDOS PARA JUSTIFICATIVA DA CONTINGENCIA E DE 256 E A MINIMA E 15' DESCRICAO FROM DUAL UNION  
    SELECT 4000 COD, 'TIPO DE PESSOA DO TOMADOR NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4001 COD, 'CNPJ DO TOMADOR E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4002 COD, 'CPF DO TOMADOR E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4003 COD, 'INSCRICAO ESTA DO TOMADOR E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4004 COD, 'RAZAO SOCIAL DO TOMADOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4005 COD, 'NOME FANTASIA DO TOMADOR E MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4006 COD, 'LOGRADOURO DO TOMADOR NAO INFORMADO OU MAIOR QUE 255 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4007 COD, 'NUMERO DO ENDERECO DO TOMADOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4008 COD, 'COMPLEMENTO DO ENDERECO DO TOMADOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4009 COD, 'BAIRRO DO ENDERECO DO TOMADOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4010 COD, 'SIGLA DA UF DO TOMADOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 4011 COD, 'NOME DO MUNICIPIO DO TOMADOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4012 COD, 'SIGLA DE UF DA CIDADE IBGE DO TOMADOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4013 COD, 'CODIGO DA CIDADE IBGE DO TOMADOR  E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4014 COD, 'CIDADE IBGE DO TOMADOR NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 4015 COD, 'CODIGO IBGE DA CIDADE DO TOMADOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4016 COD, 'CEP DO TOMADOR NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4017 COD, 'CODIGO DO PAIS DO TOMADOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 4018 COD, 'NOME DO PAIS DO TOMADOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 4020 COD, 'CERTIFICADO DIGITAL NAO INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 5000 COD, 'CARACTERISITICA ADICIONAL DE TRANSPORTE NAO INFORMADA OU TAMANHO MAIOR QUE 15 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 5001 COD, 'CARACTERISITICA ADICIONAL DE SERVICO NAO INFORMADA OU TAMANHO MAIOR QUE 30 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 5002 COD, 'FUNCIONARIO EMISSOR NAO INFORMADO OU TAMANHO MAIOR QUE 20 CARACTES.' DESCRICAO FROM DUAL UNION  
    SELECT 5003 COD, 'TIPO PREVISAO DE ENTREGA NAO INFORMADA OU INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5004 COD, 'DATA HORA INICIAL INFORMADA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5005 COD, 'DATA HORA INICIAL INFORMADA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5006 COD, 'DATA HORA FINAL INFORMADA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5007 COD, 'TIPO DE HORARIO INFORMADO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 5009 COD, 'DATA HORA INICIAL INFORMADA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5010 COD, 'DATA HORA INICIAL INFORMADA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5011 COD, 'DATA HORA FINAL INFORMADA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 5012 COD, 'NOME DO MUNICIPIO DE ORIGEM NAO INFORMADO OU TAMANHO MAIOR QUE 40 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 5013 COD, 'NOME DO MUNICIPIO DE DESTINO NAO INFORMADO OU TAMANHO MAIOR QUE 40 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 5014 COD, 'OBSERVACAO NAO INFORMADA OU TAMANHO MAIOR QUE 2000 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 5015 COD, 'OBSERVACÕES DO CONTRIBUINTE MAIOR QUE 10 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 5016 COD, 'OBSERVACÕES DO FISCO MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 5017 COD, 'CNPJ DO PROPRIETARIO DO VEICULO NAO FOI INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 5018 COD, 'RNTC DO PROPRIETARIO DO VEICULO NAO FOI INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 5019 COD, 'NOME DO PROPRIETARIO DO VEICULO NAO FOI INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 5020 COD, 'IE DO PROPRIETARIO DO VEICULO NAO FOI INFORMADA' DESCRICAO FROM DUAL UNION  
    SELECT 5021 COD, 'UF DO PROPRIETARIO DO VEICULO NAO FOI INFORMADA' DESCRICAO FROM DUAL UNION  
    SELECT 5022 COD, 'NAO FORAM ENCONTRADOS DOCUMENTOS FISCAIS PARA ESTE CTE' DESCRICAO FROM DUAL UNION  
    SELECT 5050 COD, 'CODIGO DE ORIGEM DO FLUXO DA CARGA MAIOR QUE 15 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 5051 COD, 'CODIGO DE DESTINO DO FLUXO DA CARGA MAIOR QUE 15 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 5052 COD, 'CODIGO DE ROTA DO FLUXO DA CARGA MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 5053 COD, 'CODIGO DE PASSAGEM DO FLUXO DA CARGA MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 5150 COD, 'IDENTIFICACAO DO CAMPO OBSERVACÕES MENOR QUE 2 CARACTERES OU 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 5151 COD, 'CONTEUDO DO CAMPO OBSERVACÕES MENOR QUE 2 CARACTERES OU 160 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6001 COD, 'CNPJ DO EMITENTE E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 6003 COD, 'INSCRICAO ESTA DO EMITENTE E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 6004 COD, 'RAZAO SOCIAL MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6005 COD, 'NOME FANTASIA DO EMINTENTE NÃO INFORMADA OU MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6006 COD, 'LOGRADOURO DO EMITENTE NAO INFORMADO OU MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6007 COD, 'NUMERO DO ENDERECO DO EMITENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6008 COD, 'COMPLEMENTO DO ENDERECO DO EMITENTE INFORMADO E MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6009 COD, 'BAIRRO DO ENDERECO DO EMITENTE NAO INFORMADO OU E MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6010 COD, 'SIGLA DA UF DO EMITENTE E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 6011 COD, 'NOME DO MUNICIPIO DO EMITENTE MENOR QUE 2 CARACTERES OU MAIOR 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6012 COD, 'SIGLA DA UF DA CIDADE IBGE DO EMITENTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 6013 COD, 'CODIGO DA CIDADE IBGE DO EMITENTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 6014 COD, 'CIDADE IBGE DO EMITENTE NAO PERTENCE AO ESTADO.' DESCRICAO FROM DUAL UNION  
    SELECT 6015 COD, 'CODIGO IBGE DA CIDADE DO EMITENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 6016 COD, 'CEP DO EMITENTE NAO INFORMADO OU INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 6017 COD, 'CODIGO DO PAIS DO EMITENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 6018 COD, 'NOME DO PAIS DO EMITENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 6019 COD, 'TELEFONE DO EMITENTE MENOR QUE 7 CARACTERES OU MAIOR QUE 12 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7000 COD, 'TIPO DE PESSOA DO REMETENTE NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7001 COD, 'CNPJ DO REMETENTE E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7002 COD, 'CPF DO REMETENTE E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7003 COD, 'INSCRICAO ESTA DO REMETENTE E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7004 COD, 'RAZAO SOCIAL DO REMETENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7005 COD, 'NOME FANTASIA DO REMETENTE E MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7006 COD, 'LOGRADOURO DO REMETENTE NAO INFORMADO OU MAIOR QUE 255 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7007 COD, 'NUMERO DO ENDERECO DO REMETENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7008 COD, 'COMPLEMENTO DO ENDERECO DO REMETENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7009 COD, 'BAIRRO DO ENDERECO DO REMETENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7010 COD, 'SIGLA DA UF DO REMETENTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 7011 COD, 'NOME DO MUNICIPIO DO REMETENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7012 COD, 'SIGLA DE UF DA CIDADE IBGE DO REMETENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7013 COD, 'CODIGO DA CIDADE IBGE DO REMETENTE  E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7014 COD, 'CIDADE IBGE DO REMETENTE NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 7015 COD, 'CODIGO IBGE DA CIDADE DO REMETENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7016 COD, 'CEP DO REMETENTE NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7017 COD, 'CODIGO DO PAIS DO REMETENTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7018 COD, 'NOME DO PAIS DO REMETENTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 7019 COD, 'TIPO DO DOCUMENTO ORIGINARIO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 7020 COD, 'TELEFONE DO REMETENTE MENOR QUE 7 CARACTERES OU MAIOR QUE 12 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8000 COD, 'NUMERO DO ROMANEIO DA NF E MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8001 COD, 'NUMERO DO PEDIDO DA NF E MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8002 COD, 'SERIE DA NF E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 8003 COD, 'NUMERO DA NF NAO INFORMADO OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8004 COD, 'DATA DE EMISSAO DA NF INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 8005 COD, 'VALOR DA BASE DE CALCULO DO ICMS E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8006 COD, 'VALOR TOTAL DO ICMS E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8007 COD, 'VALOR DA BASE DE CALCULO DO ICMS ST E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8008 COD, 'VALOR TOTAL DO ICMS ST E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8009 COD, 'VALOR TOTAL DOS PRODUTOS E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8010 COD, 'VALOR TOTAL DA NF E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8011 COD, 'PESO TOTAL EM KG E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8012 COD, 'CODIGO SUFRAMA E MENOR QUE 2 CARACTERES OU MAIOR QUE 9 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8013 COD, 'TIPO DE PESSOA DA NF INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8014 COD, 'CPF DA NF E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8015 COD, 'CNPJ DA NF E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8016 COD, 'RAZAO SOCIAL DA NF E MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8017 COD, 'LOGRADOURO DA NF NAO INFORMADO OU MAIOR QUE 255 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8018 COD, 'NUMERO DE ENDERECO DA NF NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8019 COD, 'COMPLEMENTO DO ENDERECO DA NF NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8020 COD, 'BAIRRO DO ENDERECO DA NF NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8021 COD, 'SIGLA DA UF DA NF INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 8022 COD, 'NOME DO MUNICIPIO DA NF NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8023 COD, 'SIGLA DE UF DA CIDADE IBGE DA NF INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8024 COD, 'CODIGO DA CIDADE IBGE DA NF E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8025 COD, 'CIDADE IBGE DO EXPEDIDOR DA NF NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 8026 COD, 'CODIGO IBGE DA CIDADE DA NF INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8100 COD, 'CHAVE NFE E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 8101 COD, 'CODIGO SUFRAMA E MENOR QUE 2 CARACTERES OU MAIOR QUE 9 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8200 COD, 'TIPO DE DOCUMENTO NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 8201 COD, 'NUMERO DO DOCUMENTO MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 8202 COD, 'DATA DE EMISSAO DO DOCUMENTO COMPLEMENTADO NAO INFORMADA OU INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 8203 COD, 'VALOR DO DOCUMENTO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9000 COD, 'TIPO DE PESSOA DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9001 COD, 'CNPJ DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9002 COD, 'CPF DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9003 COD, 'INSCRICAO ESTA DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9004 COD, 'RAZAO SOCIAL DO EXPEDIDOR NAO INFORMADA OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9005 COD, 'LOGRADOURO DO EXPEDIDOR NAO INFORMADO OU MAIOR QUE 255 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9006 COD, 'NUMERO DO ENDERECO DO EXPEDIDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9007 COD, 'COMPLEMENTO DO ENDERECO DO EXPEDIDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9008 COD, 'BAIRRO DO ENDERECO DO EXPEDIDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9009 COD, 'SIGLA DA UF DO EXPEDIDOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 9010 COD, 'NOME DO MUNICIPIO DO EXPEDIDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9011 COD, 'SIGLA DE UF DA CIDADE IBGE DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9012 COD, 'CODIGO DA CIDADE IBGE DO EXPEDIDOR  E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9013 COD, 'CIDADE IBGE DO EXPEDIDOR NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 9014 COD, 'CODIGO IBGE DA CIDADE DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9015 COD, 'CEP DO EXPEDIDOR NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9016 COD, 'CODIGO DO PAIS DO EXPEDIDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 9017 COD, 'NOME DO PAIS DO EXPEDIDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 9018 COD, 'TELEFONE DO EXPEDIDOR MENOR QUE 7 CARACTERES OU MAIOR QUE 12 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10000 COD, 'TIPO DE PESSOA DO RECEBEDOR NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10001 COD, 'CNPJ DO RECEBEDOR E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10002 COD, 'CPF DO RECEBEDOR E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10003 COD, 'INSCRICAO ESTA DO RECEBEDOR E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10004 COD, 'RAZAO SOCIAL DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10005 COD, 'LOGRADOURO DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 255 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10006 COD, 'NUMERO DO ENDERECO DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10007 COD, 'COMPLEMENTO DO ENDERECO DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10008 COD, 'BAIRRO DO ENDERECO DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10009 COD, 'SIGLA DA UF DO RECEBEDOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 10010 COD, 'NOME DO MUNICIPIO DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10011 COD, 'SIGLA DE UF DA CIDADE IBGE DO RECEBEDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10012 COD, 'CODIGO DA CIDADE IBGE DO RECEBEDOR  E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10013 COD, 'CIDADE IBGE DO RECEBEDOR NAO PERTENCE AO ESTADO' DESCRICAO FROM DUAL UNION  
    SELECT 10014 COD, 'CODIGO IBGE DA CIDADE DO RECEBEDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10015 COD, 'CEP DO RECEBEDOR NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10016 COD, 'CODIGO DO PAIS DO RECEBEDOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 10017 COD, 'NOME DO PAIS DO RECEBEDOR NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 10018 COD, 'TELEFONE DO RECEBEDOR MENOR QUE 7 CARACTERES OU MAIOR QUE 12 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 11000 COD, 'TIPO DE PESSOA INFORMADO PARA O DESTINATARIO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 11001 COD, 'CNPJ DO DESTINATARIO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11002 COD, 'CPF DO DESTINATARIO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11003 COD, 'INSCRICAO ESTATUAL DO DESTINATARIO E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 11004 COD, 'RAZAO SOCIAL DO DESTINATARIO E MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 11005 COD, 'LOGRADOURO DO DESTINATARIO MENOR QUE 2 CARACTERES OU MAIOR QUE 255 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11006 COD, 'NUMERO DO ENDERECO DO DESTINATARIO NAO INFORMADO OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11007 COD, 'COMPLEMENTO DO ENDERECO DO DESTINATARIO E MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11008 COD, 'BAIRRO DO DESTINATARIO NAO INFORMADO OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11009 COD, 'SIGLA DA UF DO DESTINATARIO E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 11010 COD, 'NOME DO MUNICIPIO DO DESTINATARIO E MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11011 COD, 'SIGLA DA UF DA CIDADE IBGE DO DESTINATARIO E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 11012 COD, 'CODIGO DA CIDADE IBGE DO DESTINATARIO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11013 COD, 'CIDADE IBGE NAO PERTENCE AO ESTADO.' DESCRICAO FROM DUAL UNION  
    SELECT 11014 COD, 'CODIGO IBGE DA CIDADE INFORMADA NO DESTINATARIO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11015 COD, 'CEP DO DESTINATARIO NAO INFORMADO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11016 COD, 'CODIGO DO PAIS DE DESTINATARIO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11017 COD, 'NOME DO PAIS DO DESTINATARIO NAO INFORMADO OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11018 COD, 'TELEFONE DO DESTINATARIO MENOR QUE 7 CARACTERES OU MAIOR QUE 12 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11019 COD, 'INSCRICAO DO SUFRAMA DO DESTINATARIO INFORMADA E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 11020 COD, 'TIPO DE PESSOA DO LOCAL DE ENTREGA INFORMADO NO DESTINATARIO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11021 COD, 'CNPJ DO LOCAL DE ENTREGA E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11022 COD, 'CPF DO LOCAL DE ENTREGA E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11023 COD, 'RAZAO SOCIAL DO LOCAL DE ENTREGA E MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 11024 COD, 'LOGRADOURO DO LOCAL DE ENTREGA MENOR QUE 2 CARACTERES OU MAIOR QUE 255 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11025 COD, 'NUMERO DO ENDERECO DO LOCAL DE ENTREGA NAO INFORMADO OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11026 COD, 'COMPLEMENTO DO ENDERECO DO LOCAL DE ENTREGA E MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11027 COD, 'BAIRRO DO LOCAL DE ENTREGA NAO INFORMADO OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11028 COD, 'SIGLA DA UF DO LOCAL DE ENTREGA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 11029 COD, 'NOME DO MUNICIPIO DO LOCAL DE ENTREGA E MENOR QUE 2 CARACTERES OU MAIOR QUE 60 CARACTERES.' DESCRICAO FROM DUAL UNION  
    SELECT 11030 COD, 'SIGLA DA UF DA CIDADE IBGE DO LOCAL DE ENTREGA E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 11031 COD, 'CODIGO DA CIDADE IBGE DO LOCAL DE ENTREGA E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 11032 COD, 'CIDADE IBGE NAO PERTENCE AO ESTADO.' DESCRICAO FROM DUAL UNION  
    SELECT 11033 COD, 'CODIGO IBGE DA CIDADE INFORMADA NO LOCAL DE ENTREGA E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 12000 COD, 'VALOR TOTAL DA PRESTACAO DE SERVICO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 12001 COD, 'VALOR A RECEBER DA PRESTACAO DE SERVICO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 12002 COD, 'NOME DO COMPONENTE DA PRESTACAO DE SERVICO NAO INFORMADO OU MAIOR QUE 15 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 12003 COD, 'VALOR DO COMPONENTE DA PRESTACAO DE SERVICO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 13000 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13001 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 13002 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13003 COD, 'PERCENTUAL DE REDUCAO DA BASE DE CALCULO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13004 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13005 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 13006 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13007 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13008 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 13009 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13010 COD, 'VALOR DO CREDITO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13011 COD, 'PERCENTUAL DE REDUCAO DA BASE DE CALCULO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13012 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13013 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 13014 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13015 COD, 'VALOR DO CREDITO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 13016 COD, 'INFORMACAO ADICIONAL INFORMADA E MAIOR QUE 2000 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 13017 COD, 'TIPO DE SITUACAO TRIBUTARIA DE ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 14000 COD, 'TOTAL DA MERCADORIA E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14001 COD, 'PRODUTO PREDOMINANTE NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14002 COD, 'OUTRAS CARACTERISTICAS INFORMADA E MAIOR QUE 30 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14003 COD, 'CODIGO DE UNIDADE DE MEDIDA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14004 COD, 'QUANTIDADE INFORMADA E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14006 COD, 'NUMERO DO CONTAINER NAO INFORMADO OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14007 COD, 'INFORACÕES DO LACRE NAO INFORMADA OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14008 COD, 'DATA PREVISTA DE ENTREGA NAO INFORMADA OU INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14010 COD, 'SIGLA DA UF DO EMISSOR DO DOCUMENTO ANTERIOR NAO INFORMADA' DESCRICAO FROM DUAL UNION  
    SELECT 14011 COD, 'TIPO PESSOA DO EMISSOR DO DOCUMENTO ANTERIOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14012 COD, 'RAZAO SOCIAL DO EMISSOR DO DOCUMENTO ANTERIOR NAO INFORMADA OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14014 COD, 'TIPO DO DOCUMENTO DE TRANSPORTE ANTERIOR EM PAPEL INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14015 COD, 'SERIE DO DOCUMENTO DE TRANSPORTE ANTERIOR EM PAPEL INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14016 COD, 'NUMERO DO DOCUMENTO DE TRANSPORTE ANTERIOR EM PAPEL INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14017 COD, 'DATA DE EMISSAO DO DOCUMENTO DE TRANSPORTE ANTERIOR EM PAPEL INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14018 COD, 'CHAVE CTE DO DOCUMENTO DE TRANSPORTE ANTERIOR ELETRONICO INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14019 COD, 'RESPONSAVEL PELO SEGURO INFORMADO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14020 COD, 'NOME DA SEGURADO NAO INFORMADO OU MAIOR QUE 30 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14021 COD, 'NUMERO DA APOLICE DO SEGURO NAO INFORMADO OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14022 COD, 'NUMERO DA AVERBACAO DO SEGURO NAO INFORMADO OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14023 COD, 'VALOR DA MERCADORIA INFORMADO NO SEGURO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14024 COD, 'CONTRATO DO TRANSPORTE E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14025 COD, 'O RNTC DO TRANSPORTE INFORMADO DIFERENTE DE 8 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14026 COD, 'DATA PREVISTA DE ENTREGA INFORMADA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14027 COD, 'CODIGO IDENTIFICADOR DA OPERACAO DE TRANSPORTE INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14029 COD, 'A SERIE INFORMADA NA COLETA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14030 COD, 'A ORDEM INFORMADA NA COLETA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14031 COD, 'A DATA DE EMISSAO DA COLETA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14032 COD, 'CNPJ DA COLETA ESTA INCORRETO' DESCRICAO FROM DUAL UNION  
    SELECT 14033 COD, 'CODIGO INTERNO DA TRANSPORTADOR ESTA MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14034 COD, 'INSCRICAO ESTA DA COLETA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14035 COD, 'SIGLA DE UF DA COLETA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14036 COD, 'TELEFONE DA COLETA ESTA MAIOR QUE 12 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14037 COD, 'CNPJ DA EMPRESA FORNECEDORORA DO VALE-PEDAGIO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14038 COD, 'NUMERO DO COMPROVANTE DE COMPRA NAO INFORMADO OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14039 COD, 'CNPJ DO RESPONSAVEL PELO PAGAMENTO DO VALE-PEDAGIO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14040 COD, 'VALOR DO VALE-PEDAGIO NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14045 COD, 'CODIGO INTERNO DO VEICULO E MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14046 COD, 'RENAVAN DO VEICULO INFORMADO ESTA INCORRETO' DESCRICAO FROM DUAL UNION  
    SELECT 14047 COD, 'PLACA DO VEICULO INFORMADO INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14048 COD, 'TARA DO VEICULO INFORMADO ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14049 COD, 'CAPACIDADE DE KG INFORMADA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14050 COD, 'CAPACIDADE DE M3 INFORMADA ESTA INCORRETA' DESCRICAO FROM DUAL UNION  
    SELECT 14051 COD, 'PROPRIEDADE DO VEICULO E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14052 COD, 'VEICULO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14053 COD, 'TIPO RODADO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14054 COD, 'TIPO CARROCERIA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14055 COD, 'TIPO DE SIGLA UF DO VEICULO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14056 COD, 'TIPO PESSOA (CNPJ/ CPF) INFORMADO PARA O PROPRIETARIO DO VEICULO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14057 COD, 'CNPJ DO PROPRIETARIO DO VEICULO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14058 COD, 'CPF DO PROPRIETARIO DO VEICULO  E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14059 COD, 'RNTC DO PROPRIETARIO DO VEICULO INFORMADO ESTA INCORRETO' DESCRICAO FROM DUAL UNION  
    SELECT 14060 COD, 'RAZAO SOCIAL DO PROPRIETARIO DO VEICULO NAO INFORMADA OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14061 COD, 'INSCRICAO ESTA DO PROPRIETARIO DO VEICULO E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14062 COD, 'SIGLA DA UF DO PROPRIETARIO DO VEICULO E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14063 COD, 'PROPRIETARIO DO VEICULO INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14064 COD, 'INFORMACOES DO LACRE DO CONTRATO RODOVIARIO NAO INFORMADAS OU E MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14065 COD, 'CPF DO MOTORISTA NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14066 COD, 'NOME DO MOTORISTA NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14089 COD, 'TIPO DO TRAFEGO NAO INFORMADO PARA O CONTRATO FERROVIARIO' DESCRICAO FROM DUAL UNION  
    SELECT 14090 COD, 'O FLUXO DO CONTRATO FERROVIARIO NAO INFORMADO OU MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14091 COD, 'IDENTIFICACAO DO TREM INFORMADO E MAIOR QUE 7 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14092 COD, 'VALOR DO FRETE NAO INFORMADO' DESCRICAO FROM DUAL UNION  
    SELECT 14093 COD, 'CNPJ DA FERROVIA SUBSTITUIDA E INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14094 COD, 'CODIGO INTENO DA FERROVIA SUBSTITUIDA E MAIOR QUE 10 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14095 COD, 'INSCRICAO ESTA DA FERROVIA SUBSTITUIDA E INVALIDA OU E MAIOR QUE 14 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14096 COD, 'RAZAO SOCIAL DA FERROVIA SUBSTITUIDA NAO INFORMADA OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14097 COD, 'LOGRADOURO DO ENDERECO DA FERROVIA SUBSTITUIDA NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14098 COD, 'NUMERO DO ENDERECO DA FERROVIA SUBSTITUIDA NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14099 COD, 'COMPLEMENTO DO ENDERECO DA FERROVIA SUBSTITUIDA NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14100 COD, 'SIGLA DA UF DA FERROVIA SUBSTITUIDA E INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14101 COD, 'NOME DO MUNICIPIO DA FERROVIA SUBSTITUIDA NAO INFORMADO OU MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14102 COD, 'CEP DA FERROVIA SUBSTITUIDA INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14124 COD, 'BAIRRO DA FERROVIA SUBSTITUIDA E MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14126 COD, 'NOME APROPRIADO PARA EMBARQUE NAO INFORMADO OU MAIOR QUE 150 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14127 COD, 'CLASSE DE RISCO NAO INFORMADO OU MAIOR QUE 40 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14130 COD, 'QUANTIDADE VOLUME INFORMADA MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14131 COD, 'PONTO FULGOR INFORMADO MAIOR QUE 6 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14137 COD, 'CHAVE CTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14138 COD, 'CHAVE CTE INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14139 COD, 'CNPJ DO TOMADOR NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14140 COD, 'TAMANHO DO MODELO DO CTE DIFERENTE DE 2 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14141 COD, 'SERIE DO CTE MAIOR QUE 3 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14142 COD, 'SUB-SERIE DO CTE MAIOR QUE 3 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14143 COD, 'NUMERO DO DOCUMENTO DO CTE NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14144 COD, 'VALOR DO CTE NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14145 COD, 'DATA DE EMISSAO DO CTE NAO INFORMADA OU INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14146 COD, 'CHAVE DO CTE NAO INFORMADA OU INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14147 COD, 'CHAVE DO CTE ANULADA NÃO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14149 COD, 'TAMANHO DO NUMERO DA FATUDA MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14150 COD, 'VALOR ORIGINAL DA FATURA NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14151 COD, 'VALOR DE DESCONTO DA FATURA NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14152 COD, 'VALOR LIQUIDO DA FATURA NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14153 COD, 'TAMANHO DO NUMERO DA DUPLICATA MAIOR QUE 60 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14154 COD, 'DATA DE VENCIMENTO DA DUPLICATA NAO INFORMADA OU INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14155 COD, 'VALOR DA DUPLICATA NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 14156 COD, 'DADOS DOS DOCUMENTOS DE TRANSPORTE ANTERIOR EM PAPEL E/OU DOS DOCUMENTOS DE TRANSPORTE ANTERIOR ELETRONICOS NAO INFORMADOS' DESCRICAO FROM DUAL UNION  
    SELECT 14157 COD, 'SUBSERIE DO DOCUMENTO DE TRANSPORTE ANTERIOR EM PAPEL INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14158 COD, 'INSCRICAO ESTA DO EMISSOR DO DOCUMENTO ANTERIOR INVALIDA' DESCRICAO FROM DUAL UNION  
    SELECT 14159 COD, 'CNPJ/ CPF DO EMISSOR DO DOCUMENTO ANTERIOR INVALIDO' DESCRICAO FROM DUAL UNION  
    SELECT 15000 COD, 'CHAVE DO CTE CONTEM CARACTERES INVALIDO - SOMENTE NUMEROS.' DESCRICAO FROM DUAL UNION  
    SELECT 15001 COD, 'TIPO DO COMPLEMENTO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15002 COD, 'VALOR DA PRESTACAO DE SERVICO INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15003 COD, 'NOME DO COMPONENTE NAO INFORMADO OU MAIOR QUE 15 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 15004 COD, 'VALOR DO COMPONENTE INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15005 COD, 'TIPO DE SITUACAO TRIBUTARIA DE ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 15006 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15007 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 15008 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15009 COD, 'PERCENTUAL DE REDUCAO DA BASE DE CALCULO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15010 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15011 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 15012 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15013 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15014 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 15015 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15016 COD, 'VALOR DO CREDITO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15017 COD, 'PERCENTUAL DE REDUCAO DA BASE DE CALCULO E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15018 COD, 'VALOR DA BASE DE CALCULO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15019 COD, 'ALIQUOTA DO ICMS E INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 15020 COD, 'VALOR DO ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15021 COD, 'VALOR DO CREDITO DE ICMS E INVALIDO.' DESCRICAO FROM DUAL UNION  
    SELECT 15022 COD, 'INFORMACAO ADICIONAL INFORMADA E MAIOR QUE 2000 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 16000 COD, 'CHAVE DO CTE GERADA ESTA INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 16001 COD, 'DATA DE EMISSAO INFORMADA ESTA INVALIDA.' DESCRICAO FROM DUAL UNION  
    SELECT 14128 COD, 'GRUPO DE EMBALAGEM INFORMADO E MAIOR QUE 6 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 14129 COD, 'QUANTIDADE TOTAL NAO INFORMADO OU MAIOR QUE 20 CARACTERES' DESCRICAO FROM DUAL UNION  
    SELECT 100000 COD, 'NAO INFORMADO O WEBSERVICE PARA UF DO EMITENTE NO CONFIGURADOR' DESCRICAO FROM DUAL UNION  
    SELECT 100001 COD, 'PROBLEMA COM CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION  
    SELECT 100002 COD, 'ERRO NA CHAMADA DO WEBSERVICE' DESCRICAO FROM DUAL UNION  
    SELECT 100003 COD, 'CONSUMO DE UM WEBSERVICE UTILIZANDO O WSDL DE OUTRO.' DESCRICAO FROM DUAL   
  ) LOOP
  
    SELECT COUNT(*) INTO iCOUNT FROM PCMENSAGEMCTE WHERE CODMENSAGEM = DADOS.COD;
    
    IF iCOUNT = 0 THEN
       INSERT INTO PCMENSAGEMCTE (CODMENSAGEM, DESCRICAO) VALUES(DADOS.COD ,DADOS.DESCRICAO);
    ELSE
       UPDATE PCMENSAGEMCTE SET
         DESCRICAO = DADOS.DESCRICAO
       WHERE CODMENSAGEM = DADOS.COD;       
    END IF;
  END LOOP;
  COMMIT;
END