/*
  Separação de view para inativação dinamica com joins 
*/

CREATE or REPLACE VIEW VW_INT_C5_PRECOAPARTIR AS (
  SELECT C5.CODFILIALINTEGRACAO SEQPRECOAPARTIR,
         'CLIENTE ATACADO FILIAL '||TO_CHAR(C5.CODFILIALINTEGRACAO)  DESCRICAO,
         SYSDATE - 10 DTAHORINICIO,
         SYSDATE + 10000 DTAHORFIM,
         1 NROSEGMENTO,
         CODFILIALINTEGRACAO NROEMPRESA,
         'S' ATIVO
   FROM VW_INT_C5_OBTER_FILIAIS_C5 C5
   WHERE FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('UTILIZAGATCLIATAC', C5.CODFILIAL, 'N') = 'S'

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPESSOA AS (
  SELECT 
    C5.CODFILIALINTEGRACAO SEQPRECOAPARTIR,
    C.CODCLI SEQPESSOA,
    'S' ATIVO
  FROM
    PCCLIENT C, VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE NVL(C.CLIATACADO, 'N') = 'S'
  AND  FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('UTILIZAGATCLIATAC', C5.CODFILIAL, 'N') = 'S'
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPRODUTO AS (
  SELECT 
    C5.CODFILIALINTEGRACAO SEQPRECOAPARTIR,
    T.SEQPRODUTO,
    --MIN(T.PRECO/NVL(T.QTDEMBALAGEM,1)) PRECO,
    --LEAST(ROUNDABNT(MIN(T.PRECO), 2), 9999999.99) PRECO,
    LEAST(ROUNDABNT(MIN(E.PVENDAATAC), 2), 9999999.99) PRECO,
    NULL PERCDESCONTO,
    1 QTDE,
    'S' ATIVO
  FROM
    MONITORPDVMIDDLE.TB_PRODPRECO T,
    VW_INT_C5_EMBPROD E,
    VW_INT_C5_OBTER_FILIAIS_C5 C5,
    PCPARAMFILIAL F
  WHERE E.codauxiliar = REPLACE(T.IDREF, 'A', '')
  AND E.codfilialintegracao = T.NROEMPRESA
  AND E.codfilial = C5.CODFILIAL
  AND E.codfilial = F.CODFILIAL
  AND INSTR(T.IDREF, 'A') > 0 
  AND T.PRECO > 0
  AND T.PROMOCAO = 'N'
  AND T.ATIVO = 'S'
  AND C5.CODFILIALINTEGRACAO = T.NROEMPRESA
  AND F.CODFILIAL = C5.CODFILIAL
  AND F.NOME = 'NUMREGIAOPADRAOVAREJO'
  AND  FERRAMENTAS.F_BUSCARPARAMETRO_ALFA('UTILIZAGATCLIATAC', C5.CODFILIAL, 'N') = 'S'
  GROUP BY C5.CODFILIALINTEGRACAO, T.SEQPRODUTO
  )
