/*
  Separação de view para inativação dinamica com joins 
*/

CREATE or REPLACE VIEW VW_INT_C5_PRECOAPARTIR AS (
  SELECT 
    1 SEQPRECOAPARTIR, 
    'CLIENTE ATACADO' DESCRICAO,
    'S' ATIVO  
  FROM DUAL

  UNION ALL

  SELECT
    CODFIDELIDADE SEQPRECOAPARTIR,
    'CLIENTE FIDELIDADE ' || CODFIDELIDADE DESCRICAO,
    CASE
      WHEN DTEXCLUSAO IS NULL AND (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL) THEN
        'S'
      ELSE
        'N'
    END ATIVO
  FROM
    PCDESCONTOFIDELIDADE T
    LEFT JOIN MONITORPDVMIDDLE.TB_PRECOAPARTIR TP
    ON (TP.SEQPRECOAPARTIR = T.CODFIDELIDADE),
    VW_INT_C5_OBTER_FILIAIS_C5 F,
    (
      SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PRECOAPARTIR')
    ) DATAPADRAO
  WHERE
    ( 
      (TP.ATIVO = 'S' AND (T.DTEXCLUSAO IS NOT NULL or (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL)))
      OR (T.DTEXCLUSAO IS NULL) 
    )
    AND T.CODFILIAL = F.CODFILIAL
    AND T.DTINICIAL <= TRUNC(sysdate)
    AND NVL(T.CODCLI, 0) <> 0
    AND NVL(T.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPESSOA AS (
  SELECT 
    1 SEQPRECOAPARTIR,
    CODCLI SEQPESSOA,
    'S' ATIVO
  FROM
    PCCLIENT
  WHERE 
    CLIATACADO = 'S' 
    
  UNION ALL

  SELECT 
    CODFIDELIDADE SEQPRECOAPARTIR,
    CODCLI SEQPESSOA,
    CASE
        WHEN DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) BETWEEN DTINICIAL AND DTFINAL) THEN
          'S'
        ELSE
          'N'
      END ATIVO
  FROM
      PCDESCONTOFIDELIDADE T
      LEFT JOIN MONITORPDVMIDDLE.TB_PRECOAPARTIRPESSOA TP
      ON (TP.SEQPRECOAPARTIR = T.CODFIDELIDADE),
      VW_INT_C5_OBTER_FILIAIS_C5 F,
      (
        SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PRECOAPARTIRPESSOA')
      ) DATAPADRAO
  WHERE
    ( 
      (TP.ATIVO = 'S' AND (T.DTEXCLUSAO IS NOT NULL or (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL)))
      OR (T.DTEXCLUSAO IS NULL) 
    )
    AND T.CODFILIAL = F.CODFILIAL
    AND T.DTINICIAL <= TRUNC(SYSDATE)
    AND NVL(T.CODCLI, 0) <> 0
    AND NVL(T.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIREMPRESA AS (
  SELECT 
    1 SEQPRECOAPARTIR,
    CODFILIALINTEGRACAO NROEMPRESA,
    'S' ATIVO
  FROM
    VW_INT_C5_OBTER_FILIAIS_C5
    
  UNION ALL

  SELECT 
    T.CODFIDELIDADE SEQPRECOAPARTIR,
    F.CODFILIALINTEGRACAO NROEMPRESA,
    CASE
        WHEN DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) BETWEEN DTINICIAL AND DTFINAL) THEN
          'S'
        ELSE
          'N'
      END ATIVO
  FROM
      PCDESCONTOFIDELIDADE T
      LEFT JOIN MONITORPDVMIDDLE.TB_PRECOAPARTIREMPRESA TP
      ON (TP.SEQPRECOAPARTIR = T.CODFIDELIDADE),
      VW_INT_C5_OBTER_FILIAIS_C5 F,
      (
        SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PRECOAPARTIREMPRESA')
      ) DATAPADRAO
  WHERE
    ( 
      (TP.ATIVO = 'S' AND (T.DTEXCLUSAO IS NOT NULL or (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL)))
      OR (T.DTEXCLUSAO IS NULL) 
    )
    AND T.CODFILIAL = F.CODFILIAL
    AND T.DTINICIAL <= TRUNC(SYSDATE)
    AND NVL(T.CODCLI, 0) <> 0
    AND NVL(T.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRSEGMENTO AS (
  SELECT 
    1 SEQPRECOAPARTIR,
    1 NROSEGMENTO,
    'S' ATIVO
  FROM
    dual
    
  UNION ALL

  SELECT 
    T.CODFIDELIDADE SEQPRECOAPARTIR,
    1 NROSEGMENTO,
    CASE
        WHEN DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) BETWEEN DTINICIAL AND DTFINAL) THEN
          'S'
        ELSE
          'N'
      END ATIVO
  FROM
      PCDESCONTOFIDELIDADE T
      LEFT JOIN MONITORPDVMIDDLE.TB_PRECOAPARTIRSEGMENTO TP
      ON (TP.SEQPRECOAPARTIR = T.CODFIDELIDADE),
      VW_INT_C5_OBTER_FILIAIS_C5 F,
      (
        SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PRECOAPARTIRSEGMENTO')
      ) DATAPADRAO
  WHERE
    ( 
      (TP.ATIVO = 'S' AND (T.DTEXCLUSAO IS NOT NULL or (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL)))
      OR (T.DTEXCLUSAO IS NULL) 
    )
    AND T.CODFILIAL = F.CODFILIAL
    AND T.DTINICIAL <= TRUNC(SYSDATE)
    AND NVL(T.CODCLI, 0) <> 0
    AND NVL(T.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPERIODO AS (
  SELECT 
    1 SEQPRECOAPARTIR,
    SYSDATE - 10 DTAHORINICIO,
    SYSDATE + 10000 DTAHORFIM,
    'S' ATIVO
  FROM
    dual
    
  UNION ALL

  SELECT 
    T.CODFIDELIDADE SEQPRECOAPARTIR,
    T.DTINICIAL DTAHORINICIO,
    T.DTFINAL DTAHORFIM,
    CASE
      WHEN DTEXCLUSAO IS NULL AND (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL) THEN
        'S'
      ELSE
        'N'
    END ATIVO
  FROM
      PCDESCONTOFIDELIDADE T
      LEFT JOIN MONITORPDVMIDDLE.TB_PRECOAPARTIRPERIODO TP
      ON (TP.SEQPRECOAPARTIR = T.CODFIDELIDADE),
      VW_INT_C5_OBTER_FILIAIS_C5 F,
      (
        SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
        FROM PCCONTROLECONSINCO S
        WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PRECOAPARTIRPERIODO')
      ) DATAPADRAO
  WHERE
    ( 
      (TP.ATIVO = 'S' AND (T.DTEXCLUSAO IS NOT NULL or (trunc(sysdate) BETWEEN DTINICIAL and DTFINAL)))
      OR (T.DTEXCLUSAO IS NULL) 
    )
    AND T.CODFILIAL = F.CODFILIAL
    AND T.DTINICIAL <= TRUNC(SYSDATE)
    AND NVL(T.CODCLI, 0) <> 0
    AND NVL(T.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPERIODO AS (
  SELECT
    1 SEQPRECOAPARTIR,
    SEQPRODUTO,
    PRECO,
    NULL PERCDESCONTO,
    1 QTDE
  FROM
    MONITORPDVMIDDLE.TB_PRODPRECO
  WHERE INSTR(IDREF, 'A') > 0 
    AND PRECO > 0
    AND PROMOCAO = 'N'

  UNION ALL

  SELECT
    T.CODFIDELIDADE SEQPRECOAPARTIR ,
    DEPARA.SEQPRODUTO,
    NULL PRECO,
    T.PERCDESCONTO,
    1 QTDE,
    CASE
        WHEN T.DTEXCLUSAO IS NULL AND (trunc(sysdate) BETWEEN T.DTINICIAL and T.DTFINAL) THEN
          'S'
        ELSE
          'N'
      END ATIVO
  FROM 
    PCDESCONTOFIDELIDADE T
  INNER JOIN PCPRODUT 
  ON (
    PCPRODUT.CODSEC = T.CODSECAO 
    OR PCPRODUT.CODEPTO = T.CODEPTO 
    OR PCPRODUT.CODFORNEC = T.CODFORNEC 
    OR PCPRODUT.CODPROD = T.CODPROD 
    OR PCPRODUT.CODCATEGORIA = T.CODCATEGORIA 
  )
  INNER JOIN PCDEPARAPRODC5 DEPARA
    ON DEPARA.CODPROD = PCPRODUT.CODPROD
  LEFT JOIN MONITORPDVMIDDLE.TB_PRECOAPARTIRPERIODO TP
    ON (TP.SEQPRECOAPARTIR = T.CODFIDELIDADE),
  VW_INT_C5_OBTER_FILIAIS_C5 F,
  (
    SELECT MIN(S.ULTIMAEXECUCAO) ULTIMAEXECUCAO
      FROM PCCONTROLECONSINCO S
      WHERE (UPPER(S.OBJETOREFERENCIA) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_PRECOAPARTIRPRODUTO')
  ) DATAPADRAO
  WHERE
  ( 
      (TP.ATIVO = 'S' AND (T.DTEXCLUSAO IS NOT NULL or (trunc(sysdate) BETWEEN DTINICIAL AND DTFINAL)))
      OR (T.DTEXCLUSAO IS NULL) 
    )
  AND F.CODFILIAL = T.CODFILIAL 
  AND T.DTINICIAL <= TRUNC(SYSDATE)
  AND NVL(T.CODCLI, 0) <> 0
  AND NVL(T.DTALTERC5, DATAPADRAO.ULTIMAEXECUCAO) >= DATAPADRAO.ULTIMAEXECUCAO
)