/*
  Separação de view para inativação dinamica com joins 
*/


CREATE or REPLACE VIEW VW_INT_C5_PRECOAPARTIR AS (
  SELECT 
    1 SEQPRECOAPARTIR, 
    'CLIENTE ATACADO' DESCRICAO,
    SYSDATE - 10 DTAHORINICIO,
    SYSDATE + 10000 DTAHORFIM,
    1 NROSEGMENTO,
    TO_CHAR(CODFILIALINTEGRACAO) NROEMPRESA,
    'S' ATIVO
  FROM VW_INT_C5_OBTER_FILIAIS_C5

  UNION ALL

  SELECT
    CODFIDELIDADE SEQPRECOAPARTIR,
    'CLIENTE FIDELIDADE ' || CODFIDELIDADE DESCRICAO,
    T.DTINICIAL DTAHORINICIO,
    T.DTFINAL DTAHORFIM,
    1 NROSEGMENTO,
    T.CODFILIAL NROEMPRESA,
    'S' ATIVO
  FROM
    PCDESCONTOFIDELIDADE T,
    VW_INT_C5_OBTER_FILIAIS_C5 F
  WHERE
    T.CODFILIAL = F.CODFILIALINTEGRACAO
    AND T.DTEXCLUSAO IS NOT NULL
    AND TRUNC(SYSDATE) BETWEEN T.DTINICIAL AND T.DTFINAL
    AND NVL(T.CODCLI, 0) <> 0
)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPESSOA AS (
  SELECT 
    1 SEQPRECOAPARTIR,
    CODCLI SEQPESSOA,
    'S' ATIVO
  FROM
    PCCLIENT
  WHERE 
    CLIATACADO = 'S' 
    
  UNION ALL

  SELECT 
    CODFIDELIDADE SEQPRECOAPARTIR,
    CODCLI SEQPESSOA,
    'S' ATIVO
  FROM
    PCDESCONTOFIDELIDADE T,
    VW_INT_C5_OBTER_FILIAIS_C5 F
  WHERE
    T.CODFILIAL = F.CODFILIALINTEGRACAO
    AND T.DTEXCLUSAO IS NOT NULL
    AND TRUNC(SYSDATE) BETWEEN T.DTINICIAL AND T.DTFINAL
    AND NVL(T.CODCLI, 0) <> 0

)

\

CREATE OR REPLACE VIEW VW_INT_C5_PRECOAPARTIRPRODUTO AS (
  SELECT DISTINCT
    1 SEQPRECOAPARTIR,
    SEQPRODUTO,
    PRECO,
    NULL PERCDESCONTO,
    1 QTDE,
    'S' ATIVO
  FROM
    MONITORPDVMIDDLE.TB_PRODPRECO,
 	  VW_INT_C5_OBTER_FILIAIS_C5 F
  WHERE INSTR(IDREF, 'A') > 0 
    AND PRECO > 0
    AND PROMOCAO = 'N'
    AND F.CODFILIALINTEGRACAO = NROEMPRESA

  UNION ALL

  SELECT
    T.CODFIDELIDADE SEQPRECOAPARTIR ,
    DEPARA.SEQPRODUTO,
    NULL PRECO,
    T.PERCDESCONTO,
    1 QTDE,
    'S' ATIVO
  FROM 
    PCDESCONTOFIDELIDADE T
  INNER JOIN PCPRODUT 
  ON (
    PCPRODUT.CODSEC = T.CODSECAO 
    OR PCPRODUT.CODEPTO = T.CODEPTO 
    OR PCPRODUT.CODFORNEC = T.CODFORNEC 
    OR PCPRODUT.CODPROD = T.CODPROD 
    OR PCPRODUT.CODCATEGORIA = T.CODCATEGORIA 
  )
  INNER JOIN PCDEPARAPRODC5 DEPARA
    ON (DEPARA.CODPROD = PCPRODUT.CODPROD),
  VW_INT_C5_OBTER_FILIAIS_C5 F
  WHERE
    F.CODFILIALINTEGRACAO = T.CODFILIAL 
    AND T.DTEXCLUSAO IS NOT NULL
    AND NVL(T.CODCLI, 0) <> 0
    AND TRUNC(SYSDATE) BETWEEN T.DTINICIAL AND T.DTFINAL
)