CREATE OR REPLACE TRIGGER TRG_PCLOGDADOSLOGIS_PCPRODUT
BEFORE
  INSERT OR UPDATE OR DELETE
  ON PCPRODUT
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
  
DECLARE
  VSPROGRAMA VARCHAR2(80);
  VSUSUARIO  VARCHAR2(80);
  VSMAQUINA  VARCHAR2(80);
  VSOPERACAO VARCHAR2(100);
BEGIN

  VSMAQUINA  := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 80);
  VSUSUARIO  := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 80);
  VSPROGRAMA := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 80);

  IF VSPROGRAMA IS NULL THEN
    VSPROGRAMA := 'Client do oracle desatualizado';
  END IF;
  
  IF UPDATING THEN
    VSOPERACAO := 'UPDATE';
  ELSIF INSERTING THEN 
    VSOPERACAO := 'INSERT';
  ELSE
    VSOPERACAO := 'DELETE';
  END IF;
      

  insert into pclogdadoslogisticos (
  codfilial,
  codfilial_ant,
  codendereco,
  codendereco_ant,
  deposito,
  deposito_ant,
  rua,
  rua_ant,
  predio,
  predio_ant,
  nivel,
  nivel_ant,
  apto,
  apto_ant,
  codprod,
  codprod_ant,
  descricao,
  descricao_ant,
  embalagem,
  embalagem_ant,
  embalagemmaster,
  embalagemmaster_ant,
  unidade,
  unidade_ant,
  unidademaster,
  unidademaster_ant,
  qtunit,
  qtunit_ant,
  qtunitcx,
  qtunitcx_ant,
  codfab,
  codfab_ant,
  dun_caixa,
  dun_caixa_ant,
  ean_unidade,
  ean_unidade_ant,
  lastropal,
  lastropal_ant,
  alturapal,
  alturapal_ant,
  qttotpal,
  qttotpal_ant,
  altura_un,
  altura_un_ant,
  largura_un,
  largura_un_ant,
  comprimento_un,
  comprimento_un_ant,
  volume_venda,
  volume_venda_ant,
  altura_cx,
  altura_cx_ant,
  largura_cx,
  largura_cx_ant,
  comprimento_cx,
  comprimento_cx_ant,
  volume_master,
  volume_master_ant,
  pesobruto_cx,
  pesobruto_cx_ant,
  pesoliq_cx,
  pesoliq_cx_ant,
  pesobruto_un,
  pesobruto_un_ant,
  pesoliq_un,
  pesoliq_un_ant,
  usawms,
  usawms_ant,
  estoquepordtvalidade,
  estoquepordtvalidade_ant,
  prazoval,
  prazoval_ant,
  perctoleranciaval,
  perctoleranciaval_ant,
  pesovariavel,
  pesovariavel_ant,
  tipoestoque,
  tipoestoque_ant,
  tipo,
  tipo_ant,
  capacidade,
  capacidade_ant,
  pontoreposicao,
  pontoreposicao_ant,
  abastepalete,
  abastepalete_ant,
  abastepaletecx,
  abastepaletecx_ant,
  normapalete,
  normapalete_ant,
  expedecaixafechada,
  expedecaixafechada_ant,
  nivelmaximoarm,
  nivelmaximoarm_ant,
  nivelminimoarm,
  nivelminimoarm_ant,
  restricaoblocado,
  restricaoblocado_ant,
  digitarqtmaster,
  digitarqtmaster_ant,
  validacapacidadepicking,
  validacapacidadepicking_ant,
  estoquepordtvalidadepk,
  estoquepordtvalidadepk_ant,
  tipovariacao,
  tipovariacao_ant,
  fracionado,
  fracionado_ant,
  tipocarga,
  tipocarga_ant,
  controlanumserie,
  controlanumserie_ant,
  novacaixaflowrack,
  novacaixaflowrack_ant,
  estoqueporlote,
  estoqueporlote_ant,
  induzlote,
  induzlote_ant,
  utilizaqtdesupmultipla,
  utilizaqtdesupmultipla_ant,
  utilizamultiplicador,
  utilizamultiplicador_ant,
  usaformulacao,
  usaformulacao_ant,
  perctoleranciacorte,
  perctoleranciacorte_ant,
  perctoleranciadepuratransf,
  perctoleranciadepuratransf_ant,
  emitiretqent,
  emitiretqent_ant,
  atualizafilialgestaowms,
  atualizafilialgestaowms_ant,
  filialgestaowms,
  filialgestaowms_ant,
  enderecamentocubagem,
  enderecamentocubagem_ant,
  estrupk,
  estrupk_ant,
  pk_end,
  pk_end_ant,
  caracteristica,
  caracteristica_ant,
  estrupul,
  estrupul_ant,
  pulmao,
  pulmao_ant,
  tipoprod,
  tipoprod_ant,
  PROGRAMA,
  MAQUINA,
  USUARIO,
  DATA,
  OPERACAO
  )
    (SELECT e.codfilial,
           e.codfilial,
           e.codendereco,
           e.codendereco,
           e.deposito,
           e.deposito,
           e.rua,
           e.rua,
           e.predio,
           e.predio,
           e.nivel,
           e.nivel,
           e.apto,
           e.apto,
           :new.codprod,
           :old.codprod,
           :new.descricao,
           :old.descricao,
           :new.embalagem,
           :old.embalagem,
           :new.embalagemmaster,
           :old.embalagemmaster,
           :new.unidade,
           :old.unidade,
           :new.unidademaster,
           :old.unidademaster,
           :new.qtunit,
           :old.qtunit,
           :new.qtunitcx,
           :old.qtunitcx,
           :new.codfab,
           :old.codfab,
           :new.codauxiliar2,
           :old.codauxiliar2,
           :new.codauxiliar,
           :old.codauxiliar,
           f.lastropal,
           f.lastropal,
           f.alturapal,
           f.alturapal,
           f.qttotpal,
           f.qttotpal,
           :new.alturam3 altura_un,
           :old.alturam3 altura_un,
           :new.larguram3 largura_un,
           :old.larguram3 largura_un,
           :new.comprimentom3 comprimento_un,
           :old.comprimentom3 comprimento_un,
           :new.volume AS volume_venda,
           :old.volume AS volume_venda,
           :new.alturaarm altura_cx,
           :old.alturaarm altura_cx,
           :new.larguraarm largura_cx,
           :old.larguraarm largura_cx,
           :new.comprimentoarm comprimento_cx,
           :old.comprimentoarm comprimento_cx,
           :new.volumerec AS volume_master,
           :old.volumerec AS volume_master,
           :new.pesobrutomaster pesobruto_cx,
           :old.pesobrutomaster pesobruto_cx,
           :new.pesoliqmaster pesoliq_cx,
           :old.pesoliqmaster pesoliq_cx,
           :new.pesobruto pesobruto_un,
           :old.pesobruto pesobruto_un,
           :new.pesoliq pesoliq_un,
           :old.pesoliq pesoliq_un,
           DECODE (:new.usawms,
                   'S',
                   'SIM',
                   'N',
                   'N?O')
               usawms,
           DECODE (:old.usawms,
                   'S',
                   'SIM',
                   'N',
                   'N?O')
               usawms,
           :new.estoquepordtvalidade,
           :old.estoquepordtvalidade,
           f.prazoval,
           f.prazoval,
           f.perctoleranciaval,
           f.perctoleranciaval,
           :new.pesovariavel,
           :old.pesovariavel,
           :new.tipoestoque,
           :old.tipoestoque,
           DECODE (k.tipo,
                   'V',
                   'VENDA',
                   'M',
                   'M?STER',
                   'P',
                   'PR?-PICK')
               tipo,
           DECODE (k.tipo,
                   'V',
                   'VENDA',
                   'M',
                   'M?STER',
                   'P',
                   'PR?-PICK')
               tipo,
           k.capacidade,
           k.capacidade,
           k.pontoreposicao,
           k.pontoreposicao,
           f.abastepalete,
           f.abastepalete,
           f.abastepaletecx,
           f.abastepaletecx,
           f.normapalete,
           f.normapalete,
           f.expedecaixafechada,
           f.expedecaixafechada,
           f.nivelmaximoarm,
           f.nivelmaximoarm,
           f.nivelminimoarm,
           f.nivelminimoarm,
           f.restricaoblocado,
           f.restricaoblocado,
           f.digitarqtmaster,
           f.digitarqtmaster,
           f.validacapacidadepicking,
           f.validacapacidadepicking,
           f.estoquepordtvalidadepk,
           f.estoquepordtvalidadepk,
           f.tipovariacao,
           f.tipovariacao,
           f.fracionado,
           f.fracionado,
           f.tipocarga,
           f.tipocarga,
           f.controlanumserie,
           f.controlanumserie,
           f.novacaixaflowrack,
           f.novacaixaflowrack,
           :new.estoqueporlote,
           :old.estoqueporlote,
           :new.induzlote,
           :old.induzlote,
           f.utilizaqtdesupmultipla,
           f.utilizaqtdesupmultipla,
           :new.utilizamultiplicador,
           :old.utilizamultiplicador,
           f.usaformulacao,
           f.usaformulacao,
           f.perctoleranciacorte,
           f.perctoleranciacorte,
           f.perctoleranciadepuratransf,
           f.perctoleranciadepuratransf,
           f.emitiretqent,
           f.emitiretqent,
           f.atualizafilialgestaowms,
           f.atualizafilialgestaowms,
           f.filialgestaowms,
           f.filialgestaowms,
           :new.enderecamentocubagem,
           :old.enderecamentocubagem,
           k.tipoestrutura || '-' || (t.descricao) estrupk,
           k.tipoestrutura || '-' || (t.descricao) estrupk,
           (k.tipoendereco || '-' || (ll.descricao)) pk_end,
           (k.tipoendereco || '-' || (ll.descricao)) pk_end,
           f.codcaracprod || ' - ' || (d.descricao) caracteristica,
           f.codcaracprod || ' - ' || (d.descricao) caracteristica,
           f.tipopalpul || '-' || (t.descricao) estrupul,
           f.tipopalpul || '-' || (t.descricao) estrupul,
           l.codigo || ' - ' || (l.descricao) pulmao,
           l.codigo || ' - ' || (l.descricao) pulmao,
           DECODE (f.tipoprod,
                   '1',
                   '1 - GRANDEZA',
                   '2',
                   '2 - MIUDEZA',
                   '3',
                   '3 - LEVEZA',
                   '4',
                   '4 - PERIGOSO',
                   '5',
                   '5 - EMBALADO')
               tipoprod,
           DECODE (f.tipoprod,
                   '1',
                   '1 - GRANDEZA',
                   '2',
                   '2 - MIUDEZA',
                   '3',
                   '3 - LEVEZA',
                   '4',
                   '4 - PERIGOSO',
                   '5',
                   '5 - EMBALADO')
               tipoprod,
         VSPROGRAMA,
         VSMAQUINA,
         VSUSUARIO,
         SYSDATE,
         VSOPERACAO
    FROM   pcprodfilial f,
           pcfornec c,
           pcprodutpicking k,
           pcendereco e,
           pccaracprod d,
           pctipopal l,
           pctipoestrutura t,
           pctipopal ll
   WHERE       :new.codprod = f.codprod
           AND k.codprod = :new.codprod
           AND k.codendereco = e.codendereco
           AND f.codfilial = e.codfilial
           AND d.codigo = f.codcaracprod
           AND l.codigo = f.tipopalpul
           AND k.tipoestrutura = t.codigo
           AND ll.codigo = k.tipoendereco
           AND :new.codfornec = c.codfornec);

END;
