CREATE OR REPLACE TRIGGER TRG_LOG_PCTRIBPISCOFINS
   BEFORE INSERT OR UPDATE OR DELETE
   ON PCTRIBPISCOFINS
   REFERENCING OLD AS OLD NEW AS NEW
   FOR EACH ROW
DECLARE
   VSEQUIPAMENTO   VARCHAR2(64);
   VSUSUARIO       VARCHAR2(30);
   VSPROGRAMA      VARCHAR2(48);
   VSTIPO          VARCHAR2(20);

   PROCEDURE GERARLOG(PNOMECOLUNA VARCHAR2, POLDVALUE VARCHAR2, PNEWVALUE VARCHAR2)
   IS
   BEGIN
      IF NVL(POLDVALUE, 'X') <> NVL(PNEWVALUE, 'X')
      THEN
         INSERT INTO PCLOGALTERACAODADOS
                     (DATA
                    , TABELA
                    , COLUNA
                    , CODIGO
                    , OBSERVACOES
                    , PROGRAMA
                    , TERMINAL
                    , OSUSER
                    , VALORALFAANT
                    , VALORALFA
                    , OPERACAO
                    , OBSERVACOES2)
              VALUES (SYSDATE
                    , 'PCTRIBPISCOFINS'
                    , PNOMECOLUNA
                    , DECODE(VSTIPO,'D',:OLD.CODTRIBPISCOFINS,:NEW.CODTRIBPISCOFINS)
                    , 'CODTRIBPISCOFINS: ' || DECODE(VSTIPO,'D',:OLD.CODTRIBPISCOFINS,:NEW.CODTRIBPISCOFINS)
                    , VSPROGRAMA
                    , VSEQUIPAMENTO
                    , VSUSUARIO
                    , POLDVALUE
                    , PNEWVALUE
                    , VSTIPO
                    , 'CODTRIBPISCOFINS: ' || :OLD.CODTRIBPISCOFINS);
      END IF;
   END;
BEGIN
   VSEQUIPAMENTO              := SUBSTR(SYS_CONTEXT('USERENV', 'TERMINAL'), 1, 64);
   VSUSUARIO                  := SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'), 1, 30);
   VSPROGRAMA                 := SUBSTR(SYS_CONTEXT('USERENV', 'MODULE'), 1, 48);

   IF UPDATING
   THEN
      VSTIPO                     := 'U';
   ELSIF INSERTING
   THEN
      VSTIPO                     := 'I';
   ELSE
      VSTIPO                     := 'D';
   END IF;

   /*Gerar Log*/
    GERARLOG('CODTRIBPISCOFINS', TO_CHAR(:OLD.CODTRIBPISCOFINS), TO_CHAR(:NEW.CODTRIBPISCOFINS));
    GERARLOG('DESCRICAOTRIBPISCOFINS', TO_CHAR(:OLD.DESCRICAOTRIBPISCOFINS), TO_CHAR(:NEW.DESCRICAOTRIBPISCOFINS));
    GERARLOG('CONSIDERAVLFIXOLIT', TO_CHAR(:OLD.CONSIDERAVLFIXOLIT), TO_CHAR(:NEW.CONSIDERAVLFIXOLIT));
    GERARLOG('UTILIZAPERCPISCOFINSDIFCONS', TO_CHAR(:OLD.UTILIZAPERCPISCOFINSDIFCONS), TO_CHAR(:NEW.UTILIZAPERCPISCOFINSDIFCONS));
    GERARLOG('CONSIDERAPRECOMERC', TO_CHAR(:OLD.CONSIDERAPRECOMERC), TO_CHAR(:NEW.CONSIDERAPRECOMERC));
    GERARLOG('CONSIDERAPAUTA', TO_CHAR(:OLD.CONSIDERAPAUTA), TO_CHAR(:NEW.CONSIDERAPAUTA));
    GERARLOG('VLPAUTAPIS', TO_CHAR(:OLD.VLPAUTAPIS), TO_CHAR(:NEW.VLPAUTAPIS));
    GERARLOG('VLPAUTACOFINS', TO_CHAR(:OLD.VLPAUTACOFINS), TO_CHAR(:NEW.VLPAUTACOFINS));
    GERARLOG('CONSIDERAIPI', TO_CHAR(:OLD.CONSIDERAIPI), TO_CHAR(:NEW.CONSIDERAIPI));
    GERARLOG('CONSIDERAST', TO_CHAR(:OLD.CONSIDERAST), TO_CHAR(:NEW.CONSIDERAST));
    GERARLOG('CONSIDERAOUTRASDESP', TO_CHAR(:OLD.CONSIDERAOUTRASDESP), TO_CHAR(:NEW.CONSIDERAOUTRASDESP));
    GERARLOG('CONSIDERAFRETE', TO_CHAR(:OLD.CONSIDERAFRETE), TO_CHAR(:NEW.CONSIDERAFRETE));
    GERARLOG('CONSIDERASUFRAMA', TO_CHAR(:OLD.CONSIDERASUFRAMA), TO_CHAR(:NEW.CONSIDERASUFRAMA));
    GERARLOG('RETERPISCOFINS', TO_CHAR(:OLD.RETERPISCOFINS), TO_CHAR(:NEW.RETERPISCOFINS));
    GERARLOG('PERCPIS', TO_CHAR(:OLD.PERCPIS), TO_CHAR(:NEW.PERCPIS));
    GERARLOG('PERCCOFINS', TO_CHAR(:OLD.PERCCOFINS), TO_CHAR(:NEW.PERCCOFINS));
    GERARLOG('SITTRIBUT', TO_CHAR(:OLD.SITTRIBUT), TO_CHAR(:NEW.SITTRIBUT));
    GERARLOG('SITTRIBUTDEV', TO_CHAR(:OLD.SITTRIBUTDEV), TO_CHAR(:NEW.SITTRIBUTDEV));
    GERARLOG('PERCPISCALCDI', TO_CHAR(:OLD.PERCPISCALCDI), TO_CHAR(:NEW.PERCPISCALCDI));
    GERARLOG('PERCCOFINSCALCDI', TO_CHAR(:OLD.PERCCOFINSCALCDI), TO_CHAR(:NEW.PERCCOFINSCALCDI));
    GERARLOG('BASEPISCOFINSLIT', TO_CHAR(:OLD.BASEPISCOFINSLIT), TO_CHAR(:NEW.BASEPISCOFINSLIT));
    GERARLOG('VLPISLIT', TO_CHAR(:OLD.VLPISLIT), TO_CHAR(:NEW.VLPISLIT));
    GERARLOG('VLCOFINSLIT', TO_CHAR(:OLD.VLCOFINSLIT), TO_CHAR(:NEW.VLCOFINSLIT));
    GERARLOG('MENSAGEMGERAL', TO_CHAR(:OLD.MENSAGEMGERAL), TO_CHAR(:NEW.MENSAGEMGERAL));
    GERARLOG('PERCPISCONSUMO', TO_CHAR(:OLD.PERCPISCONSUMO), TO_CHAR(:NEW.PERCPISCONSUMO));
    GERARLOG('PERCCOFINSCONSUMO', TO_CHAR(:OLD.PERCCOFINSCONSUMO), TO_CHAR(:NEW.PERCCOFINSCONSUMO));
    GERARLOG('SITTRIBUTCONSUMO', TO_CHAR(:OLD.SITTRIBUTCONSUMO), TO_CHAR(:NEW.SITTRIBUTCONSUMO));
    GERARLOG('SITTRIBUTCONSUMODEV', TO_CHAR(:OLD.SITTRIBUTCONSUMODEV), TO_CHAR(:NEW.SITTRIBUTCONSUMODEV));
    GERARLOG('MENSAGEMCONSUMO', TO_CHAR(:OLD.MENSAGEMCONSUMO), TO_CHAR(:NEW.MENSAGEMCONSUMO));
    GERARLOG('CONSIDERADIFALIQ', TO_CHAR(:OLD.CONSIDERADIFALIQ), TO_CHAR(:NEW.CONSIDERADIFALIQ));
    GERARLOG('GERABASEPISCOFINSSEMALIQ', TO_CHAR(:OLD.GERABASEPISCOFINSSEMALIQ), TO_CHAR(:NEW.GERABASEPISCOFINSSEMALIQ));
    GERARLOG('ALIQREDUCAOPIS', TO_CHAR(:OLD.ALIQREDUCAOPIS), TO_CHAR(:NEW.ALIQREDUCAOPIS));
    GERARLOG('ALIQREDUCAOCOFINS', TO_CHAR(:OLD.ALIQREDUCAOCOFINS), TO_CHAR(:NEW.ALIQREDUCAOCOFINS));
    GERARLOG('CONSIDERAPAUTAMINIMA', TO_CHAR(:OLD.CONSIDERAPAUTAMINIMA), TO_CHAR(:NEW.CONSIDERAPAUTAMINIMA));
    GERARLOG('SITTRIBUTPAUTAMIN', TO_CHAR(:OLD.SITTRIBUTPAUTAMIN), TO_CHAR(:NEW.SITTRIBUTPAUTAMIN));
    GERARLOG('SITTRIBUTDEVPAUTAMIN', TO_CHAR(:OLD.SITTRIBUTDEVPAUTAMIN), TO_CHAR(:NEW.SITTRIBUTDEVPAUTAMIN));
    GERARLOG('ZERARBCCSTST', TO_CHAR(:OLD.ZERARBCCSTST), TO_CHAR(:NEW.ZERARBCCSTST));
    GERARLOG('PERCREDBASCALPC', TO_CHAR(:OLD.PERCREDBASCALPC), TO_CHAR(:NEW.PERCREDBASCALPC));
    GERARLOG('CODEXCTRIBPISCOFINS', TO_CHAR(:OLD.CODEXCTRIBPISCOFINS), TO_CHAR(:NEW.CODEXCTRIBPISCOFINS));
    GERARLOG('EXCLUIRICMSBASEPISCOFINS', TO_CHAR(:OLD.EXCLUIRICMSBASEPISCOFINS), TO_CHAR(:NEW.EXCLUIRICMSBASEPISCOFINS));
    GERARLOG('EXCLUIRDIFALBASEPISCOFINS', TO_CHAR(:OLD.EXCLUIRDIFALBASEPISCOFINS), TO_CHAR(:NEW.EXCLUIRDIFALBASEPISCOFINS));

END;
