CREATE OR REPLACE VIEW VW_INT_C5_CARTAOPRESENTE AS
(
SELECT G.NUMGIFTCARD AS NROCARTAO,
       G.VALOR AS VALOR,
       'G' AS STATUS,
       CASE
         WHEN ((G.STATUS <> 'A') OR (G.DTINATIVO IS NOT NULL) OR
              (TRUNC(SYSDATE) >= G.DTVALIDADE)) THEN
          'N'
         ELSE
          'S'
       END ATIVO
  FROM PCCADGIFTCARD G,
       (SELECT S.ULTIMAEXECUCAO
          FROM PCCONTROLECONSINCO S
         WHERE UPPER(S.OBJETOREFERENCIA) =
               'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CARTAOPRESENTE') D
 WHERE NVL(G.DTALTERC5, D.ULTIMAEXECUCAO) >= D.ULTIMAEXECUCAO
)