CREATE OR REPLACE VIEW SQL_NFE_PARCELA_SAIDA_ST AS
SELECT DH.Numtransvendast AS NUM_TRANSACAO,
       DH.DUPLIC ||' - '||DH.PREST AS PRESTACAO,
       DH.DUPLIC,
       DH.PREST,
       DH.DTVENC AS DTVENC,
       SUM(NVL(DH.VALORENTFUT, DH.VALOR)) AS VALOR,
       DH.CODCOB AS CODCOB,
       0 AS VALORDESC,
       DH.CODCOBSEFAZ,
       DH.RAZAOCREDENCCARTAO AS RAZAO_CRED_CARTAO,
       DH.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       DH.NSUTEF AS NUMAUTOR_CARTAO,
       DH.BANDEIRACARTAO AS BANDEIRA_CARTAO,
       NVL(DH.CORRESPONDENTE, '2') AS TP_INTEGRA,
       MAX(DH.DATACONSOLIDACAOPREFAT) DATACONSOLIDACAOPREFAT,
       'N' PREFATURAMENTO,
       PCCOB.INDPAG,
	   DH.CNPJPAG,
       DH.UFPAG,
       DH.CNPJRECEB,
       DH.IDTERMPAG
FROM  PCPREST DH, PCNFSAID, PCCOB
WHERE DH.STATUS = 'A'
AND   DH.DTDESD IS NULL
AND   DH.DTESTORNO IS NULL
AND   PCNFSAID.NUMTRANSVENDA = DH.NUMTRANSVENDAST
AND   PCCOB.CODCOB = DH.CODCOB
AND   ((NVL(PCNFSAID.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAID.CODFILIAL) = 'S'))
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(DH.PERMITEESTORNO, 'S') = 'S'
AND   NVL(DH.VALOR, 0) > 0
GROUP BY DH.NUMTRANSVENDAST, DH.DUPLIC, DH.PREST, DH.CODCOB, DH.DTVENC,
         DH.CODCOBSEFAZ, DH.RAZAOCREDENCCARTAO, DH.CNPJCREDENCCARTAO, DH.NSUTEF, DH.BANDEIRACARTAO, DH.CORRESPONDENTE,PCCOB.INDPAG,
	     DH.CNPJPAG, DH.UFPAG, DH.CNPJRECEB, DH.IDTERMPAG
UNION ALL
SELECT DH.Numtransvendast AS NUM_TRANSACAO,
       DH.DUPLIC ||' - '||DH.PREST AS PRESTACAO,
       DH.DUPLIC,
       DH.PREST,
       DH.DTVENC AS DTVENC,
       SUM(NVL(DH.VALORENTFUT, DH.VALOR)) AS VALOR,
       DH.CODCOB AS CODCOB,
       0 AS VALORDESC,
       DH.CODCOBSEFAZ,
       DH.RAZAOCREDENCCARTAO AS RAZAO_CRED_CARTAO,
       DH.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       DH.NSUTEF AS NUMAUTOR_CARTAO,
       DH.BANDEIRACARTAO AS BANDEIRA_CARTAO,
       NVL(DH.CORRESPONDENTE, '2') AS TP_INTEGRA,
       MAX(DH.DATACONSOLIDACAOPREFAT) DATACONSOLIDACAOPREFAT,
       'S' PREFATURAMENTO,
       PCCOB.INDPAG,
	   DH.CNPJPAG,
       DH.UFPAG,
       DH.CNPJRECEB,
       DH.IDTERMPAG
FROM  PCPRESTPREFAT DH, PCNFSAIDPREFAT, PCCOB
WHERE DH.STATUS = 'A'
AND   DH.DTDESD IS NULL
AND   DH.DTESTORNO IS NULL
AND   PCNFSAIDPREFAT.NUMTRANSVENDA = DH.NUMTRANSVENDAST
AND   PCCOB.CODCOB = DH.CODCOB
AND   ((NVL(PCNFSAIDPREFAT.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAIDPREFAT.CODFILIAL) = 'S'))
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(DH.PERMITEESTORNO, 'S') = 'S'
AND   NVL(DH.VALOR, 0) > 0
AND   DH.DATACONSOLIDACAOPREFAT IS NULL
GROUP BY DH.NUMTRANSVENDAST, DH.DUPLIC, DH.PREST, DH.CODCOB, DH.DTVENC,
         DH.CODCOBSEFAZ, DH.RAZAOCREDENCCARTAO, DH.CNPJCREDENCCARTAO, DH.NSUTEF, DH.BANDEIRACARTAO, DH.CORRESPONDENTE,PCCOB.INDPAG,
	     DH.CNPJPAG, DH.UFPAG, DH.CNPJRECEB, DH.IDTERMPAG