CREATE OR REPLACE VIEW SQL_NFE_REF_SAIDA_COMP AS
SELECT PCNFSAID.NUMTRANSVENDA AS NUM_TRANSACAO,
       UF_E.UF AS SIGLA_UF,
       REPLACE(REPLACE(REPLACE(EMITENTE.CGC,'.',''),'/',''),'-','') AS CNPJ_E,       
       PCNFSAID.DTSAIDA AS DATA_EMISSAO,
       PCNFSAID.CHAVENFE AS CHAVE_ACESSO,
       DECODE(NVL(PCNFSAID.CHAVENFE,
                  '01'),
              '01',
              '01',
              '55') AS MODELO,
       DECODE(NVL(PCNFSAID.SERIE,
                  'U'),
              'U',
              '0',
              PCNFSAID.SERIE) AS SERIE,
       PCNFSAID.NUMNOTA AS NUMERO_NOTA
FROM   PCNFSAID,
       PCFORNEC EMITENTE,
       PCESTADO UF_E,
       PCCIDADE CIDADE_E,
       PCFILIAL
WHERE  NVL(PCNFSAID.CODFILIALNF,
           PCNFSAID.CODFILIAL) = PCFILIAL.CODIGO
AND    PCFILIAL.CODFORNEC = EMITENTE.CODFORNEC
AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE
AND    PCNFSAID.SERIE <> 'CF'
AND    CIDADE_E.UF = UF_E.UF 