CREATE OR REPLACE FUNCTION FNC_MENORVALORDISPONIVEL(VCAMPO  VARCHAR2,
                                                  VTABELA VARCHAR2)
  RETURN NUMBER IS
  MENOR_VALOR         NUMBER;
  VSQL                VARCHAR2(4000);
  VTAMANHOMAXIMOCAMPO NUMBER;
BEGIN

  BEGIN
    SELECT (POWER(10, U.DATA_PRECISION) - 1)
      INTO VTAMANHOMAXIMOCAMPO
      FROM USER_TAB_COLUMNS U
     WHERE U.COLUMN_NAME = UPPER(VCAMPO)
       AND U.TABLE_NAME = UPPER(VTABELA)
       AND U.DATA_SCALE = 0;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
  END;

  VSQL := ' SELECT MIN(T1.' || VCAMPO || ' + 1) ' ||
          ' FROM ( ' ||
          ' SELECT ' || VCAMPO || ', LEAD(' || VCAMPO ||') OVER (ORDER BY ' || VCAMPO || ') AS PROXIMO ' ||
		  ' FROM ' || VTABELA || ' ' || ' ) T1 ' ||
		  ' WHERE T1.PROXIMO IS NOT NULL ' ||
          ' AND T1.' || VCAMPO || ' + 1 < T1.PROXIMO' ||
		  ' AND T1.' || VCAMPO || ' > 0 ';

  EXECUTE IMMEDIATE VSQL INTO MENOR_VALOR;

  -- VERIFICA SE 1 ESTÁ AUSENTE COMO CASO INICIAL
  IF MENOR_VALOR IS NULL THEN
    VSQL := ' SELECT CASE ' || 
	        ' WHEN EXISTS (SELECT 1 FROM ' || VTABELA || ' WHERE ' || VCAMPO || ' = 1) THEN NULL ' || ' ELSE 1 ' ||
            ' END ' ||
			' FROM DUAL ';
  
    EXECUTE IMMEDIATE VSQL INTO MENOR_VALOR;
  END IF;

  IF MENOR_VALOR IS NULL THEN
    VSQL := ' SELECT MAX(' || VCAMPO || ') + 1 ' || ' FROM ' || VTABELA || ' ';
  
    EXECUTE IMMEDIATE VSQL INTO MENOR_VALOR;
  END IF;

  IF MENOR_VALOR > VTAMANHOMAXIMOCAMPO THEN
    RETURN NULL;
  END IF;

  RETURN MENOR_VALOR;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL; -- NENHUM INTERVALO FALTANTE ENCONTRADO
END FNC_MENORVALORDISPONIVEL;