CREATE OR REPLACE PACKAGE PKG_SINC_PDV_CONSINCO_UTIL IS

  TYPE TR_DADOS_PCFILAMENSAGEM IS RECORD(
    ROWPCFILAMENSAGEM PCFILAMENSAGEM%ROWTYPE);
  TYPE TB_DADOS_PCFILAMENSAGEM IS TABLE OF TR_DADOS_PCFILAMENSAGEM;

  PROCEDURE INSERIR_PCFILAMENSAGEM(P_PCFILAMENSAGEM TR_DADOS_PCFILAMENSAGEM);
  PROCEDURE INSERIR_PCFILAMENSAGEM_ERRO(P_PCFILAMENSAGEM TR_DADOS_PCFILAMENSAGEM,
                                        P_MSG_ERRO       VARCHAR2);

END PKG_SINC_PDV_CONSINCO_UTIL;
