CREATE OR REPLACE PACKAGE BODY pkg_sinc_pdv_consinco_util IS
  PROCEDURE INSERIR_PCFILAMENSAGEM(P_PCFILAMENSAGEM TR_DADOS_PCFILAMENSAGEM) IS
    DADOS_PCFILAMENSAGEM TR_DADOS_PCFILAMENSAGEM;
  BEGIN
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.IDMENSAGEM          := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.IDMENSAGEM;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.DATATRANSACAO       := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.DATATRANSACAO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CODFILIAL           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CODFILIAL;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.NUMCAIXA            := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.NUMCAIXA;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.NUMNOTA             := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.NUMNOTA;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.SERIE               := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.SERIE;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CHAVESEFAZ          := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CHAVESEFAZ;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.PROTOCOLO           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.PROTOCOLO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CONTINGENCIA        := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CONTINGENCIA;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.IDEXTERNO           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.IDEXTERNO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.STATUS              := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.STATUS;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.QTPROCESSAMENTO     := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.QTPROCESSAMENTO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPODOCUMENTO       := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPODOCUMENTO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPOOPERACAO        := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPOOPERACAO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.MENSAGEM            := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.MENSAGEM;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPOMENSAGEM        := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPOMENSAGEM;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CODIGOERRO          := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CODIGOERRO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.DATAULTIMAALTERACAO := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.DATAULTIMAALTERACAO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.PDVORIGEM           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.PDVORIGEM;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.QTREPROCESSADO      := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.QTREPROCESSADO;
    DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.SEQDOCTO            := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.SEQDOCTO;
  
    INSERT INTO PCFILAMENSAGEM S
    VALUES DADOS_PCFILAMENSAGEM.ROWPCFILAMENSAGEM;
  END INSERIR_PCFILAMENSAGEM;

  PROCEDURE INSERIR_PCFILAMENSAGEM_ERRO(P_PCFILAMENSAGEM TR_DADOS_PCFILAMENSAGEM,
                                        P_MSG_ERRO       VARCHAR2) IS
    ROWPCFILAMENSAGEMERRO PCFILAMENSAGEMERRO%ROWTYPE;
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    ROWPCFILAMENSAGEMERRO.IDMENSAGEM          := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.IDMENSAGEM;
    ROWPCFILAMENSAGEMERRO.DATATRANSACAO       := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.DATATRANSACAO;
    ROWPCFILAMENSAGEMERRO.CODFILIAL           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CODFILIAL;
    ROWPCFILAMENSAGEMERRO.NUMCAIXA            := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.NUMCAIXA;
    ROWPCFILAMENSAGEMERRO.NUMNOTA             := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.NUMNOTA;
    ROWPCFILAMENSAGEMERRO.SERIE               := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.SERIE;
    ROWPCFILAMENSAGEMERRO.CHAVESEFAZ          := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CHAVESEFAZ;
    ROWPCFILAMENSAGEMERRO.PROTOCOLO           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.PROTOCOLO;
    ROWPCFILAMENSAGEMERRO.CONTINGENCIA        := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CONTINGENCIA;
    ROWPCFILAMENSAGEMERRO.IDEXTERNO           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.IDEXTERNO;
    ROWPCFILAMENSAGEMERRO.STATUS              := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.STATUS;
    ROWPCFILAMENSAGEMERRO.QTPROCESSAMENTO     := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.QTPROCESSAMENTO;
    ROWPCFILAMENSAGEMERRO.TIPODOCUMENTO       := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPODOCUMENTO;
    ROWPCFILAMENSAGEMERRO.TIPOOPERACAO        := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPOOPERACAO;
    ROWPCFILAMENSAGEMERRO.MENSAGEM            := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.MENSAGEM;
    ROWPCFILAMENSAGEMERRO.TIPOMENSAGEM        := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.TIPOMENSAGEM;
    ROWPCFILAMENSAGEMERRO.CODIGOERRO          := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.CODIGOERRO;
    ROWPCFILAMENSAGEMERRO.DATAULTIMAALTERACAO := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.DATAULTIMAALTERACAO;
    ROWPCFILAMENSAGEMERRO.PDVORIGEM           := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.PDVORIGEM;
    ROWPCFILAMENSAGEMERRO.QTREPROCESSADO      := P_PCFILAMENSAGEM.ROWPCFILAMENSAGEM.QTREPROCESSADO;
    ROWPCFILAMENSAGEMERRO.DETALHE             := P_MSG_ERRO;
    --ROWPCFILAMENSAGEMERRO.SEQDOCTO            := SEQDOCTO;
  
    INSERT INTO PCFILAMENSAGEMERRO S VALUES ROWPCFILAMENSAGEMERRO;
  END INSERIR_PCFILAMENSAGEM_ERRO;
END PKG_SINC_PDV_CONSINCO_UTIL;
