DECLARE
  VCONSTRAINT USER_INDEXES.INDEX_NAME%TYPE;
  CURSOR C_CONSTRAINTS(PCONSTRAINT VARCHAR2) IS
    SELECT A.CONSTRAINT_NAME, A.TABLE_NAME
      FROM USER_CONSTRAINTS A
     WHERE A.TABLE_NAME = 'PCMENSAGEMMDFE'
       AND A.CONSTRAINT_NAME = PCONSTRAINT 
       AND A.INDEX_NAME IS NOT NULL;  
       
  CURSOR C_INDEXES IS
    SELECT A.INDEX_NAME, COUNT(B.COLUMN_NAME) QTDECOLUMN
      FROM USER_INDEXES A
         , USER_IND_COLUMNS B
     WHERE A.TABLE_NAME = 'PCMENSAGEMMDFE'
       AND A.INDEX_NAME = B.INDEX_NAME
       AND A.TABLE_NAME = B.TABLE_NAME
       AND A.INDEX_TYPE = 'NORMAL'
  GROUP BY A.INDEX_NAME;
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE PCMENSAGEMMDFE';
   
  FOR C IN C_INDEXES LOOP
    IF C.QTDECOLUMN <> 2 THEN
      VCONSTRAINT := C.INDEX_NAME;
      FOR C IN C_CONSTRAINTS(VCONSTRAINT) LOOP
        BEGIN
          EXECUTE IMMEDIATE 'ALTER TABLE ' || C.TABLE_NAME || ' DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
        EXCEPTION
          WHEN OTHERS THEN
            NULL;
        END;    
      END LOOP;   
             
      BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX ' || C.INDEX_NAME;
      EXCEPTION
        WHEN OTHERS THEN
          NULL;
      END;
    END IF;    
  END LOOP;
        
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCMENSAGEMMDFE MODIFY REJEICAOSEFAZ VARCHAR2(1) NOT NULL';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
      
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PCMENSAGEMMDFE ADD CONSTRAINT PCMENSAGEMMDFE_PK PRIMARY KEY (CODMENSAGEM, REJEICAOSEFAZ) USING INDEX TABLESPACE TS_INDICE';        
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;     

  FOR DADOS IN (
    SELECT 1   COD, 'MDF-E SENDO PROCESSADO PELO SERVIDOR LOCAL' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 100 COD, 'AUTORIZADO O USO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 101 COD, 'CANCELAMENTO DE MDF-E HOMOLOGADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 103 COD, 'ARQUIVO RECEBIDO COM SUCESSO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 104 COD, 'ARQUIVO PROCESSADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 105 COD, 'ARQUIVO EM PROCESSAMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 106 COD, 'ARQUIVO NÃO LOCALIZADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 107 COD, 'SERVIÇO EM OPERAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 108 COD, 'SERVIÇO PARALISADO MOMENTANEAMENTE (CURTO PRAZO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 109 COD, 'SERVIÇO PARALISADO SEM PREVISAO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 111 COD, 'CONSULTA NÃO ENCERRADOS LOCALIZOU MDF-E NESSA SITUAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 112 COD, 'CONSULTA NÃO ENCERRADOS NÃO LOCALIZOU MDF-E NESSA SITUAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 113 COD, 'CADASTRO DE TRANSPORTADOR ATUALIZADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 114 COD, 'CADASTRO DE FROTA ATUALIZADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 132 COD, 'ENCERRAMENTO DE MDF-E HOMOLOGADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 134 COD, 'EVENTO REGISTRADO COM ALERTA PARA SITUAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 138 COD, 'DOCUMENTOLOCALIZADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 135 COD, 'EVENTO REGISTRADO E VINCULADO A MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 136 COD, 'EVENTO REGISTRADO, MAS NÃO VINCULADO A MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 137 COD, 'EVENTO REGISTRADO COM ALERTA PARA SITUAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 202 COD, 'REJEIÇÃO: CPF DO EMITENTE DEFERE DO CPF DO CERTIFICADO DIGITAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 203 COD, 'REJEIÇÃO: EMISSOR NÃO HABILITADO PARA EMISSÃO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 204 COD, 'REJEIÇÃO: DUPLICIDADE DE MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 207 COD, 'REJEIÇÃO: CNPJ DO EMITENTE INVÁLIDO ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 209 COD, 'REJEIÇÃO: IE DO EMITENTE INVÁLIDA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 210 COD, 'REJEIÇÃO: CPF DO EMITENTE INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 212 COD, 'REJEIÇÃO: DATA DE EMISSÃO MDF-E POSTERIOR A DATA DE RECEBIMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 213 COD, 'REJEIÇÃO: CNPJ-BASE DO EMITENTE DIFERE DO CNPJ-BASE DO CERTIFICADO DIGITAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 214 COD, 'REJEIÇÃO: TAMANHO DA MENSAGEM EXCEDEU O LIMITE ESTABELECIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 215 COD, 'REJEIÇÃO: FALHA NO SCHEMA XML' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 216 COD, 'REJEIÇÃO: CHAVE DE ACESSO DIFERE DA CADASTRADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 217 COD, 'REJEIÇÃO: MDF-E NÃO CONSTA NA BASE DE DADOS DA SEFAZ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 218 COD, 'REJEIÇÃO: MDF-E JA ESTA CANCELADO NA BASE DE DADOS DA SEFAZ. [NPROT:999999999999999][DHCANC: AAAA MM-DDTHH:MM:SS TZD]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 219 COD, 'REJEIÇÃO: CIRCULACAO DO MDF-E VERIFICADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 220 COD, 'REJEIÇÃO: MDF-E AUTORIZADO HA MAIS DE 24 HORAS' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 222 COD, 'REJEIÇÃO: PROTOCOLO DE AUTORIZACAO DE USO DIFERE DO CADASTRADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 223 COD, 'REJEIÇÃO: CNPJ DO TRANSMISSOR DO ARQUIVO DIFERE DO CNPJ/CPF DO TRANSMISSOR DA CONSULTA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 225 COD, 'REJEIÇÃO: FALHA NO SCHEMA XML DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 226 COD, 'REJEIÇÃO: CODIGO DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 227 COD, 'REJEIÇÃO: ERRO NA COMPOSICAO DO CAMPO ID' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 228 COD, 'REJEIÇÃO: DATA DE EMISSÃO MUITO ATRASADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 229 COD, 'REJEIÇÃO: IE DO EMITENTE NÃO INFORMADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 230 COD, 'REJEIÇÃO: IE DO EMITENTE NÃO CADASTRADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 231 COD, 'REJEIÇÃO: IE DO EMITENTE NÃO VINCULADA AO CNPJ/CPF' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 232 COD, 'REJEIÇÃO: CNPJ DO EMITENTE COM SERIE INCOMPATIVEL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 233 COD, 'REJEIÇÃO: CPF DO EMITENTE COM SERIE INCOMPATIVEL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 234 COD, 'REJEIÇÃO: TIPO DE EMITENTE INVÁLIDO PARA EMITENTE PESSOA FISICA ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 236 COD, 'REJEIÇÃO: CHAVE DE ACESSO COM DIGITO VERIFICADOR INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 238 COD, 'REJEIÇÃO: CABECALHO - VERSAO DO ARQUIVO XML SUPERIOR A VERSAO VIGENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 239 COD, 'REJEIÇÃO: CABECALHO - VERSAO DO ARQUIVO XML NÃO SUPORTADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 242 COD, 'REJEIÇÃO: ELEMENTO MDFECABECMSG INEXISTENTE NO SOAP HEADER' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 243 COD, 'REJEIÇÃO: XML MAL FORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 245 COD, 'REJEIÇÃO: CNPJ EMITENTE NÃO CADASTRADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 247 COD, 'REJEIÇÃO: SIGLA DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 248 COD, 'REJEIÇÃO: UF DO RECIBO DIVERGE DA UF AUTORIZADORA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 249 COD, 'REJEIÇÃO: UF DA CHAVE DE ACESSO DIVERGE DA UF AUTORIZADORA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 250 COD, 'REJEIÇÃO: UF DIVERGE DA UF AUTORIZADORA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 252 COD, 'REJEIÇÃO: AMBIENTE INFORMADO DIVERGE DO AMBIENTE DE RECEBIMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 253 COD, 'REJEIÇÃO: DIGITO VERIFICADOR DA CHAVE DE ACESSO COMPOSTA INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 280 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 281 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR DATA VALIDADE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 282 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR SEM CNPJ/CPF' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 283 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR - ERRO CADEIA DE CERTIFICACAO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 284 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR REVOGADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 285 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR DIFERE ICP-BRASIL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 286 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR ERRO NO ACESSO A LCR' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 287 COD, 'REJEIÇÃO: CERTIFICADO TRANSMISSOR SEM CNPJ OU CPF' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 290 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 291 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA DATA VALIDADE ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 292 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA SEM CNPJ/CPF' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 293 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA - ERRO CADEIA DE CERTIFICACAO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 294 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA REVOGADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 295 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA DIFERE ICP-BRASIL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 296 COD, 'REJEIÇÃO: CERTIFICADO ASSINATURA ERRO NO ACESSO A LCR' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 297 COD, 'REJEIÇÃO: ASSINATURA DIFERE DO CALCULADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 298 COD, 'REJEIÇÃO: ASSINATURA DIFERE DO PADRAO DO PROJETO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 299 COD, 'REJEIÇÃO: XML DA AREA DE CABECALHO COM CODIFICACAO DIFERENTE DE UTF-8' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    
    SELECT 301 COD, 'REJEIÇÃO: O NCM DO PRODUTO PREDOMINANTE DA CARGA LOTAÇÃO DEVE SER INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 302 COD, 'REJEIÇÃO: AS INFORMAÇÕES DE PAGAMENTO DEVEM SER INFORMADAS PARA CARGA LOTAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 303 COD, 'REJEIÇÃO: DADOS BANCÁRIOS E DE PAGAMENTO DEVEM SER INFORMADOS PARA TAC E EQUIPARADO A TAC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 304 COD, 'REJEIÇÃO: CIOT DEVE SER INFORMADO PARA TAC E EQUIPARADO A TAC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION    

    SELECT 402 COD, 'REJEIÇÃO: XML DA AREA DE DADOS COM CODIFICACAO DIFERENTE DE UTF-8' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 404 COD, 'REJEIÇÃO: USO DE PREFIXO DE NAMESPACE NÃO PERMITIDO ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 405 COD, 'REJEIÇÃO: MUNICÍPIO DE CARREGAMENTO INEXISTENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 406 COD, 'REJEIÇÃO: MUNICÍPIO DE DESCARREGAMENTO INEXISTENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 407 COD, 'REJEIÇÃO: CODIGO DE MUNICÍPIO DIVERGE DA UF DO EMITENTE DO MDF-E ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 408 COD, 'REJEIÇÃO: MUNICÍPIO DO EMITENTE INEXISTENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 409 COD, 'REJEIÇÃO: CAMPO CUF INEXISTENTE NO ELEMENTO MDFECABECMSG DO SOAP HEADER' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 410 COD, 'REJEIÇÃO: UF INFORMADA NO CAMPO CUF NÃO A ATENDIDA PELO WEBSERVICE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 411 COD, 'REJEIÇÃO: CAMPO VERSAODADOS INEXISTENTE NO ELEMENTO MDFECABECMSG DO SOAP HEADER' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 412 COD, 'REJEIÇÃO: DATA DO REGISTRO SUPERIOR A DATA ATUAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 413 COD, 'REJEIÇÃO: DUPLICIDADE DE RNTRC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 414 COD, 'REJEIÇÃO: CNPJ DO TRANSPORTADOR INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 415 COD, 'REJEIÇÃO: CNPJ ASSOCIADO A OUTRO RNTRC EM SITUAÇÃO ATIVO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 416 COD, 'REJEIÇÃO: CPF DO TRANSPORTADOR AUTONOMO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 417 COD, 'REJEIÇÃO: CPF ASSOCIADO A OUTRO RNTRC EM SITUAÇÃO ATIVO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 418 COD, 'REJEIÇÃO: CPF NÃO PODE SER INFORMADO PARA CATEGORIA DIFERENTE DE TAC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 419 COD, 'REJEIÇÃO: CNPJ NÃO PODE SER INFORMADO PARA CATEGORIA TAC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 420 COD, 'REJEIÇÃO: RNTRC INEXISTENTE NA BASE DE DADOS DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 421 COD, 'REJEIÇÃO: RNTRC JA ESTA DESATIVADO NA BASE DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 422 COD, 'REJEIÇÃO: RNTRC JA ESTA EM SITUAÇÃO ATIVO NA BASE DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 423 COD, 'REJEIÇÃO: RNTRC INATIVO NA BASE DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 424 COD, 'REJEIÇÃO: PLACA INFORMADA JA ASSOCIADA A OUTRO RNTRC ATIVO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 425 COD, 'REJEIÇÃO: DUPLICIDADE DE VEÍCULO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 426 COD, 'REJEIÇÃO: PLACA INFORMADA PARA EXCLUSAO NÃO EXISTE ASSOCIADA AO RNTRC INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 454 COD, 'REJEIÇÃO: TIPO DE TRANSPORTADOR PARA CARGA PROPRIA E PROPRIETÁRIO DO VEÍCULO DIFERENTE DO EMITENTE DEVE SER TAC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 455 COD, 'REJEIÇÃO: CODIGO DE MUNICÍPIO DE CARREGAMENTO DO MDF-E: DIGITO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 456 COD, 'REJEIÇÃO: CODIGO DE MUNICÍPIO DIVERGE DA UF DE CARREGAMENTO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 457 COD, 'REJEIÇÃO: TIPO DE TRANSPORTADOR DEVE SER DIFERENTE DE TAC' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 458 COD, 'REJEIÇÃO: TIPO DE TRANSPORTADOR NÃO DEVE SER INFORMADO PARA EMITENTE DE CARGA PROPRIA PROPRIETÁRIO DO VEÍCULO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 459 COD, 'REJEIÇÃO: DOCUMENTO AUTORIZADO AO XML DUPLICADO NO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 460 COD, 'REJEIÇÃO: CONSULTA A UMA CHAVE DE ACESSO MUITO ANTIGA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 461 COD, 'REJEIÇÃO: MUNICÍPIO DE ENCERRAMENTO INVÁLIDO PARA ENCERRAMENTO EM TERRITORIO NACIONAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 462 COD, 'REJEIÇÃO: EXISTE MDF-E NÃO ENCERRADO HA MAIS DE 5 DIAS PARA PLACA COM ATE 2 UF DE PERCURSO INFORMADAS' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 473 COD, 'REJEIÇÃO: TIPO AUTORIZADOR DO RECIBO DIVERGE DO ORGAO AUTORIZADOR' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 479 COD, 'REJEIÇÃO: ENDEREÇO DO SITE DO PORTAL NACIONAL PARA A CONSULTA VIA QR CODE DIFERE DO PREVISTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 480 COD, 'REJEIÇÃO: O GRUPO DE INFORMAÇÕES DO QRCODE (INFMDFESUPL) DEVE SER INFORMADO ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 481 COD, 'REJEIÇÃO: PARÂMETRO CHAVE DE ACESSO NO QR CODE DIVERGE DA CHAVE DE ACESSO DO MDF-E ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 482 COD, 'REJEIÇÃO: SE TIPO DE EMISSÃO FOR IGUAL A CONTINGÊNCIA:O PARÂMETRO SIGN DEVE INFORMADO NO QR-CODE OBRIG' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 488 COD, 'REJEIÇÃO: SE TIPO DE EMISSÃO FOR IGUAL A NORMAL:O PARÂMETRO SIGN NÃO DEVE SER INFORMADO NO QR-CODE OBRIG.' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 489 COD, 'REJEIÇÃO: CNPJ INFORMADO INVÁLIDO (DV OU ZEROS)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 490 COD, 'REJEIÇÃO: CPF INFORMADO INVÁLIDO (DV OU ZEROS)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 491 COD, 'REJEIÇÃO: CNPJ-BASE CONSULTADO DIFERE DO CNPJ-BASE DO CERTIFICADO DIGITAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 492 COD, 'REJEIÇÃO: CPF CONSULTADO DIFERE DO CPF DO CERTIFICADO DIGITAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 493 COD, 'REJEIÇÃO: NÚMERO DO NSU INFORMADO SUPERIOR AO MAIOR NSU DA BASE DE DADOS DO AMBIENTE NACIONAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 494 COD, 'REJEIÇÃO: PROCESSO DE EMISSÃO INFORMADO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 496 COD, 'REJEIÇÃO: SE TIPO DE EMISSÃO FOR IGUAL A CONTINGÊNCIA:VALOR DA ASSINATURA (SIGN) DO QR-CODE DIFERE DO VALOR CALCULADO ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 518 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CTE MUITO ANTIGA [CHCTE:9999999999999999999999999999999999999999999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION  
    SELECT 519 COD, 'REJEIÇÃO: CHAVE DE ACESSO DA NFE INFORMADA MUITO ANTIGA [CHNFE:99999999999999999999999999999999999999999999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION  
    SELECT 520 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDFE INFORMADA MUITO ANTIGA [CHMDFE:99999999999999999999999999999999999999999999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION  
    SELECT 521 COD, 'REJEIÇÃO: PLACA DE VEÍCULO INVÁLIDA CONFORME SENATRAN' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION  
    SELECT 522 COD, 'REJEIÇÃO: PLACA INFORMADA NO VEÍCULO DE TRAÇÃO PERTENCE A UM VEÍCULO REBOCÁVEL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION  
    SELECT 523 COD, 'REJEIÇÃO: PELO MENOS UM REBOQUE DEVE SER COLOCADO NA COMPOSIÇÃO EM UM TRANSPORTE COM CAVALO MECÂNICO.' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION  
    SELECT 539 COD, 'REJEIÇÃO: DUPLICIDADE DE MDF-E, COM DIFERENCA NA CHAVE DE ACESSO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 540 COD, 'REJEIÇÃO: NÃO DEVE SER INFORMADO CONHECIMENTO DE TRANSPORTE PARA TIPO DE EMITENTE PRESTADOR SERVIÇO DE TRANSPORTE QUE EMITIRÁ CTE GLOBALIZADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 541 COD, 'REJEIÇÃO: TIPO DE EMITENTE INVÁLIDO PARA OPERAÇÕES INTERESTADUAIS OU COM EXTERIOR' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 577 COD, 'REJEIÇÃO: DUPLICIDADE DE CONDUTOR' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 578 COD, 'REJEIÇÃO: INFORMACOES DOS TOMADORES E OBRIGATORIA PARA ESTA OPERAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 579 COD, 'REJEIÇÃO: VERSAO INFORMADA PARA O MODAL NÃO SUPORTADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 580 COD, 'REJEIÇÃO: FALHA NO SCHEMA XML ESPECIFICO PARA O MODAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 588 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (UF INVÁLIDA)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 589 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (UF INVÁLIDA)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 590 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (UF INVÁLIDA)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 591 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (UF INVÁLIDA)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 592 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (ANO < 2012 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 593 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (MES = 0 OU MES > 12)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 594 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (CNPJ / CPF ZERADO OU DIGITO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 595 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (MODELO DIFERENTE DE 58)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 596 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (NÚMERO MDFE = 0)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 597 COD, 'REJEIÇÃO: CHAVE DE ACESSO INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 598 COD, 'REJEIÇÃO: USAR SOMENTE O NAMESPACE PADRAO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 599 COD, 'REJEIÇÃO: NÃO EH PERMITIDA A PRESENCA DE CARACTERES DE EDICAO NO INICIO/FIM DA MENSAGEM OU ENTRE AS TAGS DA MENSAGEM' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 600 COD, 'REJEIÇÃO: CHAVE DE ACESSO DIFERE DA EXISTENTE EM BD' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 601 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO CT-E INFORMADO INVÁLIDA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 602 COD, 'REJEIÇÃO: SEGUNDO CODIGO DE BARRAS DEVE SER INFORMADO PARA CT-E EM CONTINGENCIA FS-DA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 603 COD, 'REJEIÇÃO: SEGUNDO CODIGO DE BARRAS NÃO DEVE SER INFORMADO PARA CT-E COM ESTE TIPO DE EMISSÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 604 COD, 'REJEIÇÃO: CHAVE DE ACESSO DA NF-E INFORMADA INVÁLIDA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 605 COD, 'REJEIÇÃO: NF-E EMITIDA POR EMPRESA DIFERENTE DA EMPRESA EMITENTE DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 606 COD, 'REJEIÇÃO: SEGUNDO CODIGO DE BARRAS DEVE SER INFORMADO PARA NF-E EM CONTINGENCIA (FS-DA E FSIA)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 607 COD, 'REJEIÇÃO: SEGUNDO CODIGO DE BARRAS NÃO DEVE SER INFORMADO PARA NF-E COM ESTE TIPO DE EMISSÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 608 COD, 'REJEIÇÃO: NF EMITIDA POR EMPRESA DIFERENTE DA EMPRESA EMITENTE DO MDF-E ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 609 COD, 'REJEIÇÃO: MDF-E JA ESTA ENCERRADO NA BASE DE DADOS DA SEFAZ. [NPROT:999999999999999][DHENC: AAAA-MM DDTHH:MM:SS TZD]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 610 COD, 'REJEIÇÃO: EXISTE MDF-E NÃO ENCERRADO PARA ESTA PLACA, UF CARREGAMENTO E UF DESCARREGAMENTO EM DATA DE EMISSÃO DIFERENTE ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 611 COD, 'REJEIÇÃO: EXISTE MDF-E NÃO ENCERRADO PARA ESTA PLACA, TIPO DE EMITENTE E UF DESCARREGAMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 612 COD, 'REJEIÇÃO: CODIGO DE MUNICÍPIO DIVERGE DA UF DE DESCARREGAMENTO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 613 COD, 'REJEIÇÃO: CODIGO DE MUNICÍPIO DE ENCERRAMENTO: DIGITO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 614 COD, 'REJEIÇÃO: CODIGO DE MUNICÍPIO DIVERGE DA UF DE ENCERRAMENTO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 615 COD, 'REJEIÇÃO: DATA DE ENCERRAMENTO ANTERIOR A DATA DE AUTORIZACAO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 616 COD, 'REJEIÇÃO: NENHUM GRUPO DE DOCUMENTOS FOI INFORMADO (CT-E, CT, NF-E, NF, MDF-E) RETORNAR MUNICÍPIO DE DESCARREGAMENTO SEM DFE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 617 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (ANO < 2009 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 618 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (MES = 0 OU MES > 12)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 619 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (CNPJ ZERADO OU DIGITO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 620 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (MODELO DIFERENTE DE 57)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 621 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (NÚMERO CT = 0)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 622 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (ANO < 2005 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 623 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (MES = 0 OU MES > 12)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 624 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (CNPJ/CPF ZERADO OU DIGITO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 625 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (MODELO DIFERENTE DE 55)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 626 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (NÚMERO NF = 0)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 627 COD, 'REJEIÇÃO: CNPJ DO AUTOR DO EVENTO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 628 COD, 'REJEIÇÃO: ERRO ATRIBUTO ID DO EVENTO NÃO CORRESPONDE A CONCATENACAO DOS CAMPOS ("ID" +TPEVENTO + CHMDFE + NSEQEVENTO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 629 COD, 'REJEIÇÃO: O TPEVENTO INFORMADO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 630 COD, 'REJEIÇÃO: FALHA NO SCHEMA XML ESPECIFICO PARA O EVENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 631 COD, 'REJEIÇÃO: DUPLICIDADE DE EVENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 632 COD, 'REJEIÇÃO: O AUTOR DO EVENTO DIVERGE DO EMISSOR DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 633 COD, 'REJEIÇÃO: O AUTOR DO EVENTO NÃO A UM ORGAO AUTORIZADO A GERAR O EVENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 634 COD, 'REJEIÇÃO: A DATA DO EVENTO NÃO PODE SER MENOR QUE A DATA DE EMISSÃO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 635 COD, 'REJEIÇÃO: A DATA DO EVENTO NÃO PODE SER MAIOR QUE A DATA DO PROCESSAMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 636 COD, 'REJEIÇÃO: O NÚMERO SEQUENCIAL DO EVENTO A MAIOR QUE O PERMITIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 637 COD, 'REJEIÇÃO: A DATA DO EVENTO NÃO PODE SER MENOR QUE A DATA DE AUTORIZACAO DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 638 COD, 'REJEIÇÃO: NÃO DEVE SER INFORMADA NOTA FISCAL PARA TIPO DE EMITENTE PRESTADOR SERVIÇO DE TRANSPORTE.' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 639 COD, 'REJEIÇÃO: NÃO DEVE SER INFORMADO CONHECIMENTO DE TRANSPORTE PARA TIPO DE EMITENTE TRANSPORTE DE CARGA PROPRIA.' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 640 COD, 'REJEIÇÃO: CPF DO FUNCIONARIO DO REGISTRO DE PASSAGEM INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 641 COD, 'REJEIÇÃO: UF AUTORIZADORA DIFERE DA UF DE PASSAGEM' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 642 COD, 'REJEIÇÃO: REGISTRO DE PASSAGEM DESCARTADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 643 COD, 'REJEIÇÃO: PLACA DO VEÍCULO DE TRACAO DEVE SER INFORMADA NO REGISTRO DE PASSAGEM PARA O MODAL RODOVIARIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 644 COD, 'REJEIÇÃO: EVENTO DE INCLUSAO DE CONDUTOR SO PODE SER REGISTRADO PARA O MODAL RODOVIARIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 645 COD, 'REJEIÇÃO: CPF DO CONDUTOR INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 646 COD, 'REJEIÇÃO: PLACA DE VEÍCULO FORMATO INVÁLIDO (UF CARREGAMENTO E DESCARREGAMENTO <> "EX")' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 647 COD, 'REJEIÇÃO: MDF-E SO PODE SER REFERENCIADO POR MANIFESTO DO MODAL AQUAVIARIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 648 COD, 'REJEIÇÃO: MDF-E SO PODE SER REFERENCIADO QUANDO UF DE CARREGAMENTO/DESCARREGAMENTO FOR IGUAL A AM OU AP' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 649 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INFORMADA INVÁLIDA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 650 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (ANO < 2013 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 651 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (MES = 0 OU MES > 12)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 652 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (CNPJ/CPF ZERADO OU DIGITO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 653 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (MODELO DIFERENTE DE 58)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 654 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (NÚMERO MDF = 0)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 655 COD, 'REJEIÇÃO: MDF-E REFERENCIADO NÃO EXISTE NA BASE DE DADOS DA SEFAZ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 656 COD, 'REJEIÇÃO: CHAVE DE ACESSO DO MDF-E REFERENCIADO DIFERE DA EXISTENTE EM BD' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 657 COD, 'REJEIÇÃO: MDF-E REFERENCIADO JA ESTA CANCELADO NA BASE DE DADOS DA SEFAZ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 658 COD, 'REJEIÇÃO: MODAL DO MDF-E REFERENCIADO DIFERENTE DE RODOVIARIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 659 COD, 'REJEIÇÃO: TIPO DO EMITENTE DO MDF-E REFERENCIADO DIFERE DE TRANSPORTADOR DE CARGA PROPRIA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 660 COD, 'REJEIÇÃO: CNPJ AUTORIZADO PARA DOWNLOAD INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 661 COD, 'REJEIÇÃO: CPF AUTORIZADO PARA DOWNLOAD INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 662 COD, 'REJEIÇÃO: EXISTE MDF-E ABERTO PARA A PLACA DO VEÍCULO TRACAO CONTENDO DOCUMENTO RELACIONADO NO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 663 COD, 'REJEIÇÃO: PERCURSO INFORMADO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 664 COD, 'REJEIÇÃO: VEDADA A EMISSÃO DE CONHECIMENTO DE TRANSPORTE EM PAPEL CT-E OBRIGATORIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 665 COD, 'REJEIÇÃO: EMITENTE DA NOTA FISCAL A OBRIGADO A EMISSÃO DE NOTA FISCAL ELETRONICA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 666 COD, 'REJEIÇÃO: ANO DO MDF-E INFORMADO NA CHAVE DE ACESSO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 667 COD, 'REJEIÇÃO: QUANTIDADE INFORMADA NO GRUPO DE TOTALIZADORES NÃO CONFERE COM A QUANTIDADE DE DOCUMENTOS RELACIONADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 668 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E DUPLICADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 669 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E DUPLICADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 670 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE CT-E INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 671 COD, 'REJEIÇÃO: CT-E INFORMADO NÃO EXISTE NA BASE DE DADOS DA SEFAZ ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 672 COD, 'REJEIÇÃO: CT-E INFORMADO COM DIFERENCA DE CHAVE DE ACESSO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 673 COD, 'REJEIÇÃO: CT-E INFORMADO NÃO PODE ESTAR CANCELADO/DENEGADO NA BASE DA SEFAZ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 674 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NF-E INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 675 COD, 'REJEIÇÃO: NF-E INFORMADA NÃO EXISTE NA BASE DE DADOS DA SEFAZ [CHNFE: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 676 COD, 'REJEIÇÃO: NF-E INFORMADA COM DIFERENCA DE CHAVE DE ACESSO [CHNFE:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 677 COD, 'REJEIÇÃO: NF-E INFORMADA NÃO PODE ESTAR CANCELADA/DENEGADA NA BASE DA SEFAZ [CHNFE:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 678 COD, 'REJEIÇÃO: USO INDEVIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 679 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE MDF-E INVÁLIDA (TIPO DE EMISSÃO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 680 COD, 'REJEIÇÃO: MUNICÍPIO DE DESCARREGAMENTO DUPLICADO NO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 681 COD, 'REJEIÇÃO: RNTRC INFORMADO INEXISTENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 682 COD, 'REJEIÇÃO: RNTRC SITUAÇÃO INVÁLIDA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 683 COD, 'REJEIÇÃO: PLACA DO VEÍCULO DE TRACAO NÃO VINCULADA AO RNTRC INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 684 COD, 'REJEIÇÃO: CIOT OBRIGATORIO PARA RNTRC INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 685 COD, 'REJEIÇÃO: MUNICÍPIO DE CARREGAMENTO DUPLICADO NO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 686 COD, 'REJEIÇÃO: EXISTE MDF-E NÃO ENCERRADO HA MAIS DE 30 DIAS PARA O EMITENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 687 COD, 'REJEIÇÃO: RNTRC DEVE ESTAR ASSOCIADO AO TRANSPORTADOR INDICADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 688 COD, 'REJEIÇÃO: RNTRC DEVE SER INFORMADO PARA PRESTADOR DE SERVIÇO DE TRANSPORTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 689 COD, 'REJEIÇÃO: MUNICÍPIO DE ENCERRAMENTO DEVE SER 9999999 PARA ENCERRAMENTO NO EXTERIOR' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 690 COD, 'REJEIÇÃO: A DATA DO REGISTRO DE PASSAGEM NÃO PODE SER MAIOR QUE A DATA DE PROCESSAMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 691 COD, 'REJEIÇÃO: MDF-E EM SITUAÇÃO QUE IMPEDE LIBERAR PRAZO DE CANCELAMENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 692 COD, 'REJEIÇÃO: UF NÃO TEM PERMISSAO DE LIBERAR PRAZO DE CANCELAMENTO PARA O CT-E INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 693 COD, 'REJEIÇÃO: DATA DE INICIO DA VIGENCIA INFERIOR A DATA ATUAL ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 694 COD, 'REJEIÇÃO: DATA DE FIM DA VIGENCIA SUPERIOR A 6 MESES DA DATA ATUAL' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 695 COD, 'REJEIÇÃO: DATA DE FIM DA VIGENCIA INFERIOR A DATA DE INICIO DA VIGENCIA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 696 COD, 'REJEIÇÃO: EVENTO DE LIBERACAO DE PRAZO DE CANCELAMENTO INEXISTENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 697 COD, 'REJEIÇÃO: EVENTO DE LIBERACAO DE PRAZO DE CANCELAMENTO JA ESTA ANULADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 698 COD, 'REJEIÇÃO: SEGURO DA CARGA E OBRIGATORIO PARA MODAL PRESTADOR DE SERVIÇO DE TRANSPORTE NO MODAL RODOVIARIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 699 COD, 'REJEIÇÃO: DADOS DO SEGURO DE CARGA INCOMPLETOS PARA O MODAL RODOVIARIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 700 COD, 'REJEIÇÃO: CPF DO AUTOR DO EVENTO INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 701 COD, 'REJEIÇÃO: TIPO DE EVENTO INCOMPATIVEL COM EMITENTE PESSOA FISICA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 702 COD, 'REJEIÇÃO: MODAL INVÁLIDO PARA ENTREGA PARCIAL(APENAS MODAL AEREO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 703 COD, 'REJEIÇÃO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR, DEVE SER INFORMADO APENAS UM MUNICÍPIO DE CARREGAMENTO E UM MUNICÍPIO DE DESCARREGAMENTO(DEVEM SER IGUAIS)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 704 COD, 'REJEIÇÃO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), UF DE CARREGAMENTO DEVE SER IGUAL A UF DE DESCARREGAMENTO E DIFERENTES DE EX ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 705 COD, 'REJEIÇÃO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), MODAL DEVE SER RODOVIÁRIO ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 706 COD, 'REJEIÇÃO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), OS GRUPOS DE DOCUMENTOS RANSPORTADOS NÃO DEVEM SER INFORMADOS (CT-E, NF-E E MDF-E)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 707 COD, 'REJEIÇÃO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), O TIPO DO EMITENTE DEVE SER TRANSPORTE PRÓPRIO (2)  ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 708 COD, 'REJEIÇÃO: MDFE DEVE POSSUI INDICAÇÃO DE CARREGAMENTO POSTERIOR PARA INCLUSÃO DE DF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 709 COD, 'REJEIÇÃO: CHAVE DE ACESSO DE NFE INVÁLIDA NO EVENTO DE INCLUSÃO [MOTIVO: CNPJ/CPF INVÁLIDO / MODELO DIFERENTE DE 55 / ANO INVÁLIDO (< 2006) / MÊS INVÁLIDO (0 OU > 12) / TIPO DE EMISSÃO INVÁLIDO / UF INVÁLIDA / NÚMERO ZERADO / DV INVÁLIDO]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 710 COD, 'REJEIÇÃO: CANCELAMENTO NÃO É PERMITIDO PARA MDFE COM INDICAÇÃO DE CARREGAMENTO POSTERIOR QUE JÁ REALIZOU INSERÇÃO DE DF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 711 COD, 'REJEIÇÃO: NFE JÁ ESTÁ VINCULADA AO MDFE POR OUTRO EVENTO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION    
    SELECT 712 COD, 'REJEIÇÃO: EXISTE MDF-E COM INDICAÇÃO DE CARREGAMENTO POSTERIOR(INDCARREGAPOSTERIOR=1) SEM EVENTO DE INCLUSÃO DE DF-E HÁ MAIS DE 168 HORAS PARAO MESMO CNPJ / CPF DO EMITENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 713 COD, 'REJEIÇÃO: CNPJ DO DESENVOLVEDOR DO SISTEMA INVÁLIDO (ZERADO OU DIGITO INVÁLIDO)' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 714 COD, 'REJEIÇÃO: MUNICÍPIO DE ENCERRAMENTO INEXISTENTE' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 715 COD, 'REJEIÇÃO: NÃO É PERMITIDO ENCERRAR MDFE COM INDICAÇÃO DE CARREGAMENTO POSTERIOR SEM INCLUSÃO DE DF-E ASSOCIADA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 716 COD, 'REJEIÇÃO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO CIOT(INFCIOT): REJEITAR SE O CPF/CNPJ DO RESPONSÁVEL PELA GERAÇÃO DO CIOT INFORMADO ESTIVER INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 717 COD, 'REJEIÇÃO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO CONTRATANTE(INFCONTRATANTE): REJEITAR SE O CPF/CNPJ INFORMADO PARA O CONTRATANTE ESTIVER INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 718 COD, 'REJEIÇÃO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO(VEICTRACAO/PROP): REJEITAR SE O CPF/CNPJ INFORMADO PARA O PROPRIETÁRIO ESTIVER INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 719 COD, 'REJEIÇÃO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO PROPRIETÁRIO DO VEÍCULO REBOQUE(VEICREBOQUE/PROP): REJEITAR SE O CPF/CNPJ INFORMADO PARA O PROPRIETÁRIO ESTIVER INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 722 COD, 'REJEIÇÃO: MDF-E DEVE SER DO MODAL RODOVIÁRIO PARA O EVENTO PAGAMENTO DE MDF' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 723 COD, 'REJEIÇÃO: O TIPO DO PROPRIETÁRIO DO MDF-E DEVE SER DO TIPO TAC AGREGADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 724 COD, 'REJEIÇÃO: GRUPO DE INFORMAÇÕES DO PAGAMENTO A PRAZO DEVE SER INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 725 COD, 'REJEIÇÃO: GRUPO PRODUTO PREDOMINANTE DEVE SER INFORMADO PARA MODAL RODOVIÁRIO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 726 COD, 'REJEIÇÃO: O GRUPO DE INFORMAÇÕES DA CARGA LOTAÇÃO DEVE SER INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 727 COD, 'REJEIÇÃO: CNPJ/CPF DO RESPONSÁVEL PELO PAGAMENTO DO FRETE INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 728 COD, 'REJEIÇÃO: CNPJ DA INSTITUIÇÃO DE PAGAMENTO ELETRÔNICO DO FRETE INVÁLIDO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 729 COD, 'REJEIÇÃO: GRUPO DE INFORMAÇÕES DO PAGAMENTO A PRAZO NÃO DEVE SER INFORMADO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 735 COD, 'REJEIÇÃO: NÚMERO DA PARCELA INVÁLIDO [NPARCELA:999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 736 COD, 'REJEIÇÃO: DATA DE VENCIMENTO DA PARCELA MENOR QUE A DATA DE EMISSÃO [NPARCELA:999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 737 COD, 'REJEIÇÃO: DATA DE VENCIMENTO DA PARCELA MENOR QUE A DATA DA PARCELA ANTERIOR [NPARCELA: 999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 738 COD, 'REJEIÇÃO: SOMATÓRIO DO VALOR DAS PARCELAS DIFERENTE DO VALOR DO CONTRATO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 739 COD, 'REJEIÇÃO: VALOR DO ADIANTAMENTO NÃO PODE SER INFORMADO PARA PAGAMENTO A VISTA' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 740 COD, 'REJEIÇÃO: O PROPRIETÁRIO DO VEÍCULO QUANDO INFORMADO DEVE SER DIFERENTE DO EMITENTE DO MDF-E' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 741 COD, 'REJEIÇÃO: O CONTRATANTE DEVE SER IGUAL AO EMITENTE DO MDF-E QUANDO INDICADO PROPRIETÁRIO DO VEÍCULO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 742 COD, 'REJEIÇÃO: CONTRATANTE INFORMADO DUPLICADO [CONTRATANTE: 99999999999]' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 743 COD, 'REJEIÇÃO: O TIPO DE TRANSPORTADOR DEVE SER TAC QUANDO INFORMADO CPF DO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 744 COD, 'REJEIÇÃO: O TIPO DE TRANSPORTADOR DEVE SER ETC OU CTE QUANDO INFORMADO CNPJ DO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 745 COD, 'REJEIÇÃO: O TIPO DE TRANSPORTADOR NÃO SER INFORMADO QUANDO NÃO ESTIVER INFORMADO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 746 COD, 'REJEIÇÃO: A SOMA DOS COMPONENTES DO PAGAMENTO DEVE SER IGUAL AO VALOR DO CONTRATO ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 999 COD, 'REJEIÇÃO: ERRO NÃO CATALOGADO (INFORMAR A MSG DE ERRO CAPTURADO NO TRATAMENTO DA EXCECAO) ' DESCRICAO, 'S' REJEICAOSEFAZ FROM DUAL UNION
  
    SELECT 1002 COD, 'QUANTIDADE MÁXIMA DE 10 CARACTERES PERMITIDOS PARA O CODIGO DO VEÍCULO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1003 COD, 'PLACA DO VEÍCULO NÃO INFORMADO OU INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1004 COD, 'QUANTIDADE MÁXIMA DE 06 CARACTERES PERMITIDOS PARA A TARA DO VEÍCULO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1005 COD, 'QUANTIDADE MÁXIMA DE 06 CARACTERES PERMITIDOS PARA A CAPACIDADE EM KG DO VEÍCULO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1006 COD, 'QUANTIDADE MÁXIMA DE 03 CARACTERES PERMITIDOS PARA A CAPACIDADE M3 DO VEÍCULO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1007 COD, 'CNPJ OU CPF INVÁLIDO OU NÃO INFORMADO NO CADASTRO DO VEÍCULO CAMPO PROPRIETÁRIO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1008 COD, 'RNTRC DO PROPRIETÁRIO DO VEÍCULO INVÁLIDO OU NÃO INFORMADO. VALIDAR NO CADASTRO DO VEÍCULO(DEVE TER TAMANHO IGUAL A 8)' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1009 COD, 'O NOME DO PROPRIETÁRIO DO VEÍCULO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1010 COD, 'A INSCRICAO ESTADUAL DO PROPRIETÁRIO DO VEÍCULO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1011 COD, 'A UF DO PROPRIETÁRIO DO VEÍCULO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1012 COD, 'TIPO PROPRIETÁRIO INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1013 COD, 'NOME DO MOTORISTA DO VEÍCULO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1014 COD, 'CPF DO MOTORISTA DO VEÍCULO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1015 COD, 'TIPO DE RODADO INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1016 COD, 'TIPO DE CARROCERIA INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1017 COD, 'UF DO VEÍCULO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1018 COD, 'TIPO AMBIENTE INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1019 COD, 'VALOR TOTAL DO MDFE NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1020 COD, 'CODIGO DO MUNICÍPIO DE DESCARREGAMENTO INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1021 COD, 'PLACA DO VEÍCULO DE REBOQUE DEVE TER 07 CARACTERES ' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1022 COD, 'QUANTIDADE MÁXIMA DE 06 CARACTERES PERMITIDOS PARA A TARA DO VEÍCULO DE REBOQUE' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1023 COD, 'QUANTIDADE MÁXIMA DE 06 CARACTERES PERMITIDOS PARA A CAPACIDADE EM KG DO VEÍCULO DE REBOQUE' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1024 COD, 'QUANTIDADE MINIMA DE 09 OU MÁXIMA DE 11 CARACTERES PERMITIDOS PARA O RENAVAM DO VEÍCULO DE REBOQUE' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1025 COD, 'NÚMERO ONU/UN DO GRUPO PERI INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1026 COD, 'QUANTIDADE TOTAL POR PRODUTO DO GRUPO PERI INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1027 COD, 'INFORMACOES DO RESPONSÁVEL PELO SEGURO DA CARGA NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1028 COD, 'RESPONSÁVEL PELO SEGURO NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1029 COD, 'RESPONSÁVEL PELO SEGURO NÃO INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1030 COD, 'NÚMERO DO CNPJ DO RESPONSÁVEL PELO SEGURO NÃO INFORAMDO ' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1031 COD, 'NÚMERO DO CNPJ DO RESPONSÁVEL PELO SEGURO INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1032 COD, 'NOME DA SEGURADORA NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1033 COD, 'NOME DA SEGURADORA INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1034 COD, 'NÚMERO DO CNPJ DA SEGURADORA INVÁLIDO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1035 COD, 'NÚMERO DO CNPJ DA SEGURADORA NÃO INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1036 COD, 'RNTRC DO EMITENTE DO MDFE INVÁLIDO OU NÃO INFORMADO. VALIDAR NO CADASTRO DA FILIAL, ROTINA 535(DEVE TER TAMANHO IGUAL A 8)' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1037 COD, 'CNPJ/CPF DO CONTRATANTE DO SERVIÇO INVÁLIDO(VALIDAR TOMADOR DO CTE)' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1038 COD, 'TIPO DE PREDOMINÂNCIA DO PRODUTO NÃO INFORMADA. VALIDAR CADASTRO DO PRODUTO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1039 COD, 'DESCRIÇÃO DO PRODUTO NÃO INFORMADA OU INVÁLIDA. VALIDAR CADASTRO DO PRODUTO (DEVE ESTAR COM TAMANHO ENTRE 2 E 120)' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1040 COD, 'EAN DO PRODUTO PREDOMINANTE INVÁLIDO OU NÃO INFORMADO. VALIDAR CADASTRO DO PRODUTO PREDOMINANTE DO MDFE' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1041 COD, 'NCM DO PRODUTO PREDOMINANTE INVÁLIDO OU NÃO INFORMADO. VALIDAR CADASTRO DO PRODUTO PREDOMINANTE DO MDFE' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL UNION
    SELECT 1042 COD, 'PARA MDFE DE CTE, O PRODUTO PREDOMINANTE DEVE SER INFORMADO' DESCRICAO, 'N' REJEICAOSEFAZ FROM DUAL 
  ) LOOP
    INSERT INTO PCMENSAGEMMDFE (CODMENSAGEM, REJEICAOSEFAZ, DESCRICAO) VALUES(DADOS.COD, DADOS.REJEICAOSEFAZ, substr(DADOS.DESCRICAO, 0, 180));
  END LOOP;
  COMMIT;
END;
