DECLARE 
  iCOUNT Integer;
BEGIN     

  FOR DADOS IN (
    SELECT 100 COD, 'AUTORIZADO O USO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 101 COD, 'CANCELAMENTO DE MDF-E HOMOLOGADO' DESCRICAO FROM DUAL UNION
    SELECT 103 COD, 'ARQUIVO RECEBIDO COM SUCESSO' DESCRICAO FROM DUAL UNION
    SELECT 104 COD, 'ARQUIVO PROCESSADO' DESCRICAO FROM DUAL UNION
    SELECT 105 COD, 'ARQUIVO EM PROCESSAMENTO' DESCRICAO FROM DUAL UNION
    SELECT 106 COD, 'ARQUIVO NAO LOCALIZADO' DESCRICAO FROM DUAL UNION
    SELECT 107 COD, 'SERVICO EM OPERACAO' DESCRICAO FROM DUAL UNION
    SELECT 108 COD, 'SERVICO PARALISADO MOMENTANEAMENTE (CURTO PRAZO)' DESCRICAO FROM DUAL UNION
    SELECT 109 COD, 'SERVICO PARALISADO SEM PREVISAO' DESCRICAO FROM DUAL UNION
    SELECT 111 COD, 'CONSULTA NAO ENCERRADOS LOCALIZOU MDF-E NESSA SITUACAO' DESCRICAO FROM DUAL UNION
    SELECT 112 COD, 'CONSULTA NAO ENCERRADOS NAO LOCALIZOU MDF-E NESSA SITUACAO' DESCRICAO FROM DUAL UNION
    SELECT 113 COD, 'CADASTRO DE TRANSPORTADOR ATUALIZADO' DESCRICAO FROM DUAL UNION
    SELECT 114 COD, 'CADASTRO DE FROTA ATUALIZADO' DESCRICAO FROM DUAL UNION
    SELECT 132 COD, 'ENCERRAMENTO DE MDF-E HOMOLOGADO' DESCRICAO FROM DUAL UNION
    SELECT 134 COD, 'EVENTO REGISTRADO COM ALERTA PARA SITUACAO' DESCRICAO FROM DUAL UNION
    SELECT 138 COD, 'DOCUMENTOLOCALIZADO' DESCRICAO FROM DUAL UNION
    SELECT 135 COD, 'EVENTO REGISTRADO E VINCULADO A MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 136 COD, 'EVENTO REGISTRADO, MAS NAO VINCULADO A MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 137 COD, 'EVENTO REGISTRADO COM ALERTA PARA SITUACAO' DESCRICAO FROM DUAL UNION
    SELECT 202 COD, 'REJEICAO: CPF DO EMITENTE DEFERE DO CPF DO CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION
    SELECT 203 COD, 'REJEICAO: EMISSOR NAO HABILITADO PARA EMISSAO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 204 COD, 'REJEICAO: DUPLICIDADE DE MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 207 COD, 'REJEICAO: CNPJ DO EMITENTE INVALIDO ' DESCRICAO FROM DUAL UNION
    SELECT 209 COD, 'REJEICAO: IE DO EMITENTE INVALIDA' DESCRICAO FROM DUAL UNION
    SELECT 210 COD, 'REJEICAO: CPF DO EMITENTE INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 212 COD, 'REJEICAO: DATA DE EMISSAO MDF-E POSTERIOR A DATA DE RECEBIMENTO' DESCRICAO FROM DUAL UNION
    SELECT 213 COD, 'REJEICAO: CNPJ-BASE DO EMITENTE DIFERE DO CNPJ-BASE DO CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION
    SELECT 214 COD, 'REJEICAO: TAMANHO DA MENSAGEM EXCEDEU O LIMITE ESTABELECIDO' DESCRICAO FROM DUAL UNION
    SELECT 215 COD, 'REJEICAO: FALHA NO SCHEMA XML' DESCRICAO FROM DUAL UNION
    SELECT 216 COD, 'REJEICAO: CHAVE DE ACESSO DIFERE DA CADASTRADA' DESCRICAO FROM DUAL UNION
    SELECT 217 COD, 'REJEICAO: MDF-E NAO CONSTA NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION
    SELECT 218 COD, 'REJEICAO: MDF-E JA ESTA CANCELADO NA BASE DE DADOS DA SEFAZ. [NPROT:999999999999999][DHCANC: AAAA MM-DDTHH:MM:SS TZD]' DESCRICAO FROM DUAL UNION
    SELECT 219 COD, 'REJEICAO: CIRCULACAO DO MDF-E VERIFICADA' DESCRICAO FROM DUAL UNION
    SELECT 220 COD, 'REJEICAO: MDF-E AUTORIZADO HA MAIS DE 24 HORAS' DESCRICAO FROM DUAL UNION
    SELECT 222 COD, 'REJEICAO: PROTOCOLO DE AUTORIZACAO DE USO DIFERE DO CADASTRADO' DESCRICAO FROM DUAL UNION
    SELECT 223 COD, 'REJEICAO: CNPJ DO TRANSMISSOR DO ARQUIVO DIFERE DO CNPJ/CPF DO TRANSMISSOR DA CONSULTA' DESCRICAO FROM DUAL UNION
    SELECT 225 COD, 'REJEICAO: FALHA NO SCHEMA XML DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 226 COD, 'REJEICAO: CODIGO DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 227 COD, 'REJEICAO: ERRO NA COMPOSICAO DO CAMPO ID' DESCRICAO FROM DUAL UNION
    SELECT 228 COD, 'REJEICAO: DATA DE EMISSAO MUITO ATRASADA' DESCRICAO FROM DUAL UNION
    SELECT 229 COD, 'REJEICAO: IE DO EMITENTE NAO INFORMADA' DESCRICAO FROM DUAL UNION
    SELECT 230 COD, 'REJEICAO: IE DO EMITENTE NAO CADASTRADA' DESCRICAO FROM DUAL UNION
    SELECT 231 COD, 'REJEICAO: IE DO EMITENTE NAO VINCULADA AO CNPJ/CPF' DESCRICAO FROM DUAL UNION
    SELECT 232 COD, 'REJEICAO: CNPJ DO EMITENTE COM SERIE INCOMPATIVEL' DESCRICAO FROM DUAL UNION
    SELECT 233 COD, 'REJEICAO: CPF DO EMITENTE COM SERIE INCOMPATIVEL' DESCRICAO FROM DUAL UNION
    SELECT 234 COD, 'REJEICAO: TIPO DE EMITENTE INVALIDO PARA EMITENTE PESSOA FISICA ' DESCRICAO FROM DUAL UNION
    SELECT 236 COD, 'REJEICAO: CHAVE DE ACESSO COM DIGITO VERIFICADOR INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 238 COD, 'REJEICAO: CABECALHO - VERSAO DO ARQUIVO XML SUPERIOR A VERSAO VIGENTE' DESCRICAO FROM DUAL UNION
    SELECT 239 COD, 'REJEICAO: CABECALHO - VERSAO DO ARQUIVO XML NAO SUPORTADA' DESCRICAO FROM DUAL UNION
    SELECT 242 COD, 'REJEICAO: ELEMENTO MDFECABECMSG INEXISTENTE NO SOAP HEADER' DESCRICAO FROM DUAL UNION
    SELECT 243 COD, 'REJEICAO: XML MAL FORMADO' DESCRICAO FROM DUAL UNION
    SELECT 245 COD, 'REJEICAO: CNPJ EMITENTE NAO CADASTRADO' DESCRICAO FROM DUAL UNION
    SELECT 247 COD, 'REJEICAO: SIGLA DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 248 COD, 'REJEICAO: UF DO RECIBO DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 249 COD, 'REJEICAO: UF DA CHAVE DE ACESSO DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 250 COD, 'REJEICAO: UF DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 252 COD, 'REJEICAO: AMBIENTE INFORMADO DIVERGE DO AMBIENTE DE RECEBIMENTO' DESCRICAO FROM DUAL UNION
    SELECT 253 COD, 'REJEICAO: DIGITO VERIFICADOR DA CHAVE DE ACESSO COMPOSTA INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 280 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 281 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR DATA VALIDADE' DESCRICAO FROM DUAL UNION
    SELECT 282 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR SEM CNPJ/CPF' DESCRICAO FROM DUAL UNION
    SELECT 283 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR - ERRO CADEIA DE CERTIFICACAO' DESCRICAO FROM DUAL UNION
    SELECT 284 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR REVOGADO' DESCRICAO FROM DUAL UNION
    SELECT 285 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR DIFERE ICP-BRASIL' DESCRICAO FROM DUAL UNION
    SELECT 286 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR ERRO NO ACESSO A LCR' DESCRICAO FROM DUAL UNION
    SELECT 287 COD, 'REJEICAO: CERTIFICADO TRANSMISSOR SEM CNPJ OU CPF' DESCRICAO FROM DUAL UNION
    SELECT 290 COD, 'REJEICAO: CERTIFICADO ASSINATURA INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 291 COD, 'REJEICAO: CERTIFICADO ASSINATURA DATA VALIDADE ' DESCRICAO FROM DUAL UNION
    SELECT 292 COD, 'REJEICAO: CERTIFICADO ASSINATURA SEM CNPJ/CPF' DESCRICAO FROM DUAL UNION
    SELECT 293 COD, 'REJEICAO: CERTIFICADO ASSINATURA - ERRO CADEIA DE CERTIFICACAO' DESCRICAO FROM DUAL UNION
    SELECT 294 COD, 'REJEICAO: CERTIFICADO ASSINATURA REVOGADO' DESCRICAO FROM DUAL UNION
    SELECT 295 COD, 'REJEICAO: CERTIFICADO ASSINATURA DIFERE ICP-BRASIL' DESCRICAO FROM DUAL UNION
    SELECT 296 COD, 'REJEICAO: CERTIFICADO ASSINATURA ERRO NO ACESSO A LCR' DESCRICAO FROM DUAL UNION
    SELECT 297 COD, 'REJEICAO: ASSINATURA DIFERE DO CALCULADO' DESCRICAO FROM DUAL UNION
    SELECT 298 COD, 'REJEICAO: ASSINATURA DIFERE DO PADRAO DO PROJETO' DESCRICAO FROM DUAL UNION
    SELECT 299 COD, 'REJEICAO: XML DA AREA DE CABECALHO COM CODIFICACAO DIFERENTE DE UTF-8' DESCRICAO FROM DUAL UNION
    SELECT 402 COD, 'REJEICAO: XML DA AREA DE DADOS COM CODIFICACAO DIFERENTE DE UTF-8' DESCRICAO FROM DUAL UNION
    SELECT 404 COD, 'REJEICAO: USO DE PREFIXO DE NAMESPACE NAO PERMITIDO ' DESCRICAO FROM DUAL UNION
    SELECT 405 COD, 'REJEICAO: MUNICIPIO DE CARREGAMENTO INEXISTENTE' DESCRICAO FROM DUAL UNION
    SELECT 406 COD, 'REJEICAO: MUNICIPIO DE DESCARREGAMENTO INEXISTENTE' DESCRICAO FROM DUAL UNION
    SELECT 407 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DO EMITENTE DO MDF-E ' DESCRICAO FROM DUAL UNION
    SELECT 408 COD, 'REJEICAO: MUNICIPIO DO EMITENTE INEXISTENTE' DESCRICAO FROM DUAL UNION
    SELECT 409 COD, 'REJEICAO: CAMPO CUF INEXISTENTE NO ELEMENTO MDFECABECMSG DO SOAP HEADER' DESCRICAO FROM DUAL UNION
    SELECT 410 COD, 'REJEICAO: UF INFORMADA NO CAMPO CUF NAO A ATENDIDA PELO WEBSERVICE' DESCRICAO FROM DUAL UNION
    SELECT 411 COD, 'REJEICAO: CAMPO VERSAODADOS INEXISTENTE NO ELEMENTO MDFECABECMSG DO SOAP HEADER' DESCRICAO FROM DUAL UNION
    SELECT 412 COD, 'REJEICAO: DATA DO REGISTRO SUPERIOR A DATA ATUAL' DESCRICAO FROM DUAL UNION
    SELECT 413 COD, 'REJEICAO: DUPLICIDADE DE RNTRC' DESCRICAO FROM DUAL UNION
    SELECT 414 COD, 'REJEICAO: CNPJ DO TRANSPORTADOR INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 415 COD, 'REJEICAO: CNPJ ASSOCIADO A OUTRO RNTRC EM SITUACAO ATIVO' DESCRICAO FROM DUAL UNION
    SELECT 416 COD, 'REJEICAO: CPF DO TRANSPORTADOR AUTONOMO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 417 COD, 'REJEICAO: CPF ASSOCIADO A OUTRO RNTRC EM SITUACAO ATIVO' DESCRICAO FROM DUAL UNION
    SELECT 418 COD, 'REJEICAO: CPF NAO PODE SER INFORMADO PARA CATEGORIA DIFERENTE DE TAC' DESCRICAO FROM DUAL UNION
    SELECT 419 COD, 'REJEICAO: CNPJ NAO PODE SER INFORMADO PARA CATEGORIA TAC' DESCRICAO FROM DUAL UNION
    SELECT 420 COD, 'REJEICAO: RNTRC INEXISTENTE NA BASE DE DADOS DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 421 COD, 'REJEICAO: RNTRC JA ESTA DESATIVADO NA BASE DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 422 COD, 'REJEICAO: RNTRC JA ESTA EM SITUACAO ATIVO NA BASE DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 423 COD, 'REJEICAO: RNTRC INATIVO NA BASE DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 424 COD, 'REJEICAO: PLACA INFORMADA JA ASSOCIADA A OUTRO RNTRC ATIVO' DESCRICAO FROM DUAL UNION
    SELECT 425 COD, 'REJEICAO: DUPLICIDADE DE VEICULO' DESCRICAO FROM DUAL UNION
    SELECT 426 COD, 'REJEICAO: PLACA INFORMADA PARA EXCLUSAO NAO EXISTE ASSOCIADA AO RNTRC INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 454 COD, 'REJEICAO: TIPO DE TRANSPORTADOR PARA CARGA PROPRIA E PROPRIETARIO DO VEICULO DIFERENTE DO EMITENTE DEVE SER TAC' DESCRICAO FROM DUAL UNION
    SELECT 455 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE CARREGAMENTO DO MDF-E: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 456 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE CARREGAMENTO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 457 COD, 'REJEICAO: TIPO DE TRANSPORTADOR DEVE SER DIFERENTE DE TAC' DESCRICAO FROM DUAL UNION
    SELECT 458 COD, 'REJEICAO: TIPO DE TRANSPORTADOR NAO DEVE SER INFORMADO PARA EMITENTE DE CARGA PROPRIA PROPRIETARIO DO VEICULO' DESCRICAO FROM DUAL UNION
    SELECT 459 COD, 'REJEICAO: DOCUMENTO AUTORIZADO AO XML DUPLICADO NO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 460 COD, 'REJEICAO: CONSULTA A UMA CHAVE DE ACESSO MUITO ANTIGA' DESCRICAO FROM DUAL UNION
    SELECT 461 COD, 'REJEICAO: MUNICIPIO DE ENCERRAMENTO INVALIDO PARA ENCERRAMENTO EM TERRITORIO NACIONAL' DESCRICAO FROM DUAL UNION
    SELECT 462 COD, 'REJEICAO: EXISTE MDF-E NAO ENCERRADO HA MAIS DE 5 DIAS PARA PLACA COM ATE 2 UF DE PERCURSO INFORMADAS' DESCRICAO FROM DUAL UNION
    SELECT 473 COD, 'REJEICAO: TIPO AUTORIZADOR DO RECIBO DIVERGE DO ORGAO AUTORIZADOR' DESCRICAO FROM DUAL UNION
    SELECT 479 COD, 'REJEICAO: ENDEREÇO DO SITE DO PORTAL NACIONAL PARA A CONSULTA VIA QR CODE DIFERE DO PREVISTO' DESCRICAO FROM DUAL UNION
    SELECT 480 COD, 'REJEICAO: O GRUPO DE INFORMAÇÕES DO QRCODE (INFMDFESUPL) DEVE SER INFORMADO ' DESCRICAO FROM DUAL UNION
    SELECT 481 COD, 'REJEICAO: PARÂMETRO CHAVE DE ACESSO NO QR CODE DIVERGE DA CHAVE DE ACESSO DO MDF-E ' DESCRICAO FROM DUAL UNION
    SELECT 482 COD, 'REJEICAO: SE TIPO DE EMISSÃO FOR IGUAL A CONTINGÊNCIA:O PARÂMETRO SIGN DEVE INFORMADO NO QR-CODE OBRIG' DESCRICAO FROM DUAL UNION
    SELECT 488 COD, 'REJEICAO: SE TIPO DE EMISSÃO FOR IGUAL A NORMAL:O PARÂMETRO SIGN NÃO DEVE SER INFORMADO NO QR-CODE OBRIG.' DESCRICAO FROM DUAL UNION
    SELECT 489 COD, 'REJEICAO: CNPJ INFORMADO INVALIDO (DV OU ZEROS)' DESCRICAO FROM DUAL UNION
    SELECT 490 COD, 'REJEICAO: CPF INFORMADO INVALIDO (DV OU ZEROS)' DESCRICAO FROM DUAL UNION
    SELECT 491 COD, 'REJEICAO: CNPJ-BASE CONSULTADO DIFERE DO CNPJ-BASE DO CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION
    SELECT 492 COD, 'REJEICAO: CPF CONSULTADO DIFERE DO CPF DO CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION
    SELECT 493 COD, 'REJEICAO: NÚMERO DO NSU INFORMADO SUPERIOR AO MAIOR NSU DA BASE DE DADOS DO AMBIENTE NACIONAL' DESCRICAO FROM DUAL UNION
    SELECT 494 COD, 'REJEICAO: PROCESSO DE EMISSAO INFORMADO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 496 COD, 'REJEICAO: SE TIPO DE EMISSÃO FOR IGUAL A CONTINGÊNCIA:VALOR DA ASSINATURA (SIGN) DO QR-CODE DIFERE DO VALOR CALCULADO ' DESCRICAO FROM DUAL UNION
    SELECT 539 COD, 'REJEICAO: DUPLICIDADE DE MDF-E, COM DIFERENCA NA CHAVE DE ACESSO' DESCRICAO FROM DUAL UNION
    SELECT 540 COD, 'REJEICAO: NÃO DEVE SER INFORMADO CONHECIMENTO DE TRANSPORTE PARA TIPO DE EMITENTE PRESTADOR SERVIÇO DE TRANSPORTE QUE EMITIRÁ CTE GLOBALIZADO' DESCRICAO FROM DUAL UNION
    SELECT 541 COD, 'REJEICAO: TIPO DE EMITENTE INVÁLIDO PARA OPERAÇÕES INTERESTADUAIS OU COM EXTERIOR' DESCRICAO FROM DUAL UNION
    SELECT 577 COD, 'REJEICAO: DUPLICIDADE DE CONDUTOR' DESCRICAO FROM DUAL UNION
    SELECT 578 COD, 'REJEICAO: INFORMACOES DOS TOMADORES E OBRIGATORIA PARA ESTA OPERACAO' DESCRICAO FROM DUAL UNION
    SELECT 579 COD, 'REJEICAO: VERSAO INFORMADA PARA O MODAL NAO SUPORTADA' DESCRICAO FROM DUAL UNION
    SELECT 580 COD, 'REJEICAO: FALHA NO SCHEMA XML ESPECIFICO PARA O MODAL' DESCRICAO FROM DUAL UNION
    SELECT 588 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (UF INVALIDA)' DESCRICAO FROM DUAL UNION
    SELECT 589 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (UF INVALIDA)' DESCRICAO FROM DUAL UNION
    SELECT 590 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (UF INVALIDA)' DESCRICAO FROM DUAL UNION
    SELECT 591 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (UF INVALIDA)' DESCRICAO FROM DUAL UNION
    SELECT 592 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (ANO < 2012 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION
    SELECT 593 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION
    SELECT 594 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (CNPJ / CPF ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 595 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (MODELO DIFERENTE DE 58)' DESCRICAO FROM DUAL UNION
    SELECT 596 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (NUMERO MDFE = 0)' DESCRICAO FROM DUAL UNION
    SELECT 597 COD, 'REJEICAO: CHAVE DE ACESSO INVALIDA (TIPO DE EMISSAO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 598 COD, 'REJEICAO: USAR SOMENTE O NAMESPACE PADRAO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 599 COD, 'REJEICAO: NAO EH PERMITIDA A PRESENCA DE CARACTERES DE EDICAO NO INICIO/FIM DA MENSAGEM OU ENTRE AS TAGS DA MENSAGEM' DESCRICAO FROM DUAL UNION
    SELECT 600 COD, 'REJEICAO: CHAVE DE ACESSO DIFERE DA EXISTENTE EM BD' DESCRICAO FROM DUAL UNION
    SELECT 601 COD, 'REJEICAO: CHAVE DE ACESSO DO CT-E INFORMADO INVALIDA' DESCRICAO FROM DUAL UNION
    SELECT 602 COD, 'REJEICAO: SEGUNDO CODIGO DE BARRAS DEVE SER INFORMADO PARA CT-E EM CONTINGENCIA FS-DA' DESCRICAO FROM DUAL UNION
    SELECT 603 COD, 'REJEICAO: SEGUNDO CODIGO DE BARRAS NAO DEVE SER INFORMADO PARA CT-E COM ESTE TIPO DE EMISSAO' DESCRICAO FROM DUAL UNION
    SELECT 604 COD, 'REJEICAO: CHAVE DE ACESSO DA NF-E INFORMADA INVALIDA' DESCRICAO FROM DUAL UNION
    SELECT 605 COD, 'REJEICAO: NF-E EMITIDA POR EMPRESA DIFERENTE DA EMPRESA EMITENTE DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 606 COD, 'REJEICAO: SEGUNDO CODIGO DE BARRAS DEVE SER INFORMADO PARA NF-E EM CONTINGENCIA (FS-DA E FSIA)' DESCRICAO FROM DUAL UNION
    SELECT 607 COD, 'REJEICAO: SEGUNDO CODIGO DE BARRAS NAO DEVE SER INFORMADO PARA NF-E COM ESTE TIPO DE EMISSAO' DESCRICAO FROM DUAL UNION
    SELECT 608 COD, 'REJEICAO: NF EMITIDA POR EMPRESA DIFERENTE DA EMPRESA EMITENTE DO MDF-E ' DESCRICAO FROM DUAL UNION
    SELECT 609 COD, 'REJEICAO: MDF-E JA ESTA ENCERRADO NA BASE DE DADOS DA SEFAZ. [NPROT:999999999999999][DHENC: AAAA-MM DDTHH:MM:SS TZD]' DESCRICAO FROM DUAL UNION
    SELECT 610 COD, 'REJEICAO: EXISTE MDF-E NAO ENCERRADO PARA ESTA PLACA, UF CARREGAMENTO E UF DESCARREGAMENTO EM DATA DE EMISSAO DIFERENTE ' DESCRICAO FROM DUAL UNION
    SELECT 611 COD, 'REJEICAO: EXISTE MDF-E NAO ENCERRADO PARA ESTA PLACA, TIPO DE EMITENTE E UF DESCARREGAMENTO' DESCRICAO FROM DUAL UNION
    SELECT 612 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE DESCARREGAMENTO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 613 COD, 'REJEICAO: CODIGO DE MUNICIPIO DE ENCERRAMENTO: DIGITO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 614 COD, 'REJEICAO: CODIGO DE MUNICIPIO DIVERGE DA UF DE ENCERRAMENTO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 615 COD, 'REJEICAO: DATA DE ENCERRAMENTO ANTERIOR A DATA DE AUTORIZACAO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 616 COD, 'REJEICAO: NENHUM GRUPO DE DOCUMENTOS FOI INFORMADO (CT-E, CT, NF-E, NF, MDF-E) RETORNAR MUNICIPIO DE DESCARREGAMENTO SEM DFE' DESCRICAO FROM DUAL UNION
    SELECT 617 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (ANO < 2009 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION
    SELECT 618 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION
    SELECT 619 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (CNPJ ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 620 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (MODELO DIFERENTE DE 57)' DESCRICAO FROM DUAL UNION
    SELECT 621 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (NUMERO CT = 0)' DESCRICAO FROM DUAL UNION
    SELECT 622 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (ANO < 2005 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION
    SELECT 623 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION
    SELECT 624 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (CNPJ/CPF ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 625 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (MODELO DIFERENTE DE 55)' DESCRICAO FROM DUAL UNION
    SELECT 626 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (NUMERO NF = 0)' DESCRICAO FROM DUAL UNION
    SELECT 627 COD, 'REJEICAO: CNPJ DO AUTOR DO EVENTO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 628 COD, 'REJEICAO: ERRO ATRIBUTO ID DO EVENTO NAO CORRESPONDE A CONCATENACAO DOS CAMPOS ("ID" +TPEVENTO + CHMDFE + NSEQEVENTO)' DESCRICAO FROM DUAL UNION
    SELECT 629 COD, 'REJEICAO: O TPEVENTO INFORMADO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 630 COD, 'REJEICAO: FALHA NO SCHEMA XML ESPECIFICO PARA O EVENTO' DESCRICAO FROM DUAL UNION
    SELECT 631 COD, 'REJEICAO: DUPLICIDADE DE EVENTO' DESCRICAO FROM DUAL UNION
    SELECT 632 COD, 'REJEICAO: O AUTOR DO EVENTO DIVERGE DO EMISSOR DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 633 COD, 'REJEICAO: O AUTOR DO EVENTO NAO A UM ORGAO AUTORIZADO A GERAR O EVENTO' DESCRICAO FROM DUAL UNION
    SELECT 634 COD, 'REJEICAO: A DATA DO EVENTO NAO PODE SER MENOR QUE A DATA DE EMISSAO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 635 COD, 'REJEICAO: A DATA DO EVENTO NAO PODE SER MAIOR QUE A DATA DO PROCESSAMENTO' DESCRICAO FROM DUAL UNION
    SELECT 636 COD, 'REJEICAO: O NUMERO SEQUENCIAL DO EVENTO A MAIOR QUE O PERMITIDO' DESCRICAO FROM DUAL UNION
    SELECT 637 COD, 'REJEICAO: A DATA DO EVENTO NAO PODE SER MENOR QUE A DATA DE AUTORIZACAO DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 638 COD, 'REJEICAO: NAO DEVE SER INFORMADA NOTA FISCAL PARA TIPO DE EMITENTE PRESTADOR SERVICO DE TRANSPORTE.' DESCRICAO FROM DUAL UNION
    SELECT 639 COD, 'REJEICAO: NAO DEVE SER INFORMADO CONHECIMENTO DE TRANSPORTE PARA TIPO DE EMITENTE TRANSPORTE DE CARGA PROPRIA.' DESCRICAO FROM DUAL UNION
    SELECT 640 COD, 'REJEICAO: CPF DO FUNCIONARIO DO REGISTRO DE PASSAGEM INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 641 COD, 'REJEICAO: UF AUTORIZADORA DIFERE DA UF DE PASSAGEM' DESCRICAO FROM DUAL UNION
    SELECT 642 COD, 'REJEICAO: REGISTRO DE PASSAGEM DESCARTADO' DESCRICAO FROM DUAL UNION
    SELECT 643 COD, 'REJEICAO: PLACA DO VEICULO DE TRACAO DEVE SER INFORMADA NO REGISTRO DE PASSAGEM PARA O MODAL RODOVIARIO' DESCRICAO FROM DUAL UNION
    SELECT 644 COD, 'REJEICAO: EVENTO DE INCLUSAO DE CONDUTOR SO PODE SER REGISTRADO PARA O MODAL RODOVIARIO' DESCRICAO FROM DUAL UNION
    SELECT 645 COD, 'REJEICAO: CPF DO CONDUTOR INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 646 COD, 'REJEICAO: PLACA DE VEICULO FORMATO INVALIDO (UF CARREGAMENTO E DESCARREGAMENTO <> "EX")' DESCRICAO FROM DUAL UNION
    SELECT 647 COD, 'REJEICAO: MDF-E SO PODE SER REFERENCIADO POR MANIFESTO DO MODAL AQUAVIARIO' DESCRICAO FROM DUAL UNION
    SELECT 648 COD, 'REJEICAO: MDF-E SO PODE SER REFERENCIADO QUANDO UF DE CARREGAMENTO/DESCARREGAMENTO FOR IGUAL A AM OU AP' DESCRICAO FROM DUAL UNION
    SELECT 649 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INFORMADA INVALIDA' DESCRICAO FROM DUAL UNION
    SELECT 650 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (ANO < 2013 OU ANO MAIOR QUE ANO CORRENTE)' DESCRICAO FROM DUAL UNION
    SELECT 651 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (MES = 0 OU MES > 12)' DESCRICAO FROM DUAL UNION
    SELECT 652 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (CNPJ/CPF ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 653 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (MODELO DIFERENTE DE 58)' DESCRICAO FROM DUAL UNION
    SELECT 654 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (NUMERO MDF = 0)' DESCRICAO FROM DUAL UNION
    SELECT 655 COD, 'REJEICAO: MDF-E REFERENCIADO NAO EXISTE NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION
    SELECT 656 COD, 'REJEICAO: CHAVE DE ACESSO DO MDF-E REFERENCIADO DIFERE DA EXISTENTE EM BD' DESCRICAO FROM DUAL UNION
    SELECT 657 COD, 'REJEICAO: MDF-E REFERENCIADO JA ESTA CANCELADO NA BASE DE DADOS DA SEFAZ' DESCRICAO FROM DUAL UNION
    SELECT 658 COD, 'REJEICAO: MODAL DO MDF-E REFERENCIADO DIFERENTE DE RODOVIARIO' DESCRICAO FROM DUAL UNION
    SELECT 659 COD, 'REJEICAO: TIPO DO EMITENTE DO MDF-E REFERENCIADO DIFERE DE TRANSPORTADOR DE CARGA PROPRIA' DESCRICAO FROM DUAL UNION
    SELECT 660 COD, 'REJEICAO: CNPJ AUTORIZADO PARA DOWNLOAD INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 661 COD, 'REJEICAO: CPF AUTORIZADO PARA DOWNLOAD INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 662 COD, 'REJEICAO: EXISTE MDF-E ABERTO PARA A PLACA DO VEICULO TRACAO CONTENDO DOCUMENTO RELACIONADO NO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 663 COD, 'REJEICAO: PERCURSO INFORMADO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 664 COD, 'REJEICAO: VEDADA A EMISSAO DE CONHECIMENTO DE TRANSPORTE EM PAPEL CT-E OBRIGATORIO' DESCRICAO FROM DUAL UNION
    SELECT 665 COD, 'REJEICAO: EMITENTE DA NOTA FISCAL A OBRIGADO A EMISSAO DE NOTA FISCAL ELETRONICA' DESCRICAO FROM DUAL UNION
    SELECT 666 COD, 'REJEICAO: ANO DO MDF-E INFORMADO NA CHAVE DE ACESSO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 667 COD, 'REJEICAO: QUANTIDADE INFORMADA NO GRUPO DE TOTALIZADORES NAO CONFERE COM A QUANTIDADE DE DOCUMENTOS RELACIONADA' DESCRICAO FROM DUAL UNION
    SELECT 668 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E DUPLICADA' DESCRICAO FROM DUAL UNION
    SELECT 669 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E DUPLICADA' DESCRICAO FROM DUAL UNION
    SELECT 670 COD, 'REJEICAO: CHAVE DE ACESSO DE CT-E INVALIDA (TIPO DE EMISSAO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 671 COD, 'REJEICAO: CT-E INFORMADO NAO EXISTE NA BASE DE DADOS DA SEFAZ ' DESCRICAO FROM DUAL UNION
    SELECT 672 COD, 'REJEICAO: CT-E INFORMADO COM DIFERENCA DE CHAVE DE ACESSO' DESCRICAO FROM DUAL UNION
    SELECT 673 COD, 'REJEICAO: CT-E INFORMADO NAO PODE ESTAR CANCELADO/DENEGADO NA BASE DA SEFAZ' DESCRICAO FROM DUAL UNION
    SELECT 674 COD, 'REJEICAO: CHAVE DE ACESSO DE NF-E INVALIDA (TIPO DE EMISSAO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 675 COD, 'REJEICAO: NF-E INFORMADA NAO EXISTE NA BASE DE DADOS DA SEFAZ [CHNFE: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO FROM DUAL UNION
    SELECT 676 COD, 'REJEICAO: NF-E INFORMADA COM DIFERENCA DE CHAVE DE ACESSO [CHNFE:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO FROM DUAL UNION
    SELECT 677 COD, 'REJEICAO: NF-E INFORMADA NAO PODE ESTAR CANCELADA/DENEGADA NA BASE DA SEFAZ [CHNFE:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]' DESCRICAO FROM DUAL UNION
    SELECT 678 COD, 'REJEICAO: USO INDEVIDO' DESCRICAO FROM DUAL UNION
    SELECT 679 COD, 'REJEICAO: CHAVE DE ACESSO DE MDF-E INVALIDA (TIPO DE EMISSAO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 680 COD, 'REJEICAO: MUNICIPIO DE DESCARREGAMENTO DUPLICADO NO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 681 COD, 'REJEICAO: RNTRC INFORMADO INEXISTENTE' DESCRICAO FROM DUAL UNION
    SELECT 682 COD, 'REJEICAO: RNTRC SITUACAO INVALIDA' DESCRICAO FROM DUAL UNION
    SELECT 683 COD, 'REJEICAO: PLACA DO VEICULO DE TRACAO NAO VINCULADA AO RNTRC INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 684 COD, 'REJEICAO: CIOT OBRIGATORIO PARA RNTRC INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 685 COD, 'REJEICAO: MUNICIPIO DE CARREGAMENTO DUPLICADO NO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 686 COD, 'REJEICAO: EXISTE MDF-E NAO ENCERRADO HA MAIS DE 30 DIAS PARA O EMITENTE' DESCRICAO FROM DUAL UNION
    SELECT 687 COD, 'REJEICAO: RNTRC DEVE ESTAR ASSOCIADO AO TRANSPORTADOR INDICADO' DESCRICAO FROM DUAL UNION
    SELECT 688 COD, 'REJEICAO: RNTRC DEVE SER INFORMADO PARA PRESTADOR DE SERVIÇO DE TRANSPORTE' DESCRICAO FROM DUAL UNION
    SELECT 689 COD, 'REJEICAO: MUNICIPIO DE ENCERRAMENTO DEVE SER 9999999 PARA ENCERRAMENTO NO EXTERIOR' DESCRICAO FROM DUAL UNION
    SELECT 690 COD, 'REJEICAO: A DATA DO REGISTRO DE PASSAGEM NAO PODE SER MAIOR QUE A DATA DE PROCESSAMENTO' DESCRICAO FROM DUAL UNION
    SELECT 691 COD, 'REJEICAO: MDF-E EM SITUACAO QUE IMPEDE LIBERAR PRAZO DE CANCELAMENTO' DESCRICAO FROM DUAL UNION
    SELECT 692 COD, 'REJEICAO: UF NAO TEM PERMISSAO DE LIBERAR PRAZO DE CANCELAMENTO PARA O CT-E INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 693 COD, 'REJEICAO: DATA DE INICIO DA VIGENCIA INFERIOR A DATA ATUAL ' DESCRICAO FROM DUAL UNION
    SELECT 694 COD, 'REJEICAO: DATA DE FIM DA VIGENCIA SUPERIOR A 6 MESES DA DATA ATUAL' DESCRICAO FROM DUAL UNION
    SELECT 695 COD, 'REJEICAO: DATA DE FIM DA VIGENCIA INFERIOR A DATA DE INICIO DA VIGENCIA' DESCRICAO FROM DUAL UNION
    SELECT 696 COD, 'REJEICAO: EVENTO DE LIBERACAO DE PRAZO DE CANCELAMENTO INEXISTENTE' DESCRICAO FROM DUAL UNION
    SELECT 697 COD, 'REJEICAO: EVENTO DE LIBERACAO DE PRAZO DE CANCELAMENTO JA ESTA ANULADO' DESCRICAO FROM DUAL UNION
    SELECT 698 COD, 'REJEICAO: SEGURO DA CARGA E OBRIGATORIO PARA MODAL PRESTADOR DE SERVICO DE TRANSPORTE NO MODAL RODOVIARIO' DESCRICAO FROM DUAL UNION
    SELECT 699 COD, 'REJEICAO: DADOS DO SEGURO DE CARGA INCOMPLETOS PARA O MODAL RODOVIARIO' DESCRICAO FROM DUAL UNION
    SELECT 700 COD, 'REJEICAO: CPF DO AUTOR DO EVENTO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 701 COD, 'REJEICAO: TIPO DE EVENTO INCOMPATIVEL COM EMITENTE PESSOA FISICA' DESCRICAO FROM DUAL UNION
    SELECT 702 COD, 'REJEICAO: MODAL INVALIDO PARA ENTREGA PARCIAL(APENAS MODAL AEREO)' DESCRICAO FROM DUAL UNION
    SELECT 703 COD, 'REJEICAO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR, DEVE SER INFORMADO APENAS UM MUNICÍPIO DE CARREGAMENTO E UM MUNICÍPIO DE DESCARREGAMENTO(DEVEM SER IGUAIS)' DESCRICAO FROM DUAL UNION
    SELECT 704 COD, 'REJEICAO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), UF DE CARREGAMENTO DEVE SER IGUAL A UF DE DESCARREGAMENTO E DIFERENTES DE EX ' DESCRICAO FROM DUAL UNION
    SELECT 705 COD, 'REJEICAO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), MODAL DEVE SER RODOVIÁRIO ' DESCRICAO FROM DUAL UNION
    SELECT 706 COD, 'REJEICAO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), OS GRUPOS DE DOCUMENTOS RANSPORTADOS NÃO DEVEM SER INFORMADOS (CT-E, NF-E E MDF-E)' DESCRICAO FROM DUAL UNION
    SELECT 707 COD, 'REJEICAO: SE INFORMADO INDICADOR DE CARREGAMENTO POSTERIOR (INDCARREGAPOSTERIOR=1), O TIPO DO EMITENTE DEVE SER TRANSPORTE PRÓPRIO (2)  ' DESCRICAO FROM DUAL UNION
    SELECT 708 COD, 'REJEIÇÃO: MDFE DEVE POSSUI INDICAÇÃO DE CARREGAMENTO POSTERIOR PARA INCLUSÃO DE DF-E' DESCRICAO FROM DUAL UNION
    SELECT 709 COD, 'CHAVE DE ACESSO DE NFE INVÁLIDA NO EVENTO DE INCLUSÃO [MOTIVO: CNPJ/CPF INVÁLIDO / MODELO DIFERENTE DE 55 / ANO INVÁLIDO (< 2006) / MÊS INVÁLIDO (0 OU > 12) / TIPO DE EMISSÃO INVÁLIDO / UF INVÁLIDA / NÚMERO ZERADO / DV INVÁLIDO]' DESCRICAO FROM DUAL UNION
    SELECT 710 COD, 'CANCELAMENTO NÃO É PERMITIDO PARA MDFE COM INDICAÇÃO DE CARREGAMENTO POSTERIOR QUE JÁ REALIZOU INSERÇÃO DE DF-E' DESCRICAO FROM DUAL UNION
    SELECT 711 COD, 'NFE JÁ ESTÁ VINCULADA AO MDFE POR OUTRO EVENTO' DESCRICAO FROM DUAL UNION    
    SELECT 712 COD, 'REJEICAO: EXISTE MDF-E COM INDICAÇÃO DE CARREGAMENTO POSTERIOR(INDCARREGAPOSTERIOR=1) SEM EVENTO DE INCLUSÃO DE DF-E HÁ MAIS DE 168 HORAS PARAO MESMO CNPJ / CPF DO EMITENTE' DESCRICAO FROM DUAL UNION
    SELECT 713 COD, 'REJEICAO: CNPJ DO DESENVOLVEDOR DO SISTEMA INVALIDO (ZERADO OU DIGITO INVALIDO)' DESCRICAO FROM DUAL UNION
    SELECT 714 COD, 'REJEICAO: MUNICIPIO DE ENCERRAMENTO INEXISTENTE' DESCRICAO FROM DUAL UNION
    SELECT 715 COD, 'REJEICAO: NÃO É PERMITIDO ENCERRAR MDFE COM INDICAÇÃO DE CARREGAMENTO POSTERIOR SEM INCLUSÃO DE DF-E ASSOCIADA' DESCRICAO FROM DUAL UNION
    SELECT 716 COD, 'REJEICAO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO CIOT(INFCIOT): REJEITAR SE O CPF/CNPJ DO RESPONSÁVEL PELA GERAÇÃO DO CIOT INFORMADO ESTIVER INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 717 COD, 'REJEICAO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO CONTRATANTE(INFCONTRATANTE): REJEITAR SE O CPF/CNPJ INFORMADO PARA O CONTRATANTE ESTIVER INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 718 COD, 'REJEICAO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO(VEICTRACAO/PROP): REJEITAR SE O CPF/CNPJ INFORMADO PARA O PROPRIETÁRIO ESTIVER INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 719 COD, 'REJEICAO: SE MODAL RODOVIÁRIO E INFORMADO GRUPO DO PROPRIETÁRIO DO VEÍCULO REBOQUE(VEICREBOQUE/PROP): REJEITAR SE O CPF/CNPJ INFORMADO PARA O PROPRIETÁRIO ESTIVER INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 722 COD, 'REJEIÇÃO: MDF-E DEVE SER DO MODAL RODOVIÁRIO PARA O EVENTO PAGAMENTO DE MDF' DESCRICAO FROM DUAL UNION
    SELECT 723 COD, 'REJEIÇÃO: O TIPO DO PROPRIETÁRIO DO MDF-E DEVE SER DO TIPO TAC AGREGADO' DESCRICAO FROM DUAL UNION
    SELECT 724 COD, 'REJEICAO: GRUPO DE INFORMAÇÕES DO PAGAMENTO A PRAZO DEVE SER INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 725 COD, 'REJEICAO: GRUPO PRODUTO PREDOMINANTE DEVE SER INFORMADO PARA MODAL RODOVIÁRIO' DESCRICAO FROM DUAL UNION
    SELECT 726 COD, 'REJEICAO: O GRUPO DE INFORMAÇÕES DA CARGA LOTAÇÃO DEVE SER INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 727 COD, 'REJEICAO: CNPJ/CPF DO RESPONSÁVEL PELO PAGAMENTO DO FRETE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 728 COD, 'REJEICAO: CNPJ DA INSTITUIÇÃO DE PAGAMENTO ELETRÔNICO DO FRETE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 729 COD, 'REJEIÇÃO: GRUPO DE INFORMAÇÕES DO PAGAMENTO A PRAZO NÃO DEVE SER INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 735 COD, 'REJEIÇÃO: NÚMERO DA PARCELA INVÁLIDO [NPARCELA:999]' DESCRICAO FROM DUAL UNION
    SELECT 736 COD, 'REJEIÇÃO: DATA DE VENCIMENTO DA PARCELA MENOR QUE A DATA DE EMISSÃO [NPARCELA:999]' DESCRICAO FROM DUAL UNION
    SELECT 737 COD, 'REJEIÇÃO: DATA DE VENCIMENTO DA PARCELA MENOR QUE A DATA DA PARCELA ANTERIOR [NPARCELA: 999]' DESCRICAO FROM DUAL UNION
    SELECT 738 COD, 'REJEIÇÃO: SOMATÓRIO DO VALOR DAS PARCELAS DIFERENTE DO VALOR DO CONTRATO' DESCRICAO FROM DUAL UNION
    SELECT 739 COD, 'REJEIÇÃO: VALOR DO ADIANTAMENTO NÃO PODE SER INFORMADO PARA PAGAMENTO A VISTA' DESCRICAO FROM DUAL UNION
    SELECT 740 COD, 'REJEIÇÃO: O PROPRIETÁRIO DO VEÍCULO QUANDO INFORMADO DEVE SER DIFERENTE DO EMITENTE DO MDF-E' DESCRICAO FROM DUAL UNION
    SELECT 741 COD, 'REJEIÇÃO: O CONTRATANTE DEVE SER IGUAL AO EMITENTE DO MDF-E QUANDO INDICADO PROPRIETÁRIO DO VEÍCULO' DESCRICAO FROM DUAL UNION
    SELECT 742 COD, 'REJEIÇÃO: CONTRATANTE INFORMADO DUPLICADO [CONTRATANTE: 99999999999]' DESCRICAO FROM DUAL UNION
    SELECT 743 COD, 'REJEIÇÃO: O TIPO DE TRANSPORTADOR DEVE SER TAC QUANDO INFORMADO CPF DO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO' DESCRICAO FROM DUAL UNION
    SELECT 744 COD, 'REJEIÇÃO: O TIPO DE TRANSPORTADOR DEVE SER ETC OU CTE QUANDO INFORMADO CNPJ DO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO' DESCRICAO FROM DUAL UNION
    SELECT 745 COD, 'REJEIÇÃO: O TIPO DE TRANSPORTADOR NÃO SER INFORMADO QUANDO NÃO ESTIVER INFORMADO PROPRIETÁRIO DO VEÍCULO DE TRAÇÃO' DESCRICAO FROM DUAL UNION
    SELECT 746 COD, 'REJEIÇÃO: A SOMA DOS COMPONENTES DO PAGAMENTO DEVE SER IGUAL AO VALOR DO CONTRATO ' DESCRICAO FROM DUAL UNION
    SELECT 999 COD, 'REJEICAO: ERRO NAO CATALOGADO (INFORMAR A MSG DE ERRO CAPTURADO NO TRATAMENTO DA EXCECAO) ' DESCRICAO FROM DUAL UNION
    SELECT 1002 COD, 'QUANTIDADE MAXIMA DE 10 CARACTERES PERMITIDOS PARA O CODIGO DO VEICULO' DESCRICAO FROM DUAL UNION
    SELECT 1003 COD, 'PLACA DO VEICULO NAO INFORMADO OU INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1004 COD, 'QUANTIDADE MAXIMA DE 06 CARACTERES PERMITIDOS PARA A TARA DO VEICULO' DESCRICAO FROM DUAL UNION
    SELECT 1005 COD, 'QUANTIDADE MAXIMA DE 06 CARACTERES PERMITIDOS PARA A CAPACIDADE EM KG DO VEICULO' DESCRICAO FROM DUAL UNION
    SELECT 1006 COD, 'QUANTIDADE MAXIMA DE 03 CARACTERES PERMITIDOS PARA A CAPACIDADE M3 DO VEICULO' DESCRICAO FROM DUAL UNION
    SELECT 1007 COD, 'CNPJ OU CPF INVALIDO OU NAO INFORMADO NO CADASTRO DO VEICULO CAMPO PROPRIETARIO' DESCRICAO FROM DUAL UNION
    SELECT 1008 COD, 'RNTRC DO PROPRIETARIO DO VEICULO INVALIDO OU NAO INFORMADO. VALIDAR NO CADASTRO DO VEICULO(DEVE TER TAMANHO IGUAL A 8)' DESCRICAO FROM DUAL UNION
    SELECT 1009 COD, 'O NOME DO PROPRIETARIO DO VEICULO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1010 COD, 'A INSCRICAO ESTADUAL DO PROPRIETARIO DO VEICULO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1011 COD, 'A UF DO PROPRIETARIO DO VEICULO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1012 COD, 'TIPO PROPRIETARIO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1013 COD, 'NOME DO MOTORISTA DO VEICULO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1014 COD, 'CPF DO MOTORISTA DO VEICULO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1015 COD, 'TIPO DE RODADO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1016 COD, 'TIPO DE CARROCERIA INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1017 COD, 'UF DO VEICULO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1018 COD, 'TIPO AMBIENTE INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1019 COD, 'VALOR TOTAL DO MDFE NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1020 COD, 'CODIGO DO MUNICIPIO DE DESCARREGAMENTO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1021 COD, 'PLACA DO VEICULO DE REBOQUE DEVE TER 07 CARACTERES ' DESCRICAO FROM DUAL UNION
    SELECT 1022 COD, 'QUANTIDADE MAXIMA DE 06 CARACTERES PERMITIDOS PARA A TARA DO VEICULO DE REBOQUE' DESCRICAO FROM DUAL UNION
    SELECT 1023 COD, 'QUANTIDADE MAXIMA DE 06 CARACTERES PERMITIDOS PARA A CAPACIDADE EM KG DO VEICULO DE REBOQUE' DESCRICAO FROM DUAL UNION
    SELECT 1024 COD, 'QUANTIDADE MINIMA DE 09 OU MAXIMA DE 11 CARACTERES PERMITIDOS PARA O RENAVAM DO VEICULO DE REBOQUE' DESCRICAO FROM DUAL UNION
    SELECT 1025 COD, 'NUMERO ONU/UN DO GRUPO PERI INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1026 COD, 'QUANTIDADE TOTAL POR PRODUTO DO GRUPO PERI INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1027 COD, 'INFORMACOES DO RESPONSAVEL PELO SEGURO DA CARGA NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1028 COD, 'RESPONSAVEL PELO SEGURO NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1029 COD, 'RESPONSAVEL PELO SEGURO NAO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1030 COD, 'NUMERO DO CNPJ DO RESPONSAVEL PELO SEGURO NAO INFORAMDO ' DESCRICAO FROM DUAL UNION
    SELECT 1031 COD, 'NUMERO DO CNPJ DO RESPONSAVEL PELO SEGURO INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1032 COD, 'NOME DA SEGURADORA NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1033 COD, 'NOME DA SEGURADORA INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1034 COD, 'NUMERO DO CNPJ DA SEGURADORA INVALIDO' DESCRICAO FROM DUAL UNION
    SELECT 1035 COD, 'NUMERO DO CNPJ DA SEGURADORA NAO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 1036 COD, 'RNTRC DO EMITENTE DO MDFE INVALIDO OU NAO INFORMADO. VALIDAR NO CADASTRO DA FILIAL, ROTINA 535(DEVE TER TAMANHO IGUAL A 8)' DESCRICAO FROM DUAL UNION
    SELECT 1037 COD, 'CNPJ/CPF DO CONTRATANTE DO SERVIÇO INVALIDO(VALIDAR TOMADOR DO CTE)' DESCRICAO FROM DUAL UNION
    SELECT 1038 COD, 'TIPO DE PREDOMINÂNCIA DO PRODUTO NÃO INFORMADA. VALIDAR CADASTRO DO PRODUTO' DESCRICAO FROM DUAL UNION
    SELECT 1039 COD, 'DESCRIÇÃO DO PRODUTO NÃO INFORMADA OU INVÁLIDA. VALIDAR CADASTRO DO PRODUTO (DEVE ESTAR COM TAMANHO ENTRE 2 E 120)' DESCRICAO FROM DUAL UNION
    SELECT 1040 COD, 'EAN DO PRODUTO PREDOMINANTE INVÁLIDO OU NÃO INFORMADO. VALIDAR CADASTRO DO PRODUTO PREDOMINANTE DO MDFE' DESCRICAO FROM DUAL UNION
    SELECT 1041 COD, 'NCM DO PRODUTO PREDOMINANTE INVÁLIDO OU NÃO INFORMADO. VALIDAR CADASTRO DO PRODUTO PREDOMINANTE DO MDFE' DESCRICAO FROM DUAL UNION
    SELECT 1042 COD, 'PARA MDFE DE CTE, O PRODUTO PREDOMINANTE DEVE SER INFORMADO' DESCRICAO FROM DUAL 

  ) LOOP
  
    SELECT COUNT(*) INTO iCOUNT FROM PCMENSAGEMMDFE WHERE CODMENSAGEM = DADOS.COD;
    
    IF iCOUNT = 0 THEN
       INSERT INTO PCMENSAGEMMDFE (CODMENSAGEM, DESCRICAO) VALUES(DADOS.COD, substr(DADOS.DESCRICAO,0,180));
    ELSE
       UPDATE PCMENSAGEMMDFE SET
         DESCRICAO = substr(DADOS.DESCRICAO,0,180)
       WHERE CODMENSAGEM = DADOS.COD;       
    END IF;
  END LOOP;
  COMMIT;
END;