DECLARE
  V_QTD NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO V_QTD
    FROM ALL_INDEXES
   WHERE INDEX_NAME = 'PCCIAPITEM_UK2'
     AND TABLE_NAME = 'PCCIAPITEM';

  IF V_QTD > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX PCCIAPITEM_UK2';
  END IF;
END;