DECLARE
  V_COUNT NUMBER;
BEGIN

  SELECT COUNT(*)
    INTO V_COUNT
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'PCCIAPITEM'
     AND CONSTRAINT_NAME = 'PCCIAPITEM_UK2';

  IF V_COUNT > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PCCIAPITEM DROP CONSTRAINT PCCIAPITEM_UK2';
  ELSE
  
  SELECT COUNT(*)
	INTO V_COUNT
	FROM USER_INDEXES
     WHERE INDEX_NAME = 'PCCIAPITEM_UK2';
  
  IF V_COUNT > 0 THEN
	EXECUTE IMMEDIATE 'DROP INDEX PCCIAPITEM_UK2';
    END IF;
  
  END IF;

END;