DECLARE
    iCOUNT Integer;
BEGIN
--------------------------------------------------Carga de variáveis de layout de arquivo--------------------------------------------------
    FOR DADOS IN (
        SELECT '[CODIGOTIPOCHAVEPIX]' AS NOME, 'Código do tipo da chave pix (pclanc.codtipochavepix)' AS DESCRICAO, 1 AS CODPROCESSO, 'RR' AS NATUREZAOPERACAO, 'SIST' AS TIPOCONTEUDO, '' AS CONTEUDO, 'TX' AS TIPODADOS, 'PCLANC' AS TABELASIS, 'CODTIPOCHAVEPIX' AS COLUNASIS FROM DUAL UNION
        SELECT '[TIPOCHAVEPIX]' AS NOME, 'Descrição do tipo da chave pix (pclanc.tipochavepix)' AS DESCRICAO, 1 AS CODPROCESSO, 'RR' AS NATUREZAOPERACAO, 'SIST' AS TIPOCONTEUDO, '' AS CONTEUDO, 'TX' AS TIPODADOS, 'PCLANC' AS TABELASIS, 'TIPOCHAVEPIX' AS COLUNASIS FROM DUAL UNION
        SELECT '[CHAVEPIX]' AS NOME, 'Chave pix para transferência (pclanc.chavepix)' AS DESCRICAO, 1 AS CODPROCESSO, 'RR' AS NATUREZAOPERACAO, 'SIST' AS TIPOCONTEUDO, '' AS CONTEUDO, 'TX' AS TIPODADOS, 'PCLANC' AS TABELASIS, 'CHAVEPIX' AS COLUNASIS FROM DUAL UNION
        SELECT '[QRCODEPIX]' AS NOME, 'Qr-code para pagamento com pix (pclanc.qrcodepix)' AS DESCRICAO, 1 AS CODPROCESSO, 'RR' AS NATUREZAOPERACAO, 'SIST' AS TIPOCONTEUDO, '' AS CONTEUDO, 'TX' AS TIPODADOS, 'PCLANC' AS TABELASIS, 'QRCODEPIX' AS COLUNASIS FROM DUAL
	) LOOP
	    SELECT COUNT(*) INTO iCOUNT FROM PCLAYOUTCOBVAR WHERE NOME = DADOS.NOME AND DESCRICAO = DADOS.DESCRICAO;

		IF iCOUNT = 0 THEN
		    INSERT INTO PCLAYOUTCOBVAR (NOME, DESCRICAO, CODPROCESSO, NATUREZAOPERACAO, TIPOCONTEUDO, CONTEUDO, TIPODADOS, TABELASIS, COLUNASIS) 
			VALUES (DADOS.NOME, DADOS.DESCRICAO, DADOS.CODPROCESSO, DADOS.NATUREZAOPERACAO, DADOS.TIPOCONTEUDO, DADOS.CONTEUDO, DADOS.TIPODADOS, DADOS.TABELASIS, DADOS.COLUNASIS);
		ELSE
		    UPDATE PCLAYOUTCOBVAR SET
			    CODPROCESSO = DADOS.CODPROCESSO,
				NATUREZAOPERACAO = DADOS.NATUREZAOPERACAO,
				TIPOCONTEUDO = DADOS.TIPOCONTEUDO,
				CONTEUDO = DADOS.CONTEUDO,
				TIPODADOS = DADOS.TIPODADOS,
				TABELASIS = DADOS.TABELASIS,
				COLUNASIS = DADOS.COLUNASIS
            WHERE
                NOME = DADOS.NOME AND
                DESCRICAO = DADOS.DESCRICAO;
		END IF;
	END LOOP;

	dbms_output.put_line('Atualizou tabela de variáveis do layout de arquivo - contas a pagar (rotina 770)');
	COMMIT;	
----------------------------------------------------------------------Fim------------------------------------------------------------------
END;