CREATE OR REPLACE TRIGGER TRG_PCCLIENT_CODROTALT_MATCON
    BEFORE UPDATE ON PCCLIENT
    FOR EACH ROW
DECLARE
    V_ROTINA VARCHAR2(2000);
BEGIN
    BEGIN
        V_ROTINA := SUBSTR(UPPER(SYS_CONTEXT('USERENV', 'MODULE')), 1, 2000);

        IF UPDATING THEN
            IF (UPPER(:OLD.CODROTINAALT) = 'WINTHORINTEGRACAOMATCON') THEN
                IF (V_ROTINA <> 'WINTHORANYWHERE') OR
                   ((V_ROTINA = 'WINTHORANYWHERE') AND (UPPER(:NEW.CODROTINAALT) <> 'WINTHORINTEGRACAOMATCON')) THEN
                    IF (:OLD.CODROTINAALT = :NEW.CODROTINAALT) THEN
                        :NEW.CODROTINAALT := NULL;
                    END IF;
                END IF;
            END IF;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
END;
