BEGIN
	DECLARE
	v_total  NUMBER := 0;
	v_div    NUMBER := 0; 
	v_len15  NUMBER := 0; 
	BEGIN

	SELECT COUNT(*) INTO v_total FROM PCPEDIFV;
	DBMS_OUTPUT.PUT_LINE('Iniciando migration em PCPEDIFV | linhas='||v_total);

	EXECUTE IMMEDIATE 'ALTER TABLE PCPEDIFV ADD (NUMPEDCLI_NUM_BKP NUMBER(22))';
	EXECUTE IMMEDIATE 'UPDATE PCPEDIFV SET NUMPEDCLI_NUM_BKP = NUMPEDCLI';
	DBMS_OUTPUT.PUT_LINE('Backup em coluna NUMPEDCLI_NUM_BKP criado.');

	EXECUTE IMMEDIATE 'ALTER TABLE PCPEDIFV ADD (NUMPEDCLI_VC VARCHAR2(15))';
	EXECUTE IMMEDIATE q'[
		UPDATE PCPEDIFV
		SET NUMPEDCLI_VC = CASE
								WHEN NUMPEDCLI IS NULL THEN NULL
								ELSE TO_CHAR(NUMPEDCLI, 'TM')
							END
	]';

	EXECUTE IMMEDIATE
		'SELECT COUNT(*) FROM PCPEDIFV
		WHERE NUMPEDCLI IS NOT NULL
			AND TO_NUMBER(NUMPEDCLI_VC) <> NUMPEDCLI'
		INTO v_div;

	EXECUTE IMMEDIATE
		'SELECT COUNT(*) FROM PCPEDIFV
		WHERE NUMPEDCLI_VC IS NOT NULL
			AND LENGTH(NUMPEDCLI_VC) > 15'
		INTO v_len15;

	IF v_div > 0 OR v_len15 > 0 THEN
		RAISE_APPLICATION_ERROR(-20001,
		'Falha na checagem mínima: divergencias='||v_div||' | >15='||v_len15||
		'. Backup de coluna mantido (NUMPEDCLI_NUM_BKP).');
	END IF;

	EXECUTE IMMEDIATE 'ALTER TABLE PCPEDIFV RENAME COLUMN NUMPEDCLI TO NUMPEDCLI_NUM';
	EXECUTE IMMEDIATE 'ALTER TABLE PCPEDIFV RENAME COLUMN NUMPEDCLI_VC TO NUMPEDCLI';

	EXECUTE IMMEDIATE 'ALTER TABLE PCPEDIFV DROP COLUMN NUMPEDCLI_NUM';
	EXECUTE IMMEDIATE 'ALTER TABLE PCPEDIFV DROP COLUMN NUMPEDCLI_NUM_BKP';

	DBMS_OUTPUT.PUT_LINE('Migration executada e limpa com sucesso');
	EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERRO: '||SQLERRM||'. Backup em coluna preservado (NUMPEDCLI_NUM_BKP). CONTATE O SUPORTE PARA RESTAURAÇÃO');
		RAISE;
	END;
END;