DECLARE

  V_SQL_FORMULA_101 VARCHAR2(10000);
  V_SQL_FORMULA_102 VARCHAR2(10000);
  V_SQL_FORMULA_103 VARCHAR2(10000);
  V_SQL_FORMULA_104 VARCHAR2(10000);
  V_SQL_FORMULA_105 VARCHAR2(10000);
  V_SQL_FORMULA_106 VARCHAR2(10000);
  V_SQL_FORMULA_107 VARCHAR2(10000);
  V_SQL_FORMULA_108 VARCHAR2(10000);
  V_SQL_FORMULA_109 VARCHAR2(10000);
  V_SQL_FORMULA_110 VARCHAR2(10000);

  V_SQL_FORMULA_DETALHE_101 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_102 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_103 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_104 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_105 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_106 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_107 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_108 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_109 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_110 VARCHAR2(10000);

BEGIN

  V_SQL_FORMULA_101 := 'SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_102 := 'SELECT CASE WHEN (IP.TOTAL / COUNT(I.CODPROD) * 100) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, (IP.TOTAL / COUNT(I.CODPROD) * 100) VALOR_OBTIDO FROM PCPEDI I, (SELECT P.NUMPED, COUNT(P.CODPROD) TOTAL FROM PCPEDI P, PCDESCONTO D WHERE P.CODPROMOCAOMED = D.CODPROMOCAOMED AND P.CODPROD = D.CODPROD AND P.NUMPED = :NUMPED AND P.CODPROMOCAOMED = :CODPROMOCAOMED AND D.OBRIGATORIOPARCIALMED = ''S'' GROUP BY P.NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_103 := 'SELECT CASE WHEN COUNT(DISTINCT CODPROD) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, COUNT(DISTINCT CODPROD) VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED';
  V_SQL_FORMULA_104 := 'SELECT CASE WHEN COUNT(1) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, COUNT(1) VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_105 := 'SELECT CASE WHEN (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) = 1 THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, NULL PARAMETRO, (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) VALOR_OBTIDO FROM DUAL';
  V_SQL_FORMULA_106 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_107 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_108 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE NUMPED = :NUMPED';
  V_SQL_FORMULA_109 := 'SELECT CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN ''FALSE'' ELSE ''TRUE'' END PODE_SEGUIR, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.PARAMETRO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.PARAMETRO END) END) PARAMETRO, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.VALOR_OBTIDO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.VALOR_OBTIDO END) END) VALOR_OBTIDO FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= B.QTMINMIXFORNECEDORMED THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, B.QTMINMIXFORNECEDORMED PARAMETRO, COUNT(DISTINCT(I.CODPROD)) VALOR_OBTIDO FROM PCPEDI I, PCPRODUT P, (SELECT P.CODFORNEC, SUM(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCDESCONTO D, PCPRODUT P, PCPEDI I WHERE D.CODPROD = P.CODPROD AND D.CODPROD = I.CODPROD AND I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.NUMPED = :NUMPED AND D.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) B WHERE P.CODFORNEC = B.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND B.QTMINMIXFORNECEDORMED > 0 GROUP BY B.QTMINMIXFORNECEDORMED) A';
  V_SQL_FORMULA_110 := 'SELECT CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN ''FALSE'' ELSE ''TRUE'' END PODE_SEGUIR, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.PARAMETRO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.PARAMETRO END) END) PARAMETRO, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.VALOR_OBTIDO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.VALOR_OBTIDO END) END) VALOR_OBTIDO FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= B.QTMINMIXFORNECEDORMED THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, B.QTMINMIXFORNECEDORMED PARAMETRO, COUNT(DISTINCT(I.CODPROD)) VALOR_OBTIDO FROM PCPEDI I, PCPRODUT P, (SELECT P.CODFORNEC, MAX(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCDESCONTO D, PCPRODUT P, PCPEDI I WHERE D.CODPROD = P.CODPROD AND D.CODPROD = I.CODPROD AND I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.NUMPED = :NUMPED AND D.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) B WHERE P.CODFORNEC = B.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND B.QTMINMIXFORNECEDORMED > 0 GROUP BY B.QTMINMIXFORNECEDORMED) A';

  V_SQL_FORMULA_DETALHE_101 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar itens que não estejam vinculados à promoção ou reduzir a quantidade de itens vinculados à promoção.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, (IP.TOTAL / SUM(I.QT * I.PVENDA) * 100) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL) A';
  V_SQL_FORMULA_DETALHE_102 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar mais itens vinculados à promoção no pedido.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN (IP.TOTAL / COUNT(I.CODPROD) * 100) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, (IP.TOTAL / COUNT(I.CODPROD) * 100) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI I, (SELECT P.NUMPED, COUNT(P.CODPROD) TOTAL FROM PCPEDI P, PCDESCONTO D WHERE P.CODPROMOCAOMED = D.CODPROMOCAOMED AND P.CODPROD = D.CODPROD AND P.NUMPED = :NUMPED AND P.CODPROMOCAOMED = :CODPROMOCAOMED AND D.OBRIGATORIOPARCIALMED = ''S'' GROUP BY P.NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY IP.TOTAL) A';
  V_SQL_FORMULA_DETALHE_103 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN CASE WHEN (A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item distinto ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) || '' itens distintos ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(DISTINCT CODPROD) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, COUNT(DISTINCT CODPROD) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED) A';
  V_SQL_FORMULA_DETALHE_104 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN CASE WHEN (A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item da promoção ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) || '' itens da promoção ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(1) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, COUNT(1) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED) A';
  V_SQL_FORMULA_DETALHE_105 := 'SELECT B.REQUISITO_STATUS, B.REQUISITO_VALOR_ALVO, B.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN B.REQUISITO_STATUS = ''F'' THEN ''Remover as demais promoções vinculadas ao pedido, mantendo apenas esta.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) = 1 THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, 1 AS REQUISITO_VALOR_ALVO, (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) AS REQUISITO_VALOR_OBTIDO FROM DUAL) B';
  V_SQL_FORMULA_DETALHE_106 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Reduzir o valor do pedido em '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_OBTIDO - A.REQUISITO_VALOR_ALVO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || ''.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED) A';
  V_SQL_FORMULA_DETALHE_107 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar o valor de '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || '' ao pedido para que ele possa ser gerado usando esta promoção.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED) A';
  V_SQL_FORMULA_DETALHE_108 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar o valor faltante de '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || '' para gerar o pedido.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE NUMPED = :NUMPED) A';
  V_SQL_FORMULA_DETALHE_109 := 'SELECT NULL AS REQUISITO_STATUS, NULL AS REQUISITO_VALOR_ALVO, NULL AS REQUISITO_VALOR_OBTIDO, B.CODFORNEC AS NIVEL_CODIGO, B.FORNECEDOR AS NIVEL_DESCRICAO, B.STATUS AS NIVEL_STATUS, B.VALOR_ALVO AS NIVEL_VALOR_ALVO, B.VALOR_OBTIDO AS NIVEL_VALOR_OBTIDO, CASE WHEN B.STATUS = ''F'' THEN CASE WHEN (B.VALOR_ALVO - B.VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item do fornecedor ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(B.VALOR_ALVO - B.VALOR_OBTIDO) || '' itens do fornecedor ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= A.QTMINMIXFORNECEDORMED THEN ''T'' ELSE ''F'' END AS STATUS, A.QTMINMIXFORNECEDORMED AS VALOR_ALVO, COUNT(DISTINCT(I.CODPROD)) AS VALOR_OBTIDO, F.CODFORNEC, (''Fornecedor '' || TO_CHAR(F.CODFORNEC) || '' - '' || F.FORNECEDOR) AS FORNECEDOR FROM PCPEDI I, PCPRODUT P, PCFORNEC F, (SELECT P.CODFORNEC, SUM(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCDESCONTO D, PCPRODUT P, PCPEDI I WHERE D.CODPROD = P.CODPROD AND D.CODPROD = I.CODPROD AND I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.NUMPED = :NUMPED AND D.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) A WHERE P.CODFORNEC = A.CODFORNEC AND P.CODFORNEC = F.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND A.QTMINMIXFORNECEDORMED > 0 GROUP BY A.QTMINMIXFORNECEDORMED, F.CODFORNEC, F.FORNECEDOR) B';
  V_SQL_FORMULA_DETALHE_110 := 'SELECT NULL AS REQUISITO_STATUS, NULL AS REQUISITO_VALOR_ALVO, NULL AS REQUISITO_VALOR_OBTIDO, B.CODFORNEC AS NIVEL_CODIGO, B.FORNECEDOR AS NIVEL_DESCRICAO, B.STATUS AS NIVEL_STATUS, B.VALOR_ALVO AS NIVEL_VALOR_ALVO, B.VALOR_OBTIDO AS NIVEL_VALOR_OBTIDO, CASE WHEN B.STATUS = ''F'' THEN CASE WHEN (B.VALOR_ALVO - B.VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item do fornecedor ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(B.VALOR_ALVO - B.VALOR_OBTIDO) || '' itens do fornecedor ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= A.QTMINMIXFORNECEDORMED THEN ''T'' ELSE ''F'' END AS STATUS, A.QTMINMIXFORNECEDORMED AS VALOR_ALVO, COUNT(DISTINCT(I.CODPROD)) AS VALOR_OBTIDO, F.CODFORNEC, (''Fornecedor '' || TO_CHAR(F.CODFORNEC) || '' - '' || F.FORNECEDOR) AS FORNECEDOR FROM PCPEDI I, PCPRODUT P, PCFORNEC F, (SELECT P.CODFORNEC, MAX(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCDESCONTO D, PCPRODUT P, PCPEDI I WHERE D.CODPROD = P.CODPROD AND D.CODPROD = I.CODPROD AND I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.NUMPED = :NUMPED AND D.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) A WHERE P.CODFORNEC = A.CODFORNEC AND P.CODFORNEC = F.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND A.QTMINMIXFORNECEDORMED > 0 GROUP BY A.QTMINMIXFORNECEDORMED, F.CODFORNEC, F.FORNECEDOR) B';

  MERGE INTO PCFILTROAVANCADOCONFIG tgt
  USING (     
    SELECT 101 AS CODCONFIG
         , 'CALCULADO' AS TABELA
         , 'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO' AS CAMPO
         , 'NUMBER' AS TIPOCAMPO
         , 'Percentual máximo permitido sobre o valor dos itens da promoção no pedido' AS NOMELIVRE
         , 'I' AS VISIVELFILTRO
         , NULL AS TABELAPESQUISA
         , NULL AS CAMPOPESQUISA
         , NULL AS DESCRICAOPESQUISA
         , NULL AS CRITERIOPESQUISA
         , NULL AS ROTULOPESQUISA
         , 'S' AS VISIVELCONDICAO
         , 'S' AS VISIVELREGRAEXCECAO
         , 'Calculado' AS GRUPO
         , 'PARAM;NUMPED;CODPROMOCAOMED' AS CHAVEMULTIPLA
         , NULL AS NOMEPARAMETRO
		 , 'NUMBER;NUMBER;NUMBER' AS TIPOPARAMETRO
         , NULL AS CODIGONIVEL
         , 'C' AS TIPOVALIDACAO
         , V_SQL_FORMULA_101 AS FORMULASQL
         , V_SQL_FORMULA_DETALHE_101 AS DETALHEFORMULASQL
      FROM DUAL UNION ALL     
    SELECT 102, 'CALCULADO', 'PERCENTUALMINIMOITENSOBRIGATORIOPEDIDO',    'NUMBER',   'Percentual mínimo necessário de itens obrigatórios distintos da promoção no pedido',     'I', NULL, NULL, NULL, NULL, NULL,     'S', 'S', 'Calculado', 'PARAM;NUMPED;CODPROMOCAOMED', NULL, 'NUMBER;NUMBER;NUMBER', NULL, 'C', V_SQL_FORMULA_102, V_SQL_FORMULA_DETALHE_102 FROM DUAL UNION ALL
    SELECT 103, 'CALCULADO', 'QUANTIDADEMINIMAITENSDISTINTOSPEDIDO',      'NUMBER',   'Quantidade mínima necessária de itens distintos no pedido',                              'I', NULL, NULL, NULL, NULL, NULL,     'S', 'S', 'Calculado', 'PARAM;NUMPED',                NULL, 'NUMBER;NUMBER',        NULL, 'C', V_SQL_FORMULA_103, V_SQL_FORMULA_DETALHE_103 FROM DUAL UNION ALL
    SELECT 104, 'CALCULADO', 'QUANTIDADEMINIMAITENSPROMOCAO',             'NUMBER',   'Quantidade mínima necessária de itens distintos da promoção no pedido',                  'I', NULL, NULL, NULL, NULL, NULL,     'S', 'S', 'Calculado', 'PARAM;NUMPED;CODPROMOCAOMED', NULL, 'NUMBER;NUMBER;NUMBER', NULL, 'C', V_SQL_FORMULA_104, V_SQL_FORMULA_DETALHE_104 FROM DUAL UNION ALL
    SELECT 105, 'CALCULADO', 'PROMOCAOUNICAPEDIDO',                       'VARCHAR2', 'Ativa promoção exclusiva contendo apenas itens desta promoção',                          'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', 'NUMPED',                      NULL, 'NUMBER',               NULL, 'C', V_SQL_FORMULA_105, V_SQL_FORMULA_DETALHE_105 FROM DUAL UNION ALL
    SELECT 106, 'CALCULADO', 'VALORMAXIMOPERMITIDOPEDIDO',                'NUMBER',   'Valor máximo permitido para os itens da promoção no pedido',                             'I', NULL, NULL, NULL, NULL, NULL,     'S', 'S', 'Calculado', 'PARAM;NUMPED;CODPROMOCAOMED', NULL, 'NUMBER;NUMBER;NUMBER', NULL, 'C', V_SQL_FORMULA_106, V_SQL_FORMULA_DETALHE_106 FROM DUAL UNION ALL
    SELECT 107, 'CALCULADO', 'VALORMINIMOEXIGIDOATIVARPROMOCAO',          'NUMBER',   'Valor mínimo necessário para os itens da promoção no pedido',                            'I', NULL, NULL, NULL, NULL, NULL,     'S', 'S', 'Calculado', 'PARAM;NUMPED;CODPROMOCAOMED', NULL, 'NUMBER;NUMBER;NUMBER', NULL, 'C', V_SQL_FORMULA_107, V_SQL_FORMULA_DETALHE_107 FROM DUAL UNION ALL
    SELECT 108, 'CALCULADO', 'VALORMINIMOTOTALEXIGIDOPEDIDO',             'NUMBER',   'Valor mínimo necessário para o total do pedido',                                         'I', NULL, NULL, NULL, NULL, NULL,     'S', 'S', 'Calculado', 'PARAM;NUMPED',                NULL, 'NUMBER;NUMBER',        NULL, 'C', V_SQL_FORMULA_108, V_SQL_FORMULA_DETALHE_108 FROM DUAL UNION ALL
    SELECT 109, 'CALCULADO', 'ATIVAVALIDACAOMIXSOMAITENSMESMOFABRICANTE', 'VARCHAR2', 'Ativa validação de mix considerando a soma do mix dos itens de um mesmo fabricante',     'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', 'NUMPED;CODPROMOCAOMED',       NULL, 'NUMBER;NUMBER',        NULL, 'C', V_SQL_FORMULA_109, V_SQL_FORMULA_DETALHE_109 FROM DUAL UNION ALL
    SELECT 110, 'CALCULADO', 'ATIVAVALIDACAOMIXMAIORFABRICANTE',          'VARCHAR2', 'Ativa validação de mix considerando o maior mix entre os itens de um mesmo fabricante',  'I', NULL, NULL, NULL, NULL, 'SIMNAO', 'S', 'S', 'Calculado', 'NUMPED;CODPROMOCAOMED',       NULL, 'NUMBER;NUMBER',        NULL, 'C', V_SQL_FORMULA_110, V_SQL_FORMULA_DETALHE_110 FROM DUAL
  ) src
     ON (tgt.CODCONFIG = src.CODCONFIG)
   WHEN MATCHED THEN UPDATE SET
    tgt.TABELA = src.TABELA
   ,tgt.CAMPO = src.CAMPO
   ,tgt.TIPOCAMPO = src.TIPOCAMPO
   ,tgt.TABELAPESQUISA = src.TABELAPESQUISA
   ,tgt.CAMPOPESQUISA = src.CAMPOPESQUISA
   ,tgt.DESCRICAOPESQUISA = src.DESCRICAOPESQUISA
   ,tgt.CRITERIOPESQUISA = src.CRITERIOPESQUISA
   ,tgt.ROTULOPESQUISA = src.ROTULOPESQUISA
   ,tgt.GRUPO = src.GRUPO
   ,tgt.NOMEPARAMETRO = src.NOMEPARAMETRO
   ,tgt.TIPOPARAMETRO = src.TIPOPARAMETRO   
   ,tgt.CODIGONIVEL = src.CODIGONIVEL
   ,tgt.TIPOVALIDACAO = src.TIPOVALIDACAO
   ,tgt.CHAVEMULTIPLA = src.CHAVEMULTIPLA
   ,tgt.FORMULASQL = src.FORMULASQL
   ,tgt.DETALHEFORMULASQL = src.DETALHEFORMULASQL
   WHEN NOT MATCHED THEN
     INSERT (CODCONFIG, TABELA, CAMPO, TIPOCAMPO, NOMELIVRE, VISIVELFILTRO, TABELAPESQUISA, CAMPOPESQUISA, DESCRICAOPESQUISA, CRITERIOPESQUISA, ROTULOPESQUISA, VISIVELCONDICAO, VISIVELREGRAEXCECAO, GRUPO, NOMEPARAMETRO, TIPOPARAMETRO, CODIGONIVEL, TIPOVALIDACAO, CHAVEMULTIPLA, FORMULASQL, DETALHEFORMULASQL)
     VALUES (src.CODCONFIG, src.TABELA, src.CAMPO, src.TIPOCAMPO, src.NOMELIVRE, src.VISIVELFILTRO, src.TABELAPESQUISA, src.CAMPOPESQUISA, src.DESCRICAOPESQUISA, src.CRITERIOPESQUISA, src.ROTULOPESQUISA, src.VISIVELCONDICAO, src.VISIVELREGRAEXCECAO, src.GRUPO, src.NOMEPARAMETRO, src.TIPOPARAMETRO, src.CODIGONIVEL, src.TIPOVALIDACAO, src.CHAVEMULTIPLA, src.FORMULASQL, src.DETALHEFORMULASQL);

  MERGE INTO PCFILTROAVANCADOLAYOUTC tgt
  USING (
    SELECT 2 AS CODLAYOUT, 
	      'Requisitos de promoção de medicamentos' AS DESCRICAO 
      FROM DUAL
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT)
   WHEN MATCHED THEN UPDATE SET
     tgt.DESCRICAO = src.DESCRICAO
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, DESCRICAO) VALUES (src.CODLAYOUT, src.DESCRICAO);
    
  MERGE INTO PCFILTROAVANCADOLAYOUTI tgt
  USING (
    SELECT 2 AS CODLAYOUT, 
           CODCONFIG 
      FROM PCFILTROAVANCADOCONFIG 
     WHERE TIPOCAMPO <> 'NIVEL' 
       AND CODCONFIG BETWEEN 101 AND 110
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT AND tgt.CODCONFIG = src.CODCONFIG)
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, CODCONFIG) VALUES (src.CODLAYOUT, src.CODCONFIG);

END;