CREATE SEQUENCE DFSEQ_INT_C5_PRODPRECOAPARTIR
minvalue 1
maxvalue 999999999999999999999999999
start with 1
increment by 1
cache 20

\

CREATE OR REPLACE VIEW VW_INT_C5_PRODPRECOAPARTIR AS
(
SELECT DISTINCT
         A.codfilial NROEMPRESA,
         1 NROSEGMENTO,
         A.codauxiliar,
         P.SEQPRODUTO SEQPRODUTO,
         NULL SEQFAMILIA,
         E.QTMINIMAATACADO QTDE,
         0 PERCDESCONTO,
         A.vlofertaatac PRECO,
         B.DTINICIAL DTAINICIO,
         B.DTFINAL DTAFIM,
         (CASE
          WHEN (B.DTCANCEL IS NOT NULL) OR (B.DTFINAL < TRUNC(SYSDATE))  THEN 'N'
          ELSE 'S'
          END)  ATIVO,
         '2011' IDREF
  FROM PCOFERTAPROGRAMADAI A,
       PCOFERTAPROGRAMADAC B,
       PCEMBALAGEM E,
       PCDEPARAEMBALAGENSC5 P,
       monitorpdvmiddle.tb_produto C
  WHERE A.CODOFERTA = B.CODOFERTA
  AND A.CODFILIAL = B.CODFILIAL
  AND A.CODFILIAL = E.CODFILIAL
  AND A.CODAUXILIAR = E.CODAUXILIAR
  AND A.CODAUXILIAR = P.CODAUXILIAR
  AND E.CODAUXILIAR = P.CODAUXILIAR
  AND C.SEQPRODUTO  = P.SEQPRODUTO
  AND A.CODPROD     = C.SEQFAMILIA
  AND E.CODPROD     = A.CODPROD
  AND E.CODPROD     = C.SEQFAMILIA
  AND B.dtinicial IS NOT NULL
  AND B.dtfinal IS NOT NULL
  AND TRUNC(SYSDATE) BETWEEN B.DTINICIAL AND B.DTFINAL
  AND A.VLOFERTAATAC > 0
  AND E.QTMINIMAATACADO > 0
  AND NOT EXISTS(SELECT M.SEQAPARTIRDE
                 FROM MONITORPDVMIDDLE.TB_PRODPRECOAPARTIR M
                 WHERE M.SEQPRODUTO = P.SEQPRODUTO
                 AND   M.NROEMPRESA = A.CODFILIAL
                 AND   M.PRECO = A.VLOFERTAATAC
                 AND   M.QTDE  = E.QTMINIMAATACADO
                 AND   M.ATIVO = 'S')
UNION ALL
SELECT DISTINCT
         E.codfilial NROEMPRESA,
         1 NROSEGMENTO,
         E.codauxiliar,
         P.SEQPRODUTO SEQPRODUTO,
         NULL SEQFAMILIA,
         E.QTMINIMAATACADO QTDE,
         0 PERCDESCONTO,
         E.POFERTAATAC PRECO,
         E.DTOFERTAATACINI DTAINICIO,
         E.DTOFERTAATACFIM DTAFIM,
         'S' ATIVO,
         '2017' IDREF
  FROM PCEMBALAGEM E,
       PCDEPARAEMBALAGENSC5 P,
       monitorpdvmiddle.tb_produto C
  WHERE E.CODAUXILIAR = P.CODAUXILIAR
  AND C.SEQPRODUTO  = P.SEQPRODUTO
  AND E.CODPROD     = C.SEQFAMILIA
  AND E.DTOFERTAATACINI IS NOT NULL
  AND E.DTOFERTAATACFIM IS NOT NULL
  AND TRUNC(SYSDATE) BETWEEN E.DTOFERTAATACINI AND E.DTOFERTAATACFIM
  AND E.POFERTAATAC > 0
  AND E.QTMINIMAATACADO > 0
  AND NVL(E.enviafrentecaixa,'S') = 'S'
  AND E.DTINATIVO IS NULL
  AND NOT EXISTS(SELECT M.SEQAPARTIRDE
                 FROM MONITORPDVMIDDLE.TB_PRODPRECOAPARTIR M
                 WHERE M.SEQPRODUTO = P.SEQPRODUTO
                 AND   M.NROEMPRESA = E.CODFILIAL
                 AND   M.PRECO = E.POFERTAATAC
                 AND   M.QTDE  = E.QTMINIMAATACADO
                 AND   M.ATIVO = 'S')

)