CREATE OR REPLACE VIEW VW_INT_C5_PRODPRECOAPARTIR AS
(
SELECT
  MAX(PRODPRECOAPARTIR.SEQAPARTIRDE)SEQAPARTIRDE,
  PRODPRECOAPARTIR.NROEMPRESA,
  PRODPRECOAPARTIR.NROSEGMENTO,
  PRODPRECOAPARTIR.SEQPRODUTO,
  PRODPRECOAPARTIR.SEQFAMILIA,
  PRODPRECOAPARTIR.QTDE,
  PRODPRECOAPARTIR.PERCDESCONTO,
  PRODPRECOAPARTIR.PRECO,
  PRODPRECOAPARTIR.DTAINICIO,
  PRODPRECOAPARTIR.DTAFIM,
  MAX(PRODPRECOAPARTIR.ATIVO) ATIVO,
  MAX(TO_NUMBER(PRODPRECOAPARTIR.IDREF)) IDREF
FROM (

--Ofertas da 2011 ativas
SELECT DISTINCT
         TO_NUMBER(A.CODFILIAL) NROEMPRESA,
         1 NROSEGMENTO,
         P.SEQPRODUTO SEQPRODUTO,
         0 SEQAPARTIRDE,
         NULL SEQFAMILIA,
         E.QTMINIMAATACADO QTDE,
         0 PERCDESCONTO,
         A.vlofertaatac PRECO,
         B.DTINICIAL DTAINICIO,
         B.DTFINAL DTAFIM,
         '2011' IDREF,
         'S' ATIVO
  FROM PCOFERTAPROGRAMADAI A,
       PCOFERTAPROGRAMADAC B,
       PCEMBALAGEM E,
       PCDEPARAEMBALAGENSC5 P,
       monitorpdvmiddle.tb_produto C,
       VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE A.CODOFERTA = B.CODOFERTA
  AND A.CODFILIAL = B.CODFILIAL
  AND A.CODFILIAL = E.CODFILIAL
  AND A.CODAUXILIAR = E.CODAUXILIAR
  AND A.CODAUXILIAR = P.CODAUXILIAR
  AND E.CODAUXILIAR = P.CODAUXILIAR
  AND C.SEQPRODUTO  = P.SEQPRODUTO
  AND A.CODPROD     = C.SEQFAMILIA
  AND E.CODPROD     = A.CODPROD
  AND E.CODPROD     = C.SEQFAMILIA
  AND B.CODFILIAL = C5.CODFILIAL
  AND B.dtinicial IS NOT NULL
  AND B.dtfinal IS NOT NULL
  AND B.DTCANCEL IS NULL
  AND TRUNC(SYSDATE) BETWEEN B.DTINICIAL AND B.DTFINAL
  AND A.VLOFERTAATAC > 0
  AND E.QTMINIMAATACADO > 0
UNION ALL
--Ofertas da 2017 ativas
SELECT DISTINCT
         TO_NUMBER(E.CODFILIAL) NROEMPRESA,
         1 NROSEGMENTO,
         P.SEQPRODUTO SEQPRODUTO,
         0 SEQAPARTIRDE,
         NULL SEQFAMILIA,
         E.QTMINIMAATACADO QTDE,
         0 PERCDESCONTO,
         E.POFERTAATAC PRECO,
         E.DTOFERTAATACINI DTAINICIO,
         E.DTOFERTAATACFIM DTAFIM,
         '2017' IDREF,
         'S' ATIVO
  FROM PCEMBALAGEM E,
       PCDEPARAEMBALAGENSC5 P,
       monitorpdvmiddle.tb_produto C,
       VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE E.CODAUXILIAR = P.CODAUXILIAR
  AND C.SEQPRODUTO  = P.SEQPRODUTO
  AND E.CODPROD     = C.SEQFAMILIA
  AND E.DTOFERTAATACINI IS NOT NULL
  AND E.DTOFERTAATACFIM IS NOT NULL
  AND TRUNC(SYSDATE) BETWEEN E.DTOFERTAATACINI AND E.DTOFERTAATACFIM
  AND E.POFERTAATAC > 0
  AND E.QTMINIMAATACADO > 0
  AND NVL(E.enviafrentecaixa,'S') = 'S'
  AND E.CODFILIAL = C5.CODFILIAL
  AND E.DTINATIVO IS NULL
UNION ALL
--Ofertas que já desceram pra TB_PRODPRECOAPARTIR e que devem ser desativas
SELECT DISTINCT
         M.NROEMPRESA,
         M.NROSEGMENTO,
         M.SEQPRODUTO,
         M.SEQAPARTIRDE,
         M.SEQFAMILIA,
         M.QTDE,
         M.PERCDESCONTO,
         M.PRECO,
         M.DTAINICIO,
         M.DTAFIM,
         M.IDREF,
         'N' ATIVO
  FROM MONITORPDVMIDDLE.TB_PRODPRECOAPARTIR M
  WHERE TRUNC(SYSDATE) BETWEEN M.DTAINICIO AND M.DTAFIM
  AND  M.IDREF = '0'
  ) PRODPRECOAPARTIR
GROUP BY
  PRODPRECOAPARTIR.NROEMPRESA,
  PRODPRECOAPARTIR.NROSEGMENTO,
  PRODPRECOAPARTIR.SEQPRODUTO,
  PRODPRECOAPARTIR.SEQFAMILIA,
  PRODPRECOAPARTIR.QTDE,
  PRODPRECOAPARTIR.PERCDESCONTO,
  PRODPRECOAPARTIR.PRECO,
  PRODPRECOAPARTIR.DTAINICIO,
  PRODPRECOAPARTIR.DTAFIM
)

