DECLARE
vCount NUMBER;
BEGIN
 vCount := 0;
 BEGIN
  SELECT COUNT(1)
  INTO vCount
  FROM PCSSERVFATATIVO
  WHERE ID = 1;
 END;

 IF vCount <= 0 THEN
   INSERT INTO PCSSERVFATATIVO (ID, ATIVO, BEAT) VALUES (1, 'N', SYSTIMESTAMP);
   COMMIT;
 ELSE
  UPDATE PCSSERVFATATIVO
     SET  BEAT =  SYSTIMESTAMP
   WHERE ID = 1;
   COMMIT;
 END IF;

END;