CREATE OR REPLACE VIEW VW_INT_C5_INUT AS(
  SELECT 'N' EXPORTADO,
        A.NROEMPRESA CODFILIAL,
        D.DTAMOVIMENTO DATA,
        (TO_CHAR(A.DTAHORINUTILIZACAO,'YYYY-MM-DD')) DTHORAPROCESSAMENTO,
        NVL(E.JUSTIFICATIVA,'FALHA COMUNICACAO SEFAZ') JUSTIFICATIVA,
        C.NRONOTAFISCAL NUMNOTAINICIAL,
        C.NRONOTAFISCAL NUMNOTAFINAL,
        A.SERIEDOCTO SERIE,
        TO_CHAR(D.DTAMOVIMENTO,'YYYY') ANO,
        D.SEQUSUARIO CODUSUARIO,
        A.PROTOCOLOINUTILIZACAO,
        E.AMBIENTE,
        A.NROCHECKOUT NUMCAIXA,
        'L' POSICAO,
        D.SEQDOCTO,
        D.ESPECIE,
        D.ROWID AS ROWID_TB_DOCTO
    FROM MONITORPDVMIDDLE.TB_DOCTOINUTNFE A,
        MONITORPDVMIDDLE.TB_DOCTONFE E,
        MONITORPDVMIDDLE.TB_DOCTO D,
        MONITORPDVMIDDLE.TB_DOCTOCUPOM C
  WHERE A.NROEMPRESA = E.NROEMPRESA
    AND A.NROCHECKOUT = E.NROCHECKOUT
    AND A.SEQDOCTO = E.SEQDOCTO
    AND A.NROEMPRESA = C.NROEMPRESA
    AND A.NROCHECKOUT = C.NROCHECKOUT
    AND A.SEQDOCTO = C.SEQDOCTO
    AND A.NROEMPRESA = D.NROEMPRESA
    AND A.NROCHECKOUT = D.NROCHECKOUT
    AND A.SEQDOCTO = D.SEQDOCTO
    AND D.REPLICACAO = 'P'
)