CREATE OR REPLACE VIEW VW_INT_C5_INUT AS(
  SELECT 'N' EXPORTADO,
        C5.CODFILIAL CODFILIAL,
        D.DTAMOVIMENTO DATA,
        (TO_CHAR(D.DTAMOVIMENTO,'YYYY-MM-DD')) DTHORAPROCESSAMENTO,
        NVL(E.JUSTIFICATIVA,'FALHA COMUNICACAO SEFAZ') JUSTIFICATIVA,
        A.NRONOTAFISCAL NUMNOTAINICIAL,
        A.NRONOTAFISCAL NUMNOTAFINAL,
        A.SERIEDOCTO SERIE,
        TO_CHAR(D.DTAMOVIMENTO,'YYYY') ANO,
        D.SEQUSUARIO CODUSUARIO,
        A.PROTOCOLOINUTILIZACAO,
        E.AMBIENTE,
        A.NROCHECKOUT NUMCAIXA,
        'L' POSICAO,
        D.SEQDOCTO,
        D.ESPECIE,
        D.ROWID AS ROWID_TB_DOCTO,
		D.NROEMPRESA,
		D.NROCHECKOUT
    FROM MONITORPDVMIDDLE.TB_DOCTOINUTNFE A,
        MONITORPDVMIDDLE.TB_DOCTONFE E,
        MONITORPDVMIDDLE.TB_DOCTO D,
        MONITORPDVMIDDLE.TB_DOCTOCUPOM C,
		VW_INT_C5_OBTER_FILIAIS_C5 C5
  WHERE A.NROEMPRESA = E.NROEMPRESA
    AND A.NROCHECKOUT = E.NROCHECKOUT
    AND A.SEQDOCTO = E.SEQDOCTO
    AND A.NROEMPRESA = C.NROEMPRESA
    AND A.NROCHECKOUT = C.NROCHECKOUT
    AND A.SEQDOCTO = C.SEQDOCTO
    AND A.NROEMPRESA = D.NROEMPRESA
    AND A.NROCHECKOUT = D.NROCHECKOUT
    AND A.SEQDOCTO = D.SEQDOCTO
	AND C5.CODFILIALINTEGRACAO = A.NROEMPRESA
	AND C5.CODFILIALINTEGRACAO = E.NROEMPRESA
	AND C5.CODFILIALINTEGRACAO = D.NROEMPRESA
	AND C5.CODFILIALINTEGRACAO = C.NROEMPRESA
    --AND D.REPLICACAO = 'P'
    AND NOT EXISTS (SELECT 1
					 FROM PCFILAMENSAGEM M
					WHERE M.SEQDOCTO = D.seqdocto
					  AND M.NUMCAIXA = D.NROCHECKOUT
					  AND M.CODFILIAL = C5.codfilial
					  AND M.TIPOOPERACAO = 'INUT'
					UNION ALL
				   SELECT 1
					 FROM PCFILAMENSAGEMHISTORICO MH
					WHERE MH.SEQDOCTO = D.seqdocto
					  AND MH.NUMCAIXA = TO_CHAR(D.NROCHECKOUT)
					  AND MH.CODFILIAL = C5.codfilial
					  AND MH.TIPOOPERACAO = 'INUT'
					UNION ALL
				   SELECT 1
					 FROM PCFILAMENSAGEMERRO ME
					WHERE ME.SEQDOCTO = D.seqdocto
					  AND ME.NUMCAIXA = D.NROCHECKOUT
					  AND ME.CODFILIAL = C5.codfilial
					  AND ME.TIPOOPERACAO = 'INUT') 
)