CREATE OR REPLACE VIEW SQL_NFE_RODAPE_SAIDA AS
SELECT PCNFSAID.NUMTRANSVENDA AS NUM_TRANSACAO
      ,SUM(PRODUTO.BASE_ICMS) AS BASE_ICMS
      ,SUM(PRODUTO.VALOR_ICMS) AS VALOR_ICMS
      ,SUM(PRODUTO.BASE_ST) AS BASE_ICMS_ST
      ,SUM(PRODUTO.VALOR_ST) AS VALOR_ICMS_ST
      ,SUM(PRODUTO.VALOR_PRODUTOS) AS VALOR_TOTAL_PRODUTOS
      ,SUM(PRODUTO.VALOR_FRETE) AS VALOR_FRETE
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),0) AS VALOR_DESCONTO
      ,SUM(PRODUTO.VALOR_IPI) AS VALOR_IPI
      ,SUM(PRODUTO.VALOR_II) AS VALOR_II
      ,SUM(PRODUTO.VALOR_OUTROS) AS VALOR_OUTRO
      ,PCNFSAID.VLTOTAL AS VALOR_TOTAL
      ,NVL(SUM(PRODUTO.VALOR_COFINS),
           0) VALOR_COFINS
      ,NVL(SUM(PRODUTO.VALOR_PIS),
           0) VALOR_PIS
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),
           0) VLDESCRODAPE
      ,NULL AS INFORMACAOADICIONALFISCO
       -------------- ISSNTOT-----------------------
      ,0 AS BASE_ISS
      ,0 AS VALOR_ISS
       ------------------- FRETE ---------------------
      ,DECODE(NVL(NVL(PCNFSAID.TIPOFRETE, PCNFSAID.FRETEDESPACHO),
                  'N'),
              'C',
              0,
              'F',
              1,
              'T',
              2,
              'R',
              3,
              'D',
              4,
              'G',
              9,
              'N',
              9,
              'S',
              9) AS MODALIDADE_FRETE
       --MODFRETE
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.CGC,
              NVL(FRETEIRO.CGC,
                  PCFILIAL.CGCTRANSP)) AS CNPJ_TRANSPORTADOR
      ,CASE WHEN (PCNFSAID.CODFORNECFRETE IS NOT NULL) THEN
              PCNFSAID.TRANSPORTADORA
              ELSE DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.FORNECEDOR,
              NVL(FRETEIRO.FORNECEDOR,
                  PCFILIAL.RAZAOTRANSP)) END AS TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              DECODE(NVL(FRETEIRO.CONTRIBUINTEICMS,
                         'S'),
                     'S',
                     FRETEIRO.IE,
                     NULL),
              DECODE(NVL(FRETEIRO.CONTRIBUINTEICMS,
                         'S'),
                     'S',
                     NVL(FRETEIRO.IE,
                         PCFILIAL.IETRANSP),
                     NULL)) AS IE_TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              (FRETEIRO.ENDER || ', ' || FRETEIRO.NUMEROEND || ' - ' ||
              FRETEIRO.BAIRRO),
              NVL(DECODE((FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO),
                         ' - ',
                         NULL,
                         (FRETEIRO.ENDER || ', ' || FRETEIRO.NUMEROEND ||
                         ' - ' || FRETEIRO.BAIRRO)),
                  PCFILIAL.ENDTRANSP)) AS END_TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.CIDADE,
              NVL(FRETEIRO.CIDADE,
                  PCFILIAL.CIDADETRANSP)) AS CIDADE_TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.ESTADO,
              NVL(FRETEIRO.ESTADO,
                  PCFILIAL.UFTRANSP)) AS ESTADO_TRANSPORTADOR

      ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PESOLIQIGUALAPESOBRUTONFE',
                                                PCFILIAL.CODIGO),
                  'N'),
              'S',
              NVL(PCNFSAID.TOTPESOAGRUPADO,
                  PCNFSAID.TOTPESO),
              NVL(PCNFSAID.TOTPESOLIQAGRUPADO,
                  (SELECT SUM(NVL(PCMOV.QTCONT,
                                  0) * NVL(NVL(PCMOV.PESOLIQ, PCPRODUT.PESOLIQ),
                                           0))
                   FROM   PCPRODUT
                         ,PCMOV
                   WHERE  PCPRODUT.CODPROD = PCMOV.CODPROD
                   AND    PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA))) AS PESO_LIQUIDO
      ,NVL(PCNFSAID.TOTPESOAGRUPADO, PCNFSAID.TOTPESO) AS PESO_BRUTO
       ------------------ VEICULO --------------------
      ,(SELECT PCVEICUL.ANTT AS ANTT
        FROM   PCVEICUL
        WHERE  PCVEICUL.CODVEICULO =
               NVL(PCNFSAID.CODVEICULO,
                   PCCARREG.CODVEICULO)) AS ANTT
      ,NVL(PCNFSAID.UFPLACAVEIC, PCFILIAL.UF) AS PLACA_UF
      ,PCNFSAID.PLACAVEIC AS PLACA
       ------------------ GRUPO DE VOLUMES -----------
      ,NVL(PCNFSAID.NUMVOLUME, 1) NUM_VOLUME
      ,PCPEDC.MARCAVOLUME
      ,NVL(PCNFSAID.ESPECIEVOLUME, PCPEDC.ESPECIEVOLUME) AS ESPECIEVOLUME
      ,PCPEDC.NUMVOLUME VOLUME_PEDIDO
      --Variavel NVol - Padrão XML e DANFe
       , CASE
           WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('VOLUMEDANFE',PCFILIAL.CODIGO),'Q') = 'Q' THEN
                NVL(NVL(PCNFSAID.NUMVOLUME, PCNFSAID.TOTVOLUMEAGRUPADO), SUM(PRODUTO.QUANTIDADE_COMERCIAL))
           WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('VOLUMEDANFE',PCFILIAL.CODIGO),'X') = 'V' THEN
                NVL(NVL(PCNFSAID.NUMVOLUME, PCNFSAID.TOTVOLUMEAGRUPADO), PCNFSAID.TOTVOLUME)
           WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('VOLUMEDANFE',PCFILIAL.CODIGO),'X') = 'P' THEN
                NVL(NVL(PCNFSAID.NUMVOLUME, PCNFSAID.TOTVOLUMEAGRUPADO), SUM(PRODUTO.QTPECAS))
           ELSE
                NVL(PCNFSAID.NUMVOLUME, 0)
         END AS NUMVOL
       ,SUM(PRODUTO.QTD_EMBALAGEM) AS NUM_VOLUME_EMB
      -- Fim Variavel NVol - Padrão XML e DANFe
      ,SUM(PRODUTO.NUMVOLUMESCONFERENCIA) AS NUMVOLUMESCONFERENCIA
      ,PCNFSAID.DTENTREGA
      ,PCNFSAID.NUMCAR
      ,PCNFSAID.CODMOTORISTA
      ,PCEMPR.NOME AS NOME_MOTORISTA
      ,NULL AS NVOL
      ,PCPLPAG.DESCRICAO AS DESC_PL_PAGTO
      ,SUM(PRODUTO.VLTOTALIMPOSTOS) AS VLTOTALIMPOSTOS
      ,SUM(PRODUTO.VALOR_SEGURO) AS VALOR_TOTAL_SEGURO
      ,SUM(PRODUTO.VLICMSDESONERACAO) AS VALOR_TOTAL_DESONERADO
      ,SUM(NVL(PRODUTO.VLFCPPART, 0)) AS VLFCPPART
      ,SUM(NVL(PRODUTO.VLICMSPARTDEST, 0)) AS VLICMSPARTDEST
      ,SUM(NVL(PRODUTO.VLICMSPARTREM, 0)) AS VLICMSPARTREM
      ,SUM(NVL(PRODUTO.VLBASEFCPICMS, 0)) AS VLBASEFCPICMS
      ,SUM(NVL(PRODUTO.VLBASEFCPST, 0)) AS VLBASEFCPST
      ,SUM(NVL(PRODUTO.VLBCFCPSTRET, 0)) AS VLBCFCPSTRET
      ,SUM(NVL(PRODUTO.VLFCPSTRET, 0)) AS VLFCPSTRET
      ,SUM(NVL(PRODUTO.VLCREDFCPICMSSN, 0)) AS VLCREDFCPICMSSN
      ,SUM(NVL(PRODUTO.VLFECP, 0)) AS VLFECP
      ,SUM(NVL(PRODUTO.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP
      ,CASE
           WHEN PCNFSAID.TIPOVENDA = 'DF' THEN
                SUM(NVL(PRODUTO.VALOR_IPI_OUTROS, 0))  
           WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('DESTACAIPIVLOUTRA',PCFILIAL.CODIGO),'N') = 'S' THEN
                0
           ELSE
                SUM(NVL(PRODUTO.VALOR_IPI_OUTROS, 0))
       END AS VALOR_IPI_DEVOLVIDO
      ,PCNFSAID.DATACONSOLIDACAOPREFAT
      ,'N' PREFATURAMENTO
      ,SUM(NVL(PRODUTO.QBCMONO, 0)) AS QBCMONO
      ,SUM(NVL(PRODUTO.VICMSMONO, 0)) AS VICMSMONO
      ,SUM(NVL(PRODUTO.QBCMONORETEN, 0)) AS QBCMONORETEN
      ,SUM(NVL(PRODUTO.VICMSMONORETEN, 0)) AS VICMSMONORETEN
      ,SUM(NVL(PRODUTO.QBCMONODIF, 0)) AS QBCMONODIF
      ,SUM(NVL(PRODUTO.VICMSMONODIF, 0)) AS VICMSMONODIF
      ,SUM(NVL(PRODUTO.QBCMONORET, 0)) AS QBCMONORET
      ,SUM(NVL(PRODUTO.VICMSMONORET, 0)) AS VICMSMONORET      
      ,PRODUTO.GERAGRPRETTRIB
      ,SUM(NVL(PRODUTO.VLPISRETORGPUB, 0)) AS VLPISRETORGPUB
      ,SUM(NVL(PRODUTO.VLCOFINSRETORGPUB, 0)) AS VLCOFINSRETORGPUB
      ,SUM(NVL(PRODUTO.VLCSLLRETORGPUB, 0)) AS VLCSLLRETORGPUB
      ,SUM(NVL(PRODUTO.VLIRPJRETORGPUB, 0)) AS VLIRPJRETORGPUB
      ,SUM(NVL(PRODUTO.VLBCIRRFRETORGPUB, 0)) AS VLBCIRRFRETORGPUB      
       --Retenção do ICMS de transporte
      ,PCNFSAID.VLSERVICOFRETEAUTON AS VALOR_SERVICO_TRANSP
      ,PCNFSAID.VLBASEFRETEAUTON AS BASE_RETENCAO_ICMS_TRANSP
      ,PCNFSAID.ALIQICMFRETEAUTON AS PERC_RETENCAO_ICMS_TRANSP
      ,PCNFSAID.VLICMFRETEAUTON AS VALOR_RETENCAO_ICMS_TRANSP
      ,PCNFSAID.CODFISCALFRETEAUTON AS CFOP_TRANSP
      ,PCNFSAID.CODMUNICIPFATGERADOR AS COD_MUN_FATO_GERADOR_TRANSP
      ,PCNFSAID.FINALIDADENFE
FROM   PCNFSAID
      ,PCFORNEC FRETEIRO
      ,PCCARREG
      ,PCPEDC
      ,PCEMPR
      ,PCFILIAL
      ,TABLE(NFE_PRODUTO_SAIDA(PCNFSAID.NUMTRANSVENDA)) PRODUTO
      ,PCPLPAG
WHERE  PCNFSAID.NUMCAR = PCCARREG.NUMCAR(+)
AND    PCNFSAID.CODMOTORISTA = PCEMPR.MATRICULA(+)
AND    PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
AND    PCNFSAID.CODFORNECFRETE = FRETEIRO.CODFORNEC(+)
AND    PCNFSAID.CODPLPAG = PCPLPAG.CODPLPAG(+)
AND    NVL(PCNFSAID.CODFILIALNF,
           PCNFSAID.CODFILIAL) = PCFILIAL.CODIGO
AND    PRODUTO.PREFATURAMENTO = 'N'
GROUP  BY PCNFSAID.NUMTRANSVENDA
,PCNFSAID.VLTOTAL
,PCNFSAID.TIPOFRETE
,PCNFSAID.FRETEDESPACHO
,PCFILIAL.USATRANSPORTADOPADRAONFE
,FRETEIRO.CGC
,PRODUTO.GERAGRPRETTRIB
,PCFILIAL.CGCTRANSP
,FRETEIRO.FORNECEDOR
,PCFILIAL.RAZAOTRANSP
,FRETEIRO.CONTRIBUINTEICMS
,FRETEIRO.IE
,PCFILIAL.IETRANSP
,FRETEIRO.ENDER
,FRETEIRO.NUMEROEND
,FRETEIRO.BAIRRO
,PCFILIAL.ENDTRANSP
,FRETEIRO.CIDADE
,PCFILIAL.CIDADETRANSP
,FRETEIRO.ESTADO
,PCFILIAL.UFTRANSP
,PCFILIAL.CODIGO
,PCNFSAID.TOTPESOAGRUPADO
,PCNFSAID.TOTPESO
,PCNFSAID.TOTPESOLIQAGRUPADO
,PCNFSAID.CODVEICULO
,PCCARREG.CODVEICULO
,PCNFSAID.UFPLACAVEIC
,PCFILIAL.UF
,PCNFSAID.PLACAVEIC
,PCNFSAID.NUMVOLUME
,PCPEDC.MARCAVOLUME
,PCNFSAID.ESPECIEVOLUME
,PCPEDC.ESPECIEVOLUME
,PCPEDC.NUMVOLUME
,PCNFSAID.TOTVOLUMEAGRUPADO
,PCNFSAID.TOTVOLUME
,PCNFSAID.DTENTREGA
,PCNFSAID.NUMCAR
,PCNFSAID.CODMOTORISTA
,PCEMPR.NOME
,PCPLPAG.DESCRICAO
,PCNFSAID.CODFORNECFRETE
,PCNFSAID.TRANSPORTADORA
,PCNFSAID.DATACONSOLIDACAOPREFAT
,PCNFSAID.VLSERVICOFRETEAUTON
,PCNFSAID.VLBASEFRETEAUTON
,PCNFSAID.ALIQICMFRETEAUTON
,PCNFSAID.VLICMFRETEAUTON
,PCNFSAID.CODFISCALFRETEAUTON
,PCNFSAID.CODMUNICIPFATGERADOR
,PCNFSAID.FINALIDADENFE
,PCNFSAID.TIPOVENDA
UNION ALL
SELECT PCNFSAIDPREFAT.NUMTRANSVENDA AS NUM_TRANSACAO
      ,SUM(PRODUTO.BASE_ICMS) AS BASE_ICMS
      ,SUM(PRODUTO.VALOR_ICMS) AS VALOR_ICMS
      ,SUM(PRODUTO.BASE_ST) AS BASE_ICMS_ST
      ,SUM(PRODUTO.VALOR_ST) AS VALOR_ICMS_ST
      ,SUM(PRODUTO.VALOR_PRODUTOS) AS VALOR_TOTAL_PRODUTOS
      ,SUM(PRODUTO.VALOR_FRETE) AS VALOR_FRETE
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),0) AS VALOR_DESCONTO
      ,SUM(PRODUTO.VALOR_IPI) AS VALOR_IPI
      ,SUM(PRODUTO.VALOR_II) AS VALOR_II
      ,SUM(PRODUTO.VALOR_OUTROS) AS VALOR_OUTRO
      ,PCNFSAIDPREFAT.VLTOTAL AS VALOR_TOTAL
      ,NVL(SUM(PRODUTO.VALOR_COFINS),
           0) VALOR_COFINS
      ,NVL(SUM(PRODUTO.VALOR_PIS),
           0) VALOR_PIS
      ,NVL(SUM(PRODUTO.VALOR_DESCONTO),
           0) VLDESCRODAPE
      ,NULL AS INFORMACAOADICIONALFISCO
       -------------- ISSNTOT-----------------------
      ,0 AS BASE_ISS
      ,0 AS VALOR_ISS
       ------------------- FRETE ---------------------
      ,DECODE(NVL(NVL(PCNFSAIDPREFAT.TIPOFRETE, PCNFSAIDPREFAT.FRETEDESPACHO),
                  'N'),
              'C',
              0,
              'F',
              1,
              'T',
              2,
              'R',
              3,
              'D',
              4,
              'G',
              9,
              'N',
              9,
              'S',
              9) AS MODALIDADE_FRETE
       --MODFRETE
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.CGC,
              NVL(FRETEIRO.CGC,
                  PCFILIAL.CGCTRANSP)) AS CNPJ_TRANSPORTADOR
      ,CASE WHEN (PCNFSAIDPREFAT.CODFORNECFRETE IS NOT NULL) THEN
              PCNFSAIDPREFAT.TRANSPORTADORA
              ELSE DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.FORNECEDOR,
              NVL(FRETEIRO.FORNECEDOR,
                  PCFILIAL.RAZAOTRANSP)) END AS TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              DECODE(NVL(FRETEIRO.CONTRIBUINTEICMS,
                         'S'),
                     'S',
                     FRETEIRO.IE,
                     NULL),
              DECODE(NVL(FRETEIRO.CONTRIBUINTEICMS,
                         'S'),
                     'S',
                     NVL(FRETEIRO.IE,
                         PCFILIAL.IETRANSP),
                     NULL)) AS IE_TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              (FRETEIRO.ENDER || ', ' || FRETEIRO.NUMEROEND || ' - ' ||
              FRETEIRO.BAIRRO),
              NVL(DECODE((FRETEIRO.ENDER || ' - ' || FRETEIRO.BAIRRO),
                         ' - ',
                         NULL,
                         (FRETEIRO.ENDER || ', ' || FRETEIRO.NUMEROEND ||
                         ' - ' || FRETEIRO.BAIRRO)),
                  PCFILIAL.ENDTRANSP)) AS END_TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.CIDADE,
              NVL(FRETEIRO.CIDADE,
                  PCFILIAL.CIDADETRANSP)) AS CIDADE_TRANSPORTADOR
      ,DECODE(NVL(PCFILIAL.USATRANSPORTADOPADRAONFE,
                  'N'),
              'N',
              FRETEIRO.ESTADO,
              NVL(FRETEIRO.ESTADO,
                  PCFILIAL.UFTRANSP)) AS ESTADO_TRANSPORTADOR

      ,DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PESOLIQIGUALAPESOBRUTONFE',
                                                PCFILIAL.CODIGO),
                  'N'),
              'S',
              NVL(PCNFSAIDPREFAT.TOTPESOAGRUPADO,
                  PCNFSAIDPREFAT.TOTPESO),
              NVL(PCNFSAIDPREFAT.TOTPESOLIQAGRUPADO,
                  (SELECT SUM(NVL(PCMOVPREFAT.QTCONT,
                                  0) * NVL(NVL(PCMOVPREFAT.PESOLIQ, PCPRODUT.PESOLIQ),
                                           0))
                   FROM   PCPRODUT
                         ,PCMOVPREFAT
                   WHERE  PCPRODUT.CODPROD = PCMOVPREFAT.CODPROD
                   AND    PCMOVPREFAT.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA))) AS PESO_LIQUIDO
      ,NVL(PCNFSAIDPREFAT.TOTPESOAGRUPADO,
           PCNFSAIDPREFAT.TOTPESO) AS
       ------------------ VEICULO --------------------
      ,

       (SELECT PCVEICUL.ANTT AS ANTT
        FROM   PCVEICUL
        WHERE  PCVEICUL.CODVEICULO =
               NVL(PCNFSAIDPREFAT.CODVEICULO,
                   PCCARREG.CODVEICULO)) AS ANTT
      ,NVL(
       PCNFSAIDPREFAT.UFPLACAVEIC, PCFILIAL.UF)/*,
       (SELECT PCVEICUL.UFPLACAVEICULO AS UFPLACAVEICUL
        FROM   PCVEICUL
        WHERE  PCVEICUL.CODVEICULO =
               NVL(PCNFSAIDPREFAT.CODVEICULO,
                   PCCARREG.CODVEICULO)))*/
                   AS PLACA_UF
      ,
       --NVL(
       PCNFSAIDPREFAT.PLACAVEIC
       /*(SELECT PCVEICUL.PLACA AS PLACA
        FROM   PCVEICUL
        WHERE  PCVEICUL.CODVEICULO =
               NVL(PCNFSAIDPREFAT.CODVEICULO,
                   PCCARREG.CODVEICULO)))*/ AS PLACA

       /*
                                     VEICULO.ANTT,
                                     NVL(PCNFSAIDPREFAT.PLACAVEIC, DECODE(NVL(VEICULO.UFPLACAVEICULO,
                                                'XX'),
                                            'XX',
                                            NULL,
                                            NVL(PCNFSAIDPREFAT.PLACAVEIC,
                                                DECODE(NVL(PCCARREG.NUMCAR,
                                                           0),
                                                       0,
                                                       NULL,
                                                       DECODE(PRODUTO.COD_OPERACAO,
                                                              'SD',
                                                              NULL,
                                                              VEICULO.PLACA))))) AS PLACA,
                                     NVL(PCNFSAIDPREFAT.UFPLACAVEIC,VEICULO.UFPLACAVEICULO) AS PLACA_UF*/
       ------------------ GRUPO DE VOLUMES -----------
      ,NVL(PCNFSAIDPREFAT.NUMVOLUME,
           1) NUM_VOLUME
      ,PCPEDC.MARCAVOLUME
      ,NVL(PCNFSAIDPREFAT.ESPECIEVOLUME,
           PCPEDC.ESPECIEVOLUME) AS ESPECIEVOLUME
      ,PCPEDC.NUMVOLUME VOLUME_PEDIDO
      --Variavel NVol - Padrão XML e DANFe
       ,CASE
         WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('VOLUMEDANFE',PCFILIAL.CODIGO),'Q') = 'Q' THEN
          NVL(NVL(PCNFSAIDPREFAT.NUMVOLUME, PCNFSAIDPREFAT.TOTVOLUMEAGRUPADO), SUM(PRODUTO.QUANTIDADE_COMERCIAL))
         WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('VOLUMEDANFE',PCFILIAL.CODIGO),'X') = 'V' THEN
          NVL(NVL(PCNFSAIDPREFAT.NUMVOLUME, PCNFSAIDPREFAT.TOTVOLUMEAGRUPADO), PCNFSAIDPREFAT.TOTVOLUME)
         WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('VOLUMEDANFE',PCFILIAL.CODIGO),'X') = 'P' THEN
          NVL(NVL(PCNFSAIDPREFAT.NUMVOLUME, PCNFSAIDPREFAT.TOTVOLUMEAGRUPADO), SUM(PRODUTO.QTPECAS))
         ELSE
          NVL(PCNFSAIDPREFAT.NUMVOLUME, 0)
         END as NUMVOL
       ,SUM(PRODUTO.QTD_EMBALAGEM) AS NUM_VOLUME_EMB
      -- Fim Variavel NVol - Padrão XML e DANFe
      /*,NVL(NVL(PCNFSAIDPREFAT.NUMVOLUME,
               PCNFSAIDPREFAT.TOTVOLUMEAGRUPADO),
           SUM(PRODUTO.QUANTIDADE_COMERCIAL)) AS NUMVOL*/ --Realizado acima conforme tarefa: 157328
      ,SUM(PRODUTO.NUMVOLUMESCONFERENCIA) AS NUMVOLUMESCONFERENCIA
      ,PCNFSAIDPREFAT.DTENTREGA
      ,PCNFSAIDPREFAT.NUMCAR
      ,PCNFSAIDPREFAT.CODMOTORISTA
      ,PCEMPR.NOME AS NOME_MOTORISTA
      ,NULL AS NVOL
      ,PCPLPAG.DESCRICAO AS DESC_PL_PAGTO
      ,SUM(PRODUTO.VLTOTALIMPOSTOS) AS VLTOTALIMPOSTOS
      ,SUM(PRODUTO.VALOR_SEGURO) AS VALOR_TOTAL_SEGURO
      ,SUM(PRODUTO.VLICMSDESONERACAO) AS VALOR_TOTAL_DESONERADO
      ,SUM(NVL(PRODUTO.VLFCPPART, 0)) AS VLFCPPART
      ,SUM(NVL(PRODUTO.VLICMSPARTDEST, 0)) AS VLICMSPARTDEST
      ,SUM(NVL(PRODUTO.VLICMSPARTREM, 0)) AS VLICMSPARTREM
      ,SUM(NVL(PRODUTO.VLBASEFCPICMS, 0)) AS VLBASEFCPICMS
      ,SUM(NVL(PRODUTO.VLBASEFCPST, 0)) AS VLBASEFCPST
      ,SUM(NVL(PRODUTO.VLBCFCPSTRET, 0)) AS VLBCFCPSTRET
      ,SUM(NVL(PRODUTO.VLFCPSTRET, 0)) AS VLFCPSTRET
      ,SUM(NVL(PRODUTO.VLCREDFCPICMSSN, 0)) AS VLCREDFCPICMSSN
      ,SUM(NVL(PRODUTO.VLFECP, 0)) AS VLFECP
      ,SUM(NVL(PRODUTO.VLACRESCIMOFUNCEP, 0)) AS VLACRESCIMOFUNCEP
      ,CASE
           WHEN PCNFSAIDPREFAT.TIPOVENDA = 'DF' THEN
                SUM(NVL(PRODUTO.VALOR_IPI_OUTROS, 0))
           WHEN NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('DESTACAIPIVLOUTRA',PCFILIAL.CODIGO),'N') = 'S' THEN
                0
           ELSE
                SUM(NVL(PRODUTO.VALOR_IPI_OUTROS, 0))
       END AS VALOR_IPI_DEVOLVIDO
      ,PCNFSAIDPREFAT.DATACONSOLIDACAOPREFAT
      ,'S' PREFATURAMENTO
      ,SUM(NVL(PRODUTO.QBCMONO, 0)) AS QBCMONO
      ,SUM(NVL(PRODUTO.VICMSMONO, 0)) AS VICMSMONO
      ,SUM(NVL(PRODUTO.QBCMONORETEN, 0)) AS QBCMONORETEN
      ,SUM(NVL(PRODUTO.VICMSMONORETEN, 0)) AS VICMSMONORETEN
      ,SUM(NVL(PRODUTO.QBCMONODIF, 0)) AS QBCMONODIF
      ,SUM(NVL(PRODUTO.VICMSMONODIF, 0)) AS VICMSMONODIF
      ,SUM(NVL(PRODUTO.QBCMONORET, 0)) AS QBCMONORET
      ,SUM(NVL(PRODUTO.VICMSMONORET, 0)) AS VICMSMONORET      
      ,PRODUTO.GERAGRPRETTRIB
      ,SUM(NVL(PRODUTO.VLPISRETORGPUB, 0)) AS VLPISRETORGPUB
      ,SUM(NVL(PRODUTO.VLCOFINSRETORGPUB, 0)) AS VLCOFINSRETORGPUB
      ,SUM(NVL(PRODUTO.VLCSLLRETORGPUB, 0)) AS VLCSLLRETORGPUB
      ,SUM(NVL(PRODUTO.VLIRPJRETORGPUB, 0)) AS VLIRPJRETORGPUB
      ,SUM(NVL(PRODUTO.VLBCIRRFRETORGPUB, 0)) AS VLBCIRRFRETORGPUB      
      ,PCNFSAIDPREFAT.VLSERVICOFRETEAUTON
      ,PCNFSAIDPREFAT.VLBASEFRETEAUTON
      ,PCNFSAIDPREFAT.ALIQICMFRETEAUTON
      ,PCNFSAIDPREFAT.VLICMFRETEAUTON
      ,PCNFSAIDPREFAT.CODFISCALFRETEAUTON
      ,PCNFSAIDPREFAT.CODMUNICIPFATGERADOR
      ,PCNFSAIDPREFAT.FINALIDADENFE
FROM   PCNFSAIDPREFAT
      ,PCFORNEC FRETEIRO
      ,PCCARREG
      ,PCPEDC
      ,PCEMPR
      ,PCFILIAL
      ,TABLE(NFE_PRODUTO_SAIDA(PCNFSAIDPREFAT.NUMTRANSVENDA)) PRODUTO
      ,PCPLPAG
WHERE  PCNFSAIDPREFAT.NUMCAR = PCCARREG.NUMCAR(+)
AND    PCNFSAIDPREFAT.CODMOTORISTA = PCEMPR.MATRICULA(+)
AND    PCNFSAIDPREFAT.NUMPED = PCPEDC.NUMPED(+)
AND    PCNFSAIDPREFAT.CODFORNECFRETE = FRETEIRO.CODFORNEC(+)
AND    PCNFSAIDPREFAT.CODPLPAG = PCPLPAG.CODPLPAG(+)
AND    NVL(PCNFSAIDPREFAT.CODFILIALNF,
           PCNFSAIDPREFAT.CODFILIAL) = PCFILIAL.CODIGO
AND    PCNFSAIDPREFAT.DATACONSOLIDACAOPREFAT IS NULL
AND    PRODUTO.PREFATURAMENTO = 'S'
GROUP  BY PCNFSAIDPREFAT.NUMTRANSVENDA
,PCNFSAIDPREFAT.VLTOTAL
,PCNFSAIDPREFAT.TIPOFRETE
,PCNFSAIDPREFAT.FRETEDESPACHO
,PCFILIAL.USATRANSPORTADOPADRAONFE
,FRETEIRO.CGC
,PRODUTO.GERAGRPRETTRIB
,PCFILIAL.CGCTRANSP
,FRETEIRO.FORNECEDOR
,PCFILIAL.RAZAOTRANSP
,FRETEIRO.CONTRIBUINTEICMS
,FRETEIRO.IE
,PCFILIAL.IETRANSP
,FRETEIRO.ENDER
,FRETEIRO.NUMEROEND
,FRETEIRO.BAIRRO
,PCFILIAL.ENDTRANSP
,FRETEIRO.CIDADE
,PCFILIAL.CIDADETRANSP
,FRETEIRO.ESTADO
,PCFILIAL.UFTRANSP
,PCFILIAL.CODIGO
,PCNFSAIDPREFAT.TOTPESOAGRUPADO
,PCNFSAIDPREFAT.TOTPESO
,PCNFSAIDPREFAT.TOTPESOLIQAGRUPADO
,PCNFSAIDPREFAT.CODVEICULO
,PCCARREG.CODVEICULO
,PCNFSAIDPREFAT.UFPLACAVEIC
,PCFILIAL.UF
,PCNFSAIDPREFAT.PLACAVEIC
,PCNFSAIDPREFAT.NUMVOLUME
,PCPEDC.MARCAVOLUME
,PCNFSAIDPREFAT.ESPECIEVOLUME
,PCPEDC.ESPECIEVOLUME
,PCPEDC.NUMVOLUME
,PCNFSAIDPREFAT.TOTVOLUMEAGRUPADO
,PCNFSAIDPREFAT.TOTVOLUME
,PCNFSAIDPREFAT.DTENTREGA
,PCNFSAIDPREFAT.NUMCAR
,PCNFSAIDPREFAT.CODMOTORISTA
,PCEMPR.NOME
,PCPLPAG.DESCRICAO
,PCNFSAIDPREFAT.CODFORNECFRETE
,PCNFSAIDPREFAT.TRANSPORTADORA
,PCNFSAIDPREFAT.DATACONSOLIDACAOPREFAT
,PCNFSAIDPREFAT.VLSERVICOFRETEAUTON
,PCNFSAIDPREFAT.VLBASEFRETEAUTON
,PCNFSAIDPREFAT.ALIQICMFRETEAUTON
,PCNFSAIDPREFAT.VLICMFRETEAUTON
,PCNFSAIDPREFAT.CODFISCALFRETEAUTON
,PCNFSAIDPREFAT.CODMUNICIPFATGERADOR
,PCNFSAIDPREFAT.FINALIDADENFE
,PCNFSAIDPREFAT.TIPOVENDA