CREATE OR REPLACE FUNCTION F_OBTERNOMEAPLICACAO 
  RETURN VARCHAR2 
IS
  NOME VARCHAR2(100);
BEGIN
  NOME := NULL;
  /*Para versões do Oracle 12 acima*/
  BEGIN
    NOME := SYS_CONTEXT('userenv', 'CLIENT_PROGRAM_NAME');
  EXCEPTION WHEN OTHERS THEN
    NOME := NULL;
  END;
  /*Para outras versões do Oracle anteriores ao 12*/
  IF NOME IS NULL THEN
    NOME := SYS_CONTEXT('userenv', 'MODULE');
  END IF;
  
  RETURN NOME;
EXCEPTION WHEN OTHERS THEN
  RETURN 'Erro na: F_OBTERNOMEAPLICACAO';
END F_OBTERNOMEAPLICACAO;