CREATE OR REPLACE FUNCTION REPROCESSAR_FINANC3LANCFINIMP(PDATA      IN DATE,
                                                         PCODFILIAL IN VARCHAR2)
  RETURN VARCHAR2 IS
  VTOTALPCFINANC NUMBER;
  PRAGMA AUTONOMOUS_TRANSACTION;
  V_MENSSAGEM VARCHAR2(20);
BEGIN
  BEGIN
    SELECT COUNT(1) TOTAL
      INTO VTOTALPCFINANC
      FROM PCFINANC3LANCFINIMP
     WHERE DATAREFERENCIA = PDATA
       AND CODFILIAL = PCODFILIAL
       AND CODROTINAGERACAO <> 117;

    IF VTOTALPCFINANC = 0 THEN
      INSERT INTO PCFINANC3LANCFINIMP
        (DATAREFERENCIA
        ,DATAGERACAO
        ,CODROTINAGERACAO
        ,CODFILIAL
        ,TIPODADO
        ,RECNUM
        ,RECNUMPRINC
        ,DTLANC
        ,CODGRUPO
        ,CODCONTA
        ,CODFORNEC
        ,NUMNOTA
        ,DUPLIC
        ,VALOR
        ,DTVENC
        ,VPAGO
        ,DTPAGTO
        ,TIPOPARCEIRO
        ,DTDESD
        ,VALORDEV
        ,TXPERM
        ,DESCONTOFIN
        ,NUMBORDERO
        ,VPAGOBORDERO
        ,INVESTIMENTO
        ,CON_CODCONTEMPREST
        ,CODCONTAEMPRESTIMONACIONAL
        ,CODCONTAEMPRESTIMOESTRANGEIRO
        ,CODROTINA)
        SELECT PDATA
              ,TRUNC(SYSDATE)
              ,CODROTINAGERACAO
              ,CODFILIAL
              ,TIPODADO
              ,RECNUM
              ,RECNUMPRINC
              ,DTLANC
              ,CODGRUPO
              ,CODCONTA
              ,CODFORNEC
              ,NUMNOTA
              ,DUPLIC
              ,VALOR
              ,DTVENC
              ,VPAGO
              ,DTPAGTO
              ,TIPOPARCEIRO
              ,DTDESD
              ,VALORDEV
              ,TXPERM
              ,DESCONTOFIN
              ,NUMBORDERO
              ,VPAGOBORDERO
              ,INVESTIMENTO
              ,CON_CODCONTEMPREST
              ,CODCONTAEMPRESTIMONACIONAL
              ,CODCONTAEMPRESTIMOESTRANGEIRO
              ,CODROTINA
          FROM PCFINANC3LANCFINIMP
         WHERE DATAREFERENCIA = PDATA - 1
           AND CODFILIAL = PCODFILIAL
           AND CODROTINAGERACAO <> 117;

      V_MENSSAGEM := 'OK';
	  COMMIT;

    ELSE
      V_MENSSAGEM := 'Tabela não está vazia';
    END IF;

  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, ('Erro original: ' || SQLERRM));
	ROLLBACK;  
  END;

  RETURN V_MENSSAGEM;
END;
