DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PCMED_TEMP_PREMIA_COMPLEMPRO'
     AND COLUMN_NAME = 'CODFILIALORIGINAL'
     AND DATA_TYPE = 'VARCHAR2'
     AND DATA_LENGTH = 2;

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PCMED_TEMP_PREMIA_COMPLEMPRO ADD CODFILIALORIGINAL_TMP VARCHAR2(2)';
    EXECUTE IMMEDIATE 'UPDATE PCMED_TEMP_PREMIA_COMPLEMPRO SET CODFILIALORIGINAL_TMP = TO_CHAR(CODFILIALORIGINAL)';
    EXECUTE IMMEDIATE 'ALTER TABLE PCMED_TEMP_PREMIA_COMPLEMPRO DROP COLUMN CODFILIALORIGINAL';
    EXECUTE IMMEDIATE 'ALTER TABLE PCMED_TEMP_PREMIA_COMPLEMPRO RENAME COLUMN CODFILIALORIGINAL_TMP TO CODFILIALORIGINAL';
  END IF;
END;