CREATE OR REPLACE FUNCTION GET_SQL_LIVRO_ENTRADA(PDIAANTERIOR IN BOOLEAN) RETURN VARCHAR2 IS
    v_sql VARCHAR2(4000);
BEGIN
    v_sql := 'SELECT PCNFBASEENT.CODFILIALNF
      ,PCNFBASEENT.NUMTRANSENT
      ,PCNFBASEENT.DTENTRADA
      ,PCNFBASEENT.DTEMISSAO
      ,PCNFBASEENT.ESPECIE
      ,PCNFBASEENT.SERIE
      ,PCNFBASEENT.NUMNOTA
      ,PCNFBASEENT.CODFORNEC
      ,PCNFBASEENT.UF
      ,PCNFBASEENT.VLTOTAL
      ,PCNFBASEENT.CODCONT
      ,PCNFBASEENT.CODFISCAL
      ,PCNFBASEENT.VLBASE
      ,PCNFBASEENT.VLICMS
      ,PCNFBASEENT.VLISENTAS
      ,PCNFBASEENT.VLOUTRAS
      ,PCNFBASEENT.OBS
      ,PCNFBASEENT.FLAG
      ,PCNFBASEENT.PERCICM
      ,PCNFBASEENT.VLDESDOBRADO
      ,PCNFBASEENT.BASEST
      ,PCNFBASEENT.VLST
      ,PCNFBASEENT.ALIQUOTA
      ,PCNFBASEENT.VLBASEIPI
      ,PCNFBASEENT.VLIPI
      ,PCNFBASEENT.PERCIPI
      ,PCNFBASEENT.ALIQDIF
      ,PCNFBASEENT.DTGERA
      ,PCNFBASEENT.TIPOCOMPRA
      ,PCNFBASEENT.BCIMPESTADUAL
      ,PCNFBASEENT.VLIMPESTADUAL
      ,PCNFBASEENT.BASESTFORANF
      ,PCNFBASEENT.VLSTFORANF
      ,PCNFBASEENT.TIPOREGISTRO
      ,PCNFBASEENT.VLISENTAS_DAPI
      ,PCNFBASEENT.VLNAOTRIB_DAPI
      ,PCNFBASEENT.VLBASERED_DAPI
      ,PCNFBASEENT.VLSUSPENSAS_DAPI
      ,PCNFBASEENT.VLST_DAPI
      ,PCNFBASEENT.VLOUTRAS_DAPI
      ,PCNFBASEENT.FORNECEDOR
      ,PCNFBASEENT.CGC
      ,PCNFBASEENT.IE
      ,PCNFBASEENT.VLISENTASIPI
      ,PCNFBASEENT.VLOUTRASIPI
      ,PCNFBASEENT.VLBASEFRETE
      ,PCNFBASEENT.VLBASEOUTRASDESP
      ,PCNFBASEENT.VLFRETE
      ,PCNFBASEENT.VLOUTRASDESP
      ,PCNFBASEENT.VLBASENAOTRIB
      ,PCNFBASEENT.CODOPER
      ,PCNFBASEENT.UFFILIAL
      ,PCNFBASEENT.VLPIS
      ,PCNFBASEENT.VLCOFINS
      ,PCNFBASEENT.VLBASE_REDUCAO
      ,PCNFBASEENT.VLBASEOUTRASIPI
      ,PCNFBASEENT.VLBASEISENTASIPI
      ,PCNFBASEENT.SITTRIBUT
      ,PCNFBASEENT.PERCICMNAOTRIB
      ,PCNFBASEENT.VLICMSNAOTRIB
      ,PCNFBASEENT.VLCREDPRESUMIDO
      ,PCNFBASEENT.VLSISCOMEX
      ,PCNFBASEENT.VLIMPORTACAO
      ,PCNFBASEENT.VLCAPATAZIA
      ,PCNFBASEENT.VLAFRMM
      ,PCNFBASEENT.VLSEGURO
      ,PCNFBASEENT.VLADUANEIRA
      ,PCNFBASEENT.VLOUTRASDESPIMP
      ,PCNFBASEENT.VLANTIDUMPING
      ,PCNFBASEENT.VLPISCALCDI
      ,PCNFBASEENT.VLCOFINSCALCDI
      ,PCNFBASEENT.VLFRETECONT
      ,PCNFBASEENT.VLFCP
      ,PCNFBASEENT.VLICMSUFREM
      ,PCNFBASEENT.VLICMSUFDEST
      ,PCNFBASEENT.VLICMSDIFALIQPART
      ,PCNFBASEENT.VLBASEPARTDEST
      ,PCNFBASEENT.VLDIFALIQUOTA
      ,PCNFBASEENT.VLCREDITO_CIAP
      ,PCNFBASEENT.PERCIMPPRODUTORRURAL
      ,PCNFBASEENT.VLOUTROSCUSTOSCUSTO
      ,PCNFBASEENT.VLICMSANTECIPADO
      ,PCNFBASEENT.VLIMPPRODUTORURAL
      ,PCNFBASEENT.VLOUTROSCUSTOS
      ,PCNFBASEENT.VLFECP
      ,PCNFBASEENT.VLACRESCIMOFUNCEP
      ,PCNFBASEENT.VLDESPFORANF
      ,PCNFBASEENT.VLFRETECONHEC
      ,PCNFBASEENT.PERACRESCIMOFUNCEP
      ,PCNFBASEENT.VLBASEFCPICMS
      ,PCNFBASEENT.VLBASEFCPST
      ,PCNFBASEENT.ALIQICMSFECP
      ,PCNFBASEENT.PERCREDBASEPISCOFINSFRETE
      ,PCNFBASEENT.VLICMSBCR
      ,PCNFBASEENT.VLSTBCR
      ,PCNFBASEENT.VLICMSBR
      ,PCNFBASEENT.VLFECPSTGUIA
      ,PCNFENT.TIPODESCARGA
      ,PCNFENT.IMPORTADOXML
  FROM PCNFBASEENT
 INNER JOIN PCNFENT
    ON PCNFENT.NUMTRANSENT = PCNFBASEENT.NUMTRANSENT
   AND PCNFENT.DTEMISSAO = PCNFBASEENT.DTEMISSAO ';
     IF PDIAANTERIOR THEN
    V_SQL := V_SQL || ' WHERE PCNFENT.DTEMISSAO BETWEEN TRUNC(SYSDATE-90) AND  TRUNC(SYSDATE-1) ';
  ELSE
    V_SQL := V_SQL || ' WHERE PCNFENT.DTEMISSAO BETWEEN TRUNC(SYSDATE-90) AND TRUNC(SYSDATE) ';
  END IF;
    RETURN v_sql;
END;
