DECLARE
   V_EXISTE USER_CONSTRAINTS.CONSTRAINT_NAME%TYPE;
BEGIN
   SELECT T.CONSTRAINT_NAME
     INTO V_EXISTE
     FROM USER_CONSTRAINTS T
    WHERE T.CONSTRAINT_NAME = 'PCVIGENCIANTSEFAZ_UK1'
      AND T.TABLE_NAME = 'PCVIGENCIANTSEFAZ'
      AND OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER');
   IF NOT V_EXISTE IS NULL THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PCVIGENCIANTSEFAZ DROP CONSTRAINT PCVIGENCIANTSEFAZ_UK1';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      V_EXISTE := NULL;
END;
\
DECLARE
  vSQL VARCHAR2(200);
BEGIN
  vSQL := 'UPDATE PCVIGENCIANTSEFAZ SET UF = ''BR'' WHERE NVL(UF, ''XX'') = ''XX''';
  EXECUTE IMMEDIATE vSQL;
  COMMIT;  
 
  vSQL := 'ALTER TABLE PCVIGENCIANTSEFAZ ADD CONSTRAINT PCVIGENCIANTSEFAZ_UK1 UNIQUE (IDENTIFICADOR_NT, UF) USING INDEX TABLESPACE TS_DADOS';
  EXECUTE IMMEDIATE vSQL;
END;