CREATE OR REPLACE TRIGGER TRG_PCFILTROAVANCADO
BEFORE INSERT OR UPDATE ON PCFILTROAVANCADO
FOR EACH ROW
BEGIN
  BEGIN
    SELECT CASE WHEN COUNT(DISTINCT CONFIG.TIPOVALIDACAO) > 1
             THEN 'A'
             ELSE MAX(CONFIG.TIPOVALIDACAO)
           END
      INTO :NEW.TIPOVALIDACAO
      FROM PCFILTROAVANCADOCONFIG CONFIG
     WHERE EXISTS(
      SELECT 1
        FROM PCFILTROAVANCADOCONDICAO
       WHERE CODCONFIG = CONFIG.CODCONFIG
         AND CODIGO = :NEW.CODIGO
      UNION
      SELECT 1
        FROM PCFILTROAVANCADOREGRA
       WHERE CODCONFIG = CONFIG.CODCONFIG
         AND CODIGO = :NEW.CODIGO
      UNION
      SELECT 1
        FROM PCFILTROAVANCADOEXCECAO
       WHERE CODCONFIG = CONFIG.CODCONFIG
         AND CODIGO = :NEW.CODIGO);
  EXCEPTION
    WHEN NO_DATA_FOUND  THEN
      :NEW.TIPOVALIDACAO := 'A';
  END;
END;