CREATE OR REPLACE FUNCTION GET_SQL_LIVRO_SAIDA(PDIAANTERIOR IN BOOLEAN) RETURN VARCHAR2 IS
  V_SQL VARCHAR2(4000);
BEGIN
  V_SQL := 'SELECT PCNFSAID.CONDVENDA
      ,PCNFBASESAID.CODFILIALNF
      ,PCNFBASESAID.NUMTRANSVENDA
      ,PCNFBASESAID.ESPECIE
      ,PCNFBASESAID.SERIE
      ,PCNFBASESAID.NUMNOTA
      ,PCNFBASESAID.DTSAIDA
      ,PCNFBASESAID.DTCANCEL
      ,PCNFBASESAID.CODCLI
      ,PCNFBASESAID.PERCICM
      ,PCNFBASESAID.UF
      ,PCNFBASESAID.VLTOTAL
      ,PCNFBASESAID.CODCONT
      ,PCNFBASESAID.CODFISCAL
      ,PCNFBASESAID.VLBASE
      ,PCNFBASESAID.VLICMS
      ,PCNFBASESAID.VLISENTAS
      ,PCNFBASESAID.VLOUTRAS
      ,PCNFBASESAID.OBS
      ,PCNFBASESAID.FLAG
      ,PCNFBASESAID.VLDESDOBRADO
      ,PCNFBASESAID.TIPOVENDA
      ,PCNFBASESAID.BASEST
      ,PCNFBASESAID.VLST
      ,PCNFBASESAID.VLBASEIPI
      ,PCNFBASESAID.VLIPI
      ,PCNFBASESAID.PERCIPI
      ,PCNFBASESAID.DTGERA
      ,PCNFBASESAID.BCIMPESTADUAL
      ,PCNFBASESAID.VLIMPESTADUAL
      ,PCNFBASESAID.TIPOFJ
      ,PCNFBASESAID.VLPISRETIDO
      ,PCNFBASESAID.VLREPASSE
      ,PCNFBASESAID.VLBASEBCR
      ,PCNFBASESAID.VLSTBCR
      ,PCNFBASESAID.TIPOREGISTRO
      ,PCNFBASESAID.VLISENTAS_DAPI
      ,PCNFBASESAID.VLNAOTRIB_DAPI
      ,PCNFBASESAID.VLBASERED_DAPI
      ,PCNFBASESAID.VLSUSPENSAS_DAPI
      ,PCNFBASESAID.VLST_DAPI
      ,PCNFBASESAID.VLOUTRAS_DAPI
      ,PCNFBASESAID.CLIENTE
      ,PCNFBASESAID.CGC
      ,PCNFBASESAID.IE
      ,PCNFBASESAID.VLISENTASIPI
      ,PCNFBASESAID.VLOUTRASIPI
      ,PCNFBASESAID.VLBASEFRETE
      ,PCNFBASESAID.VLBASEOUTRASDESP
      ,PCNFBASESAID.VLFRETE
      ,PCNFBASESAID.VLOUTRASDESP
      ,PCNFBASESAID.SUBSERIE
      ,PCNFBASESAID.VLBASENAOTRIB
      ,PCNFBASESAID.CODOPER
      ,PCNFBASESAID.UFFILIAL
      ,PCNFBASESAID.VLPIS
      ,PCNFBASESAID.VLCOFINS
      ,PCNFBASESAID.VLBASE_REDUCAO
      ,PCNFBASESAID.BASESTFORANF
      ,PCNFBASESAID.VLSTFORANF
      ,PCNFBASESAID.VLBASEOUTRASIPI
      ,PCNFBASESAID.VLBASEISENTASIPI
      ,PCNFBASESAID.VLICMSDIFERIDO
      ,PCNFBASESAID.SITTRIBUT
      ,PCNFBASESAID.PERCICMNAOTRIB
      ,PCNFBASESAID.VLICMSNAOTRIB
      ,PCNFBASESAID.VLDESCREDUCAOPIS
      ,PCNFBASESAID.VLDESCREDUCAOCOFINS
      ,PCNFBASESAID.VLCREDPRESUMIDO
      ,PCNFBASESAID.VLFCP
      ,PCNFBASESAID.VLICMSUFREM
      ,PCNFBASESAID.VLICMSUFDEST
      ,PCNFBASESAID.VLICMSDIFALIQPART
      ,PCNFBASESAID.VLBASEPARTDEST
      ,PCNFBASESAID.VLIPIDEVFORNEC
      ,PCNFBASESAID.VLFECP
      ,PCNFBASESAID.VLACRESCIMOFUNCEP
      ,PCNFBASESAID.PERACRESCIMOFUNCEP
      ,PCNFBASESAID.VLBASEFCPICMS
      ,PCNFBASESAID.VLBASEFCPST
      ,PCNFBASESAID.ALIQICMSFECP
      ,PCNFBASESAID.VLICMSBCR
      ,PCNFBASESAID.VLICMSBR
  FROM PCNFBASESAID
 INNER JOIN PCNFSAID
    ON PCNFSAID.NUMTRANSVENDA = PCNFBASESAID.NUMTRANSVENDA
   AND PCNFSAID.DTSAIDA = PCNFBASESAID.DTSAIDA ';
  IF PDIAANTERIOR THEN
    V_SQL := V_SQL ||
             ' WHERE PCNFBASESAID.DTSAIDA BETWEEN TRUNC(SYSDATE-90) AND TRUNC(SYSDATE-1) ';
  ELSE
    V_SQL := V_SQL ||
             ' WHERE PCNFBASESAID.DTSAIDA BETWEEN TRUNC(SYSDATE-90) AND TRUNC(SYSDATE) ';
  END IF;
  RETURN V_SQL;
END;
