DECLARE
vSQL VARCHAR2(200);
BEGIN
 -- CRIANDO TABELA DE BKP
 vSQL := 'create table PCCOMPOSICAO_BKPPROD as (select * from PCCOMPOSICAO)';
 EXECUTE IMMEDIATE vSQL;
 vSQL := 'create table PCMAPACOMPOSICAO_BKPPROD as (select * from PCMAPACOMPOSICAO)'; 
 EXECUTE IMMEDIATE vSQL;
 
 
 -- add a coluna temporaria na tabela PCCOMPOSICAO
 vSQL := 'ALTER TABLE PCCOMPOSICAO ADD OBSMETODOTEMPS VARCHAR2(200)';
 EXECUTE IMMEDIATE vSQL;
 -- add a coluna temporaria na tabela PCMAPACOMPOSICAO
  vSQL := 'ALTER TABLE PCMAPACOMPOSICAO ADD OBSMETODOTEMPS VARCHAR2(200)';
 EXECUTE IMMEDIATE vSQL;
 
 -- clonando os registros da coluna OBSMETODO para a coluna OBSMETODOTEMPS
 vSQL := 'UPDATE PCCOMPOSICAO SET OBSMETODOTEMPS = OBSMETODO';
 EXECUTE IMMEDIATE vSQL;
 -- clonando os registros da coluna OBSMETODO para a coluna OBSMETODOTEMPS
  vSQL := 'UPDATE PCMAPACOMPOSICAO SET OBSMETODOTEMPS = OBSMETODO';
 EXECUTE IMMEDIATE vSQL;
 
 -- excluindo a coluna OBSMETODO da tabela PCCOMPOSICAO  
 vSQL :='ALTER TABLE PCCOMPOSICAO DROP COLUMN OBSMETODO';
 EXECUTE IMMEDIATE vSQL;
  -- excluindo a coluna OBSMETODO da tabela PCMAPACOMPOSICAO  
 vSQL :='ALTER TABLE PCMAPACOMPOSICAO DROP COLUMN OBSMETODO';
 EXECUTE IMMEDIATE vSQL;
  
 -- add o campo OBSMETODO no tipo clob na tabela PCCOMPOSICAO 
 vSQL := 'ALTER TABLE PCCOMPOSICAO ADD OBSMETODO CLOB';
 EXECUTE IMMEDIATE vSQL;
  -- add o campo OBSMETODO no tipo clob na tabela PCMAPACOMPOSICAO 
 vSQL := 'ALTER TABLE PCMAPACOMPOSICAO ADD OBSMETODO CLOB';
 EXECUTE IMMEDIATE vSQL;

-- clonando os valores da coluna OBSMETODOTEMPS para a coluna OBSMETODO
 vSQL := 'UPDATE PCCOMPOSICAO SET OBSMETODO = OBSMETODOTEMPS'; 
  EXECUTE IMMEDIATE vSQL;
  
  -- clonando os valores da coluna OBSMETODOTEMPS para a coluna OBSMETODO
 vSQL := 'UPDATE PCMAPACOMPOSICAO SET OBSMETODO = OBSMETODOTEMPS'; 
  EXECUTE IMMEDIATE vSQL;
 
 COMMIT;  
END;