CREATE OR REPLACE VIEW VW_INT_C5_PCPEDICANCECF AS
SELECT  D.ROWID ROWID_TB_DOCTO,
        I.SEQDOCTO,
        'N' EXPORTADO,
        I.CODACESSO CODAUXILIAR,
        I.NROEMPRESA CODFILIAL,
        D.SEQUSUARIO CODFUNCCANCEL,
        D.SEQUSUARIO CODFUNCCANCELECF,
        D.SEQUSUARIO CODFUNCCX,
        NVL(C.SEQPESSOA,1) CODCLI,
        (CASE
            WHEN C.STATUS = 'C'
                THEN 'S'
            ELSE
                'N'
         END) CUPOMFECHADO,
        NULL CANCMANUAL,
        V.SEQFAMILIA CODPROD,
        V.CODCEST CODCEST,
        FNC_INT_C5_CODUSUR(D.SEQUSUARIO) CODUSUR,
        A.CODST,
        TO_CHAR(D.DTAHOREMISSAO,'YYYY-MM-DD') DATA,
        TO_CHAR(D.DTAMOVIMENTO,'YYYY-MM-DD') DTCANCEL,
        TO_CHAR(D.DTAHORINCLUSAO,'YYYY-MM-DD') DTCANCELECF,
        TO_CHAR(D.DTAHORINCLUSAO,'YYYY-MM-DD') DTEXPORTACAO,
        NULL DTEXPORTACAOSERVINT,
        NULL DTIMPORTACAOSERVPRINC,
        NULL EXPORTADOSERVINT,
        'N' IMPORTADO,
        NULL IMPORTADOSERVPRINC,
        NULL MD5PAF,
        NULL MOTIVOCANCELAMENTO,
        I.NROCHECKOUT NUMCAIXA,
        0 NUMCCF,
        NULL NUMCAR,
        C.NRONOTAFISCAL NUMCUPOM,
        NULL NUMPED,
        'NOTAFISCAL' NUMSERIEEQUIP,
        I.SEQITEM NUMSEQ,
        NULL PERCBASERED,
        0 PERCBASEREDST,
        0 PERCBASEREDSTFONTE,
        NULL PERCICM,
        0 PERCIPI,
        0 PERCOM,
        ROUND(NVL(((NVL(I.VLRDESCONTO,0)/ I.QUANTIDADE) * 100)/ I.VLRUNITARIO, 0), 6) PERDESC,
        0 PERFRETECMV,
        NULL POSICAORETORNO,
        I.VLRUNITARIO PORIGINAL,
        I.VLRUNITARIO - (NVL(I.VLRDESCONTO,0)/ I.QUANTIDADE) PVENDA,
        0 ST,
        FNC_INT_C5_TIPO_CANCEL_ITEM(I.SEQDOCTO,I.NROCHECKOUT,I.NROEMPRESA,I.SEQITEM) TIPOCANCEL,
        NULL VLACRESCRODAPE,
        (SELECT VLCUSTOFIN
           FROM VW_INT_C5_CUSTOS
          WHERE CODFILIAL = I.NROEMPRESA
            AND CODAUXILIAR = I.CODACESSO) VLCUSTOFIN,
        0 VLCUSTOREAL,
        0 VLCUSTOREP,
        0 VLCUSTOCONT,
        I.VLRDESCONTO VLDESCFIN,
        0 VLDESCRODAPE,
        0 VLIPI,
        0 VLOUTRASDESP,
        0 QTFALTA,
    0 TOTPESO,
        I.QUANTIDADE QT,
        '2099' ROTINALANC,
        NULL TOTALIZADOR
  FROM  MONITORPDVMIDDLE.TB_DOCTOITEM   I,
        MONITORPDVMIDDLE.TB_DOCTO       D,
        MONITORPDVMIDDLE.TB_DOCTOCUPOM  C,
        MONITORPDVMIDDLE.TB_PRODUTO     P,
        MONITORPDVMIDDLE.TB_DOCTOTRIBUTACAOITEM TI,
        MONITORPDVMIDDLE.TB_FAMILIA     V,
        PCCONSOLIDATRIBUTACAO           A,
        VW_INT_C5_TIPOCANCEL            ITEM
 WHERE  I.SEQDOCTO = D.SEQDOCTO
   AND  I.NROEMPRESA = D.NROEMPRESA
   AND  I.NROCHECKOUT = D.NROCHECKOUT
   AND  I.SEQPRODUTO = P.SEQPRODUTO
   AND  D.SEQDOCTO = C.SEQDOCTO
   AND  D.NROEMPRESA = C.NROEMPRESA
   AND  D.NROCHECKOUT = C.NROCHECKOUT
   AND  P.SEQPRODUTO = V.SEQFAMILIA
   AND  I.SEQPRODUTO = V.SEQFAMILIA
   AND  I.SEQDOCTO = TI.SEQDOCTO
   AND  I.NROCHECKOUT = TI.NROCHECKOUT
   AND  I.NROEMPRESA = TI.NROEMPRESA
   AND  I.SEQITEM = TI.SEQITEM
   AND  I.NROTRIBUTACAO = A.CODST
   AND  A.NUMREGIAO = FERRAMENTAS.F_BUSCARPARAMETRO_NUM('NUMREGIAOPADRAOVAREJO',D.NROEMPRESA,1)
   AND  C.SEQDOCTO = ITEM.SEQDOCTO
   AND  C.NROEMPRESA = ITEM.NROEMPRESA
   AND  ((I.STATUS = 'C'
         AND
         (C.STATUS = DECODE(ITEM.TIPOCANCEL,'P','V',I.STATUS)))
          OR
          (C.STATUS = 'C'))
