DECLARE
  vsVALOR_ABATER_FECP PCGMPARAMETRO.VALOR%TYPE;
  vsVALOR_ABATER_IPI  PCGMPARAMETRO.VALOR%TYPE;
  vsVALOR_ABATER_ST   PCGMPARAMETRO.VALOR%TYPE;  
  
  FUNCTION GET_PARAMETRO(pCHAVE PCGMPARAMETRO.CHAVE%TYPE) 
    RETURN PCGMPARAMETRO.VALOR%TYPE IS
  vsVALOR PCGMPARAMETRO.VALOR%TYPE;
  BEGIN
    BEGIN
        SELECT VALOR INTO vsVALOR FROM PCGMPARAMETRO WHERE CHAVE = pCHAVE;
    EXCEPTION
      WHEN OTHERS THEN
        vsVALOR := 'N';
    END;
    RETURN vsVALOR;
  END;
    
  PROCEDURE INSERT_PARAMETRO(pCHAVE PCGMPARAMETRO.CHAVE%TYPE, 
                        pVALOR PCGMPARAMETRO.VALOR%TYPE) IS
  vnQTDE NUMBER;
  BEGIN
    SELECT COUNT(*) INTO vnQTDE FROM PCGMPARAMETRO WHERE CHAVE = pCHAVE;
    IF vnQTDE = 0 THEN 
      INSERT INTO PCGMPARAMETRO(CHAVE, VALOR) VALUES(pCHAVE, pVALOR);
    END IF;
  END;
BEGIN
  --ABATER_VALOR_FECP
  vsVALOR_ABATER_FECP := GET_PARAMETRO('ABATER_VALOR_FECP');
  INSERT_PARAMETRO('ABATER_VALOR_FECP_META'    ,vsVALOR_ABATER_FECP);
  INSERT_PARAMETRO('ABATER_VALOR_FECP_COMISSAO',vsVALOR_ABATER_FECP);
  
  --ABATER_VALOR_IPI
  vsVALOR_ABATER_IPI := GET_PARAMETRO('ABATER_VALOR_IPI');
  INSERT_PARAMETRO('ABATER_VALOR_IPI_META'     ,vsVALOR_ABATER_IPI);
  INSERT_PARAMETRO('ABATER_VALOR_IPI_COMISSAO' ,vsVALOR_ABATER_IPI);
  
  --ABATER_VALOR_ST
  vsVALOR_ABATER_ST := GET_PARAMETRO('ABATER_VALOR_ST');
  INSERT_PARAMETRO('ABATER_VALOR_ST_META'      ,vsVALOR_ABATER_ST);
  INSERT_PARAMETRO('ABATER_VALOR_ST_COMISSAO'  ,vsVALOR_ABATER_ST);
END;