CREATE OR REPLACE FUNCTION PODE_DEVOLVER(P_CODIGO NUMBER) RETURN VARCHAR2 IS
  RESULTADO VARCHAR2(1);
BEGIN

  SELECT DECODE(P_CODIGO,
                100,
                'S',
                'N')
  INTO   RESULTADO
  FROM   DUAL;

  RETURN RESULTADO;

END; 