BEGIN
    DELETE FROM PCPARAMINTEGRACAOWMSSAAS
    WHERE PARAMETRO IN ('TIPODOCUMENTOINTEGRADORECEBIMENTO');

    DELETE FROM PCPARAMINTEGRACAOWMSSAASROTULO
    WHERE PARAMETRO IN ('TIPODOCUMENTOINTEGRADORECEBIMENTO');
    COMMIT;
END;