CREATE OR REPLACE PACKAGE PKG_INT_C5_CANCELAMENTO IS
  PROCEDURE PROCESSAR_CANCELAMENTO(P_SEQDOCTO NUMBER DEFAULT 0,
                                   P_NROCHECKOUT NUMBER DEFAULT 0,
                                   P_NROEMPRESA  NUMBER DEFAULT 0) ;
END PKG_INT_C5_CANCELAMENTO;