DECLARE

  vCODIGO NUMBER;
  vDESCRICAO VARCHAR2(70);
  vQTD_TABELA NUMBER;
  vOBJETO_TRIGGER_EXISTE VARCHAR2(1);

BEGIN

  SELECT COUNT(*)
    INTO vQTD_TABELA
    FROM USER_TABLES
   WHERE TABLE_NAME = 'PCRESTRICAOAVANCADACONFIG';

  IF vQTD_TABELA > 0 THEN

    FOR DADOS IN (SELECT * FROM PCRESTRICAOAVANCADA WHERE CODFILTROAVANCADO IS NULL ORDER BY CODIGO) LOOP

      SELECT DFSEQ_PCFILTROAVANCADO.NEXTVAL
        INTO vCODIGO
        FROM DUAL;

      vDESCRICAO := 'FILTRO: '|| DADOS.CODIGO || ' - ' || DADOS.DESCRICAO;

      INSERT INTO PCFILTROAVANCADO(CODIGO, DESCRICAO, CODLAYOUT, TIPOVALIDACAO)
             VALUES(vCODIGO, vDESCRICAO, 1, DADOS.TIPOVALIDACAO);
             
      INSERT INTO PCFILTROAVANCADOCONDICAO(CODIGO, CODCONFIG, OPERADOR, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO)
      SELECT vCODIGO, CODCONFIG, OPERADOR, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO 
        FROM PCRESTRICAOAVANCADACONDICAO
       WHERE CODIGO = DADOS.CODIGO;
       
      INSERT INTO PCFILTROAVANCADOREGRA(CODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO)
      SELECT vCODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO
        FROM PCRESTRICAOAVANCADAREGRA
       WHERE CODIGO = DADOS.CODIGO;

      INSERT INTO PCFILTROAVANCADOEXCECAO(CODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO)
      SELECT vCODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO 
        FROM PCRESTRICAOAVANCADAEXCECAO
       WHERE CODIGO = DADOS.CODIGO;
       
      UPDATE PCRESTRICAOAVANCADA
         SET CODFILTROAVANCADO = vCODIGO
       WHERE CODIGO = DADOS.CODIGO;

    END LOOP;

    MERGE INTO PCFILTROAVANCADOCONFIG tgt
    USING (SELECT * FROM PCRESTRICAOAVANCADACONFIG) src
       ON (tgt.CODCONFIG = src.CODCONFIG)
     WHEN MATCHED THEN UPDATE SET tgt.NOMELIVRE = src.NOMELIVRE
                                , tgt.VISIVELFILTRO = src.VISIVELFILTRO
                                , tgt.VISIVELCONDICAO = src.CONDICAO
                                , tgt.VISIVELREGRAEXCECAO = src.REGRAEXCECAO;

    DELETE FROM PCRESTRICAOAVANCADACONDICAO;
    DELETE FROM PCRESTRICAOAVANCADAREGRA;
    DELETE FROM PCRESTRICAOAVANCADAEXCECAO;
    DELETE FROM PCRESTRICAOAVANCADACONFIG;

  END IF;

  BEGIN

    SELECT 'S'
      INTO vOBJETO_TRIGGER_EXISTE
      FROM ALL_TRIGGERS T
    WHERE T.OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
      AND T.TRIGGER_NAME = 'TRG_PCRESTRICAOAVANCADA';

  EXCEPTION

    WHEN NO_DATA_FOUND THEN
      vOBJETO_TRIGGER_EXISTE := 'N';

  END;

  IF vOBJETO_TRIGGER_EXISTE = 'S' THEN

    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PCRESTRICAOAVANCADA';

  END IF;

END;