DECLARE
  vCODIGO NUMBER;
  vDESCRICAO VARCHAR2(70);
BEGIN
  FOR DADOS IN(SELECT * FROM PCRESTRICAOAVANCADA ORDER BY CODIGO) LOOP

    vCODIGO := DFSEQ_PCFILTROAVANCADO.NEXTVAL;
    vDESCRICAO := 'FILTRO: '|| DADOS.CODIGO || ' - ' || DADOS.DESCRICAO;

    INSERT INTO PCFILTROAVANCADO(CODIGO, DESCRICAO, CODLAYOUT, TIPOVALIDACAO)
           VALUES(vCODIGO, vDESCRICAO, 1, DADOS.TIPOVALIDACAO);
           
    INSERT INTO PCFILTROAVANCADOCONDICAO(CODIGO, CODCONFIG, OPERADOR, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO)
    SELECT vCODIGO, CODCONFIG, OPERADOR, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO 
      FROM PCRESTRICAOAVANCADACONDICAO
     WHERE CODIGO = DADOS.CODIGO;
     
    INSERT INTO PCFILTROAVANCADOREGRA(CODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO)
    SELECT vCODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO
      FROM PCRESTRICAOAVANCADAREGRA
     WHERE CODIGO = DADOS.CODIGO;

    INSERT INTO PCFILTROAVANCADOEXCECAO(CODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO)
    SELECT vCODIGO, CODCONFIG, OPERADOR, NUMREGRA, VALOR_VARCHAR, INICIAL_NUMBER, FINAL_NUMBER, INICIAL_DATE, FINAL_DATE, DATA_CORRENTE, NUMCRITERIO 
      FROM PCRESTRICAOAVANCADAEXCECAO
     WHERE CODIGO = DADOS.CODIGO;
     
    UPDATE PCRESTRICAOAVANCADA SET
      CODFILTROAVANCADO = vCODIGO
     WHERE CODIGO = DADOS.CODIGO;
  END LOOP;

  MERGE INTO PCFILTROAVANCADOCONFIG tgt
  USING (SELECT * FROM PCRESTRICAOAVANCADACONFIG) src 
     ON (tgt.CODCONFIG = src.CODCONFIG)
   WHEN MATCHED THEN UPDATE SET
     tgt.NOMELIVRE = src.NOMELIVRE
    ,tgt.VISIVELFILTRO = src.VISIVELFILTRO
    ,tgt.VISIVELCONDICAO = src.CONDICAO
    ,tgt.VISIVELREGRAEXCECAO = src.REGRAEXCECAO;
    
  DELETE FROM PCRESTRICAOAVANCADACONDICAO;
  DELETE FROM PCFILTROAVANCADOREGRA;
  DELETE FROM PCRESTRICAOAVANCADAEXCECAO;
  DELETE FROM PCRESTRICAOAVANCADACONFIG;
END;