DECLARE

  V_SQL_FORMULA_101 VARCHAR2(10000);
  V_SQL_FORMULA_102 VARCHAR2(10000);
  V_SQL_FORMULA_103 VARCHAR2(10000);
  V_SQL_FORMULA_104 VARCHAR2(10000);
  V_SQL_FORMULA_105 VARCHAR2(10000);
  V_SQL_FORMULA_106 VARCHAR2(10000);
  V_SQL_FORMULA_107 VARCHAR2(10000);
  V_SQL_FORMULA_108 VARCHAR2(10000);
  V_SQL_FORMULA_109 VARCHAR2(10000);
  V_SQL_FORMULA_110 VARCHAR2(10000);
  V_SQL_FORMULA_111 VARCHAR2(10000);
  V_SQL_FORMULA_112 VARCHAR2(10000);
  V_SQL_FORMULA_113 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_101 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_102 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_103 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_104 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_105 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_106 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_107 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_108 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_109 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_110 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_111 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_112 VARCHAR2(10000);
  V_SQL_FORMULA_DETALHE_113 VARCHAR2(10000);

BEGIN

  V_SQL_FORMULA_101 := 'SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_102 := 'SELECT CASE WHEN (IP.TOTAL / COUNT(DISTINCT I.CODPROD) * 100) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, (IP.TOTAL / COUNT(DISTINCT I.CODPROD) * 100) VALOR_OBTIDO FROM PCPEDI I, (SELECT P.NUMPED, COUNT(DISTINCT P.CODPROD) TOTAL FROM PCPEDI P, PCDESCONTO D WHERE P.CODPROMOCAOMED = D.CODPROMOCAOMED AND P.CODDESCONTO = D.CODDESCONTO AND P.NUMPED = :NUMPED AND P.CODPROMOCAOMED = :CODPROMOCAOMED AND D.OBRIGATORIOPARCIALMED = ''S'' GROUP BY P.NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_103 := 'SELECT CASE WHEN COUNT(DISTINCT CODPROD) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, COUNT(DISTINCT CODPROD) VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED';
  V_SQL_FORMULA_104 := 'SELECT CASE WHEN COUNT(1) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, COUNT(1) VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_105 := 'SELECT CASE WHEN (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) = 1 THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, NULL PARAMETRO, (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) VALOR_OBTIDO FROM DUAL';
  V_SQL_FORMULA_106 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_107 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED';
  V_SQL_FORMULA_108 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE NUMPED = :NUMPED';
  V_SQL_FORMULA_109 := 'SELECT CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN ''FALSE'' ELSE ''TRUE'' END PODE_SEGUIR, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.PARAMETRO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.PARAMETRO END) END) PARAMETRO, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.VALOR_OBTIDO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.VALOR_OBTIDO END) END) VALOR_OBTIDO FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= B.QTMINMIXFORNECEDORMED THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, B.CODFORNEC, B.QTMINMIXFORNECEDORMED PARAMETRO, COUNT(DISTINCT(I.CODPROD)) VALOR_OBTIDO FROM PCPEDI I, PCPRODUT P, (SELECT CODFORNEC, SUM(QTMINMIXFORNECEDORMED) QTMINMIXFORNECEDORMED FROM (SELECT DISTINCT P.CODPROD, P.CODFORNEC, NVL(D.QTMINMIXFORNECEDORMED, 0) QTMINMIXFORNECEDORMED FROM PCPEDI I, PCDESCONTO D, PCPRODUT P WHERE I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.CODDESCONTO = D.CODDESCONTO AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED) GROUP BY CODFORNEC) B WHERE P.CODFORNEC = B.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND B.QTMINMIXFORNECEDORMED > 0 GROUP BY B.CODFORNEC, B.QTMINMIXFORNECEDORMED) A';
  V_SQL_FORMULA_110 := 'SELECT CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN ''FALSE'' ELSE ''TRUE'' END PODE_SEGUIR, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.PARAMETRO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.PARAMETRO END) END) PARAMETRO, (CASE WHEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN 1 ELSE 0 END) > 0 THEN SUM(CASE WHEN A.PODE_SEGUIR = ''FALSE'' THEN A.VALOR_OBTIDO END) ELSE SUM(CASE WHEN A.PODE_SEGUIR = ''TRUE'' THEN A.VALOR_OBTIDO END) END) VALOR_OBTIDO FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= B.QTMINMIXFORNECEDORMED THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, B.CODFORNEC, B.QTMINMIXFORNECEDORMED PARAMETRO, COUNT(DISTINCT(I.CODPROD)) VALOR_OBTIDO FROM PCPEDI I, PCPRODUT P, (SELECT P.CODFORNEC, MAX(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCPEDI I, PCDESCONTO D, PCPRODUT P WHERE I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.CODDESCONTO = D.CODDESCONTO AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) B WHERE P.CODFORNEC = B.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND B.QTMINMIXFORNECEDORMED > 0 GROUP BY B.CODFORNEC, B.QTMINMIXFORNECEDORMED) A';
  V_SQL_FORMULA_111 := 'SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODDESCONTO = :CODDESCONTO GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL';
  V_SQL_FORMULA_112 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODDESCONTO = :CODDESCONTO';
  V_SQL_FORMULA_113 := 'SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''TRUE'' ELSE ''FALSE'' END PODE_SEGUIR, :PARAM PARAMETRO, SUM(I.QT * I.PVENDA) VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODDESCONTO = :CODDESCONTO';

  V_SQL_FORMULA_DETALHE_101 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar itens que não estejam vinculados à promoção ou reduzir a quantidade de itens vinculados à promoção.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, (IP.TOTAL / SUM(I.QT * I.PVENDA) * 100) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL) A';
  V_SQL_FORMULA_DETALHE_102 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar mais itens vinculados à promoção no pedido.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN (IP.TOTAL / COUNT(DISTINCT I.CODPROD) * 100) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, (IP.TOTAL / COUNT(DISTINCT I.CODPROD) * 100) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI I, (SELECT P.NUMPED, COUNT(DISTINCT P.CODPROD) TOTAL FROM PCPEDI P, PCDESCONTO D WHERE P.CODPROMOCAOMED = D.CODPROMOCAOMED AND P.CODDESCONTO = D.CODDESCONTO AND P.NUMPED = :NUMPED AND P.CODPROMOCAOMED = :CODPROMOCAOMED AND D.OBRIGATORIOPARCIALMED = ''S'' GROUP BY P.NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY IP.TOTAL) A';
  V_SQL_FORMULA_DETALHE_103 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN CASE WHEN (A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item distinto ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) || '' itens distintos ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(DISTINCT CODPROD) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, COUNT(DISTINCT CODPROD) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED) A';
  V_SQL_FORMULA_DETALHE_104 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN CASE WHEN (A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item da promoção ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO) || '' itens da promoção ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(1) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, COUNT(1) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI WHERE NUMPED = :NUMPED AND CODPROMOCAOMED = :CODPROMOCAOMED) A';
  V_SQL_FORMULA_DETALHE_105 := 'SELECT B.REQUISITO_STATUS, B.REQUISITO_VALOR_ALVO, B.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN B.REQUISITO_STATUS = ''F'' THEN ''Remover as demais promoções vinculadas ao pedido, mantendo apenas esta.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) = 1 THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, 1 AS REQUISITO_VALOR_ALVO, (SELECT COUNT(1) FROM (SELECT CODPROMOCAOMED FROM PCPEDI I WHERE NUMPED = :NUMPED GROUP BY CODPROMOCAOMED) A) AS REQUISITO_VALOR_OBTIDO FROM DUAL) B';
  V_SQL_FORMULA_DETALHE_106 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Reduzir o valor do pedido em '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_OBTIDO - A.REQUISITO_VALOR_ALVO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || ''.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED) A';
  V_SQL_FORMULA_DETALHE_107 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar o valor de '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || '' ao pedido para que ele possa ser gerado usando esta promoção.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED) A';
  V_SQL_FORMULA_DETALHE_108 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar o valor faltante de '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || '' para gerar o pedido.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE NUMPED = :NUMPED) A';
  V_SQL_FORMULA_DETALHE_109 := 'SELECT NULL AS REQUISITO_STATUS, NULL AS REQUISITO_VALOR_ALVO, NULL AS REQUISITO_VALOR_OBTIDO, B.CODFORNEC AS NIVEL_CODIGO, B.FORNECEDOR AS NIVEL_DESCRICAO, B.STATUS AS NIVEL_STATUS, B.VALOR_ALVO AS NIVEL_VALOR_ALVO, B.VALOR_OBTIDO AS NIVEL_VALOR_OBTIDO, CASE WHEN B.STATUS = ''F'' THEN CASE WHEN (B.VALOR_ALVO - B.VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item do fornecedor ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(B.VALOR_ALVO - B.VALOR_OBTIDO) || '' itens do fornecedor ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= A.QTMINMIXFORNECEDORMED THEN ''T'' ELSE ''F'' END AS STATUS, A.QTMINMIXFORNECEDORMED AS VALOR_ALVO, COUNT(DISTINCT(I.CODPROD)) AS VALOR_OBTIDO, F.CODFORNEC, (''Fornecedor '' || TO_CHAR(F.CODFORNEC) || '' - '' || F.FORNECEDOR) AS FORNECEDOR FROM PCPEDI I, PCPRODUT P, PCFORNEC F, (SELECT CODFORNEC, SUM(QTMINMIXFORNECEDORMED) QTMINMIXFORNECEDORMED FROM (SELECT DISTINCT P.CODPROD, P.CODFORNEC, NVL(D.QTMINMIXFORNECEDORMED, 0) QTMINMIXFORNECEDORMED FROM PCPEDI I, PCDESCONTO D, PCPRODUT P WHERE I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.CODDESCONTO = D.CODDESCONTO AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED) GROUP BY CODFORNEC) A WHERE P.CODFORNEC = A.CODFORNEC AND P.CODFORNEC = F.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND A.QTMINMIXFORNECEDORMED > 0 GROUP BY A.QTMINMIXFORNECEDORMED, F.CODFORNEC, F.FORNECEDOR) B';
  V_SQL_FORMULA_DETALHE_110 := 'SELECT NULL AS REQUISITO_STATUS, NULL AS REQUISITO_VALOR_ALVO, NULL AS REQUISITO_VALOR_OBTIDO, B.CODFORNEC AS NIVEL_CODIGO, B.FORNECEDOR AS NIVEL_DESCRICAO, B.STATUS AS NIVEL_STATUS, B.VALOR_ALVO AS NIVEL_VALOR_ALVO, B.VALOR_OBTIDO AS NIVEL_VALOR_OBTIDO, CASE WHEN B.STATUS = ''F'' THEN CASE WHEN (B.VALOR_ALVO - B.VALOR_OBTIDO) = 1 THEN ''Adicionar 1 item do fornecedor ao pedido.'' ELSE ''Adicionar '' || TO_CHAR(B.VALOR_ALVO - B.VALOR_OBTIDO) || '' itens do fornecedor ao pedido.'' END ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN COUNT(DISTINCT(I.CODPROD)) >= A.QTMINMIXFORNECEDORMED THEN ''T'' ELSE ''F'' END AS STATUS, A.QTMINMIXFORNECEDORMED AS VALOR_ALVO, COUNT(DISTINCT(I.CODPROD)) AS VALOR_OBTIDO, F.CODFORNEC, (''Fornecedor '' || TO_CHAR(F.CODFORNEC) || '' - '' || F.FORNECEDOR) AS FORNECEDOR FROM PCPEDI I, PCPRODUT P, PCFORNEC F, (SELECT P.CODFORNEC, MAX(NVL(D.QTMINMIXFORNECEDORMED, 0)) QTMINMIXFORNECEDORMED FROM PCPEDI I, PCDESCONTO D, PCPRODUT P WHERE I.CODPROMOCAOMED = D.CODPROMOCAOMED AND I.CODDESCONTO = D.CODDESCONTO AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND I.CODPROMOCAOMED = :CODPROMOCAOMED GROUP BY P.CODFORNEC) A WHERE P.CODFORNEC = A.CODFORNEC AND P.CODFORNEC = F.CODFORNEC AND I.CODPROD = P.CODPROD AND I.NUMPED = :NUMPED AND A.QTMINMIXFORNECEDORMED > 0 GROUP BY A.QTMINMIXFORNECEDORMED, F.CODFORNEC, F.FORNECEDOR) B';
  V_SQL_FORMULA_DETALHE_111 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar itens que não estejam vinculados à promoção ou reduzir a quantidade de itens vinculados à promoção.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN IP.TOTAL / SUM(I.QT * I.PVENDA) * 100 <= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, (IP.TOTAL / SUM(I.QT * I.PVENDA) * 100) AS REQUISITO_VALOR_OBTIDO FROM PCPEDI I, (SELECT NUMPED, SUM(QT * PVENDA) TOTAL FROM PCPEDI WHERE NUMPED = :NUMPED AND CODDESCONTO = :CODDESCONTO GROUP BY NUMPED) IP WHERE I.NUMPED = IP.NUMPED AND I.NUMPED = :NUMPED GROUP BY IP.TOTAL) A';
  V_SQL_FORMULA_DETALHE_112 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Reduzir o valor do pedido em '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_OBTIDO - A.REQUISITO_VALOR_ALVO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || ''.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) <= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODDESCONTO = :CODDESCONTO) A';
  V_SQL_FORMULA_DETALHE_113 := 'SELECT A.REQUISITO_STATUS, A.REQUISITO_VALOR_ALVO, A.REQUISITO_VALOR_OBTIDO, NULL AS NIVEL_CODIGO, NULL AS NIVEL_DESCRICAO, NULL AS NIVEL_STATUS, NULL AS NIVEL_VALOR_ALVO, NULL AS NIVEL_VALOR_OBTIDO, CASE WHEN A.REQUISITO_STATUS = ''F'' THEN ''Adicionar o valor de '' || TRIM(TO_CHAR(A.REQUISITO_VALOR_ALVO - A.REQUISITO_VALOR_OBTIDO, ''999G999D99'', ''NLS_NUMERIC_CHARACTERS = '''',.'''''')) || '' ao pedido para que ele possa ser gerado usando esta promoção.'' ELSE NULL END AS TEXTO_AJUDA FROM (SELECT CASE WHEN SUM(I.QT * I.PVENDA) >= :PARAM THEN ''T'' ELSE ''F'' END AS REQUISITO_STATUS, :PARAM AS REQUISITO_VALOR_ALVO, SUM(I.QT * I.PVENDA) REQUISITO_VALOR_OBTIDO FROM PCPEDI I WHERE I.NUMPED = :NUMPED AND I.CODDESCONTO = :CODDESCONTO) A';

  DELETE PCFILTROAVANCADOCONFIG WHERE CODCONFIG IN (69, 88, 89, 90, 91, 92, 93, 94, 95, 99);

  MERGE INTO PCFILTROAVANCADOCONFIG tgt
  USING (
    SELECT 1 AS CODCONFIG
         , 'Produto' AS GRUPO
         , 'PCPRODUT' AS TABELA
         , 'CODPROD'AS CAMPO
         , 'NUMBER' AS TIPOCAMPO
         , 'CODPROD' AS NOMEPARAMETRO
         , NULL AS CHAVEMULTIPLA
         , 'Produto' AS NOMELIVRE
         , 'N' AS VISIVELFILTRO
         , 'S' AS VISIVELCONDICAO
         , 'S' AS VISIVELREGRAEXCECAO
         , 'PCPRODUT' AS TABELAPESQUISA
         , 'CODPROD' AS CAMPOPESQUISA
         , 'DESCRICAO' AS DESCRICAOPESQUISA
         , NULL AS CRITERIOPESQUISA
         , NULL AS ROTULOPESQUISA
         , '1' AS CODIGONIVEL
         , 'I' AS TIPOVALIDACAO
         , NULL AS FORMULASQL
         , 'NUMBER' AS TIPOPARAMETRO
         , NULL AS DETALHEFORMULASQL
      FROM DUAL
     UNION ALL
        -- CODCONFIG, GRUPO,            TABELA,                         CAMPO,                                       TIPOCAMPO,   NOMEPARAMETRO,     CHAVEMULTIPLA,                 NOMELIVRE,                                                                               VISIVELFILTRO,   VISIVELCONDICAO,   VISIVELREGRAEXCECAO,   TABELAPESQUISA,      CAMPOPESQUISA,     DESCRICAOPESQUISA,   CRITERIOPESQUISA,   ROTULOPESQUISA,     CODIGONIVEL,   TIPOVALIDACAO,   FORMULASQL,        TIPOPARAMETRO,          DETALHEFORMULASQL
    SELECT 2,         'Produto',        'PCPRODUT',                     'CODFORNEC',                                 'NUMBER',    'CODPROD',         NULL,                          'Fornecedor',                                                                            'N',             'S',               'S',                   'PCFORNEC',          'CODFORNEC',       'FORNECEDOR',        NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 3,         'Produto',        'PCPRODUT',                     'CODEPTO',                                   'NUMBER',    'CODPROD',         NULL,                          'Departamento',                                                                          'N',             'S',               'S',                   'PCDEPTO',           'CODEPTO',         'DESCRICAO',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 4,         'Produto',        'PCPRODUT',                     'CODSEC',                                    'NUMBER',    'CODPROD',         NULL,                          'Seção',                                                                                 'N',             'S',               'S',                   'PCSECAO',           'CODSEC',          'DESCRICAO',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 5,         'Produto',        'PCPRODUT',                     'CODCATEGORIA',                              'NUMBER',    'CODPROD',         NULL,                          'Categoria',                                                                             'N',             'N',               'N',                   'PCCATEGORIA',       'CODCATEGORIA',    'CATEGORIA',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 6,         'Produto',        'PCPRODUT',                     'CODLINHAPROD',                              'NUMBER',    'CODPROD',         NULL,                          'Linha de Produto',                                                                      'N',             'N',               'N',                   'PCLINHAPROD',       'CODLINHA',        'DESCRICAO',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 7,         'Produto',        'PCPRODUT',                     'TIPOMERC',                                  'VARCHAR2',  'CODPROD',         NULL,                          'Tipo de Mercadoria',                                                                    'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'TIPOMERCADORIA',   '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 8,         'Produto',        'PCPRODUT',                     'NBM',                                       'VARCHAR2',  'CODPROD',         NULL,                          'NCM',                                                                                   'N',             'N',               'N',                   'PCNCM',             'CODNCM',          'DESCRICAO',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 9,         'Produto',        'PCPRODUT',                     'CODPRODPRINC',                              'NUMBER',    'CODPROD',         NULL,                          'Produto Principal',                                                                     'N',             'N',               'N',                   'PCPRODUT',          'CODPROD',         'DESCRICAO',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 10,        'Produto',        'PCPRODUT',                     'CLASSEVENDA',                               'VARCHAR2',  'CODPROD',         NULL,                          'Classe de Venda (Produto)',                                                             'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 11,        'Produto',        'PCPRODUT',                     'TIPOESTOQUE',                               'VARCHAR2',  'CODPROD',         NULL,                          'Tipo de Estoque',                                                                       'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'TIPOESTOQUE',      '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 12,        'Produto',        'PCPRODUT',                     'GRUPOFATURAMENTO',                          'VARCHAR2',  'CODPROD',         NULL,                          'Grupo de Faturamento',                                                                  'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'GRUPOFATURAMENTO', '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 13,        'Produto',        'PCPRODUT',                     'TIPOMEDICAMENTO',                           'VARCHAR2',  'CODPROD',         NULL,                          'Tipo de Medicamento',                                                                   'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'TIPOMEDICAMENTO',  '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 14,        'Produto',        'PCPRODUT',                     'CODMARCA',                                  'NUMBER',    'CODPROD',         NULL,                          'Marca',                                                                                 'N',             'S',               'S',                   'PCMARCA',           'CODMARCA',        'MARCA',             NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 15,        'Produto',        'PCPRODUT',                     'CODSUBMARCA',                               'NUMBER',    'CODPROD',         NULL,                          'Sub-Marca',                                                                             'N',             'N',               'N',                   'PCSUBMARCA',        'CODSUBMARCA',     'DESCSUBMARCA',      NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 16,        'Produto',        'PCPRODUT',                     'OBS2',                                      'VARCHAR2',  'CODPROD',         NULL,                          'Fora de Linha',                                                                         'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'FORALINHA',        '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 17,        'Produto',        'PCPRODUT',                     'CODSUBCATEGORIA',                           'NUMBER',    'CODPROD',         NULL,                          'Sub-Categoria',                                                                         'N',             'N',               'N',                   'PCSUBCATEGORIA',    'CODSUBCATEGORIA', 'SUBCATEGORIA',      NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 18,        'Produto',        'PCPRODUT',                     'DTCADASTRO',                                'DATE',      'CODPROD',         NULL,                          'Data de Cadastro (Produto)',                                                            'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 19,        'Produto',        'PCPRODUT',                     'CLASSE',                                    'VARCHAR2',  'CODPROD',         NULL,                          'Classe do Produto',                                                                     'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 20,        'Produto',        'PCPRODUT',                     'VOLUME',                                    'NUMBER',    'CODPROD',         NULL,                          'Volume do Produto',                                                                     'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 21,        'Produto',        'PCPRODUT',                     'PESOBRUTO',                                 'NUMBER',    'CODPROD',         NULL,                          'Peso Bruto',                                                                            'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 22,        'Produto',        'PCPRODUT',                     'PESOLIQ',                                   'NUMBER',    'CODPROD',         NULL,                          'Peso Líquido',                                                                          'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 23,        'Produto',        'PCPRODUT',                     'PSICOTROPICO',                              'VARCHAR2',  'CODPROD',         NULL,                          'Psicotrópico?',                                                                         'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 24,        'Produto',        'PCPRODUT',                     'RETINOICO',                                 'VARCHAR2',  'CODPROD',         NULL,                          'Retinóico',                                                                             'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'RETINOICO',        '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 25,        'Produto',        'PCPRODUT',                     'FARMACIAPOPULAR',                           'VARCHAR2',  'CODPROD',         NULL,                          'Produto Farmácia Popular?',                                                             'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'FARMACIAPOPULAR',  '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 26,        'Produto',        'PCPRODUT',                     'CODAUXILIAR',                               'NUMBER',    'CODPROD',         NULL,                          'Código de Barras de Venda',                                                             'N',             'N',               'N',                   'PCEMBALAGEM',       'CODAUXILIAR',     'EMBALAGEM',         NULL,               NULL,               '1',           'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 27,        'Produto',        'PCPRODFILIAL',                 'FABRICANTE',                                'VARCHAR2',  NULL,              'CODPROD;CODFILIAL',           'Fabricante',                                                                            'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '96',          'I',             NULL,              'NUMBER;VARCHAR2',      NULL                      FROM DUAL UNION ALL
    SELECT 28,        'Produto',        'PCPRODFILIAL',                 'SUBCLASSE',                                 'VARCHAR2',  NULL,              'CODPROD;CODFILIAL',           'Sub-Classe do Produto',                                                                 'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '96',          'I',             NULL,              'NUMBER;VARCHAR2',      NULL                      FROM DUAL UNION ALL
    SELECT 29,        'Produto',        'VW_GRUPOSCAMPANHA_PRODUTO',    'CODGRUPO',                                  'NUMBER',    NULL,              'CODPROD;CODFILIAL',           'Grupo de Produto',                                                                      'N',             'N',               'N',                   'PCGRUPOSCAMPANHAC', 'CODGRUPO',        'DESCRICAO',         'TIPO = ''GP''',    NULL,               '96',          'I',             NULL,              'NUMBER;VARCHAR2',      NULL                      FROM DUAL UNION ALL
    SELECT 30,        'Cliente',        'PCCLIENT',                     'CODCLI',                                    'NUMBER',    'CODCLI',          NULL,                          'Cliente',                                                                               'N',             'S',               'S',                   'PCCLIENT',          'CODCLI',          'CLIENTE',           NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 31,        'Cliente',        'PCCLIENT',                     'CODBAIRROENT',                              'NUMBER',    'CODCLI',          NULL,                          'Bairro',                                                                                'N',             'N',               'N',                   'PCBAIRRO',          'CODBAIRRO',       'DESCRICAO',         NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 32,        'Cliente',        'PCCLIENT',                     'CLASSEVENDA',                               'VARCHAR2',  'CODCLI',          NULL,                          'Classe de Venda (Cliente)',                                                             'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'CLASSEVENDA',      '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 33,        'Cliente',        'PCCLIENT',                     'CODATV1',                                   'NUMBER',    'CODCLI',          NULL,                          'Atividade',                                                                             'N',             'N',               'N',                   'PCATIVI',           'CODATIV',         'RAMO',              NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 34,        'Cliente',        'PCCLIENT',                     'CODCIDADE',                                 'NUMBER',    'CODCLI',          NULL,                          'Cidade',                                                                                'N',             'N',               'N',                   'PCCIDADE',          'CODCIDADE',       'NOMECIDADE',        NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 35,        'Cliente',        'PCCLIENT',                     'CODCLIPRINC',                               'NUMBER',    'CODCLI',          NULL,                          'Cliente Principal',                                                                     'N',             'N',               'N',                   'PCCLIENT',          'CODCLI',          'CLIENTE',           NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 36,        'Cliente',        'PCCLIENT',                     'CODCNAE',                                   'VARCHAR2',  'CODCLI',          NULL,                          'CNAE',                                                                                  'N',             'N',               'N',                   'PCCNAE',            'CODCNAE',         'DESCCNAE',          NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 37,        'Cliente',        'PCCLIENT',                     'CODCONDCOMERCIAL',                          'VARCHAR2',  'CODCLI',          NULL,                          'Condição Comercial (Indústria)',                                                        'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 38,        'Cliente',        'PCCLIENT',                     'CODPRACA',                                  'NUMBER',    'CODCLI',          NULL,                          'Praça',                                                                                 'N',             'S',               'S',                   'PCPRACA',           'CODPRACA',        'PRACA',             NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 39,        'Cliente',        'PCCLIENT',                     'CODREDE',                                   'NUMBER',    'CODCLI',          NULL,                          'Rede de Cliente',                                                                       'N',             'N',               'N',                   'PCREDECLIENTE',     'CODREDE',         'DESCRICAO',         NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 40,        'Cliente',        'PCCLIENT',                     'CONSUMIDORFINAL',                           'VARCHAR2',  'CODCLI',          NULL,                          'Consumidor Final?',                                                                     'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 41,        'Cliente',        'PCCLIENT',                     'CONTRIBUINTE',                              'VARCHAR2',  'CODCLI',          NULL,                          'Contribuinte?',                                                                         'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 42,        'Cliente',        'PCCLIENT',                     'TIPOFJ',                                    'VARCHAR2',  'CODCLI',          NULL,                          'Tipo de Pessoa',                                                                        'N',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               'TIPOPESSOA',       '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 43,        'Cliente',        'PCCLIENT',                     'DTCADASTRO',                                'DATE',      'CODCLI',          NULL,                          'Data de Cadastro (Cliente)',                                                            'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 44,        'Cliente',        'PCCLIENT',                     'DTVALIDADECONV',                            'DATE',      'CODCLI',          NULL,                          'Dt. Val. do Convênio',                                                                  'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 45,        'Cliente',        'PCCLIENT',                     'DTVALIDADEIBAMA',                           'DATE',      'CODCLI',          NULL,                          'Dt. Val. do Registro no IBAMA',                                                         'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 46,        'Cliente',        'PCCLIENT',                     'DTVENCALVARA',                              'DATE',      'CODCLI',          NULL,                          'Dt. Venc. Alvará do Psicotrópicos',                                                     'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 47,        'Cliente',        'PCCLIENT',                     'DTVENCALVARAANVISA',                        'DATE',      'CODCLI',          NULL,                          'Dt. Venc. Alvará da ANVISA',                                                            'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 48,        'Cliente',        'PCCLIENT',                     'DTVENCALVARAFUNC',                          'DATE',      'CODCLI',          NULL,                          'Dt. Venc. Alvará de Funcionamento',                                                     'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 49,        'Cliente',        'PCCLIENT',                     'DTVENCALVARARETINOICO',                     'DATE',      'CODCLI',          NULL,                          'Dt Venc. Alvará do Retinóico',                                                          'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 50,        'Cliente',        'PCCLIENT',                     'DTVENCALVARASUS',                           'DATE',      'CODCLI',          NULL,                          'Dt. Venc. Alvará do SUS',                                                               'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 51,        'Cliente',        'PCCLIENT',                     'DTVENCCRF',                                 'DATE',      'CODCLI',          NULL,                          'Dt. Venc. Alvará do CRF',                                                               'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 52,        'Cliente',        'PCCLIENT',                     'DTVENCSUFRAMA',                             'DATE',      'CODCLI',          NULL,                          'Dt. Venc. Suframa',                                                                     'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 53,        'Cliente',        'PCCLIENT',                     'ESTENT',                                    'VARCHAR2',  'CODCLI',          NULL,                          'UF do Estado',                                                                          'N',             'N',               'N',                   'PCESTADO',          'UF',              'ESTADO',            NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 54,        'Cliente',        'PCCLIENT',                     'ORGAOPUB',                                  'VARCHAR2',  'CODCLI',          NULL,                          'Orgão Público Estadual?',                                                               'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 55,        'Cliente',        'PCCLIENT',                     'ORGAOPUBFEDERAL',                           'VARCHAR2',  'CODCLI',          NULL,                          'Orgão Público Federal?',                                                                'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 56,        'Cliente',        'PCCLIENT',                     'ORGAOPUBMUNICIPAL',                         'VARCHAR2',  'CODCLI',          NULL,                          'Orgão Público Municipal?',                                                              'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 57,        'Cliente',        'PCCLIENT',                     'PARTICIPAFARMACIAPOPULAR',                  'VARCHAR2',  'CODCLI',          NULL,                          'Participa da Farmácia Popular?',                                                        'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 58,        'Cliente',        'PCCLIENT',                     'TIPOEMPRESA',                               'VARCHAR2',  'CODCLI',          NULL,                          'Tipo de Empresa',                                                                       'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'TIPOEMPRESA',      '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 59,        'Cliente',        'PCCLIENT',                     'TIPOCLIMED',                                'VARCHAR2',  'CODCLI',          NULL,                          'Tipo do Ramo de Medicamentos',                                                          'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'TIPOCLIMED',       '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 60,        'Cliente',        'PCCLIENT',                     'USADEBCREDRCA',                             'VARCHAR2',  'CODCLI',          NULL,                          'Usa Débito e Crédito de RCA?',                                                          'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 61,        'Cliente',        'PCCLIENT',                     'LIMCRED',                                   'NUMBER',    'CODCLI',          NULL,                          'Limite de Crédito',                                                                     'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 62,        'Cliente',        'PCCLIENT',                     'CODPLPAG',                                  'NUMBER',    'CODCLI',          NULL,                          'Plano de Pagamento (Nível de Venda - Cliente)',                                         'N',             'N',               'N',                   'PCPLPAG',           'CODPLPAG',        'DESCRICAO',         NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 63,        'Cliente',        'PCCLIENT',                     'CLIENTEMONITORADO',                         'VARCHAR2',  'CODCLI',          NULL,                          'Cliente Monitorado?',                                                                   'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 64,        'Cliente',        'PCCLIENT',                     'USACRECLIFAT',                              'VARCHAR2',  'CODCLI',          NULL,                          'Cliente Utiliza Créd. Faturamento?',                                                    'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 65,        'Cliente',        'PCCLIENT',                     'CODUSUR1',                                  'NUMBER',    'CODCLI',          NULL,                          'RCA 1 (Cliente)',                                                                       'N',             'N',               'N',                   'PCUSUARI',          'CODUSUR',         'NOME',              NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 66,        'Cliente',        'PCCLIENT',                     'CODUSUR2',                                  'NUMBER',    'CODCLI',          NULL,                          'RCA 2 (Cliente)',                                                                       'N',             'N',               'N',                   'PCUSUARI',          'CODUSUR',         'NOME',              NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 67,        'Cliente',        'PCCLIENT',                     'CODUSUR3',                                  'NUMBER',    'CODCLI',          NULL,                          'RCA 3 (Cliente)',                                                                       'N',             'N',               'N',                   'PCUSUARI',          'CODUSUR',         'NOME',              NULL,               NULL,               '30',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 68,        'Cliente',        'VW_GRUPOSCAMPANHA_CLIENTE',    'CODGRUPO',                                  'NUMBER',    NULL,              'CODCLI;CODFILIAL',            'Grupo de Cliente',                                                                      'N',             'N',               'N',                   'PCGRUPOSCAMPANHAC', 'CODGRUPO',        'DESCRICAO',         'TIPO = ''CL''',    NULL,               '97',          'I',             NULL,              'NUMBER;VARCHAR2',      NULL                      FROM DUAL UNION ALL
    SELECT 70,        'Pedido',         'PCPEDC',                       'ORIGEMPED',                                 'VARCHAR2',  'ORIGEMPED',       NULL,                          'Origem do Pedido',                                                                      'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'ORIGEMPEDIDO',     NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 71,        'Pedido',         'PCPEDC',                       'FRETEDESPACHO',                             'VARCHAR2',  'FRETEDESPACHO',   NULL,                          'Tipo de Frete',                                                                         'N',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               'TIPOFRETE',        NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 72,        'Pedido',         'PCPEDC',                       'CONDVENDA',                                 'VARCHAR2',  'CONDVENDA',       NULL,                          'Condição de Venda',                                                                     'N',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               'CONDVENDA',        NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 73,        'Pedido',         'PCPEDC',                       'CODPLPAG',                                  'NUMBER',    'CODPLPAG',        NULL,                          'Plano de Pagamento (Pedido)',                                                           'N',             'S',               'S',                   'PCPLPAG',           'CODPLPAG',        'DESCRICAO',         NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 74,        'Pedido',         'PCPEDC',                       'CODCOB',                                    'VARCHAR2',  'CODCOB',          NULL,                          'Cobrança',                                                                              'N',             'S',               'S',                   'PCCOB',             'CODCOB',          'COBRANCA',          NULL,               NULL,               NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 75,        'Pedido',         'PCPEDC',                       'CODFILIALNF',                               'VARCHAR2',  'CODFILIALNF',     NULL,                          'Filial (Pedido)',                                                                       'N',             'N',               'N',                   'PCFILIAL',          'CODIGO',          'RAZAOSOCIAL',       NULL,               NULL,               NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 76,        'Pedido',         'PCPEDC',                       'CODUSUR',                                   'NUMBER',    'CODUSUR',         NULL,                          'RCA (Pedido)',                                                                          'N',             'S',               'S',                   'PCUSUARI',          'CODUSUR',         'NOME',              NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 77,        'Pedido',         'VW_GRUPOSCAMPANHA_RCA',        'CODGRUPO',                                  'NUMBER',    NULL,              'CODUSUR;CODFILIAL',           'Grupo de RCA',                                                                          'N',             'N',               'N',                   'PCGRUPOSCAMPANHAC', 'CODGRUPO',        'DESCRICAO',         'TIPO = ''GR''',    NULL,               '98',          'I',             NULL,              'NUMBER;VARCHAR2',      NULL                      FROM DUAL UNION ALL
    SELECT 78,        'Item do Pedido', 'PCPEDI',                       'PVENDA',                                    'NUMBER',    'PVENDA',          NULL,                          'Preço de Venda',                                                                        'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 79,        'Item do Pedido', 'PCPEDI',                       'QT',                                        'NUMBER',    'QT',              NULL,                          'Quantidade do item',                                                                    'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 80,        'Item do Pedido', 'PCPEDI',                       'SUBTOTAL',                                  'NUMBER',    'SUBTOTAL',        NULL,                          'Subtotal do Item',                                                                      'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 81,        'Item do Pedido', 'PCPEDI',                       'CODFILIALRETIRA',                           'VARCHAR2',  'CODFILIALRETIRA', NULL,                          'Filial Retira',                                                                         'N',             'S',               'S',                   'PCFILIAL',          'CODIGO',          'RAZAOSOCIAL',       NULL,               NULL,               NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 82,        'Item do Pedido', 'PCPEDI',                       'CODST',                                     'NUMBER',    'CODST',           NULL,                          'Figura Tributária',                                                                     'I',             'N',               'N',                   'PCTRIBUT',          'CODST',           'MENSAGEM',          NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 83,        'Item do Pedido', 'PCPEDI',                       'CODLINHAPRAZO',                             'NUMBER',    'CODLINHAPRAZO',   NULL,                          'Linha de Prazo',                                                                        'I',             'N',               'N',                   'PCLINHAPRAZO',      'CODLINHAPRAZO',   'DESCRICAO',         NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 84,        'Pedido',         'PCPEDC',                       'CODFILIAL',                                 'VARCHAR2',  'CODFILIAL',       NULL,                          'Filial',                                                                                'N',             'S',               'S',                   'PCFILIAL',          'CODIGO',          'RAZAOSOCIAL',       NULL,               NULL,               NULL,          'I',             NULL,              'VARCHAR2',             NULL                      FROM DUAL UNION ALL
    SELECT 85,        'Pedido',         'PCPEDC',                       'NUMREGIAO',                                 'NUMBER',    'NUMREGIAO',       NULL,                          'Região',                                                                                'N',             'S',               'S',                   'PCREGIAO',          'NUMREGIAO',       'REGIAO',            NULL,               NULL,               NULL,          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 86,        'Pedido',         'PCUSUARI',                     'CODSUPERVISOR',                             'NUMBER',    'CODUSUR',         NULL,                          'Supervisor',                                                                            'N',             'N',               'N',                   'PCSUPERV',          'CODSUPERVISOR',   'NOME',              NULL,               NULL,               '76',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 87,        'Pedido',         'PCSUPERV',                     'CODGERENTE',                                'NUMBER',    'CODUSUR',         NULL,                          'Gerente',                                                                               'N',             'N',               'N',                   'PCGERENTE',         'CODGERENTE',      'NOMEGERENTE',       NULL,               NULL,               '86',          'I',             NULL,              'NUMBER',               NULL                      FROM DUAL UNION ALL
    SELECT 96,        'Nivel',          'NIVEL',                        'CODPROD, CODFILIAL',                        'NIVEL',     NULL,              NULL,                          'NIVEL',                                                                                 'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'I',             NULL,              NULL,                   NULL                      FROM DUAL UNION ALL
    SELECT 97,        'Nivel',          'NIVEL',                        'CODCLI, CODFILIAL',                         'NIVEL',     NULL,              NULL,                          'NIVEL',                                                                                 'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'I',             NULL,              NULL,                   NULL                      FROM DUAL UNION ALL
    SELECT 98,        'Nivel',          'NIVEL',                        'CODUSUR, CODFILIAL',                        'NIVEL',     NULL,              NULL,                          'NIVEL',                                                                                 'I',             'N',               'N',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'I',             NULL,              NULL,                   NULL                      FROM DUAL UNION ALL
    SELECT 100,       'Produto',        'VW_GRUPOSCAMPANHA_FORNECEDOR', 'CODGRUPO',                                  'NUMBER',    NULL,              'CODPROD;CODFILIAL',           'Grupo de Fornecedores',                                                                 'N',             'N',               'N',                   'PCGRUPOSCAMPANHAC', 'CODGRUPO',        'DESCRICAO',         'TIPO = ''GF''',    NULL,               '96',          'I',             NULL,              'NUMBER;VARCHAR2',      NULL                      FROM DUAL UNION ALL
    SELECT 101,       'Calculado',      'CALCULADO',                    'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO',      'NUMBER',    NULL,              'PARAM;NUMPED;CODPROMOCAOMED', 'Percentual máximo permitido sobre o valor dos itens da promoção no pedido',             'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_101, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_101 FROM DUAL UNION ALL
    SELECT 102,       'Calculado',      'CALCULADO',                    'PERCENTUALMINIMOITENSOBRIGATORIOPEDIDO',    'NUMBER',    NULL,              'PARAM;NUMPED;CODPROMOCAOMED', 'Percentual mínimo necessário de itens obrigatórios distintos da promoção no pedido',    'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_102, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_102 FROM DUAL UNION ALL
    SELECT 103,       'Calculado',      'CALCULADO',                    'QUANTIDADEMINIMAITENSDISTINTOSPEDIDO',      'NUMBER',    NULL,              'PARAM;NUMPED',                'Quantidade mínima necessária de itens distintos no pedido',                             'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_103, 'NUMBER;NUMBER',        V_SQL_FORMULA_DETALHE_103 FROM DUAL UNION ALL
    SELECT 104,       'Calculado',      'CALCULADO',                    'QUANTIDADEMINIMAITENSPROMOCAO',             'NUMBER',    NULL,              'PARAM;NUMPED;CODPROMOCAOMED', 'Quantidade mínima necessária de itens distintos da promoção no pedido',                 'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_104, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_104 FROM DUAL UNION ALL
    SELECT 105,       'Calculado',      'CALCULADO',                    'PROMOCAOUNICAPEDIDO',                       'VARCHAR2',  NULL,              'NUMPED',                      'Ativa promoção exclusiva contendo apenas itens desta promoção',                         'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           NULL,          'C',             V_SQL_FORMULA_105, 'NUMBER',               V_SQL_FORMULA_DETALHE_105 FROM DUAL UNION ALL
    SELECT 106,       'Calculado',      'CALCULADO',                    'VALORMAXIMOPERMITIDOPEDIDO',                'NUMBER',    NULL,              'PARAM;NUMPED;CODPROMOCAOMED', 'Valor máximo permitido para os itens da promoção no pedido',                            'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_106, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_106 FROM DUAL UNION ALL
    SELECT 107,       'Calculado',      'CALCULADO',                    'VALORMINIMOEXIGIDOATIVARPROMOCAO',          'NUMBER',    NULL,              'PARAM;NUMPED;CODPROMOCAOMED', 'Valor mínimo necessário para os itens da promoção no pedido',                           'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_107, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_107 FROM DUAL UNION ALL
    SELECT 108,       'Calculado',      'CALCULADO',                    'VALORMINIMOTOTALEXIGIDOPEDIDO',             'NUMBER',    NULL,              'PARAM;NUMPED',                'Valor mínimo necessário para o total do pedido',                                        'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_108, 'NUMBER;NUMBER',        V_SQL_FORMULA_DETALHE_108 FROM DUAL UNION ALL
    SELECT 109,       'Calculado',      'CALCULADO',                    'ATIVAVALIDACAOMIXSOMAITENSMESMOFABRICANTE', 'VARCHAR2',  NULL,              'NUMPED;CODPROMOCAOMED',       'Ativa validação de mix considerando a soma do mix dos itens de um mesmo fabricante',    'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           NULL,          'C',             V_SQL_FORMULA_109, 'NUMBER;NUMBER',        V_SQL_FORMULA_DETALHE_109 FROM DUAL UNION ALL
    SELECT 110,       'Calculado',      'CALCULADO',                    'ATIVAVALIDACAOMIXMAIORFABRICANTE',          'VARCHAR2',  NULL,              'NUMPED;CODPROMOCAOMED',       'Ativa validação de mix considerando o maior mix entre os itens de um mesmo fabricante', 'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               'SIMNAO',           NULL,          'C',             V_SQL_FORMULA_110, 'NUMBER;NUMBER',        V_SQL_FORMULA_DETALHE_110 FROM DUAL UNION ALL
    SELECT 111,       'Calculado',      'CALCULADO',                    'PERCENTUALMAXIMOPERMITIDOVALORPEDIDO2',     'NUMBER',    NULL,              'PARAM;NUMPED;CODDESCONTO',    'Percentual máximo permitido sobre o valor dos itens da promoção no pedido',             'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_111, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_111 FROM DUAL UNION ALL
    SELECT 112,       'Calculado',      'CALCULADO',                    'VALORMAXIMOPERMITIDOPEDIDO2',               'NUMBER',    NULL,              'PARAM;NUMPED;CODDESCONTO',    'Valor máximo permitido para os itens da promoção no pedido',                            'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_112, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_112 FROM DUAL UNION ALL
    SELECT 113,       'Calculado',      'CALCULADO',                    'VALORMINIMOEXIGIDOATIVARPROMOCAO2',         'NUMBER',    NULL,              'PARAM;NUMPED;CODDESCONTO',    'Valor mínimo necessário para os itens da promoção no pedido',                           'I',             'S',               'S',                   NULL,                NULL,              NULL,                NULL,               NULL,               NULL,          'C',             V_SQL_FORMULA_113, 'NUMBER;NUMBER;NUMBER', V_SQL_FORMULA_DETALHE_113 FROM DUAL
  ) src
  ON (
    tgt.CODCONFIG = src.CODCONFIG
  )
  WHEN MATCHED THEN
    UPDATE SET tgt.GRUPO = src.GRUPO,
               tgt.TABELA = src.TABELA,
               tgt.CAMPO = src.CAMPO,
               tgt.TIPOCAMPO = src.TIPOCAMPO,
               tgt.NOMEPARAMETRO = src.NOMEPARAMETRO,
               tgt.CHAVEMULTIPLA = src.CHAVEMULTIPLA,
               tgt.TABELAPESQUISA = src.TABELAPESQUISA,
               tgt.CAMPOPESQUISA = src.CAMPOPESQUISA,
               tgt.DESCRICAOPESQUISA = src.DESCRICAOPESQUISA,
               tgt.CRITERIOPESQUISA = src.CRITERIOPESQUISA,
               tgt.ROTULOPESQUISA = src.ROTULOPESQUISA,
               tgt.CODIGONIVEL = src.CODIGONIVEL,
               tgt.TIPOVALIDACAO = src.TIPOVALIDACAO,
               tgt.FORMULASQL = src.FORMULASQL,
               tgt.TIPOPARAMETRO = src.TIPOPARAMETRO,
               tgt.DETALHEFORMULASQL = src.DETALHEFORMULASQL
    WHEN NOT MATCHED THEN
      INSERT (
        CODCONFIG,
        GRUPO,
        TABELA,
        CAMPO,
        TIPOCAMPO,
        NOMEPARAMETRO,
        CHAVEMULTIPLA,
        NOMELIVRE,
        VISIVELFILTRO,
        VISIVELCONDICAO,
        VISIVELREGRAEXCECAO,
        TABELAPESQUISA,
        CAMPOPESQUISA,
        DESCRICAOPESQUISA,
        CRITERIOPESQUISA,
        ROTULOPESQUISA,
        CODIGONIVEL,
        TIPOVALIDACAO,
        FORMULASQL,
        TIPOPARAMETRO,
        DETALHEFORMULASQL
      )
      VALUES (
        src.CODCONFIG,
        src.GRUPO,
        src.TABELA,
        src.CAMPO,
        src.TIPOCAMPO,
        src.NOMEPARAMETRO,
        src.CHAVEMULTIPLA,
        src.NOMELIVRE,
        src.VISIVELFILTRO,
        src.VISIVELCONDICAO,
        src.VISIVELREGRAEXCECAO,
        src.TABELAPESQUISA,
        src.CAMPOPESQUISA,
        src.DESCRICAOPESQUISA,
        src.CRITERIOPESQUISA,
        src.ROTULOPESQUISA,
        src.CODIGONIVEL,
        src.TIPOVALIDACAO,
        src.FORMULASQL,
        src.TIPOPARAMETRO,
        src.DETALHEFORMULASQL
      );

END;