CREATE OR REPLACE VIEW SQL_NFE_PRODUTO_SAIDA_CIAP AS 
SELECT ALIQUOTA_COFINS
      ,ALIQUOTA_ICMS
      ,ALIQUOTA_IPI
      ,ALIQUOTA_PIS
      ,ALIQUOTA_ST
      ,ALIQUOTA_CREDITO_SN
      ,BASE_ICMS
      ,BASE_IPI
      ,BASE_ST
      ,BASE_II
      ,BASEBCR
      ,CFOP
      ,CLASSIFICFISCAL
      ,CODFILIALRETIRA
      ,COD_OPERACAO
      ,CODIGO_FABRICANTE
      ,CODIGO_SECAO
      ,CODIGO_DEPARTAMENTO
      ,CODIGO_FORNECEDOR
      ,CODPROD
      ,CODIGO_PRODUTO
      ,CODST
      ,DATA_FABRICACAO
      ,DATA_VALIDADE
      ,DESCRICAO_DEPARTAMENTO
      ,DESCRICAO_SECAO
      ,DIGITO_PRODUTO
      ,EAN
      ,EAN_UNIDADE
      ,EMBALAGEM
      ,EMBALAGEMMASTER
      ,EXTIPI
      ,FANTASIA
      ,FATORUNFARM
      ,FORNECEDOR
      ,GENERO
      ,INFO_TECNICA
      ,MARCA
      ,MODALIDADE_BC_ICMS
      ,MODALIDADE_BC_ST
      ,NATUREZAPRODUTO
      ,NCM
      ,NUM_TRANSACAO
      ,NUMERO_ADICAO
      ,NUMERO_LOTE
      ,NUMERO_SEQUENCIA
      ,NUMORIGINAL
      ,NUMERO_PEDIDO
      ,NUMERO_ITEM_PEDIDO
      ,NUMVOLUMESCONFERENCIA
      ,ORIGEM_MERCADORIA
      ,PERACRESCIMOCUSTO
      ,PERCDESC
      ,PERCENTUAL_MARGEM
      ,PERCENTUAL_REDUCAO_BC
      ,PERCENTUAL_REDUCAO_ST
      ,PERCIPIVENDA
      ,PESO_BRUTO
      ,PESOCX
      ,PESOEMBALAGEM
      ,PRECO_MAXIMO
      ,PRINCIPIOATIVO
      ,PRODUTO
      ,PTABELA
      ,PUNITCONT
      ,QT_LOTE
      ,QTCX
      ,QTD_CAIXA
      ,QTD_UNIDADE
      ,QTD_CAIXAS_MASTER
      ,QTD_PECAS_INTERM
      ,QTPECAS
      ,QTUN
      ,QTUNIT
      ,QTUNITCX
      ,QTUNITEMB
      ,QTD_EMBALAGEM
      ,QUANTIDADE AS QUANTIDADE_COMERCIAL
      ,QUANTIDADE_ENTREGA
      ,QUANTIDADE AS QUANTIDADE_TRIBUTAVEL
      ,RETIDO
      ,SIT_PIS_CONFINS
      ,SITUACAO_TRIBUTARIA
      ,SITUACAO_TRIBUTARIA_IPI
      ,STBCR
      ,STCLIENTEGNRE
      ,TIPO_QUANTIDADE
      ,TIPOESTOQUE
      ,TIPOMERC
      ,TIPOTRIBUTMEDIC
      ,TIPOSEPARACAO
      ,TOTPESOLIQUNIT
      ,UNIDADE AS UNIDADE_COMERCIAL
      ,UNIDADE AS UNIDADE_TRIBUTAVEL
      ,UNIDADEMASTER
      ,UNIDADE_EMBALAGEM
      ,VALOR_COFINS
      ,ROUND(VALOR_UNITARIO / QUANTIDADE,10) AS VALOR_COMERCIAL
      ,VALOR_DESCONTO
      ,VALOR_DESCONTO_ADICAO
      ,VALOR_FRETE
      ,CASE WHEN ((SITUACAO_TRIBUTARIA = '51') AND
                  (ALIQUOTAICMSDIF > 0)) THEN
         VALOR_ICMS_DEVIDO
       ELSE
         VALOR_ICMS
       END AS VALOR_ICMS_DEVIDO
      ,CASE WHEN ((SITUACAO_TRIBUTARIA = '51') AND
                  (ALIQUOTAICMSDIF > 0)) THEN
         VALOR_ICMS_DEVIDO
       ELSE
         VALOR_ICMS
       END AS VALOR_ICMS
      ,VALOR_CREDITO_ICMS_SN
      ,VALOR_IPI
      ,VALOR_IPI_UNIDADE
      ,VALOR_LIQUIDO / QUANTIDADE AS VALOR_LIQUIDO
      ,VALOR_PIS
      ,VALOR_UNITARIO AS VALOR_PRODUTOS
      ,VALOR_SEGURO
      ,VALOR_OUTROS
      ,VALOR_ST
      ,VALOR_TOT_EMBALAGEM
      ,VALOR_II
      ,VALOR_DESPESA_ADUANEIRA
      ,VALOR_IOF
      ,ROUND(VALOR_UNITARIO / QUANTIDADE, 10) AS VALOR_TRIBUTAVEL
      ,VL_BASE_CONFINS
      ,VL_BASE_PIS
      ,VLBASEGNRE
      ,VLIPIPORKGVENDA
      ,VOLUME
      --dados sobre veiculos
      ,TPOPERACAO
      ,CHASSIVEICULO
      ,CORVEICULO
      ,DESCCORVEICULO
      ,POTVEICULO
      ,CILINVEICULO
      ,PESOLVEICULO
      ,PESOBVEICULO
      ,SERIALVEICULO
      ,TPCOMBVEICULO
      ,NMOTORVEICULO
      ,CMTVEICULO
      ,DISTEIXOVEICULO
      ,ANOMODVEICULO
      ,ANOFABVEICULO
      ,TPPINTVEICULO
      ,TPVEICVEICULO
      ,ESPVEICVEICULO
      ,CONDVINVEICULO
      ,CONDVEICVEICULO
      ,MARCMODVEICULO
      ,CORDENATRANVEICULO
      ,LOTACAOVEICULO
      ,TPRESTVEICULO
      --fim dados sobre veiculos
      ,PRECO_MAX_CONSUMIDOR
      ,PRECO_FABRICA
      ,DESCONTO_FABRICA
      ,CODPRODCABCESTA
      ,PERCBONIFIC
      ,NUMERO_FCI
      ,CODIGOANP
      ,DESC_ANP
      ,CASE WHEN ((SITUACAO_TRIBUTARIA = '51') AND
                  (ALIQUOTAICMSDIF > 0)) THEN
         VALORICMSDIF
       ELSE
         0
       END VALORICMSDIF
      ,CASE WHEN ((SITUACAO_TRIBUTARIA = '51') AND
                  (ALIQUOTAICMSDIF > 0)) THEN
        VALOR_ICMS
       ELSE
         0
       END VALOR_ICMS_OPERACAO
      ,ALIQUOTAICMSDIF
      ,VALOR_ICMS_DESONERADO
      ,COD_MOTIVO_DESONERACAO
      ,VALOR_IPI_OUTROS
      ,TIPO_PRESENCA_ADQUIRINTE
      ,(BASE_ICMS / QUANTIDADE) AS BASE_ICMS_UNITARIO
      ,ALIQFCPPART
      ,ALIQINTERNADEST
      ,ALIQINTERORIGPART
      ,VLFCPPART
      ,VLBASEPARTDEST
      ,PERCPROVPART
      ,VLICMSDIFALIQPART
      ,VLICMSPARTDEST
      ,VLICMSPARTREM
      ,CODCEST
      ,CODENQIPI AS CODENQUADRAMENTOIPI
      ,COD_BENEFICIO_FISCAL
      ,COD_AGREGACAO
      ,IND_ESCALA_RELEVANTE
      ,CNPJ_FABRICANTE
      ,BASE_FCP_ICMS
      ,PERC_FCP
      ,VALOR_FCP
      ,BASE_CALC_FCP_ST
      ,PERC_FCP_ST
      ,VL_FCP_ST
      ,VLBCFCPSTRET
      ,PERFCPSTRET
      ,VLFCPSTRET
      ,PERFCPSN
      ,VLCREDFCPICMSSN
      ,MOTREDADREM
      ,ADREMICMS
      ,ADREMICMSRETEN
      ,PREDADREM
      ,ADREMICMSDIF
      ,ADREMICMSRET
      ,QBCMONO
      ,VICMSMONO
      ,QBCMONORETEN
      ,VICMSMONORETEN
      ,QBCMONODIF
      ,VICMSMONODIF
      ,QBCMONORET
      ,VICMSMONORET      
      ,COD_PRIORIDADE_IMPRESSAO
      ,NULL DATACONSOLIDACAOPREFAT
      ,'N' PREFATURAMENTO
      ,PERCENTUAL_IPI_DEVOLUCAO
    FROM   (SELECT PCMOVCIAP.NUMTRANSVENDA AS NUM_TRANSACAO
              ,PCMOVCIAP.CODPROD
              ,TO_CHAR(PCMOVCIAP.CODPROD) AS CODIGO_PRODUTO
              ,0 AS CODST
              ,PCMOVCIAP.CODOPER AS COD_OPERACAO
              ,PCMOVCIAP.CODFILIAL
              ,CASE
                 WHEN LENGTH(NVL(PCPRODCIAP.CODAUXILIAR,
                                 '')) IN (8,
                                          12,
                                          13,
                                          14) THEN
                  TO_CHAR(PCPRODCIAP.CODAUXILIAR)
                ELSE CASE
                  WHEN (LENGTH(PCPRODCIAP.CODAUXILIAR) < NVL(PCPRODCIAP.GTINCODAUXILIAR,0)) THEN
                      LPAD(TO_CHAR(PCPRODCIAP.CODAUXILIAR), PCPRODCIAP.GTINCODAUXILIAR,'0')
                ELSE
                  NULL
                END
               END AS EAN
              ,0 AS DIGITO_PRODUTO
              ,PCPRODCIAP.DESCRICAO AS PRODUTO
              ,'X' AS NATUREZAPRODUTO
              ,TRIM( CASE WHEN NVL(PCMOVCIAP.VLACRESCIMOFUNCEP, 0) > 0 THEN
                         ' VBCFCP: ' || TRIM(TO_CHAR(ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLBASEFCPICMS, 0),2),'999999999999999990.99')) ||
                         ' PFCP: '   || TRIM(TO_CHAR(NVL(PCMOVCIAP.PERACRESCIMOFUNCEP, 0),'999999999999999990.99')) ||
                         ' VFCP: '   || TRIM(TO_CHAR(ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLACRESCIMOFUNCEP, 0),2),'999999999999999990.99'))
               END ||
               CASE WHEN NVL(PCMOVCIAP.VLFECP, 0) > 0 THEN
                         ' VBCFCPST: ' || TRIM(TO_CHAR(ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLBASEFCPST, 0),2),'999999999999999990.99')) ||
                         ' PFCPST: '   || TRIM(TO_CHAR(NVL(PCMOVCIAP.ALIQICMSFECP, 0),'999999999999999990.99')) ||
                         ' VFCPST: '   || TRIM(TO_CHAR(ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLFECP, 0),2),'999999999999999990.99'))
               END ||
               CASE WHEN ((NVL(PCMOVCIAP.SITTRIBUT, '55') IN ('60','500')) AND (SQL_NFE_CABECALHO_SAIDA.CONTRIBUINTE = 'S')) THEN
                    CASE WHEN NVL(PCMOVCIAP.VLFCPSTRET, 0) > 0 THEN
                              ' VBCFCPSTRET: ' || TRIM(TO_CHAR(ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLBCFCPSTRET, 0),2),'999999999999999990.99')) ||
                              ' PFCPSTRET: '   || TRIM(TO_CHAR(NVL(PCMOVCIAP.PERFCPSTRET, 0),'999999999999999990.99')) ||
                              ' VFCPSTRET: '   || TRIM(TO_CHAR(ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLFCPSTRET, 0),2),'999999999999999990.99'))  
                    END
               END ||
               CASE WHEN ((NVL(PCMOVCIAP.SITTRIBUT, '55') = '61') AND
                          (NVL(PCMOVCIAP.VICMSMONORET, 0) > 0) AND
                          (SQL_NFE_CABECALHO_SAIDA.CONSUMIDOR_FINAL = 'S') AND
                          (SQL_NFE_CABECALHO_SAIDA.CONTRIBUINTE = 'N')) THEN
                        'ICMS monofásico sobre combustíveis cobrado anteriormente conforme Convênio ICMS 199/2022.'
                ELSE NULL
               END ) AS INFO_TECNICA
              ,PCPRODCIAP.CODNCM AS NCM
              ,PCPRODCIAP.EXTIPI AS EXTIPI
              ,NULL AS GENERO
              ,PCMOVCIAP.CODFISCAL AS CFOP
              ,NVL(PCMOVCIAP.UTRIB, 'UN') AS UNIDADE
              ,PCMOVCIAP.QTCONT AS QUANTIDADE
              ,ROUND(PCMOVCIAP.QTCONT *
                     (NVL(PCMOVCIAP.PUNITCONT, 0) + NVL(PCMOVCIAP.VLDESCONTO, 0) -
                     NVL(PCMOVCIAP.VLIPI, 0) - NVL(PCMOVCIAP.VLST, 0) -
                     DECODE(NVL(PCMOVCIAP.CODOPER, 'SD'),
                             'SD',
                             NVL(PCMOVCIAP.VLOUTRASDESP, 0),
                             0) - 
                     DECODE(NVL(PCMOVCIAP.CODOPER, 'X'),
                             'SD',
                             NVL(PCMOVCIAP.VLIPIDEVFORNEC, 0),
                             0)                             
                             - NVL(PCMOVCIAP.VLFRETE, 0)
                      - NVL(PCMOVCIAP.VLSEGURO, 0)       
                      ),
                     NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CON_NUMCASASDECVENDA'),2)) AS VALOR_UNITARIO
              ,NVL(PUNITCONT,0) * PCMOVCIAP.QTCONT AS VALOR_LIQUIDO
              ,CASE
                  --NÃO TEM UM GTIN PARA O CODAUXILIAREANTRIB, ORIENTARAM A USAR O MESMO DO CODAUXILIAR
                  WHEN (LENGTH(PCPRODCIAP.CODAUXILIAREANTRIB) <= NVL(PCPRODCIAP.GTINCODAUXILIAR,0)) THEN
                      LPAD(TO_CHAR(PCPRODCIAP.CODAUXILIAREANTRIB), PCPRODCIAP.GTINCODAUXILIAR,'0')
               ELSE
                  CASE
                    WHEN (LENGTH(PCPRODCIAP.CODAUXILIAR) <= NVL(PCPRODCIAP.GTINCODAUXILIAR,0)) THEN
                        LPAD(TO_CHAR(PCPRODCIAP.CODAUXILIAR), PCPRODCIAP.GTINCODAUXILIAR,'0')
                  ELSE
                    NULL
                  END
               END AS EAN_UNIDADE
              ,( PCMOVCIAP.QTCONT * PCMOVCIAP.VLFRETE )AS VALOR_FRETE
              ,PCMOVCIAP.VLSEGURO AS VALOR_SEGURO
              ,ROUND(PCMOVCIAP.QTCONT * PCMOVCIAP.VLDESCONTO,2) AS VALOR_DESCONTO
              ,0 AS PESO_BRUTO
              ,0 AS PERCIPIVENDA
              ,0 AS VLIPIPORKGVENDA
              ,PCPRODCIAP.TIPOMERC
              ,1 AS NUMERO_ADICAO
              ,1 AS NUMERO_SEQUENCIA
              ,0 AS VALOR_DESCONTO_ADICAO
              ,NULL AS NUMERO_LOTE
              ,NULL AS DATA_FABRICACAO
              ,NULL AS DATA_VALIDADE
              ,0 AS QT_LOTE
              ,0 AS PRECO_MAXIMO
              ,NVL(PCMOVCIAP.ORIGMERCTRIB ,DECODE(NVL(PCPRODCIAP.IMPORTADO,'N'),'S',2,'D',1,0)) AS ORIGEM_MERCADORIA
              ,PCMOVCIAP.SITTRIBUT AS SITUACAO_TRIBUTARIA
              ,PCMOVCIAP.MODBCICMS AS MODALIDADE_BC_ICMS
              ,ROUND(NVL(PCMOVCIAP.BASEICMS, 0) * PCMOVCIAP.QTCONT, 2) BASE_ICMS
              ,NVL(NVL(PCMOVCIAP.PERCICM, PCMOVCIAP.ALIQICMS1),0) AS ALIQUOTA_ICMS
              ,CASE WHEN (NVL(PCMOVCIAP.VLICMS, 0) > 0) THEN
                    ROUND(PCMOVCIAP.QTCONT * PCMOVCIAP.VLICMS,2)
                ELSE
                    ROUND(NVL(((PCMOVCIAP.BASEICMS * PCMOVCIAP.QTCONT) * (PCMOVCIAP.ALIQICMS1/100)) ,0),2)
                END AS VALOR_ICMS
              ,0 AS ALIQUOTA_CREDITO_SN
              ,0 AS VALOR_CREDITO_ICMS_SN
              ,0 AS BASE_II
              ,0 AS VALOR_DESPESA_ADUANEIRA
              ,0 AS VALOR_II
              ,0 AS VALOR_IOF
              ,NVL(PCMOVCIAP.CODSITTRIBIPI, PCPRODCIAP.SITTRIBUTIPI) AS SITUACAO_TRIBUTARIA_IPI
              ,ROUND(NVL(PCMOVCIAP.VLBASEIPI * PCMOVCIAP.QTCONT,0),2) AS BASE_IPI
              ,ROUND(NVL(PCMOVCIAP.VLIPI * PCMOVCIAP.QTCONT ,0), 2) AS VALOR_IPI
              ,ROUND(NVL(PCMOVCIAP.VLIPI * PCMOVCIAP.QTCONT ,0), 2) AS VALOR_IPI_CALCULO
              ,ROUND(NVL(PCMOVCIAP.VLIPI ,0), 2) AS VALOR_IPI_UNIDADE
              ,NVL(PCMOVCIAP.PERCIPI,0) AS ALIQUOTA_IPI
              ,CASE WHEN PCMOVCIAP.SITTRIBUT in ('20', '70') THEN
                    CASE WHEN NVL(PCMOVCIAP.VLITEM,0) <> 0 THEN
                       ROUND(100 - (((PCMOVCIAP.BASEICMS / (PCMOVCIAP.VLITEM)) * 100)),2)
                    ELSE
                       0
                    END
                ELSE
                    NVL(PCMOVCIAP.PERCBASERED,0)
                END AS PERCENTUAL_REDUCAO_BC
              ,PCMOVCIAP.PAUTA AS MODALIDADE_BC_ST
              ,ROUND(NVL(PCMOVCIAP.IVA,
                         0),
                     2) AS PERCENTUAL_MARGEM
              ,PCMOVCIAP.PERCBASEREDST AS PERCENTUAL_REDUCAO_ST
              ,ROUND(NVL(PCMOVCIAP.BASEICST,0) * PCMOVCIAP.QTCONT, 2) AS BASE_ST
              ,ROUND(NVL(PCMOVCIAP.VLST * PCMOVCIAP.QTCONT,0), 2) AS VALOR_ST
              ,0 AS VALOR_TOT_EMBALAGEM
              ,PCMOVCIAP.ALIQICMS1 AS ALIQUOTA_ST
              ,'I' AS RETIDO
              ,NVL(PCMOVCIAP.PERCOFINS,0) AS ALIQUOTA_COFINS
              ,NVL(PCMOVCIAP.PERPIS,0) AS ALIQUOTA_PIS
              ,NVL(PCMOVCIAP.CODSITTRIBPISCOFINS,99) AS SIT_PIS_CONFINS
              ,ROUND(NVL(PCMOVCIAP.VLBASEPISCOFINS * PCMOVCIAP.QTCONT,0), 2) AS VL_BASE_PIS
              ,ROUND(NVL(PCMOVCIAP.VLCOFINS * PCMOVCIAP.QTCONT,0), 2) AS VALOR_COFINS
              ,ROUND(NVL(PCMOVCIAP.VLBASEPISCOFINS * PCMOVCIAP.QTCONT,0), 2) AS VL_BASE_CONFINS
              ,ROUND(NVL(PCMOVCIAP.VLPIS * PCMOVCIAP.QTCONT,0), 2) AS VALOR_PIS
              ,NULL AS CLASSIFICFISCAL
              ,NULL AS CODFILIALRETIRA
              ,0 AS CODIGO_FABRICANTE
              ,0 AS CODIGO_FORNECEDOR
              ,PCPRODCIAP.EMBALAGEM AS EMBALAGEM
              ,NULL AS EMBALAGEMMASTER
              ,NULL AS FANTASIA
              ,NULL AS FORNECEDOR
              ,0 AS PESOEMBALAGEM
              ,0 AS FATORUNFARM
              ,0 AS NUMORIGINAL
              ,NULL AS MARCA
              ,NULL AS PRINCIPIOATIVO
              ,CASE WHEN (NVL(PCMOVCIAP.VLITEM,0) <> 0) AND (NVL(PCMOVCIAP.QTCONT,0) <> 0) THEN 
                   (PCMOVCIAP.VLDESCONTO / (PCMOVCIAP.VLITEM / PCMOVCIAP.QTCONT)) * 100 
               ELSE
                   0    
               END AS PERCDESC
              ,0 AS PESOCX
              ,0 AS QTCX
              ,0 AS QTPECAS
              ,0 AS QTUN
              ,PCMOVCIAP.PUNITCONT AS PTABELA
              ,PCMOVCIAP.PUNITCONT
              ,0 AS QTD_CAIXAS_MASTER
              ,0 AS QTD_PECAS_INTERM
              ,0 AS QTUNITCX
              ,PCMOVCIAP.QTCONT AS QUANTIDADE_ENTREGA
              ,'UN' AS TIPO_QUANTIDADE
              ,0 AS STCLIENTEGNRE
              ,'PA'AS TIPOESTOQUE
              ,'X' AS TIPOTRIBUTMEDIC
              ,0   AS TOTPESOLIQUNIT
              ,NULL AS UNIDADEMASTER
              ,0 AS VLBASEGNRE
              ,0 AS NUMVOLUMESCONFERENCIA
              ,0 AS PERACRESCIMOCUSTO
              ,NULL AS TIPOSEPARACAO
              ,0 AS QTUNITEMB
              ,NULL AS UNIDADE_EMBALAGEM
              ,0 AS QTD_EMBALAGEM
              ,0 AS CODIGO_SECAO
              ,0 AS CODIGO_DEPARTAMENTO
              ,NULL AS DESCRICAO_SECAO
              ,NULL AS DESCRICAO_DEPARTAMENTO
              ,0 AS BASEBCR
              ,0 AS STBCR
              ,0 AS VOLUME
              ,0 AS QTD_CAIXA
              ,0 AS QTD_UNIDADE
              ,0 AS NUMERO_PEDIDO
              ,0 AS NUMERO_ITEM_PEDIDO
              ,0 AS NUMSEQ
              ,0 AS QTUNIT
              ,0 AS VALOR_UN_EMABALAGEM
              ,ROUND(PCMOVCIAP.QTCONT *  DECODE(NVL(PCMOVCIAP.CODOPER, 'SD'), 'SD', NVL(PCMOVCIAP.VLOUTRASDESP, 0), 0), 2) AS VALOR_OUTROS              
              --dados veiculos
              ,NULL AS TPOPERACAO
              ,NULL AS CHASSIVEICULO
              ,NULL AS CORVEICULO
              ,NULL AS DESCCORVEICULO
              ,NULL AS POTVEICULO
              ,NULL AS  CILINVEICULO
              ,NULL AS  PESOLVEICULO
              ,NULL AS PESOBVEICULO
              ,NULL AS SERIALVEICULO
              ,NULL AS TPCOMBVEICULO
              ,NULL AS NMOTORVEICULO
              ,NULL AS CMTVEICULO
              ,NULL AS DISTEIXOVEICULO
              ,NULL AS ANOMODVEICULO
              ,NULL AS ANOFABVEICULO
              ,NULL AS TPPINTVEICULO
              ,NULL AS TPVEICVEICULO
              ,NULL AS ESPVEICVEICULO
              ,NULL AS CONDVINVEICULO
              ,NULL AS CONDVEICVEICULO
              ,NULL AS MARCMODVEICULO
              ,NULL AS CORDENATRANVEICULO
              ,NULL AS LOTACAOVEICULO
              ,NULL AS TPRESTVEICULO
              --fim dados veiculos
              ,0 AS PRECO_MAX_CONSUMIDOR
              ,0 AS PRECO_FABRICA
              ,0 AS DESCONTO_FABRICA
              ,NULL AS CODPRODCABCESTA
              ,NULL AS PERCBONIFIC
              ,NULL AS NUMERO_FCI
              ,PCPRODCIAP.CODANP AS CODIGOANP
              ,PCPRODCIAP.DESCANP AS DESC_ANP
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLICMSDEVIDO,0), 2) AS VALOR_ICMS_DEVIDO
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLICMSDIFERIDO,0), 2) AS VALORICMSDIF
              ,NVL(PCMOVCIAP.PERCICMSDIFERIDO,0) AS ALIQUOTAICMSDIF
              ,ROUND(PCMOVCIAP.QTCONT * PCMOVCIAP.VLICMSDESONERACAO, 2) AS VALOR_ICMS_DESONERADO
              ,NVL(PCMOVCIAP.MOTDESICMS, PCMOVCIAP.CODMOTIVOICMSDESONERADO) AS COD_MOTIVO_DESONERACAO
              ,ROUND(NVL(PCMOVCIAP.VLIPIDEVFORNEC * PCMOVCIAP.QTCONT,0),2) AS VALOR_IPI_OUTROS
              , NULL AS TIPO_PRESENCA_ADQUIRINTE
              ,nvl(PCMOVCIAP.ALIQFCP, 0) as ALIQFCPPART
              ,nvl(PCMOVCIAP.ALIQINTERNADEST, 0) as ALIQINTERNADEST
              ,nvl(PCMOVCIAP.ALIQINTERORIGPART, 0) as ALIQINTERORIGPART
              ,ROUND(PCMOVCIAP.QTCONT * nvl(PCMOVCIAP.VLFCPPART, 0),2) as VLFCPPART
              ,ROUND(PCMOVCIAP.QTCONT * nvl(PCMOVCIAP.VLBASEPARTDEST, 0),2) as VLBASEPARTDEST
              ,nvl(PCMOVCIAP.PERCPROVPART,0) as PERCPROVPART
              ,ROUND(PCMOVCIAP.QTCONT * nvl(PCMOVCIAP.VLICMSDIFALIQPART, 0),2) as VLICMSDIFALIQPART
              ,ROUND(PCMOVCIAP.QTCONT * nvl(PCMOVCIAP.VLICMSPARTDEST, 0),2) as VLICMSPARTDEST
              ,ROUND(PCMOVCIAP.QTCONT * nvl(PCMOVCIAP.VLICMSPARTREM, 0),2) as VLICMSPARTREM
              ,PCMOVCIAP.CODCEST
              ,PCMOVCIAP.CODENQIPI
              ,PCMOVCIAP.CODBENEFICIOFISCAL AS COD_BENEFICIO_FISCAL
              ,PCPRODCIAP.INDESCALARELEVANTE AS IND_ESCALA_RELEVANTE
              ,PCPRODCIAP.CNPJFABRICANTE AS CNPJ_FABRICANTE
              ,PCMOVCIAP.CODAGREGACAO AS COD_AGREGACAO
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLBASEFCPICMS, PCMOVCIAP.BASECALCFCP),2) AS BASE_FCP_ICMS
              ,NVL(PCMOVCIAP.PERACRESCIMOFUNCEP, PCMOVCIAP.PERCFCP) AS PERC_FCP
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLACRESCIMOFUNCEP, PCMOVCIAP.VLFCP),2) AS VALOR_FCP   
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.BASECALCFCPST,0),2) AS BASE_CALC_FCP_ST
              ,PCMOVCIAP.PERCFCPST AS PERC_FCP_ST
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VLFCPST,0),2) AS VL_FCP_ST
              ,PCMOVCIAP.VLBCFCPSTRET
              ,PCMOVCIAP.PERFCPSTRET
              ,PCMOVCIAP.VLFCPSTRET
              ,PCMOVCIAP.PERFCPSN
              ,PCMOVCIAP.VLCREDFCPICMSSN
              ,PCMOVCIAP.MOTREDADREM
              ,NVL(PCMOVCIAP.ADREMICMS, 0) AS ADREMICMS
              ,NVL(PCMOVCIAP.ADREMICMSRETEN, 0) AS ADREMICMSRETEN
              ,NVL(PCMOVCIAP.PREDADREM, 0) AS PREDADREM
              ,NVL(PCMOVCIAP.ADREMICMSDIF, 0) AS ADREMICMSDIF
              ,NVL(PCMOVCIAP.ADREMICMSRET, 0) AS ADREMICMSRET
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.QBCMONO, 0),2) AS QBCMONO
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VICMSMONO, 0),2) AS VICMSMONO
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.QBCMONORETEN, 0),2) AS QBCMONORETEN
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VICMSMONORETEN, 0),2) AS VICMSMONORETEN
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.QBCMONODIF, 0),2) AS QBCMONODIF
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VICMSMONODIF, 0),2) AS VICMSMONODIF
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.QBCMONORET, 0),2) AS QBCMONORET
              ,ROUND(PCMOVCIAP.QTCONT * NVL(PCMOVCIAP.VICMSMONORET, 0),2) AS VICMSMONORET              
              ,0 AS COD_PRIORIDADE_IMPRESSAO
              ,NVL((SELECT NVL(M.PERCIPI,0) FROM PCMOVCIAP M
                 WHERE PCMOVCIAP.NUMTRANSENT = SQL_NFE_CABECALHO_SAIDA.NUMTRANSENTORIGEM
                 AND M.CODPROD = PCMOVCIAP.CODPROD
                 AND ROWNUM = 1),0) AS PERCENTUAL_IPI_DEVOLUCAO
        FROM   PCMOVCIAP
              ,PCPRODCIAP
              ,SQL_NFE_CABECALHO_SAIDA
        WHERE  PCMOVCIAP.NUMTRANSVENDA = SQL_NFE_CABECALHO_SAIDA.NUM_TRANSACAO
        AND    PCMOVCIAP.CODPROD = PCPRODCIAP.CODPROD
        AND    NVL(PCMOVCIAP.QTCONT,0) > 0
        AND    ((NOT EXISTS(SELECT 1 FROM PCNFBASE WHERE PCNFBASE.NUMTRANSVENDA = PCMOVCIAP.NUMTRANSVENDA)) OR
               (SQL_NFE_CABECALHO_SAIDA.FINALIDADE NOT IN (2,3)))
        )
ORDER  BY NUMSEQ