DECLARE 
  iCOUNT Integer;
BEGIN     

  FOR DADOS IN (
    SELECT 108 COD, 'SERVIÇO PARALISADO MOMENTANEAMENTE (CURTO PRAZO)' DESCRICAO FROM DUAL UNION
    SELECT 109 COD, 'SERVIÇO PARALISADO SEM PREVISÃO' DESCRICAO FROM DUAL UNION
    SELECT 128 COD, 'LOTE DE EVENTO PROCESSADO' DESCRICAO FROM DUAL UNION
    SELECT 135 COD, 'EVENTO REGISTRADO E VINCULADO AO DOCUMENTO' DESCRICAO FROM DUAL UNION
    SELECT 136 COD, 'EVENTO REGISTRADO, MAS NÃO VINCULADO AO DOCUMENTO' DESCRICAO FROM DUAL UNION
    SELECT 213 COD, 'CNPJ-BASE DO EMITENTE DIFERE DO CNPJ-BASE DO CERTIFICADO DIGITAL' DESCRICAO FROM DUAL UNION
    SELECT 214 COD, 'TAMANHO DA MENSAGEM EXCEDEU O LIMITE ESTABELECIDO' DESCRICAO FROM DUAL UNION
    SELECT 225 COD, 'FALHA NO SCHEMA XML DO LOTE DE CCE' DESCRICAO FROM DUAL UNION
    SELECT 226 COD, 'CODIGO DA UF DO EMITENTE DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 238 COD, 'CABEÇALHO - VERSÃO DO ARQUIVO XML SUPERIOR A VERSÃO VIGENTE' DESCRICAO FROM DUAL UNION
    SELECT 239 COD, 'CABEÇALHO - VERSÃO DO ARQUIVO XML NÃO SUPORTADA' DESCRICAO FROM DUAL UNION
    SELECT 242 COD, 'CABEÇALHO - FALHA NO SCHEMA XML' DESCRICAO FROM DUAL UNION
    SELECT 250 COD, 'UF DIVERGE DA UF AUTORIZADORA' DESCRICAO FROM DUAL UNION
    SELECT 252 COD, 'AMBIENTE INFORMADO DIVERGE DO AMBIENTE DE RECEBIMENTO' DESCRICAO FROM DUAL UNION
    SELECT 280 COD, 'CERTIFICADO TRANSMISSOR INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 281 COD, 'CERTIFICADO TRANSMISSOR DATA VALIDADE' DESCRICAO FROM DUAL UNION
    SELECT 282 COD, 'CERTIFICADO TRANSMISSOR SEM CNPJ' DESCRICAO FROM DUAL UNION
    SELECT 283 COD, 'CERTIFICADO TRANSMISSOR - ERRO CADEIA DE CERTIFICAÇÃO' DESCRICAO FROM DUAL UNION
    SELECT 284 COD, 'CERTIFICADO TRANSMISSOR REVOGADO' DESCRICAO FROM DUAL UNION
    SELECT 285 COD, 'CERTIFICADO TRANSMISSOR DIFERE ICP-BRASIL' DESCRICAO FROM DUAL UNION
    SELECT 286 COD, 'CERTIFICADO TRANSMISSOR ERRO NO ACESSO A LCR' DESCRICAO FROM DUAL UNION
    SELECT 290 COD, 'CERTIFICADO ASSINATURA INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 291 COD, 'CERTIFICADO ASSINATURA DATA VALIDADE' DESCRICAO FROM DUAL UNION
    SELECT 292 COD, 'CERTIFICADO ASSINATURA SEM CNPJ' DESCRICAO FROM DUAL UNION
    SELECT 293 COD, 'CERTIFICADO ASSINATURA - ERRO CADEIA DE CERTIFICAÇÃO' DESCRICAO FROM DUAL UNION
    SELECT 294 COD, 'CERTIFICADO ASSINATURA REVOGADO' DESCRICAO FROM DUAL UNION
    SELECT 295 COD, 'CERTIFICADO ASSINATURA DIFERE ICP-BRASIL' DESCRICAO FROM DUAL UNION
    SELECT 296 COD, 'CERTIFICADO ASSINATURA ERRO NO ACESSO A LCR' DESCRICAO FROM DUAL UNION
    SELECT 297 COD, 'ASSINATURA DIFERE DO CALCULADO' DESCRICAO FROM DUAL UNION
    SELECT 298 COD, 'ASSINATURA DIFERE DO PADRÃO DO PROJETO' DESCRICAO FROM DUAL UNION
    SELECT 402 COD, 'XML DA ÁREA DE DADOS COM CODIFICAÇÃO DIFERENTE DE UTF-8' DESCRICAO FROM DUAL UNION
    SELECT 404 COD, 'USO DE PREFIXO DE NAMESPACE NÃO PERMITIDO' DESCRICAO FROM DUAL UNION
    SELECT 409 COD, 'CAMPO CUF INEXISTENTE NO ELEMENTO NFECABECMSG DO SOAP HEADER' DESCRICAO FROM DUAL UNION
    SELECT 410 COD, 'UF INFORMADA NO CAMPO CUF NÃO É ATENDIDA PELO WEB SERVICE' DESCRICAO FROM DUAL UNION
    SELECT 411 COD, 'CAMPO VERSAODADOS INEXISTENTE NO ELEMENTO NFECABECMSG DO SOAP HEADER' DESCRICAO FROM DUAL UNION
    SELECT 489 COD, 'CNPJ DO AUTOR DO EVENTO INFORMADO INVÁLIDO (DV OU ZEROS)' DESCRICAO FROM DUAL UNION
    SELECT 490 COD, 'CPF DO AUTOR DO EVENTO INFORMADO INVÁLIDO (DV OU ZEROS)' DESCRICAO FROM DUAL UNION
    SELECT 491 COD, 'TIPO DE EVENTO INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 492 COD, 'VERSÃO DO EVENTO INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 493 COD, 'DETALHE DO EVENTO NÃO ATENDE O RESPECTIVO SCHEMA XML' DESCRICAO FROM DUAL UNION
    SELECT 494 COD, 'CHAVE DE ACESSO INEXISTENTE PARA O TPEVENTO QUE EXIGE A EXISTÊNCIA DA NFE' DESCRICAO FROM DUAL UNION
    SELECT 501 COD, 'NF-E AUTORIZADA HÁ MAIS DE 30 DIAS (720) HORAS' DESCRICAO FROM DUAL UNION
    SELECT 516 COD, 'FALHA NO SCHEMA XML' DESCRICAO FROM DUAL UNION
    SELECT 517 COD, 'FALHA NO SCHEMA XML' DESCRICAO FROM DUAL UNION
    SELECT 545 COD, 'FALHA NO SCHEMA XML' DESCRICAO FROM DUAL UNION
    SELECT 572 COD, 'CAMPO ID DO XML INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 573 COD, 'EVENTO COM DUPLICIDADE (TIPOEVENTO + CHAVENFE + SEQUENCIAENVENTO)' DESCRICAO FROM DUAL UNION
    SELECT 574 COD, 'AUTOR DO EVENTO DIVERGE DO EMISSOR DA NF-E' DESCRICAO FROM DUAL UNION
    SELECT 575 COD, 'AUTOR DO EVENTO DIVERGE DO DESTINATÁRIO DA NF-E' DESCRICAO FROM DUAL UNION
    SELECT 576 COD, 'AUTOR DO EVENTO NÃO É UM ÓRGÃO AUTORIZADO A GERAR O EVENTO' DESCRICAO FROM DUAL UNION
    SELECT 577 COD, 'DATA DO EVENTO NÃO PODE SER MENOR QUE A DATA DE EMISSÃO DA NF-E, SE EXISTIR' DESCRICAO FROM DUAL UNION
    SELECT 578 COD, 'DATA DO EVENTO NÃO PODE SER MAIOR QUE A DATA DE PROCESSAMENTO' DESCRICAO FROM DUAL UNION
    SELECT 579 COD, 'DATA DO EVENTO NÃO PODE SER MENOR QUE A DATA DE AUTORIZAÇÃO PARA NF-E NÃO EMITIDA EM CONTINGÊNCIA SE A NF-E EXISTIR' DESCRICAO FROM DUAL UNION
    SELECT 580 COD, 'NF-E NÃO AUTORIZADA (CANCELADA OU DENEGADA)' DESCRICAO FROM DUAL UNION
    SELECT 587 COD, 'USAR SOMENTE O NAMESPACE PADRÃO DA NF-E' DESCRICAO FROM DUAL UNION
    SELECT 588 COD, 'NÃO É PERMITIDA A PRESENÇA DE CARACTERES DE EIÇÃO NO INÍCIO/FIM DA MENSAGEM OU ENTRE AS TAGS DA MENSAGEM' DESCRICAO FROM DUAL UNION
    SELECT 594 COD, 'SEQUENCIAL DO EVENTO (HP15 - NSEQEVENTO) ESTÁ COM VALOR INVÁLIDO (1-20)' DESCRICAO FROM DUAL UNION
    SELECT 999 COD, 'ERRO NÃO CATALOGADO' DESCRICAO FROM DUAL UNION
    SELECT 1000 COD, 'NOTA REPROVADA PELO VALIDADOR LOCAL' DESCRICAO FROM DUAL UNION
    SELECT 1001 COD, 'NOTA SENDO PROCESSADA PELO SERVIDOR LOCAL' DESCRICAO FROM DUAL UNION
    SELECT 2000 COD, 'CERTIFICADO DO EMITENTE INVÁLIDO OU NÃO INFORMADO' DESCRICAO FROM DUAL UNION
    SELECT 2001 COD, 'UF DO EMITENTE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 2002 COD, 'TIPO DE AMBIENTE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 2003 COD, 'TIPO DE PESSOA DO EMITENTE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 2004 COD, 'CPF DO EMITENTE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 2005 COD, 'CNPJ DO EMITENTE INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 2006 COD, 'CHAVE NFE DIFERENTE DE 44 CARACTERES' DESCRICAO FROM DUAL UNION
    SELECT 2007 COD, 'DATA E HORA DO EVENTO INVÁLIDO' DESCRICAO FROM DUAL UNION
    SELECT 2008 COD, 'DESCRIÇÃO DA CORREÇÃO MENOR 15 OU MAIOR QUE 1000 CARACTERES' DESCRICAO FROM DUAL
  ) LOOP
  
    SELECT COUNT(*) INTO iCOUNT FROM PCMENSAGEMCCE WHERE CODMENSAGEM = DADOS.COD;
    
    IF iCOUNT = 0 THEN
       INSERT INTO PCMENSAGEMCCE (CODMENSAGEM, DESCRICAO) VALUES(DADOS.COD, substr(DADOS.DESCRICAO, 0, 180));
    ELSE
       UPDATE PCMENSAGEMCCE SET
         DESCRICAO = substr(DADOS.DESCRICAO, 0, 180)
       WHERE CODMENSAGEM = DADOS.COD;       
    END IF;
  END LOOP;
  COMMIT;
END;