BEGIN 
UPDATE PCDICIONARIOITEMROT SET SECAO = '01-Geral', EXIBIRRESPESQ = 'S' 
 WHERE CODROTINA = '3328' 
   AND NOMEOBJETO = 'PCTRIBNCMFILIAL' 
   AND NOMECAMPO IN ('CODFILIAL','CODNCM','PERCENTFISICA','PERCENTJURIDICA','PERCENTJURIDICAIMPORTADO','PERCFISICAMUNICNAC', 
                     'PERCFISICAESTNAC','PERCJURIDICMUNICNAC','PERCJURIDICESTNAC','PERCFISICAMUNICIMP','PERCFISICAESTIMP',
                     'PERCJURIDICMUNICIMP','PERCJURIDICESTIMP','PERCENTFISICAIMPORTADO'); 
COMMIT; 

UPDATE PCDICIONARIOITEMROT SET PSQCAMPO = 'CODNCM=Código do NCM,CODEX=Código da exceção do NCM,DESCRICAO=Descrição do NCM,CODNCMEX=Código do NCM com exceção'
 WHERE CODROTINA = '3328' 
   AND NOMEOBJETO = 'PCTRIBNCMFILIAL' 
   AND NOMECAMPO = 'CODNCM';   
COMMIT; 
 
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Fed.PF prod.Nacional'  WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCENTFISICA';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Fed.PF prod.Importado' WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCENTFISICAIMPORTADO';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Fed.PJ prod.Nacional'  WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCENTJURIDICA';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Fed.PJ prod.Importado' WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCENTJURIDICAIMPORTADO';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Est.PF prod.Importado' WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCFISICAESTIMP';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Est.PF prod.Nacional'  WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCFISICAESTNAC';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Mun.PF prod.Importado' WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCFISICAMUNICIMP';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Mun.PF prod.Nacional'  WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCFISICAMUNICNAC';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Est.PJ prod.Importado' WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCJURIDICESTIMP';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Est.PJ prod.Nacional'  WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCJURIDICESTNAC';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Mun.PJ prod.Importado' WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCJURIDICMUNICIMP';
UPDATE PCDICIONARIOITEM SET TITULO = '% Trib.Mun.PJ prod.Nacional'  WHERE NOMEOBJETO = 'PCTRIBNCMFILIAL' AND NOMECAMPO = 'PERCJURIDICMUNICNAC';
 
COMMIT; 
END; 