CREATE OR REPLACE PACKAGE PKG_INT_C5_GIFTCARD IS

  PROCEDURE PROCESSAR_GIFTCARD(P_SEQDOCTO NUMBER DEFAULT 0, P_NROCHECKOUT NUMBER DEFAULT 0, P_NROEMPRESA NUMBER DEFAULT 0);

END PKG_INT_C5_GIFTCARD;
