ALTER TABLE PCINTEGRACAODEPARA DROP CONSTRAINT PCINTEGRACAODEPARA_UK1 CASCADE;
\
ALTER TABLE PCINTEGRACAODEPARA DROP CONSTRAINT PCINTEGRACAODEPARA_UK2 CASCADE;
\ 
ALTER TABLE PCINTEGRACAODEPARA ADD CONSTRAINT PCINTEGRACAODEPARA_UK1 UNIQUE (TABELA, CAMPO, IDINTERNO, IDEXTERNO);