DECLARE
  EXISTE_UNIQUE NUMBER;
  TYPE ListaCampos IS TABLE OF VARCHAR2(60);
  nomeCampo ListaCampos := ListaCampos('PCINTEGRACAODEPARA_UK1', 'PCINTEGRACAODEPARA_UK2');
  vScript VARCHAR2(4000);
BEGIN
FOR i IN 1 .. nomeCampo.COUNT LOOP
    BEGIN
      SELECT COUNT(1)
        INTO EXISTE_UNIQUE
        FROM All_Constraints A
       WHERE A.TABLE_NAME = 'PCINTEGRACAODEPARA'
         AND A.INDEX_NAME IS NOT NULL
         AND A.CONSTRAINT_NAME = nomeCampo(I);
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        EXISTE_UNIQUE := 0;
    END;
  
    IF nomeCampo(I) = 'PCINTEGRACAODEPARA_UK1' AND EXISTE_UNIQUE <> 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PCINTEGRACAODEPARA DROP CONSTRAINT PCINTEGRACAODEPARA_UK1 CASCADE';
    END IF;
  
    IF nomeCampo(I) = 'PCINTEGRACAODEPARA_UK2' AND EXISTE_UNIQUE <> 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PCINTEGRACAODEPARA DROP CONSTRAINT PCINTEGRACAODEPARA_UK2 CASCADE';
    END IF;
  END LOOP;
  
  vScript := 'ALTER TABLE PCINTEGRACAODEPARA ADD CONSTRAINT PCINTEGRACAODEPARA_UK1 UNIQUE (TABELA, CAMPO, IDINTERNO, IDEXTERNO)';
  execute immediate vscript;
  
END;
