CREATE OR REPLACE PACKAGE BODY PKG_CREDITOCLIENTE AS
/*
PACKAGE CRIADA PARA MANIPULAR OS PROCESSOS DE INCLUSÃO, BAIXA E ESTORNO DE CREDITOS.
DESENVOLVIDO POR PAULO GONÇALVES EM 15-MAI-2016
*/
  /*
  1. "FNC_BAIXARCREDITOCLIENTE"
  FUNÇÃO CRIADA PARA ATENDER A PACKAGE DE FATURAMENTO DA EQUIPE DE VENDAS.
  ONDE É PASSADO A NOTA, VALOR E CLIENTE. AUTOMATICAMENTE É FEITO AS BAIXAS DOS CREDITOS EM ABERTO.
  */
  FUNCTION FNC_BAIXARCREDITOCLIENTE(psFILIAL           IN VARCHAR2,
                                    pfCODCLI           IN NUMBER,
                                    pfNUMNOTA          IN NUMBER,
                                    pfNUMTRANSVENDA    IN NUMBER,
                                    pfNUMPED           IN NUMBER,
                                    pfVALORNOTA        IN NUMBER,
                                    pfCODIGOROTINA     IN NUMBER,
                                    pfMATRICULAUSUARIO IN NUMBER
                                   ) RETURN NUMBER IS
      vfVALOR NUMBER(14,2);
      vfNUMCRED NUMBER(10);
      voCREDITOCLIENTE T_PC_CREDITOCLIENTE;
      voDESD T_PC_DESDCREDITOCLIENTE;
    BEGIN
      --VALIDANDO PARAMETROS DE ENTRADA!
      IF ((TRIM(psFILIAL) = '') OR (psFILIAL IS NULL)) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UMA FILIAL');
      END IF;

      IF (pfCODCLI <= 0) OR (pfCODCLI IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO PARA O CLIENTE');
      END IF;

      IF (pfVALORNOTA <= 0) OR (pfVALORNOTA IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM VALOR PARA SER BAIXADO O CREDITO');
      END IF;

      vfVALOR := pfVALORNOTA;
      --CRIANDO OBJETO DE PERSISTENCIA COM PCCRECLI
      voCREDITOCLIENTE := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voDESD           := T_PC_DESDCREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      --OBTENDO O "NUMCRED" CODIGO IDENTIFICADOR PARA RELACIONAMENTO DE REGISTROS NA BAIXA
      IF NVL(voCREDITOCLIENTE.NUMCRED,0) > 0 THEN
       vfNUMCRED:= voCREDITOCLIENTE.NUMCRED;
      ELSE
       SELECT DFSEQ_PCCRECLI_NUMCRED.NEXTVAL INTO vfNUMCRED FROM DUAL;
      END IF;

      INSERELOG('FNC_BAIXARCREDITOCLIENTE', psFILIAL, 0, 0, pfNUMTRANSVENDA, 0, 0, pfVALORNOTA, 'Iniciou', vfNUMCRED, pfNUMPED, pfCODIGOROTINA);

      --BUSCANDO OS CREDITOS DO CLIENTE INFORMADO
      FOR LISTACREDITOS IN ( SELECT C.CODCLI,
                                    C.DTLANC,
                                    C.CODFILIAL,
                                    C.ORIGEM,
                                    C.NUMNOTA,
                                    NVL(C.NUMTRANSVENDA, 0) NUMTRANSVENDA,
                                    C.NUMTRANSENTDEVCLI,
                                    C.VALOR,
                                    NVL(C.NUMTRANS, 0) NUMTRANS,
                                    NVL(C.NUMLANC, 0) NUMLANC,
                                    C.SERIE,
                                    C.HISTORICO,
                                    C.NUMPED,
                                    C.DTEMISSAOTITULO,
                                    C.CODIGO,
                                    C.CODPLPAG,
                                    C.NUMERARIO,
                                    C.CODMOVIMENTO
                             FROM PCCRECLI C
                             WHERE C.CODCLI =  pfCODCLI
                             AND   C.DTDESCONTO IS NULL
                             AND   C.DTESTORNO IS NULL
                             AND   C.SITUACAO IS NULL
                             AND   ((PARAMFILIAL.OBTERCOMOVARCHAR2('USACREDCLITODASFILIAIS') = 'S') OR (C.CODFILIAL = psFILIAL))
                             AND   NVL(C.NUMPED,0) = DECODE(NVL(pfNUMPED, 0), 0, 0, NVL(pfNUMPED, 0))
                             ORDER BY C.VALOR)
      LOOP
         --ATRIBUO UMA VEZ VALOR AO OBJETO. E FAÇO AS MODIFICACOES COM BASE NA OPERACAO QUE DESEJAR.
         voCREDITOCLIENTE.LIMPAR;
         voCREDITOCLIENTE.DTLANC            := LISTACREDITOS.DTLANC;
         voCREDITOCLIENTE.DTEMISSAOTITULO   := LISTACREDITOS.DTEMISSAOTITULO;
         voCREDITOCLIENTE.CODIGO            := LISTACREDITOS.CODIGO;
         voCREDITOCLIENTE.CODCLI            := LISTACREDITOS.CODCLI;
         voCREDITOCLIENTE.CODFILIAL         := LISTACREDITOS.CODFILIAL;
         voCREDITOCLIENTE.CODFILIALDESC     := LISTACREDITOS.CODFILIAL;
         voCREDITOCLIENTE.NUMTRANS          := LISTACREDITOS.NUMTRANS;
         voCREDITOCLIENTE.NUMLANC           := LISTACREDITOS.NUMLANC;
         voCREDITOCLIENTE.NUMNOTA           := LISTACREDITOS.NUMNOTA;
         voCREDITOCLIENTE.NUMNOTADESC       := pfNUMNOTA;
         voCREDITOCLIENTE.SERIE             := LISTACREDITOS.SERIE;
         voCREDITOCLIENTE.SERIEDESC         := LISTACREDITOS.SERIE;
         voCREDITOCLIENTE.NUMTRANSVENDADESC := pfNUMTRANSVENDA;
         voCREDITOCLIENTE.NUMTRANSVENDA     := LISTACREDITOS.NUMTRANSVENDA;
         voCREDITOCLIENTE.NUMTRANSENTDEVCLI := LISTACREDITOS.NUMTRANSENTDEVCLI;
         voCREDITOCLIENTE.ORIGEM            := LISTACREDITOS.ORIGEM;
         voCREDITOCLIENTE.NUMPED            := LISTACREDITOS.NUMPED;
         voCREDITOCLIENTE.VALOR             := LISTACREDITOS.VALOR;
         voCREDITOCLIENTE.NUMCRED           := vfNUMCRED;
         voCREDITOCLIENTE.CODPLPAG          := LISTACREDITOS.CODPLPAG;
         voCREDITOCLIENTE.NUMERARIO         := LISTACREDITOS.NUMERARIO;
         voCREDITOCLIENTE.CODMOVIMENTO      := LISTACREDITOS.CODMOVIMENTO;
        -- SE NÃO TEM MAIS NADA. SAIR DO LAÇO!
        IF (vfVALOR <= 0) THEN
          INSERELOG('FNC_BAIXARCREDITOCLIENTE', psFILIAL, 0, 0, pfNUMTRANSVENDA, 0, vfVALOR, pfVALORNOTA, 'Saiu', vfNUMCRED, pfNUMPED, pfCODIGOROTINA);
          EXIT;
        -- SE O VALOR DA NOTA É IGUAL AO VALOR DO CREDITO. BAIXAR APENAS O CREDITO.
        ELSIF ((LISTACREDITOS.VALOR = vfVALOR) OR (LISTACREDITOS.VALOR < vfVALOR))  THEN
          INSERELOG('FNC_BAIXARCREDITOCLIENTE', psFILIAL, 0, 0, pfNUMTRANSVENDA, LISTACREDITOS.VALOR, vfVALOR, pfVALORNOTA, 'BaixaTotal Codigo: '||LISTACREDITOS.CODIGO, vfNUMCRED, pfNUMPED, pfCODIGOROTINA);
          voCREDITOCLIENTE.HISTORICO         := SUBSTR(LISTACREDITOS.HISTORICO || '-' || 'BX NF.: '|| pfNUMNOTA || ' - NUMTRANSVENDA.:  ' ||pfNUMTRANSVENDA, 1, 100);
          voCREDITOCLIENTE.BAIXAR;
          vfVALOR                            := vfVALOR - LISTACREDITOS.VALOR;
        -- O CREDITO É MAIOR QUE O VALOR DA NOTA
        ELSIF (LISTACREDITOS.VALOR > vfVALOR)  THEN
          INSERELOG('FNC_BAIXARCREDITOCLIENTE', psFILIAL, 0, 0, pfNUMTRANSVENDA, vfVALOR, vfVALOR, pfVALORNOTA, 'BaixaParcial Codigo: '||LISTACREDITOS.CODIGO, vfNUMCRED, pfNUMPED, pfCODIGOROTINA);
          --ESTORNAR O ORIGINAL
          voCREDITOCLIENTE.HISTORICO         := SUBSTR(LISTACREDITOS.HISTORICO || '-' || 'DESD BX NF.: '|| pfNUMNOTA || ' - NUMTRANSVENDA.:  ' ||pfNUMTRANSVENDA, 1, 100);
          voCREDITOCLIENTE.ESTORNARTOTAL;
          --GERAR CREDITO QUITADO DO VALOR DA NOTA
          voCREDITOCLIENTE.CODIGO            := voCREDITOCLIENTE.PROXIMOCODIGOCREDITO;
          voCREDITOCLIENTE.HISTORICO         := SUBSTR(LISTACREDITOS.HISTORICO || '-' || 'BX PARC NF.: '|| pfNUMNOTA || ' - NUMTRANSVENDA.:  ' ||pfNUMTRANSVENDA, 1, 100);
          voCREDITOCLIENTE.DTESTORNO         := NULL;
          voCREDITOCLIENTE.DTDESCONTO        := TRUNC(SYSDATE);
          voCREDITOCLIENTE.VALOR             := vfVALOR;
          voCREDITOCLIENTE.INSERIR;
          voDESD.CODIGOORIG                  := LISTACREDITOS.CODIGO;
          voDESD.CODIGODEST                  := voCREDITOCLIENTE.CODIGO;
          voDESD.INSERIR;
          --GERAR CREDITO EM ABERTO COM A DIFERENCA
          voCREDITOCLIENTE.CODIGO            := voCREDITOCLIENTE.PROXIMOCODIGOCREDITO;
          voCREDITOCLIENTE.HISTORICO         := SUBSTR(LISTACREDITOS.HISTORICO || '-' || 'DIF BX PARC NF.: '|| pfNUMNOTA || ' - NUMTRANSVENDA.:  ' ||pfNUMTRANSVENDA, 1, 100);
          voCREDITOCLIENTE.CODFILIALDESC     := NULL;
          voCREDITOCLIENTE.DTESTORNO         := NULL;
          voCREDITOCLIENTE.DTDESCONTO        := NULL;
          voCREDITOCLIENTE.NUMNOTADESC       := NULL;
          voCREDITOCLIENTE.NUMTRANSVENDADESC := NULL;
          voCREDITOCLIENTE.SERIEDESC         := NULL;
          voCREDITOCLIENTE.NUMPED            := NULL;
          voCREDITOCLIENTE.VALOR             := LISTACREDITOS.VALOR - vfVALOR;
          voCREDITOCLIENTE.DTLANC            := LISTACREDITOS.DTLANC;
          voCREDITOCLIENTE.INSERIR;
          voDESD.CODIGOORIG                  := LISTACREDITOS.CODIGO;
          voDESD.CODIGODEST                  := voCREDITOCLIENTE.CODIGO;
          voDESD.DTLANC                      := LISTACREDITOS.DTLANC;
          voDESD.INSERIR;
          vfVALOR                            := vfVALOR - vfVALOR;
        END IF;
      END LOOP; --FIM DO LOOP DOS CREDITOS

      INSERELOG('FNC_BAIXARCREDITOCLIENTE', psFILIAL, 0, 0, pfNUMTRANSVENDA, 0, vfVALOR, pfVALORNOTA, 'Fim', vfNUMCRED, pfNUMPED, pfCODIGOROTINA);

      IF (vfVALOR <= 0) THEN --SE O VALOR FOR NEGATIVO, NÃO DEVE GERAR NOVO TITULO.
         RETURN 0;
      ELSE
         RETURN vfVALOR; --SOBROU VALOR DA NOTA, DEVE SER DESDOBRADO EM TITULO.
      END IF;
   EXCEPTION WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20016,
                             CHR(13) ||
                             'NAO FOI POSSIVEL FAZER A BAIXA AUTOMATICA DE CREDITOS DE CLIENTE!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
  END FNC_BAIXARCREDITOCLIENTE;

  ----------------------------------------------------------------------------------------
  /*
  2. "FNC_ESTORNARCREDITOBAIXADO"
  FUNÇÃO CRIADA PARA ATENDER A FUNCAO DE CANCELAMENTO DE NOTA DA EQUIPE DE VENDAS.
  ONDE É PASSADO O NUMTRANSVENDA E AUTOMATICA SERA LOCALIZADO OS CREDITOS BAIXADOS E FEITO O ESTORNO TORNANDO EM ABERTO NOVAMENTE.
  O VALOR RETORNADO É O TOTAL DE CREDITO QUE CONSEGUIU SER ESTORNADO.
  PARA ATENDER A ROTINA 1209:
  **SE TIVER DE ESTORNAR O CREDITO DE UM TITULO ESPECIFICO SERÁ NECESSARIO INFORMAR "pfPRESTACAO" QUE EQUIVALE A BUSCAR PELO TITULO.
  **PARA ESTORNAR AUTOMATICAMENTE A PCPREST BASTA MARCAR O PARAMETRO "pbGERARPCPRESTAUTOMATICAMENTE", LEMBRANDO QUE PRECISA TAMBÉM DO "pfPRESTACAO.
  */
  FUNCTION FNC_ESTORNARCREDITOBAIXADO(pfNUMTRANSVENDA               IN NUMBER,
                                      pfCODIGOROTINA                IN NUMBER,
                                      pfMATRICULAUSUARIO            IN NUMBER,
                                      pfPRESTACAO                   IN VARCHAR2 DEFAULT '0',
                                      pbGERARPCPRESTAUTOMATICAMENTE IN BOOLEAN DEFAULT FALSE

  )
  RETURN NUMBER IS
    vfNUMCRED               NUMBER(10);
    voCREDITOCLIENTE        T_PC_CREDITOCLIENTE;
    voDESD                  T_PC_DESDCREDITOCLIENTE;
    vfTOTALCREDITOESTORNADO NUMBER(14,2);
    voCONTASRECEBER         T_PC_CONTASRECEBER;
  BEGIN

    IF (pfNUMTRANSVENDA <= 0) OR (pfNUMTRANSVENDA IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O NUMERO DE TRANSACAO DE VENDA (NUMTRANSVENDA) PARA FAZER O ESTORNO DO CREDITO BAIXADO.');
    END IF;

    IF ((pbGERARPCPRESTAUTOMATICAMENTE = TRUE) AND ((pfPRESTACAO IS NULL) OR (TRIM(pfPRESTACAO) = ''))) THEN
      RAISE_APPLICATION_ERROR(-20016,'PARA GERAR TITULOS NO CONTAS A RECEBER AUTOMATICAMENTO SERA NECESSARIO INFORMAR A PRESTACAO DO TITULO.');
    END IF;

    vfTOTALCREDITOESTORNADO := 0;
    --CRIANDO OBJETO DE PERSISTENCIA COM PCCRECLI
    voCREDITOCLIENTE := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    voDESD           := T_PC_DESDCREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    --OBTENDO O "NUMCRED" CODIGO IDENTIFICADOR PARA RELACIONAMENTO DE REGISTROS NA BAIXA
    IF NVL(voCREDITOCLIENTE.NUMCRED,0) > 0 THEN
     vfNUMCRED:= voCREDITOCLIENTE.NUMCRED;
    ELSE
     SELECT DFSEQ_PCCRECLI_NUMCRED.NEXTVAL INTO vfNUMCRED FROM DUAL;
    END IF;

    INSERELOG('FNC_ESTORNARCREDITOBAIXADO', '99', 0, 0, pfNUMTRANSVENDA, 0, 0, 0, 'Iniciou', vfNUMCRED, 0, pfCODIGOROTINA);
    --BUSCANDO OS CREDITOS BAIXADOS PARA O NUMTRANSVENDA INFORMADO. FAZER O ESTORNO SOMENTE DOS BAIXADOS!
    FOR LISTACREDITOS IN (SELECT C.CODCLI,
                                 C.DTLANC,
                                 C.CODFILIAL,
                                 C.ORIGEM,
                                 C.NUMNOTA,
                                 NVL(C.NUMTRANSVENDA, 0) NUMTRANSVENDA,
                                 C.NUMTRANSENTDEVCLI,
                                 C.VALOR,
                                 NVL(C.NUMTRANS, 0) NUMTRANS,
                                 NVL(C.NUMLANC, 0) NUMLANC,
                                 C.SERIE,
                                 C.HISTORICO,
                                 C.NUMPED,
                                 C.DTEMISSAOTITULO,
                                 C.CODIGO,
                                 C.DTDESCONTO,
                                 C.CODPLPAG,
                                 C.NUMERARIO,
                                 C.CODMOVIMENTO,
                                 C.NUMTRANSVENDADESC,
                                 C.PRESTRESTCLI
                          FROM PCCRECLI C
                          WHERE C.DTDESCONTO IS NOT NULL
                          AND   C.DTESTORNO IS NULL
                          AND   C.NUMTRANSVENDADESC = pfNUMTRANSVENDA
                          AND   ((C.PRESTRESTCLI = NVL(pfPRESTACAO,'')) OR ( pfPRESTACAO = '0' )) )
    LOOP
      --ATRIBUO UMA VEZ VALOR AO OBJETO. E FAÇO AS MODIFICACOES COM BASE NA OPERACAO QUE DESEJAR.
      voCREDITOCLIENTE.LIMPAR;
      voCREDITOCLIENTE.CODIGO            := LISTACREDITOS.CODIGO;
      voCREDITOCLIENTE.DTLANC            := LISTACREDITOS.DTLANC;
      voCREDITOCLIENTE.DTEMISSAOTITULO   := LISTACREDITOS.DTEMISSAOTITULO;
      voCREDITOCLIENTE.CODCLI            := LISTACREDITOS.CODCLI;
      voCREDITOCLIENTE.CODFILIAL         := LISTACREDITOS.CODFILIAL;
      voCREDITOCLIENTE.NUMTRANS          := LISTACREDITOS.NUMTRANS;
      voCREDITOCLIENTE.NUMLANC           := LISTACREDITOS.NUMLANC;
      voCREDITOCLIENTE.NUMNOTA           := LISTACREDITOS.NUMNOTA;
      voCREDITOCLIENTE.SERIE             := LISTACREDITOS.SERIE;
      voCREDITOCLIENTE.NUMTRANSVENDA     := LISTACREDITOS.NUMTRANSVENDA;
      voCREDITOCLIENTE.NUMTRANSVENDADESC := LISTACREDITOS.NUMTRANSVENDADESC;
      voCREDITOCLIENTE.PRESTRESTCLI      := LISTACREDITOS.PRESTRESTCLI;
      voCREDITOCLIENTE.NUMTRANSENTDEVCLI := LISTACREDITOS.NUMTRANSENTDEVCLI;
      voCREDITOCLIENTE.ORIGEM            := LISTACREDITOS.ORIGEM;
      voCREDITOCLIENTE.NUMPED            := LISTACREDITOS.NUMPED;
      voCREDITOCLIENTE.VALOR             := LISTACREDITOS.VALOR;
      voCREDITOCLIENTE.DTDESCONTO        := LISTACREDITOS.DTDESCONTO;
      voCREDITOCLIENTE.NUMCRED           := vfNUMCRED;
      --ESTORNAR O TITULO
      voCREDITOCLIENTE.HISTORICO         := SUBSTR(LISTACREDITOS.HISTORICO || '-' || 'EST BX NF.: '|| LISTACREDITOS.NUMNOTA || ' - NUMTRANSVENDA.:  ' ||pfNUMTRANSVENDA, 1, 100);
      voCREDITOCLIENTE.ESTORNARTOTAL;
      --CRIAR UM NOVO EM ABERTO IGUAL AO ORIGINAL
      voCREDITOCLIENTE.CODIGO            := voCREDITOCLIENTE.PROXIMOCODIGOCREDITO;
      voCREDITOCLIENTE.HISTORICO         := SUBSTR(LISTACREDITOS.HISTORICO || '-' || 'EST BX NF.: '|| LISTACREDITOS.NUMNOTA || ' - NUMTRANSVENDA.:  ' ||pfNUMTRANSVENDA, 1, 100);
      voCREDITOCLIENTE.CODFILIALDESC     := NULL;
      voCREDITOCLIENTE.DTESTORNO         := NULL;
      voCREDITOCLIENTE.DTDESCONTO        := NULL;
      voCREDITOCLIENTE.NUMNOTADESC       := NULL;
      voCREDITOCLIENTE.NUMTRANSVENDADESC := NULL;
      voCREDITOCLIENTE.PRESTRESTCLI      := NULL;
      voCREDITOCLIENTE.SERIEDESC         := NULL;
      voCREDITOCLIENTE.VALOR             := LISTACREDITOS.VALOR;
      voCREDITOCLIENTE.CODPLPAG          := LISTACREDITOS.CODPLPAG;
      voCREDITOCLIENTE.NUMERARIO         := LISTACREDITOS.NUMERARIO;
      voCREDITOCLIENTE.CODMOVIMENTO      := LISTACREDITOS.CODMOVIMENTO;
      voCREDITOCLIENTE.INSERIR;

      voDESD.CODIGOORIG                  := LISTACREDITOS.CODIGO;
      voDESD.CODIGODEST                  := voCREDITOCLIENTE.CODIGO;
      voDESD.DTLANC                      := LISTACREDITOS.DTLANC;
      voDESD.INSERIR;
      vfTOTALCREDITOESTORNADO            := vfTOTALCREDITOESTORNADO + LISTACREDITOS.VALOR;
      INSERELOG('FNC_ESTORNARCREDITOBAIXADO', LISTACREDITOS.CODFILIAL, 0, 0, pfNUMTRANSVENDA, vfTOTALCREDITOESTORNADO, LISTACREDITOS.VALOR, 0, 'Estornou: ' ||pfNUMTRANSVENDA || ' - ' || NVL(pfPRESTACAO,''), vfNUMCRED, 0, pfCODIGOROTINA);
    END LOOP;

    IF vfTOTALCREDITOESTORNADO <= 0 THEN
      RAISE_APPLICATION_ERROR(-20016,'NÃO FOI POSSÍVEL LOCALIZAR O CRÉDITO VINCULADO COM A TRANSAÇAO NUMTRANSVENDA.:  ' || pfNUMTRANSVENDA || ' - PREST: ' || NVL(pfPRESTACAO,''));
    END IF;

    IF pbGERARPCPRESTAUTOMATICAMENTE THEN
      voCONTASRECEBER := T_PC_CONTASRECEBER(pfMATRICULAUSUARIO);
      voCONTASRECEBER.BUSCARREGISTRO(pfNUMTRANSVENDA, pfPRESTACAO);

      IF voCONTASRECEBER.DTPAG IS NULL THEN
        RAISE_APPLICATION_ERROR(-20016,'O TITULO QUE ESTA TENTANDO ESTORNAR ESTA EM ABERTO.');
      END IF;

      -- GERA O ESTORNO E TITULO EM ABERTO
      voCONTASRECEBER.ESTORNAR;
    END IF;

    INSERELOG('FNC_ESTORNARCREDITOBAIXADO', '99', 0, 0, pfNUMTRANSVENDA, 0, 0, 0, 'Fim', vfNUMCRED, 0, pfCODIGOROTINA);

    RETURN vfTOTALCREDITOESTORNADO;
   EXCEPTION WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20016,
                             CHR(13) ||
                             'NAO FOI POSSIVEL FAZER O ESTORNO DE CREDITO BAIXADO!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
  END FNC_ESTORNARCREDITOBAIXADO;

  ----------------------------------------------------------------------------------------
  /*
  3. "FNC_TOTALCREDITODISPONIVEL"
  FUNÇÃO RETORNA O TOTAL DE CREDITO DISPONIVEL PARA BAIXA. QUANDO O NUMPED=0 CONSULTA DOS OS CREDITOS, SENÃO APENAS PARA O NUMERO DE PEDIDO INFORMADO.
  */
  FUNCTION FNC_TOTALCREDITODISPONIVEL(psFILIAL           IN VARCHAR2,
                                      pfCODCLI           IN NUMBER,
                                      pfNUMPED           IN NUMBER DEFAULT 0
                                     )
  RETURN NUMBER IS
    vfTOTALCREDITO NUMBER(14,2);
  BEGIN
    --VALIDANDO PARAMETROS DE ENTRADA!
    IF ((TRIM(psFILIAL) = '') OR (psFILIAL IS NULL)) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UMA FILIAL');
    END IF;

    IF (pfCODCLI <= 0) OR (pfCODCLI IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO PARA O CLIENTE');
    END IF;

    SELECT NVL(SUM(C.VALOR),0)
    INTO vfTOTALCREDITO
    FROM PCCRECLI C
    WHERE C.CODCLI =  pfCODCLI
    AND   C.DTDESCONTO IS NULL
    AND   C.DTESTORNO IS NULL
    AND   C.SITUACAO IS NULL
    AND   ((PARAMFILIAL.OBTERCOMOVARCHAR2('USACREDCLITODASFILIAIS') = 'S') OR (C.CODFILIAL = psFILIAL))
    AND   ((C.NUMPED = NVL(pfNUMPED,0)) OR ( 0 = NVL(pfNUMPED,0)));

    RETURN vfTOTALCREDITO;
  END FNC_TOTALCREDITODISPONIVEL;

  ----------------------------------------------------------------------------------------
  /*
  4. "FNC_BAIXAR1CREDITONTITULOS"
  PERMITE BAIXA UM CREDITO COM VÁRIOS TITULOS. PARA CADA TITULO PODE SER FEITO BAIXA PARCIAL.
  */
  FUNCTION FNC_BAIXAR1CREDITONTITULOS(pfCODIGOCREDITO           IN NUMBER,
                                      poLISTA_PC_CONTASRECEBER  IN LISTA_PC_CONTASRECEBER,
                                      pfCODIGOROTINA            IN NUMBER,
                                      pfMATRICULAUSUARIO        IN NUMBER
                                      )
  RETURN BOOLEAN IS
    voCREDITOCLIENTE        T_PC_CREDITOCLIENTE;
    voCREDITOCLIENTEAUX     T_PC_CREDITOCLIENTE;
    voCONTASRECEBER         T_PC_CONTASRECEBER;
    voCONTASRECEBERAUX      T_PC_CONTASRECEBER;
    vfNUMCRED               NUMBER(10);
    vfVALORCREDITO          NUMBER(14,2);
    voDESDCREDITO           T_PC_DESDCREDITOCLIENTE;
    voDESDCONTASRECEBER     T_PC_DESDCONTASRECEBER;
    vbBAIXAPARCIAL          BOOLEAN;
    vfTOTALVALORAPROVEITADO NUMBER(14,2);
    voHISTORICOCREDITO      VARCHAR2(100);
  BEGIN
    --VALIDANDO OS PARAMETROS DE ENTRADA!
    IF (pfCODIGOCREDITO <= 0) OR (pfCODIGOCREDITO IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO DO CREDITO');
    END IF;

    IF (poLISTA_PC_CONTASRECEBER IS NULL) OR (poLISTA_PC_CONTASRECEBER.COUNT <= 0) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR OS TITULOS QUE DEVERÃO SER BAIXADOS COM O CREDITO');
    END IF;
    --OBTENDO O "NUMCRED" CODIGO IDENTIFICADOR PARA RELACIONAMENTO DE REGISTROS NA BAIXA
    IF NVL(voCREDITOCLIENTE.NUMCRED,0) > 0 THEN
     vfNUMCRED:= voCREDITOCLIENTE.NUMCRED;
    ELSE
     SELECT DFSEQ_PCCRECLI_NUMCRED.NEXTVAL INTO vfNUMCRED FROM DUAL;
    END IF;
    --BUSCANDO O CREDITO INFORMADO
    voCREDITOCLIENTE         := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    voCREDITOCLIENTE.BUSCARCREDITO(pfCODIGOCREDITO);
    voCREDITOCLIENTE.NUMCRED := vfNUMCRED;
    voHISTORICOCREDITO       := voCREDITOCLIENTE.HISTORICO;

    IF NOT (voCREDITOCLIENTE.DTESTORNO IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'O CREDITO N. '|| pfCODIGOCREDITO ||' INFORMADO NÃO PODE SER UTILIZADO PORQUE O MESMO ENCONTRA-SE ESTORNADO');
    END IF;

    IF NOT (voCREDITOCLIENTE.DTDESCONTO IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'O CREDITO N. '|| pfCODIGOCREDITO ||' INFORMADO NÃO PODE SER UTILIZADO PORQUE O MESMO ENCONTRA-SE BAIXADO');
    END IF;
    --VARIAVEL DE CONTROLE DO CREDITO APROVEITADO
    vfVALORCREDITO := voCREDITOCLIENTE.VALOR;
    --CRIANDO UM OBJETO DE REFERENCIA AO ORIGINAL PARA FAZER AS PERSISTENCIAS NO BANCO.
    voCREDITOCLIENTEAUX := voCREDITOCLIENTE;
    --CRIANDO OBJETO DE DESDOBRAMENTO DE CREDITO
    voDESDCREDITO := T_PC_DESDCREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    voDESDCREDITO.CODIGOORIG:= voCREDITOCLIENTE.CODIGO;
    --CRIANDO OBJETO DE DESDOBRAMENTO DE TITULO
    voDESDCONTASRECEBER     := T_PC_DESDCONTASRECEBER(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    --INICIALIZANDO VARIAVEIS
    vfTOTALVALORAPROVEITADO := 0;

    INSERELOG('FNC_BAIXAR1CREDITONTITULOS', '99', 0, 0, 0, 0, 0, 0, 'Iniciou CodigoCredito: '||pfCODIGOCREDITO, 0, 0, pfCODIGOROTINA);

    FOR i IN 1 .. poLISTA_PC_CONTASRECEBER.COUNT
    LOOP
      voCONTASRECEBER := T_PC_CONTASRECEBER(1);
      voCONTASRECEBER := poLISTA_PC_CONTASRECEBER(i);
      -- ACUMULANDO O TOTAL APROVEITADO, PARA VER SE O FINAL O VALOR TOTAL APROVEITADO NÃO PODE SER MAIOR QUE O CREDITO!
      vfTOTALVALORAPROVEITADO := vfTOTALVALORAPROVEITADO + voCONTASRECEBER.VALORAPROVEITADOCREDITO;
      --VALIDACOES DOS PARAMETROS DE ENTRADA
      IF (voCONTASRECEBER.NUMTRANSVENDA <= 0) OR (voCONTASRECEBER.NUMTRANSVENDA IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O NUMERO DE TRANSACAO DE VENDA DO TITULO');
      END IF;

      IF (TRIM(voCONTASRECEBER.PREST) = '') OR (voCONTASRECEBER.PREST IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR A PRESTACAO DO TITULO');
      END IF;

      IF (voCONTASRECEBER.VALORAPROVEITADOCREDITO <= 0) OR (voCONTASRECEBER.VALORAPROVEITADOCREDITO IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O VALOR APROVEITADO PARA BAIXA.');
      END IF;

      IF (voCONTASRECEBER.VALORAPROVEITADOCREDITO > voCONTASRECEBER.VALOR) THEN
        RAISE_APPLICATION_ERROR(-20016,'O VALOR APROVEITADO NAO PODE SER MAIOR QUE O VALOR DO TITULO.');
      END IF;
      --1. BAIXA TOTAL. VALOR DO TITULO = VALOR APROVEITADO = VALOR DO CREDITO
      IF ((voCONTASRECEBER.VALOR = voCONTASRECEBER.VALORAPROVEITADOCREDITO) AND
          (vfVALORCREDITO = voCONTASRECEBER.VALORAPROVEITADOCREDITO)) THEN
        --BAIXA NO CONTAS A RECEBER
        voCONTASRECEBER.VPAGO := voCONTASRECEBER.VALOR;
        voCONTASRECEBER.BAIXARCOMCREDITO;
        --BAIXA O CREDITO
        voCREDITOCLIENTE.CODFILIALDESC     := voCONTASRECEBER.CODFILIAL;
        voCREDITOCLIENTE.NUMNOTADESC       := voCONTASRECEBER.DUPLIC;
        voCREDITOCLIENTE.NUMTRANSVENDADESC := voCONTASRECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTE.PRESTRESTCLI      := voCONTASRECEBER.PREST;
        voCREDITOCLIENTE.CODFUNCCX         := voCONTASRECEBER.CODFUNCCHECKOUT;
        voCREDITOCLIENTE.BAIXAR;
        vbBAIXAPARCIAL := FALSE;
        INSERELOG('FNC_BAIXAR1CREDITONTITULOS', '99', 0, 0, voCONTASRECEBER.NUMTRANSVENDA, 0, voCONTASRECEBER.VALOR, voCONTASRECEBER.VPAGO, 'BaixaTotal: '||voCONTASRECEBER.NUMTRANSVENDA || ' - ' ||voCONTASRECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
      --2. BAIXA PARCIAL. VALOR DO TITULO = VALOR APROVEITADO <> VALOR DO CREDITO
      --EXEMPLO: CREDITO DE $1000 - 1 TITULO DE $600 E OUTRO DE $300 -> BAIXAS OS TITLOS COMO "CRED", DESDOBRA O CREDITO DE $1000, GERA 2 BAIXADOS ($600 E $200) E EM ABERTO DE $100
      ELSIF ((voCONTASRECEBER.VALOR = voCONTASRECEBER.VALORAPROVEITADOCREDITO) AND
             (vfVALORCREDITO <> voCONTASRECEBER.VALORAPROVEITADOCREDITO)) THEN
        --BAIXA NO CONTAS A RECEBER
        voCONTASRECEBER.VPAGO := voCONTASRECEBER.VALOR;
        voCONTASRECEBER.BAIXARCOMCREDITO;
        --INSERIR UM CREDITO BAIXADO COM O VALOR APROVEITADO
        voCREDITOCLIENTEAUX.CODIGO            := voCREDITOCLIENTEAUX.PROXIMOCODIGOCREDITO;
        voCREDITOCLIENTEAUX.HISTORICO         := SUBSTR(voHISTORICOCREDITO || '-' || 'BX NF.: '|| voCONTASRECEBER.DUPLIC || ' - NUMTRANSVENDA.:  ' ||voCONTASRECEBER.NUMTRANSVENDA, 1, 100);
        voCREDITOCLIENTEAUX.DTESTORNO         := NULL;
        voCREDITOCLIENTEAUX.DTDESCONTO        := TRUNC(SYSDATE);
        voCREDITOCLIENTEAUX.VALOR             := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCREDITOCLIENTEAUX.NUMNOTADESC       := voCONTASRECEBER.DUPLIC;
        voCREDITOCLIENTEAUX.NUMTRANSVENDADESC := voCONTASRECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTEAUX.PRESTRESTCLI      := voCONTASRECEBER.PREST;
        voCREDITOCLIENTEAUX.CODFUNCCX         := voCONTASRECEBER.CODFUNCCHECKOUT;
        voCREDITOCLIENTEAUX.CODPLPAG          := voCREDITOCLIENTE.CODPLPAG;
        voCREDITOCLIENTEAUX.DTLANC            := voCREDITOCLIENTE.DTLANC;
        voCREDITOCLIENTEAUX.INSERIR;
        --HISTORICO DE DESDOBRAMENTO
        voDESDCREDITO.CODIGODEST              := voCREDITOCLIENTEAUX.CODIGO;
        voDESDCREDITO.DTLANC                  := voCREDITOCLIENTE.DTLANC;
        voDESDCREDITO.INSERIR;

        vbBAIXAPARCIAL := TRUE;
        INSERELOG('FNC_BAIXAR1CREDITONTITULOS', '99', 0, 0, voCONTASRECEBER.NUMTRANSVENDA, 0, voCONTASRECEBER.VALOR, voCONTASRECEBER.VPAGO, 'Baixa Parcial: '||voCONTASRECEBER.NUMTRANSVENDA || ' - ' ||voCONTASRECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
      --3. BAIXA PARCIAL. VALOR DO TITULO <> VALOR APROVEITADO <> VALOR DO CREDITO
      --EXEMPLO: TITULO $300 APROVEITADO $200 -> DESD $300, BAIXAR $200CRED, ABERTO $100 e PCCRECLI $200.
      ELSIF ((voCONTASRECEBER.VALOR <> voCONTASRECEBER.VALORAPROVEITADOCREDITO) AND
             (vfVALORCREDITO <> voCONTASRECEBER.VALORAPROVEITADOCREDITO)) THEN
        --BUSCANDO TODAS AS INFORMACOES DO TITULO. POIS NESSA OPCAO É NECESSARIO FAZER A INCLUSÃO DO REGISTRO.
        voCONTASRECEBER.BUSCARREGISTRO(voCONTASRECEBER.NUMTRANSVENDA, voCONTASRECEBER.PREST);
        --PREPARANDO O OBJETO DE DESDOBRAMENTO DE CONTAS A PAGAR... PARA PASSAR APENAS A "PRESTDEST" DEPOIS!
        voDESDCONTASRECEBER.NUMTRANSVENDAORIG := voCONTASRECEBER.NUMTRANSVENDA;
        voDESDCONTASRECEBER.PRESTORIG         := voCONTASRECEBER.PREST;
        voDESDCONTASRECEBER.CODCLIORIG        := voCONTASRECEBER.CODCLI;
        voDESDCONTASRECEBER.NUMTRANSVENDADEST := voCONTASRECEBER.NUMTRANSVENDA;
        voDESDCONTASRECEBER.CODCLIDEST        := voCONTASRECEBER.CODCLI;
        --FAZENDO UM CLONE. POIS UM IRA BAIXAR COMO CREDITO, E O OUTRO IRA LANÇAR A DIFERENÇA EM ABERTO.
        voCONTASRECEBERAUX  := voCONTASRECEBER;
        --DESDOBRANDO O TITULO (COLOCANDO ELE COMO "DESD"
        voCONTASRECEBERAUX.DESDOBRAR;
        --BAIXANDO O TITULO COMO CREDITO
        voCONTASRECEBERAUX.CODCOB       := 'CRED';
        voCONTASRECEBERAUX.PREST        := FNC_GETPROXIMAPREST(voCONTASRECEBER.NUMTRANSVENDA);
        voCONTASRECEBERAUX.VALOR        := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCONTASRECEBERAUX.VALORORIG    := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCONTASRECEBERAUX.VPAGO        := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCONTASRECEBERAUX.DTPAG        := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.DTBAIXA      := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.DTDESD       := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.CODFUNCFECHA := pfMATRICULAUSUARIO;
        voCONTASRECEBERAUX.CODFUNCCXMOT := pfMATRICULAUSUARIO;
        voCONTASRECEBERAUX.INSERIR;
        INSERELOG('FNC_BAIXAR1CREDITONTITULOS', '99', 0, 0, voCONTASRECEBER.NUMTRANSVENDA, 0, voCONTASRECEBER.VALOR, voCONTASRECEBER.VPAGO, 'Baixa Parcial: '||voCONTASRECEBER.NUMTRANSVENDA || ' - ' ||voCONTASRECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
        --GRAVANDO PCDESD
        voDESDCONTASRECEBER.PRESTDEST   := voCONTASRECEBERAUX.PREST;
        voDESDCONTASRECEBER.INSERIR;
        --GERANDO A DIFERENCA EM ABERTO
        voCONTASRECEBERAUX.CODCOB       := voCONTASRECEBER.CODCOB;
        voCONTASRECEBERAUX.PREST        := FNC_GETPROXIMAPREST(voCONTASRECEBER.NUMTRANSVENDA);
        voCONTASRECEBERAUX.VALOR        := (voCONTASRECEBER.VALOR - voCONTASRECEBER.VALORAPROVEITADOCREDITO);
        voCONTASRECEBERAUX.VALORORIG    := (voCONTASRECEBER.VALOR - voCONTASRECEBER.VALORAPROVEITADOCREDITO);
        voCONTASRECEBERAUX.VPAGO        := NULL;
        voCONTASRECEBERAUX.DTPAG        := NULL;
        voCONTASRECEBERAUX.DTBAIXA      := NULL;
        voCONTASRECEBERAUX.DTDESD       := NULL;
        voCONTASRECEBERAUX.CODFUNCFECHA := NULL;
        voCONTASRECEBERAUX.CODFUNCCXMOT := NULL;
        voCONTASRECEBERAUX.INSERIR;
        --GRAVANDO PCDESD
        voDESDCONTASRECEBER.PRESTDEST   := voCONTASRECEBERAUX.PREST;
        voDESDCONTASRECEBER.INSERIR;
        --INSERIR UM CREDITO BAIXADO COM O VALOR APROVEITADO
        voCREDITOCLIENTEAUX.CODIGO            := voCREDITOCLIENTEAUX.PROXIMOCODIGOCREDITO;
        voCREDITOCLIENTEAUX.HISTORICO         := SUBSTR(voHISTORICOCREDITO || '-' || 'BX PARC NF.: '|| voCONTASRECEBER.DUPLIC || ' - NUMTRANSVENDA.:  ' ||voCONTASRECEBER.NUMTRANSVENDA, 1, 100);
        voCREDITOCLIENTEAUX.DTESTORNO         := NULL;
        voCREDITOCLIENTEAUX.DTDESCONTO        := TRUNC(SYSDATE);
        voCREDITOCLIENTEAUX.VALOR             := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCREDITOCLIENTEAUX.NUMNOTADESC       := voCONTASRECEBER.DUPLIC;
        voCREDITOCLIENTEAUX.NUMTRANSVENDADESC := voCONTASRECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTEAUX.PRESTRESTCLI      := voCONTASRECEBER.PREST;
        voCREDITOCLIENTEAUX.CODFUNCCX         := voCONTASRECEBER.CODFUNCCHECKOUT;
        voCREDITOCLIENTEAUX.CODPLPAG          := voCREDITOCLIENTE.CODPLPAG;
        voCREDITOCLIENTEAUX.INSERIR;
        --HISTORICO DE DESDOBRAMENTO
        voDESDCREDITO.CODIGODEST              := voCREDITOCLIENTEAUX.CODIGO;
        voDESDCREDITO.INSERIR;
        vbBAIXAPARCIAL := FALSE;
      --4. BAIXA PARCIAL. VALOR DO TITULO <> VALOR APROVEITADO <> VALOR DO CREDITO
      --EXEMPLO: TITULO $1500 APROVEITADO $750 CREDITO $750 -> DESD $1500, BAIXAR $750CRED, ABERTO $750 e PCCRECLI $750 BAIXADO.
      ELSIF ((voCONTASRECEBER.VALOR <> voCONTASRECEBER.VALORAPROVEITADOCREDITO) AND
             (vfVALORCREDITO = voCONTASRECEBER.VALORAPROVEITADOCREDITO)) THEN
        --BUSCANDO TODAS AS INFORMACOES DO TITULO. POIS NESSA OPCAO É NECESSARIO FAZER A INCLUSÃO DO REGISTRO.
        voCONTASRECEBER.BUSCARREGISTRO(voCONTASRECEBER.NUMTRANSVENDA, voCONTASRECEBER.PREST);
        --PREPARANDO O OBJETO DE DESDOBRAMENTO DE CONTAS A PAGAR... PARA PASSAR APENAS A "PRESTDEST" DEPOIS!
        voDESDCONTASRECEBER.NUMTRANSVENDAORIG := voCONTASRECEBER.NUMTRANSVENDA;
        voDESDCONTASRECEBER.PRESTORIG         := voCONTASRECEBER.PREST;
        voDESDCONTASRECEBER.CODCLIORIG        := voCONTASRECEBER.CODCLI;
        voDESDCONTASRECEBER.NUMTRANSVENDADEST := voCONTASRECEBER.NUMTRANSVENDA;
        voDESDCONTASRECEBER.CODCLIDEST        := voCONTASRECEBER.CODCLI;
        --FAZENDO UM CLONE. POIS UM IRA BAIXAR COMO CREDITO, E O OUTRO IRA LANÇAR A DIFERENÇA EM ABERTO.
        voCONTASRECEBERAUX  := voCONTASRECEBER;
        --DESDOBRANDO O TITULO (COLOCANDO ELE COMO "DESD"
        voCONTASRECEBERAUX.DESDOBRAR;
        --BAIXANDO O TITULO COMO CREDITO
        voCONTASRECEBERAUX.CODCOB       := 'CRED';
        voCONTASRECEBERAUX.PREST        := FNC_GETPROXIMAPREST(voCONTASRECEBER.NUMTRANSVENDA);
        voCONTASRECEBERAUX.VALOR        := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCONTASRECEBERAUX.VALORORIG    := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCONTASRECEBERAUX.VPAGO        := voCONTASRECEBER.VALORAPROVEITADOCREDITO;
        voCONTASRECEBERAUX.DTPAG        := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.DTBAIXA      := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.DTDESD       := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.CODFUNCFECHA := pfMATRICULAUSUARIO;
        voCONTASRECEBERAUX.CODFUNCCXMOT := pfMATRICULAUSUARIO;
        voCONTASRECEBERAUX.INSERIR;
        INSERELOG('FNC_BAIXAR1CREDITONTITULOS', '99', 0, 0, voCONTASRECEBER.NUMTRANSVENDA, 0, voCONTASRECEBER.VALOR, voCONTASRECEBER.VPAGO, 'Baixa Parcial: '||voCONTASRECEBER.NUMTRANSVENDA || ' - ' ||voCONTASRECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
        --GRAVANDO PCDESD
        voDESDCONTASRECEBER.PRESTDEST   := voCONTASRECEBERAUX.PREST;
        voDESDCONTASRECEBER.INSERIR;
        --GERANDO A DIFERENCA EM ABERTO
        voCONTASRECEBERAUX.CODCOB       := voCONTASRECEBER.CODCOB;
        voCONTASRECEBERAUX.PREST        := FNC_GETPROXIMAPREST(voCONTASRECEBER.NUMTRANSVENDA);
        voCONTASRECEBERAUX.VALOR        := (voCONTASRECEBER.VALOR - voCONTASRECEBER.VALORAPROVEITADOCREDITO);
        voCONTASRECEBERAUX.VALORORIG    := (voCONTASRECEBER.VALOR - voCONTASRECEBER.VALORAPROVEITADOCREDITO);
        voCONTASRECEBERAUX.VPAGO        := NULL;
        voCONTASRECEBERAUX.DTPAG        := NULL;
        voCONTASRECEBERAUX.DTBAIXA      := NULL;
        voCONTASRECEBERAUX.DTDESD       := NULL;
        voCONTASRECEBERAUX.CODFUNCFECHA := NULL;
        voCONTASRECEBERAUX.CODFUNCCXMOT := NULL;
        voCONTASRECEBERAUX.INSERIR;
        --GRAVANDO PCDESD
        voDESDCONTASRECEBER.PRESTDEST   := voCONTASRECEBERAUX.PREST;
        voDESDCONTASRECEBER.INSERIR;
        --BAIXA O CREDITO
        voCREDITOCLIENTE.CODFILIALDESC     := voCONTASRECEBER.CODFILIAL;
        voCREDITOCLIENTE.NUMNOTADESC       := voCONTASRECEBER.DUPLIC;
        voCREDITOCLIENTE.NUMTRANSVENDADESC := voCONTASRECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTE.PRESTRESTCLI      := voCONTASRECEBER.PREST;
        voCREDITOCLIENTE.DTLANC            := voCREDITOCLIENTE.DTLANC;

        voCREDITOCLIENTE.BAIXAR;
        vbBAIXAPARCIAL := FALSE;
      END IF;
      --DECREMENTANDO O VALOR DO CREDITO, PARA SABER O QUANTO AINDA TEM PARA APROVEITAR DO CREDITO.
      vfVALORCREDITO := vfVALORCREDITO - voCONTASRECEBER.VALORAPROVEITADOCREDITO;
    END LOOP;

    --O TOTAL APROVEITADO (TITULOS) NAO PODE SER MAIOR QUE O CREDITO.
    IF vfTOTALVALORAPROVEITADO > voCREDITOCLIENTE.VALOR THEN
      RAISE_APPLICATION_ERROR(-20016,'O VALOR APROVEITADO TOTAL NAO PODE SER MAIOR QUE O VALOR DO CREDITO.' ||CHR(13) ||
                              'VALOR DO CREDITO: '|| TO_CHAR(voCREDITOCLIENTE.VALOR, '9999999999.99') || CHR(13) ||
                              'VALOR TOTAL APROVEITADO: '|| TO_CHAR(vfTOTALVALORAPROVEITADO, '9999999999.99'));
    END IF;
    --GERAR A SOBRA DO CREDITO EM ABERTO.
    IF (vfVALORCREDITO > 0) THEN
      voCREDITOCLIENTEAUX.LIMPAR;
      voCREDITOCLIENTEAUX            := voCREDITOCLIENTE;
      voCREDITOCLIENTEAUX.CODIGO     := voCREDITOCLIENTEAUX.PROXIMOCODIGOCREDITO;
      voCREDITOCLIENTEAUX.VALOR      := vfVALORCREDITO;
      voCREDITOCLIENTEAUX.CODPLPAG   := voCREDITOCLIENTEAUX.CODPLPAG;
      voCREDITOCLIENTEAUX.DTLANC     := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTEAUX.INSERIR;
      --HISTORICO DE DESDOBRAMENTO
      voDESDCREDITO.CODIGODEST       := voCREDITOCLIENTEAUX.CODIGO;
      voDESDCREDITO.DTLANC           := voCREDITOCLIENTE.DTLANC;
      voDESDCREDITO.INSERIR;
    END IF;
    --SE HOUVE BAIXA PARCIAL. FAZER O ESTORNO DO CREDITO ORIGINAL.
    IF (vbBAIXAPARCIAL) THEN
      voCREDITOCLIENTE.HISTORICO     := SUBSTR(voHISTORICOCREDITO || '-' || 'DESD BX NF.: '|| voCONTASRECEBER.DUPLIC || ' - NUMTRANSVENDA.:  ' ||voCONTASRECEBER.NUMTRANSVENDA, 1, 100);
      voCREDITOCLIENTE.DTLANC        := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTE.ESTORNARTOTAL;
    END IF;

    INSERELOG('FNC_BAIXAR1CREDITONTITULOS', '99', 0, 0, 0, 0, 0, vfVALORCREDITO, 'Fim CodigoCredito: '||pfCODIGOCREDITO, 0, 0, pfCODIGOROTINA);

    RETURN TRUE;
   EXCEPTION WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20016,
                             CHR(13) ||
                             'NAO FOI POSSIVEL REALIZAR O PROCESSO BAIXAR 1 CREDITO COM VARIOS TITULOS!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
     RETURN FALSE;
  END FNC_BAIXAR1CREDITONTITULOS;

  ----------------------------------------------------------------------------------------
  /*
  5. "FNC_BAIXAR1TITULONCREDITOS"
  PERMITE BAIXA UM TITULO COM VÁRIOS CREDITOS.
  */
  FUNCTION FNC_BAIXAR1TITULONCREDITOS(poCONTARECEBER            IN OUT T_PC_CONTASRECEBER,
                                      poLISTA_PC_CREDITOCLIENTE IN LISTA_PC_CREDITOCLIENTE,
                                      pfCODIGOROTINA            IN NUMBER,
                                      pfMATRICULAUSUARIO        IN NUMBER)
  RETURN BOOLEAN IS
    vfVALORCONTASRECEBER    NUMBER(14,2);
    voCREDITOCLIENTE        T_PC_CREDITOCLIENTE;
    voCREDITOCLIENTEAUX     T_PC_CREDITOCLIENTE;
    voCONTASRECEBERAUX      T_PC_CONTASRECEBER;
    vfNUMCRED               NUMBER(10);
    voDESDCONTASRECEBER     T_PC_DESDCONTASRECEBER;
    voDESDCREDITO           T_PC_DESDCREDITOCLIENTE;
    vbBAIXAPARCIAL          BOOLEAN;
    voHISTORICOCREDITO      VARCHAR2(100);
  BEGIN
    --VALIDACOES DOS PARAMETROS DE ENTRADA
    IF (poCONTARECEBER.NUMTRANSVENDA <= 0) OR (poCONTARECEBER.NUMTRANSVENDA IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O NUMERO DE TRANSACAO DE VENDA DO TITULO');
    END IF;

    IF (TRIM(poCONTARECEBER.PREST) = '') OR (poCONTARECEBER.PREST IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR A PRESTACAO DO TITULO');
    END IF;

    IF (poLISTA_PC_CREDITOCLIENTE IS NULL) OR (poLISTA_PC_CREDITOCLIENTE.COUNT <= 0) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR OS CREDITOS QUE DEVERAO SER BAIXADOS O TITULO');
    END IF;
    --BUSCANDO TODAS AS INFORMACOES DO TITULO. POIS NESSA OPCAO É NECESSARIO FAZER A INCLUSÃO DO REGISTRO.
    poCONTARECEBER.BUSCARREGISTRO(poCONTARECEBER.NUMTRANSVENDA, poCONTARECEBER.PREST);

    IF NOT (poCONTARECEBER.DTPAG IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'O TITULO INFORMADO JÁ ESTA BAIXADO');
    END IF;

    --INICIALIZANDO VARIAVEIS
    vfVALORCONTASRECEBER                  := poCONTARECEBER.VALOR;
    --FAZENDO UM CLONE. POIS UM IRA BAIXAR COMO CREDITO, E O OUTRO IRA LANÇAR A DIFERENÇA EM ABERTO.
    voCONTASRECEBERAUX                    := T_PC_CONTASRECEBER(pfMATRICULAUSUARIO);
    voCONTASRECEBERAUX                    := poCONTARECEBER;
    --CRIANDO OBJETO DE DESDOBRAMENTO DE CREDITO
    voDESDCREDITO                         := T_PC_DESDCREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    --CRIANDO OBJETO DE DESDOBRAMENTO DE TITULO
    voDESDCONTASRECEBER                   := T_PC_DESDCONTASRECEBER(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    voDESDCONTASRECEBER.NUMTRANSVENDAORIG := poCONTARECEBER.NUMTRANSVENDA;
    voDESDCONTASRECEBER.PRESTORIG         := poCONTARECEBER.PREST;
    voDESDCONTASRECEBER.CODCLIORIG        := poCONTARECEBER.CODCLI;
    voDESDCONTASRECEBER.NUMTRANSVENDADEST := poCONTARECEBER.NUMTRANSVENDA;
    voDESDCONTASRECEBER.CODCLIDEST        := poCONTARECEBER.CODCLI;
    --OBTENDO O "NUMCRED" CODIGO IDENTIFICADOR PARA RELACIONAMENTO DE REGISTROS NA BAIXA
    IF NVL(voCREDITOCLIENTE.NUMCRED,0) > 0 THEN
     vfNUMCRED:= voCREDITOCLIENTE.NUMCRED;
    ELSE
     SELECT DFSEQ_PCCRECLI_NUMCRED.NEXTVAL INTO vfNUMCRED FROM DUAL;
    END IF;

    INSERELOG('FNC_BAIXAR1TITULONCREDITOS', '99', 0, 0, 0, 0, 0, 0, 'Inicio', vfNUMCRED, 0, pfCODIGOROTINA);
    --PERCORRENDO TODOS OS CREDITOS
    FOR i IN 1 .. poLISTA_PC_CREDITOCLIENTE.COUNT
    LOOP
      --ATRIBUINDO A LISTA AO OBJETO
      voCREDITOCLIENTE    := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voCREDITOCLIENTE    := poLISTA_PC_CREDITOCLIENTE(i);
      voCREDITOCLIENTE.BUSCARCREDITO(poLISTA_PC_CREDITOCLIENTE(i).CODIGO);
      voCREDITOCLIENTE.NUMCRED := vfNUMCRED;
      voCREDITOCLIENTEAUX := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voCREDITOCLIENTEAUX := voCREDITOCLIENTE;
      voHISTORICOCREDITO  := voCREDITOCLIENTE.HISTORICO;

      IF NOT (voCREDITOCLIENTEAUX.DTESTORNO IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'O CREDITO N. '|| voCREDITOCLIENTEAUX.CODIGO ||' INFORMADO NÃO PODE SER UTILIZADO PORQUE O MESMO ENCONTRA-SE ESTORNADO');
      END IF;

      IF NOT (voCREDITOCLIENTEAUX.DTDESCONTO IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'O CREDITO N. '|| voCREDITOCLIENTEAUX.CODIGO ||' INFORMADO NÃO PODE SER UTILIZADO PORQUE O MESMO ENCONTRA-SE BAIXADO');
      END IF;

      voDESDCREDITO.CODIGOORIG :=  voCREDITOCLIENTE.CODIGO;
      --VALOR DO TITULO = CREDITO.
      IF (vfVALORCONTASRECEBER = voCREDITOCLIENTE.VALOR) THEN
        --BAIXAR O CREDITO
        voCREDITOCLIENTE.CODFILIALDESC     := poCONTARECEBER.CODFILIAL;
        voCREDITOCLIENTE.NUMNOTADESC       := poCONTARECEBER.DUPLIC;
        voCREDITOCLIENTE.NUMTRANSVENDADESC := poCONTARECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTE.PRESTRESTCLI      := poCONTARECEBER.PREST;
        voCREDITOCLIENTE.DTLANC            := poLISTA_PC_CREDITOCLIENTE(I).DTLANC;
        voCREDITOCLIENTE.BAIXAR;
        --BAIXAR O TITULO
        poCONTARECEBER.VPAGO               := poCONTARECEBER.VALOR;
        poCONTARECEBER.BAIXARCOMCREDITO;

        vbBAIXAPARCIAL                     := FALSE;
        INSERELOG('FNC_BAIXAR1TITULONCREDITOS', '99', 0, 0, poCONTARECEBER.NUMTRANSVENDA, 0, poCONTARECEBER.VALOR, poCONTARECEBER.VPAGO, 'BaixaTotal: '||poCONTARECEBER.NUMTRANSVENDA || ' - ' ||poCONTARECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
        EXIT;
      --VALOR DO TITULO MAIOR QUE O CREDITO -> $1000 DE TITULO, SENDO $800 DE CREDITO.
      ELSIF (vfVALORCONTASRECEBER > voCREDITOCLIENTE.VALOR) THEN
        --INSERIR A DIFERENÇA DO TITULO COMO CRED BAIXADO (O DESDOBRAMENTO SERA NO FINAL)
        voCONTASRECEBERAUX.CODCOB       := 'CRED';
        voCONTASRECEBERAUX.PREST        := FNC_GETPROXIMAPREST(poCONTARECEBER.NUMTRANSVENDA);
        voCONTASRECEBERAUX.VALOR        := voCREDITOCLIENTE.VALOR;
        voCONTASRECEBERAUX.VALORORIG    := voCREDITOCLIENTE.VALOR;
        voCONTASRECEBERAUX.VPAGO        := voCREDITOCLIENTE.VALOR;
        voCONTASRECEBERAUX.DTPAG        := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.DTBAIXA      := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.DTDESD       := TRUNC(SYSDATE);
        voCONTASRECEBERAUX.CODFUNCFECHA := pfMATRICULAUSUARIO;
        voCONTASRECEBERAUX.CODFUNCCXMOT := pfMATRICULAUSUARIO;
        voCONTASRECEBERAUX.INSERIR;
        INSERELOG('FNC_BAIXAR1TITULONCREDITOS', '99', 0, 0, poCONTARECEBER.NUMTRANSVENDA, 0, poCONTARECEBER.VALOR, poCONTARECEBER.VPAGO, 'BaixaParcial: '||poCONTARECEBER.NUMTRANSVENDA || ' - ' ||poCONTARECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
        --GRAVANDO PCDESD
        voDESDCONTASRECEBER.PRESTDEST   := voCONTASRECEBERAUX.PREST;
        voDESDCONTASRECEBER.INSERIR;
        --BAIXAR O CREDITO
        voCREDITOCLIENTE.CODFILIALDESC     := poCONTARECEBER.CODFILIAL;
        voCREDITOCLIENTE.NUMNOTADESC       := poCONTARECEBER.DUPLIC;
        voCREDITOCLIENTE.NUMTRANSVENDADESC := poCONTARECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTE.PRESTRESTCLI      := poCONTARECEBER.PREST;
        voCREDITOCLIENTE.DTLANC            := poLISTA_PC_CREDITOCLIENTE(I).DTLANC;
        voCREDITOCLIENTE.BAIXAR;

        vbBAIXAPARCIAL                     := TRUE;
      --VALOR DO TITULO OU O QUE SOBROU MENOR QUE O CREDITO ->  $700 TITULO, $800 CREDITO
      ELSIF (vfVALORCONTASRECEBER < voCREDITOCLIENTE.VALOR) THEN
        --DESDOBRAR O CREDITO
        voCREDITOCLIENTEAUX.HISTORICO          := SUBSTR(voHISTORICOCREDITO || '-' || 'DESD BX NF.: '|| poCONTARECEBER.DUPLIC || ' - NUMTRANSVENDA.:  ' ||poCONTARECEBER.NUMTRANSVENDA, 1, 100);
        voCREDITOCLIENTEAUX.ESTORNARTOTAL;
        --BAIXAR O CREDITO NO VALOR DO CONTAS A RECEBER
        voCREDITOCLIENTEAUX.CODIGO             := voCREDITOCLIENTEAUX.PROXIMOCODIGOCREDITO;
        voCREDITOCLIENTEAUX.DTESTORNO          := NULL;
        voCREDITOCLIENTEAUX.CODFILIALDESC      := poCONTARECEBER.CODFILIAL;
        voCREDITOCLIENTEAUX.HISTORICO          := SUBSTR(voHISTORICOCREDITO || '-' || 'DESD BX NF.: '|| poCONTARECEBER.DUPLIC || ' - NUMTRANSVENDA.:  ' ||poCONTARECEBER.NUMTRANSVENDA, 1, 100);
        voCREDITOCLIENTEAUX.NUMTRANSVENDADESC  := poCONTARECEBER.NUMTRANSVENDA;
        voCREDITOCLIENTEAUX.NUMNOTADESC        := poCONTARECEBER.DUPLIC;
        voCREDITOCLIENTEAUX.VALOR              := vfVALORCONTASRECEBER;
        voCREDITOCLIENTEAUX.DTDESCONTO         := TRUNC(SYSDATE);
        voCREDITOCLIENTEAUX.PRESTRESTCLI       := poCONTARECEBER.PREST;
        voCREDITOCLIENTEAUX.CODPLPAG           := voCREDITOCLIENTE.CODPLPAG;
        voCREDITOCLIENTE.DTLANC                := voCREDITOCLIENTE.DTLANC;
        voCREDITOCLIENTEAUX.INSERIR;
        --HISTORICO DE DESDOBRAMENTO
        voDESDCREDITO.CODIGODEST               := voCREDITOCLIENTEAUX.CODIGO;
        voDESDCREDITO.DTLANC                   := voCREDITOCLIENTE.DTLANC;
        voDESDCREDITO.INSERIR;
        --LANCAR A DIFERENCA EM ABERTO
        voCREDITOCLIENTEAUX.CODIGO             := voCREDITOCLIENTEAUX.PROXIMOCODIGOCREDITO;
        voCREDITOCLIENTEAUX.DTESTORNO          := NULL;
        voCREDITOCLIENTEAUX.CODFILIALDESC      := NULL;
        voCREDITOCLIENTEAUX.DTDESCONTO         := NULL;
        voCREDITOCLIENTEAUX.HISTORICO          := SUBSTR(voHISTORICOCREDITO || '-' || 'DIF BX NF.: '|| poCONTARECEBER.DUPLIC || ' - NUMTRANSVENDA.:  ' ||poCONTARECEBER.NUMTRANSVENDA, 1, 100);
        voCREDITOCLIENTEAUX.NUMTRANSVENDADESC  := NULL;
        voCREDITOCLIENTEAUX.NUMNOTADESC        := NULL;
        voCREDITOCLIENTEAUX.VALOR              := voCREDITOCLIENTE.VALOR - vfVALORCONTASRECEBER;
        voCREDITOCLIENTEAUX.CODPLPAG           := voCREDITOCLIENTE.CODPLPAG;
        voCREDITOCLIENTEAUX.DTLANC             := voCREDITOCLIENTE.DTLANC;
        voCREDITOCLIENTEAUX.INSERIR;
        --HISTORICO DE DESDOBRAMENTO
        voDESDCREDITO.CODIGODEST               := voCREDITOCLIENTEAUX.CODIGO;
        voDESDCREDITO.DTLANC                   := voCREDITOCLIENTE.DTLANC;
        voDESDCREDITO.INSERIR;
        --VALIDACAO PARA O QUE FAZER COM O TITULO
        IF vfVALORCONTASRECEBER = poCONTARECEBER.VALOR THEN --BAIXA O TITULO
          poCONTARECEBER.VPAGO               := poCONTARECEBER.VALOR;
          poCONTARECEBER.BAIXARCOMCREDITO;
          vbBAIXAPARCIAL                     := FALSE;
          INSERELOG('FNC_BAIXAR1TITULONCREDITOS', '99', 0, 0, poCONTARECEBER.NUMTRANSVENDA, 0, poCONTARECEBER.VALOR, poCONTARECEBER.VPAGO, 'BaixaTotal: '||poCONTARECEBER.NUMTRANSVENDA || ' - ' ||poCONTARECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
        ELSE --INSERE O TITULO
          voCONTASRECEBERAUX.CODCOBORIG   := poCONTARECEBER.CODCOB;
          voCONTASRECEBERAUX.CODCOB       := 'CRED';
          voCONTASRECEBERAUX.PREST        := FNC_GETPROXIMAPREST(poCONTARECEBER.NUMTRANSVENDA);
          voCONTASRECEBERAUX.VALOR        := vfVALORCONTASRECEBER;
          voCONTASRECEBERAUX.VALORORIG    := vfVALORCONTASRECEBER;
          voCONTASRECEBERAUX.VPAGO        := vfVALORCONTASRECEBER;
          voCONTASRECEBERAUX.DTPAG        := TRUNC(SYSDATE);
          voCONTASRECEBERAUX.DTBAIXA      := TRUNC(SYSDATE);
          voCONTASRECEBERAUX.DTDESD       := TRUNC(SYSDATE);
          voCONTASRECEBERAUX.CODFUNCFECHA := pfMATRICULAUSUARIO;
          voCONTASRECEBERAUX.CODFUNCCXMOT := pfMATRICULAUSUARIO;          
          voCONTASRECEBERAUX.INSERIR;
          --GRAVANDO PCDESD
          voDESDCONTASRECEBER.PRESTDEST   := voCONTASRECEBERAUX.PREST;
          voDESDCONTASRECEBER.INSERIR;

          vbBAIXAPARCIAL                     := TRUE;
          INSERELOG('FNC_BAIXAR1TITULONCREDITOS', '99', 0, 0, poCONTARECEBER.NUMTRANSVENDA, 0, poCONTARECEBER.VALOR, poCONTARECEBER.VPAGO, 'BaixaParcial: '||poCONTARECEBER.NUMTRANSVENDA || ' - ' ||poCONTARECEBER.PREST, vfNUMCRED, 0, pfCODIGOROTINA);
        END IF;
      END IF;

      vfVALORCONTASRECEBER := vfVALORCONTASRECEBER - voCREDITOCLIENTE.VALOR;
    END LOOP;

    INSERELOG('FNC_BAIXAR1TITULONCREDITOS', '99', 0, 0, 0, 0, 0, 0, 'Fim', vfNUMCRED, 0, pfCODIGOROTINA);

    --FIM DA FUNCAO
    IF vbBAIXAPARCIAL THEN
      poCONTARECEBER.DESDOBRAR;

      IF vfVALORCONTASRECEBER > 0 THEN
        poCONTARECEBER.VALOR     := vfVALORCONTASRECEBER;
        poCONTARECEBER.VALORORIG := vfVALORCONTASRECEBER;
        poCONTARECEBER.PREST     := FNC_GETPROXIMAPREST(poCONTARECEBER.NUMTRANSVENDA);
        poCONTARECEBER.INSERIR;
      END IF;
    END IF;
    RETURN TRUE;
  EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20016,
                             CHR(13) ||
                             'NAO FOI POSSIVEL REALIZAR O PROCESSO BAIXAR 1 TITULO COM VARIOS CREDITOS!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
      RETURN FALSE;
  END FNC_BAIXAR1TITULONCREDITOS;

 ----------------------------------------------------------------------------------------
  /*
  6. "FNC_BAIXADECREDITOVAREJO"
  FUNÇÃO CRIADA PARA SER UTILIZADA PELA EQUIPE DO VAREJO QUE POSSUI SUAS PARTICULARIDADES.
  */
  FUNCTION FNC_BAIXADECREDITOVAREJO(pfCODIGOCREDITO           IN NUMBER,
                                    pfVALORBAIXAR             IN NUMBER,
                                    pfNUMPEDECF               IN NUMBER,
                                    psNUMSERIEEQUIP           IN VARCHAR2,
                                    pfNUMCAIXA                IN NUMBER,
                                    pfNUMCUPOM                IN NUMBER,
                                    psHISTORICO               IN VARCHAR2,
                                    pfCODIGOROTINA            IN NUMBER,
                                    pfMATRICULAUSUARIO        IN NUMBER,
                                    psCODIGOFILIALDESCONTO    IN VARCHAR2,
                                    psCODIGOSCREDITOGERADO    IN OUT VARCHAR2
                                    )
  RETURN LISTA_PC_CREDITOCLIENTE IS
    voLISTA LISTA_PC_CREDITOCLIENTE;
    voCREDITOCLIENTE               T_PC_CREDITOCLIENTE;
    voCREDITOCLIENTEESTORNADO      T_PC_CREDITOCLIENTE;
    voCREDITOCLIENTEPARCIALBAIXADO T_PC_CREDITOCLIENTE;
    voCREDITOCLIENTEPARCIALABERTO  T_PC_CREDITOCLIENTE;
    voDESDCREDITO                  T_PC_DESDCREDITOCLIENTE;
    vfNUMCRED                      NUMBER(10);
  BEGIN
    --VALIDACOES DOS PARAMETROS DE ENTRADA
    IF (pfCODIGOCREDITO <= 0) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO DE CREDITO VALIDO!');
    END IF;

    IF (pfVALORBAIXAR <= 0) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O VALOR A SER BAIXADO COM CREDITO!');
    END IF;

    IF (pfNUMPEDECF <= 0) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM NUMERO DE PEDIDO ECF VALIDO!');
    END IF;

    IF (TRIM(psNUMSERIEEQUIP) = '') OR (psNUMSERIEEQUIP IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM NUMERO DE SERIE DE EQUIPAMENTO VALIDO!');
    END IF;

    IF (TRIM(psHISTORICO) = '') OR (psHISTORICO IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O HISTORICO!');
    END IF;

    IF (TRIM(psCODIGOFILIALDESCONTO) = '') OR (psCODIGOFILIALDESCONTO IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR O CODIGO DA FILIAL DE DESCONTO!');
    END IF;
    --BUSCANDO O CREDITO INFORMADO
    voCREDITOCLIENTE := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
    voCREDITOCLIENTE.BUSCARCREDITO(pfCODIGOCREDITO);

    IF (pfVALORBAIXAR > voCREDITOCLIENTE.VALOR)  THEN
      RAISE_APPLICATION_ERROR(-20016,'O VALOR INFORMADO PARA BAIXA É MAIOR QUE O VALOR DO CREDITO!');
    END IF;

    IF NOT (voCREDITOCLIENTE.DTESTORNO IS NULL)  THEN
      RAISE_APPLICATION_ERROR(-20016,'O CREDITO INFORMADO JÁ ENCONTRA-SE ESTORNADO!');
    END IF;

    IF NOT (voCREDITOCLIENTE.DTDESCONTO IS NULL)  THEN
      RAISE_APPLICATION_ERROR(-20016,'O CREDITO INFORMADO JÁ ENCONTRA-SE BAIXADO!');
    END IF;

    IF (voCREDITOCLIENTE.SITUACAO = 'P') THEN
      RAISE_APPLICATION_ERROR(-20016,'O CREDITO INFORMADO ESTA PENDENTE, FAVOR LIBERAR CRÉDITO NA ROTINA 603!');
    END IF;
    --OBTENDO O "NUMCRED" CODIGO IDENTIFICADOR PARA RELACIONAMENTO DE REGISTROS NA BAIXA
    IF NVL(voCREDITOCLIENTE.NUMCRED,0) > 0 THEN
     vfNUMCRED:= voCREDITOCLIENTE.NUMCRED;
    ELSE
     SELECT DFSEQ_PCCRECLI_NUMCRED.NEXTVAL INTO vfNUMCRED FROM DUAL;
    END IF;
    --CRIANDO A LISTA COM OS CREDITOS PARA RETORNO
    voLISTA := LISTA_PC_CREDITOCLIENTE();

    INSERELOG('FNC_BAIXADECREDITOVAREJO', '99', 0, 0, 0, 0, 0, pfVALORBAIXAR, 'Iniciou', vfNUMCRED, 0, pfCODIGOROTINA);
    --INICIANDO PROCESSO DE BAIXA DO CREDITO
    --1. BAIXANDO O CREDITO INTEGRAL
    IF (pfVALORBAIXAR = voCREDITOCLIENTE.VALOR) THEN
      voCREDITOCLIENTE.NUMCRED       := vfNUMCRED;
      voCREDITOCLIENTE.NUMPEDECF     := pfNUMPEDECF;
      voCREDITOCLIENTE.NUMSERIEEQUIP := psNUMSERIEEQUIP;
      voCREDITOCLIENTE.NUMCAIXA      := pfNUMCAIXA;
      voCREDITOCLIENTE.NUMCUPOM      := pfNUMCUPOM;
      voCREDITOCLIENTE.HISTORICO     := psHISTORICO;
      voCREDITOCLIENTE.CODFILIALDESC := psCODIGOFILIALDESCONTO;
      voCREDITOCLIENTE.CODFUNC       := pfMATRICULAUSUARIO;
      voCREDITOCLIENTE.CODROTINA     := pfCODIGOROTINA;
      voCREDITOCLIENTE.CODFUNCCX     := pfMATRICULAUSUARIO;
      voCREDITOCLIENTE.DTLANC        := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTE.BAIXAR;

      INSERELOG('FNC_BAIXADECREDITOVAREJO', '99', 0, 0, 0, 0, voCREDITOCLIENTE.VALOR, pfVALORBAIXAR, 'BaixaTotal', vfNUMCRED, 0, pfCODIGOROTINA);

      voLISTA.EXTEND(1);
      voLISTA(1) := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voLISTA(1) := voCREDITOCLIENTE;
      psCODIGOSCREDITOGERADO := voCREDITOCLIENTE.CODIGO;
    --2. BAIXANDO CREDITO A MENOR
    ELSIF (pfVALORBAIXAR < voCREDITOCLIENTE.VALOR) THEN
      --CRIANDO OBJETO DE DESDOBRAMENTO DE CREDITO
      voDESDCREDITO                  := T_PC_DESDCREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voDESDCREDITO.CODIGOORIG       := voCREDITOCLIENTE.CODIGO;
      voDESDCREDITO.DTLANC           := voCREDITOCLIENTE.DTLANC;
      --INICIALIZANDO OBJETOS DE CREDITO
      voCREDITOCLIENTEESTORNADO      := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voCREDITOCLIENTEESTORNADO      := voCREDITOCLIENTE;
      voCREDITOCLIENTEPARCIALBAIXADO := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voCREDITOCLIENTEPARCIALBAIXADO := voCREDITOCLIENTE;
      voCREDITOCLIENTEPARCIALABERTO  := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voCREDITOCLIENTEPARCIALABERTO  := voCREDITOCLIENTE;
      voCREDITOCLIENTEPARCIALABERTO.CODFILIALDESC := NULL;
      --ESTORNANDO O CREDITO
      voCREDITOCLIENTEESTORNADO.NUMCRED       := vfNUMCRED;
      voCREDITOCLIENTEESTORNADO.NUMPEDECF     := pfNUMPEDECF;
      voCREDITOCLIENTEESTORNADO.NUMSERIEEQUIP := psNUMSERIEEQUIP;
      voCREDITOCLIENTEESTORNADO.NUMCAIXA      := pfNUMCAIXA;
      voCREDITOCLIENTEESTORNADO.NUMCUPOM      := pfNUMCUPOM;
      voCREDITOCLIENTEESTORNADO.HISTORICO     := psHISTORICO;
      voCREDITOCLIENTEESTORNADO.CODFILIALDESC := psCODIGOFILIALDESCONTO;
      voCREDITOCLIENTEESTORNADO.CODFUNC       := pfMATRICULAUSUARIO;
      voCREDITOCLIENTEESTORNADO.CODROTINA     := pfCODIGOROTINA;
      voCREDITOCLIENTEESTORNADO.DTLANC        := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTEESTORNADO.ESTORNARTOTAL;
      --BAIXANDO O VALOR INFORMADO
      voCREDITOCLIENTEPARCIALBAIXADO.CODIGO        := voCREDITOCLIENTEPARCIALBAIXADO.PROXIMOCODIGOCREDITO;
      voCREDITOCLIENTEPARCIALBAIXADO.NUMCRED       := vfNUMCRED;
      voCREDITOCLIENTEPARCIALBAIXADO.VALOR         := pfVALORBAIXAR;
      voCREDITOCLIENTEPARCIALBAIXADO.DTDESCONTO    := TRUNC(SYSDATE);
      voCREDITOCLIENTEPARCIALBAIXADO.CODFUNC       := pfMATRICULAUSUARIO;
      voCREDITOCLIENTEPARCIALBAIXADO.HORA          := TO_CHAR(SYSDATE,'HH24');
      voCREDITOCLIENTEPARCIALBAIXADO.MINUTO        := TO_CHAR(SYSDATE,'MI');
      voCREDITOCLIENTEPARCIALBAIXADO.NUMPEDECF     := pfNUMPEDECF;
      voCREDITOCLIENTEPARCIALBAIXADO.NUMSERIEEQUIP := psNUMSERIEEQUIP;
      voCREDITOCLIENTEPARCIALBAIXADO.NUMCAIXA      := pfNUMCAIXA;
      voCREDITOCLIENTEPARCIALBAIXADO.NUMCUPOM      := pfNUMCUPOM;
      voCREDITOCLIENTEPARCIALBAIXADO.HISTORICO     := psHISTORICO;
      voCREDITOCLIENTEPARCIALBAIXADO.CODFILIALDESC := psCODIGOFILIALDESCONTO;
      voCREDITOCLIENTEPARCIALBAIXADO.CODFUNC       := pfMATRICULAUSUARIO;
      voCREDITOCLIENTEPARCIALBAIXADO.CODROTINA     := pfCODIGOROTINA;
      voCREDITOCLIENTEPARCIALBAIXADO.CODFUNCCX     := pfMATRICULAUSUARIO;
      voCREDITOCLIENTEPARCIALBAIXADO.CODPLPAG      := voCREDITOCLIENTE.CODPLPAG;
      voCREDITOCLIENTEPARCIALBAIXADO.DTVENC        := voCREDITOCLIENTE.DTVENC;
      voCREDITOCLIENTEPARCIALBAIXADO.DTLANC        := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTEPARCIALBAIXADO.INSERIR;
      INSERELOG('FNC_BAIXADECREDITOVAREJO', '99', 0, 0, 0, 0, voCREDITOCLIENTE.VALOR, pfVALORBAIXAR, 'BaixaParcial', vfNUMCRED, 0, pfCODIGOROTINA);
      --GRAVANDO DESDOBRAMENTO
      voDESDCREDITO.CODIGODEST                     := voCREDITOCLIENTEPARCIALBAIXADO.CODIGO;
      voDESDCREDITO.DTLANC                         := voCREDITOCLIENTE.DTLANC;
      voDESDCREDITO.INSERIR;
      --EM ABERTO A DIFERENÇA
      voCREDITOCLIENTEPARCIALABERTO.CODIGO        := voCREDITOCLIENTEPARCIALABERTO.PROXIMOCODIGOCREDITO;
      voCREDITOCLIENTEPARCIALABERTO.NUMCRED       := vfNUMCRED;
      voCREDITOCLIENTEPARCIALABERTO.VALOR         := (voCREDITOCLIENTEPARCIALABERTO.VALOR - pfVALORBAIXAR);
      voCREDITOCLIENTEPARCIALABERTO.HISTORICO     := psHISTORICO;
      voCREDITOCLIENTEPARCIALABERTO.CODFUNC       := pfMATRICULAUSUARIO;
      voCREDITOCLIENTEPARCIALABERTO.CODROTINA     := pfCODIGOROTINA;
      voCREDITOCLIENTEPARCIALABERTO.CODPLPAG      := voCREDITOCLIENTE.CODPLPAG;
      voCREDITOCLIENTEPARCIALABERTO.DTVENC        := voCREDITOCLIENTE.DTVENC;
      voCREDITOCLIENTEPARCIALABERTO.PRESTRESTCLI  := voCREDITOCLIENTE.PRESTRESTCLI;
      voCREDITOCLIENTEPARCIALABERTO.DTLANC        := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTEPARCIALABERTO.INSERIR;
      --GRAVANDO DESDOBRAMENTO
      voDESDCREDITO.CODIGODEST := voCREDITOCLIENTEPARCIALABERTO.CODIGO;
      voDESDCREDITO.DTLANC := voCREDITOCLIENTE.DTLANC;
      voDESDCREDITO.INSERIR;

      voLISTA.EXTEND(2);
      voLISTA(1) := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voLISTA(1) := voCREDITOCLIENTEPARCIALBAIXADO;
      psCODIGOSCREDITOGERADO := voCREDITOCLIENTEPARCIALBAIXADO.CODIGO;

      voLISTA(2) := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voLISTA(2) := voCREDITOCLIENTEPARCIALABERTO;
      psCODIGOSCREDITOGERADO := psCODIGOSCREDITOGERADO ||','|| voCREDITOCLIENTEPARCIALABERTO.CODIGO;
    END IF;

    INSERELOG('FNC_BAIXADECREDITOVAREJO', '99', 0, 0, 0, 0, 0, pfVALORBAIXAR, 'Fim', vfNUMCRED, 0, pfCODIGOROTINA);
    RETURN voLISTA; --RETORNANDO A LISTA COM OS CREDITOS GERADOS!
  END FNC_BAIXADECREDITOVAREJO;

 ----------------------------------------------------------------------------------------
  /*
  7. "FNC_ATUALIZABAIXACREDITOVAREJO"
  FUNÇÃO CRIADA PARA SER UTILIZADA PELA EQUIPE DO VAREJO QUE POSSUI SUAS PARTICULARIDADES.
  NESSE MOMENTO IRA ATUALIZAR DADOS DO CREDITO REFERENTE A BAIXA FEITA NA FUNÇÃO "FNC_BAIXADECREDITOVAREJO"
  */
  FUNCTION FNC_ATUALIZABAIXACREDITOVAREJO(pfCODIGOCREDITO           IN NUMBER,
                                          pfCODIGOROTINA            IN NUMBER,
                                          pfMATRICULAUSUARIO        IN NUMBER
                                    )
  RETURN BOOLEAN IS
    vsPREST          VARCHAR2(2);
    vfNUMTRANSVENDA  NUMBER(10);
    voCREDITOCLIENTE T_PC_CREDITOCLIENTE;
  BEGIN
      --VALIDACOES DOS PARAMETROS DE ENTRADA
      IF (pfCODIGOCREDITO <= 0) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO DE CREDITO VALIDO!');
      END IF;
      --BUSCANDO O CREDITO INFORMADO
      voCREDITOCLIENTE         := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
      voCREDITOCLIENTE.BUSCARCREDITO(pfCODIGOCREDITO);

      IF NOT (voCREDITOCLIENTE.DTESTORNO IS NULL)  THEN
        RAISE_APPLICATION_ERROR(-20016,'ESSE CREDITO ESTA ESTORNADO. FAVOR INFORMAR UM CREDITO VALIDO!');
      END IF;

      IF (voCREDITOCLIENTE.DTDESCONTO IS NULL)  THEN
        RAISE_APPLICATION_ERROR(-20016,'ESSE CREDITO NAO ESTA BAIXADO. FAVOR INFORMAR UM CREDITO VALIDO BAIXADO!');
      END IF;

      INSERELOG('FNC_ATUALIZABAIXACREDITOVAREJO', '99', 0, 0, 0, 0, 0, 0, 'Inicio', pfCODIGOCREDITO, 0, pfCODIGOROTINA);

      BEGIN --BUSCANDO INFORMACOES DO TITULO PARA ATUALIZAR A PCCRECLI
         SELECT PRESTECF, NUMTRANSVENDA
         INTO vsPREST, vfNUMTRANSVENDA
         FROM PCPRESTECF
         WHERE CODCOB = 'CRED'
           AND NUMPEDECF = voCREDITOCLIENTE.NUMPEDECF
           AND CODFILIAL = voCREDITOCLIENTE.CODFILIALDESC
           AND NUMCHECKOUT = voCREDITOCLIENTE.NUMCAIXA
           AND ROWNUM = 1;
      EXCEPTION WHEN NO_DATA_FOUND THEN
         RAISE_APPLICATION_ERROR(-20016,'NAO FOI POSSIVEL LOCALIZAR O TITULO NA PCPREST!');
      END;

      --ATUALIZANDO O CREDITO!
      voCREDITOCLIENTE.NUMTRANSVENDADESC := vfNUMTRANSVENDA;
      voCREDITOCLIENTE.PRESTRESTCLI      := vsPREST;
      voCREDITOCLIENTE.NUMNOTADESC       := voCREDITOCLIENTE.NUMCUPOM;
      voCREDITOCLIENTE.DTLANC            := voCREDITOCLIENTE.DTLANC;
      voCREDITOCLIENTE.BAIXAR;

      INSERELOG('FNC_ATUALIZABAIXACREDITOVAREJO', '99', 0, 0, 0, 0, 0, 0, 'Fim', pfCODIGOCREDITO, 0, pfCODIGOROTINA);

      RETURN TRUE;
    EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20016,
                             CHR(13) ||
                             'NAO FOI POSSIVEL REALIZAR O PROCESSO ATUALIZAÇÃO DE BAIXA DE CREDITO DO VAREJO!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
      RETURN FALSE;
  END FNC_ATUALIZABAIXACREDITOVAREJO;

 ----------------------------------------------------------------------------------------
  /*
  8. "FNC_ESTORNARBAIXACREDITOVAREJO"
  FUNÇÃO CRIADA PARA SER UTILIZADA PELA EQUIPE DO VAREJO QUE POSSUI SUAS PARTICULARIDADES.
  FARA O ESTORNO DO CREDITO BAIXADO PELO VAREJO FAZENDO CONFORME CRITERIOS PASSADOS PELO VAREJO
  */
FUNCTION FNC_ESTORNARBAIXACREDITOVAREJO(pfNUMPEDECF               IN NUMBER,
                                          psNUMSERIEEQUIP           IN VARCHAR2,
                                          pfNUMCAIXA                IN NUMBER,
                                          pfNUMCUPOM                IN NUMBER,
                                          psHISTORICO               IN VARCHAR2,
                                          pfCODIGOROTINA            IN NUMBER,
                                          pfMATRICULAUSUARIO        IN NUMBER,                                          
                                          psCODIGOSCREDITOGERADO    IN OUT VARCHAR2,
                                          psCAIXAVENDAABERTA        IN VARCHAR2 DEFAULT 'N')
  RETURN VARCHAR2 IS
     vnQtCreditos NUMBER;
     vsCODIGOSCREDITOGERADO varchar2(4000);
     vCODIGOESTORNO PCCRECLI.CODIGO%TYPE;
     vUltimoCredito VARCHAR2(1);
     vCancelouPrimeiroCredito VARCHAR2(1);
     vCodigoCredito PCCRECLI.CODIGO%TYPE;
     vExisteDesdobramento NUMBER(10);
  BEGIN
     --VALIDACOES DOS PARAMETROS DE ENTRADA
     IF (pfNUMPEDECF <= 0) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM NUMERO DE PEDIDO ECF VALIDO!');
     END IF;

     INSERELOG('FNC_ESTORNARBAIXACREDITOVAREJO', '99', 0, 0, pfNUMCUPOM, 0, 0, 0, 'Inicio', 0, 0, pfCODIGOROTINA);

     IF (TRIM(psNUMSERIEEQUIP) = '') OR (psNUMSERIEEQUIP IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM NUMERO DE SERIE DE EQUIPAMENTO VALIDO!');
     END IF;

     IF (pfNUMCAIXA <= 0) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM NUMERO DE CAIXA VALIDO!');
     END IF;
     
     vCancelouPrimeiroCredito := 'S';
     vnQtCreditos := 0;
     
     -- BUSCANDO CREDITOS UTILIZADOS NA VENDA
     FOR CREDITOS IN (SELECT DISTINCT D.CODIGOORIG CODIGO,
                             (SELECT MAX(CL.CODIGODEST)
                              FROM PCDESDCRECLI CL
                              WHERE CL.CODIGOORIG = C.CODIGO) CODIGODEST,
                             (SELECT MIN(CL.CODIGODEST)
                              FROM PCDESDCRECLI CL
                              WHERE CL.CODIGOORIG = C.CODIGO) CODIGODESTPRI
                      FROM PCDESDCRECLI D,
                           PCCRECLI C
                      WHERE D.CODIGOORIG = C.CODIGO
                        AND C.NUMCUPOM = pfNUMCUPOM
                        AND C.NUMPEDECF = PFNUMPEDECF
                        AND C.NUMSERIEEQUIP = PSNUMSERIEEQUIP
                        AND C.NUMCAIXA = PFNUMCAIXA
                        AND C.DTDESCONTO IS NOT NULL
                        AND TRUNC(C.DTDESCONTO) >= (TRUNC(SYSDATE) - 5)
                        AND C.VALOR > 0
                        AND C.DTESTORNO IS NULL
                      ORDER BY D.CODIGOORIG)
     LOOP
        vCancelouPrimeiroCredito := 'N';

        BEGIN
           vUltimoCredito := 'N';

           SELECT 'S'
           INTO vUltimoCredito
           FROM PCCRECLI CC
           WHERE CC.CODIGO = CREDITOS.CODIGODEST
             AND CC.DTDESCONTO IS NULL;
        EXCEPTION WHEN OTHERS THEN
           vUltimoCredito := 'N';
        END;

        VCODIGOESTORNO := CREDITOS.CODIGO;
        vnQtCreditos := vnQtCreditos + 1;
        -- ESTORNA O CRÉDITO
        IF PKG_CREDITOCLIENTE.FNC_CANCELARESTORCREDITOVAREJO(vCODIGOESTORNO, vUltimoCredito, pfNUMCUPOM, pfCODIGOROTINA, pfMATRICULAUSUARIO, CREDITOS.CODIGODESTPRI, pfNUMPEDECF, psNUMSERIEEQUIP, pfNUMCAIXA) THEN
           IF (vsCODIGOSCREDITOGERADO = '') OR (vsCODIGOSCREDITOGERADO IS NULL) THEN
              vsCODIGOSCREDITOGERADO := vCODIGOESTORNO;
           ELSE
              vsCODIGOSCREDITOGERADO := vsCODIGOSCREDITOGERADO || ',' || vCODIGOESTORNO;
           END IF;
        END IF;
     END LOOP;

     -- NECESSÁRIO PARA RETORNAR O CRÉDITO QUE NÃO HOUVE DESDOBRAMENTO.
     IF vCancelouPrimeiroCredito = 'S' AND PFNUMPEDECF > 0 THEN
        FOR CRED IN (SELECT CC.CODIGO,
                            CC.NUMCUPOM,
                            CC.NUMPEDECF,
                            CC.NUMSERIEEQUIP,
                            CC.NUMCAIXA
                     FROM PCCRECLI CC
                     WHERE CC.NUMCUPOM = pfNUMCUPOM
                       AND CC.DTDESCONTO IS NOT NULL
                       AND CC.NUMPEDECF = PFNUMPEDECF
                       AND CC.NUMSERIEEQUIP = PSNUMSERIEEQUIP
                       AND CC.NUMCAIXA = PFNUMCAIXA
                       AND TRUNC(CC.DTDESCONTO) >= (TRUNC(SYSDATE) - 5)
                       AND CC.VALOR > 0
                       AND CC.DTESTORNO IS NULL
                       AND NOT EXISTS (SELECT 1 FROM PCDESDCRECLI DC WHERE DC.CODIGOORIG = CC.CODIGO))
        LOOP
           vnQtCreditos := vnQtCreditos + 1;
           vCodigoCredito := CRED.CODIGO;
           
           IF (psCAIXAVENDAABERTA = 'S') THEN           
              BEGIN
                SELECT NVL(D.CODIGOORIG, 0) INTO vCodigoCredito
                  FROM pccrecli CC, PCDESDCRECLI D
                 WHERE CC.CODIGO = CRED.CODIGO
                   AND CC.CODIGO = D.CODIGODEST
                   AND EXISTS (SELECT 1
                          FROM PCCRECLI C
                         WHERE C.CODIGO = D.CODIGOORIG
                           AND C.NUMCUPOM = CRED.NUMCUPOM
                           AND C.DTDESCONTO IS NOT NULL
                           AND C.NUMPEDECF = CRED.NUMPEDECF
                           AND C.NUMSERIEEQUIP = CRED.NUMSERIEEQUIP
                           AND C.NUMCAIXA = CRED.NUMCAIXA);
              EXCEPTION WHEN OTHERS THEN
                vCodigoCredito := CRED.CODIGO;
              END;                         
                  
                DELETE FROM PCCRECLI C
                 WHERE C.CODIGO IN
                       (SELECT DESD.CODIGODEST
                          FROM PCDESDCRECLI DESD
                         WHERE DESD.CODIGOORIG = vCodigoCredito);
                
                DELETE FROM PCCRECLI C
                 WHERE C.NUMPEDECF             = CRED.NUMPEDECF
                   AND C.NUMCUPOM              = CRED.NUMCUPOM
                   AND C.NUMSERIEEQUIP         = CRED.NUMSERIEEQUIP
                   AND C.NUMCAIXA              = CRED.NUMCAIXA
                   AND C.VALOR                 < 0;
                
                 DELETE FROM PCDESDCRECLI D
                 WHERE D.CODIGOORIG = vCodigoCredito;
           END IF;  
           
           --REABRINDO O CREDITO
           UPDATE PCCRECLI SET DTDESCONTO        = NULL,
                               CODFILIALDESC     = NULL,
                               NUMNOTADESC       = NULL,
                               SERIEDESC         = NULL,
                               NUMTRANSVENDADESC = NULL,
                               NUMCRED           = NULL,
                               DTESTORNO         = NULL,
                               NUMCUPOM          = NULL,
                               NUMPEDECF         = NULL
           WHERE CODIGO = vCodigoCredito
             AND NVL(VALOR,0) > 0;

           IF (vsCODIGOSCREDITOGERADO = '') OR (vsCODIGOSCREDITOGERADO IS NULL) THEN
              vsCODIGOSCREDITOGERADO := vCodigoCredito;
           ELSE
              vsCODIGOSCREDITOGERADO := vsCODIGOSCREDITOGERADO || ',' || vCodigoCredito;
           END IF;
        END LOOP;
     END IF;

     IF (vnQtCreditos = 0) THEN
        RAISE_APPLICATION_ERROR(-20016,'NÃO FOI POSSÍVEL LOCALIZAR CRÉDITO(S) BAIXADO(S) PARA ESTORNAR!!');
     END IF;
     -- RETORNA A LISTA DE CRÉDITOS ESTORNADOS
     RETURN vsCODIGOSCREDITOGERADO;

     INSERELOG('FNC_ESTORNARBAIXACREDITOVAREJO', '99', 0, 0, pfNUMCUPOM, 0, 0, 0, 'Fim', 0, 0, pfCODIGOROTINA);
  EXCEPTION WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20016, CHR(13) ||
                             'NAO FOI POSSIVEL REALIZAR O PROCESSO DE ESTORNO DE BAIXA DE CREDITO DO VAREJO!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
  END FNC_ESTORNARBAIXACREDITOVAREJO;


  function FC_RETORNA_VERSAO return varchar2 is
    vsVERSAO varchar2(20) := '';
  begin
    select VSVERSAOPACKAGE
    into   vsVERSAO
    from   DUAL;

    return vsVERSAO;
  end;


  PROCEDURE INSERELOG(PMETODO VARCHAR2,
                      PCODFILIAL VARCHAR2,
                      PNUMTRANSENT NUMBER,
                      PNUMTRANSVENDA NUMBER,
                      PNUMTRANSVENDADESC NUMBER,
                      PVALORNOTA NUMBER,
                      PVALORCRED NUMBER,
                      PVALORBAIXA NUMBER,
                      POBSERVACAO VARCHAR2,
                      PNUMCRED NUMBER,
                      PNUMPED NUMBER,
                      PCODROTINA NUMBER) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    VVERSAOPKG VARCHAR2(100);
    VVERSAOBD VARCHAR2(100);
    VOPERACAO PCLOGALTERACAODADOS.OBSERVACOES2%TYPE;
    VSERRO PCLOGALTERACAODADOS.OBSERVACOES2%TYPE;
  BEGIN
    VOPERACAO := SUBSTR('CODFILIAL: ' || PCODFILIAL || ' NUMTRANSENT: ' || PNUMTRANSENT || ' NUMTRANSVENDA: ' || PNUMTRANSVENDA || ' NUMTRANSVENDADESC: ' || PNUMTRANSVENDADESC || ' NUMCRED: ' || PNUMCRED || ' NUMPED: ' || PNUMPED || ' VALORNOTA: ' || PVALORNOTA || ' CRED: ' || PVALORCRED || ' BAIXA: ' || PVALORBAIXA, 1, 2000);
    VVERSAOBD := '';
    VVERSAOPKG:= '';

    BEGIN
      select VERSAO, FC_RETORNA_VERSAO
        into VVERSAOBD, VVERSAOPKG
        FROM PCVERSAOBD
       WHERE UPPER(DESCRICAO) LIKE '%PKG_CREDITOCLIENTE%'
         and ROWNUM = 1;
    EXCEPTION WHEN OTHERS THEN
        null;
    END;

    INSERT INTO PCLOGALTERACAODADOS
          (DATA, CODROTINA, PROGRAMA, TABELA, OBSERVACOES, OBSERVACOES2, VALORALFA, VALORNUM, CODIGO, OBSERVACOES3)
    VALUES
          (SYSDATE,
          PCODROTINA,
          SUBSTR('PKG_CREDITOCLIENTE', 1, 64),
          SUBSTR(PMETODO, 1, 30),
          SUBSTR(POBSERVACAO, 1, 100),
          VOPERACAO,
          'VALORALFA',
          PVALORCRED,
          PNUMCRED,
          SUBSTR('VERSAOBD: ' || VVERSAOBD || ' VERSAOPKG: ' || VVERSAOPKG, 1, 100));

    COMMIT;

    EXCEPTION WHEN OTHERS THEN
    BEGIN
       VSERRO := SUBSTR('SQLCODE: ' || SQLCODE || ' SQLERRM: ' || SQLERRM, 1, 2000);

       INSERT INTO PCLOGALTERACAODADOS
            (DATA, CODROTINA, PROGRAMA, TABELA, OBSERVACOES, OBSERVACOES2, VALORALFA, CODIGO, OBSERVACOES3)
       VALUES
            (SYSDATE,
             PCODROTINA,
             SUBSTR('PKG_CREDITOCLIENTE', 1, 64),
             SUBSTR(PMETODO, 1, 30),
             'ERRO',
             VSERRO,
             vOPERACAO,
             PNUMCRED,
             SUBSTR('VERSAOBD: ' || VVERSAOBD || ' VERSAOPKG: ' || VVERSAOPKG, 1, 100));
       COMMIT;
    END;
  END;

 ----------------------------------------------------------------------------------------
  /*
  9. FNC_CANCELARESTORNOCREDITOVAREJO
  FUNCAO CRIADA PARA FAZER O CANCELAMENTO DO ESTORNO REALIZADO POR BAIXA PARCIAL NO VAREJO.
  EX: CASO TENHA UM CREDITO DE 100,00 E FACA A BAIXA DE 80,00 FICARA 20,00 EM ABERTO.
  SE O CODIGO INFORMADO FOR DO CREDITO DE 100,00 QUE JA ENCONTRA-SE ESTORNADO, O SISTEMA IRA
  APAGAR OS CREDITOS DE 80,00 E 20,00 VOLTANDO 100,00 EM ABERTO.
  */
  FUNCTION FNC_CANCELARESTORCREDITOVAREJO(pfCODIGOCREDITO IN NUMBER, pUltimoCredito IN VARCHAR2,
           pNUMCUPOM IN NUMBER, pfCODIGOROTINA IN NUMBER, pfMATRICULAUSUARIO IN NUMBER, pCODIGODEST IN NUMBER,
           pNUMPEDECF IN NUMBER, pNUMSERIEEQUIP IN VARCHAR2, pNUMCAIXA IN NUMBER)
  RETURN BOOLEAN IS
     vsCODIGOS  VARCHAR2(100);
     V_SQL      VARCHAR2(100);
     V_CONTADOR NUMBER(2);
     V_ROWS_FOUND BOOLEAN := FALSE;
     vGerarRegistros VARCHAR2(1);
  BEGIN
     --VALIDACOES DOS PARAMETROS DE ENTRADA
     IF (pfCODIGOCREDITO <= 0) THEN
        RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO DE CREDITO VALIDO!');
     END IF;
     --UTILIZANDO ESSA VARIAVEL PORQUE O CREDITO PODE TER SIDO DESDOBRADO VÁRIAS VEZES E ASSIM PODE CANCELANDO OS OUTROS DESDOBRAMENTOS.
     vGerarRegistros := 'S';
     vsCODIGOS := pfCODIGOCREDITO;
     --LOCALIZANDO OS DESDOBRAMENTOS PARA FAZER A EXCLUSAO.
     IF pUltimoCredito = 'S' THEN
        <<VOLTA_REGISTRO>>
        FOR DADOS IN (SELECT ROWNUM,
                             D.CODIGODEST,
                             D.CODIGOORIG,
                             C.NUMCRED,
                             C.NUMCUPOM
                      FROM PCDESDCRECLI D, PCCRECLI C
                      WHERE D.CODIGODEST = C.CODIGO
                        AND D.CODIGOORIG IN (vsCODIGOS)
                      ORDER BY ROWNUM)
        LOOP
           V_ROWS_FOUND := TRUE;
           --LIMPANDO A LISTA LOGO NO PRIMEIRO REGISTRO
           IF DADOS.ROWNUM = 1 THEN
              vsCODIGOS := '';
           END IF;
           --EXCLUINDO PCCRECLI - CREDITO
           DELETE FROM PCCRECLI C WHERE C.CODIGO = DADOS.CODIGODEST;
           --EXCLUINDO TODOS OS CUPONS QUE NÃO SÃO DO CRÉDITO PRINCIPAL, CASO EXISTA MAIS DE UM CRÉDITO USADO
           DELETE FROM PCCRECLI C WHERE C.CODIGO <> DADOS.CODIGOORIG AND C.NUMCUPOM = pNUMCUPOM AND C.NUMCRED = DADOS.NUMCRED;
           --EXCLUINDO PCDESDCRECLI - RASTREAMENTO DO DESDOBRAMENTO
           DELETE FROM PCDESDCRECLI D WHERE D.CODIGOORIG = DADOS.CODIGOORIG AND D.CODIGODEST = DADOS.CODIGODEST;
           --VERIFICANDO SE O CREDITO FOI REDESDOBRADO
           V_SQL := 'SELECT COUNT(*) CONTADOR FROM PCDESDCRECLI WHERE CODIGOORIG = :CODIGOORIG ';
           EXECUTE IMMEDIATE V_SQL INTO V_CONTADOR USING DADOS.CODIGODEST;

           IF (V_CONTADOR > 0) THEN
              IF (LENGTH(TRIM(vsCODIGOS))) > 0 THEN
                 vsCODIGOS := vsCODIGOS ||','|| DADOS.CODIGODEST;
              ELSE
                 vsCODIGOS := DADOS.CODIGODEST;
              END IF;
           END IF;
        END LOOP;
        -- Caso algum código de crédito tenha ficado sem excluir, irá voltar para o início do <<VOLTA_REGISTRO>>
        IF ((LENGTH(TRIM(vsCODIGOS)) > 0) AND (V_ROWS_FOUND = TRUE)) THEN
           V_ROWS_FOUND := FALSE;
           GOTO VOLTA_REGISTRO;
        END IF;
        -- Caso não exista o registro na tabela PCCRECLI e ainda exista na tabela PCDESDCRECLI, deve excluir o que está na PCDESDCRECLI, pois não existe mais o vínculo entre elas.
        IF ((LENGTH(TRIM(vsCODIGOS)) > 0) AND (V_ROWS_FOUND = FALSE)) THEN
           DELETE FROM PCDESDCRECLI D WHERE D.CODIGOORIG IN (vsCODIGOS) AND NOT EXISTS (SELECT 1 FROM PCCRECLI WHERE CODIGO IN (vsCODIGOS));
        END IF;
     ELSE
        FOR DADOS IN (SELECT ROWNUM,
                             D.CODIGODEST,
                             D.CODIGOORIG,
                             C.NUMCRED,
                             C.NUMCUPOM
                      FROM PCDESDCRECLI D, PCCRECLI C
                      WHERE D.CODIGODEST = C.CODIGO
                        AND D.CODIGOORIG IN (vsCODIGOS)
                      ORDER BY ROWNUM)
        LOOP
           IF vGerarRegistros = 'S' THEN
              vGerarRegistros := 'N';

              INSERIRREGISTROSVAREJO(pCODIGODEST, pfCODIGOROTINA, pfMATRICULAUSUARIO);
           END IF;
        END LOOP;
     END IF;

     IF pUltimoCredito = 'S' THEN
        --REABRINDO O CREDITO
        UPDATE PCCRECLI SET DTDESCONTO        = NULL,
                            CODFILIALDESC     = NULL,
                            NUMNOTADESC       = NULL,
                            SERIEDESC         = NULL,
                            NUMTRANSVENDADESC = NULL,
                            NUMCRED           = NULL,
                            DTESTORNO         = NULL,
                            NUMCUPOM          = NULL
        WHERE CODIGO = pfCODIGOCREDITO
          AND NVL(VALOR,0) > 0;
     END IF;

     -- NECESSÁRIO PARA RETORNAR O CRÉDITO QUE NÃO HOUVE DESDOBRAMENTO.
     IF pNUMPEDECF > 0 AND vGerarRegistros = 'S' THEN
        FOR CRED IN (SELECT CC.CODIGO
                     FROM PCCRECLI CC
                     WHERE CC.NUMCUPOM = pNUMCUPOM
                       AND CC.NUMPEDECF = pNUMPEDECF
                       AND CC.NUMSERIEEQUIP = pNUMSERIEEQUIP
                       AND CC.NUMCAIXA = pNUMCAIXA
                       AND CC.DTDESCONTO IS NOT NULL
                       AND TRUNC(CC.DTDESCONTO) >= (TRUNC(SYSDATE) - 5)
                       AND CC.VALOR > 0
                       AND CC.DTESTORNO IS NULL
                       AND NOT EXISTS (SELECT 1 FROM PCDESDCRECLI DC WHERE DC.CODIGOORIG = CC.CODIGO AND NVL(VALOR,0) > 0))
        LOOP
           --REABRINDO O CREDITO
           UPDATE PCCRECLI SET DTDESCONTO        = NULL,
                               CODFILIALDESC     = NULL,
                               NUMNOTADESC       = NULL,
                               SERIEDESC         = NULL,
                               NUMTRANSVENDADESC = NULL,
                               NUMCRED           = NULL,
                               DTESTORNO         = NULL,
                               NUMCUPOM          = NULL
           WHERE CODIGO = CRED.CODIGO
             AND NVL(VALOR,0) > 0;
        END LOOP;
     END IF;

     RETURN TRUE;
  EXCEPTION WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20016,
                             CHR(13) ||
                             'NAO FOI POSSIVEL REALIZAR O PROCESSO DE CANCELAMENTO DE ESTORNO DE CREDITO!'
                             ||CHR(13)||'MENSAGEM.: '|| SQLERRM);
     RETURN FALSE;
  END FNC_CANCELARESTORCREDITOVAREJO;

 ----------------------------------------------------------------------------------------
  /*
  10. FNC_CHECKOUT_BAIXA_CREDITO
  FUNCAO DESENVOLVIDA PELA EQUIPE DO VAREJO E PEDIDA PARA INCLUIR NA PACKAGE DE CREDITO DE CLIENTE
  */
  FUNCTION FNC_CHECKOUT_BAIXA_CREDITO(codigo             IN NUMBER,
                                      valorBaixar        IN NUMBER,
                                      numPedEcf          IN NUMBER,
                                      numSerieEquip      IN VARCHAR2,
                                      numCaixa           IN NUMBER,
                                      numCupom           IN NUMBER,
                                      matriculaOperador  IN NUMBER,
                                      filial             IN VARCHAR2,
                                      psHISTORICO        IN VARCHAR2
  )
  RETURN VARCHAR2  IS
    v_retorno            LISTA_PC_CREDITOCLIENTE;
    v_retorno_string     VARCHAR2(4000);
    v_codigos_retornados  VARCHAR2(4000);
    handle_exception EXCEPTION;
    pragma exception_init(handle_exception,-20016);
  BEGIN
    v_retorno := pkg_creditocliente.fnc_baixadecreditovarejo(codigo,
                                                             valorBaixar,
                                                             numPedEcf,
                                                             numSerieEquip,
                                                             numCaixa,
                                                             numCupom,
                                                             psHISTORICO,
                                                             2075,
                                                             matriculaOperador,
                                                             filial,
                                                             v_codigos_retornados);
    IF v_codigos_retornados IS NOT NULL THEN
      v_retorno_string := v_codigos_retornados;
    ELSE
      v_retorno_string := 'NAO FORAM GERADOS NOVOS CREDITOS';
    END IF;

    RETURN v_retorno_string;
  EXCEPTION WHEN handle_exception THEN
        RETURN 'ERRO AO BAIXAR CREDITO - CODIGO: '|| codigo || ' Motivo: ' || SUBSTR(SQLERRM, 1, 200);
  END FNC_CHECKOUT_BAIXA_CREDITO;


FUNCTION FNC_CANCELARCREDITOCLIENTE(psFILIAL IN VARCHAR2, 
                                    pfNUMTRANSVENDA IN NUMBER, 
                                    pfVALOR IN NUMBER, 
                                    pfCODIGOROTINA IN NUMBER, 
                                    pfMATRICULAUSUARIO IN NUMBER, 
                                    pfNUMTRANSENT IN NUMBER DEFAULT 0)
RETURN NUMBER IS
   vfNUMCRED NUMBER(10);
   voCREDITOCLIENTE T_PC_CREDITOCLIENTE;
   vMENSAGEM VARCHAR2(1);
BEGIN
   --CRIANDO OBJETO DE PERSISTENCIA COM PCCRECLI
   voCREDITOCLIENTE := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
   --OBTENDO O "NUMCRED" CODIGO IDENTIFICADOR PARA RELACIONAMENTO DE REGISTROS NA BAIXA
   IF NVL(voCREDITOCLIENTE.NUMCRED,0) > 0 THEN
      vfNUMCRED:= voCREDITOCLIENTE.NUMCRED;
   ELSE
      SELECT DFSEQ_PCCRECLI_NUMCRED.NEXTVAL INTO vfNUMCRED FROM DUAL;
   END IF;
   --inicio
   --BUSCANDO OS CREDITOS DO CLIENTE INFORMADO
   FOR LISTACREDITOS IN (SELECT C.CODCLI,
                                C.DTLANC,
                                C.CODFILIAL,
                                C.ORIGEM,
                                C.NUMNOTA,
                                NVL(C.NUMTRANSVENDA, 0) NUMTRANSVENDA,
                                C.NUMTRANSENTDEVCLI,
                                C.VALOR,
                                NVL(C.NUMTRANS, 0) NUMTRANS,
                                NVL(C.NUMLANC, 0) NUMLANC,
                                C.SERIE,
                                C.HISTORICO,
                                C.NUMPED,
                                C.DTEMISSAOTITULO,
                                C.CODIGO,
                                C.CODPLPAG,
                                C.SITUACAO
                         FROM PCCRECLI C
                         WHERE C.DTDESCONTO IS NULL
                           AND C.DTESTORNO IS NULL
                           AND ((PARAMFILIAL.OBTERCOMOVARCHAR2('USACREDCLITODASFILIAIS') = 'S') OR (C.CODFILIAL = psFILIAL))
                           AND NVL(C.NUMTRANSVENDA,0) = pfNUMTRANSVENDA
                           AND NVL(C.NUMTRANSENTDEVCLI,0) = pfNUMTRANSENT
                         ORDER BY C.VALOR)
   LOOP
      vMENSAGEM := 'S';
      IF LISTACREDITOS.VALOR < pfVALOR THEN
         vMENSAGEM := 'N';
         
         RAISE_APPLICATION_ERROR(-20016, CHR(13) ||
                                 'NAO FOI POSSIVEL REALIZAR O PROCESSO DE CANCELAMENTO DO CRÉDITO DO CLIENTE!'||CHR(13)||
                                 '- VALOR INFORMADO É MAIOR QUE O VALOR DO CRÉDITO DO CLIENTE:'||CHR(13)||
                                 '  VALOR DO CRÉDITO = '|| LISTACREDITOS.VALOR|| ', VALOR INFORMADO PARA A FUNÇÃO = '||pfVALOR||CHR(13)||
                                 'MENSAGEM.: '|| SQLERRM);
      END IF;
      --ATRIBUO UMA VEZ VALOR AO OBJETO. E FAÇO AS MODIFICACOES COM BASE NA OPERACAO QUE DESEJAR.
      voCREDITOCLIENTE.LIMPAR;
      voCREDITOCLIENTE.DTLANC            := LISTACREDITOS.DTLANC;
      voCREDITOCLIENTE.DTEMISSAOTITULO   := LISTACREDITOS.DTEMISSAOTITULO;
      voCREDITOCLIENTE.CODIGO            := LISTACREDITOS.CODIGO;
      voCREDITOCLIENTE.CODCLI            := LISTACREDITOS.CODCLI;
      voCREDITOCLIENTE.CODFILIAL         := LISTACREDITOS.CODFILIAL;
      voCREDITOCLIENTE.CODFILIALDESC     := LISTACREDITOS.CODFILIAL;
      voCREDITOCLIENTE.NUMTRANS          := LISTACREDITOS.NUMTRANS;
      voCREDITOCLIENTE.NUMLANC           := LISTACREDITOS.NUMLANC;
      voCREDITOCLIENTE.NUMNOTA           := LISTACREDITOS.NUMNOTA;
      voCREDITOCLIENTE.NUMNOTADESC       := LISTACREDITOS.NUMNOTA;
      voCREDITOCLIENTE.SERIE             := LISTACREDITOS.SERIE;
      voCREDITOCLIENTE.SERIEDESC         := LISTACREDITOS.SERIE;
      voCREDITOCLIENTE.NUMTRANSVENDADESC := pfNUMTRANSVENDA;
      voCREDITOCLIENTE.NUMTRANSVENDA     := LISTACREDITOS.NUMTRANSVENDA;
      voCREDITOCLIENTE.NUMTRANSENTDEVCLI := LISTACREDITOS.NUMTRANSENTDEVCLI;
      voCREDITOCLIENTE.ORIGEM            := LISTACREDITOS.ORIGEM;
      voCREDITOCLIENTE.NUMPED            := LISTACREDITOS.NUMPED;
      voCREDITOCLIENTE.VALOR             := LISTACREDITOS.VALOR;
      voCREDITOCLIENTE.NUMCRED           := vfNUMCRED;
      voCREDITOCLIENTE.CODPLPAG          := LISTACREDITOS.CODPLPAG;
      voCREDITOCLIENTE.SITUACAO          := LISTACREDITOS.SITUACAO;
      voCREDITOCLIENTE.HISTORICO         := LISTACREDITOS.HISTORICO;
      
       IF LISTACREDITOS.VALOR = pfVALOR THEN
         voCREDITOCLIENTE.DTCANCEL := TRUNC(SYSDATE);
       END IF;
      
      voCREDITOCLIENTE.BAIXAR;

      voCREDITOCLIENTE.ESTORNARTOTAL;
      ---CANCELAMENTO PARCIAL---
      IF LISTACREDITOS.VALOR > pfVALOR THEN
         ---Lançando o valor a ser cancelado
         voCREDITOCLIENTE.NUMTRANS := NULL;
         voCREDITOCLIENTE.VALOR := pfVALOR;
         voCREDITOCLIENTE.CODIGO := NULL;
         voCREDITOCLIENTE.DTLANC := voCREDITOCLIENTE.DTLANC;
         voCREDITOCLIENTE.HISTORICO := voCREDITOCLIENTE.HISTORICO;
         voCREDITOCLIENTE.DTCANCEL := NULL;
         voCREDITOCLIENTE.INSERIR;
         voCREDITOCLIENTE.DTCANCEL := TRUNC(SYSDATE);
         voCREDITOCLIENTE.BAIXAR;
         voCREDITOCLIENTE.ESTORNARTOTAL;
         ---Lançando a diferença em aberto
         voCREDITOCLIENTE.DTDESCONTO := NULL;
         voCREDITOCLIENTE.HORA := NULL;
         voCREDITOCLIENTE.MINUTO := NULL;
         voCREDITOCLIENTE.DTESTORNO := NULL;
         voCREDITOCLIENTE.CODFILIALDESC := NULL;
         voCREDITOCLIENTE.NUMTRANS := NULL;
         voCREDITOCLIENTE.NUMNOTADESC := NULL;
         voCREDITOCLIENTE.SERIEDESC := NULL;
         voCREDITOCLIENTE.NUMTRANSVENDADESC := NULL;
         voCREDITOCLIENTE.VALOR := LISTACREDITOS.VALOR - pfVALOR;
         voCREDITOCLIENTE.CODIGO := NULL;
         voCREDITOCLIENTE.SITUACAO := NULL;
         voCREDITOCLIENTE.DTLANC := voCREDITOCLIENTE.DTLANC;
         voCREDITOCLIENTE.HISTORICO := voCREDITOCLIENTE.HISTORICO;
         voCREDITOCLIENTE.DTCANCEL := NULL;
         voCREDITOCLIENTE.INSERIR;
      END IF;
   END LOOP; --FIM DO LOOP DOS CREDITOS
   --fim
   RETURN voCREDITOCLIENTE.CODIGO;
EXCEPTION WHEN OTHERS THEN
   IF vMENSAGEM = 'S' THEN
      RAISE_APPLICATION_ERROR(-20016, CHR(13) ||
                              'NAO FOI POSSIVEL REALIZAR O PROCESSO DE CANCELAMENTO DO CRÉDITO DO CLIENTE!'||CHR(13)||
                              'MENSAGEM.: '|| SQLERRM);
   END IF;

   RETURN 0;
END FNC_CANCELARCREDITOCLIENTE;

 ----------------------------------------------------------------------------------------
 /*
 11. FNC_CHECKOUT_BAIXA_CREDITO
 FUNCAO DESENVOLVIDA PELA EQUIPE DO VAREJO E PEDIDA PARA INCLUIR NA PACKAGE DE CREDITO DE CLIENTE
 */
PROCEDURE INSERIRREGISTROSVAREJO(pCODIGO IN NUMBER, pfCODIGOROTINA IN NUMBER, pfMATRICULAUSUARIO IN NUMBER)
IS
   voCREDITOCLIENTE T_PC_CREDITOCLIENTE;
   voDESD T_PC_DESDCREDITOCLIENTE;
   vNUMCRED NUMBER(10);
   vEXISTEREGISTRO VARCHAR2(1);
BEGIN
   voCREDITOCLIENTE := T_PC_CREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
   voDESD := T_PC_DESDCREDITOCLIENTE(pfMATRICULAUSUARIO, pfCODIGOROTINA);
   vEXISTEREGISTRO := 'N';

   BEGIN
      voCREDITOCLIENTE.LIMPAR;

      SELECT CR.CODCLI, --01
             CR.DTLANC, --02
             CR.NUMCUPOM, --03
             CR.NUMCRED, --04
             CR.VALOR, --05
             NVL(CR.DTDESCONTO,SYSDATE), --06
             CR.NUMSERIEEQUIP, --08
             CR.CODROTINA, --09
             CR.CODFILIAL, --10
             CR.NUMNOTA, --11
             CR.NUMTRANSVENDA, --12
             CR.SERIE, --13
             CR.CODFILIALDESC, --14
             CR.NUMNOTADESC, --15
             CR.SERIEDESC, --16
             CR.CODFUNC, --17
             CR.HORA, --18
             CR.MINUTO, --19
             CR.ORIGEM, --20
             CR.NUMTRANSVENDADESC, --21
             CR.NUMTRANSENTDEVCLI, --22
             CR.HISTORICO, --23
             CR.CODFUNCLANC, --24
             CR.NUMPED, --25
             CR.NUMERARIO, --26
             CR.CODMOVIMENTO, --27
             CR.NUMLANC, --28
             CR.NUMPEDECF, --29
             CR.NUMCAIXA, --30
             CR.CODFUNCCX, --31
             CR.PRESTRESTCLI, --32
             NVL(CR.DTESTORNO,SYSDATE) --33
      INTO voCREDITOCLIENTE.CODCLI, --01
           voCREDITOCLIENTE.DTLANC, --02
           voCREDITOCLIENTE.NUMCUPOM, --03
           vNUMCRED, --04
           voCREDITOCLIENTE.VALOR, --05
           voCREDITOCLIENTE.DTDESCONTO, --06
           voCREDITOCLIENTE.NUMSERIEEQUIP, --08
           voCREDITOCLIENTE.CODROTINA, --09
           voCREDITOCLIENTE.CODFILIAL, --10
           voCREDITOCLIENTE.NUMNOTA, --11
           voCREDITOCLIENTE.NUMTRANSVENDA, --12
           voCREDITOCLIENTE.SERIE, --13
           voCREDITOCLIENTE.CODFILIALDESC, --14
           voCREDITOCLIENTE.NUMNOTADESC, --15
           voCREDITOCLIENTE.SERIEDESC, --16
           voCREDITOCLIENTE.CODFUNC, --17
           voCREDITOCLIENTE.HORA, --18
           voCREDITOCLIENTE.MINUTO, --19
           voCREDITOCLIENTE.ORIGEM, --20
           voCREDITOCLIENTE.NUMTRANSVENDADESC, --21
           voCREDITOCLIENTE.NUMTRANSENTDEVCLI, --22
           voCREDITOCLIENTE.HISTORICO, --23
           voCREDITOCLIENTE.CODFUNCLANC, --24
           voCREDITOCLIENTE.NUMPED, --25
           voCREDITOCLIENTE.NUMERARIO, --26
           voCREDITOCLIENTE.CODMOVIMENTO, --27
           voCREDITOCLIENTE.NUMLANC, --28
           voCREDITOCLIENTE.NUMPEDECF, --29
           voCREDITOCLIENTE.NUMCAIXA, --30
           voCREDITOCLIENTE.CODFUNCCX, --31
           voCREDITOCLIENTE.PRESTRESTCLI, --32
           voCREDITOCLIENTE.DTESTORNO --33
      FROM PCCRECLI CR
      WHERE CR.CODIGO = pCODIGO;

      vEXISTEREGISTRO := 'S';
   EXCEPTION WHEN OTHERS THEN
      vEXISTEREGISTRO := 'N';
      voCREDITOCLIENTE.LIMPAR;
   END;

   INSERELOG('INSERIRREGISTROSVAREJO', 'PCCRECLI', 0, 0, pCODIGO, 0, 0, 0, 'pCODIGO = '||pCODIGO, 0, 0, pfCODIGOROTINA);

   IF vEXISTEREGISTRO = 'S' THEN
      IF vNUMCRED > 0 THEN
         voCREDITOCLIENTE.NUMCRED := vNUMCRED;
      END IF;
      --Inserindo o débito do que será estornado
      voCREDITOCLIENTE.DTESTORNO := TRUNC(SYSDATE);
      voCREDITOCLIENTE.CODIGO := voCREDITOCLIENTE.PROXIMOCODIGOCREDITO;
      voCREDITOCLIENTE.DTLANC := NVL(voCREDITOCLIENTE.DTLANC, TRUNC(SYSDATE));
      voCREDITOCLIENTE.INSERIR;
      --Inserindo os desdobramentos do retorno do débito
      voDESD.LIMPAR;
      voDESD.CODIGOORIG := pCODIGO;
      voDESD.CODIGODEST := voCREDITOCLIENTE.CODIGO;
      voDESD.DTLANC := NVL(voCREDITOCLIENTE.DTLANC, TRUNC(SYSDATE));
      voDESD.INSERIR;
      --Inserindo o crédito do que será estornado
      voCREDITOCLIENTE.CODIGO := voCREDITOCLIENTE.PROXIMOCODIGOCREDITO;
      voCREDITOCLIENTE.VALOR := voCREDITOCLIENTE.VALOR * -1;
      voCREDITOCLIENTE.DTLANC := NVL(voCREDITOCLIENTE.DTLANC, TRUNC(SYSDATE));
      voCREDITOCLIENTE.INSERIR;
      --Inserindo os desdobramentos do retorno do crédito
      voDESD.CODIGODEST := voCREDITOCLIENTE.CODIGO;
      voDESD.DTLANC := NVL(voCREDITOCLIENTE.DTLANC, TRUNC(SYSDATE));
      voDESD.INSERIR;
      voCREDITOCLIENTE.LIMPAR;
      voDESD.LIMPAR;
      INSERELOG('INSERIRREGISTROSVAREJO', 'PCDESDCRECLI', 0, 0, pCODIGO, 0, 0, 0, 'pCODIGO = '||pCODIGO, 0, 0, pfCODIGOROTINA);
      --Reabrindo o Crédito
      UPDATE PCCRECLI SET DTDESCONTO = NULL,
                          CODFILIALDESC = NULL,
                          NUMNOTADESC = NULL,
                          SERIEDESC = NULL,
                          NUMTRANSVENDADESC = NULL,
                          NUMCRED = NULL,
                          DTESTORNO = NULL,
                          NUMCUPOM = NULL
      WHERE CODIGO = pCODIGO;
   END IF;
END INSERIRREGISTROSVAREJO;
----------------------------------------------------------------------------------------

  /*
  13. "FNC_BUSCACREDITO_CODIGO"
  FUNÇÃO RETORNA O CREDITO DISPONIVEL PARA O CODIGO INFORMADO.
  */
  FUNCTION FNC_BUSCACREDITO_CODIGO( pfCODIGOCREDITO    IN NUMBER,
                                    psFILIAL           IN VARCHAR2
                                    )
  RETURN NUMBER IS
    vfVALORCREDITO NUMBER(14,2);
  BEGIN
    --VALIDANDO PARAMETROS DE ENTRADA!
    IF ((TRIM(psFILIAL) = '') OR (psFILIAL IS NULL)) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UMA FILIAL');
    END IF;

    IF (pfCODIGOCREDITO <= 0) OR (pfCODIGOCREDITO IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20016,'FAVOR INFORMAR UM CODIGO DE CREDITO VALIDO.');
    END IF;

    SELECT C.VALOR
    INTO vfVALORCREDITO
    FROM PCCRECLI C
    WHERE C.CODIGO =  pfCODIGOCREDITO
    AND   C.DTDESCONTO IS NULL
    AND   C.DTESTORNO IS NULL
    AND   C.SITUACAO IS NULL
    AND   ((PARAMFILIAL.OBTERCOMOVARCHAR2('USACREDCLITODASFILIAIS') = 'S') OR (C.CODFILIAL = psFILIAL));

    RETURN vfVALORCREDITO;
  END FNC_BUSCACREDITO_CODIGO;

----------------------------------------------------------------------------------------

END PKG_CREDITOCLIENTE;
