DECLARE
  iCOUNT Integer;
BEGIN

  FOR DADOS IN (
          SELECT 'AFEGANISTAO' NOME FROM DUAL UNION
          SELECT 'ALBANIA' NOME FROM DUAL UNION
          SELECT 'ALEMANHA' NOME FROM DUAL UNION
          SELECT 'BURKINA FASO' NOME FROM DUAL UNION
          SELECT 'ANDORRA' NOME FROM DUAL UNION
          SELECT 'ANGOLA' NOME FROM DUAL UNION
          SELECT 'ANGUILLA' NOME FROM DUAL UNION
          SELECT 'ANTIGUA E BARBUDA' NOME FROM DUAL UNION
          SELECT 'ANTILHAS HOLANDESAS' NOME FROM DUAL UNION
          SELECT 'ARABIA SAUDITA' NOME FROM DUAL UNION
          SELECT 'ARGELIA' NOME FROM DUAL UNION
          SELECT 'ARGENTINA' NOME FROM DUAL UNION
          SELECT 'ARMENIA' NOME FROM DUAL
  ) LOOP
  
    INSERT INTO PCTESTE (NOME) VALUES(DADOS.NOME);

  END LOOP;
  COMMIT;
END;