--05_PKG_SL_TRIGGER_GENERATOR.sql

CREATE OR REPLACE PACKAGE PKG_SL_TRIGGER_GENERATOR AS
    PROCEDURE GENERATE_FOR_ENTITY(p_entity_name IN VARCHAR2);
    PROCEDURE DROP_FOR_ENTITY(p_entity_name IN VARCHAR2);
END PKG_SL_TRIGGER_GENERATOR;
