  DECLARE
    TIPOCAMPO VARCHAR2(20);
  BEGIN
    SELECT DATA_TYPE
      INTO TIPOCAMPO
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PCMOVCOMPLE'
       AND COLUMN_NAME = 'INDDEDUZDESONERACAO';
  
    IF TIPOCAMPO = 'NUMBER' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PCMOVCOMPLE DROP COLUMN INDDEDUZDESONERACAO';
      EXECUTE IMMEDIATE 'ALTER TABLE PCMOVCOMPLE ADD INDDEDUZDESONERACAO VARCHAR2(1)';  
  
      UPDATE PCMOVCOMPLE SET INDDEDUZDESONERACAO = '0'
       WHERE NUMTRANSITEM IN (SELECT V.NUMTRANSITEM 
                                FROM PCMOV V
                               WHERE TO_CHAR(V.DTMOV, 'DD/MM/YYYY') >= '01/07/2024'   
                                AND V.ROTINALANC = 'AUTOSERVICO.FATURAMENTO.EXE');   
      COMMIT;
    END IF;
  END;
END;