CREATE OR REPLACE VIEW SQL_NFE_PARCELA_SAIDA_NORMAL AS 
SELECT PCPREST.NUMTRANSVENDA AS NUM_TRANSACAO,
       (TO_CHAR(PCPREST.DUPLIC) || ' - ' || TO_CHAR(PCPREST.PREST)) AS PRESTACAO,
       PCPREST.DUPLIC,
       PCPREST.PREST,
       DECODE(PCPREST.CODCOB,
              'VPP',
              PCPREST.DTEMISSAO,
              PCPREST.DTVENC) AS DTVENC,
       NVL(PCPREST.VALORENTFUT, PCPREST.VALOR) AS VALOR,
       PCPREST.CODCOB,
       NVL(PCPREST.VALORDESC, 0) AS VALORDESC,
       PCPREST.CODCOBSEFAZ,
       PCPREST.RAZAOCREDENCCARTAO AS RAZAO_CRED_CARTAO,
       PCPREST.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       PCPREST.NSUTEF AS NUMAUTOR_CARTAO,
       NVL(PCPREST.BANDEIRACARTAO, NVL(TO_NUMBER(PCCOB.CODBANDEIRAOPERADORACARTAO), 99)) AS BANDEIRA_CARTAO,
       NVL(PCPREST.CORRESPONDENTE, '2') AS TP_INTEGRA,
       PCPREST.DATACONSOLIDACAOPREFAT,
       'N' PREFATURAMENTO,
       PCCOB.INDPAG,
	   PCPREST.CNPJPAG,
       PCPREST.UFPAG,
       PCPREST.CNPJRECEB,
       PCPREST.IDTERMPAG
FROM   PCPREST, PCNFSAID, PCCOB
WHERE  PCPREST.STATUS = 'A'
AND    PCPREST.DTDESD IS NULL
AND    PCPREST.DTESTORNO IS NULL
AND    PCPREST.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
AND    PCPREST.CODCLI = PCNFSAID.CODCLI
AND    PCCOB.CODCOB = PCPREST.CODCOB
AND    ((NVL(PCNFSAID.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAID.CODFILIAL) = 'S'))
AND    NVL(PCPREST.VALOR, 0) > 0
AND    PCPREST.CODCOB NOT IN ('DESC', 'DESD', 'DEVP', 'DEVT', 'BNFM', 
                              'BNFI', 'BNTR', 'BNFN', 'BNFC', 'DH', 'D', 'TR')
     --códigos removidos por conta da nfe 4.00: 'BNF', 'BNFT', 'BNFR', 'BNTR','BNRP', 'CRED',
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(PCPREST.PERMITEESTORNO, 'S') = 'S'
UNION ALL
SELECT PCPRESTPREFAT.NUMTRANSVENDA AS NUM_TRANSACAO,
       (TO_CHAR(PCPRESTPREFAT.DUPLIC) || ' - ' || TO_CHAR(PCPRESTPREFAT.PREST)) AS PRESTACAO,
       PCPRESTPREFAT.DUPLIC,
       PCPRESTPREFAT.PREST,
       DECODE(PCPRESTPREFAT.CODCOB,
              'VPP',
              PCPRESTPREFAT.DTEMISSAO,
              PCPRESTPREFAT.DTVENC) AS DTVENC,
       NVL(PCPRESTPREFAT.VALORENTFUT, PCPRESTPREFAT.VALOR) AS VALOR,
       PCPRESTPREFAT.CODCOB,
       NVL(PCPRESTPREFAT.VALORDESC, 0) AS VALORDESC,
       PCPRESTPREFAT.CODCOBSEFAZ,
       PCPRESTPREFAT.RAZAOCREDENCCARTAO AS RAZAO_CRED_CARTAO,
       PCPRESTPREFAT.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO,
       PCPRESTPREFAT.NSUTEF AS NUMAUTOR_CARTAO,
       NVL(PCPRESTPREFAT.BANDEIRACARTAO, NVL(TO_NUMBER(PCCOB.CODBANDEIRAOPERADORACARTAO), 99)) AS BANDEIRA_CARTAO,
       NVL(PCPRESTPREFAT.CORRESPONDENTE, '2') AS TP_INTEGRA,
       PCPRESTPREFAT.DATACONSOLIDACAOPREFAT,
       'S' PREFATURAMENTO,
       PCCOB.INDPAG,
	   PCPRESTPREFAT.CNPJPAG,
       PCPRESTPREFAT.UFPAG,
       PCPRESTPREFAT.CNPJRECEB,
       PCPRESTPREFAT.IDTERMPAG
FROM   PCPRESTPREFAT, PCNFSAIDPREFAT, PCCOB
WHERE  PCPRESTPREFAT.STATUS = 'A'
AND    PCPRESTPREFAT.DTDESD IS NULL
AND    PCPRESTPREFAT.DTESTORNO IS NULL
AND    PCPRESTPREFAT.NUMTRANSVENDA = PCNFSAIDPREFAT.NUMTRANSVENDA
AND    PCPRESTPREFAT.CODCLI = PCNFSAIDPREFAT.CODCLI
AND    PCCOB.CODCOB = PCPRESTPREFAT.CODCOB
AND    PCPRESTPREFAT.CODCOB NOT IN ('DESC', 'DESD', 'DEVP', 'DEVT', 'BNFM')
AND    ((NVL(PCNFSAIDPREFAT.NUMCUPOM,0) = 0) OR (PARAMFILIAL.OBTERCOMOVARCHAR2('COBCUPOMNFE', PCNFSAIDPREFAT.CODFILIAL) = 'S'))
AND    NVL(PCPRESTPREFAT.VALOR, 0) > 0
AND    PCPRESTPREFAT.CODCOB NOT IN ('DESC', 'DESD', 'DEVP', 'DEVT', 'BNFM', 
                                    'BNFI', 'BNTR', 'BNFN', 'BNFC', 'DH', 'D', 'TR')
     --códigos removidos por conta da nfe 4.00: 'BNF', 'BNFT', 'BNFR', 'BNTR','BNRP', 'CRED',
AND   NVL(PCCOB.CARTAO,'N') = 'N'
AND   NVL(PCPRESTPREFAT.PERMITEESTORNO, 'S') = 'S'
AND   PCPRESTPREFAT.DATACONSOLIDACAOPREFAT IS NULL
