CREATE OR REPLACE VIEW SQL_NFE_REF_SAIDA_DEVAVUL AS
SELECT PCNFSAID.NUMTRANSVENDA AS NUM_TRANSACAO,
       UF_E.UF AS SIGLA_UF,
       REPLACE(REPLACE(REPLACE(EMITENTE.CGC,'.',''),'/',''),'-','') AS CNPJ_E,
       PCDEVAVULSO.DTEMISSAO AS DATA_EMISSAO,
       NULL AS CHAVE_ACESSO,
       '01' AS MODELO,
       DECODE(NVL(PCDEVAVULSO.SERIE,
                  'U'),
              'U',
              '0',
              PCDEVAVULSO.SERIE) AS SERIE,
       PCDEVAVULSO.NUMNOTA AS NUMERO_NOTA
FROM   PCNFSAID,
       PCFORNEC EMITENTE,
       PCESTADO UF_E,
       PCCIDADE CIDADE_E,
       PCFILIAL,
       PCDEVAVULSO
WHERE  NVL(PCNFSAID.CODFILIALNF,
           PCNFSAID.CODFILIAL) = PCFILIAL.CODIGO
AND    PCFILIAL.CODFORNEC = EMITENTE.CODFORNEC
AND    EMITENTE.CODCIDADE = CIDADE_E.CODCIDADE
AND    PCNFSAID.SERIE <> 'CF'
AND    CIDADE_E.UF = UF_E.UF
AND    PCNFSAID.NUMTRANSVENDA = PCDEVAVULSO.NUMTRANSVENDA 