declare 
  vContIdx NUMBER;
  vEXEC    VARCHAR2(4000);  
begin
  vContIdx := 0;
  vEXEC    := '';  
  SELECT COUNT(1)
    INTO vContIdx
    FROM ALL_INDEXES I
  WHERE I.TABLE_NAME = 'PCORDEMAPURACAOCOMIS' AND I.INDEX_NAME = 'PCORDEMAPURACAOCOMIS_PK';

  IF (vContIdx > 0) THEN
    vEXEC := 'DROP INDEX PCORDEMAPURACAOCOMIS_PK';
    EXECUTE IMMEDIATE vEXEC;
    vEXEC := 'ALTER TABLE PCORDEMAPURACAOCOMIS ADD CONSTRAINT PCORDEMAPURACAOCOMIS_PK PRIMARY KEY (CODFILIAL, CODCOMIS)';
  END IF; 
end;