declare 
  vContIdx NUMBER;
  vContPk NUMBER;
  vEXEC    VARCHAR2(4000);  
begin
  vContIdx := 0;
  vContPk  := 0;
  vEXEC    := '';  
  SELECT COUNT(1)
    INTO vContIdx
    FROM USER_INDEXES I
  WHERE I.TABLE_NAME = 'PCORDEMAPURACAOCOMIS' AND I.INDEX_NAME = 'PCORDEMAPURACAOCOMIS_PK';

  select count(1) 
    INTO vContPk
    from user_constraints where constraint_name = 'PCORDEMAPURACAOCOMIS_PK';

  IF (vContIdx > 0) AND (vContPk = 0) THEN
    vEXEC := 'DROP INDEX PCORDEMAPURACAOCOMIS_PK';
    EXECUTE IMMEDIATE vEXEC;
    vEXEC := 'ALTER TABLE PCORDEMAPURACAOCOMIS ADD CONSTRAINT PCORDEMAPURACAOCOMIS_PK PRIMARY KEY (CODFILIAL, CODCOMIS)';
    EXECUTE IMMEDIATE vEXEC;
  END IF;
  
  SELECT count(1) into vContPk
  FROM USER_CONS_COLUMNS
  WHERE TABLE_NAME = 'PCORDEMAPURACAOCOMIS'
  AND CONSTRAINT_NAME = (SELECT CONSTRAINT_NAME
                         FROM USER_CONSTRAINTS
                         WHERE TABLE_NAME = 'PCORDEMAPURACAOCOMIS'
                         AND CONSTRAINT_TYPE = 'P');                        
  IF(vContPk = 1) then
     vEXEC := 'ALTER TABLE PCORDEMAPURACAOCOMIS DROP CONSTRAINT PCORDEMAPURACAOCOMIS_PK';
     EXECUTE IMMEDIATE vEXEC;
     vEXEC := 'ALTER TABLE PCORDEMAPURACAOCOMIS ADD CONSTRAINT PCORDEMAPURACAOCOMIS_PK PRIMARY KEY (CODFILIAL, CODCOMIS)';
     EXECUTE IMMEDIATE vEXEC;  
  END IF; 
  IF(vContPk = 0) then
     vEXEC := 'ALTER TABLE PCORDEMAPURACAOCOMIS ADD CONSTRAINT PCORDEMAPURACAOCOMIS_PK PRIMARY KEY (CODFILIAL, CODCOMIS)';
     EXECUTE IMMEDIATE vEXEC;  
  END IF;   
end;


