BEGIN
    DELETE FROM PCPARAMINTEGRACAOWMSSAAS
    WHERE PARAMETRO IN ('RETIRAR_SOMA_QUANTIDADE_AVARIA_NO_INVENTARIO');

    DELETE FROM PCPARAMINTEGRACAOWMSSAASROTULO
    WHERE PARAMETRO IN ('RETIRAR_SOMA_QUANTIDADE_AVARIA_NO_INVENTARIO');
    COMMIT;
END;