DECLARE
  V_CONTADOR NUMBER;
BEGIN

  UPDATE PCESTRUTURALAYOUTREGISTRO
     SET NOME = 'HEADER LOTE'
   WHERE CODIGO = 2
     AND ORDEM = 2;
  SELECT COUNT(*) AS CONTADOR
    INTO V_CONTADOR
    FROM PCESTRUTURALAYOUTREGISTRO
   WHERE CODIGO = 1
     AND CODIGO_ESTRUTURA = 1;
  IF (V_CONTADOR <= 0) THEN
    BEGIN
      INSERT INTO PCESTRUTURALAYOUTREGISTRO
        (CODIGO, CODIGO_ESTRUTURA, NOME, ORDEM)
      VALUES
        (1, 1, 'HEADER ARQUIVO', 1);
    END;
  END IF;

  COMMIT;
END;