DECLARE  VN_CODGRUPO PCGRUPOAVARIA.CODGRUPO%TYPE;
  V_SQL VARCHAR2(1000);BEGIN
  
 SELECT (MAX(NVL(PCGRUPOAVARIA.CODGRUPO, 0)) + 1)
   INTO  VN_CODGRUPO
 FROM PCGRUPOAVARIA; 
 
  V_SQL := 'CREATE SEQUENCE DFSEQ_PCGRUPOAVARIA ' ||
           ' MINVALUE 1 ' ||
           ' MAXVALUE 999999999999999999999999999 ' ||
           ' START WITH ' || VN_CODGRUPO || 
           ' INCREMENT BY 1 ' ||
           ' NOCACHE';  -- Execução do comando
  EXECUTE IMMEDIATE V_SQL; 
 
END;