DECLARE
  VN_CODGRUPO NUMBER;
  V_SQL       VARCHAR2(1000);
BEGIN
  SELECT NVL(MAX(TO_NUMBER(CODGRUPO)), 0) + 1
    INTO VN_CODGRUPO
    FROM PCGRUPOAVARIA
   WHERE REGEXP_LIKE(TRIM(CODGRUPO), '^[0-9]+$');

  V_SQL := 'CREATE SEQUENCE DFSEQ_PCGRUPOAVARIA ' ||
           'START WITH ' || VN_CODGRUPO || ' ' ||
           'INCREMENT BY 1 ' ||
           'MINVALUE 1 ' ||
           'NOCACHE';

  EXECUTE IMMEDIATE V_SQL;
END;