DECLARE
  vExiste VARCHAR2(1);
BEGIN
  BEGIN
    SELECT 'S'
      INTO vExiste
      FROM PCROTINATABELA
     WHERE CODROTINA = 2356
       AND NOMEOBJETO = 'PCCLIUSURFILIALLINHAPROD';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      vExiste := 'N';
  END; 
  IF vExiste = 'N' THEN
    INSERT INTO PCROTINATABELA(CODROTINA,NOMEOBJETO,USARCADGENERICO,WHEREADICIONALPESQ,PERMITEINCLUIR,PERMITEALTERAR,PERMITEEXCLUIR,TITULOROTINA,ATUALIZARPERMISSAO)
    VALUES (2356,'PCCLIUSURFILIALLINHAPROD' ,'N', NULL, 'S', 'S', 'S', 'RCA do Cliente por Filial e Linha Prod','S');
    COMMIT;
  END IF;


  BEGIN
    SELECT 'S'
      INTO vExiste
      FROM PCROTINAI
     WHERE CODROTINA = 2356
       AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      vExiste := 'N';
  END; 
  IF vExiste = 'N' THEN
    INSERT INTO PCROTINAI(CODROTINA,CODCONTROLE,DESCRICAO) SELECT 2356, CODCONTROLE, DESCRICAO FROM PCROTINAI WHERE CODROTINA = 203 AND CODCONTROLE BETWEEN 101 AND 110;
    COMMIT;
  END IF;    
END;