DECLARE
BEGIN
  BEGIN  
    INSERT INTO PCROTINATABELA(CODROTINA,NOMEOBJETO,USARCADGENERICO,WHEREADICIONALPESQ,PERMITEINCLUIR,PERMITEALTERAR,PERMITEEXCLUIR,TITULOROTINA,ATUALIZARPERMISSAO)
    VALUES (2356,'PCCLIUSURFILIALLINHAPROD' ,'N',                         NULL,              'S', 'S', 'S',                               'RCA do Cliente por Filial e Linha Prod','S');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;    

  BEGIN  
    INSERT INTO PCROTINAI(CODROTINA,CODCONTROLE,DESCRICAO) SELECT 2356, CODCONTROLE, DESCRICAO FROM PCROTINAI WHERE CODROTINA = 2329 AND CODCONTROLE BETWEEN 101 AND 108;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;    

  COMMIT;
END;
