DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PCCLIENTENDENT'
     AND COLUMN_NAME = 'IERECEBEDOR'
     AND DATA_TYPE = 'VARCHAR2'
     AND DATA_LENGTH = 15;

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PCCLIENTENDENT ADD IERECEBEDOR_TMP VARCHAR2(15)';
    EXECUTE IMMEDIATE 'UPDATE PCCLIENTENDENT SET IERECEBEDOR_TMP = TO_CHAR(IERECEBEDOR)';
    EXECUTE IMMEDIATE 'ALTER TABLE PCCLIENTENDENT DROP COLUMN IERECEBEDOR';
    EXECUTE IMMEDIATE 'ALTER TABLE PCCLIENTENDENT RENAME COLUMN IERECEBEDOR_TMP TO IERECEBEDOR';
  END IF;
END;