-- 08_PKG_SL_BACKGROUND_PROCESS.sql
-- Descrição: Processa solicitações de rotação de log de forma assíncrona.

CREATE OR REPLACE PACKAGE PKG_SL_BACKGROUND_PROCESS AS
    PROCEDURE PROCESS_ROTATION_REQUESTS;
END PKG_SL_BACKGROUND_PROCESS;

