CREATE OR REPLACE FUNCTION F_OBRIGARECEITUARIOAGRICOLA(pi_nCodProd IN NUMBER)
  RETURN VARCHAR2 IS

  VSOBRIGARECEITUARIOAGRICOLA VARCHAR2(1) := 'N';
BEGIN
  SELECT NVL(D.OBRIGARECEITUARIOAGRICOLA, 'N') OBRIGARECEITUARIOAGRICOLA
    INTO VSOBRIGARECEITUARIOAGRICOLA
    FROM PCNCM D, PCPRODUT T
   WHERE T.CODNCMEX = D.CODNCMEX
     AND T.CODPROD = pi_nCodProd
     AND D.DTEXCLUSAO IS NULL
     AND ROWNUM = 1;

  RETURN VSOBRIGARECEITUARIOAGRICOLA;
  
  EXCEPTION
    WHEN OTHERS THEN
      VSOBRIGARECEITUARIOAGRICOLA := 'N';

END F_OBRIGARECEITUARIOAGRICOLA;