DECLARE
  v_exists NUMBER;
  v_codagendadortarefa NUMBER;
  v_codagendadormalha NUMBER;  
BEGIN
   SELECT COUNT(1)
     INTO v_exists
     FROM DUAL
    WHERE EXISTS (SELECT 1
                    FROM PCAGENDADORTAREFA t
                   WHERE t.ARTEFATO = 'C:\pcsist\produtos\agendador\apps\PCSISAGD3390.exe'
                     AND t.CODMODULO = 0)
       OR EXISTS (SELECT 1
                    FROM PCAGENDADORMALHA m
                   WHERE m.DESCRICAO = 'RESTRIÇÃO AVANÇADA AUTOMATICA');
  
  IF v_exists = 0 THEN	
	INSERT INTO PCAGENDADORTAREFA (
	  CODAGENDADORTAREFA, 
	  ARTEFATO, 
	  CODMODULO
	) VALUES (
	  DFSEQ_PCAGENDADORTAREFA.NEXTVAL, 
	  'C:\pcsist\produtos\agendador\apps\PCSISAGD3390.exe', 
	  0
	)
	RETURNING CODAGENDADORTAREFA
	INTO v_codagendadortarefa;
	 
	INSERT INTO	PCAGENDADORMALHA (
      CODAGENDADORMALHA,
      DESCRICAO,
      DATAVIGENCIAINICIAL,
      DATAVIGENCIAFINAL,
      CRIADOSISTEMA,
      LIMITEPERIODO,
      TIPOEXECUCAO
    ) VALUES (
      DFSEQ_PCAGENDADORMALHA.NEXTVAL,
      'RESTRIÇÃO AVANÇADA AUTOMATICA',
      SYSTIMESTAMP,
      ADD_MONTHS(SYSTIMESTAMP, 12),
      'S',
      NULL,
      NULL
	)
    RETURNING CODAGENDADORMALHA
	INTO v_codagendadormalha;
	 
	INSERT INTO	PCAGENDADORMALHATAREFA (
      CODAGENDADORMALHATAREFA,
      CODAGENDADORMALHA,
      CODAGENDADORTAREFA,
      PASSO,
      DELAY
    ) VALUES (
      DFSEQ_PCAGENDADORMALHATAREFA.NEXTVAL,
      v_codagendadormalha,
      v_codagendadortarefa,
      1,
      NULL
    );
	 
	INSERT INTO	PCAGENDADORCONFIGURACAO (
      CODAGENDADORCONFIGURACAO,
      CODAGENDADORMALHA,
      CRON,
      SITUACAO,
      EXECUCAOMANUAL
    ) VALUES (
      DFSEQ_PCAGENDADORCONFIGURACAO.NEXTVAL,
      v_codagendadormalha,
      '* * * * * * 0 *',
      'A',
      'N'
    );
  END IF;
END;
