CREATE OR REPLACE VIEW VW_INT_C5_LIM_CRED_CLIENTE AS
(
SELECT C.CODCLI SEQPESSOA, 
       F.CODFINALIZADORA NROFORMAPAGTO,
       0 VLRLIMITE,
       0 VLRUTILIZADO,
       'L' SITUACAOCREDITO,
       'N' COBRATAXA,
       CASE
         WHEN C.DTEXCLUSAO IS NULL THEN
              'S'
         ELSE 'N'     
       END ATIVO,
       NULL VLRLIMITEPARCELADO    
FROM PCCLIENT C, 
     MONITORPDVMIDDLE.TB_CLIENTE TC,
     (SELECT DISTINCT * FROM PCFINALIZADORA FIN, VW_INT_C5_OBTER_FILIAIS_C5 C5 WHERE FIN.CODFILIAL = C5.CODFILIAL) F, 
     (select s.ultimaexecucao from pccontroleconsinco s where upper(s.objetoreferencia) = 'PKG_SINC_PDV_CONSINCO.CARREGA_TB_CLIENTECREDITO') DTPADRAO
WHERE 0 = 0 
AND  TC.SEQPESSOA = C.CODCLI  
AND C.CODCLI NOT IN(1,2,3)
AND F.VERIFICALIMITE = 'S' 
AND ((C.LIMCRED > 0) OR (C.CODCLI IN (SELECT DISTINCT CODCLI FROM PCLIMCREDCOB WHERE LIMCRED > 0)))
AND GREATEST(NVL(C.dtalterc5, DTPADRAO.ULTIMAEXECUCAO),
             NVL(F.dtalterc5, DTPADRAO.ULTIMAEXECUCAO)
            ) >= DTPADRAO.ULTIMAEXECUCAO

)
