DECLARE

BEGIN 
  MERGE INTO PCFILTROAVANCADOLAYOUTC tgt
  USING (
    SELECT 1 AS CODLAYOUT, 'Layout Rotina 3391' AS DESCRICAO FROM DUAL
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT)
   WHEN MATCHED THEN UPDATE SET
     tgt.DESCRICAO = src.DESCRICAO
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, DESCRICAO) VALUES (src.CODLAYOUT, src.DESCRICAO);
    
  MERGE INTO PCFILTROAVANCADOLAYOUTI tgt
  USING (
    SELECT 1 AS CODLAYOUT, 
           CODCONFIG 
      FROM PCFILTROAVANCADOCONFIG 
     WHERE TIPOCAMPO <> 'NIVEL' 
       AND CODCONFIG BETWEEN 1 AND 100
  ) src 
     ON (tgt.CODLAYOUT = src.CODLAYOUT AND tgt.CODCONFIG = src.CODCONFIG)
   WHEN NOT MATCHED THEN
     INSERT (CODLAYOUT, CODCONFIG) VALUES (src.CODLAYOUT, src.CODCONFIG);
END;