CREATE OR REPLACE TRIGGER T_MONITOR_DFES_PRESOS_PCNFSAID
  BEFORE INSERT OR UPDATE OF ESPECIE, SITUACAONFE ON PCNFSAID
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  VQTDREG   NUMBER(10);
  VTIPODOC  VARCHAR2(2);
  VSITUACAO NUMBER(5);
  VREJEITADOSEFAZ VARCHAR2(1) := 'N';
  CTIPOMOV  VARCHAR2(1) := 'S';

  procedure GERAR_LOG(VNUMTRANSACAO IN NUMBER,
                      VTIPOMOV      IN VARCHAR2,
                      VTIPODOC      IN VARCHAR2,
                      VLOG          IN VARCHAR2) is
  begin
    insert into PCMONITORDFESPRESOSLOG
      (NUMTRANSACAO,
       TIPOMOV,
       TIPODOC,
       DATA,
       LOG,
       TERMINAL,
       MAQUINA,
       PROGRAMA,
       OSUSER)
    values
      (VNUMTRANSACAO,
       VTIPOMOV,
       VTIPODOC,
       SYSDATE,
       VLOG,
       SYS_CONTEXT('USERENV', 'TERMINAL'),
       SYS_CONTEXT('USERENV', 'HOST'),
       SYS_CONTEXT('USERENV', 'MODULE'),
       SYS_CONTEXT('USERENV', 'OS_USER'));
  end;

BEGIN
    IF (NVL(:NEW.ESPECIE, :OLD.ESPECIE) IN ('NE', 'NF')) THEN
      VTIPODOC  := 'NF';  
      VSITUACAO := :NEW.SITUACAONFE;
      VREJEITADOSEFAZ := NVL(:NEW.REJEITADOSEFAZ, 'N');
    ELSE
      RETURN;  
    END IF;

  IF UPDATING THEN 
    IF (VTIPODOC IS NOT NULL AND (VSITUACAO IN (103, 1) OR (VSITUACAO = 1001 AND VREJEITADOSEFAZ = 'N'))) THEN
      GERAR_LOG(:OLD.NUMTRANSVENDA, CTIPOMOV, VTIPODOC,
                VTIPODOC || ' EM PROCESSAMENTO, SITUAÇÃO ' || VSITUACAO);

      UPDATE PCMONITORDFESPRESOS
         SET DATAULTIMAALTERACAO = SYSDATE,
             ULTIMA_SITUACAO = VSITUACAO
       WHERE NUMTRANSACAO = :OLD.NUMTRANSVENDA
         AND TIPODOC = VTIPODOC
         AND TIPOMOV = CTIPOMOV;

      IF (SQL%ROWCOUNT = 0) THEN
        INSERT INTO PCMONITORDFESPRESOS (NUMTRANSACAO, TIPOMOV, TIPODOC, DATAULTIMAALTERACAO, ULTIMA_SITUACAO)
        VALUES(:OLD.NUMTRANSVENDA, CTIPOMOV, VTIPODOC, SYSDATE, VSITUACAO);
      END IF;
    ELSIF (VSITUACAO = 100) THEN
      GERAR_LOG(:OLD.NUMTRANSVENDA, CTIPOMOV, VTIPODOC, VTIPODOC || ' APROVADA!');
    
      DELETE FROM PCMONITORDFESPRESOS
       WHERE NUMTRANSACAO = :OLD.NUMTRANSVENDA
         AND TIPODOC = VTIPODOC
         AND TIPOMOV = CTIPOMOV;
    END IF;
  ELSIF INSERTING THEN
    IF (:NEW.SITUACAONFE = 100) OR (:NEW.SITUACAOCTE = 100)  THEN
      GERAR_LOG(:NEW.NUMTRANSVENDA, CTIPOMOV, 'NF', 'NF' || ' APROVADA!');
    
      DELETE FROM PCMONITORDFESPRESOS
       WHERE NUMTRANSACAO = :NEW.NUMTRANSVENDA
         AND TIPODOC = VTIPODOC
         AND TIPOMOV = CTIPOMOV;       
    END IF;
  END IF;
END;
