DECLARE
  vNUMPED          VARCHAR2(10); --VARIAVEL P/NUMERO DO PEDIDO
  vCODPROD         VARCHAR2(10); --VARIAVEL P/O CÓDIGO DO PRODUTO
  vNUMLOTE         VARCHAR2(50); --VARIAVEL P/NUMERO DO LOTE
  vNUMCAR          VARCHAR2(50); --VARIAVEL P/NUMERO DO CARREGAMENT
  vNUMNOTA         VARCHAR2(50); --VARIAVEL P/NUMERO DA NOTA 
  vCODFILIAL       VARCHAR2(2);  --VARIAVEL P/FILIAL
  vCONTADOR        INT;          --VARIAVEL P/O CONTADOR  
  vQT              NUMBER(10, 0);--VARIAVEL P/QT
  vCODOPER         VARCHAR2(10);
  vCODCLI          VARCHAR2(10);
  vCODFILIALORIGEM VARCHAR2(2);
  vPVENDA          VARCHAR2(20);
  vQTAVARIA        VARCHAR2(20);
  vQTBLOQUEADA     VARCHAR2(20);
  vQTBOX           VARCHAR2(20);
  vQTCX            VARCHAR2(20);
  vQTCXORIG        VARCHAR2(20);
  vQTPALETE        VARCHAR2(20);
  vQTPECAS         VARCHAR2(20);
  vQTPECASORIG     VARCHAR2(20);
  vQTTOTPALCX      VARCHAR2(20);
  vQTUN            VARCHAR2(20);
  vQTUNITCX        VARCHAR2(20);
  vTOTPESO         VARCHAR2(20);
  vTOTVOLUME       VARCHAR2(20);
  vNUMTRANSWMS     VARCHAR2(20);
  vNUMTRANSVENDA   VARCHAR2(20);
  v_ERORRCODE      NUMBER;
  vLOG_GRAVADO     VARCHAR2(1);
  v_ERRMSG         VARCHAR2(64); 
  
  PROCEDURE LimparVariaveis 
  AS
  BEGIN
    vLOG_GRAVADO := 'N';
    
    IF (vNUMPED > 0) AND (vLOG_GRAVADO = 'N') THEN
      EXECUTE IMMEDIATE 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || vNUMPED || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || vCODPROD || ', ' ||  vNUMLOTE || ', ' || vCODFILIAL || ')';
      DELETE FROM PCWMS WHERE NUMPED = vNUMPED AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;
    
    IF (vNUMNOTA > 0) AND (vLOG_GRAVADO = 'N') THEN
      EXECUTE IMMEDIATE 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || vNUMPED || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || vCODPROD || ', ' ||  vNUMLOTE || ', ' || vCODFILIAL || ')';
      DELETE FROM PCWMS WHERE NUMNOTA = vNUMNOTA AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;
    
    IF vNUMTRANSVENDA > 0 AND (vLOG_GRAVADO = 'N') THEN
      EXECUTE IMMEDIATE 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || vNUMPED || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || vCODPROD || ', ' ||  vNUMLOTE || ', ' || vCODFILIAL || ')';
      DELETE FROM PCWMS WHERE NUMTRANSVENDA = vNUMTRANSVENDA AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;    
    
    vQT              := 0; 
    vQTAVARIA        := 0;
    vQTBLOQUEADA     := 0;
    vQTBOX           := 0;
    vQTCX            := 0;
    vQTCXORIG        := 0;
    vQTPALETE        := 0;
    vQTPECAS         := 0;
    vQTPECASORIG     := 0;
    vQTTOTPALCX      := 0;
    vQTUN            := 0;
    vQTUNITCX        := 0;
    vTOTPESO         := 0;
    vTOTVOLUME       := 0;      
    vNUMNOTA         := 0;
    vNUMCAR          := 0;
    vLOG_GRAVADO     := 'N';
  END LimparVariaveis;
  
  PROCEDURE BKP_PCWMS_MIGRACAO
  AS
  BEGIN
    DECLARE
      V_TABELA_EXISTE NUMBER DEFAULT 0;        
    BEGIN

      SELECT COUNT(*)
        INTO V_TABELA_EXISTE
        FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME = 'PC_BKP_MIGRACAO_PCWMS_ORIGINAL';
         
       IF V_TABELA_EXISTE = 0 THEN
         RAISE_APPLICATION_ERROR(-20001, 'Tabela PC_BKP_MIGRACAO_PCWMS_ORIGINAL não criada.');
       ELSE                  --FAZENDO BKP DA TABELA INTEIRA
         EXECUTE IMMEDIATE 'INSERT INTO PC_BKP_MIGRACAO_PCWMS_ORIGINAL SELECT * FROM PCWMS WHERE 1 = 1';
         COMMIT;
       END IF;
         
      SELECT COUNT(*)
        INTO V_TABELA_EXISTE
        FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME = 'PC_BKP_MIGRACAO_PCWMS';
         
       IF V_TABELA_EXISTE = 0 THEN
         RAISE_APPLICATION_ERROR(-20001, 'Tabela PC_BKP_MIGRACAO_PCWMS não criada.');
       END IF;
         
      SELECT COUNT(*)
        INTO V_TABELA_EXISTE
        FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME = 'PC_LOG_MIGRACAO_PCWMS';
         
       IF V_TABELA_EXISTE = 0 THEN
         RAISE_APPLICATION_ERROR(-20001, 'Tabela PC_LOG_MIGRACAO_PCWMS não criada.');
       END IF;           
      
    END;  
  END BKP_PCWMS_MIGRACAO;
  
  FUNCTION ADICIONA_DADOS_TRATADOS RETURN BOOLEAN
  IS
  BEGIN
    DECLARE vSQL VARCHAR2(4000);
    BEGIN
      vSQL := 'INSERT INTO PC_BKP_MIGRACAO_PCWMS (NUMPED, CODPROD, NUMLOTE, NUMCAR, NUMNOTA, CODFILIAL, QT, CODOPER, CODCLI, CODFILIALORIGEM, PVENDA, QTAVARIA, NUMTRANSWMS,
                       QTBLOQUEADA, QTBOX, QTCX, QTCXORIG, QTPALETE, QTPECAS, QTPECASORIG, QTTOTPALCX, QTUN, QTUNITCX, TOTPESO, TOTVOLUME, NUMTRANSVENDA)
               VALUES (' || vNUMPED || ',' || vCODPROD || ',' || vNUMLOTE || ',' || NVL(vNUMCAR, 0) || ',' ||  vNUMNOTA || ',' ||  vCODFILIAL || ',' ||  vQT || ',' ||  '''' || vCODOPER || '''' || ',' ||  NVL(vCODCLI, 0) || ',' ||  NVL(vCODFILIALORIGEM, vCODFILIAL) || ',' ||  NVL(vPVENDA, 0) || ',' ||  vQTAVARIA || ',' ||  vNUMTRANSWMS || ',' || 
                       vQTBLOQUEADA || ',' ||  vQTBOX || ',' ||  vQTCX || ',' ||  vQTCXORIG || ',' ||  vQTPALETE || ',' ||  vQTPECAS || ',' ||  vQTPECASORIG || ',' ||  vQTTOTPALCX || ',' ||  vQTUN || ',' ||  vQTUNITCX || ',' ||  vTOTPESO || ',' ||  vTOTVOLUME || ',' ||  NVL(vNUMTRANSVENDA, 0) || ')';
                       
    EXECUTE IMMEDIATE vSQL;
    COMMIT;                       
   END;
    
    RETURN TRUE;   
    
  END ADICIONA_DADOS_TRATADOS;

BEGIN  
  
  BKP_PCWMS_MIGRACAO;

  DECLARE
    CURSOR CUR_PEDIDO IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO
        FROM PCWMS
       WHERE (NUMPED, CODPROD, CODFILIAL) IN 
             (SELECT NUMPED, CODPROD, CODFILIAL
                FROM PCWMS
               WHERE NVL(NUMPED, 0) > 0
               GROUP BY NUMPED, CODPROD, NUMLOTE, DTENT, NUMTRANSENT, CODFILIAL)
       ORDER BY NUMPED, CODPROD, CODFILIAL, NUMCAR DESC;
  
  BEGIN  
  
    vCONTADOR := 0;
    vNUMPED   := 0;
    FOR CUR_PEDIDO_REC IN CUR_PEDIDO LOOP
      IF vNUMPED > 0 THEN
        IF (vNUMPED <> CUR_PEDIDO_REC.NUMPED) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMPED = CUR_PEDIDO_REC.NUMPED) AND (vCODPROD <> CUR_PEDIDO_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := NVL(CUR_PEDIDO_REC.NUMPED, vNUMPED);
      vCODPROD         := NVL(CUR_PEDIDO_REC.CODPROD, vCODPROD);
      vNUMLOTE         := NVL(CUR_PEDIDO_REC.NUMLOTE, vNUMLOTE);
      
      IF NVL(CUR_PEDIDO_REC.NUMCAR, 0) = 0 THEN
        vNUMCAR := vNUMCAR;
      ELSE 
        IF NVL(CUR_PEDIDO_REC.NUMCAR, 0) > 0 THEN
          vNUMCAR := CUR_PEDIDO_REC.NUMCAR;
        ELSE
          vNUMCAR := vNUMCAR;
        END IF;
      END IF;
      
      IF NVL(CUR_PEDIDO_REC.NUMNOTA, 0) = 0 THEN 
        vNUMNOTA := vNUMNOTA;
      ELSE
        IF NVL(CUR_PEDIDO_REC.NUMNOTA, 0) > 0 THEN
          vNUMNOTA := CUR_PEDIDO_REC.NUMNOTA;
        ELSE
          vNUMNOTA := vNUMNOTA;
        END IF;
      END IF;
      
      vCODFILIAL       := NVL(CUR_PEDIDO_REC.CODFILIAL, vCODFILIAL);
      vQT              := REPLACE(NVL(VQT, 0) + NVL(CUR_PEDIDO_REC.QT, NVL(VQT, 0)), ',', '.');
      vCODOPER         := NVL(CUR_PEDIDO_REC.CODOPER, vCODOPER);      
      vCODCLI          := NVL(CUR_PEDIDO_REC.CODCLI, vCODCLI);
      vCODFILIALORIGEM := NVL(CUR_PEDIDO_REC.CODFILIALORIGEM, vCODFILIALORIGEM);
      
      IF NVL(CUR_PEDIDO_REC.PVENDA, 0) = 0 THEN 
        vPVENDA := vPVENDA;
      ELSE
        IF NVL(CUR_PEDIDO_REC.PVENDA, 0) > 0 THEN
          vPVENDA := CUR_PEDIDO_REC.PVENDA;
        ELSE
          vPVENDA := vPVENDA;
        END IF;
      END IF;
      
      vQTAVARIA        := REPLACE(NVL(VQTAVARIA, 0) + NVL(CUR_PEDIDO_REC.QTAVARIA, NVL(VQTAVARIA, 0)), ',', '.');
      vQTBLOQUEADA     := REPLACE(NVL(VQTBLOQUEADA, 0) + NVL(CUR_PEDIDO_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0)), ',', '.');
      vQTBOX           := REPLACE(NVL(VQTBOX, 0) + NVL(CUR_PEDIDO_REC.QTBOX, NVL(VQTBOX, 0)), ',', '.');
      vQTCX            := REPLACE(NVL(VQTCX, 0) + NVL(CUR_PEDIDO_REC.QTCX, NVL(VQTCX, 0)), ',', '.');
      vQTCXORIG        := REPLACE(NVL(VQTCXORIG, 0) + NVL(CUR_PEDIDO_REC.QTCXORIG, NVL(VQTCXORIG, 0)), ',', '.');
      vQTPALETE        := REPLACE(NVL(VQTPALETE, 0) + NVL(CUR_PEDIDO_REC.QTCXORIG, NVL(VQTPALETE, 0)), ',', '.');
      vQTPECAS         := REPLACE(NVL(VQTPECAS, 0) + NVL(CUR_PEDIDO_REC.QTPECAS, NVL(VQTPECAS, 0)), ',', '.');
      vQTPECASORIG     := REPLACE(NVL(VQTPECASORIG, 0) + NVL(CUR_PEDIDO_REC.QTPECASORIG, NVL(VQTPECASORIG, 0)), ',','.');
      vQTTOTPALCX      := REPLACE(NVL(VQTTOTPALCX, 0) + NVL(CUR_PEDIDO_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0)), ',', '.') ;
      vQTUN            := REPLACE(NVL(VQTUN, 0) + NVL(CUR_PEDIDO_REC.QTUN, NVL(VQTUN, 0)), ',', '.');
      vQTUNITCX        := REPLACE(NVL(VQTUNITCX, 0) + NVL(CUR_PEDIDO_REC.QTUNITCX, NVL(VQTUNITCX, 0)), ',', '.');
      vTOTPESO         := REPLACE(NVL(VTOTPESO, 0) + NVL(CUR_PEDIDO_REC.TOTPESO, NVL(VTOTPESO, 0)), ',', '.');
      vTOTVOLUME       := REPLACE(NVL(VTOTVOLUME, 0) + NVL(CUR_PEDIDO_REC.TOTVOLUME, NVL(VTOTVOLUME, 0)), ',', '.');
      vNUMTRANSWMS     := NVL(CUR_PEDIDO_REC.NUMTRANSWMS, 0);
      vCONTADOR        := vCONTADOR + 1;


    END LOOP;
    LimparVariaveis;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END;
       
  DECLARE
    CURSOR CUR_NOTA IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO
        FROM PCWMS
       WHERE (NUMNOTA, CODPROD, CODFILIAL) IN 
             (SELECT NUMNOTA, CODPROD, CODFILIAL
                FROM PCWMS
               WHERE NVL(NUMNOTA, 0) > 0
               GROUP BY NUMNOTA, CODPROD, NUMLOTE, DTENT, NUMTRANSENT, CODFILIAL)
       ORDER BY NUMNOTA, CODPROD, CODFILIAL, NUMCAR DESC;     
  
  BEGIN
    vCONTADOR := 0;
    vNUMNOTA   := 0;
    FOR CUR_NOTA_REC IN CUR_NOTA LOOP
      IF vNUMNOTA > 0 THEN
        IF (vNUMNOTA <> CUR_NOTA_REC.NUMNOTA) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMNOTA = CUR_NOTA_REC.NUMNOTA) AND (vCODPROD <> CUR_NOTA_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := NVL(CUR_NOTA_REC.NUMPED, vNUMPED);
      vCODPROD         := NVL(CUR_NOTA_REC.CODPROD, vCODPROD);
      vNUMLOTE         := NVL(CUR_NOTA_REC.NUMLOTE, vNUMLOTE);
      
      IF NVL(CUR_NOTA_REC.NUMCAR, 0) = 0 THEN
        vNUMCAR := vNUMCAR;
      ELSE 
        IF NVL(CUR_NOTA_REC.NUMCAR, 0) > 0 THEN
          vNUMCAR := CUR_NOTA_REC.NUMCAR;
        ELSE
          vNUMCAR := vNUMCAR;
        END IF;
      END IF;
      
      IF NVL(CUR_NOTA_REC.NUMNOTA, 0) = 0 THEN 
        vNUMNOTA := vNUMNOTA;
      ELSE
        IF NVL(CUR_NOTA_REC.NUMNOTA, 0) > 0 THEN
          vNUMNOTA := CUR_NOTA_REC.NUMNOTA;
        ELSE
          vNUMNOTA := vNUMNOTA;
        END IF;
      END IF;
      
      vCODFILIAL       := NVL(CUR_NOTA_REC.CODFILIAL, vCODFILIAL);
      vQT              := REPLACE(NVL(VQT, 0) + NVL(CUR_NOTA_REC.QT, NVL(VQT, 0)), ',', '.');
      vCODOPER         := NVL(CUR_NOTA_REC.CODOPER, vCODOPER);      
      vCODCLI          := NVL(CUR_NOTA_REC.CODCLI, vCODCLI);
      vCODFILIALORIGEM := NVL(CUR_NOTA_REC.CODFILIALORIGEM, vCODFILIALORIGEM);
      
      IF NVL(CUR_NOTA_REC.PVENDA, 0) = 0 THEN 
        vPVENDA := vPVENDA;
      ELSE
        IF NVL(CUR_NOTA_REC.PVENDA, 0) > 0 THEN
          vPVENDA := CUR_NOTA_REC.PVENDA;
        ELSE
          vPVENDA := vPVENDA;
        END IF;
      END IF;
      
      vQTAVARIA        := REPLACE(NVL(VQTAVARIA, 0) + NVL(CUR_NOTA_REC.QTAVARIA, NVL(VQTAVARIA, 0)), ',', '.');
      vQTBLOQUEADA     := REPLACE(NVL(VQTBLOQUEADA, 0) + NVL(CUR_NOTA_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0)), ',', '.');
      vQTBOX           := REPLACE(NVL(VQTBOX, 0) + NVL(CUR_NOTA_REC.QTBOX, NVL(VQTBOX, 0)), ',', '.');
      vQTCX            := REPLACE(NVL(VQTCX, 0) + NVL(CUR_NOTA_REC.QTCX, NVL(VQTCX, 0)), ',', '.');
      vQTCXORIG        := REPLACE(NVL(VQTCXORIG, 0) + NVL(CUR_NOTA_REC.QTCXORIG, NVL(VQTCXORIG, 0)), ',', '.');
      vQTPALETE        := REPLACE(NVL(VQTPALETE, 0) + NVL(CUR_NOTA_REC.QTCXORIG, NVL(VQTPALETE, 0)), ',', '.');
      vQTPECAS         := REPLACE(NVL(VQTPECAS, 0) + NVL(CUR_NOTA_REC.QTPECAS, NVL(VQTPECAS, 0)), ',', '.');
      vQTPECASORIG     := REPLACE(NVL(VQTPECASORIG, 0) + NVL(CUR_NOTA_REC.QTPECASORIG, NVL(VQTPECASORIG, 0)), ',','.');
      vQTTOTPALCX      := REPLACE(NVL(VQTTOTPALCX, 0) + NVL(CUR_NOTA_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0)), ',', '.') ;
      vQTUN            := REPLACE(NVL(VQTUN, 0) + NVL(CUR_NOTA_REC.QTUN, NVL(VQTUN, 0)), ',', '.');
      vQTUNITCX        := REPLACE(NVL(VQTUNITCX, 0) + NVL(CUR_NOTA_REC.QTUNITCX, NVL(VQTUNITCX, 0)), ',', '.');
      vTOTPESO         := REPLACE(NVL(VTOTPESO, 0) + NVL(CUR_NOTA_REC.TOTPESO, NVL(VTOTPESO, 0)), ',', '.');
      vTOTVOLUME       := REPLACE(NVL(VTOTVOLUME, 0) + NVL(CUR_NOTA_REC.TOTVOLUME, NVL(VTOTVOLUME, 0)), ',', '.');
      vNUMTRANSWMS     := NVL(CUR_NOTA_REC.NUMTRANSWMS, 0);
      vCONTADOR        := vCONTADOR + 1;


    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END; 
  


  DECLARE
    CURSOR CUR_NUMTRANSVENDA IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO      
        FROM PCWMS
     WHERE NVL(NUMTRANSVENDA, 0) > 0
       ORDER BY NUMPED, CODPROD, NUMLOTE, NUMNOTA, CODFILIAL;
  
  BEGIN
    vCONTADOR := 0;
    vNUMPED   := 0;
    vNUMNOTA  := 0;
    FOR CUR_NUMTRANSVENDA_REC IN CUR_NUMTRANSVENDA LOOP
      IF (vNUMTRANSVENDA > 0) THEN
        IF (vNUMTRANSVENDA <> CUR_NUMTRANSVENDA_REC.NUMTRANSVENDA) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMTRANSVENDA = CUR_NUMTRANSVENDA_REC.NUMTRANSVENDA) AND (vCODPROD <> CUR_NUMTRANSVENDA_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := NVL(CUR_NUMTRANSVENDA_REC.NUMPED, vNUMPED);
      vCODPROD         := NVL(CUR_NUMTRANSVENDA_REC.CODPROD, vCODPROD);
      vNUMLOTE         := NVL(CUR_NUMTRANSVENDA_REC.NUMLOTE, vNUMLOTE);
      
      IF NVL(CUR_NUMTRANSVENDA_REC.NUMCAR, 0) = 0 THEN
        vNUMCAR := vNUMCAR;
      ELSE 
        IF NVL(CUR_NUMTRANSVENDA_REC.NUMCAR, 0) > 0 THEN
          vNUMCAR := CUR_NUMTRANSVENDA_REC.NUMCAR;
        ELSE
          vNUMCAR := vNUMCAR;
        END IF;
      END IF;
      
      IF NVL(CUR_NUMTRANSVENDA_REC.NUMNOTA, 0) = 0 THEN 
        vNUMNOTA := vNUMNOTA;
      ELSE
        IF NVL(CUR_NUMTRANSVENDA_REC.NUMNOTA, 0) > 0 THEN
          vNUMNOTA := CUR_NUMTRANSVENDA_REC.NUMNOTA;
        ELSE
          vNUMNOTA := vNUMNOTA;
        END IF;
      END IF;
      
      vCODFILIAL       := NVL(CUR_NUMTRANSVENDA_REC.CODFILIAL, vCODFILIAL);
      vQT              := REPLACE(NVL(VQT, 0) + NVL(CUR_NUMTRANSVENDA_REC.QT, NVL(VQT, 0)), ',', '.');
      vCODOPER         := NVL(CUR_NUMTRANSVENDA_REC.CODOPER, vCODOPER);      
      vCODCLI          := NVL(CUR_NUMTRANSVENDA_REC.CODCLI, vCODCLI);
      vCODFILIALORIGEM := NVL(CUR_NUMTRANSVENDA_REC.CODFILIALORIGEM, vCODFILIALORIGEM);
      
      IF NVL(CUR_NUMTRANSVENDA_REC.PVENDA, 0) = 0 THEN 
        vPVENDA := vPVENDA;
      ELSE
        IF NVL(CUR_NUMTRANSVENDA_REC.PVENDA, 0) > 0 THEN
          vPVENDA := CUR_NUMTRANSVENDA_REC.PVENDA;
        ELSE
          vPVENDA := vPVENDA;
        END IF;
      END IF;
      
      vQTAVARIA        := REPLACE(NVL(VQTAVARIA, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTAVARIA, NVL(VQTAVARIA, 0)), ',', '.');
      vQTBLOQUEADA     := REPLACE(NVL(VQTBLOQUEADA, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0)), ',', '.');
      vQTBOX           := REPLACE(NVL(VQTBOX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTBOX, NVL(VQTBOX, 0)), ',', '.');
      vQTCX            := REPLACE(NVL(VQTCX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTCX, NVL(VQTCX, 0)), ',', '.');
      vQTCXORIG        := REPLACE(NVL(VQTCXORIG, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTCXORIG, NVL(VQTCXORIG, 0)), ',', '.');
      vQTPALETE        := REPLACE(NVL(VQTPALETE, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTCXORIG, NVL(VQTPALETE, 0)), ',', '.');
      vQTPECAS         := REPLACE(NVL(VQTPECAS, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTPECAS, NVL(VQTPECAS, 0)), ',', '.');
      vQTPECASORIG     := REPLACE(NVL(VQTPECASORIG, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTPECASORIG, NVL(VQTPECASORIG, 0)), ',','.');
      vQTTOTPALCX      := REPLACE(NVL(VQTTOTPALCX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0)), ',', '.') ;
      vQTUN            := REPLACE(NVL(VQTUN, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTUN, NVL(VQTUN, 0)), ',', '.');
      vQTUNITCX        := REPLACE(NVL(VQTUNITCX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTUNITCX, NVL(VQTUNITCX, 0)), ',', '.');
      vTOTPESO         := REPLACE(NVL(VTOTPESO, 0) + NVL(CUR_NUMTRANSVENDA_REC.TOTPESO, NVL(VTOTPESO, 0)), ',', '.');
      vTOTVOLUME       := REPLACE(NVL(VTOTVOLUME, 0) + NVL(CUR_NUMTRANSVENDA_REC.TOTVOLUME, NVL(VTOTVOLUME, 0)), ',', '.');
      vNUMTRANSWMS     := NVL(CUR_NUMTRANSVENDA_REC.NUMTRANSWMS, 0);
      vCONTADOR        := vCONTADOR + 1;

    END LOOP;
    LimparVariaveis;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END;
  
  BEGIN
    EXECUTE IMMEDIATE 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMCAR = NULL WHERE NUMCAR = 0';
    COMMIT;
    EXECUTE IMMEDIATE 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMPED = NULL WHERE NUMPED = 0';
    COMMIT;
    EXECUTE IMMEDIATE 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMNOTA = NULL WHERE NUMNOTA = 0';
    COMMIT;
    EXECUTE IMMEDIATE 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMTRANSENT = NULL WHERE NUMTRANSENT = 0';
    COMMIT;
    EXECUTE IMMEDIATE 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMTRANSVENDA = NULL WHERE NUMTRANSVENDA = 0';
    COMMIT;
    DELETE FROM PCWMS WHERE 1 = 1;
    COMMIT;
    EXECUTE IMMEDIATE 'ALTER TABLE PC_BKP_MIGRACAO_PCWMS ADD CONSTRAINT UK_PCWMS UNIQUE (CODPROD, NUMCAR, NUMLOTE, NUMPED, NUMNOTA, CODFILIAL, NUMTRANSENT, NUMTRANSVENDA)';
    COMMIT;
    EXECUTE IMMEDIATE 'INSERT INTO PCWMS AS SELECT * FROM PC_BKP_MIGRACAO_PCWMS WHERE 1 = 1';    
    COMMIT;
    EXECUTE IMMEDIATE 'ALTER TABLE PCWMS ADD CONSTRAINT UK_PCWMS UNIQUE (CODPROD, NUMCAR, NUMLOTE, NUMPED, NUMNOTA, CODFILIAL, NUMTRANSENT, NUMTRANSVENDA)';
    COMMIT;
  END;
  

    EXCEPTION
      WHEN OTHERS THEN
        v_ERORRCODE := SQLCODE;
        v_ERRMSG    := SUBSTR(SQLERRM, 1, 64);

        DBMS_OUTPUT.PUT_LINE('----------------------------------');
        DBMS_OUTPUT.PUT_LINE('Erro: ao inserir dados.');
        DBMS_OUTPUT.PUT_LINE('Erro: ' || v_ERORRCODE || ' ' || v_ERRMSG);
        IF vNUMPED IS NOT NULL THEN
          DBMS_OUTPUT.PUT_LINE('Não é possível inserir o Pedido ' || vNUMPED || ' - NUMTRANSWMS: ' || vNUMTRANSWMS || ' - CODPROD: ' || vCODPROD);
        ELSE
          IF vNUMNOTA IS NOT NULL THEN
             DBMS_OUTPUT.PUT_LINE('Não é possível inserir a Nota ' || vNUMNOTA || ' - NUMTRANSWMS: ' || vNUMTRANSWMS || ' - CODPROD: ' || vCODPROD);
          END IF;            
        END IF;          
        DBMS_OUTPUT.PUT_LINE('----------------------------------');
        ROLLBACK;

END;