DECLARE
  vNUMPED          NUMBER(10,0); --VARIAVEL P/NUMERO DO PEDIDO
  vCODPROD         VARCHAR2(10); --VARIAVEL P/O CÓDIGO DO PRODUTO
  vNUMLOTE         VARCHAR2(50); --VARIAVEL P/NUMERO DO LOTE
  vNUMCAR          NUMBER(8,0);   --VARIAVEL P/NUMERO DO CARREGAMENTO
  vNUMNOTA         NUMBER(10,0); 
  vCODFILIAL       VARCHAR2(2);  --VARIAVEL P/FILIAL
  vCONTADOR        INT;          --VARIAVEL P/O CONTADOR  
  vQT              NUMBER(10, 0);--VARIAVEL P/QT
  vCODOPER         VARCHAR2(10);
  vCODCLI          VARCHAR2(10);
  vCODFILIALORIGEM VARCHAR2(5);
  vPVENDA          VARCHAR2(20);
  vQTAVARIA        VARCHAR2(20);
  vQTBLOQUEADA     VARCHAR2(20);
  vQTBOX           VARCHAR2(20);
  vQTCX            VARCHAR2(20);
  vQTCXORIG        VARCHAR2(20);
  vQTPALETE        VARCHAR2(20);
  vQTPECAS         VARCHAR2(20);
  vQTPECASORIG     VARCHAR2(20);
  vQTTOTPALCX      VARCHAR2(20);
  vQTUN            VARCHAR2(20);
  vQTUNITCX        VARCHAR2(20);
  vTOTPESO         VARCHAR2(20);
  vTOTVOLUME       VARCHAR2(20);
  vNUMTRANSWMS     VARCHAR2(20);
  vNUMTRANSVENDA   NUMBER(10,0); 
  vNUMTRANSENT     NUMBER(10,0);
  v_ERORRCODE      NUMBER;
  vLOG_GRAVADO     VARCHAR2(1);
  v_ERRMSG         VARCHAR2(64); 
  vQry             VARCHAR2(4000);
  vSQL             VARCHAR2(4000);
  vCampos           VARCHAR2(4000);
  
  PROCEDURE LimparVariaveis 
  AS
  BEGIN
    vLOG_GRAVADO := 'N';
    
    IF (NVL(vNUMPED, 0) > 0) AND (vLOG_GRAVADO = 'N') THEN
      vSQL := 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || NVL(vNUMPED, 0) || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || vCODPROD || ', ' ||  '''' || vNUMLOTE || '''' || ', ' || vCODFILIAL || ')';
      EXECUTE IMMEDIATE vSQL;
      DELETE FROM PCWMS WHERE NUMPED = vNUMPED AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;
    
    IF (NVL(vNUMNOTA, 0) > 0) AND (vLOG_GRAVADO = 'N') THEN
      vSQL := 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || NVL(vNUMPED, 0) || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || vCODPROD || ', ' || '''' || vNUMLOTE || '''' || ', ' || vCODFILIAL || ')';
      EXECUTE IMMEDIATE vSQL;
      DELETE FROM PCWMS WHERE NUMNOTA = vNUMNOTA AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;
    
    IF (NVL(vNUMTRANSVENDA, 0) > 0) AND (vLOG_GRAVADO = 'N') THEN
      vSQL := 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || NVL(vNUMPED, 0) || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || vCODPROD || ', ' || '''' || vNUMLOTE || '''' || ', ' || vCODFILIAL || ')';
      EXECUTE IMMEDIATE vSQL;
      DELETE FROM PCWMS WHERE NUMTRANSVENDA = vNUMTRANSVENDA AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;
    
    IF (NVL(vNUMTRANSENT, 0) > 0) AND (vLOG_GRAVADO = 'N') THEN
      vSQL := 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, NUMTRANSENT, CODPROD, NUMLOTE, CODFILIAL)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || NVL(vNUMPED, 0) || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || NVL(vNUMTRANSENT, 0) || ',' || vCODPROD || ', ' || '''' || vNUMLOTE || '''' || ', ' || vCODFILIAL || ')';
      EXECUTE IMMEDIATE vSQL;
      DELETE FROM PCWMS WHERE NUMTRANSENT = vNUMTRANSENT AND CODFILIAL = vCODFILIAL;
      COMMIT;
      vLOG_GRAVADO := 'S';
    END IF;    
    
    vQT              := 0; 
    vQTAVARIA        := 0;
    vQTBLOQUEADA     := 0;
    vQTBOX           := 0;
    vQTCX            := 0;
    vQTCXORIG        := 0;
    vQTPALETE        := 0;
    vQTPECAS         := 0;
    vQTPECASORIG     := 0;
    vQTTOTPALCX      := 0;
    vQTUN            := 0;
    vQTUNITCX        := 0;
    vTOTPESO         := 0;
    vTOTVOLUME       := 0;      
    vNUMNOTA         := 0;
    vNUMCAR          := 0;
    vNUMTRANSENT     := 0;
    vLOG_GRAVADO     := 'N';
    vQry             := '';
  END LimparVariaveis;
  
  PROCEDURE BKP_PCWMS_MIGRACAO
  AS
  BEGIN
    DECLARE
      V_TABELA_EXISTE NUMBER DEFAULT 0;        
    BEGIN

      SELECT COUNT(*)
        INTO V_TABELA_EXISTE
        FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME = 'PC_BKP_MIGRACAO_PCWMS_ORIGINAL';
         
       IF V_TABELA_EXISTE = 0 THEN
         RAISE_APPLICATION_ERROR(-20001, 'Tabela PC_BKP_MIGRACAO_PCWMS_ORIGINAL não criada.');
       ELSE                  --FAZENDO BKP DA TABELA INTEIRA
         vCampos := 'CODPROD, NUMBONUS, QT, CODOPER, NUMCAR, NUMLOTE, CODCLI, CODVEICULO, MAPAGERADO, ABASTECIDO, DATAWMS, DTCANCEL, CODROTINA, DESTINO, NUMPED, ' || CHR(13) ||
                    'CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, NUMSEQENTREGA, NUMNOTA, CODFILIAL, DTENT, CODFORNEC, NUMTRANSENT, VLTOTAL, ' || CHR(13) ||
                    'TIPOEMBALAGEMPEDIDO, PVENDA, DTENTREGA, CODPRACA, CODFUNCCONF, CODFUNCEMBALADOR, HORAINICIALSEP, MINUTOINICIALSEP, HORAFINALSEP, ' || CHR(13) ||
                    'MINUTOFINALSEP, PVENDABASE, QTSEPARADA, NUMTRANSVENDA, SEPARACAOCONCLUIDA, TIPOMAPA, QTUNITCX, QTTOTPALCX, QTBOX, QTCX, QTPALETE, QTUN, ' || CHR(13) ||
                    'FRACIONADO, NUMSEQ, DTGERACAO, CODFUNCGERA, BLOCADO, NUMSEQMONTAGEM, QTAVARIA, QTBLOQUEADA, CODFILIALORIGEM, NUMOP, QTPECAS, LISTARPEDIDO, ' || CHR(13) ||
                    'QTPECASORIG, QTCXORIG, DTINICIOPROMOLOTE, DTFIMPROMOLOTE, NUMTRANSABASTECIMENTO, QTANTECIPADA, CODPRODACAB, DTINTEGRACAO';
         vSQL    := 'INSERT INTO PC_BKP_MIGRACAO_PCWMS_ORIGINAL (' || vCampos || ') ' || 'SELECT ' || vCampos || ' FROM PCWMS WHERE 1 = 1';
         EXECUTE IMMEDIATE vSQL;
         COMMIT;
       END IF;
         
      SELECT COUNT(*)
        INTO V_TABELA_EXISTE
        FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME = 'PC_BKP_MIGRACAO_PCWMS';
         
       IF V_TABELA_EXISTE = 0 THEN
         RAISE_APPLICATION_ERROR(-20001, 'Tabela PC_BKP_MIGRACAO_PCWMS não criada.');
       END IF;
         
      SELECT COUNT(*)
        INTO V_TABELA_EXISTE
        FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME = 'PC_LOG_MIGRACAO_PCWMS';
         
       IF V_TABELA_EXISTE = 0 THEN
         RAISE_APPLICATION_ERROR(-20001, 'Tabela PC_LOG_MIGRACAO_PCWMS não criada.');
       END IF;           
      
    END;  
  END BKP_PCWMS_MIGRACAO;
  
  FUNCTION ADICIONA_DADOS_TRATADOS RETURN BOOLEAN
  IS
  BEGIN    
    BEGIN
      vQT              := TO_CHAR(REPLACE(vQT, ',', '.'));
      vPVENDA          := TO_CHAR(REPLACE(vPVENDA, ',', '.'));
      vQTAVARIA        := TO_CHAR(REPLACE(vQTAVARIA, ',', '.'));
      vQTBLOQUEADA     := TO_CHAR(REPLACE(vQTBLOQUEADA, ',', '.'));
      vQTBOX           := TO_CHAR(REPLACE(vQTBOX, ',', '.'));
      vQTCX            := TO_CHAR(REPLACE(vQTCX, ',', '.'));
      vQTCXORIG        := TO_CHAR(REPLACE(vQTCXORIG, ',', '.'));
      vQTPALETE        := TO_CHAR(REPLACE(vQTPALETE, ',', '.'));
      vQTPECAS         := TO_CHAR(REPLACE(vQTPECAS, ',', '.'));
      vQTPECASORIG     := TO_CHAR(REPLACE(vQTPECASORIG, ',', '.'));
      vQTTOTPALCX      := TO_CHAR(REPLACE(vQTTOTPALCX, ',', '.'));
      vQTUN            := TO_CHAR(REPLACE(vQTUN, ',', '.'));
      vQTUNITCX        := TO_CHAR(REPLACE(vQTUNITCX, ',', '.'));
      vTOTPESO         := TO_CHAR(REPLACE(vTOTPESO, ',', '.'));
      vTOTVOLUME       := TO_CHAR(REPLACE(vTOTVOLUME, ',', '.'));    

      
      vSQL := 'INSERT INTO PC_BKP_MIGRACAO_PCWMS (NUMPED, CODPROD, NUMLOTE, NUMCAR, NUMNOTA, CODFILIAL, QT, CODOPER, CODCLI, CODFILIALORIGEM, PVENDA, QTAVARIA, NUMTRANSWMS,
                       QTBLOQUEADA, QTBOX, QTCX, QTCXORIG, QTPALETE, QTPECAS, QTPECASORIG, QTTOTPALCX, QTUN, QTUNITCX, TOTPESO, TOTVOLUME, NUMTRANSVENDA, NUMTRANSENT)
               VALUES (' || NVL(vNUMPED, 0) || ',' || vCODPROD || ',' || '''' || vNUMLOTE || '''' || ',' || NVL(vNUMCAR, 0) || ',' ||  NVL(VNUMNOTA, 0) || ',' ||  vCODFILIAL || ',' ||  vQT || ',' ||  '''' || vCODOPER || '''' || ',' ||  vCODCLI || ',' ||  vCODFILIALORIGEM || ',' ||  vPVENDA || ',' ||  vQTAVARIA || ',' ||  vNUMTRANSWMS || ',' || 
                       vQTBLOQUEADA || ',' ||  vQTBOX || ',' ||  vQTCX || ',' ||  vQTCXORIG || ',' ||  vQTPALETE || ',' ||  vQTPECAS || ',' ||  vQTPECASORIG || ',' ||  vQTTOTPALCX || ',' ||  vQTUN || ',' ||  vQTUNITCX || ',' ||  vTOTPESO || ',' ||  vTOTVOLUME || ',' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || NVL(vNUMTRANSENT, 0) || ')';
                       
    EXECUTE IMMEDIATE vSQL;
    COMMIT;                       
   END;
    
    RETURN TRUE;   
    
  END ADICIONA_DADOS_TRATADOS;

BEGIN  
  
  BKP_PCWMS_MIGRACAO;

  DECLARE
    CURSOR CUR_PEDIDO IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO
        FROM PCWMS
       WHERE (NUMPED, CODPROD, CODFILIAL) IN 
             (SELECT NUMPED, CODPROD, CODFILIAL
                FROM PCWMS
               WHERE NVL(NUMPED, 0) > 0
               GROUP BY NUMPED, CODPROD, NUMLOTE, DTENT, NUMTRANSENT, CODFILIAL)
       ORDER BY NUMPED, CODPROD, CODFILIAL, NUMCAR DESC;
  
  BEGIN  
  
    vCONTADOR := 0;
    vNUMPED   := 0;
    FOR CUR_PEDIDO_REC IN CUR_PEDIDO LOOP
      IF vNUMPED > 0 THEN
        IF (vNUMPED <> CUR_PEDIDO_REC.NUMPED) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMPED = CUR_PEDIDO_REC.NUMPED) AND (vCODPROD <> CUR_PEDIDO_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := CUR_PEDIDO_REC.NUMPED;
      vCODPROD         := NVL(TO_CHAR(CUR_PEDIDO_REC.CODPROD), 'NULL');
      vNUMLOTE         := NVL(TO_CHAR(CUR_PEDIDO_REC.NUMLOTE), 'NULL');
      vNUMCAR          := CUR_PEDIDO_REC.NUMCAR;
      vNUMNOTA         := CUR_PEDIDO_REC.NUMNOTA;      
      vCODFILIAL       := NVL(TO_CHAR(CUR_PEDIDO_REC.CODFILIAL), 'NULL');
      vQT              := NVL(VQT, 0) + NVL(CUR_PEDIDO_REC.QT, NVL(VQT, 0));
      vCODOPER         := NVL(TO_CHAR(CUR_PEDIDO_REC.CODOPER), 'NULL');      
      vCODCLI          := NVL(TO_CHAR(CUR_PEDIDO_REC.CODCLI), 'NULL');
      vCODFILIALORIGEM := NVL(TO_CHAR(CUR_PEDIDO_REC.CODFILIALORIGEM), 'NULL');
      vPVENDA          := NVL(TO_CHAR(CUR_PEDIDO_REC.PVENDA), '0');
      vQTAVARIA        := NVL(VQTAVARIA, 0) + NVL(CUR_PEDIDO_REC.QTAVARIA, NVL(VQTAVARIA, 0));
      vQTBLOQUEADA     := NVL(VQTBLOQUEADA, 0) + NVL(CUR_PEDIDO_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0));
      vQTBOX           := NVL(VQTBOX, 0) + NVL(CUR_PEDIDO_REC.QTBOX, NVL(VQTBOX, 0));
      vQTCX            := NVL(VQTCX, 0) + NVL(CUR_PEDIDO_REC.QTCX, NVL(VQTCX, 0));
      vQTCXORIG        := NVL(VQTCXORIG, 0) + NVL(CUR_PEDIDO_REC.QTCXORIG, NVL(VQTCXORIG, 0));
      vQTPALETE        := NVL(VQTPALETE, 0) + NVL(CUR_PEDIDO_REC.QTCXORIG, NVL(VQTPALETE, 0));
      vQTPECAS         := NVL(VQTPECAS, 0) + NVL(CUR_PEDIDO_REC.QTPECAS, NVL(VQTPECAS, 0));
      vQTPECASORIG     := NVL(VQTPECASORIG, 0) + NVL(CUR_PEDIDO_REC.QTPECASORIG, 0);
      vQTTOTPALCX      := NVL(VQTTOTPALCX, 0) + NVL(CUR_PEDIDO_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0));
      vQTUN            := NVL(VQTUN, 0) + NVL(CUR_PEDIDO_REC.QTUN, NVL(VQTUN, 0));
      vQTUNITCX        := NVL(VQTUNITCX, 0) + NVL(CUR_PEDIDO_REC.QTUNITCX, NVL(VQTUNITCX, 0));
      vTOTPESO         := NVL(VTOTPESO, 0) + NVL(CUR_PEDIDO_REC.TOTPESO, 0);
      vTOTVOLUME       := NVL(VTOTVOLUME, 0) + NVL(CUR_PEDIDO_REC.TOTVOLUME, 0);
      vNUMTRANSWMS     := NVL(TO_CHAR(CUR_PEDIDO_REC.NUMTRANSWMS), 'NULL');
      vNUMTRANSVENDA   := CUR_PEDIDO_REC.NUMTRANSVENDA;      
      vCONTADOR        := vCONTADOR + 1;


    END LOOP;
    LimparVariaveis;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END;
       
  DECLARE
    CURSOR CUR_NOTA IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO
        FROM PCWMS
       WHERE (NUMNOTA, CODPROD, CODFILIAL) IN 
             (SELECT NUMNOTA, CODPROD, CODFILIAL
                FROM PCWMS
               WHERE NVL(NUMNOTA, 0) > 0
               GROUP BY NUMNOTA, CODPROD, NUMLOTE, DTENT, NUMTRANSENT, CODFILIAL)
       ORDER BY NUMNOTA, CODPROD, CODFILIAL, NUMCAR DESC;     
  
  BEGIN
    vNUMPED   := 0;
    vNUMNOTA  := 0;
    FOR CUR_NOTA_REC IN CUR_NOTA LOOP
      IF vNUMNOTA > 0 THEN
        IF (vNUMNOTA <> CUR_NOTA_REC.NUMNOTA) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMNOTA = CUR_NOTA_REC.NUMNOTA) AND (vCODPROD <> CUR_NOTA_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := CUR_NOTA_REC.NUMPED;
      vCODPROD         := NVL(TO_CHAR(CUR_NOTA_REC.CODPROD), 'NULL');
      vNUMLOTE         := NVL(TO_CHAR(CUR_NOTA_REC.NUMLOTE), 'NULL');
      vNUMCAR          := CUR_NOTA_REC.NUMCAR;
      vNUMNOTA         := CUR_NOTA_REC.NUMNOTA;      
      vCODFILIAL       := NVL(TO_CHAR(CUR_NOTA_REC.CODFILIAL), 'NULL');
      vQT              := NVL(VQT, 0) + NVL(CUR_NOTA_REC.QT, NVL(VQT, 0));
      vCODOPER         := NVL(TO_CHAR(CUR_NOTA_REC.CODOPER), 'NULL');      
      vCODCLI          := NVL(TO_CHAR(CUR_NOTA_REC.CODCLI), 'NULL');
      vCODFILIALORIGEM := NVL(TO_CHAR(CUR_NOTA_REC.CODFILIALORIGEM), 'NULL');
      vPVENDA          := NVL(TO_CHAR(CUR_NOTA_REC.PVENDA), '0');
      vQTAVARIA        := NVL(VQTAVARIA, 0) + NVL(CUR_NOTA_REC.QTAVARIA, NVL(VQTAVARIA, 0));
      vQTBLOQUEADA     := NVL(VQTBLOQUEADA, 0) + NVL(CUR_NOTA_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0));
      vQTBOX           := NVL(VQTBOX, 0) + NVL(CUR_NOTA_REC.QTBOX, NVL(VQTBOX, 0));
      vQTCX            := NVL(VQTCX, 0) + NVL(CUR_NOTA_REC.QTCX, NVL(VQTCX, 0));
      vQTCXORIG        := NVL(VQTCXORIG, 0) + NVL(CUR_NOTA_REC.QTCXORIG, NVL(VQTCXORIG, 0));
      vQTPALETE        := NVL(VQTPALETE, 0) + NVL(CUR_NOTA_REC.QTCXORIG, NVL(VQTPALETE, 0));
      vQTPECAS         := NVL(VQTPECAS, 0) + NVL(CUR_NOTA_REC.QTPECAS, NVL(VQTPECAS, 0));
      vQTPECASORIG     := NVL(VQTPECASORIG, 0) + NVL(CUR_NOTA_REC.QTPECASORIG, NVL(VQTPECASORIG, 0));
      vQTTOTPALCX      := NVL(VQTTOTPALCX, 0) + NVL(CUR_NOTA_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0));
      vQTUN            := NVL(VQTUN, 0) + NVL(CUR_NOTA_REC.QTUN, NVL(VQTUN, 0));
      vQTUNITCX        := NVL(VQTUNITCX, 0) + NVL(CUR_NOTA_REC.QTUNITCX, NVL(VQTUNITCX, 0));
      vTOTPESO         := NVL(VTOTPESO, 0) + NVL(CUR_NOTA_REC.TOTPESO, 0);
      vTOTVOLUME       := NVL(VTOTVOLUME, 0) + NVL(CUR_NOTA_REC.TOTVOLUME, 0);
      vNUMTRANSWMS     := NVL(TO_CHAR(CUR_NOTA_REC.NUMTRANSWMS), 'NULL');
      vNUMTRANSVENDA   := CUR_NOTA_REC.NUMTRANSVENDA;      
      vCONTADOR        := vCONTADOR + 1;


    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END; 
  


  DECLARE
    CURSOR CUR_NUMTRANSVENDA IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO      
        FROM PCWMS
     WHERE NVL(NUMTRANSVENDA, 0) > 0
       ORDER BY NUMTRANSVENDA, CODPROD, NUMLOTE, NUMNOTA, CODFILIAL;
  
  BEGIN
    vNUMPED   := 0;
    vNUMNOTA  := 0;
    FOR CUR_NUMTRANSVENDA_REC IN CUR_NUMTRANSVENDA LOOP
      IF (vNUMTRANSVENDA > 0) THEN
        IF (vNUMTRANSVENDA <> CUR_NUMTRANSVENDA_REC.NUMTRANSVENDA) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMTRANSVENDA = CUR_NUMTRANSVENDA_REC.NUMTRANSVENDA) AND (vCODPROD <> CUR_NUMTRANSVENDA_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := CUR_NUMTRANSVENDA_REC.NUMPED;
      vCODPROD         := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.CODPROD), 'NULL');
      vNUMLOTE         := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.NUMLOTE), 'NULL');
      vNUMCAR          := CUR_NUMTRANSVENDA_REC.NUMCAR;
      vNUMNOTA         := CUR_NUMTRANSVENDA_REC.NUMNOTA;      
      vCODFILIAL       := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.CODFILIAL), 'NULL');
      vQT              := NVL(VQT, 0) + NVL(CUR_NUMTRANSVENDA_REC.QT, NVL(VQT, 0));
      vCODOPER         := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.CODOPER), 'NULL');      
      vCODCLI          := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.CODCLI), 'NULL');
      vCODFILIALORIGEM := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.CODFILIALORIGEM), 'NULL');
      vPVENDA          := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.PVENDA), '0');
      vQTAVARIA        := NVL(VQTAVARIA, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTAVARIA, NVL(VQTAVARIA, 0));
      vQTBLOQUEADA     := NVL(VQTBLOQUEADA, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0));
      vQTBOX           := NVL(VQTBOX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTBOX, NVL(VQTBOX, 0));
      vQTCX            := NVL(VQTCX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTCX, NVL(VQTCX, 0));
      vQTCXORIG        := NVL(VQTCXORIG, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTCXORIG, NVL(VQTCXORIG, 0));
      vQTPALETE        := NVL(VQTPALETE, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTCXORIG, NVL(VQTPALETE, 0));
      vQTPECAS         := NVL(VQTPECAS, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTPECAS, NVL(VQTPECAS, 0));
      vQTPECASORIG     := NVL(VQTPECASORIG, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTPECASORIG, 0);
      vQTTOTPALCX      := NVL(VQTTOTPALCX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0));
      vQTUN            := NVL(VQTUN, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTUN, NVL(VQTUN, 0));
      vQTUNITCX        := NVL(VQTUNITCX, 0) + NVL(CUR_NUMTRANSVENDA_REC.QTUNITCX, NVL(VQTUNITCX, 0));
      vTOTPESO         := NVL(VTOTPESO, 0) + NVL(CUR_NUMTRANSVENDA_REC.TOTPESO, 0);
      vTOTVOLUME       := NVL(VTOTVOLUME, 0) + NVL(CUR_NUMTRANSVENDA_REC.TOTVOLUME, 0);
      vNUMTRANSWMS     := NVL(TO_CHAR(CUR_NUMTRANSVENDA_REC.NUMTRANSWMS), 'NULL');
      vNUMTRANSVENDA   := CUR_NUMTRANSVENDA_REC.NUMTRANSVENDA;      
      vCONTADOR        := vCONTADOR + 1;

    END LOOP;
    LimparVariaveis;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END;
  

  DECLARE
    CURSOR CUR_NUMTRANSENT IS
      SELECT CODPROD, QT, CODOPER, NUMCAR, NUMLOTE, NUMNOTA, CODFILIAL, CODCLI, CODVEICULO, MAPAGERADO, DATAWMS, CODROTINA, DESTINO,
             NUMPED, CODDISTRIB, NUMVIASMAPA, NUMTRANSWMS, TOTPESO, TOTVOLUME, PVENDA, DTENTREGA, NUMTRANSVENDA, SEPARACAOCONCLUIDA, NUMTRANSENT,
             QTUNITCX, QTTOTPALCX, QTPALETE, QTCX, QTUN, NUMSEQ, QTBOX, DTGERACAO, CODFUNCGERA, QTAVARIA, NUMSEQMONTAGEM, QTBLOQUEADA,
             CODFILIALORIGEM, NUMOP, QTPECAS, QTPECASORIG, QTCXORIG, LISTARPEDIDO      
        FROM PCWMS
     WHERE NVL(NUMTRANSENT, 0) > 0
       ORDER BY NUMTRANSENT, CODPROD, NUMLOTE, NUMNOTA, CODFILIAL;
  
  BEGIN
    vNUMPED       := 0;
    vNUMTRANSENT  := 0;
    FOR CUR_NUMTRANSENT_REC IN CUR_NUMTRANSENT LOOP
      IF (vNUMTRANSENT > 0) THEN
        IF (vNUMTRANSENT <> CUR_NUMTRANSENT_REC.NUMTRANSENT) THEN
          IF ADICIONA_DADOS_TRATADOS THEN
            LimparVariaveis;          
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
          END IF;
        ELSE 
          IF (vNUMTRANSENT = CUR_NUMTRANSENT_REC.NUMTRANSENT) AND (vCODPROD <> CUR_NUMTRANSENT_REC.CODPROD) THEN
            IF ADICIONA_DADOS_TRATADOS THEN
              LimparVariaveis;          
            ELSE
              RAISE_APPLICATION_ERROR(-20001, 'Erro ao inserir dados.'); 
            END IF;
          END IF;
        END IF;
      END IF;
    
      vNUMPED          := CUR_NUMTRANSENT_REC.NUMPED;
      vCODPROD         := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.CODPROD), 'NULL');
      vNUMLOTE         := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.NUMLOTE), 'NULL');
      vNUMCAR          := CUR_NUMTRANSENT_REC.NUMCAR;
      vNUMNOTA         := CUR_NUMTRANSENT_REC.NUMNOTA;      
      vCODFILIAL       := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.CODFILIAL), 'NULL');
      vQT              := NVL(VQT, 0) + NVL(CUR_NUMTRANSENT_REC.QT, NVL(VQT, 0));
      vCODOPER         := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.CODOPER), 'NULL');      
      vCODCLI          := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.CODCLI), 'NULL');
      vCODFILIALORIGEM := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.CODFILIALORIGEM), 'NULL');
      vPVENDA          := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.PVENDA), '0');
      vQTAVARIA        := NVL(VQTAVARIA, 0) + NVL(CUR_NUMTRANSENT_REC.QTAVARIA, NVL(VQTAVARIA, 0));
      vQTBLOQUEADA     := NVL(VQTBLOQUEADA, 0) + NVL(CUR_NUMTRANSENT_REC.QTBLOQUEADA, NVL(VQTBLOQUEADA, 0));
      vQTBOX           := NVL(VQTBOX, 0) + NVL(CUR_NUMTRANSENT_REC.QTBOX, NVL(VQTBOX, 0));
      vQTCX            := NVL(VQTCX, 0) + NVL(CUR_NUMTRANSENT_REC.QTCX, NVL(VQTCX, 0));
      vQTCXORIG        := NVL(VQTCXORIG, 0) + NVL(CUR_NUMTRANSENT_REC.QTCXORIG, NVL(VQTCXORIG, 0));
      vQTPALETE        := NVL(VQTPALETE, 0) + NVL(CUR_NUMTRANSENT_REC.QTCXORIG, NVL(VQTPALETE, 0));
      vQTPECAS         := NVL(VQTPECAS, 0) + NVL(CUR_NUMTRANSENT_REC.QTPECAS, NVL(VQTPECAS, 0));
      vQTPECASORIG     := NVL(VQTPECASORIG, 0) + NVL(CUR_NUMTRANSENT_REC.QTPECASORIG, 0);
      vQTTOTPALCX      := NVL(VQTTOTPALCX, 0) + NVL(CUR_NUMTRANSENT_REC.QTTOTPALCX, NVL(VQTTOTPALCX, 0));
      vQTUN            := NVL(VQTUN, 0) + NVL(CUR_NUMTRANSENT_REC.QTUN, NVL(VQTUN, 0));
      vQTUNITCX        := NVL(VQTUNITCX, 0) + NVL(CUR_NUMTRANSENT_REC.QTUNITCX, NVL(VQTUNITCX, 0));
      vTOTPESO         := NVL(VTOTPESO, 0) + NVL(CUR_NUMTRANSENT_REC.TOTPESO, 0);
      vTOTVOLUME       := NVL(VTOTVOLUME, 0) + NVL(CUR_NUMTRANSENT_REC.TOTVOLUME, 0);
      vNUMTRANSWMS     := NVL(TO_CHAR(CUR_NUMTRANSENT_REC.NUMTRANSWMS), 'NULL');
      vNUMTRANSVENDA   := CUR_NUMTRANSENT_REC.NUMTRANSVENDA;      
      vNUMTRANSENT     := CUR_NUMTRANSENT_REC.NUMTRANSENT;
      vCONTADOR        := vCONTADOR + 1;

    END LOOP;
    LimparVariaveis;
    DBMS_OUTPUT.PUT_LINE('Finalizado com ' || TO_CHAR(vCONTADOR) || ' linhas.');
  END;
  
  
  
  
  BEGIN
    vSQL := 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMCAR = NULL WHERE NUMCAR = 0';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    vSQL := 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMPED = NULL WHERE NUMPED = 0';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    vSQL := 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMNOTA = NULL WHERE NUMNOTA = 0';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    vSQL := 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMTRANSENT = NULL WHERE NUMTRANSENT = 0';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    vSQL := 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMTRANSVENDA = NULL WHERE NUMTRANSVENDA = 0';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    vSQL := 'UPDATE PC_BKP_MIGRACAO_PCWMS SET NUMLOTE = NULL WHERE NUMLOTE = ''0''';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    DELETE FROM PCWMS WHERE 1 = 1;
    COMMIT;
    vSQL := 'ALTER TABLE PC_BKP_MIGRACAO_PCWMS ADD CONSTRAINT UK_PCWMS_CHAVE UNIQUE (CODPROD, NUMCAR, NUMLOTE, NUMPED, NUMNOTA, CODFILIAL, NUMTRANSENT, NUMTRANSVENDA, CODOPER)';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
    vSQL := 'INSERT INTO PCWMS (' || vCampos || ') ' || 'SELECT ' || vCampos || ' FROM PC_BKP_MIGRACAO_PCWMS WHERE 1 = 1';	
    EXECUTE IMMEDIATE vSQL;    
    COMMIT;
    vSQL := 'ALTER TABLE PCWMS ADD CONSTRAINT UK_CHAVE_PCWMS UNIQUE (CODPROD, NUMCAR, NUMLOTE, NUMPED, NUMNOTA, CODFILIAL, NUMTRANSENT, NUMTRANSVENDA, CODOPER)';
    EXECUTE IMMEDIATE vSQL;
    COMMIT;
  END;
  

    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        v_ERORRCODE := SQLCODE;
        v_ERRMSG    := SUBSTR(SQLERRM, 1, 64);

        DBMS_OUTPUT.PUT_LINE('----------------------------------');
        DBMS_OUTPUT.PUT_LINE('Erro: ao inserir dados.');
        DBMS_OUTPUT.PUT_LINE('Erro: ' || v_ERORRCODE || ' ' || v_ERRMSG);
        IF vNUMPED IS NOT NULL THEN
          DBMS_OUTPUT.PUT_LINE('Não é possível inserir o Pedido ' || vNUMPED || ' - NUMTRANSWMS: ' || vNUMTRANSWMS || ' - CODPROD: ' || vCODPROD);
        ELSE
          IF vNUMNOTA IS NOT NULL THEN
             DBMS_OUTPUT.PUT_LINE('Não é possível inserir a Nota ' || vNUMNOTA || ' - NUMTRANSWMS: ' || vNUMTRANSWMS || ' - CODPROD: ' || vCODPROD);
          END IF;            
        END IF;          
        DBMS_OUTPUT.PUT_LINE('----------------------------------');
        v_ERRMSG := REPLACE(REPLACE(v_ERRMSG, '/', '_'), ':', '_');
        vSQL     := REPLACE(vSQL, '''', ''''''); 
        vQry     := 'INSERT INTO PC_LOG_MIGRACAO_PCWMS (ID, NUMPED, NUMNOTA, NUMTRANSVENDA, NUMTRANSENT, CODPROD, NUMLOTE, CODFILIAL, ERR_NUMBER, ERR_MSG, QRY_EM_EXECUCAO, DATA_DO_LOG, HORA_DO_LOG)' || CHR(13) ||
                        '            VALUES (' || vCONTADOR || ', ' || NVL(vNUMPED, 0) || ', ' ||  NVL(VNUMNOTA, 0) || ', ' ||  NVL(VNUMTRANSVENDA, 0) || ', ' || NVL(vNUMTRANSENT, 0) || ', ' || NVL(vCODPROD, 0) || ', ' ||  '''' || vNUMLOTE || '''' || ', ' || NVL(vCODFILIAL, 0) || ', ' || '''' || v_ERORRCODE || '''' || ', ' ||  '''' || v_ERRMSG || '''' || ',' || '''' || vSQL || '''' || ',' || '''' || TO_CHAR(SYSDATE, 'DD-MM-YYYY') || '''' || ', ' || '''' || TO_CHAR(SYSDATE, 'HH24: MI: SS') || '''' || ')';
        EXECUTE IMMEDIATE vQry;
        vQry        := '';
        COMMIT;        

END;